language: c
os:
    - osx
    - linux

compiler:
    - clang
    - gcc
    - x86_64-w64-mingw32-gcc

cache:
  directories:
  - depends/built
  - depends/sdk-sources

addons:
  apt:
    packages:
        - valgrind
        - binutils-mingw-w64
        - gcc-mingw-w64
        - wine
        - libevent-dev

before_install:
  - pip install --user cpp-coveralls
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then brew install valgrind gnu-sed libevent --default-names; fi

matrix:
    fast_finish:
        - true
    exclude:
      - os: osx
        compiler: x86_64-w64-mingw32-gcc

before_script:
    - ./autogen.sh
    - if [ "$CC" == i686-w64-mingw32-gcc ]; then
          export CROSS_COMPILE=${CC%%gcc}; unset CC;
          ./configure --disable-net mingw $CONFIG_OPTS -Wno-pedantic-ms-format;
      elif [ "$CC" == x86_64-w64-mingw32-gcc ]; then
          make -C depends HOST=x86_64-w64-mingw32;
          export CROSS_COMPILE=${CC%%gcc}; unset CC;
          LIBTOOL_APP_LDFLAGS='-all-static' LDFLAGS='-static' ./configure --prefix=$TRAVIS_BUILD_DIR/depends/x86_64-w64-mingw32 --disable-shared --enable-static;
      else
          ./configure --enable-debug CFLAGS='-fprofile-arcs -ftest-coverage';
      fi

script: 
    - make -j2 V=1
    - if ( [ "${TRAVIS_OS_NAME}" == "linux" ] ) && ( [ "$CC" == "gcc" ] ); then
          valgrind --track-origins=yes --leak-check=full --error-exitcode=1 ./tests;
          ./tests;
      else
          if [ "$CROSS_COMPILE" ]; then
             wine tests.exe;
          else
             make check;
             if [ ! -f test-suite.log; ]; then
                 cat test-suite.log;
             fi
          fi
      fi
    - if [ ${CC} = gcc ]; then ./tooltests.py ; fi;

after_success:
  - if [ ${CC} = gcc ] && [ "${TRAVIS_OS_NAME}" = "linux" ]; then coveralls --verbose -i src -x c -e src/logdb -e src/secp256k1 -r $TRAVIS_BUILD_DIR -b $TRAVIS_BUILD_DIR --gcov-options '\-lp'; fi;