language: c
os:
    - osx
    - linux

compiler:
    - clang
    - gcc

before_install:
  - pip install --user cpp-coveralls
  
matrix:
    fast_finish:
        - true

script: 
    - ./autogen.sh
    - ./configure CFLAGS='-fprofile-arcs -ftest-coverage'
    - make clean && make check
    
after_success:
  - coveralls --verbose -i src -x c -e src/secp256k1 -r $TRAVIS_BUILD_DIR -b $TRAVIS_BUILD_DIR --gcov-options '\-lp'