#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
gen_buff_mu_vectors.py - byte-exact fixtures for raccoong_pk_hash
and raccoong_buff_mu against upstream `ThRc_Api._buff_mu`
(Raccoon-G-44, kappa=128).

Records, for several deterministic (pk, msg) inputs:
  - the pk bytes (length up to RACCOONG_PK_BYTES = 16144 B)
  - the msg bytes (variable)
  - tr  = SHAKE256(pk).read(32)
  - mu  = SHAKE256(tr || msg).read(32)

Pin: lattice-hd-wallets@461a5ed9b6d57e3bf8c381be3bb79325ab21d906.
"""

import argparse
import hashlib
import sys

UPSTREAM_COMMIT = "461a5ed9b6d57e3bf8c381be3bb79325ab21d906"
CRH = 32


def emit_u8(name: str, data: bytes, width: int = 16) -> str:
    if len(data) == 0:
        return f"static const uint8_t {name}[1] = {{ 0 }}; /* unused, len=0 */"
    lines = [f"static const uint8_t {name}[{len(data)}] = {{"]
    for i in range(0, len(data), width):
        chunk = ", ".join(f"0x{b:02x}" for b in data[i:i + width])
        lines.append(f"    {chunk},")
    lines.append("};")
    return "\n".join(lines)


def gen_blob(seed: bytes, n: int) -> bytes:
    out = bytearray()
    counter = 0
    while len(out) < n:
        out.extend(hashlib.sha256(seed + counter.to_bytes(4, "big")).digest())
        counter += 1
    return bytes(out[:n])


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--upstream", required=True,
                   help="path to lattice-hd-wallets/src/raccoon/thrc-py")
    p.add_argument("--out", required=True, help="header file to write")
    args = p.parse_args()

    sys.path.insert(0, args.upstream)
    from thrc_api import TRaccoon   # type: ignore  # noqa: E402

    api = TRaccoon(kappa=128)

    # Cases sized to exercise rate boundaries and the full pk path.
    # PK_BYTES (Raccoon-G-44) is 16144 — the largest size in this fixture
    # is 16144 to mirror a real serialized vk.
    cases = [
        (b"", b""),
        (gen_blob(b"buff_mu/case1/pk", 16), b""),
        (gen_blob(b"buff_mu/case2/pk", 1024),
            b"hello dogecoin"),
        (gen_blob(b"buff_mu/case3/pk", 16144),
            hashlib.sha3_512(b"buff_mu/case3/msg").digest()),
        (gen_blob(b"buff_mu/case4/pk", 16144),
            gen_blob(b"buff_mu/case4/msg", 512)),
    ]

    out_lines = []
    out_lines.append("/* SPDX-License-Identifier: MIT */")
    out_lines.append("/* Auto-generated by contrib/raccoon_g/"
                     "gen_buff_mu_vectors.py - DO NOT EDIT. */")
    out_lines.append(f"/* Pin: lattice-hd-wallets@{UPSTREAM_COMMIT} */")
    out_lines.append("#ifndef RACCOONG_BUFF_MU_VECTORS_H")
    out_lines.append("#define RACCOONG_BUFF_MU_VECTORS_H")
    out_lines.append("#include <stddef.h>")
    out_lines.append("#include <stdint.h>")
    out_lines.append("")
    out_lines.append(f"#define RACCOONG_BUFF_MU_FIXTURE_COUNT {len(cases)}")
    out_lines.append(f"#define RACCOONG_BUFF_MU_FIXTURE_CRH    {CRH}")
    out_lines.append("")

    for idx, (pk, msg) in enumerate(cases):
        # tr = SHAKE256(pk).read(crh); mu = SHAKE256(tr || msg).read(crh).
        from Crypto.Hash import SHAKE256  # type: ignore
        tr = SHAKE256.new(pk).read(CRH)
        mu = api._buff_mu(tr, msg)
        assert len(tr) == CRH and len(mu) == CRH

        out_lines.append(emit_u8(f"kRaccoongBuffMuFixturePk{idx}", pk))
        out_lines.append("")
        out_lines.append(emit_u8(f"kRaccoongBuffMuFixtureMsg{idx}", msg))
        out_lines.append("")
        out_lines.append(emit_u8(f"kRaccoongBuffMuFixtureTr{idx}", tr))
        out_lines.append("")
        out_lines.append(emit_u8(f"kRaccoongBuffMuFixtureMu{idx}", mu))
        out_lines.append("")

    out_lines.append("typedef struct {")
    out_lines.append("    const uint8_t* pk;")
    out_lines.append("    size_t         pk_len;")
    out_lines.append("    const uint8_t* msg;")
    out_lines.append("    size_t         msg_len;")
    out_lines.append("    const uint8_t* tr;")
    out_lines.append("    const uint8_t* mu;")
    out_lines.append("} raccoong_buff_mu_fixture_t;")
    out_lines.append("")
    out_lines.append("static const raccoong_buff_mu_fixture_t "
                     "kRaccoongBuffMuFixtures"
                     "[RACCOONG_BUFF_MU_FIXTURE_COUNT] = {")
    for idx, (pk, msg) in enumerate(cases):
        out_lines.append(
            f"    {{ kRaccoongBuffMuFixturePk{idx}, {len(pk)}, "
            f"kRaccoongBuffMuFixtureMsg{idx}, {len(msg)}, "
            f"kRaccoongBuffMuFixtureTr{idx}, "
            f"kRaccoongBuffMuFixtureMu{idx} }},")
    out_lines.append("};")
    out_lines.append("")
    out_lines.append("#endif /* RACCOONG_BUFF_MU_VECTORS_H */")

    with open(args.out, "w") as f:
        f.write("\n".join(out_lines) + "\n")
    print(f"wrote {args.out} ({len(cases)} cases)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
