#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
gen_ntt_vectors.py - generate C fixture for src/raccoon_g/ntt.c.

Emits a header containing:
  * RACC_W (256-entry twiddle table) verbatim from upstream polyr.py.
  * SHA-256 of RACC_W (little-endian u64 encoding) for an additional gate.
  * Two input polynomials A, B and the expected results of
        ntt(A)
        intt(ntt(A))                            ==  A
        intt(mul_ntt(ntt(A), ntt(B)))           ==  schoolbook(A, B) mod X^n+1
        schoolbook(A, B) mod X^n+1
    so the C side can independently confirm both directions and the
    NTT-multiply equivalence.

USAGE:
    git clone https://github.com/p-11/lattice-hd-wallets /tmp/lattice-hd-wallets
    git -C /tmp/lattice-hd-wallets checkout 461a5ed9b6d57e3bf8c381be3bb79325ab21d906
    python3 contrib/raccoon_g/gen_ntt_vectors.py \\
        --upstream /tmp/lattice-hd-wallets/src/raccoon/thrc-py \\
        --out test/data/raccoong_ntt_vectors.h

Pin: upstream commit 461a5ed9b6d57e3bf8c381be3bb79325ab21d906.
"""

import argparse
import hashlib
import os
import sys


UPSTREAM_COMMIT = "461a5ed9b6d57e3bf8c381be3bb79325ab21d906"


def shake_poly(label: str, n: int, q: int) -> list:
    """Deterministic polynomial of degree n with coefficients in [0, q)."""
    h = hashlib.shake_256()
    h.update(label.encode())
    buf = h.digest(n * 8)
    return [int.from_bytes(buf[i * 8:(i + 1) * 8], "little") % q for i in range(n)]


def emit_array_u64(name: str, values: list) -> str:
    """Emit a uint64_t array in 8-per-line format."""
    lines = [f"static const uint64_t {name}[RACCOONG_N] = {{"]
    for i in range(0, len(values), 8):
        chunk = ", ".join(f"{v}ULL" for v in values[i:i + 8])
        lines.append(f"    {chunk},")
    lines.append("};")
    return "\n".join(lines)


def schoolbook(a: list, b: list, q: int, n: int) -> list:
    """Negacyclic schoolbook multiplication in Z_q[X]/(X^n+1)."""
    r = [0] * n
    for i in range(n):
        for j in range(n):
            t = (a[i] * b[j]) % q
            k = i + j
            if k < n:
                r[k] = (r[k] + t) % q
            else:
                r[k - n] = (r[k - n] - t) % q
    return r


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--upstream", required=True,
                    help="Path to upstream thrc-py directory")
    ap.add_argument("--out", required=True, help="Output header path")
    args = ap.parse_args()

    sys.path.insert(0, args.upstream)
    import polyr  # noqa: E402

    n = polyr.RACC_N
    q = polyr.RACC_Q

    # Twiddle table digest (LE u64 encoding).
    le = b"".join(int(w).to_bytes(8, "little") for w in polyr.RACC_W)
    w_sha = hashlib.sha256(le).hexdigest()

    a = shake_poly("raccoong-ntt-vectors:A", n, q)
    b = shake_poly("raccoong-ntt-vectors:B", n, q)

    a_ntt = polyr.ntt(a.copy())
    a_roundtrip = polyr.intt(a_ntt.copy())
    assert a_roundtrip == a, "upstream NTT roundtrip broken"

    sb = schoolbook(a, b, q, n)
    b_ntt = polyr.ntt(b.copy())
    pointwise = polyr.mul_ntt(a_ntt, b_ntt)
    via_ntt = polyr.intt(pointwise)
    assert via_ntt == sb, "upstream NTT-multiply doesn't match schoolbook"

    header = f"""/*
 * Auto-generated by contrib/raccoon_g/gen_ntt_vectors.py.
 * DO NOT EDIT BY HAND.
 *
 * Upstream pin: p-11/lattice-hd-wallets @ {UPSTREAM_COMMIT}
 *               (src/raccoon/thrc-py/polyr.py)
 *
 * RACC_W (LE-u64) SHA-256: {w_sha}
 */

#ifndef LIBDOGECOIN_TEST_RACCOONG_NTT_VECTORS_H
#define LIBDOGECOIN_TEST_RACCOONG_NTT_VECTORS_H

#include <stdint.h>

#include "src/raccoon_g/polyr.h"

#define RACCOONG_NTT_W_SHA256_HEX \\
    "{w_sha}"

{emit_array_u64('raccoong_ntt_w_table', polyr.RACC_W)}

{emit_array_u64('raccoong_ntt_input_a', a)}

{emit_array_u64('raccoong_ntt_input_b', b)}

{emit_array_u64('raccoong_ntt_expected_ntt_a', a_ntt)}

{emit_array_u64('raccoong_ntt_expected_intt_ntt_a', a_roundtrip)}

{emit_array_u64('raccoong_ntt_expected_schoolbook_ab', sb)}

{emit_array_u64('raccoong_ntt_expected_via_ntt_ab', via_ntt)}

#endif /* LIBDOGECOIN_TEST_RACCOONG_NTT_VECTORS_H */
"""

    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    with open(args.out, "w") as fp:
        fp.write(header)
    print(f"wrote {args.out}  (RACC_W SHA-256: {w_sha})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
