#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
gen_xof_sample_q_vectors.py - generate C fixture for the Raccoon-G uniform
Z_q rejection sampler (`_xof_sample_q` upstream).

Emits a header containing several pinned (seed, expected[N]) cells that the
C side will reproduce byte-exactly.  We pick a small spread of inputs that
exercise the sampler from realistic call sites:

  * cell_A_0_0  : 'A' || i=0 || j=0 || A_seed16   (ExpandA matrix entry)
  * cell_A_3_5  : 'A' || i=3 || j=5 || A_seed16   (mid-matrix)
  * cell_A_8_8  : 'A' || i=8 || j=8 || A_seed16   (last entry of 9x9 matrix)
  * cell_p_1_4  : 'p' || k=0 || i=1 || j=4 || key (poly-coefficient call site)

`A_seed16` and `key` are deterministic test seeds, not random — bit-identical
inputs are required for byte-exact agreement (see the gaussian-sampler note
in the same fixture family).

USAGE:
    git clone https://github.com/p-11/lattice-hd-wallets /tmp/lattice-hd-wallets
    git -C /tmp/lattice-hd-wallets checkout 461a5ed9b6d57e3bf8c381be3bb79325ab21d906
    python3 contrib/raccoon_g/gen_xof_sample_q_vectors.py \\
        --upstream /tmp/lattice-hd-wallets/src/raccoon/thrc-py \\
        --out test/data/raccoong_xof_sample_q_vectors.h

Pin: upstream commit 461a5ed9b6d57e3bf8c381be3bb79325ab21d906.
"""

import argparse
import os
import sys

UPSTREAM_COMMIT = "461a5ed9b6d57e3bf8c381be3bb79325ab21d906"

# Raccoon-G-44 ring/security params (mirrors src/raccoon_g/polyr.h).
RACCOONG_N = 256
RACCOONG_Q = 562949953438721


def _hdr8(ds: str, *args) -> bytes:
    """Reproduce upstream `_hdr8` exactly: 1 char + 7 byte-fields, zero-padded."""
    if len(args) > 7:
        raise ValueError("hdr8 takes at most 7 byte fields")
    fields = list(args) + [0] * (7 - len(args))
    return bytes([ord(ds)]) + bytes(fields)


def _hdr24(ds: str, i: int = 0, j: int = 0, k: int = 0) -> bytes:
    """Reproduce upstream `_hdr24`: 1 char + 1 byte k + 3-byte i + 3-byte j."""
    return (bytes([ord(ds), k]) + int(i).to_bytes(3, "little")
                                + int(j).to_bytes(3, "little"))


def emit_array_u8(name: str, data: bytes) -> str:
    """Emit a uint8_t array, 12-per-line."""
    lines = [f"static const uint8_t {name}[{len(data)}] = {{"]
    for i in range(0, len(data), 12):
        chunk = ", ".join(f"0x{b:02x}" for b in data[i:i + 12])
        lines.append(f"    {chunk},")
    lines.append("};")
    return "\n".join(lines)


def emit_array_u64(name: str, values: list) -> str:
    """Emit a uint64_t array, 8-per-line."""
    lines = [f"static const uint64_t {name}[RACCOONG_N] = {{"]
    for i in range(0, len(values), 8):
        chunk = ", ".join(f"{v}ULL" for v in values[i:i + 8])
        lines.append(f"    {chunk},")
    lines.append("};")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(
        description=("Generate raccoong xof_sample_q fixture pinned to "
                     "upstream " + UPSTREAM_COMMIT))
    ap.add_argument("--upstream", required=True,
                    help="Path to lattice-hd-wallets/src/raccoon/thrc-py")
    ap.add_argument("--out", required=True,
                    help="Output header path under test/data/")
    args = ap.parse_args()

    sys.path.insert(0, args.upstream)
    from thrc_core import ThRc_Core  # noqa: E402

    iut = ThRc_Core()
    assert iut.n == RACCOONG_N
    assert iut.q == RACCOONG_Q

    # Deterministic test seeds; arbitrary but pinned for reproducibility.
    A_seed = bytes(range(16))                          # 0x00..0x0f
    key    = bytes([0xaa]) * 32                        # 32 bytes of 0xaa

    cells = [
        ("cell_A_0_0", _hdr8('A', 0, 0) + A_seed),
        ("cell_A_3_5", _hdr8('A', 3, 5) + A_seed),
        ("cell_A_8_8", _hdr8('A', 8, 8) + A_seed),
        ("cell_p_1_4", _hdr24('p', i=1, j=4, k=0) + key),
    ]

    chunks = []
    chunks.append("/* Auto-generated by contrib/raccoon_g/gen_xof_sample_q_vectors.py")
    chunks.append(" * from upstream commit " + UPSTREAM_COMMIT + ".")
    chunks.append(" * Do not edit; regenerate from a fresh upstream clone if needed.")
    chunks.append(" */")
    chunks.append("#ifndef LIBDOGECOIN_TEST_DATA_RACCOONG_XOF_SAMPLE_Q_VECTORS_H")
    chunks.append("#define LIBDOGECOIN_TEST_DATA_RACCOONG_XOF_SAMPLE_Q_VECTORS_H")
    chunks.append("")
    chunks.append("#include <stdint.h>")
    chunks.append("")
    chunks.append("#include \"src/raccoon_g/polyr.h\"  /* for RACCOONG_N */")
    chunks.append("")

    for name, seed in cells:
        out = iut._xof_sample_q(seed)
        assert len(out) == RACCOONG_N
        chunks.append(f"/* seed = {seed.hex()} ({len(seed)} bytes) */")
        chunks.append(emit_array_u8(f"raccoong_xofq_{name}_seed", seed))
        chunks.append(emit_array_u64(f"raccoong_xofq_{name}_expected", out))
        chunks.append("")

    # Index table for the test driver.
    chunks.append("typedef struct {")
    chunks.append("    const char*    name;")
    chunks.append("    const uint8_t* seed;")
    chunks.append("    size_t         seed_len;")
    chunks.append("    const uint64_t* expected;")
    chunks.append("} raccoong_xofq_case_t;")
    chunks.append("")
    chunks.append("static const raccoong_xofq_case_t raccoong_xofq_cases[] = {")
    for name, seed in cells:
        chunks.append(f"    {{ \"{name}\", raccoong_xofq_{name}_seed, "
                      f"sizeof(raccoong_xofq_{name}_seed), "
                      f"raccoong_xofq_{name}_expected }},")
    chunks.append("};")
    chunks.append("")
    chunks.append("#define RACCOONG_XOFQ_CASE_COUNT "
                  "(sizeof(raccoong_xofq_cases) / sizeof(raccoong_xofq_cases[0]))")
    chunks.append("")
    chunks.append("#endif")
    chunks.append("")

    text = "\n".join(chunks)
    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    with open(args.out, "w", encoding="utf-8") as f:
        f.write(text)

    print(f"wrote {args.out}  ({len(cells)} cells)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
