#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
gen_matvec_vectors.py - generate C fixture for raccoong_mul_mat_vec_ntt
(and indirectly raccoong_expand_a).

Records, byte-exact, the upstream output of:

    A_ntt = _expand_a(A_seed)                # 9 x 9, in NTT domain
    v[j]  = _xof_sample_q(seed_v_j)          # 9 polys, treated as NTT domain
    t     = mul_mat_vec_ntt(A_ntt, v)        # 9 polys, in NTT domain

The C side reconstructs A from `A_seed` via raccoong_expand_a, v from the
recorded `v_seed_j` byte sequences via raccoong_xof_sample_q, computes t via
raccoong_mul_mat_vec_ntt, and asserts byte-exact equality across the full
9 * 256 u64 output.

Also emits one expected (A_row, v_col) pointwise product to validate the
NTT-domain pointwise multiply on its own (not the full sum).

USAGE:
    git clone https://github.com/p-11/lattice-hd-wallets /tmp/lattice-hd-wallets
    git -C /tmp/lattice-hd-wallets checkout 461a5ed9b6d57e3bf8c381be3bb79325ab21d906
    python3 contrib/raccoon_g/gen_matvec_vectors.py \\
        --upstream /tmp/lattice-hd-wallets/src/raccoon/thrc-py \\
        --out test/data/raccoong_matvec_vectors.h

Pin: upstream commit 461a5ed9b6d57e3bf8c381be3bb79325ab21d906.
"""

import argparse
import os
import sys

UPSTREAM_COMMIT = "461a5ed9b6d57e3bf8c381be3bb79325ab21d906"

# Match src/raccoon_g/thrc.h.
RACCOONG_N   = 256
RACCOONG_Q   = 562949953438721
RACCOONG_K   = 9
RACCOONG_ELL = 9


def emit_array_u8(name: str, data: bytes) -> str:
    lines = [f"static const uint8_t {name}[{len(data)}] = {{"]
    for i in range(0, len(data), 12):
        chunk = ", ".join(f"0x{b:02x}" for b in data[i:i + 12])
        lines.append(f"    {chunk},")
    lines.append("};")
    return "\n".join(lines)


def emit_array_u64(name: str, values: list, dim_macro: str) -> str:
    lines = [f"static const uint64_t {name}[{dim_macro}] = {{"]
    for i in range(0, len(values), 8):
        chunk = ", ".join(f"{v}ULL" for v in values[i:i + 8])
        lines.append(f"    {chunk},")
    lines.append("};")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(
        description=("Generate raccoong matvec fixture pinned to "
                     "upstream " + UPSTREAM_COMMIT))
    ap.add_argument("--upstream", required=True,
                    help="Path to lattice-hd-wallets/src/raccoon/thrc-py")
    ap.add_argument("--out", required=True,
                    help="Output header path under test/data/")
    args = ap.parse_args()

    sys.path.insert(0, args.upstream)
    from thrc_core import ThRc_Core  # noqa: E402
    from polyr import mul_mat_vec_ntt, mul_ntt  # noqa: E402

    iut = ThRc_Core()
    assert iut.n == RACCOONG_N
    assert iut.q == RACCOONG_Q
    assert iut.k == RACCOONG_K and iut.ell == RACCOONG_ELL

    # Pinned, deterministic seeds.
    A_seed = bytes(range(16))                      # 0x00..0x0f
    # 16-byte v seeds chosen distinct per column so each v[j] is independent.
    v_seeds = [b'V' + bytes([j]) + bytes(14) for j in range(RACCOONG_ELL)]

    A_ntt = iut._expand_a(A_seed)
    assert len(A_ntt) == RACCOONG_K
    assert all(len(row) == RACCOONG_ELL for row in A_ntt)

    v = [iut._xof_sample_q(s) for s in v_seeds]
    assert len(v) == RACCOONG_ELL

    t = mul_mat_vec_ntt(A_ntt, v)
    assert len(t) == RACCOONG_K
    for row in t:
        assert len(row) == RACCOONG_N
        assert all(0 <= c < RACCOONG_Q for c in row)

    # Pointwise gate: r0 = mul_ntt(A[0][0], v[0]).  This verifies the C
    # `polyr_mul_pointwise` semantics on a fixed pair without summing.
    pointwise_00 = mul_ntt(A_ntt[0][0], v[0])

    chunks = []
    chunks.append("/* Auto-generated by contrib/raccoon_g/gen_matvec_vectors.py")
    chunks.append(" * from upstream commit " + UPSTREAM_COMMIT + ".")
    chunks.append(" * Do not edit; regenerate from a fresh upstream clone if needed.")
    chunks.append(" */")
    chunks.append("#ifndef LIBDOGECOIN_TEST_DATA_RACCOONG_MATVEC_VECTORS_H")
    chunks.append("#define LIBDOGECOIN_TEST_DATA_RACCOONG_MATVEC_VECTORS_H")
    chunks.append("")
    chunks.append("#include <stdint.h>")
    chunks.append("")
    chunks.append("#include \"src/raccoon_g/polyr.h\"  /* RACCOONG_N */")
    chunks.append("#include \"src/raccoon_g/thrc.h\"   /* RACCOONG_K, RACCOONG_ELL, RACCOONG_A_SEED_BYTES */")
    chunks.append("")

    # A_seed
    chunks.append(emit_array_u8("raccoong_matvec_A_seed", A_seed))
    chunks.append("")

    # v seeds (concatenated as one blob with a fixed stride for simplicity).
    seed_len = len(v_seeds[0])
    assert all(len(s) == seed_len for s in v_seeds)
    chunks.append(f"#define RACCOONG_MATVEC_V_SEED_LEN {seed_len}")
    blob = b''.join(v_seeds)
    chunks.append(emit_array_u8("raccoong_matvec_v_seeds_blob", blob))
    chunks.append("")

    # Expected mat-vec output (k * n u64).
    flat_t = [c for row in t for c in row]
    chunks.append(emit_array_u64("raccoong_matvec_t_expected",
                                 flat_t,
                                 "(RACCOONG_K * RACCOONG_N)"))
    chunks.append("")

    # Pointwise A[0][0] * v[0] expected.
    chunks.append(emit_array_u64("raccoong_matvec_pointwise_00_expected",
                                 pointwise_00,
                                 "RACCOONG_N"))
    chunks.append("")

    chunks.append("#endif")
    chunks.append("")

    text = "\n".join(chunks)
    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    with open(args.out, "w", encoding="utf-8") as f:
        f.write(text)

    print(f"wrote {args.out}  (matvec t: {RACCOONG_K * RACCOONG_N} u64)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
