#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
gen_hd_derive_vectors.py - byte-exact fixture for thrc_hd_derive_priv /
thrc_hd_derive_pub against upstream Raccoon-G HD-wallet primitives.

The chain-code-driven tweak-seed derivation is libdogecoin-defined (upstream
exposes the additive lattice machinery but does not pin a BIP-32-shaped
HMAC layout). We mirror the convention implemented in src/raccoon_g/thrc.c
exactly:

    data = tag || sha256(parent_key) || index_BE  (37 bytes)
    tweak_seed = HMAC-SHA512(chaincode, data)[:32]
    drbg_seed  = HKDF-SHA256(tweak_seed, 48)
    key        = NIST_KAT_DRBG(drbg_seed).random_bytes(32)

    non-hardened: tag = b'p' (0x70), parent_key = parent_pk
    hardened:     tag = b'S' (0x53), parent_key = parent_sk

Records, for `seed = bytes(range(32))`, `chaincode = b'\\x42' * 32`, and
index = 7:
  - non-hardened: tweak_seed, child_pk, child_sk
  - hardened:     tweak_seed, child_pk, child_sk

USAGE:
    git clone https://github.com/p-11/lattice-hd-wallets /tmp/lattice-hd-wallets
    git -C /tmp/lattice-hd-wallets checkout 461a5ed9b6d57e3bf8c381be3bb79325ab21d906
    python3 contrib/raccoon_g/gen_hd_derive_vectors.py \\
        --upstream /tmp/lattice-hd-wallets/src/raccoon/thrc-py \\
        --out test/data/raccoong_hd_derive_vectors.h

Pin: upstream commit 461a5ed9b6d57e3bf8c381be3bb79325ab21d906.
"""

import argparse
import hashlib
import hmac
import os
import struct
import sys

UPSTREAM_COMMIT = "461a5ed9b6d57e3bf8c381be3bb79325ab21d906"
PK_BYTES = 16144
SK_BYTES = 32272
A_SEED_BYTES = 16


def emit_u8(name: str, data: bytes, width: int = 12) -> str:
    lines = [f"static const uint8_t {name}[{len(data)}] = {{"]
    for i in range(0, len(data), width):
        chunk = ", ".join(f"0x{b:02x}" for b in data[i:i + width])
        lines.append(f"    {chunk},")
    lines.append("};")
    return "\n".join(lines)


def derive_tweak_seed(chaincode: bytes, parent_key: bytes, index: int,
                      hardened: bool) -> bytes:
    tag = b'S' if hardened else b'p'
    data = tag + hashlib.sha256(parent_key).digest() + struct.pack(">I", index)
    return hmac.new(chaincode, data, hashlib.sha512).digest()[:32]


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--upstream", required=True,
                   help="path to lattice-hd-wallets/src/raccoon/thrc-py")
    p.add_argument("--out", required=True, help="header file to write")
    args = p.parse_args()

    sys.path.insert(0, args.upstream)
    from raccoon_primitives import (  # type: ignore  # noqa: E402
        generate_keypair_from_seed,
        generate_tweak_keypair_from_seed,
        add_public_keys,
        add_signing_keys,
        get_public_matrix_seed,
        _PUBLIC_KEY_SIZE,
        _SIGNING_KEY_SIZE,
    )

    assert _PUBLIC_KEY_SIZE == PK_BYTES, _PUBLIC_KEY_SIZE
    assert _SIGNING_KEY_SIZE == SK_BYTES, _SIGNING_KEY_SIZE

    seed = bytes(range(32))
    chaincode = b'\x42' * 32
    index = 7

    parent_pk, parent_sk = generate_keypair_from_seed(seed)
    assert len(parent_pk) == PK_BYTES and len(parent_sk) == SK_BYTES

    parent_A_seed = get_public_matrix_seed(parent_pk)
    assert len(parent_A_seed) == A_SEED_BYTES

    # -------- non-hardened child --------
    nh_tweak_seed = derive_tweak_seed(chaincode, parent_pk, index, False)
    tweak_pk_nh, tweak_sk_nh = generate_tweak_keypair_from_seed(
        nh_tweak_seed, parent_A_seed)
    child_pk_nh = add_public_keys(parent_pk, tweak_pk_nh)
    child_sk_nh = add_signing_keys(parent_sk, tweak_sk_nh)
    assert len(child_pk_nh) == PK_BYTES
    assert len(child_sk_nh) == SK_BYTES

    # -------- hardened child --------
    h_tweak_seed = derive_tweak_seed(chaincode, parent_sk, index | 0x80000000,
                                     True)
    tweak_pk_h, tweak_sk_h = generate_tweak_keypair_from_seed(
        h_tweak_seed, parent_A_seed)
    child_pk_h = add_public_keys(parent_pk, tweak_pk_h)
    child_sk_h = add_signing_keys(parent_sk, tweak_sk_h)
    assert len(child_pk_h) == PK_BYTES
    assert len(child_sk_h) == SK_BYTES

    parts = [
        "/* Auto-generated by contrib/raccoon_g/gen_hd_derive_vectors.py."
        " DO NOT EDIT. */",
        "/* Upstream: p-11/lattice-hd-wallets@"
        f"{UPSTREAM_COMMIT} (generate_tweak_keypair_from_seed +"
        " add_public_keys / add_signing_keys). */",
        "/* Chain-code-driven tweak_seed derivation is libdogecoin-defined;"
        " see src/raccoon_g/thrc.c::hd_derive_tweak_seed. */",
        "#ifndef LIBDOGECOIN_TEST_RACCOONG_HD_DERIVE_VECTORS_H",
        "#define LIBDOGECOIN_TEST_RACCOONG_HD_DERIVE_VECTORS_H",
        "",
        "#include <stdint.h>",
        "",
        f"#define RACCOONG_HD_PK_BYTES {PK_BYTES}u",
        f"#define RACCOONG_HD_SK_BYTES {SK_BYTES}u",
        f"#define RACCOONG_HD_INDEX 0x{index:08x}u",
        "",
        emit_u8("raccoong_hd_seed", seed),
        "",
        emit_u8("raccoong_hd_chaincode", chaincode),
        "",
        emit_u8("raccoong_hd_parent_pk", parent_pk),
        "",
        emit_u8("raccoong_hd_parent_sk", parent_sk),
        "",
        "/* Non-hardened (index = 7). */",
        emit_u8("raccoong_hd_nh_tweak_seed", nh_tweak_seed),
        "",
        emit_u8("raccoong_hd_nh_child_pk", child_pk_nh),
        "",
        emit_u8("raccoong_hd_nh_child_sk", child_sk_nh),
        "",
        "/* Hardened (index | 0x80000000). */",
        emit_u8("raccoong_hd_h_tweak_seed", h_tweak_seed),
        "",
        emit_u8("raccoong_hd_h_child_pk", child_pk_h),
        "",
        emit_u8("raccoong_hd_h_child_sk", child_sk_h),
        "",
        "#endif /* LIBDOGECOIN_TEST_RACCOONG_HD_DERIVE_VECTORS_H */",
        "",
    ]
    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    with open(args.out, "w", encoding="utf-8") as f:
        f.write("\n".join(parts))
    print(f"wrote {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
