#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
gen_sign_vectors.py — byte-exact fixture for `thrc_sign_with_random` and
`thrc_verify` against upstream `ThRc_Core.plain_sign` / `verify`
(Raccoon-G-44, kappa=128).

Generates ONE deterministic test case:
  - kg_seed         (32 B)   - feeds `thrc_keygen_from_seed`
  - msg             (variable)
  - master_random   (32 B)   - replaces the upstream `random_bytes(kg_sz)` call
  - sig             (20768 B)- encoded with libdogecoin's fixed 7-B / 2-B wire
                               format (NOT upstream's compressed sig_sz=11524)

Pin: lattice-hd-wallets@461a5ed9b6d57e3bf8c381be3bb79325ab21d906.
"""

import argparse
import sys

UPSTREAM_COMMIT = "461a5ed9b6d57e3bf8c381be3bb79325ab21d906"


def emit_u8(name: str, data: bytes, width: int = 16) -> str:
    if len(data) == 0:
        return f"static const uint8_t {name}[1] = {{ 0 }}; /* unused, len=0 */"
    lines = [f"static const uint8_t {name}[{len(data)}] = {{"]
    for i in range(0, len(data), width):
        chunk = ", ".join(f"0x{b:02x}" for b in data[i:i + width])
        lines.append(f"    {chunk},")
    lines.append("};")
    return "\n".join(lines)


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--upstream", required=True,
                   help="path to lattice-hd-wallets/src/raccoon/thrc-py")
    p.add_argument("--out", required=True, help="header file to write")
    args = p.parse_args()

    sys.path.insert(0, args.upstream)
    from raccoon_primitives import (  # noqa: E402
        generate_keypair_from_seed,
        deserialize_signing_key,
        serialize_signature as _ss,
        deserialize_signature as _ds,
        _sign_with_unrounded_public_key,
        _verify_with_unrounded_public_key,
        _compute_buff_mu,
    )
    from thrc_api import TRaccoon  # noqa: E402

    kg_seed = bytes(range(1, 33))           # 0x01..0x20
    master_random = bytes(range(0x20, 0x40))  # 0x20..0x3f
    msg = b"libdogecoin raccoon-g sign KAT v1"

    pk_bytes, sk_bytes = generate_keypair_from_seed(kg_seed)
    assert len(pk_bytes) == 16144
    assert len(sk_bytes) == 32272

    api = TRaccoon(kappa=128)

    # Replace the one-shot `random_bytes(kg_sz)` call inside plain_sign with a
    # deterministic 32-byte blob.  Any other call (none expected in plain_sign)
    # would trip the assertion.
    state = {"calls": 0}

    def det_rand(n):
        state["calls"] += 1
        if n != 32:
            raise RuntimeError(f"unexpected random_bytes len={n}")
        if state["calls"] > 1:
            raise RuntimeError("plain_sign drew randomness more than once")
        return master_random

    api.random_bytes = det_rand

    msk = deserialize_signing_key(sk_bytes)
    vk, s = msk
    mu = _compute_buff_mu(api, vk, msg)
    c_hash, z, h = _sign_with_unrounded_public_key(api, vk, s, mu)

    q = api.q
    q_w = api.q_w
    sig = bytearray(c_hash)
    for poly in z:
        for c in poly:
            sig.extend(int(c % q).to_bytes(7, "little"))
    for poly in h:
        for c in poly:
            sig.extend(int(c % q_w).to_bytes(2, "little"))
    sig = bytes(sig)
    assert len(sig) == 20768, f"unexpected sig len {len(sig)}"

    # Sanity: upstream HD-variant verify accepts the tuple after serialization
    # round-trip (upstream's `_check_bounds` requires centered h to clear the
    # bound; `_sign_with_unrounded_public_key` returns h in [0, q_w) and only
    # `deserialize_signature` centers it to [-q_w/2, q_w/2)).
    sig_tuple_round_tripped = _ds(_ss((c_hash, z, h)))
    assert _verify_with_unrounded_public_key(api, vk, mu,
                                             sig_tuple_round_tripped)

    out_lines = []
    out_lines.append("/* SPDX-License-Identifier: MIT */")
    out_lines.append("/* Auto-generated by contrib/raccoon_g/gen_sign_vectors.py"
                     " - DO NOT EDIT. */")
    out_lines.append(f"/* Pin: lattice-hd-wallets@{UPSTREAM_COMMIT} */")
    out_lines.append("#ifndef RACCOONG_SIGN_VECTORS_H")
    out_lines.append("#define RACCOONG_SIGN_VECTORS_H")
    out_lines.append("#include <stddef.h>")
    out_lines.append("#include <stdint.h>")
    out_lines.append("")
    out_lines.append(emit_u8("kRaccoongSignKgSeed", kg_seed))
    out_lines.append("")
    out_lines.append(emit_u8("kRaccoongSignMasterRandom", master_random))
    out_lines.append("")
    out_lines.append(emit_u8("kRaccoongSignMsg", msg))
    out_lines.append(f"#define RACCOONG_SIGN_MSG_LEN {len(msg)}")
    out_lines.append("")
    out_lines.append(emit_u8("kRaccoongSignExpectedSig", sig))
    out_lines.append(f"#define RACCOONG_SIGN_EXPECTED_SIG_LEN {len(sig)}")
    out_lines.append("")
    out_lines.append("#endif /* RACCOONG_SIGN_VECTORS_H */")

    with open(args.out, "w") as f:
        f.write("\n".join(out_lines) + "\n")
    print(f"wrote {args.out} (msg_len={len(msg)}, sig_len={len(sig)})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
