#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
gen_chal_poly_vectors.py - byte-exact fixture for raccoong_chal_poly
against upstream `ThRc_Core._chal_poly` (Raccoon-G-44, kappa=128, tau=23).

Records, for several deterministically-chosen 32-byte challenge digests:
  - the input c_hash (32 bytes)
  - the resulting tau-weight ternary polynomial (256 int8 values in
    {-1, 0, +1}, with exactly tau non-zero entries)

Pin: lattice-hd-wallets@461a5ed9b6d57e3bf8c381be3bb79325ab21d906.

USAGE:
    git clone https://github.com/p-11/lattice-hd-wallets /tmp/lhd
    git -C /tmp/lhd checkout 461a5ed9b6d57e3bf8c381be3bb79325ab21d906
    python3 contrib/raccoon_g/gen_chal_poly_vectors.py \
        --upstream /tmp/lhd/src/raccoon/thrc-py \
        --out test/data/raccoong_chal_poly_vectors.h
"""

import argparse
import hashlib
import sys

UPSTREAM_COMMIT = "461a5ed9b6d57e3bf8c381be3bb79325ab21d906"
N = 256
TAU = 23


def emit_u8(name: str, data: bytes, width: int = 16) -> str:
    lines = [f"static const uint8_t {name}[{len(data)}] = {{"]
    for i in range(0, len(data), width):
        chunk = ", ".join(f"0x{b:02x}" for b in data[i:i + width])
        lines.append(f"    {chunk},")
    lines.append("};")
    return "\n".join(lines)


def emit_i8(name: str, data, width: int = 16) -> str:
    lines = [f"static const int8_t {name}[{len(data)}] = {{"]
    for i in range(0, len(data), width):
        chunk = ", ".join(f"{x:2d}" for x in data[i:i + width])
        lines.append(f"    {chunk},")
    lines.append("};")
    return "\n".join(lines)


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--upstream", required=True,
                   help="path to lattice-hd-wallets/src/raccoon/thrc-py")
    p.add_argument("--out", required=True, help="header file to write")
    args = p.parse_args()

    sys.path.insert(0, args.upstream)
    from thrc_core import ThRc_Core   # type: ignore  # noqa: E402

    raccoon = ThRc_Core(kappa=128)
    assert raccoon.tau == TAU, raccoon.tau
    assert raccoon.n == N

    # Deterministic, distinct 32-byte digests covering several distributions.
    seeds = [
        hashlib.sha256(b"raccoong-chal-poly-fixture-v1/0").digest(),
        hashlib.sha256(b"raccoong-chal-poly-fixture-v1/1").digest(),
        hashlib.sha256(b"raccoong-chal-poly-fixture-v1/2").digest(),
        bytes(32),                       # all-zero
        bytes(b"\xff" * 32),             # all-ones
    ]

    out_lines = []
    out_lines.append("/* SPDX-License-Identifier: MIT */")
    out_lines.append("/* Auto-generated by contrib/raccoon_g/"
                     "gen_chal_poly_vectors.py - DO NOT EDIT. */")
    out_lines.append(f"/* Pin: lattice-hd-wallets@{UPSTREAM_COMMIT} */")
    out_lines.append("#ifndef RACCOONG_CHAL_POLY_VECTORS_H")
    out_lines.append("#define RACCOONG_CHAL_POLY_VECTORS_H")
    out_lines.append("#include <stdint.h>")
    out_lines.append("")
    out_lines.append(f"#define RACCOONG_CHAL_POLY_FIXTURE_N    {N}")
    out_lines.append(f"#define RACCOONG_CHAL_POLY_FIXTURE_TAU  {TAU}")
    out_lines.append(f"#define RACCOONG_CHAL_POLY_FIXTURE_COUNT {len(seeds)}")
    out_lines.append("")

    for i, seed in enumerate(seeds):
        c_poly = raccoon._chal_poly(seed)
        assert len(c_poly) == N
        nz = sum(1 for v in c_poly if v != 0)
        assert nz == TAU, f"weight {nz} != tau={TAU}"
        for v in c_poly:
            assert v in (-1, 0, 1), v
        out_lines.append(emit_u8(f"kRaccoongChalPolyFixtureCHash{i}", seed))
        out_lines.append("")
        out_lines.append(emit_i8(f"kRaccoongChalPolyFixtureExpected{i}", c_poly))
        out_lines.append("")

    out_lines.append("typedef struct {")
    out_lines.append("    const uint8_t* c_hash;")
    out_lines.append("    const int8_t*  expected;")
    out_lines.append("} raccoong_chal_poly_fixture_t;")
    out_lines.append("")
    out_lines.append("static const raccoong_chal_poly_fixture_t "
                     "kRaccoongChalPolyFixtures[RACCOONG_CHAL_POLY_FIXTURE_COUNT] = {")
    for i in range(len(seeds)):
        out_lines.append(
            f"    {{ kRaccoongChalPolyFixtureCHash{i}, "
            f"kRaccoongChalPolyFixtureExpected{i} }},")
    out_lines.append("};")
    out_lines.append("")
    out_lines.append("#endif /* RACCOONG_CHAL_POLY_VECTORS_H */")

    with open(args.out, "w") as f:
        f.write("\n".join(out_lines) + "\n")
    print(f"wrote {args.out} ({len(seeds)} cases)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
