#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
gen_polyr_vectors.py - generate C fixture for src/raccoon_g/polyr.c.

Imports the upstream Raccoon-G Python reference (p-11/lattice-hd-wallets) and
emits a C header containing input vectors (A, B), a scalar, shift counts, and
the expected results of every polyr.c arithmetic operation we implement.

USAGE:
    git clone https://github.com/p-11/lattice-hd-wallets /tmp/lattice-hd-wallets
    cd /tmp/lattice-hd-wallets && git checkout 461a5ed9b6d57e3bf8c381be3bb79325ab21d906
    python3 contrib/raccoon_g/gen_polyr_vectors.py \\
        --upstream /tmp/lattice-hd-wallets/src/raccoon/thrc-py \\
        --out test/data/raccoong_polyr_vectors.h

The generated header is checked in; this script is committed so future
contributors can re-derive it byte-for-byte.

Pin: upstream commit 461a5ed9b6d57e3bf8c381be3bb79325ab21d906 ("update name in
README (#14)").
"""

import argparse
import hashlib
import os
import sys


UPSTREAM_COMMIT = "461a5ed9b6d57e3bf8c381be3bb79325ab21d906"

# Test parameters
SCALAR = 7
LSHIFT = 3
RSHIFT = 5


def shake_poly(label: str, n: int, q: int) -> list:
    """Deterministic polynomial of degree n with coefficients in [0, q)."""
    h = hashlib.shake_256()
    h.update(label.encode())
    buf = h.digest(n * 8)
    return [int.from_bytes(buf[i * 8:(i + 1) * 8], "little") % q for i in range(n)]


def emit_array_u64(name: str, values: list) -> str:
    """Emit a 256-element uint64_t array, eight values per line."""
    lines = [f"static const uint64_t {name}[RACCOONG_N] = {{"]
    for i in range(0, len(values), 8):
        chunk = ", ".join(f"{v}ULL" for v in values[i:i + 8])
        lines.append(f"    {chunk},")
    lines.append("};")
    return "\n".join(lines)


def emit_array_i64(name: str, values: list) -> str:
    """Emit a 256-element int64_t array (for centered values)."""
    lines = [f"static const int64_t {name}[RACCOONG_N] = {{"]
    for i in range(0, len(values), 8):
        chunk = ", ".join(f"{v}LL" for v in values[i:i + 8])
        lines.append(f"    {chunk},")
    lines.append("};")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--upstream", required=True,
                    help="Path to upstream thrc-py directory")
    ap.add_argument("--out", required=True, help="Output header path")
    args = ap.parse_args()

    sys.path.insert(0, args.upstream)
    import polyr  # noqa: E402  (imported via dynamic path)

    n = polyr.RACC_N
    q = polyr.RACC_Q
    ni = polyr.RACC_NI

    a = shake_poly("raccoong-polyr-vectors:A", n, q)
    b = shake_poly("raccoong-polyr-vectors:B", n, q)

    expected = {
        "expected_add":      polyr.poly_add(a, b),
        "expected_sub":      polyr.poly_sub(a, b),
        "expected_mul_pw":   polyr.mul_ntt(a, b),       # pointwise mul in NTT domain (C: polyr_mul_pointwise)
        "expected_scale":    polyr.poly_scale(SCALAR, a),
        "expected_lshift":   polyr.poly_lshift(a, LSHIFT),
        "expected_rshift":   polyr.poly_rshift(a, RSHIFT),
    }
    expected_center = polyr.poly_center(a)  # signed

    header = f"""/*
 * Auto-generated by contrib/raccoon_g/gen_polyr_vectors.py.
 * DO NOT EDIT BY HAND.
 *
 * Upstream pin: p-11/lattice-hd-wallets @ {UPSTREAM_COMMIT}
 *               (src/raccoon/thrc-py/polyr.py)
 *
 * Parameters: N={n}, Q={q}, NI={ni}.
 */

#ifndef LIBDOGECOIN_TEST_RACCOONG_POLYR_VECTORS_H
#define LIBDOGECOIN_TEST_RACCOONG_POLYR_VECTORS_H

#include <stdint.h>

#include "src/raccoon_g/polyr.h"

#define RACCOONG_POLYR_TEST_SCALAR  {SCALAR}ULL
#define RACCOONG_POLYR_TEST_LSHIFT  {LSHIFT}
#define RACCOONG_POLYR_TEST_RSHIFT  {RSHIFT}

{emit_array_u64('raccoong_polyr_input_a', a)}

{emit_array_u64('raccoong_polyr_input_b', b)}

{emit_array_u64('raccoong_polyr_expected_add', expected['expected_add'])}

{emit_array_u64('raccoong_polyr_expected_sub', expected['expected_sub'])}

{emit_array_u64('raccoong_polyr_expected_mul_pointwise', expected['expected_mul_pw'])}

{emit_array_u64('raccoong_polyr_expected_scale', expected['expected_scale'])}

{emit_array_u64('raccoong_polyr_expected_lshift', expected['expected_lshift'])}

{emit_array_u64('raccoong_polyr_expected_rshift', expected['expected_rshift'])}

{emit_array_i64('raccoong_polyr_expected_center', expected_center)}

#endif /* LIBDOGECOIN_TEST_RACCOONG_POLYR_VECTORS_H */
"""

    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    with open(args.out, "w") as fp:
        fp.write(header)
    print(f"wrote {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
