#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
gen_gaussian_vectors.py - Raccoon-G rounded-Gaussian fixture generator.

Drives upstream `thrc_gauss.sample_rounded` from a fixed seed and emits:
  * `raccoong_gauss_xof_bytes`   - the SHAKE256(seed) prefix consumed by the
                                   sampler. Long enough to cover all
                                   accept/reject iterations needed to produce
                                   `RACCOONG_N` samples for sigma^2 = 2^40.
  * `raccoong_gauss_xof_len`     - the byte length above.
  * `raccoong_gauss_lg_sigma2`   - log2(sigma^2) (= 40 for sigma = 2^20).
  * `raccoong_gauss_seed_bytes`  - the 32-byte seed used (for traceability;
                                   not consumed by the C side in Session 5).
  * `raccoong_gauss_expected[N]` - upstream-produced samples (signed int64).

The C kernel re-runs the math against the recorded byte stream and asserts
byte-exact equality.  Any divergence means the MPFR/mpmath equivalence has
broken at the configured precision and the port must stop.

USAGE:
    git -C /tmp/lattice-hd-wallets checkout 461a5ed9b6d57e3bf8c381be3bb79325ab21d906
    python3 contrib/raccoon_g/gen_gaussian_vectors.py \\
        --upstream /tmp/lattice-hd-wallets/src/raccoon/thrc-py \\
        --out test/data/raccoong_gaussian_vectors.h
"""

import argparse
import os
import sys


UPSTREAM_COMMIT = "461a5ed9b6d57e3bf8c381be3bb79325ab21d906"

# Fixed test seed.  Anything 32 bytes; chosen for traceability.
SEED = bytes.fromhex(
    "5261636f6f6e472d3434204761757373696166697874757265312d76307830"
    "30"  # 32 bytes total
)
assert len(SEED) == 32

# log2(sigma^2): sigma = 2^20 -> sig2 = 2^40.  Matches upstream's smoke test.
LG_SIGMA2 = 40

# How many SHAKE256 bytes the recorded stream covers.  16 bytes per polar
# attempt; with a ~22% rejection rate, 256 samples need ~165 attempts ≈ 2640
# bytes.  Round up generously so the test never hits end-of-stream first.
XOF_LEN = 8192


def emit_array_u8(name: str, values: bytes) -> str:
    lines = [f"static const uint8_t {name}[{len(values)}] = {{"]
    for i in range(0, len(values), 16):
        chunk = ", ".join(f"0x{b:02x}" for b in values[i:i + 16])
        lines.append(f"    {chunk},")
    lines.append("};")
    return "\n".join(lines)


def emit_array_i64(name: str, values: list) -> str:
    lines = [f"static const int64_t {name}[RACCOONG_N] = {{"]
    for i in range(0, len(values), 4):
        chunk = ", ".join(f"INT64_C({v})" for v in values[i:i + 4])
        lines.append(f"    {chunk},")
    lines.append("};")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--upstream", required=True,
                    help="Path to upstream thrc-py directory")
    ap.add_argument("--out", required=True, help="Output header path")
    args = ap.parse_args()

    sys.path.insert(0, args.upstream)
    import thrc_gauss  # noqa: E402  (relies on `from polyr import RACC_N`)

    n = thrc_gauss.RACC_N

    sig2 = 1 << LG_SIGMA2

    # Reference samples
    expected = thrc_gauss.sample_rounded(sig2, SEED, n=n)

    # Recorded XOF byte stream (independent of sampler internal state).
    from Crypto.Hash import SHAKE256
    xof = SHAKE256.new(SEED)
    xof_bytes = xof.read(XOF_LEN)

    header = f"""/*
 * Auto-generated by contrib/raccoon_g/gen_gaussian_vectors.py.
 * DO NOT EDIT BY HAND.
 *
 * Upstream pin: p-11/lattice-hd-wallets @ {UPSTREAM_COMMIT}
 *               (src/raccoon/thrc-py/thrc_gauss.py)
 *
 * sig2 = 2^{LG_SIGMA2} (sigma = 2^{LG_SIGMA2 // 2}).
 * mpmath precision: 256 bits.
 */

#ifndef LIBDOGECOIN_TEST_RACCOONG_GAUSSIAN_VECTORS_H
#define LIBDOGECOIN_TEST_RACCOONG_GAUSSIAN_VECTORS_H

#include <stdint.h>

#include "src/raccoon_g/polyr.h"

#define RACCOONG_GAUSS_LG_SIGMA2  {LG_SIGMA2}
#define RACCOONG_GAUSS_XOF_LEN    {XOF_LEN}

{emit_array_u8('raccoong_gauss_seed_bytes', SEED)}

{emit_array_u8('raccoong_gauss_xof_bytes', xof_bytes)}

{emit_array_i64('raccoong_gauss_expected', expected)}

#endif /* LIBDOGECOIN_TEST_RACCOONG_GAUSSIAN_VECTORS_H */
"""

    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    with open(args.out, "w") as fp:
        fp.write(header)
    print(f"wrote {args.out}  (n={n}, sig2=2^{LG_SIGMA2}, xof={XOF_LEN}B)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
