#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
gen_signature_serialize_vectors.py - byte-exact fixture for
raccoong_serialize_signature / raccoong_deserialize_signature against
upstream Raccoon-G HD-wallet primitives.

Records, for a deterministically-constructed signature tuple
(c_hash, z, h):
  - the raw component arrays (so the C side can build the same tuple)
  - the canonical 20768-byte serialization produced by upstream
    `serialize_signature`

The (z, h) values are NOT taken from a real sign() run (which would
require the full sign/verify port and a deterministic-RNG hook). Instead
they are filled with simple deterministic patterns that exercise the
boundary conditions of the encoder:

  z[i][j] = (RACC_Q - 1 - (12345 * (i * 256 + j) + 7)) % RACC_Q
            (covers the high end of [0, q) and forces a non-trivial
             7-byte little-endian payload for every coefficient)

  h_signed[i][j] in {-q_w/2, ..., q_w/2 - 1} cycling through:
      ((42 * (i * 256 + j) + 1) % q_w) - q_w/2
            (covers both the negative and positive half of the centered
             range so the round-trip exercises the centering logic)

  c_hash = SHA256(b"raccoong-sig-serialize-fixture-v1").digest()

Pin: upstream commit 461a5ed9b6d57e3bf8c381be3bb79325ab21d906.

USAGE:
    git clone https://github.com/p-11/lattice-hd-wallets /tmp/lattice-hd-wallets
    git -C /tmp/lattice-hd-wallets checkout 461a5ed9b6d57e3bf8c381be3bb79325ab21d906
    python3 contrib/raccoon_g/gen_signature_serialize_vectors.py \
        --upstream /tmp/lattice-hd-wallets/src/raccoon/thrc-py \
        --out test/data/raccoong_signature_serialize_vectors.h
"""

import argparse
import hashlib
import sys

UPSTREAM_COMMIT = "461a5ed9b6d57e3bf8c381be3bb79325ab21d906"
SIG_BYTES = 20768
CRH_BYTES = 32
COEFF_BYTES = 7
H_COEFF_BYTES = 2
ELL = 9
K = 9
N = 256


def emit_u8(name: str, data: bytes, width: int = 12) -> str:
    lines = [f"static const uint8_t {name}[{len(data)}] = {{"]
    for i in range(0, len(data), width):
        chunk = ", ".join(f"0x{b:02x}" for b in data[i:i + width])
        lines.append(f"    {chunk},")
    lines.append("};")
    return "\n".join(lines)


def emit_u64(name: str, data, width: int = 4) -> str:
    lines = [f"static const uint64_t {name}[{len(data)}] = {{"]
    for i in range(0, len(data), width):
        chunk = ", ".join(f"0x{x:016x}ULL" for x in data[i:i + width])
        lines.append(f"    {chunk},")
    lines.append("};")
    return "\n".join(lines)


def emit_i16(name: str, data, width: int = 12) -> str:
    lines = [f"static const int16_t {name}[{len(data)}] = {{"]
    for i in range(0, len(data), width):
        chunk = ", ".join(f"{x:d}" for x in data[i:i + width])
        lines.append(f"    {chunk},")
    lines.append("};")
    return "\n".join(lines)


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--upstream", required=True,
                   help="path to lattice-hd-wallets/src/raccoon/thrc-py")
    p.add_argument("--out", required=True, help="header file to write")
    args = p.parse_args()

    sys.path.insert(0, args.upstream)
    from raccoon_primitives import (  # type: ignore  # noqa: E402
        serialize_signature,
        deserialize_signature,
        _SIGNATURE_SIZE,
        _CRH_SIZE,
        _COEFF_BYTES,
        _H_COEFF_BYTES,
        _Q_W,
        _ELL,
        _K,
        _N,
    )
    from polyr import RACC_Q  # type: ignore  # noqa: E402

    assert _SIGNATURE_SIZE == SIG_BYTES, _SIGNATURE_SIZE
    assert _CRH_SIZE == CRH_BYTES
    assert _COEFF_BYTES == COEFF_BYTES
    assert _H_COEFF_BYTES == H_COEFF_BYTES
    assert _ELL == ELL and _K == K and _N == N

    half_qw = _Q_W // 2

    c_hash = hashlib.sha256(
        b"raccoong-sig-serialize-fixture-v1").digest()[:CRH_BYTES]

    z = []
    z_flat = []
    for i in range(ELL):
        poly = []
        for j in range(N):
            v = (RACC_Q - 1 - (12345 * (i * N + j) + 7)) % RACC_Q
            poly.append(v)
            z_flat.append(v)
        z.append(poly)

    h_signed = []
    h_flat_signed = []
    for i in range(K):
        poly = []
        for j in range(N):
            v = ((42 * (i * N + j) + 1) % _Q_W) - half_qw
            poly.append(v)
            h_flat_signed.append(v)
        h_signed.append(poly)

    sig_bytes = serialize_signature((c_hash, z, h_signed))
    assert len(sig_bytes) == SIG_BYTES

    # Round-trip check upstream-side
    c2, z2, h2 = deserialize_signature(sig_bytes)
    assert c2 == c_hash
    assert z2 == z
    assert h2 == h_signed

    out = []
    out.append("/* SPDX-License-Identifier: MIT */")
    out.append("/* Auto-generated by contrib/raccoon_g/"
               "gen_signature_serialize_vectors.py - DO NOT EDIT. */")
    out.append(f"/* Pin: lattice-hd-wallets@{UPSTREAM_COMMIT} */")
    out.append("#ifndef RACCOONG_SIGNATURE_SERIALIZE_VECTORS_H")
    out.append("#define RACCOONG_SIGNATURE_SERIALIZE_VECTORS_H")
    out.append("#include <stdint.h>")
    out.append("")
    out.append(f"#define RACCOONG_SIG_FIXTURE_BYTES {SIG_BYTES}")
    out.append(f"#define RACCOONG_SIG_FIXTURE_ELL   {ELL}")
    out.append(f"#define RACCOONG_SIG_FIXTURE_K     {K}")
    out.append(f"#define RACCOONG_SIG_FIXTURE_N     {N}")
    out.append("")
    out.append(emit_u8("kRaccoongSigFixtureCHash", c_hash))
    out.append("")
    out.append(emit_u64("kRaccoongSigFixtureZFlat", z_flat))
    out.append("")
    out.append(emit_i16("kRaccoongSigFixtureHFlatSigned", h_flat_signed))
    out.append("")
    out.append(emit_u8("kRaccoongSigFixtureSerialized", sig_bytes))
    out.append("")
    out.append("#endif /* RACCOONG_SIGNATURE_SERIALIZE_VECTORS_H */")

    with open(args.out, "w") as f:
        f.write("\n".join(out) + "\n")
    print(f"wrote {args.out} ({len(sig_bytes)} sig bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
