#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
gen_hash_vec_vectors.py - byte-exact fixture for raccoong_hash_vec
against upstream `ThRc_Core._hash_vec` (Raccoon-G-44, kappa=128).

Records, for several deterministic inputs of varying dat/vec lengths:
  - the ds byte ('H')
  - the input `dat` (variable length)
  - the input vector `v` (uint64 coefficients reduced mod q on-the-fly)
  - the resulting 32-byte digest

Pin: lattice-hd-wallets@461a5ed9b6d57e3bf8c381be3bb79325ab21d906.
"""

import argparse
import hashlib
import sys

UPSTREAM_COMMIT = "461a5ed9b6d57e3bf8c381be3bb79325ab21d906"
CRH = 32


def emit_u8(name: str, data: bytes, width: int = 16) -> str:
    if len(data) == 0:
        return f"static const uint8_t {name}[1] = {{ 0 }}; /* unused, len=0 */"
    lines = [f"static const uint8_t {name}[{len(data)}] = {{"]
    for i in range(0, len(data), width):
        chunk = ", ".join(f"0x{b:02x}" for b in data[i:i + width])
        lines.append(f"    {chunk},")
    lines.append("};")
    return "\n".join(lines)


def emit_u64(name: str, data, width: int = 4) -> str:
    if len(data) == 0:
        return f"static const uint64_t {name}[1] = {{ 0 }}; /* unused, len=0 */"
    lines = [f"static const uint64_t {name}[{len(data)}] = {{"]
    for i in range(0, len(data), width):
        chunk = ", ".join(f"{x}ULL" for x in data[i:i + width])
        lines.append(f"    {chunk},")
    lines.append("};")
    return "\n".join(lines)


def gen_vec(seed: bytes, n: int, q: int) -> list:
    """Deterministic pseudo-random vector of n entries in [0, q)."""
    out = []
    counter = 0
    while len(out) < n:
        block = hashlib.sha256(seed + counter.to_bytes(4, "big")).digest()
        for i in range(0, len(block), 8):
            if len(out) >= n:
                break
            x = int.from_bytes(block[i:i + 8], "little") % q
            out.append(x)
        counter += 1
    return out


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--upstream", required=True,
                   help="path to lattice-hd-wallets/src/raccoon/thrc-py")
    p.add_argument("--out", required=True, help="header file to write")
    args = p.parse_args()

    sys.path.insert(0, args.upstream)
    from thrc_core import ThRc_Core   # type: ignore  # noqa: E402
    from polyr import RACC_Q          # type: ignore  # noqa: E402

    raccoon = ThRc_Core(kappa=128)
    n = raccoon.n
    k = raccoon.k

    # Cases:
    #   0) empty dat, 1-element vector (upstream `_hash_vec` requires |v|>=1)
    #   1) short dat, single polynomial worth of coefficients (n)
    #   2) 32-byte mu, full w-style vector (k * n)
    #   3) larger dat (3*n random bytes), 2*n coefficients
    cases = [
        ("H", b"", [0]),
        ("H", b"raccoong-hash-vec/short-dat",
            gen_vec(b"hash_vec/case1", n, RACC_Q)),
        ("H", hashlib.sha256(b"raccoong-hash-vec/mu-style").digest(),
            gen_vec(b"hash_vec/case2", k * n, RACC_Q)),
        ("H", hashlib.sha3_512(b"raccoong-hash-vec/long-dat").digest()
              + hashlib.sha3_512(b"raccoong-hash-vec/long-dat/2").digest(),
            gen_vec(b"hash_vec/case3", 2 * n, RACC_Q)),
    ]

    out_lines = []
    out_lines.append("/* SPDX-License-Identifier: MIT */")
    out_lines.append("/* Auto-generated by contrib/raccoon_g/"
                     "gen_hash_vec_vectors.py - DO NOT EDIT. */")
    out_lines.append(f"/* Pin: lattice-hd-wallets@{UPSTREAM_COMMIT} */")
    out_lines.append("#ifndef RACCOONG_HASH_VEC_VECTORS_H")
    out_lines.append("#define RACCOONG_HASH_VEC_VECTORS_H")
    out_lines.append("#include <stddef.h>")
    out_lines.append("#include <stdint.h>")
    out_lines.append("")
    out_lines.append(f"#define RACCOONG_HASH_VEC_FIXTURE_COUNT {len(cases)}")
    out_lines.append(f"#define RACCOONG_HASH_VEC_FIXTURE_CRH    {CRH}")
    out_lines.append("")

    for idx, (ds, dat, v) in enumerate(cases):
        digest = raccoon._hash_vec(dat, v, ds=ds)
        assert len(digest) == CRH

        out_lines.append(emit_u8(f"kRaccoongHashVecFixtureDat{idx}", dat))
        out_lines.append("")
        out_lines.append(emit_u64(f"kRaccoongHashVecFixtureV{idx}", v))
        out_lines.append("")
        out_lines.append(emit_u8(f"kRaccoongHashVecFixtureDigest{idx}",
                                 bytes(digest)))
        out_lines.append("")

    out_lines.append("typedef struct {")
    out_lines.append("    char           ds;")
    out_lines.append("    const uint8_t* dat;")
    out_lines.append("    size_t         dat_len;")
    out_lines.append("    const uint64_t* v;")
    out_lines.append("    size_t         v_len;")
    out_lines.append("    const uint8_t* digest;")
    out_lines.append("} raccoong_hash_vec_fixture_t;")
    out_lines.append("")
    out_lines.append("static const raccoong_hash_vec_fixture_t "
                     "kRaccoongHashVecFixtures"
                     "[RACCOONG_HASH_VEC_FIXTURE_COUNT] = {")
    for idx, (ds, dat, v) in enumerate(cases):
        out_lines.append(
            f"    {{ '{ds}', "
            f"kRaccoongHashVecFixtureDat{idx}, {len(dat)}, "
            f"kRaccoongHashVecFixtureV{idx}, {len(v)}, "
            f"kRaccoongHashVecFixtureDigest{idx} }},")
    out_lines.append("};")
    out_lines.append("")
    out_lines.append("#endif /* RACCOONG_HASH_VEC_VECTORS_H */")

    with open(args.out, "w") as f:
        f.write("\n".join(out_lines) + "\n")
    print(f"wrote {args.out} ({len(cases)} cases)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
