#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
gen_keygen_t_vectors.py - byte-exact fixture for raccoong_keygen_t_unrounded
against upstream `_keygen_unrounded(raccoon, key)`.

Records, for a fixed 32-byte `key = bytes(range(32))`:
  - A_seed         (16 bytes)
  - t              (9 polynomials x 256 coefficients, each in [0, q))
  - s slices       (first row of the secret vector, signed int64)
  - e1 slices      (recomputed locally, signed int64) — for localization

USAGE:
    git clone https://github.com/p-11/lattice-hd-wallets /tmp/lattice-hd-wallets
    git -C /tmp/lattice-hd-wallets checkout 461a5ed9b6d57e3bf8c381be3bb79325ab21d906
    python3 contrib/raccoon_g/gen_keygen_t_vectors.py \\
        --upstream /tmp/lattice-hd-wallets/src/raccoon/thrc-py \\
        --out test/data/raccoong_keygen_t_vectors.h

Pin: upstream commit 461a5ed9b6d57e3bf8c381be3bb79325ab21d906.
"""

import argparse
import os
import sys

UPSTREAM_COMMIT = "461a5ed9b6d57e3bf8c381be3bb79325ab21d906"

RACCOONG_N = 256
RACCOONG_Q = 562949953438721
RACCOONG_K = 9
RACCOONG_ELL = 9
A_SEED_BYTES = 16


def emit_u8(name: str, data: bytes) -> str:
    lines = [f"static const uint8_t {name}[{len(data)}] = {{"]
    for i in range(0, len(data), 12):
        chunk = ", ".join(f"0x{b:02x}" for b in data[i:i + 12])
        lines.append(f"    {chunk},")
    lines.append("};")
    return "\n".join(lines)


def emit_u64(name: str, values: list, dim_macro: str) -> str:
    lines = [f"static const uint64_t {name}[{dim_macro}] = {{"]
    for i in range(0, len(values), 8):
        chunk = ", ".join(f"{v}ULL" for v in values[i:i + 8])
        lines.append(f"    {chunk},")
    lines.append("};")
    return "\n".join(lines)


def emit_i64(name: str, values: list, length: int) -> str:
    lines = [f"static const int64_t {name}[{length}] = {{"]
    for i in range(0, len(values), 8):
        chunk = ", ".join(f"{v}LL" for v in values[i:i + 8])
        lines.append(f"    {chunk},")
    lines.append("};")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(
        description=("Generate raccoong keygen-t fixture pinned to "
                     "upstream " + UPSTREAM_COMMIT))
    ap.add_argument("--upstream", required=True)
    ap.add_argument("--out", required=True)
    args = ap.parse_args()

    sys.path.insert(0, args.upstream)
    from thrc_core import ThRc_Core  # noqa: E402
    from thrc_gauss import sample_rounded  # noqa: E402
    from raccoon_primitives import _keygen_unrounded  # noqa: E402

    iut = ThRc_Core()
    assert iut.n == RACCOONG_N
    assert iut.q == RACCOONG_Q
    assert iut.k == RACCOONG_K and iut.ell == RACCOONG_ELL
    assert iut.as_sz == A_SEED_BYTES
    assert iut.lg_st == 7  # → sigma_t^2 = 2^14

    key = bytes(range(32))
    vk, s = _keygen_unrounded(iut, key)
    A_seed, t = vk

    # Sanity: every t coefficient must already be reduced to [0, q).
    for row in t:
        assert len(row) == RACCOONG_N
        assert all(0 <= c < RACCOONG_Q for c in row)

    # Recompute s[0] and e1[0] independently for localized regression
    # diagnostics — these are what the C-side gaussian helper feeds the NTT.
    sigt2 = 1 << (2 * iut.lg_st)  # 2^14
    s0_signed = sample_rounded(sigt2, iut._hdr8('s', 0) + key, n=RACCOONG_N)
    e1_0_signed = sample_rounded(sigt2, iut._hdr8('e', 0, 1) + key,
                                 n=RACCOONG_N)
    # Self-check: s[0] from _keygen_unrounded must match recomputed s0.
    assert list(s[0]) == list(s0_signed), \
        "internal: upstream s[0] != recomputed sample_rounded"

    flat_t = [c for row in t for c in row]

    chunks = []
    chunks.append("/* Auto-generated by "
                  "contrib/raccoon_g/gen_keygen_t_vectors.py")
    chunks.append(" * from upstream commit " + UPSTREAM_COMMIT + ".")
    chunks.append(" * Do not edit; regenerate from a fresh upstream clone.")
    chunks.append(" */")
    chunks.append("#ifndef LIBDOGECOIN_TEST_DATA_RACCOONG_KEYGEN_T_VECTORS_H")
    chunks.append("#define LIBDOGECOIN_TEST_DATA_RACCOONG_KEYGEN_T_VECTORS_H")
    chunks.append("")
    chunks.append("#include <stdint.h>")
    chunks.append("")
    chunks.append('#include "src/raccoon_g/polyr.h"  /* RACCOONG_N */')
    chunks.append('#include "src/raccoon_g/thrc.h"   /* RACCOONG_K, _ELL, _A_SEED_BYTES */')
    chunks.append("")

    chunks.append(emit_u8("raccoong_keygen_t_key", key))
    chunks.append("")
    chunks.append(emit_u8("raccoong_keygen_t_A_seed_expected", A_seed))
    chunks.append("")
    chunks.append(emit_u64("raccoong_keygen_t_expected", flat_t,
                           "(RACCOONG_K * RACCOONG_N)"))
    chunks.append("")
    chunks.append(emit_i64("raccoong_keygen_t_s0_expected", s0_signed,
                           RACCOONG_N))
    chunks.append("")
    chunks.append(emit_i64("raccoong_keygen_t_e1_0_expected", e1_0_signed,
                           RACCOONG_N))
    chunks.append("")
    chunks.append("#endif")
    chunks.append("")

    text = "\n".join(chunks)
    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    with open(args.out, "w", encoding="utf-8") as f:
        f.write(text)
    print(f"wrote {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
