#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
gen_keypair_vectors.py - byte-exact fixture for thrc_keygen_from_seed
against upstream `generate_keypair_from_seed(seed)`.

Records, for `seed = bytes(range(32))`:
  - seed       (32 bytes)
  - drbg_seed  (48 bytes, HKDF-SHA256 output)
  - drbg_key   (32 bytes, drbg.random_bytes(32))   -- feeds _keygen_unrounded
  - pk         (16144 bytes, serialize_public_key)
  - sk         (32272 bytes, serialize_signing_key)

USAGE:
    git clone https://github.com/p-11/lattice-hd-wallets /tmp/lattice-hd-wallets
    git -C /tmp/lattice-hd-wallets checkout 461a5ed9b6d57e3bf8c381be3bb79325ab21d906
    python3 contrib/raccoon_g/gen_keypair_vectors.py \\
        --upstream /tmp/lattice-hd-wallets/src/raccoon/thrc-py \\
        --out test/data/raccoong_keypair_vectors.h

Pin: upstream commit 461a5ed9b6d57e3bf8c381be3bb79325ab21d906.
"""

import argparse
import os
import sys

UPSTREAM_COMMIT = "461a5ed9b6d57e3bf8c381be3bb79325ab21d906"
PK_BYTES = 16144
SK_BYTES = 32272


def emit_u8(name: str, data: bytes, width: int = 12) -> str:
    lines = [f"static const uint8_t {name}[{len(data)}] = {{"]
    for i in range(0, len(data), width):
        chunk = ", ".join(f"0x{b:02x}" for b in data[i:i + width])
        lines.append(f"    {chunk},")
    lines.append("};")
    return "\n".join(lines)


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--upstream", required=True,
                   help="path to lattice-hd-wallets/src/raccoon/thrc-py")
    p.add_argument("--out", required=True, help="header file to write")
    args = p.parse_args()

    sys.path.insert(0, args.upstream)
    from raccoon_primitives import (  # type: ignore  # noqa: E402
        generate_keypair_from_seed,
        _drbg_seed_from_entropy,
        _PUBLIC_KEY_SIZE,
        _SIGNING_KEY_SIZE,
    )
    from nist_kat_drbg import NIST_KAT_DRBG  # type: ignore  # noqa: E402

    assert _PUBLIC_KEY_SIZE == PK_BYTES, _PUBLIC_KEY_SIZE
    assert _SIGNING_KEY_SIZE == SK_BYTES, _SIGNING_KEY_SIZE

    seed = bytes(range(32))
    drbg_seed = _drbg_seed_from_entropy(seed)
    drbg = NIST_KAT_DRBG(drbg_seed)
    drbg_key = drbg.random_bytes(32)
    pk, sk = generate_keypair_from_seed(seed)
    assert len(pk) == PK_BYTES and len(sk) == SK_BYTES

    parts = [
        "/* Auto-generated by contrib/raccoon_g/gen_keypair_vectors.py."
        " DO NOT EDIT. */",
        "/* Upstream: p-11/lattice-hd-wallets@"
        f"{UPSTREAM_COMMIT} (raccoon_primitives.generate_keypair_from_seed)."
        " */",
        "#ifndef LIBDOGECOIN_TEST_RACCOONG_KEYPAIR_VECTORS_H",
        "#define LIBDOGECOIN_TEST_RACCOONG_KEYPAIR_VECTORS_H",
        "",
        "#include <stdint.h>",
        "",
        f"#define RACCOONG_KEYPAIR_PK_BYTES {PK_BYTES}u",
        f"#define RACCOONG_KEYPAIR_SK_BYTES {SK_BYTES}u",
        "",
        emit_u8("raccoong_keypair_seed", seed),
        "",
        emit_u8("raccoong_keypair_drbg_seed", drbg_seed),
        "",
        emit_u8("raccoong_keypair_drbg_key", drbg_key),
        "",
        emit_u8("raccoong_keypair_pk", pk),
        "",
        emit_u8("raccoong_keypair_sk", sk),
        "",
        "#endif /* LIBDOGECOIN_TEST_RACCOONG_KEYPAIR_VECTORS_H */",
        "",
    ]
    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    with open(args.out, "w", encoding="utf-8") as f:
        f.write("\n".join(parts))
    print(f"wrote {args.out} ({len(pk) + len(sk) + len(seed) + 80} bytes of data)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
