#!/usr/bin/env python3
# Copyright (c) 2026 bluezr
# Copyright (c) 2026 The Dogecoin Foundation
# Distributed under the MIT software license, see the accompanying
# file COPYING or http://www.opensource.org/licenses/mit-license.php.
"""Regenerate the BIP157 filter-header checkpoint tables in src/cf_checkpoints.c.

The tables are trust anchors: a peer's filter header chain is accepted because
it agrees with them. They are also ~12,800 lines of hex that no reviewer can
check by reading, so the only thing that makes them reviewable is being able to
re-derive them and diff.

Requires a Dogecoin Core node with the basic filter index enabled:

    dogecoind -blockfilterindex=1

and, for testnet, -testnet. Wait for the index to finish before running: a
partially built index answers for the blocks it has and fails for the rest,
which produces a short table rather than an error.

    ./gen_cf_checkpoints.py --rpcuser u --rpcpassword p > mainnet.inc
    ./gen_cf_checkpoints.py --testnet --rpcuser u --rpcpassword p > testnet.inc

Spacing is per network and deliberate. getcfcheckpt is defined at multiples of
1000 and that is fixed by BIP157, but these are our own anchors: testnet is an
order of magnitude longer than mainnet, so it is stored every 10,000. The
consequence, which the generated header repeats, is that on testnet only every
tenth entry of a getcfcheckpt response has a local anchor to check against.
"""

import argparse
import datetime
import json
import sys
import urllib.request

MAINNET_SPACING = 1000
TESTNET_SPACING = 10000


def rpc(url, user, password, method, params=None):
    payload = json.dumps({
        "jsonrpc": "1.0", "id": "gen_cf_checkpoints",
        "method": method, "params": params or [],
    }).encode()
    req = urllib.request.Request(url, data=payload,
                                 headers={"Content-Type": "application/json"})
    if user is not None:
        import base64
        token = base64.b64encode(f"{user}:{password}".encode()).decode()
        req.add_header("Authorization", "Basic " + token)
    with urllib.request.urlopen(req, timeout=120) as resp:
        body = json.load(resp)
    if body.get("error"):
        raise RuntimeError(f"{method}: {body['error']}")
    return body["result"]


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--rpcurl", default=None)
    ap.add_argument("--rpcuser", default=None)
    ap.add_argument("--rpcpassword", default=None)
    ap.add_argument("--testnet", action="store_true")
    ap.add_argument("--spacing", type=int, default=None,
                    help="override the per-network spacing")
    ap.add_argument("--stop-height", type=int, default=None,
                    help="highest height to emit (default: chain tip, rounded down)")
    args = ap.parse_args()

    url = args.rpcurl or ("http://127.0.0.1:44555" if args.testnet
                          else "http://127.0.0.1:22555")
    spacing = args.spacing or (TESTNET_SPACING if args.testnet else MAINNET_SPACING)
    net = "testnet" if args.testnet else "mainnet"

    call = lambda m, p=None: rpc(url, args.rpcuser, args.rpcpassword, m, p)

    info = call("getblockchaininfo")
    netinfo = call("getnetworkinfo")
    tip = info["blocks"]
    chain = info["chain"]

    if (chain == "test") != args.testnet:
        sys.exit(f"node is on chain '{chain}' but --testnet is "
                 f"{'set' if args.testnet else 'not set'}")

    stop = args.stop_height if args.stop_height is not None else tip
    stop -= stop % spacing

    rows = []
    for height in range(spacing, stop + 1, spacing):
        blockhash = call("getblockhash", [height])
        try:
            result = call("getblockfilter", [blockhash, "basic"])
        except RuntimeError as exc:
            sys.exit(f"height {height}: {exc}\n"
                     f"is -blockfilterindex=1 set, and has the index finished?")
        rows.append((height, result["header"]))

    # Provenance goes in the generated file, because the reason to trust these
    # bytes is knowing what produced them and being able to run it again.
    stamp = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d %H:%M:%SZ")
    print(f"/* Generated by contrib/devtools/gen_cf_checkpoints.py -- do not edit by hand.")
    print(f" *")
    print(f" * network:      {net}")
    print(f" * spacing:      every {spacing} blocks")
    print(f" * entries:      {len(rows)} ({rows[0][0]}..{rows[-1][0]})" if rows else " * entries:      0")
    print(f" * node version: {netinfo.get('subversion', '?')} (protocol {netinfo.get('protocolversion', '?')})")
    print(f" * chain tip at generation: {tip}")
    print(f" * generated:    {stamp}")
    print(f" *")
    print(f" * Re-derive with the same node version and stop height to diff.")
    print(f" */")
    for height, header in rows:
        print(f'    {{{height}, "{header}"}},')


if __name__ == "__main__":
    main()
