libdogecoin: src/libevent/arc4random.c File Reference
arc4random.c File Reference
#include "evconfig-private.h"
#include <fcntl.h>
#include <unistd.h>
#include <sys/param.h>
#include <sys/time.h>
#include <limits.h>
#include <stdlib.h>
#include <string.h>
Data Structures
struct arc4_stream
Macros
#define ARC4RANDOM_EXPORT
#define ARC4RANDOM_UINT32 uint32_t
#define ADD_ENTROPY 32
#define BYTES_BEFORE_RESEED 1600000
#define TRY_SEED_URANDOM
Functions
static unsigned char arc4_getbyte (void)
static void arc4_init (void)
static void arc4_addrandom (const unsigned char *dat, int datlen)
static ssize_t read_all (int fd, unsigned char *buf, size_t count)
static int arc4_seed_urandom_helper_ (const char *fname)
static int arc4_seed_urandom (void)
static int arc4_seed (void)
static int arc4_stir (void)
static void arc4_stir_if_needed (void)
static unsigned int arc4_getword (void)
ARC4RANDOM_EXPORT int arc4random_stir (void)
ARC4RANDOM_EXPORT void arc4random_addrandom (const unsigned char *dat, int datlen)
ARC4RANDOM_EXPORT ARC4RANDOM_UINT32 arc4random (void)
ARC4RANDOM_EXPORT void arc4random_buf (void *buf_, size_t n)
ARC4RANDOM_EXPORT unsigned int arc4random_uniform (unsigned int upper_bound)
Variables
static int rs_initialized
static struct arc4_stream rs
static pid_t arc4_stir_pid
static int arc4_count
static char * arc4random_urandom_filename = NULL
Macro Definition Documentation
ADD_ENTROPY
#define ADD_ENTROPY 32
Definition at line 76 of file arc4random.c.
ARC4RANDOM_EXPORT
#define ARC4RANDOM_EXPORT
Definition at line 45 of file arc4random.c.
ARC4RANDOM_UINT32
#define ARC4RANDOM_UINT32 uint32_t
Definition at line 49 of file arc4random.c.
BYTES_BEFORE_RESEED
#define BYTES_BEFORE_RESEED 1600000
Definition at line 79 of file arc4random.c.
TRY_SEED_URANDOM
#define TRY_SEED_URANDOM
Definition at line 290 of file arc4random.c.
Function Documentation
arc4_addrandom()
static void arc4_addrandom (const unsigned char * dat, int datlen) inline static
Definition at line 111 of file arc4random.c.
{
    int     n;
    unsigned char si;
    rs.i--;
    for (n = 0; n < 256; n++) {
        rs.i = (rs.i + 1);
        si = rs.s[rs.i];
        rs.j = (rs.j + si + dat[n % datlen]);
        rs.s[rs.i] = rs.s[rs.j];
        rs.s[rs.j] = si;
    }
    rs.j = rs.i;
}
References arc4_stream::i, arc4_stream::j, rs, and arc4_stream::s.
Referenced by arc4_seed_urandom_helper_(), and arc4random_addrandom().
arc4_getbyte()
static unsigned char arc4_getbyte (void) inline static
Definition at line 416 of file arc4random.c.
{
    unsigned char si, sj;
    rs.i = (rs.i + 1);
    si = rs.s[rs.i];
    rs.j = (rs.j + si);
    sj = rs.s[rs.j];
    rs.s[rs.i] = sj;
    rs.s[rs.j] = si;
    return (rs.s[(si + sj) & 0xff]);
}
References arc4_stream::i, arc4_stream::j, rs, and arc4_stream::s.
Referenced by arc4_getword(), arc4_stir(), and arc4random_buf().
arc4_getword()
static unsigned int arc4_getword (void) inline static
Definition at line 430 of file arc4random.c.
{
    unsigned int val;
    val = arc4_getbyte() << 24;
    val |= arc4_getbyte() << 16;
    val |= arc4_getbyte() << 8;
    val |= arc4_getbyte();
    return val;
}
References arc4_getbyte().
Referenced by arc4random().
arc4_init()
static void arc4_init (void) inline static
Definition at line 100 of file arc4random.c.
{
    int     n;
    for (n = 0; n < 256; n++)
        rs.s[n] = n;
    rs.i = 0;
    rs.j = 0;
}
References arc4_stream::i, arc4_stream::j, rs, and arc4_stream::s.
Referenced by arc4_stir().
arc4_seed()
static int arc4_seed (void) static
Definition at line 333 of file arc4random.c.
{
    int ok = 0;
    /* We try every method that might work, and don't give up even if one
     * does seem to work.  There's no real harm in over-seeding, and if
     * one of these sources turns out to be broken, that would be bad. */
#ifdef TRY_SEED_WIN32
    if (0 == arc4_seed_win32())
        ok = 1;
#endif
#ifdef TRY_SEED_GETRANDOM
    if (0 == arc4_seed_getrandom())
        ok = 1;
#endif
#ifdef TRY_SEED_URANDOM
    if (0 == arc4_seed_urandom())
        ok = 1;
#endif
#ifdef TRY_SEED_PROC_SYS_KERNEL_RANDOM_UUID
    if (arc4random_urandom_filename == NULL &&
        0 == arc4_seed_proc_sys_kernel_random_uuid())
        ok = 1;
#endif
#ifdef TRY_SEED_SYSCTL_BSD
    if (0 == arc4_seed_sysctl_bsd())
        ok = 1;
#endif
    return ok ? 0 : -1;
}
References arc4_seed_urandom(), and arc4random_urandom_filename.
Referenced by arc4_stir().
arc4_seed_urandom()
static int arc4_seed_urandom (void) static
Definition at line 312 of file arc4random.c.
{
    /* This is adapted from Tor's crypto_seed_rng() */
    static const char *filenames[] = {
        "/dev/srandom", "/dev/urandom", "/dev/random", NULL
    };
    int i;
    if (arc4random_urandom_filename)
        return arc4_seed_urandom_helper_(arc4random_urandom_filename);
    for (i = 0; filenames[i]; ++i) {
        if (arc4_seed_urandom_helper_(filenames[i]) == 0) {
            return 0;
        }
    }
    return -1;
}
References arc4_seed_urandom_helper_(), arc4random_urandom_filename, and arc4_stream::i.
Referenced by arc4_seed().
arc4_seed_urandom_helper_()
static int arc4_seed_urandom_helper_ (const char * fname) static
Definition at line 293 of file arc4random.c.
{
    unsigned char buf[ADD_ENTROPY];
    int fd;
    size_t n;
    fd = evutil_open_closeonexec_(fname, O_RDONLY, 0);
    if (fd<0)
        return -1;
    n = read_all(fd, buf, sizeof(buf));
    close(fd);
    if (n != sizeof(buf))
        return -1;
    arc4_addrandom(buf, sizeof(buf));
    evutil_memclear_(buf, sizeof(buf));
    return 0;
}
References ADD_ENTROPY, arc4_addrandom(), evutil_memclear_(), evutil_open_closeonexec_(), and read_all().
Referenced by arc4_seed_urandom().
arc4_stir()
static int arc4_stir (void) static
Definition at line 364 of file arc4random.c.
{
    int     i;
    if (!rs_initialized) {
        arc4_init();
        rs_initialized = 1;
    }
    if (0 != arc4_seed())
        return -1;
    /*
     * Discard early keystream, as per recommendations in
     * "Weaknesses in the Key Scheduling Algorithm of RC4" by
     * Scott Fluhrer, Itsik Mantin, and Adi Shamir.
     * http://www.wisdom.weizmann.ac.il/~itsik/RC4/Papers/Rc4_ksa.ps
     *
     * Ilya Mironov's "(Not So) Random Shuffles of RC4" suggests that
     * we drop at least 2*256 bytes, with 12*256 as a conservative
     * value.
     *
     * RFC4345 says to drop 6*256.
     *
     * At least some versions of this code drop 4*256, in a mistaken
     * belief that "words" in the Fluhrer/Mantin/Shamir paper refers
     * to processor words.
     *
     * We add another sect to the cargo cult, and choose 12*256.
     */
    for (i = 0; i < 12*256; i++)
        (void)arc4_getbyte();
    arc4_count = BYTES_BEFORE_RESEED;
    return 0;
}
References arc4_count, arc4_getbyte(), arc4_init(), arc4_seed(), BYTES_BEFORE_RESEED, arc4_stream::i, and rs_initialized.
Referenced by arc4_stir_if_needed(), arc4random_addrandom(), arc4random_buf(), arc4random_stir(), and evutil_secure_rng_init().
arc4_stir_if_needed()
static void arc4_stir_if_needed (void) static
Definition at line 404 of file arc4random.c.
{
    pid_t pid = getpid();
    if (arc4_count <= 0 || !rs_initialized || arc4_stir_pid != pid)
    {
        arc4_stir_pid = pid;
        arc4_stir();
    }
}
References arc4_count, arc4_stir(), arc4_stir_pid, and rs_initialized.
Referenced by arc4random(), and arc4random_buf().
arc4random()
ARC4RANDOM_EXPORT ARC4RANDOM_UINT32 arc4random (void)
Definition at line 475 of file arc4random.c.
{
    ARC4RANDOM_UINT32 val;
    ARC4_LOCK_();
    arc4_count -= 4;
    arc4_stir_if_needed();
    val = arc4_getword();
    ARC4_UNLOCK_();
    return val;
}
References arc4_count, arc4_getword(), ARC4_LOCK_, arc4_stir_if_needed(), ARC4_UNLOCK_, and ARC4RANDOM_UINT32.
Referenced by arc4random_uniform().
arc4random_addrandom()
ARC4RANDOM_EXPORT void arc4random_addrandom (const unsigned char * dat, int datlen)
Definition at line 456 of file arc4random.c.
{
    int j;
    ARC4_LOCK_();
    if (!rs_initialized)
        arc4_stir();
    for (j = 0; j < datlen; j += 256) {
        /* arc4_addrandom() ignores all but the first 256 bytes of
         * its input.  We want to make sure to look at ALL the
         * data in 'dat', just in case the user is doing something
         * crazy like passing us all the files in /var/log. */
        arc4_addrandom(dat + j, datlen - j);
    }
    ARC4_UNLOCK_();
}
References arc4_addrandom(), ARC4_LOCK_, arc4_stir(), ARC4_UNLOCK_, arc4_stream::j, and rs_initialized.
Referenced by evutil_secure_rng_add_bytes().
arc4random_buf()
ARC4RANDOM_EXPORT void arc4random_buf (void * buf_, size_t n)
Definition at line 488 of file arc4random.c.
{
    unsigned char *buf = buf_;
    ARC4_LOCK_();
    arc4_stir_if_needed();
    while (n--) {
        if (--arc4_count <= 0)
            arc4_stir();
        buf[n] = arc4_getbyte();
    }
    ARC4_UNLOCK_();
}
References arc4_count, arc4_getbyte(), ARC4_LOCK_, arc4_stir(), arc4_stir_if_needed(), and ARC4_UNLOCK_.
Referenced by ev_arc4random_buf().
arc4random_stir()
ARC4RANDOM_EXPORT int arc4random_stir (void)
Definition at line 444 of file arc4random.c.
{
    int val;
    ARC4_LOCK_();
    val = arc4_stir();
    ARC4_UNLOCK_();
    return val;
}
References ARC4_LOCK_, arc4_stir(), and ARC4_UNLOCK_.
arc4random_uniform()
ARC4RANDOM_EXPORT unsigned int arc4random_uniform (unsigned int upper_bound)
Definition at line 513 of file arc4random.c.
{
    ARC4RANDOM_UINT32 r, min;
    if (upper_bound < 2)
        return 0;
#if (UINT_MAX > 0xffffffffUL)
    min = 0x100000000UL % upper_bound;
#else
    /* Calculate (2**32 % upper_bound) avoiding 64-bit math */
    if (upper_bound > 0x80000000)
        min = 1 + ~upper_bound;     /* 2**32 - upper_bound */
    else {
        /* (2**32 - (x * 2)) % x == 2**32 % x when x <= 2**31 */
        min = ((0xffffffff - (upper_bound * 2)) + 1) % upper_bound;
    }
#endif
    /*
     * This could theoretically loop forever but each retry has
     * p > 0.5 (worst case, usually far better) of selecting a
     * number inside the range we need, so it should rarely need
     * to re-roll.
     */
    for (;;) {
        r = arc4random();
        if (r >= min)
            break;
    }
    return r % upper_bound;
}
References arc4random(), and ARC4RANDOM_UINT32.
read_all()
static ssize_t read_all (int fd, unsigned char * buf, size_t count) static
Definition at line 129 of file arc4random.c.
{
    size_t numread = 0;
    ssize_t result;
    while (numread < count) {
        result = read(fd, buf+numread, count-numread);
        if (result<0)
            return -1;
        else if (result == 0)
            break;
        numread += result;
    }
    return (ssize_t)numread;
}
References count.
Referenced by arc4_seed_urandom_helper_().
Variable Documentation
arc4_count
int arc4_count static
Definition at line 95 of file arc4random.c.
Referenced by arc4_stir(), arc4_stir_if_needed(), arc4random(), and arc4random_buf().
arc4_stir_pid
pid_t arc4_stir_pid static
Definition at line 94 of file arc4random.c.
Referenced by arc4_stir_if_needed().
arc4random_urandom_filename
char* arc4random_urandom_filename = NULL static
Definition at line 291 of file arc4random.c.
Referenced by arc4_seed(), arc4_seed_urandom(), and evutil_secure_rng_set_urandom_device_file().
rs
struct arc4_stream rs static
Definition at line 93 of file arc4random.c.
Referenced by arc4_addrandom(), arc4_getbyte(), arc4_init(), secp256k1_ecdsa_sig_parse(), and test_ecmult_multi().
rs_initialized
int rs_initialized static
Definition at line 92 of file arc4random.c.
Referenced by arc4_stir(), arc4_stir_if_needed(), and arc4random_addrandom().