libdogecoin: src/secp256k1/src/bench_ecmult.c File Reference
bench_ecmult.c File Reference
#include <stdio.h>
#include "secp256k1.c"
#include "../include/secp256k1.h"
#include "util.h"
#include "hash_impl.h"
#include "field_impl.h"
#include "group_impl.h"
#include "scalar_impl.h"
#include "ecmult_impl.h"
#include "bench.h"
Data Structures
struct bench_data
Macros
#define POINTS 32768
Functions
void help (char **argv)
static void hash_into_offset (bench_data *data, size_t x)
static void bench_ecmult_teardown_helper (bench_data *data, size_t *seckey_offset, size_t *scalar_offset, size_t *scalar_gen_offset, int iters)
static void bench_ecmult_setup (void *arg)
static void bench_ecmult_gen (void *arg, int iters)
static void bench_ecmult_gen_teardown (void *arg, int iters)
static void bench_ecmult_const (void *arg, int iters)
static void bench_ecmult_const_teardown (void *arg, int iters)
static void bench_ecmult_1p (void *arg, int iters)
static void bench_ecmult_1p_teardown (void *arg, int iters)
static void bench_ecmult_0p_g (void *arg, int iters)
static void bench_ecmult_0p_g_teardown (void *arg, int iters)
static void bench_ecmult_1p_g (void *arg, int iters)
static void bench_ecmult_1p_g_teardown (void *arg, int iters)
static void run_ecmult_bench (bench_data *data, int iters)
static int bench_ecmult_multi_callback (secp256k1_scalar *sc, secp256k1_ge *ge, size_t idx, void *arg)
static void bench_ecmult_multi (void *arg, int iters)
static void bench_ecmult_multi_setup (void *arg)
static void bench_ecmult_multi_teardown (void *arg, int iters)
static void generate_scalar (uint32_t num, secp256k1_scalar *scalar)
static void run_ecmult_multi_bench (bench_data *data, size_t count, int includes_g, int num_iters)
int main (int argc, char **argv)
Macro Definition Documentation
POINTS
#define POINTS 32768
Definition at line 19 of file bench_ecmult.c.
Function Documentation
bench_ecmult_0p_g()
static void bench_ecmult_0p_g (void * arg, int iters) static
Definition at line 141 of file bench_ecmult.c.
{
    bench_data* data = (bench_data*)arg;
    secp256k1_scalar zero;
    int i;
    secp256k1_scalar_set_int(&zero, 0);
    for (i = 0; i < iters; ++i) {
        secp256k1_ecmult(&data->output[i], NULL, &zero, &data->scalars[(data->offset1+i) % POINTS]);
    }
}
References bench_data::offset1, bench_data::output, POINTS, bench_data::scalars, secp256k1_ecmult(), and secp256k1_scalar_set_int().
Referenced by run_ecmult_bench().
bench_ecmult_0p_g_teardown()
static void bench_ecmult_0p_g_teardown (void * arg, int iters) static
Definition at line 152 of file bench_ecmult.c.
{
    bench_data* data = (bench_data*)arg;
    bench_ecmult_teardown_helper(data, NULL, NULL, &data->offset1, iters);
}
References bench_ecmult_teardown_helper(), and bench_data::offset1.
Referenced by run_ecmult_bench().
bench_ecmult_1p()
static void bench_ecmult_1p (void * arg, int iters) static
Definition at line 127 of file bench_ecmult.c.
{
    bench_data* data = (bench_data*)arg;
    int i;
    for (i = 0; i < iters; ++i) {
        secp256k1_ecmult(&data->output[i], &data->pubkeys_gej[(data->offset1+i) % POINTS], &data->scalars[(data->offset2+i) % POINTS], NULL);
    }
}
References bench_data::offset1, bench_data::offset2, bench_data::output, POINTS, bench_data::pubkeys_gej, bench_data::scalars, and secp256k1_ecmult().
Referenced by run_ecmult_bench().
bench_ecmult_1p_g()
static void bench_ecmult_1p_g (void * arg, int iters) static
Definition at line 157 of file bench_ecmult.c.
{
    bench_data* data = (bench_data*)arg;
    int i;
    for (i = 0; i < iters/2; ++i) {
        secp256k1_ecmult(&data->output[i], &data->pubkeys_gej[(data->offset1+i) % POINTS], &data->scalars[(data->offset2+i) % POINTS], &data->scalars[(data->offset1+i) % POINTS]);
    }
}
References bench_data::offset1, bench_data::offset2, bench_data::output, POINTS, bench_data::pubkeys_gej, bench_data::scalars, and secp256k1_ecmult().
Referenced by run_ecmult_bench().
bench_ecmult_1p_g_teardown()
static void bench_ecmult_1p_g_teardown (void * arg, int iters) static
Definition at line 166 of file bench_ecmult.c.
{
    bench_data* data = (bench_data*)arg;
    bench_ecmult_teardown_helper(data, &data->offset1, &data->offset2, &data->offset1, iters/2);
}
References bench_ecmult_teardown_helper(), bench_data::offset1, and bench_data::offset2.
Referenced by run_ecmult_bench().
bench_ecmult_1p_teardown()
static void bench_ecmult_1p_teardown (void * arg, int iters) static
Definition at line 136 of file bench_ecmult.c.
{
    bench_data* data = (bench_data*)arg;
    bench_ecmult_teardown_helper(data, &data->offset1, &data->offset2, NULL, iters);
}
References bench_ecmult_teardown_helper(), bench_data::offset1, and bench_data::offset2.
Referenced by run_ecmult_bench().
bench_ecmult_const()
static void bench_ecmult_const (void * arg, int iters) static
Definition at line 113 of file bench_ecmult.c.
{
    bench_data* data = (bench_data*)arg;
    int i;
    for (i = 0; i < iters; ++i) {
        secp256k1_ecmult_const(&data->output[i], &data->pubkeys[(data->offset1+i) % POINTS], &data->scalars[(data->offset2+i) % POINTS], 256);
    }
}
References bench_data::offset1, bench_data::offset2, bench_data::output, POINTS, bench_data::pubkeys, bench_data::scalars, and secp256k1_ecmult_const().
Referenced by run_ecmult_bench().
bench_ecmult_const_teardown()
static void bench_ecmult_const_teardown (void * arg, int iters) static
Definition at line 122 of file bench_ecmult.c.
{
    bench_data* data = (bench_data*)arg;
    bench_ecmult_teardown_helper(data, &data->offset1, &data->offset2, NULL, iters);
}
References bench_ecmult_teardown_helper(), bench_data::offset1, and bench_data::offset2.
Referenced by run_ecmult_bench().
bench_ecmult_gen()
static void bench_ecmult_gen (void * arg, int iters) static
Definition at line 99 of file bench_ecmult.c.
{
    bench_data* data = (bench_data*)arg;
    int i;
    for (i = 0; i < iters; ++i) {
        secp256k1_ecmult_gen(&data->ctx->ecmult_gen_ctx, &data->output[i], &data->scalars[(data->offset1+i) % POINTS]);
    }
}
References bench_data::ctx, secp256k1_context_struct::ecmult_gen_ctx, bench_data::offset1, bench_data::output, POINTS, bench_data::scalars, and secp256k1_ecmult_gen().
Referenced by run_ecmult_bench().
bench_ecmult_gen_teardown()
static void bench_ecmult_gen_teardown (void * arg, int iters) static
Definition at line 108 of file bench_ecmult.c.
{
    bench_data* data = (bench_data*)arg;
    bench_ecmult_teardown_helper(data, NULL, NULL, &data->offset1, iters);
}
References bench_ecmult_teardown_helper(), and bench_data::offset1.
Referenced by run_ecmult_bench().
bench_ecmult_multi()
static void bench_ecmult_multi (void * arg, int iters) static
Definition at line 201 of file bench_ecmult.c.
{
    bench_data* data = (bench_data*)arg;
    int includes_g = data->includes_g;
    int iter;
    int count = data->count;
    iters = iters / data->count;
    for (iter = 0; iter < iters; ++iter) {
        data->ecmult_multi(&data->ctx->error_callback, data->scratch, &data->output[iter], data->includes_g ? &data->scalars[data->offset1] : NULL, bench_ecmult_multi_callback, arg, count - includes_g);
        data->offset1 = (data->offset1 + count) % POINTS;
        data->offset2 = (data->offset2 + count - 1) % POINTS;
    }
}
References bench_ecmult_multi_callback(), bench_data::count, count, bench_data::ctx, bench_data::ecmult_multi, secp256k1_context_struct::error_callback, bench_data::includes_g, bench_data::offset1, bench_data::offset2, bench_data::output, POINTS, bench_data::scalars, and bench_data::scratch.
Referenced by run_ecmult_multi_bench().
bench_ecmult_multi_callback()
static int bench_ecmult_multi_callback (secp256k1_scalar * sc, secp256k1_ge * ge, size_t idx, void * arg) static
Definition at line 188 of file bench_ecmult.c.
{
    bench_data* data = (bench_data*)arg;
    if (data->includes_g) ++idx;
    if (idx == 0) {
        *sc = data->scalars[data->offset1];
        *ge = secp256k1_ge_const_g;
    } else {
        *sc = data->scalars[(data->offset1 + idx) % POINTS];
        *ge = data->pubkeys[(data->offset2 + idx - 1) % POINTS];
    }
    return 1;
}
References bench_data::includes_g, bench_data::offset1, bench_data::offset2, POINTS, bench_data::pubkeys, bench_data::scalars, and secp256k1_ge_const_g.
Referenced by bench_ecmult_multi().
bench_ecmult_multi_setup()
static void bench_ecmult_multi_setup (void * arg) static
Definition at line 216 of file bench_ecmult.c.
{
    bench_data* data = (bench_data*)arg;
    hash_into_offset(data, data->count);
}
References bench_data::count, and hash_into_offset().
Referenced by run_ecmult_multi_bench().
bench_ecmult_multi_teardown()
static void bench_ecmult_multi_teardown (void * arg, int iters) static
Definition at line 221 of file bench_ecmult.c.
{
    bench_data* data = (bench_data*)arg;
    int iter;
    iters = iters / data->count;
    /* Verify the results in teardown, to avoid doing comparisons while benchmarking. */
    for (iter = 0; iter < iters; ++iter) {
        secp256k1_gej tmp;
        secp256k1_gej_add_var(&tmp, &data->output[iter], &data->expected_output[iter], NULL);
        CHECK(secp256k1_gej_is_infinity(&tmp));
    }
}
References CHECK, bench_data::count, bench_data::expected_output, bench_data::output, secp256k1_gej_add_var(), and secp256k1_gej_is_infinity().
Referenced by run_ecmult_multi_bench().
bench_ecmult_setup()
static void bench_ecmult_setup (void * arg) static
Definition at line 92 of file bench_ecmult.c.
{
    bench_data* data = (bench_data*)arg;
    /* Re-randomize offset to ensure that we're using different scalars and
     * group elements in each run. */
    hash_into_offset(data, data->offset1);
}
References hash_into_offset(), and bench_data::offset1.
Referenced by run_ecmult_bench().
bench_ecmult_teardown_helper()
static void bench_ecmult_teardown_helper (bench_data * data, size_t * seckey_offset, size_t * scalar_offset, size_t * scalar_gen_offset, int iters) static
Definition at line 68 of file bench_ecmult.c.
{
    int i;
    secp256k1_gej sum_output, tmp;
    secp256k1_scalar sum_scalars;
    secp256k1_gej_set_infinity(&sum_output);
    secp256k1_scalar_clear(&sum_scalars);
    for (i = 0; i < iters; ++i) {
        secp256k1_gej_add_var(&sum_output, &sum_output, &data->output[i], NULL);
        if (scalar_gen_offset != NULL) {
            secp256k1_scalar_add(&sum_scalars, &sum_scalars, &data->scalars[(*scalar_gen_offset+i) % POINTS]);
        }
        if (seckey_offset != NULL) {
            secp256k1_scalar s = data->seckeys[(*seckey_offset+i) % POINTS];
            secp256k1_scalar_mul(&s, &s, &data->scalars[(*scalar_offset+i) % POINTS]);
            secp256k1_scalar_add(&sum_scalars, &sum_scalars, &s);
        }
    }
    secp256k1_ecmult_gen(&data->ctx->ecmult_gen_ctx, &tmp, &sum_scalars);
    secp256k1_gej_neg(&tmp, &tmp);
    secp256k1_gej_add_var(&tmp, &tmp, &sum_output, NULL);
    CHECK(secp256k1_gej_is_infinity(&tmp));
}
References CHECK, bench_data::ctx, secp256k1_context_struct::ecmult_gen_ctx, bench_data::output, POINTS, bench_data::scalars, bench_data::seckeys, secp256k1_ecmult_gen(), secp256k1_gej_add_var(), secp256k1_gej_is_infinity(), secp256k1_gej_neg(), secp256k1_gej_set_infinity(), secp256k1_scalar_add(), secp256k1_scalar_clear(), and secp256k1_scalar_mul().
Referenced by bench_ecmult_0p_g_teardown(), bench_ecmult_1p_g_teardown(), bench_ecmult_1p_teardown(), bench_ecmult_const_teardown(), and bench_ecmult_gen_teardown().
generate_scalar()
static void generate_scalar (uint32_t num, secp256k1_scalar * scalar) static
Definition at line 233 of file bench_ecmult.c.
{
    secp256k1_sha256 sha256;
    unsigned char c[10] = {'e', 'c', 'm', 'u', 'l', 't', 0, 0, 0, 0};
    unsigned char buf[32];
    int overflow = 0;
    c[6] = num;
    c[7] = num >> 8;
    c[8] = num >> 16;
    c[9] = num >> 24;
    secp256k1_sha256_initialize(&sha256);
    secp256k1_sha256_write(&sha256, c, sizeof(c));
    secp256k1_sha256_finalize(&sha256, buf);
    secp256k1_scalar_set_b32(scalar, buf, &overflow);
    CHECK(!overflow);
}
References CHECK, secp256k1_scalar_set_b32(), secp256k1_sha256_finalize(), secp256k1_sha256_initialize(), and secp256k1_sha256_write().
Referenced by main().
hash_into_offset()
static void hash_into_offset (bench_data * data, size_t x) static
Definition at line 61 of file bench_ecmult.c.
{
    data->offset1 = (x * 0x537b7f6f + 0x8f66a481) % POINTS;
    data->offset2 = (x * 0x7f6f537b + 0x6a1a8f49) % POINTS;
}
References bench_data::offset1, bench_data::offset2, and POINTS.
Referenced by bench_ecmult_multi_setup(), bench_ecmult_setup(), main(), and run_ecmult_multi_bench().
help()
void help (char ** argv)
Definition at line 21 of file bench_ecmult.c.
                       {
    printf("Benchmark EC multiplication algorithms\n");
    printf("\n");
    printf("Usage: %s <help|pippenger_wnaf|strauss_wnaf|simple>\n", argv[0]);
    printf("The output shows the number of multiplied and summed points right after the\n");
    printf("function name. The letter 'g' indicates that one of the points is the generator.\n");
    printf("The benchmarks are divided by the number of points.\n");
    printf("\n");
    printf("default (ecmult_multi): picks pippenger_wnaf or strauss_wnaf depending on the\n");
    printf("                        batch size\n");
    printf("pippenger_wnaf:         for all batch sizes\n");
    printf("strauss_wnaf:           for all batch sizes\n");
    printf("simple:                 multiply and sum each point individually\n");
}
Referenced by main().
main()
int main (int argc, char ** argv)
Definition at line 281 of file bench_ecmult.c.
{
    bench_data data;
    int i, p;
    size_t scratch_size;
    int iters = get_iters(10000);
    data.ecmult_multi = secp256k1_ecmult_multi_var;
    if (argc > 1) {
        if(have_flag(argc, argv, "-h")
           || have_flag(argc, argv, "--help")
           || have_flag(argc, argv, "help")) {
            help(argv);
            return 0;
        } else if(have_flag(argc, argv, "pippenger_wnaf")) {
            printf("Using pippenger_wnaf:\n");
            data.ecmult_multi = secp256k1_ecmult_pippenger_batch_single;
        } else if(have_flag(argc, argv, "strauss_wnaf")) {
            printf("Using strauss_wnaf:\n");
            data.ecmult_multi = secp256k1_ecmult_strauss_batch_single;
        } else if(have_flag(argc, argv, "simple")) {
            printf("Using simple algorithm:\n");
        } else {
            fprintf(stderr, "%s: unrecognized argument '%s'.\n\n", argv[0], argv[1]);
            help(argv);
            return 1;
        }
    }
    data.ctx = secp256k1_context_create(SECP256K1_CONTEXT_SIGN | SECP256K1_CONTEXT_VERIFY);
    scratch_size = secp256k1_strauss_scratch_size(POINTS) + STRAUSS_SCRATCH_OBJECTS*16;
    if (!have_flag(argc, argv, "simple")) {
        data.scratch = secp256k1_scratch_space_create(data.ctx, scratch_size);
    } else {
        data.scratch = NULL;
    }
    /* Allocate stuff */
    data.scalars = malloc(sizeof(secp256k1_scalar) * POINTS);
    data.seckeys = malloc(sizeof(secp256k1_scalar) * POINTS);
    data.pubkeys = malloc(sizeof(secp256k1_ge) * POINTS);
    data.pubkeys_gej = malloc(sizeof(secp256k1_gej) * POINTS);
    data.expected_output = malloc(sizeof(secp256k1_gej) * (iters + 1));
    data.output = malloc(sizeof(secp256k1_gej) * (iters + 1));
    /* Generate a set of scalars, and private/public keypairs. */
    secp256k1_gej_set_ge(&data.pubkeys_gej[0], &secp256k1_ge_const_g);
    secp256k1_scalar_set_int(&data.seckeys[0], 1);
    for (i = 0; i < POINTS; ++i) {
        generate_scalar(i, &data.scalars[i]);
        if (i) {
            secp256k1_gej_double_var(&data.pubkeys_gej[i], &data.pubkeys_gej[i - 1], NULL);
            secp256k1_scalar_add(&data.seckeys[i], &data.seckeys[i - 1], &data.seckeys[i - 1]);
        }
    }
    secp256k1_ge_set_all_gej_var(data.pubkeys, data.pubkeys_gej, POINTS);
    print_output_table_header_row();
    /* Initialize offset1 and offset2 */
    hash_into_offset(&data, 0);
    run_ecmult_bench(&data, iters);
    for (i = 1; i <= 8; ++i) {
        run_ecmult_multi_bench(&data, i, 1, iters);
    }
    /* This is disabled with low count of iterations because the loop runs 77 times even with iters=1
    * and the higher it goes the longer the computation takes(more points)
    * So we don't run this benchmark with low iterations to prevent slow down */
     if (iters > 2) {
        for (p = 0; p <= 11; ++p) {
            for (i = 9; i <= 16; ++i) {
                run_ecmult_multi_bench(&data, i << p, 1, iters);
            }
        }
    }
    if (data.scratch != NULL) {
        secp256k1_scratch_space_destroy(data.ctx, data.scratch);
    }
    secp256k1_context_destroy(data.ctx);
    free(data.scalars);
    free(data.pubkeys);
    free(data.pubkeys_gej);
    free(data.seckeys);
    free(data.output);
    free(data.expected_output);
    return(0);
}
References bench_data::ctx, bench_data::ecmult_multi, bench_data::expected_output, generate_scalar(), get_iters(), hash_into_offset(), have_flag(), help(), bench_data::output, POINTS, print_output_table_header_row(), bench_data::pubkeys, bench_data::pubkeys_gej, run_ecmult_bench(), run_ecmult_multi_bench(), bench_data::scalars, bench_data::scratch, bench_data::seckeys, secp256k1_context_create(), secp256k1_context_destroy(), SECP256K1_CONTEXT_SIGN, SECP256K1_CONTEXT_VERIFY, secp256k1_ecmult_multi_var(), secp256k1_ecmult_pippenger_batch_single(), secp256k1_ecmult_strauss_batch_single(), secp256k1_ge_const_g, secp256k1_ge_set_all_gej_var(), secp256k1_gej_double_var(), secp256k1_gej_set_ge(), secp256k1_scalar_add(), secp256k1_scalar_set_int(), secp256k1_scratch_space_create(), secp256k1_scratch_space_destroy(), secp256k1_strauss_scratch_size(), and STRAUSS_SCRATCH_OBJECTS.
run_ecmult_bench()
static void run_ecmult_bench (bench_data * data, int iters) static
Definition at line 171 of file bench_ecmult.c.
{
    char str[32];
    sprintf(str, "ecmult_gen");
    run_benchmark(str, bench_ecmult_gen, bench_ecmult_setup, bench_ecmult_gen_teardown, data, 10, iters);
    sprintf(str, "ecmult_const");
    run_benchmark(str, bench_ecmult_const, bench_ecmult_setup, bench_ecmult_const_teardown, data, 10, iters);
    /* ecmult with non generator point */
    sprintf(str, "ecmult_1p");
    run_benchmark(str, bench_ecmult_1p, bench_ecmult_setup, bench_ecmult_1p_teardown, data, 10, iters);
    /* ecmult with generator point */
    sprintf(str, "ecmult_0p_g");
    run_benchmark(str, bench_ecmult_0p_g, bench_ecmult_setup, bench_ecmult_0p_g_teardown, data, 10, iters);
    /* ecmult with generator and non-generator point. The reported time is per point. */
    sprintf(str, "ecmult_1p_g");
    run_benchmark(str, bench_ecmult_1p_g, bench_ecmult_setup, bench_ecmult_1p_g_teardown, data, 10, 2*iters);
}
References bench_ecmult_0p_g(), bench_ecmult_0p_g_teardown(), bench_ecmult_1p(), bench_ecmult_1p_g(), bench_ecmult_1p_g_teardown(), bench_ecmult_1p_teardown(), bench_ecmult_const(), bench_ecmult_const_teardown(), bench_ecmult_gen(), bench_ecmult_gen_teardown(), bench_ecmult_setup(), and run_benchmark().
Referenced by main().
run_ecmult_multi_bench()
static void run_ecmult_multi_bench (bench_data * data, size_t count, int includes_g, int num_iters) static
Definition at line 249 of file bench_ecmult.c.
{
    char str[32];
    static const secp256k1_scalar zero = SECP256K1_SCALAR_CONST(0, 0, 0, 0, 0, 0, 0, 0);
    size_t iters = 1 + num_iters / count;
    size_t iter;
    data->count = count;
    data->includes_g = includes_g;
    /* Compute (the negation of) the expected results directly. */
    hash_into_offset(data, data->count);
    for (iter = 0; iter < iters; ++iter) {
        secp256k1_scalar tmp;
        secp256k1_scalar total = data->scalars[(data->offset1++) % POINTS];
        size_t i = 0;
        for (i = 0; i + 1 < count; ++i) {
            secp256k1_scalar_mul(&tmp, &data->seckeys[(data->offset2++) % POINTS], &data->scalars[(data->offset1++) % POINTS]);
            secp256k1_scalar_add(&total, &total, &tmp);
        }
        secp256k1_scalar_negate(&total, &total);
        secp256k1_ecmult(&data->expected_output[iter], NULL, &zero, &total);
    }
    /* Run the benchmark. */
    if (includes_g) {
        sprintf(str, "ecmult_multi_%ip_g", (int)count - 1);
    } else {
        sprintf(str, "ecmult_multi_%ip", (int)count);
    }
    run_benchmark(str, bench_ecmult_multi, bench_ecmult_multi_setup, bench_ecmult_multi_teardown, data, 10, count * iters);
}
References bench_ecmult_multi(), bench_ecmult_multi_setup(), bench_ecmult_multi_teardown(), bench_data::count, count, bench_data::expected_output, hash_into_offset(), bench_data::includes_g, bench_data::offset1, bench_data::offset2, POINTS, run_benchmark(), bench_data::scalars, bench_data::seckeys, secp256k1_ecmult(), secp256k1_scalar_add(), SECP256K1_SCALAR_CONST, secp256k1_scalar_mul(), and secp256k1_scalar_negate().
Referenced by main().