libdogecoin: src/bip32.c File Reference
bip32.c File Reference
#include <assert.h>
#include <inttypes.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <dogecoin/bip32.h>
#include <dogecoin/base58.h>
#include <dogecoin/ecc.h>
#include <dogecoin/hash.h>
#include <dogecoin/key.h>
#include <dogecoin/rmd160.h>
#include <dogecoin/sha2.h>
#include <dogecoin/mem.h>
#include <dogecoin/utils.h>
Functions
static void write_be (uint8_t *data, uint32_t x)
This function writes 4 big endian bytes.
static uint32_t read_be (const uint8_t *data)
This function reads 4 big endian bytes.
dogecoin_hdnode * dogecoin_hdnode_new ()
This function allocates memory for a new HD node object and returns a pointer to it.
dogecoin_hdnode * dogecoin_hdnode_copy (const dogecoin_hdnode *hdnode)
The function creates a new HD node object and copies all information from the old to the new.
void dogecoin_hdnode_free (dogecoin_hdnode *hdnode)
This function frees an HD node object in memory.
dogecoin_bool dogecoin_hdnode_from_seed (const uint8_t *seed, int seed_len, dogecoin_hdnode *out)
This function generates a private and public keypair along with chain_code for a hierarchical deterministic wallet. This is derived from a seed which usually consists of 12 random mnemonic words.
dogecoin_bool dogecoin_hdnode_public_ckd (dogecoin_hdnode *inout, uint32_t i)
This function derives a child key from the public key of the specified master HD node.
dogecoin_bool dogecoin_hdnode_private_ckd (dogecoin_hdnode *inout, uint32_t i)
This function derives a child key from the private key of the specified master HD node.
void dogecoin_hdnode_fill_public_key (dogecoin_hdnode *node)
This function derives a public key from a private key taken from the HD node provided.
static void dogecoin_hdnode_serialize (const dogecoin_hdnode *node, uint32_t version, char use_public, char *str, size_t strsize)
This function serializes the information inside an HD node and loads it into string variable str using WIF- encoding to represent the public or private key.
void dogecoin_hdnode_serialize_public (const dogecoin_hdnode *node, const dogecoin_chainparams *chain, char *str, size_t strsize)
This function serializes the HD node information into a string using the public key.
void dogecoin_hdnode_serialize_private (const dogecoin_hdnode *node, const dogecoin_chainparams *chain, char *str, size_t strsize)
This function serializes the HD node information into a string using the private key.
void dogecoin_hdnode_get_hash160 (const dogecoin_hdnode *node, uint160 hash160_out)
This function applies the sha256 and rmd160 hash functions to public key and loads variable hash160_out with result.
void dogecoin_hdnode_get_p2pkh_address (const dogecoin_hdnode *node, const dogecoin_chainparams *chain, char *str, size_t strsize)
This function produces a dogecoin pay-to- public-key-hash (p2pkh) address from the public key of the given node.
dogecoin_bool dogecoin_hdnode_get_pub_hex (const dogecoin_hdnode *node, char *str, size_t *strsize)
This function converts a public key from binary to hexadecimal string format.
dogecoin_bool dogecoin_hdnode_deserialize (const char *str, const dogecoin_chainparams *chain, dogecoin_hdnode *node)
This function takes a string buffer containing HD node data and loads an HD node object with that data. The function will copy either a private key or a public key, depending on the prefix of the given buffer.
dogecoin_bool dogecoin_hd_generate_key (dogecoin_hdnode *node, const char *keypath, const uint8_t *keymaster, const uint8_t *chaincode, dogecoin_bool usepubckd)
This function generates a child key from a given master key and loads it into an HD node.
dogecoin_bool dogecoin_hdnode_has_privkey (dogecoin_hdnode *node)
This function checks if the HD node has a private key.
Function Documentation
dogecoin_hd_generate_key()
dogecoin_bool dogecoin_hd_generate_key (dogecoin_hdnode * node, const char * keypath, const uint8_t * keymaster, const uint8_t * chaincode, dogecoin_bool usepubckd)
This function generates a child key from a given master key and loads it into an HD node.
derive dogecoin_hdnode from extended private or extended public key orkey
Parameters
node The HD node to be filled with the derived key.
keypath The derivation path of the desired key (e.g. "m/0h/0/0")
keymaster The master key to derive the child from.
chaincode A 32-byte value that is used to generate the child key.
usepubckd Whether to use public or private key derivation function.
Returns
Nothing.
Definition at line 471 of file bip32.c.
{
    static char delim[] = "/";
    static char prime[] = "phH\'";
    static char digits[] = "0123456789";
    uint64_t idx = 0;
    assert(strlens(keypath) < 1024);
    char *pch, *kp = dogecoin_malloc(strlens(keypath) + 1);
    char *saveptr; /* for strtok_r calls - fix for concurrent calls error*/
    if (!kp) {
        return false;
    }
    if (strlens(keypath) < strlens("m/")) {
        goto err;
    }
    dogecoin_mem_zero(kp, strlens(keypath) + 1);
    memcpy_safe(kp, keypath, strlens(keypath));
    if (kp[0] != 'm' || kp[1] != '/') {
        goto err;
    }
    node->depth = 0;
    node->child_num = 0;
    node->fingerprint = 0;
    memcpy_safe(node->chain_code, chaincode, DOGECOIN_BIP32_CHAINCODE_SIZE);
    if (usepubckd == true) {
        memcpy_safe(node->public_key, keymaster, DOGECOIN_ECKEY_COMPRESSED_LENGTH);
    } else {
        memcpy_safe(node->private_key, keymaster, DOGECOIN_ECKEY_PKEY_LENGTH);
        dogecoin_hdnode_fill_public_key(node);
    }
    pch = strtok_r(kp + 2, delim, &saveptr);
    while (pch != NULL) {
        size_t i = 0;
        int prm = 0;
        for (; i < strlens(pch); i++) {
            if (strchr(prime, pch[i])) {
                if ((i != strlens(pch) - 1) || usepubckd == true) {
                    goto err;
                }
                prm = 1;
            } else if (!strchr(digits, pch[i])) {
                goto err;
            }
        }
        idx = strtoull(pch, NULL, 10);
        if (idx > UINT32_MAX) {
            goto err;
        }
        if (prm) {
            if (dogecoin_hdnode_private_ckd_prime(node, idx) != true) {
                goto err;
            }
        } else {
            if ((usepubckd == true ? dogecoin_hdnode_public_ckd(node, idx) : dogecoin_hdnode_private_ckd(node, idx)) != true) {
                goto err;
            }
        }
        pch = strtok_r(NULL, delim, &saveptr);
    }
    dogecoin_free(kp);
    return true;
err:
    dogecoin_free(kp);
    return false;
}
References dogecoin_hdnode::chain_code, dogecoin_hdnode::child_num, dogecoin_hdnode::depth, DOGECOIN_BIP32_CHAINCODE_SIZE, DOGECOIN_ECKEY_COMPRESSED_LENGTH, DOGECOIN_ECKEY_PKEY_LENGTH, dogecoin_free(), dogecoin_hdnode_fill_public_key(), dogecoin_hdnode_private_ckd(), dogecoin_hdnode_private_ckd_prime, dogecoin_hdnode_public_ckd(), dogecoin_malloc(), dogecoin_mem_zero(), dogecoin_hdnode::fingerprint, memcpy_safe(), dogecoin_hdnode::private_key, dogecoin_hdnode::public_key, strlens, and strtok_r().
Referenced by derive_bip44_extended_private_key(), derive_bip44_extended_public_key(), getDerivedHDAddressByPath(), and hd_derive().
dogecoin_hdnode_copy()
dogecoin_hdnode * dogecoin_hdnode_copy (const dogecoin_hdnode * hdnode)
The function creates a new HD node object and copies all information from the old to the new.
Parameters
hdnode The HD node to be copied.
Returns
The pointer to the new node.
Definition at line 99 of file bip32.c.
{
    dogecoin_hdnode* newnode = dogecoin_hdnode_new();
    newnode->depth = hdnode->depth;
    newnode->fingerprint = hdnode->fingerprint;
    newnode->child_num = hdnode->child_num;
    memcpy_safe(newnode->chain_code, hdnode->chain_code, sizeof(hdnode->chain_code));
    memcpy_safe(newnode->private_key, hdnode->private_key, sizeof(hdnode->private_key));
    memcpy_safe(newnode->public_key, hdnode->public_key, sizeof(hdnode->public_key));
    return newnode;
}
References dogecoin_hdnode::chain_code, dogecoin_hdnode::child_num, dogecoin_hdnode::depth, dogecoin_hdnode_new(), dogecoin_hdnode::fingerprint, memcpy_safe(), dogecoin_hdnode::private_key, and dogecoin_hdnode::public_key.
dogecoin_hdnode_deserialize()
dogecoin_bool dogecoin_hdnode_deserialize (const char * str, const dogecoin_chainparams * chain, dogecoin_hdnode * node)
This function takes a string buffer containing HD node data and loads an HD node object with that data. The function will copy either a private key or a public key, depending on the prefix of the given buffer.
Parameters
str The buffer containing the node information.
chain The chain parameters to use.
node The HD node to be filled.
Returns
Nothing.
Definition at line 426 of file bip32.c.
{
    if (!str || !chain || !node) return false;
    const size_t ndlen = sizeof(uint8_t) * sizeof(dogecoin_hdnode);
    uint8_t* node_data = (uint8_t*)dogecoin_calloc(1, ndlen);
    dogecoin_mem_zero(node, sizeof(dogecoin_hdnode));
    if (!dogecoin_base58_decode_check(str, node_data, ndlen)) {
        dogecoin_free(node_data);
        return false;
    }
    uint32_t version = read_be(node_data);
    if (version == chain->b58prefix_bip32_pubkey) { // public node
        memcpy_safe(node->public_key, node_data + 45, DOGECOIN_ECKEY_COMPRESSED_LENGTH);
    } else if (version == chain->b58prefix_bip32_privkey) { // private node
        if (node_data[45]) {                                // invalid data
            dogecoin_free(node_data);
            return false;
        }
        memcpy_safe(node->private_key, node_data + 46, DOGECOIN_ECKEY_PKEY_LENGTH);
        dogecoin_hdnode_fill_public_key(node);
    } else {
        dogecoin_free(node_data);
        return false; // invalid version
    }
    node->depth = node_data[4];
    node->fingerprint = read_be(node_data + 5);
    node->child_num = read_be(node_data + 9);
    memcpy_safe(node->chain_code, node_data + 13, DOGECOIN_BIP32_CHAINCODE_SIZE);
    dogecoin_free(node_data);
    return true;
}
References dogecoin_chainparams_::b58prefix_bip32_privkey, dogecoin_chainparams_::b58prefix_bip32_pubkey, dogecoin_hdnode::chain_code, dogecoin_hdnode::child_num, dogecoin_hdnode::depth, dogecoin_base58_decode_check(), DOGECOIN_BIP32_CHAINCODE_SIZE, dogecoin_calloc(), DOGECOIN_ECKEY_COMPRESSED_LENGTH, DOGECOIN_ECKEY_PKEY_LENGTH, dogecoin_free(), dogecoin_hdnode_fill_public_key(), dogecoin_mem_zero(), dogecoin_hdnode::fingerprint, memcpy_safe(), dogecoin_hdnode::private_key, dogecoin_hdnode::public_key, and read_be().
Referenced by generateDerivedHDPubkey(), getDerivedHDAddressByPath(), hd_derive(), hd_print_node(), main(), and verifyHDMasterPubKeypair().
dogecoin_hdnode_fill_public_key()
void dogecoin_hdnode_fill_public_key (dogecoin_hdnode * node)
This function derives a public key from a private key taken from the HD node provided.
Parameters
node The HD node which contains the private key.
Returns
Nothing.
Definition at line 283 of file bip32.c.
{
    size_t outsize = DOGECOIN_ECKEY_COMPRESSED_LENGTH;
    dogecoin_ecc_get_pubkey(node->private_key, node->public_key, &outsize, true);
}
References dogecoin_ecc_get_pubkey(), DOGECOIN_ECKEY_COMPRESSED_LENGTH, dogecoin_hdnode::private_key, and dogecoin_hdnode::public_key.
Referenced by dogecoin_hd_generate_key(), dogecoin_hdnode_deserialize(), dogecoin_hdnode_from_seed(), and dogecoin_hdnode_private_ckd().
dogecoin_hdnode_free()
void dogecoin_hdnode_free (dogecoin_hdnode * hdnode)
This function frees an HD node object in memory.
Parameters
hdnode The HD node to be freed.
Returns
Nothing.
Definition at line 121 of file bip32.c.
{
    dogecoin_mem_zero(hdnode->chain_code, sizeof(hdnode->chain_code));
    dogecoin_mem_zero(hdnode->private_key, sizeof(hdnode->private_key));
    dogecoin_mem_zero(hdnode->public_key, sizeof(hdnode->public_key));
    dogecoin_free(hdnode);
}
References dogecoin_hdnode::chain_code, dogecoin_free(), dogecoin_mem_zero(), dogecoin_hdnode::private_key, and dogecoin_hdnode::public_key.
Referenced by generateDerivedHDPubkey().
dogecoin_hdnode_from_seed()
dogecoin_bool dogecoin_hdnode_from_seed (const uint8_t * seed, int seed_len, dogecoin_hdnode * out)
This function generates a private and public keypair along with chain_code for a hierarchical deterministic wallet. This is derived from a seed which usually consists of 12 random mnemonic words.
Parameters
seed The byte string containing the seed phrase.
seed_len The length of the phrase in characters.
out The master node which stores the generated data.
Returns
Nothing.
Definition at line 142 of file bip32.c.
{
    uint8_t I[DOGECOIN_ECKEY_PKEY_LENGTH + DOGECOIN_BIP32_CHAINCODE_SIZE];
    dogecoin_mem_zero(out, sizeof(dogecoin_hdnode));
    out->depth = 0;
    out->fingerprint = 0x00000000;
    out->child_num = 0;
    hmac_sha512((const uint8_t*)"Bitcoin seed", 12, seed, seed_len, I);
    memcpy_safe(out->private_key, I, DOGECOIN_ECKEY_PKEY_LENGTH);
    if (!dogecoin_ecc_verify_privatekey(out->private_key)) {
        dogecoin_mem_zero(I, sizeof(I));
        return false;
    }
    memcpy_safe(out->chain_code, I + DOGECOIN_ECKEY_PKEY_LENGTH, DOGECOIN_BIP32_CHAINCODE_SIZE);
    dogecoin_hdnode_fill_public_key(out);
    dogecoin_mem_zero(I, sizeof(I));
    return true;
}
References dogecoin_hdnode::chain_code, dogecoin_hdnode::child_num, dogecoin_hdnode::depth, DOGECOIN_BIP32_CHAINCODE_SIZE, dogecoin_ecc_verify_privatekey(), DOGECOIN_ECKEY_PKEY_LENGTH, dogecoin_hdnode_fill_public_key(), dogecoin_mem_zero(), dogecoin_hdnode::fingerprint, hmac_sha512(), memcpy_safe(), and dogecoin_hdnode::private_key.
Referenced by generateHDMasterPubKeypairFromMnemonic(), getDerivedHDAddressFromMnemonic(), hd_gen_master(), and verifyHDMasterPubKeypairFromMnemonic().
dogecoin_hdnode_get_hash160()
void dogecoin_hdnode_get_hash160 (const dogecoin_hdnode * node, uint160 hash160_out)
This function applies the sha256 and rmd160 hash functions to public key and loads variable hash160_out with result.
Parameters
node The node containing the public key and its chain code.
hash160_out The hash160 of the public key.
Returns
Nothing.
Definition at line 365 of file bip32.c.
{
    uint256 hashout;
    dogecoin_hash_sngl_sha256(node->public_key, DOGECOIN_ECKEY_COMPRESSED_LENGTH, hashout);
    rmd160(hashout, sizeof(hashout), hash160_out);
}
References DOGECOIN_ECKEY_COMPRESSED_LENGTH, dogecoin_hash_sngl_sha256(), dogecoin_hdnode::public_key, rmd160(), and uint256.
Referenced by dogecoin_hdnode_get_p2pkh_address().
dogecoin_hdnode_get_p2pkh_address()
void dogecoin_hdnode_get_p2pkh_address (const dogecoin_hdnode * node, const dogecoin_chainparams * chain, char * str, size_t strsize)
This function produces a dogecoin pay-to- public-key-hash (p2pkh) address from the public key of the given node.
Parameters
node The HD node containing the public key.
chain The chain parameters to use.
str The string containing the p2pkh address.
strsize The size of the string to be returned.
Returns
Nothing.
Definition at line 385 of file bip32.c.
{
    uint8_t hash160[sizeof(uint160) + 1];
    hash160[0] = chain->b58prefix_pubkey_address;
    dogecoin_hdnode_get_hash160(node, hash160 + 1);
    dogecoin_base58_encode_check(hash160, sizeof(hash160), str, strsize);
}
References dogecoin_chainparams_::b58prefix_pubkey_address, dogecoin_base58_encode_check(), and dogecoin_hdnode_get_hash160().
Referenced by generateDerivedHDPubkey(), generateHDMasterPubKeypairFromMnemonic(), getDerivedHDAddressFromMnemonic(), verifyHDMasterPubKeypair(), and verifyHDMasterPubKeypairFromMnemonic().
dogecoin_hdnode_get_pub_hex()
dogecoin_bool dogecoin_hdnode_get_pub_hex (const dogecoin_hdnode * node, char * str, size_t * strsize)
This function converts a public key from binary to hexadecimal string format.
Parameters
node The HD node containing the public key.
str The hexadecimal string to be returned.
strsize The size of the string to be returned.
Returns
Nothing.
Definition at line 404 of file bip32.c.
{
    dogecoin_pubkey pubkey;
    dogecoin_pubkey_init(&pubkey);
    memcpy_safe(&pubkey.pubkey, node->public_key, DOGECOIN_ECKEY_COMPRESSED_LENGTH);
    pubkey.compressed = true;
    return dogecoin_pubkey_get_hex(&pubkey, str, strsize);
}
References dogecoin_pubkey_::compressed, DOGECOIN_ECKEY_COMPRESSED_LENGTH, dogecoin_pubkey_get_hex(), dogecoin_pubkey_init(), memcpy_safe(), dogecoin_pubkey_::pubkey, and dogecoin_hdnode::public_key.
Referenced by hd_print_node().
dogecoin_hdnode_has_privkey()
dogecoin_bool dogecoin_hdnode_has_privkey (dogecoin_hdnode * node)
This function checks if the HD node has a private key.
checks if a node has the according private key (or if its a pubkey only node)
Parameters
node The HD node to check.
Returns
A boolean value, true if node has a private key.
Definition at line 554 of file bip32.c.
{
    int i;
    for (i = 0; i < DOGECOIN_ECKEY_PKEY_LENGTH; ++i) {
        if (node->private_key[i] != 0)
            return true;
    }
    return false;
}
References DOGECOIN_ECKEY_PKEY_LENGTH, and dogecoin_hdnode::private_key.
Referenced by getDerivedHDAddressByPath(), hd_derive(), and hd_print_node().
dogecoin_hdnode_new()
dogecoin_hdnode * dogecoin_hdnode_new ()
This function allocates memory for a new HD node object and returns a pointer to it.
Returns
The pointer to the new HD node object.
Definition at line 83 of file bip32.c.
{
    dogecoin_hdnode* hdnode;
    hdnode = dogecoin_calloc(1, sizeof(*hdnode));
    return hdnode;
}
References dogecoin_calloc().
Referenced by dogecoin_hdnode_copy(), and generateDerivedHDPubkey().
dogecoin_hdnode_private_ckd()
dogecoin_bool dogecoin_hdnode_private_ckd (dogecoin_hdnode * inout, uint32_t i)
This function derives a child key from the private key of the specified master HD node.
Parameters
inout The node to derive the child key from.
i The index of the child key, specified in derivation path.
Returns
Nothing.
Definition at line 223 of file bip32.c.
{
    uint8_t data[1 + DOGECOIN_ECKEY_PKEY_LENGTH + 4];
    uint8_t I[DOGECOIN_ECKEY_PKEY_LENGTH + DOGECOIN_BIP32_CHAINCODE_SIZE];
    uint8_t fingerprint[DOGECOIN_BIP32_CHAINCODE_SIZE];
    uint8_t p[DOGECOIN_ECKEY_PKEY_LENGTH], z[DOGECOIN_ECKEY_PKEY_LENGTH];
    if (i & 0x80000000) { // private derivation
        data[0] = 0;
        memcpy_safe(data + 1, inout->private_key, DOGECOIN_ECKEY_PKEY_LENGTH);
    } else { // public derivation
        memcpy_safe(data, inout->public_key, DOGECOIN_ECKEY_COMPRESSED_LENGTH);
    }
    write_be(data + DOGECOIN_ECKEY_COMPRESSED_LENGTH, i);
    sha256_raw(inout->public_key, DOGECOIN_ECKEY_COMPRESSED_LENGTH, fingerprint);
    rmd160(fingerprint, 32, fingerprint);
    inout->fingerprint = (fingerprint[0] << 24) + (fingerprint[1] << 16) +
                         (fingerprint[2] << 8) + fingerprint[3];
    dogecoin_mem_zero(fingerprint, sizeof(fingerprint));
    memcpy_safe(p, inout->private_key, DOGECOIN_ECKEY_PKEY_LENGTH);
    hmac_sha512(inout->chain_code, DOGECOIN_BIP32_CHAINCODE_SIZE, data, sizeof(data), I);
    memcpy_safe(inout->chain_code, I + DOGECOIN_ECKEY_PKEY_LENGTH, DOGECOIN_BIP32_CHAINCODE_SIZE);
    memcpy_safe(inout->private_key, I, DOGECOIN_ECKEY_PKEY_LENGTH);
    memcpy_safe(z, inout->private_key, DOGECOIN_ECKEY_PKEY_LENGTH);
    int failed = 0;
    if (!dogecoin_ecc_verify_privatekey(z)) {
        failed = 1;
    }
    memcpy_safe(inout->private_key, p, DOGECOIN_ECKEY_PKEY_LENGTH);
    if (!dogecoin_ecc_private_key_tweak_add(inout->private_key, z)) {
        failed = 1;
    }
    if (!failed) {
        inout->depth++;
        inout->child_num = i;
        dogecoin_hdnode_fill_public_key(inout);
    }
    dogecoin_mem_zero(data, sizeof(data));
    dogecoin_mem_zero(I, sizeof(I));
    dogecoin_mem_zero(z, sizeof(z));
    return true;
}
References dogecoin_hdnode::chain_code, dogecoin_hdnode::child_num, dogecoin_hdnode::depth, DOGECOIN_BIP32_CHAINCODE_SIZE, dogecoin_ecc_private_key_tweak_add(), dogecoin_ecc_verify_privatekey(), DOGECOIN_ECKEY_COMPRESSED_LENGTH, DOGECOIN_ECKEY_PKEY_LENGTH, dogecoin_hdnode_fill_public_key(), dogecoin_mem_zero(), dogecoin_hdnode::fingerprint, hmac_sha512(), memcpy_safe(), dogecoin_hdnode::private_key, dogecoin_hdnode::public_key, rmd160(), sha256_raw(), and write_be().
Referenced by dogecoin_hd_generate_key().
dogecoin_hdnode_public_ckd()
dogecoin_bool dogecoin_hdnode_public_ckd (dogecoin_hdnode * inout, uint32_t i)
This function derives a child key from the public key of the specified master HD node.
Parameters
inout The node to derive the child key from.
i The index of the child key, specified in derivation path.
Returns
Nothing.
Definition at line 173 of file bip32.c.
{
    uint8_t data[1 + 32 + 4];
    uint8_t I[32 + DOGECOIN_BIP32_CHAINCODE_SIZE];
    uint8_t fingerprint[32];
    if (i & 0x80000000) { // private derivation
        return false;
    } else { // public derivation
        memcpy_safe(data, inout->public_key, DOGECOIN_ECKEY_COMPRESSED_LENGTH);
    }
    write_be(data + DOGECOIN_ECKEY_COMPRESSED_LENGTH, i);
    sha256_raw(inout->public_key, DOGECOIN_ECKEY_COMPRESSED_LENGTH, fingerprint);
    rmd160(fingerprint, 32, fingerprint);
    inout->fingerprint = (fingerprint[0] << 24) + (fingerprint[1] << 16) + (fingerprint[2] << 8) + fingerprint[3];
    dogecoin_mem_zero(inout->private_key, 32);
    int failed = 0;
    hmac_sha512(inout->chain_code, 32, data, sizeof(data), I);
    memcpy_safe(inout->chain_code, I + 32, DOGECOIN_BIP32_CHAINCODE_SIZE);
    if (!dogecoin_ecc_public_key_tweak_add(inout->public_key, I))
        failed = false;
    if (!failed) {
        inout->depth++;
        inout->child_num = i;
    }
    // Wipe all stack data.
    dogecoin_mem_zero(data, sizeof(data));
    dogecoin_mem_zero(I, sizeof(I));
    dogecoin_mem_zero(fingerprint, sizeof(fingerprint));
    return failed ? false : true;
}
References dogecoin_hdnode::chain_code, dogecoin_hdnode::child_num, dogecoin_hdnode::depth, DOGECOIN_BIP32_CHAINCODE_SIZE, dogecoin_ecc_public_key_tweak_add(), DOGECOIN_ECKEY_COMPRESSED_LENGTH, dogecoin_mem_zero(), false, dogecoin_hdnode::fingerprint, hmac_sha512(), memcpy_safe(), dogecoin_hdnode::private_key, dogecoin_hdnode::public_key, rmd160(), sha256_raw(), and write_be().
Referenced by dogecoin_hd_generate_key().
dogecoin_hdnode_serialize()
static void dogecoin_hdnode_serialize (const dogecoin_hdnode * node, uint32_t version, char use_public, char * str, size_t strsize) static
This function serializes the information inside an HD node and loads it into string variable str using WIF- encoding to represent the public or private key.
Parameters
node The HD node containing the key.
version The version byte.
use_public Whether to use public or private key.
str The string to contain the encoded output.
strsize The size of the string that will be returned.
Returns
Nothing.
Definition at line 303 of file bip32.c.
{
    uint8_t node_data[78];
    write_be(node_data, version);
    node_data[4] = node->depth;
    write_be(node_data + 5, node->fingerprint);
    write_be(node_data + 9, node->child_num);
    memcpy_safe(node_data + 13, node->chain_code, DOGECOIN_BIP32_CHAINCODE_SIZE);
    if (use_public) {
        memcpy_safe(node_data + 45, node->public_key, DOGECOIN_ECKEY_COMPRESSED_LENGTH);
    } else {
        node_data[45] = 0;
        memcpy_safe(node_data + 46, node->private_key, DOGECOIN_ECKEY_PKEY_LENGTH);
    }
    dogecoin_base58_encode_check(node_data, 78, str, strsize);
}
References dogecoin_hdnode::chain_code, dogecoin_hdnode::child_num, dogecoin_hdnode::depth, dogecoin_base58_encode_check(), DOGECOIN_BIP32_CHAINCODE_SIZE, DOGECOIN_ECKEY_COMPRESSED_LENGTH, DOGECOIN_ECKEY_PKEY_LENGTH, dogecoin_hdnode::fingerprint, memcpy_safe(), dogecoin_hdnode::private_key, dogecoin_hdnode::public_key, and write_be().
Referenced by dogecoin_hdnode_serialize_private(), and dogecoin_hdnode_serialize_public().
dogecoin_hdnode_serialize_private()
void dogecoin_hdnode_serialize_private (const dogecoin_hdnode * node, const dogecoin_chainparams * chain, char * str, size_t strsize)
This function serializes the HD node information into a string using the private key.
Parameters
node The HD node containing the key.
chain The chain parameters to use.
str The string to contain the encoded private key.
strsize The size of the string to be returned.
Returns
Nothing.
Definition at line 349 of file bip32.c.
{
    dogecoin_hdnode_serialize(node, chain->b58prefix_bip32_privkey, 0, str, strsize);
}
References dogecoin_chainparams_::b58prefix_bip32_privkey, and dogecoin_hdnode_serialize().
Referenced by generateHDMasterPubKeypairFromMnemonic(), getDerivedHDAddressByPath(), hd_derive(), hd_gen_master(), main(), and verifyHDMasterPubKeypairFromMnemonic().
dogecoin_hdnode_serialize_public()
void dogecoin_hdnode_serialize_public (const dogecoin_hdnode * node, const dogecoin_chainparams * chain, char * str, size_t strsize)
This function serializes the HD node information into a string using the public key.
Parameters
node The HD node containing the key.
chain The preset chain parameters to use.
str The string to contain the encoded public key.
strsize The size of the string to be returned.
Returns
Nothing.
Definition at line 332 of file bip32.c.
{
    dogecoin_hdnode_serialize(node, chain->b58prefix_bip32_pubkey, 1, str, strsize);
}
References dogecoin_chainparams_::b58prefix_bip32_pubkey, and dogecoin_hdnode_serialize().
Referenced by getDerivedHDAddressByPath(), hd_derive(), hd_print_node(), and main().
read_be()
static uint32_t read_be (const uint8_t * data) static
This function reads 4 big endian bytes.
Parameters
data The bytes to be read.
Returns
The data buffer in int format.
Definition at line 68 of file bip32.c.
{
    return (((uint32_t)data[0]) << 24) |
           (((uint32_t)data[1]) << 16) |
           (((uint32_t)data[2]) << 8) |
           (((uint32_t)data[3]));
}
Referenced by dogecoin_hdnode_deserialize().
write_be()
static void write_be (uint8_t * data, uint32_t x) static
This function writes 4 big endian bytes.
Copyright (c) 2013-2014 Tomas Dzetkulic Copyright (c) 2013-2014 Pavol Rusnak Copyright (c) 2015 Douglas J. Bakkumk Copyright (c) 2022 bluezr Copyright (c) 2022 The Dogecoin Foundation
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
Parameters
data The buffer being written to.
x The 4 bytes to be written, bundled as int.
Returns
Nothing.
Definition at line 52 of file bip32.c.
{
    data[0] = x >> 24;
    data[1] = x >> 16;
    data[2] = x >> 8;
    data[3] = x;
}
Referenced by dogecoin_hdnode_private_ckd(), dogecoin_hdnode_public_ckd(), and dogecoin_hdnode_serialize().