libdogecoin: include/dogecoin/bip44.h File Reference
bip44.h File Reference
#include <dogecoin/bip32.h>
Macros
#define BIP44_PURPOSE "44" /* Purpose for key derivation according to BIP 44 */
#define BIP44_COIN_TYPE "3" /* Coin type for Dogecoin (3, SLIP 44) */
#define BIP44_COIN_TYPE_TEST "1" /* Coin type for Testnet (1, SLIP44) */
#define BIP44_CHANGE_EXTERNAL "0" /* Change level for external addresses */
#define BIP44_CHANGE_INTERNAL "1" /* Change level for internal addresses */
#define BIP44_CHANGE_LEVEL_SIZE 1 + 1 /* Change level size with a null terminator */
#define SLIP44_KEY_PATH "m/" BIP44_PURPOSE "'/" /* Key path to derive keys */
#define BIP44_MAX_ADDRESS 2^31 - 1 /* Maximum address is 2^31 - 1 */
#define BIP44_KEY_PATH_MAX_LENGTH 255 /* Maximum length of key path string */
#define BIP44_KEY_PATH_MAX_SIZE BIP44_KEY_PATH_MAX_LENGTH + 1 /* Key path size with a null terminator */
#define BIP44_ADDRESS_GAP_LIMIT 20 /* Maximum gap between unused addresses */
#define BIP44_FIRST_ACCOUNT_NODE 0 /* Index of the first account node */
#define BIP44_FIRST_ADDRESS_INDEX 0 /* Index of the first address */
Typedefs
typedef char CHANGE_LEVEL[BIP44_CHANGE_LEVEL_SIZE]
typedef char KEY_PATH[BIP44_KEY_PATH_MAX_SIZE]
Functions
int derive_bip44_extended_private_key (const dogecoin_hdnode *master_key, const uint32_t account, const uint32_t *address_index, const CHANGE_LEVEL change_level, const KEY_PATH path, const dogecoin_bool is_testnet, KEY_PATH keypath, dogecoin_hdnode *bip44_key)
This function derives the BIP 44 extended private key from a master private key.
int derive_bip44_extended_public_key (const dogecoin_hdnode *master_key, const uint32_t account, const uint32_t *address_index, const CHANGE_LEVEL change_level, const KEY_PATH path, const dogecoin_bool is_testnet, KEY_PATH keypath, dogecoin_hdnode *bip44_key)
This function derives the BIP 44 extended public key from a master public key.
Macro Definition Documentation
BIP44_ADDRESS_GAP_LIMIT
#define BIP44_ADDRESS_GAP_LIMIT 20 /* Maximum gap between unused addresses */
Definition at line 32 of file bip44.h.
BIP44_CHANGE_EXTERNAL
#define BIP44_CHANGE_EXTERNAL "0" /* Change level for external addresses */
Definition at line 23 of file bip44.h.
BIP44_CHANGE_INTERNAL
#define BIP44_CHANGE_INTERNAL "1" /* Change level for internal addresses */
Definition at line 24 of file bip44.h.
BIP44_CHANGE_LEVEL_SIZE
#define BIP44_CHANGE_LEVEL_SIZE 1 + 1 /* Change level size with a null terminator */
Definition at line 25 of file bip44.h.
BIP44_COIN_TYPE
#define BIP44_COIN_TYPE "3" /* Coin type for Dogecoin (3, SLIP 44) */
Definition at line 21 of file bip44.h.
BIP44_COIN_TYPE_TEST
#define BIP44_COIN_TYPE_TEST "1" /* Coin type for Testnet (1, SLIP44) */
Definition at line 22 of file bip44.h.
BIP44_FIRST_ACCOUNT_NODE
#define BIP44_FIRST_ACCOUNT_NODE 0 /* Index of the first account node */
Definition at line 33 of file bip44.h.
BIP44_FIRST_ADDRESS_INDEX
#define BIP44_FIRST_ADDRESS_INDEX 0 /* Index of the first address */
Definition at line 34 of file bip44.h.
BIP44_KEY_PATH_MAX_LENGTH
#define BIP44_KEY_PATH_MAX_LENGTH 255 /* Maximum length of key path string */
Definition at line 30 of file bip44.h.
BIP44_KEY_PATH_MAX_SIZE
#define BIP44_KEY_PATH_MAX_SIZE BIP44_KEY_PATH_MAX_LENGTH + 1 /* Key path size with a null terminator */
Definition at line 31 of file bip44.h.
BIP44_MAX_ADDRESS
#define BIP44_MAX_ADDRESS 2^31 - 1 /* Maximum address is 2^31 - 1 */
Definition at line 29 of file bip44.h.
BIP44_PURPOSE
#define BIP44_PURPOSE "44" /* Purpose for key derivation according to BIP 44 */
Definition at line 20 of file bip44.h.
SLIP44_KEY_PATH
#define SLIP44_KEY_PATH "m/" BIP44_PURPOSE "'/" /* Key path to derive keys */
Definition at line 26 of file bip44.h.
Typedef Documentation
CHANGE_LEVEL
typedef char CHANGE_LEVEL[BIP44_CHANGE_LEVEL_SIZE]
Definition at line 42 of file bip44.h.
KEY_PATH
typedef char KEY_PATH[BIP44_KEY_PATH_MAX_SIZE]
Definition at line 46 of file bip44.h.
Function Documentation
derive_bip44_extended_private_key()
int derive_bip44_extended_private_key (const dogecoin_hdnode * master_key, const uint32_t account, const uint32_t * address_index, const CHANGE_LEVEL change_level, const KEY_PATH custom_path, const dogecoin_bool is_testnet, KEY_PATH keypath, dogecoin_hdnode * bip44_key)
This function derives the BIP 44 extended private key from a master private key.
BIP 44 is a standard for deterministic wallet generation, which allows for the generation of a hierarchy of keys starting from a single seed. The extended private key is a specific key in this hierarchy that is derived using BIP 44 constants and the input parameters.
Parameters
master_key The master private key to derive from.
account The account number to use in the BIP 44 key derivation.
address_index The address index to use in the BIP 44 key derivation.
change_level The change level to use in the BIP 44 key derivation, either "external" or "internal".
custom_path A custom BIP 44 keypath to use for the derivation (optional).
keypath A string buffer to store the BIP 44 keypath used for the derivation.
bip44_key The BIP 44 extended private key to be generated.
Returns
0 if the key is derived successfully, -1 otherwise.
Definition at line 46 of file bip44.c.
{
    char addr_idx_str[UINT32_MAX_DIGITS + 1] = "";
    /* Validate input parameters */
    if (master_key == NULL || change_level == NULL || keypath == NULL || bip44_key == NULL) {
        fprintf(stderr, "ERROR: invalid input arguments\n");
        return -1;
    }
    /* Convert the address index to a string */
    if (address_index != NULL) {
        snprintf(addr_idx_str, UINT32_MAX_DIGITS + 1, "/%u", (uint32_t) *address_index);
    }
    /* Validate the change level input */
    if (strcmp(change_level, BIP44_CHANGE_EXTERNAL) != 0 && strcmp(change_level, BIP44_CHANGE_INTERNAL) != 0) {
        fprintf(stderr, "ERROR: invalid change level\n");
        return -1;
    }
    /* Check for custom key path */
    if (custom_path != NULL) {
        /* Construct the BIP 44 keypath using the custom path */
        snprintf(keypath, BIP44_KEY_PATH_MAX_LENGTH, "%s%s", custom_path, addr_idx_str);
    }
    else {
        /* Construct the BIP 44 keypath using the input parameters and BIP 44 constants */
        snprintf(keypath, BIP44_KEY_PATH_MAX_LENGTH, SLIP44_KEY_PATH "%s'/%u'/%s%s", is_testnet ? BIP44_COIN_TYPE_TEST : BIP44_COIN_TYPE , account, change_level, addr_idx_str);
    }
    /* Generate the BIP 44 extended private key using the master key and keypath */
    if (!dogecoin_hd_generate_key(bip44_key, keypath, master_key->private_key, master_key->chain_code, false)) {
        return -1;
    }
    debug_print("Account: %u\n", account);
    debug_print("Derivation path: %s\n", keypath);
    return 0;
}
References BIP44_CHANGE_EXTERNAL, BIP44_CHANGE_INTERNAL, BIP44_COIN_TYPE, BIP44_COIN_TYPE_TEST, BIP44_KEY_PATH_MAX_LENGTH, dogecoin_hdnode::chain_code, debug_print, dogecoin_hd_generate_key(), is_testnet, dogecoin_hdnode::private_key, SLIP44_KEY_PATH, and UINT32_MAX_DIGITS.
Referenced by getDerivedHDAddressFromMnemonic().
derive_bip44_extended_public_key()
int derive_bip44_extended_public_key (const dogecoin_hdnode * master_key, const uint32_t account, const uint32_t * address_index, const CHANGE_LEVEL change_level, const KEY_PATH custom_path, const dogecoin_bool is_testnet, KEY_PATH keypath, dogecoin_hdnode * bip44_key)
This function derives the BIP 44 extended public key from a master public key.
BIP 44 is a standard for deterministic wallet generation, which allows for the generation of a hierarchy of keys starting from a single seed. The extended public key is a specific key in this hierarchy that is derived using BIP 44 constants and the input parameters.
Parameters
master_key The master public key to derive from.
account The account number to use in the BIP 44 key derivation.
address_index The address index to use in the BIP 44 key derivation.
change_level The change level to use in the BIP 44 key derivation, either "external" or "internal".
custom_path A custom BIP 44 keypath to use for the derivation (optional).
keypath A string buffer to store the BIP 44 keypath used for the derivation.
bip44_key The BIP 44 extended public key to be generated.
Returns
0 if the key is derived successfully, -1 otherwise.
Definition at line 102 of file bip44.c.
{
    char addr_idx_str[UINT32_MAX_DIGITS + 1] = "";
    /* Validate input parameters */
    if (master_key == NULL || change_level == NULL || keypath == NULL || bip44_key == NULL) {
        fprintf(stderr, "ERROR: invalid input arguments\n");
        return -1;
    }
    /* Convert the address index to a string */
    if (address_index != NULL) {
        snprintf(addr_idx_str, UINT32_MAX_DIGITS + 1, "/%u", (uint32_t) *address_index);
    }
    /* Validate the change level input */
    if (strcmp(change_level, BIP44_CHANGE_EXTERNAL) != 0 && strcmp(change_level, BIP44_CHANGE_INTERNAL) != 0) {
        fprintf(stderr, "ERROR: invalid change level\n");
        return -1;
    }
    /* Check for custom key path */
    if (custom_path != NULL) {
        /* Construct the BIP 44 keypath using the custom path */
        snprintf(keypath, BIP44_KEY_PATH_MAX_LENGTH, "%s%s", custom_path, addr_idx_str);
    }
    else {
        /* Construct the BIP 44 keypath using the input parameters and BIP 44 constants */
        snprintf(keypath, BIP44_KEY_PATH_MAX_LENGTH, SLIP44_KEY_PATH "%s'/%u'/%s%s", is_testnet ? BIP44_COIN_TYPE_TEST : BIP44_COIN_TYPE , account, change_level, addr_idx_str);
    }
    /* Generate the BIP 44 extended public key using the master key and keypath */
    if (!dogecoin_hd_generate_key(bip44_key, keypath, master_key->public_key, master_key->chain_code, true)) {
        return -1;
    }
    debug_print("Account: %u\n", account);
    debug_print("Derivation path: %s\n", keypath);
    return 0;
}
References BIP44_CHANGE_EXTERNAL, BIP44_CHANGE_INTERNAL, BIP44_COIN_TYPE, BIP44_COIN_TYPE_TEST, BIP44_KEY_PATH_MAX_LENGTH, dogecoin_hdnode::chain_code, debug_print, dogecoin_hd_generate_key(), is_testnet, dogecoin_hdnode::public_key, SLIP44_KEY_PATH, and UINT32_MAX_DIGITS.