libdogecoin: src/block.c File Reference
block.c File Reference
#include <stddef.h>
#include <stdint.h>
#include <string.h>
#include <dogecoin/block.h>
#include <dogecoin/protocol.h>
#include <dogecoin/serialize.h>
#include <dogecoin/sha2.h>
#include <dogecoin/utils.h>
Functions
dogecoin_block_header * dogecoin_block_header_new ()
This function allocates a new dogecoin block header.
void dogecoin_block_header_free (dogecoin_block_header *header)
This function sets the memory for the specified block header to zero and then frees the memory.
int dogecoin_block_header_deserialize (dogecoin_block_header *header, struct const_buffer *buf)
This function takes a raw buffer and deserializes it into a dogecoin block header object.
void dogecoin_block_header_serialize (cstring *s, const dogecoin_block_header *header)
This function serializes a dogecoin block header into a cstring object.
void dogecoin_block_header_copy (dogecoin_block_header *dest, const dogecoin_block_header *src)
This function copies the contents of one header object into another.
dogecoin_bool dogecoin_block_header_hash (dogecoin_block_header *header, uint256 hash)
This function takes a block header and generates its SHA256 hash.
Function Documentation
dogecoin_block_header_copy()
void dogecoin_block_header_copy (dogecoin_block_header * dest, const dogecoin_block_header * src)
This function copies the contents of one header object into another.
Parameters
dest The pointer to the header object copy.
src The pointer to the source block header object.
Returns
Nothing.
Definition at line 122 of file block.c.
{
    dest->version = src->version;
    memcpy_safe(&dest->prev_block, &src->prev_block, sizeof(src->prev_block));
    memcpy_safe(&dest->merkle_root, &src->merkle_root, sizeof(src->merkle_root));
    dest->timestamp = src->timestamp;
    dest->bits = src->bits;
    dest->nonce = src->nonce;
}
References memcpy_safe().
dogecoin_block_header_deserialize()
int dogecoin_block_header_deserialize (dogecoin_block_header * header, struct const_buffer * buf)
This function takes a raw buffer and deserializes it into a dogecoin block header object.
Parameters
header The header object to be constructed.
buf The buffer to deserialize from.
Returns
1 if deserialization was successful, 0 otherwise.
Definition at line 79 of file block.c.
{
    if (!deser_s32(&header->version, buf))
        return false;
    if (!deser_u256(header->prev_block, buf))
        return false;
    if (!deser_u256(header->merkle_root, buf))
        return false;
    if (!deser_u32(&header->timestamp, buf))
        return false;
    if (!deser_u32(&header->bits, buf))
        return false;
    if (!deser_u32(&header->nonce, buf))
        return false;
    return true;
}
References deser_s32(), deser_u256(), and deser_u32().
dogecoin_block_header_free()
void dogecoin_block_header_free (dogecoin_block_header * header)
This function sets the memory for the specified block header to zero and then frees the memory.
Parameters
header The pointer to the block header to be freed.
Returns
Nothing.
Definition at line 59 of file block.c.
{
    if (!header) return;
    header->version = 1;
    dogecoin_mem_zero(&header->prev_block, DOGECOIN_HASH_LENGTH);
    dogecoin_mem_zero(&header->merkle_root, DOGECOIN_HASH_LENGTH);
    header->bits = 0;
    header->timestamp = 0;
    header->nonce = 0;
    dogecoin_free(header);
}
References dogecoin_free(), DOGECOIN_HASH_LENGTH, and dogecoin_mem_zero().
dogecoin_block_header_hash()
dogecoin_bool dogecoin_block_header_hash (dogecoin_block_header * header, uint256 hash)
This function takes a block header and generates its SHA256 hash.
Parameters
header The pointer to the block header to hash.
hash The SHA256 hash of the block header.
Returns
True.
Definition at line 140 of file block.c.
{
    cstring* s = cstr_new_sz(80);
    dogecoin_block_header_serialize(s, header);
    sha256_raw((const uint8_t*)s->str, s->len, hash);
    sha256_raw(hash, SHA256_DIGEST_LENGTH, hash);
    cstr_free(s, true);
    dogecoin_bool ret = true;
    return ret;
}
References cstr_free(), cstr_new_sz(), dogecoin_block_header_serialize(), cstring::len, SHA256_DIGEST_LENGTH, sha256_raw(), and cstring::str.
dogecoin_block_header_new()
dogecoin_block_header * dogecoin_block_header_new ()
This function allocates a new dogecoin block header.
Returns
A pointer to the new dogecoin block header object.
Definition at line 45 of file block.c.
{
    dogecoin_block_header* header;
    header = dogecoin_calloc(1, sizeof(*header));
    return header;
}
References dogecoin_calloc().
dogecoin_block_header_serialize()
void dogecoin_block_header_serialize (cstring * s, const dogecoin_block_header * header)
This function serializes a dogecoin block header into a cstring object.
Parameters
s The cstring to write the serialized header.
header The block header to be serialized.
Returns
Nothing.
Definition at line 104 of file block.c.
{
    ser_s32(s, header->version);
    ser_u256(s, header->prev_block);
    ser_u256(s, header->merkle_root);
    ser_u32(s, header->timestamp);
    ser_u32(s, header->bits);
    ser_u32(s, header->nonce);
}
References ser_s32(), ser_u256(), and ser_u32().
Referenced by dogecoin_block_header_hash().