libdogecoin: src/libevent/bufferevent_async.c File Reference
bufferevent_async.c File Reference
#include "event2/event-config.h"
#include "evconfig-private.h"
#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/queue.h>
#include "event2/util.h"
#include "event2/bufferevent.h"
#include "event2/buffer.h"
#include "event2/bufferevent_struct.h"
#include "event2/event.h"
#include "event-internal.h"
#include "log-internal.h"
#include "mm-internal.h"
#include "bufferevent-internal.h"
#include "util-internal.h"
#include "iocp-internal.h"
Data Structures
struct bufferevent_async
Macros
#define SO_UPDATE_CONNECT_CONTEXT 0x7010
Functions
static int be_async_enable (struct bufferevent *, short)
static int be_async_disable (struct bufferevent *, short)
static void be_async_destruct (struct bufferevent *)
static int be_async_flush (struct bufferevent *, short, enum bufferevent_flush_mode)
static int be_async_ctrl (struct bufferevent *, enum bufferevent_ctrl_op, union bufferevent_ctrl_data *)
static void be_async_run_eventcb (struct bufferevent *bev, short what, int options)
static void be_async_trigger_nolock (struct bufferevent *bev, short what, int options)
static int fatal_error (int err)
static struct bufferevent_async * upcast (struct bufferevent *bev)
static struct bufferevent_async * upcast_connect (struct event_overlapped *eo)
static struct bufferevent_async * upcast_read (struct event_overlapped *eo)
static struct bufferevent_async * upcast_write (struct event_overlapped *eo)
static void bev_async_del_write (struct bufferevent_async *beva)
static void bev_async_del_read (struct bufferevent_async *beva)
static void bev_async_add_write (struct bufferevent_async *beva)
static void bev_async_add_read (struct bufferevent_async *beva)
static void bev_async_consider_writing (struct bufferevent_async *beva)
static void bev_async_consider_reading (struct bufferevent_async *beva)
static void be_async_outbuf_callback (struct evbuffer *buf, const struct evbuffer_cb_info *cbinfo, void *arg)
static void be_async_inbuf_callback (struct evbuffer *buf, const struct evbuffer_cb_info *cbinfo, void *arg)
static void bev_async_set_wsa_error (struct bufferevent *bev, struct event_overlapped *eo)
static void connect_complete (struct event_overlapped *eo, ev_uintptr_t key, ev_ssize_t nbytes, int ok)
static void read_complete (struct event_overlapped *eo, ev_uintptr_t key, ev_ssize_t nbytes, int ok)
static void write_complete (struct event_overlapped *eo, ev_uintptr_t key, ev_ssize_t nbytes, int ok)
struct bufferevent * bufferevent_async_new_ (struct event_base *base, evutil_socket_t fd, int options)
void bufferevent_async_set_connected_ (struct bufferevent *bev)
int bufferevent_async_can_connect_ (struct bufferevent *bev)
int bufferevent_async_connect_ (struct bufferevent *bev, evutil_socket_t fd, const struct sockaddr *sa, int socklen)
Variables
const struct bufferevent_ops bufferevent_ops_async
Macro Definition Documentation
SO_UPDATE_CONNECT_CONTEXT
#define SO_UPDATE_CONNECT_CONTEXT 0x7010
Definition at line 70 of file bufferevent_async.c.
Function Documentation
be_async_ctrl()
static int be_async_ctrl (struct bufferevent * bev, enum bufferevent_ctrl_op op, union bufferevent_ctrl_data * data) static
Definition at line 665 of file bufferevent_async.c.
{
    switch (op) {
    case BEV_CTRL_GET_FD:
        data->fd = evbuffer_overlapped_get_fd_(bev->input);
        return 0;
    case BEV_CTRL_SET_FD: {
        struct bufferevent_async *bev_a = upcast(bev);
        struct event_iocp_port *iocp;
        if (data->fd == evbuffer_overlapped_get_fd_(bev->input))
            return 0;
        if (!(iocp = event_base_get_iocp_(bev->ev_base)))
            return -1;
        if (event_iocp_port_associate_(iocp, data->fd, 1) < 0) {
            if (fatal_error(GetLastError()))
                return -1;
        }
        evbuffer_overlapped_set_fd_(bev->input, data->fd);
        evbuffer_overlapped_set_fd_(bev->output, data->fd);
        bev_a->ok = data->fd >= 0;
        return 0;
    }
    case BEV_CTRL_CANCEL_ALL: {
        struct bufferevent_async *bev_a = upcast(bev);
        evutil_socket_t fd = evbuffer_overlapped_get_fd_(bev->input);
        if (fd != (evutil_socket_t)EVUTIL_INVALID_SOCKET &&
            (bev_a->bev.options & BEV_OPT_CLOSE_ON_FREE)) {
            closesocket(fd);
            evbuffer_overlapped_set_fd_(bev->input, EVUTIL_INVALID_SOCKET);
        }
        bev_a->ok = 0;
        return 0;
    }
    case BEV_CTRL_GET_UNDERLYING:
    default:
        return -1;
    }
}
References bufferevent_async::bev, BEV_CTRL_CANCEL_ALL, BEV_CTRL_GET_FD, BEV_CTRL_GET_UNDERLYING, BEV_CTRL_SET_FD, evbuffer_overlapped_get_fd_(), evbuffer_overlapped_set_fd_(), event_base_get_iocp_(), event_iocp_port_associate_(), fatal_error(), bufferevent_ctrl_data::fd, bufferevent_async::ok, bufferevent_private::options, and upcast().
be_async_destruct()
static void be_async_destruct (struct bufferevent * bev) static
Definition at line 393 of file bufferevent_async.c.
{
    struct bufferevent_async *bev_async = upcast(bev);
    struct bufferevent_private *bev_p = BEV_UPCAST(bev);
    evutil_socket_t fd;
    EVUTIL_ASSERT(!upcast(bev)->write_in_progress &&
            !upcast(bev)->read_in_progress);
    bev_async_del_read(bev_async);
    bev_async_del_write(bev_async);
    fd = evbuffer_overlapped_get_fd_(bev->input);
    if (fd != (evutil_socket_t)EVUTIL_INVALID_SOCKET &&
        (bev_p->options & BEV_OPT_CLOSE_ON_FREE)) {
        evutil_closesocket(fd);
        evbuffer_overlapped_set_fd_(bev->input, EVUTIL_INVALID_SOCKET);
    }
}
References bufferevent_private::bev, bufferevent_async::bev, bev_async_del_read(), bev_async_del_write(), BEV_UPCAST, evbuffer_overlapped_get_fd_(), evbuffer_overlapped_set_fd_(), EVUTIL_ASSERT, evutil_closesocket(), bufferevent_private::options, and upcast().
be_async_disable()
static int be_async_disable (struct bufferevent * bev, short what) static
Definition at line 373 of file bufferevent_async.c.
{
    struct bufferevent_async *bev_async = upcast(bev);
    /* XXXX If we disable reading or writing, we may want to consider
     * canceling any in-progress read or write operation, though it might
     * not work. */
    if (what & EV_READ) {
        BEV_DEL_GENERIC_READ_TIMEOUT(bev);
        bev_async_del_read(bev_async);
    }
    if (what & EV_WRITE) {
        BEV_DEL_GENERIC_WRITE_TIMEOUT(bev);
        bev_async_del_write(bev_async);
    }
    return 0;
}
References bufferevent_async::bev, bev_async_del_read(), bev_async_del_write(), BEV_DEL_GENERIC_READ_TIMEOUT, BEV_DEL_GENERIC_WRITE_TIMEOUT, and upcast().
be_async_enable()
static int be_async_enable (struct bufferevent * buf, short what) static
Definition at line 345 of file bufferevent_async.c.
{
    struct bufferevent_async *bev_async = upcast(buf);
    if (!bev_async->ok)
        return -1;
    if (bev_async->bev.connecting) {
        /* Don't launch anything during connection attempts. */
        return 0;
    }
    if (what & EV_READ)
        BEV_RESET_GENERIC_READ_TIMEOUT(buf);
    if (what & EV_WRITE)
        BEV_RESET_GENERIC_WRITE_TIMEOUT(buf);
    /* If we newly enable reading or writing, and we aren't reading or
       writing already, consider launching a new read or write. */
    if (what & EV_READ)
        bev_async_consider_reading(bev_async);
    if (what & EV_WRITE)
        bev_async_consider_writing(bev_async);
    return 0;
}
References bufferevent_async::bev, bev_async_consider_reading(), bev_async_consider_writing(), BEV_RESET_GENERIC_READ_TIMEOUT, BEV_RESET_GENERIC_WRITE_TIMEOUT, bufferevent_private::connecting, bufferevent_async::ok, and upcast().
Referenced by bufferevent_async_set_connected_().
be_async_flush()
static int be_async_flush (struct bufferevent * bev, short what, enum bufferevent_flush_mode mode) static
Definition at line 426 of file bufferevent_async.c.
{
    return 0;
}
be_async_inbuf_callback()
static void be_async_inbuf_callback (struct evbuffer * buf, const struct evbuffer_cb_info * cbinfo, void * arg) static
Definition at line 326 of file bufferevent_async.c.
{
    struct bufferevent *bev = arg;
    struct bufferevent_async *bev_async = upcast(bev);
    /* If we drained data from the inbuf and were not reading before,
     * we may want to read now */
    bufferevent_incref_and_lock_(bev);
    if (cbinfo->n_deleted)
        bev_async_consider_reading(bev_async);
    bufferevent_decref_and_unlock_(bev);
}
References bufferevent_async::bev, bev_async_consider_reading(), bufferevent_decref_and_unlock_(), bufferevent_incref_and_lock_(), and upcast().
Referenced by bufferevent_async_new_().
be_async_outbuf_callback()
static void be_async_outbuf_callback (struct evbuffer * buf, const struct evbuffer_cb_info * cbinfo, void * arg) static
Definition at line 307 of file bufferevent_async.c.
{
    struct bufferevent *bev = arg;
    struct bufferevent_async *bev_async = upcast(bev);
    /* If we added data to the outbuf and were not writing before,
     * we may want to write now. */
    bufferevent_incref_and_lock_(bev);
    if (cbinfo->n_added)
        bev_async_consider_writing(bev_async);
    bufferevent_decref_and_unlock_(bev);
}
References bufferevent_async::bev, bev_async_consider_writing(), bufferevent_decref_and_unlock_(), bufferevent_incref_and_lock_(), and upcast().
Referenced by bufferevent_async_new_().
be_async_run_eventcb()
static void be_async_run_eventcb (struct bufferevent * bev, short what, int options) inline static
Definition at line 105 of file bufferevent_async.c.
{ bufferevent_run_eventcb_(bev, what, options|BEV_TRIG_DEFER_CALLBACKS); }
References bufferevent_run_eventcb_().
Referenced by bev_async_consider_reading(), bev_async_consider_writing(), connect_complete(), read_complete(), and write_complete().
be_async_trigger_nolock()
static void be_async_trigger_nolock (struct bufferevent * bev, short what, int options) inline static
Definition at line 109 of file bufferevent_async.c.
{ bufferevent_trigger_nolock_(bev, what, options|BEV_TRIG_DEFER_CALLBACKS); }
References bufferevent_trigger_nolock_().
Referenced by read_complete(), and write_complete().
bev_async_add_read()
static void bev_async_add_read (struct bufferevent_async * beva) static
Definition at line 196 of file bufferevent_async.c.
{
    struct bufferevent *bev = &beva->bev.bev;
    if (!beva->read_added) {
        beva->read_added = 1;
        event_base_add_virtual_(bev->ev_base);
    }
}
References bufferevent_private::bev, bufferevent_async::bev, event_base_add_virtual_(), and bufferevent_async::read_added.
Referenced by bev_async_consider_reading().
bev_async_add_write()
static void bev_async_add_write (struct bufferevent_async * beva) static
Definition at line 185 of file bufferevent_async.c.
{
    struct bufferevent *bev = &beva->bev.bev;
    if (!beva->write_added) {
        beva->write_added = 1;
        event_base_add_virtual_(bev->ev_base);
    }
}
References bufferevent_private::bev, bufferevent_async::bev, event_base_add_virtual_(), and bufferevent_async::write_added.
Referenced by bev_async_consider_writing().
bev_async_consider_reading()
static void bev_async_consider_reading (struct bufferevent_async * beva) static
Definition at line 251 of file bufferevent_async.c.
{
    size_t cur_size;
    size_t read_high;
    size_t at_most;
    int limit;
    struct bufferevent *bev = &beva->bev.bev;
    /* Don't read if there is a read in progress, or we do not
     * want to read. */
    if (beva->read_in_progress || beva->bev.connecting)
        return;
    if (!beva->ok || !(bev->enabled&EV_READ)) {
        bev_async_del_read(beva);
        return;
    }
    /* Don't read if we're full */
    cur_size = evbuffer_get_length(bev->input);
    read_high = bev->wm_read.high;
    if (read_high) {
        if (cur_size >= read_high) {
            bev_async_del_read(beva);
            return;
        }
        at_most = read_high - cur_size;
    } else {
        at_most = 16384; /* FIXME totally magic. */
    }
    /* XXXX This over-commits. */
    /* XXXX see also not above on cast on bufferevent_get_write_max_() */
    limit = (int)bufferevent_get_read_max_(&beva->bev);
    if (at_most >= (size_t)limit && limit >= 0)
        at_most = limit;
    if (beva->bev.read_suspended) {
        bev_async_del_read(beva);
        return;
    }
    bufferevent_incref_(bev);
    if (evbuffer_launch_read_(bev->input, at_most, &beva->read_overlapped)) {
        beva->ok = 0;
        be_async_run_eventcb(bev, BEV_EVENT_ERROR, 0);
        bufferevent_decref_(bev);
    } else {
        beva->read_in_progress = at_most;
        bufferevent_decrement_read_buckets_(&beva->bev, at_most);
        bev_async_add_read(beva);
    }
    return;
}
References be_async_run_eventcb(), bufferevent_private::bev, bufferevent_async::bev, bev_async_add_read(), bev_async_del_read(), bufferevent_decref_, bufferevent_decrement_read_buckets_(), bufferevent_get_read_max_(), bufferevent_incref_, bufferevent_private::connecting, evbuffer_get_length(), evbuffer_launch_read_(), bufferevent_async::ok, bufferevent_async::read_in_progress, bufferevent_async::read_overlapped, and bufferevent_private::read_suspended.
Referenced by be_async_enable(), be_async_inbuf_callback(), and read_complete().
bev_async_consider_writing()
static void bev_async_consider_writing (struct bufferevent_async * beva) static
Definition at line 207 of file bufferevent_async.c.
{
    size_t at_most;
    int limit;
    struct bufferevent *bev = &beva->bev.bev;
    /* Don't write if there's a write in progress, or we do not
     * want to write, or when there's nothing left to write. */
    if (beva->write_in_progress || beva->bev.connecting)
        return;
    if (!beva->ok || !(bev->enabled&EV_WRITE) ||
        !evbuffer_get_length(bev->output)) {
        bev_async_del_write(beva);
        return;
    }
    at_most = evbuffer_get_length(bev->output);
    /* This is safe so long as bufferevent_get_write_max never returns
     * more than INT_MAX.  That's true for now. XXXX */
    limit = (int)bufferevent_get_write_max_(&beva->bev);
    if (at_most >= (size_t)limit && limit >= 0)
        at_most = limit;
    if (beva->bev.write_suspended) {
        bev_async_del_write(beva);
        return;
    }
    /*  XXXX doesn't respect low-water mark very well. */
    bufferevent_incref_(bev);
    if (evbuffer_launch_write_(bev->output, at_most,
        &beva->write_overlapped)) {
        bufferevent_decref_(bev);
        beva->ok = 0;
        be_async_run_eventcb(bev, BEV_EVENT_ERROR, 0);
    } else {
        beva->write_in_progress = at_most;
        bufferevent_decrement_write_buckets_(&beva->bev, at_most);
        bev_async_add_write(beva);
    }
}
References be_async_run_eventcb(), bufferevent_private::bev, bufferevent_async::bev, bev_async_add_write(), bev_async_del_write(), bufferevent_decref_, bufferevent_decrement_write_buckets_(), bufferevent_get_write_max_(), bufferevent_incref_, bufferevent_private::connecting, evbuffer_get_length(), evbuffer_launch_write_(), bufferevent_async::ok, bufferevent_async::write_in_progress, bufferevent_async::write_overlapped, and bufferevent_private::write_suspended.
Referenced by be_async_enable(), be_async_outbuf_callback(), and write_complete().
bev_async_del_read()
static void bev_async_del_read (struct bufferevent_async * beva) static
Definition at line 174 of file bufferevent_async.c.
{
    struct bufferevent *bev = &beva->bev.bev;
    if (beva->read_added) {
        beva->read_added = 0;
        event_base_del_virtual_(bev->ev_base);
    }
}
References bufferevent_private::bev, bufferevent_async::bev, event_base_del_virtual_(), and bufferevent_async::read_added.
Referenced by be_async_destruct(), be_async_disable(), and bev_async_consider_reading().
bev_async_del_write()
static void bev_async_del_write (struct bufferevent_async * beva) static
Definition at line 163 of file bufferevent_async.c.
{
    struct bufferevent *bev = &beva->bev.bev;
    if (beva->write_added) {
        beva->write_added = 0;
        event_base_del_virtual_(bev->ev_base);
    }
}
References bufferevent_private::bev, bufferevent_async::bev, event_base_del_virtual_(), and bufferevent_async::write_added.
Referenced by be_async_destruct(), be_async_disable(), and bev_async_consider_writing().
bev_async_set_wsa_error()
static void bev_async_set_wsa_error (struct bufferevent * bev, struct event_overlapped * eo) static
Definition at line 416 of file bufferevent_async.c.
{
    DWORD bytes, flags;
    evutil_socket_t fd;
    fd = evbuffer_overlapped_get_fd_(bev->input);
    WSAGetOverlappedResult(fd, &eo->overlapped, &bytes, FALSE, &flags);
}
References bufferevent_private::bev, and evbuffer_overlapped_get_fd_().
Referenced by connect_complete(), read_complete(), and write_complete().
bufferevent_async_can_connect_()
int bufferevent_async_can_connect_ (struct bufferevent * bev)
Definition at line 605 of file bufferevent_async.c.
{
    const struct win32_extension_fns *ext =
        event_get_win32_extension_fns_();
    if (BEV_IS_ASYNC(bev) &&
        event_base_get_iocp_(bev->ev_base) &&
        ext && ext->ConnectEx)
        return 1;
    return 0;
}
References BEV_IS_ASYNC, event_base_get_iocp_(), and event_get_win32_extension_fns_().
Referenced by bufferevent_socket_connect().
bufferevent_async_connect_()
int bufferevent_async_connect_ (struct bufferevent * bev, evutil_socket_t fd, const struct sockaddr * sa, int socklen)
Definition at line 619 of file bufferevent_async.c.
{
    BOOL rc;
    struct bufferevent_async *bev_async = upcast(bev);
    struct sockaddr_storage ss;
    const struct win32_extension_fns *ext =
        event_get_win32_extension_fns_();
    EVUTIL_ASSERT(ext && ext->ConnectEx && fd >= 0 && sa != NULL);
    /* ConnectEx() requires that the socket be bound to an address
     * with bind() before using, otherwise it will fail. We attempt
     * to issue a bind() here, taking into account that the error
     * code is set to WSAEINVAL when the socket is already bound. */
    memset(&ss, 0, sizeof(ss));
    if (sa->sa_family == AF_INET) {
        struct sockaddr_in *sin = (struct sockaddr_in *)&ss;
        sin->sin_family = AF_INET;
        sin->sin_addr.s_addr = INADDR_ANY;
    } else if (sa->sa_family == AF_INET6) {
        struct sockaddr_in6 *sin6 = (struct sockaddr_in6 *)&ss;
        sin6->sin6_family = AF_INET6;
        sin6->sin6_addr = in6addr_any;
    } else {
        /* Well, the user will have to bind() */
        return -1;
    }
    if (bind(fd, (struct sockaddr *)&ss, sizeof(ss)) < 0 &&
        WSAGetLastError() != WSAEINVAL)
        return -1;
    event_base_add_virtual_(bev->ev_base);
    bufferevent_incref_(bev);
    rc = ext->ConnectEx(fd, sa, socklen, NULL, 0, NULL,
                &bev_async->connect_overlapped.overlapped);
    if (rc || WSAGetLastError() == ERROR_IO_PENDING)
        return 0;
    event_base_del_virtual_(bev->ev_base);
    bufferevent_decref_(bev);
    return -1;
}
References AF_INET6, bufferevent_async::bev, bufferevent_decref_, bufferevent_incref_, bufferevent_async::connect_overlapped, event_base_add_virtual_(), event_base_del_virtual_(), event_get_win32_extension_fns_(), EVUTIL_ASSERT, sockaddr_in6::sin6_addr, sockaddr_in6::sin6_family, and upcast().
Referenced by bufferevent_socket_connect().
bufferevent_async_new_()
struct bufferevent * bufferevent_async_new_ (struct event_base * base, evutil_socket_t fd, int options)
Definition at line 543 of file bufferevent_async.c.
{
    struct bufferevent_async *bev_a;
    struct bufferevent *bev;
    struct event_iocp_port *iocp;
    options |= BEV_OPT_THREADSAFE;
    if (!(iocp = event_base_get_iocp_(base)))
        return NULL;
    if (fd >= 0 && event_iocp_port_associate_(iocp, fd, 1)<0) {
        if (fatal_error(GetLastError()))
            return NULL;
    }
    if (!(bev_a = mm_calloc(1, sizeof(struct bufferevent_async))))
        return NULL;
    bev = &bev_a->bev.bev;
    if (!(bev->input = evbuffer_overlapped_new_(fd))) {
        mm_free(bev_a);
        return NULL;
    }
    if (!(bev->output = evbuffer_overlapped_new_(fd))) {
        evbuffer_free(bev->input);
        mm_free(bev_a);
        return NULL;
    }
    if (bufferevent_init_common_(&bev_a->bev, base, &bufferevent_ops_async,
        options)<0)
        goto err;
    evbuffer_add_cb(bev->input, be_async_inbuf_callback, bev);
    evbuffer_add_cb(bev->output, be_async_outbuf_callback, bev);
    event_overlapped_init_(&bev_a->connect_overlapped, connect_complete);
    event_overlapped_init_(&bev_a->read_overlapped, read_complete);
    event_overlapped_init_(&bev_a->write_overlapped, write_complete);
    bufferevent_init_generic_timeout_cbs_(bev);
    bev_a->ok = fd >= 0;
    return bev;
err:
    bufferevent_free(&bev_a->bev.bev);
    return NULL;
}
References be_async_inbuf_callback(), be_async_outbuf_callback(), bufferevent_private::bev, bufferevent_async::bev, bufferevent_free(), bufferevent_init_common_(), bufferevent_init_generic_timeout_cbs_(), bufferevent_ops_async, connect_complete(), bufferevent_async::connect_overlapped, evbuffer_add_cb(), evbuffer_free(), evbuffer_overlapped_new_(), event_base_get_iocp_(), event_iocp_port_associate_(), event_overlapped_init_(), fatal_error(), mm_calloc, mm_free, bufferevent_async::ok, read_complete(), bufferevent_async::read_overlapped, write_complete(), and bufferevent_async::write_overlapped.
Referenced by bufferevent_socket_new().
bufferevent_async_set_connected_()
void bufferevent_async_set_connected_ (struct bufferevent * bev)
Definition at line 596 of file bufferevent_async.c.
{
    struct bufferevent_async *bev_async = upcast(bev);
    bev_async->ok = 1;
    /* Now's a good time to consider reading/writing */
    be_async_enable(bev, bev->enabled);
}
References be_async_enable(), bufferevent_async::bev, bufferevent_async::ok, and upcast().
Referenced by bufferevent_writecb(), and connect_complete().
connect_complete()
static void connect_complete (struct event_overlapped * eo, ev_uintptr_t key, ev_ssize_t nbytes, int ok) static
Definition at line 433 of file bufferevent_async.c.
{
    struct bufferevent_async *bev_a = upcast_connect(eo);
    struct bufferevent *bev = &bev_a->bev.bev;
    evutil_socket_t sock;
    BEV_LOCK(bev);
    EVUTIL_ASSERT(bev_a->bev.connecting);
    bev_a->bev.connecting = 0;
    sock = evbuffer_overlapped_get_fd_(bev_a->bev.bev.input);
    /* XXXX Handle error? */
    setsockopt(sock, SOL_SOCKET, SO_UPDATE_CONNECT_CONTEXT, NULL, 0);
    if (ok)
        bufferevent_async_set_connected_(bev);
    else
        bev_async_set_wsa_error(bev, eo);
    be_async_run_eventcb(bev, ok ? BEV_EVENT_CONNECTED : BEV_EVENT_ERROR, 0);
    event_base_del_virtual_(bev->ev_base);
    bufferevent_decref_and_unlock_(bev);
}
References be_async_run_eventcb(), bufferevent_private::bev, bufferevent_async::bev, bev_async_set_wsa_error(), BEV_LOCK, bufferevent_async_set_connected_(), bufferevent_decref_and_unlock_(), bufferevent_private::connecting, evbuffer_overlapped_get_fd_(), event_base_del_virtual_(), EVUTIL_ASSERT, SO_UPDATE_CONNECT_CONTEXT, and upcast_connect().
Referenced by bufferevent_async_new_().
fatal_error()
static int fatal_error (int err) inline static
Definition at line 113 of file bufferevent_async.c.
{
    switch (err) {
        /* We may have already associated this fd with a port.
         * Let's hope it's this port, and that the error code
         * for doing this neer changes. */
        case ERROR_INVALID_PARAMETER:
            return 0;
    }
    return 1;
}
Referenced by be_async_ctrl(), and bufferevent_async_new_().
read_complete()
static void read_complete (struct event_overlapped * eo, ev_uintptr_t key, ev_ssize_t nbytes, int ok) static
Definition at line 461 of file bufferevent_async.c.
{
    struct bufferevent_async *bev_a = upcast_read(eo);
    struct bufferevent *bev = &bev_a->bev.bev;
    short what = BEV_EVENT_READING;
    ev_ssize_t amount_unread;
    BEV_LOCK(bev);
    EVUTIL_ASSERT(bev_a->read_in_progress);
    amount_unread = bev_a->read_in_progress - nbytes;
    evbuffer_commit_read_(bev->input, nbytes);
    bev_a->read_in_progress = 0;
    if (amount_unread)
        bufferevent_decrement_read_buckets_(&bev_a->bev, -amount_unread);
    if (!ok)
        bev_async_set_wsa_error(bev, eo);
    if (bev_a->ok) {
        if (ok && nbytes) {
            BEV_RESET_GENERIC_READ_TIMEOUT(bev);
            be_async_trigger_nolock(bev, EV_READ, 0);
            bev_async_consider_reading(bev_a);
        } else if (!ok) {
            what |= BEV_EVENT_ERROR;
            bev_a->ok = 0;
            be_async_run_eventcb(bev, what, 0);
        } else if (!nbytes) {
            what |= BEV_EVENT_EOF;
            bev_a->ok = 0;
            be_async_run_eventcb(bev, what, 0);
        }
    }
    bufferevent_decref_and_unlock_(bev);
}
References be_async_run_eventcb(), be_async_trigger_nolock(), bufferevent_private::bev, bufferevent_async::bev, bev_async_consider_reading(), bev_async_set_wsa_error(), BEV_LOCK, BEV_RESET_GENERIC_READ_TIMEOUT, bufferevent_decref_and_unlock_(), bufferevent_decrement_read_buckets_(), evbuffer_commit_read_(), EVUTIL_ASSERT, bufferevent_async::ok, bufferevent_async::read_in_progress, and upcast_read().
Referenced by bufferevent_async_new_().
upcast()
static struct bufferevent_async * upcast (struct bufferevent * bev) inline static
Definition at line 126 of file bufferevent_async.c.
{
    struct bufferevent_async *bev_a;
    if (!BEV_IS_ASYNC(bev))
        return NULL;
    bev_a = EVUTIL_UPCAST(bev, struct bufferevent_async, bev.bev);
    return bev_a;
}
References bufferevent_private::bev, bufferevent_async::bev, BEV_IS_ASYNC, and EVUTIL_UPCAST.
Referenced by be_async_ctrl(), be_async_destruct(), be_async_disable(), be_async_enable(), be_async_inbuf_callback(), be_async_outbuf_callback(), bufferevent_async_connect_(), and bufferevent_async_set_connected_().
upcast_connect()
static struct bufferevent_async * upcast_connect (struct event_overlapped * eo) inline static
Definition at line 136 of file bufferevent_async.c.
{
    struct bufferevent_async *bev_a;
    bev_a = EVUTIL_UPCAST(eo, struct bufferevent_async, connect_overlapped);
    EVUTIL_ASSERT(BEV_IS_ASYNC(&bev_a->bev.bev));
    return bev_a;
}
References bufferevent_private::bev, bufferevent_async::bev, BEV_IS_ASYNC, bufferevent_async::connect_overlapped, EVUTIL_ASSERT, and EVUTIL_UPCAST.
Referenced by connect_complete().
upcast_read()
static struct bufferevent_async * upcast_read (struct event_overlapped * eo) inline static
Definition at line 145 of file bufferevent_async.c.
{
    struct bufferevent_async *bev_a;
    bev_a = EVUTIL_UPCAST(eo, struct bufferevent_async, read_overlapped);
    EVUTIL_ASSERT(BEV_IS_ASYNC(&bev_a->bev.bev));
    return bev_a;
}
References bufferevent_private::bev, bufferevent_async::bev, BEV_IS_ASYNC, EVUTIL_ASSERT, EVUTIL_UPCAST, and bufferevent_async::read_overlapped.
Referenced by read_complete().
upcast_write()
static struct bufferevent_async * upcast_write (struct event_overlapped * eo) inline static
Definition at line 154 of file bufferevent_async.c.
{
    struct bufferevent_async *bev_a;
    bev_a = EVUTIL_UPCAST(eo, struct bufferevent_async, write_overlapped);
    EVUTIL_ASSERT(BEV_IS_ASYNC(&bev_a->bev.bev));
    return bev_a;
}
References bufferevent_private::bev, bufferevent_async::bev, BEV_IS_ASYNC, EVUTIL_ASSERT, EVUTIL_UPCAST, and bufferevent_async::write_overlapped.
Referenced by write_complete().
write_complete()
static void write_complete (struct event_overlapped * eo, ev_uintptr_t key, ev_ssize_t nbytes, int ok) static
Definition at line 500 of file bufferevent_async.c.
{
    struct bufferevent_async *bev_a = upcast_write(eo);
    struct bufferevent *bev = &bev_a->bev.bev;
    short what = BEV_EVENT_WRITING;
    ev_ssize_t amount_unwritten;
    BEV_LOCK(bev);
    EVUTIL_ASSERT(bev_a->write_in_progress);
    amount_unwritten = bev_a->write_in_progress - nbytes;
    evbuffer_commit_write_(bev->output, nbytes);
    bev_a->write_in_progress = 0;
    if (amount_unwritten)
        bufferevent_decrement_write_buckets_(&bev_a->bev,
                                             -amount_unwritten);
    if (!ok)
        bev_async_set_wsa_error(bev, eo);
    if (bev_a->ok) {
        if (ok && nbytes) {
            BEV_RESET_GENERIC_WRITE_TIMEOUT(bev);
            be_async_trigger_nolock(bev, EV_WRITE, 0);
            bev_async_consider_writing(bev_a);
        } else if (!ok) {
            what |= BEV_EVENT_ERROR;
            bev_a->ok = 0;
            be_async_run_eventcb(bev, what, 0);
        } else if (!nbytes) {
            what |= BEV_EVENT_EOF;
            bev_a->ok = 0;
            be_async_run_eventcb(bev, what, 0);
        }
    }
    bufferevent_decref_and_unlock_(bev);
}
References be_async_run_eventcb(), be_async_trigger_nolock(), bufferevent_private::bev, bufferevent_async::bev, bev_async_consider_writing(), bev_async_set_wsa_error(), BEV_LOCK, BEV_RESET_GENERIC_WRITE_TIMEOUT, bufferevent_decref_and_unlock_(), bufferevent_decrement_write_buckets_(), evbuffer_commit_write_(), EVUTIL_ASSERT, bufferevent_async::ok, upcast_write(), and bufferevent_async::write_in_progress.
Referenced by bufferevent_async_new_().
Variable Documentation
bufferevent_ops_async
const struct bufferevent_ops bufferevent_ops_async
Initial value:
= {
    "socket_async",
    evutil_offsetof(struct bufferevent_async, bev.bev),
    be_async_enable,
    be_async_disable,
    NULL,
    be_async_destruct,
    bufferevent_generic_adj_timeouts_,
    be_async_flush,
    be_async_ctrl,
}
Definition at line 92 of file bufferevent_async.c.
Referenced by bufferevent_async_new_().