libdogecoin: src/libevent/bufferevent.c File Reference
bufferevent.c File Reference
#include "event2/event-config.h"
#include "evconfig-private.h"
#include <sys/types.h>
#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "event2/util.h"
#include "event2/buffer.h"
#include "event2/buffer_compat.h"
#include "event2/bufferevent.h"
#include "event2/bufferevent_struct.h"
#include "event2/bufferevent_compat.h"
#include "event2/event.h"
#include "event-internal.h"
#include "log-internal.h"
#include "mm-internal.h"
#include "bufferevent-internal.h"
#include "evbuffer-internal.h"
#include "util-internal.h"
Macros
#define UNLOCKED(stmt) do { BEV_UNLOCK(bufev); stmt; BEV_LOCK(bufev); } while(0)
#define SCHEDULE_DEFERRED(bevp)
#define BEV_TRIG_ALL_OPTS
#define MAX_CBS 16
Functions
static void bufferevent_cancel_all_ (struct bufferevent *bev)
static void bufferevent_finalize_cb_ (struct event_callback *evcb, void *arg_)
void bufferevent_suspend_read_ (struct bufferevent *bufev, bufferevent_suspend_flags what)
void bufferevent_unsuspend_read_ (struct bufferevent *bufev, bufferevent_suspend_flags what)
void bufferevent_suspend_write_ (struct bufferevent *bufev, bufferevent_suspend_flags what)
void bufferevent_unsuspend_write_ (struct bufferevent *bufev, bufferevent_suspend_flags what)
static void bufferevent_inbuf_wm_check (struct bufferevent *bev)
static void bufferevent_inbuf_wm_cb (struct evbuffer *buf, const struct evbuffer_cb_info *cbinfo, void *arg)
static void bufferevent_run_deferred_callbacks_locked (struct event_callback *cb, void *arg)
static void bufferevent_run_deferred_callbacks_unlocked (struct event_callback *cb, void *arg)
void bufferevent_run_readcb_ (struct bufferevent *bufev, int options)
void bufferevent_run_writecb_ (struct bufferevent *bufev, int options)
void bufferevent_trigger (struct bufferevent *bufev, short iotype, int options)
void bufferevent_run_eventcb_ (struct bufferevent *bufev, short what, int options)
void bufferevent_trigger_event (struct bufferevent *bufev, short what, int options)
int bufferevent_init_common_ (struct bufferevent_private *bufev_private, struct event_base *base, const struct bufferevent_ops *ops, enum bufferevent_options options)
void bufferevent_setcb (struct bufferevent *bufev, bufferevent_data_cb readcb, bufferevent_data_cb writecb, bufferevent_event_cb eventcb, void *cbarg)
void bufferevent_getcb (struct bufferevent *bufev, bufferevent_data_cb *readcb_ptr, bufferevent_data_cb *writecb_ptr, bufferevent_event_cb *eventcb_ptr, void **cbarg_ptr)
struct evbuffer * bufferevent_get_input (struct bufferevent *bufev)
struct evbuffer * bufferevent_get_output (struct bufferevent *bufev)
struct event_base * bufferevent_get_base (struct bufferevent *bufev)
int bufferevent_get_priority (const struct bufferevent *bufev)
int bufferevent_write (struct bufferevent *bufev, const void *data, size_t size)
int bufferevent_write_buffer (struct bufferevent *bufev, struct evbuffer *buf)
size_t bufferevent_read (struct bufferevent *bufev, void *data, size_t size)
int bufferevent_read_buffer (struct bufferevent *bufev, struct evbuffer *buf)
int bufferevent_enable (struct bufferevent *bufev, short event)
int bufferevent_set_timeouts (struct bufferevent *bufev, const struct timeval *tv_read, const struct timeval *tv_write)
void bufferevent_settimeout (struct bufferevent *bufev, int timeout_read, int timeout_write)
int bufferevent_disable_hard_ (struct bufferevent *bufev, short event)
int bufferevent_disable (struct bufferevent *bufev, short event)
void bufferevent_setwatermark (struct bufferevent *bufev, short events, size_t lowmark, size_t highmark)
int bufferevent_getwatermark (struct bufferevent *bufev, short events, size_t *lowmark, size_t *highmark)
int bufferevent_flush (struct bufferevent *bufev, short iotype, enum bufferevent_flush_mode mode)
void bufferevent_incref_and_lock_ (struct bufferevent *bufev)
int bufferevent_decref_and_unlock_ (struct bufferevent *bufev)
int bufferevent_decref (struct bufferevent *bufev)
void bufferevent_free (struct bufferevent *bufev)
void bufferevent_incref (struct bufferevent *bufev)
int bufferevent_enable_locking_ (struct bufferevent *bufev, void *lock)
int bufferevent_setfd (struct bufferevent *bev, evutil_socket_t fd)
evutil_socket_t bufferevent_getfd (struct bufferevent *bev)
enum bufferevent_options bufferevent_get_options_ (struct bufferevent *bev)
short bufferevent_get_enabled (struct bufferevent *bufev)
struct bufferevent * bufferevent_get_underlying (struct bufferevent *bev)
static void bufferevent_generic_read_timeout_cb (evutil_socket_t fd, short event, void *ctx)
static void bufferevent_generic_write_timeout_cb (evutil_socket_t fd, short event, void *ctx)
void bufferevent_init_generic_timeout_cbs_ (struct bufferevent *bev)
int bufferevent_generic_adj_timeouts_ (struct bufferevent *bev)
int bufferevent_generic_adj_existing_timeouts_ (struct bufferevent *bev)
int bufferevent_add_event_ (struct event *ev, const struct timeval *tv)
void bufferevent_lock (struct bufferevent *bev)
void bufferevent_unlock (struct bufferevent *bev)
Macro Definition Documentation
BEV_TRIG_ALL_OPTS
#define BEV_TRIG_ALL_OPTS
Value:
        (           \
        BEV_TRIG_IGNORE_WATERMARKS| \
        BEV_TRIG_DEFER_CALLBACKS    \
    )
Definition at line 271 of file bufferevent.c.
MAX_CBS
#define MAX_CBS 16
SCHEDULE_DEFERRED
#define SCHEDULE_DEFERRED (bevp)
Value:
    do {                                \
        if (event_deferred_cb_schedule_(            \
                (bevp)->bev.ev_base,            \
            &(bevp)->deferred))             \
            bufferevent_incref_(&(bevp)->bev);      \
    } while (0)
Definition at line 231 of file bufferevent.c.
UNLOCKED
#define UNLOCKED (stmt) do { BEV_UNLOCK(bufev); stmt; BEV_LOCK(bufev); } while(0)
Function Documentation
bufferevent_add_event_()
int bufferevent_add_event_ (struct event * ev, const struct timeval * tv)
Internal: Add the event 'ev' with timeout tv, unless tv is set to 0, in which case add ev with no timeout.
Definition at line 1016 of file bufferevent.c.
{
    if (!evutil_timerisset(tv))
        return event_add(ev, NULL);
    else
        return event_add(ev, tv);
}
References event_add().
Referenced by be_openssl_outbuf_cb(), be_socket_enable(), bufferevent_generic_adj_existing_timeouts_(), bufferevent_socket_outbuf_cb(), set_open_callbacks(), start_reading(), and start_writing().
bufferevent_cancel_all_()
static void bufferevent_cancel_all_ (struct bufferevent * bev) static
Definition at line 908 of file bufferevent.c.
{
    union bufferevent_ctrl_data d;
    memset(&d, 0, sizeof(d));
    BEV_LOCK(bev);
    if (bev->be_ops->ctrl)
        bev->be_ops->ctrl(bev, BEV_CTRL_CANCEL_ALL, &d);
    BEV_UNLOCK(bev);
}
References BEV_CTRL_CANCEL_ALL, BEV_LOCK, and BEV_UNLOCK.
Referenced by bufferevent_free().
bufferevent_decref()
int bufferevent_decref (struct bufferevent * bufev)
Definition at line 799 of file bufferevent.c.
{
    BEV_LOCK(bufev);
    return bufferevent_decref_and_unlock_(bufev);
}
References BEV_LOCK, and bufferevent_decref_and_unlock_().
bufferevent_decref_and_unlock_()
int bufferevent_decref_and_unlock_ (struct bufferevent * bufev)
Internal: Drop the reference count on bufev, freeing as necessary, and unlocking it otherwise. Returns 1 if it freed the bufferevent.
Definition at line 706 of file bufferevent.c.
{
    struct bufferevent_private *bufev_private = BEV_UPCAST(bufev);
    int n_cbs = 0;
#define MAX_CBS 16
    struct event_callback *cbs[MAX_CBS];
    EVUTIL_ASSERT(bufev_private->refcnt > 0);
    if (--bufev_private->refcnt) {
        BEV_UNLOCK(bufev);
        return 0;
    }
    if (bufev->be_ops->unlink)
        bufev->be_ops->unlink(bufev);
    /* Okay, we're out of references. Let's finalize this once all the
     * callbacks are done running. */
    cbs[0] = &bufev->ev_read.ev_evcallback;
    cbs[1] = &bufev->ev_write.ev_evcallback;
    cbs[2] = &bufev_private->deferred;
    n_cbs = 3;
    if (bufev_private->rate_limiting) {
        struct event *e = &bufev_private->rate_limiting->refill_bucket_event;
        if (event_initialized(e))
            cbs[n_cbs++] = &e->ev_evcallback;
    }
    n_cbs += evbuffer_get_callbacks_(bufev->input, cbs+n_cbs, MAX_CBS-n_cbs);
    n_cbs += evbuffer_get_callbacks_(bufev->output, cbs+n_cbs, MAX_CBS-n_cbs);
    event_callback_finalize_many_(bufev->ev_base, n_cbs, cbs,
        bufferevent_finalize_cb_);
#undef MAX_CBS
    BEV_UNLOCK(bufev);
    return 1;
}
References BEV_UNLOCK, BEV_UPCAST, bufferevent_finalize_cb_(), bufferevent_private::deferred, evbuffer_get_callbacks_(), event_callback_finalize_many_(), event_initialized(), EVUTIL_ASSERT, MAX_CBS, bufferevent_private::rate_limiting, bufferevent_private::refcnt, and bufferevent_rate_limit::refill_bucket_event.
Referenced by be_async_inbuf_callback(), be_async_outbuf_callback(), be_filter_flush(), be_openssl_handshakeeventcb(), be_openssl_readeventcb(), be_openssl_writeeventcb(), bufferevent_connect_getaddrinfo_cb(), bufferevent_decref(), bufferevent_enable(), bufferevent_filtered_outbuf_cb(), bufferevent_free(), bufferevent_generic_read_timeout_cb(), bufferevent_generic_write_timeout_cb(), bufferevent_readcb(), bufferevent_run_deferred_callbacks_locked(), bufferevent_run_deferred_callbacks_unlocked(), bufferevent_socket_connect(), bufferevent_trigger(), bufferevent_trigger_event(), bufferevent_unlock(), bufferevent_writecb(), connect_complete(), decref_and_unlock(), read_complete(), and write_complete().
bufferevent_disable()
int bufferevent_disable (struct bufferevent * bufev, short event)
Definition at line 573 of file bufferevent.c.
{
    int r = 0;
    BEV_LOCK(bufev);
    bufev->enabled &= ~event;
    if (bufev->be_ops->disable(bufev, event) < 0)
        r = -1;
    if (r)
        event_debug(("%s: cannot disable 0x%hx on %p", __func__, event, bufev));
    BEV_UNLOCK(bufev);
    return r;
}
References __func__, BEV_LOCK, BEV_UNLOCK, and event_debug.
Referenced by bufferevent_generic_read_timeout_cb(), bufferevent_generic_write_timeout_cb(), bufferevent_readcb(), bufferevent_socket_connect(), bufferevent_writecb(), evhttp_connection_fail_(), evhttp_connection_stop_detectclose(), evhttp_get_request_connection(), evhttp_handle_request(), evhttp_read_body(), evhttp_read_trailer(), evhttp_send_continue_done(), evhttp_start_read_(), and evhttp_start_write_().
bufferevent_disable_hard_()
int bufferevent_disable_hard_ (struct bufferevent * bufev, short event)
Definition at line 556 of file bufferevent.c.
{
    int r = 0;
    struct bufferevent_private *bufev_private = BEV_UPCAST(bufev);
    BEV_LOCK(bufev);
    bufev->enabled &= ~event;
    bufev_private->connecting = 0;
    if (bufev->be_ops->disable(bufev, event) < 0)
        r = -1;
    BEV_UNLOCK(bufev);
    return r;
}
References BEV_LOCK, BEV_UNLOCK, BEV_UPCAST, and bufferevent_private::connecting.
Referenced by evhttp_connection_reset_().
bufferevent_enable()
int bufferevent_enable (struct bufferevent * bufev, short event)
Definition at line 482 of file bufferevent.c.
{
    struct bufferevent_private *bufev_private = BEV_UPCAST(bufev);
    short impl_events = event;
    int r = 0;
    bufferevent_incref_and_lock_(bufev);
    if (bufev_private->read_suspended)
        impl_events &= ~EV_READ;
    if (bufev_private->write_suspended)
        impl_events &= ~EV_WRITE;
    bufev->enabled |= event;
    if (impl_events && bufev->be_ops->enable(bufev, impl_events) < 0)
        r = -1;
    if (r)
        event_debug(("%s: cannot enable 0x%hx on %p", __func__, event, bufev));
    bufferevent_decref_and_unlock_(bufev);
    return r;
}
References __func__, BEV_UPCAST, bufferevent_decref_and_unlock_(), bufferevent_incref_and_lock_(), event_debug, bufferevent_private::read_suspended, and bufferevent_private::write_suspended.
Referenced by be_socket_setfd(), bufferevent_filter_new(), bufferevent_openssl_new_impl(), do_handshake(), dogecoin_node_group_connect_next_nodes(), evhttp_connection_connect_(), evhttp_connection_start_detectclose(), evhttp_get_request_connection(), evhttp_send_continue(), evhttp_start_read_(), evhttp_start_write_(), evhttp_write_buffer(), and set_handshake_callbacks().
bufferevent_enable_locking_()
int bufferevent_enable_locking_ (struct bufferevent * bufev, void * lock)
Internal: Set up locking on a bufferevent. If lock is set, use it. Otherwise, use a new lock.
Definition at line 829 of file bufferevent.c.
{
#ifdef EVENT__DISABLE_THREAD_SUPPORT
    return -1;
#else
    struct bufferevent *underlying;
    if (BEV_UPCAST(bufev)->lock)
        return -1;
    underlying = bufferevent_get_underlying(bufev);
    if (!lock && underlying && BEV_UPCAST(underlying)->lock) {
        lock = BEV_UPCAST(underlying)->lock;
        BEV_UPCAST(bufev)->lock = lock;
        BEV_UPCAST(bufev)->own_lock = 0;
    } else if (!lock) {
        EVTHREAD_ALLOC_LOCK(lock, EVTHREAD_LOCKTYPE_RECURSIVE);
        if (!lock)
            return -1;
        BEV_UPCAST(bufev)->lock = lock;
        BEV_UPCAST(bufev)->own_lock = 1;
    } else {
        BEV_UPCAST(bufev)->lock = lock;
        BEV_UPCAST(bufev)->own_lock = 0;
    }
    evbuffer_enable_locking(bufev->input, lock);
    evbuffer_enable_locking(bufev->output, lock);
    if (underlying && !BEV_UPCAST(underlying)->lock)
        bufferevent_enable_locking_(underlying, lock);
    return 0;
#endif
}
References BEV_UPCAST, bufferevent_enable_locking_(), bufferevent_get_underlying(), evbuffer_enable_locking(), and EVTHREAD_ALLOC_LOCK.
Referenced by bufferevent_enable_locking_(), bufferevent_filter_new(), bufferevent_init_common_(), bufferevent_openssl_new_impl(), and bufferevent_pair_new().
bufferevent_finalize_cb_()
static void bufferevent_finalize_cb_ (struct event_callback * evcb, void * arg_) static
Definition at line 747 of file bufferevent.c.
{
    struct bufferevent *bufev = arg_;
    struct bufferevent *underlying;
    struct bufferevent_private *bufev_private = BEV_UPCAST(bufev);
    BEV_LOCK(bufev);
    underlying = bufferevent_get_underlying(bufev);
    /* Clean up the shared info */
    if (bufev->be_ops->destruct)
        bufev->be_ops->destruct(bufev);
    /* XXX what happens if refcnt for these buffers is > 1?
     * The buffers can share a lock with this bufferevent object,
     * but the lock might be destroyed below. */
    /* evbuffer will free the callbacks */
    evbuffer_free(bufev->input);
    evbuffer_free(bufev->output);
    if (bufev_private->rate_limiting) {
        if (bufev_private->rate_limiting->group)
            bufferevent_remove_from_rate_limit_group_internal_(bufev,0);
        mm_free(bufev_private->rate_limiting);
        bufev_private->rate_limiting = NULL;
    }
    BEV_UNLOCK(bufev);
    if (bufev_private->own_lock)
        EVTHREAD_FREE_LOCK(bufev_private->lock,
            EVTHREAD_LOCKTYPE_RECURSIVE);
    /* Free the actual allocated memory. */
    mm_free(((char*)bufev) - bufev->be_ops->mem_offset);
    /* Release the reference to underlying now that we no longer need the
     * reference to it.  We wait this long mainly in case our lock is
     * shared with underlying.
     *
     * The 'destruct' function will also drop a reference to underlying
     * if BEV_OPT_CLOSE_ON_FREE is set.
     *
     * XXX Should we/can we just refcount evbuffer/bufferevent locks?
     * It would probably save us some headaches.
     */
    if (underlying)
        bufferevent_decref_(underlying);
}
References BEV_LOCK, BEV_UNLOCK, BEV_UPCAST, bufferevent_decref_, bufferevent_get_underlying(), bufferevent_remove_from_rate_limit_group_internal_(), evbuffer_free(), EVTHREAD_FREE_LOCK, bufferevent_rate_limit::group, bufferevent_private::lock, mm_free, bufferevent_private::own_lock, and bufferevent_private::rate_limiting.
Referenced by bufferevent_decref_and_unlock_().
bufferevent_flush()
int bufferevent_flush (struct bufferevent * bufev, short iotype, enum bufferevent_flush_mode mode)
Definition at line 667 of file bufferevent.c.
{
    int r = -1;
    BEV_LOCK(bufev);
    if (bufev->be_ops->flush)
        r = bufev->be_ops->flush(bufev, iotype, mode);
    BEV_UNLOCK(bufev);
    return r;
}
References BEV_LOCK, and BEV_UNLOCK.
Referenced by be_filter_flush().
bufferevent_free()
void bufferevent_free (struct bufferevent * bufev)
Definition at line 806 of file bufferevent.c.
{
    BEV_LOCK(bufev);
    bufferevent_setcb(bufev, NULL, NULL, NULL, NULL);
    bufferevent_cancel_all_(bufev);
    bufferevent_decref_and_unlock_(bufev);
}
References BEV_LOCK, bufferevent_cancel_all_(), bufferevent_decref_and_unlock_(), and bufferevent_setcb().
Referenced by be_filter_unlink(), be_openssl_unlink(), bio_bufferevent_free(), bufferevent_async_new_(), bufferevent_openssl_new_impl(), bufferevent_pair_elt_new(), bufferevent_pair_new(), dogecoin_node_group_connect_next_nodes(), dogecoin_node_release_events(), and evhttp_connection_free().
bufferevent_generic_adj_existing_timeouts_()
int bufferevent_generic_adj_existing_timeouts_ (struct bufferevent * bev)
Definition at line 993 of file bufferevent.c.
{
    int r = 0;
    if (event_pending(&bev->ev_read, EV_READ, NULL)) {
        if (evutil_timerisset(&bev->timeout_read)) {
                if (bufferevent_add_event_(&bev->ev_read, &bev->timeout_read) < 0)
                    r = -1;
        } else {
            event_remove_timer(&bev->ev_read);
        }
    }
    if (event_pending(&bev->ev_write, EV_WRITE, NULL)) {
        if (evutil_timerisset(&bev->timeout_write)) {
            if (bufferevent_add_event_(&bev->ev_write, &bev->timeout_write) < 0)
                r = -1;
        } else {
            event_remove_timer(&bev->ev_write);
        }
    }
    return r;
}
References bufferevent_private::bev, bufferevent_add_event_(), event_pending(), and event_remove_timer().
Referenced by be_openssl_adj_timeouts().
bufferevent_generic_adj_timeouts_()
int bufferevent_generic_adj_timeouts_ (struct bufferevent * bev)
Internal use: Add or delete the generic timeout events as appropriate. (If an event is enabled and a timeout is set, we add the event. Otherwise we delete it.) Call this from anything that changes the timeout values, that enabled EV_READ or EV_WRITE, or that disables EV_READ or EV_WRITE.
Definition at line 970 of file bufferevent.c.
{
    const short enabled = bev->enabled;
    struct bufferevent_private *bev_p = BEV_UPCAST(bev);
    int r1=0, r2=0;
    if ((enabled & EV_READ) && !bev_p->read_suspended &&
        evutil_timerisset(&bev->timeout_read))
        r1 = event_add(&bev->ev_read, &bev->timeout_read);
    else
        r1 = event_del(&bev->ev_read);
    if ((enabled & EV_WRITE) && !bev_p->write_suspended &&
        evutil_timerisset(&bev->timeout_write) &&
        evbuffer_get_length(bev->output))
        r2 = event_add(&bev->ev_write, &bev->timeout_write);
    else
        r2 = event_del(&bev->ev_write);
    if (r1 < 0 || r2 < 0)
        return -1;
    return 0;
}
References bufferevent_private::bev, BEV_UPCAST, evbuffer_get_length(), event_add(), event_del(), bufferevent_private::read_suspended, and bufferevent_private::write_suspended.
Referenced by be_openssl_adj_timeouts().
bufferevent_generic_read_timeout_cb()
static void bufferevent_generic_read_timeout_cb (evutil_socket_t fd, short event, void * ctx) static
Definition at line 942 of file bufferevent.c.
{
    struct bufferevent *bev = ctx;
    bufferevent_incref_and_lock_(bev);
    bufferevent_disable(bev, EV_READ);
    bufferevent_run_eventcb_(bev, BEV_EVENT_TIMEOUT|BEV_EVENT_READING, 0);
    bufferevent_decref_and_unlock_(bev);
}
References bufferevent_decref_and_unlock_(), bufferevent_disable(), bufferevent_incref_and_lock_(), bufferevent_run_eventcb_(), and ctx.
Referenced by bufferevent_init_generic_timeout_cbs_().
bufferevent_generic_write_timeout_cb()
static void bufferevent_generic_write_timeout_cb (evutil_socket_t fd, short event, void * ctx) static
Definition at line 951 of file bufferevent.c.
{
    struct bufferevent *bev = ctx;
    bufferevent_incref_and_lock_(bev);
    bufferevent_disable(bev, EV_WRITE);
    bufferevent_run_eventcb_(bev, BEV_EVENT_TIMEOUT|BEV_EVENT_WRITING, 0);
    bufferevent_decref_and_unlock_(bev);
}
References bufferevent_decref_and_unlock_(), bufferevent_disable(), bufferevent_incref_and_lock_(), bufferevent_run_eventcb_(), and ctx.
Referenced by bufferevent_init_generic_timeout_cbs_().
bufferevent_get_base()
struct event_base * bufferevent_get_base (struct bufferevent * bufev)
Definition at line 436 of file bufferevent.c.
{
    return bufev->ev_base;
}
Referenced by evhttp_connection_base_bufferevent_new().
bufferevent_get_enabled()
short bufferevent_get_enabled (struct bufferevent * bufev)
Definition at line 919 of file bufferevent.c.
{
    short r;
    BEV_LOCK(bufev);
    r = bufev->enabled;
    BEV_UNLOCK(bufev);
    return r;
}
References BEV_LOCK, and BEV_UNLOCK.
bufferevent_get_input()
struct evbuffer * bufferevent_get_input (struct bufferevent * bufev)
Definition at line 424 of file bufferevent.c.
{
    return bufev->input;
}
Referenced by bio_bufferevent_ctrl(), bio_bufferevent_read(), evhttp_connection_reset_(), evhttp_error_cb(), evhttp_get_body(), evhttp_get_body_length(), evhttp_lingering_close(), evhttp_read_body(), evhttp_read_cb(), evhttp_read_firstline(), evhttp_read_header(), evhttp_read_trailer(), evhttp_start_read_(), and read_cb().
bufferevent_get_options_()
enum bufferevent_options bufferevent_get_options_ (struct bufferevent * bev)
Definition at line 895 of file bufferevent.c.
{
    struct bufferevent_private *bev_p = BEV_UPCAST(bev);
    enum bufferevent_options options;
    BEV_LOCK(bev);
    options = bev_p->options;
    BEV_UNLOCK(bev);
    return options;
}
References bufferevent_private::bev, BEV_LOCK, BEV_UNLOCK, BEV_UPCAST, and bufferevent_private::options.
Referenced by evhttp_connection_free().
bufferevent_get_output()
struct evbuffer * bufferevent_get_output (struct bufferevent * bufev)
Definition at line 430 of file bufferevent.c.
{
    return bufev->output;
}
Referenced by bio_bufferevent_ctrl(), bio_bufferevent_write(), evhttp_connection_read_on_write_error(), evhttp_connection_reset_(), evhttp_make_header(), evhttp_make_header_request(), evhttp_make_header_response(), evhttp_read_header(), evhttp_send_continue(), evhttp_send_reply_chunk_with_cb(), evhttp_send_reply_end(), and evhttp_write_connectioncb().
bufferevent_get_priority()
int bufferevent_get_priority (const struct bufferevent * bufev)
Definition at line 442 of file bufferevent.c.
{
    if (event_initialized(&bufev->ev_read)) {
        return event_get_priority(&bufev->ev_read);
    } else {
        return event_base_get_npriorities(bufev->ev_base) / 2;
    }
}
References event_base_get_npriorities(), event_get_priority(), and event_initialized().
Referenced by evhttp_connection_base_bufferevent_new().
bufferevent_get_underlying()
struct bufferevent * bufferevent_get_underlying (struct bufferevent * bev)
Definition at line 929 of file bufferevent.c.
{
    union bufferevent_ctrl_data d;
    int res = -1;
    d.ptr = NULL;
    BEV_LOCK(bev);
    if (bev->be_ops->ctrl)
        res = bev->be_ops->ctrl(bev, BEV_CTRL_GET_UNDERLYING, &d);
    BEV_UNLOCK(bev);
    return (res<0) ? NULL : d.ptr;
}
References BEV_CTRL_GET_UNDERLYING, BEV_LOCK, BEV_UNLOCK, and bufferevent_ctrl_data::ptr.
Referenced by bufferevent_enable_locking_(), and bufferevent_finalize_cb_().
bufferevent_getcb()
void bufferevent_getcb (struct bufferevent * bufev, bufferevent_data_cb * readcb_ptr, bufferevent_data_cb * writecb_ptr, bufferevent_event_cb * eventcb_ptr, void ** cbarg_ptr)
Definition at line 404 of file bufferevent.c.
{
    BEV_LOCK(bufev);
    if (readcb_ptr)
        *readcb_ptr = bufev->readcb;
    if (writecb_ptr)
        *writecb_ptr = bufev->writecb;
    if (eventcb_ptr)
        *eventcb_ptr = bufev->errorcb;
    if (cbarg_ptr)
        *cbarg_ptr = bufev->cbarg;
    BEV_UNLOCK(bufev);
}
References BEV_LOCK, and BEV_UNLOCK.
bufferevent_getfd()
evutil_socket_t bufferevent_getfd (struct bufferevent * bev)
Definition at line 880 of file bufferevent.c.
{
    union bufferevent_ctrl_data d;
    int res = -1;
    d.fd = -1;
    BEV_LOCK(bev);
    if (bev->be_ops->ctrl)
        res = bev->be_ops->ctrl(bev, BEV_CTRL_GET_FD, &d);
    if (res)
        event_debug(("%s: cannot get fd for %p", __func__, bev));
    BEV_UNLOCK(bev);
    return (res<0) ? -1 : d.fd;
}
References __func__, BEV_CTRL_GET_FD, BEV_LOCK, BEV_UNLOCK, event_debug, and bufferevent_ctrl_data::fd.
Referenced by bufferevent_socket_connect(), evhttp_connection_cb(), evhttp_connection_free(), evhttp_connection_reset_(), and evhttp_error_cb().
bufferevent_getwatermark()
int bufferevent_getwatermark (struct bufferevent * bufev, short events, size_t * lowmark, size_t * highmark)
Definition at line 641 of file bufferevent.c.
{
    if (events == EV_WRITE) {
        BEV_LOCK(bufev);
        if (lowmark)
            *lowmark = bufev->wm_write.low;
        if (highmark)
            *highmark = bufev->wm_write.high;
        BEV_UNLOCK(bufev);
        return 0;
    }
    if (events == EV_READ) {
        BEV_LOCK(bufev);
        if (lowmark)
            *lowmark = bufev->wm_read.low;
        if (highmark)
            *highmark = bufev->wm_read.high;
        BEV_UNLOCK(bufev);
        return 0;
    }
    return -1;
}
References BEV_LOCK, and BEV_UNLOCK.
bufferevent_inbuf_wm_cb()
static void bufferevent_inbuf_wm_cb (struct evbuffer * buf, const struct evbuffer_cb_info * cbinfo, void * arg) static
Definition at line 136 of file bufferevent.c.
{
    struct bufferevent *bufev = arg;
    size_t size;
    size = evbuffer_get_length(buf);
    if (size >= bufev->wm_read.high)
        bufferevent_wm_suspend_read(bufev);
    else
        bufferevent_wm_unsuspend_read(bufev);
}
References bufferevent_wm_suspend_read, bufferevent_wm_unsuspend_read, and evbuffer_get_length().
Referenced by bufferevent_setwatermark().
bufferevent_inbuf_wm_check()
static void bufferevent_inbuf_wm_check (struct bufferevent * bev) static
Sometimes bufferevent's implementation can overrun high watermarks (one of examples is openssl) and in this case if the read callback will not handle enough data do over condition above the read callback will never be called again (due to suspend above).
To avoid this we are scheduling read callback again here, but only from the user callback to avoid multiple scheduling:
when the data had been added to it
when the data had been drained from it (user specified read callback)
Definition at line 121 of file bufferevent.c.
{
    if (!bev->wm_read.high)
        return;
    if (!(bev->enabled & EV_READ))
        return;
    if (evbuffer_get_length(bev->input) < bev->wm_read.high)
        return;
    bufferevent_trigger(bev, EV_READ, BEV_OPT_DEFER_CALLBACKS);
}
References bufferevent_private::bev, bufferevent_trigger(), and evbuffer_get_length().
Referenced by bufferevent_run_deferred_callbacks_locked(), bufferevent_run_deferred_callbacks_unlocked(), and bufferevent_run_readcb_().
bufferevent_incref()
void bufferevent_incref (struct bufferevent * bufev)
Definition at line 815 of file bufferevent.c.
{
    struct bufferevent_private *bufev_private = BEV_UPCAST(bufev);
    /* XXX: now that this function is public, we might want to
     * - return the count from this function
     * - create a new function to atomically grab the current refcount
     */
    BEV_LOCK(bufev);
    ++bufev_private->refcnt;
    BEV_UNLOCK(bufev);
}
References BEV_LOCK, BEV_UNLOCK, BEV_UPCAST, and bufferevent_private::refcnt.
bufferevent_incref_and_lock_()
void bufferevent_incref_and_lock_ (struct bufferevent * bufev)
Internal: Lock bufev and increase its reference count. unlocking it otherwise.
Definition at line 680 of file bufferevent.c.
{
    struct bufferevent_private *bufev_private = BEV_UPCAST(bufev);
    BEV_LOCK(bufev);
    ++bufev_private->refcnt;
}
References BEV_LOCK, BEV_UPCAST, and bufferevent_private::refcnt.
Referenced by be_async_inbuf_callback(), be_async_outbuf_callback(), be_filter_flush(), be_openssl_handshakeeventcb(), be_openssl_readeventcb(), be_openssl_writeeventcb(), bufferevent_enable(), bufferevent_filtered_outbuf_cb(), bufferevent_generic_read_timeout_cb(), bufferevent_generic_write_timeout_cb(), bufferevent_lock(), bufferevent_readcb(), bufferevent_socket_connect(), bufferevent_trigger(), bufferevent_trigger_event(), bufferevent_writecb(), and incref_and_lock().
bufferevent_init_common_()
int bufferevent_init_common_ (struct bufferevent_private * bufev_private, struct event_base * base, const struct bufferevent_ops * ops, enum bufferevent_options options)
Initialize the shared parts of a bufferevent.
Definition at line 309 of file bufferevent.c.
{
    struct bufferevent *bufev = &bufev_private->bev;
    if (!bufev->input) {
        if ((bufev->input = evbuffer_new()) == NULL)
            goto err;
    }
    if (!bufev->output) {
        if ((bufev->output = evbuffer_new()) == NULL)
            goto err;
    }
    bufev_private->refcnt = 1;
    bufev->ev_base = base;
    /* Disable timeouts. */
    evutil_timerclear(&bufev->timeout_read);
    evutil_timerclear(&bufev->timeout_write);
    bufev->be_ops = ops;
    if (bufferevent_ratelim_init_(bufev_private))
        goto err;
    /*
     * Set to EV_WRITE so that using bufferevent_write is going to
     * trigger a callback.  Reading needs to be explicitly enabled
     * because otherwise no data will be available.
     */
    bufev->enabled = EV_WRITE;
#ifndef EVENT__DISABLE_THREAD_SUPPORT
    if (options & BEV_OPT_THREADSAFE) {
        if (bufferevent_enable_locking_(bufev, NULL) < 0)
            goto err;
    }
#endif
    if ((options & (BEV_OPT_DEFER_CALLBACKS|BEV_OPT_UNLOCK_CALLBACKS))
        == BEV_OPT_UNLOCK_CALLBACKS) {
        event_warnx("UNLOCK_CALLBACKS requires DEFER_CALLBACKS");
        goto err;
    }
    if (options & BEV_OPT_UNLOCK_CALLBACKS)
        event_deferred_cb_init_(
            &bufev_private->deferred,
            event_base_get_npriorities(base) / 2,
            bufferevent_run_deferred_callbacks_unlocked,
            bufev_private);
    else
        event_deferred_cb_init_(
            &bufev_private->deferred,
            event_base_get_npriorities(base) / 2,
            bufferevent_run_deferred_callbacks_locked,
            bufev_private);
    bufev_private->options = options;
    evbuffer_set_parent_(bufev->input, bufev);
    evbuffer_set_parent_(bufev->output, bufev);
    return 0;
err:
    if (bufev->input) {
        evbuffer_free(bufev->input);
        bufev->input = NULL;
    }
    if (bufev->output) {
        evbuffer_free(bufev->output);
        bufev->output = NULL;
    }
    return -1;
}
References bufferevent_private::bev, bufferevent_enable_locking_(), bufferevent_ratelim_init_(), bufferevent_run_deferred_callbacks_locked(), bufferevent_run_deferred_callbacks_unlocked(), bufferevent_private::deferred, evbuffer_free(), evbuffer_new(), evbuffer_set_parent_(), event_base_get_npriorities(), event_deferred_cb_init_(), event_warnx(), bufferevent_private::options, and bufferevent_private::refcnt.
Referenced by bufferevent_async_new_(), bufferevent_filter_new(), bufferevent_openssl_new_impl(), bufferevent_pair_elt_new(), and bufferevent_socket_new().
bufferevent_init_generic_timeout_cbs_()
void bufferevent_init_generic_timeout_cbs_ (struct bufferevent * bev)
Internal use: Set up the ev_read and ev_write callbacks so that the other "generic_timeout" functions will work on it. Call this from the constructor function.
Definition at line 961 of file bufferevent.c.
{
    event_assign(&bev->ev_read, bev->ev_base, -1, EV_FINALIZE,
        bufferevent_generic_read_timeout_cb, bev);
    event_assign(&bev->ev_write, bev->ev_base, -1, EV_FINALIZE,
        bufferevent_generic_write_timeout_cb, bev);
}
References bufferevent_generic_read_timeout_cb(), bufferevent_generic_write_timeout_cb(), and event_assign().
Referenced by bufferevent_async_new_(), bufferevent_filter_new(), bufferevent_openssl_new_impl(), and bufferevent_pair_elt_new().
bufferevent_lock()
void bufferevent_lock (struct bufferevent * bev)
Definition at line 1027 of file bufferevent.c.
{
    bufferevent_incref_and_lock_(bev);
}
References bufferevent_private::bev, and bufferevent_incref_and_lock_().
bufferevent_read()
size_t bufferevent_read (struct bufferevent * bufev, void * data, size_t size)
Definition at line 470 of file bufferevent.c.
{
    return (evbuffer_remove(bufev->input, data, size));
}
References evbuffer_remove().
bufferevent_read_buffer()
int bufferevent_read_buffer (struct bufferevent * bufev, struct evbuffer * buf)
Definition at line 476 of file bufferevent.c.
{
    return (evbuffer_add_buffer(buf, bufev->input));
}
References evbuffer_add_buffer().
bufferevent_run_deferred_callbacks_locked()
static void bufferevent_run_deferred_callbacks_locked (struct event_callback * cb, void * arg) static
Definition at line 152 of file bufferevent.c.
{
    struct bufferevent_private *bufev_private = arg;
    struct bufferevent *bufev = &bufev_private->bev;
    BEV_LOCK(bufev);
    if ((bufev_private->eventcb_pending & BEV_EVENT_CONNECTED) &&
        bufev->errorcb) {
        /* The "connected" happened before any reads or writes, so
           send it first. */
        bufev_private->eventcb_pending &= ~BEV_EVENT_CONNECTED;
        bufev->errorcb(bufev, BEV_EVENT_CONNECTED, bufev->cbarg);
    }
    if (bufev_private->readcb_pending && bufev->readcb) {
        bufev_private->readcb_pending = 0;
        bufev->readcb(bufev, bufev->cbarg);
        bufferevent_inbuf_wm_check(bufev);
    }
    if (bufev_private->writecb_pending && bufev->writecb) {
        bufev_private->writecb_pending = 0;
        bufev->writecb(bufev, bufev->cbarg);
    }
    if (bufev_private->eventcb_pending && bufev->errorcb) {
        short what = bufev_private->eventcb_pending;
        int err = bufev_private->errno_pending;
        bufev_private->eventcb_pending = 0;
        bufev_private->errno_pending = 0;
        EVUTIL_SET_SOCKET_ERROR(err);
        bufev->errorcb(bufev, what, bufev->cbarg);
    }
    bufferevent_decref_and_unlock_(bufev);
}
References bufferevent_private::bev, BEV_LOCK, bufferevent_decref_and_unlock_(), bufferevent_inbuf_wm_check(), bufferevent_private::errno_pending, bufferevent_private::eventcb_pending, bufferevent_private::readcb_pending, and bufferevent_private::writecb_pending.
Referenced by bufferevent_init_common_().
bufferevent_run_deferred_callbacks_unlocked()
static void bufferevent_run_deferred_callbacks_unlocked (struct event_callback * cb, void * arg) static
Definition at line 186 of file bufferevent.c.
{
    struct bufferevent_private *bufev_private = arg;
    struct bufferevent *bufev = &bufev_private->bev;
    BEV_LOCK(bufev);
#define UNLOCKED(stmt) \
    do { BEV_UNLOCK(bufev); stmt; BEV_LOCK(bufev); } while(0)
    if ((bufev_private->eventcb_pending & BEV_EVENT_CONNECTED) &&
        bufev->errorcb) {
        /* The "connected" happened before any reads or writes, so
           send it first. */
        bufferevent_event_cb errorcb = bufev->errorcb;
        void *cbarg = bufev->cbarg;
        bufev_private->eventcb_pending &= ~BEV_EVENT_CONNECTED;
        UNLOCKED(errorcb(bufev, BEV_EVENT_CONNECTED, cbarg));
    }
    if (bufev_private->readcb_pending && bufev->readcb) {
        bufferevent_data_cb readcb = bufev->readcb;
        void *cbarg = bufev->cbarg;
        bufev_private->readcb_pending = 0;
        UNLOCKED(readcb(bufev, cbarg));
        bufferevent_inbuf_wm_check(bufev);
    }
    if (bufev_private->writecb_pending && bufev->writecb) {
        bufferevent_data_cb writecb = bufev->writecb;
        void *cbarg = bufev->cbarg;
        bufev_private->writecb_pending = 0;
        UNLOCKED(writecb(bufev, cbarg));
    }
    if (bufev_private->eventcb_pending && bufev->errorcb) {
        bufferevent_event_cb errorcb = bufev->errorcb;
        void *cbarg = bufev->cbarg;
        short what = bufev_private->eventcb_pending;
        int err = bufev_private->errno_pending;
        bufev_private->eventcb_pending = 0;
        bufev_private->errno_pending = 0;
        EVUTIL_SET_SOCKET_ERROR(err);
        UNLOCKED(errorcb(bufev,what,cbarg));
    }
    bufferevent_decref_and_unlock_(bufev);
#undef UNLOCKED
}
References bufferevent_private::bev, BEV_LOCK, bufferevent_decref_and_unlock_(), bufferevent_inbuf_wm_check(), bufferevent_private::errno_pending, bufferevent_private::eventcb_pending, bufferevent_private::readcb_pending, UNLOCKED, and bufferevent_private::writecb_pending.
Referenced by bufferevent_init_common_().
bufferevent_run_eventcb_()
void bufferevent_run_eventcb_ (struct bufferevent * bufev, short what, int options)
Internal: If callbacks are deferred and we have an eventcb, schedule it to run with events "what". Otherwise just run the eventcb. See bufferevent_trigger_event for meaning of "options".
Definition at line 285 of file bufferevent.c.
{
    /* Requires that we hold the lock and a reference */
    struct bufferevent_private *p = BEV_UPCAST(bufev);
    if (bufev->errorcb == NULL)
        return;
    if ((p->options|options) & BEV_OPT_DEFER_CALLBACKS) {
        p->eventcb_pending |= what;
        p->errno_pending = EVUTIL_SOCKET_ERROR();
        SCHEDULE_DEFERRED(p);
    } else {
        bufev->errorcb(bufev, what, bufev->cbarg);
    }
}
References BEV_UPCAST, bufferevent_private::errno_pending, bufferevent_private::eventcb_pending, bufferevent_private::options, and SCHEDULE_DEFERRED.
Referenced by be_async_run_eventcb(), be_filter_eventcb(), be_openssl_eventcb(), be_openssl_handshakeeventcb(), be_openssl_readeventcb(), be_openssl_writeeventcb(), be_pair_flush(), bufferevent_connect_getaddrinfo_cb(), bufferevent_generic_read_timeout_cb(), bufferevent_generic_write_timeout_cb(), bufferevent_readcb(), bufferevent_socket_connect(), bufferevent_trigger_event(), bufferevent_writecb(), conn_closed(), and do_handshake().
bufferevent_run_readcb_()
void bufferevent_run_readcb_ (struct bufferevent * bufev, int options)
Internal: If callbacks are deferred and we have a read callback, schedule a readcb. Otherwise just run the readcb. Ignores watermarks.
Definition at line 241 of file bufferevent.c.
{
    /* Requires that we hold the lock and a reference */
    struct bufferevent_private *p = BEV_UPCAST(bufev);
    if (bufev->readcb == NULL)
        return;
    if ((p->options|options) & BEV_OPT_DEFER_CALLBACKS) {
        p->readcb_pending = 1;
        SCHEDULE_DEFERRED(p);
    } else {
        bufev->readcb(bufev, bufev->cbarg);
        bufferevent_inbuf_wm_check(bufev);
    }
}
References BEV_UPCAST, bufferevent_inbuf_wm_check(), bufferevent_private::options, bufferevent_private::readcb_pending, and SCHEDULE_DEFERRED.
Referenced by bufferevent_trigger_nolock_().
bufferevent_run_writecb_()
void bufferevent_run_writecb_ (struct bufferevent * bufev, int options)
Internal: If callbacks are deferred and we have a write callback, schedule a writecb. Otherwise just run the writecb. Ignores watermarks.
Definition at line 257 of file bufferevent.c.
{
    /* Requires that we hold the lock and a reference */
    struct bufferevent_private *p = BEV_UPCAST(bufev);
    if (bufev->writecb == NULL)
        return;
    if ((p->options|options) & BEV_OPT_DEFER_CALLBACKS) {
        p->writecb_pending = 1;
        SCHEDULE_DEFERRED(p);
    } else {
        bufev->writecb(bufev, bufev->cbarg);
    }
}
References BEV_UPCAST, bufferevent_private::options, SCHEDULE_DEFERRED, and bufferevent_private::writecb_pending.
Referenced by bufferevent_trigger_nolock_().
bufferevent_set_timeouts()
int bufferevent_set_timeouts (struct bufferevent * bufev, const struct timeval * tv_read, const struct timeval * tv_write)
Definition at line 506 of file bufferevent.c.
{
    int r = 0;
    BEV_LOCK(bufev);
    if (tv_read) {
        bufev->timeout_read = *tv_read;
    } else {
        evutil_timerclear(&bufev->timeout_read);
    }
    if (tv_write) {
        bufev->timeout_write = *tv_write;
    } else {
        evutil_timerclear(&bufev->timeout_write);
    }
    if (bufev->be_ops->adj_timeouts)
        r = bufev->be_ops->adj_timeouts(bufev);
    BEV_UNLOCK(bufev);
    return r;
}
References BEV_LOCK, and BEV_UNLOCK.
Referenced by bufferevent_settimeout(), evhttp_connection_cb(), evhttp_connection_connect_(), and evhttp_connection_set_timeout_tv().
bufferevent_setcb()
void bufferevent_setcb (struct bufferevent * bufev, bufferevent_data_cb readcb, bufferevent_data_cb writecb, bufferevent_event_cb eventcb, void * cbarg)
Definition at line 389 of file bufferevent.c.
{
    BEV_LOCK(bufev);
    bufev->readcb = readcb;
    bufev->writecb = writecb;
    bufev->errorcb = eventcb;
    bufev->cbarg = cbarg;
    BEV_UNLOCK(bufev);
}
References BEV_LOCK, and BEV_UNLOCK.
Referenced by be_filter_unlink(), be_openssl_unlink(), bufferevent_filter_new(), bufferevent_free(), bufferevent_new(), dogecoin_node_group_connect_next_nodes(), evhttp_connection_base_bufferevent_new(), evhttp_connection_cb(), evhttp_connection_connect_(), evhttp_connection_reset_(), evhttp_send_continue(), evhttp_start_read_(), evhttp_write_buffer(), set_handshake_callbacks(), and set_open_callbacks().
bufferevent_setfd()
int bufferevent_setfd (struct bufferevent * bev, evutil_socket_t fd)
Definition at line 865 of file bufferevent.c.
{
    union bufferevent_ctrl_data d;
    int res = -1;
    d.fd = fd;
    BEV_LOCK(bev);
    if (bev->be_ops->ctrl)
        res = bev->be_ops->ctrl(bev, BEV_CTRL_SET_FD, &d);
    if (res)
        event_debug(("%s: cannot set fd for %p to "EV_SOCK_FMT, __func__, bev, fd));
    BEV_UNLOCK(bev);
    return res;
}
References __func__, BEV_CTRL_SET_FD, BEV_LOCK, BEV_UNLOCK, EV_SOCK_FMT, event_debug, and bufferevent_ctrl_data::fd.
Referenced by bufferevent_socket_connect(), evhttp_connection_connect_(), evhttp_connection_reset_(), evhttp_get_request_connection(), and set_handshake_callbacks().
bufferevent_settimeout()
void bufferevent_settimeout (struct bufferevent * bufev, int timeout_read, int timeout_write)
Definition at line 533 of file bufferevent.c.
{
    struct timeval tv_read, tv_write;
    struct timeval *ptv_read = NULL, *ptv_write = NULL;
    memset(&tv_read, 0, sizeof(tv_read));
    memset(&tv_write, 0, sizeof(tv_write));
    if (timeout_read) {
        tv_read.tv_sec = timeout_read;
        ptv_read = &tv_read;
    }
    if (timeout_write) {
        tv_write.tv_sec = timeout_write;
        ptv_write = &tv_write;
    }
    bufferevent_set_timeouts(bufev, ptv_read, ptv_write);
}
References bufferevent_set_timeouts().
bufferevent_setwatermark()
void bufferevent_setwatermark (struct bufferevent * bufev, short events, size_t lowmark, size_t highmark)
Definition at line 594 of file bufferevent.c.
{
    struct bufferevent_private *bufev_private = BEV_UPCAST(bufev);
    BEV_LOCK(bufev);
    if (events & EV_WRITE) {
        bufev->wm_write.low = lowmark;
        bufev->wm_write.high = highmark;
    }
    if (events & EV_READ) {
        bufev->wm_read.low = lowmark;
        bufev->wm_read.high = highmark;
        if (highmark) {
            /* There is now a new high-water mark for read.
               enable the callback if needed, and see if we should
               suspend/bufferevent_wm_unsuspend. */
            if (bufev_private->read_watermarks_cb == NULL) {
                bufev_private->read_watermarks_cb =
                    evbuffer_add_cb(bufev->input,
                            bufferevent_inbuf_wm_cb,
                            bufev);
            }
            evbuffer_cb_set_flags(bufev->input,
                      bufev_private->read_watermarks_cb,
                      EVBUFFER_CB_ENABLED|EVBUFFER_CB_NODEFER);
            if (evbuffer_get_length(bufev->input) >= highmark)
                bufferevent_wm_suspend_read(bufev);
            else if (evbuffer_get_length(bufev->input) < highmark)
                bufferevent_wm_unsuspend_read(bufev);
        } else {
            /* There is now no high-water mark for read. */
            if (bufev_private->read_watermarks_cb)
                evbuffer_cb_clear_flags(bufev->input,
                    bufev_private->read_watermarks_cb,
                    EVBUFFER_CB_ENABLED);
            bufferevent_wm_unsuspend_read(bufev);
        }
    }
    BEV_UNLOCK(bufev);
}
References BEV_LOCK, BEV_UNLOCK, BEV_UPCAST, bufferevent_inbuf_wm_cb(), bufferevent_wm_suspend_read, bufferevent_wm_unsuspend_read, evbuffer_add_cb(), evbuffer_cb_clear_flags(), EVBUFFER_CB_NODEFER, evbuffer_cb_set_flags(), evbuffer_get_length(), and bufferevent_private::read_watermarks_cb.
Referenced by bufferevent_openssl_new_impl().
bufferevent_suspend_read_()
void bufferevent_suspend_read_ (struct bufferevent * bufev, bufferevent_suspend_flags what)
For internal use: temporarily stop all reads on bufev, until the conditions in 'what' are over.
Definition at line 67 of file bufferevent.c.
{
    struct bufferevent_private *bufev_private = BEV_UPCAST(bufev);
    BEV_LOCK(bufev);
    if (!bufev_private->read_suspended)
        bufev->be_ops->disable(bufev, EV_READ);
    bufev_private->read_suspended |= what;
    BEV_UNLOCK(bufev);
}
References BEV_LOCK, BEV_UNLOCK, BEV_UPCAST, and bufferevent_private::read_suspended.
Referenced by be_filter_disable(), bev_group_suspend_reading_(), bufferevent_add_to_rate_limit_group(), bufferevent_decrement_read_buckets_(), bufferevent_decrement_read_limit(), bufferevent_filter_new(), bufferevent_get_rlim_max_(), bufferevent_openssl_new_impl(), bufferevent_set_rate_limit(), bufferevent_socket_connect_hostname(), and stop_reading().
bufferevent_suspend_write_()
void bufferevent_suspend_write_ (struct bufferevent * bufev, bufferevent_suspend_flags what)
For internal use: temporarily stop all writes on bufev, until the conditions in 'what' are over.
Definition at line 89 of file bufferevent.c.
{
    struct bufferevent_private *bufev_private = BEV_UPCAST(bufev);
    BEV_LOCK(bufev);
    if (!bufev_private->write_suspended)
        bufev->be_ops->disable(bufev, EV_WRITE);
    bufev_private->write_suspended |= what;
    BEV_UNLOCK(bufev);
}
References BEV_LOCK, BEV_UNLOCK, BEV_UPCAST, and bufferevent_private::write_suspended.
Referenced by bev_group_suspend_writing_(), bufferevent_add_to_rate_limit_group(), bufferevent_decrement_write_buckets_(), bufferevent_decrement_write_limit(), bufferevent_get_rlim_max_(), bufferevent_set_rate_limit(), and bufferevent_socket_connect_hostname().
bufferevent_trigger()
void bufferevent_trigger (struct bufferevent * bufev, short iotype, int options)
Definition at line 277 of file bufferevent.c.
{
    bufferevent_incref_and_lock_(bufev);
    bufferevent_trigger_nolock_(bufev, iotype, options&BEV_TRIG_ALL_OPTS);
    bufferevent_decref_and_unlock_(bufev);
}
References BEV_TRIG_ALL_OPTS, bufferevent_decref_and_unlock_(), bufferevent_incref_and_lock_(), bufferevent_trigger_nolock_(), and bufferevent_private::options.
Referenced by bufferevent_inbuf_wm_check().
bufferevent_trigger_event()
void bufferevent_trigger_event (struct bufferevent * bufev, short what, int options)
Definition at line 301 of file bufferevent.c.
{
    bufferevent_incref_and_lock_(bufev);
    bufferevent_run_eventcb_(bufev, what, options&BEV_TRIG_ALL_OPTS);
    bufferevent_decref_and_unlock_(bufev);
}
References BEV_TRIG_ALL_OPTS, bufferevent_decref_and_unlock_(), bufferevent_incref_and_lock_(), bufferevent_run_eventcb_(), and bufferevent_private::options.
bufferevent_unlock()
void bufferevent_unlock (struct bufferevent * bev)
Definition at line 1033 of file bufferevent.c.
{
    bufferevent_decref_and_unlock_(bev);
}
References bufferevent_private::bev, and bufferevent_decref_and_unlock_().
bufferevent_unsuspend_read_()
void bufferevent_unsuspend_read_ (struct bufferevent * bufev, bufferevent_suspend_flags what)
For internal use: clear the conditions 'what' on bufev, and re-enable reading if there are no conditions left.
Definition at line 78 of file bufferevent.c.
{
    struct bufferevent_private *bufev_private = BEV_UPCAST(bufev);
    BEV_LOCK(bufev);
    bufev_private->read_suspended &= ~what;
    if (!bufev_private->read_suspended && (bufev->enabled & EV_READ))
        bufev->be_ops->enable(bufev, EV_READ);
    BEV_UNLOCK(bufev);
}
References BEV_LOCK, BEV_UNLOCK, BEV_UPCAST, and bufferevent_private::read_suspended.
Referenced by be_filter_enable(), be_filter_unlink(), be_openssl_unlink(), bev_refill_callback_(), bufferevent_connect_getaddrinfo_cb(), bufferevent_decrement_read_buckets_(), bufferevent_decrement_read_limit(), bufferevent_remove_from_rate_limit_group_internal_(), bufferevent_set_rate_limit(), start_reading(), start_writing(), and stop_writing().
bufferevent_unsuspend_write_()
void bufferevent_unsuspend_write_ (struct bufferevent * bufev, bufferevent_suspend_flags what)
For internal use: clear the conditions 'what' on bufev, and re-enable writing if there are no conditions left.
Definition at line 100 of file bufferevent.c.
{
    struct bufferevent_private *bufev_private = BEV_UPCAST(bufev);
    BEV_LOCK(bufev);
    bufev_private->write_suspended &= ~what;
    if (!bufev_private->write_suspended && (bufev->enabled & EV_WRITE))
        bufev->be_ops->enable(bufev, EV_WRITE);
    BEV_UNLOCK(bufev);
}
References BEV_LOCK, BEV_UNLOCK, BEV_UPCAST, and bufferevent_private::write_suspended.
Referenced by bev_refill_callback_(), bufferevent_connect_getaddrinfo_cb(), bufferevent_decrement_write_buckets_(), bufferevent_decrement_write_limit(), bufferevent_remove_from_rate_limit_group_internal_(), and bufferevent_set_rate_limit().
bufferevent_write()
int bufferevent_write (struct bufferevent * bufev, const void * data, size_t size)
Definition at line 452 of file bufferevent.c.
{
    if (evbuffer_add(bufev->output, data, size) == -1)
        return (-1);
    return 0;
}
References evbuffer_add().
Referenced by dogecoin_node_send().
bufferevent_write_buffer()
int bufferevent_write_buffer (struct bufferevent * bufev, struct evbuffer * buf)
Definition at line 461 of file bufferevent.c.
{
    if (evbuffer_add_buffer(bufev->output, buf) == -1)
        return (-1);
    return 0;
}
References evbuffer_add_buffer().