libdogecoin: src/libevent/bufferevent_pair.c File Reference
bufferevent_pair.c File Reference
#include "event2/event-config.h"
#include "evconfig-private.h"
#include <sys/types.h>
#include "event2/util.h"
#include "event2/buffer.h"
#include "event2/bufferevent.h"
#include "event2/bufferevent_struct.h"
#include "event2/event.h"
#include "defer-internal.h"
#include "bufferevent-internal.h"
#include "mm-internal.h"
#include "util-internal.h"
Data Structures
struct bufferevent_pair
Macros
#define downcast(bev_pair) (&(bev_pair)->bev.bev)
Functions
static struct bufferevent_pair * upcast (struct bufferevent *bev)
static void incref_and_lock (struct bufferevent *b)
static void decref_and_unlock (struct bufferevent *b)
static void be_pair_outbuf_cb (struct evbuffer *, const struct evbuffer_cb_info *, void *)
static struct bufferevent_pair * bufferevent_pair_elt_new (struct event_base *base, int options)
int bufferevent_pair_new (struct event_base *base, int options, struct bufferevent *pair[2])
static void be_pair_transfer (struct bufferevent *src, struct bufferevent *dst, int ignore_wm)
static int be_pair_wants_to_talk (struct bufferevent_pair *src, struct bufferevent_pair *dst)
static int be_pair_enable (struct bufferevent *bufev, short events)
static int be_pair_disable (struct bufferevent *bev, short events)
static void be_pair_unlink (struct bufferevent *bev)
static void be_pair_destruct (struct bufferevent *bev)
static int be_pair_flush (struct bufferevent *bev, short iotype, enum bufferevent_flush_mode mode)
struct bufferevent * bufferevent_pair_get_partner (struct bufferevent *bev)
Variables
const struct bufferevent_ops bufferevent_ops_pair
Macro Definition Documentation
downcast
#define downcast (bev_pair) (&(bev_pair)->bev.bev)
Definition at line 66 of file bufferevent_pair.c.
Function Documentation
be_pair_destruct()
static void be_pair_destruct (struct bufferevent * bev) static
Definition at line 278 of file bufferevent_pair.c.
{
    struct bufferevent_pair *bev_p = upcast(bev);
    /* Transfer ownership of the lock into partner, otherwise we will use
     * already free'd lock during freeing second bev, see next example:
     *
     * bev1->own_lock = 1
     * bev2->own_lock = 0
     * bev2->lock = bev1->lock
     *
     * bufferevent_free(bev1) # refcnt == 0 -> unlink
     * bufferevent_free(bev2) # refcnt == 0 -> unlink
     *
     * event_base_free() -> finilizers -> EVTHREAD_FREE_LOCK(bev1->lock)
     *                                 -> BEV_LOCK(bev2->lock) <-- already freed
     *
     * Where bev1 == pair[0], bev2 == pair[1].
     */
    if (bev_p->unlinked_partner && bev_p->bev.own_lock) {
        bev_p->unlinked_partner->bev.own_lock = 1;
        bev_p->bev.own_lock = 0;
    }
    bev_p->unlinked_partner = NULL;
}
References bufferevent_pair::bev, bufferevent_private::own_lock, bufferevent_pair::unlinked_partner, and upcast().
be_pair_disable()
static int be_pair_disable (struct bufferevent * bev, short events) static
Definition at line 253 of file bufferevent_pair.c.
{
    if (events & EV_READ) {
        BEV_DEL_GENERIC_READ_TIMEOUT(bev);
    }
    if (events & EV_WRITE) {
        BEV_DEL_GENERIC_WRITE_TIMEOUT(bev);
    }
    return 0;
}
References bufferevent_pair::bev, BEV_DEL_GENERIC_READ_TIMEOUT, and BEV_DEL_GENERIC_WRITE_TIMEOUT.
be_pair_enable()
static int be_pair_enable (struct bufferevent * bufev, short events) static
Definition at line 225 of file bufferevent_pair.c.
{
    struct bufferevent_pair *bev_p = upcast(bufev);
    struct bufferevent_pair *partner = bev_p->partner;
    incref_and_lock(bufev);
    if (events & EV_READ) {
        BEV_RESET_GENERIC_READ_TIMEOUT(bufev);
    }
    if ((events & EV_WRITE) && evbuffer_get_length(bufev->output))
        BEV_RESET_GENERIC_WRITE_TIMEOUT(bufev);
    /* We're starting to read! Does the other side have anything to write?*/
    if ((events & EV_READ) && partner &&
        be_pair_wants_to_talk(partner, bev_p)) {
        be_pair_transfer(downcast(partner), bufev, 0);
    }
    /* We're starting to write! Does the other side want to read? */
    if ((events & EV_WRITE) && partner &&
        be_pair_wants_to_talk(bev_p, partner)) {
        be_pair_transfer(bufev, downcast(partner), 0);
    }
    decref_and_unlock(bufev);
    return 0;
}
References be_pair_transfer(), be_pair_wants_to_talk(), BEV_RESET_GENERIC_READ_TIMEOUT, BEV_RESET_GENERIC_WRITE_TIMEOUT, decref_and_unlock(), downcast, evbuffer_get_length(), incref_and_lock(), bufferevent_pair::partner, and upcast().
be_pair_flush()
static int be_pair_flush (struct bufferevent * bev, short iotype, enum bufferevent_flush_mode mode) static
Definition at line 305 of file bufferevent_pair.c.
{
    struct bufferevent_pair *bev_p = upcast(bev);
    struct bufferevent *partner;
    if (!bev_p->partner)
        return -1;
    if (mode == BEV_NORMAL)
        return 0;
    incref_and_lock(bev);
    partner = downcast(bev_p->partner);
    if ((iotype & EV_READ) != 0)
        be_pair_transfer(partner, bev, 1);
    if ((iotype & EV_WRITE) != 0)
        be_pair_transfer(bev, partner, 1);
    if (mode == BEV_FINISHED) {
        short what = BEV_EVENT_EOF;
        if (iotype & EV_READ)
            what |= BEV_EVENT_WRITING;
        if (iotype & EV_WRITE)
            what |= BEV_EVENT_READING;
        bufferevent_run_eventcb_(partner, what, 0);
    }
    decref_and_unlock(bev);
    return 0;
}
References be_pair_transfer(), bufferevent_pair::bev, bufferevent_run_eventcb_(), decref_and_unlock(), downcast, incref_and_lock(), bufferevent_pair::partner, and upcast().
be_pair_outbuf_cb()
static void be_pair_outbuf_cb (struct evbuffer * outbuf, const struct evbuffer_cb_info * info, void * arg) static
Definition at line 205 of file bufferevent_pair.c.
{
    struct bufferevent_pair *bev_pair = arg;
    struct bufferevent_pair *partner = bev_pair->partner;
    incref_and_lock(downcast(bev_pair));
    if (info->n_added > info->n_deleted && partner) {
        /* We got more data.  If the other side's reading, then
           hand it over. */
        if (be_pair_wants_to_talk(bev_pair, partner)) {
            be_pair_transfer(downcast(bev_pair), downcast(partner), 0);
        }
    }
    decref_and_unlock(downcast(bev_pair));
}
References be_pair_transfer(), be_pair_wants_to_talk(), decref_and_unlock(), downcast, incref_and_lock(), and bufferevent_pair::partner.
Referenced by bufferevent_pair_elt_new().
be_pair_transfer()
static void be_pair_transfer (struct bufferevent * src, struct bufferevent * dst, int ignore_wm) static
Definition at line 153 of file bufferevent_pair.c.
{
    size_t dst_size;
    size_t n;
    evbuffer_unfreeze(src->output, 1);
    evbuffer_unfreeze(dst->input, 0);
    if (dst->wm_read.high) {
        dst_size = evbuffer_get_length(dst->input);
        if (dst_size < dst->wm_read.high) {
            n = dst->wm_read.high - dst_size;
            evbuffer_remove_buffer(src->output, dst->input, n);
        } else {
            if (!ignore_wm)
                goto done;
            n = evbuffer_get_length(src->output);
            evbuffer_add_buffer(dst->input, src->output);
        }
    } else {
        n = evbuffer_get_length(src->output);
        evbuffer_add_buffer(dst->input, src->output);
    }
    if (n) {
        BEV_RESET_GENERIC_READ_TIMEOUT(dst);
        if (evbuffer_get_length(dst->output))
            BEV_RESET_GENERIC_WRITE_TIMEOUT(dst);
        else
            BEV_DEL_GENERIC_WRITE_TIMEOUT(dst);
    }
    bufferevent_trigger_nolock_(dst, EV_READ, 0);
    bufferevent_trigger_nolock_(src, EV_WRITE, 0);
done:
    evbuffer_freeze(src->output, 1);
    evbuffer_freeze(dst->input, 0);
}
References BEV_DEL_GENERIC_WRITE_TIMEOUT, BEV_RESET_GENERIC_READ_TIMEOUT, BEV_RESET_GENERIC_WRITE_TIMEOUT, bufferevent_trigger_nolock_(), evbuffer_add_buffer(), evbuffer_freeze(), evbuffer_get_length(), evbuffer_remove_buffer(), and evbuffer_unfreeze().
Referenced by be_pair_enable(), be_pair_flush(), and be_pair_outbuf_cb().
be_pair_unlink()
static void be_pair_unlink (struct bufferevent * bev) static
Definition at line 265 of file bufferevent_pair.c.
{
    struct bufferevent_pair *bev_p = upcast(bev);
    if (bev_p->partner) {
        bev_p->unlinked_partner = bev_p->partner;
        bev_p->partner->partner = NULL;
        bev_p->partner = NULL;
    }
}
References bufferevent_pair::bev, bufferevent_pair::partner, bufferevent_pair::unlinked_partner, and upcast().
be_pair_wants_to_talk()
static int be_pair_wants_to_talk (struct bufferevent_pair * src, struct bufferevent_pair * dst) inline static
Definition at line 195 of file bufferevent_pair.c.
{
    return (downcast(src)->enabled & EV_WRITE) &&
        (downcast(dst)->enabled & EV_READ) &&
        !dst->bev.read_suspended &&
        evbuffer_get_length(downcast(src)->output);
}
References bufferevent_pair::bev, downcast, evbuffer_get_length(), and bufferevent_private::read_suspended.
Referenced by be_pair_enable(), and be_pair_outbuf_cb().
bufferevent_pair_elt_new()
static struct bufferevent_pair * bufferevent_pair_elt_new (struct event_base * base, int options) static
Definition at line 93 of file bufferevent_pair.c.
{
    struct bufferevent_pair *bufev;
    if (! (bufev = mm_calloc(1, sizeof(struct bufferevent_pair))))
        return NULL;
    if (bufferevent_init_common_(&bufev->bev, base, &bufferevent_ops_pair,
        options)) {
        mm_free(bufev);
        return NULL;
    }
    if (!evbuffer_add_cb(bufev->bev.bev.output, be_pair_outbuf_cb, bufev)) {
        bufferevent_free(downcast(bufev));
        return NULL;
    }
    bufferevent_init_generic_timeout_cbs_(&bufev->bev.bev);
    return bufev;
}
References be_pair_outbuf_cb(), bufferevent_private::bev, bufferevent_pair::bev, bufferevent_free(), bufferevent_init_common_(), bufferevent_init_generic_timeout_cbs_(), bufferevent_ops_pair, downcast, evbuffer_add_cb(), mm_calloc, and mm_free.
Referenced by bufferevent_pair_new().
bufferevent_pair_get_partner()
struct bufferevent * bufferevent_pair_get_partner (struct bufferevent * bev)
Definition at line 340 of file bufferevent_pair.c.
{
    struct bufferevent_pair *bev_p;
    struct bufferevent *partner = NULL;
    bev_p = upcast(bev);
    if (! bev_p)
        return NULL;
    incref_and_lock(bev);
    if (bev_p->partner)
        partner = downcast(bev_p->partner);
    decref_and_unlock(bev);
    return partner;
}
References decref_and_unlock(), downcast, incref_and_lock(), bufferevent_pair::partner, and upcast().
bufferevent_pair_new()
int bufferevent_pair_new (struct event_base * base, int options, struct bufferevent * pair[2])
Definition at line 115 of file bufferevent_pair.c.
{
    struct bufferevent_pair *bufev1 = NULL, *bufev2 = NULL;
    int tmp_options;
    options |= BEV_OPT_DEFER_CALLBACKS;
    tmp_options = options & ~BEV_OPT_THREADSAFE;
    bufev1 = bufferevent_pair_elt_new(base, options);
    if (!bufev1)
        return -1;
    bufev2 = bufferevent_pair_elt_new(base, tmp_options);
    if (!bufev2) {
        bufferevent_free(downcast(bufev1));
        return -1;
    }
    if (options & BEV_OPT_THREADSAFE) {
        /*XXXX check return */
        bufferevent_enable_locking_(downcast(bufev2), bufev1->bev.lock);
    }
    bufev1->partner = bufev2;
    bufev2->partner = bufev1;
    evbuffer_freeze(downcast(bufev1)->input, 0);
    evbuffer_freeze(downcast(bufev1)->output, 1);
    evbuffer_freeze(downcast(bufev2)->input, 0);
    evbuffer_freeze(downcast(bufev2)->output, 1);
    pair[0] = downcast(bufev1);
    pair[1] = downcast(bufev2);
    return 0;
}
References bufferevent_pair::bev, bufferevent_enable_locking_(), bufferevent_free(), bufferevent_pair_elt_new(), downcast, evbuffer_freeze(), bufferevent_private::lock, and bufferevent_pair::partner.
decref_and_unlock()
static void decref_and_unlock (struct bufferevent * b) inline static
Definition at line 79 of file bufferevent_pair.c.
{
    struct bufferevent_pair *bevp = upcast(b);
    if (bevp->partner)
        bufferevent_decref_and_unlock_(downcast(bevp->partner));
    bufferevent_decref_and_unlock_(b);
}
References bufferevent_decref_and_unlock_(), downcast, bufferevent_pair::partner, and upcast().
Referenced by be_pair_enable(), be_pair_flush(), be_pair_outbuf_cb(), and bufferevent_pair_get_partner().
incref_and_lock()
static void incref_and_lock (struct bufferevent * b) inline static
Definition at line 69 of file bufferevent_pair.c.
{
    struct bufferevent_pair *bevp;
    bufferevent_incref_and_lock_(b);
    bevp = upcast(b);
    if (bevp->partner)
        bufferevent_incref_and_lock_(downcast(bevp->partner));
}
References bufferevent_incref_and_lock_(), downcast, bufferevent_pair::partner, and upcast().
Referenced by be_pair_enable(), be_pair_flush(), be_pair_outbuf_cb(), and bufferevent_pair_get_partner().
upcast()
static struct bufferevent_pair * upcast (struct bufferevent * bev) inline static
Definition at line 56 of file bufferevent_pair.c.
{
    struct bufferevent_pair *bev_p;
    if (!BEV_IS_PAIR(bev))
        return NULL;
    bev_p = EVUTIL_UPCAST(bev, struct bufferevent_pair, bev.bev);
    EVUTIL_ASSERT(BEV_IS_PAIR(&bev_p->bev.bev));
    return bev_p;
}
References bufferevent_private::bev, bufferevent_pair::bev, BEV_IS_PAIR, EVUTIL_ASSERT, and EVUTIL_UPCAST.
Referenced by be_pair_destruct(), be_pair_enable(), be_pair_flush(), be_pair_unlink(), bufferevent_pair_get_partner(), decref_and_unlock(), and incref_and_lock().
Variable Documentation
bufferevent_ops_pair
const struct bufferevent_ops bufferevent_ops_pair
Initial value:
= {
    "pair_elt",
    evutil_offsetof(struct bufferevent_pair, bev.bev),
    be_pair_enable,
    be_pair_disable,
    be_pair_unlink,
    be_pair_destruct,
    bufferevent_generic_adj_timeouts_,
    be_pair_flush,
    NULL,
}
Definition at line 355 of file bufferevent_pair.c.
Referenced by bufferevent_pair_elt_new().