libdogecoin: src/buffer.c File Reference
buffer.c File Reference
#include <dogecoin/buffer.h>
#include <dogecoin/mem.h>
Functions
int buffer_equal (const void *a_, const void *b_)
This function compares two buffers to see if they are equal.
void buffer_free (void *struct_buffer)
This function frees the memory allocated for the specified buffer.
struct buffer * buffer_copy (const void *data, size_t data_len)
This function creates a new empty buffer and copies data from the old buffer.
Function Documentation
buffer_copy()
struct buffer * buffer_copy (const void * data, size_t data_len)
This function creates a new empty buffer and copies data from the old buffer.
Parameters
data The data to be copied.
data_len The length of the data to be copied.
Returns
The pointer to the new buffer.
Definition at line 61 of file buffer.c.
{
    struct buffer* buf;
    buf = dogecoin_calloc(1, sizeof(*buf));
    if (!buf) {
        goto err_out;
    }
    buf->p = dogecoin_calloc(1, data_len);
    if (!buf->p) {
        goto err_out_free;
    }
    memcpy_safe(buf->p, data, data_len);
    buf->len = data_len;
    return buf;
err_out_free:
    dogecoin_free(buf);
err_out:
    return NULL;
}
References dogecoin_calloc(), dogecoin_free(), buffer::len, memcpy_safe(), and buffer::p.
buffer_equal()
int buffer_equal (const void * a_, const void * b_)
This function compares two buffers to see if they are equal.
Parameters
a_ The reference buffer.
b_ The buffer to compare.
Returns
1 if buffers are equal, 0 otherwise.
Definition at line 21 of file buffer.c.
{
    const struct buffer* a = a_;
    const struct buffer* b = b_;
    if (a->len != b->len)
        return 0;
    return memcmp(a->p, b->p, a->len) == 0;
}
References buffer::len, and buffer::p.
buffer_free()
void buffer_free (void * struct_buffer)
This function frees the memory allocated for the specified buffer.
Parameters
struct_buffer The pointer to the buffer to be freed.
Returns
Nothing.
Definition at line 40 of file buffer.c.
{
    struct buffer* buf = struct_buffer;
    if (!buf) {
        return;
    }
    dogecoin_free(buf->p);
    dogecoin_free(buf);
}
References dogecoin_free(), and buffer::p.