libdogecoin: src/libevent/buffer_iocp.c File Reference
buffer_iocp.c File Reference
#include "event2/event-config.h"
#include "evconfig-private.h"
#include "event2/buffer.h"
#include "event2/buffer_compat.h"
#include "event2/util.h"
#include "event2/thread.h"
#include "util-internal.h"
#include "evthread-internal.h"
#include "evbuffer-internal.h"
#include "iocp-internal.h"
#include "mm-internal.h"
#include <winsock2.h>
#include <winerror.h>
#include <windows.h>
#include <stdio.h>
Data Structures
struct evbuffer_overlapped
Macros
#define MAX_WSABUFS 16
Functions
static struct evbuffer_overlapped * upcast_evbuffer (struct evbuffer *buf)
static void pin_release (struct evbuffer_overlapped *eo, unsigned flag)
void evbuffer_commit_read_ (struct evbuffer *evbuf, ev_ssize_t nBytes)
void evbuffer_commit_write_ (struct evbuffer *evbuf, ev_ssize_t nBytes)
struct evbuffer * evbuffer_overlapped_new_ (evutil_socket_t fd)
int evbuffer_launch_write_ (struct evbuffer *buf, ev_ssize_t at_most, struct event_overlapped *ol)
int evbuffer_launch_read_ (struct evbuffer *buf, size_t at_most, struct event_overlapped *ol)
evutil_socket_t evbuffer_overlapped_get_fd_ (struct evbuffer *buf)
void evbuffer_overlapped_set_fd_ (struct evbuffer *buf, evutil_socket_t fd)
Detailed Description
This module implements overlapped read and write functions for evbuffer objects on Windows.
Definition in file buffer_iocp.c.
Macro Definition Documentation
MAX_WSABUFS
#define MAX_WSABUFS 16
Definition at line 51 of file buffer_iocp.c.
Function Documentation
evbuffer_commit_read_()
void evbuffer_commit_read_ (struct evbuffer * evbuf, ev_ssize_t nBytes)
XXX document
Definition at line 98 of file buffer_iocp.c.
{
    struct evbuffer_overlapped *buf = upcast_evbuffer(evbuf);
    struct evbuffer_chain **chainp;
    size_t remaining, len;
    unsigned i;
    EVBUFFER_LOCK(evbuf);
    EVUTIL_ASSERT(buf->read_in_progress && !buf->write_in_progress);
    EVUTIL_ASSERT(nBytes >= 0); /* XXXX Can this be false? */
    evbuffer_unfreeze(evbuf, 0);
    chainp = evbuf->last_with_datap;
    if (!((*chainp)->flags & EVBUFFER_MEM_PINNED_R))
        chainp = &(*chainp)->next;
    remaining = nBytes;
    for (i = 0; remaining > 0 && i < (unsigned)buf->n_buffers; ++i) {
        EVUTIL_ASSERT(*chainp);
        len = buf->buffers[i].len;
        if (remaining < len)
            len = remaining;
        (*chainp)->off += len;
        evbuf->last_with_datap = chainp;
        remaining -= len;
        chainp = &(*chainp)->next;
    }
    pin_release(buf, EVBUFFER_MEM_PINNED_R);
    buf->read_in_progress = 0;
    evbuf->total_len += nBytes;
    evbuf->n_add_for_cb += nBytes;
    evbuffer_invoke_callbacks_(evbuf);
    evbuffer_decref_and_unlock_(evbuf);
}
References evbuffer_overlapped::buffers, evbuffer_decref_and_unlock_(), evbuffer_invoke_callbacks_(), EVBUFFER_LOCK, EVBUFFER_MEM_PINNED_R, evbuffer_unfreeze(), EVUTIL_ASSERT, evbuffer::last_with_datap, evbuffer::n_add_for_cb, evbuffer_overlapped::n_buffers, evbuffer_chain::next, pin_release(), evbuffer_overlapped::read_in_progress, evbuffer::total_len, upcast_evbuffer(), and evbuffer_overlapped::write_in_progress.
Referenced by read_complete().
evbuffer_commit_write_()
void evbuffer_commit_write_ (struct evbuffer * evbuf, ev_ssize_t nBytes)
Definition at line 139 of file buffer_iocp.c.
{
    struct evbuffer_overlapped *buf = upcast_evbuffer(evbuf);
    EVBUFFER_LOCK(evbuf);
    EVUTIL_ASSERT(buf->write_in_progress && !buf->read_in_progress);
    evbuffer_unfreeze(evbuf, 1);
    evbuffer_drain(evbuf, nBytes);
    pin_release(buf,EVBUFFER_MEM_PINNED_W);
    buf->write_in_progress = 0;
    evbuffer_decref_and_unlock_(evbuf);
}
References evbuffer_decref_and_unlock_(), evbuffer_drain(), EVBUFFER_LOCK, EVBUFFER_MEM_PINNED_W, evbuffer_unfreeze(), EVUTIL_ASSERT, pin_release(), evbuffer_overlapped::read_in_progress, upcast_evbuffer(), and evbuffer_overlapped::write_in_progress.
Referenced by write_complete().
evbuffer_launch_read_()
int evbuffer_launch_read_ (struct evbuffer * buf, size_t n, struct event_overlapped * ol)
Start reading data onto the end of an overlapped evbuffer.
An evbuffer can only have one read pending at a time. While the read is in progress, no other data may be added to the end of the buffer. The buffer must be created with event_overlapped_init_(). evbuffer_commit_read_() must be called in the completion callback.
Parameters
buf The buffer to read onto
n The number of bytes to try to read.
ol Overlapped object with associated completion callback.
Returns
0 on success, -1 on error.
Definition at line 246 of file buffer_iocp.c.
{
    struct evbuffer_overlapped *buf_o = upcast_evbuffer(buf);
    int r = -1, i;
    int nvecs;
    int npin=0;
    struct evbuffer_chain *chain=NULL, **chainp;
    DWORD bytesRead;
    DWORD flags = 0;
    struct evbuffer_iovec vecs[MAX_WSABUFS];
    if (!buf_o)
        return -1;
    EVBUFFER_LOCK(buf);
    EVUTIL_ASSERT(!buf_o->write_in_progress);
    if (buf->freeze_end || buf_o->read_in_progress)
        goto done;
    buf_o->first_pinned = NULL;
    buf_o->n_buffers = 0;
    memset(buf_o->buffers, 0, sizeof(buf_o->buffers));
    if (evbuffer_expand_fast_(buf, at_most, MAX_WSABUFS) == -1)
        goto done;
    evbuffer_freeze(buf, 0);
    nvecs = evbuffer_read_setup_vecs_(buf, at_most,
        vecs, MAX_WSABUFS, &chainp, 1);
    for (i=0;i<nvecs;++i) {
        WSABUF_FROM_EVBUFFER_IOV(
            &buf_o->buffers[i],
            &vecs[i]);
    }
    buf_o->n_buffers = nvecs;
    buf_o->first_pinned = chain = *chainp;
    npin=0;
    for ( ; chain; chain = chain->next) {
        evbuffer_chain_pin_(chain, EVBUFFER_MEM_PINNED_R);
        ++npin;
    }
    EVUTIL_ASSERT(npin == nvecs);
    evbuffer_incref_(buf);
    if (WSARecv(buf_o->fd, buf_o->buffers, nvecs, &bytesRead, &flags,
            &ol->overlapped, NULL)) {
        int error = WSAGetLastError();
        if (error != WSA_IO_PENDING) {
            /* An actual error. */
            pin_release(buf_o, EVBUFFER_MEM_PINNED_R);
            evbuffer_unfreeze(buf, 0);
            evbuffer_free(buf); /* decref */
            goto done;
        }
    }
    buf_o->read_in_progress = 1;
    r = 0;
done:
    EVBUFFER_UNLOCK(buf);
    return r;
}
References evbuffer_overlapped::buffers, evbuffer_chain_pin_(), evbuffer_expand_fast_(), evbuffer_free(), evbuffer_freeze(), evbuffer_incref_(), EVBUFFER_LOCK, EVBUFFER_MEM_PINNED_R, evbuffer_read_setup_vecs_(), evbuffer_unfreeze(), EVBUFFER_UNLOCK, EVUTIL_ASSERT, evbuffer_overlapped::fd, evbuffer_overlapped::first_pinned, evbuffer_chain::flags, evbuffer::freeze_end, MAX_WSABUFS, evbuffer_overlapped::n_buffers, evbuffer_chain::next, pin_release(), evbuffer_overlapped::read_in_progress, upcast_evbuffer(), evbuffer_overlapped::write_in_progress, and WSABUF_FROM_EVBUFFER_IOV.
Referenced by bev_async_consider_reading().
evbuffer_launch_write_()
int evbuffer_launch_write_ (struct evbuffer * buf, ev_ssize_t n, struct event_overlapped * ol)
Start writing data from the start of an evbuffer.
An evbuffer can only have one write pending at a time. While the write is in progress, no other data may be removed from the front of the buffer. The buffer must be created with event_overlapped_init_(). evbuffer_commit_write_() must be called in the completion callback.
Parameters
buf The buffer to read onto
n The number of bytes to try to read.
ol Overlapped object with associated completion callback.
Returns
0 on success, -1 on error.
Definition at line 172 of file buffer_iocp.c.
{
    struct evbuffer_overlapped *buf_o = upcast_evbuffer(buf);
    int r = -1;
    int i;
    struct evbuffer_chain *chain;
    DWORD bytesSent;
    if (!buf) {
        /* No buffer, or it isn't overlapped */
        return -1;
    }
    EVBUFFER_LOCK(buf);
    EVUTIL_ASSERT(!buf_o->read_in_progress);
    if (buf->freeze_start || buf_o->write_in_progress)
        goto done;
    if (!buf->total_len) {
        /* Nothing to write */
        r = 0;
        goto done;
    } else if (at_most < 0 || (size_t)at_most > buf->total_len) {
        at_most = buf->total_len;
    }
    evbuffer_freeze(buf, 1);
    buf_o->first_pinned = NULL;
    buf_o->n_buffers = 0;
    memset(buf_o->buffers, 0, sizeof(buf_o->buffers));
    chain = buf_o->first_pinned = buf->first;
    for (i=0; i < MAX_WSABUFS && chain; ++i, chain=chain->next) {
        WSABUF *b = &buf_o->buffers[i];
        b->buf = (char*)( chain->buffer + chain->misalign );
        evbuffer_chain_pin_(chain, EVBUFFER_MEM_PINNED_W);
        if ((size_t)at_most > chain->off) {
            /* XXXX Cast is safe for now, since win32 has no
               mmaped chains.  But later, we need to have this
               add more WSAbufs if chain->off is greater than
               ULONG_MAX */
            b->len = (unsigned long)chain->off;
            at_most -= chain->off;
        } else {
            b->len = (unsigned long)at_most;
            ++i;
            break;
        }
    }
    buf_o->n_buffers = i;
    evbuffer_incref_(buf);
    if (WSASend(buf_o->fd, buf_o->buffers, i, &bytesSent, 0,
        &ol->overlapped, NULL)) {
        int error = WSAGetLastError();
        if (error != WSA_IO_PENDING) {
            /* An actual error. */
            pin_release(buf_o, EVBUFFER_MEM_PINNED_W);
            evbuffer_unfreeze(buf, 1);
            evbuffer_free(buf); /* decref */
            goto done;
        }
    }
    buf_o->write_in_progress = 1;
    r = 0;
done:
    EVBUFFER_UNLOCK(buf);
    return r;
}
References evbuffer_chain::buffer, evbuffer_overlapped::buffers, evbuffer_chain_pin_(), evbuffer_free(), evbuffer_freeze(), evbuffer_incref_(), EVBUFFER_LOCK, EVBUFFER_MEM_PINNED_W, evbuffer_unfreeze(), EVBUFFER_UNLOCK, EVUTIL_ASSERT, evbuffer_overlapped::fd, evbuffer::first, evbuffer_overlapped::first_pinned, evbuffer::freeze_start, MAX_WSABUFS, evbuffer_chain::misalign, evbuffer_overlapped::n_buffers, evbuffer_chain::next, evbuffer_chain::off, pin_release(), evbuffer_overlapped::read_in_progress, evbuffer::total_len, upcast_evbuffer(), and evbuffer_overlapped::write_in_progress.
Referenced by bev_async_consider_writing().
evbuffer_overlapped_get_fd_()
evutil_socket_t evbuffer_overlapped_get_fd_ (struct evbuffer * buf)
XXXX Document (nickm)
Definition at line 312 of file buffer_iocp.c.
{
    struct evbuffer_overlapped *buf_o = upcast_evbuffer(buf);
    return buf_o ? buf_o->fd : -1;
}
References evbuffer_overlapped::fd, and upcast_evbuffer().
Referenced by be_async_ctrl(), be_async_destruct(), bev_async_set_wsa_error(), and connect_complete().
evbuffer_overlapped_new_()
struct evbuffer * evbuffer_overlapped_new_ (evutil_socket_t fd)
Allocate and return a new evbuffer that supports overlapped IO on a given socket. The socket must be associated with an IO completion port using event_iocp_port_associate_.
Definition at line 153 of file buffer_iocp.c.
{
    struct evbuffer_overlapped *evo;
    evo = mm_calloc(1, sizeof(struct evbuffer_overlapped));
    if (!evo)
        return NULL;
    LIST_INIT(&evo->buffer.callbacks);
    evo->buffer.refcnt = 1;
    evo->buffer.last_with_datap = &evo->buffer.first;
    evo->buffer.is_overlapped = 1;
    evo->fd = fd;
    return &evo->buffer;
}
References evbuffer_overlapped::buffer, evbuffer_overlapped::fd, evbuffer::first, evbuffer::last_with_datap, mm_calloc, and evbuffer::refcnt.
Referenced by bufferevent_async_new_().
evbuffer_overlapped_set_fd_()
void evbuffer_overlapped_set_fd_ (struct evbuffer * buf, evutil_socket_t fd)
Definition at line 319 of file buffer_iocp.c.
{
    struct evbuffer_overlapped *buf_o = upcast_evbuffer(buf);
    EVBUFFER_LOCK(buf);
    /* XXX is this right?, should it cancel current I/O operations? */
    if (buf_o)
        buf_o->fd = fd;
    EVBUFFER_UNLOCK(buf);
}
References EVBUFFER_LOCK, EVBUFFER_UNLOCK, evbuffer_overlapped::fd, and upcast_evbuffer().
Referenced by be_async_ctrl(), and be_async_destruct().
pin_release()
static void pin_release (struct evbuffer_overlapped * eo, unsigned flag) static
Unpin all the chains noted as pinned in 'eo'.
Definition at line 84 of file buffer_iocp.c.
{
    int i;
    struct evbuffer_chain *next, *chain = eo->first_pinned;
    for (i = 0; i < eo->n_buffers; ++i) {
        EVUTIL_ASSERT(chain);
        next = chain->next;
        evbuffer_chain_unpin_(chain, flag);
        chain = next;
    }
}
References evbuffer_chain_unpin_(), EVUTIL_ASSERT, evbuffer_overlapped::first_pinned, evbuffer_overlapped::n_buffers, and evbuffer_chain::next.
Referenced by evbuffer_commit_read_(), evbuffer_commit_write_(), evbuffer_launch_read_(), and evbuffer_launch_write_().
upcast_evbuffer()
static struct evbuffer_overlapped * upcast_evbuffer (struct evbuffer * buf) inline static
Given an evbuffer, return the correponding evbuffer structure, or NULL if the evbuffer isn't overlapped.
Definition at line 75 of file buffer_iocp.c.
{
    if (!buf || !buf->is_overlapped)
        return NULL;
    return EVUTIL_UPCAST(buf, struct evbuffer_overlapped, buffer);
}
References EVUTIL_UPCAST.
Referenced by evbuffer_commit_read_(), evbuffer_commit_write_(), evbuffer_launch_read_(), evbuffer_launch_write_(), evbuffer_overlapped_get_fd_(), and evbuffer_overlapped_set_fd_().