libdogecoin: src/libevent/bufferevent-internal.h File Reference
bufferevent-internal.h File Reference
#include "event2/event-config.h"
#include "event2/event_struct.h"
#include "evconfig-private.h"
#include "event2/util.h"
#include "defer-internal.h"
#include "evthread-internal.h"
#include "event2/thread.h"
#include "ratelim-internal.h"
#include "event2/bufferevent_struct.h"
#include "ipv6-internal.h"
Data Structures
struct bufferevent_rate_limit_group
struct bufferevent_rate_limit
struct bufferevent_private
union bufferevent_ctrl_data
struct bufferevent_ops
Macros
#define BEV_SUSPEND_WM 0x01
#define BEV_SUSPEND_BW 0x02
#define BEV_SUSPEND_BW_GROUP 0x04
#define BEV_SUSPEND_LOOKUP 0x08
#define BEV_SUSPEND_FILT_READ 0x10
#define BEV_IS_SOCKET(bevp) ((bevp)->be_ops == &bufferevent_ops_socket)
#define BEV_IS_FILTER(bevp) ((bevp)->be_ops == &bufferevent_ops_filter)
#define BEV_IS_PAIR(bevp) ((bevp)->be_ops == &bufferevent_ops_pair)
#define BEV_IS_OPENSSL(bevp) 0
#define BEV_IS_ASYNC(bevp) 0
#define bufferevent_wm_suspend_read(b) bufferevent_suspend_read_((b), BEV_SUSPEND_WM)
#define bufferevent_wm_unsuspend_read(b) bufferevent_unsuspend_read_((b), BEV_SUSPEND_WM)
#define bufferevent_incref_(bufev) bufferevent_incref(bufev)
#define bufferevent_decref_(bufev) bufferevent_decref(bufev)
#define BEV_RESET_GENERIC_READ_TIMEOUT(bev)
#define BEV_RESET_GENERIC_WRITE_TIMEOUT(bev)
#define BEV_DEL_GENERIC_READ_TIMEOUT(bev) event_del(&(bev)->ev_read)
#define BEV_DEL_GENERIC_WRITE_TIMEOUT(bev) event_del(&(bev)->ev_write)
#define BEV_UPCAST(b) EVUTIL_UPCAST((b), struct bufferevent_private, bev)
#define BEV_LOCK(b)
#define BEV_UNLOCK(b)
Typedefs
typedef ev_uint16_t bufferevent_suspend_flags
Enumerations
enum bufferevent_ctrl_op { BEV_CTRL_SET_FD , BEV_CTRL_GET_FD , BEV_CTRL_GET_UNDERLYING , BEV_CTRL_CANCEL_ALL }
Functions
EVENT2_EXPORT_SYMBOL int bufferevent_init_common_ (struct bufferevent_private *, struct event_base *, const struct bufferevent_ops *, enum bufferevent_options options)
EVENT2_EXPORT_SYMBOL void bufferevent_suspend_read_ (struct bufferevent *bufev, bufferevent_suspend_flags what)
EVENT2_EXPORT_SYMBOL void bufferevent_unsuspend_read_ (struct bufferevent *bufev, bufferevent_suspend_flags what)
void bufferevent_suspend_write_ (struct bufferevent *bufev, bufferevent_suspend_flags what)
void bufferevent_unsuspend_write_ (struct bufferevent *bufev, bufferevent_suspend_flags what)
EVENT2_EXPORT_SYMBOL int bufferevent_disable_hard_ (struct bufferevent *bufev, short event)
EVENT2_EXPORT_SYMBOL int bufferevent_enable_locking_ (struct bufferevent *bufev, void *lock)
EVENT2_EXPORT_SYMBOL void bufferevent_incref_and_lock_ (struct bufferevent *bufev)
EVENT2_EXPORT_SYMBOL int bufferevent_decref_and_unlock_ (struct bufferevent *bufev)
EVENT2_EXPORT_SYMBOL void bufferevent_run_readcb_ (struct bufferevent *bufev, int options)
EVENT2_EXPORT_SYMBOL void bufferevent_run_writecb_ (struct bufferevent *bufev, int options)
EVENT2_EXPORT_SYMBOL void bufferevent_run_eventcb_ (struct bufferevent *bufev, short what, int options)
static void bufferevent_trigger_nolock_ (struct bufferevent *bufev, short iotype, int options)
EVENT2_EXPORT_SYMBOL int bufferevent_add_event_ (struct event *ev, const struct timeval *tv)
EVENT2_EXPORT_SYMBOL void bufferevent_init_generic_timeout_cbs_ (struct bufferevent *bev)
EVENT2_EXPORT_SYMBOL int bufferevent_generic_adj_timeouts_ (struct bufferevent *bev)
EVENT2_EXPORT_SYMBOL int bufferevent_generic_adj_existing_timeouts_ (struct bufferevent *bev)
EVENT2_EXPORT_SYMBOL enum bufferevent_options bufferevent_get_options_ (struct bufferevent *bev)
EVENT2_EXPORT_SYMBOL const struct sockaddr * bufferevent_socket_get_conn_address_ (struct bufferevent *bev)
EVENT2_EXPORT_SYMBOL void bufferevent_socket_set_conn_address_fd_ (struct bufferevent *bev, evutil_socket_t fd)
EVENT2_EXPORT_SYMBOL void bufferevent_socket_set_conn_address_ (struct bufferevent *bev, struct sockaddr *addr, size_t addrlen)
EVENT2_EXPORT_SYMBOL int bufferevent_decrement_write_buckets_ (struct bufferevent_private *bev, ev_ssize_t bytes)
EVENT2_EXPORT_SYMBOL int bufferevent_decrement_read_buckets_ (struct bufferevent_private *bev, ev_ssize_t bytes)
EVENT2_EXPORT_SYMBOL ev_ssize_t bufferevent_get_read_max_ (struct bufferevent_private *bev)
EVENT2_EXPORT_SYMBOL ev_ssize_t bufferevent_get_write_max_ (struct bufferevent_private *bev)
int bufferevent_ratelim_init_ (struct bufferevent_private *bev)
Variables
const struct bufferevent_ops bufferevent_ops_socket
const struct bufferevent_ops bufferevent_ops_filter
const struct bufferevent_ops bufferevent_ops_pair
Macro Definition Documentation
BEV_DEL_GENERIC_READ_TIMEOUT
#define BEV_DEL_GENERIC_READ_TIMEOUT (bev) event_del(&(bev)->ev_read)
Definition at line 470 of file bufferevent-internal.h.
BEV_DEL_GENERIC_WRITE_TIMEOUT
#define BEV_DEL_GENERIC_WRITE_TIMEOUT (bev) event_del(&(bev)->ev_write)
Definition at line 472 of file bufferevent-internal.h.
BEV_IS_ASYNC
#define BEV_IS_ASYNC (bevp) 0
Definition at line 320 of file bufferevent-internal.h.
BEV_IS_FILTER
#define BEV_IS_FILTER (bevp) ((bevp)->be_ops == &bufferevent_ops_filter)
Definition at line 306 of file bufferevent-internal.h.
BEV_IS_OPENSSL
#define BEV_IS_OPENSSL (bevp) 0
Definition at line 313 of file bufferevent-internal.h.
BEV_IS_PAIR
#define BEV_IS_PAIR (bevp) ((bevp)->be_ops == &bufferevent_ops_pair)
Definition at line 307 of file bufferevent-internal.h.
BEV_IS_SOCKET
#define BEV_IS_SOCKET (bevp) ((bevp)->be_ops == &bufferevent_ops_socket)
Definition at line 305 of file bufferevent-internal.h.
BEV_LOCK
#define BEV_LOCK (b)
Value:
        do {                        \
        struct bufferevent_private *locking =  BEV_UPCAST(b);   \
        EVLOCK_LOCK(locking->lock, 0);              \
    } while (0)
Internal: Grab the lock (if any) on a bufferevent
Definition at line 485 of file bufferevent-internal.h.
BEV_RESET_GENERIC_READ_TIMEOUT
#define BEV_RESET_GENERIC_READ_TIMEOUT (bev)
Value:
    do {                                \
        if (evutil_timerisset(&(bev)->timeout_read))        \
            event_add(&(bev)->ev_read, &(bev)->timeout_read); \
    } while (0)
Internal use: We have just successfully read data into an inbuf, so reset the read timeout (if any).
Definition at line 458 of file bufferevent-internal.h.
BEV_RESET_GENERIC_WRITE_TIMEOUT
#define BEV_RESET_GENERIC_WRITE_TIMEOUT (bev)
Value:
    do {                                \
        if (evutil_timerisset(&(bev)->timeout_write))       \
            event_add(&(bev)->ev_write, &(bev)->timeout_write); \
    } while (0)
Internal use: We have just successfully written data from an inbuf, so reset the read timeout (if any).
Definition at line 465 of file bufferevent-internal.h.
BEV_SUSPEND_BW
#define BEV_SUSPEND_BW 0x02
Definition at line 67 of file bufferevent-internal.h.
BEV_SUSPEND_BW_GROUP
#define BEV_SUSPEND_BW_GROUP 0x04
Definition at line 69 of file bufferevent-internal.h.
BEV_SUSPEND_FILT_READ
#define BEV_SUSPEND_FILT_READ 0x10
Definition at line 75 of file bufferevent-internal.h.
BEV_SUSPEND_LOOKUP
#define BEV_SUSPEND_LOOKUP 0x08
Definition at line 72 of file bufferevent-internal.h.
BEV_SUSPEND_WM
#define BEV_SUSPEND_WM 0x01
Definition at line 65 of file bufferevent-internal.h.
BEV_UNLOCK
#define BEV_UNLOCK (b)
Value:
        do {                        \
        struct bufferevent_private *locking =  BEV_UPCAST(b);   \
        EVLOCK_UNLOCK(locking->lock, 0);            \
    } while (0)
Internal: Release the lock (if any) on a bufferevent
Definition at line 491 of file bufferevent-internal.h.
BEV_UPCAST
#define BEV_UPCAST (b) EVUTIL_UPCAST((b), struct bufferevent_private, bev)
Internal: Given a bufferevent, return its corresponding bufferevent_private.
Definition at line 478 of file bufferevent-internal.h.
bufferevent_decref_
#define bufferevent_decref_ (bufev) bufferevent_decref(bufev)
Internal: backwards compat macro for the now public function Decrement the reference count on bufev. Returns 1 if it freed the bufferevent.
Definition at line 377 of file bufferevent-internal.h.
bufferevent_incref_
#define bufferevent_incref_ (bufev) bufferevent_incref(bufev)
Internal: backwards compat macro for the now public function Increment the reference count on bufev.
Definition at line 369 of file bufferevent-internal.h.
bufferevent_wm_suspend_read
#define bufferevent_wm_suspend_read (b) bufferevent_suspend_read_((b), BEV_SUSPEND_WM)
Definition at line 343 of file bufferevent-internal.h.
bufferevent_wm_unsuspend_read
#define bufferevent_wm_unsuspend_read (b) bufferevent_unsuspend_read_((b), BEV_SUSPEND_WM)
Definition at line 345 of file bufferevent-internal.h.
Typedef Documentation
bufferevent_suspend_flags
typedef ev_uint16_t bufferevent_suspend_flags
Definition at line 77 of file bufferevent-internal.h.
Enumeration Type Documentation
bufferevent_ctrl_op
enum bufferevent_ctrl_op
Possible operations for a control callback.
Enumerator
BEV_CTRL_SET_FD
BEV_CTRL_GET_FD
BEV_CTRL_GET_UNDERLYING
BEV_CTRL_CANCEL_ALL
Definition at line 236 of file bufferevent-internal.h.
{
    BEV_CTRL_SET_FD,
    BEV_CTRL_GET_FD,
    BEV_CTRL_GET_UNDERLYING,
    BEV_CTRL_CANCEL_ALL
};
Function Documentation
bufferevent_add_event_()
EVENT2_EXPORT_SYMBOL int bufferevent_add_event_ (struct event * ev, const struct timeval * tv)
Internal: Add the event 'ev' with timeout tv, unless tv is set to 0, in which case add ev with no timeout.
Definition at line 1016 of file bufferevent.c.
{
    if (!evutil_timerisset(tv))
        return event_add(ev, NULL);
    else
        return event_add(ev, tv);
}
References event_add().
Referenced by be_openssl_outbuf_cb(), be_socket_enable(), bufferevent_generic_adj_existing_timeouts_(), bufferevent_socket_outbuf_cb(), set_open_callbacks(), start_reading(), and start_writing().
bufferevent_decref_and_unlock_()
EVENT2_EXPORT_SYMBOL int bufferevent_decref_and_unlock_ (struct bufferevent * bufev)
Internal: Drop the reference count on bufev, freeing as necessary, and unlocking it otherwise. Returns 1 if it freed the bufferevent.
Definition at line 706 of file bufferevent.c.
{
    struct bufferevent_private *bufev_private = BEV_UPCAST(bufev);
    int n_cbs = 0;
#define MAX_CBS 16
    struct event_callback *cbs[MAX_CBS];
    EVUTIL_ASSERT(bufev_private->refcnt > 0);
    if (--bufev_private->refcnt) {
        BEV_UNLOCK(bufev);
        return 0;
    }
    if (bufev->be_ops->unlink)
        bufev->be_ops->unlink(bufev);
    /* Okay, we're out of references. Let's finalize this once all the
     * callbacks are done running. */
    cbs[0] = &bufev->ev_read.ev_evcallback;
    cbs[1] = &bufev->ev_write.ev_evcallback;
    cbs[2] = &bufev_private->deferred;
    n_cbs = 3;
    if (bufev_private->rate_limiting) {
        struct event *e = &bufev_private->rate_limiting->refill_bucket_event;
        if (event_initialized(e))
            cbs[n_cbs++] = &e->ev_evcallback;
    }
    n_cbs += evbuffer_get_callbacks_(bufev->input, cbs+n_cbs, MAX_CBS-n_cbs);
    n_cbs += evbuffer_get_callbacks_(bufev->output, cbs+n_cbs, MAX_CBS-n_cbs);
    event_callback_finalize_many_(bufev->ev_base, n_cbs, cbs,
        bufferevent_finalize_cb_);
#undef MAX_CBS
    BEV_UNLOCK(bufev);
    return 1;
}
References BEV_UNLOCK, BEV_UPCAST, bufferevent_finalize_cb_(), bufferevent_private::deferred, evbuffer_get_callbacks_(), event_callback_finalize_many_(), event_initialized(), EVUTIL_ASSERT, MAX_CBS, bufferevent_private::rate_limiting, bufferevent_private::refcnt, and bufferevent_rate_limit::refill_bucket_event.
Referenced by be_async_inbuf_callback(), be_async_outbuf_callback(), be_filter_flush(), be_openssl_handshakeeventcb(), be_openssl_readeventcb(), be_openssl_writeeventcb(), bufferevent_connect_getaddrinfo_cb(), bufferevent_decref(), bufferevent_enable(), bufferevent_filtered_outbuf_cb(), bufferevent_free(), bufferevent_generic_read_timeout_cb(), bufferevent_generic_write_timeout_cb(), bufferevent_readcb(), bufferevent_run_deferred_callbacks_locked(), bufferevent_run_deferred_callbacks_unlocked(), bufferevent_socket_connect(), bufferevent_trigger(), bufferevent_trigger_event(), bufferevent_unlock(), bufferevent_writecb(), connect_complete(), decref_and_unlock(), read_complete(), and write_complete().
bufferevent_decrement_read_buckets_()
EVENT2_EXPORT_SYMBOL int bufferevent_decrement_read_buckets_ (struct bufferevent_private * bev, ev_ssize_t bytes)
Definition at line 273 of file bufferevent_ratelim.c.
{
    /* XXXXX Make sure all users of this function check its return value */
    int r = 0;
    /* need to hold lock on bev */
    if (!bev->rate_limiting)
        return 0;
    if (bev->rate_limiting->cfg) {
        bev->rate_limiting->limit.read_limit -= bytes;
        if (bev->rate_limiting->limit.read_limit <= 0) {
            bufferevent_suspend_read_(&bev->bev, BEV_SUSPEND_BW);
            if (event_add(&bev->rate_limiting->refill_bucket_event,
                &bev->rate_limiting->cfg->tick_timeout) < 0)
                r = -1;
        } else if (bev->read_suspended & BEV_SUSPEND_BW) {
            if (!(bev->write_suspended & BEV_SUSPEND_BW))
                event_del(&bev->rate_limiting->refill_bucket_event);
            bufferevent_unsuspend_read_(&bev->bev, BEV_SUSPEND_BW);
        }
    }
    if (bev->rate_limiting->group) {
        LOCK_GROUP(bev->rate_limiting->group);
        bev->rate_limiting->group->rate_limit.read_limit -= bytes;
        bev->rate_limiting->group->total_read += bytes;
        if (bev->rate_limiting->group->rate_limit.read_limit <= 0) {
            bev_group_suspend_reading_(bev->rate_limiting->group);
        } else if (bev->rate_limiting->group->read_suspended) {
            bev_group_unsuspend_reading_(bev->rate_limiting->group);
        }
        UNLOCK_GROUP(bev->rate_limiting->group);
    }
    return r;
}
References bufferevent_private::bev, bev_group_suspend_reading_(), bev_group_unsuspend_reading_(), BEV_SUSPEND_BW, bufferevent_suspend_read_(), bufferevent_unsuspend_read_(), bufferevent_rate_limit::cfg, event_add(), event_del(), bufferevent_rate_limit::group, bufferevent_rate_limit::limit, LOCK_GROUP, bufferevent_rate_limit_group::rate_limit, bufferevent_private::rate_limiting, ev_token_bucket::read_limit, bufferevent_rate_limit_group::read_suspended, bufferevent_private::read_suspended, bufferevent_rate_limit::refill_bucket_event, ev_token_bucket_cfg::tick_timeout, bufferevent_rate_limit_group::total_read, UNLOCK_GROUP, and bufferevent_private::write_suspended.
Referenced by bev_async_consider_reading(), bufferevent_readcb(), decrement_buckets(), and read_complete().
bufferevent_decrement_write_buckets_()
EVENT2_EXPORT_SYMBOL int bufferevent_decrement_write_buckets_ (struct bufferevent_private * bev, ev_ssize_t bytes)
Definition at line 311 of file bufferevent_ratelim.c.
{
    /* XXXXX Make sure all users of this function check its return value */
    int r = 0;
    /* need to hold lock */
    if (!bev->rate_limiting)
        return 0;
    if (bev->rate_limiting->cfg) {
        bev->rate_limiting->limit.write_limit -= bytes;
        if (bev->rate_limiting->limit.write_limit <= 0) {
            bufferevent_suspend_write_(&bev->bev, BEV_SUSPEND_BW);
            if (event_add(&bev->rate_limiting->refill_bucket_event,
                &bev->rate_limiting->cfg->tick_timeout) < 0)
                r = -1;
        } else if (bev->write_suspended & BEV_SUSPEND_BW) {
            if (!(bev->read_suspended & BEV_SUSPEND_BW))
                event_del(&bev->rate_limiting->refill_bucket_event);
            bufferevent_unsuspend_write_(&bev->bev, BEV_SUSPEND_BW);
        }
    }
    if (bev->rate_limiting->group) {
        LOCK_GROUP(bev->rate_limiting->group);
        bev->rate_limiting->group->rate_limit.write_limit -= bytes;
        bev->rate_limiting->group->total_written += bytes;
        if (bev->rate_limiting->group->rate_limit.write_limit <= 0) {
            bev_group_suspend_writing_(bev->rate_limiting->group);
        } else if (bev->rate_limiting->group->write_suspended) {
            bev_group_unsuspend_writing_(bev->rate_limiting->group);
        }
        UNLOCK_GROUP(bev->rate_limiting->group);
    }
    return r;
}
References bufferevent_private::bev, bev_group_suspend_writing_(), bev_group_unsuspend_writing_(), BEV_SUSPEND_BW, bufferevent_suspend_write_(), bufferevent_unsuspend_write_(), bufferevent_rate_limit::cfg, event_add(), event_del(), bufferevent_rate_limit::group, bufferevent_rate_limit::limit, LOCK_GROUP, bufferevent_rate_limit_group::rate_limit, bufferevent_private::rate_limiting, bufferevent_private::read_suspended, bufferevent_rate_limit::refill_bucket_event, ev_token_bucket_cfg::tick_timeout, bufferevent_rate_limit_group::total_written, UNLOCK_GROUP, ev_token_bucket::write_limit, bufferevent_rate_limit_group::write_suspended, and bufferevent_private::write_suspended.
Referenced by bev_async_consider_writing(), bufferevent_writecb(), decrement_buckets(), and write_complete().
bufferevent_disable_hard_()
EVENT2_EXPORT_SYMBOL int bufferevent_disable_hard_ (struct bufferevent * bufev, short event)
Definition at line 556 of file bufferevent.c.
{
    int r = 0;
    struct bufferevent_private *bufev_private = BEV_UPCAST(bufev);
    BEV_LOCK(bufev);
    bufev->enabled &= ~event;
    bufev_private->connecting = 0;
    if (bufev->be_ops->disable(bufev, event) < 0)
        r = -1;
    BEV_UNLOCK(bufev);
    return r;
}
References BEV_LOCK, BEV_UNLOCK, BEV_UPCAST, and bufferevent_private::connecting.
Referenced by evhttp_connection_reset_().
bufferevent_enable_locking_()
EVENT2_EXPORT_SYMBOL int bufferevent_enable_locking_ (struct bufferevent * bufev, void * lock)
Internal: Set up locking on a bufferevent. If lock is set, use it. Otherwise, use a new lock.
Definition at line 829 of file bufferevent.c.
{
#ifdef EVENT__DISABLE_THREAD_SUPPORT
    return -1;
#else
    struct bufferevent *underlying;
    if (BEV_UPCAST(bufev)->lock)
        return -1;
    underlying = bufferevent_get_underlying(bufev);
    if (!lock && underlying && BEV_UPCAST(underlying)->lock) {
        lock = BEV_UPCAST(underlying)->lock;
        BEV_UPCAST(bufev)->lock = lock;
        BEV_UPCAST(bufev)->own_lock = 0;
    } else if (!lock) {
        EVTHREAD_ALLOC_LOCK(lock, EVTHREAD_LOCKTYPE_RECURSIVE);
        if (!lock)
            return -1;
        BEV_UPCAST(bufev)->lock = lock;
        BEV_UPCAST(bufev)->own_lock = 1;
    } else {
        BEV_UPCAST(bufev)->lock = lock;
        BEV_UPCAST(bufev)->own_lock = 0;
    }
    evbuffer_enable_locking(bufev->input, lock);
    evbuffer_enable_locking(bufev->output, lock);
    if (underlying && !BEV_UPCAST(underlying)->lock)
        bufferevent_enable_locking_(underlying, lock);
    return 0;
#endif
}
References BEV_UPCAST, bufferevent_enable_locking_(), bufferevent_get_underlying(), evbuffer_enable_locking(), and EVTHREAD_ALLOC_LOCK.
Referenced by bufferevent_enable_locking_(), bufferevent_filter_new(), bufferevent_init_common_(), bufferevent_openssl_new_impl(), and bufferevent_pair_new().
bufferevent_generic_adj_existing_timeouts_()
EVENT2_EXPORT_SYMBOL int bufferevent_generic_adj_existing_timeouts_ (struct bufferevent * bev)
Definition at line 993 of file bufferevent.c.
{
    int r = 0;
    if (event_pending(&bev->ev_read, EV_READ, NULL)) {
        if (evutil_timerisset(&bev->timeout_read)) {
                if (bufferevent_add_event_(&bev->ev_read, &bev->timeout_read) < 0)
                    r = -1;
        } else {
            event_remove_timer(&bev->ev_read);
        }
    }
    if (event_pending(&bev->ev_write, EV_WRITE, NULL)) {
        if (evutil_timerisset(&bev->timeout_write)) {
            if (bufferevent_add_event_(&bev->ev_write, &bev->timeout_write) < 0)
                r = -1;
        } else {
            event_remove_timer(&bev->ev_write);
        }
    }
    return r;
}
References bufferevent_private::bev, bufferevent_add_event_(), event_pending(), and event_remove_timer().
Referenced by be_openssl_adj_timeouts().
bufferevent_generic_adj_timeouts_()
EVENT2_EXPORT_SYMBOL int bufferevent_generic_adj_timeouts_ (struct bufferevent * bev)
Internal use: Add or delete the generic timeout events as appropriate. (If an event is enabled and a timeout is set, we add the event. Otherwise we delete it.) Call this from anything that changes the timeout values, that enabled EV_READ or EV_WRITE, or that disables EV_READ or EV_WRITE.
Definition at line 970 of file bufferevent.c.
{
    const short enabled = bev->enabled;
    struct bufferevent_private *bev_p = BEV_UPCAST(bev);
    int r1=0, r2=0;
    if ((enabled & EV_READ) && !bev_p->read_suspended &&
        evutil_timerisset(&bev->timeout_read))
        r1 = event_add(&bev->ev_read, &bev->timeout_read);
    else
        r1 = event_del(&bev->ev_read);
    if ((enabled & EV_WRITE) && !bev_p->write_suspended &&
        evutil_timerisset(&bev->timeout_write) &&
        evbuffer_get_length(bev->output))
        r2 = event_add(&bev->ev_write, &bev->timeout_write);
    else
        r2 = event_del(&bev->ev_write);
    if (r1 < 0 || r2 < 0)
        return -1;
    return 0;
}
References bufferevent_private::bev, BEV_UPCAST, evbuffer_get_length(), event_add(), event_del(), bufferevent_private::read_suspended, and bufferevent_private::write_suspended.
Referenced by be_openssl_adj_timeouts().
bufferevent_get_options_()
EVENT2_EXPORT_SYMBOL enum bufferevent_options bufferevent_get_options_ (struct bufferevent * bev)
Definition at line 895 of file bufferevent.c.
{
    struct bufferevent_private *bev_p = BEV_UPCAST(bev);
    enum bufferevent_options options;
    BEV_LOCK(bev);
    options = bev_p->options;
    BEV_UNLOCK(bev);
    return options;
}
References bufferevent_private::bev, BEV_LOCK, BEV_UNLOCK, BEV_UPCAST, and bufferevent_private::options.
Referenced by evhttp_connection_free().
bufferevent_get_read_max_()
EVENT2_EXPORT_SYMBOL ev_ssize_t bufferevent_get_read_max_ (struct bufferevent_private * bev)
Definition at line 261 of file bufferevent_ratelim.c.
{
    return bufferevent_get_rlim_max_(bev, 0);
}
References bufferevent_get_rlim_max_().
Referenced by bev_async_consider_reading(), bufferevent_get_max_to_read(), bufferevent_readcb(), bytes_to_read(), and do_read().
bufferevent_get_write_max_()
EVENT2_EXPORT_SYMBOL ev_ssize_t bufferevent_get_write_max_ (struct bufferevent_private * bev)
Definition at line 267 of file bufferevent_ratelim.c.
{
    return bufferevent_get_rlim_max_(bev, 1);
}
References bufferevent_get_rlim_max_().
Referenced by bev_async_consider_writing(), bufferevent_get_max_to_write(), bufferevent_writecb(), and do_write().
bufferevent_incref_and_lock_()
EVENT2_EXPORT_SYMBOL void bufferevent_incref_and_lock_ (struct bufferevent * bufev)
Internal: Lock bufev and increase its reference count. unlocking it otherwise.
Definition at line 680 of file bufferevent.c.
{
    struct bufferevent_private *bufev_private = BEV_UPCAST(bufev);
    BEV_LOCK(bufev);
    ++bufev_private->refcnt;
}
References BEV_LOCK, BEV_UPCAST, and bufferevent_private::refcnt.
Referenced by be_async_inbuf_callback(), be_async_outbuf_callback(), be_filter_flush(), be_openssl_handshakeeventcb(), be_openssl_readeventcb(), be_openssl_writeeventcb(), bufferevent_enable(), bufferevent_filtered_outbuf_cb(), bufferevent_generic_read_timeout_cb(), bufferevent_generic_write_timeout_cb(), bufferevent_lock(), bufferevent_readcb(), bufferevent_socket_connect(), bufferevent_trigger(), bufferevent_trigger_event(), bufferevent_writecb(), and incref_and_lock().
bufferevent_init_common_()
EVENT2_EXPORT_SYMBOL int bufferevent_init_common_ (struct bufferevent_private * bufev_private, struct event_base * base, const struct bufferevent_ops * ops, enum bufferevent_options options)
Initialize the shared parts of a bufferevent.
Definition at line 309 of file bufferevent.c.
{
    struct bufferevent *bufev = &bufev_private->bev;
    if (!bufev->input) {
        if ((bufev->input = evbuffer_new()) == NULL)
            goto err;
    }
    if (!bufev->output) {
        if ((bufev->output = evbuffer_new()) == NULL)
            goto err;
    }
    bufev_private->refcnt = 1;
    bufev->ev_base = base;
    /* Disable timeouts. */
    evutil_timerclear(&bufev->timeout_read);
    evutil_timerclear(&bufev->timeout_write);
    bufev->be_ops = ops;
    if (bufferevent_ratelim_init_(bufev_private))
        goto err;
    /*
     * Set to EV_WRITE so that using bufferevent_write is going to
     * trigger a callback.  Reading needs to be explicitly enabled
     * because otherwise no data will be available.
     */
    bufev->enabled = EV_WRITE;
#ifndef EVENT__DISABLE_THREAD_SUPPORT
    if (options & BEV_OPT_THREADSAFE) {
        if (bufferevent_enable_locking_(bufev, NULL) < 0)
            goto err;
    }
#endif
    if ((options & (BEV_OPT_DEFER_CALLBACKS|BEV_OPT_UNLOCK_CALLBACKS))
        == BEV_OPT_UNLOCK_CALLBACKS) {
        event_warnx("UNLOCK_CALLBACKS requires DEFER_CALLBACKS");
        goto err;
    }
    if (options & BEV_OPT_UNLOCK_CALLBACKS)
        event_deferred_cb_init_(
            &bufev_private->deferred,
            event_base_get_npriorities(base) / 2,
            bufferevent_run_deferred_callbacks_unlocked,
            bufev_private);
    else
        event_deferred_cb_init_(
            &bufev_private->deferred,
            event_base_get_npriorities(base) / 2,
            bufferevent_run_deferred_callbacks_locked,
            bufev_private);
    bufev_private->options = options;
    evbuffer_set_parent_(bufev->input, bufev);
    evbuffer_set_parent_(bufev->output, bufev);
    return 0;
err:
    if (bufev->input) {
        evbuffer_free(bufev->input);
        bufev->input = NULL;
    }
    if (bufev->output) {
        evbuffer_free(bufev->output);
        bufev->output = NULL;
    }
    return -1;
}
References bufferevent_private::bev, bufferevent_enable_locking_(), bufferevent_ratelim_init_(), bufferevent_run_deferred_callbacks_locked(), bufferevent_run_deferred_callbacks_unlocked(), bufferevent_private::deferred, evbuffer_free(), evbuffer_new(), evbuffer_set_parent_(), event_base_get_npriorities(), event_deferred_cb_init_(), event_warnx(), bufferevent_private::options, and bufferevent_private::refcnt.
Referenced by bufferevent_async_new_(), bufferevent_filter_new(), bufferevent_openssl_new_impl(), bufferevent_pair_elt_new(), and bufferevent_socket_new().
bufferevent_init_generic_timeout_cbs_()
EVENT2_EXPORT_SYMBOL void bufferevent_init_generic_timeout_cbs_ (struct bufferevent * bev)
Internal use: Set up the ev_read and ev_write callbacks so that the other "generic_timeout" functions will work on it. Call this from the constructor function.
Definition at line 961 of file bufferevent.c.
{
    event_assign(&bev->ev_read, bev->ev_base, -1, EV_FINALIZE,
        bufferevent_generic_read_timeout_cb, bev);
    event_assign(&bev->ev_write, bev->ev_base, -1, EV_FINALIZE,
        bufferevent_generic_write_timeout_cb, bev);
}
References bufferevent_generic_read_timeout_cb(), bufferevent_generic_write_timeout_cb(), and event_assign().
Referenced by bufferevent_async_new_(), bufferevent_filter_new(), bufferevent_openssl_new_impl(), and bufferevent_pair_elt_new().
bufferevent_ratelim_init_()
int bufferevent_ratelim_init_ (struct bufferevent_private * bev)
Definition at line 1082 of file bufferevent_ratelim.c.
{
    bev->rate_limiting = NULL;
    bev->max_single_read = MAX_SINGLE_READ_DEFAULT;
    bev->max_single_write = MAX_SINGLE_WRITE_DEFAULT;
    return 0;
}
References bufferevent_private::bev, MAX_SINGLE_READ_DEFAULT, and MAX_SINGLE_WRITE_DEFAULT.
Referenced by bufferevent_init_common_().
bufferevent_run_eventcb_()
EVENT2_EXPORT_SYMBOL void bufferevent_run_eventcb_ (struct bufferevent * bufev, short what, int options)
Internal: If callbacks are deferred and we have an eventcb, schedule it to run with events "what". Otherwise just run the eventcb. See bufferevent_trigger_event for meaning of "options".
Definition at line 285 of file bufferevent.c.
{
    /* Requires that we hold the lock and a reference */
    struct bufferevent_private *p = BEV_UPCAST(bufev);
    if (bufev->errorcb == NULL)
        return;
    if ((p->options|options) & BEV_OPT_DEFER_CALLBACKS) {
        p->eventcb_pending |= what;
        p->errno_pending = EVUTIL_SOCKET_ERROR();
        SCHEDULE_DEFERRED(p);
    } else {
        bufev->errorcb(bufev, what, bufev->cbarg);
    }
}
References BEV_UPCAST, bufferevent_private::errno_pending, bufferevent_private::eventcb_pending, bufferevent_private::options, and SCHEDULE_DEFERRED.
Referenced by be_async_run_eventcb(), be_filter_eventcb(), be_openssl_eventcb(), be_openssl_handshakeeventcb(), be_openssl_readeventcb(), be_openssl_writeeventcb(), be_pair_flush(), bufferevent_connect_getaddrinfo_cb(), bufferevent_generic_read_timeout_cb(), bufferevent_generic_write_timeout_cb(), bufferevent_readcb(), bufferevent_socket_connect(), bufferevent_trigger_event(), bufferevent_writecb(), conn_closed(), and do_handshake().
bufferevent_run_readcb_()
EVENT2_EXPORT_SYMBOL void bufferevent_run_readcb_ (struct bufferevent * bufev, int options)
Internal: If callbacks are deferred and we have a read callback, schedule a readcb. Otherwise just run the readcb. Ignores watermarks.
Definition at line 241 of file bufferevent.c.
{
    /* Requires that we hold the lock and a reference */
    struct bufferevent_private *p = BEV_UPCAST(bufev);
    if (bufev->readcb == NULL)
        return;
    if ((p->options|options) & BEV_OPT_DEFER_CALLBACKS) {
        p->readcb_pending = 1;
        SCHEDULE_DEFERRED(p);
    } else {
        bufev->readcb(bufev, bufev->cbarg);
        bufferevent_inbuf_wm_check(bufev);
    }
}
References BEV_UPCAST, bufferevent_inbuf_wm_check(), bufferevent_private::options, bufferevent_private::readcb_pending, and SCHEDULE_DEFERRED.
Referenced by bufferevent_trigger_nolock_().
bufferevent_run_writecb_()
EVENT2_EXPORT_SYMBOL void bufferevent_run_writecb_ (struct bufferevent * bufev, int options)
Internal: If callbacks are deferred and we have a write callback, schedule a writecb. Otherwise just run the writecb. Ignores watermarks.
Definition at line 257 of file bufferevent.c.
{
    /* Requires that we hold the lock and a reference */
    struct bufferevent_private *p = BEV_UPCAST(bufev);
    if (bufev->writecb == NULL)
        return;
    if ((p->options|options) & BEV_OPT_DEFER_CALLBACKS) {
        p->writecb_pending = 1;
        SCHEDULE_DEFERRED(p);
    } else {
        bufev->writecb(bufev, bufev->cbarg);
    }
}
References BEV_UPCAST, bufferevent_private::options, SCHEDULE_DEFERRED, and bufferevent_private::writecb_pending.
Referenced by bufferevent_trigger_nolock_().
bufferevent_socket_get_conn_address_()
EVENT2_EXPORT_SYMBOL const struct sockaddr * bufferevent_socket_get_conn_address_ (struct bufferevent * bev)
Definition at line 100 of file bufferevent_sock.c.
{
    struct bufferevent_private *bev_p = BEV_UPCAST(bev);
    return (struct sockaddr *)&bev_p->conn_address;
}
References bufferevent_private::bev, BEV_UPCAST, and bufferevent_private::conn_address.
Referenced by evhttp_connection_get_addr().
bufferevent_socket_set_conn_address_()
EVENT2_EXPORT_SYMBOL void bufferevent_socket_set_conn_address_ (struct bufferevent * bev, struct sockaddr * addr, size_t addrlen)
Definition at line 120 of file bufferevent_sock.c.
{
    struct bufferevent_private *bev_p = BEV_UPCAST(bev);
    EVUTIL_ASSERT(addrlen <= sizeof(bev_p->conn_address));
    memcpy(&bev_p->conn_address, addr, addrlen);
}
References bufferevent_private::bev, BEV_UPCAST, bufferevent_private::conn_address, and EVUTIL_ASSERT.
Referenced by bufferevent_connect_getaddrinfo_cb(), and evhttp_get_request_connection().
bufferevent_socket_set_conn_address_fd_()
EVENT2_EXPORT_SYMBOL void bufferevent_socket_set_conn_address_fd_ (struct bufferevent * bev, evutil_socket_t fd)
Definition at line 107 of file bufferevent_sock.c.
{
    struct bufferevent_private *bev_p = BEV_UPCAST(bev);
    socklen_t len = sizeof(bev_p->conn_address);
    struct sockaddr *addr = (struct sockaddr *)&bev_p->conn_address;
    if (addr->sa_family != AF_UNSPEC)
        getpeername(fd, addr, &len);
}
References bufferevent_private::bev, BEV_UPCAST, and bufferevent_private::conn_address.
Referenced by bufferevent_writecb().
bufferevent_suspend_read_()
EVENT2_EXPORT_SYMBOL void bufferevent_suspend_read_ (struct bufferevent * bufev, bufferevent_suspend_flags what)
For internal use: temporarily stop all reads on bufev, until the conditions in 'what' are over.
Definition at line 67 of file bufferevent.c.
{
    struct bufferevent_private *bufev_private = BEV_UPCAST(bufev);
    BEV_LOCK(bufev);
    if (!bufev_private->read_suspended)
        bufev->be_ops->disable(bufev, EV_READ);
    bufev_private->read_suspended |= what;
    BEV_UNLOCK(bufev);
}
References BEV_LOCK, BEV_UNLOCK, BEV_UPCAST, and bufferevent_private::read_suspended.
Referenced by be_filter_disable(), bev_group_suspend_reading_(), bufferevent_add_to_rate_limit_group(), bufferevent_decrement_read_buckets_(), bufferevent_decrement_read_limit(), bufferevent_filter_new(), bufferevent_get_rlim_max_(), bufferevent_openssl_new_impl(), bufferevent_set_rate_limit(), bufferevent_socket_connect_hostname(), and stop_reading().
bufferevent_suspend_write_()
void bufferevent_suspend_write_ (struct bufferevent * bufev, bufferevent_suspend_flags what)
For internal use: temporarily stop all writes on bufev, until the conditions in 'what' are over.
Definition at line 89 of file bufferevent.c.
{
    struct bufferevent_private *bufev_private = BEV_UPCAST(bufev);
    BEV_LOCK(bufev);
    if (!bufev_private->write_suspended)
        bufev->be_ops->disable(bufev, EV_WRITE);
    bufev_private->write_suspended |= what;
    BEV_UNLOCK(bufev);
}
References BEV_LOCK, BEV_UNLOCK, BEV_UPCAST, and bufferevent_private::write_suspended.
Referenced by bev_group_suspend_writing_(), bufferevent_add_to_rate_limit_group(), bufferevent_decrement_write_buckets_(), bufferevent_decrement_write_limit(), bufferevent_get_rlim_max_(), bufferevent_set_rate_limit(), and bufferevent_socket_connect_hostname().
bufferevent_trigger_nolock_()
static void bufferevent_trigger_nolock_ (struct bufferevent * bufev, short iotype, int options) inline static
Internal: Run or schedule (if deferred or options contain BEV_TRIG_DEFER_CALLBACKS) I/O callbacks specified in iotype. Must already hold the bufev lock. Honors watermarks unless BEV_TRIG_IGNORE_WATERMARKS is in options.
Definition at line 407 of file bufferevent-internal.h.
{
    if ((iotype & EV_READ) && ((options & BEV_TRIG_IGNORE_WATERMARKS) ||
        evbuffer_get_length(bufev->input) >= bufev->wm_read.low))
        bufferevent_run_readcb_(bufev, options);
    if ((iotype & EV_WRITE) && ((options & BEV_TRIG_IGNORE_WATERMARKS) ||
        evbuffer_get_length(bufev->output) <= bufev->wm_write.low))
        bufferevent_run_writecb_(bufev, options);
}
References bufferevent_run_readcb_(), bufferevent_run_writecb_(), and evbuffer_get_length().
Referenced by be_async_trigger_nolock(), be_filter_process_output(), be_filter_read_nolock_(), be_pair_transfer(), bufferevent_readcb(), bufferevent_socket_connect(), bufferevent_trigger(), bufferevent_writecb(), consider_reading(), consider_writing(), and do_write().
bufferevent_unsuspend_read_()
EVENT2_EXPORT_SYMBOL void bufferevent_unsuspend_read_ (struct bufferevent * bufev, bufferevent_suspend_flags what)
For internal use: clear the conditions 'what' on bufev, and re-enable reading if there are no conditions left.
Definition at line 78 of file bufferevent.c.
{
    struct bufferevent_private *bufev_private = BEV_UPCAST(bufev);
    BEV_LOCK(bufev);
    bufev_private->read_suspended &= ~what;
    if (!bufev_private->read_suspended && (bufev->enabled & EV_READ))
        bufev->be_ops->enable(bufev, EV_READ);
    BEV_UNLOCK(bufev);
}
References BEV_LOCK, BEV_UNLOCK, BEV_UPCAST, and bufferevent_private::read_suspended.
Referenced by be_filter_enable(), be_filter_unlink(), be_openssl_unlink(), bev_refill_callback_(), bufferevent_connect_getaddrinfo_cb(), bufferevent_decrement_read_buckets_(), bufferevent_decrement_read_limit(), bufferevent_remove_from_rate_limit_group_internal_(), bufferevent_set_rate_limit(), start_reading(), start_writing(), and stop_writing().
bufferevent_unsuspend_write_()
void bufferevent_unsuspend_write_ (struct bufferevent * bufev, bufferevent_suspend_flags what)
For internal use: clear the conditions 'what' on bufev, and re-enable writing if there are no conditions left.
Definition at line 100 of file bufferevent.c.
{
    struct bufferevent_private *bufev_private = BEV_UPCAST(bufev);
    BEV_LOCK(bufev);
    bufev_private->write_suspended &= ~what;
    if (!bufev_private->write_suspended && (bufev->enabled & EV_WRITE))
        bufev->be_ops->enable(bufev, EV_WRITE);
    BEV_UNLOCK(bufev);
}
References BEV_LOCK, BEV_UNLOCK, BEV_UPCAST, and bufferevent_private::write_suspended.
Referenced by bev_refill_callback_(), bufferevent_connect_getaddrinfo_cb(), bufferevent_decrement_write_buckets_(), bufferevent_decrement_write_limit(), bufferevent_remove_from_rate_limit_group_internal_(), and bufferevent_set_rate_limit().
Variable Documentation
bufferevent_ops_filter
const struct bufferevent_ops bufferevent_ops_filter extern
Definition at line 103 of file bufferevent_filter.c.
Referenced by bufferevent_filter_new().
bufferevent_ops_pair
const struct bufferevent_ops bufferevent_ops_pair extern
Definition at line 355 of file bufferevent_pair.c.
Referenced by bufferevent_pair_elt_new().
bufferevent_ops_socket
const struct bufferevent_ops bufferevent_ops_socket extern
Definition at line 87 of file bufferevent_sock.c.
Referenced by bufferevent_socket_new().