libdogecoin: src/libevent/bufferevent_sock.c File Reference
bufferevent_sock.c File Reference
#include "event2/event-config.h"
#include "evconfig-private.h"
#include <sys/types.h>
#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "event2/util.h"
#include "event2/bufferevent.h"
#include "event2/buffer.h"
#include "event2/bufferevent_struct.h"
#include "event2/bufferevent_compat.h"
#include "event2/event.h"
#include "log-internal.h"
#include "mm-internal.h"
#include "bufferevent-internal.h"
#include "util-internal.h"
Functions
static int be_socket_enable (struct bufferevent *, short)
static int be_socket_disable (struct bufferevent *, short)
static void be_socket_destruct (struct bufferevent *)
static int be_socket_flush (struct bufferevent *, short, enum bufferevent_flush_mode)
static int be_socket_ctrl (struct bufferevent *, enum bufferevent_ctrl_op, union bufferevent_ctrl_data *)
static void be_socket_setfd (struct bufferevent *, evutil_socket_t)
const struct sockaddr * bufferevent_socket_get_conn_address_ (struct bufferevent *bev)
void bufferevent_socket_set_conn_address_fd_ (struct bufferevent *bev, evutil_socket_t fd)
void bufferevent_socket_set_conn_address_ (struct bufferevent *bev, struct sockaddr *addr, size_t addrlen)
static void bufferevent_socket_outbuf_cb (struct evbuffer *buf, const struct evbuffer_cb_info *cbinfo, void *arg)
static void bufferevent_readcb (evutil_socket_t fd, short event, void *arg)
static void bufferevent_writecb (evutil_socket_t fd, short event, void *arg)
struct bufferevent * bufferevent_socket_new (struct event_base *base, evutil_socket_t fd, int options)
int bufferevent_socket_connect (struct bufferevent *bev, const struct sockaddr *sa, int socklen)
static void bufferevent_connect_getaddrinfo_cb (int result, struct evutil_addrinfo *ai, void *arg)
int bufferevent_socket_connect_hostname (struct bufferevent *bev, struct evdns_base *evdns_base, int family, const char *hostname, int port)
int bufferevent_socket_get_dns_error (struct bufferevent *bev)
struct bufferevent * bufferevent_new (evutil_socket_t fd, bufferevent_data_cb readcb, bufferevent_data_cb writecb, bufferevent_event_cb eventcb, void *cbarg)
int bufferevent_priority_set (struct bufferevent *bufev, int priority)
int bufferevent_base_set (struct event_base *base, struct bufferevent *bufev)
Variables
const struct bufferevent_ops bufferevent_ops_socket
Function Documentation
be_socket_ctrl()
static int be_socket_ctrl (struct bufferevent * bev, enum bufferevent_ctrl_op op, union bufferevent_ctrl_data * data) static
Definition at line 692 of file bufferevent_sock.c.
{
    switch (op) {
    case BEV_CTRL_SET_FD:
        be_socket_setfd(bev, data->fd);
        return 0;
    case BEV_CTRL_GET_FD:
        data->fd = event_get_fd(&bev->ev_read);
        return 0;
    case BEV_CTRL_GET_UNDERLYING:
    case BEV_CTRL_CANCEL_ALL:
    default:
        return -1;
    }
}
References be_socket_setfd(), bufferevent_private::bev, BEV_CTRL_CANCEL_ALL, BEV_CTRL_GET_FD, BEV_CTRL_GET_UNDERLYING, BEV_CTRL_SET_FD, event_get_fd(), and bufferevent_ctrl_data::fd.
be_socket_destruct()
static void be_socket_destruct (struct bufferevent * bufev) static
Definition at line 596 of file bufferevent_sock.c.
{
    struct bufferevent_private *bufev_p = BEV_UPCAST(bufev);
    evutil_socket_t fd;
    EVUTIL_ASSERT(BEV_IS_SOCKET(bufev));
    fd = event_get_fd(&bufev->ev_read);
    if ((bufev_p->options & BEV_OPT_CLOSE_ON_FREE) && fd >= 0)
        EVUTIL_CLOSESOCKET(fd);
    evutil_getaddrinfo_cancel_async_(bufev_p->dns_request);
}
References BEV_IS_SOCKET, BEV_UPCAST, bufferevent_private::dns_request, event_get_fd(), EVUTIL_ASSERT, evutil_getaddrinfo_cancel_async_(), and bufferevent_private::options.
be_socket_disable()
static int be_socket_disable (struct bufferevent * bufev, short event) static
Definition at line 580 of file bufferevent_sock.c.
{
    struct bufferevent_private *bufev_p = BEV_UPCAST(bufev);
    if (event & EV_READ) {
        if (event_del(&bufev->ev_read) == -1)
            return -1;
    }
    /* Don't actually disable the write if we are trying to connect. */
    if ((event & EV_WRITE) && ! bufev_p->connecting) {
        if (event_del(&bufev->ev_write) == -1)
            return -1;
    }
    return 0;
}
References BEV_UPCAST, bufferevent_private::connecting, and event_del().
be_socket_enable()
static int be_socket_enable (struct bufferevent * bufev, short event) static
Definition at line 568 of file bufferevent_sock.c.
{
    if (event & EV_READ &&
        bufferevent_add_event_(&bufev->ev_read, &bufev->timeout_read) == -1)
            return -1;
    if (event & EV_WRITE &&
        bufferevent_add_event_(&bufev->ev_write, &bufev->timeout_write) == -1)
            return -1;
    return 0;
}
References bufferevent_add_event_().
Referenced by bufferevent_socket_connect().
be_socket_flush()
static int be_socket_flush (struct bufferevent * bev, short iotype, enum bufferevent_flush_mode mode) static
Definition at line 611 of file bufferevent_sock.c.
{
    return 0;
}
be_socket_setfd()
static void be_socket_setfd (struct bufferevent * bufev, evutil_socket_t fd) static
Definition at line 619 of file bufferevent_sock.c.
{
    struct bufferevent_private *bufev_p = BEV_UPCAST(bufev);
    BEV_LOCK(bufev);
    EVUTIL_ASSERT(BEV_IS_SOCKET(bufev));
    event_del(&bufev->ev_read);
    event_del(&bufev->ev_write);
    evbuffer_unfreeze(bufev->input, 0);
    evbuffer_unfreeze(bufev->output, 1);
    event_assign(&bufev->ev_read, bufev->ev_base, fd,
        EV_READ|EV_PERSIST|EV_FINALIZE, bufferevent_readcb, bufev);
    event_assign(&bufev->ev_write, bufev->ev_base, fd,
        EV_WRITE|EV_PERSIST|EV_FINALIZE, bufferevent_writecb, bufev);
    if (fd >= 0)
        bufferevent_enable(bufev, bufev->enabled);
    evutil_getaddrinfo_cancel_async_(bufev_p->dns_request);
    BEV_UNLOCK(bufev);
}
References BEV_IS_SOCKET, BEV_LOCK, BEV_UNLOCK, BEV_UPCAST, bufferevent_enable(), bufferevent_readcb(), bufferevent_writecb(), bufferevent_private::dns_request, evbuffer_unfreeze(), event_assign(), event_del(), EVUTIL_ASSERT, and evutil_getaddrinfo_cancel_async_().
Referenced by be_socket_ctrl().
bufferevent_base_set()
int bufferevent_base_set (struct event_base * base, struct bufferevent * bufev)
Definition at line 671 of file bufferevent_sock.c.
{
    int res = -1;
    BEV_LOCK(bufev);
    if (!BEV_IS_SOCKET(bufev))
        goto done;
    bufev->ev_base = base;
    res = event_base_set(base, &bufev->ev_read);
    if (res == -1)
        goto done;
    res = event_base_set(base, &bufev->ev_write);
done:
    BEV_UNLOCK(bufev);
    return res;
}
References BEV_IS_SOCKET, BEV_LOCK, BEV_UNLOCK, and event_base_set().
Referenced by evhttp_connection_base_bufferevent_new(), and evhttp_connection_set_base().
bufferevent_connect_getaddrinfo_cb()
static void bufferevent_connect_getaddrinfo_cb (int result, struct evutil_addrinfo * ai, void * arg) static
Definition at line 457 of file bufferevent_sock.c.
{
    struct bufferevent *bev = arg;
    struct bufferevent_private *bev_p = BEV_UPCAST(bev);
    int r;
    BEV_LOCK(bev);
    bufferevent_unsuspend_write_(bev, BEV_SUSPEND_LOOKUP);
    bufferevent_unsuspend_read_(bev, BEV_SUSPEND_LOOKUP);
    bev_p->dns_request = NULL;
    if (result == EVUTIL_EAI_CANCEL) {
        bev_p->dns_error = result;
        bufferevent_decref_and_unlock_(bev);
        return;
    }
    if (result != 0) {
        bev_p->dns_error = result;
        bufferevent_run_eventcb_(bev, BEV_EVENT_ERROR, 0);
        bufferevent_decref_and_unlock_(bev);
        if (ai)
            evutil_freeaddrinfo(ai);
        return;
    }
    /* XXX use the other addrinfos? */
    bufferevent_socket_set_conn_address_(bev, ai->ai_addr, (int)ai->ai_addrlen);
    r = bufferevent_socket_connect(bev, ai->ai_addr, (int)ai->ai_addrlen);
    if (r < 0)
        bufferevent_run_eventcb_(bev, BEV_EVENT_ERROR, 0);
    bufferevent_decref_and_unlock_(bev);
    evutil_freeaddrinfo(ai);
}
References bufferevent_private::bev, BEV_LOCK, BEV_SUSPEND_LOOKUP, BEV_UPCAST, bufferevent_decref_and_unlock_(), bufferevent_run_eventcb_(), bufferevent_socket_connect(), bufferevent_socket_set_conn_address_(), bufferevent_unsuspend_read_(), bufferevent_unsuspend_write_(), bufferevent_private::dns_error, bufferevent_private::dns_request, and evutil_freeaddrinfo().
Referenced by bufferevent_socket_connect_hostname().
bufferevent_new()
struct bufferevent * bufferevent_new (evutil_socket_t fd, bufferevent_data_cb readcb, bufferevent_data_cb writecb, bufferevent_event_cb eventcb, void * cbarg)
Definition at line 552 of file bufferevent_sock.c.
{
    struct bufferevent *bufev;
    if (!(bufev = bufferevent_socket_new(NULL, fd, 0)))
        return NULL;
    bufferevent_setcb(bufev, readcb, writecb, eventcb, cbarg);
    return bufev;
}
References bufferevent_setcb(), and bufferevent_socket_new().
bufferevent_priority_set()
int bufferevent_priority_set (struct bufferevent * bufev, int priority)
Definition at line 647 of file bufferevent_sock.c.
{
    int r = -1;
    struct bufferevent_private *bufev_p = BEV_UPCAST(bufev);
    BEV_LOCK(bufev);
    if (BEV_IS_ASYNC(bufev) || BEV_IS_FILTER(bufev) || BEV_IS_PAIR(bufev))
        goto done;
    if (event_priority_set(&bufev->ev_read, priority) == -1)
        goto done;
    if (event_priority_set(&bufev->ev_write, priority) == -1)
        goto done;
    event_deferred_cb_set_priority_(&bufev_p->deferred, priority);
    r = 0;
done:
    BEV_UNLOCK(bufev);
    return r;
}
References BEV_IS_ASYNC, BEV_IS_FILTER, BEV_IS_PAIR, BEV_LOCK, BEV_UNLOCK, BEV_UPCAST, bufferevent_private::deferred, event_deferred_cb_set_priority_(), and event_priority_set().
bufferevent_readcb()
static void bufferevent_readcb (evutil_socket_t fd, short event, void * arg) static
Definition at line 149 of file bufferevent_sock.c.
{
    struct bufferevent *bufev = arg;
    struct bufferevent_private *bufev_p = BEV_UPCAST(bufev);
    struct evbuffer *input;
    int res = 0;
    short what = BEV_EVENT_READING;
    ev_ssize_t howmuch = -1, readmax=-1;
    bufferevent_incref_and_lock_(bufev);
    if (event == EV_TIMEOUT) {
        /* Note that we only check for event==EV_TIMEOUT. If
         * event==EV_TIMEOUT|EV_READ, we can safely ignore the
         * timeout, since a read has occurred */
        what |= BEV_EVENT_TIMEOUT;
        goto error;
    }
    input = bufev->input;
    /*
     * If we have a high watermark configured then we don't want to
     * read more data than would make us reach the watermark.
     */
    if (bufev->wm_read.high != 0) {
        howmuch = bufev->wm_read.high - evbuffer_get_length(input);
        /* we somehow lowered the watermark, stop reading */
        if (howmuch <= 0) {
            bufferevent_wm_suspend_read(bufev);
            goto done;
        }
    }
    readmax = bufferevent_get_read_max_(bufev_p);
    if (howmuch < 0 || howmuch > readmax) /* The use of -1 for "unlimited"
                           * uglifies this code. XXXX */
        howmuch = readmax;
    if (bufev_p->read_suspended)
        goto done;
    evbuffer_unfreeze(input, 0);
    res = evbuffer_read(input, fd, (int)howmuch); /* XXXX evbuffer_read would do better to take and return ev_ssize_t */
    evbuffer_freeze(input, 0);
    if (res == -1) {
        int err = evutil_socket_geterror(fd);
        if (EVUTIL_ERR_RW_RETRIABLE(err))
            goto reschedule;
        if (EVUTIL_ERR_CONNECT_REFUSED(err)) {
            bufev_p->connection_refused = 1;
            goto done;
        }
        /* error case */
        what |= BEV_EVENT_ERROR;
    } else if (res == 0) {
        /* eof case */
        what |= BEV_EVENT_EOF;
    }
    if (res <= 0)
        goto error;
    bufferevent_decrement_read_buckets_(bufev_p, res);
    /* Invoke the user callback - must always be called last */
    bufferevent_trigger_nolock_(bufev, EV_READ, 0);
    goto done;
 reschedule:
    goto done;
 error:
    bufferevent_disable(bufev, EV_READ);
    bufferevent_run_eventcb_(bufev, what, 0);
 done:
    bufferevent_decref_and_unlock_(bufev);
}
References BEV_UPCAST, bufferevent_decref_and_unlock_(), bufferevent_decrement_read_buckets_(), bufferevent_disable(), bufferevent_get_read_max_(), bufferevent_incref_and_lock_(), bufferevent_run_eventcb_(), bufferevent_trigger_nolock_(), bufferevent_wm_suspend_read, bufferevent_private::connection_refused, evbuffer_freeze(), evbuffer_get_length(), evbuffer_read(), evbuffer_unfreeze(), EVUTIL_ERR_CONNECT_REFUSED, EVUTIL_ERR_RW_RETRIABLE, and bufferevent_private::read_suspended.
Referenced by be_socket_setfd(), and bufferevent_socket_new().
bufferevent_socket_connect()
int bufferevent_socket_connect (struct bufferevent * bev, const struct sockaddr * sa, int socklen)
Definition at line 380 of file bufferevent_sock.c.
{
    struct bufferevent_private *bufev_p = BEV_UPCAST(bev);
    evutil_socket_t fd;
    int r = 0;
    int result=-1;
    int ownfd = 0;
    bufferevent_incref_and_lock_(bev);
    fd = bufferevent_getfd(bev);
    if (fd < 0) {
        if (!sa)
            goto done;
        fd = evutil_socket_(sa->sa_family,
            SOCK_STREAM|EVUTIL_SOCK_NONBLOCK, 0);
        if (fd < 0)
            goto freesock;
        ownfd = 1;
    }
    if (sa) {
#ifdef _WIN32
        if (bufferevent_async_can_connect_(bev)) {
            bufferevent_setfd(bev, fd);
            r = bufferevent_async_connect_(bev, fd, sa, socklen);
            if (r < 0)
                goto freesock;
            bufev_p->connecting = 1;
            result = 0;
            goto done;
        } else
#endif
        r = evutil_socket_connect_(&fd, sa, socklen);
        if (r < 0)
            goto freesock;
    }
#ifdef _WIN32
    /* ConnectEx() isn't always around, even when IOCP is enabled.
     * Here, we borrow the socket object's write handler to fall back
     * on a non-blocking connect() when ConnectEx() is unavailable. */
    if (BEV_IS_ASYNC(bev)) {
        event_assign(&bev->ev_write, bev->ev_base, fd,
            EV_WRITE|EV_PERSIST|EV_FINALIZE, bufferevent_writecb, bev);
    }
#endif
    bufferevent_setfd(bev, fd);
    if (r == 0) {
        if (! be_socket_enable(bev, EV_WRITE)) {
            bufev_p->connecting = 1;
            result = 0;
            goto done;
        }
    } else if (r == 1) {
        /* The connect succeeded already. How very BSD of it. */
        result = 0;
        bufev_p->connecting = 1;
        bufferevent_trigger_nolock_(bev, EV_WRITE, BEV_OPT_DEFER_CALLBACKS);
    } else {
        /* The connect failed already.  How very BSD of it. */
        result = 0;
        bufferevent_run_eventcb_(bev, BEV_EVENT_ERROR, BEV_OPT_DEFER_CALLBACKS);
        bufferevent_disable(bev, EV_WRITE|EV_READ);
    }
    goto done;
freesock:
    if (ownfd)
        evutil_closesocket(fd);
done:
    bufferevent_decref_and_unlock_(bev);
    return result;
}
References be_socket_enable(), bufferevent_private::bev, BEV_IS_ASYNC, BEV_UPCAST, bufferevent_async_can_connect_(), bufferevent_async_connect_(), bufferevent_decref_and_unlock_(), bufferevent_disable(), bufferevent_getfd(), bufferevent_incref_and_lock_(), bufferevent_run_eventcb_(), bufferevent_setfd(), bufferevent_trigger_nolock_(), bufferevent_writecb(), bufferevent_private::connecting, event_assign(), evutil_closesocket(), EVUTIL_SOCK_NONBLOCK, evutil_socket_(), and evutil_socket_connect_().
Referenced by bufferevent_connect_getaddrinfo_cb(), dogecoin_node_group_connect_next_nodes(), and evhttp_connection_connect_().
bufferevent_socket_connect_hostname()
int bufferevent_socket_connect_hostname (struct bufferevent * bev, struct evdns_base * evdns_base, int family, const char * hostname, int port)
Definition at line 494 of file bufferevent_sock.c.
{
    char portbuf[10];
    struct evutil_addrinfo hint;
    struct bufferevent_private *bev_p = BEV_UPCAST(bev);
    if (family != AF_INET && family != AF_INET6 && family != AF_UNSPEC)
        return -1;
    if (port < 1 || port > 65535)
        return -1;
    memset(&hint, 0, sizeof(hint));
    hint.ai_family = family;
    hint.ai_protocol = IPPROTO_TCP;
    hint.ai_socktype = SOCK_STREAM;
    evutil_snprintf(portbuf, sizeof(portbuf), "%d", port);
    BEV_LOCK(bev);
    bev_p->dns_error = 0;
    bufferevent_suspend_write_(bev, BEV_SUSPEND_LOOKUP);
    bufferevent_suspend_read_(bev, BEV_SUSPEND_LOOKUP);
    bufferevent_incref_(bev);
    bev_p->dns_request = evutil_getaddrinfo_async_(evdns_base, hostname,
        portbuf, &hint, bufferevent_connect_getaddrinfo_cb, bev);
    BEV_UNLOCK(bev);
    return 0;
}
References AF_INET6, bufferevent_private::bev, BEV_LOCK, BEV_SUSPEND_LOOKUP, BEV_UNLOCK, BEV_UPCAST, bufferevent_connect_getaddrinfo_cb(), bufferevent_incref_, bufferevent_suspend_read_(), bufferevent_suspend_write_(), bufferevent_private::dns_error, bufferevent_private::dns_request, evutil_getaddrinfo_async_(), and evutil_snprintf().
Referenced by evhttp_connection_connect_().
bufferevent_socket_get_conn_address_()
const struct sockaddr * bufferevent_socket_get_conn_address_ (struct bufferevent * bev)
Definition at line 100 of file bufferevent_sock.c.
{
    struct bufferevent_private *bev_p = BEV_UPCAST(bev);
    return (struct sockaddr *)&bev_p->conn_address;
}
References bufferevent_private::bev, BEV_UPCAST, and bufferevent_private::conn_address.
Referenced by evhttp_connection_get_addr().
bufferevent_socket_get_dns_error()
int bufferevent_socket_get_dns_error (struct bufferevent * bev)
Definition at line 528 of file bufferevent_sock.c.
{
    int rv;
    struct bufferevent_private *bev_p = BEV_UPCAST(bev);
    BEV_LOCK(bev);
    rv = bev_p->dns_error;
    BEV_UNLOCK(bev);
    return rv;
}
References bufferevent_private::bev, BEV_LOCK, BEV_UNLOCK, BEV_UPCAST, and bufferevent_private::dns_error.
bufferevent_socket_new()
struct bufferevent * bufferevent_socket_new (struct event_base * base, evutil_socket_t fd, int options)
Definition at line 344 of file bufferevent_sock.c.
{
    struct bufferevent_private *bufev_p;
    struct bufferevent *bufev;
#ifdef _WIN32
    if (base && event_base_get_iocp_(base))
        return bufferevent_async_new_(base, fd, options);
#endif
    if ((bufev_p = mm_calloc(1, sizeof(struct bufferevent_private)))== NULL)
        return NULL;
    if (bufferevent_init_common_(bufev_p, base, &bufferevent_ops_socket,
                    options) < 0) {
        mm_free(bufev_p);
        return NULL;
    }
    bufev = &bufev_p->bev;
    evbuffer_set_flags(bufev->output, EVBUFFER_FLAG_DRAINS_TO_FD);
    event_assign(&bufev->ev_read, bufev->ev_base, fd,
        EV_READ|EV_PERSIST|EV_FINALIZE, bufferevent_readcb, bufev);
    event_assign(&bufev->ev_write, bufev->ev_base, fd,
        EV_WRITE|EV_PERSIST|EV_FINALIZE, bufferevent_writecb, bufev);
    evbuffer_add_cb(bufev->output, bufferevent_socket_outbuf_cb, bufev);
    evbuffer_freeze(bufev->input, 0);
    evbuffer_freeze(bufev->output, 1);
    return bufev;
}
References bufferevent_private::bev, bufferevent_async_new_(), bufferevent_init_common_(), bufferevent_ops_socket, bufferevent_readcb(), bufferevent_socket_outbuf_cb(), bufferevent_writecb(), evbuffer_add_cb(), evbuffer_freeze(), evbuffer_set_flags(), event_assign(), event_base_get_iocp_(), mm_calloc, and mm_free.
Referenced by bufferevent_new(), dogecoin_node_group_connect_next_nodes(), and evhttp_connection_base_bufferevent_new().
bufferevent_socket_outbuf_cb()
static void bufferevent_socket_outbuf_cb (struct evbuffer * buf, const struct evbuffer_cb_info * cbinfo, void * arg) static
Definition at line 129 of file bufferevent_sock.c.
{
    struct bufferevent *bufev = arg;
    struct bufferevent_private *bufev_p = BEV_UPCAST(bufev);
    if (cbinfo->n_added &&
        (bufev->enabled & EV_WRITE) &&
        !event_pending(&bufev->ev_write, EV_WRITE, NULL) &&
        !bufev_p->write_suspended) {
        /* Somebody added data to the buffer, and we would like to
         * write, and we were not writing.  So, start writing. */
        if (bufferevent_add_event_(&bufev->ev_write, &bufev->timeout_write) == -1) {
            /* Should we log this? */
        }
    }
}
References BEV_UPCAST, bufferevent_add_event_(), event_pending(), and bufferevent_private::write_suspended.
Referenced by bufferevent_socket_new().
bufferevent_socket_set_conn_address_()
void bufferevent_socket_set_conn_address_ (struct bufferevent * bev, struct sockaddr * addr, size_t addrlen)
Definition at line 120 of file bufferevent_sock.c.
{
    struct bufferevent_private *bev_p = BEV_UPCAST(bev);
    EVUTIL_ASSERT(addrlen <= sizeof(bev_p->conn_address));
    memcpy(&bev_p->conn_address, addr, addrlen);
}
References bufferevent_private::bev, BEV_UPCAST, bufferevent_private::conn_address, and EVUTIL_ASSERT.
Referenced by bufferevent_connect_getaddrinfo_cb(), and evhttp_get_request_connection().
bufferevent_socket_set_conn_address_fd_()
void bufferevent_socket_set_conn_address_fd_ (struct bufferevent * bev, evutil_socket_t fd)
Definition at line 107 of file bufferevent_sock.c.
{
    struct bufferevent_private *bev_p = BEV_UPCAST(bev);
    socklen_t len = sizeof(bev_p->conn_address);
    struct sockaddr *addr = (struct sockaddr *)&bev_p->conn_address;
    if (addr->sa_family != AF_UNSPEC)
        getpeername(fd, addr, &len);
}
References bufferevent_private::bev, BEV_UPCAST, and bufferevent_private::conn_address.
Referenced by bufferevent_writecb().
bufferevent_writecb()
static void bufferevent_writecb (evutil_socket_t fd, short event, void * arg) static
Definition at line 230 of file bufferevent_sock.c.
{
    struct bufferevent *bufev = arg;
    struct bufferevent_private *bufev_p = BEV_UPCAST(bufev);
    int res = 0;
    short what = BEV_EVENT_WRITING;
    int connected = 0;
    ev_ssize_t atmost = -1;
    bufferevent_incref_and_lock_(bufev);
    if (event == EV_TIMEOUT) {
        /* Note that we only check for event==EV_TIMEOUT. If
         * event==EV_TIMEOUT|EV_WRITE, we can safely ignore the
         * timeout, since a read has occurred */
        what |= BEV_EVENT_TIMEOUT;
        goto error;
    }
    if (bufev_p->connecting) {
        int c = evutil_socket_finished_connecting_(fd);
        /* we need to fake the error if the connection was refused
         * immediately - usually connection to localhost on BSD */
        if (bufev_p->connection_refused) {
            bufev_p->connection_refused = 0;
            c = -1;
        }
        if (c == 0)
            goto done;
        bufev_p->connecting = 0;
        if (c < 0) {
            event_del(&bufev->ev_write);
            event_del(&bufev->ev_read);
            bufferevent_run_eventcb_(bufev, BEV_EVENT_ERROR, 0);
            goto done;
        } else {
            connected = 1;
            bufferevent_socket_set_conn_address_fd_(bufev, fd);
#ifdef _WIN32
            if (BEV_IS_ASYNC(bufev)) {
                event_del(&bufev->ev_write);
                bufferevent_async_set_connected_(bufev);
                bufferevent_run_eventcb_(bufev,
                        BEV_EVENT_CONNECTED, 0);
                goto done;
            }
#endif
            bufferevent_run_eventcb_(bufev,
                    BEV_EVENT_CONNECTED, 0);
            if (!(bufev->enabled & EV_WRITE) ||
                bufev_p->write_suspended) {
                event_del(&bufev->ev_write);
                goto done;
            }
        }
    }
    atmost = bufferevent_get_write_max_(bufev_p);
    if (bufev_p->write_suspended)
        goto done;
    if (evbuffer_get_length(bufev->output)) {
        evbuffer_unfreeze(bufev->output, 1);
        res = evbuffer_write_atmost(bufev->output, fd, atmost);
        evbuffer_freeze(bufev->output, 1);
        if (res == -1) {
            int err = evutil_socket_geterror(fd);
            if (EVUTIL_ERR_RW_RETRIABLE(err))
                goto reschedule;
            what |= BEV_EVENT_ERROR;
        } else if (res == 0) {
            /* eof case
               XXXX Actually, a 0 on write doesn't indicate
               an EOF. An ECONNRESET might be more typical.
             */
            what |= BEV_EVENT_EOF;
        }
        if (res <= 0)
            goto error;
        bufferevent_decrement_write_buckets_(bufev_p, res);
    }
    if (evbuffer_get_length(bufev->output) == 0) {
        event_del(&bufev->ev_write);
    }
    /*
     * Invoke the user callback if our buffer is drained or below the
     * low watermark.
     */
    if (res || !connected) {
        bufferevent_trigger_nolock_(bufev, EV_WRITE, 0);
    }
    goto done;
 reschedule:
    if (evbuffer_get_length(bufev->output) == 0) {
        event_del(&bufev->ev_write);
    }
    goto done;
 error:
    bufferevent_disable(bufev, EV_WRITE);
    bufferevent_run_eventcb_(bufev, what, 0);
 done:
    bufferevent_decref_and_unlock_(bufev);
}
References BEV_IS_ASYNC, BEV_UPCAST, bufferevent_async_set_connected_(), bufferevent_decref_and_unlock_(), bufferevent_decrement_write_buckets_(), bufferevent_disable(), bufferevent_get_write_max_(), bufferevent_incref_and_lock_(), bufferevent_run_eventcb_(), bufferevent_socket_set_conn_address_fd_(), bufferevent_trigger_nolock_(), bufferevent_private::connecting, bufferevent_private::connection_refused, evbuffer_freeze(), evbuffer_get_length(), evbuffer_unfreeze(), evbuffer_write_atmost(), event_del(), EVUTIL_ERR_RW_RETRIABLE, evutil_socket_finished_connecting_(), and bufferevent_private::write_suspended.
Referenced by be_socket_setfd(), bufferevent_socket_connect(), and bufferevent_socket_new().
Variable Documentation
bufferevent_ops_socket
const struct bufferevent_ops bufferevent_ops_socket
Initial value:
= {
    "socket",
    evutil_offsetof(struct bufferevent_private, bev),
    be_socket_enable,
    be_socket_disable,
    NULL,
    be_socket_destruct,
    bufferevent_generic_adj_existing_timeouts_,
    be_socket_flush,
    be_socket_ctrl,
}
Definition at line 87 of file bufferevent_sock.c.
Referenced by bufferevent_socket_new().