libdogecoin: src/libevent/changelist-internal.h File Reference
changelist-internal.h File Reference
#include "event2/util.h"
Data Structures
struct event_change
Macros
#define EV_CHANGE_ADD 0x01
#define EV_CHANGE_DEL 0x02
#define EV_CHANGE_SIGNAL EV_SIGNAL
#define EV_CHANGE_PERSIST EV_PERSIST
#define EV_CHANGE_ET EV_ET
#define EVENT_CHANGELIST_FDINFO_SIZE sizeof(int)
Functions
void event_changelist_init_ (struct event_changelist *changelist)
void event_changelist_remove_all_ (struct event_changelist *changelist, struct event_base *base)
void event_changelist_freemem_ (struct event_changelist *changelist)
int event_changelist_add_ (struct event_base *base, evutil_socket_t fd, short old, short events, void *p)
int event_changelist_del_ (struct event_base *base, evutil_socket_t fd, short old, short events, void *p)
Macro Definition Documentation
EV_CHANGE_ADD
#define EV_CHANGE_ADD 0x01
Definition at line 71 of file changelist-internal.h.
EV_CHANGE_DEL
#define EV_CHANGE_DEL 0x02
Definition at line 73 of file changelist-internal.h.
EV_CHANGE_ET
#define EV_CHANGE_ET EV_ET
Definition at line 79 of file changelist-internal.h.
EV_CHANGE_PERSIST
#define EV_CHANGE_PERSIST EV_PERSIST
Definition at line 77 of file changelist-internal.h.
EV_CHANGE_SIGNAL
#define EV_CHANGE_SIGNAL EV_SIGNAL
Definition at line 75 of file changelist-internal.h.
EVENT_CHANGELIST_FDINFO_SIZE
#define EVENT_CHANGELIST_FDINFO_SIZE sizeof(int)
Definition at line 83 of file changelist-internal.h.
Function Documentation
event_changelist_add_()
int event_changelist_add_ (struct event_base * base, evutil_socket_t fd, short old, short events, void * p)
Implementation of eventop_add that queues the event in a changelist.
Definition at line 866 of file evmap.c.
{
    struct event_changelist *changelist = &base->changelist;
    struct event_changelist_fdinfo *fdinfo = p;
    struct event_change *change;
    ev_uint8_t evchange = EV_CHANGE_ADD | (events & (EV_ET|EV_PERSIST|EV_SIGNAL));
    event_changelist_check(base);
    change = event_changelist_get_or_construct(changelist, fd, old, fdinfo);
    if (!change)
        return -1;
    /* An add replaces any previous delete, but doesn't result in a no-op,
     * since the delete might fail (because the fd had been closed since
     * the last add, for instance. */
    if (events & (EV_READ|EV_SIGNAL))
        change->read_change = evchange;
    if (events & EV_WRITE)
        change->write_change = evchange;
    if (events & EV_CLOSED)
        change->close_change = evchange;
    event_changelist_check(base);
    return (0);
}
References event_base::changelist, event_change::close_change, EV_CHANGE_ADD, event_changelist_check, event_changelist_get_or_construct(), event_change::fd, event_change::read_change, and event_change::write_change.
Referenced by evmap_check_integrity_().
event_changelist_del_()
int event_changelist_del_ (struct event_base * base, evutil_socket_t fd, short old, short events, void * p)
Implementation of eventop_del that queues the event in a changelist.
Definition at line 896 of file evmap.c.
{
    struct event_changelist *changelist = &base->changelist;
    struct event_changelist_fdinfo *fdinfo = p;
    struct event_change *change;
    ev_uint8_t del = EV_CHANGE_DEL | (events & EV_ET);
    event_changelist_check(base);
    change = event_changelist_get_or_construct(changelist, fd, old, fdinfo);
    event_changelist_check(base);
    if (!change)
        return -1;
    /* A delete on an event set that doesn't contain the event to be
       deleted produces a no-op.  This effectively emoves any previous
       uncommitted add, rather than replacing it: on those platforms where
       "add, delete, dispatch" is not the same as "no-op, dispatch", we
       want the no-op behavior.
       If we have a no-op item, we could remove it it from the list
       entirely, but really there's not much point: skipping the no-op
       change when we do the dispatch later is far cheaper than rejuggling
       the array now.
       As this stands, it also lets through deletions of events that are
       not currently set.
     */
    if (events & (EV_READ|EV_SIGNAL)) {
        if (!(change->old_events & (EV_READ | EV_SIGNAL)))
            change->read_change = 0;
        else
            change->read_change = del;
    }
    if (events & EV_WRITE) {
        if (!(change->old_events & EV_WRITE))
            change->write_change = 0;
        else
            change->write_change = del;
    }
    if (events & EV_CLOSED) {
        if (!(change->old_events & EV_CLOSED))
            change->close_change = 0;
        else
            change->close_change = del;
    }
    event_changelist_check(base);
    return (0);
}
References event_base::changelist, event_change::close_change, EV_CHANGE_DEL, event_changelist_check, event_changelist_get_or_construct(), event_change::fd, event_change::old_events, event_change::read_change, and event_change::write_change.
event_changelist_freemem_()
void event_changelist_freemem_ (struct event_changelist * changelist)
Free all memory held in a changelist.
Definition at line 800 of file evmap.c.
{
    if (changelist->changes)
        mm_free(changelist->changes);
    event_changelist_init_(changelist); /* zero it all out. */
}
References event_changelist::changes, event_changelist_init_(), and mm_free.
Referenced by event_base_free_(), and event_reinit().
event_changelist_init_()
void event_changelist_init_ (struct event_changelist * changelist)
Set up the data fields in a changelist.
Definition at line 708 of file evmap.c.
{
    changelist->changes = NULL;
    changelist->changes_size = 0;
    changelist->n_changes = 0;
}
References event_changelist::changes, event_changelist::changes_size, and event_changelist::n_changes.
Referenced by event_base_new_with_config(), and event_changelist_freemem_().
event_changelist_remove_all_()
void event_changelist_remove_all_ (struct event_changelist * changelist, struct event_base * base)
Remove every change in the changelist, and make corresponding changes in the event maps in the base. This function is generally used right after making all the changes in the changelist.
Definition at line 779 of file evmap.c.
{
    int i;
    event_changelist_check(base);
    for (i = 0; i < changelist->n_changes; ++i) {
        struct event_change *ch = &changelist->changes[i];
        struct event_changelist_fdinfo *fdinfo =
            event_change_get_fdinfo(base, ch);
        EVUTIL_ASSERT(fdinfo->idxplus1 == i + 1);
        fdinfo->idxplus1 = 0;
    }
    changelist->n_changes = 0;
    event_changelist_check(base);
}
References event_changelist::changes, event_change_get_fdinfo(), event_changelist_check, EVUTIL_ASSERT, event_changelist_fdinfo::idxplus1, and event_changelist::n_changes.