libdogecoin: src/cstr.c File Reference
cstr.c File Reference
#include <dogecoin/cstr.h>
#include <dogecoin/mem.h>
Functions
static int cstr_alloc_min_sz (cstring *s, size_t sz)
This function takes a cstring and allocates a new buffer of the specified size. If the buffer is already allocated and is large enough, no change occurs.
int cstr_alloc_minsize (cstring *s, size_t new_sz)
This function takes a cstring and allocates a new buffer of the specified size. If the new size is greater than the current, it allocates a new buffer of this size and copies the buffer's contents to the new location. If the new size is smaller, the string will be truncated.
cstring * cstr_new_sz (size_t sz)
This function allocates a new cstring of the specified size.
cstring * cstr_new_buf (const void *buf, size_t sz)
The function creates a new cstring and initializes it with the first sz bytes of the specified buffer.
cstring * cstr_new_cstr (const cstring *copy_str)
This function creates a new cstring from an existing cstring.
cstring * cstr_new (const char *init_str)
void cstr_free (cstring *s, int free_buf)
This function frees the memory allocated for the cstring object.
int cstr_resize (cstring *s, size_t new_sz)
This function resizes the buffer inside cstring object.
int cstr_append_buf (cstring *s, const void *buf, size_t sz)
This function appends the contents of a buffer to the buffer of the specified cstring, resizing the destination buffer as necessary.
int cstr_append_cstr (cstring *s, cstring *append)
This function appends the contents of one cstring to another, resizing the destination buffer as necessary.
int cstr_append_c (cstring *s, char ch)
This function appends a single character to the buffer of a cstring.
int cstr_equal (const cstring *a, const cstring *b)
This function compares two cstrings and checks if their contents are equal.
int cstr_compare (const cstring *a, const cstring *b)
This function compares the buffers of two cstrings and returns which one is greater.
int cstr_erase (cstring *s, size_t pos, ssize_t len)
This function erases the characters in the string starting at position pos and ending at pos + len.
Function Documentation
cstr_alloc_min_sz()
static int cstr_alloc_min_sz (cstring * s, size_t sz) static
This function takes a cstring and allocates a new buffer of the specified size. If the buffer is already allocated and is large enough, no change occurs.
Parameters
s The cstring whose buffer is to be reallocated.
sz The new desired size of the buffer.
Returns
1 if the buffer is allocated successfully, 0 otherwise.
Definition at line 22 of file cstr.c.
{
    unsigned int shift;
    unsigned int al_sz;
    char* new_s;
    sz++; /* NULL overhead */
    if (s->alloc && (s->alloc >= sz)) {
        return 1;
    }
    shift = 3;
    while ((al_sz = (1 << shift)) < sz) {
        shift++;
    }
    new_s = dogecoin_realloc(s->str, al_sz);
    if (!new_s) {
        return 0;
    }
    s->str = new_s;
    s->alloc = al_sz;
    s->str[s->len] = 0;
    return 1;
}
References cstring::alloc, dogecoin_realloc(), cstring::len, and cstring::str.
Referenced by cstr_alloc_minsize(), cstr_append_buf(), cstr_new_sz(), and cstr_resize().
cstr_alloc_minsize()
int cstr_alloc_minsize (cstring * s, size_t new_sz)
This function takes a cstring and allocates a new buffer of the specified size. If the new size is greater than the current, it allocates a new buffer of this size and copies the buffer's contents to the new location. If the new size is smaller, the string will be truncated.
Parameters
s The pointer to the cstring whose buffer is to be resized.
sz The new desired size of the buffer.
Returns
1 if the buffer was successfully resized, 0 otherwise.
Definition at line 64 of file cstr.c.
{
    /* no change */
    if (new_sz == s->len) {
        return 1;
    }
    /* truncate string */
    if (new_sz <= s->len) {
        return 0;
    }
    /* increase string size */
    if (!cstr_alloc_min_sz(s, new_sz)) {
        return 0;
    }
    /* contents of string tail undefined */
    // s->len = new_sz;
    s->str[s->len] = 0;
    return 1;
}
References cstr_alloc_min_sz(), cstring::len, and cstring::str.
Referenced by read_cb().
cstr_append_buf()
int cstr_append_buf (cstring * s, const void * buf, size_t sz)
This function appends the contents of a buffer to the buffer of the specified cstring, resizing the destination buffer as necessary.
Parameters
s The pointer to the cstring to append to.
buf The buffer to be appended.
sz The size of the buffer to be appended.
Returns
1 if the data was appended successfully, 0 otherwise.
Definition at line 235 of file cstr.c.
{
    if (!cstr_alloc_min_sz(s, s->len + sz)) {
        return 0;
    }
    memcpy_safe(s->str + s->len, buf, sz);
    s->len += sz;
    s->str[s->len] = 0;
    return 1;
}
References cstr_alloc_min_sz(), cstring::len, memcpy_safe(), and cstring::str.
Referenced by cstr_append_c(), cstr_append_cstr(), deser_varstr(), dogecoin_get_default_datadir(), dogecoin_p2p_message_new(), dogecoin_script_append_op(), dogecoin_script_append_pushdata(), dogecoin_script_build_multisig(), dogecoin_script_copy_without_op_codeseperator(), dogecoin_tx_in_copy(), dogecoin_tx_out_copy(), dogecoin_tx_sighash(), ser_bytes(), ser_u16(), ser_u32(), and ser_u64().
cstr_append_c()
int cstr_append_c (cstring * s, char ch)
This function appends a single character to the buffer of a cstring.
Parameters
s The pointer to the cstring to append to.
ch The character to be appended.
Returns
1 if the character was appended successfully, 0 otherwise.
Definition at line 273 of file cstr.c.
{
    return cstr_append_buf(s, &ch, 1);
}
References cstr_append_buf().
Referenced by dogecoin_get_default_datadir(), and dogecoin_p2p_msg_version_ser().
cstr_append_cstr()
int cstr_append_cstr (cstring * s, cstring * append)
This function appends the contents of one cstring to another, resizing the destination buffer as necessary.
Parameters
s The pointer to the cstring to append to.
append The pointer to the cstring whose buffer will be appended.
Returns
1 if the cstring was appended successfully, 0 otherwise.
Definition at line 258 of file cstr.c.
{
    return cstr_append_buf(s, append->str, append->len);
}
References append(), and cstr_append_buf().
cstr_compare()
int cstr_compare (const cstring * a, const cstring * b)
This function compares the buffers of two cstrings and returns which one is greater.
Parameters
a The pointer to the cstring to compare.
b The pointer to the reference cstring.
Returns
1 if the string value of a is greater, -1 if the string value of b is greater, 0 if the strings are equal.
Definition at line 313 of file cstr.c.
{
    unsigned int i;
    if (a->len > b->len) {
        return (1);
    }
    if (a->len < b->len) {
        return (-1);
    }
    /* length equal, byte per byte compare */
    for (i = 0; i < a->len; i++) {
        char a1 = a->str[i];
        char b1 = b->str[i];
        if (a1 > b1) {
            return (1);
        }
        if (a1 < b1) {
            return (-1);
        }
    }
    return (0);
}
References cstring::len, and cstring::str.
cstr_equal()
int cstr_equal (const cstring * a, const cstring * b)
This function compares two cstrings and checks if their contents are equal.
Parameters
a The pointer to the reference cstring.
b The pointer to the cstring to compare.
Returns
1 if the contents are equal, 0 otherwise.
Definition at line 288 of file cstr.c.
{
    if (a == b) {
        return 1;
    }
    if (!a || !b) {
        return 0;
    }
    if (a->len != b->len) {
        return 0;
    }
    return (memcmp(a->str, b->str, a->len) == 0);
}
References cstring::len, and cstring::str.
cstr_erase()
int cstr_erase (cstring * s, size_t pos, ssize_t len)
This function erases the characters in the string starting at position pos and ending at pos + len.
Parameters
s The pointer to the cstring to modify.
pos The index of the buffer to start erasing from.
len The number of characters to remove.
Returns
The number of characters successfully erased.
Definition at line 349 of file cstr.c.
{
    ssize_t old_tail;
    if (pos == s->len && len == 0) {
        return 1;
    }
    if (pos >= s->len) {
        return 0;
    }
    old_tail = s->len - pos;
    if ((len >= 0) && (len > old_tail)) {
        return 0;
    }
    memmove(&s->str[pos], &s->str[pos + len], old_tail - len);
    s->len -= len;
    s->str[s->len] = 0;
    return 1;
}
References cstring::len, and cstring::str.
Referenced by transaction_input_menu().
cstr_free()
void cstr_free (cstring * s, int free_buf)
This function frees the memory allocated for the cstring object.
Parameters
s The pointer to the cstring to be freed.
free_buf Whether the buffer inside the cstring should be freed.
Returns
Nothing.
Definition at line 173 of file cstr.c.
{
    if (!s) {
        return;
    }
    if (free_buf) {
        dogecoin_free(s->str);
    }
    dogecoin_mem_zero(s, sizeof(*s));
    dogecoin_free(s);
}
References dogecoin_free(), dogecoin_mem_zero(), and cstring::str.
Referenced by broadcast_handshake_done(), broadcast_post_cmd(), deser_varstr(), dogecoin_block_header_hash(), dogecoin_node_free(), dogecoin_node_parse_message(), dogecoin_node_send_version(), dogecoin_tx_hash(), dogecoin_tx_in_free(), dogecoin_tx_out_free(), dogecoin_tx_outputs_hash(), dogecoin_tx_prevout_hash(), dogecoin_tx_sequence_hash(), dogecoin_tx_sighash(), dogecoin_tx_sign_input(), get_raw_transaction(), main(), node_periodical_timer(), read_cb(), and sign_raw_transaction().
cstr_new()
cstring * cstr_new (const char * init_str)
Definition at line 151 of file cstr.c.
{
    size_t slen;
    if (!init_str || !*init_str) {
        return cstr_new_sz(0);
    }
    slen = strlen(init_str);
    return cstr_new_buf(init_str, slen);
}
References cstr_new_buf(), and cstr_new_sz().
cstr_new_buf()
cstring * cstr_new_buf (const void * buf, size_t sz)
The function creates a new cstring and initializes it with the first sz bytes of the specified buffer.
Parameters
buf The data to be copied into the cstring.
sz The size of the string to allocate and initialize.
Returns
A pointer to the new cstring object.
Definition at line 123 of file cstr.c.
{
    cstring* s = cstr_new_sz(sz);
    if (!s) {
        return NULL;
    }
    memcpy_safe(s->str, buf, sz);
    s->len = sz;
    s->str[s->len] = 0;
    return s;
}
References cstr_new_sz(), cstring::len, memcpy_safe(), and cstring::str.
Referenced by cstr_new(), cstr_new_cstr(), main(), read_cb(), and sign_raw_transaction().
cstr_new_cstr()
cstring * cstr_new_cstr (const cstring * copy_str)
This function creates a new cstring from an existing cstring.
Parameters
copy_str The cstring object to be copied.
Returns
A pointer to the new cstring object.
Definition at line 146 of file cstr.c.
{
    return cstr_new_buf(copy_str->str, copy_str->len);
}
References cstr_new_buf(), cstring::len, and cstring::str.
Referenced by dogecoin_tx_sign_input().
cstr_new_sz()
cstring * cstr_new_sz (size_t sz)
This function allocates a new cstring of the specified size.
Parameters
sz The size of the string to allocate.
Returns
a pointer to the new cstring object.
Definition at line 97 of file cstr.c.
{
    cstring* s = dogecoin_calloc(1, sizeof(cstring));
    if (!s) {
        return NULL;
    }
    if (!cstr_alloc_min_sz(s, sz)) {
        dogecoin_free(s);
        return NULL;
    }
    return s;
}
References cstr_alloc_min_sz(), dogecoin_calloc(), and dogecoin_free().
Referenced by broadcast_handshake_done(), broadcast_post_cmd(), cstr_new(), cstr_new_buf(), deser_varstr(), dogecoin_block_header_hash(), dogecoin_node_new(), dogecoin_node_send_version(), dogecoin_p2p_message_new(), dogecoin_tx_add_data_out(), dogecoin_tx_add_p2pkh_hash160_out(), dogecoin_tx_add_p2sh_hash160_out(), dogecoin_tx_add_puzzle_out(), dogecoin_tx_hash(), dogecoin_tx_in_copy(), dogecoin_tx_out_copy(), dogecoin_tx_outputs_hash(), dogecoin_tx_prevout_hash(), dogecoin_tx_sequence_hash(), dogecoin_tx_sighash(), get_raw_transaction(), main(), and sign_raw_transaction().
cstr_resize()
int cstr_resize (cstring * s, size_t new_sz)
This function resizes the buffer inside cstring object.
Parameters
s The pointer to the cstring whose buffer is to be resized.
new_sz The new desired size of the buffer.
Returns
1 if buffer was resized successfully, 0 otherwise.
Definition at line 196 of file cstr.c.
{
    /* no change */
    if (new_sz == s->len) {
        return 1;
    }
    /* truncate string */
    if (new_sz <= s->len) {
        s->len = new_sz;
        s->str[s->len] = 0;
        return 1;
    }
    /* increase string size */
    if (!cstr_alloc_min_sz(s, new_sz)) {
        return 0;
    }
    /* contents of string tail undefined */
    s->len = new_sz;
    s->str[s->len] = 0;
    return 1;
}
References cstr_alloc_min_sz(), cstring::len, and cstring::str.
Referenced by dogecoin_script_build_multisig(), dogecoin_script_build_p2pkh(), dogecoin_script_build_p2sh(), and dogecoin_tx_sighash().