libdogecoin: src/libevent/defer-internal.h File Reference
defer-internal.h File Reference
#include "event2/event-config.h"
#include "evconfig-private.h"
#include <sys/queue.h>
Typedefs
typedef void(* deferred_cb_fn) (struct event_callback *, void *)
Functions
EVENT2_EXPORT_SYMBOL void event_deferred_cb_init_ (struct event_callback *, ev_uint8_t, deferred_cb_fn, void *)
void event_deferred_cb_set_priority_ (struct event_callback *, ev_uint8_t)
EVENT2_EXPORT_SYMBOL void event_deferred_cb_cancel_ (struct event_base *, struct event_callback *)
EVENT2_EXPORT_SYMBOL int event_deferred_cb_schedule_ (struct event_base *, struct event_callback *)
Typedef Documentation
deferred_cb_fn
typedef void(* deferred_cb_fn) (struct event_callback *, void *)
Definition at line 39 of file defer-internal.h.
Function Documentation
event_deferred_cb_cancel_()
EVENT2_EXPORT_SYMBOL void event_deferred_cb_cancel_ (struct event_base * base, struct event_callback * cb)
Cancel a struct event_callback if it is currently scheduled in an event_base.
Definition at line 3115 of file event.c.
{
    if (!base)
        base = current_base;
    event_callback_cancel_(base, cb);
}
References current_base, and event_callback_cancel_().
Referenced by evbuffer_decref_and_unlock_(), evhttp_connection_free(), and evhttp_read_cb().
event_deferred_cb_init_()
EVENT2_EXPORT_SYMBOL void event_deferred_cb_init_ (struct event_callback * cb, ev_uint8_t priority, deferred_cb_fn fn, void * arg)
Initialize an empty, non-pending event_callback.
Parameters
deferred The struct event_callback structure to initialize.
priority The priority that the callback should run at.
cb The function to run when the struct event_callback executes.
arg The function's second argument.
Definition at line 3099 of file event.c.
{
    memset(cb, 0, sizeof(*cb));
    cb->evcb_cb_union.evcb_selfcb = fn;
    cb->evcb_arg = arg;
    cb->evcb_pri = priority;
    cb->evcb_closure = EV_CLOSURE_CB_SELF;
}
References EV_CLOSURE_CB_SELF.
Referenced by bufferevent_init_common_(), evbuffer_defer_callbacks(), evhttp_connection_base_bufferevent_new(), and reply_schedule_callback().
event_deferred_cb_schedule_()
EVENT2_EXPORT_SYMBOL int event_deferred_cb_schedule_ (struct event_base * base, struct event_callback * cb)
Activate a struct event_callback if it is not currently scheduled in an event_base.
Return true if it was not previously scheduled.
Definition at line 3124 of file event.c.
{
    int r = 1;
    if (!base)
        base = current_base;
    EVBASE_ACQUIRE_LOCK(base, th_base_lock);
    if (base->n_deferreds_queued > MAX_DEFERREDS_QUEUED) {
        r = event_callback_activate_later_nolock_(base, cb);
    } else {
        r = event_callback_activate_nolock_(base, cb);
        if (r) {
            ++base->n_deferreds_queued;
        }
    }
    EVBASE_RELEASE_LOCK(base, th_base_lock);
    return r;
}
References current_base, EVBASE_ACQUIRE_LOCK, EVBASE_RELEASE_LOCK, event_callback_activate_later_nolock_(), event_callback_activate_nolock_(), MAX_DEFERREDS_QUEUED, event_base::n_deferreds_queued, and event_base::th_base_lock.
Referenced by evbuffer_invoke_callbacks_(), evhttp_error_cb(), evhttp_start_read_(), and reply_schedule_callback().
event_deferred_cb_set_priority_()
void event_deferred_cb_set_priority_ (struct event_callback * cb, ev_uint8_t priority)
Change the priority of a non-pending event_callback.
Definition at line 3109 of file event.c.
{
    cb->evcb_pri = priority;
}
Referenced by bufferevent_priority_set().