libdogecoin: src/ecc.c File Reference
ecc.c File Reference
#include <assert.h>
#include <stdint.h>
#include <string.h>
#include <dogecoin/random.h>
#include <dogecoin/dogecoin.h>
#include <dogecoin/utils.h>
#include "secp256k1/include/secp256k1.h"
#include "secp256k1/include/secp256k1_recovery.h"
Functions
dogecoin_bool dogecoin_ecc_start (void)
init static ecc context
void dogecoin_ecc_stop (void)
destroys the static ecc context
void dogecoin_ecc_get_pubkey (const uint8_t *private_key, uint8_t *public_key, size_t *in_outlen, dogecoin_bool compressed)
get public key from given private key
dogecoin_bool dogecoin_ecc_private_key_tweak_add (uint8_t *private_key, const uint8_t *tweak)
ec mul tweak on given private key
dogecoin_bool dogecoin_ecc_public_key_tweak_add (uint8_t *public_key_inout, const uint8_t *tweak)
ec mul tweak on given public key
dogecoin_bool dogecoin_ecc_verify_privatekey (const uint8_t *private_key)
verifies a given 32byte key
dogecoin_bool dogecoin_ecc_verify_pubkey (const uint8_t *public_key, dogecoin_bool compressed)
verifies a given public key (compressed[33] or uncompressed[65] bytes)
dogecoin_bool dogecoin_ecc_sign (const uint8_t *private_key, const uint256 hash, unsigned char *sigder, size_t *outlen)
create a DER signature (72-74 bytes) with private key
dogecoin_bool dogecoin_ecc_sign_compact (const uint8_t *private_key, const uint256 hash, unsigned char *sigcomp, size_t *outlen)
create a compact (64bytes) signature with private key
dogecoin_bool dogecoin_ecc_sign_compact_recoverable (const uint8_t *private_key, const uint256 hash, unsigned char *sigrec, size_t *outlen, int *recid)
create a compact recoverable (65bytes) signature with private key
dogecoin_bool dogecoin_ecc_sign_compact_recoverable_fcomp (const uint8_t *private_key, const uint256 hash, unsigned char *sigrec, size_t *outlen, int *recid, bool fCompressed)
create a compact recoverable (65bytes) signature with private key with compressed or uncompressed bytes flag
dogecoin_bool dogecoin_recover_pubkey (const unsigned char *sigrec, const uint256 hash, const int recid, uint8_t *public_key, size_t *outlen)
recover a specific pubkey from a signature and recid
dogecoin_bool dogecoin_ecc_recover_pubkey (const unsigned char *sigrec, const uint256 hash, const int recid, uint8_t *public_key, size_t *outlen)
recover a pubkey from a signature and recid
dogecoin_bool dogecoin_ecc_verify_sig (const uint8_t *public_key, dogecoin_bool compressed, const uint256 hash, unsigned char *sigder, size_t siglen)
verify DER signature with public key
dogecoin_bool dogecoin_ecc_verify_sigcmp (const uint8_t *public_key, dogecoin_bool compressed, const uint256 hash, unsigned char *sigcmp)
verify compact signature with public key
dogecoin_bool dogecoin_ecc_compact_to_der_normalized (unsigned char *sigcomp_in, unsigned char *sigder_out, size_t *sigder_len_out)
converts (and normalized) a compact signature to DER
dogecoin_bool dogecoin_ecc_der_to_compact (unsigned char *sigder_in, size_t sigder_len, unsigned char *sigcomp_out)
convert DER signature to compact
Variables
static secp256k1_context * secp256k1_ctx = NULL
Function Documentation
dogecoin_ecc_compact_to_der_normalized()
dogecoin_bool dogecoin_ecc_compact_to_der_normalized (unsigned char * sigcomp_in, unsigned char * sigder_out, size_t * sigder_len_out)
converts (and normalized) a compact signature to DER
Definition at line 191 of file ecc.c.
{
    assert(secp256k1_ctx);
    secp256k1_ecdsa_signature sig;
    if (!secp256k1_ecdsa_signature_parse_compact(secp256k1_ctx, &sig, sigcomp_in))
        return false;
    secp256k1_ecdsa_signature sigNorm;
    secp256k1_ecdsa_signature_normalize(secp256k1_ctx, &sigNorm, &sig);
    return secp256k1_ecdsa_signature_serialize_der(secp256k1_ctx, sigder_out, sigder_len_out, &sigNorm);
}
References secp256k1_ctx, secp256k1_ecdsa_signature_normalize(), secp256k1_ecdsa_signature_parse_compact(), and secp256k1_ecdsa_signature_serialize_der().
Referenced by dogecoin_tx_sign_input(), and main().
dogecoin_ecc_der_to_compact()
dogecoin_bool dogecoin_ecc_der_to_compact (unsigned char * sigder_in, size_t sigder_len, unsigned char * sigcomp_out)
convert DER signature to compact
Definition at line 202 of file ecc.c.
{
    assert(secp256k1_ctx);
    secp256k1_ecdsa_signature sig;
    if (!secp256k1_ecdsa_signature_parse_der(secp256k1_ctx, &sig, sigder_in, sigder_len))
        return false;
    return secp256k1_ecdsa_signature_serialize_compact(secp256k1_ctx, sigcomp_out, &sig);
}
References secp256k1_ctx, secp256k1_ecdsa_signature_parse_der(), and secp256k1_ecdsa_signature_serialize_compact().
dogecoin_ecc_get_pubkey()
void dogecoin_ecc_get_pubkey (const uint8_t * private_key, uint8_t * public_key, size_t * in_outlen, dogecoin_bool compressed)
get public key from given private key
Definition at line 39 of file ecc.c.
{
    secp256k1_pubkey pubkey;
    assert(secp256k1_ctx);
    assert((int)*in_outlen == (compressed ? 33 : 65));
    dogecoin_mem_zero(public_key, *in_outlen);
    if (!secp256k1_ec_pubkey_create(secp256k1_ctx, &pubkey, (const unsigned char*)private_key))
        return;
    if (!secp256k1_ec_pubkey_serialize(secp256k1_ctx, public_key, in_outlen, &pubkey, compressed ? SECP256K1_EC_COMPRESSED : SECP256K1_EC_UNCOMPRESSED))
        return;
    return;
}
References dogecoin_mem_zero(), secp256k1_ctx, SECP256K1_EC_COMPRESSED, secp256k1_ec_pubkey_create(), secp256k1_ec_pubkey_serialize(), and SECP256K1_EC_UNCOMPRESSED.
Referenced by dogecoin_hdnode_fill_public_key(), and dogecoin_pubkey_from_key().
dogecoin_ecc_private_key_tweak_add()
dogecoin_bool dogecoin_ecc_private_key_tweak_add (uint8_t * private_key, const uint8_t * tweak)
ec mul tweak on given private key
Definition at line 52 of file ecc.c.
{
    assert(secp256k1_ctx);
    return secp256k1_ec_privkey_tweak_add(secp256k1_ctx, (unsigned char*)private_key, (const unsigned char*)tweak);
}
References secp256k1_ctx, and secp256k1_ec_privkey_tweak_add().
Referenced by dogecoin_hdnode_private_ckd().
dogecoin_ecc_public_key_tweak_add()
dogecoin_bool dogecoin_ecc_public_key_tweak_add (uint8_t * public_key_inout, const uint8_t * tweak)
ec mul tweak on given public key
Definition at line 58 of file ecc.c.
{
    size_t out = DOGECOIN_ECKEY_COMPRESSED_LENGTH;
    secp256k1_pubkey pubkey;
    assert(secp256k1_ctx);
    if (!secp256k1_ec_pubkey_parse(secp256k1_ctx, &pubkey, public_key_inout, 33))
        return false;
    if (!secp256k1_ec_pubkey_tweak_add(secp256k1_ctx, &pubkey, (const unsigned char*)tweak))
        return false;
    if (!secp256k1_ec_pubkey_serialize(secp256k1_ctx, public_key_inout, &out, &pubkey, SECP256K1_EC_COMPRESSED))
        return false;
    return true;
}
References DOGECOIN_ECKEY_COMPRESSED_LENGTH, secp256k1_ctx, SECP256K1_EC_COMPRESSED, secp256k1_ec_pubkey_parse(), secp256k1_ec_pubkey_serialize(), and secp256k1_ec_pubkey_tweak_add().
Referenced by dogecoin_hdnode_public_ckd().
dogecoin_ecc_recover_pubkey()
dogecoin_bool dogecoin_ecc_recover_pubkey (const unsigned char * sigrec, const uint256 hash, const int recid, uint8_t * public_key, size_t * outlen)
recover a pubkey from a signature and recid
Definition at line 151 of file ecc.c.
{
    assert(secp256k1_ctx);
    secp256k1_pubkey pubkey;
    secp256k1_ecdsa_recoverable_signature sig;
    if (!secp256k1_ecdsa_recoverable_signature_parse_compact(secp256k1_ctx, &sig, sigrec, recid))
        return false;
    if (!secp256k1_ecdsa_recover(secp256k1_ctx, &pubkey, &sig, hash))
        return 0;
    if (!secp256k1_ec_pubkey_serialize(secp256k1_ctx, public_key, outlen, &pubkey, SECP256K1_EC_COMPRESSED))
        return 0;
    return 1;
}
References secp256k1_ctx, SECP256K1_EC_COMPRESSED, secp256k1_ec_pubkey_serialize(), secp256k1_ecdsa_recover(), and secp256k1_ecdsa_recoverable_signature_parse_compact().
Referenced by dogecoin_key_sign_recover_pubkey().
dogecoin_ecc_sign()
dogecoin_bool dogecoin_ecc_sign (const uint8_t * private_key, const uint256 hash, unsigned char * sigder, size_t * outlen)
create a DER signature (72-74 bytes) with private key
Definition at line 90 of file ecc.c.
{
    assert(secp256k1_ctx);
    secp256k1_ecdsa_signature sig;
    if (!secp256k1_ecdsa_sign(secp256k1_ctx, &sig, hash, private_key, secp256k1_nonce_function_rfc6979, NULL))
        return 0;
    if (!secp256k1_ecdsa_signature_serialize_der(secp256k1_ctx, sigder, outlen, &sig))
        return 0;
    return 1;
}
References secp256k1_ctx, secp256k1_ecdsa_sign(), secp256k1_ecdsa_signature_serialize_der(), and secp256k1_nonce_function_rfc6979.
Referenced by dogecoin_key_sign_hash().
dogecoin_ecc_sign_compact()
dogecoin_bool dogecoin_ecc_sign_compact (const uint8_t * private_key, const uint256 hash, unsigned char * sigcomp, size_t * outlen)
create a compact (64bytes) signature with private key
Definition at line 101 of file ecc.c.
{
    assert(secp256k1_ctx);
    secp256k1_ecdsa_signature sig;
    if (!secp256k1_ecdsa_sign(secp256k1_ctx, &sig, hash, private_key, secp256k1_nonce_function_rfc6979, NULL))
        return 0;
    *outlen = 64;
    if (!secp256k1_ecdsa_signature_serialize_compact(secp256k1_ctx, sigcomp, &sig))
        return 0;
    return 1;
}
References secp256k1_ctx, secp256k1_ecdsa_sign(), secp256k1_ecdsa_signature_serialize_compact(), and secp256k1_nonce_function_rfc6979.
Referenced by dogecoin_key_sign_hash_compact().
dogecoin_ecc_sign_compact_recoverable()
dogecoin_bool dogecoin_ecc_sign_compact_recoverable (const uint8_t * private_key, const uint256 hash, unsigned char * sigrec, size_t * outlen, int * recid)
create a compact recoverable (65bytes) signature with private key
Definition at line 113 of file ecc.c.
{
    assert(secp256k1_ctx);
    secp256k1_ecdsa_recoverable_signature sig;
    if (!secp256k1_ecdsa_sign_recoverable(secp256k1_ctx, &sig, hash, private_key, secp256k1_nonce_function_rfc6979, NULL))
        return 0;
    *outlen = 65;
    if (!secp256k1_ecdsa_recoverable_signature_serialize_compact(secp256k1_ctx, sigrec, recid, &sig))
        return 0;
    return 1;
}
References secp256k1_ctx, secp256k1_ecdsa_recoverable_signature_serialize_compact(), secp256k1_ecdsa_sign_recoverable(), and secp256k1_nonce_function_rfc6979.
Referenced by dogecoin_key_sign_hash_compact_recoverable().
dogecoin_ecc_sign_compact_recoverable_fcomp()
dogecoin_bool dogecoin_ecc_sign_compact_recoverable_fcomp (const uint8_t * private_key, const uint256 hash, unsigned char * sigrec, size_t * outlen, int * recid, bool fCompressed)
create a compact recoverable (65bytes) signature with private key with compressed or uncompressed bytes flag
Definition at line 125 of file ecc.c.
{
    assert(secp256k1_ctx);
    secp256k1_ecdsa_recoverable_signature sig;
    if (!secp256k1_ecdsa_sign_recoverable(secp256k1_ctx, &sig, hash, private_key, secp256k1_nonce_function_rfc6979, NULL))
        return 0;
    *outlen = 65;
    secp256k1_ecdsa_recoverable_signature_serialize_compact(secp256k1_ctx, &sigrec[1], recid, &sig);
    sigrec[0] = (27 + *recid + (fCompressed ? 4 : 0));
    return true;
}
References secp256k1_ctx, secp256k1_ecdsa_recoverable_signature_serialize_compact(), secp256k1_ecdsa_sign_recoverable(), and secp256k1_nonce_function_rfc6979.
Referenced by dogecoin_key_sign_hash_compact_recoverable_fcomp().
dogecoin_ecc_start()
dogecoin_bool dogecoin_ecc_start (void)
init static ecc context
Definition at line 14 of file ecc.c.
{
    dogecoin_random_init();
    secp256k1_ctx = secp256k1_context_create(SECP256K1_CONTEXT_SIGN | SECP256K1_CONTEXT_VERIFY);
    if (secp256k1_ctx == NULL)
        return false;
    uint8_t seed[32];
    int ret;
    ret = dogecoin_random_bytes(seed, 32, 0);
    if (!ret)
        return false;
    ret = secp256k1_context_randomize(secp256k1_ctx, seed);
    if (!ret)
        return false;
    return true;
}
References dogecoin_random_bytes(), dogecoin_random_init(), secp256k1_context_create(), secp256k1_context_randomize(), SECP256K1_CONTEXT_SIGN, SECP256K1_CONTEXT_VERIFY, and secp256k1_ctx.
Referenced by main().
dogecoin_ecc_stop()
void dogecoin_ecc_stop (void)
destroys the static ecc context
Definition at line 31 of file ecc.c.
{
    secp256k1_context* ctx = secp256k1_ctx;
    secp256k1_ctx = NULL;
    if (ctx)
        secp256k1_context_destroy(ctx);
}
References ctx, secp256k1_context_destroy(), and secp256k1_ctx.
Referenced by main(), and showError().
dogecoin_ecc_verify_privatekey()
dogecoin_bool dogecoin_ecc_verify_privatekey (const uint8_t * private_key)
verifies a given 32byte key
Definition at line 72 of file ecc.c.
{
    assert(secp256k1_ctx);
    return secp256k1_ec_seckey_verify(secp256k1_ctx, (const unsigned char*)private_key);
}
References secp256k1_ctx, and secp256k1_ec_seckey_verify().
Referenced by dogecoin_hdnode_from_seed(), dogecoin_hdnode_private_ckd(), dogecoin_privkey_gen(), and dogecoin_privkey_is_valid().
dogecoin_ecc_verify_pubkey()
dogecoin_bool dogecoin_ecc_verify_pubkey (const uint8_t * public_key, dogecoin_bool compressed)
verifies a given public key (compressed[33] or uncompressed[65] bytes)
Definition at line 78 of file ecc.c.
{
    secp256k1_pubkey pubkey;
    assert(secp256k1_ctx);
    if (!secp256k1_ec_pubkey_parse(secp256k1_ctx, &pubkey, public_key, compressed ? 33 : 65)) {
        dogecoin_mem_zero(&pubkey, sizeof(pubkey));
        return false;
    }
    dogecoin_mem_zero(&pubkey, sizeof(pubkey));
    return true;
}
References dogecoin_mem_zero(), secp256k1_ctx, and secp256k1_ec_pubkey_parse().
Referenced by dogecoin_pubkey_is_valid().
dogecoin_ecc_verify_sig()
dogecoin_bool dogecoin_ecc_verify_sig (const uint8_t * public_key, dogecoin_bool compressed, const uint256 hash, unsigned char * sigder, size_t siglen)
verify DER signature with public key
Definition at line 165 of file ecc.c.
{
    assert(secp256k1_ctx);
    secp256k1_ecdsa_signature sig;
    secp256k1_pubkey pubkey;
    if (!secp256k1_ec_pubkey_parse(secp256k1_ctx, &pubkey, public_key, compressed ? 33 : 65))
        return false;
    if (!secp256k1_ecdsa_signature_parse_der(secp256k1_ctx, &sig, sigder, siglen))
        return false;
    return secp256k1_ecdsa_verify(secp256k1_ctx, &sig, hash, &pubkey);
}
References secp256k1_ctx, secp256k1_ec_pubkey_parse(), secp256k1_ecdsa_signature_parse_der(), and secp256k1_ecdsa_verify().
Referenced by dogecoin_pubkey_verify_sig().
dogecoin_ecc_verify_sigcmp()
dogecoin_bool dogecoin_ecc_verify_sigcmp (const uint8_t * public_key, dogecoin_bool compressed, const uint256 hash, unsigned char * sigcmp)
verify compact signature with public key
Definition at line 177 of file ecc.c.
{
    assert(secp256k1_ctx);
    secp256k1_ecdsa_signature sig;
    secp256k1_pubkey pubkey;
    if (!secp256k1_ec_pubkey_parse(secp256k1_ctx, &pubkey, public_key, compressed ? 33 : 65)) {
        return false;
    }
    if (!secp256k1_ecdsa_signature_parse_compact(secp256k1_ctx, &sig, &sigcmp[1])) {
        return false;
    }
    return secp256k1_ecdsa_verify(secp256k1_ctx, &sig, hash, &pubkey);
}
References secp256k1_ctx, secp256k1_ec_pubkey_parse(), secp256k1_ecdsa_signature_parse_compact(), and secp256k1_ecdsa_verify().
Referenced by dogecoin_pubkey_verify_sigcmp().
dogecoin_recover_pubkey()
dogecoin_bool dogecoin_recover_pubkey (const unsigned char * sigrec, const uint256 hash, const int recid, uint8_t * public_key, size_t * outlen)
recover a specific pubkey from a signature and recid
Definition at line 137 of file ecc.c.
{
    assert(secp256k1_ctx);
    secp256k1_pubkey pubkey;
    secp256k1_ecdsa_recoverable_signature sig;
    if (!secp256k1_ecdsa_recoverable_signature_parse_compact(secp256k1_ctx, &sig, &sigrec[1], recid))
        return false;
    if (!secp256k1_ecdsa_recover(secp256k1_ctx, &pubkey, &sig, hash))
        return 0;
    if (!secp256k1_ec_pubkey_serialize(secp256k1_ctx, public_key, outlen, &pubkey, SECP256K1_EC_COMPRESSED))
        return 0;
    return 1;
}
References secp256k1_ctx, SECP256K1_EC_COMPRESSED, secp256k1_ec_pubkey_serialize(), secp256k1_ecdsa_recover(), and secp256k1_ecdsa_recoverable_signature_parse_compact().
Referenced by dogecoin_key_recover_pubkey().
Variable Documentation
secp256k1_ctx
secp256k1_context* secp256k1_ctx = NULL static
Definition at line 12 of file ecc.c.
Referenced by dogecoin_ecc_compact_to_der_normalized(), dogecoin_ecc_der_to_compact(), dogecoin_ecc_get_pubkey(), dogecoin_ecc_private_key_tweak_add(), dogecoin_ecc_public_key_tweak_add(), dogecoin_ecc_recover_pubkey(), dogecoin_ecc_sign(), dogecoin_ecc_sign_compact(), dogecoin_ecc_sign_compact_recoverable(), dogecoin_ecc_sign_compact_recoverable_fcomp(), dogecoin_ecc_start(), dogecoin_ecc_stop(), dogecoin_ecc_verify_privatekey(), dogecoin_ecc_verify_pubkey(), dogecoin_ecc_verify_sig(), dogecoin_ecc_verify_sigcmp(), and dogecoin_recover_pubkey().