libdogecoin: src/secp256k1/src/eckey_impl.h File Reference
eckey_impl.h File Reference
#include "eckey.h"
#include "scalar.h"
#include "field.h"
#include "group.h"
#include "ecmult_gen.h"
Functions
static int secp256k1_eckey_pubkey_parse (secp256k1_ge *elem, const unsigned char *pub, size_t size)
static int secp256k1_eckey_pubkey_serialize (secp256k1_ge *elem, unsigned char *pub, size_t *size, int compressed)
static int secp256k1_eckey_privkey_tweak_add (secp256k1_scalar *key, const secp256k1_scalar *tweak)
static int secp256k1_eckey_pubkey_tweak_add (secp256k1_ge *key, const secp256k1_scalar *tweak)
static int secp256k1_eckey_privkey_tweak_mul (secp256k1_scalar *key, const secp256k1_scalar *tweak)
static int secp256k1_eckey_pubkey_tweak_mul (secp256k1_ge *key, const secp256k1_scalar *tweak)
Function Documentation
secp256k1_eckey_privkey_tweak_add()
static int secp256k1_eckey_privkey_tweak_add (secp256k1_scalar * key, const secp256k1_scalar * tweak) static
Definition at line 55 of file eckey_impl.h.
{
    secp256k1_scalar_add(key, key, tweak);
    return !secp256k1_scalar_is_zero(key);
}
References secp256k1_scalar_add(), and secp256k1_scalar_is_zero().
secp256k1_eckey_privkey_tweak_mul()
static int secp256k1_eckey_privkey_tweak_mul (secp256k1_scalar * key, const secp256k1_scalar * tweak) static
Definition at line 74 of file eckey_impl.h.
{
    int ret;
    ret = !secp256k1_scalar_is_zero(tweak);
    secp256k1_scalar_mul(key, key, tweak);
    return ret;
}
References secp256k1_scalar_is_zero(), and secp256k1_scalar_mul().
secp256k1_eckey_pubkey_parse()
static int secp256k1_eckey_pubkey_parse (secp256k1_ge * elem, const unsigned char * pub, size_t size) static
Definition at line 17 of file eckey_impl.h.
{
    if (size == 33 && (pub[0] == SECP256K1_TAG_PUBKEY_EVEN || pub[0] == SECP256K1_TAG_PUBKEY_ODD)) {
        secp256k1_fe x;
        return secp256k1_fe_set_b32(&x, pub+1) && secp256k1_ge_set_xo_var(elem, &x, pub[0] == SECP256K1_TAG_PUBKEY_ODD);
    } else if (size == 65 && (pub[0] == SECP256K1_TAG_PUBKEY_UNCOMPRESSED || pub[0] == SECP256K1_TAG_PUBKEY_HYBRID_EVEN || pub[0] == SECP256K1_TAG_PUBKEY_HYBRID_ODD)) {
        secp256k1_fe x, y;
        if (!secp256k1_fe_set_b32(&x, pub+1) || !secp256k1_fe_set_b32(&y, pub+33)) {
            return 0;
        }
        secp256k1_ge_set_xy(elem, &x, &y);
        if ((pub[0] == SECP256K1_TAG_PUBKEY_HYBRID_EVEN || pub[0] == SECP256K1_TAG_PUBKEY_HYBRID_ODD) &&
            secp256k1_fe_is_odd(&y) != (pub[0] == SECP256K1_TAG_PUBKEY_HYBRID_ODD)) {
            return 0;
        }
        return secp256k1_ge_is_valid_var(elem);
    } else {
        return 0;
    }
}
References secp256k1_fe_is_odd(), secp256k1_fe_set_b32(), secp256k1_ge_is_valid_var(), secp256k1_ge_set_xo_var(), secp256k1_ge_set_xy(), SECP256K1_TAG_PUBKEY_EVEN, SECP256K1_TAG_PUBKEY_HYBRID_EVEN, SECP256K1_TAG_PUBKEY_HYBRID_ODD, SECP256K1_TAG_PUBKEY_ODD, and SECP256K1_TAG_PUBKEY_UNCOMPRESSED.
secp256k1_eckey_pubkey_serialize()
static int secp256k1_eckey_pubkey_serialize (secp256k1_ge * elem, unsigned char * pub, size_t * size, int compressed) static
Definition at line 37 of file eckey_impl.h.
{
    if (secp256k1_ge_is_infinity(elem)) {
        return 0;
    }
    secp256k1_fe_normalize_var(&elem->x);
    secp256k1_fe_normalize_var(&elem->y);
    secp256k1_fe_get_b32(&pub[1], &elem->x);
    if (compressed) {
        *size = 33;
        pub[0] = secp256k1_fe_is_odd(&elem->y) ? SECP256K1_TAG_PUBKEY_ODD : SECP256K1_TAG_PUBKEY_EVEN;
    } else {
        *size = 65;
        pub[0] = SECP256K1_TAG_PUBKEY_UNCOMPRESSED;
        secp256k1_fe_get_b32(&pub[33], &elem->y);
    }
    return 1;
}
References secp256k1_fe_get_b32(), secp256k1_fe_is_odd(), secp256k1_fe_normalize_var(), secp256k1_ge_is_infinity(), SECP256K1_TAG_PUBKEY_EVEN, SECP256K1_TAG_PUBKEY_ODD, SECP256K1_TAG_PUBKEY_UNCOMPRESSED, secp256k1_ge::x, and secp256k1_ge::y.
secp256k1_eckey_pubkey_tweak_add()
static int secp256k1_eckey_pubkey_tweak_add (secp256k1_ge * key, const secp256k1_scalar * tweak) static
Definition at line 60 of file eckey_impl.h.
{
    secp256k1_gej pt;
    secp256k1_scalar one;
    secp256k1_gej_set_ge(&pt, key);
    secp256k1_scalar_set_int(&one, 1);
    secp256k1_ecmult(&pt, &pt, &one, tweak);
    if (secp256k1_gej_is_infinity(&pt)) {
        return 0;
    }
    secp256k1_ge_set_gej(key, &pt);
    return 1;
}
References secp256k1_ecmult(), secp256k1_ge_set_gej(), secp256k1_gej_is_infinity(), secp256k1_gej_set_ge(), and secp256k1_scalar_set_int().
secp256k1_eckey_pubkey_tweak_mul()
static int secp256k1_eckey_pubkey_tweak_mul (secp256k1_ge * key, const secp256k1_scalar * tweak) static
Definition at line 82 of file eckey_impl.h.
{
    secp256k1_scalar zero;
    secp256k1_gej pt;
    if (secp256k1_scalar_is_zero(tweak)) {
        return 0;
    }
    secp256k1_scalar_set_int(&zero, 0);
    secp256k1_gej_set_ge(&pt, key);
    secp256k1_ecmult(&pt, &pt, tweak, &zero);
    secp256k1_ge_set_gej(key, &pt);
    return 1;
}
References secp256k1_ecmult(), secp256k1_ge_set_gej(), secp256k1_gej_set_ge(), secp256k1_scalar_is_zero(), and secp256k1_scalar_set_int().