libdogecoin: include/dogecoin/eckey.h File Reference
eckey.h File Reference
#include <dogecoin/dogecoin.h>
#include <dogecoin/key.h>
#include <dogecoin/uthash.h>
Data Structures
struct eckey
Typedefs
typedef LIBDOGECOIN_BEGIN_DECL struct eckey eckey
Functions
LIBDOGECOIN_API eckey * new_eckey (dogecoin_bool is_testnet)
This function instantiates a new working eckey, but does not add it to the hash table.
LIBDOGECOIN_API eckey * new_eckey_from_privkey (char *key)
This function instantiates a new working eckey, but does not add it to the hash table.
LIBDOGECOIN_API void add_eckey (eckey *key)
This function takes a pointer to an existing working eckey object and adds it to the hash table.
LIBDOGECOIN_API eckey * find_eckey (int idx)
This function takes an index and returns the working eckey associated with that index in the hash table.
LIBDOGECOIN_API void remove_eckey (eckey *key)
This function removes the specified working eckey from the hash table and frees the keys in memory.
LIBDOGECOIN_API void dogecoin_key_free (eckey *eckey)
This function frees the memory allocated for an eckey.
LIBDOGECOIN_API int start_key (dogecoin_bool is_testnet)
This function creates a new key, places it in the hash table, and returns the index of the new key, starting from 1 and incrementing each subsequent call.
Variables
static eckey * keys = NULL
Typedef Documentation
eckey
typedef LIBDOGECOIN_BEGIN_DECL struct eckey eckey
Function Documentation
add_eckey()
LIBDOGECOIN_API void add_eckey (eckey * key)
This function takes a pointer to an existing working eckey object and adds it to the hash table.
Parameters
key The pointer to the working eckey.
Returns
Nothing.
Definition at line 97 of file eckey.c.
{
    eckey* key_old;
    HASH_FIND_INT(keys, &key->idx, key_old);
    if (key_old == NULL) {
        HASH_ADD_INT(keys, idx, key);
    } else {
        HASH_REPLACE_INT(keys, idx, key, key_old);
    }
    dogecoin_free(key_old);
}
dogecoin_key_free()
LIBDOGECOIN_API void dogecoin_key_free (eckey * eckey)
This function frees the memory allocated for an eckey.
Parameters
eckey The pointer to the eckey to be freed.
Returns
Nothing.
Definition at line 146 of file eckey.c.
{
    dogecoin_free(eckey);
}
References dogecoin_free().
Referenced by remove_eckey().
find_eckey()
LIBDOGECOIN_API eckey * find_eckey (int idx)
This function takes an index and returns the working eckey associated with that index in the hash table.
Parameters
idx The index of the target working eckey.
Returns
The pointer to the working eckey associated with the provided index.
Definition at line 117 of file eckey.c.
{
    eckey* key;
    HASH_FIND_INT(keys, &idx, key);
    return key;
}
new_eckey()
LIBDOGECOIN_API eckey * new_eckey (dogecoin_bool is_testnet)
This function instantiates a new working eckey, but does not add it to the hash table.
Returns
A pointer to the new working eckey.
Definition at line 42 of file eckey.c.
{
    eckey* key = (struct eckey*)dogecoin_calloc(1, sizeof *key);
    dogecoin_privkey_init(&key->private_key);
    assert(dogecoin_privkey_is_valid(&key->private_key) == 0);
    dogecoin_privkey_gen(&key->private_key);
    assert(dogecoin_privkey_is_valid(&key->private_key)==1);
    dogecoin_pubkey_init(&key->public_key);
    dogecoin_pubkey_from_key(&key->private_key, &key->public_key);
    assert(dogecoin_pubkey_is_valid(&key->public_key) == 1);
    strcpy(key->public_key_hex, utils_uint8_to_hex((const uint8_t *)&key->public_key, 33));
    uint8_t pkeybase58c[34];
    const dogecoin_chainparams* chain = is_testnet ? &dogecoin_chainparams_test : &dogecoin_chainparams_main;
    pkeybase58c[0] = chain->b58prefix_secret_address;
    pkeybase58c[33] = 1; /* always use compressed keys */
    memcpy_safe(&pkeybase58c[1], &key->private_key, DOGECOIN_ECKEY_PKEY_LENGTH);
    assert(dogecoin_base58_encode_check(pkeybase58c, sizeof(pkeybase58c), key->private_key_wif, sizeof(key->private_key_wif)) != 0);
    if (!dogecoin_pubkey_getaddr_p2pkh(&key->public_key, chain, (char*)&key->address)) return false;
    key->idx = HASH_COUNT(keys) + 1;
    return key;
}
References eckey::address, dogecoin_chainparams_::b58prefix_secret_address, dogecoin_base58_encode_check(), dogecoin_calloc(), dogecoin_chainparams_main, dogecoin_chainparams_test, DOGECOIN_ECKEY_PKEY_LENGTH, dogecoin_privkey_gen(), dogecoin_privkey_init(), dogecoin_privkey_is_valid(), dogecoin_pubkey_from_key(), dogecoin_pubkey_getaddr_p2pkh(), dogecoin_pubkey_init(), dogecoin_pubkey_is_valid(), HASH_COUNT, eckey::idx, is_testnet, keys, memcpy_safe(), eckey::private_key, eckey::private_key_wif, eckey::public_key, eckey::public_key_hex, and utils_uint8_to_hex().
Referenced by start_key().
new_eckey_from_privkey()
LIBDOGECOIN_API eckey * new_eckey_from_privkey (char * private_key)
This function instantiates a new working eckey, but does not add it to the hash table.
Returns
A pointer to the new working eckey.
Definition at line 69 of file eckey.c.
{
    eckey* key = (struct eckey*)dogecoin_calloc(1, sizeof *key);
    dogecoin_privkey_init(&key->private_key);
    const dogecoin_chainparams* chain = chain_from_b58_prefix(private_key);
    if (!dogecoin_privkey_decode_wif(private_key, chain, &key->private_key)) return false;
    assert(dogecoin_privkey_is_valid(&key->private_key)==1);
    dogecoin_pubkey_init(&key->public_key);
    dogecoin_pubkey_from_key(&key->private_key, &key->public_key);
    assert(dogecoin_pubkey_is_valid(&key->public_key) == 1);
    strcpy(key->public_key_hex, utils_uint8_to_hex((const uint8_t *)&key->public_key, 33));
    uint8_t pkeybase58c[34];
    pkeybase58c[0] = chain->b58prefix_secret_address;
    pkeybase58c[33] = 1; /* always use compressed keys */
    memcpy_safe(&pkeybase58c[1], &key->private_key, DOGECOIN_ECKEY_PKEY_LENGTH);
    assert(dogecoin_base58_encode_check(pkeybase58c, sizeof(pkeybase58c), key->private_key_wif, sizeof(key->private_key_wif)) != 0);
    if (!dogecoin_pubkey_getaddr_p2pkh(&key->public_key, chain, (char*)&key->address)) return false;
    key->idx = HASH_COUNT(keys) + 1;
    return key;
}
References eckey::address, dogecoin_chainparams_::b58prefix_secret_address, chain_from_b58_prefix(), dogecoin_base58_encode_check(), dogecoin_calloc(), DOGECOIN_ECKEY_PKEY_LENGTH, dogecoin_privkey_decode_wif(), dogecoin_privkey_init(), dogecoin_privkey_is_valid(), dogecoin_pubkey_from_key(), dogecoin_pubkey_getaddr_p2pkh(), dogecoin_pubkey_init(), dogecoin_pubkey_is_valid(), HASH_COUNT, eckey::idx, keys, memcpy_safe(), eckey::private_key, eckey::private_key_wif, eckey::public_key, eckey::public_key_hex, and utils_uint8_to_hex().
Referenced by main().
remove_eckey()
LIBDOGECOIN_API void remove_eckey (eckey * key)
This function removes the specified working eckey from the hash table and frees the keys in memory.
Parameters
key The pointer to the eckey to remove.
Returns
Nothing.
Definition at line 131 of file eckey.c.
{
    HASH_DEL(keys, key); /* delete it (keys advances to next) */
    dogecoin_privkey_cleanse(&key->private_key);
    dogecoin_pubkey_cleanse(&key->public_key);
    dogecoin_key_free(key);
}
start_key()
LIBDOGECOIN_API int start_key (dogecoin_bool is_testnet)
This function creates a new key, places it in the hash table, and returns the index of the new key, starting from 1 and incrementing each subsequent call.
Parameters
is_testnet
Returns
The index of the new key.
Definition at line 160 of file eckey.c.
{
    eckey* key = new_eckey(is_testnet);
    int index = key->idx;
    add_eckey(key);
    return index;
}
References add_eckey(), eckey::idx, is_testnet, and new_eckey().
Variable Documentation
keys
eckey* keys = NULL static
Definition at line 50 of file eckey.h.
Referenced by add_eckey(), find_eckey(), new_eckey(), new_eckey_from_privkey(), and remove_eckey().