libdogecoin: src/secp256k1/src/ecmult_gen.h File Reference
ecmult_gen.h File Reference
#include "scalar.h"
#include "group.h"
Data Structures
struct secp256k1_ecmult_gen_context
Macros
#define ECMULT_GEN_PREC_G(bits) (1 << bits)
#define ECMULT_GEN_PREC_N(bits) (256 / bits)
Functions
static void secp256k1_ecmult_gen_context_build (secp256k1_ecmult_gen_context *ctx)
static void secp256k1_ecmult_gen_context_clear (secp256k1_ecmult_gen_context *ctx)
static void secp256k1_ecmult_gen (const secp256k1_ecmult_gen_context *ctx, secp256k1_gej *r, const secp256k1_scalar *a)
static void secp256k1_ecmult_gen_blind (secp256k1_ecmult_gen_context *ctx, const unsigned char *seed32)
Macro Definition Documentation
ECMULT_GEN_PREC_G
#define ECMULT_GEN_PREC_G (bits) (1 << bits)
Definition at line 16 of file ecmult_gen.h.
ECMULT_GEN_PREC_N
#define ECMULT_GEN_PREC_N (bits) (256 / bits)
Definition at line 17 of file ecmult_gen.h.
Function Documentation
secp256k1_ecmult_gen()
static void secp256k1_ecmult_gen (const secp256k1_ecmult_gen_context * ctx, secp256k1_gej * r, const secp256k1_scalar * a) static
Multiply with the generator: R = a*G
Referenced by bench_ecmult_gen(), bench_ecmult_teardown_helper(), main(), run_context_tests(), secp256k1_ec_pubkey_create_helper(), secp256k1_ecdsa_sig_sign(), test_ec_combine(), test_ecdsa_edge_cases(), test_ecdsa_sign_verify(), test_ecmult_accumulate(), test_ecmult_gen_blind(), test_ecmult_multi_random(), and test_ecmult_target().
secp256k1_ecmult_gen_blind()
static void secp256k1_ecmult_gen_blind (secp256k1_ecmult_gen_context * ctx, const unsigned char * seed32) static
Referenced by secp256k1_context_randomize(), test_ecmult_gen_blind(), and test_ecmult_gen_blind_reset().
secp256k1_ecmult_gen_context_build()
static void secp256k1_ecmult_gen_context_build (secp256k1_ecmult_gen_context * ctx) static
Referenced by secp256k1_context_preallocated_create().
secp256k1_ecmult_gen_context_clear()
static void secp256k1_ecmult_gen_context_clear (secp256k1_ecmult_gen_context * ctx) static
Referenced by secp256k1_context_preallocated_destroy().