libdogecoin: src/secp256k1/src/ecmult_compute_table_impl.h File Reference
ecmult_compute_table_impl.h File Reference
#include "ecmult_compute_table.h"
#include "group_impl.h"
#include "field_impl.h"
#include "ecmult.h"
#include "util.h"
Functions
static void secp256k1_ecmult_compute_table (secp256k1_ge_storage *table, int window_g, const secp256k1_gej *gen)
static void secp256k1_ecmult_compute_two_tables (secp256k1_ge_storage *table, secp256k1_ge_storage *table_128, int window_g, const secp256k1_ge *gen)
Function Documentation
secp256k1_ecmult_compute_table()
static void secp256k1_ecmult_compute_table (secp256k1_ge_storage * table, int window_g, const secp256k1_gej * gen) static
Definition at line 16 of file ecmult_compute_table_impl.h.
{
    secp256k1_gej gj;
    secp256k1_ge ge, dgen;
    int j;
    gj = *gen;
    secp256k1_ge_set_gej_var(&ge, &gj);
    secp256k1_ge_to_storage(&table[0], &ge);
    secp256k1_gej_double_var(&gj, gen, NULL);
    secp256k1_ge_set_gej_var(&dgen, &gj);
    for (j = 1; j < ECMULT_TABLE_SIZE(window_g); ++j) {
        secp256k1_gej_set_ge(&gj, &ge);
        secp256k1_gej_add_ge_var(&gj, &gj, &dgen, NULL);
        secp256k1_ge_set_gej_var(&ge, &gj);
        secp256k1_ge_to_storage(&table[j], &ge);
    }
}
References ECMULT_TABLE_SIZE, secp256k1_ge_set_gej_var(), secp256k1_ge_to_storage(), secp256k1_gej_add_ge_var(), secp256k1_gej_double_var(), and secp256k1_gej_set_ge().
Referenced by secp256k1_ecmult_compute_two_tables().
secp256k1_ecmult_compute_two_tables()
static void secp256k1_ecmult_compute_two_tables (secp256k1_ge_storage * table, secp256k1_ge_storage * table_128, int window_g, const secp256k1_ge * gen) static
Definition at line 37 of file ecmult_compute_table_impl.h.
{
    secp256k1_gej gj;
    int i;
    secp256k1_gej_set_ge(&gj, gen);
    secp256k1_ecmult_compute_table(table, window_g, &gj);
    for (i = 0; i < 128; ++i) {
        secp256k1_gej_double_var(&gj, &gj, NULL);
    }
    secp256k1_ecmult_compute_table(table_128, window_g, &gj);
}
References secp256k1_ecmult_compute_table(), secp256k1_gej_double_var(), and secp256k1_gej_set_ge().