libdogecoin: src/secp256k1/src/ecmult_gen_impl.h File Reference
ecmult_gen_impl.h File Reference
#include "util.h"
#include "scalar.h"
#include "group.h"
#include "ecmult_gen.h"
#include "hash_impl.h"
#include "precomputed_ecmult_gen.h"
Functions
static void secp256k1_ecmult_gen_context_build (secp256k1_ecmult_gen_context *ctx)
static int secp256k1_ecmult_gen_context_is_built (const secp256k1_ecmult_gen_context *ctx)
static void secp256k1_ecmult_gen_context_clear (secp256k1_ecmult_gen_context *ctx)
static void secp256k1_ecmult_gen (const secp256k1_ecmult_gen_context *ctx, secp256k1_gej *r, const secp256k1_scalar *gn)
static void secp256k1_ecmult_gen_blind (secp256k1_ecmult_gen_context *ctx, const unsigned char *seed32)
Function Documentation
secp256k1_ecmult_gen()
static void secp256k1_ecmult_gen (const secp256k1_ecmult_gen_context * ctx, secp256k1_gej * r, const secp256k1_scalar * gn) static
This uses a conditional move to avoid any secret data in array indexes. Any use of secret indexes has been demonstrated to result in timing sidechannels, even when the cache-line access patterns are uniform. See also: "A word of warning", CHES 2013 Rump Session, by Daniel J. Bernstein and Peter Schwabe (https://cryptojedi.org/peter/data/chesrump-20130822.pdf) and "Cache Attacks and Countermeasures: the Case of AES", RSA 2006, by Dag Arne Osvik, Adi Shamir, and Eran Tromer (https://www.tau.ac.il/~tromer/papers/cache.pdf)
Definition at line 45 of file ecmult_gen_impl.h.
{
    int bits = ECMULT_GEN_PREC_BITS;
    int g = ECMULT_GEN_PREC_G(bits);
    int n = ECMULT_GEN_PREC_N(bits);
    secp256k1_ge add;
    secp256k1_ge_storage adds;
    secp256k1_scalar gnb;
    int i, j, n_i;
    memset(&adds, 0, sizeof(adds));
    *r = ctx->initial;
    /* Blind scalar/point multiplication by computing (n-b)G + bG instead of nG. */
    secp256k1_scalar_add(&gnb, gn, &ctx->blind);
    add.infinity = 0;
    for (i = 0; i < n; i++) {
        n_i = secp256k1_scalar_get_bits(&gnb, i * bits, bits);
        for (j = 0; j < g; j++) {
            secp256k1_ge_storage_cmov(&adds, &secp256k1_ecmult_gen_prec_table[i][j], j == n_i);
        }
        secp256k1_ge_from_storage(&add, &adds);
        secp256k1_gej_add_ge(r, r, &add);
    }
    n_i = 0;
    secp256k1_ge_clear(&add);
    secp256k1_scalar_clear(&gnb);
}
References ctx, ECMULT_GEN_PREC_BITS, ECMULT_GEN_PREC_G, ECMULT_GEN_PREC_N, secp256k1_ge::infinity, secp256k1_ecmult_gen_prec_table, secp256k1_ge_clear(), secp256k1_ge_from_storage(), secp256k1_ge_storage_cmov(), secp256k1_gej_add_ge(), secp256k1_scalar_add(), secp256k1_scalar_clear(), and secp256k1_scalar_get_bits().
Referenced by secp256k1_ecmult_gen_blind().
secp256k1_ecmult_gen_blind()
static void secp256k1_ecmult_gen_blind (secp256k1_ecmult_gen_context * ctx, const unsigned char * seed32) static
Using a CSPRNG allows a failure free interface, avoids needing large amounts of random data, and guards against weak or adversarial seeds. This is a simpler and safer interface than asking the caller for blinding values directly and expecting them to retry on failure.
Definition at line 84 of file ecmult_gen_impl.h.
{
    secp256k1_scalar b;
    secp256k1_gej gb;
    secp256k1_fe s;
    unsigned char nonce32[32];
    secp256k1_rfc6979_hmac_sha256 rng;
    int overflow;
    unsigned char keydata[64] = {0};
    if (seed32 == NULL) {
        /* When seed is NULL, reset the initial point and blinding value. */
        secp256k1_gej_set_ge(&ctx->initial, &secp256k1_ge_const_g);
        secp256k1_gej_neg(&ctx->initial, &ctx->initial);
        secp256k1_scalar_set_int(&ctx->blind, 1);
    }
    /* The prior blinding value (if not reset) is chained forward by including it in the hash. */
    secp256k1_scalar_get_b32(nonce32, &ctx->blind);
    memcpy(keydata, nonce32, 32);
    if (seed32 != NULL) {
        memcpy(keydata + 32, seed32, 32);
    }
    secp256k1_rfc6979_hmac_sha256_initialize(&rng, keydata, seed32 ? 64 : 32);
    memset(keydata, 0, sizeof(keydata));
    /* Accept unobservably small non-uniformity. */
    secp256k1_rfc6979_hmac_sha256_generate(&rng, nonce32, 32);
    overflow = !secp256k1_fe_set_b32(&s, nonce32);
    overflow |= secp256k1_fe_is_zero(&s);
    secp256k1_fe_cmov(&s, &secp256k1_fe_one, overflow);
    /* Randomize the projection to defend against multiplier sidechannels. */
    secp256k1_gej_rescale(&ctx->initial, &s);
    secp256k1_fe_clear(&s);
    secp256k1_rfc6979_hmac_sha256_generate(&rng, nonce32, 32);
    secp256k1_scalar_set_b32(&b, nonce32, NULL);
    /* A blinding value of 0 works, but would undermine the projection hardening. */
    secp256k1_scalar_cmov(&b, &secp256k1_scalar_one, secp256k1_scalar_is_zero(&b));
    secp256k1_rfc6979_hmac_sha256_finalize(&rng);
    memset(nonce32, 0, 32);
    secp256k1_ecmult_gen(ctx, &gb, &b);
    secp256k1_scalar_negate(&b, &b);
    ctx->blind = b;
    ctx->initial = gb;
    secp256k1_scalar_clear(&b);
    secp256k1_gej_clear(&gb);
}
References ctx, secp256k1_ecmult_gen(), secp256k1_fe_clear(), secp256k1_fe_cmov(), secp256k1_fe_is_zero(), secp256k1_fe_one, secp256k1_fe_set_b32(), secp256k1_ge_const_g, secp256k1_gej_clear(), secp256k1_gej_neg(), secp256k1_gej_rescale(), secp256k1_gej_set_ge(), secp256k1_rfc6979_hmac_sha256_finalize(), secp256k1_rfc6979_hmac_sha256_generate(), secp256k1_rfc6979_hmac_sha256_initialize(), secp256k1_scalar_clear(), secp256k1_scalar_cmov(), secp256k1_scalar_get_b32(), secp256k1_scalar_is_zero(), secp256k1_scalar_negate(), secp256k1_scalar_one, secp256k1_scalar_set_b32(), and secp256k1_scalar_set_int().
Referenced by secp256k1_ecmult_gen_context_build().
secp256k1_ecmult_gen_context_build()
static void secp256k1_ecmult_gen_context_build (secp256k1_ecmult_gen_context * ctx) static
Definition at line 17 of file ecmult_gen_impl.h.
{
    secp256k1_ecmult_gen_blind(ctx, NULL);
    ctx->built = 1;
}
References ctx, and secp256k1_ecmult_gen_blind().
secp256k1_ecmult_gen_context_clear()
static void secp256k1_ecmult_gen_context_clear (secp256k1_ecmult_gen_context * ctx) static
Definition at line 26 of file ecmult_gen_impl.h.
{
    ctx->built = 0;
    secp256k1_scalar_clear(&ctx->blind);
    secp256k1_gej_clear(&ctx->initial);
}
References ctx, secp256k1_gej_clear(), and secp256k1_scalar_clear().
secp256k1_ecmult_gen_context_is_built()
static int secp256k1_ecmult_gen_context_is_built (const secp256k1_ecmult_gen_context * ctx) static
Definition at line 22 of file ecmult_gen_impl.h.
{
    return ctx->built;
}
References ctx.
Referenced by secp256k1_context_randomize(), secp256k1_ec_pubkey_create(), and secp256k1_ecdsa_sign().