libdogecoin: src/libevent/evbuffer-internal.h File Reference
evbuffer-internal.h File Reference
#include "event2/event-config.h"
#include "evconfig-private.h"
#include "event2/util.h"
#include "event2/event_struct.h"
#include "util-internal.h"
#include "defer-internal.h"
#include <sys/queue.h>
Data Structures
struct evbuffer_cb_entry
struct evbuffer
struct evbuffer_chain
struct evbuffer_chain_reference
struct evbuffer_chain_file_segment
struct evbuffer_file_segment
struct evbuffer_multicast_parent
Macros
#define EVBUFFER_CB_NODEFER 2
#define MIN_BUFFER_SIZE 512
#define EVBUFFER_CHAIN_MAX ((size_t)EV_SSIZE_MAX)
#define EVBUFFER_FILESEGMENT 0x0001
#define EVBUFFER_SENDFILE 0x0002
#define EVBUFFER_REFERENCE 0x0004
#define EVBUFFER_IMMUTABLE 0x0008
#define EVBUFFER_MEM_PINNED_R 0x0010
#define EVBUFFER_MEM_PINNED_W 0x0020
#define EVBUFFER_MEM_PINNED_ANY (EVBUFFER_MEM_PINNED_R|EVBUFFER_MEM_PINNED_W)
#define EVBUFFER_DANGLING 0x0040
#define EVBUFFER_MULTICAST 0x0080
#define EVBUFFER_CHAIN_SIZE sizeof(struct evbuffer_chain)
#define EVBUFFER_CHAIN_EXTRA(t, c) (t *)((struct evbuffer_chain *)(c) + 1)
#define ASSERT_EVBUFFER_LOCKED(buffer) EVLOCK_ASSERT_LOCKED((buffer)->lock)
#define EVBUFFER_LOCK(buffer)
#define EVBUFFER_UNLOCK(buffer)
#define EVBUFFER_LOCK2(buffer1, buffer2)
#define EVBUFFER_UNLOCK2(buffer1, buffer2)
#define WSABUF_FROM_EVBUFFER_IOV(i, ei)
Typedefs
typedef ev_off_t ev_misalign_t
Functions
void evbuffer_incref_ (struct evbuffer *buf)
void evbuffer_incref_and_lock_ (struct evbuffer *buf)
void evbuffer_chain_pin_ (struct evbuffer_chain *chain, unsigned flag)
void evbuffer_chain_unpin_ (struct evbuffer_chain *chain, unsigned flag)
void evbuffer_decref_and_unlock_ (struct evbuffer *buffer)
int evbuffer_expand_fast_ (struct evbuffer *, size_t, int)
int evbuffer_read_setup_vecs_ (struct evbuffer *buf, ev_ssize_t howmuch, struct evbuffer_iovec *vecs, int n_vecs, struct evbuffer_chain ***chainp, int exact)
void evbuffer_set_parent_ (struct evbuffer *buf, struct bufferevent *bev)
void evbuffer_invoke_callbacks_ (struct evbuffer *buf)
int evbuffer_get_callbacks_ (struct evbuffer *buffer, struct event_callback **cbs, int max_cbs)
Macro Definition Documentation
ASSERT_EVBUFFER_LOCKED
#define ASSERT_EVBUFFER_LOCKED (buffer) EVLOCK_ASSERT_LOCKED((buffer)->lock)
Assert that we are holding the lock on an evbuffer
Definition at line 282 of file evbuffer-internal.h.
EVBUFFER_CB_NODEFER
#define EVBUFFER_CB_NODEFER 2
Definition at line 44 of file evbuffer-internal.h.
EVBUFFER_CHAIN_EXTRA
#define EVBUFFER_CHAIN_EXTRA (t, c) (t *)((struct evbuffer_chain *)(c) + 1)
Return a pointer to extra data allocated along with an evbuffer.
Definition at line 279 of file evbuffer-internal.h.
EVBUFFER_CHAIN_MAX
#define EVBUFFER_CHAIN_MAX ((size_t)EV_SSIZE_MAX)
Definition at line 166 of file evbuffer-internal.h.
EVBUFFER_CHAIN_SIZE
#define EVBUFFER_CHAIN_SIZE sizeof(struct evbuffer_chain)
Definition at line 277 of file evbuffer-internal.h.
EVBUFFER_DANGLING
#define EVBUFFER_DANGLING 0x0040
a chain that should be freed, but can't be freed until it is un-pinned.
Definition at line 200 of file evbuffer-internal.h.
EVBUFFER_FILESEGMENT
#define EVBUFFER_FILESEGMENT 0x0001
A chain used for a file segment
Definition at line 189 of file evbuffer-internal.h.
EVBUFFER_IMMUTABLE
#define EVBUFFER_IMMUTABLE 0x0008
read-only chain
Definition at line 192 of file evbuffer-internal.h.
EVBUFFER_LOCK
#define EVBUFFER_LOCK (buffer)
Value:
    do {                                \
        EVLOCK_LOCK((buffer)->lock, 0);             \
    } while (0)
Definition at line 285 of file evbuffer-internal.h.
EVBUFFER_LOCK2
#define EVBUFFER_LOCK2 (buffer1, buffer2)
Value:
    do {                                \
        EVLOCK_LOCK2((buffer1)->lock, (buffer2)->lock, 0, 0);   \
    } while (0)
Definition at line 293 of file evbuffer-internal.h.
EVBUFFER_MEM_PINNED_ANY
#define EVBUFFER_MEM_PINNED_ANY (EVBUFFER_MEM_PINNED_R|EVBUFFER_MEM_PINNED_W)
Definition at line 197 of file evbuffer-internal.h.
EVBUFFER_MEM_PINNED_R
#define EVBUFFER_MEM_PINNED_R 0x0010
a chain that mustn't be reallocated or freed, or have its contents memmoved, until the chain is un-pinned.
Definition at line 195 of file evbuffer-internal.h.
EVBUFFER_MEM_PINNED_W
#define EVBUFFER_MEM_PINNED_W 0x0020
Definition at line 196 of file evbuffer-internal.h.
EVBUFFER_MULTICAST
#define EVBUFFER_MULTICAST 0x0080
a chain that is a referenced copy of another chain
Definition at line 202 of file evbuffer-internal.h.
EVBUFFER_REFERENCE
#define EVBUFFER_REFERENCE 0x0004
a chain with a mem reference
Definition at line 191 of file evbuffer-internal.h.
EVBUFFER_SENDFILE
#define EVBUFFER_SENDFILE 0x0002
a chain used with sendfile
Definition at line 190 of file evbuffer-internal.h.
EVBUFFER_UNLOCK
#define EVBUFFER_UNLOCK (buffer)
Value:
    do {                                \
        EVLOCK_UNLOCK((buffer)->lock, 0);           \
    } while (0)
Definition at line 289 of file evbuffer-internal.h.
EVBUFFER_UNLOCK2
#define EVBUFFER_UNLOCK2 (buffer1, buffer2)
Value:
    do {                                \
        EVLOCK_UNLOCK2((buffer1)->lock, (buffer2)->lock, 0, 0); \
    } while (0)
Definition at line 297 of file evbuffer-internal.h.
MIN_BUFFER_SIZE
#define MIN_BUFFER_SIZE 512
Definition at line 55 of file evbuffer-internal.h.
WSABUF_FROM_EVBUFFER_IOV
#define WSABUF_FROM_EVBUFFER_IOV (i, ei)
Value:
        do {        \
        (i)->buf = (ei)->iov_base;      \
        (i)->len = (unsigned long)(ei)->iov_len;    \
    } while (0)
Definition at line 330 of file evbuffer-internal.h.
Typedef Documentation
ev_misalign_t
typedef ev_off_t ev_misalign_t
Definition at line 162 of file evbuffer-internal.h.
Function Documentation
evbuffer_chain_pin_()
void evbuffer_chain_pin_ (struct evbuffer_chain * chain, unsigned flag)
Pin a single buffer chain using a given flag. A pinned chunk may not be moved or freed until it is unpinned.
Definition at line 340 of file buffer.c.
{
    EVUTIL_ASSERT((chain->flags & flag) == 0);
    chain->flags |= flag;
}
References EVUTIL_ASSERT, and evbuffer_chain::flags.
Referenced by evbuffer_launch_read_(), and evbuffer_launch_write_().
evbuffer_chain_unpin_()
void evbuffer_chain_unpin_ (struct evbuffer_chain * chain, unsigned flag)
Unpin a single buffer chain using a given flag.
Definition at line 347 of file buffer.c.
{
    EVUTIL_ASSERT((chain->flags & flag) != 0);
    chain->flags &= ~flag;
    if (chain->flags & EVBUFFER_DANGLING)
        evbuffer_chain_free(chain);
}
References evbuffer_chain_free(), EVBUFFER_DANGLING, EVUTIL_ASSERT, and evbuffer_chain::flags.
Referenced by pin_release().
evbuffer_decref_and_unlock_()
void evbuffer_decref_and_unlock_ (struct evbuffer * buffer)
As evbuffer_free, but requires that we hold a lock on the buffer, and releases the lock before freeing it and the buffer.
Definition at line 561 of file buffer.c.
{
    struct evbuffer_chain *chain, *next;
    ASSERT_EVBUFFER_LOCKED(buffer);
    EVUTIL_ASSERT(buffer->refcnt > 0);
    if (--buffer->refcnt > 0) {
        EVBUFFER_UNLOCK(buffer);
        return;
    }
    for (chain = buffer->first; chain != NULL; chain = next) {
        next = chain->next;
        evbuffer_chain_free(chain);
    }
    evbuffer_remove_all_callbacks(buffer);
    if (buffer->deferred_cbs)
        event_deferred_cb_cancel_(buffer->cb_queue, &buffer->deferred);
    EVBUFFER_UNLOCK(buffer);
    if (buffer->own_lock)
        EVTHREAD_FREE_LOCK(buffer->lock, EVTHREAD_LOCKTYPE_RECURSIVE);
    mm_free(buffer);
}
References ASSERT_EVBUFFER_LOCKED, evbuffer_chain_free(), evbuffer_remove_all_callbacks(), EVBUFFER_UNLOCK, event_deferred_cb_cancel_(), EVTHREAD_FREE_LOCK, EVUTIL_ASSERT, mm_free, and evbuffer_chain::next.
Referenced by evbuffer_chain_free(), evbuffer_commit_read_(), evbuffer_commit_write_(), evbuffer_deferred_callback(), and evbuffer_free().
evbuffer_expand_fast_()
int evbuffer_expand_fast_ (struct evbuffer * buf, size_t datlen, int n)
As evbuffer_expand, but does not guarantee that the newly allocated memory is contiguous. Instead, it may be split across two or more chunks.
Definition at line 2051 of file buffer.c.
{
    struct evbuffer_chain *chain = buf->last, *tmp, *next;
    size_t avail;
    int used;
    ASSERT_EVBUFFER_LOCKED(buf);
    EVUTIL_ASSERT(n >= 2);
    if (chain == NULL || (chain->flags & EVBUFFER_IMMUTABLE)) {
        /* There is no last chunk, or we can't touch the last chunk.
         * Just add a new chunk. */
        chain = evbuffer_chain_new(datlen);
        if (chain == NULL)
            return (-1);
        evbuffer_chain_insert(buf, chain);
        return (0);
    }
    used = 0; /* number of chains we're using space in. */
    avail = 0; /* how much space they have. */
    /* How many bytes can we stick at the end of buffer as it is?  Iterate
     * over the chains at the end of the buffer, tring to see how much
     * space we have in the first n. */
    for (chain = *buf->last_with_datap; chain; chain = chain->next) {
        if (chain->off) {
            size_t space = (size_t) CHAIN_SPACE_LEN(chain);
            EVUTIL_ASSERT(chain == *buf->last_with_datap);
            if (space) {
                avail += space;
                ++used;
            }
        } else {
            /* No data in chain; realign it. */
            chain->misalign = 0;
            avail += chain->buffer_len;
            ++used;
        }
        if (avail >= datlen) {
            /* There is already enough space.  Just return */
            return (0);
        }
        if (used == n)
            break;
    }
    /* There wasn't enough space in the first n chains with space in
     * them. Either add a new chain with enough space, or replace all
     * empty chains with one that has enough space, depending on n. */
    if (used < n) {
        /* The loop ran off the end of the chains before it hit n
         * chains; we can add another. */
        EVUTIL_ASSERT(chain == NULL);
        tmp = evbuffer_chain_new(datlen - avail);
        if (tmp == NULL)
            return (-1);
        buf->last->next = tmp;
        buf->last = tmp;
        /* (we would only set last_with_data if we added the first
         * chain. But if the buffer had no chains, we would have
         * just allocated a new chain earlier) */
        return (0);
    } else {
        /* Nuke _all_ the empty chains. */
        int rmv_all = 0; /* True iff we removed last_with_data. */
        chain = *buf->last_with_datap;
        if (!chain->off) {
            EVUTIL_ASSERT(chain == buf->first);
            rmv_all = 1;
            avail = 0;
        } else {
            /* can't overflow, since only mutable chains have
             * huge misaligns. */
            avail = (size_t) CHAIN_SPACE_LEN(chain);
            chain = chain->next;
        }
        for (; chain; chain = next) {
            next = chain->next;
            EVUTIL_ASSERT(chain->off == 0);
            evbuffer_chain_free(chain);
        }
        EVUTIL_ASSERT(datlen >= avail);
        tmp = evbuffer_chain_new(datlen - avail);
        if (tmp == NULL) {
            if (rmv_all) {
                ZERO_CHAIN(buf);
            } else {
                buf->last = *buf->last_with_datap;
                (*buf->last_with_datap)->next = NULL;
            }
            return (-1);
        }
        if (rmv_all) {
            buf->first = buf->last = tmp;
            buf->last_with_datap = &buf->first;
        } else {
            (*buf->last_with_datap)->next = tmp;
            buf->last = tmp;
        }
        return (0);
    }
}
References ASSERT_EVBUFFER_LOCKED, evbuffer_chain::buffer_len, CHAIN_SPACE_LEN, evbuffer_chain_free(), evbuffer_chain_insert(), evbuffer_chain_new(), EVBUFFER_IMMUTABLE, EVUTIL_ASSERT, evbuffer::first, evbuffer_chain::flags, evbuffer::last, evbuffer::last_with_datap, evbuffer_chain::misalign, evbuffer_chain::next, evbuffer_chain::off, and ZERO_CHAIN().
Referenced by evbuffer_add_iovec(), evbuffer_launch_read_(), evbuffer_read(), and evbuffer_reserve_space().
evbuffer_get_callbacks_()
int evbuffer_get_callbacks_ (struct evbuffer * buffer, struct event_callback ** cbs, int max_cbs)
Definition at line 3451 of file buffer.c.
{
    int r = 0;
    EVBUFFER_LOCK(buffer);
    if (buffer->deferred_cbs) {
        if (max_cbs < 1) {
            r = -1;
            goto done;
        }
        cbs[0] = &buffer->deferred;
        r = 1;
    }
done:
    EVBUFFER_UNLOCK(buffer);
    return r;
}
References EVBUFFER_LOCK, and EVBUFFER_UNLOCK.
Referenced by bufferevent_decref_and_unlock_().
evbuffer_incref_()
void evbuffer_incref_ (struct evbuffer * buf)
Increase the reference count of buf by one.
Definition at line 396 of file buffer.c.
{
    EVBUFFER_LOCK(buf);
    ++buf->refcnt;
    EVBUFFER_UNLOCK(buf);
}
References EVBUFFER_LOCK, EVBUFFER_UNLOCK, and evbuffer::refcnt.
Referenced by APPEND_CHAIN_MULTICAST(), evbuffer_launch_read_(), and evbuffer_launch_write_().
evbuffer_incref_and_lock_()
void evbuffer_incref_and_lock_ (struct evbuffer * buf)
Increase the reference count of buf by one and acquire the lock.
Definition at line 404 of file buffer.c.
{
    EVBUFFER_LOCK(buf);
    ++buf->refcnt;
}
References EVBUFFER_LOCK, and evbuffer::refcnt.
Referenced by evbuffer_invoke_callbacks_().
evbuffer_invoke_callbacks_()
void evbuffer_invoke_callbacks_ (struct evbuffer * buf)
Definition at line 514 of file buffer.c.
{
    if (LIST_EMPTY(&buffer->callbacks)) {
        buffer->n_add_for_cb = buffer->n_del_for_cb = 0;
        return;
    }
    if (buffer->deferred_cbs) {
        if (event_deferred_cb_schedule_(buffer->cb_queue, &buffer->deferred)) {
            evbuffer_incref_and_lock_(buffer);
            if (buffer->parent)
                bufferevent_incref_(buffer->parent);
            EVBUFFER_UNLOCK(buffer);
        }
    }
    evbuffer_run_callbacks(buffer, 0);
}
References bufferevent_incref_, evbuffer_incref_and_lock_(), evbuffer_run_callbacks(), EVBUFFER_UNLOCK, and event_deferred_cb_schedule_().
Referenced by evbuffer_add(), evbuffer_add_buffer(), evbuffer_add_buffer_reference(), evbuffer_add_file_segment(), evbuffer_add_reference(), evbuffer_add_vprintf(), evbuffer_commit_read_(), evbuffer_commit_space(), evbuffer_drain(), evbuffer_prepend(), evbuffer_prepend_buffer(), evbuffer_read(), and evbuffer_remove_buffer().
evbuffer_read_setup_vecs_()
int evbuffer_read_setup_vecs_ (struct evbuffer * buf, ev_ssize_t howmuch, struct evbuffer_iovec * vecs, int n_vecs_avail, struct evbuffer_chain *** chainp, int exact)
Helper: prepares for a readv/WSARecv call by expanding the buffer to hold enough memory to read 'howmuch' bytes in possibly noncontiguous memory. Sets up the one or two iovecs in 'vecs' to point to the free memory and its extent, and *chainp to point to the first chain that we'll try to read into. Returns the number of vecs used.
Helper function to figure out which space to use for reading data into an evbuffer. Internal use only.
Parameters
buf The buffer to read into
howmuch How much we want to read.
vecs An array of two or more iovecs or WSABUFs.
n_vecs_avail The length of vecs
chainp A pointer to a variable to hold the first chain we're reading into.
exact Boolean: if true, we do not provide more than 'howmuch' space in the vectors, even if more space is available.
Returns
The number of buffers we're using.
Definition at line 2225 of file buffer.c.
{
    struct evbuffer_chain *chain;
    struct evbuffer_chain **firstchainp;
    size_t so_far;
    int i;
    ASSERT_EVBUFFER_LOCKED(buf);
    if (howmuch < 0)
        return -1;
    so_far = 0;
    /* Let firstchain be the first chain with any space on it */
    firstchainp = buf->last_with_datap;
    EVUTIL_ASSERT(*firstchainp);
    if (CHAIN_SPACE_LEN(*firstchainp) == 0) {
        firstchainp = &(*firstchainp)->next;
    }
    chain = *firstchainp;
    EVUTIL_ASSERT(chain);
    for (i = 0; i < n_vecs_avail && so_far < (size_t)howmuch; ++i) {
        size_t avail = (size_t) CHAIN_SPACE_LEN(chain);
        if (avail > (howmuch - so_far) && exact)
            avail = howmuch - so_far;
        vecs[i].iov_base = (void *)CHAIN_SPACE_PTR(chain);
        vecs[i].iov_len = avail;
        so_far += avail;
        chain = chain->next;
    }
    *chainp = firstchainp;
    return i;
}
References ASSERT_EVBUFFER_LOCKED, CHAIN_SPACE_LEN, CHAIN_SPACE_PTR, EVUTIL_ASSERT, evbuffer::last_with_datap, and evbuffer_chain::next.
Referenced by evbuffer_launch_read_(), evbuffer_read(), and evbuffer_reserve_space().
evbuffer_set_parent_()
void evbuffer_set_parent_ (struct evbuffer * buf, struct bufferevent * bev)
Set the parent bufferevent object for buf to bev
Definition at line 448 of file buffer.c.
{
    EVBUFFER_LOCK(buf);
    buf->parent = bev;
    EVBUFFER_UNLOCK(buf);
}
References EVBUFFER_LOCK, EVBUFFER_UNLOCK, and evbuffer::parent.
Referenced by bufferevent_init_common_().