libdogecoin: src/libevent/event_tagging.c File Reference
event_tagging.c File Reference
#include "event2/event-config.h"
#include "evconfig-private.h"
#include <sys/queue.h>
#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <syslog.h>
#include <limits.h>
#include "event2/event.h"
#include "event2/tag.h"
#include "event2/buffer.h"
#include "log-internal.h"
#include "mm-internal.h"
#include "util-internal.h"
Macros
#define ENCODE_INT_INTERNAL(data, number)
#define DECODE_INT_INTERNAL(number, maxnibbles, pnumber, evbuf, offset)
Functions
EVENT2_EXPORT_SYMBOL int evtag_decode_int (ev_uint32_t *pnumber, struct evbuffer *evbuf)
EVENT2_EXPORT_SYMBOL int evtag_decode_int64 (ev_uint64_t *pnumber, struct evbuffer *evbuf)
EVENT2_EXPORT_SYMBOL int evtag_encode_tag (struct evbuffer *evbuf, ev_uint32_t tag)
EVENT2_EXPORT_SYMBOL int evtag_decode_tag (ev_uint32_t *ptag, struct evbuffer *evbuf)
void evtag_init (void)
static int encode_int_internal (ev_uint8_t *data, ev_uint32_t number)
static int encode_int64_internal (ev_uint8_t *data, ev_uint64_t number)
void evtag_encode_int (struct evbuffer *evbuf, ev_uint32_t number)
void evtag_encode_int64 (struct evbuffer *evbuf, ev_uint64_t number)
static int decode_tag_internal (ev_uint32_t *ptag, struct evbuffer *evbuf, int dodrain)
void evtag_marshal (struct evbuffer *evbuf, ev_uint32_t tag, const void *data, ev_uint32_t len)
void evtag_marshal_buffer (struct evbuffer *evbuf, ev_uint32_t tag, struct evbuffer *data)
void evtag_marshal_int (struct evbuffer *evbuf, ev_uint32_t tag, ev_uint32_t integer)
void evtag_marshal_int64 (struct evbuffer *evbuf, ev_uint32_t tag, ev_uint64_t integer)
void evtag_marshal_string (struct evbuffer *buf, ev_uint32_t tag, const char *string)
void evtag_marshal_timeval (struct evbuffer *evbuf, ev_uint32_t tag, struct timeval *tv)
static int decode_int_internal (ev_uint32_t *pnumber, struct evbuffer *evbuf, int offset)
static int decode_int64_internal (ev_uint64_t *pnumber, struct evbuffer *evbuf, int offset)
int evtag_peek (struct evbuffer *evbuf, ev_uint32_t *ptag)
int evtag_peek_length (struct evbuffer *evbuf, ev_uint32_t *plength)
int evtag_payload_length (struct evbuffer *evbuf, ev_uint32_t *plength)
int evtag_unmarshal_header (struct evbuffer *evbuf, ev_uint32_t *ptag)
int evtag_consume (struct evbuffer *evbuf)
int evtag_unmarshal (struct evbuffer *src, ev_uint32_t *ptag, struct evbuffer *dst)
int evtag_unmarshal_int (struct evbuffer *evbuf, ev_uint32_t need_tag, ev_uint32_t *pinteger)
int evtag_unmarshal_int64 (struct evbuffer *evbuf, ev_uint32_t need_tag, ev_uint64_t *pinteger)
int evtag_unmarshal_fixed (struct evbuffer *src, ev_uint32_t need_tag, void *data, size_t len)
int evtag_unmarshal_string (struct evbuffer *evbuf, ev_uint32_t need_tag, char **pstring)
int evtag_unmarshal_timeval (struct evbuffer *evbuf, ev_uint32_t need_tag, struct timeval *ptv)
Macro Definition Documentation
DECODE_INT_INTERNAL
#define DECODE_INT_INTERNAL (number, maxnibbles, pnumber, evbuf, offset)
Definition at line 319 of file event_tagging.c.
ENCODE_INT_INTERNAL
#define ENCODE_INT_INTERNAL (data, number)
Value:
    do {                \
    int off = 1, nibbles = 0;                   \
                                    \
    memset(data, 0, sizeof(number)+1);              \
    while (number) {                        \
        if (off & 0x1)                      \
            data[off/2] = (data[off/2] & 0xf0) | (number & 0x0f); \
        else                            \
            data[off/2] = (data[off/2] & 0x0f) |        \
                ((number & 0x0f) << 4);         \
        number >>= 4;                       \
        off++;                          \
    }                               \
                                    \
    if (off > 2)                            \
        nibbles = off - 2;                  \
                                    \
    /* Off - 1 is the number of encoded nibbles */          \
    data[0] = (data[0] & 0x0f) | ((nibbles & 0x0f) << 4);       \
                                    \
    return ((off + 1) / 2);                     \
} while (0)
Definition at line 121 of file event_tagging.c.
Function Documentation
decode_int64_internal()
static int decode_int64_internal (ev_uint64_t * pnumber, struct evbuffer * evbuf, int offset) static
Definition at line 373 of file event_tagging.c.
{
    ev_uint64_t number = 0;
    DECODE_INT_INTERNAL(number, 16, pnumber, evbuf, offset);
}
References DECODE_INT_INTERNAL.
Referenced by evtag_decode_int64(), and evtag_unmarshal_int64().
decode_int_internal()
static int decode_int_internal (ev_uint32_t * pnumber, struct evbuffer * evbuf, int offset) static
Definition at line 366 of file event_tagging.c.
{
    ev_uint32_t number = 0;
    DECODE_INT_INTERNAL(number, 8, pnumber, evbuf, offset);
}
References DECODE_INT_INTERNAL.
Referenced by evtag_decode_int(), evtag_payload_length(), evtag_peek_length(), evtag_unmarshal_int(), and evtag_unmarshal_timeval().
decode_tag_internal()
static int decode_tag_internal (ev_uint32_t * ptag, struct evbuffer * evbuf, int dodrain) static
Definition at line 201 of file event_tagging.c.
{
    ev_uint32_t number = 0;
    size_t len = evbuffer_get_length(evbuf);
    ev_uint8_t *data;
    size_t count = 0;
    int  shift = 0, done = 0;
    /*
     * the encoding of a number is at most one byte more than its
     * storage size.  however, it may also be much smaller.
     */
    data = evbuffer_pullup(
        evbuf, len < sizeof(number) + 1 ? len : sizeof(number) + 1);
    if (!data)
        return (-1);
    while (count++ < len) {
        ev_uint8_t lower = *data++;
        if (shift >= 28) {
            /* Make sure it fits into 32 bits */
            if (shift > 28)
                return (-1);
            if ((lower & 0x7f) > 15)
                return (-1);
        }
        number |= (lower & (unsigned)0x7f) << shift;
        shift += 7;
        if (!(lower & 0x80)) {
            done = 1;
            break;
        }
    }
    if (!done)
        return (-1);
    if (dodrain)
        evbuffer_drain(evbuf, count);
    if (ptag != NULL)
        *ptag = number;
    return count > INT_MAX ? INT_MAX : (int)(count);
}
References count, evbuffer_drain(), evbuffer_get_length(), and evbuffer_pullup().
Referenced by evtag_decode_tag(), evtag_payload_length(), evtag_peek(), evtag_peek_length(), evtag_unmarshal_header(), evtag_unmarshal_int(), and evtag_unmarshal_int64().
encode_int64_internal()
static int encode_int64_internal (ev_uint8_t * data, ev_uint64_t number) inline static
Definition at line 151 of file event_tagging.c.
{
    ENCODE_INT_INTERNAL(data, number);
}
References ENCODE_INT_INTERNAL.
Referenced by evtag_encode_int64(), and evtag_marshal_int64().
encode_int_internal()
static int encode_int_internal (ev_uint8_t * data, ev_uint32_t number) inline static
Definition at line 145 of file event_tagging.c.
{
    ENCODE_INT_INTERNAL(data, number);
}
References ENCODE_INT_INTERNAL.
Referenced by evtag_encode_int(), evtag_marshal_int(), and evtag_marshal_timeval().
evtag_consume()
int evtag_consume (struct evbuffer * evbuf)
Definition at line 458 of file event_tagging.c.
{
    int len;
    if ((len = evtag_unmarshal_header(evbuf, NULL)) == -1)
        return (-1);
    evbuffer_drain(evbuf, len);
    return (0);
}
References evbuffer_drain(), and evtag_unmarshal_header().
evtag_decode_int()
int evtag_decode_int (ev_uint32_t * pnumber, struct evbuffer * evbuf)
Definition at line 380 of file event_tagging.c.
{
    int res = decode_int_internal(pnumber, evbuf, 0);
    if (res != -1)
        evbuffer_drain(evbuf, res);
    return (res == -1 ? -1 : 0);
}
References decode_int_internal(), and evbuffer_drain().
Referenced by evtag_unmarshal_header(), evtag_unmarshal_int(), and evtag_unmarshal_int64().
evtag_decode_int64()
int evtag_decode_int64 (ev_uint64_t * pnumber, struct evbuffer * evbuf)
Definition at line 390 of file event_tagging.c.
{
    int res = decode_int64_internal(pnumber, evbuf, 0);
    if (res != -1)
        evbuffer_drain(evbuf, res);
    return (res == -1 ? -1 : 0);
}
References decode_int64_internal(), and evbuffer_drain().
evtag_decode_tag()
int evtag_decode_tag (ev_uint32_t * ptag, struct evbuffer * evbuf)
Definition at line 249 of file event_tagging.c.
{
    return (decode_tag_internal(ptag, evbuf, 1 /* dodrain */));
}
References decode_tag_internal().
evtag_encode_int()
void evtag_encode_int (struct evbuffer * evbuf, ev_uint32_t number)
Definition at line 157 of file event_tagging.c.
{
    ev_uint8_t data[5];
    int len = encode_int_internal(data, number);
    evbuffer_add(evbuf, data, len);
}
References encode_int_internal(), and evbuffer_add().
Referenced by evtag_marshal(), evtag_marshal_buffer(), evtag_marshal_int(), and evtag_marshal_int64().
evtag_encode_int64()
void evtag_encode_int64 (struct evbuffer * evbuf, ev_uint64_t number)
Definition at line 165 of file event_tagging.c.
{
    ev_uint8_t data[9];
    int len = encode_int64_internal(data, number);
    evbuffer_add(evbuf, data, len);
}
References encode_int64_internal(), and evbuffer_add().
evtag_encode_tag()
int evtag_encode_tag (struct evbuffer * evbuf, ev_uint32_t tag)
Definition at line 178 of file event_tagging.c.
{
    int bytes = 0;
    ev_uint8_t data[5];
    memset(data, 0, sizeof(data));
    do {
        ev_uint8_t lower = tag & 0x7f;
        tag >>= 7;
        if (tag)
            lower |= 0x80;
        data[bytes++] = lower;
    } while (tag);
    if (evbuf != NULL)
        evbuffer_add(evbuf, data, bytes);
    return (bytes);
}
References evbuffer_add().
Referenced by evtag_marshal(), evtag_marshal_buffer(), evtag_marshal_int(), and evtag_marshal_int64().
evtag_init()
void evtag_init (void)
Definition at line 106 of file event_tagging.c.
{
}
Referenced by evrpc_init().
evtag_marshal()
void evtag_marshal (struct evbuffer * evbuf, ev_uint32_t tag, const void * data, ev_uint32_t len)
Definition at line 261 of file event_tagging.c.
{
    evtag_encode_tag(evbuf, tag);
    evtag_encode_int(evbuf, len);
    evbuffer_add(evbuf, (void *)data, len);
}
References evbuffer_add(), evtag_encode_int(), and evtag_encode_tag().
Referenced by evtag_marshal_string(), and evtag_marshal_timeval().
evtag_marshal_buffer()
void evtag_marshal_buffer (struct evbuffer * evbuf, ev_uint32_t tag, struct evbuffer * data)
Definition at line 270 of file event_tagging.c.
{
    evtag_encode_tag(evbuf, tag);
    /* XXX support more than UINT32_MAX data */
    evtag_encode_int(evbuf, (ev_uint32_t)evbuffer_get_length(data));
    evbuffer_add_buffer(evbuf, data);
}
References evbuffer_add_buffer(), evbuffer_get_length(), evtag_encode_int(), and evtag_encode_tag().
evtag_marshal_int()
void evtag_marshal_int (struct evbuffer * evbuf, ev_uint32_t tag, ev_uint32_t integer)
Definition at line 281 of file event_tagging.c.
{
    ev_uint8_t data[5];
    int len = encode_int_internal(data, integer);
    evtag_encode_tag(evbuf, tag);
    evtag_encode_int(evbuf, len);
    evbuffer_add(evbuf, data, len);
}
References encode_int_internal(), evbuffer_add(), evtag_encode_int(), and evtag_encode_tag().
evtag_marshal_int64()
void evtag_marshal_int64 (struct evbuffer * evbuf, ev_uint32_t tag, ev_uint64_t integer)
Definition at line 292 of file event_tagging.c.
{
    ev_uint8_t data[9];
    int len = encode_int64_internal(data, integer);
    evtag_encode_tag(evbuf, tag);
    evtag_encode_int(evbuf, len);
    evbuffer_add(evbuf, data, len);
}
References encode_int64_internal(), evbuffer_add(), evtag_encode_int(), and evtag_encode_tag().
evtag_marshal_string()
void evtag_marshal_string (struct evbuffer * buf, ev_uint32_t tag, const char * string)
Definition at line 304 of file event_tagging.c.
{
    /* TODO support strings longer than UINT32_MAX ? */
    evtag_marshal(buf, tag, string, (ev_uint32_t)strlen(string));
}
References evtag_marshal().
evtag_marshal_timeval()
void evtag_marshal_timeval (struct evbuffer * evbuf, ev_uint32_t tag, struct timeval * tv)
Definition at line 311 of file event_tagging.c.
{
    ev_uint8_t data[10];
    int len = encode_int_internal(data, tv->tv_sec);
    len += encode_int_internal(data + len, tv->tv_usec);
    evtag_marshal(evbuf, tag, data, len);
}
References encode_int_internal(), and evtag_marshal().
evtag_payload_length()
int evtag_payload_length (struct evbuffer * evbuf, ev_uint32_t * plength)
Definition at line 424 of file event_tagging.c.
{
    int res, len;
    len = decode_tag_internal(NULL, evbuf, 0 /* dodrain */);
    if (len == -1)
        return (-1);
    res = decode_int_internal(plength, evbuf, len);
    if (res == -1)
        return (-1);
    return (0);
}
References decode_int_internal(), and decode_tag_internal().
evtag_peek()
int evtag_peek (struct evbuffer * evbuf, ev_uint32_t * ptag)
Definition at line 400 of file event_tagging.c.
{
    return (decode_tag_internal(ptag, evbuf, 0 /* dodrain */));
}
References decode_tag_internal().
evtag_peek_length()
int evtag_peek_length (struct evbuffer * evbuf, ev_uint32_t * plength)
Definition at line 406 of file event_tagging.c.
{
    int res, len;
    len = decode_tag_internal(NULL, evbuf, 0 /* dodrain */);
    if (len == -1)
        return (-1);
    res = decode_int_internal(plength, evbuf, len);
    if (res == -1)
        return (-1);
    *plength += res + len;
    return (0);
}
References decode_int_internal(), and decode_tag_internal().
evtag_unmarshal()
int evtag_unmarshal (struct evbuffer * src, ev_uint32_t * ptag, struct evbuffer * dst)
Definition at line 471 of file event_tagging.c.
{
    int len;
    if ((len = evtag_unmarshal_header(src, ptag)) == -1)
        return (-1);
    if (evbuffer_add(dst, evbuffer_pullup(src, len), len) == -1)
        return (-1);
    evbuffer_drain(src, len);
    return (len);
}
References evbuffer_add(), evbuffer_drain(), evbuffer_pullup(), and evtag_unmarshal_header().
evtag_unmarshal_fixed()
int evtag_unmarshal_fixed (struct evbuffer * src, ev_uint32_t need_tag, void * data, size_t len)
Definition at line 543 of file event_tagging.c.
{
    ev_uint32_t tag;
    int tag_len;
    /* Now unmarshal a tag and check that it matches the tag we want */
    if ((tag_len = evtag_unmarshal_header(src, &tag)) < 0 ||
        tag != need_tag)
        return (-1);
    if ((size_t)tag_len != len)
        return (-1);
    evbuffer_remove(src, data, len);
    return (0);
}
References evbuffer_remove(), and evtag_unmarshal_header().
evtag_unmarshal_header()
int evtag_unmarshal_header (struct evbuffer * evbuf, ev_uint32_t * ptag)
Definition at line 442 of file event_tagging.c.
{
    ev_uint32_t len;
    if (decode_tag_internal(ptag, evbuf, 1 /* dodrain */) == -1)
        return (-1);
    if (evtag_decode_int(&len, evbuf) == -1)
        return (-1);
    if (evbuffer_get_length(evbuf) < len)
        return (-1);
    return (len);
}
References decode_tag_internal(), evbuffer_get_length(), and evtag_decode_int().
Referenced by evtag_consume(), evtag_unmarshal(), evtag_unmarshal_fixed(), evtag_unmarshal_string(), and evtag_unmarshal_timeval().
evtag_unmarshal_int()
int evtag_unmarshal_int (struct evbuffer * evbuf, ev_uint32_t need_tag, ev_uint32_t * pinteger)
Definition at line 489 of file event_tagging.c.
{
    ev_uint32_t tag;
    ev_uint32_t len;
    int result;
    if (decode_tag_internal(&tag, evbuf, 1 /* dodrain */) == -1)
        return (-1);
    if (need_tag != tag)
        return (-1);
    if (evtag_decode_int(&len, evbuf) == -1)
        return (-1);
    if (evbuffer_get_length(evbuf) < len)
        return (-1);
    result = decode_int_internal(pinteger, evbuf, 0);
    evbuffer_drain(evbuf, len);
    if (result < 0 || (size_t)result > len) /* XXX Should this be != rather than > ?*/
        return (-1);
    else
        return result;
}
References decode_int_internal(), decode_tag_internal(), evbuffer_drain(), evbuffer_get_length(), and evtag_decode_int().
evtag_unmarshal_int64()
int evtag_unmarshal_int64 (struct evbuffer * evbuf, ev_uint32_t need_tag, ev_uint64_t * pinteger)
Definition at line 515 of file event_tagging.c.
{
    ev_uint32_t tag;
    ev_uint32_t len;
    int result;
    if (decode_tag_internal(&tag, evbuf, 1 /* dodrain */) == -1)
        return (-1);
    if (need_tag != tag)
        return (-1);
    if (evtag_decode_int(&len, evbuf) == -1)
        return (-1);
    if (evbuffer_get_length(evbuf) < len)
        return (-1);
    result = decode_int64_internal(pinteger, evbuf, 0);
    evbuffer_drain(evbuf, len);
    if (result < 0 || (size_t)result > len) /* XXX Should this be != rather than > ?*/
        return (-1);
    else
        return result;
}
References decode_int64_internal(), decode_tag_internal(), evbuffer_drain(), evbuffer_get_length(), and evtag_decode_int().
evtag_unmarshal_string()
int evtag_unmarshal_string (struct evbuffer * evbuf, ev_uint32_t need_tag, char ** pstring)
Definition at line 562 of file event_tagging.c.
{
    ev_uint32_t tag;
    int tag_len;
    if ((tag_len = evtag_unmarshal_header(evbuf, &tag)) == -1 ||
        tag != need_tag)
        return (-1);
    *pstring = mm_malloc(tag_len + 1);
    if (*pstring == NULL) {
        event_warn("%s: malloc", __func__);
        return -1;
    }
    evbuffer_remove(evbuf, *pstring, tag_len);
    (*pstring)[tag_len] = '\0';
    return (0);
}
References __func__, evbuffer_remove(), event_warn(), evtag_unmarshal_header(), and mm_malloc.
evtag_unmarshal_timeval()
int evtag_unmarshal_timeval (struct evbuffer * evbuf, ev_uint32_t need_tag, struct timeval * ptv)
Definition at line 584 of file event_tagging.c.
{
    ev_uint32_t tag;
    ev_uint32_t integer;
    int len, offset, offset2;
    int result = -1;
    if ((len = evtag_unmarshal_header(evbuf, &tag)) == -1)
        return (-1);
    if (tag != need_tag)
        goto done;
    if ((offset = decode_int_internal(&integer, evbuf, 0)) == -1)
        goto done;
    ptv->tv_sec = integer;
    if ((offset2 = decode_int_internal(&integer, evbuf, offset)) == -1)
        goto done;
    ptv->tv_usec = integer;
    if (offset + offset2 > len) /* XXX Should this be != instead of > ? */
        goto done;
    result = 0;
 done:
    evbuffer_drain(evbuf, len);
    return result;
}
References decode_int_internal(), evbuffer_drain(), and evtag_unmarshal_header().