libdogecoin: src/libevent/event_iocp.c File Reference
event_iocp.c File Reference
#include "evconfig-private.h"
#include <winsock2.h>
#include <windows.h>
#include <process.h>
#include <stdio.h>
#include <mswsock.h>
#include "event2/util.h"
#include "util-internal.h"
#include "iocp-internal.h"
#include "log-internal.h"
#include "mm-internal.h"
#include "event-internal.h"
#include "evthread-internal.h"
Macros
#define _WIN32_WINNT 0x0403
#define NOTIFICATION_KEY ((ULONG_PTR)-1)
#define WSAID_ACCEPTEX {0xb5367df1,0xcbac,0x11cf,{0x95,0xca,0x00,0x80,0x5f,0x48,0xa1,0x92}}
#define WSAID_CONNECTEX {0x25a207b9,0xddf3,0x4660,{0x8e,0xe9,0x76,0xe5,0x8c,0x74,0x06,0x3e}}
#define WSAID_GETACCEPTEXSOCKADDRS {0xb5367df2,0xcbac,0x11cf,{0x95,0xca,0x00,0x80,0x5f,0x48,0xa1,0x92}}
#define N_CPUS_DEFAULT 2
Functions
void event_overlapped_init_ (struct event_overlapped *o, iocp_callback cb)
static void handle_entry (OVERLAPPED *o, ULONG_PTR completion_key, DWORD nBytes, int ok)
static void loop (void *port_)
int event_iocp_port_associate_ (struct event_iocp_port *port, evutil_socket_t fd, ev_uintptr_t key)
static void * get_extension_function (SOCKET s, const GUID *which_fn)
static void init_extension_functions (struct win32_extension_fns *ext)
const struct win32_extension_fns * event_get_win32_extension_fns_ (void)
struct event_iocp_port * event_iocp_port_launch_ (int n_cpus)
static void event_iocp_port_unlock_and_free_ (struct event_iocp_port *port)
static int event_iocp_notify_all (struct event_iocp_port *port)
int event_iocp_shutdown_ (struct event_iocp_port *port, long waitMsec)
int event_iocp_activate_overlapped_ (struct event_iocp_port *port, struct event_overlapped *o, ev_uintptr_t key, ev_uint32_t n)
struct event_iocp_port * event_base_get_iocp_ (struct event_base *base)
Variables
static int extension_fns_initialized = 0
static struct win32_extension_fns the_extension_fns
Macro Definition Documentation
_WIN32_WINNT
#define _WIN32_WINNT 0x0403
Definition at line 30 of file event_iocp.c.
N_CPUS_DEFAULT
#define N_CPUS_DEFAULT 2
Definition at line 173 of file event_iocp.c.
NOTIFICATION_KEY
#define NOTIFICATION_KEY ((ULONG_PTR)-1)
Definition at line 46 of file event_iocp.c.
WSAID_ACCEPTEX
#define WSAID_ACCEPTEX {0xb5367df1,0xcbac,0x11cf,{0x95,0xca,0x00,0x80,0x5f,0x48,0xa1,0x92}}
Definition at line 133 of file event_iocp.c.
WSAID_CONNECTEX
#define WSAID_CONNECTEX {0x25a207b9,0xddf3,0x4660,{0x8e,0xe9,0x76,0xe5,0x8c,0x74,0x06,0x3e}}
Definition at line 137 of file event_iocp.c.
WSAID_GETACCEPTEXSOCKADDRS
#define WSAID_GETACCEPTEXSOCKADDRS {0xb5367df2,0xcbac,0x11cf,{0x95,0xca,0x00,0x80,0x5f,0x48,0xa1,0x92}}
Definition at line 141 of file event_iocp.c.
Function Documentation
event_base_get_iocp_()
struct event_iocp_port * event_base_get_iocp_ (struct event_base * base)
Definition at line 287 of file event_iocp.c.
{
#ifdef _WIN32
    return base->iocp;
#else
    return NULL;
#endif
}
Referenced by be_async_ctrl(), bufferevent_async_can_connect_(), bufferevent_async_new_(), bufferevent_socket_new(), and evconnlistener_new().
event_get_win32_extension_fns_()
const struct win32_extension_fns * event_get_win32_extension_fns_ (void)
Definition at line 168 of file event_iocp.c.
{
    return &the_extension_fns;
}
References the_extension_fns.
Referenced by bufferevent_async_can_connect_(), bufferevent_async_connect_(), and evconnlistener_new().
event_iocp_activate_overlapped_()
int event_iocp_activate_overlapped_ (struct event_iocp_port * port, struct event_overlapped * o, ev_uintptr_t key, ev_uint32_t n)
Definition at line 276 of file event_iocp.c.
{
    BOOL r;
    r = PostQueuedCompletionStatus(port->port, n, key, &o->overlapped);
    return (r==0) ? -1 : 0;
}
event_iocp_notify_all()
static int event_iocp_notify_all (struct event_iocp_port * port) static
Definition at line 237 of file event_iocp.c.
{
    int i, r, ok=1;
    for (i=0; i<port->n_threads; ++i) {
        r = PostQueuedCompletionStatus(port->port, 0, NOTIFICATION_KEY,
            NULL);
        if (!r)
            ok = 0;
    }
    return ok ? 0 : -1;
}
References NOTIFICATION_KEY.
Referenced by event_iocp_shutdown_().
event_iocp_port_associate_()
int event_iocp_port_associate_ (struct event_iocp_port * port, evutil_socket_t fd, ev_uintptr_t key)
Associate a file descriptor with an iocp, such that overlapped IO on the fd will happen on one of the iocp's worker threads.
Definition at line 102 of file event_iocp.c.
{
    HANDLE h;
    h = CreateIoCompletionPort((HANDLE)fd, port->port, key, port->n_threads);
    if (!h)
        return -1;
    return 0;
}
Referenced by be_async_ctrl(), and bufferevent_async_new_().
event_iocp_port_launch_()
struct event_iocp_port * event_iocp_port_launch_ (int n_cpus)
Create an IOCP, and launch its worker threads. Internal use only.
This interface is unstable, and will change.
Definition at line 176 of file event_iocp.c.
{
    struct event_iocp_port *port;
    int i;
    if (!extension_fns_initialized)
        init_extension_functions(&the_extension_fns);
    if (!(port = mm_calloc(1, sizeof(struct event_iocp_port))))
        return NULL;
    if (n_cpus <= 0)
        n_cpus = N_CPUS_DEFAULT;
    port->n_threads = n_cpus * 2;
    port->threads = mm_calloc(port->n_threads, sizeof(HANDLE));
    if (!port->threads)
        goto err;
    port->port = CreateIoCompletionPort(INVALID_HANDLE_VALUE, NULL, 0,
            n_cpus);
    port->ms = -1;
    if (!port->port)
        goto err;
    port->shutdownSemaphore = CreateSemaphore(NULL, 0, 1, NULL);
    if (!port->shutdownSemaphore)
        goto err;
    for (i=0; i<port->n_threads; ++i) {
        ev_uintptr_t th = _beginthread(loop, 0, port);
        if (th == (ev_uintptr_t)-1)
            goto err;
        port->threads[i] = (HANDLE)th;
        ++port->n_live_threads;
    }
    InitializeCriticalSectionAndSpinCount(&port->lock, 1000);
    return port;
err:
    if (port->port)
        CloseHandle(port->port);
    if (port->threads)
        mm_free(port->threads);
    if (port->shutdownSemaphore)
        CloseHandle(port->shutdownSemaphore);
    mm_free(port);
    return NULL;
}
References extension_fns_initialized, init_extension_functions(), loop(), mm_calloc, mm_free, N_CPUS_DEFAULT, and the_extension_fns.
Referenced by event_base_start_iocp_().
event_iocp_port_unlock_and_free_()
static void event_iocp_port_unlock_and_free_ (struct event_iocp_port * port) static
Definition at line 227 of file event_iocp.c.
{
    DeleteCriticalSection(&port->lock);
    CloseHandle(port->port);
    CloseHandle(port->shutdownSemaphore);
    mm_free(port->threads);
    mm_free(port);
}
References mm_free.
Referenced by event_iocp_shutdown_().
event_iocp_shutdown_()
int event_iocp_shutdown_ (struct event_iocp_port * port, long waitMsec)
Tell all threads serving an iocp to stop. Wait for up to waitMsec for all the threads to finish whatever they're doing. If waitMsec is -1, wait as long as required. If all the threads are done, free the port and return 0. Otherwise, return -1. If you get a -1 return value, it is safe to call this function again.
Definition at line 250 of file event_iocp.c.
{
    DWORD ms = INFINITE;
    int n;
    EnterCriticalSection(&port->lock);
    port->shutdown = 1;
    LeaveCriticalSection(&port->lock);
    event_iocp_notify_all(port);
    if (waitMsec >= 0)
        ms = waitMsec;
    WaitForSingleObject(port->shutdownSemaphore, ms);
    EnterCriticalSection(&port->lock);
    n = port->n_live_threads;
    LeaveCriticalSection(&port->lock);
    if (n == 0) {
        event_iocp_port_unlock_and_free_(port);
        return 0;
    } else {
        return -1;
    }
}
References event_iocp_notify_all(), and event_iocp_port_unlock_and_free_().
Referenced by event_base_stop_iocp_().
event_overlapped_init_()
void event_overlapped_init_ (struct event_overlapped * o, iocp_callback cb)
Initialize the fields in an event_overlapped.
Parameters
overlapped The struct event_overlapped to initialize
cb The callback that should be invoked once the IO operation has finished.
Definition at line 49 of file event_iocp.c.
{
    memset(o, 0, sizeof(struct event_overlapped));
    o->cb = cb;
}
References event_overlapped::cb.
Referenced by bufferevent_async_new_().
get_extension_function()
static void * get_extension_function (SOCKET s, const GUID * which_fn) static
Definition at line 113 of file event_iocp.c.
{
    void *ptr = NULL;
    DWORD bytes=0;
    WSAIoctl(s, SIO_GET_EXTENSION_FUNCTION_POINTER,
        (GUID*)which_fn, sizeof(*which_fn),
        &ptr, sizeof(ptr),
        &bytes, NULL, NULL);
    /* No need to detect errors here: if ptr is set, then we have a good
       function pointer.  Otherwise, we should behave as if we had no
       function pointer.
    */
    return ptr;
}
Referenced by init_extension_functions().
handle_entry()
static void handle_entry (OVERLAPPED * o, ULONG_PTR completion_key, DWORD nBytes, int ok) static
Definition at line 56 of file event_iocp.c.
{
    struct event_overlapped *eo =
        EVUTIL_UPCAST(o, struct event_overlapped, overlapped);
    eo->cb(eo, completion_key, nBytes, ok);
}
References event_overlapped::cb, and EVUTIL_UPCAST.
Referenced by loop().
init_extension_functions()
static void init_extension_functions (struct win32_extension_fns * ext) static
Definition at line 148 of file event_iocp.c.
{
    const GUID acceptex = WSAID_ACCEPTEX;
    const GUID connectex = WSAID_CONNECTEX;
    const GUID getacceptexsockaddrs = WSAID_GETACCEPTEXSOCKADDRS;
    SOCKET s = socket(AF_INET, SOCK_STREAM, 0);
    if (s == EVUTIL_INVALID_SOCKET)
        return;
    ext->AcceptEx = get_extension_function(s, &acceptex);
    ext->ConnectEx = get_extension_function(s, &connectex);
    ext->GetAcceptExSockaddrs = get_extension_function(s,
        &getacceptexsockaddrs);
    closesocket(s);
    extension_fns_initialized = 1;
}
References extension_fns_initialized, get_extension_function(), WSAID_ACCEPTEX, WSAID_CONNECTEX, and WSAID_GETACCEPTEXSOCKADDRS.
Referenced by event_iocp_port_launch_().
loop()
static void loop (void * port_) static
Definition at line 64 of file event_iocp.c.
{
    struct event_iocp_port *port = port_;
    long ms = port->ms;
    HANDLE p = port->port;
    if (ms <= 0)
        ms = INFINITE;
    while (1) {
        OVERLAPPED *overlapped=NULL;
        ULONG_PTR key=0;
        DWORD bytes=0;
        int ok = GetQueuedCompletionStatus(p, &bytes, &key,
            &overlapped, ms);
        EnterCriticalSection(&port->lock);
        if (port->shutdown) {
            if (--port->n_live_threads == 0)
                ReleaseSemaphore(port->shutdownSemaphore, 1,
                        NULL);
            LeaveCriticalSection(&port->lock);
            return;
        }
        LeaveCriticalSection(&port->lock);
        if (key != NOTIFICATION_KEY && overlapped)
            handle_entry(overlapped, key, bytes, ok);
        else if (!overlapped)
            break;
    }
    event_warnx("GetQueuedCompletionStatus exited with no event.");
    EnterCriticalSection(&port->lock);
    if (--port->n_live_threads == 0)
        ReleaseSemaphore(port->shutdownSemaphore, 1, NULL);
    LeaveCriticalSection(&port->lock);
}
References event_warnx(), handle_entry(), and NOTIFICATION_KEY.
Referenced by event_iocp_port_launch_().
Variable Documentation
extension_fns_initialized
int extension_fns_initialized = 0 static
Definition at line 145 of file event_iocp.c.
Referenced by event_iocp_port_launch_(), and init_extension_functions().
the_extension_fns
struct win32_extension_fns the_extension_fns static
Definition at line 165 of file event_iocp.c.
Referenced by event_get_win32_extension_fns_(), and event_iocp_port_launch_().