libdogecoin: src/libevent/event-internal.h File Reference
event-internal.h File Reference
#include "event2/event-config.h"
#include "evconfig-private.h"
#include <time.h>
#include <sys/queue.h>
#include "event2/event_struct.h"
#include "minheap-internal.h"
#include "evsignal-internal.h"
#include "mm-internal.h"
#include "defer-internal.h"
Data Structures
struct eventop
struct event_signal_map
struct common_timeout_list
struct event_changelist
struct event_once
struct event_base
struct event_config_entry
struct event_config
Macros
#define ev_signal_next ev_.ev_signal.ev_signal_next
#define ev_io_next ev_.ev_io.ev_io_next
#define ev_io_timeout ev_.ev_io.ev_timeout
#define ev_ncalls ev_.ev_signal.ev_ncalls
#define ev_pncalls ev_.ev_signal.ev_pncalls
#define ev_pri ev_evcallback.evcb_pri
#define ev_flags ev_evcallback.evcb_flags
#define ev_closure ev_evcallback.evcb_closure
#define ev_callback ev_evcallback.evcb_cb_union.evcb_callback
#define ev_arg ev_evcallback.evcb_arg
#define event_io_map event_signal_map
#define COMMON_TIMEOUT_MICROSECONDS_MASK 0x000fffff
#define EVENT_DEBUG_MODE_IS_ON() (event_debug_mode_on_)
#define LIST_END(head) NULL
#define TAILQ_FIRST(head) ((head)->tqh_first)
#define TAILQ_END(head) NULL
#define TAILQ_NEXT(elm, field) ((elm)->field.tqe_next)
#define TAILQ_FOREACH(var, head, field)
#define TAILQ_INSERT_BEFORE(listelm, elm, field)
#define N_ACTIVE_CALLBACKS(base) ((base)->event_count_active)
#define EVENT_DEL_NOBLOCK 0
#define EVENT_DEL_BLOCK 1
#define EVENT_DEL_AUTOBLOCK 2
#define EVENT_DEL_EVEN_IF_FINALIZING 3
Event closure codes
Possible values for evcb_closure in struct event_callback
#define EV_CLOSURE_EVENT 0
#define EV_CLOSURE_EVENT_SIGNAL 1
#define EV_CLOSURE_EVENT_PERSIST 2
#define EV_CLOSURE_CB_SELF 3
#define EV_CLOSURE_CB_FINALIZE 4
#define EV_CLOSURE_EVENT_FINALIZE 5
#define EV_CLOSURE_EVENT_FINALIZE_FREE 6
Functions
TAILQ_HEAD (evcallback_list, event_callback)
int evsig_set_handler_ (struct event_base *base, int evsignal, void(*fn)(int))
int evsig_restore_handler_ (struct event_base *base, int evsignal)
int event_add_nolock_ (struct event *ev, const struct timeval *tv, int tv_is_absolute)
int event_del_nolock_ (struct event *ev, int blocking)
int event_remove_timer_nolock_ (struct event *ev)
void event_active_nolock_ (struct event *ev, int res, short count)
EVENT2_EXPORT_SYMBOL int event_callback_activate_ (struct event_base *, struct event_callback *)
int event_callback_activate_nolock_ (struct event_base *, struct event_callback *)
int event_callback_cancel_ (struct event_base *base, struct event_callback *evcb)
void event_callback_finalize_nolock_ (struct event_base *base, unsigned flags, struct event_callback *evcb, void(*cb)(struct event_callback *, void *))
EVENT2_EXPORT_SYMBOL void event_callback_finalize_ (struct event_base *base, unsigned flags, struct event_callback *evcb, void(*cb)(struct event_callback *, void *))
int event_callback_finalize_many_ (struct event_base *base, int n_cbs, struct event_callback **evcb, void(*cb)(struct event_callback *, void *))
EVENT2_EXPORT_SYMBOL void event_active_later_ (struct event *ev, int res)
void event_active_later_nolock_ (struct event *ev, int res)
int event_callback_activate_later_nolock_ (struct event_base *base, struct event_callback *evcb)
int event_callback_cancel_nolock_ (struct event_base *base, struct event_callback *evcb, int even_if_finalizing)
void event_callback_init_ (struct event_base *base, struct event_callback *cb)
EVENT2_EXPORT_SYMBOL void event_base_add_virtual_ (struct event_base *base)
void event_base_del_virtual_ (struct event_base *base)
EVENT2_EXPORT_SYMBOL void event_base_assert_ok_ (struct event_base *base)
void event_base_assert_ok_nolock_ (struct event_base *base)
int event_base_foreach_event_nolock_ (struct event_base *base, event_base_foreach_event_cb cb, void *arg)
void event_disable_debug_mode (void)
Variables
int event_debug_mode_on_
Macro Definition Documentation
COMMON_TIMEOUT_MICROSECONDS_MASK
#define COMMON_TIMEOUT_MICROSECONDS_MASK 0x000fffff
Mask used to get the real tv_usec value from a common timeout.
Definition at line 177 of file event-internal.h.
ev_arg
#define ev_arg ev_evcallback.evcb_arg
Definition at line 60 of file event-internal.h.
ev_callback
#define ev_callback ev_evcallback.evcb_cb_union.evcb_callback
Definition at line 59 of file event-internal.h.
ev_closure
#define ev_closure ev_evcallback.evcb_closure
Definition at line 58 of file event-internal.h.
EV_CLOSURE_CB_FINALIZE
#define EV_CLOSURE_CB_FINALIZE 4
A finalizing callback. Uses the evcb_cbfinalize callback.
Definition at line 77 of file event-internal.h.
EV_CLOSURE_CB_SELF
#define EV_CLOSURE_CB_SELF 3
A simple callback. Uses the evcb_selfcb callback.
Definition at line 75 of file event-internal.h.
EV_CLOSURE_EVENT
#define EV_CLOSURE_EVENT 0
A regular event. Uses the evcb_callback callback
Definition at line 69 of file event-internal.h.
EV_CLOSURE_EVENT_FINALIZE
#define EV_CLOSURE_EVENT_FINALIZE 5
A finalizing event. Uses the evcb_evfinalize callback.
Definition at line 79 of file event-internal.h.
EV_CLOSURE_EVENT_FINALIZE_FREE
#define EV_CLOSURE_EVENT_FINALIZE_FREE 6
A finalizing event that should get freed after. Uses the evcb_evfinalize callback.
Definition at line 82 of file event-internal.h.
EV_CLOSURE_EVENT_PERSIST
#define EV_CLOSURE_EVENT_PERSIST 2
A persistent non-signal event. Uses the evcb_callback callback
Definition at line 73 of file event-internal.h.
EV_CLOSURE_EVENT_SIGNAL
#define EV_CLOSURE_EVENT_SIGNAL 1
A signal event. Uses the evcb_callback callback
Definition at line 71 of file event-internal.h.
ev_flags
#define ev_flags ev_evcallback.evcb_flags
Definition at line 57 of file event-internal.h.
ev_io_next
#define ev_io_next ev_.ev_io.ev_io_next
Definition at line 49 of file event-internal.h.
ev_io_timeout
#define ev_io_timeout ev_.ev_io.ev_timeout
Definition at line 50 of file event-internal.h.
ev_ncalls
#define ev_ncalls ev_.ev_signal.ev_ncalls
Definition at line 53 of file event-internal.h.
ev_pncalls
#define ev_pncalls ev_.ev_signal.ev_pncalls
Definition at line 54 of file event-internal.h.
ev_pri
#define ev_pri ev_evcallback.evcb_pri
Definition at line 56 of file event-internal.h.
ev_signal_next
#define ev_signal_next ev_.ev_signal.ev_signal_next
Definition at line 48 of file event-internal.h.
EVENT_DEBUG_MODE_IS_ON
#define EVENT_DEBUG_MODE_IS_ON () (event_debug_mode_on_)
Definition at line 192 of file event-internal.h.
EVENT_DEL_AUTOBLOCK
#define EVENT_DEL_AUTOBLOCK 2
Argument for event_del_nolock_. Tells event_del to block on the event if it is running in another thread and it doesn't have EV_FINALIZE set.
Definition at line 420 of file event-internal.h.
EVENT_DEL_BLOCK
#define EVENT_DEL_BLOCK 1
Argument for event_del_nolock_. Tells event_del to block on the event if it's running in another thread, regardless of its value for EV_FINALIZE
Definition at line 416 of file event-internal.h.
EVENT_DEL_EVEN_IF_FINALIZING
#define EVENT_DEL_EVEN_IF_FINALIZING 3
Argument for event_del_nolock_. Tells event_del to proceed even if the event is set up for finalization rather for regular use.
Definition at line 423 of file event-internal.h.
EVENT_DEL_NOBLOCK
#define EVENT_DEL_NOBLOCK 0
Argument for event_del_nolock_. Tells event_del not to block on the event if it's running in another thread.
Definition at line 412 of file event-internal.h.
event_io_map
#define event_io_map event_signal_map
Definition at line 144 of file event-internal.h.
LIST_END
#define LIST_END (head) NULL
Definition at line 372 of file event-internal.h.
N_ACTIVE_CALLBACKS
#define N_ACTIVE_CALLBACKS (base) ((base)->event_count_active)
Definition at line 401 of file event-internal.h.
TAILQ_END
#define TAILQ_END (head) NULL
Definition at line 379 of file event-internal.h.
TAILQ_FIRST
#define TAILQ_FIRST (head) ((head)->tqh_first)
Definition at line 376 of file event-internal.h.
TAILQ_FOREACH
#define TAILQ_FOREACH (var, head, field)
Value:
    for ((var) = TAILQ_FIRST(head);                 \
         (var) != TAILQ_END(head);                  \
         (var) = TAILQ_NEXT(var, field))
Definition at line 386 of file event-internal.h.
TAILQ_INSERT_BEFORE
#define TAILQ_INSERT_BEFORE (listelm, elm, field)
Value:
    do {            \
    (elm)->field.tqe_prev = (listelm)->field.tqe_prev;      \
    (elm)->field.tqe_next = (listelm);              \
    *(listelm)->field.tqe_prev = (elm);             \
    (listelm)->field.tqe_prev = &(elm)->field.tqe_next;     \
} while (0)
Definition at line 393 of file event-internal.h.
TAILQ_NEXT
#define TAILQ_NEXT (elm, field) ((elm)->field.tqe_next)
Definition at line 382 of file event-internal.h.
Function Documentation
event_active_later_()
EVENT2_EXPORT_SYMBOL void event_active_later_ (struct event * ev, int res)
Definition at line 2970 of file event.c.
{
    EVBASE_ACQUIRE_LOCK(ev->ev_base, th_base_lock);
    event_active_later_nolock_(ev, res);
    EVBASE_RELEASE_LOCK(ev->ev_base, th_base_lock);
}
References EVBASE_ACQUIRE_LOCK, EVBASE_RELEASE_LOCK, event_active_later_nolock_(), and event_base::th_base_lock.
event_active_later_nolock_()
void event_active_later_nolock_ (struct event * ev, int res)
Definition at line 2978 of file event.c.
{
    struct event_base *base = ev->ev_base;
    EVENT_BASE_ASSERT_LOCKED(base);
    if (ev->ev_flags & (EVLIST_ACTIVE|EVLIST_ACTIVE_LATER)) {
        /* We get different kinds of events, add them together */
        ev->ev_res |= res;
        return;
    }
    ev->ev_res = res;
    event_callback_activate_later_nolock_(base, event_to_event_callback(ev));
}
References EVENT_BASE_ASSERT_LOCKED, event_callback_activate_later_nolock_(), and event_to_event_callback().
Referenced by event_active_later_().
event_active_nolock_()
void event_active_nolock_ (struct event * ev, int res, short count)
Definition at line 2919 of file event.c.
{
    struct event_base *base;
    event_debug(("event_active: %p (fd "EV_SOCK_FMT"), res %d, callback %p",
        ev, EV_SOCK_ARG(ev->ev_fd), (int)res, ev->ev_callback));
    base = ev->ev_base;
    EVENT_BASE_ASSERT_LOCKED(base);
    if (ev->ev_flags & EVLIST_FINALIZING) {
        /* XXXX debug */
        return;
    }
    switch ((ev->ev_flags & (EVLIST_ACTIVE|EVLIST_ACTIVE_LATER))) {
    default:
    case EVLIST_ACTIVE|EVLIST_ACTIVE_LATER:
        EVUTIL_ASSERT(0);
        break;
    case EVLIST_ACTIVE:
        /* We get different kinds of events, add them together */
        ev->ev_res |= res;
        return;
    case EVLIST_ACTIVE_LATER:
        ev->ev_res |= res;
        break;
    case 0:
        ev->ev_res = res;
        break;
    }
    if (ev->ev_pri < base->event_running_priority)
        base->event_continue = 1;
    if (ev->ev_events & EV_SIGNAL) {
#ifndef EVENT__DISABLE_THREAD_SUPPORT
        if (base->current_event == event_to_event_callback(ev) &&
            !EVBASE_IN_THREAD(base)) {
            ++base->current_event_waiters;
            EVTHREAD_COND_WAIT(base->current_event_cond, base->th_base_lock);
        }
#endif
        ev->ev_ncalls = ncalls;
        ev->ev_pncalls = NULL;
    }
    event_callback_activate_nolock_(base, event_to_event_callback(ev));
}
References event_base::current_event, event_base::current_event_cond, event_base::current_event_waiters, EV_SOCK_ARG, EV_SOCK_FMT, EVBASE_IN_THREAD, EVENT_BASE_ASSERT_LOCKED, event_callback_activate_nolock_(), event_base::event_continue, event_debug, event_base::event_running_priority, event_to_event_callback(), EVTHREAD_COND_WAIT, EVUTIL_ASSERT, and event_base::th_base_lock.
Referenced by common_timeout_callback(), event_active(), event_base_active_by_fd(), event_base_once(), event_finalize_nolock_(), evmap_io_active_(), evmap_signal_active_(), and timeout_process().
event_add_nolock_()
int event_add_nolock_ (struct event * ev, const struct timeval * tv, int tv_is_absolute)
Definition at line 2597 of file event.c.
{
    struct event_base *base = ev->ev_base;
    int res = 0;
    int notify = 0;
    EVENT_BASE_ASSERT_LOCKED(base);
    event_debug_assert_is_setup_(ev);
    event_debug((
         "event_add: event: %p (fd "EV_SOCK_FMT"), %s%s%s%scall %p",
         ev,
         EV_SOCK_ARG(ev->ev_fd),
         ev->ev_events & EV_READ ? "EV_READ " : " ",
         ev->ev_events & EV_WRITE ? "EV_WRITE " : " ",
         ev->ev_events & EV_CLOSED ? "EV_CLOSED " : " ",
         tv ? "EV_TIMEOUT " : " ",
         ev->ev_callback));
    EVUTIL_ASSERT(!(ev->ev_flags & ~EVLIST_ALL));
    if (ev->ev_flags & EVLIST_FINALIZING) {
        /* XXXX debug */
        return (-1);
    }
    /*
     * prepare for timeout insertion further below, if we get a
     * failure on any step, we should not change any state.
     */
    if (tv != NULL && !(ev->ev_flags & EVLIST_TIMEOUT)) {
        if (min_heap_reserve_(&base->timeheap,
            1 + min_heap_size_(&base->timeheap)) == -1)
            return (-1);  /* ENOMEM == errno */
    }
    /* If the main thread is currently executing a signal event's
     * callback, and we are not the main thread, then we want to wait
     * until the callback is done before we mess with the event, or else
     * we can race on ev_ncalls and ev_pncalls below. */
#ifndef EVENT__DISABLE_THREAD_SUPPORT
    if (base->current_event == event_to_event_callback(ev) &&
        (ev->ev_events & EV_SIGNAL)
        && !EVBASE_IN_THREAD(base)) {
        ++base->current_event_waiters;
        EVTHREAD_COND_WAIT(base->current_event_cond, base->th_base_lock);
    }
#endif
    if ((ev->ev_events & (EV_READ|EV_WRITE|EV_CLOSED|EV_SIGNAL)) &&
        !(ev->ev_flags & (EVLIST_INSERTED|EVLIST_ACTIVE|EVLIST_ACTIVE_LATER))) {
        if (ev->ev_events & (EV_READ|EV_WRITE|EV_CLOSED))
            res = evmap_io_add_(base, ev->ev_fd, ev);
        else if (ev->ev_events & EV_SIGNAL)
            res = evmap_signal_add_(base, (int)ev->ev_fd, ev);
        if (res != -1)
            event_queue_insert_inserted(base, ev);
        if (res == 1) {
            /* evmap says we need to notify the main thread. */
            notify = 1;
            res = 0;
        }
    }
    /*
     * we should change the timeout state only if the previous event
     * addition succeeded.
     */
    if (res != -1 && tv != NULL) {
        struct timeval now;
        int common_timeout;
#ifdef USE_REINSERT_TIMEOUT
        int was_common;
        int old_timeout_idx;
#endif
        /*
         * for persistent timeout events, we remember the
         * timeout value and re-add the event.
         *
         * If tv_is_absolute, this was already set.
         */
        if (ev->ev_closure == EV_CLOSURE_EVENT_PERSIST && !tv_is_absolute)
            ev->ev_io_timeout = *tv;
#ifndef USE_REINSERT_TIMEOUT
        if (ev->ev_flags & EVLIST_TIMEOUT) {
            event_queue_remove_timeout(base, ev);
        }
#endif
        /* Check if it is active due to a timeout.  Rescheduling
         * this timeout before the callback can be executed
         * removes it from the active list. */
        if ((ev->ev_flags & EVLIST_ACTIVE) &&
            (ev->ev_res & EV_TIMEOUT)) {
            if (ev->ev_events & EV_SIGNAL) {
                /* See if we are just active executing
                 * this event in a loop
                 */
                if (ev->ev_ncalls && ev->ev_pncalls) {
                    /* Abort loop */
                    *ev->ev_pncalls = 0;
                }
            }
            event_queue_remove_active(base, event_to_event_callback(ev));
        }
        gettime(base, &now);
        common_timeout = is_common_timeout(tv, base);
#ifdef USE_REINSERT_TIMEOUT
        was_common = is_common_timeout(&ev->ev_timeout, base);
        old_timeout_idx = COMMON_TIMEOUT_IDX(&ev->ev_timeout);
#endif
        if (tv_is_absolute) {
            ev->ev_timeout = *tv;
        } else if (common_timeout) {
            struct timeval tmp = *tv;
            tmp.tv_usec &= MICROSECONDS_MASK;
            evutil_timeradd(&now, &tmp, &ev->ev_timeout);
            ev->ev_timeout.tv_usec |=
                (tv->tv_usec & ~MICROSECONDS_MASK);
        } else {
            evutil_timeradd(&now, tv, &ev->ev_timeout);
        }
        event_debug((
             "event_add: event %p, timeout in %d seconds %d useconds, call %p",
             ev, (int)tv->tv_sec, (int)tv->tv_usec, ev->ev_callback));
#ifdef USE_REINSERT_TIMEOUT
        event_queue_reinsert_timeout(base, ev, was_common, common_timeout, old_timeout_idx);
#else
        event_queue_insert_timeout(base, ev);
#endif
        if (common_timeout) {
            struct common_timeout_list *ctl =
                get_common_timeout_list(base, &ev->ev_timeout);
            if (ev == TAILQ_FIRST(&ctl->events)) {
                common_timeout_schedule(ctl, &now, ev);
            }
        } else {
            struct event* top = NULL;
            /* See if the earliest timeout is now earlier than it
             * was before: if so, we will need to tell the main
             * thread to wake up earlier than it would otherwise.
             * We double check the timeout of the top element to
             * handle time distortions due to system suspension.
             */
            if (min_heap_elt_is_top_(ev))
                notify = 1;
            else if ((top = min_heap_top_(&base->timeheap)) != NULL &&
                     evutil_timercmp(&top->ev_timeout, &now, <))
                notify = 1;
        }
    }
    /* if we are not in the right thread, we need to wake up the loop */
    if (res != -1 && notify && EVBASE_NEED_NOTIFY(base))
        evthread_notify_base(base);
    event_debug_note_add_(ev);
    return (res);
}
References common_timeout_list::base, COMMON_TIMEOUT_IDX, common_timeout_schedule(), event_base::current_event, event_base::current_event_cond, event_base::current_event_waiters, EV_CLOSURE_EVENT_PERSIST, EV_SOCK_ARG, EV_SOCK_FMT, EVBASE_IN_THREAD, EVBASE_NEED_NOTIFY, EVENT_BASE_ASSERT_LOCKED, event_debug, event_debug_assert_is_setup_(), event_debug_note_add_(), event_queue_insert_inserted(), event_queue_insert_timeout(), event_queue_remove_active(), event_queue_remove_timeout(), event_to_event_callback(), common_timeout_list::events, evmap_io_add_(), evmap_signal_add_(), EVTHREAD_COND_WAIT, evthread_notify_base(), EVUTIL_ASSERT, get_common_timeout_list(), gettime(), is_common_timeout(), MICROSECONDS_MASK, min_heap_elt_is_top_(), min_heap_reserve_(), min_heap_size_(), min_heap_top_(), TAILQ_FIRST, event_base::th_base_lock, and event_base::timeheap.
Referenced by common_timeout_schedule(), event_add(), event_base_once(), event_persist_closure(), event_reinit(), evsig_add(), and evthread_make_base_notifiable_nolock_().
event_base_add_virtual_()
EVENT2_EXPORT_SYMBOL void event_base_add_virtual_ (struct event_base * base)
Definition at line 3871 of file event.c.
{
    EVBASE_ACQUIRE_LOCK(base, th_base_lock);
    base->virtual_event_count++;
    MAX_EVENT_COUNT(base->virtual_event_count_max, base->virtual_event_count);
    EVBASE_RELEASE_LOCK(base, th_base_lock);
}
References common_timeout_list::base, EVBASE_ACQUIRE_LOCK, EVBASE_RELEASE_LOCK, MAX_EVENT_COUNT, event_base::virtual_event_count, and event_base::virtual_event_count_max.
Referenced by bev_async_add_read(), bev_async_add_write(), and bufferevent_async_connect_().
event_base_assert_ok_()
EVENT2_EXPORT_SYMBOL void event_base_assert_ok_ (struct event_base * base)
For debugging: unless assertions are disabled, verify the referential integrity of the internal data structures of 'base'. This operation can be expensive.
Returns on success; aborts on failure.
Definition at line 3956 of file event.c.
{
    EVBASE_ACQUIRE_LOCK(base, th_base_lock);
    event_base_assert_ok_nolock_(base);
    EVBASE_RELEASE_LOCK(base, th_base_lock);
}
References common_timeout_list::base, EVBASE_ACQUIRE_LOCK, EVBASE_RELEASE_LOCK, and event_base_assert_ok_nolock_().
event_base_assert_ok_nolock_()
void event_base_assert_ok_nolock_ (struct event_base * base)
Definition at line 3964 of file event.c.
{
    int i;
    int count;
    /* First do checks on the per-fd and per-signal lists */
    evmap_check_integrity_(base);
    /* Check the heap property */
    for (i = 1; i < (int)base->timeheap.n; ++i) {
        int parent = (i - 1) / 2;
        struct event *ev, *p_ev;
        ev = base->timeheap.p[i];
        p_ev = base->timeheap.p[parent];
        EVUTIL_ASSERT(ev->ev_flags & EVLIST_TIMEOUT);
        EVUTIL_ASSERT(evutil_timercmp(&p_ev->ev_timeout, &ev->ev_timeout, <=));
        EVUTIL_ASSERT(ev->ev_timeout_pos.min_heap_idx == i);
    }
    /* Check that the common timeouts are fine */
    for (i = 0; i < base->n_common_timeouts; ++i) {
        struct common_timeout_list *ctl = base->common_timeout_queues[i];
        struct event *last=NULL, *ev;
        EVUTIL_ASSERT_TAILQ_OK(&ctl->events, event, ev_timeout_pos.ev_next_with_common_timeout);
        TAILQ_FOREACH(ev, &ctl->events, ev_timeout_pos.ev_next_with_common_timeout) {
            if (last)
                EVUTIL_ASSERT(evutil_timercmp(&last->ev_timeout, &ev->ev_timeout, <=));
            EVUTIL_ASSERT(ev->ev_flags & EVLIST_TIMEOUT);
            EVUTIL_ASSERT(is_common_timeout(&ev->ev_timeout,base));
            EVUTIL_ASSERT(COMMON_TIMEOUT_IDX(&ev->ev_timeout) == i);
            last = ev;
        }
    }
    /* Check the active queues. */
    count = 0;
    for (i = 0; i < base->nactivequeues; ++i) {
        struct event_callback *evcb;
        EVUTIL_ASSERT_TAILQ_OK(&base->activequeues[i], event_callback, evcb_active_next);
        TAILQ_FOREACH(evcb, &base->activequeues[i], evcb_active_next) {
            EVUTIL_ASSERT((evcb->evcb_flags & (EVLIST_ACTIVE|EVLIST_ACTIVE_LATER)) == EVLIST_ACTIVE);
            EVUTIL_ASSERT(evcb->evcb_pri == i);
            ++count;
        }
    }
    {
        struct event_callback *evcb;
        TAILQ_FOREACH(evcb, &base->active_later_queue, evcb_active_next) {
            EVUTIL_ASSERT((evcb->evcb_flags & (EVLIST_ACTIVE|EVLIST_ACTIVE_LATER)) == EVLIST_ACTIVE_LATER);
            ++count;
        }
    }
    EVUTIL_ASSERT(count == base->event_count_active);
}
References event_base::active_later_queue, event_base::activequeues, common_timeout_list::base, COMMON_TIMEOUT_IDX, event_base::common_timeout_queues, count, event_base::event_count_active, common_timeout_list::events, evmap_check_integrity_(), EVUTIL_ASSERT, EVUTIL_ASSERT_TAILQ_OK, is_common_timeout(), min_heap::n, event_base::n_common_timeouts, event_base::nactivequeues, min_heap::p, TAILQ_FOREACH, and event_base::timeheap.
Referenced by event_base_assert_ok_().
event_base_del_virtual_()
void event_base_del_virtual_ (struct event_base * base)
Definition at line 3880 of file event.c.
{
    EVBASE_ACQUIRE_LOCK(base, th_base_lock);
    EVUTIL_ASSERT(base->virtual_event_count > 0);
    base->virtual_event_count--;
    if (base->virtual_event_count == 0 && EVBASE_NEED_NOTIFY(base))
        evthread_notify_base(base);
    EVBASE_RELEASE_LOCK(base, th_base_lock);
}
References common_timeout_list::base, EVBASE_ACQUIRE_LOCK, EVBASE_NEED_NOTIFY, EVBASE_RELEASE_LOCK, evthread_notify_base(), EVUTIL_ASSERT, and event_base::virtual_event_count.
Referenced by bev_async_del_read(), bev_async_del_write(), bufferevent_async_connect_(), and connect_complete().
event_base_foreach_event_nolock_()
int event_base_foreach_event_nolock_ (struct event_base * base, event_base_foreach_event_cb cb, void * arg)
Definition at line 3680 of file event.c.
{
    int r, i;
    unsigned u;
    struct event *ev;
    /* Start out with all the EVLIST_INSERTED events. */
    if ((r = evmap_foreach_event_(base, fn, arg)))
        return r;
    /* Okay, now we deal with those events that have timeouts and are in
     * the min-heap. */
    for (u = 0; u < base->timeheap.n; ++u) {
        ev = base->timeheap.p[u];
        if (ev->ev_flags & EVLIST_INSERTED) {
            /* we already processed this one */
            continue;
        }
        if ((r = fn(base, ev, arg)))
            return r;
    }
    /* Now for the events in one of the timeout queues.
     * the min-heap. */
    for (i = 0; i < base->n_common_timeouts; ++i) {
        struct common_timeout_list *ctl =
            base->common_timeout_queues[i];
        TAILQ_FOREACH(ev, &ctl->events,
            ev_timeout_pos.ev_next_with_common_timeout) {
            if (ev->ev_flags & EVLIST_INSERTED) {
                /* we already processed this one */
                continue;
            }
            if ((r = fn(base, ev, arg)))
                return r;
        }
    }
    /* Finally, we deal wit all the active events that we haven't touched
     * yet. */
    for (i = 0; i < base->nactivequeues; ++i) {
        struct event_callback *evcb;
        TAILQ_FOREACH(evcb, &base->activequeues[i], evcb_active_next) {
            if ((evcb->evcb_flags & (EVLIST_INIT|EVLIST_INSERTED|EVLIST_TIMEOUT)) != EVLIST_INIT) {
                /* This isn't an event (evlist_init clear), or
                 * we already processed it. (inserted or
                 * timeout set */
                continue;
            }
            ev = event_callback_to_event(evcb);
            if ((r = fn(base, ev, arg)))
                return r;
        }
    }
    return 0;
}
References event_base::activequeues, common_timeout_list::base, event_base::common_timeout_queues, event_callback_to_event(), common_timeout_list::events, evmap_foreach_event_(), min_heap::n, event_base::n_common_timeouts, event_base::nactivequeues, min_heap::p, TAILQ_FOREACH, and event_base::timeheap.
Referenced by event_base_dump_events(), and event_base_foreach_event().
event_callback_activate_()
EVENT2_EXPORT_SYMBOL int event_callback_activate_ (struct event_base * base, struct event_callback * evcb)
Definition at line 2995 of file event.c.
{
    int r;
    EVBASE_ACQUIRE_LOCK(base, th_base_lock);
    r = event_callback_activate_nolock_(base, evcb);
    EVBASE_RELEASE_LOCK(base, th_base_lock);
    return r;
}
References EVBASE_ACQUIRE_LOCK, EVBASE_RELEASE_LOCK, event_callback_activate_nolock_(), and event_base::th_base_lock.
event_callback_activate_later_nolock_()
int event_callback_activate_later_nolock_ (struct event_base * base, struct event_callback * evcb)
Definition at line 3037 of file event.c.
{
    if (evcb->evcb_flags & (EVLIST_ACTIVE|EVLIST_ACTIVE_LATER))
        return 0;
    event_queue_insert_active_later(base, evcb);
    if (EVBASE_NEED_NOTIFY(base))
        evthread_notify_base(base);
    return 1;
}
References EVBASE_NEED_NOTIFY, event_queue_insert_active_later(), and evthread_notify_base().
Referenced by event_active_later_nolock_(), and event_deferred_cb_schedule_().
event_callback_activate_nolock_()
int event_callback_activate_nolock_ (struct event_base * base, struct event_callback * evcb)
Definition at line 3006 of file event.c.
{
    int r = 1;
    if (evcb->evcb_flags & EVLIST_FINALIZING)
        return 0;
    switch (evcb->evcb_flags & (EVLIST_ACTIVE|EVLIST_ACTIVE_LATER)) {
    default:
        EVUTIL_ASSERT(0);
        EVUTIL_FALLTHROUGH;
    case EVLIST_ACTIVE_LATER:
        event_queue_remove_active_later(base, evcb);
        r = 0;
        break;
    case EVLIST_ACTIVE:
        return 0;
    case 0:
        break;
    }
    event_queue_insert_active(base, evcb);
    if (EVBASE_NEED_NOTIFY(base))
        evthread_notify_base(base);
    return r;
}
References EVBASE_NEED_NOTIFY, event_queue_insert_active(), event_queue_remove_active_later(), evthread_notify_base(), EVUTIL_ASSERT, and EVUTIL_FALLTHROUGH.
Referenced by event_active_nolock_(), event_callback_activate_(), event_callback_finalize_nolock_(), and event_deferred_cb_schedule_().
event_callback_cancel_()
int event_callback_cancel_ (struct event_base * base, struct event_callback * evcb)
Definition at line 3058 of file event.c.
{
    int r;
    EVBASE_ACQUIRE_LOCK(base, th_base_lock);
    r = event_callback_cancel_nolock_(base, evcb, 0);
    EVBASE_RELEASE_LOCK(base, th_base_lock);
    return r;
}
References EVBASE_ACQUIRE_LOCK, EVBASE_RELEASE_LOCK, event_callback_cancel_nolock_(), and event_base::th_base_lock.
Referenced by event_deferred_cb_cancel_().
event_callback_cancel_nolock_()
int event_callback_cancel_nolock_ (struct event_base * base, struct event_callback * evcb, int even_if_finalizing)
Definition at line 3069 of file event.c.
{
    if ((evcb->evcb_flags & EVLIST_FINALIZING) && !even_if_finalizing)
        return 0;
    if (evcb->evcb_flags & EVLIST_INIT)
        return event_del_nolock_(event_callback_to_event(evcb),
            even_if_finalizing ? EVENT_DEL_EVEN_IF_FINALIZING : EVENT_DEL_AUTOBLOCK);
    switch ((evcb->evcb_flags & (EVLIST_ACTIVE|EVLIST_ACTIVE_LATER))) {
    default:
    case EVLIST_ACTIVE|EVLIST_ACTIVE_LATER:
        EVUTIL_ASSERT(0);
        break;
    case EVLIST_ACTIVE:
        /* We get different kinds of events, add them together */
        event_queue_remove_active(base, evcb);
        return 0;
    case EVLIST_ACTIVE_LATER:
        event_queue_remove_active_later(base, evcb);
        break;
    case 0:
        break;
    }
    return 0;
}
References event_callback_to_event(), EVENT_DEL_AUTOBLOCK, EVENT_DEL_EVEN_IF_FINALIZING, event_del_nolock_(), event_queue_remove_active(), event_queue_remove_active_later(), and EVUTIL_ASSERT.
Referenced by event_base_cancel_single_callback_(), event_callback_cancel_(), event_callback_finalize_many_(), and event_callback_finalize_nolock_().
event_callback_finalize_()
EVENT2_EXPORT_SYMBOL void event_callback_finalize_ (struct event_base * base, unsigned flags, struct event_callback * evcb, void(*)(struct event_callback *, void *) cb)
Definition at line 2306 of file event.c.
{
    EVBASE_ACQUIRE_LOCK(base, th_base_lock);
    event_callback_finalize_nolock_(base, flags, evcb, cb);
    EVBASE_RELEASE_LOCK(base, th_base_lock);
}
References EVBASE_ACQUIRE_LOCK, EVBASE_RELEASE_LOCK, and event_callback_finalize_nolock_().
event_callback_finalize_many_()
int event_callback_finalize_many_ (struct event_base * base, int n_cbs, struct event_callback ** evcbs, void(*)(struct event_callback *, void *) cb)
Internal: Finalize all of the n_cbs callbacks in evcbs. The provided callback will be invoked on one of them, after they have all been finalized.
Definition at line 2317 of file event.c.
{
    int n_pending = 0, i;
    if (base == NULL)
        base = current_base;
    EVBASE_ACQUIRE_LOCK(base, th_base_lock);
    event_debug(("%s: %d events finalizing", __func__, n_cbs));
    /* At most one can be currently executing; the rest we just
     * cancel... But we always make sure that the finalize callback
     * runs. */
    for (i = 0; i < n_cbs; ++i) {
        struct event_callback *evcb = evcbs[i];
        if (evcb == base->current_event) {
            event_callback_finalize_nolock_(base, 0, evcb, cb);
            ++n_pending;
        } else {
            event_callback_cancel_nolock_(base, evcb, 0);
        }
    }
    if (n_pending == 0) {
        /* Just do the first one. */
        event_callback_finalize_nolock_(base, 0, evcbs[0], cb);
    }
    EVBASE_RELEASE_LOCK(base, th_base_lock);
    return 0;
}
References __func__, current_base, event_base::current_event, EVBASE_ACQUIRE_LOCK, EVBASE_RELEASE_LOCK, event_callback_cancel_nolock_(), event_callback_finalize_nolock_(), and event_debug.
Referenced by bufferevent_decref_and_unlock_().
event_callback_finalize_nolock_()
void event_callback_finalize_nolock_ (struct event_base * base, unsigned flags, struct event_callback * evcb, void(*)(struct event_callback *, void *) cb)
Definition at line 2289 of file event.c.
{
    struct event *ev = NULL;
    if (evcb->evcb_flags & EVLIST_INIT) {
        ev = event_callback_to_event(evcb);
        event_del_nolock_(ev, EVENT_DEL_NOBLOCK);
    } else {
        event_callback_cancel_nolock_(base, evcb, 0); /*XXX can this fail?*/
    }
    evcb->evcb_closure = EV_CLOSURE_CB_FINALIZE;
    evcb->evcb_cb_union.evcb_cbfinalize = cb;
    event_callback_activate_nolock_(base, evcb); /* XXX can this really fail?*/
    evcb->evcb_flags |= EVLIST_FINALIZING;
}
References EV_CLOSURE_CB_FINALIZE, event_callback_activate_nolock_(), event_callback_cancel_nolock_(), event_callback_to_event(), EVENT_DEL_NOBLOCK, and event_del_nolock_().
Referenced by event_callback_finalize_(), and event_callback_finalize_many_().
event_callback_init_()
void event_callback_init_ (struct event_base * base, struct event_callback * cb)
Definition at line 3050 of file event.c.
{
    memset(cb, 0, sizeof(*cb));
    cb->evcb_pri = base->nactivequeues - 1;
}
References event_base::nactivequeues.
event_del_nolock_()
int event_del_nolock_ (struct event * ev, int blocking)
Helper for event_del: always called with th_base_lock held.
"blocking" must be one of the EVENT_DEL_{BLOCK, NOBLOCK, AUTOBLOCK, EVEN_IF_FINALIZING} values. See those for more information.
Definition at line 2810 of file event.c.
{
    struct event_base *base;
    int res = 0, notify = 0;
    event_debug(("event_del: %p (fd "EV_SOCK_FMT"), callback %p",
        ev, EV_SOCK_ARG(ev->ev_fd), ev->ev_callback));
    /* An event without a base has not been added */
    if (ev->ev_base == NULL)
        return (-1);
    EVENT_BASE_ASSERT_LOCKED(ev->ev_base);
    if (blocking != EVENT_DEL_EVEN_IF_FINALIZING) {
        if (ev->ev_flags & EVLIST_FINALIZING) {
            /* XXXX Debug */
            return 0;
        }
    }
    base = ev->ev_base;
    EVUTIL_ASSERT(!(ev->ev_flags & ~EVLIST_ALL));
    /* See if we are just active executing this event in a loop */
    if (ev->ev_events & EV_SIGNAL) {
        if (ev->ev_ncalls && ev->ev_pncalls) {
            /* Abort loop */
            *ev->ev_pncalls = 0;
        }
    }
    if (ev->ev_flags & EVLIST_TIMEOUT) {
        /* NOTE: We never need to notify the main thread because of a
         * deleted timeout event: all that could happen if we don't is
         * that the dispatch loop might wake up too early.  But the
         * point of notifying the main thread _is_ to wake up the
         * dispatch loop early anyway, so we wouldn't gain anything by
         * doing it.
         */
        event_queue_remove_timeout(base, ev);
    }
    if (ev->ev_flags & EVLIST_ACTIVE)
        event_queue_remove_active(base, event_to_event_callback(ev));
    else if (ev->ev_flags & EVLIST_ACTIVE_LATER)
        event_queue_remove_active_later(base, event_to_event_callback(ev));
    if (ev->ev_flags & EVLIST_INSERTED) {
        event_queue_remove_inserted(base, ev);
        if (ev->ev_events & (EV_READ|EV_WRITE|EV_CLOSED))
            res = evmap_io_del_(base, ev->ev_fd, ev);
        else
            res = evmap_signal_del_(base, (int)ev->ev_fd, ev);
        if (res == 1) {
            /* evmap says we need to notify the main thread. */
            notify = 1;
            res = 0;
        }
        /* If we do not have events, let's notify event base so it can
         * exit without waiting */
        if (!event_haveevents(base) && !N_ACTIVE_CALLBACKS(base))
            notify = 1;
    }
    /* if we are not in the right thread, we need to wake up the loop */
    if (res != -1 && notify && EVBASE_NEED_NOTIFY(base))
        evthread_notify_base(base);
    event_debug_note_del_(ev);
    /* If the main thread is currently executing this event's callback,
     * and we are not the main thread, then we want to wait until the
     * callback is done before returning. That way, when this function
     * returns, it will be safe to free the user-supplied argument.
     */
#ifndef EVENT__DISABLE_THREAD_SUPPORT
    if (blocking != EVENT_DEL_NOBLOCK &&
        base->current_event == event_to_event_callback(ev) &&
        !EVBASE_IN_THREAD(base) &&
        (blocking == EVENT_DEL_BLOCK || !(ev->ev_events & EV_FINALIZE))) {
        ++base->current_event_waiters;
        EVTHREAD_COND_WAIT(base->current_event_cond, base->th_base_lock);
    }
#endif
    return (res);
}
References event_base::current_event, event_base::current_event_cond, event_base::current_event_waiters, EV_SOCK_ARG, EV_SOCK_FMT, EVBASE_IN_THREAD, EVBASE_NEED_NOTIFY, EVENT_BASE_ASSERT_LOCKED, event_debug, event_debug_note_del_(), EVENT_DEL_BLOCK, EVENT_DEL_EVEN_IF_FINALIZING, EVENT_DEL_NOBLOCK, event_haveevents(), event_queue_remove_active(), event_queue_remove_active_later(), event_queue_remove_inserted(), event_queue_remove_timeout(), event_to_event_callback(), evmap_io_del_(), evmap_signal_del_(), EVTHREAD_COND_WAIT, evthread_notify_base(), EVUTIL_ASSERT, N_ACTIVE_CALLBACKS, and event_base::th_base_lock.
Referenced by common_timeout_callback(), event_callback_cancel_nolock_(), event_callback_finalize_nolock_(), event_del_(), event_finalize_nolock_(), event_process_active_single_queue(), event_reinit(), and timeout_process().
event_disable_debug_mode()
void event_disable_debug_mode (void)
Definition at line 586 of file event.c.
{
#ifndef EVENT__DISABLE_DEBUG_MODE
    struct event_debug_entry **ent, *victim;
    EVLOCK_LOCK(event_debug_map_lock_, 0);
    for (ent = HT_START(event_debug_map, &global_debug_map); ent; ) {
        victim = *ent;
        ent = HT_NEXT_RMV(event_debug_map, &global_debug_map, ent);
        mm_free(victim);
    }
    HT_CLEAR(event_debug_map, &global_debug_map);
    EVLOCK_UNLOCK(event_debug_map_lock_ , 0);
    event_debug_mode_on_  = 0;
#endif
}
References event_debug_map_lock_, event_debug_mode_on_, EVLOCK_LOCK, EVLOCK_UNLOCK, HT_CLEAR, HT_NEXT_RMV, HT_START, and mm_free.
Referenced by libevent_global_shutdown().
event_remove_timer_nolock_()
int event_remove_timer_nolock_ (struct event * ev)
Definition at line 2555 of file event.c.
{
    struct event_base *base = ev->ev_base;
    EVENT_BASE_ASSERT_LOCKED(base);
    event_debug_assert_is_setup_(ev);
    event_debug(("event_remove_timer_nolock: event: %p", ev));
    /* If it's not pending on a timeout, we don't need to do anything. */
    if (ev->ev_flags & EVLIST_TIMEOUT) {
        event_queue_remove_timeout(base, ev);
        evutil_timerclear(&ev->ev_.ev_io.ev_timeout);
    }
    return (0);
}
References EVENT_BASE_ASSERT_LOCKED, event_debug, event_debug_assert_is_setup_(), and event_queue_remove_timeout().
Referenced by event_remove_timer().
evsig_restore_handler_()
int evsig_restore_handler_ (struct event_base * base, int evsignal)
Definition at line 326 of file signal.c.
{
    int ret = 0;
    struct evsig_info *sig = &base->sig;
#ifdef EVENT__HAVE_SIGACTION
    struct sigaction *sh;
#else
    ev_sighandler_t *sh;
#endif
    if (evsignal >= sig->sh_old_max) {
        /* Can't actually restore. */
        /* XXXX.*/
        return 0;
    }
    /* restore previous handler */
    sh = sig->sh_old[evsignal];
    sig->sh_old[evsignal] = NULL;
#ifdef EVENT__HAVE_SIGACTION
    if (sigaction(evsignal, sh, NULL) == -1) {
        event_warn("sigaction");
        ret = -1;
    }
#else
    if (signal(evsignal, *sh) == SIG_ERR) {
        event_warn("signal");
        ret = -1;
    }
#endif
    mm_free(sh);
    return ret;
}
References event_warn(), mm_free, evsig_info::sh_old, evsig_info::sh_old_max, and event_base::sig.
Referenced by evsig_dealloc_(), and evsig_del().
evsig_set_handler_()
int evsig_set_handler_ (struct event_base * base, int evsignal, void(*)(int) fn)
TAILQ_HEAD()
TAILQ_HEAD (evcallback_list , event_callback)
Variable Documentation
event_debug_mode_on_
int event_debug_mode_on_ extern
Definition at line 205 of file event.c.