libdogecoin: src/libevent/evmap.c File Reference
evmap.c File Reference
#include "event2/event-config.h"
#include "evconfig-private.h"
#include <sys/types.h>
#include <sys/queue.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <errno.h>
#include <limits.h>
#include <signal.h>
#include <string.h>
#include <time.h>
#include "event-internal.h"
#include "evmap-internal.h"
#include "mm-internal.h"
#include "changelist-internal.h"
Data Structures
struct evmap_io
struct evmap_signal
struct event_changelist_fdinfo
struct evmap_foreach_event_helper
Macros
#define GET_SIGNAL_SLOT(x, map, slot, type) (x) = (struct type *)((map)->entries[slot])
#define GET_SIGNAL_SLOT_AND_CTOR(x, map, slot, type, ctor, fdinfo_len)
#define GET_IO_SLOT(x, map, slot, type) GET_SIGNAL_SLOT(x,map,slot,type)
#define GET_IO_SLOT_AND_CTOR(x, map, slot, type, ctor, fdinfo_len) GET_SIGNAL_SLOT_AND_CTOR(x,map,slot,type,ctor,fdinfo_len)
#define FDINFO_OFFSET sizeof(struct evmap_io)
#define event_changelist_check(base) ((void)0)
Typedefs
typedef int(* evmap_io_foreach_fd_cb) (struct event_base *, evutil_socket_t, struct evmap_io *, void *)
typedef int(* evmap_signal_foreach_signal_cb) (struct event_base *, int, struct evmap_signal *, void *)
Functions
void evmap_io_initmap_ (struct event_io_map *ctx)
void evmap_io_clear_ (struct event_io_map *ctx)
static int evmap_make_space (struct event_signal_map *map, int slot, int msize)
void evmap_signal_initmap_ (struct event_signal_map *ctx)
void evmap_signal_clear_ (struct event_signal_map *ctx)
static void evmap_io_init (struct evmap_io *entry)
int evmap_io_add_ (struct event_base *base, evutil_socket_t fd, struct event *ev)
int evmap_io_del_ (struct event_base *base, evutil_socket_t fd, struct event *ev)
void evmap_io_active_ (struct event_base *base, evutil_socket_t fd, short events)
static void evmap_signal_init (struct evmap_signal *entry)
int evmap_signal_add_ (struct event_base *base, int sig, struct event *ev)
int evmap_signal_del_ (struct event_base *base, int sig, struct event *ev)
void evmap_signal_active_ (struct event_base *base, evutil_socket_t sig, int ncalls)
void * evmap_io_get_fdinfo_ (struct event_io_map *map, evutil_socket_t fd)
static int evmap_io_foreach_fd (struct event_base *base, evmap_io_foreach_fd_cb fn, void *arg)
static int evmap_signal_foreach_signal (struct event_base *base, evmap_signal_foreach_signal_cb fn, void *arg)
static int evmap_io_reinit_iter_fn (struct event_base *base, evutil_socket_t fd, struct evmap_io *ctx, void *arg)
static int evmap_signal_reinit_iter_fn (struct event_base *base, int signum, struct evmap_signal *ctx, void *arg)
int evmap_reinit_ (struct event_base *base)
static int delete_all_in_dlist (struct event_dlist *dlist)
static int evmap_io_delete_all_iter_fn (struct event_base *base, evutil_socket_t fd, struct evmap_io *io_info, void *arg)
static int evmap_signal_delete_all_iter_fn (struct event_base *base, int signum, struct evmap_signal *sig_info, void *arg)
void evmap_delete_all_ (struct event_base *base)
void event_changelist_init_ (struct event_changelist *changelist)
static struct event_changelist_fdinfo * event_change_get_fdinfo (struct event_base *base, const struct event_change *change)
static int event_changelist_assert_ok_foreach_iter_fn (struct event_base *base, evutil_socket_t fd, struct evmap_io *io, void *arg)
static void event_changelist_assert_ok (struct event_base *base)
void event_changelist_remove_all_ (struct event_changelist *changelist, struct event_base *base)
void event_changelist_freemem_ (struct event_changelist *changelist)
static int event_changelist_grow (struct event_changelist *changelist)
static struct event_change * event_changelist_get_or_construct (struct event_changelist *changelist, evutil_socket_t fd, short old_events, struct event_changelist_fdinfo *fdinfo)
int event_changelist_add_ (struct event_base *base, evutil_socket_t fd, short old, short events, void *p)
int event_changelist_del_ (struct event_base *base, evutil_socket_t fd, short old, short events, void *p)
static int evmap_io_check_integrity_fn (struct event_base *base, evutil_socket_t fd, struct evmap_io *io_info, void *arg)
static int evmap_signal_check_integrity_fn (struct event_base *base, int signum, struct evmap_signal *sig_info, void *arg)
void evmap_check_integrity_ (struct event_base *base)
static int evmap_io_foreach_event_fn (struct event_base *base, evutil_socket_t fd, struct evmap_io *io_info, void *arg)
static int evmap_signal_foreach_event_fn (struct event_base *base, int signum, struct evmap_signal *sig_info, void *arg)
int evmap_foreach_event_ (struct event_base *base, event_base_foreach_event_cb fn, void *arg)
Macro Definition Documentation
event_changelist_check
#define event_changelist_check (base) ((void)0)
Definition at line 775 of file evmap.c.
FDINFO_OFFSET
#define FDINFO_OFFSET sizeof(struct evmap_io)
Definition at line 187 of file evmap.c.
GET_IO_SLOT
#define GET_IO_SLOT (x, map, slot, type) GET_SIGNAL_SLOT(x,map,slot,type)
Definition at line 184 of file evmap.c.
GET_IO_SLOT_AND_CTOR
#define GET_IO_SLOT_AND_CTOR (x, map, slot, type, ctor, fdinfo_len) GET_SIGNAL_SLOT_AND_CTOR(x,map,slot,type,ctor,fdinfo_len)
Definition at line 185 of file evmap.c.
GET_SIGNAL_SLOT
#define GET_SIGNAL_SLOT (x, map, slot, type) (x) = (struct type *)((map)->entries[slot])
Definition at line 162 of file evmap.c.
GET_SIGNAL_SLOT_AND_CTOR
#define GET_SIGNAL_SLOT_AND_CTOR (x, map, slot, type, ctor, fdinfo_len)
Value:
    do {                                \
        if ((map)->entries[slot] == NULL) {         \
            (map)->entries[slot] =              \
                mm_calloc(1,sizeof(struct type)+fdinfo_len); \
            if (EVUTIL_UNLIKELY((map)->entries[slot] == NULL)) \
                return (-1);                \
            (ctor)((struct type *)(map)->entries[slot]);    \
        }                           \
        (x) = (struct type *)((map)->entries[slot]);        \
    } while (0)
Definition at line 169 of file evmap.c.
Typedef Documentation
evmap_io_foreach_fd_cb
typedef int(* evmap_io_foreach_fd_cb) (struct event_base *, evutil_socket_t, struct evmap_io *, void *)
Definition at line 529 of file evmap.c.
evmap_signal_foreach_signal_cb
typedef int(* evmap_signal_foreach_signal_cb) (struct event_base *, int, struct evmap_signal *, void *)
Definition at line 571 of file evmap.c.
Function Documentation
delete_all_in_dlist()
static int delete_all_in_dlist (struct event_dlist * dlist) static
Definition at line 668 of file evmap.c.
{
    struct event *ev;
    while ((ev = LIST_FIRST(dlist)))
        event_del(ev);
    return 0;
}
References event_del().
Referenced by evmap_io_delete_all_iter_fn(), and evmap_signal_delete_all_iter_fn().
event_change_get_fdinfo()
static struct event_changelist_fdinfo * event_change_get_fdinfo (struct event_base * base, const struct event_change * change) inline static
Helper: return the changelist_fdinfo corresponding to a given change.
Definition at line 717 of file evmap.c.
{
    char *ptr;
    if (change->read_change & EV_CHANGE_SIGNAL) {
        struct evmap_signal *ctx;
        GET_SIGNAL_SLOT(ctx, &base->sigmap, change->fd, evmap_signal);
        ptr = ((char*)ctx) + sizeof(struct evmap_signal);
    } else {
        struct evmap_io *ctx;
        GET_IO_SLOT(ctx, &base->io, change->fd, evmap_io);
        ptr = ((char*)ctx) + sizeof(struct evmap_io);
    }
    return (void*)ptr;
}
References ctx, EV_CHANGE_SIGNAL, event_change::fd, GET_IO_SLOT, GET_SIGNAL_SLOT, event_base::io, event_change::read_change, and event_base::sigmap.
Referenced by event_changelist_assert_ok(), and event_changelist_remove_all_().
event_changelist_add_()
int event_changelist_add_ (struct event_base * base, evutil_socket_t fd, short old, short events, void * p)
Implementation of eventop_add that queues the event in a changelist.
Definition at line 866 of file evmap.c.
{
    struct event_changelist *changelist = &base->changelist;
    struct event_changelist_fdinfo *fdinfo = p;
    struct event_change *change;
    ev_uint8_t evchange = EV_CHANGE_ADD | (events & (EV_ET|EV_PERSIST|EV_SIGNAL));
    event_changelist_check(base);
    change = event_changelist_get_or_construct(changelist, fd, old, fdinfo);
    if (!change)
        return -1;
    /* An add replaces any previous delete, but doesn't result in a no-op,
     * since the delete might fail (because the fd had been closed since
     * the last add, for instance. */
    if (events & (EV_READ|EV_SIGNAL))
        change->read_change = evchange;
    if (events & EV_WRITE)
        change->write_change = evchange;
    if (events & EV_CLOSED)
        change->close_change = evchange;
    event_changelist_check(base);
    return (0);
}
References event_base::changelist, event_change::close_change, EV_CHANGE_ADD, event_changelist_check, event_changelist_get_or_construct(), event_change::fd, event_change::read_change, and event_change::write_change.
Referenced by evmap_check_integrity_().
event_changelist_assert_ok()
static void event_changelist_assert_ok (struct event_base * base) static
Make sure that the changelist is consistent with the evmap structures.
Definition at line 752 of file evmap.c.
{
    int i;
    struct event_changelist *changelist = &base->changelist;
    EVUTIL_ASSERT(changelist->changes_size >= changelist->n_changes);
    for (i = 0; i < changelist->n_changes; ++i) {
        struct event_change *c = &changelist->changes[i];
        struct event_changelist_fdinfo *f;
        EVUTIL_ASSERT(c->fd >= 0);
        f = event_change_get_fdinfo(base, c);
        EVUTIL_ASSERT(f);
        EVUTIL_ASSERT(f->idxplus1 == i + 1);
    }
    evmap_io_foreach_fd(base,
        event_changelist_assert_ok_foreach_iter_fn,
        NULL);
}
References event_base::changelist, event_changelist::changes, event_changelist::changes_size, event_change_get_fdinfo(), event_changelist_assert_ok_foreach_iter_fn(), evmap_io_foreach_fd(), EVUTIL_ASSERT, event_change::fd, event_changelist_fdinfo::idxplus1, and event_changelist::n_changes.
Referenced by evmap_check_integrity_().
event_changelist_assert_ok_foreach_iter_fn()
static int event_changelist_assert_ok_foreach_iter_fn (struct event_base * base, evutil_socket_t fd, struct evmap_io * io, void * arg) static
Callback helper for event_changelist_assert_ok
Definition at line 735 of file evmap.c.
{
    struct event_changelist *changelist = &base->changelist;
    struct event_changelist_fdinfo *f;
    f = (void*)
        ( ((char*)io) + sizeof(struct evmap_io) );
    if (f->idxplus1) {
        struct event_change *c = &changelist->changes[f->idxplus1 - 1];
        EVUTIL_ASSERT(c->fd == fd);
    }
    return 0;
}
References event_base::changelist, event_changelist::changes, EVUTIL_ASSERT, event_change::fd, and event_changelist_fdinfo::idxplus1.
Referenced by event_changelist_assert_ok().
event_changelist_del_()
int event_changelist_del_ (struct event_base * base, evutil_socket_t fd, short old, short events, void * p)
Implementation of eventop_del that queues the event in a changelist.
Definition at line 896 of file evmap.c.
{
    struct event_changelist *changelist = &base->changelist;
    struct event_changelist_fdinfo *fdinfo = p;
    struct event_change *change;
    ev_uint8_t del = EV_CHANGE_DEL | (events & EV_ET);
    event_changelist_check(base);
    change = event_changelist_get_or_construct(changelist, fd, old, fdinfo);
    event_changelist_check(base);
    if (!change)
        return -1;
    /* A delete on an event set that doesn't contain the event to be
       deleted produces a no-op.  This effectively emoves any previous
       uncommitted add, rather than replacing it: on those platforms where
       "add, delete, dispatch" is not the same as "no-op, dispatch", we
       want the no-op behavior.
       If we have a no-op item, we could remove it it from the list
       entirely, but really there's not much point: skipping the no-op
       change when we do the dispatch later is far cheaper than rejuggling
       the array now.
       As this stands, it also lets through deletions of events that are
       not currently set.
     */
    if (events & (EV_READ|EV_SIGNAL)) {
        if (!(change->old_events & (EV_READ | EV_SIGNAL)))
            change->read_change = 0;
        else
            change->read_change = del;
    }
    if (events & EV_WRITE) {
        if (!(change->old_events & EV_WRITE))
            change->write_change = 0;
        else
            change->write_change = del;
    }
    if (events & EV_CLOSED) {
        if (!(change->old_events & EV_CLOSED))
            change->close_change = 0;
        else
            change->close_change = del;
    }
    event_changelist_check(base);
    return (0);
}
References event_base::changelist, event_change::close_change, EV_CHANGE_DEL, event_changelist_check, event_changelist_get_or_construct(), event_change::fd, event_change::old_events, event_change::read_change, and event_change::write_change.
event_changelist_freemem_()
void event_changelist_freemem_ (struct event_changelist * changelist)
Free all memory held in a changelist.
Definition at line 800 of file evmap.c.
{
    if (changelist->changes)
        mm_free(changelist->changes);
    event_changelist_init_(changelist); /* zero it all out. */
}
References event_changelist::changes, event_changelist_init_(), and mm_free.
Referenced by event_base_free_(), and event_reinit().
event_changelist_get_or_construct()
static struct event_change * event_changelist_get_or_construct (struct event_changelist * changelist, evutil_socket_t fd, short old_events, struct event_changelist_fdinfo * fdinfo) static
Return a pointer to the changelist entry for the file descriptor or signal 'fd', whose fdinfo is 'fdinfo'. If none exists, construct it, setting its old_events field to old_events.
Definition at line 835 of file evmap.c.
{
    struct event_change *change;
    if (fdinfo->idxplus1 == 0) {
        int idx;
        EVUTIL_ASSERT(changelist->n_changes <= changelist->changes_size);
        if (changelist->n_changes == changelist->changes_size) {
            if (event_changelist_grow(changelist) < 0)
                return NULL;
        }
        idx = changelist->n_changes++;
        change = &changelist->changes[idx];
        fdinfo->idxplus1 = idx + 1;
        memset(change, 0, sizeof(struct event_change));
        change->fd = fd;
        change->old_events = old_events;
    } else {
        change = &changelist->changes[fdinfo->idxplus1 - 1];
        EVUTIL_ASSERT(change->fd == fd);
    }
    return change;
}
References event_changelist::changes, event_changelist::changes_size, event_changelist_grow(), EVUTIL_ASSERT, event_change::fd, event_changelist_fdinfo::idxplus1, event_changelist::n_changes, and event_change::old_events.
Referenced by event_changelist_add_(), and event_changelist_del_().
event_changelist_grow()
static int event_changelist_grow (struct event_changelist * changelist) static
Increase the size of 'changelist' to hold more changes.
Definition at line 809 of file evmap.c.
{
    int new_size;
    struct event_change *new_changes;
    if (changelist->changes_size < 64)
        new_size = 64;
    else
        new_size = changelist->changes_size * 2;
    new_changes = mm_realloc(changelist->changes,
        new_size * sizeof(struct event_change));
    if (EVUTIL_UNLIKELY(new_changes == NULL))
        return (-1);
    changelist->changes = new_changes;
    changelist->changes_size = new_size;
    return (0);
}
References event_changelist::changes, event_changelist::changes_size, EVUTIL_UNLIKELY, and mm_realloc.
Referenced by event_changelist_get_or_construct().
event_changelist_init_()
void event_changelist_init_ (struct event_changelist * changelist)
Set up the data fields in a changelist.
Definition at line 708 of file evmap.c.
{
    changelist->changes = NULL;
    changelist->changes_size = 0;
    changelist->n_changes = 0;
}
References event_changelist::changes, event_changelist::changes_size, and event_changelist::n_changes.
Referenced by event_base_new_with_config(), and event_changelist_freemem_().
event_changelist_remove_all_()
void event_changelist_remove_all_ (struct event_changelist * changelist, struct event_base * base)
Remove every change in the changelist, and make corresponding changes in the event maps in the base. This function is generally used right after making all the changes in the changelist.
Definition at line 779 of file evmap.c.
{
    int i;
    event_changelist_check(base);
    for (i = 0; i < changelist->n_changes; ++i) {
        struct event_change *ch = &changelist->changes[i];
        struct event_changelist_fdinfo *fdinfo =
            event_change_get_fdinfo(base, ch);
        EVUTIL_ASSERT(fdinfo->idxplus1 == i + 1);
        fdinfo->idxplus1 = 0;
    }
    changelist->n_changes = 0;
    event_changelist_check(base);
}
References event_changelist::changes, event_change_get_fdinfo(), event_changelist_check, EVUTIL_ASSERT, event_changelist_fdinfo::idxplus1, and event_changelist::n_changes.
evmap_check_integrity_()
void evmap_check_integrity_ (struct event_base * base)
Definition at line 1002 of file evmap.c.
{
    evmap_io_foreach_fd(base, evmap_io_check_integrity_fn, NULL);
    evmap_signal_foreach_signal(base, evmap_signal_check_integrity_fn, NULL);
    if (base->evsel->add == event_changelist_add_)
        event_changelist_assert_ok(base);
}
References eventop::add, event_changelist_add_(), event_changelist_assert_ok(), evmap_io_check_integrity_fn(), evmap_io_foreach_fd(), evmap_signal_check_integrity_fn(), evmap_signal_foreach_signal(), and event_base::evsel.
Referenced by event_base_assert_ok_nolock_().
evmap_delete_all_()
void evmap_delete_all_ (struct event_base * base)
Definition at line 693 of file evmap.c.
{
    evmap_signal_foreach_signal(base, evmap_signal_delete_all_iter_fn, NULL);
    evmap_io_foreach_fd(base, evmap_io_delete_all_iter_fn, NULL);
}
References evmap_io_delete_all_iter_fn(), evmap_io_foreach_fd(), evmap_signal_delete_all_iter_fn(), and evmap_signal_foreach_signal().
Referenced by event_base_free_().
evmap_foreach_event_()
int evmap_foreach_event_ (struct event_base * base, event_base_foreach_event_cb fn, void * arg)
Definition at line 1051 of file evmap.c.
{
    struct evmap_foreach_event_helper h;
    int r;
    h.fn = fn;
    h.arg = arg;
    if ((r = evmap_io_foreach_fd(base, evmap_io_foreach_event_fn, &h)))
        return r;
    return evmap_signal_foreach_signal(base, evmap_signal_foreach_event_fn, &h);
}
References evmap_foreach_event_helper::arg, evmap_io_foreach_event_fn(), evmap_io_foreach_fd(), evmap_signal_foreach_event_fn(), evmap_signal_foreach_signal(), and evmap_foreach_event_helper::fn.
Referenced by event_base_foreach_event_nolock_().
evmap_io_active_()
void evmap_io_active_ (struct event_base * base, evutil_socket_t fd, short events)
Active the set of events waiting on an event_base for a given fd.
Parameters
base the event_base to operate on.
fd the file descriptor that has become active.
events a bitmask of EV_READ|EV_WRITE|EV_ET.
Definition at line 420 of file evmap.c.
{
    struct event_io_map *io = &base->io;
    struct evmap_io *ctx;
    struct event *ev;
#ifndef EVMAP_USE_HT
    if (fd < 0 || fd >= io->nentries)
        return;
#endif
    GET_IO_SLOT(ctx, io, fd, evmap_io);
    if (NULL == ctx)
        return;
    LIST_FOREACH(ev, &ctx->events, ev_io_next) {
        if (ev->ev_events & (events & ~EV_ET))
            event_active_nolock_(ev, ev->ev_events & events, 1);
    }
}
References ctx, ev_io_next, event_active_nolock_(), event_io_map, GET_IO_SLOT, and event_base::io.
Referenced by event_base_active_by_fd().
evmap_io_add_()
int evmap_io_add_ (struct event_base * base, evutil_socket_t fd, struct event * ev)
Add an IO event (some combination of EV_READ or EV_WRITE) to an event_base's list of events on a given file descriptor, and tell the underlying eventops about the fd if its state has changed.
Requires that ev is not already added.
Parameters
base the event_base to operate on.
fd the file descriptor corresponding to ev.
ev the event to add.
Definition at line 273 of file evmap.c.
{
    const struct eventop *evsel = base->evsel;
    struct event_io_map *io = &base->io;
    struct evmap_io *ctx = NULL;
    int nread, nwrite, nclose, retval = 0;
    short res = 0, old = 0;
    struct event *old_ev;
    EVUTIL_ASSERT(fd == ev->ev_fd);
    if (fd < 0)
        return 0;
#ifndef EVMAP_USE_HT
    if (fd >= io->nentries) {
        if (evmap_make_space(io, fd, sizeof(struct evmap_io *)) == -1)
            return (-1);
    }
#endif
    GET_IO_SLOT_AND_CTOR(ctx, io, fd, evmap_io, evmap_io_init,
                         evsel->fdinfo_len);
    nread = ctx->nread;
    nwrite = ctx->nwrite;
    nclose = ctx->nclose;
    if (nread)
        old |= EV_READ;
    if (nwrite)
        old |= EV_WRITE;
    if (nclose)
        old |= EV_CLOSED;
    if (ev->ev_events & EV_READ) {
        if (++nread == 1)
            res |= EV_READ;
    }
    if (ev->ev_events & EV_WRITE) {
        if (++nwrite == 1)
            res |= EV_WRITE;
    }
    if (ev->ev_events & EV_CLOSED) {
        if (++nclose == 1)
            res |= EV_CLOSED;
    }
    if (EVUTIL_UNLIKELY(nread > 0xffff || nwrite > 0xffff || nclose > 0xffff)) {
        event_warnx("Too many events reading or writing on fd %d",
            (int)fd);
        return -1;
    }
    if (EVENT_DEBUG_MODE_IS_ON() &&
        (old_ev = LIST_FIRST(&ctx->events)) &&
        (old_ev->ev_events&EV_ET) != (ev->ev_events&EV_ET)) {
        event_warnx("Tried to mix edge-triggered and non-edge-triggered"
            " events on fd %d", (int)fd);
        return -1;
    }
    if (res) {
        void *extra = ((char*)ctx) + sizeof(struct evmap_io);
        /* XXX(niels): we cannot mix edge-triggered and
         * level-triggered, we should probably assert on
         * this. */
        if (evsel->add(base, ev->ev_fd,
            old, (ev->ev_events & EV_ET) | res, extra) == -1)
            return (-1);
        retval = 1;
    }
    ctx->nread = (ev_uint16_t) nread;
    ctx->nwrite = (ev_uint16_t) nwrite;
    ctx->nclose = (ev_uint16_t) nclose;
    LIST_INSERT_HEAD(&ctx->events, ev, ev_io_next);
    return (retval);
}
References eventop::add, ctx, ev_io_next, EVENT_DEBUG_MODE_IS_ON, event_io_map, event_warnx(), evmap_io_init(), evmap_make_space(), event_base::evsel, EVUTIL_ASSERT, EVUTIL_UNLIKELY, eventop::fdinfo_len, GET_IO_SLOT_AND_CTOR, event_base::io, evmap_io::nclose, evmap_io::nread, and evmap_io::nwrite.
Referenced by event_add_nolock_().
evmap_io_check_integrity_fn()
static int evmap_io_check_integrity_fn (struct event_base * base, evutil_socket_t fd, struct evmap_io * io_info, void * arg) static
Definition at line 952 of file evmap.c.
{
    struct event *ev;
    int n_read = 0, n_write = 0, n_close = 0;
    /* First, make sure the list itself isn't corrupt. Otherwise,
     * running LIST_FOREACH could be an exciting adventure. */
    EVUTIL_ASSERT_LIST_OK(&io_info->events, event, ev_io_next);
    LIST_FOREACH(ev, &io_info->events, ev_io_next) {
        EVUTIL_ASSERT(ev->ev_flags & EVLIST_INSERTED);
        EVUTIL_ASSERT(ev->ev_fd == fd);
        EVUTIL_ASSERT(!(ev->ev_events & EV_SIGNAL));
        EVUTIL_ASSERT((ev->ev_events & (EV_READ|EV_WRITE|EV_CLOSED)));
        if (ev->ev_events & EV_READ)
            ++n_read;
        if (ev->ev_events & EV_WRITE)
            ++n_write;
        if (ev->ev_events & EV_CLOSED)
            ++n_close;
    }
    EVUTIL_ASSERT(n_read == io_info->nread);
    EVUTIL_ASSERT(n_write == io_info->nwrite);
    EVUTIL_ASSERT(n_close == io_info->nclose);
    return 0;
}
References ev_io_next, evmap_io::events, EVUTIL_ASSERT, EVUTIL_ASSERT_LIST_OK, evmap_io::nclose, evmap_io::nread, and evmap_io::nwrite.
Referenced by evmap_check_integrity_().
evmap_io_clear_()
void evmap_io_clear_ (struct event_io_map * ctx)
Remove all entries from an event_map.
Parameters
ctx the map to clear.
Definition at line 194 of file evmap.c.
{
    evmap_signal_clear_(ctx);
}
References ctx, and evmap_signal_clear_().
Referenced by event_base_free_().
evmap_io_del_()
int evmap_io_del_ (struct event_base * base, evutil_socket_t fd, struct event * ev)
Remove an IO event (some combination of EV_READ or EV_WRITE) to an event_base's list of events on a given file descriptor, and tell the underlying eventops about the fd if its state has changed.
Parameters
base the event_base to operate on.
fd the file descriptor corresponding to ev.
ev the event to remove.
Definition at line 354 of file evmap.c.
{
    const struct eventop *evsel = base->evsel;
    struct event_io_map *io = &base->io;
    struct evmap_io *ctx;
    int nread, nwrite, nclose, retval = 0;
    short res = 0, old = 0;
    if (fd < 0)
        return 0;
    EVUTIL_ASSERT(fd == ev->ev_fd);
#ifndef EVMAP_USE_HT
    if (fd >= io->nentries)
        return (-1);
#endif
    GET_IO_SLOT(ctx, io, fd, evmap_io);
    nread = ctx->nread;
    nwrite = ctx->nwrite;
    nclose = ctx->nclose;
    if (nread)
        old |= EV_READ;
    if (nwrite)
        old |= EV_WRITE;
    if (nclose)
        old |= EV_CLOSED;
    if (ev->ev_events & EV_READ) {
        if (--nread == 0)
            res |= EV_READ;
        EVUTIL_ASSERT(nread >= 0);
    }
    if (ev->ev_events & EV_WRITE) {
        if (--nwrite == 0)
            res |= EV_WRITE;
        EVUTIL_ASSERT(nwrite >= 0);
    }
    if (ev->ev_events & EV_CLOSED) {
        if (--nclose == 0)
            res |= EV_CLOSED;
        EVUTIL_ASSERT(nclose >= 0);
    }
    if (res) {
        void *extra = ((char*)ctx) + sizeof(struct evmap_io);
        if (evsel->del(base, ev->ev_fd,
            old, (ev->ev_events & EV_ET) | res, extra) == -1) {
            retval = -1;
        } else {
            retval = 1;
        }
    }
    ctx->nread = nread;
    ctx->nwrite = nwrite;
    ctx->nclose = nclose;
    LIST_REMOVE(ev, ev_io_next);
    return (retval);
}
References ctx, eventop::del, ev_io_next, event_io_map, event_base::evsel, EVUTIL_ASSERT, GET_IO_SLOT, event_base::io, evmap_io::nclose, evmap_io::nread, and evmap_io::nwrite.
Referenced by event_del_nolock_().
evmap_io_delete_all_iter_fn()
static int evmap_io_delete_all_iter_fn (struct event_base * base, evutil_socket_t fd, struct evmap_io * io_info, void * arg) static
Definition at line 678 of file evmap.c.
{
    return delete_all_in_dlist(&io_info->events);
}
References delete_all_in_dlist(), and evmap_io::events.
Referenced by evmap_delete_all_().
evmap_io_foreach_event_fn()
static int evmap_io_foreach_event_fn (struct event_base * base, evutil_socket_t fd, struct evmap_io * io_info, void * arg) static
Definition at line 1021 of file evmap.c.
{
    struct evmap_foreach_event_helper *h = arg;
    struct event *ev;
    int r;
    LIST_FOREACH(ev, &io_info->events, ev_io_next) {
        if ((r = h->fn(base, ev, h->arg)))
            return r;
    }
    return 0;
}
References evmap_foreach_event_helper::arg, ev_io_next, evmap_io::events, and evmap_foreach_event_helper::fn.
Referenced by evmap_foreach_event_().
evmap_io_foreach_fd()
static int evmap_io_foreach_fd (struct event_base * base, evmap_io_foreach_fd_cb fn, void * arg) static
Definition at line 546 of file evmap.c.
{
    evutil_socket_t fd;
    struct event_io_map *iomap = &base->io;
    int r = 0;
#ifdef EVMAP_USE_HT
    struct event_map_entry **mapent;
    HT_FOREACH(mapent, event_io_map, iomap) {
        struct evmap_io *ctx = &(*mapent)->ent.evmap_io;
        fd = (*mapent)->fd;
#else
    for (fd = 0; fd < iomap->nentries; ++fd) {
        struct evmap_io *ctx = iomap->entries[fd];
        if (!ctx)
            continue;
#endif
        if ((r = fn(base, fd, ctx, arg)))
            break;
    }
    return r;
}
References ctx, event_io_map, HT_FOREACH, and event_base::io.
Referenced by event_changelist_assert_ok(), evmap_check_integrity_(), evmap_delete_all_(), evmap_foreach_event_(), and evmap_reinit_().
evmap_io_get_fdinfo_()
void * evmap_io_get_fdinfo_ (struct event_io_map * map, evutil_socket_t fd)
Definition at line 518 of file evmap.c.
{
    struct evmap_io *ctx;
    GET_IO_SLOT(ctx, map, fd, evmap_io);
    if (ctx)
        return ((char*)ctx) + sizeof(struct evmap_io);
    else
        return NULL;
}
References ctx, and GET_IO_SLOT.
evmap_io_init()
static void evmap_io_init (struct evmap_io * entry) static
Constructor for struct evmap_io
Definition at line 261 of file evmap.c.
{
    LIST_INIT(&entry->events);
    entry->nread = 0;
    entry->nwrite = 0;
    entry->nclose = 0;
}
References evmap_io::events, evmap_io::nclose, evmap_io::nread, and evmap_io::nwrite.
Referenced by evmap_io_add_().
evmap_io_initmap_()
void evmap_io_initmap_ (struct event_io_map * ctx)
Initialize an event_map for use.
Definition at line 189 of file evmap.c.
{
    evmap_signal_initmap_(ctx);
}
References ctx, and evmap_signal_initmap_().
Referenced by event_base_new_with_config().
evmap_io_reinit_iter_fn()
static int evmap_io_reinit_iter_fn (struct event_base * base, evutil_socket_t fd, struct evmap_io * ctx, void * arg) static
Definition at line 607 of file evmap.c.
{
    const struct eventop *evsel = base->evsel;
    void *extra;
    int *result = arg;
    short events = 0;
    struct event *ev;
    EVUTIL_ASSERT(ctx);
    extra = ((char*)ctx) + sizeof(struct evmap_io);
    if (ctx->nread)
        events |= EV_READ;
    if (ctx->nwrite)
        events |= EV_WRITE;
    if (ctx->nclose)
        events |= EV_CLOSED;
    if (evsel->fdinfo_len)
        memset(extra, 0, evsel->fdinfo_len);
    if (events &&
        (ev = LIST_FIRST(&ctx->events)) &&
        (ev->ev_events & EV_ET))
        events |= EV_ET;
    if (evsel->add(base, fd, 0, events, extra) == -1)
        *result = -1;
    return 0;
}
References eventop::add, ctx, evmap_io::events, event_base::evsel, EVUTIL_ASSERT, and eventop::fdinfo_len.
Referenced by evmap_reinit_().
evmap_make_space()
static int evmap_make_space (struct event_signal_map * map, int slot, int msize) static
Expand 'map' with new entries of width 'msize' until it is big enough to store a value in 'slot'.
Definition at line 205 of file evmap.c.
{
    if (map->nentries <= slot) {
        int nentries = map->nentries ? map->nentries : 32;
        void **tmp;
        if (slot > INT_MAX / 2)
            return (-1);
        while (nentries <= slot)
            nentries <<= 1;
        if (nentries > INT_MAX / msize)
            return (-1);
        tmp = (void **)mm_realloc(map->entries, nentries * msize);
        if (tmp == NULL)
            return (-1);
        memset(&tmp[map->nentries], 0,
            (nentries - map->nentries) * msize);
        map->nentries = nentries;
        map->entries = tmp;
    }
    return (0);
}
References event_signal_map::entries, mm_realloc, and event_signal_map::nentries.
Referenced by evmap_io_add_(), and evmap_signal_add_().
evmap_reinit_()
int evmap_reinit_ (struct event_base * base)
Definition at line 653 of file evmap.c.
{
    int result = 0;
    evmap_io_foreach_fd(base, evmap_io_reinit_iter_fn, &result);
    if (result < 0)
        return -1;
    evmap_signal_foreach_signal(base, evmap_signal_reinit_iter_fn, &result);
    if (result < 0)
        return -1;
    return 0;
}
References evmap_io_foreach_fd(), evmap_io_reinit_iter_fn(), evmap_signal_foreach_signal(), and evmap_signal_reinit_iter_fn().
Referenced by event_reinit().
evmap_signal_active_()
void evmap_signal_active_ (struct event_base * base, evutil_socket_t sig, int ncalls)
Definition at line 501 of file evmap.c.
{
    struct event_signal_map *map = &base->sigmap;
    struct evmap_signal *ctx;
    struct event *ev;
    if (sig < 0 || sig >= map->nentries)
        return;
    GET_SIGNAL_SLOT(ctx, map, sig, evmap_signal);
    if (!ctx)
        return;
    LIST_FOREACH(ev, &ctx->events, ev_signal_next)
        event_active_nolock_(ev, EV_SIGNAL, ncalls);
}
References ctx, ev_signal_next, event_active_nolock_(), GET_SIGNAL_SLOT, event_signal_map::nentries, and event_base::sigmap.
Referenced by event_base_active_by_signal(), and evsig_cb().
evmap_signal_add_()
int evmap_signal_add_ (struct event_base * base, int sig, struct event * ev)
Definition at line 450 of file evmap.c.
{
    const struct eventop *evsel = base->evsigsel;
    struct event_signal_map *map = &base->sigmap;
    struct evmap_signal *ctx = NULL;
    if (sig < 0 || sig >= NSIG)
        return (-1);
    if (sig >= map->nentries) {
        if (evmap_make_space(
            map, sig, sizeof(struct evmap_signal *)) == -1)
            return (-1);
    }
    GET_SIGNAL_SLOT_AND_CTOR(ctx, map, sig, evmap_signal, evmap_signal_init,
        base->evsigsel->fdinfo_len);
    if (LIST_EMPTY(&ctx->events)) {
        if (evsel->add(base, ev->ev_fd, 0, EV_SIGNAL, NULL)
            == -1)
            return (-1);
    }
    LIST_INSERT_HEAD(&ctx->events, ev, ev_signal_next);
    return (1);
}
References eventop::add, ctx, ev_signal_next, evmap_make_space(), evmap_signal_init(), event_base::evsigsel, eventop::fdinfo_len, GET_SIGNAL_SLOT_AND_CTOR, event_signal_map::nentries, and event_base::sigmap.
Referenced by event_add_nolock_().
evmap_signal_check_integrity_fn()
static int evmap_signal_check_integrity_fn (struct event_base * base, int signum, struct evmap_signal * sig_info, void * arg) static
Definition at line 985 of file evmap.c.
{
    struct event *ev;
    /* First, make sure the list itself isn't corrupt. */
    EVUTIL_ASSERT_LIST_OK(&sig_info->events, event, ev_signal_next);
    LIST_FOREACH(ev, &sig_info->events, ev_io_next) {
        EVUTIL_ASSERT(ev->ev_flags & EVLIST_INSERTED);
        EVUTIL_ASSERT(ev->ev_fd == signum);
        EVUTIL_ASSERT((ev->ev_events & EV_SIGNAL));
        EVUTIL_ASSERT(!(ev->ev_events & (EV_READ|EV_WRITE|EV_CLOSED)));
    }
    return 0;
}
References ev_io_next, ev_signal_next, evmap_signal::events, EVUTIL_ASSERT, and EVUTIL_ASSERT_LIST_OK.
Referenced by evmap_check_integrity_().
evmap_signal_clear_()
void evmap_signal_clear_ (struct event_signal_map * ctx)
Definition at line 242 of file evmap.c.
{
    if (ctx->entries != NULL) {
        int i;
        for (i = 0; i < ctx->nentries; ++i) {
            if (ctx->entries[i] != NULL)
                mm_free(ctx->entries[i]);
        }
        mm_free(ctx->entries);
        ctx->entries = NULL;
    }
    ctx->nentries = 0;
}
References ctx, and mm_free.
Referenced by event_base_free_(), and evmap_io_clear_().
evmap_signal_del_()
int evmap_signal_del_ (struct event_base * base, int sig, struct event * ev)
Definition at line 479 of file evmap.c.
{
    const struct eventop *evsel = base->evsigsel;
    struct event_signal_map *map = &base->sigmap;
    struct evmap_signal *ctx;
    if (sig < 0 || sig >= map->nentries)
        return (-1);
    GET_SIGNAL_SLOT(ctx, map, sig, evmap_signal);
    LIST_REMOVE(ev, ev_signal_next);
    if (LIST_FIRST(&ctx->events) == NULL) {
        if (evsel->del(base, ev->ev_fd, 0, EV_SIGNAL, NULL) == -1)
            return (-1);
    }
    return (1);
}
References ctx, eventop::del, ev_signal_next, event_base::evsigsel, GET_SIGNAL_SLOT, event_signal_map::nentries, and event_base::sigmap.
Referenced by event_del_nolock_().
evmap_signal_delete_all_iter_fn()
static int evmap_signal_delete_all_iter_fn (struct event_base * base, int signum, struct evmap_signal * sig_info, void * arg) static
Definition at line 686 of file evmap.c.
{
    return delete_all_in_dlist(&sig_info->events);
}
References delete_all_in_dlist(), and evmap_signal::events.
Referenced by evmap_delete_all_().
evmap_signal_foreach_event_fn()
static int evmap_signal_foreach_event_fn (struct event_base * base, int signum, struct evmap_signal * sig_info, void * arg) static
Definition at line 1037 of file evmap.c.
{
    struct event *ev;
    struct evmap_foreach_event_helper *h = arg;
    int r;
    LIST_FOREACH(ev, &sig_info->events, ev_signal_next) {
        if ((r = h->fn(base, ev, h->arg)))
            return r;
    }
    return 0;
}
References evmap_foreach_event_helper::arg, ev_signal_next, evmap_signal::events, and evmap_foreach_event_helper::fn.
Referenced by evmap_foreach_event_().
evmap_signal_foreach_signal()
static int evmap_signal_foreach_signal (struct event_base * base, evmap_signal_foreach_signal_cb fn, void * arg) static
Definition at line 585 of file evmap.c.
{
    struct event_signal_map *sigmap = &base->sigmap;
    int r = 0;
    int signum;
    for (signum = 0; signum < sigmap->nentries; ++signum) {
        struct evmap_signal *ctx = sigmap->entries[signum];
        if (!ctx)
            continue;
        if ((r = fn(base, signum, ctx, arg)))
            break;
    }
    return r;
}
References ctx, event_signal_map::entries, event_signal_map::nentries, and event_base::sigmap.
Referenced by evmap_check_integrity_(), evmap_delete_all_(), evmap_foreach_event_(), and evmap_reinit_().
evmap_signal_init()
static void evmap_signal_init (struct evmap_signal * entry) static
Definition at line 443 of file evmap.c.
{
    LIST_INIT(&entry->events);
}
References evmap_signal::events.
Referenced by evmap_signal_add_().
evmap_signal_initmap_()
void evmap_signal_initmap_ (struct event_signal_map * ctx)
Definition at line 235 of file evmap.c.
{
    ctx->nentries = 0;
    ctx->entries = NULL;
}
References ctx.
Referenced by event_base_new_with_config(), and evmap_io_initmap_().
evmap_signal_reinit_iter_fn()
static int evmap_signal_reinit_iter_fn (struct event_base * base, int signum, struct evmap_signal * ctx, void * arg) static
Definition at line 639 of file evmap.c.
{
    const struct eventop *evsel = base->evsigsel;
    int *result = arg;
    if (!LIST_EMPTY(&ctx->events)) {
        if (evsel->add(base, signum, 0, EV_SIGNAL, NULL) == -1)
            *result = -1;
    }
    return 0;
}
References eventop::add, ctx, and event_base::evsigsel.
Referenced by evmap_reinit_().