libdogecoin: src/libevent/evmap-internal.h File Reference
evmap-internal.h File Reference
Functions
void evmap_io_initmap_ (struct event_io_map *ctx)
void evmap_signal_initmap_ (struct event_signal_map *ctx)
void evmap_io_clear_ (struct event_io_map *ctx)
void evmap_signal_clear_ (struct event_signal_map *ctx)
int evmap_io_add_ (struct event_base *base, evutil_socket_t fd, struct event *ev)
int evmap_io_del_ (struct event_base *base, evutil_socket_t fd, struct event *ev)
void evmap_io_active_ (struct event_base *base, evutil_socket_t fd, short events)
int evmap_signal_add_ (struct event_base *base, int signum, struct event *ev)
int evmap_signal_del_ (struct event_base *base, int signum, struct event *ev)
void evmap_signal_active_ (struct event_base *base, evutil_socket_t signum, int ncalls)
void * evmap_io_get_fdinfo_ (struct event_io_map *ctx, evutil_socket_t fd)
int evmap_reinit_ (struct event_base *base)
void evmap_delete_all_ (struct event_base *base)
void evmap_check_integrity_ (struct event_base *base)
int evmap_foreach_event_ (struct event_base *base, event_base_foreach_event_cb fn, void *arg)
Detailed Description
An event_map is a utility structure to map each fd or signal to zero or more events. Functions to manipulate event_maps should only be used from inside libevent. They generally need to hold the lock on the corresponding event_base.
Definition in file evmap-internal.h.
Function Documentation
evmap_check_integrity_()
void evmap_check_integrity_ (struct event_base * base)
Definition at line 1002 of file evmap.c.
{
    evmap_io_foreach_fd(base, evmap_io_check_integrity_fn, NULL);
    evmap_signal_foreach_signal(base, evmap_signal_check_integrity_fn, NULL);
    if (base->evsel->add == event_changelist_add_)
        event_changelist_assert_ok(base);
}
References eventop::add, event_changelist_add_(), event_changelist_assert_ok(), evmap_io_check_integrity_fn(), evmap_io_foreach_fd(), evmap_signal_check_integrity_fn(), evmap_signal_foreach_signal(), and event_base::evsel.
Referenced by event_base_assert_ok_nolock_().
evmap_delete_all_()
void evmap_delete_all_ (struct event_base * base)
Definition at line 693 of file evmap.c.
{
    evmap_signal_foreach_signal(base, evmap_signal_delete_all_iter_fn, NULL);
    evmap_io_foreach_fd(base, evmap_io_delete_all_iter_fn, NULL);
}
References evmap_io_delete_all_iter_fn(), evmap_io_foreach_fd(), evmap_signal_delete_all_iter_fn(), and evmap_signal_foreach_signal().
Referenced by event_base_free_().
evmap_foreach_event_()
int evmap_foreach_event_ (struct event_base * base, event_base_foreach_event_cb fn, void * arg)
Definition at line 1051 of file evmap.c.
{
    struct evmap_foreach_event_helper h;
    int r;
    h.fn = fn;
    h.arg = arg;
    if ((r = evmap_io_foreach_fd(base, evmap_io_foreach_event_fn, &h)))
        return r;
    return evmap_signal_foreach_signal(base, evmap_signal_foreach_event_fn, &h);
}
References evmap_foreach_event_helper::arg, evmap_io_foreach_event_fn(), evmap_io_foreach_fd(), evmap_signal_foreach_event_fn(), evmap_signal_foreach_signal(), and evmap_foreach_event_helper::fn.
Referenced by event_base_foreach_event_nolock_().
evmap_io_active_()
void evmap_io_active_ (struct event_base * base, evutil_socket_t fd, short events)
Active the set of events waiting on an event_base for a given fd.
Parameters
base the event_base to operate on.
fd the file descriptor that has become active.
events a bitmask of EV_READ|EV_WRITE|EV_ET.
Definition at line 420 of file evmap.c.
{
    struct event_io_map *io = &base->io;
    struct evmap_io *ctx;
    struct event *ev;
#ifndef EVMAP_USE_HT
    if (fd < 0 || fd >= io->nentries)
        return;
#endif
    GET_IO_SLOT(ctx, io, fd, evmap_io);
    if (NULL == ctx)
        return;
    LIST_FOREACH(ev, &ctx->events, ev_io_next) {
        if (ev->ev_events & (events & ~EV_ET))
            event_active_nolock_(ev, ev->ev_events & events, 1);
    }
}
References ctx, ev_io_next, event_active_nolock_(), event_io_map, GET_IO_SLOT, and event_base::io.
Referenced by event_base_active_by_fd().
evmap_io_add_()
int evmap_io_add_ (struct event_base * base, evutil_socket_t fd, struct event * ev)
Add an IO event (some combination of EV_READ or EV_WRITE) to an event_base's list of events on a given file descriptor, and tell the underlying eventops about the fd if its state has changed.
Requires that ev is not already added.
Parameters
base the event_base to operate on.
fd the file descriptor corresponding to ev.
ev the event to add.
Definition at line 273 of file evmap.c.
{
    const struct eventop *evsel = base->evsel;
    struct event_io_map *io = &base->io;
    struct evmap_io *ctx = NULL;
    int nread, nwrite, nclose, retval = 0;
    short res = 0, old = 0;
    struct event *old_ev;
    EVUTIL_ASSERT(fd == ev->ev_fd);
    if (fd < 0)
        return 0;
#ifndef EVMAP_USE_HT
    if (fd >= io->nentries) {
        if (evmap_make_space(io, fd, sizeof(struct evmap_io *)) == -1)
            return (-1);
    }
#endif
    GET_IO_SLOT_AND_CTOR(ctx, io, fd, evmap_io, evmap_io_init,
                         evsel->fdinfo_len);
    nread = ctx->nread;
    nwrite = ctx->nwrite;
    nclose = ctx->nclose;
    if (nread)
        old |= EV_READ;
    if (nwrite)
        old |= EV_WRITE;
    if (nclose)
        old |= EV_CLOSED;
    if (ev->ev_events & EV_READ) {
        if (++nread == 1)
            res |= EV_READ;
    }
    if (ev->ev_events & EV_WRITE) {
        if (++nwrite == 1)
            res |= EV_WRITE;
    }
    if (ev->ev_events & EV_CLOSED) {
        if (++nclose == 1)
            res |= EV_CLOSED;
    }
    if (EVUTIL_UNLIKELY(nread > 0xffff || nwrite > 0xffff || nclose > 0xffff)) {
        event_warnx("Too many events reading or writing on fd %d",
            (int)fd);
        return -1;
    }
    if (EVENT_DEBUG_MODE_IS_ON() &&
        (old_ev = LIST_FIRST(&ctx->events)) &&
        (old_ev->ev_events&EV_ET) != (ev->ev_events&EV_ET)) {
        event_warnx("Tried to mix edge-triggered and non-edge-triggered"
            " events on fd %d", (int)fd);
        return -1;
    }
    if (res) {
        void *extra = ((char*)ctx) + sizeof(struct evmap_io);
        /* XXX(niels): we cannot mix edge-triggered and
         * level-triggered, we should probably assert on
         * this. */
        if (evsel->add(base, ev->ev_fd,
            old, (ev->ev_events & EV_ET) | res, extra) == -1)
            return (-1);
        retval = 1;
    }
    ctx->nread = (ev_uint16_t) nread;
    ctx->nwrite = (ev_uint16_t) nwrite;
    ctx->nclose = (ev_uint16_t) nclose;
    LIST_INSERT_HEAD(&ctx->events, ev, ev_io_next);
    return (retval);
}
References eventop::add, ctx, ev_io_next, EVENT_DEBUG_MODE_IS_ON, event_io_map, event_warnx(), evmap_io_init(), evmap_make_space(), event_base::evsel, EVUTIL_ASSERT, EVUTIL_UNLIKELY, eventop::fdinfo_len, GET_IO_SLOT_AND_CTOR, event_base::io, evmap_io::nclose, evmap_io::nread, and evmap_io::nwrite.
Referenced by event_add_nolock_().
evmap_io_clear_()
void evmap_io_clear_ (struct event_io_map * ctx)
Remove all entries from an event_map.
Parameters
ctx the map to clear.
Definition at line 194 of file evmap.c.
{
    evmap_signal_clear_(ctx);
}
References ctx, and evmap_signal_clear_().
Referenced by event_base_free_().
evmap_io_del_()
int evmap_io_del_ (struct event_base * base, evutil_socket_t fd, struct event * ev)
Remove an IO event (some combination of EV_READ or EV_WRITE) to an event_base's list of events on a given file descriptor, and tell the underlying eventops about the fd if its state has changed.
Parameters
base the event_base to operate on.
fd the file descriptor corresponding to ev.
ev the event to remove.
Definition at line 354 of file evmap.c.
{
    const struct eventop *evsel = base->evsel;
    struct event_io_map *io = &base->io;
    struct evmap_io *ctx;
    int nread, nwrite, nclose, retval = 0;
    short res = 0, old = 0;
    if (fd < 0)
        return 0;
    EVUTIL_ASSERT(fd == ev->ev_fd);
#ifndef EVMAP_USE_HT
    if (fd >= io->nentries)
        return (-1);
#endif
    GET_IO_SLOT(ctx, io, fd, evmap_io);
    nread = ctx->nread;
    nwrite = ctx->nwrite;
    nclose = ctx->nclose;
    if (nread)
        old |= EV_READ;
    if (nwrite)
        old |= EV_WRITE;
    if (nclose)
        old |= EV_CLOSED;
    if (ev->ev_events & EV_READ) {
        if (--nread == 0)
            res |= EV_READ;
        EVUTIL_ASSERT(nread >= 0);
    }
    if (ev->ev_events & EV_WRITE) {
        if (--nwrite == 0)
            res |= EV_WRITE;
        EVUTIL_ASSERT(nwrite >= 0);
    }
    if (ev->ev_events & EV_CLOSED) {
        if (--nclose == 0)
            res |= EV_CLOSED;
        EVUTIL_ASSERT(nclose >= 0);
    }
    if (res) {
        void *extra = ((char*)ctx) + sizeof(struct evmap_io);
        if (evsel->del(base, ev->ev_fd,
            old, (ev->ev_events & EV_ET) | res, extra) == -1) {
            retval = -1;
        } else {
            retval = 1;
        }
    }
    ctx->nread = nread;
    ctx->nwrite = nwrite;
    ctx->nclose = nclose;
    LIST_REMOVE(ev, ev_io_next);
    return (retval);
}
References ctx, eventop::del, ev_io_next, event_io_map, event_base::evsel, EVUTIL_ASSERT, GET_IO_SLOT, event_base::io, evmap_io::nclose, evmap_io::nread, and evmap_io::nwrite.
Referenced by event_del_nolock_().
evmap_io_get_fdinfo_()
void * evmap_io_get_fdinfo_ (struct event_io_map * ctx, evutil_socket_t fd)
Definition at line 518 of file evmap.c.
{
    struct evmap_io *ctx;
    GET_IO_SLOT(ctx, map, fd, evmap_io);
    if (ctx)
        return ((char*)ctx) + sizeof(struct evmap_io);
    else
        return NULL;
}
References ctx, and GET_IO_SLOT.
evmap_io_initmap_()
void evmap_io_initmap_ (struct event_io_map * ctx)
Initialize an event_map for use.
Definition at line 189 of file evmap.c.
{
    evmap_signal_initmap_(ctx);
}
References ctx, and evmap_signal_initmap_().
Referenced by event_base_new_with_config().
evmap_reinit_()
int evmap_reinit_ (struct event_base * base)
Definition at line 653 of file evmap.c.
{
    int result = 0;
    evmap_io_foreach_fd(base, evmap_io_reinit_iter_fn, &result);
    if (result < 0)
        return -1;
    evmap_signal_foreach_signal(base, evmap_signal_reinit_iter_fn, &result);
    if (result < 0)
        return -1;
    return 0;
}
References evmap_io_foreach_fd(), evmap_io_reinit_iter_fn(), evmap_signal_foreach_signal(), and evmap_signal_reinit_iter_fn().
Referenced by event_reinit().
evmap_signal_active_()
void evmap_signal_active_ (struct event_base * base, evutil_socket_t signum, int ncalls)
Definition at line 501 of file evmap.c.
{
    struct event_signal_map *map = &base->sigmap;
    struct evmap_signal *ctx;
    struct event *ev;
    if (sig < 0 || sig >= map->nentries)
        return;
    GET_SIGNAL_SLOT(ctx, map, sig, evmap_signal);
    if (!ctx)
        return;
    LIST_FOREACH(ev, &ctx->events, ev_signal_next)
        event_active_nolock_(ev, EV_SIGNAL, ncalls);
}
References ctx, ev_signal_next, event_active_nolock_(), GET_SIGNAL_SLOT, event_signal_map::nentries, and event_base::sigmap.
Referenced by event_base_active_by_signal(), and evsig_cb().
evmap_signal_add_()
int evmap_signal_add_ (struct event_base * base, int signum, struct event * ev)
Definition at line 450 of file evmap.c.
{
    const struct eventop *evsel = base->evsigsel;
    struct event_signal_map *map = &base->sigmap;
    struct evmap_signal *ctx = NULL;
    if (sig < 0 || sig >= NSIG)
        return (-1);
    if (sig >= map->nentries) {
        if (evmap_make_space(
            map, sig, sizeof(struct evmap_signal *)) == -1)
            return (-1);
    }
    GET_SIGNAL_SLOT_AND_CTOR(ctx, map, sig, evmap_signal, evmap_signal_init,
        base->evsigsel->fdinfo_len);
    if (LIST_EMPTY(&ctx->events)) {
        if (evsel->add(base, ev->ev_fd, 0, EV_SIGNAL, NULL)
            == -1)
            return (-1);
    }
    LIST_INSERT_HEAD(&ctx->events, ev, ev_signal_next);
    return (1);
}
References eventop::add, ctx, ev_signal_next, evmap_make_space(), evmap_signal_init(), event_base::evsigsel, eventop::fdinfo_len, GET_SIGNAL_SLOT_AND_CTOR, event_signal_map::nentries, and event_base::sigmap.
Referenced by event_add_nolock_().
evmap_signal_clear_()
void evmap_signal_clear_ (struct event_signal_map * ctx)
Definition at line 242 of file evmap.c.
{
    if (ctx->entries != NULL) {
        int i;
        for (i = 0; i < ctx->nentries; ++i) {
            if (ctx->entries[i] != NULL)
                mm_free(ctx->entries[i]);
        }
        mm_free(ctx->entries);
        ctx->entries = NULL;
    }
    ctx->nentries = 0;
}
References ctx, and mm_free.
Referenced by event_base_free_(), and evmap_io_clear_().
evmap_signal_del_()
int evmap_signal_del_ (struct event_base * base, int signum, struct event * ev)
Definition at line 479 of file evmap.c.
{
    const struct eventop *evsel = base->evsigsel;
    struct event_signal_map *map = &base->sigmap;
    struct evmap_signal *ctx;
    if (sig < 0 || sig >= map->nentries)
        return (-1);
    GET_SIGNAL_SLOT(ctx, map, sig, evmap_signal);
    LIST_REMOVE(ev, ev_signal_next);
    if (LIST_FIRST(&ctx->events) == NULL) {
        if (evsel->del(base, ev->ev_fd, 0, EV_SIGNAL, NULL) == -1)
            return (-1);
    }
    return (1);
}
References ctx, eventop::del, ev_signal_next, event_base::evsigsel, GET_SIGNAL_SLOT, event_signal_map::nentries, and event_base::sigmap.
Referenced by event_del_nolock_().
evmap_signal_initmap_()
void evmap_signal_initmap_ (struct event_signal_map * ctx)
Definition at line 235 of file evmap.c.
{
    ctx->nentries = 0;
    ctx->entries = NULL;
}
References ctx.
Referenced by event_base_new_with_config(), and evmap_io_initmap_().