libdogecoin: src/libevent/evrpc-internal.h File Reference
evrpc-internal.h File Reference
#include "event2/http.h"
#include "http-internal.h"
Data Structures
struct evrpc_hook
struct evrpc_hooks_
struct evrpc_base
struct evrpc_pool
struct evrpc_hook_ctx
struct evrpc_meta
struct evrpc_hook_meta
struct evrpc_req_generic
struct evrpc_request_wrapper
Macros
#define EVRPC_URI_PREFIX "/.rpc."
#define input_hooks common.in_hooks
#define output_hooks common.out_hooks
#define paused_requests common.pause_requests
Functions
TAILQ_HEAD (evrpc_hook_list, evrpc_hook)
TAILQ_HEAD (evrpc_pause_list, evrpc_hook_ctx)
void evrpc_reqstate_free_ (struct evrpc_req_generic *rpc_state)
TAILQ_HEAD (evrpc_meta_list, evrpc_meta)
static void evrpc_hook_associate_meta_ (struct evrpc_hook_meta **pctx, struct evhttp_connection *evcon)
static struct evrpc_hook_meta * evrpc_hook_meta_new_ (void)
static void evrpc_hook_context_free_ (struct evrpc_hook_meta *ctx)
Macro Definition Documentation
EVRPC_URI_PREFIX
#define EVRPC_URI_PREFIX "/.rpc."
Definition at line 36 of file evrpc-internal.h.
input_hooks
#define input_hooks common.in_hooks
Definition at line 68 of file evrpc-internal.h.
output_hooks
#define output_hooks common.out_hooks
Definition at line 69 of file evrpc-internal.h.
paused_requests
#define paused_requests common.pause_requests
Definition at line 70 of file evrpc-internal.h.
Function Documentation
evrpc_hook_associate_meta_()
static void evrpc_hook_associate_meta_ (struct evrpc_hook_meta ** pctx, struct evhttp_connection * evcon) static
evrpc_hook_context_free_()
static void evrpc_hook_context_free_ (struct evrpc_hook_meta * ctx) static
evrpc_hook_meta_new_()
static struct evrpc_hook_meta * evrpc_hook_meta_new_ (void) static
evrpc_reqstate_free_()
void evrpc_reqstate_free_ (struct evrpc_req_generic * rpc_state)
Definition at line 382 of file evrpc.c.
{
    struct evrpc *rpc;
    EVUTIL_ASSERT(rpc_state != NULL);
    rpc = rpc_state->rpc;
    /* clean up all memory */
    if (rpc_state->hook_meta != NULL)
        evrpc_hook_context_free_(rpc_state->hook_meta);
    if (rpc_state->request != NULL)
        rpc->request_free(rpc_state->request);
    if (rpc_state->reply != NULL)
        rpc->reply_free(rpc_state->reply);
    if (rpc_state->rpc_data != NULL)
        evbuffer_free(rpc_state->rpc_data);
    mm_free(rpc_state);
}
References evbuffer_free(), evrpc_hook_context_free_(), EVUTIL_ASSERT, evrpc_req_generic::hook_meta, mm_free, evrpc_req_generic::reply, evrpc_req_generic::request, evrpc_req_generic::rpc, and evrpc_req_generic::rpc_data.
Referenced by evrpc_request_cb(), evrpc_request_cb_closure(), evrpc_request_done(), and evrpc_request_done_closure().
TAILQ_HEAD() [1/3]
TAILQ_HEAD (evrpc_hook_list , evrpc_hook)
TAILQ_HEAD() [2/3]
TAILQ_HEAD (evrpc_meta_list , evrpc_meta)
TAILQ_HEAD() [3/3]
TAILQ_HEAD (evrpc_pause_list , evrpc_hook_ctx)