libdogecoin: src/libevent/evrpc.c File Reference
evrpc.c File Reference
#include "event2/event-config.h"
#include "evconfig-private.h"
#include <sys/types.h>
#include <sys/socket.h>
#include <sys/queue.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <errno.h>
#include <signal.h>
#include <string.h>
#include "event2/event.h"
#include "event2/event_struct.h"
#include "event2/rpc.h"
#include "event2/rpc_struct.h"
#include "evrpc-internal.h"
#include "event2/http.h"
#include "event2/buffer.h"
#include "event2/tag.h"
#include "event2/http_struct.h"
#include "event2/http_compat.h"
#include "event2/util.h"
#include "util-internal.h"
#include "log-internal.h"
#include "mm-internal.h"
Functions
struct evrpc_base * evrpc_init (struct evhttp *http_server)
void evrpc_free (struct evrpc_base *base)
void * evrpc_add_hook (void *vbase, enum EVRPC_HOOK_TYPE hook_type, int(*cb)(void *, struct evhttp_request *, struct evbuffer *, void *), void *cb_arg)
static int evrpc_remove_hook_internal (struct evrpc_hook_list *head, void *handle)
int evrpc_remove_hook (void *vbase, enum EVRPC_HOOK_TYPE hook_type, void *handle)
static int evrpc_process_hooks (struct evrpc_hook_list *head, void *ctx, struct evhttp_request *req, struct evbuffer *evbuf)
static void evrpc_pool_schedule (struct evrpc_pool *pool)
static void evrpc_request_cb (struct evhttp_request *, void *)
static char * evrpc_construct_uri (const char *uri)
int evrpc_register_rpc (struct evrpc_base *base, struct evrpc *rpc, void(*cb)(struct evrpc_req_generic *, void *), void *cb_arg)
int evrpc_unregister_rpc (struct evrpc_base *base, const char *name)
static int evrpc_pause_request (void *vbase, void *ctx, void(*cb)(void *, enum EVRPC_HOOK_RESULT))
static void evrpc_request_cb_closure (void *, enum EVRPC_HOOK_RESULT)
void evrpc_reqstate_free_ (struct evrpc_req_generic *rpc_state)
static void evrpc_request_done_closure (void *, enum EVRPC_HOOK_RESULT)
void evrpc_request_done (struct evrpc_req_generic *rpc_state)
void * evrpc_get_request (struct evrpc_req_generic *req)
void * evrpc_get_reply (struct evrpc_req_generic *req)
static int evrpc_schedule_request (struct evhttp_connection *connection, struct evrpc_request_wrapper *ctx)
struct evrpc_pool * evrpc_pool_new (struct event_base *base)
static void evrpc_request_wrapper_free (struct evrpc_request_wrapper *request)
void evrpc_pool_free (struct evrpc_pool *pool)
void evrpc_pool_add_connection (struct evrpc_pool *pool, struct evhttp_connection *connection)
void evrpc_pool_remove_connection (struct evrpc_pool *pool, struct evhttp_connection *connection)
void evrpc_pool_set_timeout (struct evrpc_pool *pool, int timeout_in_secs)
static void evrpc_reply_done (struct evhttp_request *, void *)
static void evrpc_request_timeout (evutil_socket_t, short, void *)
static struct evhttp_connection * evrpc_pool_find_connection (struct evrpc_pool *pool)
static void evrpc_schedule_request_closure (void *ctx, enum EVRPC_HOOK_RESULT)
int evrpc_resume_request (void *vbase, void *ctx, enum EVRPC_HOOK_RESULT res)
int evrpc_make_request (struct evrpc_request_wrapper *ctx)
struct evrpc_request_wrapper * evrpc_make_request_ctx (struct evrpc_pool *pool, void *request, void *reply, const char *rpcname, void(*req_marshal)(struct evbuffer *, void *), void(*rpl_clear)(void *), int(*rpl_unmarshal)(void *, struct evbuffer *), void(*cb)(struct evrpc_status *, void *, void *, void *), void *cbarg)
static void evrpc_reply_done_closure (void *, enum EVRPC_HOOK_RESULT)
static void evrpc_meta_data_free (struct evrpc_meta_list *meta_data)
static struct evrpc_hook_meta * evrpc_hook_meta_new_ (void)
static void evrpc_hook_associate_meta_ (struct evrpc_hook_meta **pctx, struct evhttp_connection *evcon)
static void evrpc_hook_context_free_ (struct evrpc_hook_meta *ctx)
void evrpc_hook_add_meta (void *ctx, const char *key, const void *data, size_t data_size)
int evrpc_hook_find_meta (void *ctx, const char *key, void **data, size_t *data_size)
struct evhttp_connection * evrpc_hook_get_connection (void *ctx)
int evrpc_send_request_generic (struct evrpc_pool *pool, void *request, void *reply, void(*cb)(struct evrpc_status *, void *, void *, void *), void *cb_arg, const char *rpcname, void(*req_marshal)(struct evbuffer *, void *), void(*rpl_clear)(void *), int(*rpl_unmarshal)(void *, struct evbuffer *))
static struct evrpc * evrpc_register_object (const char *name, void *(*req_new)(void *), void *req_new_arg, void(*req_free)(void *), int(*req_unmarshal)(void *, struct evbuffer *), void *(*rpl_new)(void *), void *rpl_new_arg, void(*rpl_free)(void *), int(*rpl_complete)(void *), void(*rpl_marshal)(struct evbuffer *, void *))
int evrpc_register_generic (struct evrpc_base *base, const char *name, void(*callback)(struct evrpc_req_generic *, void *), void *cbarg, void *(*req_new)(void *), void *req_new_arg, void(*req_free)(void *), int(*req_unmarshal)(void *, struct evbuffer *), void *(*rpl_new)(void *), void *rpl_new_arg, void(*rpl_free)(void *), int(*rpl_complete)(void *), void(*rpl_marshal)(struct evbuffer *, void *))
struct evrpc_pool * evrpc_request_get_pool (struct evrpc_request_wrapper *ctx)
void evrpc_request_set_pool (struct evrpc_request_wrapper *ctx, struct evrpc_pool *pool)
void evrpc_request_set_cb (struct evrpc_request_wrapper *ctx, void(*cb)(struct evrpc_status *, void *request, void *reply, void *arg), void *cb_arg)
Function Documentation
evrpc_add_hook()
void * evrpc_add_hook (void * vbase, enum EVRPC_HOOK_TYPE hook_type, int(*)(void *, struct evhttp_request *, struct evbuffer *, void *) cb, void * cb_arg)
Definition at line 120 of file evrpc.c.
{
    struct evrpc_hooks_ *base = vbase;
    struct evrpc_hook_list *head = NULL;
    struct evrpc_hook *hook = NULL;
    switch (hook_type) {
    case EVRPC_INPUT:
        head = &base->in_hooks;
        break;
    case EVRPC_OUTPUT:
        head = &base->out_hooks;
        break;
    default:
        EVUTIL_ASSERT(hook_type == EVRPC_INPUT || hook_type == EVRPC_OUTPUT);
    }
    hook = mm_calloc(1, sizeof(struct evrpc_hook));
    EVUTIL_ASSERT(hook != NULL);
    hook->process = cb;
    hook->process_arg = cb_arg;
    TAILQ_INSERT_TAIL(head, hook, next);
    return (hook);
}
References EVUTIL_ASSERT, evrpc_hooks_::in_hooks, mm_calloc, evrpc_hooks_::out_hooks, evrpc_hook::process, and evrpc_hook::process_arg.
evrpc_construct_uri()
static char * evrpc_construct_uri (const char * uri) static
Definition at line 211 of file evrpc.c.
{
    char *constructed_uri;
    size_t constructed_uri_len;
    constructed_uri_len = strlen(EVRPC_URI_PREFIX) + strlen(uri) + 1;
    if ((constructed_uri = mm_malloc(constructed_uri_len)) == NULL)
        event_err(1, "%s: failed to register rpc at %s",
            __func__, uri);
    memcpy(constructed_uri, EVRPC_URI_PREFIX, strlen(EVRPC_URI_PREFIX));
    memcpy(constructed_uri + strlen(EVRPC_URI_PREFIX), uri, strlen(uri));
    constructed_uri[constructed_uri_len - 1] = '\0';
    return (constructed_uri);
}
References __func__, event_err(), EVRPC_URI_PREFIX, and mm_malloc.
Referenced by evrpc_register_rpc(), evrpc_schedule_request_closure(), and evrpc_unregister_rpc().
evrpc_free()
void evrpc_free (struct evrpc_base * base)
Definition at line 93 of file evrpc.c.
{
    struct evrpc *rpc;
    struct evrpc_hook *hook;
    struct evrpc_hook_ctx *pause;
    int r;
    while ((rpc = TAILQ_FIRST(&base->registered_rpcs)) != NULL) {
        r = evrpc_unregister_rpc(base, rpc->uri);
        EVUTIL_ASSERT(r == 0);
    }
    while ((pause = TAILQ_FIRST(&base->paused_requests)) != NULL) {
        TAILQ_REMOVE(&base->paused_requests, pause, next);
        mm_free(pause);
    }
    while ((hook = TAILQ_FIRST(&base->input_hooks)) != NULL) {
        r = evrpc_remove_hook(base, EVRPC_INPUT, hook);
        EVUTIL_ASSERT(r);
    }
    while ((hook = TAILQ_FIRST(&base->output_hooks)) != NULL) {
        r = evrpc_remove_hook(base, EVRPC_OUTPUT, hook);
        EVUTIL_ASSERT(r);
    }
    mm_free(base);
}
References evrpc_remove_hook(), evrpc_unregister_rpc(), EVUTIL_ASSERT, mm_free, and TAILQ_FIRST.
evrpc_get_reply()
void * evrpc_get_reply (struct evrpc_req_generic * req)
Definition at line 468 of file evrpc.c.
{
    return req->reply;
}
References evrpc_req_generic::reply.
evrpc_get_request()
void * evrpc_get_request (struct evrpc_req_generic * req)
Definition at line 462 of file evrpc.c.
{
    return req->request;
}
References evrpc_req_generic::request.
evrpc_hook_add_meta()
void evrpc_hook_add_meta (void * ctx, const char * key, const void * data, size_t data_size)
Definition at line 1029 of file evrpc.c.
{
    struct evrpc_request_wrapper *req = ctx;
    struct evrpc_hook_meta *store = NULL;
    struct evrpc_meta *meta = NULL;
    if ((store = req->hook_meta) == NULL)
        store = req->hook_meta = evrpc_hook_meta_new_();
    meta = mm_malloc(sizeof(struct evrpc_meta));
    EVUTIL_ASSERT(meta != NULL);
    meta->key = mm_strdup(key);
    EVUTIL_ASSERT(meta->key != NULL);
    meta->data_size = data_size;
    meta->data = mm_malloc(data_size);
    EVUTIL_ASSERT(meta->data != NULL);
    memcpy(meta->data, data, data_size);
    TAILQ_INSERT_TAIL(&store->meta_data, meta, next);
}
References ctx, evrpc_meta::data, evrpc_meta::data_size, evrpc_hook_meta_new_(), EVUTIL_ASSERT, evrpc_request_wrapper::hook_meta, evrpc_meta::key, evrpc_hook_meta::meta_data, mm_malloc, mm_strdup, and evrpc_request_wrapper::req.
evrpc_hook_associate_meta_()
static void evrpc_hook_associate_meta_ (struct evrpc_hook_meta ** pctx, struct evhttp_connection * evcon) static
Definition at line 1011 of file evrpc.c.
{
    struct evrpc_hook_meta *ctx = *pctx;
    if (ctx == NULL)
        *pctx = ctx = evrpc_hook_meta_new_();
    ctx->evcon = evcon;
}
References ctx, evrpc_hook_meta::evcon, and evrpc_hook_meta_new_().
Referenced by evrpc_reply_done(), evrpc_request_cb(), evrpc_request_done(), and evrpc_schedule_request().
evrpc_hook_context_free_()
static void evrpc_hook_context_free_ (struct evrpc_hook_meta * ctx) static
Definition at line 1021 of file evrpc.c.
{
    evrpc_meta_data_free(&ctx->meta_data);
    mm_free(ctx);
}
References ctx, evrpc_meta_data_free(), and mm_free.
Referenced by evrpc_reqstate_free_(), and evrpc_request_wrapper_free().
evrpc_hook_find_meta()
int evrpc_hook_find_meta (void * ctx, const char * key, void ** data, size_t * data_size)
Definition at line 1052 of file evrpc.c.
{
    struct evrpc_request_wrapper *req = ctx;
    struct evrpc_meta *meta = NULL;
    if (req->hook_meta == NULL)
        return (-1);
    TAILQ_FOREACH(meta, &req->hook_meta->meta_data, next) {
        if (strcmp(meta->key, key) == 0) {
            *data = meta->data;
            *data_size = meta->data_size;
            return (0);
        }
    }
    return (-1);
}
References ctx, evrpc_meta::data, evrpc_meta::data_size, evrpc_request_wrapper::hook_meta, evrpc_meta::key, evrpc_hook_meta::meta_data, evrpc_request_wrapper::req, and TAILQ_FOREACH.
evrpc_hook_get_connection()
struct evhttp_connection * evrpc_hook_get_connection (void * ctx)
Definition at line 1072 of file evrpc.c.
{
    struct evrpc_request_wrapper *req = ctx;
    return (req->hook_meta != NULL ? req->hook_meta->evcon : NULL);
}
References ctx, and evrpc_request_wrapper::req.
evrpc_hook_meta_new_()
static struct evrpc_hook_meta * evrpc_hook_meta_new_ (void) static
Definition at line 998 of file evrpc.c.
{
    struct evrpc_hook_meta *ctx;
    ctx = mm_malloc(sizeof(struct evrpc_hook_meta));
    EVUTIL_ASSERT(ctx != NULL);
    TAILQ_INIT(&ctx->meta_data);
    ctx->evcon = NULL;
    return (ctx);
}
References ctx, EVUTIL_ASSERT, and mm_malloc.
Referenced by evrpc_hook_add_meta(), and evrpc_hook_associate_meta_().
evrpc_init()
struct evrpc_base * evrpc_init (struct evhttp * http_server)
Definition at line 72 of file evrpc.c.
{
    struct evrpc_base* base = mm_calloc(1, sizeof(struct evrpc_base));
    if (base == NULL)
        return (NULL);
    /* we rely on the tagging sub system */
    evtag_init();
    TAILQ_INIT(&base->registered_rpcs);
    TAILQ_INIT(&base->input_hooks);
    TAILQ_INIT(&base->output_hooks);
    TAILQ_INIT(&base->paused_requests);
    base->http_server = http_server;
    return (base);
}
References evtag_init(), evrpc_base::http_server, and mm_calloc.
evrpc_make_request()
int evrpc_make_request (struct evrpc_request_wrapper * ctx)
Definition at line 800 of file evrpc.c.
{
    struct evrpc_pool *pool = ctx->pool;
    /* initialize the event structure for this rpc */
    evtimer_assign(&ctx->ev_timeout, pool->base, evrpc_request_timeout, ctx);
    /* we better have some available connections on the pool */
    EVUTIL_ASSERT(TAILQ_FIRST(&pool->connections) != NULL);
    /*
     * if no connection is available, we queue the request on the pool,
     * the next time a connection is empty, the rpc will be send on that.
     */
    TAILQ_INSERT_TAIL(&pool->requests, ctx, next);
    evrpc_pool_schedule(pool);
    return (0);
}
References evrpc_pool::base, evrpc_pool::connections, ctx, evrpc_pool_schedule(), evrpc_request_timeout(), EVUTIL_ASSERT, and TAILQ_FIRST.
Referenced by evrpc_send_request_generic().
evrpc_make_request_ctx()
struct evrpc_request_wrapper * evrpc_make_request_ctx (struct evrpc_pool * pool, void * request, void * reply, const char * rpcname, void(*)(struct evbuffer *, void *) req_marshal, void(*)(void *) rpl_clear, int(*)(void *, struct evbuffer *) rpl_unmarshal, void(*)(struct evrpc_status *, void *, void *, void *) cb, void * cbarg)
Definition at line 823 of file evrpc.c.
{
    struct evrpc_request_wrapper *ctx = (struct evrpc_request_wrapper *)
        mm_malloc(sizeof(struct evrpc_request_wrapper));
    if (ctx == NULL)
        return (NULL);
    ctx->pool = pool;
    ctx->hook_meta = NULL;
    ctx->evcon = NULL;
    ctx->name = mm_strdup(rpcname);
    if (ctx->name == NULL) {
        mm_free(ctx);
        return (NULL);
    }
    ctx->cb = cb;
    ctx->cb_arg = cbarg;
    ctx->request = request;
    ctx->reply = reply;
    ctx->request_marshal = req_marshal;
    ctx->reply_clear = rpl_clear;
    ctx->reply_unmarshal = rpl_unmarshal;
    return (ctx);
}
References evrpc_request_wrapper::cb, ctx, mm_free, mm_malloc, mm_strdup, evrpc_request_wrapper::pool, evrpc_request_wrapper::reply, and evrpc_request_wrapper::request.
Referenced by evrpc_send_request_generic().
evrpc_meta_data_free()
static void evrpc_meta_data_free (struct evrpc_meta_list * meta_data) static
Definition at line 984 of file evrpc.c.
{
    struct evrpc_meta *entry;
    EVUTIL_ASSERT(meta_data != NULL);
    while ((entry = TAILQ_FIRST(meta_data)) != NULL) {
        TAILQ_REMOVE(meta_data, entry, next);
        mm_free(entry->key);
        mm_free(entry->data);
        mm_free(entry);
    }
}
References evrpc_meta::data, EVUTIL_ASSERT, evrpc_meta::key, mm_free, and TAILQ_FIRST.
Referenced by evrpc_hook_context_free_().
evrpc_pause_request()
static int evrpc_pause_request (void * vbase, void * ctx, void(*)(void *, enum EVRPC_HOOK_RESULT) cb) static
Definition at line 763 of file evrpc.c.
{
    struct evrpc_hooks_ *base = vbase;
    struct evrpc_hook_ctx *pause = mm_malloc(sizeof(*pause));
    if (pause == NULL)
        return (-1);
    pause->ctx = ctx;
    pause->cb = cb;
    TAILQ_INSERT_TAIL(&base->pause_requests, pause, next);
    return (0);
}
References evrpc_hook_ctx::cb, evrpc_hook_ctx::ctx, ctx, mm_malloc, and evrpc_hooks_::pause_requests.
Referenced by evrpc_reply_done(), evrpc_request_cb(), evrpc_request_done(), and evrpc_schedule_request().
evrpc_pool_add_connection()
void evrpc_pool_add_connection (struct evrpc_pool * pool, struct evhttp_connection * connection)
Definition at line 580 of file evrpc.c.
{
    EVUTIL_ASSERT(connection->http_server == NULL);
    TAILQ_INSERT_TAIL(&pool->connections, connection, next);
    /*
     * associate an event base with this connection
     */
    if (pool->base != NULL)
        evhttp_connection_set_base(connection, pool->base);
    /*
     * unless a timeout was specifically set for a connection,
     * the connection inherits the timeout from the pool.
     */
    if (!evutil_timerisset(&connection->timeout))
        evhttp_connection_set_timeout(connection, pool->timeout);
    /*
     * if we have any requests pending, schedule them with the new
     * connections.
     */
    if (TAILQ_FIRST(&pool->requests) != NULL) {
        struct evrpc_request_wrapper *request =
            TAILQ_FIRST(&pool->requests);
        TAILQ_REMOVE(&pool->requests, request, next);
        evrpc_schedule_request(connection, request);
    }
}
References evrpc_pool::base, evrpc_pool::connections, evhttp_connection_set_base(), evhttp_connection_set_timeout(), evrpc_schedule_request(), EVUTIL_ASSERT, evhttp_connection::http_server, evrpc_request_wrapper::pool, TAILQ_FIRST, evrpc_pool::timeout, and evhttp_connection::timeout.
evrpc_pool_find_connection()
static struct evhttp_connection * evrpc_pool_find_connection (struct evrpc_pool * pool) static
Definition at line 638 of file evrpc.c.
{
    struct evhttp_connection *connection;
    TAILQ_FOREACH(connection, &pool->connections, next) {
        if (TAILQ_FIRST(&connection->requests) == NULL)
            return (connection);
    }
    return (NULL);
}
References evrpc_pool::connections, TAILQ_FIRST, and TAILQ_FOREACH.
Referenced by evrpc_pool_schedule().
evrpc_pool_free()
void evrpc_pool_free (struct evrpc_pool * pool)
Definition at line 538 of file evrpc.c.
{
    struct evhttp_connection *connection;
    struct evrpc_request_wrapper *request;
    struct evrpc_hook_ctx *pause;
    struct evrpc_hook *hook;
    int r;
    while ((request = TAILQ_FIRST(&pool->requests)) != NULL) {
        TAILQ_REMOVE(&pool->requests, request, next);
        evrpc_request_wrapper_free(request);
    }
    while ((pause = TAILQ_FIRST(&pool->paused_requests)) != NULL) {
        TAILQ_REMOVE(&pool->paused_requests, pause, next);
        mm_free(pause);
    }
    while ((connection = TAILQ_FIRST(&pool->connections)) != NULL) {
        TAILQ_REMOVE(&pool->connections, connection, next);
        evhttp_connection_free(connection);
    }
    while ((hook = TAILQ_FIRST(&pool->input_hooks)) != NULL) {
        r = evrpc_remove_hook(pool, EVRPC_INPUT, hook);
        EVUTIL_ASSERT(r);
    }
    while ((hook = TAILQ_FIRST(&pool->output_hooks)) != NULL) {
        r = evrpc_remove_hook(pool, EVRPC_OUTPUT, hook);
        EVUTIL_ASSERT(r);
    }
    mm_free(pool);
}
References evrpc_pool::connections, evhttp_connection_free(), evrpc_remove_hook(), evrpc_request_wrapper_free(), EVUTIL_ASSERT, mm_free, evrpc_request_wrapper::request, and TAILQ_FIRST.
evrpc_pool_new()
struct evrpc_pool * evrpc_pool_new (struct event_base * base)
Definition at line 508 of file evrpc.c.
{
    struct evrpc_pool *pool = mm_calloc(1, sizeof(struct evrpc_pool));
    if (pool == NULL)
        return (NULL);
    TAILQ_INIT(&pool->connections);
    TAILQ_INIT(&pool->requests);
    TAILQ_INIT(&pool->paused_requests);
    TAILQ_INIT(&pool->input_hooks);
    TAILQ_INIT(&pool->output_hooks);
    pool->base = base;
    pool->timeout = -1;
    return (pool);
}
References evrpc_pool::base, evrpc_pool::connections, mm_calloc, and evrpc_pool::timeout.
evrpc_pool_remove_connection()
void evrpc_pool_remove_connection (struct evrpc_pool * pool, struct evhttp_connection * connection)
Definition at line 613 of file evrpc.c.
{
    TAILQ_REMOVE(&pool->connections, connection, next);
}
References evrpc_pool::connections, and evrpc_request_wrapper::pool.
evrpc_pool_schedule()
static void evrpc_pool_schedule (struct evrpc_pool * pool) static
Definition at line 954 of file evrpc.c.
{
    struct evrpc_request_wrapper *ctx = TAILQ_FIRST(&pool->requests);
    struct evhttp_connection *evcon;
    /* if no requests are pending, we have no work */
    if (ctx == NULL)
        return;
    if ((evcon = evrpc_pool_find_connection(pool)) != NULL) {
        TAILQ_REMOVE(&pool->requests, ctx, next);
        evrpc_schedule_request(evcon, ctx);
    }
}
References ctx, evrpc_pool_find_connection(), evrpc_schedule_request(), evrpc_request_wrapper::pool, and TAILQ_FIRST.
Referenced by evrpc_make_request(), and evrpc_reply_done_closure().
evrpc_pool_set_timeout()
void evrpc_pool_set_timeout (struct evrpc_pool * pool, int timeout_in_secs)
Definition at line 620 of file evrpc.c.
{
    struct evhttp_connection *evcon;
    TAILQ_FOREACH(evcon, &pool->connections, next) {
        evhttp_connection_set_timeout(evcon, timeout_in_secs);
    }
    pool->timeout = timeout_in_secs;
}
References evrpc_pool::connections, evhttp_connection_set_timeout(), TAILQ_FOREACH, and evrpc_pool::timeout.
evrpc_process_hooks()
static int evrpc_process_hooks (struct evrpc_hook_list * head, void * ctx, struct evhttp_request * req, struct evbuffer * evbuf) static
Definition at line 188 of file evrpc.c.
{
    struct evrpc_hook *hook;
    TAILQ_FOREACH(hook, head, next) {
        int res = hook->process(ctx, req, evbuf, hook->process_arg);
        if (res != EVRPC_CONTINUE)
            return (res);
    }
    return (EVRPC_CONTINUE);
}
References ctx, evrpc_hook::process, evrpc_hook::process_arg, and TAILQ_FOREACH.
Referenced by evrpc_reply_done(), evrpc_request_cb(), evrpc_request_done(), and evrpc_schedule_request().
evrpc_register_generic()
int evrpc_register_generic (struct evrpc_base * base, const char * name, void(*)(struct evrpc_req_generic *, void *) callback, void * cbarg, void *(*)(void *) req_new, void * req_new_arg, void(*)(void *) req_free, int(*)(void *, struct evbuffer *) req_unmarshal, void *(*)(void *) rpl_new, void * rpl_new_arg, void(*)(void *) rpl_free, int(*)(void *) rpl_complete, void(*)(struct evbuffer *, void *) rpl_marshal)
Definition at line 1132 of file evrpc.c.
{
    struct evrpc* rpc =
        evrpc_register_object(name, req_new, req_new_arg, req_free, req_unmarshal,
        rpl_new, rpl_new_arg, rpl_free, rpl_complete, rpl_marshal);
    if (rpc == NULL)
        return (-1);
    evrpc_register_rpc(base, rpc,
        (void (*)(struct evrpc_req_generic*, void *))callback, cbarg);
    return (0);
}
References evrpc_register_object(), and evrpc_register_rpc().
evrpc_register_object()
static struct evrpc * evrpc_register_object (const char * name, void *(*)(void *) req_new, void * req_new_arg, void(*)(void *) req_free, int(*)(void *, struct evbuffer *) req_unmarshal, void *(*)(void *) rpl_new, void * rpl_new_arg, void(*)(void *) rpl_free, int(*)(void *) rpl_complete, void(*)(struct evbuffer *, void *) rpl_marshal) static
Takes a request object and fills it in with the right magic
Definition at line 1104 of file evrpc.c.
{
    struct evrpc* rpc = (struct evrpc *)mm_calloc(1, sizeof(struct evrpc));
    if (rpc == NULL)
        return (NULL);
    rpc->uri = mm_strdup(name);
    if (rpc->uri == NULL) {
        mm_free(rpc);
        return (NULL);
    }
    rpc->request_new = req_new;
    rpc->request_new_arg = req_new_arg;
    rpc->request_free = req_free;
    rpc->request_unmarshal = req_unmarshal;
    rpc->reply_new = rpl_new;
    rpc->reply_new_arg = rpl_new_arg;
    rpc->reply_free = rpl_free;
    rpc->reply_complete = rpl_complete;
    rpc->reply_marshal = rpl_marshal;
    return (rpc);
}
References mm_calloc, mm_free, and mm_strdup.
Referenced by evrpc_register_generic().
evrpc_register_rpc()
int evrpc_register_rpc (struct evrpc_base * base, struct evrpc * rpc, void(*)(struct evrpc_req_generic *, void *) cb, void * cb_arg)
Definition at line 228 of file evrpc.c.
{
    char *constructed_uri = evrpc_construct_uri(rpc->uri);
    rpc->base = base;
    rpc->cb = cb;
    rpc->cb_arg = cb_arg;
    TAILQ_INSERT_TAIL(&base->registered_rpcs, rpc, next);
    evhttp_set_cb(base->http_server,
        constructed_uri,
        evrpc_request_cb,
        rpc);
    mm_free(constructed_uri);
    return (0);
}
References evhttp_set_cb(), evrpc_construct_uri(), evrpc_request_cb(), evrpc_base::http_server, and mm_free.
Referenced by evrpc_register_generic().
evrpc_remove_hook()
int evrpc_remove_hook (void * vbase, enum EVRPC_HOOK_TYPE hook_type, void * handle)
Definition at line 169 of file evrpc.c.
{
    struct evrpc_hooks_ *base = vbase;
    struct evrpc_hook_list *head = NULL;
    switch (hook_type) {
    case EVRPC_INPUT:
        head = &base->in_hooks;
        break;
    case EVRPC_OUTPUT:
        head = &base->out_hooks;
        break;
    default:
        EVUTIL_ASSERT(hook_type == EVRPC_INPUT || hook_type == EVRPC_OUTPUT);
    }
    return (evrpc_remove_hook_internal(head, handle));
}
References evrpc_remove_hook_internal(), EVUTIL_ASSERT, evrpc_hooks_::in_hooks, and evrpc_hooks_::out_hooks.
Referenced by evrpc_free(), and evrpc_pool_free().
evrpc_remove_hook_internal()
static int evrpc_remove_hook_internal (struct evrpc_hook_list * head, void * handle) static
Definition at line 150 of file evrpc.c.
{
    struct evrpc_hook *hook = NULL;
    TAILQ_FOREACH(hook, head, next) {
        if (hook == handle) {
            TAILQ_REMOVE(head, hook, next);
            mm_free(hook);
            return (1);
        }
    }
    return (0);
}
References mm_free, and TAILQ_FOREACH.
Referenced by evrpc_remove_hook().
evrpc_reply_done()
static void evrpc_reply_done (struct evhttp_request * req, void * arg) static
Definition at line 860 of file evrpc.c.
{
    struct evrpc_request_wrapper *ctx = arg;
    struct evrpc_pool *pool = ctx->pool;
    int hook_res = EVRPC_CONTINUE;
    /* cancel any timeout we might have scheduled */
    event_del(&ctx->ev_timeout);
    ctx->req = req;
    /* we need to get the reply now */
    if (req == NULL) {
        evrpc_reply_done_closure(ctx, EVRPC_CONTINUE);
        return;
    }
    if (TAILQ_FIRST(&pool->input_hooks) != NULL) {
        evrpc_hook_associate_meta_(&ctx->hook_meta, ctx->evcon);
        /* apply hooks to the incoming request */
        hook_res = evrpc_process_hooks(&pool->input_hooks,
            ctx, req, req->input_buffer);
        switch (hook_res) {
        case EVRPC_TERMINATE:
        case EVRPC_CONTINUE:
            break;
        case EVRPC_PAUSE:
            /*
             * if we get paused we also need to know the
             * request.  unfortunately, the underlying
             * layer is going to free it.  we need to
             * request ownership explicitly
             */
            evhttp_request_own(req);
            evrpc_pause_request(pool, ctx,
                evrpc_reply_done_closure);
            return;
        default:
            EVUTIL_ASSERT(hook_res == EVRPC_TERMINATE ||
                hook_res == EVRPC_CONTINUE ||
                hook_res == EVRPC_PAUSE);
        }
    }
    evrpc_reply_done_closure(ctx, hook_res);
    /* http request is being freed by underlying layer */
}
References ctx, event_del(), evhttp_request_own(), evrpc_hook_associate_meta_(), evrpc_pause_request(), evrpc_process_hooks(), evrpc_reply_done_closure(), EVUTIL_ASSERT, and TAILQ_FIRST.
Referenced by evrpc_schedule_request().
evrpc_reply_done_closure()
static void evrpc_reply_done_closure (void * arg, enum EVRPC_HOOK_RESULT hook_res) static
Definition at line 913 of file evrpc.c.
{
    struct evrpc_request_wrapper *ctx = arg;
    struct evhttp_request *req = ctx->req;
    struct evrpc_pool *pool = ctx->pool;
    struct evrpc_status status;
    int res = -1;
    memset(&status, 0, sizeof(status));
    status.http_req = req;
    /* we need to get the reply now */
    if (req == NULL) {
        status.error = EVRPC_STATUS_ERR_TIMEOUT;
    } else if (hook_res == EVRPC_TERMINATE) {
        status.error = EVRPC_STATUS_ERR_HOOKABORTED;
    } else {
        res = ctx->reply_unmarshal(ctx->reply, req->input_buffer);
        if (res == -1)
            status.error = EVRPC_STATUS_ERR_BADPAYLOAD;
    }
    if (res == -1) {
        /* clear everything that we might have written previously */
        ctx->reply_clear(ctx->reply);
    }
    (*ctx->cb)(&status, ctx->request, ctx->reply, ctx->cb_arg);
    evrpc_request_wrapper_free(ctx);
    /* the http layer owned the original request structure, but if we
     * got paused, we asked for ownership and need to free it here. */
    if (req != NULL && evhttp_request_is_owned(req))
        evhttp_request_free(req);
    /* see if we can schedule another request */
    evrpc_pool_schedule(pool);
}
References ctx, evhttp_request_free(), evhttp_request_is_owned(), evrpc_pool_schedule(), and evrpc_request_wrapper_free().
Referenced by evrpc_reply_done().
evrpc_reqstate_free_()
void evrpc_reqstate_free_ (struct evrpc_req_generic * rpc_state)
Definition at line 382 of file evrpc.c.
{
    struct evrpc *rpc;
    EVUTIL_ASSERT(rpc_state != NULL);
    rpc = rpc_state->rpc;
    /* clean up all memory */
    if (rpc_state->hook_meta != NULL)
        evrpc_hook_context_free_(rpc_state->hook_meta);
    if (rpc_state->request != NULL)
        rpc->request_free(rpc_state->request);
    if (rpc_state->reply != NULL)
        rpc->reply_free(rpc_state->reply);
    if (rpc_state->rpc_data != NULL)
        evbuffer_free(rpc_state->rpc_data);
    mm_free(rpc_state);
}
References evbuffer_free(), evrpc_hook_context_free_(), EVUTIL_ASSERT, evrpc_req_generic::hook_meta, mm_free, evrpc_req_generic::reply, evrpc_req_generic::request, evrpc_req_generic::rpc, and evrpc_req_generic::rpc_data.
Referenced by evrpc_request_cb(), evrpc_request_cb_closure(), evrpc_request_done(), and evrpc_request_done_closure().
evrpc_request_cb()
static void evrpc_request_cb (struct evhttp_request * req, void * arg) static
Definition at line 285 of file evrpc.c.
{
    struct evrpc *rpc = arg;
    struct evrpc_req_generic *rpc_state = NULL;
    /* let's verify the outside parameters */
    if (req->type != EVHTTP_REQ_POST ||
        evbuffer_get_length(req->input_buffer) <= 0)
        goto error;
    rpc_state = mm_calloc(1, sizeof(struct evrpc_req_generic));
    if (rpc_state == NULL)
        goto error;
    rpc_state->rpc = rpc;
    rpc_state->http_req = req;
    rpc_state->rpc_data = NULL;
    if (TAILQ_FIRST(&rpc->base->input_hooks) != NULL) {
        int hook_res;
        evrpc_hook_associate_meta_(&rpc_state->hook_meta, req->evcon);
        /*
         * allow hooks to modify the outgoing request
         */
        hook_res = evrpc_process_hooks(&rpc->base->input_hooks,
            rpc_state, req, req->input_buffer);
        switch (hook_res) {
        case EVRPC_TERMINATE:
            goto error;
        case EVRPC_PAUSE:
            evrpc_pause_request(rpc->base, rpc_state,
                evrpc_request_cb_closure);
            return;
        case EVRPC_CONTINUE:
            break;
        default:
            EVUTIL_ASSERT(hook_res == EVRPC_TERMINATE ||
                hook_res == EVRPC_CONTINUE ||
                hook_res == EVRPC_PAUSE);
        }
    }
    evrpc_request_cb_closure(rpc_state, EVRPC_CONTINUE);
    return;
error:
    if (rpc_state)
        evrpc_reqstate_free_(rpc_state);
    evhttp_send_error(req, HTTP_SERVUNAVAIL, NULL);
    return;
}
References evbuffer_get_length(), evrpc_hook_meta::evcon, evhttp_send_error(), evrpc_hook_associate_meta_(), evrpc_pause_request(), evrpc_process_hooks(), evrpc_reqstate_free_(), evrpc_request_cb_closure(), EVUTIL_ASSERT, evrpc_req_generic::hook_meta, evrpc_req_generic::http_req, mm_calloc, evrpc_req_generic::rpc, evrpc_req_generic::rpc_data, and TAILQ_FIRST.
Referenced by evrpc_register_rpc().
evrpc_request_cb_closure()
static void evrpc_request_cb_closure (void * arg, enum EVRPC_HOOK_RESULT hook_res) static
Definition at line 339 of file evrpc.c.
{
    struct evrpc_req_generic *rpc_state = arg;
    struct evrpc *rpc;
    struct evhttp_request *req;
    EVUTIL_ASSERT(rpc_state);
    rpc = rpc_state->rpc;
    req = rpc_state->http_req;
    if (hook_res == EVRPC_TERMINATE)
        goto error;
    /* let's check that we can parse the request */
    rpc_state->request = rpc->request_new(rpc->request_new_arg);
    if (rpc_state->request == NULL)
        goto error;
    if (rpc->request_unmarshal(
            rpc_state->request, req->input_buffer) == -1) {
        /* we failed to parse the request; that's a bummer */
        goto error;
    }
    /* at this point, we have a well formed request, prepare the reply */
    rpc_state->reply = rpc->reply_new(rpc->reply_new_arg);
    if (rpc_state->reply == NULL)
        goto error;
    /* give the rpc to the user; they can deal with it */
    rpc->cb(rpc_state, rpc->cb_arg);
    return;
error:
    evrpc_reqstate_free_(rpc_state);
    evhttp_send_error(req, HTTP_SERVUNAVAIL, NULL);
    return;
}
References evhttp_send_error(), evrpc_reqstate_free_(), EVUTIL_ASSERT, evrpc_req_generic::http_req, evrpc_req_generic::reply, evrpc_req_generic::request, and evrpc_req_generic::rpc.
Referenced by evrpc_request_cb().
evrpc_request_done()
void evrpc_request_done (struct evrpc_req_generic * rpc_state)
Definition at line 404 of file evrpc.c.
{
    struct evhttp_request *req;
    struct evrpc *rpc;
    EVUTIL_ASSERT(rpc_state);
    req = rpc_state->http_req;
    rpc = rpc_state->rpc;
    if (rpc->reply_complete(rpc_state->reply) == -1) {
        /* the reply was not completely filled in.  error out */
        goto error;
    }
    if ((rpc_state->rpc_data = evbuffer_new()) == NULL) {
        /* out of memory */
        goto error;
    }
    /* serialize the reply */
    rpc->reply_marshal(rpc_state->rpc_data, rpc_state->reply);
    if (TAILQ_FIRST(&rpc->base->output_hooks) != NULL) {
        int hook_res;
        evrpc_hook_associate_meta_(&rpc_state->hook_meta, req->evcon);
        /* do hook based tweaks to the request */
        hook_res = evrpc_process_hooks(&rpc->base->output_hooks,
            rpc_state, req, rpc_state->rpc_data);
        switch (hook_res) {
        case EVRPC_TERMINATE:
            goto error;
        case EVRPC_PAUSE:
            if (evrpc_pause_request(rpc->base, rpc_state,
                evrpc_request_done_closure) == -1)
                goto error;
            return;
        case EVRPC_CONTINUE:
            break;
        default:
            EVUTIL_ASSERT(hook_res == EVRPC_TERMINATE ||
                hook_res == EVRPC_CONTINUE ||
                hook_res == EVRPC_PAUSE);
        }
    }
    evrpc_request_done_closure(rpc_state, EVRPC_CONTINUE);
    return;
error:
    evrpc_reqstate_free_(rpc_state);
    evhttp_send_error(req, HTTP_SERVUNAVAIL, NULL);
    return;
}
References evbuffer_new(), evrpc_hook_meta::evcon, evhttp_send_error(), evrpc_hook_associate_meta_(), evrpc_pause_request(), evrpc_process_hooks(), evrpc_reqstate_free_(), evrpc_request_done_closure(), EVUTIL_ASSERT, evrpc_req_generic::hook_meta, evrpc_req_generic::http_req, evrpc_req_generic::reply, evrpc_req_generic::rpc, evrpc_req_generic::rpc_data, and TAILQ_FIRST.
evrpc_request_done_closure()
static void evrpc_request_done_closure (void * arg, enum EVRPC_HOOK_RESULT hook_res) static
Definition at line 474 of file evrpc.c.
{
    struct evrpc_req_generic *rpc_state = arg;
    struct evhttp_request *req;
    EVUTIL_ASSERT(rpc_state);
    req = rpc_state->http_req;
    if (hook_res == EVRPC_TERMINATE)
        goto error;
    /* on success, we are going to transmit marshaled binary data */
    if (evhttp_find_header(req->output_headers, "Content-Type") == NULL) {
        evhttp_add_header(req->output_headers,
            "Content-Type", "application/octet-stream");
    }
    evhttp_send_reply(req, HTTP_OK, "OK", rpc_state->rpc_data);
    evrpc_reqstate_free_(rpc_state);
    return;
error:
    evrpc_reqstate_free_(rpc_state);
    evhttp_send_error(req, HTTP_SERVUNAVAIL, NULL);
    return;
}
References evhttp_add_header(), evhttp_find_header(), evhttp_send_error(), evhttp_send_reply(), evrpc_reqstate_free_(), EVUTIL_ASSERT, evrpc_req_generic::http_req, and evrpc_req_generic::rpc_data.
Referenced by evrpc_request_done().
evrpc_request_get_pool()
struct evrpc_pool * evrpc_request_get_pool (struct evrpc_request_wrapper * ctx)
accessors for obscure and undocumented functionality
Definition at line 1152 of file evrpc.c.
{
    return (ctx->pool);
}
References ctx.
evrpc_request_set_cb()
void evrpc_request_set_cb (struct evrpc_request_wrapper * ctx, void(*)(struct evrpc_status *, void *request, void *reply, void *arg) cb, void * cb_arg)
Definition at line 1165 of file evrpc.c.
{
    ctx->cb = cb;
    ctx->cb_arg = cb_arg;
}
References ctx.
evrpc_request_set_pool()
void evrpc_request_set_pool (struct evrpc_request_wrapper * ctx, struct evrpc_pool * pool)
Definition at line 1158 of file evrpc.c.
{
    ctx->pool = pool;
}
References ctx.
evrpc_request_timeout()
static void evrpc_request_timeout (evutil_socket_t fd, short what, void * arg) static
Definition at line 970 of file evrpc.c.
{
    struct evrpc_request_wrapper *ctx = arg;
    struct evhttp_connection *evcon = ctx->evcon;
    EVUTIL_ASSERT(evcon != NULL);
    evhttp_connection_fail_(evcon, EVREQ_HTTP_TIMEOUT);
}
References ctx, evhttp_connection_fail_(), and EVUTIL_ASSERT.
Referenced by evrpc_make_request().
evrpc_request_wrapper_free()
static void evrpc_request_wrapper_free (struct evrpc_request_wrapper * request) static
Definition at line 529 of file evrpc.c.
{
    if (request->hook_meta != NULL)
        evrpc_hook_context_free_(request->hook_meta);
    mm_free(request->name);
    mm_free(request);
}
References evrpc_hook_context_free_(), and mm_free.
Referenced by evrpc_pool_free(), evrpc_reply_done_closure(), evrpc_schedule_request(), and evrpc_schedule_request_closure().
evrpc_resume_request()
int evrpc_resume_request (void * vbase, void * ctx, enum EVRPC_HOOK_RESULT res)
Definition at line 779 of file evrpc.c.
{
    struct evrpc_hooks_ *base = vbase;
    struct evrpc_pause_list *head = &base->pause_requests;
    struct evrpc_hook_ctx *pause;
    TAILQ_FOREACH(pause, head, next) {
        if (pause->ctx == ctx)
            break;
    }
    if (pause == NULL)
        return (-1);
    (*pause->cb)(pause->ctx, res);
    TAILQ_REMOVE(head, pause, next);
    mm_free(pause);
    return (0);
}
References evrpc_hook_ctx::cb, evrpc_hook_ctx::ctx, ctx, mm_free, evrpc_hooks_::pause_requests, and TAILQ_FOREACH.
evrpc_schedule_request()
static int evrpc_schedule_request (struct evhttp_connection * connection, struct evrpc_request_wrapper * ctx) static
Definition at line 659 of file evrpc.c.
{
    struct evhttp_request *req = NULL;
    struct evrpc_pool *pool = ctx->pool;
    struct evrpc_status status;
    if ((req = evhttp_request_new(evrpc_reply_done, ctx)) == NULL)
        goto error;
    /* serialize the request data into the output buffer */
    ctx->request_marshal(req->output_buffer, ctx->request);
    /* we need to know the connection that we might have to abort */
    ctx->evcon = connection;
    /* if we get paused we also need to know the request */
    ctx->req = req;
    if (TAILQ_FIRST(&pool->output_hooks) != NULL) {
        int hook_res;
        evrpc_hook_associate_meta_(&ctx->hook_meta, connection);
        /* apply hooks to the outgoing request */
        hook_res = evrpc_process_hooks(&pool->output_hooks,
            ctx, req, req->output_buffer);
        switch (hook_res) {
        case EVRPC_TERMINATE:
            goto error;
        case EVRPC_PAUSE:
            /* we need to be explicitly resumed */
            if (evrpc_pause_request(pool, ctx,
                evrpc_schedule_request_closure) == -1)
                goto error;
            return (0);
        case EVRPC_CONTINUE:
            /* we can just continue */
            break;
        default:
            EVUTIL_ASSERT(hook_res == EVRPC_TERMINATE ||
                hook_res == EVRPC_CONTINUE ||
                hook_res == EVRPC_PAUSE);
        }
    }
    evrpc_schedule_request_closure(ctx, EVRPC_CONTINUE);
    return (0);
error:
    memset(&status, 0, sizeof(status));
    status.error = EVRPC_STATUS_ERR_UNSTARTED;
    (*ctx->cb)(&status, ctx->request, ctx->reply, ctx->cb_arg);
    evrpc_request_wrapper_free(ctx);
    return (-1);
}
References ctx, evhttp_request_new(), evrpc_hook_associate_meta_(), evrpc_pause_request(), evrpc_process_hooks(), evrpc_reply_done(), evrpc_request_wrapper_free(), evrpc_schedule_request_closure(), EVUTIL_ASSERT, and TAILQ_FIRST.
Referenced by evrpc_pool_add_connection(), and evrpc_pool_schedule().
evrpc_schedule_request_closure()
static void evrpc_schedule_request_closure (void * ctx, enum EVRPC_HOOK_RESULT hook_res) static
Definition at line 718 of file evrpc.c.
{
    struct evrpc_request_wrapper *ctx = arg;
    struct evhttp_connection *connection = ctx->evcon;
    struct evhttp_request *req = ctx->req;
    struct evrpc_pool *pool = ctx->pool;
    struct evrpc_status status;
    char *uri = NULL;
    int res = 0;
    if (hook_res == EVRPC_TERMINATE)
        goto error;
    uri = evrpc_construct_uri(ctx->name);
    if (uri == NULL)
        goto error;
    if (pool->timeout > 0) {
        /*
         * a timeout after which the whole rpc is going to be aborted.
         */
        struct timeval tv;
        evutil_timerclear(&tv);
        tv.tv_sec = pool->timeout;
        evtimer_add(&ctx->ev_timeout, &tv);
    }
    /* start the request over the connection */
    res = evhttp_make_request(connection, req, EVHTTP_REQ_POST, uri);
    mm_free(uri);
    if (res == -1)
        goto error;
    return;
error:
    memset(&status, 0, sizeof(status));
    status.error = EVRPC_STATUS_ERR_UNSTARTED;
    (*ctx->cb)(&status, ctx->request, ctx->reply, ctx->cb_arg);
    evrpc_request_wrapper_free(ctx);
}
References ctx, evhttp_make_request(), evrpc_construct_uri(), evrpc_request_wrapper_free(), mm_free, and evrpc_pool::timeout.
Referenced by evrpc_schedule_request().
evrpc_send_request_generic()
int evrpc_send_request_generic (struct evrpc_pool * pool, void * request, void * reply, void(*)(struct evrpc_status *, void *, void *, void *) cb, void * cb_arg, const char * rpcname, void(*)(struct evbuffer *, void *) req_marshal, void(*)(void *) rpl_clear, int(*)(void *, struct evbuffer *) rpl_unmarshal)
Definition at line 1079 of file evrpc.c.
{
    struct evrpc_status status;
    struct evrpc_request_wrapper *ctx;
    ctx = evrpc_make_request_ctx(pool, request, reply,
        rpcname, req_marshal, rpl_clear, rpl_unmarshal, cb, cb_arg);
    if (ctx == NULL)
        goto error;
    return (evrpc_make_request(ctx));
error:
    memset(&status, 0, sizeof(status));
    status.error = EVRPC_STATUS_ERR_UNSTARTED;
    (*(cb))(&status, request, reply, cb_arg);
    return (-1);
}
References evrpc_request_wrapper::cb, evrpc_request_wrapper::cb_arg, ctx, evrpc_make_request(), evrpc_make_request_ctx(), evrpc_request_wrapper::pool, evrpc_request_wrapper::reply, and evrpc_request_wrapper::request.
evrpc_unregister_rpc()
int evrpc_unregister_rpc (struct evrpc_base * base, const char * name)
Definition at line 250 of file evrpc.c.
{
    char *registered_uri = NULL;
    struct evrpc *rpc;
    int r;
    /* find the right rpc; linear search might be slow */
    TAILQ_FOREACH(rpc, &base->registered_rpcs, next) {
        if (strcmp(rpc->uri, name) == 0)
            break;
    }
    if (rpc == NULL) {
        /* We did not find an RPC with this name */
        return (-1);
    }
    TAILQ_REMOVE(&base->registered_rpcs, rpc, next);
    registered_uri = evrpc_construct_uri(name);
    /* remove the http server callback */
    r = evhttp_del_cb(base->http_server, registered_uri);
    EVUTIL_ASSERT(r == 0);
    mm_free(registered_uri);
    mm_free((char *)rpc->uri);
    mm_free(rpc);
    return (0);
}
References evhttp_del_cb(), evrpc_construct_uri(), EVUTIL_ASSERT, evrpc_base::http_server, mm_free, and TAILQ_FOREACH.
Referenced by evrpc_free().