libdogecoin: src/libevent/evsignal-internal.h File Reference
evsignal-internal.h File Reference
#include "event2/util.h"
#include <signal.h>
Data Structures
struct evsig_info
Typedefs
typedef void(* ev_sighandler_t) (int)
Functions
int evsig_init_ (struct event_base *)
void evsig_dealloc_ (struct event_base *)
void evsig_set_base_ (struct event_base *base)
void evsig_free_globals_ (void)
Typedef Documentation
ev_sighandler_t
typedef void(* ev_sighandler_t) (int)
Definition at line 35 of file evsignal-internal.h.
Function Documentation
evsig_dealloc_()
void evsig_dealloc_ (struct event_base * base)
Definition at line 415 of file signal.c.
{
    int i = 0;
    if (base->sig.ev_signal_added) {
        event_del(&base->sig.ev_signal);
        base->sig.ev_signal_added = 0;
    }
    /* debug event is created in evsig_init_/event_assign even when
     * ev_signal_added == 0, so unassign is required */
    event_debug_unassign(&base->sig.ev_signal);
    for (i = 0; i < NSIG; ++i) {
        if (i < base->sig.sh_old_max && base->sig.sh_old[i] != NULL)
            evsig_restore_handler_(base, i);
    }
    EVSIGBASE_LOCK();
    if (base == evsig_base) {
        evsig_base = NULL;
        evsig_base_n_signals_added = 0;
        evsig_base_fd = -1;
    }
    EVSIGBASE_UNLOCK();
    if (base->sig.ev_signal_pair[0] != -1) {
        evutil_closesocket(base->sig.ev_signal_pair[0]);
        base->sig.ev_signal_pair[0] = -1;
    }
    if (base->sig.ev_signal_pair[1] != -1) {
        evutil_closesocket(base->sig.ev_signal_pair[1]);
        base->sig.ev_signal_pair[1] = -1;
    }
    base->sig.sh_old_max = 0;
    /* per index frees are handled in evsig_del() */
    if (base->sig.sh_old) {
        mm_free(base->sig.sh_old);
        base->sig.sh_old = NULL;
    }
}
References evsig_info::ev_signal, evsig_info::ev_signal_added, evsig_info::ev_signal_pair, event_debug_unassign(), event_del(), evsig_base, evsig_base_fd, evsig_base_n_signals_added, evsig_restore_handler_(), EVSIGBASE_LOCK, EVSIGBASE_UNLOCK, evutil_closesocket(), mm_free, evsig_info::sh_old, evsig_info::sh_old_max, and event_base::sig.
evsig_free_globals_()
void evsig_free_globals_ (void)
Definition at line 468 of file signal.c.
{
    evsig_free_globals_locks();
}
References evsig_free_globals_locks().
Referenced by event_free_evsig_globals().
evsig_init_()
int evsig_init_ (struct event_base * base)
Definition at line 176 of file signal.c.
{
    /*
     * Our signal handler is going to write to one end of the socket
     * pair to wake up our event loop.  The event loop then scans for
     * signals that got delivered.
     */
    if (evutil_make_internal_pipe_(base->sig.ev_signal_pair) == -1) {
#ifdef _WIN32
        /* Make this nonfatal on win32, where sometimes people
           have localhost firewalled. */
        event_sock_warn(-1, "%s: socketpair", __func__);
#else
        event_sock_err(1, -1, "%s: socketpair", __func__);
#endif
        return -1;
    }
    if (base->sig.sh_old) {
        mm_free(base->sig.sh_old);
    }
    base->sig.sh_old = NULL;
    base->sig.sh_old_max = 0;
    event_assign(&base->sig.ev_signal, base, base->sig.ev_signal_pair[0],
        EV_READ | EV_PERSIST, evsig_cb, base);
    base->sig.ev_signal.ev_flags |= EVLIST_INTERNAL;
    event_priority_set(&base->sig.ev_signal, 0);
    base->evsigsel = &evsigops;
    return 0;
}
References __func__, evsig_info::ev_signal, evsig_info::ev_signal_pair, event_assign(), event_priority_set(), event_sock_err(), event_sock_warn(), evsig_cb(), evsigops, event_base::evsigsel, evutil_make_internal_pipe_(), mm_free, evsig_info::sh_old, evsig_info::sh_old_max, and event_base::sig.
Referenced by event_reinit().
evsig_set_base_()
void evsig_set_base_ (struct event_base * base)
Definition at line 122 of file signal.c.
{
    EVSIGBASE_LOCK();
    evsig_base = base;
    evsig_base_n_signals_added = base->sig.ev_n_signals_added;
    evsig_base_fd = base->sig.ev_signal_pair[1];
    EVSIGBASE_UNLOCK();
}
References evsig_info::ev_n_signals_added, evsig_info::ev_signal_pair, evsig_base, evsig_base_fd, evsig_base_n_signals_added, EVSIGBASE_LOCK, EVSIGBASE_UNLOCK, and event_base::sig.
Referenced by event_base_loop().