libdogecoin: src/libevent/evthread_win32.c File Reference
evthread_win32.c File Reference
#include "event2/event-config.h"
#include "evconfig-private.h"
#include "event2/thread.h"
#include "mm-internal.h"
#include "evthread-internal.h"
#include "time-internal.h"
Data Structures
struct evthread_win32_cond
Macros
#define SPIN_COUNT 2000
Functions
static void * evthread_win32_lock_create (unsigned locktype)
static void evthread_win32_lock_free (void *lock_, unsigned locktype)
static int evthread_win32_lock (unsigned mode, void *lock_)
static int evthread_win32_unlock (unsigned mode, void *lock_)
static unsigned long evthread_win32_get_id (void)
static void * evthread_win32_cond_alloc (unsigned flags)
static void evthread_win32_cond_free (void *cond_)
static int evthread_win32_cond_signal (void *cond_, int broadcast)
static int evthread_win32_cond_wait (void *cond_, void *lock_, const struct timeval *tv)
int evthread_use_windows_threads (void)
Macro Definition Documentation
SPIN_COUNT
#define SPIN_COUNT 2000
Definition at line 48 of file evthread_win32.c.
Function Documentation
evthread_use_windows_threads()
int evthread_use_windows_threads (void)
Definition at line 300 of file evthread_win32.c.
{
    struct evthread_lock_callbacks cbs = {
        EVTHREAD_LOCK_API_VERSION,
        EVTHREAD_LOCKTYPE_RECURSIVE,
        evthread_win32_lock_create,
        evthread_win32_lock_free,
        evthread_win32_lock,
        evthread_win32_unlock
    };
    struct evthread_condition_callbacks cond_cbs = {
        EVTHREAD_CONDITION_API_VERSION,
        evthread_win32_cond_alloc,
        evthread_win32_cond_free,
        evthread_win32_cond_signal,
        evthread_win32_cond_wait
    };
#ifdef WIN32_HAVE_CONDITION_VARIABLES
    struct evthread_condition_callbacks condvar_cbs = {
        EVTHREAD_CONDITION_API_VERSION,
        evthread_win32_condvar_alloc,
        evthread_win32_condvar_free,
        evthread_win32_condvar_signal,
        evthread_win32_condvar_wait
    };
#endif
    evthread_set_lock_callbacks(&cbs);
    evthread_set_id_callback(evthread_win32_get_id);
#ifdef WIN32_HAVE_CONDITION_VARIABLES
    if (evthread_win32_condvar_init()) {
        evthread_set_condition_callbacks(&condvar_cbs);
        return 0;
    }
#endif
    evthread_set_condition_callbacks(&cond_cbs);
    return 0;
}
References evthread_set_condition_callbacks(), evthread_set_id_callback(), evthread_set_lock_callbacks(), evthread_win32_cond_alloc(), evthread_win32_cond_free(), evthread_win32_cond_signal(), evthread_win32_cond_wait(), evthread_win32_get_id(), evthread_win32_lock(), evthread_win32_lock_create(), evthread_win32_lock_free(), and evthread_win32_unlock().
evthread_win32_cond_alloc()
static void * evthread_win32_cond_alloc (unsigned flags) static
Definition at line 190 of file evthread_win32.c.
{
    struct evthread_win32_cond *cond;
    if (!(cond = mm_malloc(sizeof(struct evthread_win32_cond))))
        return NULL;
    if (InitializeCriticalSectionAndSpinCount(&cond->lock, SPIN_COUNT)==0) {
        mm_free(cond);
        return NULL;
    }
    if ((cond->event = CreateEvent(NULL,TRUE,FALSE,NULL)) == NULL) {
        DeleteCriticalSection(&cond->lock);
        mm_free(cond);
        return NULL;
    }
    cond->n_waiting = cond->n_to_wake = cond->generation = 0;
    return cond;
}
References evthread_win32_cond::event, evthread_win32_cond::generation, evthread_win32_cond::lock, mm_free, mm_malloc, evthread_win32_cond::n_to_wake, evthread_win32_cond::n_waiting, and SPIN_COUNT.
Referenced by evthread_use_windows_threads().
evthread_win32_cond_free()
static void evthread_win32_cond_free (void * cond_) static
Definition at line 209 of file evthread_win32.c.
{
    struct evthread_win32_cond *cond = cond_;
    DeleteCriticalSection(&cond->lock);
    CloseHandle(cond->event);
    mm_free(cond);
}
References evthread_win32_cond::event, evthread_win32_cond::lock, and mm_free.
Referenced by evthread_use_windows_threads().
evthread_win32_cond_signal()
static int evthread_win32_cond_signal (void * cond_, int broadcast) static
Definition at line 218 of file evthread_win32.c.
{
    struct evthread_win32_cond *cond = cond_;
    EnterCriticalSection(&cond->lock);
    if (broadcast)
        cond->n_to_wake = cond->n_waiting;
    else
        ++cond->n_to_wake;
    cond->generation++;
    SetEvent(cond->event);
    LeaveCriticalSection(&cond->lock);
    return 0;
}
References evthread_win32_cond::event, evthread_win32_cond::generation, evthread_win32_cond::lock, evthread_win32_cond::n_to_wake, and evthread_win32_cond::n_waiting.
Referenced by evthread_use_windows_threads().
evthread_win32_cond_wait()
static int evthread_win32_cond_wait (void * cond_, void * lock_, const struct timeval * tv) static
Definition at line 233 of file evthread_win32.c.
{
    struct evthread_win32_cond *cond = cond_;
    CRITICAL_SECTION *lock = lock_;
    int generation_at_start;
    int waiting = 1;
    int result = -1;
    DWORD ms = INFINITE, ms_orig = INFINITE, startTime, endTime;
    if (tv)
        ms_orig = ms = evutil_tv_to_msec_(tv);
    EnterCriticalSection(&cond->lock);
    ++cond->n_waiting;
    generation_at_start = cond->generation;
    LeaveCriticalSection(&cond->lock);
    LeaveCriticalSection(lock);
    startTime = GetTickCount();
    do {
        DWORD res;
        res = WaitForSingleObject(cond->event, ms);
        EnterCriticalSection(&cond->lock);
        if (cond->n_to_wake &&
            cond->generation != generation_at_start) {
            --cond->n_to_wake;
            --cond->n_waiting;
            result = 0;
            waiting = 0;
            goto out;
        } else if (res != WAIT_OBJECT_0) {
            result = (res==WAIT_TIMEOUT) ? 1 : -1;
            --cond->n_waiting;
            waiting = 0;
            goto out;
        } else if (ms != INFINITE) {
            endTime = GetTickCount();
            if (startTime + ms_orig <= endTime) {
                result = 1; /* Timeout */
                --cond->n_waiting;
                waiting = 0;
                goto out;
            } else {
                ms = startTime + ms_orig - endTime;
            }
        }
        /* If we make it here, we are still waiting. */
        if (cond->n_to_wake == 0) {
            /* There is nobody else who should wake up; reset
             * the event. */
            ResetEvent(cond->event);
        }
    out:
        LeaveCriticalSection(&cond->lock);
    } while (waiting);
    EnterCriticalSection(lock);
    EnterCriticalSection(&cond->lock);
    if (!cond->n_waiting)
        ResetEvent(cond->event);
    LeaveCriticalSection(&cond->lock);
    return result;
}
References evthread_win32_cond::event, evutil_tv_to_msec_(), evthread_win32_cond::generation, evthread_win32_cond::lock, evthread_win32_cond::n_to_wake, and evthread_win32_cond::n_waiting.
Referenced by evthread_use_windows_threads().
evthread_win32_get_id()
static unsigned long evthread_win32_get_id (void) static
Definition at line 92 of file evthread_win32.c.
{
    return (unsigned long) GetCurrentThreadId();
}
Referenced by evthread_use_windows_threads().
evthread_win32_lock()
static int evthread_win32_lock (unsigned mode, void * lock_) static
Definition at line 72 of file evthread_win32.c.
{
    CRITICAL_SECTION *lock = lock_;
    if ((mode & EVTHREAD_TRY)) {
        return ! TryEnterCriticalSection(lock);
    } else {
        EnterCriticalSection(lock);
        return 0;
    }
}
Referenced by evthread_use_windows_threads().
evthread_win32_lock_create()
static void * evthread_win32_lock_create (unsigned locktype) static
Definition at line 51 of file evthread_win32.c.
{
    CRITICAL_SECTION *lock = mm_malloc(sizeof(CRITICAL_SECTION));
    if (!lock)
        return NULL;
    if (InitializeCriticalSectionAndSpinCount(lock, SPIN_COUNT) == 0) {
        mm_free(lock);
        return NULL;
    }
    return lock;
}
References mm_free, mm_malloc, and SPIN_COUNT.
Referenced by evthread_use_windows_threads().
evthread_win32_lock_free()
static void evthread_win32_lock_free (void * lock_, unsigned locktype) static
Definition at line 64 of file evthread_win32.c.
{
    CRITICAL_SECTION *lock = lock_;
    DeleteCriticalSection(lock);
    mm_free(lock);
}
References mm_free.
Referenced by evthread_use_windows_threads().
evthread_win32_unlock()
static int evthread_win32_unlock (unsigned mode, void * lock_) static
Definition at line 84 of file evthread_win32.c.
{
    CRITICAL_SECTION *lock = lock_;
    LeaveCriticalSection(lock);
    return 0;
}
Referenced by evthread_use_windows_threads().