libdogecoin: src/libevent/evthread-internal.h File Reference
evthread-internal.h File Reference
#include "event2/event-config.h"
#include "evconfig-private.h"
#include "event2/thread.h"
#include "util-internal.h"
Macros
#define EVTHREAD_EXPOSE_STRUCTS
#define EVTHREAD_GET_ID() (evthread_id_fn_ ? evthread_id_fn_() : 1)
#define EVBASE_IN_THREAD(base)
#define EVBASE_NEED_NOTIFY(base)
#define EVTHREAD_ALLOC_LOCK(lockvar, locktype)
#define EVTHREAD_FREE_LOCK(lockvar, locktype)
#define EVLOCK_LOCK(lockvar, mode)
#define EVLOCK_UNLOCK(lockvar, mode)
#define EVLOCK_SORTLOCKS_(lockvar1, lockvar2)
#define EVBASE_ACQUIRE_LOCK(base, lockvar)
#define EVBASE_RELEASE_LOCK(base, lockvar)
#define EVLOCK_ASSERT_LOCKED(lock)
#define EVTHREAD_ALLOC_COND(condvar)
#define EVTHREAD_FREE_COND(cond)
#define EVTHREAD_COND_SIGNAL(cond) ((cond) ? evthread_cond_fns_.signal_condition((cond), 0) : 0)
#define EVTHREAD_COND_BROADCAST(cond) ((cond) ? evthread_cond_fns_.signal_condition((cond), 1) : 0)
#define EVTHREAD_COND_WAIT(cond, lock) ((cond) ? evthread_cond_fns_.wait_condition((cond), (lock), NULL) : 0)
#define EVTHREAD_COND_WAIT_TIMED(cond, lock, tv) ((cond) ? evthread_cond_fns_.wait_condition((cond), (lock), (tv)) : 0)
#define EVTHREAD_LOCKING_ENABLED() (evthread_lock_fns_.lock != NULL)
#define EVLOCK_SORTLOCKS_(lockvar1, lockvar2)
#define EVLOCK_LOCK2(lock1, lock2, mode1, mode2)
#define EVLOCK_UNLOCK2(lock1, lock2, mode1, mode2)
#define EVTHREAD_SETUP_GLOBAL_LOCK(lockvar, locktype)
Functions
static int EVLOCK_TRY_LOCK_ (void *lock)
EVENT2_EXPORT_SYMBOL int evthread_is_debug_lock_held_ (void *lock)
void * evthread_debug_get_real_lock_ (void *lock)
void * evthread_setup_global_lock_ (void *lock_, unsigned locktype, int enable_locks)
int event_global_setup_locks_ (const int enable_locks)
int evsig_global_setup_locks_ (const int enable_locks)
int evutil_global_setup_locks_ (const int enable_locks)
int evutil_secure_rng_global_setup_locks_ (const int enable_locks)
EVENT2_EXPORT_SYMBOL struct evthread_lock_callbacks * evthread_get_lock_callbacks (void)
struct evthread_condition_callbacks * evthread_get_condition_callbacks (void)
void evthreadimpl_disable_lock_debugging_ (void)
Variables
EVENT2_EXPORT_SYMBOL struct evthread_lock_callbacks evthread_lock_fns_
EVENT2_EXPORT_SYMBOL struct evthread_condition_callbacks evthread_cond_fns_
unsigned long(* evthread_id_fn_)(void)
EVENT2_EXPORT_SYMBOL int evthread_lock_debugging_enabled_
Macro Definition Documentation
EVBASE_ACQUIRE_LOCK
#define EVBASE_ACQUIRE_LOCK (base, lockvar)
Value:
        do {                \
        EVLOCK_LOCK((base)->lockvar, 0);            \
    } while (0)
Lock an event_base, if it is set up for locking. Acquires the lock in the base structure whose field is named 'lockvar'.
Definition at line 118 of file evthread-internal.h.
EVBASE_IN_THREAD
#define EVBASE_IN_THREAD (base)
Value:
    (evthread_id_fn_ == NULL ||          \
    (base)->th_owner_id == evthread_id_fn_())
Return true iff we're in the thread that is currently (or most recently) running a given event_base's loop. Requires lock.
Definition at line 66 of file evthread-internal.h.
EVBASE_NEED_NOTIFY
#define EVBASE_NEED_NOTIFY (base)
Value:
    (evthread_id_fn_ != NULL &&          \
        (base)->running_loop &&          \
        (base)->th_owner_id != evthread_id_fn_())
Return true iff we need to notify the base's main thread about changes to its state, because it's currently running the main loop in another thread. Requires lock.
Definition at line 73 of file evthread-internal.h.
EVBASE_RELEASE_LOCK
#define EVBASE_RELEASE_LOCK (base, lockvar)
Value:
        do {                \
        EVLOCK_UNLOCK((base)->lockvar, 0);          \
    } while (0)
Unlock an event_base, if it is set up for locking.
Definition at line 123 of file evthread-internal.h.
EVLOCK_ASSERT_LOCKED
#define EVLOCK_ASSERT_LOCKED (lock)
Value:
    do {                                \
        if ((lock) && evthread_lock_debugging_enabled_) {   \
            EVUTIL_ASSERT(evthread_is_debug_lock_held_(lock)); \
        }                           \
    } while (0)
If lock debugging is enabled, and lock is non-null, assert that 'lock' is locked and held by us.
Definition at line 129 of file evthread-internal.h.
EVLOCK_LOCK
#define EVLOCK_LOCK (lockvar, mode)
Value:
    do {                                \
        if (lockvar)                        \
            evthread_lock_fns_.lock(mode, lockvar);     \
    } while (0)
Acquire a lock.
Definition at line 93 of file evthread-internal.h.
EVLOCK_LOCK2
#define EVLOCK_LOCK2 (lock1, lock2, mode1, mode2)
Value:
    do {                                \
        void *lock1_tmplock_ = (lock1);             \
        void *lock2_tmplock_ = (lock2);             \
        EVLOCK_SORTLOCKS_(lock1_tmplock_,lock2_tmplock_);   \
        EVLOCK_LOCK(lock1_tmplock_,mode1);          \
        if (lock2_tmplock_ != lock1_tmplock_)           \
            EVLOCK_LOCK(lock2_tmplock_,mode2);      \
    } while (0)
Acquire both lock1 and lock2. Always allocates locks in the same order, so that two threads locking two locks with LOCK2 will not deadlock.
Definition at line 350 of file evthread-internal.h.
EVLOCK_SORTLOCKS_ [1/2]
#define EVLOCK_SORTLOCKS_ (lockvar1, lockvar2)
Value:
    do {                                \
        if (lockvar1 && lockvar2 && lockvar1 > lockvar2) {  \
            void *tmp = lockvar1;               \
            lockvar1 = lockvar2;                \
            lockvar2 = tmp;                 \
        }                           \
    } while (0)
Helper: put lockvar1 and lockvar2 into pointerwise ascending order.
Definition at line 339 of file evthread-internal.h.
EVLOCK_SORTLOCKS_ [2/2]
#define EVLOCK_SORTLOCKS_ (lockvar1, lockvar2)
Value:
    do {                                \
        if (lockvar1 && lockvar2 && lockvar1 > lockvar2) {  \
            void *tmp = lockvar1;               \
            lockvar1 = lockvar2;                \
            lockvar2 = tmp;                 \
        }                           \
    } while (0)
Helper: put lockvar1 and lockvar2 into pointerwise ascending order.
Definition at line 339 of file evthread-internal.h.
EVLOCK_UNLOCK
#define EVLOCK_UNLOCK (lockvar, mode)
Value:
    do {                                \
        if (lockvar)                        \
            evthread_lock_fns_.unlock(mode, lockvar);   \
    } while (0)
Release a lock
Definition at line 100 of file evthread-internal.h.
EVLOCK_UNLOCK2
#define EVLOCK_UNLOCK2 (lock1, lock2, mode1, mode2)
Value:
    do {                                \
        void *lock1_tmplock_ = (lock1);             \
        void *lock2_tmplock_ = (lock2);             \
        EVLOCK_SORTLOCKS_(lock1_tmplock_,lock2_tmplock_);   \
        if (lock2_tmplock_ != lock1_tmplock_)           \
            EVLOCK_UNLOCK(lock2_tmplock_,mode2);        \
        EVLOCK_UNLOCK(lock1_tmplock_,mode1);            \
    } while (0)
Release both lock1 and lock2.
Definition at line 360 of file evthread-internal.h.
EVTHREAD_ALLOC_COND
#define EVTHREAD_ALLOC_COND (condvar)
Value:
    do {                                \
        (condvar) = evthread_cond_fns_.alloc_condition ?    \
            evthread_cond_fns_.alloc_condition(0) : NULL;   \
    } while (0)
Allocate a new condition variable and store it in the void *, condvar
Definition at line 153 of file evthread-internal.h.
EVTHREAD_ALLOC_LOCK
#define EVTHREAD_ALLOC_LOCK (lockvar, locktype)
Value:
    ((lockvar) = evthread_lock_fns_.alloc ?     \
        evthread_lock_fns_.alloc(locktype) : NULL)
Allocate a new lock, and store it in lockvar, a void*. Sets lockvar to NULL if locking is not enabled.
Definition at line 80 of file evthread-internal.h.
EVTHREAD_COND_BROADCAST
#define EVTHREAD_COND_BROADCAST (cond) ((cond) ? evthread_cond_fns_.signal_condition((cond), 1) : 0)
Signal all threads waiting on cond
Definition at line 168 of file evthread-internal.h.
EVTHREAD_COND_SIGNAL
#define EVTHREAD_COND_SIGNAL (cond) ((cond) ? evthread_cond_fns_.signal_condition((cond), 0) : 0)
Signal one thread waiting on cond
Definition at line 165 of file evthread-internal.h.
EVTHREAD_COND_WAIT
#define EVTHREAD_COND_WAIT (cond, lock) ((cond) ? evthread_cond_fns_.wait_condition((cond), (lock), NULL) : 0)
Wait until the condition 'cond' is signalled. Must be called while holding 'lock'. The lock will be released until the condition is signalled, at which point it will be acquired again. Returns 0 for success, -1 for failure.
Definition at line 174 of file evthread-internal.h.
EVTHREAD_COND_WAIT_TIMED
#define EVTHREAD_COND_WAIT_TIMED (cond, lock, tv) ((cond) ? evthread_cond_fns_.wait_condition((cond), (lock), (tv)) : 0)
As EVTHREAD_COND_WAIT, but gives up after 'tv' has elapsed. Returns 1 on timeout.
Definition at line 178 of file evthread-internal.h.
EVTHREAD_EXPOSE_STRUCTS
#define EVTHREAD_EXPOSE_STRUCTS
Definition at line 46 of file evthread-internal.h.
EVTHREAD_FREE_COND
#define EVTHREAD_FREE_COND (cond)
Value:
    do {                                \
        if (cond)                       \
            evthread_cond_fns_.free_condition((cond));  \
    } while (0)
Deallocate and free a condition variable in condvar
Definition at line 159 of file evthread-internal.h.
EVTHREAD_FREE_LOCK
#define EVTHREAD_FREE_LOCK (lockvar, locktype)
Value:
    do {                                \
        void *lock_tmp_ = (lockvar);                \
        if (lock_tmp_ && evthread_lock_fns_.free)       \
            evthread_lock_fns_.free(lock_tmp_, (locktype)); \
    } while (0)
Free a given lock, if it is present and locking is enabled.
Definition at line 85 of file evthread-internal.h.
EVTHREAD_GET_ID
#define EVTHREAD_GET_ID () (evthread_id_fn_ ? evthread_id_fn_() : 1)
Return the ID of the current thread, or 1 if threading isn't enabled.
Definition at line 61 of file evthread-internal.h.
EVTHREAD_LOCKING_ENABLED
#define EVTHREAD_LOCKING_ENABLED () (evthread_lock_fns_.lock != NULL)
True iff locking functions have been configured.
Definition at line 182 of file evthread-internal.h.
EVTHREAD_SETUP_GLOBAL_LOCK
#define EVTHREAD_SETUP_GLOBAL_LOCK (lockvar, locktype)
Value:
    do {                                \
        lockvar = evthread_setup_global_lock_(lockvar,      \
            (locktype), enable_locks);              \
        if (!lockvar) {                     \
            event_warn("Couldn't allocate %s", #lockvar);   \
            return -1;                  \
        }                           \
    } while (0);
Definition at line 377 of file evthread-internal.h.
Function Documentation
event_global_setup_locks_()
int event_global_setup_locks_ (const int enable_locks)
Definition at line 3940 of file event.c.
{
#ifndef EVENT__DISABLE_DEBUG_MODE
    EVTHREAD_SETUP_GLOBAL_LOCK(event_debug_map_lock_, 0);
#endif
    if (evsig_global_setup_locks_(enable_locks) < 0)
        return -1;
    if (evutil_global_setup_locks_(enable_locks) < 0)
        return -1;
    if (evutil_secure_rng_global_setup_locks_(enable_locks) < 0)
        return -1;
    return 0;
}
References event_debug_map_lock_, evsig_global_setup_locks_(), EVTHREAD_SETUP_GLOBAL_LOCK, evutil_global_setup_locks_(), and evutil_secure_rng_global_setup_locks_().
Referenced by evthread_enable_lock_debugging(), and evthread_set_lock_callbacks().
EVLOCK_TRY_LOCK_()
static int EVLOCK_TRY_LOCK_ (void * lock) inline static
Try to grab the lock for 'lockvar' without blocking, and return 1 if we manage to get it.
Definition at line 140 of file evthread-internal.h.
{
    if (lock && evthread_lock_fns_.lock) {
        int r = evthread_lock_fns_.lock(EVTHREAD_TRY, lock);
        return !r;
    } else {
        /* Locking is disabled either globally or for this thing;
         * of course we count as having the lock. */
        return 1;
    }
}
References evthread_lock_fns_.
Referenced by bev_group_suspend_reading_(), bev_group_suspend_writing_(), bev_group_unsuspend_reading_(), and bev_group_unsuspend_writing_().
evsig_global_setup_locks_()
int evsig_global_setup_locks_ (const int enable_locks)
Definition at line 475 of file signal.c.
{
    EVTHREAD_SETUP_GLOBAL_LOCK(evsig_base_lock, 0);
    return 0;
}
References evsig_base_lock, and EVTHREAD_SETUP_GLOBAL_LOCK.
Referenced by event_global_setup_locks_().
evthread_debug_get_real_lock_()
void * evthread_debug_get_real_lock_ (void * lock)
Definition at line 359 of file evthread.c.
{
    struct debug_lock *lock = lock_;
    return lock->lock;
}
References debug_lock::lock.
evthread_get_condition_callbacks()
struct evthread_condition_callbacks * evthread_get_condition_callbacks (void)
Return current evthread_condition_callbacks
Definition at line 82 of file evthread.c.
{
    return evthread_lock_debugging_enabled_
        ? &original_cond_fns_ : &evthread_cond_fns_;
}
References evthread_cond_fns_, evthread_lock_debugging_enabled_, and original_cond_fns_.
Referenced by evthread_set_condition_callbacks().
evthread_get_lock_callbacks()
EVENT2_EXPORT_SYMBOL struct evthread_lock_callbacks * evthread_get_lock_callbacks (void)
Return current evthread_lock_callbacks
Definition at line 77 of file evthread.c.
{
    return evthread_lock_debugging_enabled_
        ? &original_lock_fns_ : &evthread_lock_fns_;
}
References evthread_lock_debugging_enabled_, evthread_lock_fns_, and original_lock_fns_.
Referenced by evthread_set_lock_callbacks().
evthread_is_debug_lock_held_()
EVENT2_EXPORT_SYMBOL int evthread_is_debug_lock_held_ (void * lock)
Definition at line 345 of file evthread.c.
{
    struct debug_lock *lock = lock_;
    if (! lock->count)
        return 0;
    if (evthread_id_fn_) {
        unsigned long me = evthread_id_fn_();
        if (lock->held_by != me)
            return 0;
    }
    return 1;
}
References evthread_id_fn_, and debug_lock::lock.
evthread_setup_global_lock_()
void * evthread_setup_global_lock_ (void * lock_, unsigned locktype, int enable_locks)
Definition at line 366 of file evthread.c.
{
    /* there are four cases here:
       1) we're turning on debugging; locking is not on.
       2) we're turning on debugging; locking is on.
       3) we're turning on locking; debugging is not on.
       4) we're turning on locking; debugging is on. */
    if (!enable_locks && original_lock_fns_.alloc == NULL) {
        /* Case 1: allocate a debug lock. */
        EVUTIL_ASSERT(lock_ == NULL);
        return debug_lock_alloc(locktype);
    } else if (!enable_locks && original_lock_fns_.alloc != NULL) {
        /* Case 2: wrap the lock in a debug lock. */
        struct debug_lock *lock;
        EVUTIL_ASSERT(lock_ != NULL);
        if (!(locktype & EVTHREAD_LOCKTYPE_RECURSIVE)) {
            /* We can't wrap it: We need a recursive lock */
            original_lock_fns_.free(lock_, locktype);
            return debug_lock_alloc(locktype);
        }
        lock = mm_malloc(sizeof(struct debug_lock));
        if (!lock) {
            original_lock_fns_.free(lock_, locktype);
            return NULL;
        }
        lock->lock = lock_;
        lock->locktype = locktype;
        lock->count = 0;
        lock->held_by = 0;
        return lock;
    } else if (enable_locks && ! evthread_lock_debugging_enabled_) {
        /* Case 3: allocate a regular lock */
        EVUTIL_ASSERT(lock_ == NULL);
        return evthread_lock_fns_.alloc(locktype);
    } else {
        /* Case 4: Fill in a debug lock with a real lock */
        struct debug_lock *lock = lock_ ? lock_ : debug_lock_alloc(locktype);
        EVUTIL_ASSERT(enable_locks &&
                      evthread_lock_debugging_enabled_);
        EVUTIL_ASSERT(lock->locktype == locktype);
        if (!lock->lock) {
            lock->lock = original_lock_fns_.alloc(
                locktype|EVTHREAD_LOCKTYPE_RECURSIVE);
            if (!lock->lock) {
                lock->count = -200;
                mm_free(lock);
                return NULL;
            }
        }
        return lock;
    }
}
References debug_lock_alloc(), evthread_lock_debugging_enabled_, evthread_lock_fns_, EVUTIL_ASSERT, debug_lock::lock, debug_lock::locktype, mm_free, mm_malloc, and original_lock_fns_.
evthreadimpl_disable_lock_debugging_()
void evthreadimpl_disable_lock_debugging_ (void)
Disable locking for internal usage (like global shutdown)
Definition at line 87 of file evthread.c.
{
    evthread_lock_debugging_enabled_ = 0;
}
References evthread_lock_debugging_enabled_.
Referenced by event_free_debug_globals_locks().
evutil_global_setup_locks_()
int evutil_global_setup_locks_ (const int enable_locks)
Definition at line 1844 of file evutil.c.
{
    return 0;
}
Referenced by event_global_setup_locks_().
evutil_secure_rng_global_setup_locks_()
int evutil_secure_rng_global_setup_locks_ (const int enable_locks)
Definition at line 138 of file evutil_rand.c.
{
    EVTHREAD_SETUP_GLOBAL_LOCK(arc4rand_lock, 0);
    return 0;
}
References arc4rand_lock, and EVTHREAD_SETUP_GLOBAL_LOCK.
Referenced by event_global_setup_locks_().
Variable Documentation
evthread_cond_fns_
EVENT2_EXPORT_SYMBOL struct evthread_condition_callbacks evthread_cond_fns_ extern
Definition at line 59 of file evthread.c.
Referenced by evthread_enable_lock_debugging(), evthread_get_condition_callbacks(), and evthread_set_condition_callbacks().
evthread_id_fn_
unsigned long(* evthread_id_fn_) (void) (void) extern
Definition at line 58 of file evthread.c.
Referenced by evthread_debug_lock_mark_locked(), evthread_debug_lock_mark_unlocked(), evthread_is_debug_lock_held_(), and evthread_set_id_callback().
evthread_lock_debugging_enabled_
EVENT2_EXPORT_SYMBOL int evthread_lock_debugging_enabled_ extern
Definition at line 54 of file evthread.c.
Referenced by evthread_enable_lock_debugging(), evthread_get_condition_callbacks(), evthread_get_lock_callbacks(), evthread_set_condition_callbacks(), evthread_setup_global_lock_(), and evthreadimpl_disable_lock_debugging_().
evthread_lock_fns_
EVENT2_EXPORT_SYMBOL struct evthread_lock_callbacks evthread_lock_fns_ extern
Definition at line 55 of file evthread.c.
Referenced by EVLOCK_TRY_LOCK_(), evthread_enable_lock_debugging(), evthread_get_lock_callbacks(), evthread_set_lock_callbacks(), and evthread_setup_global_lock_().