libdogecoin: src/libevent/evthread_pthread.c File Reference
evthread_pthread.c File Reference
#include "event2/event-config.h"
#include "evconfig-private.h"
#include <pthread.h>
#include "event2/thread.h"
#include <stdlib.h>
#include <string.h>
#include "mm-internal.h"
#include "evthread-internal.h"
Functions
static void * evthread_posix_lock_alloc (unsigned locktype)
static void evthread_posix_lock_free (void *lock_, unsigned locktype)
static int evthread_posix_lock (unsigned mode, void *lock_)
static int evthread_posix_unlock (unsigned mode, void *lock_)
static unsigned long evthread_posix_get_id (void)
static void * evthread_posix_cond_alloc (unsigned condflags)
static void evthread_posix_cond_free (void *cond_)
static int evthread_posix_cond_signal (void *cond_, int broadcast)
static int evthread_posix_cond_wait (void *cond_, void *lock_, const struct timeval *tv)
int evthread_use_pthreads (void)
Variables
static pthread_mutexattr_t attr_recursive
Function Documentation
evthread_posix_cond_alloc()
static void * evthread_posix_cond_alloc (unsigned condflags) static
Definition at line 104 of file evthread_pthread.c.
{
    pthread_cond_t *cond = mm_malloc(sizeof(pthread_cond_t));
    if (!cond)
        return NULL;
    if (pthread_cond_init(cond, NULL)) {
        mm_free(cond);
        return NULL;
    }
    return cond;
}
References mm_free, and mm_malloc.
Referenced by evthread_use_pthreads().
evthread_posix_cond_free()
static void evthread_posix_cond_free (void * cond_) static
Definition at line 117 of file evthread_pthread.c.
{
    pthread_cond_t *cond = cond_;
    pthread_cond_destroy(cond);
    mm_free(cond);
}
References mm_free.
Referenced by evthread_use_pthreads().
evthread_posix_cond_signal()
static int evthread_posix_cond_signal (void * cond_, int broadcast) static
Definition at line 125 of file evthread_pthread.c.
{
    pthread_cond_t *cond = cond_;
    int r;
    if (broadcast)
        r = pthread_cond_broadcast(cond);
    else
        r = pthread_cond_signal(cond);
    return r ? -1 : 0;
}
Referenced by evthread_use_pthreads().
evthread_posix_cond_wait()
static int evthread_posix_cond_wait (void * cond_, void * lock_, const struct timeval * tv) static
Definition at line 137 of file evthread_pthread.c.
{
    int r;
    pthread_cond_t *cond = cond_;
    pthread_mutex_t *lock = lock_;
    if (tv) {
        struct timeval now, abstime;
        struct timespec ts;
        evutil_gettimeofday(&now, NULL);
        evutil_timeradd(&now, tv, &abstime);
        ts.tv_sec = abstime.tv_sec;
        ts.tv_nsec = abstime.tv_usec*1000;
        r = pthread_cond_timedwait(cond, lock, &ts);
        if (r == ETIMEDOUT)
            return 1;
        else if (r)
            return -1;
        else
            return 0;
    } else {
        r = pthread_cond_wait(cond, lock);
        return r ? -1 : 0;
    }
}
References evutil_gettimeofday().
Referenced by evthread_use_pthreads().
evthread_posix_get_id()
static unsigned long evthread_posix_get_id (void) static
Definition at line 86 of file evthread_pthread.c.
{
    union {
        pthread_t thr;
#if EVENT__SIZEOF_PTHREAD_T > EVENT__SIZEOF_LONG
        ev_uint64_t id;
#else
        unsigned long id;
#endif
    } r;
#if EVENT__SIZEOF_PTHREAD_T < EVENT__SIZEOF_LONG
    memset(&r, 0, sizeof(r));
#endif
    r.thr = pthread_self();
    return (unsigned long)r.id;
}
Referenced by evthread_use_pthreads().
evthread_posix_lock()
static int evthread_posix_lock (unsigned mode, void * lock_) static
Definition at line 69 of file evthread_pthread.c.
{
    pthread_mutex_t *lock = lock_;
    if (mode & EVTHREAD_TRY)
        return pthread_mutex_trylock(lock);
    else
        return pthread_mutex_lock(lock);
}
Referenced by evthread_use_pthreads().
evthread_posix_lock_alloc()
static void * evthread_posix_lock_alloc (unsigned locktype) static
Definition at line 45 of file evthread_pthread.c.
{
    pthread_mutexattr_t *attr = NULL;
    pthread_mutex_t *lock = mm_malloc(sizeof(pthread_mutex_t));
    if (!lock)
        return NULL;
    if (locktype & EVTHREAD_LOCKTYPE_RECURSIVE)
        attr = &attr_recursive;
    if (pthread_mutex_init(lock, attr)) {
        mm_free(lock);
        return NULL;
    }
    return lock;
}
References attr_recursive, mm_free, and mm_malloc.
Referenced by evthread_use_pthreads().
evthread_posix_lock_free()
static void evthread_posix_lock_free (void * lock_, unsigned locktype) static
Definition at line 61 of file evthread_pthread.c.
{
    pthread_mutex_t *lock = lock_;
    pthread_mutex_destroy(lock);
    mm_free(lock);
}
References mm_free.
Referenced by evthread_use_pthreads().
evthread_posix_unlock()
static int evthread_posix_unlock (unsigned mode, void * lock_) static
Definition at line 79 of file evthread_pthread.c.
{
    pthread_mutex_t *lock = lock_;
    return pthread_mutex_unlock(lock);
}
Referenced by evthread_use_pthreads().
evthread_use_pthreads()
int evthread_use_pthreads (void)
Definition at line 164 of file evthread_pthread.c.
{
    struct evthread_lock_callbacks cbs = {
        EVTHREAD_LOCK_API_VERSION,
        EVTHREAD_LOCKTYPE_RECURSIVE,
        evthread_posix_lock_alloc,
        evthread_posix_lock_free,
        evthread_posix_lock,
        evthread_posix_unlock
    };
    struct evthread_condition_callbacks cond_cbs = {
        EVTHREAD_CONDITION_API_VERSION,
        evthread_posix_cond_alloc,
        evthread_posix_cond_free,
        evthread_posix_cond_signal,
        evthread_posix_cond_wait
    };
    /* Set ourselves up to get recursive locks. */
    if (pthread_mutexattr_init(&attr_recursive))
        return -1;
    if (pthread_mutexattr_settype(&attr_recursive, PTHREAD_MUTEX_RECURSIVE))
        return -1;
    evthread_set_lock_callbacks(&cbs);
    evthread_set_condition_callbacks(&cond_cbs);
    evthread_set_id_callback(evthread_posix_get_id);
    return 0;
}
References attr_recursive, evthread_posix_cond_alloc(), evthread_posix_cond_free(), evthread_posix_cond_signal(), evthread_posix_cond_wait(), evthread_posix_get_id(), evthread_posix_lock(), evthread_posix_lock_alloc(), evthread_posix_lock_free(), evthread_posix_unlock(), evthread_set_condition_callbacks(), evthread_set_id_callback(), and evthread_set_lock_callbacks().
Variable Documentation
attr_recursive
pthread_mutexattr_t attr_recursive static
Definition at line 42 of file evthread_pthread.c.
Referenced by evthread_posix_lock_alloc(), and evthread_use_pthreads().