libdogecoin: src/libevent/evthread.c File Reference
evthread.c File Reference
#include "event2/event-config.h"
#include "evconfig-private.h"
#include "event2/thread.h"
#include <stdlib.h>
#include <string.h>
#include "log-internal.h"
#include "mm-internal.h"
#include "util-internal.h"
#include "evthread-internal.h"
Data Structures
struct debug_lock
Macros
#define GLOBAL
#define DEBUG_LOCK_SIG 0xdeb0b10c
Functions
void evthread_set_id_callback (unsigned long(*id_fn)(void))
struct evthread_lock_callbacks * evthread_get_lock_callbacks ()
struct evthread_condition_callbacks * evthread_get_condition_callbacks ()
void evthreadimpl_disable_lock_debugging_ (void)
int evthread_set_lock_callbacks (const struct evthread_lock_callbacks *cbs)
int evthread_set_condition_callbacks (const struct evthread_condition_callbacks *cbs)
static void * debug_lock_alloc (unsigned locktype)
static void debug_lock_free (void *lock_, unsigned locktype)
static void evthread_debug_lock_mark_locked (unsigned mode, struct debug_lock *lock)
static int debug_lock_lock (unsigned mode, void *lock_)
static void evthread_debug_lock_mark_unlocked (unsigned mode, struct debug_lock *lock)
static int debug_lock_unlock (unsigned mode, void *lock_)
static int debug_cond_wait (void *cond_, void *lock_, const struct timeval *tv)
void evthread_enable_lock_debuging (void)
void evthread_enable_lock_debugging (void)
int evthread_is_debug_lock_held_ (void *lock_)
void * evthread_debug_get_real_lock_ (void *lock_)
void * evthread_setup_global_lock_ (void *lock_, unsigned locktype, int enable_locks)
Variables
int event_debug_created_threadable_ctx_
debug mode variable which is set for any function/structure that needs to be shared across threads (if thread support is enabled).
int event_debug_mode_on_
GLOBAL int evthread_lock_debugging_enabled_ = 0
GLOBAL struct evthread_lock_callbacks evthread_lock_fns_
GLOBAL unsigned long(* evthread_id_fn_)(void) = NULL
GLOBAL struct evthread_condition_callbacks evthread_cond_fns_
static struct evthread_lock_callbacks original_lock_fns_
static struct evthread_condition_callbacks original_cond_fns_
Macro Definition Documentation
DEBUG_LOCK_SIG
#define DEBUG_LOCK_SIG 0xdeb0b10c
Definition at line 182 of file evthread.c.
GLOBAL
#define GLOBAL
Definition at line 43 of file evthread.c.
Function Documentation
debug_cond_wait()
static int debug_cond_wait (void * cond_, void * lock_, const struct timeval * tv) static
Definition at line 297 of file evthread.c.
{
    int r;
    struct debug_lock *lock = lock_;
    EVUTIL_ASSERT(lock);
    EVUTIL_ASSERT(DEBUG_LOCK_SIG == lock->signature);
    EVLOCK_ASSERT_LOCKED(lock_);
    evthread_debug_lock_mark_unlocked(0, lock);
    r = original_cond_fns_.wait_condition(cond_, lock->lock, tv);
    evthread_debug_lock_mark_locked(0, lock);
    return r;
}
References DEBUG_LOCK_SIG, EVLOCK_ASSERT_LOCKED, evthread_debug_lock_mark_locked(), evthread_debug_lock_mark_unlocked(), EVUTIL_ASSERT, debug_lock::lock, and original_cond_fns_.
Referenced by evthread_enable_lock_debugging().
debug_lock_alloc()
static void * debug_lock_alloc (unsigned locktype) static
Definition at line 195 of file evthread.c.
{
    struct debug_lock *result = mm_malloc(sizeof(struct debug_lock));
    if (!result)
        return NULL;
    if (original_lock_fns_.alloc) {
        if (!(result->lock = original_lock_fns_.alloc(
                locktype|EVTHREAD_LOCKTYPE_RECURSIVE))) {
            mm_free(result);
            return NULL;
        }
    } else {
        result->lock = NULL;
    }
    result->signature = DEBUG_LOCK_SIG;
    result->locktype = locktype;
    result->count = 0;
    result->held_by = 0;
    return result;
}
References debug_lock::count, DEBUG_LOCK_SIG, debug_lock::held_by, debug_lock::lock, debug_lock::locktype, mm_free, mm_malloc, original_lock_fns_, and debug_lock::signature.
Referenced by evthread_enable_lock_debugging(), and evthread_setup_global_lock_().
debug_lock_free()
static void debug_lock_free (void * lock_, unsigned locktype) static
Definition at line 217 of file evthread.c.
{
    struct debug_lock *lock = lock_;
    EVUTIL_ASSERT(lock->count == 0);
    EVUTIL_ASSERT(locktype == lock->locktype);
    EVUTIL_ASSERT(DEBUG_LOCK_SIG == lock->signature);
    if (original_lock_fns_.free) {
        original_lock_fns_.free(lock->lock,
            lock->locktype|EVTHREAD_LOCKTYPE_RECURSIVE);
    }
    lock->lock = NULL;
    lock->count = -100;
    lock->signature = 0x12300fda;
    mm_free(lock);
}
References DEBUG_LOCK_SIG, EVUTIL_ASSERT, debug_lock::lock, debug_lock::locktype, mm_free, and original_lock_fns_.
Referenced by evthread_enable_lock_debugging().
debug_lock_lock()
static int debug_lock_lock (unsigned mode, void * lock_) static
Definition at line 250 of file evthread.c.
{
    struct debug_lock *lock = lock_;
    int res = 0;
    if (lock->locktype & EVTHREAD_LOCKTYPE_READWRITE)
        EVUTIL_ASSERT(mode & (EVTHREAD_READ|EVTHREAD_WRITE));
    else
        EVUTIL_ASSERT((mode & (EVTHREAD_READ|EVTHREAD_WRITE)) == 0);
    if (original_lock_fns_.lock)
        res = original_lock_fns_.lock(mode, lock->lock);
    if (!res) {
        evthread_debug_lock_mark_locked(mode, lock);
    }
    return res;
}
References evthread_debug_lock_mark_locked(), EVUTIL_ASSERT, debug_lock::lock, and original_lock_fns_.
Referenced by evthread_enable_lock_debugging().
debug_lock_unlock()
static int debug_lock_unlock (unsigned mode, void * lock_) static
Definition at line 286 of file evthread.c.
{
    struct debug_lock *lock = lock_;
    int res = 0;
    evthread_debug_lock_mark_unlocked(mode, lock);
    if (original_lock_fns_.unlock)
        res = original_lock_fns_.unlock(mode, lock->lock);
    return res;
}
References evthread_debug_lock_mark_unlocked(), debug_lock::lock, and original_lock_fns_.
Referenced by evthread_enable_lock_debugging().
evthread_debug_get_real_lock_()
void * evthread_debug_get_real_lock_ (void * lock_)
Definition at line 359 of file evthread.c.
{
    struct debug_lock *lock = lock_;
    return lock->lock;
}
References debug_lock::lock.
evthread_debug_lock_mark_locked()
static void evthread_debug_lock_mark_locked (unsigned mode, struct debug_lock * lock) static
Definition at line 234 of file evthread.c.
{
    EVUTIL_ASSERT(DEBUG_LOCK_SIG == lock->signature);
    ++lock->count;
    if (!(lock->locktype & EVTHREAD_LOCKTYPE_RECURSIVE))
        EVUTIL_ASSERT(lock->count == 1);
    if (evthread_id_fn_) {
        unsigned long me;
        me = evthread_id_fn_();
        if (lock->count > 1)
            EVUTIL_ASSERT(lock->held_by == me);
        lock->held_by = me;
    }
}
References DEBUG_LOCK_SIG, evthread_id_fn_, EVUTIL_ASSERT, and debug_lock::lock.
Referenced by debug_cond_wait(), and debug_lock_lock().
evthread_debug_lock_mark_unlocked()
static void evthread_debug_lock_mark_unlocked (unsigned mode, struct debug_lock * lock) static
Definition at line 267 of file evthread.c.
{
    EVUTIL_ASSERT(DEBUG_LOCK_SIG == lock->signature);
    if (lock->locktype & EVTHREAD_LOCKTYPE_READWRITE)
        EVUTIL_ASSERT(mode & (EVTHREAD_READ|EVTHREAD_WRITE));
    else
        EVUTIL_ASSERT((mode & (EVTHREAD_READ|EVTHREAD_WRITE)) == 0);
    if (evthread_id_fn_) {
        unsigned long me;
        me = evthread_id_fn_();
        EVUTIL_ASSERT(lock->held_by == me);
        if (lock->count == 1)
            lock->held_by = 0;
    }
    --lock->count;
    EVUTIL_ASSERT(lock->count >= 0);
}
References DEBUG_LOCK_SIG, evthread_id_fn_, EVUTIL_ASSERT, and debug_lock::lock.
Referenced by debug_cond_wait(), and debug_lock_unlock().
evthread_enable_lock_debugging()
void evthread_enable_lock_debugging (void)
Definition at line 318 of file evthread.c.
{
    struct evthread_lock_callbacks cbs = {
        EVTHREAD_LOCK_API_VERSION,
        EVTHREAD_LOCKTYPE_RECURSIVE,
        debug_lock_alloc,
        debug_lock_free,
        debug_lock_lock,
        debug_lock_unlock
    };
    if (evthread_lock_debugging_enabled_)
        return;
    memcpy(&original_lock_fns_, &evthread_lock_fns_,
        sizeof(struct evthread_lock_callbacks));
    memcpy(&evthread_lock_fns_, &cbs,
        sizeof(struct evthread_lock_callbacks));
    memcpy(&original_cond_fns_, &evthread_cond_fns_,
        sizeof(struct evthread_condition_callbacks));
    evthread_cond_fns_.wait_condition = debug_cond_wait;
    evthread_lock_debugging_enabled_ = 1;
    /* XXX return value should get checked. */
    event_global_setup_locks_(0);
}
References debug_cond_wait(), debug_lock_alloc(), debug_lock_free(), debug_lock_lock(), debug_lock_unlock(), event_global_setup_locks_(), evthread_cond_fns_, evthread_lock_debugging_enabled_, evthread_lock_fns_, original_cond_fns_, and original_lock_fns_.
Referenced by evthread_enable_lock_debuging().
evthread_enable_lock_debuging()
void evthread_enable_lock_debuging (void)
Definition at line 312 of file evthread.c.
{
    evthread_enable_lock_debugging();
}
References evthread_enable_lock_debugging().
evthread_get_condition_callbacks()
struct evthread_condition_callbacks * evthread_get_condition_callbacks (void)
Return current evthread_condition_callbacks
Definition at line 82 of file evthread.c.
{
    return evthread_lock_debugging_enabled_
        ? &original_cond_fns_ : &evthread_cond_fns_;
}
References evthread_cond_fns_, evthread_lock_debugging_enabled_, and original_cond_fns_.
Referenced by evthread_set_condition_callbacks().
evthread_get_lock_callbacks()
struct evthread_lock_callbacks * evthread_get_lock_callbacks (void)
Return current evthread_lock_callbacks
Definition at line 77 of file evthread.c.
{
    return evthread_lock_debugging_enabled_
        ? &original_lock_fns_ : &evthread_lock_fns_;
}
References evthread_lock_debugging_enabled_, evthread_lock_fns_, and original_lock_fns_.
Referenced by evthread_set_lock_callbacks().
evthread_is_debug_lock_held_()
int evthread_is_debug_lock_held_ (void * lock_)
Definition at line 345 of file evthread.c.
{
    struct debug_lock *lock = lock_;
    if (! lock->count)
        return 0;
    if (evthread_id_fn_) {
        unsigned long me = evthread_id_fn_();
        if (lock->held_by != me)
            return 0;
    }
    return 1;
}
References evthread_id_fn_, and debug_lock::lock.
evthread_set_condition_callbacks()
int evthread_set_condition_callbacks (const struct evthread_condition_callbacks * cbs)
Definition at line 136 of file evthread.c.
{
    struct evthread_condition_callbacks *target = evthread_get_condition_callbacks();
#ifndef EVENT__DISABLE_DEBUG_MODE
    if (event_debug_mode_on_) {
        if (event_debug_created_threadable_ctx_) {
            event_errx(1, "evthread initialization must be called BEFORE anything else!");
        }
    }
#endif
    if (!cbs) {
        if (target->alloc_condition)
            event_warnx("Trying to disable condition functions "
                "after they have been set up will probaby not "
                "work.");
        memset(target, 0, sizeof(evthread_cond_fns_));
        return 0;
    }
    if (target->alloc_condition) {
        /* Uh oh; we already had condition callbacks set up.*/
        if (target->condition_api_version == cbs->condition_api_version &&
            target->alloc_condition == cbs->alloc_condition &&
            target->free_condition == cbs->free_condition &&
            target->signal_condition == cbs->signal_condition &&
            target->wait_condition == cbs->wait_condition) {
            /* no change -- allow this. */
            return 0;
        }
        event_warnx("Can't change condition callbacks once they "
            "have been initialized.");
        return -1;
    }
    if (cbs->alloc_condition && cbs->free_condition &&
        cbs->signal_condition && cbs->wait_condition) {
        memcpy(target, cbs, sizeof(evthread_cond_fns_));
    }
    if (evthread_lock_debugging_enabled_) {
        evthread_cond_fns_.alloc_condition = cbs->alloc_condition;
        evthread_cond_fns_.free_condition = cbs->free_condition;
        evthread_cond_fns_.signal_condition = cbs->signal_condition;
    }
    return 0;
}
References event_debug_created_threadable_ctx_, event_debug_mode_on_, event_errx(), event_warnx(), evthread_cond_fns_, evthread_get_condition_callbacks(), and evthread_lock_debugging_enabled_.
Referenced by evthread_use_pthreads(), and evthread_use_windows_threads().
evthread_set_id_callback()
void evthread_set_id_callback (unsigned long(*)(void) id_fn)
Definition at line 72 of file evthread.c.
{
    evthread_id_fn_ = id_fn;
}
References evthread_id_fn_.
Referenced by evthread_use_pthreads(), and evthread_use_windows_threads().
evthread_set_lock_callbacks()
int evthread_set_lock_callbacks (const struct evthread_lock_callbacks * cbs)
Definition at line 93 of file evthread.c.
{
    struct evthread_lock_callbacks *target = evthread_get_lock_callbacks();
#ifndef EVENT__DISABLE_DEBUG_MODE
    if (event_debug_mode_on_) {
        if (event_debug_created_threadable_ctx_) {
            event_errx(1, "evthread initialization must be called BEFORE anything else!");
        }
    }
#endif
    if (!cbs) {
        if (target->alloc)
            event_warnx("Trying to disable lock functions after "
                "they have been set up will probaby not work.");
        memset(target, 0, sizeof(evthread_lock_fns_));
        return 0;
    }
    if (target->alloc) {
        /* Uh oh; we already had locking callbacks set up.*/
        if (target->lock_api_version == cbs->lock_api_version &&
            target->supported_locktypes == cbs->supported_locktypes &&
            target->alloc == cbs->alloc &&
            target->free == cbs->free &&
            target->lock == cbs->lock &&
            target->unlock == cbs->unlock) {
            /* no change -- allow this. */
            return 0;
        }
        event_warnx("Can't change lock callbacks once they have been "
            "initialized.");
        return -1;
    }
    if (cbs->alloc && cbs->free && cbs->lock && cbs->unlock) {
        memcpy(target, cbs, sizeof(evthread_lock_fns_));
        return event_global_setup_locks_(1);
    } else {
        return -1;
    }
}
References event_debug_created_threadable_ctx_, event_debug_mode_on_, event_errx(), event_global_setup_locks_(), event_warnx(), evthread_get_lock_callbacks(), and evthread_lock_fns_.
Referenced by evthread_use_pthreads(), and evthread_use_windows_threads().
evthread_setup_global_lock_()
void * evthread_setup_global_lock_ (void * lock_, unsigned locktype, int enable_locks)
Definition at line 366 of file evthread.c.
{
    /* there are four cases here:
       1) we're turning on debugging; locking is not on.
       2) we're turning on debugging; locking is on.
       3) we're turning on locking; debugging is not on.
       4) we're turning on locking; debugging is on. */
    if (!enable_locks && original_lock_fns_.alloc == NULL) {
        /* Case 1: allocate a debug lock. */
        EVUTIL_ASSERT(lock_ == NULL);
        return debug_lock_alloc(locktype);
    } else if (!enable_locks && original_lock_fns_.alloc != NULL) {
        /* Case 2: wrap the lock in a debug lock. */
        struct debug_lock *lock;
        EVUTIL_ASSERT(lock_ != NULL);
        if (!(locktype & EVTHREAD_LOCKTYPE_RECURSIVE)) {
            /* We can't wrap it: We need a recursive lock */
            original_lock_fns_.free(lock_, locktype);
            return debug_lock_alloc(locktype);
        }
        lock = mm_malloc(sizeof(struct debug_lock));
        if (!lock) {
            original_lock_fns_.free(lock_, locktype);
            return NULL;
        }
        lock->lock = lock_;
        lock->locktype = locktype;
        lock->count = 0;
        lock->held_by = 0;
        return lock;
    } else if (enable_locks && ! evthread_lock_debugging_enabled_) {
        /* Case 3: allocate a regular lock */
        EVUTIL_ASSERT(lock_ == NULL);
        return evthread_lock_fns_.alloc(locktype);
    } else {
        /* Case 4: Fill in a debug lock with a real lock */
        struct debug_lock *lock = lock_ ? lock_ : debug_lock_alloc(locktype);
        EVUTIL_ASSERT(enable_locks &&
                      evthread_lock_debugging_enabled_);
        EVUTIL_ASSERT(lock->locktype == locktype);
        if (!lock->lock) {
            lock->lock = original_lock_fns_.alloc(
                locktype|EVTHREAD_LOCKTYPE_RECURSIVE);
            if (!lock->lock) {
                lock->count = -200;
                mm_free(lock);
                return NULL;
            }
        }
        return lock;
    }
}
References debug_lock_alloc(), evthread_lock_debugging_enabled_, evthread_lock_fns_, EVUTIL_ASSERT, debug_lock::lock, debug_lock::locktype, mm_free, mm_malloc, and original_lock_fns_.
evthreadimpl_disable_lock_debugging_()
void evthreadimpl_disable_lock_debugging_ (void)
Disable locking for internal usage (like global shutdown)
Definition at line 87 of file evthread.c.
{
    evthread_lock_debugging_enabled_ = 0;
}
References evthread_lock_debugging_enabled_.
Referenced by event_free_debug_globals_locks().
Variable Documentation
event_debug_created_threadable_ctx_
int event_debug_created_threadable_ctx_ extern
debug mode variable which is set for any function/structure that needs to be shared across threads (if thread support is enabled).
When and if evthreads are initialized, this variable will be evaluated, and if set to something other than zero, this means the evthread setup functions were called out of order.
See: "Locks and threading" in the documentation.
Definition at line 219 of file event.c.
Referenced by event_base_new_with_config(), evthread_set_condition_callbacks(), and evthread_set_lock_callbacks().
event_debug_mode_on_
int event_debug_mode_on_ extern
Definition at line 205 of file event.c.
Referenced by event_debug_assert_is_setup_(), event_debug_assert_not_added_(), event_debug_assert_socket_nonblocking_(), event_debug_note_add_(), event_debug_note_del_(), event_debug_note_teardown_(), event_disable_debug_mode(), event_enable_debug_mode(), evthread_set_condition_callbacks(), and evthread_set_lock_callbacks().
evthread_cond_fns_
GLOBAL struct evthread_condition_callbacks evthread_cond_fns_
Initial value:
= {
    0, NULL, NULL, NULL, NULL
}
Definition at line 59 of file evthread.c.
Referenced by evthread_enable_lock_debugging(), evthread_get_condition_callbacks(), and evthread_set_condition_callbacks().
evthread_id_fn_
GLOBAL unsigned long(* evthread_id_fn_) (void) (void) = NULL
Definition at line 58 of file evthread.c.
Referenced by evthread_debug_lock_mark_locked(), evthread_debug_lock_mark_unlocked(), evthread_is_debug_lock_held_(), and evthread_set_id_callback().
evthread_lock_debugging_enabled_
GLOBAL int evthread_lock_debugging_enabled_ = 0
Definition at line 54 of file evthread.c.
Referenced by evthread_enable_lock_debugging(), evthread_get_condition_callbacks(), evthread_get_lock_callbacks(), evthread_set_condition_callbacks(), evthread_setup_global_lock_(), and evthreadimpl_disable_lock_debugging_().
evthread_lock_fns_
GLOBAL struct evthread_lock_callbacks evthread_lock_fns_
Initial value:
= {
    0, 0, NULL, NULL, NULL, NULL
}
Definition at line 55 of file evthread.c.
Referenced by EVLOCK_TRY_LOCK_(), evthread_enable_lock_debugging(), evthread_get_lock_callbacks(), evthread_set_lock_callbacks(), and evthread_setup_global_lock_().
original_cond_fns_
struct evthread_condition_callbacks original_cond_fns_ static
Initial value:
= {
    0, NULL, NULL, NULL, NULL
}
Definition at line 67 of file evthread.c.
Referenced by debug_cond_wait(), evthread_enable_lock_debugging(), and evthread_get_condition_callbacks().
original_lock_fns_
struct evthread_lock_callbacks original_lock_fns_ static
Initial value:
= {
    0, 0, NULL, NULL, NULL, NULL
}
Definition at line 64 of file evthread.c.
Referenced by debug_lock_alloc(), debug_lock_free(), debug_lock_lock(), debug_lock_unlock(), evthread_enable_lock_debugging(), evthread_get_lock_callbacks(), and evthread_setup_global_lock_().