libdogecoin: src/libevent/evutil_time.c File Reference
evutil_time.c File Reference
#include "event2/event-config.h"
#include "evconfig-private.h"
#include <sys/types.h>
#include <errno.h>
#include <limits.h>
#include <sys/timeb.h>
#include <sys/select.h>
#include <time.h>
#include <sys/stat.h>
#include <string.h>
#include "event2/util.h"
#include "util-internal.h"
#include "log-internal.h"
#include "mm-internal.h"
Macros
#define U64_LITERAL(n) n##llu
#define EPOCH_BIAS U64_LITERAL(116444736000000000)
#define UNITS_PER_SEC U64_LITERAL(10000000)
#define USEC_PER_SEC U64_LITERAL(1000000)
#define UNITS_PER_USEC U64_LITERAL(10)
#define MAX_SECONDS_IN_MSEC_LONG (((LONG_MAX) - 999) / 1000)
Typedefs
typedef void(WINAPI * GetSystemTimePreciseAsFileTime_fn_t) (LPFILETIME)
Functions
int evutil_gettimeofday (struct timeval *tv, struct timezone *tz)
long evutil_tv_to_msec_ (const struct timeval *tv)
void evutil_usleep_ (const struct timeval *tv)
int evutil_date_rfc1123 (char *date, const size_t datelen, const struct tm *tm)
static void adjust_monotonic_time (struct evutil_monotonic_timer *base, struct timeval *tv)
struct evutil_monotonic_timer * evutil_monotonic_timer_new (void)
void evutil_monotonic_timer_free (struct evutil_monotonic_timer *timer)
int evutil_configure_monotonic_time (struct evutil_monotonic_timer *timer, int flags)
int evutil_gettime_monotonic (struct evutil_monotonic_timer *timer, struct timeval *tp)
int evutil_configure_monotonic_time_ (struct evutil_monotonic_timer *base, int precise)
int evutil_gettime_monotonic_ (struct evutil_monotonic_timer *base, struct timeval *tp)
Macro Definition Documentation
EPOCH_BIAS
#define EPOCH_BIAS U64_LITERAL(116444736000000000)
MAX_SECONDS_IN_MSEC_LONG
#define MAX_SECONDS_IN_MSEC_LONG (((LONG_MAX) - 999) / 1000)
Definition at line 124 of file evutil_time.c.
U64_LITERAL
#define U64_LITERAL (n) n##llu
UNITS_PER_SEC
#define UNITS_PER_SEC U64_LITERAL(10000000)
UNITS_PER_USEC
#define UNITS_PER_USEC U64_LITERAL(10)
USEC_PER_SEC
#define USEC_PER_SEC U64_LITERAL(1000000)
Typedef Documentation
GetSystemTimePreciseAsFileTime_fn_t
typedef void(WINAPI * GetSystemTimePreciseAsFileTime_fn_t) (LPFILETIME)
evutil_usleep_()
Definition at line 69 of file evutil_time.c.
Function Documentation
adjust_monotonic_time()
static void adjust_monotonic_time (struct evutil_monotonic_timer * base, struct timeval * tv) static
Definition at line 231 of file evutil_time.c.
{
    evutil_timeradd(tv, &base->adjust_monotonic_clock, tv);
    if (evutil_timercmp(tv, &base->last_time, <)) {
        /* Guess it wasn't monotonic after all. */
        struct timeval adjust;
        evutil_timersub(&base->last_time, tv, &adjust);
        evutil_timeradd(&adjust, &base->adjust_monotonic_clock,
            &base->adjust_monotonic_clock);
        *tv = base->last_time;
    }
    base->last_time = *tv;
}
References evutil_monotonic_timer::adjust_monotonic_clock, and evutil_monotonic_timer::last_time.
Referenced by evutil_gettime_monotonic_().
evutil_configure_monotonic_time()
int evutil_configure_monotonic_time (struct evutil_monotonic_timer * timer, int flags)
Definition at line 279 of file evutil_time.c.
{
  return evutil_configure_monotonic_time_(timer, flags);
}
References evutil_configure_monotonic_time_().
evutil_configure_monotonic_time_()
int evutil_configure_monotonic_time_ (struct evutil_monotonic_timer * base, int precise)
Definition at line 604 of file evutil_time.c.
{
    memset(base, 0, sizeof(*base));
    return 0;
}
Referenced by event_base_new_with_config(), and evutil_configure_monotonic_time().
evutil_date_rfc1123()
int evutil_date_rfc1123 (char * date, const size_t datelen, const struct tm * tm)
detect _gmtime64()/_gmtime64_s()
Definition at line 184 of file evutil_time.c.
{
    static const char *DAYS[] =
        { "Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat" };
    static const char *MONTHS[] =
        { "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec" };
    time_t t = time(NULL);
#if defined(EVENT__HAVE__GMTIME64_S) || !defined(_WIN32)
    struct tm sys;
#endif
    /* If `tm` is null, set system's current time. */
    if (tm == NULL) {
#if !defined(_WIN32)
        gmtime_r(&t, &sys);
        tm = &sys;
#elif defined(EVENT__HAVE__GMTIME64_S)
        errno_t err;
        err = _gmtime64_s(&sys, &t);
        if (err) {
            event_errx(1, "Invalid argument to _gmtime64_s");
        } else {
            tm = &sys;
        }
#elif defined(EVENT__HAVE__GMTIME64)
        tm = _gmtime64(&t);
#else
        tm = gmtime(&t);
#endif
    }
    return evutil_snprintf(
        date, datelen, "%s, %02d %s %4d %02d:%02d:%02d GMT",
        DAYS[tm->tm_wday], tm->tm_mday, MONTHS[tm->tm_mon],
        1900 + tm->tm_year, tm->tm_hour, tm->tm_min, tm->tm_sec);
}
References errno_t, event_errx(), and evutil_snprintf().
Referenced by evhttp_maybe_add_date_header().
evutil_gettime_monotonic()
int evutil_gettime_monotonic (struct evutil_monotonic_timer * timer, struct timeval * tp)
Definition at line 289 of file evutil_time.c.
{
  return evutil_gettime_monotonic_(timer, tp);
}
References evutil_gettime_monotonic_().
evutil_gettime_monotonic_()
int evutil_gettime_monotonic_ (struct evutil_monotonic_timer * base, struct timeval * tp)
Definition at line 612 of file evutil_time.c.
{
    if (evutil_gettimeofday(tp, NULL) < 0)
        return -1;
    adjust_monotonic_time(base, tp);
    return 0;
}
References adjust_monotonic_time(), and evutil_gettimeofday().
Referenced by event_gettime_monotonic(), evutil_gettime_monotonic(), and gettime().
evutil_gettimeofday()
int evutil_gettimeofday (struct timeval * tv, struct timezone * tz)
Definition at line 72 of file evutil_time.c.
{
#ifdef _MSC_VER
#define U64_LITERAL(n) n##ui64
#else
#define U64_LITERAL(n) n##llu
#endif
    /* Conversion logic taken from Tor, which in turn took it
     * from Perl.  GetSystemTimeAsFileTime returns its value as
     * an unaligned (!) 64-bit value containing the number of
     * 100-nanosecond intervals since 1 January 1601 UTC. */
#define EPOCH_BIAS U64_LITERAL(116444736000000000)
#define UNITS_PER_SEC U64_LITERAL(10000000)
#define USEC_PER_SEC U64_LITERAL(1000000)
#define UNITS_PER_USEC U64_LITERAL(10)
    union {
        FILETIME ft_ft;
        ev_uint64_t ft_64;
    } ft;
    if (tv == NULL)
        return -1;
    static GetSystemTimePreciseAsFileTime_fn_t GetSystemTimePreciseAsFileTime_fn = NULL;
    static int check_precise = 1;
    if (EVUTIL_UNLIKELY(check_precise)) {
        HMODULE h = evutil_load_windows_system_library_(TEXT("kernel32.dll"));
        if (h != NULL)
            GetSystemTimePreciseAsFileTime_fn =
                (GetSystemTimePreciseAsFileTime_fn_t)
                    GetProcAddress(h, "GetSystemTimePreciseAsFileTime");
        check_precise = 0;
    }
    if (GetSystemTimePreciseAsFileTime_fn != NULL)
        GetSystemTimePreciseAsFileTime_fn(&ft.ft_ft);
    else
        GetSystemTimeAsFileTime(&ft.ft_ft);
    if (EVUTIL_UNLIKELY(ft.ft_64 < EPOCH_BIAS)) {
        /* Time before the unix epoch. */
        return -1;
    }
    ft.ft_64 -= EPOCH_BIAS;
    tv->tv_sec = (long) (ft.ft_64 / UNITS_PER_SEC);
    tv->tv_usec = (long) ((ft.ft_64 / UNITS_PER_USEC) % USEC_PER_SEC);
    return 0;
}
References EPOCH_BIAS, EVUTIL_UNLIKELY, UNITS_PER_SEC, UNITS_PER_USEC, and USEC_PER_SEC.
Referenced by event_base_gettimeofday_cached(), evthread_posix_cond_wait(), evutil_gettime_monotonic_(), evutil_weakrand_seed_(), and gettime().
evutil_monotonic_timer_free()
void evutil_monotonic_timer_free (struct evutil_monotonic_timer * timer)
Definition at line 268 of file evutil_time.c.
{
  if (timer) {
    mm_free(timer);
  }
}
References mm_free.
evutil_monotonic_timer_new()
struct evutil_monotonic_timer * evutil_monotonic_timer_new (void)
Definition at line 251 of file evutil_time.c.
{
  struct evutil_monotonic_timer *p = NULL;
  p = mm_malloc(sizeof(*p));
  if (!p) goto done;
  memset(p, 0, sizeof(*p));
 done:
  return p;
}
References mm_malloc.
evutil_tv_to_msec_()
long evutil_tv_to_msec_ (const struct timeval * tv)
Definition at line 128 of file evutil_time.c.
{
    if (tv->tv_usec > 1000000 || tv->tv_sec > MAX_SECONDS_IN_MSEC_LONG)
        return -1;
    return (tv->tv_sec * 1000) + ((tv->tv_usec + 999) / 1000);
}
References MAX_SECONDS_IN_MSEC_LONG.
Referenced by evthread_win32_cond_wait().
evutil_usleep_()
void evutil_usleep_ (const struct timeval * tv)
Definition at line 141 of file evutil_time.c.
{
    if (!tv)
        return;
#if defined(_WIN32)
    {
        __int64 usec;
        LARGE_INTEGER li;
        HANDLE timer;
        usec = tv->tv_sec * 1000000LL + tv->tv_usec;
        if (!usec)
            return;
        li.QuadPart = -10LL * usec;
        timer = CreateWaitableTimer(NULL, TRUE, NULL);
        if (!timer)
            return;
        SetWaitableTimer(timer, &li, 0, NULL, NULL, 0);
        WaitForSingleObject(timer, INFINITE);
        CloseHandle(timer);
    }
#elif defined(EVENT__HAVE_NANOSLEEP)
    {
        struct timespec ts;
        ts.tv_sec = tv->tv_sec;
        ts.tv_nsec = tv->tv_usec*1000;
        nanosleep(&ts, NULL);
    }
#elif defined(EVENT__HAVE_USLEEP)
    /* Some systems don't like to usleep more than 999999 usec */
    sleep(tv->tv_sec);
    usleep(tv->tv_usec);
#else
    {
        struct timeval tv2 = *tv;
        select(0, NULL, NULL, NULL, &tv2);
    }
#endif
}