libdogecoin: src/libevent/evutil.c File Reference
evutil.c File Reference
#include "event2/event-config.h"
#include "evconfig-private.h"
#include <sys/types.h>
#include <errno.h>
#include <limits.h>
#include <stdio.h>
#include <string.h>
#include <time.h>
#include <sys/stat.h>
#include <net/if.h>
#include "event2/util.h"
#include "util-internal.h"
#include "log-internal.h"
#include "mm-internal.h"
#include "evthread-internal.h"
#include "strlcpy-internal.h"
#include "ipv6-internal.h"
Macros
#define N_TO_READ(x) (x)
#define ERR(e) e
#define EVUTIL_AI_LIBEVENT_ALLOCATED 0x80000000
#define USE_INTERNAL_NTOP
#define USE_INTERNAL_PTON
#define IMPL_CTYPE_FN(name)
#define SOCKET_TYPE_MASK (~(EVUTIL_SOCK_NONBLOCK|EVUTIL_SOCK_CLOEXEC))
#define LOCAL_SOCKETPAIR_AF AF_UNIX
Functions
int evutil_open_closeonexec_ (const char *pathname, int flags, unsigned mode)
int evutil_read_file_ (const char *filename, char **content_out, size_t *len_out, int is_binary)
int evutil_socketpair (int family, int type, int protocol, evutil_socket_t fd[2])
int evutil_ersatz_socketpair_ (int family, int type, int protocol, evutil_socket_t fd[2])
int evutil_make_socket_nonblocking (evutil_socket_t fd)
static int evutil_fast_socket_nonblocking (evutil_socket_t fd)
int evutil_make_listen_socket_reuseable (evutil_socket_t sock)
int evutil_make_listen_socket_reuseable_port (evutil_socket_t sock)
int evutil_make_listen_socket_ipv6only (evutil_socket_t sock)
int evutil_make_tcp_listen_socket_deferred (evutil_socket_t sock)
int evutil_make_socket_closeonexec (evutil_socket_t fd)
static int evutil_fast_socket_closeonexec (evutil_socket_t fd)
int evutil_closesocket (evutil_socket_t sock)
ev_int64_t evutil_strtoll (const char *s, char **endptr, int base)
int evutil_socket_connect_ (evutil_socket_t *fd_ptr, const struct sockaddr *sa, int socklen)
int evutil_socket_finished_connecting_ (evutil_socket_t fd)
static int evutil_v4addr_is_localhost (ev_uint32_t addr)
static int evutil_v4addr_is_linklocal (ev_uint32_t addr)
static int evutil_v4addr_is_classd (ev_uint32_t addr)
int evutil_v4addr_is_local_ (const struct in_addr *in)
int evutil_v6addr_is_local_ (const struct in6_addr *in)
static void evutil_found_ifaddr (const struct sockaddr *sa)
static int evutil_check_ifaddrs (void)
static int evutil_check_interfaces (void)
struct evutil_addrinfo * evutil_new_addrinfo_ (struct sockaddr *sa, ev_socklen_t socklen, const struct evutil_addrinfo *hints)
struct evutil_addrinfo * evutil_addrinfo_append_ (struct evutil_addrinfo *first, struct evutil_addrinfo *append)
static int parse_numeric_servname (const char *servname)
static int evutil_parse_servname (const char *servname, const char *protocol, const struct evutil_addrinfo *hints)
static const char * evutil_unparse_protoname (int proto)
static void evutil_getaddrinfo_infer_protocols (struct evutil_addrinfo *hints)
int evutil_getaddrinfo_common_ (const char *nodename, const char *servname, struct evutil_addrinfo *hints, struct evutil_addrinfo **res, int *portnum)
static struct evutil_addrinfo * addrinfo_from_hostent (const struct hostent *ent, int port, const struct evutil_addrinfo *hints)
void evutil_adjust_hints_for_addrconfig_ (struct evutil_addrinfo *hints)
int evutil_getaddrinfo (const char *nodename, const char *servname, const struct evutil_addrinfo *hints_in, struct evutil_addrinfo **res)
void evutil_freeaddrinfo (struct evutil_addrinfo *ai)
void evutil_set_evdns_getaddrinfo_fn_ (evdns_getaddrinfo_fn fn)
void evutil_set_evdns_getaddrinfo_cancel_fn_ (evdns_getaddrinfo_cancel_fn fn)
struct evdns_getaddrinfo_request * evutil_getaddrinfo_async_ (struct evdns_base *dns_base, const char *nodename, const char *servname, const struct evutil_addrinfo *hints_in, void(*cb)(int, struct evutil_addrinfo *, void *), void *arg)
void evutil_getaddrinfo_cancel_async_ (struct evdns_getaddrinfo_request *data)
const char * evutil_gai_strerror (int err)
int evutil_global_setup_locks_ (const int enable_locks)
static void evutil_free_sock_err_globals (void)
int evutil_snprintf (char *buf, size_t buflen, const char *format,...)
int evutil_vsnprintf (char *buf, size_t buflen, const char *format, va_list ap)
const char * evutil_inet_ntop (int af, const void *src, char *dst, size_t len)
int evutil_inet_pton_scope (int af, const char *src, void *dst, unsigned *indexp)
int evutil_inet_pton (int af, const char *src, void *dst)
int evutil_parse_sockaddr_port (const char *ip_as_string, struct sockaddr *out, int *outlen)
const char * evutil_format_sockaddr_port_ (const struct sockaddr *sa, char *out, size_t outlen)
int evutil_sockaddr_cmp (const struct sockaddr *sa1, const struct sockaddr *sa2, int include_port)
char EVUTIL_TOLOWER_ (char c)
char EVUTIL_TOUPPER_ (char c)
int evutil_ascii_strcasecmp (const char *s1, const char *s2)
int evutil_ascii_strncasecmp (const char *s1, const char *s2, size_t n)
void evutil_rtrim_lws_ (char *str)
static int evutil_issetugid (void)
const char * evutil_getenv_ (const char *varname)
ev_uint32_t evutil_weakrand_seed_ (struct evutil_weakrand_state *state, ev_uint32_t seed)
ev_int32_t evutil_weakrand_ (struct evutil_weakrand_state *state)
ev_int32_t evutil_weakrand_range_ (struct evutil_weakrand_state *state, ev_int32_t top)
void evutil_memclear_ (void *mem, size_t len)
int evutil_sockaddr_is_loopback_ (const struct sockaddr *addr)
int evutil_hex_char_to_int_ (char c)
evutil_socket_t evutil_socket_ (int domain, int type, int protocol)
evutil_socket_t evutil_accept4_ (evutil_socket_t sockfd, struct sockaddr *addr, ev_socklen_t *addrlen, int flags)
int evutil_make_internal_pipe_ (evutil_socket_t fd[2])
evutil_socket_t evutil_eventfd_ (unsigned initval, int flags)
void evutil_free_globals_ (void)
Variables
static int have_checked_interfaces
static int had_ipv4_address
static int had_ipv6_address
static evdns_getaddrinfo_fn evdns_getaddrinfo_impl = NULL
static evdns_getaddrinfo_cancel_fn evdns_getaddrinfo_cancel_impl = NULL
static const ev_uint32_t EVUTIL_ISALPHA_TABLE [8]
static const ev_uint32_t EVUTIL_ISALNUM_TABLE [8]
static const ev_uint32_t EVUTIL_ISSPACE_TABLE [8] = { 0x3e00, 0x1, 0, 0, 0, 0, 0, 0 }
static const ev_uint32_t EVUTIL_ISXDIGIT_TABLE [8]
static const ev_uint32_t EVUTIL_ISDIGIT_TABLE [8] = { 0, 0x3ff0000, 0, 0, 0, 0, 0, 0 }
static const ev_uint32_t EVUTIL_ISPRINT_TABLE [8]
static const ev_uint32_t EVUTIL_ISUPPER_TABLE [8] = { 0, 0, 0x7fffffe, 0, 0, 0, 0, 0 }
static const ev_uint32_t EVUTIL_ISLOWER_TABLE [8] = { 0, 0, 0, 0x7fffffe, 0, 0, 0, 0 }
static const unsigned char EVUTIL_TOUPPER_TABLE [256]
static const unsigned char EVUTIL_TOLOWER_TABLE [256]
void *(*volatile evutil_memset_volatile_)(void *, int, size_t) = memset
Macro Definition Documentation
ERR
#define ERR (e) e
EVUTIL_AI_LIBEVENT_ALLOCATED
#define EVUTIL_AI_LIBEVENT_ALLOCATED 0x80000000
Definition at line 824 of file evutil.c.
IMPL_CTYPE_FN
#define IMPL_CTYPE_FN (name)
Value:
    int EVUTIL_##name##_(char c) {                  \
        ev_uint8_t u = c;                   \
        return !!(EVUTIL_##name##_TABLE[(u >> 5) & 7] & (1U << (u & 31))); \
    }
Definition at line 2369 of file evutil.c.
LOCAL_SOCKETPAIR_AF
#define LOCAL_SOCKETPAIR_AF AF_UNIX
N_TO_READ
#define N_TO_READ (x) (x)
SOCKET_TYPE_MASK
#define SOCKET_TYPE_MASK (~(EVUTIL_SOCK_NONBLOCK|EVUTIL_SOCK_CLOEXEC))
USE_INTERNAL_NTOP
#define USE_INTERNAL_NTOP
Definition at line 1892 of file evutil.c.
USE_INTERNAL_PTON
#define USE_INTERNAL_PTON
Definition at line 1893 of file evutil.c.
Function Documentation
addrinfo_from_hostent()
static struct evutil_addrinfo * addrinfo_from_hostent (const struct hostent * ent, int port, const struct evutil_addrinfo * hints) static
Definition at line 1173 of file evutil.c.
{
    int i;
    struct sockaddr_in sin;
    struct sockaddr_in6 sin6;
    struct sockaddr *sa;
    int socklen;
    struct evutil_addrinfo *res=NULL, *ai;
    void *addrp;
    if (ent->h_addrtype == PF_INET) {
        memset(&sin, 0, sizeof(sin));
        sin.sin_family = AF_INET;
        sin.sin_port = htons(port);
        sa = (struct sockaddr *)&sin;
        socklen = sizeof(struct sockaddr_in);
        addrp = &sin.sin_addr;
        if (ent->h_length != sizeof(sin.sin_addr)) {
            event_warnx("Weird h_length from gethostbyname");
            return NULL;
        }
    } else if (ent->h_addrtype == PF_INET6) {
        memset(&sin6, 0, sizeof(sin6));
        sin6.sin6_family = AF_INET6;
        sin6.sin6_port = htons(port);
        sa = (struct sockaddr *)&sin6;
        socklen = sizeof(struct sockaddr_in6);
        addrp = &sin6.sin6_addr;
        if (ent->h_length != sizeof(sin6.sin6_addr)) {
            event_warnx("Weird h_length from gethostbyname");
            return NULL;
        }
    } else
        return NULL;
    for (i = 0; ent->h_addr_list[i]; ++i) {
        memcpy(addrp, ent->h_addr_list[i], ent->h_length);
        ai = evutil_new_addrinfo_(sa, socklen, hints);
        if (!ai) {
            evutil_freeaddrinfo(res);
            return NULL;
        }
        res = evutil_addrinfo_append_(res, ai);
    }
    if (res && ((hints->ai_flags & EVUTIL_AI_CANONNAME) && ent->h_name)) {
        res->ai_canonname = mm_strdup(ent->h_name);
        if (res->ai_canonname == NULL) {
            evutil_freeaddrinfo(res);
            return NULL;
        }
    }
    return res;
}
References AF_INET6, event_warnx(), evutil_addrinfo_append_(), evutil_freeaddrinfo(), evutil_new_addrinfo_(), mm_strdup, PF_INET6, sockaddr_in6::sin6_addr, sockaddr_in6::sin6_family, and sockaddr_in6::sin6_port.
Referenced by evutil_getaddrinfo().
evutil_accept4_()
evutil_socket_t evutil_accept4_ (evutil_socket_t sockfd, struct sockaddr * addr, ev_socklen_t * addrlen, int flags)
Definition at line 2633 of file evutil.c.
{
    evutil_socket_t result;
#if defined(EVENT__HAVE_ACCEPT4) && defined(SOCK_CLOEXEC) && defined(SOCK_NONBLOCK)
    result = accept4(sockfd, addr, addrlen, flags);
    if (result >= 0 || (errno != EINVAL && errno != ENOSYS)) {
        /* A nonnegative result means that we succeeded, so return.
         * Failing with EINVAL means that an option wasn't supported,
         * and failing with ENOSYS means that the syscall wasn't
         * there: in those cases we want to fall back.  Otherwise, we
         * got a real error, and we should return. */
        return result;
    }
#endif
    result = accept(sockfd, addr, addrlen);
    if (result < 0)
        return result;
    if (flags & EVUTIL_SOCK_CLOEXEC) {
        if (evutil_fast_socket_closeonexec(result) < 0) {
            evutil_closesocket(result);
            return -1;
        }
    }
    if (flags & EVUTIL_SOCK_NONBLOCK) {
        if (evutil_fast_socket_nonblocking(result) < 0) {
            evutil_closesocket(result);
            return -1;
        }
    }
    return result;
}
References evutil_closesocket(), evutil_fast_socket_closeonexec(), evutil_fast_socket_nonblocking(), EVUTIL_SOCK_CLOEXEC, and EVUTIL_SOCK_NONBLOCK.
Referenced by listener_read_cb().
evutil_addrinfo_append_()
struct evutil_addrinfo * evutil_addrinfo_append_ (struct evutil_addrinfo * first, struct evutil_addrinfo * append)
Definition at line 877 of file evutil.c.
{
    struct evutil_addrinfo *ai = first;
    if (!ai)
        return append;
    while (ai->ai_next)
        ai = ai->ai_next;
    ai->ai_next = append;
    return first;
}
References append().
Referenced by addrinfo_from_hostent(), evdns_getaddrinfo_fromhosts(), evdns_getaddrinfo_gotresolve(), and evutil_getaddrinfo_common_().
evutil_adjust_hints_for_addrconfig_()
void evutil_adjust_hints_for_addrconfig_ (struct evutil_addrinfo * hints)
Definition at line 1236 of file evutil.c.
{
    if (!(hints->ai_flags & EVUTIL_AI_ADDRCONFIG))
        return;
    if (hints->ai_family != PF_UNSPEC)
        return;
    evutil_check_interfaces();
    if (had_ipv4_address && !had_ipv6_address) {
        hints->ai_family = PF_INET;
    } else if (!had_ipv4_address && had_ipv6_address) {
        hints->ai_family = PF_INET6;
    }
}
References evutil_check_interfaces(), had_ipv4_address, had_ipv6_address, and PF_INET6.
Referenced by evdns_getaddrinfo(), and evutil_getaddrinfo().
evutil_ascii_strcasecmp()
int evutil_ascii_strcasecmp (const char * s1, const char * s2)
Definition at line 2392 of file evutil.c.
{
    char c1, c2;
    while (1) {
        c1 = EVUTIL_TOLOWER_(*s1++);
        c2 = EVUTIL_TOLOWER_(*s2++);
        if (c1 < c2)
            return -1;
        else if (c1 > c2)
            return 1;
        else if (c1 == 0)
            return 0;
    }
}
References EVUTIL_TOLOWER_().
Referenced by evhttp_find_alias(), evhttp_find_header(), evhttp_get_body(), evhttp_get_body_length(), evhttp_have_expect(), evhttp_is_connection_close(), evhttp_parse_request_line(), evhttp_remove_header(), evhttp_remove_server_alias(), find_hosts_entry(), and reply_parse().
evutil_ascii_strncasecmp()
int evutil_ascii_strncasecmp (const char * s1, const char * s2, size_t n)
Definition at line 2406 of file evutil.c.
{
    char c1, c2;
    while (n--) {
        c1 = EVUTIL_TOLOWER_(*s1++);
        c2 = EVUTIL_TOLOWER_(*s2++);
        if (c1 < c2)
            return -1;
        else if (c1 > c2)
            return 1;
        else if (c1 == 0)
            return 0;
    }
    return 0;
}
References EVUTIL_TOLOWER_().
Referenced by evhttp_is_connection_keepalive().
evutil_check_ifaddrs()
static int evutil_check_ifaddrs (void) static
Definition at line 676 of file evutil.c.
{
#if defined(EVENT__HAVE_GETIFADDRS)
    /* Most free Unixy systems provide getifaddrs, which gives us a linked list
     * of struct ifaddrs. */
    struct ifaddrs *ifa = NULL;
    const struct ifaddrs *i;
    if (getifaddrs(&ifa) < 0) {
        event_warn("Unable to call getifaddrs()");
        return -1;
    }
    for (i = ifa; i; i = i->ifa_next) {
        if (!i->ifa_addr)
            continue;
        evutil_found_ifaddr(i->ifa_addr);
    }
    freeifaddrs(ifa);
    return 0;
#elif defined(_WIN32)
    /* Windows XP began to provide GetAdaptersAddresses. Windows 2000 had a
       "GetAdaptersInfo", but that's deprecated; let's just try
       GetAdaptersAddresses and fall back to connect+getsockname.
    */
    HMODULE lib = evutil_load_windows_system_library_(TEXT("iphlpapi.dll"));
    GetAdaptersAddresses_fn_t fn;
    ULONG size, res;
    IP_ADAPTER_ADDRESSES *addresses = NULL, *address;
    int result = -1;
#define FLAGS (GAA_FLAG_SKIP_ANYCAST | \
               GAA_FLAG_SKIP_MULTICAST | \
               GAA_FLAG_SKIP_DNS_SERVER)
    if (!lib)
        goto done;
    if (!(fn = (GetAdaptersAddresses_fn_t) GetProcAddress(lib, "GetAdaptersAddresses")))
        goto done;
    /* Guess how much space we need. */
    size = 15*1024;
    addresses = mm_malloc(size);
    if (!addresses)
        goto done;
    res = fn(AF_UNSPEC, FLAGS, NULL, addresses, &size);
    if (res == ERROR_BUFFER_OVERFLOW) {
        /* we didn't guess that we needed enough space; try again */
        mm_free(addresses);
        addresses = mm_malloc(size);
        if (!addresses)
            goto done;
        res = fn(AF_UNSPEC, FLAGS, NULL, addresses, &size);
    }
    if (res != NO_ERROR)
        goto done;
    for (address = addresses; address; address = address->Next) {
        IP_ADAPTER_UNICAST_ADDRESS *a;
        for (a = address->FirstUnicastAddress; a; a = a->Next) {
            /* Yes, it's a linked list inside a linked list */
            struct sockaddr *sa = a->Address.lpSockaddr;
            evutil_found_ifaddr(sa);
        }
    }
    result = 0;
done:
    if (lib)
        FreeLibrary(lib);
    if (addresses)
        mm_free(addresses);
    return result;
#else
    return -1;
#endif
}
References event_warn(), evutil_found_ifaddr(), mm_free, and mm_malloc.
Referenced by evutil_check_interfaces().
evutil_check_interfaces()
static int evutil_check_interfaces (void) static
Definition at line 758 of file evutil.c.
{
    evutil_socket_t fd = -1;
    struct sockaddr_in sin, sin_out;
    struct sockaddr_in6 sin6, sin6_out;
    ev_socklen_t sin_out_len = sizeof(sin_out);
    ev_socklen_t sin6_out_len = sizeof(sin6_out);
    int r;
    if (have_checked_interfaces)
        return 0;
    /* From this point on we have done the ipv4/ipv6 interface check */
    have_checked_interfaces = 1;
    if (evutil_check_ifaddrs() == 0) {
        /* Use a nice sane interface, if this system has one. */
        return 0;
    }
    /* Ugh. There was no nice sane interface.  So to check whether we have
     * an interface open for a given protocol, will try to make a UDP
     * 'connection' to a remote host on the internet.  We don't actually
     * use it, so the address doesn't matter, but we want to pick one that
     * keep us from using a host- or link-local interface. */
    memset(&sin, 0, sizeof(sin));
    sin.sin_family = AF_INET;
    sin.sin_port = htons(53);
    r = evutil_inet_pton(AF_INET, "18.244.0.188", &sin.sin_addr);
    EVUTIL_ASSERT(r);
    memset(&sin6, 0, sizeof(sin6));
    sin6.sin6_family = AF_INET6;
    sin6.sin6_port = htons(53);
    r = evutil_inet_pton(AF_INET6, "2001:4860:b002::68", &sin6.sin6_addr);
    EVUTIL_ASSERT(r);
    memset(&sin_out, 0, sizeof(sin_out));
    memset(&sin6_out, 0, sizeof(sin6_out));
    /* XXX some errnos mean 'no address'; some mean 'not enough sockets'. */
    if ((fd = socket(AF_INET, SOCK_DGRAM, IPPROTO_UDP)) >= 0 &&
        connect(fd, (struct sockaddr*)&sin, sizeof(sin)) == 0 &&
        getsockname(fd, (struct sockaddr*)&sin_out, &sin_out_len) == 0) {
        /* We might have an IPv4 interface. */
        evutil_found_ifaddr((struct sockaddr*) &sin_out);
    }
    if (fd >= 0)
        evutil_closesocket(fd);
    if ((fd = socket(AF_INET6, SOCK_DGRAM, IPPROTO_UDP)) >= 0 &&
        connect(fd, (struct sockaddr*)&sin6, sizeof(sin6)) == 0 &&
        getsockname(fd, (struct sockaddr*)&sin6_out, &sin6_out_len) == 0) {
        /* We might have an IPv6 interface. */
        evutil_found_ifaddr((struct sockaddr*) &sin6_out);
    }
    if (fd >= 0)
        evutil_closesocket(fd);
    return 0;
}
References AF_INET6, EVUTIL_ASSERT, evutil_check_ifaddrs(), evutil_closesocket(), evutil_found_ifaddr(), evutil_inet_pton(), have_checked_interfaces, sockaddr_in6::sin6_addr, sockaddr_in6::sin6_family, and sockaddr_in6::sin6_port.
Referenced by evutil_adjust_hints_for_addrconfig_().
evutil_closesocket()
int evutil_closesocket (evutil_socket_t sock)
Definition at line 454 of file evutil.c.
{
#ifndef _WIN32
    return close(sock);
#else
    return closesocket(sock);
#endif
}
Referenced by be_async_destruct(), be_openssl_destruct(), bufferevent_socket_connect(), create_bind_socket_nonblock(), evconnlistener_new_bind(), evdns_base_clear_nameservers_and_suspend(), evdns_nameserver_add_impl_(), evdns_nameserver_free(), event_listener_destroy(), evhttp_bind_socket_with_handle(), evhttp_connection_free(), evhttp_connection_reset_(), evhttp_get_request(), evsig_dealloc_(), evutil_accept4_(), evutil_check_interfaces(), evutil_ersatz_socketpair_(), evutil_eventfd_(), evutil_make_internal_pipe_(), evutil_socket_(), evutil_socket_connect_(), listener_read_cb(), and server_port_free().
evutil_ersatz_socketpair_()
int evutil_ersatz_socketpair_ (int family, int type, int protocol, evutil_socket_t fd[2])
Definition at line 212 of file evutil.c.
{
    /* This code is originally from Tor.  Used with permission. */
    /* This socketpair does not work when localhost is down. So
     * it's really not the same thing at all. But it's close enough
     * for now, and really, when localhost is down sometimes, we
     * have other problems too.
     */
#ifdef _WIN32
#define ERR(e) WSA##e
#else
#define ERR(e) e
#endif
    evutil_socket_t listener = -1;
    evutil_socket_t connector = -1;
    evutil_socket_t acceptor = -1;
    struct sockaddr_in listen_addr;
    struct sockaddr_in connect_addr;
    ev_socklen_t size;
    int saved_errno = -1;
    int family_test;
    family_test = family != AF_INET;
#ifdef AF_UNIX
    family_test = family_test && (family != AF_UNIX);
#endif
    if (protocol || family_test) {
        EVUTIL_SET_SOCKET_ERROR(ERR(EAFNOSUPPORT));
        return -1;
    }
    if (!fd) {
        EVUTIL_SET_SOCKET_ERROR(ERR(EINVAL));
        return -1;
    }
    listener = socket(AF_INET, type, 0);
    if (listener < 0)
        return -1;
    memset(&listen_addr, 0, sizeof(listen_addr));
    listen_addr.sin_family = AF_INET;
    listen_addr.sin_addr.s_addr = htonl(INADDR_LOOPBACK);
    listen_addr.sin_port = 0;   /* kernel chooses port.  */
    if (bind(listener, (struct sockaddr *) &listen_addr, sizeof (listen_addr))
        == -1)
        goto tidy_up_and_fail;
    if (listen(listener, 1) == -1)
        goto tidy_up_and_fail;
    connector = socket(AF_INET, type, 0);
    if (connector < 0)
        goto tidy_up_and_fail;
    memset(&connect_addr, 0, sizeof(connect_addr));
    /* We want to find out the port number to connect to.  */
    size = sizeof(connect_addr);
    if (getsockname(listener, (struct sockaddr *) &connect_addr, &size) == -1)
        goto tidy_up_and_fail;
    if (size != sizeof (connect_addr))
        goto abort_tidy_up_and_fail;
    if (connect(connector, (struct sockaddr *) &connect_addr,
                sizeof(connect_addr)) == -1)
        goto tidy_up_and_fail;
    size = sizeof(listen_addr);
    acceptor = accept(listener, (struct sockaddr *) &listen_addr, &size);
    if (acceptor < 0)
        goto tidy_up_and_fail;
    if (size != sizeof(listen_addr))
        goto abort_tidy_up_and_fail;
    /* Now check we are talking to ourself by matching port and host on the
       two sockets.  */
    if (getsockname(connector, (struct sockaddr *) &connect_addr, &size) == -1)
        goto tidy_up_and_fail;
    if (size != sizeof (connect_addr)
        || listen_addr.sin_family != connect_addr.sin_family
        || listen_addr.sin_addr.s_addr != connect_addr.sin_addr.s_addr
        || listen_addr.sin_port != connect_addr.sin_port)
        goto abort_tidy_up_and_fail;
    evutil_closesocket(listener);
    fd[0] = connector;
    fd[1] = acceptor;
    return 0;
 abort_tidy_up_and_fail:
    saved_errno = ERR(ECONNABORTED);
 tidy_up_and_fail:
    if (saved_errno < 0)
        saved_errno = EVUTIL_SOCKET_ERROR();
    if (listener != -1)
        evutil_closesocket(listener);
    if (connector != -1)
        evutil_closesocket(connector);
    if (acceptor != -1)
        evutil_closesocket(acceptor);
    EVUTIL_SET_SOCKET_ERROR(saved_errno);
    return -1;
#undef ERR
}
References ERR, and evutil_closesocket().
Referenced by evutil_socketpair().
evutil_eventfd_()
evutil_socket_t evutil_eventfd_ (unsigned initval, int flags)
Definition at line 2730 of file evutil.c.
{
#if defined(EVENT__HAVE_EVENTFD) && defined(EVENT__HAVE_SYS_EVENTFD_H)
    int r;
#if defined(EFD_CLOEXEC) && defined(EFD_NONBLOCK)
    r = eventfd(initval, flags);
    if (r >= 0 || flags == 0)
        return r;
#endif
    r = eventfd(initval, 0);
    if (r < 0)
        return r;
    if (flags & EVUTIL_EFD_CLOEXEC) {
        if (evutil_fast_socket_closeonexec(r) < 0) {
            evutil_closesocket(r);
            return -1;
        }
    }
    if (flags & EVUTIL_EFD_NONBLOCK) {
        if (evutil_fast_socket_nonblocking(r) < 0) {
            evutil_closesocket(r);
            return -1;
        }
    }
    return r;
#else
    return -1;
#endif
}
References evutil_closesocket(), EVUTIL_EFD_CLOEXEC, EVUTIL_EFD_NONBLOCK, evutil_fast_socket_closeonexec(), and evutil_fast_socket_nonblocking().
Referenced by evthread_make_base_notifiable_nolock_().
evutil_fast_socket_closeonexec()
static int evutil_fast_socket_closeonexec (evutil_socket_t fd) static
Definition at line 442 of file evutil.c.
{
#if !defined(_WIN32) && defined(EVENT__HAVE_SETFD)
    if (fcntl(fd, F_SETFD, FD_CLOEXEC) == -1) {
        event_warn("fcntl(%d, F_SETFD)", fd);
        return -1;
    }
#endif
    return 0;
}
References event_warn().
Referenced by evutil_accept4_(), evutil_eventfd_(), evutil_make_internal_pipe_(), and evutil_socket_().
evutil_fast_socket_nonblocking()
static int evutil_fast_socket_nonblocking (evutil_socket_t fd) static
Definition at line 351 of file evutil.c.
{
#ifdef _WIN32
    return evutil_make_socket_nonblocking(fd);
#else
    if (fcntl(fd, F_SETFL, O_NONBLOCK) == -1) {
        event_warn("fcntl(%d, F_SETFL)", fd);
        return -1;
    }
    return 0;
#endif
}
References event_warn(), and evutil_make_socket_nonblocking().
Referenced by evutil_accept4_(), evutil_eventfd_(), evutil_make_internal_pipe_(), and evutil_socket_().
evutil_format_sockaddr_port_()
const char * evutil_format_sockaddr_port_ (const struct sockaddr * sa, char * out, size_t outlen)
Formats a sockaddr sa into a string buffer of size outlen stored in out. Returns a pointer to out. Always writes something into out, so it's safe to use the output of this function without checking it for NULL.
Definition at line 2246 of file evutil.c.
{
    char b[128];
    const char *res=NULL;
    int port;
    if (sa->sa_family == AF_INET) {
        const struct sockaddr_in *sin = (const struct sockaddr_in*)sa;
        res = evutil_inet_ntop(AF_INET, &sin->sin_addr,b,sizeof(b));
        port = ntohs(sin->sin_port);
        if (res) {
            evutil_snprintf(out, outlen, "%s:%d", b, port);
            return out;
        }
    } else if (sa->sa_family == AF_INET6) {
        const struct sockaddr_in6 *sin6 = (const struct sockaddr_in6*)sa;
        res = evutil_inet_ntop(AF_INET6, &sin6->sin6_addr,b,sizeof(b));
        port = ntohs(sin6->sin6_port);
        if (res) {
            evutil_snprintf(out, outlen, "[%s]:%d", b, port);
            return out;
        }
    }
    evutil_snprintf(out, outlen, "<addr with socktype %d>",
        (int)sa->sa_family);
    return out;
}
References AF_INET6, evutil_inet_ntop(), evutil_snprintf(), sockaddr_in6::sin6_addr, and sockaddr_in6::sin6_port.
Referenced by evdns_nameserver_add_impl_(), nameserver_failed(), nameserver_probe_failed(), nameserver_read(), nameserver_send_probe(), nameserver_up(), nameserver_write_waiting(), and reply_handle().
evutil_found_ifaddr()
static void evutil_found_ifaddr (const struct sockaddr * sa) static
Definition at line 653 of file evutil.c.
{
    if (sa->sa_family == AF_INET) {
        const struct sockaddr_in *sin = (struct sockaddr_in *)sa;
        if (!evutil_v4addr_is_local_(&sin->sin_addr)) {
            event_debug(("Detected an IPv4 interface"));
            had_ipv4_address = 1;
        }
    } else if (sa->sa_family == AF_INET6) {
        const struct sockaddr_in6 *sin6 = (struct sockaddr_in6 *)sa;
        if (!evutil_v6addr_is_local_(&sin6->sin6_addr)) {
            event_debug(("Detected an IPv6 interface"));
            had_ipv6_address = 1;
        }
    }
}
References AF_INET6, event_debug, evutil_v4addr_is_local_(), evutil_v6addr_is_local_(), had_ipv4_address, had_ipv6_address, and sockaddr_in6::sin6_addr.
Referenced by evutil_check_ifaddrs(), and evutil_check_interfaces().
evutil_free_globals_()
void evutil_free_globals_ (void)
Definition at line 2761 of file evutil.c.
{
    evutil_free_secure_rng_globals_();
    evutil_free_sock_err_globals();
}
References evutil_free_secure_rng_globals_(), and evutil_free_sock_err_globals().
Referenced by event_free_evutil_globals().
evutil_free_sock_err_globals()
static void evutil_free_sock_err_globals (void) static
Definition at line 1851 of file evutil.c.
{
}
Referenced by evutil_free_globals_().
evutil_freeaddrinfo()
void evutil_freeaddrinfo (struct evutil_addrinfo * ai)
Definition at line 1576 of file evutil.c.
{
#ifdef EVENT__HAVE_GETADDRINFO
    if (!(ai->ai_flags & EVUTIL_AI_LIBEVENT_ALLOCATED)) {
        freeaddrinfo(ai);
        return;
    }
#endif
    while (ai) {
        struct evutil_addrinfo *next = ai->ai_next;
        if (ai->ai_canonname)
            mm_free(ai->ai_canonname);
        mm_free(ai);
        ai = next;
    }
}
References EVUTIL_AI_LIBEVENT_ALLOCATED, and mm_free.
Referenced by addrinfo_from_hostent(), bind_socket(), bufferevent_connect_getaddrinfo_cb(), dogecoin_get_peers_from_dns(), evdns_getaddrinfo_fromhosts(), evdns_getaddrinfo_gotresolve(), evutil_getaddrinfo(), evutil_getaddrinfo_common_(), evutil_new_addrinfo_(), and free_getaddrinfo_request().
evutil_gai_strerror()
const char * evutil_gai_strerror (int err)
Definition at line 1639 of file evutil.c.
{
    /* As a sneaky side-benefit, this case statement will get most
     * compilers to tell us if any of the error codes we defined
     * conflict with the platform's native error codes. */
    switch (err) {
    case EVUTIL_EAI_CANCEL:
        return "Request canceled";
    case 0:
        return "No error";
    case EVUTIL_EAI_ADDRFAMILY:
        return "address family for nodename not supported";
    case EVUTIL_EAI_AGAIN:
        return "temporary failure in name resolution";
    case EVUTIL_EAI_BADFLAGS:
        return "invalid value for ai_flags";
    case EVUTIL_EAI_FAIL:
        return "non-recoverable failure in name resolution";
    case EVUTIL_EAI_FAMILY:
        return "ai_family not supported";
    case EVUTIL_EAI_MEMORY:
        return "memory allocation failure";
    case EVUTIL_EAI_NODATA:
        return "no address associated with nodename";
    case EVUTIL_EAI_NONAME:
        return "nodename nor servname provided, or not known";
    case EVUTIL_EAI_SERVICE:
        return "servname not supported for ai_socktype";
    case EVUTIL_EAI_SOCKTYPE:
        return "ai_socktype not supported";
    case EVUTIL_EAI_SYSTEM:
        return "system error";
    default:
#if defined(USE_NATIVE_GETADDRINFO) && defined(_WIN32)
        return gai_strerrorA(err);
#elif defined(USE_NATIVE_GETADDRINFO)
        return gai_strerror(err);
#else
        return "Unknown error code";
#endif
    }
}
Referenced by make_addrinfo().
evutil_getaddrinfo()
int evutil_getaddrinfo (const char * nodename, const char * servname, const struct evutil_addrinfo * hints_in, struct evutil_addrinfo ** res)
Definition at line 1385 of file evutil.c.
{
#ifdef USE_NATIVE_GETADDRINFO
    struct evutil_addrinfo hints;
    int portnum=-1, need_np_hack, err;
    if (hints_in) {
        memcpy(&hints, hints_in, sizeof(hints));
    } else {
        memset(&hints, 0, sizeof(hints));
        hints.ai_family = PF_UNSPEC;
    }
#ifndef AI_ADDRCONFIG
    /* Not every system has AI_ADDRCONFIG, so fake it. */
    if (hints.ai_family == PF_UNSPEC &&
        (hints.ai_flags & EVUTIL_AI_ADDRCONFIG)) {
        evutil_adjust_hints_for_addrconfig_(&hints);
    }
#endif
#ifndef AI_NUMERICSERV
    /* Not every system has AI_NUMERICSERV, so fake it. */
    if (hints.ai_flags & EVUTIL_AI_NUMERICSERV) {
        if (servname && parse_numeric_servname(servname)<0)
            return EVUTIL_EAI_NONAME;
    }
#endif
    /* Enough operating systems handle enough common non-resolve
     * cases here weirdly enough that we are better off just
     * overriding them.  For example:
     *
     * - Windows doesn't like to infer the protocol from the
     *   socket type, or fill in socket or protocol types much at
     *   all.  It also seems to do its own broken implicit
     *   always-on version of AI_ADDRCONFIG that keeps it from
     *   ever resolving even a literal IPv6 address when
     *   ai_addrtype is PF_UNSPEC.
     */
#ifdef _WIN32
    {
        int tmp_port;
        err = evutil_getaddrinfo_common_(nodename,servname,&hints,
            res, &tmp_port);
        if (err == 0 ||
            err == EVUTIL_EAI_MEMORY ||
            err == EVUTIL_EAI_NONAME)
            return err;
        /* If we make it here, the system getaddrinfo can
         * have a crack at it. */
    }
#endif
    /* See documentation for need_numeric_port_hack above.*/
    need_np_hack = need_numeric_port_hack() && servname && !hints.ai_socktype
        && ((portnum=parse_numeric_servname(servname)) >= 0);
    if (need_np_hack) {
        if (!nodename)
            return evutil_getaddrinfo_common_(
                NULL,servname,&hints, res, &portnum);
        servname = NULL;
    }
    if (need_socktype_protocol_hack()) {
        evutil_getaddrinfo_infer_protocols(&hints);
    }
    /* Make sure that we didn't actually steal any AI_FLAGS values that
     * the system is using.  (This is a constant expression, and should ge
     * optimized out.)
     *
     * XXXX Turn this into a compile-time failure rather than a run-time
     * failure.
     */
    EVUTIL_ASSERT((ALL_NONNATIVE_AI_FLAGS & ALL_NATIVE_AI_FLAGS) == 0);
    /* Clear any flags that only libevent understands. */
    hints.ai_flags &= ~ALL_NONNATIVE_AI_FLAGS;
    err = getaddrinfo(nodename, servname, &hints, res);
    if (need_np_hack)
        apply_numeric_port_hack(portnum, res);
    if (need_socktype_protocol_hack()) {
        if (apply_socktype_protocol_hack(*res) < 0) {
            evutil_freeaddrinfo(*res);
            *res = NULL;
            return EVUTIL_EAI_MEMORY;
        }
    }
    return err;
#else
    int port=0, err;
    struct hostent *ent = NULL;
    struct evutil_addrinfo hints;
    if (hints_in) {
        memcpy(&hints, hints_in, sizeof(hints));
    } else {
        memset(&hints, 0, sizeof(hints));
        hints.ai_family = PF_UNSPEC;
    }
    evutil_adjust_hints_for_addrconfig_(&hints);
    err = evutil_getaddrinfo_common_(nodename, servname, &hints, res, &port);
    if (err != EVUTIL_EAI_NEED_RESOLVE) {
        /* We either succeeded or failed.  No need to continue */
        return err;
    }
    err = 0;
    /* Use any of the various gethostbyname_r variants as available. */
    {
#ifdef EVENT__HAVE_GETHOSTBYNAME_R_6_ARG
        /* This one is what glibc provides. */
        char buf[2048];
        struct hostent hostent;
        int r;
        r = gethostbyname_r(nodename, &hostent, buf, sizeof(buf), &ent,
            &err);
#elif defined(EVENT__HAVE_GETHOSTBYNAME_R_5_ARG)
        char buf[2048];
        struct hostent hostent;
        ent = gethostbyname_r(nodename, &hostent, buf, sizeof(buf),
            &err);
#elif defined(EVENT__HAVE_GETHOSTBYNAME_R_3_ARG)
        struct hostent_data data;
        struct hostent hostent;
        memset(&data, 0, sizeof(data));
        err = gethostbyname_r(nodename, &hostent, &data);
        ent = err ? NULL : &hostent;
#else
        /* fall back to gethostbyname. */
        /* XXXX This needs a lock everywhere but Windows. */
        ent = gethostbyname(nodename);
#ifdef _WIN32
        err = WSAGetLastError();
#else
        err = h_errno;
#endif
#endif
        /* Now we have either ent or err set. */
        if (!ent) {
            /* XXX is this right for windows ? */
            switch (err) {
            case TRY_AGAIN:
                return EVUTIL_EAI_AGAIN;
            case NO_RECOVERY:
            default:
                return EVUTIL_EAI_FAIL;
            case HOST_NOT_FOUND:
                return EVUTIL_EAI_NONAME;
            case NO_ADDRESS:
#if NO_DATA != NO_ADDRESS
            case NO_DATA:
#endif
                return EVUTIL_EAI_NODATA;
            }
        }
        if (ent->h_addrtype != hints.ai_family &&
            hints.ai_family != PF_UNSPEC) {
            /* This wasn't the type we were hoping for.  Too bad
             * we never had a chance to ask gethostbyname for what
             * we wanted. */
            return EVUTIL_EAI_NONAME;
        }
        /* Make sure we got _some_ answers. */
        if (ent->h_length == 0)
            return EVUTIL_EAI_NODATA;
        /* If we got an address type we don't know how to make a
           sockaddr for, give up. */
        if (ent->h_addrtype != PF_INET && ent->h_addrtype != PF_INET6)
            return EVUTIL_EAI_FAMILY;
        *res = addrinfo_from_hostent(ent, port, &hints);
        if (! *res)
            return EVUTIL_EAI_MEMORY;
    }
    return 0;
#endif
}
References addrinfo_from_hostent(), evutil_adjust_hints_for_addrconfig_(), EVUTIL_ASSERT, EVUTIL_EAI_NEED_RESOLVE, evutil_freeaddrinfo(), evutil_getaddrinfo_common_(), evutil_getaddrinfo_infer_protocols(), parse_numeric_servname(), and PF_INET6.
Referenced by dogecoin_get_peers_from_dns(), evdns_getaddrinfo(), evutil_getaddrinfo_async_(), and make_addrinfo().
evutil_getaddrinfo_async_()
struct evdns_getaddrinfo_request * evutil_getaddrinfo_async_ (struct evdns_base * dns_base, const char * nodename, const char * servname, const struct evutil_addrinfo * hints_in, void(*)(int, struct evutil_addrinfo *, void *) cb, void * arg)
Definition at line 1613 of file evutil.c.
{
    if (dns_base && evdns_getaddrinfo_impl) {
        return evdns_getaddrinfo_impl(
            dns_base, nodename, servname, hints_in, cb, arg);
    } else {
        struct evutil_addrinfo *ai=NULL;
        int err;
        err = evutil_getaddrinfo(nodename, servname, hints_in, &ai);
        cb(err, ai, arg);
        return NULL;
    }
}
References evdns_getaddrinfo_impl, and evutil_getaddrinfo().
Referenced by bufferevent_socket_connect_hostname().
evutil_getaddrinfo_cancel_async_()
void evutil_getaddrinfo_cancel_async_ (struct evdns_getaddrinfo_request * data)
Definition at line 1631 of file evutil.c.
{
    if (evdns_getaddrinfo_cancel_impl && data) {
        evdns_getaddrinfo_cancel_impl(data);
    }
}
References evdns_getaddrinfo_cancel_impl.
Referenced by be_socket_destruct(), and be_socket_setfd().
evutil_getaddrinfo_common_()
int evutil_getaddrinfo_common_ (const char * nodename, const char * servname, struct evutil_addrinfo * hints, struct evutil_addrinfo ** res, int * portnum)
Implements the part of looking up hosts by name that's common to both the blocking and nonblocking resolver:
Adjust 'hints' to have a reasonable socktype and protocol.
Look up the port based on 'servname', and store it in *portnum,
Handle the nodename==NULL case
Handle some invalid arguments cases.
Handle the cases where nodename is an IPv4 or IPv6 address.
If we need the resolver to look up the hostname, we return EVUTIL_EAI_NEED_RESOLVE. Otherwise, we can completely implement getaddrinfo: we return 0 or an appropriate EVUTIL_EAI_* error, and set *res as getaddrinfo would.
Definition at line 993 of file evutil.c.
{
    int port = 0;
    unsigned int if_index;
    const char *pname;
    if (nodename == NULL && servname == NULL)
        return EVUTIL_EAI_NONAME;
    /* We only understand 3 families */
    if (hints->ai_family != PF_UNSPEC && hints->ai_family != PF_INET &&
        hints->ai_family != PF_INET6)
        return EVUTIL_EAI_FAMILY;
    evutil_getaddrinfo_infer_protocols(hints);
    /* Look up the port number and protocol, if possible. */
    pname = evutil_unparse_protoname(hints->ai_protocol);
    if (servname) {
        /* XXXX We could look at the protocol we got back from
         * getservbyname, but it doesn't seem too useful. */
        port = evutil_parse_servname(servname, pname, hints);
        if (port < 0) {
            return EVUTIL_EAI_NONAME;
        }
    }
    /* If we have no node name, then we're supposed to bind to 'any' and
     * connect to localhost. */
    if (nodename == NULL) {
        struct evutil_addrinfo *res4=NULL, *res6=NULL;
        if (hints->ai_family != PF_INET) { /* INET6 or UNSPEC. */
            struct sockaddr_in6 sin6;
            memset(&sin6, 0, sizeof(sin6));
            sin6.sin6_family = AF_INET6;
            sin6.sin6_port = htons(port);
            if (hints->ai_flags & EVUTIL_AI_PASSIVE) {
                /* Bind to :: */
            } else {
                /* connect to ::1 */
                sin6.sin6_addr.s6_addr[15] = 1;
            }
            res6 = evutil_new_addrinfo_((struct sockaddr*)&sin6,
                sizeof(sin6), hints);
            if (!res6)
                return EVUTIL_EAI_MEMORY;
        }
        if (hints->ai_family != PF_INET6) { /* INET or UNSPEC */
            struct sockaddr_in sin;
            memset(&sin, 0, sizeof(sin));
            sin.sin_family = AF_INET;
            sin.sin_port = htons(port);
            if (hints->ai_flags & EVUTIL_AI_PASSIVE) {
                /* Bind to 0.0.0.0 */
            } else {
                /* connect to 127.0.0.1 */
                sin.sin_addr.s_addr = htonl(0x7f000001);
            }
            res4 = evutil_new_addrinfo_((struct sockaddr*)&sin,
                sizeof(sin), hints);
            if (!res4) {
                if (res6)
                    evutil_freeaddrinfo(res6);
                return EVUTIL_EAI_MEMORY;
            }
        }
        *res = evutil_addrinfo_append_(res4, res6);
        return 0;
    }
    /* If we can, we should try to parse the hostname without resolving
     * it. */
    /* Try ipv6. */
    if (hints->ai_family == PF_INET6 || hints->ai_family == PF_UNSPEC) {
        struct sockaddr_in6 sin6;
        memset(&sin6, 0, sizeof(sin6));
        if (1 == evutil_inet_pton_scope(
            AF_INET6, nodename, &sin6.sin6_addr, &if_index)) {
            /* Got an ipv6 address. */
            sin6.sin6_family = AF_INET6;
            sin6.sin6_port = htons(port);
            sin6.sin6_scope_id = if_index;
            *res = evutil_new_addrinfo_((struct sockaddr*)&sin6,
                sizeof(sin6), hints);
            if (!*res)
                return EVUTIL_EAI_MEMORY;
            return 0;
        }
    }
    /* Try ipv4. */
    if (hints->ai_family == PF_INET || hints->ai_family == PF_UNSPEC) {
        struct sockaddr_in sin;
        memset(&sin, 0, sizeof(sin));
        if (1==evutil_inet_pton(AF_INET, nodename, &sin.sin_addr)) {
            /* Got an ipv4 address. */
            sin.sin_family = AF_INET;
            sin.sin_port = htons(port);
            *res = evutil_new_addrinfo_((struct sockaddr*)&sin,
                sizeof(sin), hints);
            if (!*res)
                return EVUTIL_EAI_MEMORY;
            return 0;
        }
    }
    /* If we have reached this point, we definitely need to do a DNS
     * lookup. */
    if ((hints->ai_flags & EVUTIL_AI_NUMERICHOST)) {
        /* If we're not allowed to do one, then say so. */
        return EVUTIL_EAI_NONAME;
    }
    *portnum = port;
    return EVUTIL_EAI_NEED_RESOLVE;
}
References AF_INET6, evutil_addrinfo_append_(), EVUTIL_EAI_NEED_RESOLVE, evutil_freeaddrinfo(), evutil_getaddrinfo_infer_protocols(), evutil_inet_pton(), evutil_inet_pton_scope(), evutil_new_addrinfo_(), evutil_parse_servname(), evutil_unparse_protoname(), PF_INET6, in6_addr::s6_addr, sockaddr_in6::sin6_addr, sockaddr_in6::sin6_family, and sockaddr_in6::sin6_port.
Referenced by evdns_getaddrinfo(), and evutil_getaddrinfo().
evutil_getaddrinfo_infer_protocols()
static void evutil_getaddrinfo_infer_protocols (struct evutil_addrinfo * hints) static
Definition at line 952 of file evutil.c.
{
    /* If we can guess the protocol from the socktype, do so. */
    if (!hints->ai_protocol && hints->ai_socktype) {
        if (hints->ai_socktype == SOCK_DGRAM)
            hints->ai_protocol = IPPROTO_UDP;
        else if (hints->ai_socktype == SOCK_STREAM)
            hints->ai_protocol = IPPROTO_TCP;
    }
    /* Set the socktype if it isn't set. */
    if (!hints->ai_socktype && hints->ai_protocol) {
        if (hints->ai_protocol == IPPROTO_UDP)
            hints->ai_socktype = SOCK_DGRAM;
        else if (hints->ai_protocol == IPPROTO_TCP)
            hints->ai_socktype = SOCK_STREAM;
#ifdef IPPROTO_SCTP
        else if (hints->ai_protocol == IPPROTO_SCTP)
            hints->ai_socktype = SOCK_STREAM;
#endif
    }
}
Referenced by evutil_getaddrinfo(), and evutil_getaddrinfo_common_().
evutil_getenv_()
const char * evutil_getenv_ (const char * varname)
Definition at line 2463 of file evutil.c.
{
    if (evutil_issetugid())
        return NULL;
    return getenv(varname);
}
References evutil_issetugid().
Referenced by event_base_new_with_config(), and event_is_method_disabled().
evutil_global_setup_locks_()
int evutil_global_setup_locks_ (const int enable_locks)
Definition at line 1844 of file evutil.c.
{
    return 0;
}
Referenced by event_global_setup_locks_().
evutil_hex_char_to_int_()
int evutil_hex_char_to_int_ (char c)
Definition at line 2547 of file evutil.c.
{
    switch(c)
    {
        case '0': return 0;
        case '1': return 1;
        case '2': return 2;
        case '3': return 3;
        case '4': return 4;
        case '5': return 5;
        case '6': return 6;
        case '7': return 7;
        case '8': return 8;
        case '9': return 9;
        case 'A': case 'a': return 10;
        case 'B': case 'b': return 11;
        case 'C': case 'c': return 12;
        case 'D': case 'd': return 13;
        case 'E': case 'e': return 14;
        case 'F': case 'f': return 15;
    }
    return -1;
}
evutil_inet_ntop()
const char * evutil_inet_ntop (int af, const void * src, char * dst, size_t len)
Definition at line 1896 of file evutil.c.
{
#if defined(EVENT__HAVE_INET_NTOP) && !defined(USE_INTERNAL_NTOP)
    return inet_ntop(af, src, dst, len);
#else
    if (af == AF_INET) {
        const struct in_addr *in = src;
        const ev_uint32_t a = ntohl(in->s_addr);
        int r;
        r = evutil_snprintf(dst, len, "%d.%d.%d.%d",
            (int)(ev_uint8_t)((a>>24)&0xff),
            (int)(ev_uint8_t)((a>>16)&0xff),
            (int)(ev_uint8_t)((a>>8 )&0xff),
            (int)(ev_uint8_t)((a    )&0xff));
        if (r<0||(size_t)r>=len)
            return NULL;
        else
            return dst;
#ifdef AF_INET6
    } else if (af == AF_INET6) {
        const struct in6_addr *addr = src;
        char buf[64], *cp;
        int longestGapLen = 0, longestGapPos = -1, i,
            curGapPos = -1, curGapLen = 0;
        ev_uint16_t words[8];
        for (i = 0; i < 8; ++i) {
            words[i] =
                (((ev_uint16_t)addr->s6_addr[2*i])<<8) + addr->s6_addr[2*i+1];
        }
        if (words[0] == 0 && words[1] == 0 && words[2] == 0 && words[3] == 0 &&
            words[4] == 0 && ((words[5] == 0 && words[6] && words[7]) ||
            (words[5] == 0xffff))) {
            /* This is an IPv4 address. */
            if (words[5] == 0) {
                evutil_snprintf(buf, sizeof(buf), "::%d.%d.%d.%d",
                    addr->s6_addr[12], addr->s6_addr[13],
                    addr->s6_addr[14], addr->s6_addr[15]);
            } else {
                evutil_snprintf(buf, sizeof(buf), "::%x:%d.%d.%d.%d", words[5],
                    addr->s6_addr[12], addr->s6_addr[13],
                    addr->s6_addr[14], addr->s6_addr[15]);
            }
            if (strlen(buf) > len)
                return NULL;
            strlcpy(dst, buf, len);
            return dst;
        }
        i = 0;
        while (i < 8) {
            if (words[i] == 0) {
                curGapPos = i++;
                curGapLen = 1;
                while (i<8 && words[i] == 0) {
                    ++i; ++curGapLen;
                }
                if (curGapLen > longestGapLen) {
                    longestGapPos = curGapPos;
                    longestGapLen = curGapLen;
                }
            } else {
                ++i;
            }
        }
        if (longestGapLen<=1)
            longestGapPos = -1;
        cp = buf;
        for (i = 0; i < 8; ++i) {
            if (words[i] == 0 && longestGapPos == i) {
                if (i == 0)
                    *cp++ = ':';
                *cp++ = ':';
                while (i < 8 && words[i] == 0)
                    ++i;
                --i; /* to compensate for loop increment. */
            } else {
                evutil_snprintf(cp,
                                sizeof(buf)-(cp-buf), "%x", (unsigned)words[i]);
                cp += strlen(cp);
                if (i != 7)
                    *cp++ = ':';
            }
        }
        *cp = '\0';
        if (strlen(buf) > len)
            return NULL;
        strlcpy(dst, buf, len);
        return dst;
#endif
    } else {
        return NULL;
    }
#endif
}
References AF_INET6, evutil_snprintf(), in6_addr::s6_addr, and strlcpy.
Referenced by broadcast_handshake_done(), dogecoin_get_peers_from_dns(), and evutil_format_sockaddr_port_().
evutil_inet_pton()
int evutil_inet_pton (int af, const char * src, void * dst)
Definition at line 2027 of file evutil.c.
{
#if defined(EVENT__HAVE_INET_PTON) && !defined(USE_INTERNAL_PTON)
    return inet_pton(af, src, dst);
#else
    if (af == AF_INET) {
        unsigned a,b,c,d;
        char more;
        struct in_addr *addr = dst;
        if (sscanf(src, "%u.%u.%u.%u%c", &a,&b,&c,&d,&more) != 4)
            return 0;
        if (a > 255) return 0;
        if (b > 255) return 0;
        if (c > 255) return 0;
        if (d > 255) return 0;
        addr->s_addr = htonl((a<<24) | (b<<16) | (c<<8) | d);
        return 1;
#ifdef AF_INET6
    } else if (af == AF_INET6) {
        struct in6_addr *out = dst;
        ev_uint16_t words[8];
        int gapPos = -1, i, setWords=0;
        const char *dot = strchr(src, '.');
        const char *eow; /* end of words. */
        if (dot == src)
            return 0;
        else if (!dot)
            eow = src+strlen(src);
        else {
            unsigned byte1,byte2,byte3,byte4;
            char more;
            for (eow = dot-1; eow >= src && EVUTIL_ISDIGIT_(*eow); --eow)
                ;
            ++eow;
            /* We use "scanf" because some platform inet_aton()s are too lax
             * about IPv4 addresses of the form "1.2.3" */
            if (sscanf(eow, "%u.%u.%u.%u%c",
                       &byte1,&byte2,&byte3,&byte4,&more) != 4)
                return 0;
            if (byte1 > 255 ||
                byte2 > 255 ||
                byte3 > 255 ||
                byte4 > 255)
                return 0;
            words[6] = (byte1<<8) | byte2;
            words[7] = (byte3<<8) | byte4;
            setWords += 2;
        }
        i = 0;
        while (src < eow) {
            if (i > 7)
                return 0;
            if (EVUTIL_ISXDIGIT_(*src)) {
                char *next;
                long r = strtol(src, &next, 16);
                if (next > 4+src)
                    return 0;
                if (next == src)
                    return 0;
                if (r<0 || r>65536)
                    return 0;
                words[i++] = (ev_uint16_t)r;
                setWords++;
                src = next;
                if (*src != ':' && src != eow)
                    return 0;
                ++src;
            } else if (*src == ':' && i > 0 && gapPos==-1) {
                gapPos = i;
                ++src;
            } else if (*src == ':' && i == 0 && src[1] == ':' && gapPos==-1) {
                gapPos = i;
                src += 2;
            } else {
                return 0;
            }
        }
        if (setWords > 8 ||
            (setWords == 8 && gapPos != -1) ||
            (setWords < 8 && gapPos == -1))
            return 0;
        if (gapPos >= 0) {
            int nToMove = setWords - (dot ? 2 : 0) - gapPos;
            int gapLen = 8 - setWords;
            /* assert(nToMove >= 0); */
            if (nToMove < 0)
                return -1; /* should be impossible */
            memmove(&words[gapPos+gapLen], &words[gapPos],
                    sizeof(ev_uint16_t)*nToMove);
            memset(&words[gapPos], 0, sizeof(ev_uint16_t)*gapLen);
        }
        for (i = 0; i < 8; ++i) {
            out->s6_addr[2*i  ] = words[i] >> 8;
            out->s6_addr[2*i+1] = words[i] & 0xff;
        }
        return 1;
#endif
    } else {
        return -1;
    }
#endif
}
References AF_INET6, EVUTIL_ISDIGIT_(), EVUTIL_ISXDIGIT_(), and in6_addr::s6_addr.
Referenced by bracket_addr_ok(), evutil_check_interfaces(), evutil_getaddrinfo_common_(), evutil_inet_pton_scope(), and evutil_parse_sockaddr_port().
evutil_inet_pton_scope()
int evutil_inet_pton_scope (int af, const char * src, void * dst, unsigned * indexp)
Definition at line 1992 of file evutil.c.
{
    int r;
    unsigned if_index;
    char *check, *cp, *tmp_src;
    *indexp = 0; /* Reasonable default */
    /* Bail out if not IPv6 */
    if (af != AF_INET6)
        return evutil_inet_pton(af, src, dst);
    cp = strchr(src, '%');
    /* Bail out if no zone ID */
    if (cp == NULL)
        return evutil_inet_pton(af, src, dst);
    if_index = if_nametoindex(cp + 1);
    if (if_index == 0) {
        /* Could be numeric */
        if_index = strtoul(cp + 1, &check, 10);
        if (check[0] != '\0')
            return 0;
    }
    *indexp = if_index;
    tmp_src = mm_strdup(src);
    cp = strchr(tmp_src, '%');
    *cp = '\0';
    r = evutil_inet_pton(af, tmp_src, dst);
    free(tmp_src);
    return r;
}
References AF_INET6, evutil_inet_pton(), and mm_strdup.
Referenced by evutil_getaddrinfo_common_(), and evutil_parse_sockaddr_port().
evutil_issetugid()
static int evutil_issetugid (void) static
Definition at line 2444 of file evutil.c.
{
#ifdef EVENT__HAVE_ISSETUGID
    return issetugid();
#else
#ifdef EVENT__HAVE_GETEUID
    if (getuid() != geteuid())
        return 1;
#endif
#ifdef EVENT__HAVE_GETEGID
    if (getgid() != getegid())
        return 1;
#endif
    return 0;
#endif
}
Referenced by evutil_getenv_().
evutil_make_internal_pipe_()
int evutil_make_internal_pipe_ (evutil_socket_t fd[2])
Definition at line 2672 of file evutil.c.
{
    /*
      Making the second socket nonblocking is a bit subtle, given that we
      ignore any EAGAIN returns when writing to it, and you don't usally
      do that for a nonblocking socket. But if the kernel gives us EAGAIN,
      then there's no need to add any more data to the buffer, since
      the main thread is already either about to wake up and drain it,
      or woken up and in the process of draining it.
    */
#if defined(EVENT__HAVE_PIPE2)
    if (pipe2(fd, O_NONBLOCK|O_CLOEXEC) == 0)
        return 0;
#endif
#if defined(EVENT__HAVE_PIPE)
    if (pipe(fd) == 0) {
        if (evutil_fast_socket_nonblocking(fd[0]) < 0 ||
            evutil_fast_socket_nonblocking(fd[1]) < 0 ||
            evutil_fast_socket_closeonexec(fd[0]) < 0 ||
            evutil_fast_socket_closeonexec(fd[1]) < 0) {
            close(fd[0]);
            close(fd[1]);
            fd[0] = fd[1] = -1;
            return -1;
        }
        return 0;
    } else {
        event_warn("%s: pipe", __func__);
    }
#endif
#ifdef _WIN32
#define LOCAL_SOCKETPAIR_AF AF_INET
#else
#define LOCAL_SOCKETPAIR_AF AF_UNIX
#endif
    if (evutil_socketpair(LOCAL_SOCKETPAIR_AF, SOCK_STREAM, 0, fd) == 0) {
        if (evutil_fast_socket_nonblocking(fd[0]) < 0 ||
            evutil_fast_socket_nonblocking(fd[1]) < 0 ||
            evutil_fast_socket_closeonexec(fd[0]) < 0 ||
            evutil_fast_socket_closeonexec(fd[1]) < 0) {
            evutil_closesocket(fd[0]);
            evutil_closesocket(fd[1]);
            fd[0] = fd[1] = -1;
            return -1;
        }
        return 0;
    }
    fd[0] = fd[1] = -1;
    return -1;
}
References __func__, event_warn(), evutil_closesocket(), evutil_fast_socket_closeonexec(), evutil_fast_socket_nonblocking(), evutil_socketpair(), and LOCAL_SOCKETPAIR_AF.
Referenced by evsig_init_(), and evthread_make_base_notifiable_nolock_().
evutil_make_listen_socket_ipv6only()
int evutil_make_listen_socket_ipv6only (evutil_socket_t sock)
Definition at line 394 of file evutil.c.
{
#if defined(IPV6_V6ONLY)
    int one = 1;
    return setsockopt(sock, IPPROTO_IPV6, IPV6_V6ONLY, (void*) &one,
        (ev_socklen_t)sizeof(one));
#endif
    return 0;
}
Referenced by evconnlistener_new_bind().
evutil_make_listen_socket_reuseable()
int evutil_make_listen_socket_reuseable (evutil_socket_t sock)
Definition at line 365 of file evutil.c.
{
#if defined(SO_REUSEADDR) && !defined(_WIN32)
    int one = 1;
    /* REUSEADDR on Unix means, "don't hang on to this address after the
     * listener is closed."  On Windows, though, it means "don't keep other
     * processes from binding to this address while we're using it. */
    return setsockopt(sock, SOL_SOCKET, SO_REUSEADDR, (void*) &one,
        (ev_socklen_t)sizeof(one));
#else
    return 0;
#endif
}
Referenced by create_bind_socket_nonblock(), and evconnlistener_new_bind().
evutil_make_listen_socket_reuseable_port()
int evutil_make_listen_socket_reuseable_port (evutil_socket_t sock)
Definition at line 380 of file evutil.c.
{
#if defined __linux__ && defined(SO_REUSEPORT)
    int one = 1;
    /* REUSEPORT on Linux 3.9+ means, "Multiple servers (processes or
     * threads) can bind to the same port if they each set the option. */
    return setsockopt(sock, SOL_SOCKET, SO_REUSEPORT, (void*) &one,
        (ev_socklen_t)sizeof(one));
#else
    return 0;
#endif
}
Referenced by evconnlistener_new_bind().
evutil_make_socket_closeonexec()
int evutil_make_socket_closeonexec (evutil_socket_t fd)
Definition at line 419 of file evutil.c.
{
#if !defined(_WIN32) && defined(EVENT__HAVE_SETFD)
    int flags;
    if ((flags = fcntl(fd, F_GETFD, NULL)) < 0) {
        event_warn("fcntl(%d, F_GETFD)", fd);
        return -1;
    }
    if (!(flags & FD_CLOEXEC)) {
        if (fcntl(fd, F_SETFD, flags | FD_CLOEXEC) == -1) {
            event_warn("fcntl(%d, F_SETFD)", fd);
            return -1;
        }
    }
#endif
    return 0;
}
References event_warn().
evutil_make_socket_nonblocking()
int evutil_make_socket_nonblocking (evutil_socket_t fd)
Definition at line 318 of file evutil.c.
{
#ifdef _WIN32
    {
        unsigned long nonblocking = 1;
        if (ioctlsocket(fd, FIONBIO, &nonblocking) == SOCKET_ERROR) {
            event_sock_warn(fd, "fcntl(%d, F_GETFL)", (int)fd);
            return -1;
        }
    }
#else
    {
        int flags;
        if ((flags = fcntl(fd, F_GETFL, NULL)) < 0) {
            event_warn("fcntl(%d, F_GETFL)", fd);
            return -1;
        }
        if (!(flags & O_NONBLOCK)) {
            if (fcntl(fd, F_SETFL, flags | O_NONBLOCK) == -1) {
                event_warn("fcntl(%d, F_SETFL)", fd);
                return -1;
            }
        }
    }
#endif
    return 0;
}
References event_sock_warn(), and event_warn().
Referenced by evutil_fast_socket_nonblocking(), and evutil_socket_connect_().
evutil_make_tcp_listen_socket_deferred()
int evutil_make_tcp_listen_socket_deferred (evutil_socket_t sock)
Definition at line 405 of file evutil.c.
{
#if defined(EVENT__HAVE_NETINET_TCP_H) && defined(TCP_DEFER_ACCEPT)
    int one = 1;
    /* TCP_DEFER_ACCEPT tells the kernel to call defer accept() only after data
     * has arrived and ready to read */
    return setsockopt(sock, IPPROTO_TCP, TCP_DEFER_ACCEPT, &one,
        (ev_socklen_t)sizeof(one));
#endif
    return 0;
}
Referenced by evconnlistener_new_bind().
evutil_memclear_()
void evutil_memclear_ (void * mem, size_t len)
Definition at line 2526 of file evutil.c.
{
    evutil_memset_volatile_(mem, 0, len);
}
References evutil_memset_volatile_.
Referenced by arc4_seed_urandom_helper_().
evutil_new_addrinfo_()
struct evutil_addrinfo * evutil_new_addrinfo_ (struct sockaddr * sa, ev_socklen_t socklen, const struct evutil_addrinfo * hints)
Definition at line 832 of file evutil.c.
{
    struct evutil_addrinfo *res;
    EVUTIL_ASSERT(hints);
    if (hints->ai_socktype == 0 && hints->ai_protocol == 0) {
        /* Indecisive user! Give them a UDP and a TCP. */
        struct evutil_addrinfo *r1, *r2;
        struct evutil_addrinfo tmp;
        memcpy(&tmp, hints, sizeof(tmp));
        tmp.ai_socktype = SOCK_STREAM; tmp.ai_protocol = IPPROTO_TCP;
        r1 = evutil_new_addrinfo_(sa, socklen, &tmp);
        if (!r1)
            return NULL;
        tmp.ai_socktype = SOCK_DGRAM; tmp.ai_protocol = IPPROTO_UDP;
        r2 = evutil_new_addrinfo_(sa, socklen, &tmp);
        if (!r2) {
            evutil_freeaddrinfo(r1);
            return NULL;
        }
        r1->ai_next = r2;
        return r1;
    }
    /* We're going to allocate extra space to hold the sockaddr. */
    res = mm_calloc(1,sizeof(struct evutil_addrinfo)+socklen);
    if (!res)
        return NULL;
    res->ai_addr = (struct sockaddr*)
        (((char*)res) + sizeof(struct evutil_addrinfo));
    memcpy(res->ai_addr, sa, socklen);
    res->ai_addrlen = socklen;
    res->ai_family = sa->sa_family; /* Same or not? XXX */
    res->ai_flags = EVUTIL_AI_LIBEVENT_ALLOCATED;
    res->ai_socktype = hints->ai_socktype;
    res->ai_protocol = hints->ai_protocol;
    return res;
}
References EVUTIL_AI_LIBEVENT_ALLOCATED, EVUTIL_ASSERT, evutil_freeaddrinfo(), evutil_new_addrinfo_(), and mm_calloc.
Referenced by addrinfo_from_hostent(), evdns_getaddrinfo_fromhosts(), evdns_getaddrinfo_gotresolve(), evutil_getaddrinfo_common_(), and evutil_new_addrinfo_().
evutil_open_closeonexec_()
int evutil_open_closeonexec_ (const char * pathname, int flags, unsigned mode)
Definition at line 110 of file evutil.c.
{
    int fd;
#ifdef O_CLOEXEC
    fd = open(pathname, flags|O_CLOEXEC, (mode_t)mode);
    if (fd >= 0 || errno == EINVAL)
        return fd;
    /* If we got an EINVAL, fall through and try without O_CLOEXEC */
#endif
    fd = open(pathname, flags, (mode_t)mode);
    if (fd < 0)
        return -1;
#if defined(FD_CLOEXEC)
    if (fcntl(fd, F_SETFD, FD_CLOEXEC) < 0) {
        close(fd);
        return -1;
    }
#endif
    return fd;
}
Referenced by arc4_seed_urandom_helper_(), and evutil_read_file_().
evutil_parse_servname()
static int evutil_parse_servname (const char * servname, const char * protocol, const struct evutil_addrinfo * hints) static
Parse a service name in 'servname', which can be a decimal port. Return the port number, or -1 on error.
Definition at line 906 of file evutil.c.
{
    int n = parse_numeric_servname(servname);
    if (n>=0)
        return n;
#if defined(EVENT__HAVE_GETSERVBYNAME) || defined(_WIN32)
    if (!(hints->ai_flags & EVUTIL_AI_NUMERICSERV)) {
        struct servent *ent = getservbyname(servname, protocol);
        if (ent) {
            return ntohs(ent->s_port);
        }
    }
#endif
    return -1;
}
References parse_numeric_servname().
Referenced by evutil_getaddrinfo_common_().
evutil_parse_sockaddr_port()
int evutil_parse_sockaddr_port (const char * ip_as_string, struct sockaddr * out, int * outlen)
Definition at line 2139 of file evutil.c.
{
    int port;
    unsigned int if_index;
    char buf[128];
    const char *cp, *addr_part, *port_part;
    int is_ipv6;
    /* recognized formats are:
     * [ipv6]:port
     * ipv6
     * [ipv6]
     * ipv4:port
     * ipv4
     */
    cp = strchr(ip_as_string, ':');
    if (*ip_as_string == '[') {
        size_t len;
        if (!(cp = strchr(ip_as_string, ']'))) {
            return -1;
        }
        len = ( cp-(ip_as_string + 1) );
        if (len > sizeof(buf)-1) {
            return -1;
        }
        memcpy(buf, ip_as_string+1, len);
        buf[len] = '\0';
        addr_part = buf;
        if (cp[1] == ':')
            port_part = cp+2;
        else
            port_part = NULL;
        is_ipv6 = 1;
    } else if (cp && strchr(cp+1, ':')) {
        is_ipv6 = 1;
        addr_part = ip_as_string;
        port_part = NULL;
    } else if (cp) {
        is_ipv6 = 0;
        if (cp - ip_as_string > (int)sizeof(buf)-1) {
            return -1;
        }
        memcpy(buf, ip_as_string, cp-ip_as_string);
        buf[cp-ip_as_string] = '\0';
        addr_part = buf;
        port_part = cp+1;
    } else {
        addr_part = ip_as_string;
        port_part = NULL;
        is_ipv6 = 0;
    }
    if (port_part == NULL) {
        port = 0;
    } else {
        port = atoi(port_part);
        if (port <= 0 || port > 65535) {
            return -1;
        }
    }
    if (!addr_part)
        return -1; /* Should be impossible. */
#ifdef AF_INET6
    if (is_ipv6)
    {
        struct sockaddr_in6 sin6;
        memset(&sin6, 0, sizeof(sin6));
#ifdef EVENT__HAVE_STRUCT_SOCKADDR_IN6_SIN6_LEN
        sin6.sin6_len = sizeof(sin6);
#endif
        sin6.sin6_family = AF_INET6;
        sin6.sin6_port = htons(port);
        if (1 != evutil_inet_pton_scope(
            AF_INET6, addr_part, &sin6.sin6_addr, &if_index)) {
            return -1;
        }
        if ((int)sizeof(sin6) > *outlen)
            return -1;
        sin6.sin6_scope_id = if_index;
        memset(out, 0, *outlen);
        memcpy(out, &sin6, sizeof(sin6));
        *outlen = sizeof(sin6);
        return 0;
    }
    else
#endif
    {
        struct sockaddr_in sin;
        memset(&sin, 0, sizeof(sin));
#ifdef EVENT__HAVE_STRUCT_SOCKADDR_IN_SIN_LEN
        sin.sin_len = sizeof(sin);
#endif
        sin.sin_family = AF_INET;
        sin.sin_port = htons(port);
        if (1 != evutil_inet_pton(AF_INET, addr_part, &sin.sin_addr))
            return -1;
        if ((int)sizeof(sin) > *outlen)
            return -1;
        memset(out, 0, *outlen);
        memcpy(out, &sin, sizeof(sin));
        *outlen = sizeof(sin);
        return 0;
    }
}
References AF_INET6, evutil_inet_pton(), evutil_inet_pton_scope(), sockaddr_in6::sin6_addr, sockaddr_in6::sin6_family, and sockaddr_in6::sin6_port.
Referenced by dogecoin_node_set_ipport(), evdns_base_nameserver_ip_add(), evdns_base_parse_hosts_line(), and evdns_base_set_option_impl().
evutil_read_file_()
int evutil_read_file_ (const char * filename, char ** content_out, size_t * len_out, int is_binary)
Read the contents of 'filename' into a newly allocated NUL-terminated string. Set *content_out to hold this string, and *len_out to hold its length (not including the appended NUL). If 'is_binary', open the file in binary mode.
Returns 0 on success, -1 if the open fails, and -2 for all other failures.
Used internally only; may go away in a future version.
Definition at line 145 of file evutil.c.
{
    int fd, r;
    struct stat st;
    char *mem;
    size_t read_so_far=0;
    int mode = O_RDONLY;
    EVUTIL_ASSERT(content_out);
    EVUTIL_ASSERT(len_out);
    *content_out = NULL;
    *len_out = 0;
#ifdef O_BINARY
    if (is_binary)
        mode |= O_BINARY;
#endif
    fd = evutil_open_closeonexec_(filename, mode, 0);
    if (fd < 0)
        return -1;
    if (fstat(fd, &st) || st.st_size < 0 ||
        st.st_size > EV_SSIZE_MAX-1 ) {
        close(fd);
        return -2;
    }
    mem = mm_malloc((size_t)st.st_size + 1);
    if (!mem) {
        close(fd);
        return -2;
    }
    read_so_far = 0;
#ifdef _WIN32
#define N_TO_READ(x) ((x) > INT_MAX) ? INT_MAX : ((int)(x))
#else
#define N_TO_READ(x) (x)
#endif
    while ((r = read(fd, mem+read_so_far, N_TO_READ(st.st_size - read_so_far))) > 0) {
        read_so_far += r;
        if (read_so_far >= (size_t)st.st_size)
            break;
        EVUTIL_ASSERT(read_so_far < (size_t)st.st_size);
    }
    close(fd);
    if (r < 0) {
        mm_free(mem);
        return -2;
    }
    mem[read_so_far] = 0;
    *len_out = read_so_far;
    *content_out = mem;
    return 0;
}
References EVUTIL_ASSERT, evutil_open_closeonexec_(), mm_free, mm_malloc, and N_TO_READ.
Referenced by evdns_base_load_hosts_impl(), and evdns_base_resolv_conf_parse_impl().
evutil_rtrim_lws_()
void evutil_rtrim_lws_ (char * str)
Remove all trailing horizontal whitespace (space or tab) from the end of a string
Definition at line 2423 of file evutil.c.
{
    char *cp;
    if (str == NULL)
        return;
    if ((cp = strchr(str, '\0')) == NULL || (cp == str))
        return;
    --cp;
    while (*cp == ' ' || *cp == '\t') {
        *cp = '\0';
        if (cp == str)
            break;
        --cp;
    }
}
Referenced by evhttp_append_to_last_header(), and evhttp_parse_headers_().
evutil_set_evdns_getaddrinfo_cancel_fn_()
void evutil_set_evdns_getaddrinfo_cancel_fn_ (evdns_getaddrinfo_cancel_fn fn)
Definition at line 1603 of file evutil.c.
{
    if (!evdns_getaddrinfo_cancel_impl)
        evdns_getaddrinfo_cancel_impl = fn;
}
References evdns_getaddrinfo_cancel_impl.
Referenced by evdns_base_new().
evutil_set_evdns_getaddrinfo_fn_()
void evutil_set_evdns_getaddrinfo_fn_ (evdns_getaddrinfo_fn fn)
Definition at line 1597 of file evutil.c.
{
    if (!evdns_getaddrinfo_impl)
        evdns_getaddrinfo_impl = fn;
}
References evdns_getaddrinfo_impl.
Referenced by evdns_base_new().
evutil_snprintf()
int evutil_snprintf (char * buf, size_t buflen, const char * format, ...)
Definition at line 1858 of file evutil.c.
{
    int r;
    va_list ap;
    va_start(ap, format);
    r = evutil_vsnprintf(buf, buflen, format, ap);
    va_end(ap);
    return r;
}
References evutil_vsnprintf().
Referenced by bufferevent_socket_connect_hostname(), evdns_base_resolve_reverse(), evdns_get_default_hosts_filename(), evdns_server_request_add_ptr_reply(), event_is_method_disabled(), event_logv_(), evhttp_make_header_request(), evhttp_maybe_add_content_length_header(), evutil_date_rfc1123(), evutil_format_sockaddr_port_(), evutil_inet_ntop(), fake_getnameinfo(), make_addrinfo(), and reply_handle().
evutil_sockaddr_cmp()
int evutil_sockaddr_cmp (const struct sockaddr * sa1, const struct sockaddr * sa2, int include_port)
Definition at line 2275 of file evutil.c.
{
    int r;
    if (0 != (r = (sa1->sa_family - sa2->sa_family)))
        return r;
    if (sa1->sa_family == AF_INET) {
        const struct sockaddr_in *sin1, *sin2;
        sin1 = (const struct sockaddr_in *)sa1;
        sin2 = (const struct sockaddr_in *)sa2;
        if (sin1->sin_addr.s_addr < sin2->sin_addr.s_addr)
            return -1;
        else if (sin1->sin_addr.s_addr > sin2->sin_addr.s_addr)
            return 1;
        else if (include_port &&
            (r = ((int)sin1->sin_port - (int)sin2->sin_port)))
            return r;
        else
            return 0;
    }
#ifdef AF_INET6
    else if (sa1->sa_family == AF_INET6) {
        const struct sockaddr_in6 *sin1, *sin2;
        sin1 = (const struct sockaddr_in6 *)sa1;
        sin2 = (const struct sockaddr_in6 *)sa2;
        if ((r = memcmp(sin1->sin6_addr.s6_addr, sin2->sin6_addr.s6_addr, 16)))
            return r;
        else if (include_port &&
            (r = ((int)sin1->sin6_port - (int)sin2->sin6_port)))
            return r;
        else
            return 0;
    }
#endif
    return 1;
}
References AF_INET6, in6_addr::s6_addr, sockaddr_in6::sin6_addr, and sockaddr_in6::sin6_port.
Referenced by evdns_nameserver_add_impl_(), and nameserver_read().
evutil_sockaddr_is_loopback_()
int evutil_sockaddr_is_loopback_ (const struct sockaddr * sa)
Return true iff sa is a looback address. (That is, it is 127.0.0.1/8, or ::1).
Definition at line 2532 of file evutil.c.
{
    static const char LOOPBACK_S6[16] =
        "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\1";
    if (addr->sa_family == AF_INET) {
        struct sockaddr_in *sin = (struct sockaddr_in *)addr;
        return (ntohl(sin->sin_addr.s_addr) & 0xff000000) == 0x7f000000;
    } else if (addr->sa_family == AF_INET6) {
        struct sockaddr_in6 *sin6 = (struct sockaddr_in6 *)addr;
        return !memcmp(sin6->sin6_addr.s6_addr, LOOPBACK_S6, 16);
    }
    return 0;
}
References AF_INET6, in6_addr::s6_addr, and sockaddr_in6::sin6_addr.
Referenced by evdns_nameserver_add_impl_().
evutil_socket_()
evutil_socket_t evutil_socket_ (int domain, int type, int protocol)
Definition at line 2595 of file evutil.c.
{
    evutil_socket_t r;
#if defined(SOCK_NONBLOCK) && defined(SOCK_CLOEXEC)
    r = socket(domain, type, protocol);
    if (r >= 0)
        return r;
    else if ((type & (SOCK_NONBLOCK|SOCK_CLOEXEC)) == 0)
        return -1;
#endif
#define SOCKET_TYPE_MASK (~(EVUTIL_SOCK_NONBLOCK|EVUTIL_SOCK_CLOEXEC))
    r = socket(domain, type & SOCKET_TYPE_MASK, protocol);
    if (r < 0)
        return -1;
    if (type & EVUTIL_SOCK_NONBLOCK) {
        if (evutil_fast_socket_nonblocking(r) < 0) {
            evutil_closesocket(r);
            return -1;
        }
    }
    if (type & EVUTIL_SOCK_CLOEXEC) {
        if (evutil_fast_socket_closeonexec(r) < 0) {
            evutil_closesocket(r);
            return -1;
        }
    }
    return r;
}
References evutil_closesocket(), evutil_fast_socket_closeonexec(), evutil_fast_socket_nonblocking(), EVUTIL_SOCK_CLOEXEC, EVUTIL_SOCK_NONBLOCK, and SOCKET_TYPE_MASK.
Referenced by bufferevent_socket_connect(), create_bind_socket_nonblock(), evconnlistener_new_bind(), and evdns_nameserver_add_impl_().
evutil_socket_connect_()
int evutil_socket_connect_ (evutil_socket_t * fd_ptr, const struct sockaddr * sa, int socklen)
Definition at line 543 of file evutil.c.
{
    int made_fd = 0;
    if (*fd_ptr < 0) {
        if ((*fd_ptr = socket(sa->sa_family, SOCK_STREAM, 0)) < 0)
            goto err;
        made_fd = 1;
        if (evutil_make_socket_nonblocking(*fd_ptr) < 0) {
            goto err;
        }
    }
    if (connect(*fd_ptr, sa, socklen) < 0) {
        int e = evutil_socket_geterror(*fd_ptr);
        if (EVUTIL_ERR_CONNECT_RETRIABLE(e))
            return 0;
        if (EVUTIL_ERR_CONNECT_REFUSED(e))
            return 2;
        goto err;
    } else {
        return 1;
    }
err:
    if (made_fd) {
        evutil_closesocket(*fd_ptr);
        *fd_ptr = -1;
    }
    return -1;
}
References evutil_closesocket(), EVUTIL_ERR_CONNECT_REFUSED, EVUTIL_ERR_CONNECT_RETRIABLE, and evutil_make_socket_nonblocking().
Referenced by bufferevent_socket_connect().
evutil_socket_finished_connecting_()
int evutil_socket_finished_connecting_ (evutil_socket_t fd)
Definition at line 580 of file evutil.c.
{
    int e;
    ev_socklen_t elen = sizeof(e);
    if (getsockopt(fd, SOL_SOCKET, SO_ERROR, (void*)&e, &elen) < 0)
        return -1;
    if (e) {
        if (EVUTIL_ERR_CONNECT_RETRIABLE(e))
            return 0;
        EVUTIL_SET_SOCKET_ERROR(e);
        return -1;
    }
    return 1;
}
References EVUTIL_ERR_CONNECT_RETRIABLE.
Referenced by bufferevent_writecb().
evutil_socketpair()
int evutil_socketpair (int family, int type, int protocol, evutil_socket_t fd[2])
Definition at line 202 of file evutil.c.
{
#ifndef _WIN32
    return socketpair(family, type, protocol, fd);
#else
    return evutil_ersatz_socketpair_(family, type, protocol, fd);
#endif
}
References evutil_ersatz_socketpair_().
Referenced by evutil_make_internal_pipe_().
evutil_strtoll()
ev_int64_t evutil_strtoll (const char * s, char ** endptr, int base)
Definition at line 464 of file evutil.c.
{
#ifdef EVENT__HAVE_STRTOLL
    return (ev_int64_t)strtoll(s, endptr, base);
#elif EVENT__SIZEOF_LONG == 8
    return (ev_int64_t)strtol(s, endptr, base);
#elif defined(_WIN32) && defined(_MSC_VER) && _MSC_VER < 1300
    /* XXXX on old versions of MS APIs, we only support base
     * 10. */
    ev_int64_t r;
    if (base != 10)
        return 0;
    r = (ev_int64_t) _atoi64(s);
    while (isspace(*s))
        ++s;
    if (*s == '-')
        ++s;
    while (isdigit(*s))
        ++s;
    if (endptr)
        *endptr = (char*) s;
    return r;
#elif defined(_WIN32)
    return (ev_int64_t) _strtoi64(s, endptr, base);
#elif defined(EVENT__SIZEOF_LONG_LONG) && EVENT__SIZEOF_LONG_LONG == 8
    long long r;
    int n;
    if (base != 10 && base != 16)
        return 0;
    if (base == 10) {
        n = sscanf(s, "%lld", &r);
    } else {
        unsigned long long ru=0;
        n = sscanf(s, "%llx", &ru);
        if (ru > EV_INT64_MAX)
            return 0;
        r = (long long) ru;
    }
    if (n != 1)
        return 0;
    while (EVUTIL_ISSPACE_(*s))
        ++s;
    if (*s == '-')
        ++s;
    if (base == 10) {
        while (EVUTIL_ISDIGIT_(*s))
            ++s;
    } else {
        while (EVUTIL_ISXDIGIT_(*s))
            ++s;
    }
    if (endptr)
        *endptr = (char*) s;
    return r;
#else
#error "I don't know how to parse 64-bit integers."
#endif
}
References EVUTIL_ISDIGIT_(), EVUTIL_ISSPACE_(), and EVUTIL_ISXDIGIT_().
Referenced by evhttp_get_body_length(), and evhttp_handle_chunked_read().
EVUTIL_TOLOWER_()
char EVUTIL_TOLOWER_ (char c)
Definition at line 2383 of file evutil.c.
{
    return ((char)EVUTIL_TOLOWER_TABLE[(ev_uint8_t)c]);
}
References EVUTIL_TOLOWER_TABLE.
Referenced by evutil_ascii_strcasecmp(), evutil_ascii_strncasecmp(), and prefix_suffix_match().
EVUTIL_TOUPPER_()
char EVUTIL_TOUPPER_ (char c)
Definition at line 2387 of file evutil.c.
{
    return ((char)EVUTIL_TOUPPER_TABLE[(ev_uint8_t)c]);
}
References EVUTIL_TOUPPER_TABLE.
Referenced by event_is_method_disabled().
evutil_unparse_protoname()
static const char * evutil_unparse_protoname (int proto) static
Definition at line 926 of file evutil.c.
{
    switch (proto) {
    case 0:
        return NULL;
    case IPPROTO_TCP:
        return "tcp";
    case IPPROTO_UDP:
        return "udp";
#ifdef IPPROTO_SCTP
    case IPPROTO_SCTP:
        return "sctp";
#endif
    default:
#ifdef EVENT__HAVE_GETPROTOBYNUMBER
        {
            struct protoent *ent = getprotobynumber(proto);
            if (ent)
                return ent->p_name;
        }
#endif
        return NULL;
    }
}
Referenced by evutil_getaddrinfo_common_().
evutil_v4addr_is_classd()
static int evutil_v4addr_is_classd (ev_uint32_t addr) inline static
Definition at line 625 of file evutil.c.
{ return ((addr>>24) & 0xf0) == 0xe0; }
Referenced by evutil_v4addr_is_local_().
evutil_v4addr_is_linklocal()
static int evutil_v4addr_is_linklocal (ev_uint32_t addr) inline static
Definition at line 620 of file evutil.c.
{ return ((addr & 0xffff0000U) == 0xa9fe0000U); }
Referenced by evutil_v4addr_is_local_().
evutil_v4addr_is_local_()
int evutil_v4addr_is_local_ (const struct in_addr * in)
Definition at line 629 of file evutil.c.
{
    const ev_uint32_t addr = ntohl(in->s_addr);
    return addr == INADDR_ANY ||
        evutil_v4addr_is_localhost(addr) ||
        evutil_v4addr_is_linklocal(addr) ||
        evutil_v4addr_is_classd(addr);
}
References evutil_v4addr_is_classd(), evutil_v4addr_is_linklocal(), and evutil_v4addr_is_localhost().
Referenced by evutil_found_ifaddr().
evutil_v4addr_is_localhost()
static int evutil_v4addr_is_localhost (ev_uint32_t addr) inline static
Definition at line 615 of file evutil.c.
{ return addr>>24 == 127; }
Referenced by evutil_v4addr_is_local_().
evutil_v6addr_is_local_()
int evutil_v6addr_is_local_ (const struct in6_addr * in)
Definition at line 638 of file evutil.c.
{
    static const char ZEROES[] =
        "\x00\x00\x00\x00\x00\x00\x00\x00"
        "\x00\x00\x00\x00\x00\x00\x00\x00";
    const unsigned char *addr = (const unsigned char *)in->s6_addr;
    return !memcmp(addr, ZEROES, 8) ||
        ((addr[0] & 0xfe) == 0xfc) ||
        (addr[0] == 0xfe && (addr[1] & 0xc0) == 0x80) ||
        (addr[0] == 0xfe && (addr[1] & 0xc0) == 0xc0) ||
        (addr[0] == 0xff);
}
References in6_addr::s6_addr.
Referenced by evutil_found_ifaddr().
evutil_vsnprintf()
int evutil_vsnprintf (char * buf, size_t buflen, const char * format, va_list ap)
Definition at line 1869 of file evutil.c.
{
    int r;
    if (!buflen)
        return 0;
#if defined(_MSC_VER) || defined(_WIN32)
    r = _vsnprintf(buf, buflen, format, ap);
    if (r < 0)
        r = _vscprintf(format, ap);
#elif defined(sgi)
    /* Make sure we always use the correct vsnprintf on IRIX */
    extern int      _xpg5_vsnprintf(char * __restrict,
        __SGI_LIBC_NAMESPACE_QUALIFIER size_t,
        const char * __restrict, /* va_list */ char *);
    r = _xpg5_vsnprintf(buf, buflen, format, ap);
#else
    r = vsnprintf(buf, buflen, format, ap);
#endif
    buf[buflen-1] = '\0';
    return r;
}
Referenced by evbuffer_add_vprintf(), evdns_log_(), event_logv_(), and evutil_snprintf().
evutil_weakrand_()
ev_int32_t evutil_weakrand_ (struct evutil_weakrand_state * state)
Definition at line 2489 of file evutil.c.
{
    /* This RNG implementation is a linear congruential generator, with
     * modulus 2^31, multiplier 1103515245, and addend 12345.  It's also
     * used by OpenBSD, and by Glibc's TYPE_0 RNG.
     *
     * The linear congruential generator is not an industrial-strength
     * RNG!  It's fast, but it can have higher-order patterns.  Notably,
     * the low bits tend to have periodicity.
     */
    state->seed = ((state->seed) * 1103515245 + 12345) & 0x7fffffff;
    return (ev_int32_t)(state->seed);
}
References evutil_weakrand_state::seed.
Referenced by evutil_weakrand_range_().
evutil_weakrand_range_()
ev_int32_t evutil_weakrand_range_ (struct evutil_weakrand_state * state, ev_int32_t top)
Definition at line 2504 of file evutil.c.
{
    ev_int32_t divisor, result;
    /* We can't just do weakrand() % top, since the low bits of the LCG
     * are less random than the high ones.  (Specifically, since the LCG
     * modulus is 2^N, every 2^m for m<N will divide the modulus, and so
     * therefore the low m bits of the LCG will have period 2^m.) */
    divisor = EVUTIL_WEAKRAND_MAX / top;
    do {
        result = evutil_weakrand_(state) / divisor;
    } while (result >= top);
    return result;
}
References evutil_weakrand_(), and EVUTIL_WEAKRAND_MAX.
Referenced by bev_group_random_element_().
evutil_weakrand_seed_()
ev_uint32_t evutil_weakrand_seed_ (struct evutil_weakrand_state * state, ev_uint32_t seed)
Definition at line 2472 of file evutil.c.
{
    if (seed == 0) {
        struct timeval tv;
        evutil_gettimeofday(&tv, NULL);
        seed = (ev_uint32_t)tv.tv_sec + (ev_uint32_t)tv.tv_usec;
#ifdef _WIN32
        seed += (ev_uint32_t) _getpid();
#else
        seed += (ev_uint32_t) getpid();
#endif
    }
    state->seed = seed;
    return seed;
}
References evutil_gettimeofday(), and evutil_weakrand_state::seed.
Referenced by bufferevent_rate_limit_group_new().
parse_numeric_servname()
static int parse_numeric_servname (const char * servname) static
Definition at line 891 of file evutil.c.
{
    int n;
    char *endptr=NULL;
    n = (int) strtol(servname, &endptr, 10);
    if (n>=0 && n <= 65535 && servname[0] && endptr && !endptr[0])
        return n;
    else
        return -1;
}
Referenced by evutil_getaddrinfo(), and evutil_parse_servname().
Variable Documentation
evdns_getaddrinfo_cancel_impl
evdns_getaddrinfo_cancel_fn evdns_getaddrinfo_cancel_impl = NULL static
Definition at line 1594 of file evutil.c.
Referenced by evutil_getaddrinfo_cancel_async_(), and evutil_set_evdns_getaddrinfo_cancel_fn_().
evdns_getaddrinfo_impl
evdns_getaddrinfo_fn evdns_getaddrinfo_impl = NULL static
Definition at line 1593 of file evutil.c.
Referenced by evutil_getaddrinfo_async_(), and evutil_set_evdns_getaddrinfo_fn_().
EVUTIL_ISALNUM_TABLE
const ev_uint32_t EVUTIL_ISALNUM_TABLE[8] static
Initial value:
=
  { 0, 0x3ff0000, 0x7fffffe, 0x7fffffe, 0, 0, 0, 0 }
Definition at line 2320 of file evutil.c.
EVUTIL_ISALPHA_TABLE
const ev_uint32_t EVUTIL_ISALPHA_TABLE[8] static
Initial value:
=
  { 0, 0, 0x7fffffe, 0x7fffffe, 0, 0, 0, 0 }
Definition at line 2318 of file evutil.c.
EVUTIL_ISDIGIT_TABLE
const ev_uint32_t EVUTIL_ISDIGIT_TABLE[8] = { 0, 0x3ff0000, 0, 0, 0, 0, 0, 0 } static
Definition at line 2325 of file evutil.c.
EVUTIL_ISLOWER_TABLE
const ev_uint32_t EVUTIL_ISLOWER_TABLE[8] = { 0, 0, 0, 0x7fffffe, 0, 0, 0, 0 } static
Definition at line 2329 of file evutil.c.
EVUTIL_ISPRINT_TABLE
const ev_uint32_t EVUTIL_ISPRINT_TABLE[8] static
Initial value:
=
  { 0, 0xffffffff, 0xffffffff, 0x7fffffff, 0, 0, 0, 0x0 }
Definition at line 2326 of file evutil.c.
EVUTIL_ISSPACE_TABLE
const ev_uint32_t EVUTIL_ISSPACE_TABLE[8] = { 0x3e00, 0x1, 0, 0, 0, 0, 0, 0 } static
Definition at line 2322 of file evutil.c.
EVUTIL_ISUPPER_TABLE
const ev_uint32_t EVUTIL_ISUPPER_TABLE[8] = { 0, 0, 0x7fffffe, 0, 0, 0, 0, 0 } static
Definition at line 2328 of file evutil.c.
EVUTIL_ISXDIGIT_TABLE
const ev_uint32_t EVUTIL_ISXDIGIT_TABLE[8] static
Initial value:
=
  { 0, 0x3ff0000, 0x7e, 0x7e, 0, 0, 0, 0 }
Definition at line 2323 of file evutil.c.
evutil_memset_volatile_
void *(*volatile evutil_memset_volatile_) (void *, int, size_t) (void * , int , size_t) = memset
Volatile pointer to memset: we use this to keep the compiler from eliminating our call to memset.
Definition at line 2523 of file evutil.c.
Referenced by evutil_memclear_().
EVUTIL_TOLOWER_TABLE
const unsigned char EVUTIL_TOLOWER_TABLE[256] static
Initial value:
= {
  0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,
  16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,
  32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,
  48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,
  64,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,
  112,113,114,115,116,117,118,119,120,121,122,91,92,93,94,95,
  96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,
  112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,
  128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,
  144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,
  160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,
  176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,
  192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,
  208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,
  224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,
  240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,
}
Definition at line 2350 of file evutil.c.
Referenced by EVUTIL_TOLOWER_().
EVUTIL_TOUPPER_TABLE
const unsigned char EVUTIL_TOUPPER_TABLE[256] static
Initial value:
= {
  0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,
  16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,
  32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,
  48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,
  64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,
  80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,
  96,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,
  80,81,82,83,84,85,86,87,88,89,90,123,124,125,126,127,
  128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,
  144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,
  160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,
  176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,
  192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,
  208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,
  224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,
  240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,
}
Definition at line 2332 of file evutil.c.
Referenced by EVUTIL_TOUPPER_().
had_ipv4_address
int had_ipv4_address static
Definition at line 612 of file evutil.c.
Referenced by evutil_adjust_hints_for_addrconfig_(), and evutil_found_ifaddr().
had_ipv6_address
int had_ipv6_address static
Definition at line 612 of file evutil.c.
Referenced by evutil_adjust_hints_for_addrconfig_(), and evutil_found_ifaddr().
have_checked_interfaces
int have_checked_interfaces static
Definition at line 612 of file evutil.c.
Referenced by evutil_check_interfaces().