libdogecoin: src/libevent/evutil_rand.c File Reference
evutil_rand.c File Reference
#include "event2/event-config.h"
#include "evconfig-private.h"
#include <limits.h>
#include "util-internal.h"
#include "evthread-internal.h"
#include "./arc4random.c"
Macros
#define ARC4RANDOM_EXPORT static
#define ARC4_LOCK_() EVLOCK_LOCK(arc4rand_lock, 0)
#define ARC4_UNLOCK_() EVLOCK_UNLOCK(arc4rand_lock, 0)
#define ARC4RANDOM_UINT32 ev_uint32_t
#define ARC4RANDOM_NOSTIR
#define ARC4RANDOM_NORANDOM
#define ARC4RANDOM_NOUNIFORM
Functions
int evutil_secure_rng_global_setup_locks_ (const int enable_locks)
static void evutil_free_secure_rng_globals_locks (void)
int evutil_secure_rng_set_urandom_device_file (char *fname)
int evutil_secure_rng_init (void)
static void ev_arc4random_buf (void *buf, size_t n)
void evutil_secure_rng_get_bytes (void *buf, size_t n)
void evutil_secure_rng_add_bytes (const char *buf, size_t n)
void evutil_free_secure_rng_globals_ (void)
Variables
static void * arc4rand_lock
Macro Definition Documentation
ARC4_LOCK_
#define ARC4_LOCK_ () EVLOCK_LOCK(arc4rand_lock, 0)
Definition at line 123 of file evutil_rand.c.
ARC4_UNLOCK_
#define ARC4_UNLOCK_ () EVLOCK_UNLOCK(arc4rand_lock, 0)
Definition at line 124 of file evutil_rand.c.
ARC4RANDOM_EXPORT
#define ARC4RANDOM_EXPORT static
Definition at line 122 of file evutil_rand.c.
ARC4RANDOM_NORANDOM
#define ARC4RANDOM_NORANDOM
Definition at line 131 of file evutil_rand.c.
ARC4RANDOM_NOSTIR
#define ARC4RANDOM_NOSTIR
Definition at line 130 of file evutil_rand.c.
ARC4RANDOM_NOUNIFORM
#define ARC4RANDOM_NOUNIFORM
Definition at line 132 of file evutil_rand.c.
ARC4RANDOM_UINT32
#define ARC4RANDOM_UINT32 ev_uint32_t
Definition at line 129 of file evutil_rand.c.
Function Documentation
ev_arc4random_buf()
static void ev_arc4random_buf (void * buf, size_t n) static
Definition at line 180 of file evutil_rand.c.
{
    arc4random_buf(buf, n);
}
References arc4random_buf().
Referenced by evutil_secure_rng_get_bytes().
evutil_free_secure_rng_globals_()
void evutil_free_secure_rng_globals_ (void)
Definition at line 203 of file evutil_rand.c.
{
    evutil_free_secure_rng_globals_locks();
}
References evutil_free_secure_rng_globals_locks().
Referenced by evutil_free_globals_().
evutil_free_secure_rng_globals_locks()
static void evutil_free_secure_rng_globals_locks (void) static
Definition at line 146 of file evutil_rand.c.
{
#ifndef EVENT__DISABLE_THREAD_SUPPORT
    if (arc4rand_lock != NULL) {
        EVTHREAD_FREE_LOCK(arc4rand_lock, 0);
        arc4rand_lock = NULL;
    }
#endif
    return;
}
References arc4rand_lock, and EVTHREAD_FREE_LOCK.
Referenced by evutil_free_secure_rng_globals_().
evutil_secure_rng_add_bytes()
void evutil_secure_rng_add_bytes (const char * buf, size_t n)
Definition at line 195 of file evutil_rand.c.
{
    arc4random_addrandom((unsigned char*)buf,
        n>(size_t)INT_MAX ? INT_MAX : (int)n);
}
References arc4random_addrandom().
evutil_secure_rng_get_bytes()
void evutil_secure_rng_get_bytes (void * buf, size_t n)
Definition at line 188 of file evutil_rand.c.
{
    ev_arc4random_buf(buf, n);
}
References ev_arc4random_buf().
Referenced by request_new(), and transaction_id_pick().
evutil_secure_rng_global_setup_locks_()
int evutil_secure_rng_global_setup_locks_ (const int enable_locks)
Definition at line 138 of file evutil_rand.c.
{
    EVTHREAD_SETUP_GLOBAL_LOCK(arc4rand_lock, 0);
    return 0;
}
References arc4rand_lock, and EVTHREAD_SETUP_GLOBAL_LOCK.
Referenced by event_global_setup_locks_().
evutil_secure_rng_init()
int evutil_secure_rng_init (void)
Definition at line 169 of file evutil_rand.c.
{
    int val;
    ARC4_LOCK_();
    val = (!arc4_stir()) ? 0 : -1;
    ARC4_UNLOCK_();
    return val;
}
References ARC4_LOCK_, arc4_stir(), and ARC4_UNLOCK_.
Referenced by evdns_base_new().
evutil_secure_rng_set_urandom_device_file()
int evutil_secure_rng_set_urandom_device_file (char * fname)
Definition at line 158 of file evutil_rand.c.
{
#ifdef TRY_SEED_URANDOM
    ARC4_LOCK_();
    arc4random_urandom_filename = fname;
    ARC4_UNLOCK_();
#endif
    return 0;
}
References ARC4_LOCK_, ARC4_UNLOCK_, and arc4random_urandom_filename.
Variable Documentation
arc4rand_lock
void* arc4rand_lock static
Definition at line 126 of file evutil_rand.c.
Referenced by evutil_free_secure_rng_globals_locks(), and evutil_secure_rng_global_setup_locks_().