libdogecoin: src/secp256k1/src/group_impl.h File Reference
group_impl.h File Reference
#include "field.h"
#include "group.h"
Macros
#define SECP256K1_G_ORDER_13
#define SECP256K1_G_ORDER_199
#define SECP256K1_G
Functions
static void secp256k1_ge_set_gej_zinv (secp256k1_ge *r, const secp256k1_gej *a, const secp256k1_fe *zi)
static void secp256k1_ge_set_xy (secp256k1_ge *r, const secp256k1_fe *x, const secp256k1_fe *y)
static int secp256k1_ge_is_infinity (const secp256k1_ge *a)
static void secp256k1_ge_neg (secp256k1_ge *r, const secp256k1_ge *a)
static void secp256k1_ge_set_gej (secp256k1_ge *r, secp256k1_gej *a)
static void secp256k1_ge_set_gej_var (secp256k1_ge *r, secp256k1_gej *a)
static void secp256k1_ge_set_all_gej_var (secp256k1_ge *r, const secp256k1_gej *a, size_t len)
static void secp256k1_ge_table_set_globalz (size_t len, secp256k1_ge *a, const secp256k1_fe *zr)
static void secp256k1_gej_set_infinity (secp256k1_gej *r)
static void secp256k1_ge_set_infinity (secp256k1_ge *r)
static void secp256k1_gej_clear (secp256k1_gej *r)
static void secp256k1_ge_clear (secp256k1_ge *r)
static int secp256k1_ge_set_xo_var (secp256k1_ge *r, const secp256k1_fe *x, int odd)
static void secp256k1_gej_set_ge (secp256k1_gej *r, const secp256k1_ge *a)
static int secp256k1_gej_eq_x_var (const secp256k1_fe *x, const secp256k1_gej *a)
static void secp256k1_gej_neg (secp256k1_gej *r, const secp256k1_gej *a)
static int secp256k1_gej_is_infinity (const secp256k1_gej *a)
static int secp256k1_ge_is_valid_var (const secp256k1_ge *a)
static SECP256K1_INLINE void secp256k1_gej_double (secp256k1_gej *r, const secp256k1_gej *a)
static void secp256k1_gej_double_var (secp256k1_gej *r, const secp256k1_gej *a, secp256k1_fe *rzr)
static void secp256k1_gej_add_var (secp256k1_gej *r, const secp256k1_gej *a, const secp256k1_gej *b, secp256k1_fe *rzr)
static void secp256k1_gej_add_ge_var (secp256k1_gej *r, const secp256k1_gej *a, const secp256k1_ge *b, secp256k1_fe *rzr)
static void secp256k1_gej_add_zinv_var (secp256k1_gej *r, const secp256k1_gej *a, const secp256k1_ge *b, const secp256k1_fe *bzinv)
static void secp256k1_gej_add_ge (secp256k1_gej *r, const secp256k1_gej *a, const secp256k1_ge *b)
static void secp256k1_gej_rescale (secp256k1_gej *r, const secp256k1_fe *s)
static void secp256k1_ge_to_storage (secp256k1_ge_storage *r, const secp256k1_ge *a)
static void secp256k1_ge_from_storage (secp256k1_ge *r, const secp256k1_ge_storage *a)
static SECP256K1_INLINE void secp256k1_gej_cmov (secp256k1_gej *r, const secp256k1_gej *a, int flag)
static SECP256K1_INLINE void secp256k1_ge_storage_cmov (secp256k1_ge_storage *r, const secp256k1_ge_storage *a, int flag)
static void secp256k1_ge_mul_lambda (secp256k1_ge *r, const secp256k1_ge *a)
static int secp256k1_ge_is_in_correct_subgroup (const secp256k1_ge *ge)
Variables
static const secp256k1_ge secp256k1_ge_const_g = SECP256K1_G
static const secp256k1_fe secp256k1_fe_const_b = SECP256K1_FE_CONST(0, 0, 0, 0, 0, 0, 0, 7)
Macro Definition Documentation
SECP256K1_G
#define SECP256K1_G
Value:
    SECP256K1_GE_CONST(\
    0x79BE667EUL, 0xF9DCBBACUL, 0x55A06295UL, 0xCE870B07UL,\
    0x029BFCDBUL, 0x2DCE28D9UL, 0x59F2815BUL, 0x16F81798UL,\
    0x483ADA77UL, 0x26A3C465UL, 0x5DA4FBFCUL, 0x0E1108A8UL,\
    0xFD17B448UL, 0xA6855419UL, 0x9C47D08FUL, 0xFB10D4B8UL\
)
Generator for secp256k1, value 'g' defined in "Standards for Efficient Cryptography" (SEC2) 2.7.1.
Definition at line 28 of file group_impl.h.
SECP256K1_G_ORDER_13
#define SECP256K1_G_ORDER_13
Value:
    SECP256K1_GE_CONST(\
    0xc3459c3d, 0x35326167, 0xcd86cce8, 0x07a2417f,\
    0x5b8bd567, 0xde8538ee, 0x0d507b0c, 0xd128f5bb,\
    0x8e467fec, 0xcd30000a, 0x6cc1184e, 0x25d382c2,\
    0xa2f4494e, 0x2fbe9abc, 0x8b64abac, 0xd005fb24\
)
Definition at line 13 of file group_impl.h.
SECP256K1_G_ORDER_199
#define SECP256K1_G_ORDER_199
Value:
    SECP256K1_GE_CONST(\
    0x226e653f, 0xc8df7744, 0x9bacbf12, 0x7d1dcbf9,\
    0x87f05b2a, 0xe7edbd28, 0x1f564575, 0xc48dcf18,\
    0xa13872c2, 0xe933bb17, 0x5d9ffd5b, 0xb5b6e10c,\
    0x57fe3c00, 0xbaaaa15a, 0xe003ec3e, 0x9c269bae\
)
Definition at line 19 of file group_impl.h.
Function Documentation
secp256k1_ge_clear()
static void secp256k1_ge_clear (secp256k1_ge * r) static
Definition at line 208 of file group_impl.h.
{
    r->infinity = 0;
    secp256k1_fe_clear(&r->x);
    secp256k1_fe_clear(&r->y);
}
References secp256k1_ge::infinity, secp256k1_fe_clear(), secp256k1_ge::x, and secp256k1_ge::y.
secp256k1_ge_from_storage()
static void secp256k1_ge_from_storage (secp256k1_ge * r, const secp256k1_ge_storage * a) static
Definition at line 637 of file group_impl.h.
{
    secp256k1_fe_from_storage(&r->x, &a->x);
    secp256k1_fe_from_storage(&r->y, &a->y);
    r->infinity = 0;
}
References secp256k1_ge::infinity, secp256k1_fe_from_storage(), secp256k1_ge::x, secp256k1_ge_storage::x, secp256k1_ge::y, and secp256k1_ge_storage::y.
secp256k1_ge_is_in_correct_subgroup()
static int secp256k1_ge_is_in_correct_subgroup (const secp256k1_ge * ge) static
Definition at line 661 of file group_impl.h.
{
#ifdef EXHAUSTIVE_TEST_ORDER
    secp256k1_gej out;
    int i;
    /* A very simple EC multiplication ladder that avoids a dependency on ecmult. */
    secp256k1_gej_set_infinity(&out);
    for (i = 0; i < 32; ++i) {
        secp256k1_gej_double_var(&out, &out, NULL);
        if ((((uint32_t)EXHAUSTIVE_TEST_ORDER) >> (31 - i)) & 1) {
            secp256k1_gej_add_ge_var(&out, &out, ge, NULL);
        }
    }
    return secp256k1_gej_is_infinity(&out);
#else
    (void)ge;
    /* The real secp256k1 group has cofactor 1, so the subgroup is the entire curve. */
    return 1;
#endif
}
References EXHAUSTIVE_TEST_ORDER, secp256k1_gej_add_ge_var(), secp256k1_gej_double_var(), secp256k1_gej_is_infinity(), and secp256k1_gej_set_infinity().
secp256k1_ge_is_infinity()
static int secp256k1_ge_is_infinity (const secp256k1_ge * a) static
Definition at line 84 of file group_impl.h.
{
    return a->infinity;
}
References secp256k1_ge::infinity.
secp256k1_ge_is_valid_var()
static int secp256k1_ge_is_valid_var (const secp256k1_ge * a) static
Definition at line 260 of file group_impl.h.
{
    secp256k1_fe y2, x3;
    if (a->infinity) {
        return 0;
    }
    /* y^2 = x^3 + 7 */
    secp256k1_fe_sqr(&y2, &a->y);
    secp256k1_fe_sqr(&x3, &a->x); secp256k1_fe_mul(&x3, &x3, &a->x);
    secp256k1_fe_add(&x3, &secp256k1_fe_const_b);
    secp256k1_fe_normalize_weak(&x3);
    return secp256k1_fe_equal_var(&y2, &x3);
}
References secp256k1_ge::infinity, secp256k1_fe_add(), secp256k1_fe_const_b, secp256k1_fe_equal_var(), secp256k1_fe_mul(), secp256k1_fe_normalize_weak(), secp256k1_fe_sqr(), secp256k1_ge::x, and secp256k1_ge::y.
secp256k1_ge_mul_lambda()
static void secp256k1_ge_mul_lambda (secp256k1_ge * r, const secp256k1_ge * a) static
Definition at line 656 of file group_impl.h.
{
    *r = *a;
    secp256k1_fe_mul(&r->x, &r->x, &secp256k1_const_beta);
}
References secp256k1_const_beta, secp256k1_fe_mul(), and secp256k1_ge::x.
secp256k1_ge_neg()
static void secp256k1_ge_neg (secp256k1_ge * r, const secp256k1_ge * a) static
Definition at line 88 of file group_impl.h.
{
    *r = *a;
    secp256k1_fe_normalize_weak(&r->y);
    secp256k1_fe_negate(&r->y, &r->y, 1);
}
References secp256k1_fe_negate(), secp256k1_fe_normalize_weak(), and secp256k1_ge::y.
secp256k1_ge_set_all_gej_var()
static void secp256k1_ge_set_all_gej_var (secp256k1_ge * r, const secp256k1_gej * a, size_t len) static
Definition at line 122 of file group_impl.h.
{
    secp256k1_fe u;
    size_t i;
    size_t last_i = SIZE_MAX;
    for (i = 0; i < len; i++) {
        if (a[i].infinity) {
            secp256k1_ge_set_infinity(&r[i]);
        } else {
            /* Use destination's x coordinates as scratch space */
            if (last_i == SIZE_MAX) {
                r[i].x = a[i].z;
            } else {
                secp256k1_fe_mul(&r[i].x, &r[last_i].x, &a[i].z);
            }
            last_i = i;
        }
    }
    if (last_i == SIZE_MAX) {
        return;
    }
    secp256k1_fe_inv_var(&u, &r[last_i].x);
    i = last_i;
    while (i > 0) {
        i--;
        if (!a[i].infinity) {
            secp256k1_fe_mul(&r[last_i].x, &r[i].x, &u);
            secp256k1_fe_mul(&u, &u, &a[last_i].z);
            last_i = i;
        }
    }
    VERIFY_CHECK(!a[last_i].infinity);
    r[last_i].x = u;
    for (i = 0; i < len; i++) {
        if (!a[i].infinity) {
            secp256k1_ge_set_gej_zinv(&r[i], &a[i], &r[i].x);
        }
    }
}
References secp256k1_fe_inv_var(), secp256k1_fe_mul(), secp256k1_ge_set_gej_zinv(), secp256k1_ge_set_infinity(), VERIFY_CHECK, secp256k1_ge::x, and secp256k1_gej::z.
secp256k1_ge_set_gej()
static void secp256k1_ge_set_gej (secp256k1_ge * r, secp256k1_gej * a) static
Definition at line 94 of file group_impl.h.
{
    secp256k1_fe z2, z3;
    r->infinity = a->infinity;
    secp256k1_fe_inv(&a->z, &a->z);
    secp256k1_fe_sqr(&z2, &a->z);
    secp256k1_fe_mul(&z3, &a->z, &z2);
    secp256k1_fe_mul(&a->x, &a->x, &z2);
    secp256k1_fe_mul(&a->y, &a->y, &z3);
    secp256k1_fe_set_int(&a->z, 1);
    r->x = a->x;
    r->y = a->y;
}
References secp256k1_ge::infinity, secp256k1_gej::infinity, secp256k1_fe_inv(), secp256k1_fe_mul(), secp256k1_fe_set_int(), secp256k1_fe_sqr(), secp256k1_ge::x, secp256k1_gej::x, secp256k1_ge::y, secp256k1_gej::y, and secp256k1_gej::z.
secp256k1_ge_set_gej_var()
static void secp256k1_ge_set_gej_var (secp256k1_ge * r, secp256k1_gej * a) static
Definition at line 107 of file group_impl.h.
{
    secp256k1_fe z2, z3;
    if (a->infinity) {
        secp256k1_ge_set_infinity(r);
        return;
    }
    secp256k1_fe_inv_var(&a->z, &a->z);
    secp256k1_fe_sqr(&z2, &a->z);
    secp256k1_fe_mul(&z3, &a->z, &z2);
    secp256k1_fe_mul(&a->x, &a->x, &z2);
    secp256k1_fe_mul(&a->y, &a->y, &z3);
    secp256k1_fe_set_int(&a->z, 1);
    secp256k1_ge_set_xy(r, &a->x, &a->y);
}
References secp256k1_gej::infinity, secp256k1_fe_inv_var(), secp256k1_fe_mul(), secp256k1_fe_set_int(), secp256k1_fe_sqr(), secp256k1_ge_set_infinity(), secp256k1_ge_set_xy(), secp256k1_gej::x, secp256k1_gej::y, and secp256k1_gej::z.
secp256k1_ge_set_gej_zinv()
static void secp256k1_ge_set_gej_zinv (secp256k1_ge * r, const secp256k1_gej * a, const secp256k1_fe * zi) static
Definition at line 67 of file group_impl.h.
{
    secp256k1_fe zi2;
    secp256k1_fe zi3;
    VERIFY_CHECK(!a->infinity);
    secp256k1_fe_sqr(&zi2, zi);
    secp256k1_fe_mul(&zi3, &zi2, zi);
    secp256k1_fe_mul(&r->x, &a->x, &zi2);
    secp256k1_fe_mul(&r->y, &a->y, &zi3);
    r->infinity = a->infinity;
}
References secp256k1_ge::infinity, secp256k1_gej::infinity, secp256k1_fe_mul(), secp256k1_fe_sqr(), VERIFY_CHECK, secp256k1_ge::x, secp256k1_gej::x, secp256k1_ge::y, and secp256k1_gej::y.
Referenced by secp256k1_ecmult_odd_multiples_table(), secp256k1_ge_set_all_gej_var(), and secp256k1_ge_table_set_globalz().
secp256k1_ge_set_infinity()
static void secp256k1_ge_set_infinity (secp256k1_ge * r) static
Definition at line 195 of file group_impl.h.
{
    r->infinity = 1;
    secp256k1_fe_clear(&r->x);
    secp256k1_fe_clear(&r->y);
}
References secp256k1_ge::infinity, secp256k1_fe_clear(), secp256k1_ge::x, and secp256k1_ge::y.
Referenced by secp256k1_ge_set_all_gej_var(), and secp256k1_ge_set_gej_var().
secp256k1_ge_set_xo_var()
static int secp256k1_ge_set_xo_var (secp256k1_ge * r, const secp256k1_fe * x, int odd) static
Definition at line 214 of file group_impl.h.
{
    secp256k1_fe x2, x3;
    r->x = *x;
    secp256k1_fe_sqr(&x2, x);
    secp256k1_fe_mul(&x3, x, &x2);
    r->infinity = 0;
    secp256k1_fe_add(&x3, &secp256k1_fe_const_b);
    if (!secp256k1_fe_sqrt(&r->y, &x3)) {
        return 0;
    }
    secp256k1_fe_normalize_var(&r->y);
    if (secp256k1_fe_is_odd(&r->y) != odd) {
        secp256k1_fe_negate(&r->y, &r->y, 1);
    }
    return 1;
}
References secp256k1_ge::infinity, secp256k1_fe_add(), secp256k1_fe_const_b, secp256k1_fe_is_odd(), secp256k1_fe_mul(), secp256k1_fe_negate(), secp256k1_fe_normalize_var(), secp256k1_fe_sqr(), secp256k1_fe_sqrt(), secp256k1_ge::x, and secp256k1_ge::y.
secp256k1_ge_set_xy()
static void secp256k1_ge_set_xy (secp256k1_ge * r, const secp256k1_fe * x, const secp256k1_fe * y) static
Definition at line 78 of file group_impl.h.
{
    r->infinity = 0;
    r->x = *x;
    r->y = *y;
}
References secp256k1_ge::infinity, secp256k1_ge::x, and secp256k1_ge::y.
Referenced by secp256k1_ge_set_gej_var().
secp256k1_ge_storage_cmov()
static SECP256K1_INLINE void secp256k1_ge_storage_cmov (secp256k1_ge_storage * r, const secp256k1_ge_storage * a, int flag) static
Definition at line 651 of file group_impl.h.
{
    secp256k1_fe_storage_cmov(&r->x, &a->x, flag);
    secp256k1_fe_storage_cmov(&r->y, &a->y, flag);
}
References secp256k1_fe_storage_cmov(), secp256k1_ge_storage::x, and secp256k1_ge_storage::y.
secp256k1_ge_table_set_globalz()
static void secp256k1_ge_table_set_globalz (size_t len, secp256k1_ge * a, const secp256k1_fe * zr) static
Definition at line 164 of file group_impl.h.
{
    size_t i = len - 1;
    secp256k1_fe zs;
    if (len > 0) {
        /* Ensure all y values are in weak normal form for fast negation of points */
        secp256k1_fe_normalize_weak(&a[i].y);
        zs = zr[i];
        /* Work our way backwards, using the z-ratios to scale the x/y values. */
        while (i > 0) {
            secp256k1_gej tmpa;
            if (i != len - 1) {
                secp256k1_fe_mul(&zs, &zs, &zr[i]);
            }
            i--;
            tmpa.x = a[i].x;
            tmpa.y = a[i].y;
            tmpa.infinity = 0;
            secp256k1_ge_set_gej_zinv(&a[i], &tmpa, &zs);
        }
    }
}
References secp256k1_gej::infinity, secp256k1_fe_mul(), secp256k1_fe_normalize_weak(), secp256k1_ge_set_gej_zinv(), secp256k1_ge::x, secp256k1_gej::x, secp256k1_ge::y, and secp256k1_gej::y.
secp256k1_ge_to_storage()
static void secp256k1_ge_to_storage (secp256k1_ge_storage * r, const secp256k1_ge * a) static
Definition at line 626 of file group_impl.h.
{
    secp256k1_fe x, y;
    VERIFY_CHECK(!a->infinity);
    x = a->x;
    secp256k1_fe_normalize(&x);
    y = a->y;
    secp256k1_fe_normalize(&y);
    secp256k1_fe_to_storage(&r->x, &x);
    secp256k1_fe_to_storage(&r->y, &y);
}
References secp256k1_ge::infinity, secp256k1_fe_normalize(), secp256k1_fe_to_storage(), VERIFY_CHECK, secp256k1_ge::x, secp256k1_ge_storage::x, secp256k1_ge::y, and secp256k1_ge_storage::y.
secp256k1_gej_add_ge()
static void secp256k1_gej_add_ge (secp256k1_gej * r, const secp256k1_gej * a, const secp256k1_ge * b) static
In: Eric Brier and Marc Joye, Weierstrass Elliptic Curves and Side-Channel Attacks. In D. Naccache and P. Paillier, Eds., Public Key Cryptography, vol. 2274 of Lecture Notes in Computer Science, pages 335-345. Springer-Verlag, 2002. we find as solution for a unified addition/doubling formula: lambda = ((x1 + x2)^2 - x1 * x2 + a) / (y1 + y2), with a = 0 for secp256k1's curve equation. x3 = lambda^2 - (x1 + x2) 2*y3 = lambda * (x1 + x2 - 2 * x3) - (y1 + y2).
Substituting x_i = Xi / Zi^2 and yi = Yi / Zi^3, for i=1,2,3, gives: U1 = X1*Z2^2, U2 = X2*Z1^2 S1 = Y1*Z2^3, S2 = Y2*Z1^3 Z = Z1*Z2 T = U1+U2 M = S1+S2 Q = T*M^2 R = T^2-U1*U2 X3 = 4*(R^2-Q) Y3 = 4*(R*(3*Q-2*R^2)-M^4) Z3 = 2*M*Z (Note that the paper uses xi = Xi / Zi and yi = Yi / Zi instead.)
This formula has the benefit of being the same for both addition of distinct points and doubling. However, it breaks down in the case that either point is infinity, or that y1 = -y2. We handle these cases in the following ways:
If b is infinity we simply bail by means of a VERIFY_CHECK.
If a is infinity, we detect this, and at the end of the computation replace the result (which will be meaningless, but we compute to be constant-time) with b.x : b.y : 1.
If a = -b, we have y1 = -y2, which is a degenerate case. But here the answer is infinity, so we simply set the infinity flag of the result, overriding the computed values without even needing to cmov.
If y1 = -y2 but x1 != x2, which does occur thanks to certain properties of our curve (specifically, 1 has nontrivial cube roots in our field, and the curve equation has no x coefficient) then the answer is not infinity but also not given by the above equation. In this case, we cmov in place an alternate expression for lambda. Specifically (y1 - y2)/(x1 - x2). Where both these expressions for lambda are defined, they are equal, and can be obtained from each other by multiplication by (y1 + y2)/(y1 + y2) then substitution of x^3 + 7 for y^2 (using the curve equation). For all pairs of nonzero points (a, b) at least one is defined, so this covers everything.
If lambda = R/M = 0/0 we have a problem (except in the "trivial" case that Z = z1z2 = 0, and this is special-cased later on).
In case a->infinity == 1, replace r with (b->x, b->y, 1).
Definition at line 494 of file group_impl.h.
{
    /* Operations: 7 mul, 5 sqr, 4 normalize, 21 mul_int/add/negate/cmov */
    secp256k1_fe zz, u1, u2, s1, s2, t, tt, m, n, q, rr;
    secp256k1_fe m_alt, rr_alt;
    int infinity, degenerate;
    VERIFY_CHECK(!b->infinity);
    VERIFY_CHECK(a->infinity == 0 || a->infinity == 1);
    secp256k1_fe_sqr(&zz, &a->z);                       /* z = Z1^2 */
    u1 = a->x; secp256k1_fe_normalize_weak(&u1);        /* u1 = U1 = X1*Z2^2 (1) */
    secp256k1_fe_mul(&u2, &b->x, &zz);                  /* u2 = U2 = X2*Z1^2 (1) */
    s1 = a->y; secp256k1_fe_normalize_weak(&s1);        /* s1 = S1 = Y1*Z2^3 (1) */
    secp256k1_fe_mul(&s2, &b->y, &zz);                  /* s2 = Y2*Z1^2 (1) */
    secp256k1_fe_mul(&s2, &s2, &a->z);                  /* s2 = S2 = Y2*Z1^3 (1) */
    t = u1; secp256k1_fe_add(&t, &u2);                  /* t = T = U1+U2 (2) */
    m = s1; secp256k1_fe_add(&m, &s2);                  /* m = M = S1+S2 (2) */
    secp256k1_fe_sqr(&rr, &t);                          /* rr = T^2 (1) */
    secp256k1_fe_negate(&m_alt, &u2, 1);                /* Malt = -X2*Z1^2 */
    secp256k1_fe_mul(&tt, &u1, &m_alt);                 /* tt = -U1*U2 (2) */
    secp256k1_fe_add(&rr, &tt);                         /* rr = R = T^2-U1*U2 (3) */
    degenerate = secp256k1_fe_normalizes_to_zero(&m) &
                 secp256k1_fe_normalizes_to_zero(&rr);
    /* This only occurs when y1 == -y2 and x1^3 == x2^3, but x1 != x2.
     * This means either x1 == beta*x2 or beta*x1 == x2, where beta is
     * a nontrivial cube root of one. In either case, an alternate
     * non-indeterminate expression for lambda is (y1 - y2)/(x1 - x2),
     * so we set R/M equal to this. */
    rr_alt = s1;
    secp256k1_fe_mul_int(&rr_alt, 2);       /* rr = Y1*Z2^3 - Y2*Z1^3 (2) */
    secp256k1_fe_add(&m_alt, &u1);          /* Malt = X1*Z2^2 - X2*Z1^2 */
    secp256k1_fe_cmov(&rr_alt, &rr, !degenerate);
    secp256k1_fe_cmov(&m_alt, &m, !degenerate);
    /* Now Ralt / Malt = lambda and is guaranteed not to be 0/0.
     * From here on out Ralt and Malt represent the numerator
     * and denominator of lambda; R and M represent the explicit
     * expressions x1^2 + x2^2 + x1x2 and y1 + y2. */
    secp256k1_fe_sqr(&n, &m_alt);                       /* n = Malt^2 (1) */
    secp256k1_fe_mul(&q, &n, &t);                       /* q = Q = T*Malt^2 (1) */
    /* These two lines use the observation that either M == Malt or M == 0,
     * so M^3 * Malt is either Malt^4 (which is computed by squaring), or
     * zero (which is "computed" by cmov). So the cost is one squaring
     * versus two multiplications. */
    secp256k1_fe_sqr(&n, &n);
    secp256k1_fe_cmov(&n, &m, degenerate);              /* n = M^3 * Malt (2) */
    secp256k1_fe_sqr(&t, &rr_alt);                      /* t = Ralt^2 (1) */
    secp256k1_fe_mul(&r->z, &a->z, &m_alt);             /* r->z = Malt*Z (1) */
    infinity = secp256k1_fe_normalizes_to_zero(&r->z) & ~a->infinity;
    secp256k1_fe_mul_int(&r->z, 2);                     /* r->z = Z3 = 2*Malt*Z (2) */
    secp256k1_fe_negate(&q, &q, 1);                     /* q = -Q (2) */
    secp256k1_fe_add(&t, &q);                           /* t = Ralt^2-Q (3) */
    secp256k1_fe_normalize_weak(&t);
    r->x = t;                                           /* r->x = Ralt^2-Q (1) */
    secp256k1_fe_mul_int(&t, 2);                        /* t = 2*x3 (2) */
    secp256k1_fe_add(&t, &q);                           /* t = 2*x3 - Q: (4) */
    secp256k1_fe_mul(&t, &t, &rr_alt);                  /* t = Ralt*(2*x3 - Q) (1) */
    secp256k1_fe_add(&t, &n);                           /* t = Ralt*(2*x3 - Q) + M^3*Malt (3) */
    secp256k1_fe_negate(&r->y, &t, 3);                  /* r->y = Ralt*(Q - 2x3) - M^3*Malt (4) */
    secp256k1_fe_normalize_weak(&r->y);
    secp256k1_fe_mul_int(&r->x, 4);                     /* r->x = X3 = 4*(Ralt^2-Q) */
    secp256k1_fe_mul_int(&r->y, 4);                     /* r->y = Y3 = 4*Ralt*(Q - 2x3) - 4*M^3*Malt (4) */
    secp256k1_fe_cmov(&r->x, &b->x, a->infinity);
    secp256k1_fe_cmov(&r->y, &b->y, a->infinity);
    secp256k1_fe_cmov(&r->z, &secp256k1_fe_one, a->infinity);
    r->infinity = infinity;
}
References secp256k1_ge::infinity, secp256k1_gej::infinity, secp256k1_fe_add(), secp256k1_fe_cmov(), secp256k1_fe_mul(), secp256k1_fe_mul_int(), secp256k1_fe_negate(), secp256k1_fe_normalize_weak(), secp256k1_fe_normalizes_to_zero(), secp256k1_fe_one, secp256k1_fe_sqr(), VERIFY_CHECK, secp256k1_ge::x, secp256k1_gej::x, secp256k1_ge::y, secp256k1_gej::y, and secp256k1_gej::z.
secp256k1_gej_add_ge_var()
static void secp256k1_gej_add_ge_var (secp256k1_gej * r, const secp256k1_gej * a, const secp256k1_ge * b, secp256k1_fe * rzr) static
Definition at line 388 of file group_impl.h.
{
    /* 8 mul, 3 sqr, 4 normalize, 12 mul_int/add/negate */
    secp256k1_fe z12, u1, u2, s1, s2, h, i, i2, h2, h3, t;
    if (a->infinity) {
        VERIFY_CHECK(rzr == NULL);
        secp256k1_gej_set_ge(r, b);
        return;
    }
    if (b->infinity) {
        if (rzr != NULL) {
            secp256k1_fe_set_int(rzr, 1);
        }
        *r = *a;
        return;
    }
    r->infinity = 0;
    secp256k1_fe_sqr(&z12, &a->z);
    u1 = a->x; secp256k1_fe_normalize_weak(&u1);
    secp256k1_fe_mul(&u2, &b->x, &z12);
    s1 = a->y; secp256k1_fe_normalize_weak(&s1);
    secp256k1_fe_mul(&s2, &b->y, &z12); secp256k1_fe_mul(&s2, &s2, &a->z);
    secp256k1_fe_negate(&h, &u1, 1); secp256k1_fe_add(&h, &u2);
    secp256k1_fe_negate(&i, &s1, 1); secp256k1_fe_add(&i, &s2);
    if (secp256k1_fe_normalizes_to_zero_var(&h)) {
        if (secp256k1_fe_normalizes_to_zero_var(&i)) {
            secp256k1_gej_double_var(r, a, rzr);
        } else {
            if (rzr != NULL) {
                secp256k1_fe_set_int(rzr, 0);
            }
            secp256k1_gej_set_infinity(r);
        }
        return;
    }
    secp256k1_fe_sqr(&i2, &i);
    secp256k1_fe_sqr(&h2, &h);
    secp256k1_fe_mul(&h3, &h, &h2);
    if (rzr != NULL) {
        *rzr = h;
    }
    secp256k1_fe_mul(&r->z, &a->z, &h);
    secp256k1_fe_mul(&t, &u1, &h2);
    r->x = t; secp256k1_fe_mul_int(&r->x, 2); secp256k1_fe_add(&r->x, &h3); secp256k1_fe_negate(&r->x, &r->x, 3); secp256k1_fe_add(&r->x, &i2);
    secp256k1_fe_negate(&r->y, &r->x, 5); secp256k1_fe_add(&r->y, &t); secp256k1_fe_mul(&r->y, &r->y, &i);
    secp256k1_fe_mul(&h3, &h3, &s1); secp256k1_fe_negate(&h3, &h3, 1);
    secp256k1_fe_add(&r->y, &h3);
}
References secp256k1_ge::infinity, secp256k1_gej::infinity, secp256k1_fe_add(), secp256k1_fe_mul(), secp256k1_fe_mul_int(), secp256k1_fe_negate(), secp256k1_fe_normalize_weak(), secp256k1_fe_normalizes_to_zero_var(), secp256k1_fe_set_int(), secp256k1_fe_sqr(), secp256k1_gej_double_var(), secp256k1_gej_set_ge(), secp256k1_gej_set_infinity(), VERIFY_CHECK, secp256k1_ge::x, secp256k1_gej::x, secp256k1_ge::y, secp256k1_gej::y, and secp256k1_gej::z.
Referenced by secp256k1_ge_is_in_correct_subgroup().
secp256k1_gej_add_var()
static void secp256k1_gej_add_var (secp256k1_gej * r, const secp256k1_gej * a, const secp256k1_gej * b, secp256k1_fe * rzr) static
Definition at line 335 of file group_impl.h.
{
    /* Operations: 12 mul, 4 sqr, 2 normalize, 12 mul_int/add/negate */
    secp256k1_fe z22, z12, u1, u2, s1, s2, h, i, i2, h2, h3, t;
    if (a->infinity) {
        VERIFY_CHECK(rzr == NULL);
        *r = *b;
        return;
    }
    if (b->infinity) {
        if (rzr != NULL) {
            secp256k1_fe_set_int(rzr, 1);
        }
        *r = *a;
        return;
    }
    r->infinity = 0;
    secp256k1_fe_sqr(&z22, &b->z);
    secp256k1_fe_sqr(&z12, &a->z);
    secp256k1_fe_mul(&u1, &a->x, &z22);
    secp256k1_fe_mul(&u2, &b->x, &z12);
    secp256k1_fe_mul(&s1, &a->y, &z22); secp256k1_fe_mul(&s1, &s1, &b->z);
    secp256k1_fe_mul(&s2, &b->y, &z12); secp256k1_fe_mul(&s2, &s2, &a->z);
    secp256k1_fe_negate(&h, &u1, 1); secp256k1_fe_add(&h, &u2);
    secp256k1_fe_negate(&i, &s1, 1); secp256k1_fe_add(&i, &s2);
    if (secp256k1_fe_normalizes_to_zero_var(&h)) {
        if (secp256k1_fe_normalizes_to_zero_var(&i)) {
            secp256k1_gej_double_var(r, a, rzr);
        } else {
            if (rzr != NULL) {
                secp256k1_fe_set_int(rzr, 0);
            }
            secp256k1_gej_set_infinity(r);
        }
        return;
    }
    secp256k1_fe_sqr(&i2, &i);
    secp256k1_fe_sqr(&h2, &h);
    secp256k1_fe_mul(&h3, &h, &h2);
    secp256k1_fe_mul(&h, &h, &b->z);
    if (rzr != NULL) {
        *rzr = h;
    }
    secp256k1_fe_mul(&r->z, &a->z, &h);
    secp256k1_fe_mul(&t, &u1, &h2);
    r->x = t; secp256k1_fe_mul_int(&r->x, 2); secp256k1_fe_add(&r->x, &h3); secp256k1_fe_negate(&r->x, &r->x, 3); secp256k1_fe_add(&r->x, &i2);
    secp256k1_fe_negate(&r->y, &r->x, 5); secp256k1_fe_add(&r->y, &t); secp256k1_fe_mul(&r->y, &r->y, &i);
    secp256k1_fe_mul(&h3, &h3, &s1); secp256k1_fe_negate(&h3, &h3, 1);
    secp256k1_fe_add(&r->y, &h3);
}
References secp256k1_gej::infinity, secp256k1_fe_add(), secp256k1_fe_mul(), secp256k1_fe_mul_int(), secp256k1_fe_negate(), secp256k1_fe_normalizes_to_zero_var(), secp256k1_fe_set_int(), secp256k1_fe_sqr(), secp256k1_gej_double_var(), secp256k1_gej_set_infinity(), VERIFY_CHECK, secp256k1_gej::x, secp256k1_gej::y, and secp256k1_gej::z.
secp256k1_gej_add_zinv_var()
static void secp256k1_gej_add_zinv_var (secp256k1_gej * r, const secp256k1_gej * a, const secp256k1_ge * b, const secp256k1_fe * bzinv) static
We need to calculate (rx,ry,rz) = (ax,ay,az) + (bx,by,1/bzinv). Due to secp256k1's isomorphism we can multiply the Z coordinates on both sides by bzinv, and get: (rx,ry,rz*bzinv) = (ax,ay,az*bzinv) + (bx,by,1). This means that (rx,ry,rz) can be calculated as (ax,ay,az*bzinv) + (bx,by,1), when not applying the bzinv factor to rz. The variable az below holds the modified Z coordinate for a, which is used for the computation of rx and ry, but not for rz.
Definition at line 437 of file group_impl.h.
{
    /* 9 mul, 3 sqr, 4 normalize, 12 mul_int/add/negate */
    secp256k1_fe az, z12, u1, u2, s1, s2, h, i, i2, h2, h3, t;
    if (b->infinity) {
        *r = *a;
        return;
    }
    if (a->infinity) {
        secp256k1_fe bzinv2, bzinv3;
        r->infinity = b->infinity;
        secp256k1_fe_sqr(&bzinv2, bzinv);
        secp256k1_fe_mul(&bzinv3, &bzinv2, bzinv);
        secp256k1_fe_mul(&r->x, &b->x, &bzinv2);
        secp256k1_fe_mul(&r->y, &b->y, &bzinv3);
        secp256k1_fe_set_int(&r->z, 1);
        return;
    }
    r->infinity = 0;
    secp256k1_fe_mul(&az, &a->z, bzinv);
    secp256k1_fe_sqr(&z12, &az);
    u1 = a->x; secp256k1_fe_normalize_weak(&u1);
    secp256k1_fe_mul(&u2, &b->x, &z12);
    s1 = a->y; secp256k1_fe_normalize_weak(&s1);
    secp256k1_fe_mul(&s2, &b->y, &z12); secp256k1_fe_mul(&s2, &s2, &az);
    secp256k1_fe_negate(&h, &u1, 1); secp256k1_fe_add(&h, &u2);
    secp256k1_fe_negate(&i, &s1, 1); secp256k1_fe_add(&i, &s2);
    if (secp256k1_fe_normalizes_to_zero_var(&h)) {
        if (secp256k1_fe_normalizes_to_zero_var(&i)) {
            secp256k1_gej_double_var(r, a, NULL);
        } else {
            secp256k1_gej_set_infinity(r);
        }
        return;
    }
    secp256k1_fe_sqr(&i2, &i);
    secp256k1_fe_sqr(&h2, &h);
    secp256k1_fe_mul(&h3, &h, &h2);
    r->z = a->z; secp256k1_fe_mul(&r->z, &r->z, &h);
    secp256k1_fe_mul(&t, &u1, &h2);
    r->x = t; secp256k1_fe_mul_int(&r->x, 2); secp256k1_fe_add(&r->x, &h3); secp256k1_fe_negate(&r->x, &r->x, 3); secp256k1_fe_add(&r->x, &i2);
    secp256k1_fe_negate(&r->y, &r->x, 5); secp256k1_fe_add(&r->y, &t); secp256k1_fe_mul(&r->y, &r->y, &i);
    secp256k1_fe_mul(&h3, &h3, &s1); secp256k1_fe_negate(&h3, &h3, 1);
    secp256k1_fe_add(&r->y, &h3);
}
References secp256k1_ge::infinity, secp256k1_gej::infinity, secp256k1_fe_add(), secp256k1_fe_mul(), secp256k1_fe_mul_int(), secp256k1_fe_negate(), secp256k1_fe_normalize_weak(), secp256k1_fe_normalizes_to_zero_var(), secp256k1_fe_set_int(), secp256k1_fe_sqr(), secp256k1_gej_double_var(), secp256k1_gej_set_infinity(), secp256k1_ge::x, secp256k1_gej::x, secp256k1_ge::y, secp256k1_gej::y, and secp256k1_gej::z.
secp256k1_gej_clear()
static void secp256k1_gej_clear (secp256k1_gej * r) static
Definition at line 201 of file group_impl.h.
{
    r->infinity = 0;
    secp256k1_fe_clear(&r->x);
    secp256k1_fe_clear(&r->y);
    secp256k1_fe_clear(&r->z);
}
References secp256k1_gej::infinity, secp256k1_fe_clear(), secp256k1_gej::x, secp256k1_gej::y, and secp256k1_gej::z.
secp256k1_gej_cmov()
static SECP256K1_INLINE void secp256k1_gej_cmov (secp256k1_gej * r, const secp256k1_gej * a, int flag) static
Definition at line 643 of file group_impl.h.
{
    secp256k1_fe_cmov(&r->x, &a->x, flag);
    secp256k1_fe_cmov(&r->y, &a->y, flag);
    secp256k1_fe_cmov(&r->z, &a->z, flag);
    r->infinity ^= (r->infinity ^ a->infinity) & flag;
}
References secp256k1_gej::infinity, secp256k1_fe_cmov(), secp256k1_gej::x, secp256k1_gej::y, and secp256k1_gej::z.
secp256k1_gej_double()
static SECP256K1_INLINE void secp256k1_gej_double (secp256k1_gej * r, const secp256k1_gej * a) static
Definition at line 273 of file group_impl.h.
{
    /* Operations: 3 mul, 4 sqr, 0 normalize, 12 mul_int/add/negate.
     *
     * Note that there is an implementation described at
     *     https://hyperelliptic.org/EFD/g1p/auto-shortw-jacobian-0.html#doubling-dbl-2009-l
     * which trades a multiply for a square, but in practice this is actually slower,
     * mainly because it requires more normalizations.
     */
    secp256k1_fe t1,t2,t3,t4;
    r->infinity = a->infinity;
    secp256k1_fe_mul(&r->z, &a->z, &a->y);
    secp256k1_fe_mul_int(&r->z, 2);       /* Z' = 2*Y*Z (2) */
    secp256k1_fe_sqr(&t1, &a->x);
    secp256k1_fe_mul_int(&t1, 3);         /* T1 = 3*X^2 (3) */
    secp256k1_fe_sqr(&t2, &t1);           /* T2 = 9*X^4 (1) */
    secp256k1_fe_sqr(&t3, &a->y);
    secp256k1_fe_mul_int(&t3, 2);         /* T3 = 2*Y^2 (2) */
    secp256k1_fe_sqr(&t4, &t3);
    secp256k1_fe_mul_int(&t4, 2);         /* T4 = 8*Y^4 (2) */
    secp256k1_fe_mul(&t3, &t3, &a->x);    /* T3 = 2*X*Y^2 (1) */
    r->x = t3;
    secp256k1_fe_mul_int(&r->x, 4);       /* X' = 8*X*Y^2 (4) */
    secp256k1_fe_negate(&r->x, &r->x, 4); /* X' = -8*X*Y^2 (5) */
    secp256k1_fe_add(&r->x, &t2);         /* X' = 9*X^4 - 8*X*Y^2 (6) */
    secp256k1_fe_negate(&t2, &t2, 1);     /* T2 = -9*X^4 (2) */
    secp256k1_fe_mul_int(&t3, 6);         /* T3 = 12*X*Y^2 (6) */
    secp256k1_fe_add(&t3, &t2);           /* T3 = 12*X*Y^2 - 9*X^4 (8) */
    secp256k1_fe_mul(&r->y, &t1, &t3);    /* Y' = 36*X^3*Y^2 - 27*X^6 (1) */
    secp256k1_fe_negate(&t2, &t4, 2);     /* T2 = -8*Y^4 (3) */
    secp256k1_fe_add(&r->y, &t2);         /* Y' = 36*X^3*Y^2 - 27*X^6 - 8*Y^4 (4) */
}
References secp256k1_gej::infinity, secp256k1_fe_add(), secp256k1_fe_mul(), secp256k1_fe_mul_int(), secp256k1_fe_negate(), secp256k1_fe_sqr(), secp256k1_gej::x, secp256k1_gej::y, and secp256k1_gej::z.
Referenced by secp256k1_gej_double_var().
secp256k1_gej_double_var()
static void secp256k1_gej_double_var (secp256k1_gej * r, const secp256k1_gej * a, secp256k1_fe * rzr) static
For secp256k1, 2Q is infinity if and only if Q is infinity. This is because if 2Q = infinity, Q must equal -Q, or that Q.y == -(Q.y), or Q.y is 0. For a point on y^2 = x^3 + 7 to have y=0, x^3 must be -7 mod p. However, -7 has no cube root mod p.
Having said this, if this function receives a point on a sextic twist, e.g. by a fault attack, it is possible for y to be 0. This happens for y^2 = x^3 + 6, since -6 does have a cube root mod p. For this point, this function will not set the infinity flag even though the point doubles to infinity, and the result point will be gibberish (z = 0 but infinity = 0).
Definition at line 307 of file group_impl.h.
{
    if (a->infinity) {
        secp256k1_gej_set_infinity(r);
        if (rzr != NULL) {
            secp256k1_fe_set_int(rzr, 1);
        }
        return;
    }
    if (rzr != NULL) {
        *rzr = a->y;
        secp256k1_fe_normalize_weak(rzr);
        secp256k1_fe_mul_int(rzr, 2);
    }
    secp256k1_gej_double(r, a);
}
References secp256k1_gej::infinity, secp256k1_fe_mul_int(), secp256k1_fe_normalize_weak(), secp256k1_fe_set_int(), secp256k1_gej_double(), secp256k1_gej_set_infinity(), and secp256k1_gej::y.
Referenced by secp256k1_ge_is_in_correct_subgroup(), secp256k1_gej_add_ge_var(), secp256k1_gej_add_var(), and secp256k1_gej_add_zinv_var().
secp256k1_gej_eq_x_var()
static int secp256k1_gej_eq_x_var (const secp256k1_fe * x, const secp256k1_gej * a) static
Definition at line 239 of file group_impl.h.
{
    secp256k1_fe r, r2;
    VERIFY_CHECK(!a->infinity);
    secp256k1_fe_sqr(&r, &a->z); secp256k1_fe_mul(&r, &r, x);
    r2 = a->x; secp256k1_fe_normalize_weak(&r2);
    return secp256k1_fe_equal_var(&r, &r2);
}
References secp256k1_gej::infinity, secp256k1_fe_equal_var(), secp256k1_fe_mul(), secp256k1_fe_normalize_weak(), secp256k1_fe_sqr(), VERIFY_CHECK, secp256k1_gej::x, and secp256k1_gej::z.
secp256k1_gej_is_infinity()
static int secp256k1_gej_is_infinity (const secp256k1_gej * a) static
Definition at line 256 of file group_impl.h.
{
    return a->infinity;
}
References secp256k1_gej::infinity.
Referenced by secp256k1_ge_is_in_correct_subgroup().
secp256k1_gej_neg()
static void secp256k1_gej_neg (secp256k1_gej * r, const secp256k1_gej * a) static
Definition at line 247 of file group_impl.h.
{
    r->infinity = a->infinity;
    r->x = a->x;
    r->y = a->y;
    r->z = a->z;
    secp256k1_fe_normalize_weak(&r->y);
    secp256k1_fe_negate(&r->y, &r->y, 1);
}
References secp256k1_gej::infinity, secp256k1_fe_negate(), secp256k1_fe_normalize_weak(), secp256k1_gej::x, secp256k1_gej::y, and secp256k1_gej::z.
secp256k1_gej_rescale()
static void secp256k1_gej_rescale (secp256k1_gej * r, const secp256k1_fe * s) static
Definition at line 615 of file group_impl.h.
{
    /* Operations: 4 mul, 1 sqr */
    secp256k1_fe zz;
    VERIFY_CHECK(!secp256k1_fe_is_zero(s));
    secp256k1_fe_sqr(&zz, s);
    secp256k1_fe_mul(&r->x, &r->x, &zz);                /* r->x *= s^2 */
    secp256k1_fe_mul(&r->y, &r->y, &zz);
    secp256k1_fe_mul(&r->y, &r->y, s);                  /* r->y *= s^3 */
    secp256k1_fe_mul(&r->z, &r->z, s);                  /* r->z *= s   */
}
References secp256k1_fe_is_zero(), secp256k1_fe_mul(), secp256k1_fe_sqr(), VERIFY_CHECK, secp256k1_gej::x, secp256k1_gej::y, and secp256k1_gej::z.
secp256k1_gej_set_ge()
static void secp256k1_gej_set_ge (secp256k1_gej * r, const secp256k1_ge * a) static
Definition at line 232 of file group_impl.h.
{
   r->infinity = a->infinity;
   r->x = a->x;
   r->y = a->y;
   secp256k1_fe_set_int(&r->z, 1);
}
References secp256k1_ge::infinity, secp256k1_gej::infinity, secp256k1_fe_set_int(), secp256k1_ge::x, secp256k1_gej::x, secp256k1_ge::y, secp256k1_gej::y, and secp256k1_gej::z.
Referenced by secp256k1_gej_add_ge_var().
secp256k1_gej_set_infinity()
static void secp256k1_gej_set_infinity (secp256k1_gej * r) static
Definition at line 188 of file group_impl.h.
{
    r->infinity = 1;
    secp256k1_fe_clear(&r->x);
    secp256k1_fe_clear(&r->y);
    secp256k1_fe_clear(&r->z);
}
References secp256k1_gej::infinity, secp256k1_fe_clear(), secp256k1_gej::x, secp256k1_gej::y, and secp256k1_gej::z.
Referenced by secp256k1_ge_is_in_correct_subgroup(), secp256k1_gej_add_ge_var(), secp256k1_gej_add_var(), secp256k1_gej_add_zinv_var(), and secp256k1_gej_double_var().
Variable Documentation
secp256k1_fe_const_b
const secp256k1_fe secp256k1_fe_const_b = SECP256K1_FE_CONST(0, 0, 0, 0, 0, 0, 0, 7) static
Definition at line 64 of file group_impl.h.
Referenced by secp256k1_ge_is_valid_var(), and secp256k1_ge_set_xo_var().
secp256k1_ge_const_g
const secp256k1_ge secp256k1_ge_const_g = SECP256K1_G static
Definition at line 62 of file group_impl.h.
Referenced by bench_ecmult_multi_callback(), ecmult_const_chain_multiply(), ecmult_const_commutativity(), main(), print_two_tables(), run_ec_pubkey_parse_test(), run_ecmult_pre_g(), secp256k1_ecmult_gen_blind(), secp256k1_ecmult_pippenger_batch(), test_ecmult_accumulate(), test_ecmult_accumulate_cb(), test_ecmult_multi(), and test_point_times_order().