libdogecoin: include/dogecoin/hash.h File Reference
hash.h File Reference
#include <dogecoin/cstr.h>
#include <dogecoin/dogecoin.h>
#include <dogecoin/mem.h>
#include <dogecoin/sha2.h>
#include <dogecoin/vector.h>
Functions
LIBDOGECOIN_BEGIN_DECL static LIBDOGECOIN_API dogecoin_bool dogecoin_hash_is_empty (uint256 hash)
static LIBDOGECOIN_API void dogecoin_hash_clear (uint256 hash)
static LIBDOGECOIN_API dogecoin_bool dogecoin_hash_equal (uint256 hash_a, uint256 hash_b)
static LIBDOGECOIN_API void dogecoin_hash_set (uint256 hash_dest, const uint256 hash_src)
static LIBDOGECOIN_API void dogecoin_hash (const unsigned char *datain, size_t length, uint256 hashout)
static LIBDOGECOIN_API dogecoin_bool dogecoin_dblhash (const unsigned char *datain, size_t length, uint256 hashout)
static LIBDOGECOIN_API void dogecoin_hash_sngl_sha256 (const unsigned char *datain, size_t length, uint256 hashout)
Function Documentation
dogecoin_dblhash()
static LIBDOGECOIN_API dogecoin_bool dogecoin_dblhash (const unsigned char * datain, size_t length, uint256 hashout) inline static
Definition at line 66 of file hash.h.
{
    sha256_raw(datain, length, hashout);
    sha256_raw(hashout, SHA256_DIGEST_LENGTH, hashout); // dogecoin double sha256 hash
    return true;
}
References SHA256_DIGEST_LENGTH, and sha256_raw().
Referenced by dogecoin_b58check(), dogecoin_base58_encode_check(), and dogecoin_script_hash_to_p2pkh().
dogecoin_hash()
static LIBDOGECOIN_API void dogecoin_hash (const unsigned char * datain, size_t length, uint256 hashout) inline static
Definition at line 60 of file hash.h.
{
    sha256_raw(datain, length, hashout);
    sha256_raw(hashout, SHA256_DIGEST_LENGTH, hashout); // dogecoin double sha256 hash
}
References SHA256_DIGEST_LENGTH, and sha256_raw().
Referenced by dogecoin_p2p_message_new(), dogecoin_privkey_verify_pubkey(), dogecoin_tx_outputs_hash(), dogecoin_tx_prevout_hash(), dogecoin_tx_sequence_hash(), dogecoin_tx_sighash(), and hash_message().
dogecoin_hash_clear()
static LIBDOGECOIN_API void dogecoin_hash_clear (uint256 hash) inline static
Definition at line 45 of file hash.h.
{
    dogecoin_mem_zero(hash, DOGECOIN_HASH_LENGTH);
}
References DOGECOIN_HASH_LENGTH, and dogecoin_mem_zero().
Referenced by dogecoin_node_new().
dogecoin_hash_equal()
static LIBDOGECOIN_API dogecoin_bool dogecoin_hash_equal (uint256 hash_a, uint256 hash_b) inline static
Definition at line 50 of file hash.h.
{
    return (memcmp(hash_a, hash_b, DOGECOIN_HASH_LENGTH) == 0);
}
References DOGECOIN_HASH_LENGTH.
dogecoin_hash_is_empty()
LIBDOGECOIN_BEGIN_DECL static LIBDOGECOIN_API dogecoin_bool dogecoin_hash_is_empty (uint256 hash) inline static
Definition at line 40 of file hash.h.
{
    return hash[0] == 0 && !memcmp(hash, hash + 1, 19);
}
Referenced by dogecoin_tx_is_coinbase().
dogecoin_hash_set()
static LIBDOGECOIN_API void dogecoin_hash_set (uint256 hash_dest, const uint256 hash_src) inline static
Definition at line 55 of file hash.h.
{
    memcpy_safe(hash_dest, hash_src, DOGECOIN_HASH_LENGTH);
}
References DOGECOIN_HASH_LENGTH, and memcpy_safe().
dogecoin_hash_sngl_sha256()
static LIBDOGECOIN_API void dogecoin_hash_sngl_sha256 (const unsigned char * datain, size_t length, uint256 hashout) inline static
Definition at line 73 of file hash.h.
{
    sha256_raw(datain, length, hashout); // single sha256 hash
}
References sha256_raw().
Referenced by dogecoin_hdnode_get_hash160(), dogecoin_pubkey_get_hash160(), and dogecoin_script_get_scripthash().