libdogecoin: src/libevent/http-internal.h File Reference
http-internal.h File Reference
#include "event2/event_struct.h"
#include "util-internal.h"
#include "defer-internal.h"
Data Structures
struct evhttp_connection
struct evhttp_cb
struct evhttp_bound_socket
struct evhttp_server_alias
struct evhttp
Macros
#define HTTP_CONNECT_TIMEOUT 45
#define HTTP_WRITE_TIMEOUT 50
#define HTTP_READ_TIMEOUT 50
#define EVHTTP_REQ_UNKNOWN_ (1<<15)
#define EVHTTP_CON_INCOMING 0x0001 /* only one request on it ever */
#define EVHTTP_CON_OUTGOING 0x0002 /* multiple requests possible */
#define EVHTTP_CON_CLOSEDETECT 0x0004 /* detecting if persistent close */
#define EVHTTP_CON_AUTOFREE EVHTTP_CON_PUBLIC_FLAGS_END
#define EVHTTP_CON_READING_ERROR (EVHTTP_CON_AUTOFREE << 1)
Enumerations
enum message_read_status {
ALL_DATA_READ = 1 , MORE_DATA_EXPECTED = 0 , DATA_CORRUPTED = -1 , REQUEST_CANCELED = -2 ,
DATA_TOO_LONG = -3
}
enum evhttp_connection_state {
EVCON_DISCONNECTED , EVCON_CONNECTING , EVCON_IDLE , EVCON_READING_FIRSTLINE ,
EVCON_READING_HEADERS , EVCON_READING_BODY , EVCON_READING_TRAILER , EVCON_WRITING
}
Functions
TAILQ_HEAD (evconq, evhttp_connection)
void evhttp_connection_reset_ (struct evhttp_connection *)
int evhttp_connection_connect_ (struct evhttp_connection *)
EVENT2_EXPORT_SYMBOL void evhttp_connection_fail_ (struct evhttp_connection *, enum evhttp_request_error error)
EVENT2_EXPORT_SYMBOL enum message_read_status evhttp_parse_firstline_ (struct evhttp_request *, struct evbuffer *)
EVENT2_EXPORT_SYMBOL enum message_read_status evhttp_parse_headers_ (struct evhttp_request *, struct evbuffer *)
void evhttp_start_read_ (struct evhttp_connection *)
void evhttp_start_write_ (struct evhttp_connection *)
void evhttp_response_code_ (struct evhttp_request *, int, const char *)
void evhttp_send_page_ (struct evhttp_request *, struct evbuffer *)
EVENT2_EXPORT_SYMBOL int evhttp_decode_uri_internal (const char *uri, size_t length, char *ret, int decode_plus)
Macro Definition Documentation
EVHTTP_CON_AUTOFREE
#define EVHTTP_CON_AUTOFREE EVHTTP_CON_PUBLIC_FLAGS_END
Definition at line 75 of file http-internal.h.
EVHTTP_CON_CLOSEDETECT
#define EVHTTP_CON_CLOSEDETECT 0x0004 /* detecting if persistent close */
Definition at line 73 of file http-internal.h.
EVHTTP_CON_INCOMING
#define EVHTTP_CON_INCOMING 0x0001 /* only one request on it ever */
Definition at line 71 of file http-internal.h.
EVHTTP_CON_OUTGOING
#define EVHTTP_CON_OUTGOING 0x0002 /* multiple requests possible */
Definition at line 72 of file http-internal.h.
EVHTTP_CON_READING_ERROR
#define EVHTTP_CON_READING_ERROR (EVHTTP_CON_AUTOFREE << 1)
Definition at line 78 of file http-internal.h.
EVHTTP_REQ_UNKNOWN_
#define EVHTTP_REQ_UNKNOWN_ (1<<15)
Definition at line 34 of file http-internal.h.
HTTP_CONNECT_TIMEOUT
#define HTTP_CONNECT_TIMEOUT 45
Definition at line 17 of file http-internal.h.
HTTP_READ_TIMEOUT
#define HTTP_READ_TIMEOUT 50
Definition at line 19 of file http-internal.h.
HTTP_WRITE_TIMEOUT
#define HTTP_WRITE_TIMEOUT 50
Definition at line 18 of file http-internal.h.
Enumeration Type Documentation
evhttp_connection_state
enum evhttp_connection_state
Enumerator
EVCON_DISCONNECTED
not currently connected not trying either
EVCON_CONNECTING
tries to currently connect
EVCON_IDLE
connection is established
EVCON_READING_FIRSTLINE
reading Request-Line (incoming conn) or < Status-Line (outgoing conn)
EVCON_READING_HEADERS
reading request/response headers
EVCON_READING_BODY
reading request/response body
EVCON_READING_TRAILER
reading request/response chunked trailer
EVCON_WRITING
writing request/response headers/body
Definition at line 36 of file http-internal.h.
{
    EVCON_DISCONNECTED,
    EVCON_CONNECTING,
    EVCON_IDLE,
    EVCON_READING_FIRSTLINE,
    EVCON_READING_HEADERS,
    EVCON_READING_BODY,
    EVCON_READING_TRAILER,
    EVCON_WRITING
};
message_read_status
enum message_read_status
Enumerator
ALL_DATA_READ
MORE_DATA_EXPECTED
DATA_CORRUPTED
REQUEST_CANCELED
DATA_TOO_LONG
Definition at line 21 of file http-internal.h.
{
    ALL_DATA_READ = 1,
    MORE_DATA_EXPECTED = 0,
    DATA_CORRUPTED = -1,
    REQUEST_CANCELED = -2,
    DATA_TOO_LONG = -3
};
Function Documentation
evhttp_connection_connect_()
int evhttp_connection_connect_ (struct evhttp_connection * evcon)
Definition at line 2564 of file http.c.
{
    int old_state = evcon->state;
    const char *address = evcon->address;
    const struct sockaddr *sa = evhttp_connection_get_addr(evcon);
    int ret;
    if (evcon->state == EVCON_CONNECTING)
        return (0);
    evhttp_connection_reset_(evcon);
    EVUTIL_ASSERT(!(evcon->flags & EVHTTP_CON_INCOMING));
    evcon->flags |= EVHTTP_CON_OUTGOING;
    if (evcon->bind_address || evcon->bind_port) {
        evcon->fd = bind_socket(
            evcon->bind_address, evcon->bind_port, 0 /*reuse*/);
        if (evcon->fd == -1) {
            event_debug(("%s: failed to bind to \"%s\"",
                __func__, evcon->bind_address));
            return (-1);
        }
        if (bufferevent_setfd(evcon->bufev, evcon->fd))
            return (-1);
    } else {
        if (bufferevent_setfd(evcon->bufev, -1))
            return (-1);
    }
    /* Set up a callback for successful connection setup */
    bufferevent_setcb(evcon->bufev,
        NULL /* evhttp_read_cb */,
        NULL /* evhttp_write_cb */,
        evhttp_connection_cb,
        evcon);
    if (!evutil_timerisset(&evcon->timeout)) {
        const struct timeval conn_tv = { HTTP_CONNECT_TIMEOUT, 0 };
        bufferevent_set_timeouts(evcon->bufev, &conn_tv, &conn_tv);
    } else {
        bufferevent_set_timeouts(evcon->bufev, &evcon->timeout, &evcon->timeout);
    }
    /* make sure that we get a write callback */
    if (bufferevent_enable(evcon->bufev, EV_WRITE))
        return (-1);
    evcon->state = EVCON_CONNECTING;
    if (evcon->flags & EVHTTP_CON_REUSE_CONNECTED_ADDR &&
        sa &&
        (sa->sa_family == AF_INET || sa->sa_family == AF_INET6)) {
        int socklen = sizeof(struct sockaddr_in);
        if (sa->sa_family == AF_INET6) {
            socklen = sizeof(struct sockaddr_in6);
        }
        ret = bufferevent_socket_connect(evcon->bufev, sa, socklen);
    } else {
        ret = bufferevent_socket_connect_hostname(evcon->bufev,
                evcon->dns_base, evcon->ai_family, address, evcon->port);
    }
    if (ret < 0) {
        evcon->state = old_state;
        event_sock_warn(evcon->fd, "%s: connection to \"%s\" failed",
            __func__, evcon->address);
        /* some operating systems return ECONNREFUSED immediately
         * when connecting to a local address.  the cleanup is going
         * to reschedule this function call.
         */
        evhttp_connection_cb_cleanup(evcon);
        return (0);
    }
    return (0);
}
References __func__, evhttp_connection::address, AF_INET6, evhttp_connection::ai_family, evhttp_connection::bind_address, evhttp_connection::bind_port, bind_socket(), evhttp_connection::bufev, bufferevent_enable(), bufferevent_set_timeouts(), bufferevent_setcb(), bufferevent_setfd(), bufferevent_socket_connect(), bufferevent_socket_connect_hostname(), evhttp_connection::dns_base, EVCON_CONNECTING, event_debug, event_sock_warn(), EVHTTP_CON_INCOMING, EVHTTP_CON_OUTGOING, evhttp_connection_cb(), evhttp_connection_cb_cleanup(), evhttp_connection_get_addr(), evhttp_connection_reset_(), EVUTIL_ASSERT, evhttp_connection::fd, evhttp_connection::flags, HTTP_CONNECT_TIMEOUT, evhttp_connection::port, evhttp_connection::state, and evhttp_connection::timeout.
Referenced by evhttp_connection_done(), evhttp_connection_fail_(), evhttp_connection_retry(), and evhttp_make_request().
evhttp_connection_fail_()
EVENT2_EXPORT_SYMBOL void evhttp_connection_fail_ (struct evhttp_connection * evcon, enum evhttp_request_error error)
Definition at line 734 of file http.c.
{
    const int errsave = EVUTIL_SOCKET_ERROR();
    struct evhttp_request* req = TAILQ_FIRST(&evcon->requests);
    void (*cb)(struct evhttp_request *, void *);
    void *cb_arg;
    void (*error_cb)(enum evhttp_request_error, void *);
    void *error_cb_arg;
    EVUTIL_ASSERT(req != NULL);
    bufferevent_disable(evcon->bufev, EV_READ|EV_WRITE);
    if (evcon->flags & EVHTTP_CON_INCOMING) {
        /*
         * for incoming requests, there are two different
         * failure cases.  it's either a network level error
         * or an http layer error. for problems on the network
         * layer like timeouts we just drop the connections.
         * For HTTP problems, we might have to send back a
         * reply before the connection can be freed.
         */
        if (evhttp_connection_incoming_fail(req, error) == -1)
            evhttp_connection_free(evcon);
        return;
    }
    error_cb = req->error_cb;
    error_cb_arg = req->cb_arg;
    /* when the request was canceled, the callback is not executed */
    if (error != EVREQ_HTTP_REQUEST_CANCEL) {
        /* save the callback for later; the cb might free our object */
        cb = req->cb;
        cb_arg = req->cb_arg;
    } else {
        cb = NULL;
        cb_arg = NULL;
    }
    /* do not fail all requests; the next request is going to get
     * send over a new connection.   when a user cancels a request,
     * all other pending requests should be processed as normal
     */
    evhttp_request_free_(evcon, req);
    /* reset the connection */
    evhttp_connection_reset_(evcon);
    /* We are trying the next request that was queued on us */
    if (TAILQ_FIRST(&evcon->requests) != NULL)
        evhttp_connection_connect_(evcon);
    else
        if ((evcon->flags & EVHTTP_CON_OUTGOING) &&
            (evcon->flags & EVHTTP_CON_AUTOFREE)) {
            evhttp_connection_free(evcon);
        }
    /* The call to evhttp_connection_reset_ overwrote errno.
     * Let's restore the original errno, so that the user's
     * callback can have a better idea of what the error was.
     */
    EVUTIL_SET_SOCKET_ERROR(errsave);
    /* inform the user */
    if (error_cb != NULL)
        error_cb(error, error_cb_arg);
    if (cb != NULL)
        (*cb)(NULL, cb_arg);
}
References evhttp_connection::bufev, bufferevent_disable(), EVHTTP_CON_AUTOFREE, EVHTTP_CON_INCOMING, EVHTTP_CON_OUTGOING, evhttp_connection_connect_(), evhttp_connection_free(), evhttp_connection_incoming_fail(), evhttp_connection_reset_(), evhttp_request_free_(), EVUTIL_ASSERT, evhttp_connection::flags, and TAILQ_FIRST.
Referenced by evhttp_cancel_request(), evhttp_connection_read_on_write_error(), evhttp_error_cb(), evhttp_get_body(), evhttp_lingering_close(), evhttp_lingering_fail(), evhttp_read_body(), evhttp_read_firstline(), evhttp_read_header(), evhttp_read_trailer(), and evrpc_request_timeout().
evhttp_connection_reset_()
void evhttp_connection_reset_ (struct evhttp_connection * evcon)
Definition at line 1330 of file http.c.
{
    struct evbuffer *tmp;
    int err;
    bufferevent_setcb(evcon->bufev, NULL, NULL, NULL, NULL);
    /* XXXX This is not actually an optimal fix.  Instead we ought to have
       an API for "stop connecting", or use bufferevent_setfd to turn off
       connecting.  But for Libevent 2.0, this seems like a minimal change
       least likely to disrupt the rest of the bufferevent and http code.
       Why is this here?  If the fd is set in the bufferevent, and the
       bufferevent is connecting, then you can't actually stop the
       bufferevent from trying to connect with bufferevent_disable().  The
       connect will never trigger, since we close the fd, but the timeout
       might.  That caused an assertion failure in evhttp_connection_fail_.
    */
    bufferevent_disable_hard_(evcon->bufev, EV_READ|EV_WRITE);
    if (evcon->fd == -1)
        evcon->fd = bufferevent_getfd(evcon->bufev);
    if (evcon->fd != -1) {
        /* inform interested parties about connection close */
        if (evhttp_connected(evcon) && evcon->closecb != NULL)
            (*evcon->closecb)(evcon, evcon->closecb_arg);
        shutdown(evcon->fd, EVUTIL_SHUT_WR);
        evutil_closesocket(evcon->fd);
        evcon->fd = -1;
    }
    err = bufferevent_setfd(evcon->bufev, -1);
    EVUTIL_ASSERT(!err && "setfd");
    /* we need to clean up any buffered data */
    tmp = bufferevent_get_output(evcon->bufev);
    err = evbuffer_drain(tmp, -1);
    EVUTIL_ASSERT(!err && "drain output");
    tmp = bufferevent_get_input(evcon->bufev);
    err = evbuffer_drain(tmp, -1);
    EVUTIL_ASSERT(!err && "drain input");
    evcon->flags &= ~EVHTTP_CON_READING_ERROR;
    evcon->state = EVCON_DISCONNECTED;
}
References evhttp_connection::bufev, bufferevent_disable_hard_(), bufferevent_get_input(), bufferevent_get_output(), bufferevent_getfd(), bufferevent_setcb(), bufferevent_setfd(), evhttp_connection::closecb, evhttp_connection::closecb_arg, evbuffer_drain(), EVCON_DISCONNECTED, evhttp_connected(), EVUTIL_ASSERT, evutil_closesocket(), EVUTIL_SHUT_WR, evhttp_connection::fd, evhttp_connection::flags, and evhttp_connection::state.
Referenced by evhttp_connection_cb_cleanup(), evhttp_connection_connect_(), evhttp_connection_done(), evhttp_connection_fail_(), evhttp_error_cb(), and evhttp_read_cb().
evhttp_decode_uri_internal()
EVENT2_EXPORT_SYMBOL int evhttp_decode_uri_internal (const char * uri, size_t length, char * ret, int decode_plus)
Definition at line 3176 of file http.c.
{
    char c;
    int j;
    int decode_plus = (decode_plus_ctl == 1) ? 1: 0;
    unsigned i;
    for (i = j = 0; i < length; i++) {
        c = uri[i];
        if (c == '?') {
            if (decode_plus_ctl < 0)
                decode_plus = 1;
        } else if (c == '+' && decode_plus) {
            c = ' ';
        } else if ((i + 2) < length && c == '%' &&
            EVUTIL_ISXDIGIT_(uri[i+1]) && EVUTIL_ISXDIGIT_(uri[i+2])) {
            char tmp[3];
            tmp[0] = uri[i+1];
            tmp[1] = uri[i+2];
            tmp[2] = '\0';
            c = (char)strtol(tmp, NULL, 16);
            i += 2;
        }
        ret[j++] = c;
    }
    ret[j] = '\0';
    return (j);
}
References EVUTIL_ISXDIGIT_().
Referenced by evhttp_decode_uri(), evhttp_dispatch_callback(), evhttp_parse_query_impl(), and evhttp_uridecode().
evhttp_parse_firstline_()
EVENT2_EXPORT_SYMBOL enum message_read_status evhttp_parse_firstline_ (struct evhttp_request * req, struct evbuffer * buffer)
Definition at line 2025 of file http.c.
{
    char *line;
    enum message_read_status status = ALL_DATA_READ;
    size_t len;
    /* XXX try */
    line = evbuffer_readln(buffer, &len, EVBUFFER_EOL_CRLF);
    if (line == NULL) {
        if (req->evcon != NULL &&
            evbuffer_get_length(buffer) > req->evcon->max_headers_size)
            return (DATA_TOO_LONG);
        else
            return (MORE_DATA_EXPECTED);
    }
    if (req->evcon != NULL && len > req->evcon->max_headers_size) {
        mm_free(line);
        return (DATA_TOO_LONG);
    }
    req->headers_size = len;
    switch (req->kind) {
    case EVHTTP_REQUEST:
        if (evhttp_parse_request_line(req, line, len) == -1)
            status = DATA_CORRUPTED;
        break;
    case EVHTTP_RESPONSE:
        if (evhttp_parse_response_line(req, line) == -1)
            status = DATA_CORRUPTED;
        break;
    default:
        status = DATA_CORRUPTED;
    }
    mm_free(line);
    return (status);
}
References ALL_DATA_READ, DATA_CORRUPTED, DATA_TOO_LONG, evbuffer_get_length(), evbuffer_readln(), evhttp_parse_request_line(), evhttp_parse_response_line(), mm_free, and MORE_DATA_EXPECTED.
Referenced by evhttp_read_firstline().
evhttp_parse_headers_()
EVENT2_EXPORT_SYMBOL enum message_read_status evhttp_parse_headers_ (struct evhttp_request * req, struct evbuffer * buffer)
Definition at line 2096 of file http.c.
{
    enum message_read_status errcode = DATA_CORRUPTED;
    char *line;
    enum message_read_status status = MORE_DATA_EXPECTED;
    struct evkeyvalq* headers = req->input_headers;
    size_t len;
    while ((line = evbuffer_readln(buffer, &len, EVBUFFER_EOL_CRLF))
           != NULL) {
        char *skey, *svalue;
        req->headers_size += len;
        if (req->evcon != NULL &&
            req->headers_size > req->evcon->max_headers_size) {
            errcode = DATA_TOO_LONG;
            goto error;
        }
        if (*line == '\0') { /* Last header - Done */
            status = ALL_DATA_READ;
            mm_free(line);
            break;
        }
        /* Check if this is a continuation line */
        if (*line == ' ' || *line == '\t') {
            if (evhttp_append_to_last_header(headers, line) == -1)
                goto error;
            mm_free(line);
            continue;
        }
        /* Processing of header lines */
        svalue = line;
        skey = strsep(&svalue, ":");
        if (svalue == NULL)
            goto error;
        svalue += strspn(svalue, " ");
        evutil_rtrim_lws_(svalue);
        if (evhttp_add_header(headers, skey, svalue) == -1)
            goto error;
        mm_free(line);
    }
    if (status == MORE_DATA_EXPECTED) {
        if (req->evcon != NULL &&
        req->headers_size + evbuffer_get_length(buffer) > req->evcon->max_headers_size)
            return (DATA_TOO_LONG);
    }
    return (status);
 error:
    mm_free(line);
    return (errcode);
}
References ALL_DATA_READ, DATA_CORRUPTED, DATA_TOO_LONG, evbuffer_get_length(), evbuffer_readln(), evhttp_add_header(), evhttp_append_to_last_header(), evutil_rtrim_lws_(), mm_free, MORE_DATA_EXPECTED, and strsep().
Referenced by evhttp_read_header(), and evhttp_read_trailer().
evhttp_response_code_()
void evhttp_response_code_ (struct evhttp_request * req, int code, const char * reason)
Definition at line 3046 of file http.c.
{
    req->kind = EVHTTP_RESPONSE;
    req->response_code = code;
    if (req->response_code_line != NULL)
        mm_free(req->response_code_line);
    if (reason == NULL)
        reason = evhttp_response_phrase_internal(code);
    req->response_code_line = mm_strdup(reason);
    if (req->response_code_line == NULL) {
        event_warn("%s: strdup", __func__);
        /* XXX what else can we do? */
    }
}
References __func__, event_warn(), evhttp_response_phrase_internal(), mm_free, and mm_strdup.
Referenced by evhttp_handle_request(), evhttp_send_error(), evhttp_send_page_(), evhttp_send_reply(), and evhttp_send_reply_start().
evhttp_send_page_()
void evhttp_send_page_ (struct evhttp_request * req, struct evbuffer * databuf)
Definition at line 3062 of file http.c.
{
    if (!req->major || !req->minor) {
        req->major = 1;
        req->minor = 1;
    }
    if (req->kind != EVHTTP_RESPONSE)
        evhttp_response_code_(req, 200, "OK");
    evhttp_clear_headers(req->output_headers);
    evhttp_add_header(req->output_headers, "Content-Type", "text/html");
    evhttp_add_header(req->output_headers, "Connection", "close");
    evhttp_send(req, databuf);
}
References evhttp_add_header(), evhttp_clear_headers(), evhttp_response_code_(), and evhttp_send().
Referenced by evhttp_handle_request(), and evhttp_send_error().
evhttp_start_read_()
void evhttp_start_read_ (struct evhttp_connection * evcon)
Definition at line 2735 of file http.c.
{
    bufferevent_disable(evcon->bufev, EV_WRITE);
    bufferevent_enable(evcon->bufev, EV_READ);
    evcon->state = EVCON_READING_FIRSTLINE;
    /* Reset the bufferevent callbacks */
    bufferevent_setcb(evcon->bufev,
        evhttp_read_cb,
        evhttp_write_cb,
        evhttp_error_cb,
        evcon);
    /* If there's still data pending, process it next time through the
     * loop.  Don't do it now; that could get recusive. */
    if (evbuffer_get_length(bufferevent_get_input(evcon->bufev))) {
        event_deferred_cb_schedule_(get_deferred_queue(evcon),
            &evcon->read_more_deferred_cb);
    }
}
References evhttp_connection::bufev, bufferevent_disable(), bufferevent_enable(), bufferevent_get_input(), bufferevent_setcb(), evbuffer_get_length(), EVCON_READING_FIRSTLINE, event_deferred_cb_schedule_(), evhttp_error_cb(), evhttp_read_cb(), evhttp_write_cb(), get_deferred_queue, evhttp_connection::read_more_deferred_cb, and evhttp_connection::state.
Referenced by evhttp_associate_new_request_with_connection(), evhttp_connection_read_on_write_error(), and evhttp_write_connectioncb().
evhttp_start_write_()
void evhttp_start_write_ (struct evhttp_connection * evcon)
Definition at line 2757 of file http.c.
{
    bufferevent_disable(evcon->bufev, EV_WRITE);
    bufferevent_enable(evcon->bufev, EV_READ);
    evcon->state = EVCON_WRITING;
    evhttp_write_buffer(evcon, evhttp_write_connectioncb, NULL);
}
References evhttp_connection::bufev, bufferevent_disable(), bufferevent_enable(), EVCON_WRITING, evhttp_write_buffer(), evhttp_write_connectioncb(), and evhttp_connection::state.
Referenced by evhttp_read_header().
TAILQ_HEAD()
TAILQ_HEAD (evconq , evhttp_connection)