libdogecoin: src/libevent/iocp-internal.h File Reference
iocp-internal.h File Reference
Data Structures
struct event_overlapped
Typedefs
typedef void(* iocp_callback) (struct event_overlapped *, ev_uintptr_t, ev_ssize_t, int success)
Functions
EVENT2_EXPORT_SYMBOL void event_overlapped_init_ (struct event_overlapped *, iocp_callback cb)
EVENT2_EXPORT_SYMBOL struct evbuffer * evbuffer_overlapped_new_ (evutil_socket_t fd)
evutil_socket_t evbuffer_overlapped_get_fd_ (struct evbuffer *buf)
void evbuffer_overlapped_set_fd_ (struct evbuffer *buf, evutil_socket_t fd)
EVENT2_EXPORT_SYMBOL int evbuffer_launch_read_ (struct evbuffer *buf, size_t n, struct event_overlapped *ol)
EVENT2_EXPORT_SYMBOL int evbuffer_launch_write_ (struct evbuffer *buf, ev_ssize_t n, struct event_overlapped *ol)
EVENT2_EXPORT_SYMBOL void evbuffer_commit_read_ (struct evbuffer *, ev_ssize_t)
EVENT2_EXPORT_SYMBOL void evbuffer_commit_write_ (struct evbuffer *, ev_ssize_t)
EVENT2_EXPORT_SYMBOL struct event_iocp_port * event_iocp_port_launch_ (int n_cpus)
EVENT2_EXPORT_SYMBOL int event_iocp_port_associate_ (struct event_iocp_port *port, evutil_socket_t fd, ev_uintptr_t key)
EVENT2_EXPORT_SYMBOL int event_iocp_shutdown_ (struct event_iocp_port *port, long waitMsec)
EVENT2_EXPORT_SYMBOL int event_iocp_activate_overlapped_ (struct event_iocp_port *port, struct event_overlapped *o, ev_uintptr_t key, ev_uint32_t n_bytes)
EVENT2_EXPORT_SYMBOL struct event_iocp_port * event_base_get_iocp_ (struct event_base *base)
EVENT2_EXPORT_SYMBOL int event_base_start_iocp_ (struct event_base *base, int n_cpus)
void event_base_stop_iocp_ (struct event_base *base)
EVENT2_EXPORT_SYMBOL struct bufferevent * bufferevent_async_new_ (struct event_base *base, evutil_socket_t fd, int options)
void bufferevent_async_set_connected_ (struct bufferevent *bev)
int bufferevent_async_can_connect_ (struct bufferevent *bev)
int bufferevent_async_connect_ (struct bufferevent *bev, evutil_socket_t fd, const struct sockaddr *sa, int socklen)
Typedef Documentation
iocp_callback
typedef void(* iocp_callback) (struct event_overlapped *, ev_uintptr_t, ev_ssize_t, int success)
Definition at line 37 of file iocp-internal.h.
Function Documentation
bufferevent_async_can_connect_()
int bufferevent_async_can_connect_ (struct bufferevent * bev)
Definition at line 605 of file bufferevent_async.c.
{
    const struct win32_extension_fns *ext =
        event_get_win32_extension_fns_();
    if (BEV_IS_ASYNC(bev) &&
        event_base_get_iocp_(bev->ev_base) &&
        ext && ext->ConnectEx)
        return 1;
    return 0;
}
References BEV_IS_ASYNC, event_base_get_iocp_(), and event_get_win32_extension_fns_().
Referenced by bufferevent_socket_connect().
bufferevent_async_connect_()
int bufferevent_async_connect_ (struct bufferevent * bev, evutil_socket_t fd, const struct sockaddr * sa, int socklen)
Definition at line 619 of file bufferevent_async.c.
{
    BOOL rc;
    struct bufferevent_async *bev_async = upcast(bev);
    struct sockaddr_storage ss;
    const struct win32_extension_fns *ext =
        event_get_win32_extension_fns_();
    EVUTIL_ASSERT(ext && ext->ConnectEx && fd >= 0 && sa != NULL);
    /* ConnectEx() requires that the socket be bound to an address
     * with bind() before using, otherwise it will fail. We attempt
     * to issue a bind() here, taking into account that the error
     * code is set to WSAEINVAL when the socket is already bound. */
    memset(&ss, 0, sizeof(ss));
    if (sa->sa_family == AF_INET) {
        struct sockaddr_in *sin = (struct sockaddr_in *)&ss;
        sin->sin_family = AF_INET;
        sin->sin_addr.s_addr = INADDR_ANY;
    } else if (sa->sa_family == AF_INET6) {
        struct sockaddr_in6 *sin6 = (struct sockaddr_in6 *)&ss;
        sin6->sin6_family = AF_INET6;
        sin6->sin6_addr = in6addr_any;
    } else {
        /* Well, the user will have to bind() */
        return -1;
    }
    if (bind(fd, (struct sockaddr *)&ss, sizeof(ss)) < 0 &&
        WSAGetLastError() != WSAEINVAL)
        return -1;
    event_base_add_virtual_(bev->ev_base);
    bufferevent_incref_(bev);
    rc = ext->ConnectEx(fd, sa, socklen, NULL, 0, NULL,
                &bev_async->connect_overlapped.overlapped);
    if (rc || WSAGetLastError() == ERROR_IO_PENDING)
        return 0;
    event_base_del_virtual_(bev->ev_base);
    bufferevent_decref_(bev);
    return -1;
}
References AF_INET6, bufferevent_async::bev, bufferevent_decref_, bufferevent_incref_, bufferevent_async::connect_overlapped, event_base_add_virtual_(), event_base_del_virtual_(), event_get_win32_extension_fns_(), EVUTIL_ASSERT, sockaddr_in6::sin6_addr, sockaddr_in6::sin6_family, and upcast().
Referenced by bufferevent_socket_connect().
bufferevent_async_new_()
EVENT2_EXPORT_SYMBOL struct bufferevent * bufferevent_async_new_ (struct event_base * base, evutil_socket_t fd, int options)
Definition at line 543 of file bufferevent_async.c.
{
    struct bufferevent_async *bev_a;
    struct bufferevent *bev;
    struct event_iocp_port *iocp;
    options |= BEV_OPT_THREADSAFE;
    if (!(iocp = event_base_get_iocp_(base)))
        return NULL;
    if (fd >= 0 && event_iocp_port_associate_(iocp, fd, 1)<0) {
        if (fatal_error(GetLastError()))
            return NULL;
    }
    if (!(bev_a = mm_calloc(1, sizeof(struct bufferevent_async))))
        return NULL;
    bev = &bev_a->bev.bev;
    if (!(bev->input = evbuffer_overlapped_new_(fd))) {
        mm_free(bev_a);
        return NULL;
    }
    if (!(bev->output = evbuffer_overlapped_new_(fd))) {
        evbuffer_free(bev->input);
        mm_free(bev_a);
        return NULL;
    }
    if (bufferevent_init_common_(&bev_a->bev, base, &bufferevent_ops_async,
        options)<0)
        goto err;
    evbuffer_add_cb(bev->input, be_async_inbuf_callback, bev);
    evbuffer_add_cb(bev->output, be_async_outbuf_callback, bev);
    event_overlapped_init_(&bev_a->connect_overlapped, connect_complete);
    event_overlapped_init_(&bev_a->read_overlapped, read_complete);
    event_overlapped_init_(&bev_a->write_overlapped, write_complete);
    bufferevent_init_generic_timeout_cbs_(bev);
    bev_a->ok = fd >= 0;
    return bev;
err:
    bufferevent_free(&bev_a->bev.bev);
    return NULL;
}
References be_async_inbuf_callback(), be_async_outbuf_callback(), bufferevent_private::bev, bufferevent_async::bev, bufferevent_free(), bufferevent_init_common_(), bufferevent_init_generic_timeout_cbs_(), bufferevent_ops_async, connect_complete(), bufferevent_async::connect_overlapped, evbuffer_add_cb(), evbuffer_free(), evbuffer_overlapped_new_(), event_base_get_iocp_(), event_iocp_port_associate_(), event_overlapped_init_(), fatal_error(), mm_calloc, mm_free, bufferevent_async::ok, read_complete(), bufferevent_async::read_overlapped, write_complete(), and bufferevent_async::write_overlapped.
Referenced by bufferevent_socket_new().
bufferevent_async_set_connected_()
void bufferevent_async_set_connected_ (struct bufferevent * bev)
Definition at line 596 of file bufferevent_async.c.
{
    struct bufferevent_async *bev_async = upcast(bev);
    bev_async->ok = 1;
    /* Now's a good time to consider reading/writing */
    be_async_enable(bev, bev->enabled);
}
References be_async_enable(), bufferevent_async::bev, bufferevent_async::ok, and upcast().
Referenced by bufferevent_writecb(), and connect_complete().
evbuffer_commit_read_()
EVENT2_EXPORT_SYMBOL void evbuffer_commit_read_ (struct evbuffer * evbuf, ev_ssize_t nBytes)
XXX document
Definition at line 98 of file buffer_iocp.c.
{
    struct evbuffer_overlapped *buf = upcast_evbuffer(evbuf);
    struct evbuffer_chain **chainp;
    size_t remaining, len;
    unsigned i;
    EVBUFFER_LOCK(evbuf);
    EVUTIL_ASSERT(buf->read_in_progress && !buf->write_in_progress);
    EVUTIL_ASSERT(nBytes >= 0); /* XXXX Can this be false? */
    evbuffer_unfreeze(evbuf, 0);
    chainp = evbuf->last_with_datap;
    if (!((*chainp)->flags & EVBUFFER_MEM_PINNED_R))
        chainp = &(*chainp)->next;
    remaining = nBytes;
    for (i = 0; remaining > 0 && i < (unsigned)buf->n_buffers; ++i) {
        EVUTIL_ASSERT(*chainp);
        len = buf->buffers[i].len;
        if (remaining < len)
            len = remaining;
        (*chainp)->off += len;
        evbuf->last_with_datap = chainp;
        remaining -= len;
        chainp = &(*chainp)->next;
    }
    pin_release(buf, EVBUFFER_MEM_PINNED_R);
    buf->read_in_progress = 0;
    evbuf->total_len += nBytes;
    evbuf->n_add_for_cb += nBytes;
    evbuffer_invoke_callbacks_(evbuf);
    evbuffer_decref_and_unlock_(evbuf);
}
References evbuffer_overlapped::buffers, evbuffer_decref_and_unlock_(), evbuffer_invoke_callbacks_(), EVBUFFER_LOCK, EVBUFFER_MEM_PINNED_R, evbuffer_unfreeze(), EVUTIL_ASSERT, evbuffer::last_with_datap, evbuffer::n_add_for_cb, evbuffer_overlapped::n_buffers, evbuffer_chain::next, pin_release(), evbuffer_overlapped::read_in_progress, evbuffer::total_len, upcast_evbuffer(), and evbuffer_overlapped::write_in_progress.
Referenced by read_complete().
evbuffer_commit_write_()
EVENT2_EXPORT_SYMBOL void evbuffer_commit_write_ (struct evbuffer * evbuf, ev_ssize_t nBytes)
Definition at line 139 of file buffer_iocp.c.
{
    struct evbuffer_overlapped *buf = upcast_evbuffer(evbuf);
    EVBUFFER_LOCK(evbuf);
    EVUTIL_ASSERT(buf->write_in_progress && !buf->read_in_progress);
    evbuffer_unfreeze(evbuf, 1);
    evbuffer_drain(evbuf, nBytes);
    pin_release(buf,EVBUFFER_MEM_PINNED_W);
    buf->write_in_progress = 0;
    evbuffer_decref_and_unlock_(evbuf);
}
References evbuffer_decref_and_unlock_(), evbuffer_drain(), EVBUFFER_LOCK, EVBUFFER_MEM_PINNED_W, evbuffer_unfreeze(), EVUTIL_ASSERT, pin_release(), evbuffer_overlapped::read_in_progress, upcast_evbuffer(), and evbuffer_overlapped::write_in_progress.
Referenced by write_complete().
evbuffer_launch_read_()
EVENT2_EXPORT_SYMBOL int evbuffer_launch_read_ (struct evbuffer * buf, size_t n, struct event_overlapped * ol)
Start reading data onto the end of an overlapped evbuffer.
An evbuffer can only have one read pending at a time. While the read is in progress, no other data may be added to the end of the buffer. The buffer must be created with event_overlapped_init_(). evbuffer_commit_read_() must be called in the completion callback.
Parameters
buf The buffer to read onto
n The number of bytes to try to read.
ol Overlapped object with associated completion callback.
Returns
0 on success, -1 on error.
Definition at line 246 of file buffer_iocp.c.
{
    struct evbuffer_overlapped *buf_o = upcast_evbuffer(buf);
    int r = -1, i;
    int nvecs;
    int npin=0;
    struct evbuffer_chain *chain=NULL, **chainp;
    DWORD bytesRead;
    DWORD flags = 0;
    struct evbuffer_iovec vecs[MAX_WSABUFS];
    if (!buf_o)
        return -1;
    EVBUFFER_LOCK(buf);
    EVUTIL_ASSERT(!buf_o->write_in_progress);
    if (buf->freeze_end || buf_o->read_in_progress)
        goto done;
    buf_o->first_pinned = NULL;
    buf_o->n_buffers = 0;
    memset(buf_o->buffers, 0, sizeof(buf_o->buffers));
    if (evbuffer_expand_fast_(buf, at_most, MAX_WSABUFS) == -1)
        goto done;
    evbuffer_freeze(buf, 0);
    nvecs = evbuffer_read_setup_vecs_(buf, at_most,
        vecs, MAX_WSABUFS, &chainp, 1);
    for (i=0;i<nvecs;++i) {
        WSABUF_FROM_EVBUFFER_IOV(
            &buf_o->buffers[i],
            &vecs[i]);
    }
    buf_o->n_buffers = nvecs;
    buf_o->first_pinned = chain = *chainp;
    npin=0;
    for ( ; chain; chain = chain->next) {
        evbuffer_chain_pin_(chain, EVBUFFER_MEM_PINNED_R);
        ++npin;
    }
    EVUTIL_ASSERT(npin == nvecs);
    evbuffer_incref_(buf);
    if (WSARecv(buf_o->fd, buf_o->buffers, nvecs, &bytesRead, &flags,
            &ol->overlapped, NULL)) {
        int error = WSAGetLastError();
        if (error != WSA_IO_PENDING) {
            /* An actual error. */
            pin_release(buf_o, EVBUFFER_MEM_PINNED_R);
            evbuffer_unfreeze(buf, 0);
            evbuffer_free(buf); /* decref */
            goto done;
        }
    }
    buf_o->read_in_progress = 1;
    r = 0;
done:
    EVBUFFER_UNLOCK(buf);
    return r;
}
References evbuffer_overlapped::buffers, evbuffer_chain_pin_(), evbuffer_expand_fast_(), evbuffer_free(), evbuffer_freeze(), evbuffer_incref_(), EVBUFFER_LOCK, EVBUFFER_MEM_PINNED_R, evbuffer_read_setup_vecs_(), evbuffer_unfreeze(), EVBUFFER_UNLOCK, EVUTIL_ASSERT, evbuffer_overlapped::fd, evbuffer_overlapped::first_pinned, evbuffer_chain::flags, evbuffer::freeze_end, MAX_WSABUFS, evbuffer_overlapped::n_buffers, evbuffer_chain::next, pin_release(), evbuffer_overlapped::read_in_progress, upcast_evbuffer(), evbuffer_overlapped::write_in_progress, and WSABUF_FROM_EVBUFFER_IOV.
Referenced by bev_async_consider_reading().
evbuffer_launch_write_()
EVENT2_EXPORT_SYMBOL int evbuffer_launch_write_ (struct evbuffer * buf, ev_ssize_t n, struct event_overlapped * ol)
Start writing data from the start of an evbuffer.
An evbuffer can only have one write pending at a time. While the write is in progress, no other data may be removed from the front of the buffer. The buffer must be created with event_overlapped_init_(). evbuffer_commit_write_() must be called in the completion callback.
Parameters
buf The buffer to read onto
n The number of bytes to try to read.
ol Overlapped object with associated completion callback.
Returns
0 on success, -1 on error.
Definition at line 172 of file buffer_iocp.c.
{
    struct evbuffer_overlapped *buf_o = upcast_evbuffer(buf);
    int r = -1;
    int i;
    struct evbuffer_chain *chain;
    DWORD bytesSent;
    if (!buf) {
        /* No buffer, or it isn't overlapped */
        return -1;
    }
    EVBUFFER_LOCK(buf);
    EVUTIL_ASSERT(!buf_o->read_in_progress);
    if (buf->freeze_start || buf_o->write_in_progress)
        goto done;
    if (!buf->total_len) {
        /* Nothing to write */
        r = 0;
        goto done;
    } else if (at_most < 0 || (size_t)at_most > buf->total_len) {
        at_most = buf->total_len;
    }
    evbuffer_freeze(buf, 1);
    buf_o->first_pinned = NULL;
    buf_o->n_buffers = 0;
    memset(buf_o->buffers, 0, sizeof(buf_o->buffers));
    chain = buf_o->first_pinned = buf->first;
    for (i=0; i < MAX_WSABUFS && chain; ++i, chain=chain->next) {
        WSABUF *b = &buf_o->buffers[i];
        b->buf = (char*)( chain->buffer + chain->misalign );
        evbuffer_chain_pin_(chain, EVBUFFER_MEM_PINNED_W);
        if ((size_t)at_most > chain->off) {
            /* XXXX Cast is safe for now, since win32 has no
               mmaped chains.  But later, we need to have this
               add more WSAbufs if chain->off is greater than
               ULONG_MAX */
            b->len = (unsigned long)chain->off;
            at_most -= chain->off;
        } else {
            b->len = (unsigned long)at_most;
            ++i;
            break;
        }
    }
    buf_o->n_buffers = i;
    evbuffer_incref_(buf);
    if (WSASend(buf_o->fd, buf_o->buffers, i, &bytesSent, 0,
        &ol->overlapped, NULL)) {
        int error = WSAGetLastError();
        if (error != WSA_IO_PENDING) {
            /* An actual error. */
            pin_release(buf_o, EVBUFFER_MEM_PINNED_W);
            evbuffer_unfreeze(buf, 1);
            evbuffer_free(buf); /* decref */
            goto done;
        }
    }
    buf_o->write_in_progress = 1;
    r = 0;
done:
    EVBUFFER_UNLOCK(buf);
    return r;
}
References evbuffer_chain::buffer, evbuffer_overlapped::buffers, evbuffer_chain_pin_(), evbuffer_free(), evbuffer_freeze(), evbuffer_incref_(), EVBUFFER_LOCK, EVBUFFER_MEM_PINNED_W, evbuffer_unfreeze(), EVBUFFER_UNLOCK, EVUTIL_ASSERT, evbuffer_overlapped::fd, evbuffer::first, evbuffer_overlapped::first_pinned, evbuffer::freeze_start, MAX_WSABUFS, evbuffer_chain::misalign, evbuffer_overlapped::n_buffers, evbuffer_chain::next, evbuffer_chain::off, pin_release(), evbuffer_overlapped::read_in_progress, evbuffer::total_len, upcast_evbuffer(), and evbuffer_overlapped::write_in_progress.
Referenced by bev_async_consider_writing().
evbuffer_overlapped_get_fd_()
evutil_socket_t evbuffer_overlapped_get_fd_ (struct evbuffer * buf)
XXXX Document (nickm)
Definition at line 312 of file buffer_iocp.c.
{
    struct evbuffer_overlapped *buf_o = upcast_evbuffer(buf);
    return buf_o ? buf_o->fd : -1;
}
References evbuffer_overlapped::fd, and upcast_evbuffer().
Referenced by be_async_ctrl(), be_async_destruct(), bev_async_set_wsa_error(), and connect_complete().
evbuffer_overlapped_new_()
EVENT2_EXPORT_SYMBOL struct evbuffer * evbuffer_overlapped_new_ (evutil_socket_t fd)
Allocate and return a new evbuffer that supports overlapped IO on a given socket. The socket must be associated with an IO completion port using event_iocp_port_associate_.
Definition at line 153 of file buffer_iocp.c.
{
    struct evbuffer_overlapped *evo;
    evo = mm_calloc(1, sizeof(struct evbuffer_overlapped));
    if (!evo)
        return NULL;
    LIST_INIT(&evo->buffer.callbacks);
    evo->buffer.refcnt = 1;
    evo->buffer.last_with_datap = &evo->buffer.first;
    evo->buffer.is_overlapped = 1;
    evo->fd = fd;
    return &evo->buffer;
}
References evbuffer_overlapped::buffer, evbuffer_overlapped::fd, evbuffer::first, evbuffer::last_with_datap, mm_calloc, and evbuffer::refcnt.
Referenced by bufferevent_async_new_().
evbuffer_overlapped_set_fd_()
void evbuffer_overlapped_set_fd_ (struct evbuffer * buf, evutil_socket_t fd)
Definition at line 319 of file buffer_iocp.c.
{
    struct evbuffer_overlapped *buf_o = upcast_evbuffer(buf);
    EVBUFFER_LOCK(buf);
    /* XXX is this right?, should it cancel current I/O operations? */
    if (buf_o)
        buf_o->fd = fd;
    EVBUFFER_UNLOCK(buf);
}
References EVBUFFER_LOCK, EVBUFFER_UNLOCK, evbuffer_overlapped::fd, and upcast_evbuffer().
Referenced by be_async_ctrl(), and be_async_destruct().
event_base_get_iocp_()
EVENT2_EXPORT_SYMBOL struct event_iocp_port * event_base_get_iocp_ (struct event_base * base)
Definition at line 287 of file event_iocp.c.
{
#ifdef _WIN32
    return base->iocp;
#else
    return NULL;
#endif
}
Referenced by be_async_ctrl(), bufferevent_async_can_connect_(), bufferevent_async_new_(), bufferevent_socket_new(), and evconnlistener_new().
event_base_start_iocp_()
EVENT2_EXPORT_SYMBOL int event_base_start_iocp_ (struct event_base * base, int n_cpus)
Definition at line 744 of file event.c.
{
#ifdef _WIN32
    if (base->iocp)
        return 0;
    base->iocp = event_iocp_port_launch_(n_cpus);
    if (!base->iocp) {
        event_warnx("%s: Couldn't launch IOCP", __func__);
        return -1;
    }
    return 0;
#else
    return -1;
#endif
}
References __func__, event_iocp_port_launch_(), and event_warnx().
Referenced by event_base_new_with_config().
event_base_stop_iocp_()
void event_base_stop_iocp_ (struct event_base * base)
Definition at line 761 of file event.c.
{
#ifdef _WIN32
    int rv;
    if (!base->iocp)
        return;
    rv = event_iocp_shutdown_(base->iocp, -1);
    EVUTIL_ASSERT(rv >= 0);
    base->iocp = NULL;
#endif
}
References event_iocp_shutdown_(), and EVUTIL_ASSERT.
Referenced by event_base_free_().
event_iocp_activate_overlapped_()
EVENT2_EXPORT_SYMBOL int event_iocp_activate_overlapped_ (struct event_iocp_port * port, struct event_overlapped * o, ev_uintptr_t key, ev_uint32_t n_bytes)
Definition at line 276 of file event_iocp.c.
{
    BOOL r;
    r = PostQueuedCompletionStatus(port->port, n, key, &o->overlapped);
    return (r==0) ? -1 : 0;
}
event_iocp_port_associate_()
EVENT2_EXPORT_SYMBOL int event_iocp_port_associate_ (struct event_iocp_port * port, evutil_socket_t fd, ev_uintptr_t key)
Associate a file descriptor with an iocp, such that overlapped IO on the fd will happen on one of the iocp's worker threads.
Definition at line 102 of file event_iocp.c.
{
    HANDLE h;
    h = CreateIoCompletionPort((HANDLE)fd, port->port, key, port->n_threads);
    if (!h)
        return -1;
    return 0;
}
Referenced by be_async_ctrl(), and bufferevent_async_new_().
event_iocp_port_launch_()
EVENT2_EXPORT_SYMBOL struct event_iocp_port * event_iocp_port_launch_ (int n_cpus)
Create an IOCP, and launch its worker threads. Internal use only.
This interface is unstable, and will change.
Definition at line 176 of file event_iocp.c.
{
    struct event_iocp_port *port;
    int i;
    if (!extension_fns_initialized)
        init_extension_functions(&the_extension_fns);
    if (!(port = mm_calloc(1, sizeof(struct event_iocp_port))))
        return NULL;
    if (n_cpus <= 0)
        n_cpus = N_CPUS_DEFAULT;
    port->n_threads = n_cpus * 2;
    port->threads = mm_calloc(port->n_threads, sizeof(HANDLE));
    if (!port->threads)
        goto err;
    port->port = CreateIoCompletionPort(INVALID_HANDLE_VALUE, NULL, 0,
            n_cpus);
    port->ms = -1;
    if (!port->port)
        goto err;
    port->shutdownSemaphore = CreateSemaphore(NULL, 0, 1, NULL);
    if (!port->shutdownSemaphore)
        goto err;
    for (i=0; i<port->n_threads; ++i) {
        ev_uintptr_t th = _beginthread(loop, 0, port);
        if (th == (ev_uintptr_t)-1)
            goto err;
        port->threads[i] = (HANDLE)th;
        ++port->n_live_threads;
    }
    InitializeCriticalSectionAndSpinCount(&port->lock, 1000);
    return port;
err:
    if (port->port)
        CloseHandle(port->port);
    if (port->threads)
        mm_free(port->threads);
    if (port->shutdownSemaphore)
        CloseHandle(port->shutdownSemaphore);
    mm_free(port);
    return NULL;
}
References extension_fns_initialized, init_extension_functions(), loop(), mm_calloc, mm_free, N_CPUS_DEFAULT, and the_extension_fns.
Referenced by event_base_start_iocp_().
event_iocp_shutdown_()
EVENT2_EXPORT_SYMBOL int event_iocp_shutdown_ (struct event_iocp_port * port, long waitMsec)
Tell all threads serving an iocp to stop. Wait for up to waitMsec for all the threads to finish whatever they're doing. If waitMsec is -1, wait as long as required. If all the threads are done, free the port and return 0. Otherwise, return -1. If you get a -1 return value, it is safe to call this function again.
Definition at line 250 of file event_iocp.c.
{
    DWORD ms = INFINITE;
    int n;
    EnterCriticalSection(&port->lock);
    port->shutdown = 1;
    LeaveCriticalSection(&port->lock);
    event_iocp_notify_all(port);
    if (waitMsec >= 0)
        ms = waitMsec;
    WaitForSingleObject(port->shutdownSemaphore, ms);
    EnterCriticalSection(&port->lock);
    n = port->n_live_threads;
    LeaveCriticalSection(&port->lock);
    if (n == 0) {
        event_iocp_port_unlock_and_free_(port);
        return 0;
    } else {
        return -1;
    }
}
References event_iocp_notify_all(), and event_iocp_port_unlock_and_free_().
Referenced by event_base_stop_iocp_().
event_overlapped_init_()
EVENT2_EXPORT_SYMBOL void event_overlapped_init_ (struct event_overlapped * o, iocp_callback cb)
Initialize the fields in an event_overlapped.
Parameters
overlapped The struct event_overlapped to initialize
cb The callback that should be invoked once the IO operation has finished.
Definition at line 49 of file event_iocp.c.
{
    memset(o, 0, sizeof(struct event_overlapped));
    o->cb = cb;
}
References event_overlapped::cb.
Referenced by bufferevent_async_new_().