libdogecoin: src/jpeg.c File Reference
jpeg.c File Reference
#include <qr/jpeg.h>
Macros
#define JPEC_BUFFER_INIT_SIZ 65536
#define JPEC_INT_WIDTH (int)(sizeof(int) * CHAR_BIT)
#define JPEC_HUFF_NBITS(JPEC_nbits, JPEC_val)
#define JPEG_ENC_DEF_QUAL 93 /* default quality factor */
#define JPEC_ENC_HEAD_SIZ 330 /* header typical size in bytes */
#define JPEC_ENC_BLOCK_SIZ 30 /* 8x8 entropy coded block typical size in bytes */
#define JPEC_BLOCK(col, row)
Functions
jpec_buffer_t * jpec_buffer_new (void)
jpec_buffer_t * jpec_buffer_new2 (int siz)
void jpec_buffer_del (jpec_buffer_t *b)
void jpec_buffer_write_byte (jpec_buffer_t *b, int val)
void jpec_buffer_write_2bytes (jpec_buffer_t *b, int val)
static void jpec_huff_encode_block_impl (jpec_block_t *block, jpec_huff_state_t *s)
static void jpec_huff_write_bits (jpec_huff_state_t *s, unsigned int bits, int n)
void jpec_huff_skel_init (jpec_huff_skel_t *skel)
jpec_huff_t * jpec_huff_new (void)
void jpec_huff_del (jpec_huff_t *h)
void jpec_huff_encode_block (jpec_huff_t *h, jpec_block_t *block, jpec_buffer_t *buf)
static void jpec_enc_init_dqt (jpec_enc_t *e)
static void jpec_enc_open (jpec_enc_t *e)
static void jpec_enc_close (jpec_enc_t *e)
static void jpec_enc_write_soi (jpec_enc_t *e)
static void jpec_enc_write_app0 (jpec_enc_t *e)
static void jpec_enc_write_dqt (jpec_enc_t *e)
static void jpec_enc_write_sof0 (jpec_enc_t *e)
static void jpec_enc_write_dht (jpec_enc_t *e)
static void jpec_enc_write_sos (jpec_enc_t *e)
static int jpec_enc_next_block (jpec_enc_t *e)
static void jpec_enc_block_dct (jpec_enc_t *e)
static void jpec_enc_block_quant (jpec_enc_t *e)
static void jpec_enc_block_zz (jpec_enc_t *e)
jpec_enc_t * jpec_enc_new (const uint8_t *img, uint16_t w, uint16_t h)
jpec_enc_t * jpec_enc_new2 (const uint8_t *img, uint16_t w, uint16_t h, int q)
void jpec_enc_del (jpec_enc_t *e)
const uint8_t * jpec_enc_run (jpec_enc_t *e, int *len)
Variables
const uint8_t jpec_qzr [64]
const float jpec_dct [7]
const int jpec_zz [64]
const uint8_t jpec_dc_nodes [17] = { 0,0,1,5,1,1,1,1,1,1,0,0,0,0,0,0,0 }
const int jpec_dc_nb_vals = 12
const uint8_t jpec_dc_vals [12] = { 0,1,2,3,4,5,6,7,8,9,10,11 }
const uint8_t jpec_ac_nodes [17] = { 0,0,2,1,3,3,2,4,3,5,5,4,4,0,0,1,0x7d }
const int jpec_ac_nb_vals = 162
const uint8_t jpec_ac_vals [162]
const uint8_t jpec_dc_len [12] = { 2,3,3,3,3,3,4,5,6,7,8,9 }
const int jpec_dc_code [12]
const int8_t jpec_ac_len [256]
const int jpec_ac_code [256]
Macro Definition Documentation
JPEC_BLOCK
#define JPEC_BLOCK (col, row)
Value:
                            e->img[(((e->by + row) < e->h) ? e->by + row : e->h-1) * \
                            e->w + (((e->bx + col) < e->w) ? e->bx + col : e->w-1)]
JPEC_BUFFER_INIT_SIZ
#define JPEC_BUFFER_INIT_SIZ 65536
Copyright (c) 2012-2016 Moodstocks SAS
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
Definition at line 36 of file jpeg.c.
JPEC_ENC_BLOCK_SIZ
#define JPEC_ENC_BLOCK_SIZ 30 /* 8x8 entropy coded block typical size in bytes */
Definition at line 61 of file jpeg.c.
JPEC_ENC_HEAD_SIZ
#define JPEC_ENC_HEAD_SIZ 330 /* header typical size in bytes */
Definition at line 60 of file jpeg.c.
JPEC_HUFF_NBITS
#define JPEC_HUFF_NBITS (JPEC_nbits, JPEC_val)
Value:
  JPEC_nbits = 0; \
  while (val) { \
    JPEC_nbits++; \
    val >>= 1; \
  }
Definition at line 50 of file jpeg.c.
JPEC_INT_WIDTH
#define JPEC_INT_WIDTH (int)(sizeof(int) * CHAR_BIT)
Definition at line 43 of file jpeg.c.
JPEG_ENC_DEF_QUAL
#define JPEG_ENC_DEF_QUAL 93 /* default quality factor */
Definition at line 59 of file jpeg.c.
Function Documentation
jpec_buffer_del()
void jpec_buffer_del (jpec_buffer_t * b)
Definition at line 80 of file jpeg.c.
{
    assert(b);
    if (b->stream) free(b->stream);
    free(b);
}
References jpec_buffer_t_::stream.
Referenced by jpec_enc_del().
jpec_buffer_new()
jpec_buffer_t * jpec_buffer_new (void)
Definition at line 67 of file jpeg.c.
{
    return jpec_buffer_new2(-1);
}
References jpec_buffer_new2().
jpec_buffer_new2()
jpec_buffer_t * jpec_buffer_new2 (int siz)
Definition at line 71 of file jpeg.c.
{
    if (siz < 0) siz = 0;
    jpec_buffer_t* b = malloc(sizeof(*b));
    b->stream = siz > 0 ? malloc(siz) : NULL;
    b->siz = siz;
    b->len = 0;
    return b;
}
References jpec_buffer_t_::len, jpec_buffer_t_::siz, and jpec_buffer_t_::stream.
Referenced by jpec_buffer_new(), and jpec_enc_new2().
jpec_buffer_write_2bytes()
void jpec_buffer_write_2bytes (jpec_buffer_t * b, int val)
Definition at line 97 of file jpeg.c.
{
    assert(b);
    jpec_buffer_write_byte(b, (val >> 8) & 0xFF);
    jpec_buffer_write_byte(b, val & 0xFF);
}
References jpec_buffer_write_byte().
Referenced by jpec_enc_close(), jpec_enc_write_app0(), jpec_enc_write_dht(), jpec_enc_write_dqt(), jpec_enc_write_sof0(), jpec_enc_write_soi(), and jpec_enc_write_sos().
jpec_buffer_write_byte()
void jpec_buffer_write_byte (jpec_buffer_t * b, int val)
Definition at line 86 of file jpeg.c.
{
    assert(b);
    if (b->siz == b->len) {
        int nsiz = (b->siz > 0) ? 2 * b->siz : JPEC_BUFFER_INIT_SIZ;
        void* tmp = realloc(b->stream, nsiz);
        b->stream = (uint8_t*)tmp;
        b->siz = nsiz;
    }
    b->stream[b->len++] = (uint8_t)val;
}
References JPEC_BUFFER_INIT_SIZ, jpec_buffer_t_::len, jpec_buffer_t_::siz, and jpec_buffer_t_::stream.
Referenced by jpec_buffer_write_2bytes(), jpec_enc_write_app0(), jpec_enc_write_dht(), jpec_enc_write_dqt(), jpec_enc_write_sof0(), jpec_enc_write_sos(), and jpec_huff_write_bits().
jpec_enc_block_dct()
static void jpec_enc_block_dct (jpec_enc_t * e) static
Definition at line 540 of file jpeg.c.
{
    assert(e && e->bnum >= 0);
#define JPEC_BLOCK(col,row) e->img[(((e->by + row) < e->h) ? e->by + row : e->h-1) * \
                            e->w + (((e->bx + col) < e->w) ? e->bx + col : e->w-1)]
    const float* coeff = jpec_dct;
    float tmp[64];
    for (int row = 0; row < 8; row++) {
        /* NOTE: the shift by 256 allows resampling from [0 255] to [-128 127] */
        float s0 = (float)(JPEC_BLOCK(0, row) + JPEC_BLOCK(7, row) - 256);
        float s1 = (float)(JPEC_BLOCK(1, row) + JPEC_BLOCK(6, row) - 256);
        float s2 = (float)(JPEC_BLOCK(2, row) + JPEC_BLOCK(5, row) - 256);
        float s3 = (float)(JPEC_BLOCK(3, row) + JPEC_BLOCK(4, row) - 256);
        float d0 = (float)(JPEC_BLOCK(0, row) - JPEC_BLOCK(7, row));
        float d1 = (float)(JPEC_BLOCK(1, row) - JPEC_BLOCK(6, row));
        float d2 = (float)(JPEC_BLOCK(2, row) - JPEC_BLOCK(5, row));
        float d3 = (float)(JPEC_BLOCK(3, row) - JPEC_BLOCK(4, row));
        tmp[8 * row] = coeff[3] * (s0 + s1 + s2 + s3);
        tmp[8 * row + 1] = coeff[0] * d0 + coeff[2] * d1 + coeff[4] * d2 + coeff[6] * d3;
        tmp[8 * row + 2] = coeff[1] * (s0 - s3) + coeff[5] * (s1 - s2);
        tmp[8 * row + 3] = coeff[2] * d0 - coeff[6] * d1 - coeff[0] * d2 - coeff[4] * d3;
        tmp[8 * row + 4] = coeff[3] * (s0 - s1 - s2 + s3);
        tmp[8 * row + 5] = coeff[4] * d0 - coeff[0] * d1 + coeff[6] * d2 + coeff[2] * d3;
        tmp[8 * row + 6] = coeff[5] * (s0 - s3) + coeff[1] * (s2 - s1);
        tmp[8 * row + 7] = coeff[6] * d0 - coeff[4] * d1 + coeff[2] * d2 - coeff[0] * d3;
    }
    for (int col = 0; col < 8; col++) {
        float s0 = tmp[col] + tmp[56 + col];
        float s1 = tmp[8 + col] + tmp[48 + col];
        float s2 = tmp[16 + col] + tmp[40 + col];
        float s3 = tmp[24 + col] + tmp[32 + col];
        float d0 = tmp[col] - tmp[56 + col];
        float d1 = tmp[8 + col] - tmp[48 + col];
        float d2 = tmp[16 + col] - tmp[40 + col];
        float d3 = tmp[24 + col] - tmp[32 + col];
        e->block.dct[col] = coeff[3] * (s0 + s1 + s2 + s3);
        e->block.dct[8 + col] = coeff[0] * d0 + coeff[2] * d1 + coeff[4] * d2 + coeff[6] * d3;
        e->block.dct[16 + col] = coeff[1] * (s0 - s3) + coeff[5] * (s1 - s2);
        e->block.dct[24 + col] = coeff[2] * d0 - coeff[6] * d1 - coeff[0] * d2 - coeff[4] * d3;
        e->block.dct[32 + col] = coeff[3] * (s0 - s1 - s2 + s3);
        e->block.dct[40 + col] = coeff[4] * d0 - coeff[0] * d1 + coeff[6] * d2 + coeff[2] * d3;
        e->block.dct[48 + col] = coeff[5] * (s0 - s3) + coeff[1] * (s2 - s1);
        e->block.dct[56 + col] = coeff[6] * d0 - coeff[4] * d1 + coeff[2] * d2 - coeff[0] * d3;
    }
#undef JPEC_BLOCK
}
References jpec_enc_t_::block, jpec_enc_t_::bnum, jpec_block_t_::dct, JPEC_BLOCK, and jpec_dct.
Referenced by jpec_enc_run().
jpec_enc_block_quant()
static void jpec_enc_block_quant (jpec_enc_t * e) static
Definition at line 590 of file jpeg.c.
{
    assert(e && e->bnum >= 0);
    for (int i = 0; i < 64; i++) {
        e->block.quant[i] = (int)(e->block.dct[i] / e->dqt[i]);
    }
}
References jpec_enc_t_::block, jpec_enc_t_::bnum, jpec_block_t_::dct, jpec_enc_t_::dqt, and jpec_block_t_::quant.
Referenced by jpec_enc_run().
jpec_enc_block_zz()
static void jpec_enc_block_zz (jpec_enc_t * e) static
Definition at line 597 of file jpeg.c.
{
    assert(e && e->bnum >= 0);
    e->block.len = 0;
    for (int i = 0; i < 64; i++) {
        if ((e->block.zz[i] = e->block.quant[jpec_zz[i]])) e->block.len = i + 1;
    }
}
References jpec_enc_t_::block, jpec_enc_t_::bnum, jpec_zz, jpec_block_t_::len, jpec_block_t_::quant, and jpec_block_t_::zz.
Referenced by jpec_enc_run().
jpec_enc_close()
static void jpec_enc_close (jpec_enc_t * e) static
Definition at line 444 of file jpeg.c.
{
    assert(e);
    e->hskel->del(e->hskel->opq);
    jpec_buffer_write_2bytes(e->buf, 0xFFD9); /* EOI marker */
}
References jpec_enc_t_::buf, jpec_huff_skel_t_::del, jpec_enc_t_::hskel, jpec_buffer_write_2bytes(), and jpec_huff_skel_t_::opq.
Referenced by jpec_enc_run().
jpec_enc_del()
void jpec_enc_del (jpec_enc_t * e)
Definition at line 399 of file jpeg.c.
{
    assert(e);
    if (e->buf) jpec_buffer_del(e->buf);
    free(e->hskel);
    free(e);
}
References jpec_enc_t_::buf, jpec_enc_t_::hskel, and jpec_buffer_del().
Referenced by qrgen_string_to_qr_jpgfile().
jpec_enc_init_dqt()
static void jpec_enc_init_dqt (jpec_enc_t * e) static
Definition at line 421 of file jpeg.c.
{
    assert(e);
    float qualf = (float)e->qual;
    float scale = (e->qual < 50) ? (50 / qualf) : (2 - qualf / 50);
    for (int i = 0; i < 64; i++) {
        int a = (int)((float)jpec_qzr[i] * scale + 0.5);
        a = (a < 1) ? 1 : ((a > 255) ? 255 : a);
        e->dqt[i] = a;
    }
}
References jpec_enc_t_::dqt, jpec_qzr, and jpec_enc_t_::qual.
Referenced by jpec_enc_open().
jpec_enc_new()
jpec_enc_t * jpec_enc_new (const uint8_t * img, uint16_t w, uint16_t h)
Definition at line 374 of file jpeg.c.
{
    return jpec_enc_new2(img, w, h, JPEG_ENC_DEF_QUAL);
}
References jpec_enc_new2(), and JPEG_ENC_DEF_QUAL.
Referenced by qrgen_string_to_qr_jpgfile().
jpec_enc_new2()
jpec_enc_t * jpec_enc_new2 (const uint8_t * img, uint16_t w, uint16_t h, int q)
Definition at line 378 of file jpeg.c.
{
    if (img && w > 0 && !(w & 0x7) && h > 0 && !(h & 0x7))
    {
                printf("width and height assert failed\n");
    }
    jpec_enc_t* e = malloc(sizeof(*e));
    e->img = img;
    e->w = w;
    e->w8 = (((w - 1) >> 3) + 1) << 3;
    e->h = h;
    e->qual = q;
    e->bmax = (((w - 1) >> 3) + 1) * (((h - 1) >> 3) + 1);
    e->bnum = -1;
    e->bx = -1;
    e->by = -1;
    int bsiz = JPEC_ENC_HEAD_SIZ + e->bmax * JPEC_ENC_BLOCK_SIZ;
    e->buf = jpec_buffer_new2(bsiz);
    e->hskel = malloc(sizeof(*e->hskel));
    return e;
}
References jpec_enc_t_::bmax, jpec_enc_t_::bnum, jpec_enc_t_::buf, jpec_enc_t_::bx, jpec_enc_t_::by, jpec_enc_t_::h, jpec_enc_t_::hskel, jpec_enc_t_::img, jpec_buffer_new2(), JPEC_ENC_BLOCK_SIZ, JPEC_ENC_HEAD_SIZ, jpec_enc_t_::qual, jpec_enc_t_::w, and jpec_enc_t_::w8.
Referenced by jpec_enc_new().
jpec_enc_next_block()
static int jpec_enc_next_block (jpec_enc_t * e) static
Definition at line 530 of file jpeg.c.
{
    assert(e);
    int rv = (++e->bnum >= e->bmax) ? 0 : 1;
    if (rv) {
        e->bx = (e->bnum << 3) % e->w8;
        e->by = ((e->bnum << 3) / e->w8) << 3;
    }
    return rv;
}
References jpec_enc_t_::bmax, jpec_enc_t_::bnum, jpec_enc_t_::bx, jpec_enc_t_::by, and jpec_enc_t_::w8.
Referenced by jpec_enc_run().
jpec_enc_open()
static void jpec_enc_open (jpec_enc_t * e) static
Definition at line 432 of file jpeg.c.
{
    assert(e);
    jpec_huff_skel_init(e->hskel);
    jpec_enc_init_dqt(e);
    jpec_enc_write_soi(e);
    jpec_enc_write_app0(e);
    jpec_enc_write_dqt(e);
    jpec_enc_write_sof0(e);
    jpec_enc_write_dht(e);
    jpec_enc_write_sos(e);
}
References jpec_enc_t_::hskel, jpec_enc_init_dqt(), jpec_enc_write_app0(), jpec_enc_write_dht(), jpec_enc_write_dqt(), jpec_enc_write_sof0(), jpec_enc_write_soi(), jpec_enc_write_sos(), and jpec_huff_skel_init().
Referenced by jpec_enc_run().
jpec_enc_run()
const uint8_t * jpec_enc_run (jpec_enc_t * e, int * len)
Definition at line 406 of file jpeg.c.
{
    assert(e && len);
    jpec_enc_open(e);
    while (jpec_enc_next_block(e)) {
        jpec_enc_block_dct(e);
        jpec_enc_block_quant(e);
        jpec_enc_block_zz(e);
        e->hskel->encode_block(e->hskel->opq, &e->block, e->buf);
    }
    jpec_enc_close(e);
    *len = e->buf->len;
    return e->buf->stream;
}
References jpec_enc_t_::block, jpec_enc_t_::buf, jpec_huff_skel_t_::encode_block, jpec_enc_t_::hskel, jpec_enc_block_dct(), jpec_enc_block_quant(), jpec_enc_block_zz(), jpec_enc_close(), jpec_enc_next_block(), jpec_enc_open(), jpec_buffer_t_::len, jpec_huff_skel_t_::opq, and jpec_buffer_t_::stream.
Referenced by qrgen_string_to_qr_jpgfile().
jpec_enc_write_app0()
static void jpec_enc_write_app0 (jpec_enc_t * e) static
Definition at line 455 of file jpeg.c.
{
    assert(e);
    jpec_buffer_write_2bytes(e->buf, 0xFFE0); /* APP0 marker */
    jpec_buffer_write_2bytes(e->buf, 0x0010); /* segment length */
    jpec_buffer_write_byte(e->buf, 0x4A);     /* 'J' */
    jpec_buffer_write_byte(e->buf, 0x46);     /* 'F' */
    jpec_buffer_write_byte(e->buf, 0x49);     /* 'I' */
    jpec_buffer_write_byte(e->buf, 0x46);     /* 'F' */
    jpec_buffer_write_byte(e->buf, 0x00);     /* '\0' */
    jpec_buffer_write_2bytes(e->buf, 0x0101); /* v1.1 */
    jpec_buffer_write_byte(e->buf, 0x00);     /* no density unit */
    jpec_buffer_write_2bytes(e->buf, 0x0001); /* X density = 1 */
    jpec_buffer_write_2bytes(e->buf, 0x0001); /* Y density = 1 */
    jpec_buffer_write_byte(e->buf, 0x00);     /* thumbnail width = 0 */
    jpec_buffer_write_byte(e->buf, 0x00);     /* thumbnail height = 0 */
}
References jpec_enc_t_::buf, jpec_buffer_write_2bytes(), and jpec_buffer_write_byte().
Referenced by jpec_enc_open().
jpec_enc_write_dht()
static void jpec_enc_write_dht (jpec_enc_t * e) static
Definition at line 495 of file jpeg.c.
{
    assert(e);
    jpec_buffer_write_2bytes(e->buf, 0xFFC4);          /* DHT marker */
    jpec_buffer_write_2bytes(e->buf, 19 + jpec_dc_nb_vals); /* segment length */
    jpec_buffer_write_byte(e->buf, 0x00);              /* table 0 (DC), type 0 (0 = Y, 1 = UV) */
    for (int i = 0; i < 16; i++) {
        jpec_buffer_write_byte(e->buf, jpec_dc_nodes[i + 1]);
    }
    for (int i = 0; i < jpec_dc_nb_vals; i++) {
        jpec_buffer_write_byte(e->buf, jpec_dc_vals[i]);
    }
    jpec_buffer_write_2bytes(e->buf, 0xFFC4);           /* DHT marker */
    jpec_buffer_write_2bytes(e->buf, 19 + jpec_ac_nb_vals);
    jpec_buffer_write_byte(e->buf, 0x10);               /* table 1 (AC), type 0 (0 = Y, 1 = UV) */
    for (int i = 0; i < 16; i++) {
        jpec_buffer_write_byte(e->buf, jpec_ac_nodes[i + 1]);
    }
    for (int i = 0; i < jpec_ac_nb_vals; i++) {
        jpec_buffer_write_byte(e->buf, jpec_ac_vals[i]);
    }
}
References jpec_enc_t_::buf, jpec_ac_nb_vals, jpec_ac_nodes, jpec_ac_vals, jpec_buffer_write_2bytes(), jpec_buffer_write_byte(), jpec_dc_nb_vals, jpec_dc_nodes, and jpec_dc_vals.
Referenced by jpec_enc_open().
jpec_enc_write_dqt()
static void jpec_enc_write_dqt (jpec_enc_t * e) static
Definition at line 472 of file jpeg.c.
{
    assert(e);
    jpec_buffer_write_2bytes(e->buf, 0xFFDB); /* DQT marker */
    jpec_buffer_write_2bytes(e->buf, 0x0043); /* segment length */
    jpec_buffer_write_byte(e->buf, 0x00);     /* table 0, 8-bit precision (0) */
    for (int i = 0; i < 64; i++) {
        jpec_buffer_write_byte(e->buf, e->dqt[jpec_zz[i]]);
    }
}
References jpec_enc_t_::buf, jpec_enc_t_::dqt, jpec_buffer_write_2bytes(), jpec_buffer_write_byte(), and jpec_zz.
Referenced by jpec_enc_open().
jpec_enc_write_sof0()
static void jpec_enc_write_sof0 (jpec_enc_t * e) static
Definition at line 482 of file jpeg.c.
{
    assert(e);
    jpec_buffer_write_2bytes(e->buf, 0xFFC0); /* SOF0 marker */
    jpec_buffer_write_2bytes(e->buf, 0x000B); /* segment length */
    jpec_buffer_write_byte(e->buf, 0x08);     /* 8-bit precision */
    jpec_buffer_write_2bytes(e->buf, e->h);
    jpec_buffer_write_2bytes(e->buf, e->w);
    jpec_buffer_write_byte(e->buf, 0x01);     /* 1 component only (grayscale) */
    jpec_buffer_write_byte(e->buf, 0x01);     /* component ID = 1 */
    jpec_buffer_write_byte(e->buf, 0x11);     /* no subsampling */
    jpec_buffer_write_byte(e->buf, 0x00);     /* quantization table 0 */
}
References jpec_enc_t_::buf, jpec_enc_t_::h, jpec_buffer_write_2bytes(), jpec_buffer_write_byte(), and jpec_enc_t_::w.
Referenced by jpec_enc_open().
jpec_enc_write_soi()
static void jpec_enc_write_soi (jpec_enc_t * e) static
Definition at line 450 of file jpeg.c.
{
    assert(e);
    jpec_buffer_write_2bytes(e->buf, 0xFFD8); /* SOI marker */
}
References jpec_enc_t_::buf, and jpec_buffer_write_2bytes().
Referenced by jpec_enc_open().
jpec_enc_write_sos()
static void jpec_enc_write_sos (jpec_enc_t * e) static
Definition at line 517 of file jpeg.c.
{
    assert(e);
    jpec_buffer_write_2bytes(e->buf, 0xFFDA); /* SOS marker */
    jpec_buffer_write_2bytes(e->buf, 8);      /* segment length */
    jpec_buffer_write_byte(e->buf, 0x01);     /* nb. components */
    jpec_buffer_write_byte(e->buf, 0x01);     /* Y component ID */
    jpec_buffer_write_byte(e->buf, 0x00);     /* Y HT = 0 */
    /* segment end */
    jpec_buffer_write_byte(e->buf, 0x00);
    jpec_buffer_write_byte(e->buf, 0x3F);
    jpec_buffer_write_byte(e->buf, 0x00);
}
References jpec_enc_t_::buf, jpec_buffer_write_2bytes(), and jpec_buffer_write_byte().
Referenced by jpec_enc_open().
jpec_huff_del()
void jpec_huff_del (jpec_huff_t * h)
Definition at line 127 of file jpeg.c.
{
    assert(h);
    /* Flush any remaining bits and fill in the incomple byte (if any) with 1-s */
    jpec_huff_write_bits(&h->state, 0x7F, 7);
    free(h);
}
References jpec_huff_write_bits(), and jpec_huff_t_::state.
Referenced by jpec_huff_skel_init().
jpec_huff_encode_block()
void jpec_huff_encode_block (jpec_huff_t * h, jpec_block_t * block, jpec_buffer_t * buf)
Definition at line 134 of file jpeg.c.
{
    assert(h && block && buf);
    jpec_huff_state_t state;
    state.buffer = h->state.buffer;
    state.nbits = h->state.nbits;
    state.dc = h->state.dc;
    state.buf = buf;
    jpec_huff_encode_block_impl(block, &state);
    h->state.buffer = state.buffer;
    h->state.nbits = state.nbits;
    h->state.dc = state.dc;
    h->state.buf = state.buf;
}
References jpec_huff_state_t_::buf, jpec_huff_state_t_::buffer, jpec_huff_state_t_::dc, jpec_huff_encode_block_impl(), jpec_huff_state_t_::nbits, and jpec_huff_t_::state.
Referenced by jpec_huff_skel_init().
jpec_huff_encode_block_impl()
static void jpec_huff_encode_block_impl (jpec_block_t * block, jpec_huff_state_t * s) static
Definition at line 148 of file jpeg.c.
{
    assert(block && s);
    int val, bits, nbits;
    /* DC coefficient encoding */
    if (block->len > 0) {
        val = block->zz[0] - s->dc;
        s->dc = block->zz[0];
    }
    else {
        val = -s->dc;
        s->dc = 0;
    }
    bits = val;
    if (val < 0) {
        val = -val;
        bits = ~val;
    }
    JPEC_HUFF_NBITS(nbits, val);
    jpec_huff_write_bits(s, jpec_dc_code[nbits], jpec_dc_len[nbits]);
    if (nbits) jpec_huff_write_bits(s, (unsigned int)bits, nbits);
    /* AC coefficients encoding (w/ RLE of zeros) */
    int nz = 0;
    for (int i = 1; i < block->len; i++) {
        if ((val = block->zz[i]) == 0) nz++;
        else {
            while (nz >= 16) {
                jpec_huff_write_bits(s, jpec_ac_code[0xF0], jpec_ac_len[0xF0]); /* ZRL code */
                nz -= 16;
            }
            bits = val;
            if (val < 0) {
                val = -val;
                bits = ~val;
            }
            JPEC_HUFF_NBITS(nbits, val);
            int j = (nz << 4) + nbits;
            jpec_huff_write_bits(s, jpec_ac_code[j], jpec_ac_len[j]);
            if (nbits) jpec_huff_write_bits(s, (unsigned int)bits, nbits);
            nz = 0;
        }
    }
    if (block->len < 64) {
        jpec_huff_write_bits(s, jpec_ac_code[0x00], jpec_ac_len[0x00]); /* EOB marker */
    }
}
References jpec_huff_state_t_::dc, jpec_ac_code, jpec_ac_len, jpec_dc_code, jpec_dc_len, JPEC_HUFF_NBITS, jpec_huff_write_bits(), jpec_block_t_::len, and jpec_block_t_::zz.
Referenced by jpec_huff_encode_block().
jpec_huff_new()
jpec_huff_t * jpec_huff_new (void)
Definition at line 118 of file jpeg.c.
{
    jpec_huff_t* h = malloc(sizeof(*h));
    h->state.buffer = 0;
    h->state.nbits = 0;
    h->state.dc = 0;
    h->state.buf = NULL;
    return h;
}
References jpec_huff_state_t_::buf, jpec_huff_state_t_::buffer, jpec_huff_state_t_::dc, jpec_huff_state_t_::nbits, and jpec_huff_t_::state.
Referenced by jpec_huff_skel_init().
jpec_huff_skel_init()
void jpec_huff_skel_init (jpec_huff_skel_t * skel)
Skeleton initialization
Definition at line 110 of file jpeg.c.
{
    assert(skel);
    memset(skel, 0, sizeof(*skel));
    skel->opq = jpec_huff_new();
    skel->del = (void (*)(void*))jpec_huff_del;
    skel->encode_block = (void (*)(void*, jpec_block_t*, jpec_buffer_t*))jpec_huff_encode_block;
}
References jpec_huff_skel_t_::del, jpec_huff_skel_t_::encode_block, jpec_huff_del(), jpec_huff_encode_block(), jpec_huff_new(), and jpec_huff_skel_t_::opq.
Referenced by jpec_enc_open().
jpec_huff_write_bits()
static void jpec_huff_write_bits (jpec_huff_state_t * s, unsigned int bits, int n) static
Definition at line 208 of file jpeg.c.
{
    assert(s && n > 0 && n <= 16);
    int32_t mask = (((int32_t)1) << n) - 1;
    int32_t buffer = (int32_t)bits;
    int nbits = s->nbits + n;
    buffer &= mask;
    buffer <<= 24 - nbits;
    buffer |= s->buffer;
    while (nbits >= 8) {
        int chunk = (int)((buffer >> 16) & 0xFF);
        jpec_buffer_write_byte(s->buf, chunk);
        if (chunk == 0xFF) jpec_buffer_write_byte(s->buf, 0x00);
        buffer <<= 8;
        nbits -= 8;
    }
    s->buffer = buffer;
    s->nbits = nbits;
}
References jpec_huff_state_t_::buf, jpec_huff_state_t_::buffer, jpec_buffer_write_byte(), and jpec_huff_state_t_::nbits.
Referenced by jpec_huff_del(), and jpec_huff_encode_block_impl().
Variable Documentation
jpec_ac_code
const int jpec_ac_code[256]
Definition at line 321 of file jpeg.c.
Referenced by jpec_huff_encode_block_impl().
jpec_ac_len
const int8_t jpec_ac_len[256]
Luminance (Y) - AC
Definition at line 287 of file jpeg.c.
Referenced by jpec_huff_encode_block_impl().
jpec_ac_nb_vals
const int jpec_ac_nb_vals = 162
Definition at line 258 of file jpeg.c.
Referenced by jpec_enc_write_dht().
jpec_ac_nodes
const uint8_t jpec_ac_nodes[17] = { 0,0,2,1,3,3,2,4,3,5,5,4,4,0,0,1,0x7d }
Luminance (Y) - AC
Definition at line 257 of file jpeg.c.
Referenced by jpec_enc_write_dht().
jpec_ac_vals
const uint8_t jpec_ac_vals[162]
Initial value:
= {
    0x01,0x02,0x03,0x00,0x04,0x11,0x05,0x12,
    0x21,0x31,0x41,0x06,0x13,0x51,0x61,0x07,
    0x22,0x71,0x14,0x32,0x81,0x91,0xa1,0x08,
    0x23,0x42,0xb1,0xc1,0x15,0x52,0xd1,0xf0,
    0x24,0x33,0x62,0x72,0x82,0x09,0x0a,0x16,
    0x17,0x18,0x19,0x1a,0x25,0x26,0x27,0x28,
    0x29,0x2a,0x34,0x35,0x36,0x37,0x38,0x39,
    0x3a,0x43,0x44,0x45,0x46,0x47,0x48,0x49,
    0x4a,0x53,0x54,0x55,0x56,0x57,0x58,0x59,
    0x5a,0x63,0x64,0x65,0x66,0x67,0x68,0x69,
    0x6a,0x73,0x74,0x75,0x76,0x77,0x78,0x79,
    0x7a,0x83,0x84,0x85,0x86,0x87,0x88,0x89,
    0x8a,0x92,0x93,0x94,0x95,0x96,0x97,0x98,
    0x99,0x9a,0xa2,0xa3,0xa4,0xa5,0xa6,0xa7,
    0xa8,0xa9,0xaa,0xb2,0xb3,0xb4,0xb5,0xb6,
    0xb7,0xb8,0xb9,0xba,0xc2,0xc3,0xc4,0xc5,
    0xc6,0xc7,0xc8,0xc9,0xca,0xd2,0xd3,0xd4,
    0xd5,0xd6,0xd7,0xd8,0xd9,0xda,0xe1,0xe2,
    0xe3,0xe4,0xe5,0xe6,0xe7,0xe8,0xe9,0xea,
    0xf1,0xf2,0xf3,0xf4,0xf5,0xf6,0xf7,0xf8,
    0xf9,0xfa }
Definition at line 259 of file jpeg.c.
Referenced by jpec_enc_write_dht().
jpec_dc_code
const int jpec_dc_code[12]
Initial value:
= {
    0x000,0x002,0x003,0x004,0x005,0x006,
    0x00e,0x01e,0x03e,0x07e,0x0fe,0x1fe }
Definition at line 283 of file jpeg.c.
Referenced by jpec_huff_encode_block_impl().
jpec_dc_len
const uint8_t jpec_dc_len[12] = { 2,3,3,3,3,3,4,5,6,7,8,9 }
Huffman inverted tables Luminance (Y) - DC
Definition at line 282 of file jpeg.c.
Referenced by jpec_huff_encode_block_impl().
jpec_dc_nb_vals
const int jpec_dc_nb_vals = 12
Definition at line 254 of file jpeg.c.
Referenced by jpec_enc_write_dht().
jpec_dc_nodes
const uint8_t jpec_dc_nodes[17] = { 0,0,1,5,1,1,1,1,1,1,0,0,0,0,0,0,0 }
JPEG standard Huffman tables Luminance (Y) - DC
Definition at line 253 of file jpeg.c.
Referenced by jpec_enc_write_dht().
jpec_dc_vals
const uint8_t jpec_dc_vals[12] = { 0,1,2,3,4,5,6,7,8,9,10,11 }
Definition at line 255 of file jpeg.c.
Referenced by jpec_enc_write_dht().
jpec_dct
const float jpec_dct[7]
Initial value:
= {
    0.49039, 0.46194, 0.41573, 0.35355,
    0.27779, 0.19134, 0.09755 }
DCT coefficients
Definition at line 239 of file jpeg.c.
Referenced by jpec_enc_block_dct().
jpec_qzr
const uint8_t jpec_qzr[64]
Initial value:
= {
    16, 11, 10, 16, 24, 40, 51, 61,
    12, 12, 14, 19, 26, 58, 60, 55,
    14, 13, 16, 24, 40, 57, 69, 56,
    14, 17, 22, 29, 51, 87, 80, 62,
    18, 22, 37, 56, 68,109,103, 77,
    24, 35, 55, 64, 81,104,113, 92,
    49, 64, 78, 87,103,121,120,101,
    72, 92, 95, 98,112,100,103, 99 }
Standard JPEG quantizing table
Definition at line 229 of file jpeg.c.
Referenced by jpec_enc_init_dqt().
jpec_zz
const int jpec_zz[64]
Initial value:
= {
     0,  1,  8, 16,  9,  2,  3, 10,
    17, 24, 32, 25, 18, 11,  4,  5,
    12, 19, 26, 33, 40, 48, 41, 34,
    27, 20, 13,  6,  7, 14, 21, 28,
    35, 42, 49, 56, 57, 50, 43, 36,
    29, 22, 15, 23, 30, 37, 44, 51,
    58, 59, 52, 45, 38, 31, 39, 46,
    53, 60, 61, 54, 47, 55, 62, 63 }
Zig-zag order
Definition at line 243 of file jpeg.c.
Referenced by jpec_enc_block_zz(), and jpec_enc_write_dqt().