libdogecoin: include/qr/jpeg.h File Reference
jpeg.h File Reference
#include <stdint.h>
#include <assert.h>
#include <ctype.h>
#include <float.h>
#include <limits.h>
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
Data Structures
struct jpec_buffer_t_
struct jpec_block_t_
struct jpec_huff_skel_t_
struct jpec_enc_t_
struct jpec_huff_state_t_
struct jpec_huff_t_
Typedefs
typedef struct jpec_enc_t_ jpec_enc_t
typedef struct jpec_buffer_t_ jpec_buffer_t
typedef struct jpec_block_t_ jpec_block_t
typedef struct jpec_huff_skel_t_ jpec_huff_skel_t
typedef struct jpec_huff_state_t_ jpec_huff_state_t
typedef struct jpec_huff_t_ jpec_huff_t
Functions
jpec_enc_t * jpec_enc_new (const uint8_t *img, uint16_t w, uint16_t h)
jpec_enc_t * jpec_enc_new2 (const uint8_t *img, uint16_t w, uint16_t h, int q)
void jpec_enc_del (jpec_enc_t *e)
const uint8_t * jpec_enc_run (jpec_enc_t *e, int *len)
jpec_buffer_t * jpec_buffer_new (void)
jpec_buffer_t * jpec_buffer_new2 (int siz)
void jpec_buffer_del (jpec_buffer_t *b)
void jpec_buffer_write_byte (jpec_buffer_t *b, int val)
void jpec_buffer_write_2bytes (jpec_buffer_t *b, int val)
void jpec_huff_skel_init (jpec_huff_skel_t *skel)
jpec_huff_t * jpec_huff_new (void)
void jpec_huff_del (jpec_huff_t *h)
void jpec_huff_encode_block (jpec_huff_t *h, jpec_block_t *block, jpec_buffer_t *buf)
Variables
const uint8_t jpec_qzr [64]
const float jpec_dct [7]
const int jpec_zz [64]
const uint8_t jpec_dc_nodes [17]
const int jpec_dc_nb_vals
const uint8_t jpec_dc_vals [12]
const uint8_t jpec_ac_nodes [17]
const int jpec_ac_nb_vals
const uint8_t jpec_ac_vals [162]
const uint8_t jpec_dc_len [12]
const int jpec_dc_code [12]
const int8_t jpec_ac_len [256]
const int jpec_ac_code [256]
Typedef Documentation
jpec_block_t
typedef struct jpec_block_t_ jpec_block_t
Structure used to hold and process an image 8x8 block
jpec_buffer_t
typedef struct jpec_buffer_t_ jpec_buffer_t
Extensible byte buffer
jpec_enc_t
typedef struct jpec_enc_t_ jpec_enc_t
Copyright (c) 2012-2016 Moodstocks SAS
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE. Type of a JPEG encoder object
Definition at line 48 of file jpeg.h.
jpec_huff_skel_t
typedef struct jpec_huff_skel_t_ jpec_huff_skel_t
Skeleton for an Huffman entropy coder
jpec_huff_state_t
typedef struct jpec_huff_state_t_ jpec_huff_state_t
Entropy coding data that hold state along blocks
jpec_huff_t
typedef struct jpec_huff_t_ jpec_huff_t
Type of an Huffman JPEG encoder
Function Documentation
jpec_buffer_del()
void jpec_buffer_del (jpec_buffer_t * b)
Definition at line 80 of file jpeg.c.
{
    assert(b);
    if (b->stream) free(b->stream);
    free(b);
}
References jpec_buffer_t_::stream.
Referenced by jpec_enc_del().
jpec_buffer_new()
jpec_buffer_t * jpec_buffer_new (void)
Definition at line 67 of file jpeg.c.
{
    return jpec_buffer_new2(-1);
}
References jpec_buffer_new2().
jpec_buffer_new2()
jpec_buffer_t * jpec_buffer_new2 (int siz)
Definition at line 71 of file jpeg.c.
{
    if (siz < 0) siz = 0;
    jpec_buffer_t* b = malloc(sizeof(*b));
    b->stream = siz > 0 ? malloc(siz) : NULL;
    b->siz = siz;
    b->len = 0;
    return b;
}
References jpec_buffer_t_::len, jpec_buffer_t_::siz, and jpec_buffer_t_::stream.
Referenced by jpec_buffer_new(), and jpec_enc_new2().
jpec_buffer_write_2bytes()
void jpec_buffer_write_2bytes (jpec_buffer_t * b, int val)
Definition at line 97 of file jpeg.c.
{
    assert(b);
    jpec_buffer_write_byte(b, (val >> 8) & 0xFF);
    jpec_buffer_write_byte(b, val & 0xFF);
}
References jpec_buffer_write_byte().
Referenced by jpec_enc_close(), jpec_enc_write_app0(), jpec_enc_write_dht(), jpec_enc_write_dqt(), jpec_enc_write_sof0(), jpec_enc_write_soi(), and jpec_enc_write_sos().
jpec_buffer_write_byte()
void jpec_buffer_write_byte (jpec_buffer_t * b, int val)
Definition at line 86 of file jpeg.c.
{
    assert(b);
    if (b->siz == b->len) {
        int nsiz = (b->siz > 0) ? 2 * b->siz : JPEC_BUFFER_INIT_SIZ;
        void* tmp = realloc(b->stream, nsiz);
        b->stream = (uint8_t*)tmp;
        b->siz = nsiz;
    }
    b->stream[b->len++] = (uint8_t)val;
}
References JPEC_BUFFER_INIT_SIZ, jpec_buffer_t_::len, jpec_buffer_t_::siz, and jpec_buffer_t_::stream.
Referenced by jpec_buffer_write_2bytes(), jpec_enc_write_app0(), jpec_enc_write_dht(), jpec_enc_write_dqt(), jpec_enc_write_sof0(), jpec_enc_write_sos(), and jpec_huff_write_bits().
jpec_enc_del()
void jpec_enc_del (jpec_enc_t * e)
Definition at line 399 of file jpeg.c.
{
    assert(e);
    if (e->buf) jpec_buffer_del(e->buf);
    free(e->hskel);
    free(e);
}
References jpec_enc_t_::buf, jpec_enc_t_::hskel, and jpec_buffer_del().
Referenced by qrgen_string_to_qr_jpgfile().
jpec_enc_new()
jpec_enc_t * jpec_enc_new (const uint8_t * img, uint16_t w, uint16_t h)
Definition at line 374 of file jpeg.c.
{
    return jpec_enc_new2(img, w, h, JPEG_ENC_DEF_QUAL);
}
References jpec_enc_new2(), and JPEG_ENC_DEF_QUAL.
Referenced by qrgen_string_to_qr_jpgfile().
jpec_enc_new2()
jpec_enc_t * jpec_enc_new2 (const uint8_t * img, uint16_t w, uint16_t h, int q)
Definition at line 378 of file jpeg.c.
{
    if (img && w > 0 && !(w & 0x7) && h > 0 && !(h & 0x7))
    {
                printf("width and height assert failed\n");
    }
    jpec_enc_t* e = malloc(sizeof(*e));
    e->img = img;
    e->w = w;
    e->w8 = (((w - 1) >> 3) + 1) << 3;
    e->h = h;
    e->qual = q;
    e->bmax = (((w - 1) >> 3) + 1) * (((h - 1) >> 3) + 1);
    e->bnum = -1;
    e->bx = -1;
    e->by = -1;
    int bsiz = JPEC_ENC_HEAD_SIZ + e->bmax * JPEC_ENC_BLOCK_SIZ;
    e->buf = jpec_buffer_new2(bsiz);
    e->hskel = malloc(sizeof(*e->hskel));
    return e;
}
References jpec_enc_t_::bmax, jpec_enc_t_::bnum, jpec_enc_t_::buf, jpec_enc_t_::bx, jpec_enc_t_::by, jpec_enc_t_::h, jpec_enc_t_::hskel, jpec_enc_t_::img, jpec_buffer_new2(), JPEC_ENC_BLOCK_SIZ, JPEC_ENC_HEAD_SIZ, jpec_enc_t_::qual, jpec_enc_t_::w, and jpec_enc_t_::w8.
Referenced by jpec_enc_new().
jpec_enc_run()
const uint8_t * jpec_enc_run (jpec_enc_t * e, int * len)
Definition at line 406 of file jpeg.c.
{
    assert(e && len);
    jpec_enc_open(e);
    while (jpec_enc_next_block(e)) {
        jpec_enc_block_dct(e);
        jpec_enc_block_quant(e);
        jpec_enc_block_zz(e);
        e->hskel->encode_block(e->hskel->opq, &e->block, e->buf);
    }
    jpec_enc_close(e);
    *len = e->buf->len;
    return e->buf->stream;
}
References jpec_enc_t_::block, jpec_enc_t_::buf, jpec_huff_skel_t_::encode_block, jpec_enc_t_::hskel, jpec_enc_block_dct(), jpec_enc_block_quant(), jpec_enc_block_zz(), jpec_enc_close(), jpec_enc_next_block(), jpec_enc_open(), jpec_buffer_t_::len, jpec_huff_skel_t_::opq, and jpec_buffer_t_::stream.
Referenced by qrgen_string_to_qr_jpgfile().
jpec_huff_del()
void jpec_huff_del (jpec_huff_t * h)
Definition at line 127 of file jpeg.c.
{
    assert(h);
    /* Flush any remaining bits and fill in the incomple byte (if any) with 1-s */
    jpec_huff_write_bits(&h->state, 0x7F, 7);
    free(h);
}
References jpec_huff_write_bits(), and jpec_huff_t_::state.
Referenced by jpec_huff_skel_init().
jpec_huff_encode_block()
void jpec_huff_encode_block (jpec_huff_t * h, jpec_block_t * block, jpec_buffer_t * buf)
Definition at line 134 of file jpeg.c.
{
    assert(h && block && buf);
    jpec_huff_state_t state;
    state.buffer = h->state.buffer;
    state.nbits = h->state.nbits;
    state.dc = h->state.dc;
    state.buf = buf;
    jpec_huff_encode_block_impl(block, &state);
    h->state.buffer = state.buffer;
    h->state.nbits = state.nbits;
    h->state.dc = state.dc;
    h->state.buf = state.buf;
}
References jpec_huff_state_t_::buf, jpec_huff_state_t_::buffer, jpec_huff_state_t_::dc, jpec_huff_encode_block_impl(), jpec_huff_state_t_::nbits, and jpec_huff_t_::state.
Referenced by jpec_huff_skel_init().
jpec_huff_new()
jpec_huff_t * jpec_huff_new (void)
Definition at line 118 of file jpeg.c.
{
    jpec_huff_t* h = malloc(sizeof(*h));
    h->state.buffer = 0;
    h->state.nbits = 0;
    h->state.dc = 0;
    h->state.buf = NULL;
    return h;
}
References jpec_huff_state_t_::buf, jpec_huff_state_t_::buffer, jpec_huff_state_t_::dc, jpec_huff_state_t_::nbits, and jpec_huff_t_::state.
Referenced by jpec_huff_skel_init().
jpec_huff_skel_init()
void jpec_huff_skel_init (jpec_huff_skel_t * skel)
Skeleton initialization
Definition at line 110 of file jpeg.c.
{
    assert(skel);
    memset(skel, 0, sizeof(*skel));
    skel->opq = jpec_huff_new();
    skel->del = (void (*)(void*))jpec_huff_del;
    skel->encode_block = (void (*)(void*, jpec_block_t*, jpec_buffer_t*))jpec_huff_encode_block;
}
References jpec_huff_skel_t_::del, jpec_huff_skel_t_::encode_block, jpec_huff_del(), jpec_huff_encode_block(), jpec_huff_new(), and jpec_huff_skel_t_::opq.
Referenced by jpec_enc_open().
Variable Documentation
jpec_ac_code
const int jpec_ac_code[256] extern
Definition at line 321 of file jpeg.c.
Referenced by jpec_huff_encode_block_impl().
jpec_ac_len
const int8_t jpec_ac_len[256] extern
Luminance (Y) - AC
Definition at line 287 of file jpeg.c.
Referenced by jpec_huff_encode_block_impl().
jpec_ac_nb_vals
const int jpec_ac_nb_vals extern
Definition at line 258 of file jpeg.c.
Referenced by jpec_enc_write_dht().
jpec_ac_nodes
const uint8_t jpec_ac_nodes[17] extern
Luminance (Y) - AC
Definition at line 257 of file jpeg.c.
Referenced by jpec_enc_write_dht().
jpec_ac_vals
const uint8_t jpec_ac_vals[162] extern
Definition at line 259 of file jpeg.c.
Referenced by jpec_enc_write_dht().
jpec_dc_code
const int jpec_dc_code[12] extern
Definition at line 283 of file jpeg.c.
Referenced by jpec_huff_encode_block_impl().
jpec_dc_len
const uint8_t jpec_dc_len[12] extern
Huffman inverted tables Luminance (Y) - DC
Definition at line 282 of file jpeg.c.
Referenced by jpec_huff_encode_block_impl().
jpec_dc_nb_vals
const int jpec_dc_nb_vals extern
Definition at line 254 of file jpeg.c.
Referenced by jpec_enc_write_dht().
jpec_dc_nodes
const uint8_t jpec_dc_nodes[17] extern
JPEG standard Huffman tables Luminance (Y) - DC
Definition at line 253 of file jpeg.c.
Referenced by jpec_enc_write_dht().
jpec_dc_vals
const uint8_t jpec_dc_vals[12] extern
Definition at line 255 of file jpeg.c.
Referenced by jpec_enc_write_dht().
jpec_dct
const float jpec_dct[7] extern
DCT coefficients
Definition at line 239 of file jpeg.c.
Referenced by jpec_enc_block_dct().
jpec_qzr
const uint8_t jpec_qzr[64] extern
Standard JPEG quantizing table
Definition at line 229 of file jpeg.c.
Referenced by jpec_enc_init_dqt().
jpec_zz
const int jpec_zz[64] extern
Zig-zag order
Definition at line 243 of file jpeg.c.
Referenced by jpec_enc_block_zz(), and jpec_enc_write_dqt().