libdogecoin: include/dogecoin/key.h File Reference
key.h File Reference
#include <dogecoin/dogecoin.h>
#include <dogecoin/chainparams.h>
#include <dogecoin/uthash.h>
Data Structures
struct dogecoin_key_
struct dogecoin_pubkey_
Typedefs
typedef LIBDOGECOIN_BEGIN_DECL struct dogecoin_key_ dogecoin_key
typedef struct dogecoin_pubkey_ dogecoin_pubkey
Functions
LIBDOGECOIN_API void dogecoin_privkey_init (dogecoin_key *privkey)
LIBDOGECOIN_API dogecoin_bool dogecoin_privkey_is_valid (const dogecoin_key *privkey)
LIBDOGECOIN_API void dogecoin_privkey_cleanse (dogecoin_key *privkey)
LIBDOGECOIN_API dogecoin_bool dogecoin_privkey_gen (dogecoin_key *privkey)
LIBDOGECOIN_API dogecoin_bool dogecoin_privkey_verify_pubkey (dogecoin_key *privkey, dogecoin_pubkey *pubkey)
LIBDOGECOIN_API void dogecoin_privkey_encode_wif (const dogecoin_key *privkey, const dogecoin_chainparams *chain, char *privkey_wif, size_t *strsize_inout)
LIBDOGECOIN_API dogecoin_bool dogecoin_privkey_decode_wif (const char *privkey_wif, const dogecoin_chainparams *chain, dogecoin_key *privkey)
LIBDOGECOIN_API void dogecoin_pubkey_init (dogecoin_pubkey *pubkey)
LIBDOGECOIN_API unsigned int dogecoin_pubkey_get_length (unsigned char ch_header)
LIBDOGECOIN_API dogecoin_bool dogecoin_pubkey_is_valid (const dogecoin_pubkey *pubkey)
LIBDOGECOIN_API void dogecoin_pubkey_cleanse (dogecoin_pubkey *pubkey)
LIBDOGECOIN_API void dogecoin_pubkey_from_key (const dogecoin_key *privkey, dogecoin_pubkey *pubkey_inout)
LIBDOGECOIN_API void dogecoin_pubkey_get_hash160 (const dogecoin_pubkey *pubkey, uint160 hash160)
LIBDOGECOIN_API dogecoin_bool dogecoin_pubkey_get_hex (const dogecoin_pubkey *pubkey, char *str, size_t *strsize)
LIBDOGECOIN_API dogecoin_bool dogecoin_key_sign_hash (const dogecoin_key *privkey, const uint256 hash, unsigned char *sigout, size_t *outlen)
LIBDOGECOIN_API dogecoin_bool dogecoin_key_sign_hash_compact (const dogecoin_key *privkey, const uint256 hash, unsigned char *sigout, size_t *outlen)
LIBDOGECOIN_API dogecoin_bool dogecoin_key_sign_hash_compact_recoverable (const dogecoin_key *privkey, const uint256 hash, unsigned char *sigout, size_t *outlen, int *recid)
LIBDOGECOIN_API dogecoin_bool dogecoin_key_sign_hash_compact_recoverable_fcomp (const dogecoin_key *privkey, const uint256 hash, unsigned char *sigout, size_t *outlen, int *recid)
LIBDOGECOIN_API dogecoin_bool dogecoin_key_recover_pubkey (const unsigned char *sig, const uint256 hash, int recid, dogecoin_pubkey *pubkey)
LIBDOGECOIN_API dogecoin_bool dogecoin_key_sign_recover_pubkey (const unsigned char *sig, const uint256 hash, int recid, dogecoin_pubkey *pubkey)
LIBDOGECOIN_API dogecoin_bool dogecoin_pubkey_verify_sig (const dogecoin_pubkey *pubkey, const uint256 hash, unsigned char *sigder, size_t len)
LIBDOGECOIN_API dogecoin_bool dogecoin_pubkey_verify_sigcmp (const dogecoin_pubkey *pubkey, const uint256 hash, unsigned char *sigcmp)
LIBDOGECOIN_API dogecoin_bool dogecoin_pubkey_getaddr_p2pkh (const dogecoin_pubkey *pubkey, const dogecoin_chainparams *chain, char *addrout)
LIBDOGECOIN_API dogecoin_bool init_keypair (char *privkeywif, dogecoin_key *key, dogecoin_pubkey *pubkey)
Typedef Documentation
dogecoin_key
typedef LIBDOGECOIN_BEGIN_DECL struct dogecoin_key_ dogecoin_key
dogecoin_pubkey
typedef struct dogecoin_pubkey_ dogecoin_pubkey
Function Documentation
dogecoin_key_recover_pubkey()
LIBDOGECOIN_API dogecoin_bool dogecoin_key_recover_pubkey (const unsigned char * sig, const uint256 hash, int recid, dogecoin_pubkey * pubkey)
Definition at line 197 of file key.c.
{
    uint8_t pubkeybuf[128];
    size_t outlen = 128;
    if (!dogecoin_recover_pubkey(sig, hash, recid, pubkeybuf, &outlen) || outlen > DOGECOIN_ECKEY_UNCOMPRESSED_LENGTH)
        return 0;
    dogecoin_mem_zero(pubkey->pubkey, sizeof(pubkey->pubkey));
    memcpy_safe(pubkey->pubkey, pubkeybuf, outlen);
    if (outlen == DOGECOIN_ECKEY_COMPRESSED_LENGTH)
        pubkey->compressed = true;
    return 1;
}
References dogecoin_pubkey_::compressed, DOGECOIN_ECKEY_COMPRESSED_LENGTH, DOGECOIN_ECKEY_UNCOMPRESSED_LENGTH, dogecoin_mem_zero(), dogecoin_recover_pubkey(), memcpy_safe(), and dogecoin_pubkey_::pubkey.
Referenced by sign_message(), and verify_message().
dogecoin_key_sign_hash()
LIBDOGECOIN_API dogecoin_bool dogecoin_key_sign_hash (const dogecoin_key * privkey, const uint256 hash, unsigned char * sigout, size_t * outlen)
Definition at line 177 of file key.c.
{
    return dogecoin_ecc_sign(privkey->privkey, hash, sigout, outlen);
}
References dogecoin_ecc_sign().
Referenced by dogecoin_privkey_verify_pubkey().
dogecoin_key_sign_hash_compact()
LIBDOGECOIN_API dogecoin_bool dogecoin_key_sign_hash_compact (const dogecoin_key * privkey, const uint256 hash, unsigned char * sigout, size_t * outlen)
Definition at line 182 of file key.c.
{
    return dogecoin_ecc_sign_compact(privkey->privkey, hash, sigout, outlen);
}
References dogecoin_ecc_sign_compact().
Referenced by dogecoin_tx_sign_input().
dogecoin_key_sign_hash_compact_recoverable()
LIBDOGECOIN_API dogecoin_bool dogecoin_key_sign_hash_compact_recoverable (const dogecoin_key * privkey, const uint256 hash, unsigned char * sigout, size_t * outlen, int * recid)
Definition at line 187 of file key.c.
{
    return dogecoin_ecc_sign_compact_recoverable(privkey->privkey, hash, sigout, outlen, recid);
}
References dogecoin_ecc_sign_compact_recoverable().
dogecoin_key_sign_hash_compact_recoverable_fcomp()
LIBDOGECOIN_API dogecoin_bool dogecoin_key_sign_hash_compact_recoverable_fcomp (const dogecoin_key * privkey, const uint256 hash, unsigned char * sigout, size_t * outlen, int * recid)
Definition at line 192 of file key.c.
{
    return dogecoin_ecc_sign_compact_recoverable_fcomp(privkey->privkey, hash, sigout, outlen, recid, true);
}
References dogecoin_ecc_sign_compact_recoverable_fcomp().
Referenced by sign_message().
dogecoin_key_sign_recover_pubkey()
LIBDOGECOIN_API dogecoin_bool dogecoin_key_sign_recover_pubkey (const unsigned char * sig, const uint256 hash, int recid, dogecoin_pubkey * pubkey)
Definition at line 210 of file key.c.
{
    uint8_t pubkeybuf[128];
    size_t outlen = 128;
    if (!dogecoin_ecc_recover_pubkey(sig, hash, recid, pubkeybuf, &outlen) || outlen > DOGECOIN_ECKEY_UNCOMPRESSED_LENGTH)
        return 0;
    dogecoin_mem_zero(pubkey->pubkey, sizeof(pubkey->pubkey));
    memcpy_safe(pubkey->pubkey, pubkeybuf, outlen);
    if (outlen == DOGECOIN_ECKEY_COMPRESSED_LENGTH)
        pubkey->compressed = true;
    return 1;
}
References dogecoin_pubkey_::compressed, dogecoin_ecc_recover_pubkey(), DOGECOIN_ECKEY_COMPRESSED_LENGTH, DOGECOIN_ECKEY_UNCOMPRESSED_LENGTH, dogecoin_mem_zero(), memcpy_safe(), and dogecoin_pubkey_::pubkey.
dogecoin_privkey_cleanse()
LIBDOGECOIN_API void dogecoin_privkey_cleanse (dogecoin_key * privkey)
Definition at line 59 of file key.c.
{
    dogecoin_mem_zero(&privkey->privkey, DOGECOIN_ECKEY_PKEY_LENGTH);
}
References DOGECOIN_ECKEY_PKEY_LENGTH, and dogecoin_mem_zero().
Referenced by dogecoin_private_key_wif_to_script_hash(), gen_privatekey(), generatePrivPubKeypair(), pubkey_from_privatekey(), remove_eckey(), sign_message(), and verifyPrivPubKeypair().
dogecoin_privkey_decode_wif()
LIBDOGECOIN_API dogecoin_bool dogecoin_privkey_decode_wif (const char * privkey_wif, const dogecoin_chainparams * chain, dogecoin_key * privkey)
Definition at line 100 of file key.c.
{
    if (!privkey_wif || strlen(privkey_wif) < 50)
        return false;
    const size_t privkey_len = strlen(privkey_wif);
    uint8_t* privkey_data = (uint8_t*)dogecoin_calloc(1, privkey_len);
    dogecoin_mem_zero(privkey_data, privkey_len);
    size_t outlen = 0;
    outlen = dogecoin_base58_decode_check(privkey_wif, privkey_data, privkey_len);
    if (!outlen) {
        dogecoin_free(privkey_data);
        return false;
    }
    if (privkey_data[0] != chain->b58prefix_secret_address) {
        dogecoin_free(privkey_data);
        return false;
    }
    memcpy_safe(privkey->privkey, &privkey_data[1], DOGECOIN_ECKEY_PKEY_LENGTH);
    dogecoin_mem_zero(privkey_data, sizeof(privkey_data));
    dogecoin_free(privkey_data);
    return true;
}
References dogecoin_chainparams_::b58prefix_secret_address, dogecoin_base58_decode_check(), dogecoin_calloc(), DOGECOIN_ECKEY_PKEY_LENGTH, dogecoin_free(), dogecoin_mem_zero(), and memcpy_safe().
Referenced by dogecoin_private_key_wif_to_script_hash(), init_keypair(), main(), new_eckey_from_privkey(), pubkey_from_privatekey(), sign_raw_transaction(), and verifyPrivPubKeypair().
dogecoin_privkey_encode_wif()
LIBDOGECOIN_API void dogecoin_privkey_encode_wif (const dogecoin_key * privkey, const dogecoin_chainparams * chain, char * privkey_wif, size_t * strsize_inout)
Definition at line 90 of file key.c.
{
    uint8_t pkeybase58c[34];
    pkeybase58c[0] = chain->b58prefix_secret_address;
    pkeybase58c[33] = 1; /* always use compressed keys */
    memcpy_safe(&pkeybase58c[1], privkey->privkey, DOGECOIN_ECKEY_PKEY_LENGTH);
    assert(dogecoin_base58_encode_check(pkeybase58c, 34, privkey_wif, *strsize_inout) != 0);
    dogecoin_mem_zero(&pkeybase58c, 34);
}
References dogecoin_chainparams_::b58prefix_secret_address, dogecoin_base58_encode_check(), DOGECOIN_ECKEY_PKEY_LENGTH, dogecoin_mem_zero(), and memcpy_safe().
Referenced by dogecoin_private_key_wif_to_script_hash(), generatePrivPubKeypair(), and verifyPrivPubKeypair().
dogecoin_privkey_gen()
LIBDOGECOIN_API dogecoin_bool dogecoin_privkey_gen (dogecoin_key * privkey)
Definition at line 64 of file key.c.
{
    if (privkey == NULL)
        return false;
    do {
        const dogecoin_bool res = dogecoin_random_bytes(privkey->privkey, DOGECOIN_ECKEY_PKEY_LENGTH, 0);
        if (!res)
            return false;
    } while (dogecoin_ecc_verify_privatekey(privkey->privkey) == 0);
    return true;
}
References dogecoin_ecc_verify_privatekey(), DOGECOIN_ECKEY_PKEY_LENGTH, and dogecoin_random_bytes().
Referenced by gen_privatekey(), generatePrivPubKeypair(), and new_eckey().
dogecoin_privkey_init()
LIBDOGECOIN_API void dogecoin_privkey_init (dogecoin_key * privkey)
Definition at line 47 of file key.c.
{
    dogecoin_mem_zero(&privkey->privkey, DOGECOIN_ECKEY_PKEY_LENGTH);
}
References DOGECOIN_ECKEY_PKEY_LENGTH, and dogecoin_mem_zero().
Referenced by dogecoin_private_key_wif_to_script_hash(), gen_privatekey(), generatePrivPubKeypair(), init_keypair(), main(), new_eckey(), new_eckey_from_privkey(), pubkey_from_privatekey(), sign_raw_transaction(), and verifyPrivPubKeypair().
dogecoin_privkey_is_valid()
LIBDOGECOIN_API dogecoin_bool dogecoin_privkey_is_valid (const dogecoin_key * privkey)
Definition at line 52 of file key.c.
{
    if (!privkey)
        return false;
    return dogecoin_ecc_verify_privatekey(privkey->privkey);
}
References dogecoin_ecc_verify_privatekey().
Referenced by dogecoin_private_key_wif_to_script_hash(), dogecoin_tx_sign_input(), init_keypair(), new_eckey(), new_eckey_from_privkey(), and verifyPrivPubKeypair().
dogecoin_privkey_verify_pubkey()
LIBDOGECOIN_API dogecoin_bool dogecoin_privkey_verify_pubkey (dogecoin_key * privkey, dogecoin_pubkey * pubkey)
Definition at line 76 of file key.c.
{
    uint256 rnddata, hash;
    const dogecoin_bool res = dogecoin_random_bytes(rnddata, DOGECOIN_HASH_LENGTH, 0);
    if (!res)
        return false;
    dogecoin_hash(rnddata, DOGECOIN_HASH_LENGTH, hash);
    unsigned char sig[74];
    size_t siglen = 74;
    if (!dogecoin_key_sign_hash(privkey, hash, sig, &siglen))
        return false;
    return dogecoin_pubkey_verify_sig(pubkey, hash, sig, siglen);
}
References dogecoin_hash(), DOGECOIN_HASH_LENGTH, dogecoin_key_sign_hash(), dogecoin_pubkey_verify_sig(), dogecoin_random_bytes(), and uint256.
Referenced by init_keypair().
dogecoin_pubkey_cleanse()
LIBDOGECOIN_API void dogecoin_pubkey_cleanse (dogecoin_pubkey * pubkey)
Definition at line 145 of file key.c.
{
    if (pubkey == NULL)
        return;
    dogecoin_mem_zero(pubkey->pubkey, DOGECOIN_ECKEY_UNCOMPRESSED_LENGTH);
}
References DOGECOIN_ECKEY_UNCOMPRESSED_LENGTH, dogecoin_mem_zero(), and dogecoin_pubkey_::pubkey.
Referenced by dogecoin_private_key_wif_to_script_hash(), generatePrivPubKeypair(), pubkey_from_privatekey(), remove_eckey(), sign_message(), verify_message(), and verifyPrivPubKeypair().
dogecoin_pubkey_from_key()
LIBDOGECOIN_API void dogecoin_pubkey_from_key (const dogecoin_key * privkey, dogecoin_pubkey * pubkey_inout)
Definition at line 168 of file key.c.
{
    if (pubkey_inout == NULL || privkey == NULL)
        return;
    size_t in_out_len = DOGECOIN_ECKEY_COMPRESSED_LENGTH;
    dogecoin_ecc_get_pubkey(privkey->privkey, pubkey_inout->pubkey, &in_out_len, true);
    pubkey_inout->compressed = true;
}
References dogecoin_pubkey_::compressed, dogecoin_ecc_get_pubkey(), DOGECOIN_ECKEY_COMPRESSED_LENGTH, and dogecoin_pubkey_::pubkey.
Referenced by dogecoin_private_key_wif_to_script_hash(), dogecoin_tx_sign_input(), generatePrivPubKeypair(), init_keypair(), new_eckey(), new_eckey_from_privkey(), pubkey_from_privatekey(), and verifyPrivPubKeypair().
dogecoin_pubkey_get_hash160()
LIBDOGECOIN_API void dogecoin_pubkey_get_hash160 (const dogecoin_pubkey * pubkey, uint160 hash160)
Definition at line 152 of file key.c.
{
    uint256 hashout;
    dogecoin_hash_sngl_sha256(pubkey->pubkey, pubkey->compressed ? DOGECOIN_ECKEY_COMPRESSED_LENGTH : DOGECOIN_ECKEY_UNCOMPRESSED_LENGTH, hashout);
    rmd160(hashout, sizeof(hashout), hash160);
}
References dogecoin_pubkey_::compressed, DOGECOIN_ECKEY_COMPRESSED_LENGTH, DOGECOIN_ECKEY_UNCOMPRESSED_LENGTH, dogecoin_hash_sngl_sha256(), dogecoin_pubkey_::pubkey, rmd160(), and uint256.
Referenced by dogecoin_pubkey_getaddr_p2pkh(), dogecoin_tx_add_p2pkh_out(), and dogecoin_tx_sign_input().
dogecoin_pubkey_get_hex()
LIBDOGECOIN_API dogecoin_bool dogecoin_pubkey_get_hex (const dogecoin_pubkey * pubkey, char * str, size_t * strsize)
Definition at line 159 of file key.c.
{
    if (*strsize < DOGECOIN_ECKEY_COMPRESSED_LENGTH * 2 + 1)
        return false;
    utils_bin_to_hex((unsigned char*)pubkey->pubkey, DOGECOIN_ECKEY_COMPRESSED_LENGTH, str);
    *strsize = DOGECOIN_ECKEY_COMPRESSED_LENGTH * 2;
    return true;
}
References DOGECOIN_ECKEY_COMPRESSED_LENGTH, dogecoin_pubkey_::pubkey, and utils_bin_to_hex().
Referenced by dogecoin_hdnode_get_pub_hex(), and pubkey_from_privatekey().
dogecoin_pubkey_get_length()
LIBDOGECOIN_API unsigned int dogecoin_pubkey_get_length (unsigned char ch_header)
Definition at line 131 of file key.c.
{
    if (ch_header == 2 || ch_header == 3)
        return DOGECOIN_ECKEY_COMPRESSED_LENGTH;
    if (ch_header == 4 || ch_header == 6 || ch_header == 7)
        return DOGECOIN_ECKEY_UNCOMPRESSED_LENGTH;
    return 0;
}
References DOGECOIN_ECKEY_COMPRESSED_LENGTH, and DOGECOIN_ECKEY_UNCOMPRESSED_LENGTH.
Referenced by dogecoin_script_is_op_pubkey().
dogecoin_pubkey_getaddr_p2pkh()
LIBDOGECOIN_API dogecoin_bool dogecoin_pubkey_getaddr_p2pkh (const dogecoin_pubkey * pubkey, const dogecoin_chainparams * chain, char * addrout)
Definition at line 251 of file key.c.
{
    uint8_t hash160[sizeof(uint160) + 1];
    hash160[0] = chain->b58prefix_pubkey_address;
    dogecoin_pubkey_get_hash160(pubkey, hash160 + 1);
    dogecoin_base58_encode_check(hash160, sizeof(hash160), addrout, 100);
    return true;
}
References dogecoin_chainparams_::b58prefix_pubkey_address, dogecoin_base58_encode_check(), and dogecoin_pubkey_get_hash160().
Referenced by addresses_from_pubkey(), dogecoin_private_key_wif_to_script_hash(), generatePrivPubKeypair(), new_eckey(), new_eckey_from_privkey(), sign_message(), verify_message(), and verifyPrivPubKeypair().
dogecoin_pubkey_init()
LIBDOGECOIN_API void dogecoin_pubkey_init (dogecoin_pubkey * pubkey)
Definition at line 123 of file key.c.
{
    if (pubkey == NULL)
        return;
    dogecoin_mem_zero(pubkey->pubkey, DOGECOIN_ECKEY_UNCOMPRESSED_LENGTH);
    pubkey->compressed = false;
}
References dogecoin_pubkey_::compressed, DOGECOIN_ECKEY_UNCOMPRESSED_LENGTH, dogecoin_mem_zero(), and dogecoin_pubkey_::pubkey.
Referenced by addresses_from_pubkey(), dogecoin_hdnode_get_pub_hex(), dogecoin_private_key_wif_to_script_hash(), dogecoin_tx_sign_input(), generatePrivPubKeypair(), init_keypair(), new_eckey(), new_eckey_from_privkey(), pubkey_from_privatekey(), verify_message(), and verifyPrivPubKeypair().
dogecoin_pubkey_is_valid()
LIBDOGECOIN_API dogecoin_bool dogecoin_pubkey_is_valid (const dogecoin_pubkey * pubkey)
Definition at line 140 of file key.c.
{
    return dogecoin_ecc_verify_pubkey(pubkey->pubkey, pubkey->compressed);
}
References dogecoin_pubkey_::compressed, dogecoin_ecc_verify_pubkey(), and dogecoin_pubkey_::pubkey.
Referenced by addresses_from_pubkey(), dogecoin_private_key_wif_to_script_hash(), dogecoin_tx_sign_input(), generatePrivPubKeypair(), init_keypair(), new_eckey(), new_eckey_from_privkey(), pubkey_from_privatekey(), and verifyPrivPubKeypair().
dogecoin_pubkey_verify_sig()
LIBDOGECOIN_API dogecoin_bool dogecoin_pubkey_verify_sig (const dogecoin_pubkey * pubkey, const uint256 hash, unsigned char * sigder, size_t len)
Definition at line 223 of file key.c.
{
    return dogecoin_ecc_verify_sig(pubkey->pubkey, pubkey->compressed, hash, sigder, len);
}
References dogecoin_pubkey_::compressed, dogecoin_ecc_verify_sig(), and dogecoin_pubkey_::pubkey.
Referenced by dogecoin_privkey_verify_pubkey().
dogecoin_pubkey_verify_sigcmp()
LIBDOGECOIN_API dogecoin_bool dogecoin_pubkey_verify_sigcmp (const dogecoin_pubkey * pubkey, const uint256 hash, unsigned char * sigcmp)
Definition at line 228 of file key.c.
{
    return dogecoin_ecc_verify_sigcmp(pubkey->pubkey, pubkey->compressed, hash, sigcmp);
}
References dogecoin_pubkey_::compressed, dogecoin_ecc_verify_sigcmp(), and dogecoin_pubkey_::pubkey.
Referenced by verify_message().
init_keypair()
LIBDOGECOIN_API dogecoin_bool init_keypair (char * privkeywif, dogecoin_key * key, dogecoin_pubkey * pubkey)
Definition at line 233 of file key.c.
{
    dogecoin_privkey_init(key);
    assert(dogecoin_privkey_is_valid(key) == 0);
    const dogecoin_chainparams* chain = chain_from_b58_prefix(privkeywif);
    if (!dogecoin_privkey_decode_wif(privkeywif, chain, key)) {
        return false;
    }
    assert(dogecoin_privkey_is_valid(key) == 1);
    dogecoin_pubkey_init(pubkey);
    pubkey->compressed = false;
    assert(dogecoin_pubkey_is_valid(pubkey) == 0);
    dogecoin_pubkey_from_key(key, pubkey);
    if (!dogecoin_pubkey_is_valid(pubkey)) return 0;
    if (!dogecoin_privkey_verify_pubkey(key, pubkey)) return 0;
    return true;
}
References chain_from_b58_prefix(), dogecoin_pubkey_::compressed, dogecoin_privkey_decode_wif(), dogecoin_privkey_init(), dogecoin_privkey_is_valid(), dogecoin_privkey_verify_pubkey(), dogecoin_pubkey_from_key(), dogecoin_pubkey_init(), and dogecoin_pubkey_is_valid().
Referenced by sign_message().