libdogecoin: include/dogecoin/koinu.h File Reference
koinu.h File Reference
#include <dogecoin/dogecoin.h>
Functions
LIBDOGECOIN_BEGIN_DECL LIBDOGECOIN_API long double koinu_to_coins (uint64_t koinu)
LIBDOGECOIN_API int koinu_to_coins_str (uint64_t koinu, char *str)
LIBDOGECOIN_API uint64_t coins_to_koinu_str (char *coins)
LIBDOGECOIN_API unsigned long long coins_to_koinu (long double coins)
Function Documentation
coins_to_koinu()
LIBDOGECOIN_API unsigned long long coins_to_koinu (long double coins)
coins_to_koinu_str()
LIBDOGECOIN_API uint64_t coins_to_koinu_str (char * coins)
Definition at line 177 of file koinu.c.
{
    if (coins[0] == '-') return false;
    size_t length = check_length(coins);
    if (!length) return false;
    char *end, dogecoin_string[21], koinu_string[9];
    dogecoin_mem_zero(dogecoin_string, 21);
    dogecoin_mem_zero(koinu_string, 9);
    size_t i = 0, j = 0, mantissa_length = 0;
    for (; i < length; i++) {
        dogecoin_string[i] = coins[i];
        if (coins[i] == '.') {
            j = i;
            while (j < i + 8) {
                dogecoin_string[j] = '0'; j++;
            }
            dogecoin_string[i] = '\0';
            i++;
            break;
        }
    }
    for (j = 0; i < length && j < 8; i++, j++) {
        koinu_string[j] = coins[i];
        mantissa_length++;
    }
    if (mantissa_length != 8) {
        for (i = mantissa_length; i < 8; i++) {
            koinu_string[i] = '0';
        }
    } else koinu_string[strlen(koinu_string)] = '\0';
    errno = 0;
    uint64_t dogecoin = strtoull(dogecoin_string, &end, 10);
    enum conversion_type state = validate_conversion(dogecoin, (const char*)dogecoin_string, end, "\0");
    if (state == CONVERSION_SUCCESS) {
        if (strlen(dogecoin_string) <= 12) dogecoin *= 100000000;
    } else debug_print("%s\n", conversion_type_to_str(state));
    errno = 0;
    uint64_t koinu = strtoull(koinu_string, &end, 10) + dogecoin;
    state = validate_conversion(koinu, (const char*)koinu_string, end, "\0");
    if (state == CONVERSION_SUCCESS) return koinu;
    else { debug_print("%s\n", conversion_type_to_str(state)); return false; }
}
References check_length(), CONVERSION_SUCCESS, conversion_type_to_str(), debug_print, dogecoin_mem_zero(), and validate_conversion().
Referenced by add_output(), finalize_transaction(), and transaction_output_menu().
koinu_to_coins()
LIBDOGECOIN_BEGIN_DECL LIBDOGECOIN_API long double koinu_to_coins (uint64_t koinu)
koinu_to_coins_str()
LIBDOGECOIN_API int koinu_to_coins_str (uint64_t koinu, char * str)
Definition at line 141 of file koinu.c.
{
    enum conversion_type state = validate_conversion(koinu, NULL, NULL, NULL);
    if (state != CONVERSION_SUCCESS) return false;
    uint64_t i = 0, j =0, length = calc_length(koinu),
    target = length < 9 ? 10 - length : length - 9;
    if (length < 9) {
        string(koinu, str);
        size_t l = str ? strlen(str) : 0;
        char* swap = dogecoin_char_vla(l + 1);
        memcpy_safe(swap, str, l + 1);
        for (; i < target; i++) {
            if (i == 0 || i == 1) {
                str[0] = '0';
                str[1] = '.';
            } else str[i] = '0';
        }
        for (; i < 10; i++, j++) str[i] = swap[j];
        free(swap);
    } else {
        char tmp[21];
        string(koinu, tmp);
        for (; i < length; i++) {
            if (i < target) str[i] = tmp[i];
            else if (i == target) {
                str[i] = tmp[i];
                str[i + 1] = '.';
            } else if (i > target) str[i + 1] = tmp[i];
        }
        str[length + 1] = '\0';
    }
    return true;
}
References calc_length(), CONVERSION_SUCCESS, dogecoin_char_vla(), memcpy_safe(), string(), and validate_conversion().
Referenced by transaction_output_menu().