libdogecoin: include/dogecoin/libdogecoin.h File Reference
libdogecoin.h File Reference
#include <limits.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include "dogecoin.h"
#include "constants.h"
#include "uthash.h"
Data Structures
struct dogecoin_key_
struct dogecoin_pubkey_
struct eckey
Macros
#define ENT_STRING_SIZE 3
#define MAX_HEX_ENT_SIZE 64 + 1
#define MAX_MNEMONIC_SIZE 1024
#define MAX_PASS_SIZE 256
#define MAX_SEED_SIZE 64
#define CHG_LEVEL_STRING_SIZE 2
Typedefs
typedef char ENTROPY_SIZE[ENT_STRING_SIZE]
typedef char HEX_ENTROPY[MAX_HEX_ENT_SIZE]
typedef char MNEMONIC[MAX_MNEMONIC_SIZE]
typedef char PASS[MAX_PASS_SIZE]
typedef uint8_t SEED[MAX_SEED_SIZE]
typedef char CHANGE_LEVEL[CHG_LEVEL_STRING_SIZE]
typedef struct dogecoin_key_ dogecoin_key
typedef struct dogecoin_pubkey_ dogecoin_pubkey
typedef struct eckey eckey
Functions
void dogecoin_ecc_start (void)
init static ecc context
void dogecoin_ecc_stop (void)
destroys the static ecc context
int generatePrivPubKeypair (char *wif_privkey, char *p2pkh_pubkey, bool is_testnet)
This function generates a new basic public-private key pair for the specified network.
int generateHDMasterPubKeypair (char *wif_privkey_master, char *p2pkh_pubkey_master, bool is_testnet)
This function generates a new master public-private key pair for a hierarchical deterministic wallet on the specified network.
int generateDerivedHDPubkey (const char *wif_privkey_master, char *p2pkh_pubkey)
This function takes a wif-encoded HD master private key and derive a new HD public key from it on the specified network. This input should come from the result of generateHDMasterPubKeypair().
int verifyPrivPubKeypair (char *wif_privkey, char *p2pkh_pubkey, bool is_testnet)
This function verifies that a given private key matches a given public key and that both are valid on the specified network.
int verifyHDMasterPubKeypair (char *wif_privkey_master, char *p2pkh_pubkey_master, bool is_testnet)
This function verifies that a given HD master private key matches a given HD master public key and that both are valid on the specified network.
int verifyP2pkhAddress (char *p2pkh_pubkey, size_t len)
This function takes a public key and does some basic validation to determine if it is a valid Dogecoin address.
int getDerivedHDAddress (const char *masterkey, uint32_t account, bool ischange, uint32_t addressindex, char *outaddress, bool outprivkey)
This function generates a derived child address from a masterkey using a BIP44 standardized static, non hardened path comprised of an account, a change or receiving address and an address index.
int getDerivedHDAddressByPath (const char *masterkey, const char *derived_path, char *outaddress, bool outprivkey)
This function generates a derived child key from a masterkey using a custom derived path in string format.
int generateEnglishMnemonic (const HEX_ENTROPY entropy, const ENTROPY_SIZE size, MNEMONIC mnemonic)
This function gnerates an English mnemonic phrase of given size or from hex entropy.
int generateRandomEnglishMnemonic (const ENTROPY_SIZE size, MNEMONIC mnemonic)
This function generates a random English mnemonic phrase.
int dogecoin_seed_from_mnemonic (const MNEMONIC mnemonic, const PASS pass, SEED seed)
int getDerivedHDAddressFromMnemonic (const uint32_t account, const uint32_t index, const CHANGE_LEVEL change_level, const MNEMONIC mnemonic, const PASS pass, char *p2pkh_pubkey, const bool is_testnet)
int start_transaction ()
This function creates a new transaction, places it in the hash table, and returns the index of the new transaction, starting from 1 and incrementing each subsequent call.
int add_utxo (int txindex, char *hex_utxo_txid, int vout)
This function takes a transaction represented in raw hex and adds it as an input to the specified working transaction.
int add_output (int txindex, char *destinationaddress, char *amount)
This function constructs an output sending the specified amount to the specified address and adds it to the transaction with the specified index.
char * finalize_transaction (int txindex, char *destinationaddress, char *subtractedfee, char *out_dogeamount_for_verification, char *changeaddress)
This function 'closes the inputs' by returning change to the recipient after the total amount and desired fee is confirmed.
int sign_transaction (int txindex, char *script_pubkey, char *privkey)
This function signs all of the inputs in the specified working transaction using the provided script pubkey and private key.
void remove_all ()
This function removes all working transactions from the hash table.
char * get_raw_transaction (int txindex)
This function takes an index of a working transaction and returns the hex representation of it.
void clear_transaction (int txindex)
This function removes the specified working transaction from the hash table.
int qrgen_p2pkh_to_qrbits (const char *in_p2pkh, uint8_t *outQrByteArray)
int qrgen_p2pkh_to_qr_string (const char *in_p2pkh, char *outString)
void qrgen_p2pkh_consoleprint_to_qr (char *in_p2pkh)
int qrgen_string_to_qr_pngfile (const char *outFilename, const char *inString, uint8_t sizeMultiplier)
int qrgen_string_to_qr_jpgfile (const char *outFilename, const char *inString, uint8_t sizeMultiplier)
int sign_raw_transaction (int inputindex, char *incomingrawtx, char *scripthex, int sighashtype, char *privkey)
This function signs the specified input of a working transaction, according to the signing parameters specified.
int store_raw_transaction (char *incomingrawtx)
This function stores a raw transaction to the next available working transaction in the hash table.
char * dogecoin_char_vla (size_t size)
void dogecoin_free (void *ptr)
This function calls dogecoin_free_internal() using the current memory mapper.
eckey * new_eckey ()
void add_eckey (eckey *key)
This function takes a pointer to an existing working eckey object and adds it to the hash table.
eckey * find_eckey (int idx)
This function takes an index and returns the working eckey associated with that index in the hash table.
void remove_eckey (eckey *key)
This function removes the specified working eckey from the hash table and frees the keys in memory.
int start_key ()
char * sign_message (char *privkey, char *msg)
Sign message with private key.
int verify_message (char *sig, char *msg, char *address)
Verify signed message using non BIP32 encoded address.
Variables
static eckey * keys = NULL
Macro Definition Documentation
CHG_LEVEL_STRING_SIZE
#define CHG_LEVEL_STRING_SIZE 2
Definition at line 97 of file libdogecoin.h.
ENT_STRING_SIZE
#define ENT_STRING_SIZE 3
Definition at line 77 of file libdogecoin.h.
MAX_HEX_ENT_SIZE
#define MAX_HEX_ENT_SIZE 64 + 1
Definition at line 81 of file libdogecoin.h.
MAX_MNEMONIC_SIZE
#define MAX_MNEMONIC_SIZE 1024
Definition at line 85 of file libdogecoin.h.
MAX_PASS_SIZE
#define MAX_PASS_SIZE 256
Definition at line 89 of file libdogecoin.h.
MAX_SEED_SIZE
#define MAX_SEED_SIZE 64
Definition at line 93 of file libdogecoin.h.
Typedef Documentation
CHANGE_LEVEL
typedef char CHANGE_LEVEL[CHG_LEVEL_STRING_SIZE]
Definition at line 98 of file libdogecoin.h.
dogecoin_key
typedef struct dogecoin_key_ dogecoin_key
dogecoin_pubkey
typedef struct dogecoin_pubkey_ dogecoin_pubkey
eckey
typedef struct eckey eckey
ENTROPY_SIZE
typedef char ENTROPY_SIZE[ENT_STRING_SIZE]
Definition at line 78 of file libdogecoin.h.
HEX_ENTROPY
typedef char HEX_ENTROPY[MAX_HEX_ENT_SIZE]
Definition at line 82 of file libdogecoin.h.
MNEMONIC
typedef char MNEMONIC[MAX_MNEMONIC_SIZE]
Definition at line 86 of file libdogecoin.h.
PASS
typedef char PASS[MAX_PASS_SIZE]
Definition at line 90 of file libdogecoin.h.
SEED
typedef uint8_t SEED[MAX_SEED_SIZE]
Definition at line 94 of file libdogecoin.h.
Function Documentation
add_eckey()
void add_eckey (eckey * key)
This function takes a pointer to an existing working eckey object and adds it to the hash table.
Parameters
key The pointer to the working eckey.
Returns
Nothing.
Definition at line 97 of file eckey.c.
{
    eckey* key_old;
    HASH_FIND_INT(keys, &key->idx, key_old);
    if (key_old == NULL) {
        HASH_ADD_INT(keys, idx, key);
    } else {
        HASH_REPLACE_INT(keys, idx, key, key_old);
    }
    dogecoin_free(key_old);
}
References dogecoin_free(), HASH_ADD_INT, HASH_FIND_INT, HASH_REPLACE_INT, eckey::idx, and keys.
Referenced by start_key().
add_output()
int add_output (int txindex, char * destinationaddress, char * amount)
This function constructs an output sending the specified amount to the specified address and adds it to the transaction with the specified index.
Parameters
txindex The index of the transaction where the output will be added.
destinationaddress The address to send the funds to.
amount The amount of dogecoin to send.
Returns
1 if the transaction input was added successfully, 0 otherwise.
Definition at line 321 of file transaction.c.
{
    // find working transaction by index and pass to funciton local variable to manipulate:
    working_transaction* tx = find_transaction(txindex);
    // guard against null pointer exceptions
    if (tx == NULL) {
        return false;
    }
    // determine intended network by checking address prefix:
    const dogecoin_chainparams* chain = (destinationaddress[0] == 'D') ? &dogecoin_chainparams_main : &dogecoin_chainparams_test;
    uint64_t koinu = coins_to_koinu_str(amount);
    // calculate total minus fees
    // pass in transaction obect, network paramters, amount of dogecoin to send to address and finally p2pkh address:
    return dogecoin_tx_add_address_out(tx->transaction, chain, (int64_t)koinu, destinationaddress);
}
add_utxo()
int add_utxo (int txindex, char * hex_utxo_txid, int vout)
This function takes a transaction represented in raw hex and adds it as an input to the specified working transaction.
Parameters
txindex The index of the transaction to add the input to.
hex_utxo_txid The raw transaction hex of the input transaction.
vout The output index of the input transaction containing spendable funds.
Returns
1 if the transaction input was added successfully, 0 otherwise.
Definition at line 283 of file transaction.c.
{
    // find working transaction by index and pass to funciton local variable to manipulate:
    working_transaction* tx = find_transaction(txindex);
    // guard against null pointer exceptions
    if (tx == NULL) return false;
    size_t flag = tx->transaction->vin->len;
    // instantiate empty dogecoin_tx_in object to set previous output txid and output n:
    dogecoin_tx_in* tx_in = dogecoin_tx_in_new();
    // add prevout hash to tx_in->prevout.hash in prep of adding to tx->transaction-vin vector
    utils_uint256_sethex((char *)hex_utxo_txid, (uint8_t *)tx_in->prevout.hash);
    // set index of utxo we want to spend
    tx_in->prevout.n = vout;
    // add to working tx object
    vector_add(tx->transaction->vin, tx_in);
    // free tx_in struct since it has been added to our working tx
    // ensure the length of our working tx inputs length has incremented by 1
    // which will return true if successful:
    return flag + 1 == tx->transaction->vin->len;
}
clear_transaction()
void clear_transaction (int txindex)
This function removes the specified working transaction from the hash table.
Parameters
txindex The index of the working transaction to remove.
Returns
Nothing.
Definition at line 460 of file transaction.c.
{
    // find working transaction by index and pass to funciton local variable to manipulate:
    working_transaction* tx = find_transaction(txindex);
    // remove from hashmap
    remove_transaction(tx);
}
dogecoin_char_vla()
char * dogecoin_char_vla (size_t size)
Definition at line 263 of file mem.c.
{
    char* outarray;
    outarray = (char*)malloc(size * sizeof(char));
    return outarray;
}
dogecoin_ecc_start()
void dogecoin_ecc_start (void)
init static ecc context
Definition at line 14 of file ecc.c.
{
    dogecoin_random_init();
    secp256k1_ctx = secp256k1_context_create(SECP256K1_CONTEXT_SIGN | SECP256K1_CONTEXT_VERIFY);
    if (secp256k1_ctx == NULL)
        return false;
    uint8_t seed[32];
    int ret;
    ret = dogecoin_random_bytes(seed, 32, 0);
    if (!ret)
        return false;
    ret = secp256k1_context_randomize(secp256k1_ctx, seed);
    if (!ret)
        return false;
    return true;
}
References dogecoin_random_bytes(), dogecoin_random_init(), secp256k1_context_create(), secp256k1_context_randomize(), SECP256K1_CONTEXT_SIGN, SECP256K1_CONTEXT_VERIFY, and secp256k1_ctx.
Referenced by main().
dogecoin_ecc_stop()
void dogecoin_ecc_stop (void)
destroys the static ecc context
Definition at line 31 of file ecc.c.
{
    secp256k1_context* ctx = secp256k1_ctx;
    secp256k1_ctx = NULL;
    if (ctx)
        secp256k1_context_destroy(ctx);
}
References ctx, secp256k1_context_destroy(), and secp256k1_ctx.
Referenced by main(), and showError().
dogecoin_free()
void dogecoin_free (void * ptr)
This function calls dogecoin_free_internal() using the current memory mapper.
Parameters
ptr The pointer to the memory block to be freed.
Returns
Nothing.
Definition at line 121 of file mem.c.
{
    current_mem_mapper.dogecoin_free(ptr);
}
dogecoin_seed_from_mnemonic()
int dogecoin_seed_from_mnemonic (const MNEMONIC mnemonic, const PASS pass, SEED seed)
finalize_transaction()
char * finalize_transaction (int txindex, char * destinationaddress, char * subtractedfee, char * out_dogeamount_for_verification, char * changeaddress)
This function 'closes the inputs' by returning change to the recipient after the total amount and desired fee is confirmed.
Parameters
txindex The index of the working transaction to finalize.
destinationaddress The address where the funds are being sent.
subtractedfee The amount to set aside as a fee to the miner.
out_dogeamount_for_verification An echo of the total amount to send.
changeaddress The address of the sender to receive the change.
Returns
The hex of the finalized transaction.
Definition at line 378 of file transaction.c.
{
    // find working transaction by index and pass to funciton local variable to manipulate:
    working_transaction* tx = find_transaction(txindex);
    // guard against null pointer exceptions
    if (tx == NULL) return false;
    // determine intended network by checking address prefix:
    int is_testnet = chain_from_b58_prefix_bool(destinationaddress);
    uint64_t subtractedfee_koinu = coins_to_koinu_str(subtractedfee);
    uint64_t out_koinu_for_verification = coins_to_koinu_str(out_dogeamount_for_verification);
    // calculate total minus desired fees
    uint64_t total = (uint64_t)out_koinu_for_verification - (uint64_t)subtractedfee_koinu, tx_out_total = 0;
    int i, p2pkh_count = 0, length = (int)tx->transaction->vout->len;
    // iterate through transaction output values while adding each one to tx_out_total:
    for (i = 0; i < length; i++) {
        dogecoin_tx_out* tx_out_tmp = vector_idx(tx->transaction->vout, i);
        tx_out_total += tx_out_tmp->value;
        char p2pkh[36]; //mlumin: this was originally 17, caused problems if < 25.  p2pkh len is 24-36.
        //MLUMIN:MSVC
        dogecoin_mem_zero(p2pkh, sizeof(p2pkh));
        p2pkh_count = dogecoin_script_hash_to_p2pkh(tx_out_tmp, (char *)p2pkh, is_testnet);
        if (i == length - 1 && changeaddress) {
            // manually make change and send back to our public key address
            if (make_change(txindex, changeaddress, subtractedfee_koinu, out_koinu_for_verification - tx_out_total)) {
                p2pkh_count += 1;
                tx_out_tmp = vector_idx(tx->transaction->vout, tx->transaction->vout->len - 1);
                tx_out_total += tx_out_tmp->value;
            }
            break;
        }
    }
    if (p2pkh_count < 1) {
        printf("p2pkh address not found from any output script hash!\n");
        return false;
    }
    // pass in transaction obect, network paramters, amount of dogecoin to send to address and finally p2pkh address:
    return tx_out_total == total ? get_raw_transaction(txindex) : false;
}
find_eckey()
eckey * find_eckey (int idx)
This function takes an index and returns the working eckey associated with that index in the hash table.
Parameters
idx The index of the target working eckey.
Returns
The pointer to the working eckey associated with the provided index.
Definition at line 117 of file eckey.c.
{
    eckey* key;
    HASH_FIND_INT(keys, &idx, key);
    return key;
}
References HASH_FIND_INT, eckey::idx, and keys.
generateDerivedHDPubkey()
int generateDerivedHDPubkey (const char * wif_privkey_master, char * p2pkh_pubkey)
This function takes a wif-encoded HD master private key and derive a new HD public key from it on the specified network. This input should come from the result of generateHDMasterPubKeypair().
Parameters
wif_privkey_master The master private key to derive the child key from.
p2pkh_pubkey The resulting child public key.
Returns
1 if the child key was generated successfully, 0 otherwise.
Definition at line 174 of file address.c.
{
    /* require master key */
    if (!wif_privkey_master) {
        return false;
    }
    /* determine address prefix for network chainparams */
    const dogecoin_chainparams* chain = chain_from_b58_prefix(wif_privkey_master);
    char str[P2PKH_ADDR_STRINGLEN];
    /* if nothing is passed in use internal variables */
    if (p2pkh_pubkey) {
        memcpy_safe(str, p2pkh_pubkey, sizeof(str));
    }
    dogecoin_hdnode* node = dogecoin_hdnode_new();
    dogecoin_hdnode_deserialize(wif_privkey_master, chain, node);
    dogecoin_hdnode_get_p2pkh_address(node, chain, str, sizeof(str));
    /* pass back to external variable if exists */
    if (p2pkh_pubkey) {
        memcpy_safe(p2pkh_pubkey, str, sizeof(str));
    }
    /* reset internal variables */
    dogecoin_hdnode_free(node);
    dogecoin_mem_zero(str, strlen(str));
    return true;
}
References chain_from_b58_prefix(), dogecoin_hdnode_deserialize(), dogecoin_hdnode_free(), dogecoin_hdnode_get_p2pkh_address(), dogecoin_hdnode_new(), dogecoin_mem_zero(), memcpy_safe(), and P2PKH_ADDR_STRINGLEN.
Referenced by generateHDMasterPubKeypair().
generateEnglishMnemonic()
int generateEnglishMnemonic (const HEX_ENTROPY entropy, const ENTROPY_SIZE size, MNEMONIC mnemonic)
This function gnerates an English mnemonic phrase of given size or from hex entropy.
Parameters
entropy The hex string of entropy.
size The size of entropy in bits.
mnemonic The mnemonic code words.
Returns
0 (success), -1 (fail)
Definition at line 823 of file bip39.c.
{
    /* Initialize variables */
    const char* lang = "eng";     /* default english (eng) */
    const char* space = " ";      /* default utf8 ( ) */
    const char* words = 0;        /* default no custom words (NULL) */
    char* entropy_out = 0;
    size_t mnemonic_size = 0;
    /* allocate space for entropy if valid */
    if (entropy) {
        entropy_out = malloc(sizeof(char) * MAX_ENTROPY_STRING_SIZE);
        if (entropy_out == NULL) {
            fprintf(stderr, "ERROR: Failed to allocate memory for mnemonic\n");
            return -1;
        }
        memset(entropy_out, '\0', MAX_ENTROPY_STRING_SIZE);
    }
    /* first determine size of mnemonic */
    if (dogecoin_generate_mnemonic (size, lang, space, entropy, words, entropy_out, &mnemonic_size, NULL) == -1) {
        dogecoin_free (entropy_out);
        return -1;
    }
    /* generate mnemonic with entropy out */
    if (dogecoin_generate_mnemonic (size, lang, space, entropy_out, words, NULL, &mnemonic_size, mnemonic) == -1) {
        dogecoin_free (entropy_out);
        return -1;
    }
    dogecoin_free (entropy_out);
    return 0;
}
References dogecoin_free(), dogecoin_generate_mnemonic(), and MAX_ENTROPY_STRING_SIZE.
Referenced by generateRandomEnglishMnemonic(), and main().
generateHDMasterPubKeypair()
int generateHDMasterPubKeypair (char * wif_privkey_master, char * p2pkh_pubkey_master, bool is_testnet)
This function generates a new master public-private key pair for a hierarchical deterministic wallet on the specified network.
Parameters
wif_privkey_master The generated master private key.
p2pkh_pubkey_master The generated master public key.
is_testnet The flag denoting which network, 0 for mainnet and 1 for testnet.
Returns
1 if the key pair was generated successfully.
Definition at line 128 of file address.c.
{
    char hd_privkey_master[HD_MASTERKEY_STRINGLEN];
    char hd_pubkey_master[P2PKH_ADDR_STRINGLEN];
    /* if nothing is passed use internal variables */
    if (wif_privkey_master) {
        memcpy_safe(hd_privkey_master, wif_privkey_master, sizeof(hd_privkey_master));
    }
    if (p2pkh_pubkey_master) {
        memcpy_safe(hd_pubkey_master, p2pkh_pubkey_master, sizeof(hd_pubkey_master));
    }
    /* determine if mainnet or testnet/regtest */
    const dogecoin_chainparams* chain = is_testnet ? &dogecoin_chainparams_test : &dogecoin_chainparams_main;
    /* generate a new hd master key */
    if (!hd_gen_master(chain, hd_privkey_master, sizeof(hd_privkey_master))) {
        return false;
    }
    if (!generateDerivedHDPubkey(hd_privkey_master, hd_pubkey_master)) {
        return false;
    }
    if (wif_privkey_master) {
        memcpy_safe(wif_privkey_master, hd_privkey_master, sizeof(hd_privkey_master));
    }
    if (p2pkh_pubkey_master) {
        memcpy_safe(p2pkh_pubkey_master, hd_pubkey_master, sizeof(hd_pubkey_master));
    }
    return true;
}
References dogecoin_chainparams_main, dogecoin_chainparams_test, generateDerivedHDPubkey(), hd_gen_master(), HD_MASTERKEY_STRINGLEN, is_testnet, memcpy_safe(), and P2PKH_ADDR_STRINGLEN.
generatePrivPubKeypair()
int generatePrivPubKeypair (char * wif_privkey, char * p2pkh_pubkey, bool is_testnet)
This function generates a new basic public-private key pair for the specified network.
Parameters
wif_privkey The generated private key.
p2pkh_pubkey The generated public key.
is_testnet The flag denoting which network, 0 for mainnet and 1 for testnet.
Returns
1 if the key pair was generated successfully.
Definition at line 65 of file address.c.
{
    /* internal variables */
    char wif_privkey_internal[WIF_UNCOMPRESSED_PRIVKEY_STRINGLEN]; //MLUMIN: Keylength (51 or 52 chars, depending on uncompressed or compressed) +1 for string termination 'internally'?
    char p2pkh_pubkey_internal[P2PKH_ADDR_STRINGLEN]; //MLUMIN: no magic numbers. p2pkh address should be 34 characters, +1 though for string termination 'internally'?
    size_t privkey_len = sizeof(wif_privkey_internal);
    /* if nothing is passed in use internal variables */
    if (wif_privkey) {
        memcpy_safe(wif_privkey_internal, wif_privkey, sizeof(wif_privkey_internal));
    }
    if (p2pkh_pubkey) {
        memcpy_safe(p2pkh_pubkey_internal, p2pkh_pubkey, sizeof(p2pkh_pubkey_internal));
    }
    /* determine if mainnet or testnet/regtest */
    const dogecoin_chainparams* chain = is_testnet ? &dogecoin_chainparams_test : &dogecoin_chainparams_main;
    /* generate a new private key */
    dogecoin_key key;
    dogecoin_privkey_init(&key);
    dogecoin_privkey_gen(&key);
    dogecoin_privkey_encode_wif(&key, chain, wif_privkey_internal, &privkey_len);
    /* generate a new public key and export hex */
    dogecoin_pubkey pubkey;
    dogecoin_pubkey_init(&pubkey);
    assert(dogecoin_pubkey_is_valid(&pubkey) == 0);
    dogecoin_pubkey_from_key(&key, &pubkey);
    /* export p2pkh_pubkey address */
    dogecoin_pubkey_getaddr_p2pkh(&pubkey, chain, p2pkh_pubkey_internal);
    if (wif_privkey) {
        memcpy_safe(wif_privkey, wif_privkey_internal, sizeof(wif_privkey_internal));
    }
    if (p2pkh_pubkey) {
        memcpy_safe(p2pkh_pubkey, p2pkh_pubkey_internal, sizeof(p2pkh_pubkey_internal));
    }
    /* reset internal variables */
    dogecoin_mem_zero(wif_privkey_internal, strlen(wif_privkey_internal));
    dogecoin_mem_zero(p2pkh_pubkey_internal, strlen(p2pkh_pubkey_internal));
    /* cleanup memory */
    dogecoin_pubkey_cleanse(&pubkey);
    dogecoin_privkey_cleanse(&key);
    return true;
}
References dogecoin_chainparams_main, dogecoin_chainparams_test, dogecoin_mem_zero(), dogecoin_privkey_cleanse(), dogecoin_privkey_encode_wif(), dogecoin_privkey_gen(), dogecoin_privkey_init(), dogecoin_pubkey_cleanse(), dogecoin_pubkey_from_key(), dogecoin_pubkey_getaddr_p2pkh(), dogecoin_pubkey_init(), dogecoin_pubkey_is_valid(), is_testnet, memcpy_safe(), P2PKH_ADDR_STRINGLEN, and WIF_UNCOMPRESSED_PRIVKEY_STRINGLEN.
generateRandomEnglishMnemonic()
int generateRandomEnglishMnemonic (const ENTROPY_SIZE size, MNEMONIC mnemonic)
This function generates a random English mnemonic phrase.
Parameters
size The size of entropy in bits.
mnemonic The mnemonic code words.
Returns
0 (success), -1 (fail)
Definition at line 808 of file bip39.c.
{
    /* generate an English mnemonic without random entropy */
    return generateEnglishMnemonic (NULL, size, mnemonic);
}
References generateEnglishMnemonic().
get_raw_transaction()
char * get_raw_transaction (int txindex)
This function takes an index of a working transaction and returns the hex representation of it.
Parameters
txindex The index of the working transaction.
Returns
The hex representation of the transaction.
Definition at line 432 of file transaction.c.
{
    // find working transaction by index and pass to function local variable to manipulate:
    working_transaction* tx = find_transaction(txindex);
    // guard against null pointer exceptions
    if (tx == NULL) return false;
    // new allocated cstring to store hexadeicmal buffer string:
    cstring* serialized_transaction = cstr_new_sz(1024);
    // serialize transaction object to new cstring:
    dogecoin_tx_serialize(serialized_transaction, tx->transaction);
    char* hexadecimal_buffer = utils_uint8_to_hex((unsigned char*)serialized_transaction->str, serialized_transaction->len);
    cstr_free(serialized_transaction, true);
    return hexadecimal_buffer;
}
getDerivedHDAddress()
int getDerivedHDAddress (const char * masterkey, uint32_t account, bool ischange, uint32_t addressindex, char * outaddress, bool outprivkey)
This function generates a derived child address from a masterkey using a BIP44 standardized static, non hardened path comprised of an account, a change or receiving address and an address index.
Parameters
masterkey The master key from which children are derived from.
account The account that the derived address would belong to.
ischange Boolean value representing either a change or receiving address.
addressindex The index of the receiving/change address per account.
outaddress The derived address.
outprivkey The boolean value used to derive either a public or private address. 'true' for private, 'false' for public
Returns
1 if a derived address was successfully generated, 0 otherwise.
Definition at line 375 of file address.c.
{
        if (!masterkey) {
            debug_print("%s", "no extended key\n");
            return false;
        }
        char derived_path[DERIVED_PATH_STRINGLEN];
        int derived_path_size = snprintf(derived_path, sizeof(derived_path), "m/44'/3'/%u'/%u/%u", account, ischange, addressindex);
        if (derived_path_size >= (int)sizeof(derived_path)) {
            debug_print("%s", "derivation path overflow\n");
            return false;
        }
        int ret = getDerivedHDAddressByPath(masterkey, derived_path, outaddress, outprivkey);
        return ret;
}
References debug_print, DERIVED_PATH_STRINGLEN, and getDerivedHDAddressByPath().
getDerivedHDAddressByPath()
int getDerivedHDAddressByPath (const char * masterkey, const char * derived_path, char * outaddress, bool outprivkey)
This function generates a derived child key from a masterkey using a custom derived path in string format.
Parameters
masterkey The master key from which children are derived from.
derived_path The path to derive an address from according to BIP-44. e.g. m/44'/3'/1'/1/1 representing m/44'/3'/account'/ischange/index
outaddress The derived address.
outprivkey The boolean value used to derive either a public or private address. 'true' for private, 'false' for public
Returns
1 if a derived address was successfully generated, 0 otherwise
Definition at line 333 of file address.c.
{
    if (!masterkey || !derived_path || !outaddress) {
        debug_print("%s", "missing input\n");
        return false;
    }
    /* determine if mainnet or testnet/regtest */
    const dogecoin_chainparams* chain = chain_from_b58_prefix(masterkey);
    bool ret = true;
    dogecoin_hdnode node, nodenew;
    if (!dogecoin_hdnode_deserialize(masterkey, chain, &node)) {
        ret = false;
    }
    // dogecoin_hdnode_has_privkey
    bool pubckd = !dogecoin_hdnode_has_privkey(&node);
    /* derive child key, use pubckd or privckd */
    if (!dogecoin_hd_generate_key(&nodenew, derived_path, pubckd ? node.public_key : node.private_key, node.chain_code, pubckd)) {
        ret = false;
    }
    if (outprivkey) dogecoin_hdnode_serialize_private(&nodenew, chain, outaddress, HD_MASTERKEY_STRINGLEN);
    else dogecoin_hdnode_serialize_public(&nodenew, chain, outaddress, HD_MASTERKEY_STRINGLEN);
    return ret;
}
References dogecoin_hdnode::chain_code, chain_from_b58_prefix(), debug_print, dogecoin_hd_generate_key(), dogecoin_hdnode_deserialize(), dogecoin_hdnode_has_privkey(), dogecoin_hdnode_serialize_private(), dogecoin_hdnode_serialize_public(), HD_MASTERKEY_STRINGLEN, dogecoin_hdnode::private_key, and dogecoin_hdnode::public_key.
Referenced by getDerivedHDAddress().
getDerivedHDAddressFromMnemonic()
int getDerivedHDAddressFromMnemonic (const uint32_t account, const uint32_t index, const CHANGE_LEVEL change_level, const MNEMONIC mnemonic, const PASS pass, char * p2pkh_pubkey, const bool is_testnet)
new_eckey()
eckey * new_eckey ()
qrgen_p2pkh_consoleprint_to_qr()
void qrgen_p2pkh_consoleprint_to_qr (char * in_p2pkh)
qrgen_p2pkh_to_qr_string()
int qrgen_p2pkh_to_qr_string (const char * in_p2pkh, char * outString)
Definition at line 62 of file qrengine.c.
{
    uint8_t temparray[qrcodegen_BUFFER_LEN_MAX];
    stringToQrArray(in_p2pkh, temparray);
    outputQRStringFromQRBytes(temparray, outString);
    return 0;
}
qrgen_p2pkh_to_qrbits()
int qrgen_p2pkh_to_qrbits (const char * in_p2pkh, uint8_t * outQrByteArray)
Definition at line 71 of file qrengine.c.
{
    int size = qrcodegen_getSize(outQrByteArray);
    stringToQrArray(in_p2pkh,outQrByteArray);
    return size;
}
qrgen_string_to_qr_jpgfile()
int qrgen_string_to_qr_jpgfile (const char * outFilename, const char * inString, uint8_t sizeMultiplier)
Definition at line 223 of file qrengine.c.
{
    if (sizeMultiplier < 1)
    {
        sizeMultiplier = 1;
    }
    const uint8_t* jpg;
    int jpgsize;
    unsigned width;
    unsigned height;
    uint8_t tempBuffer[qrcodegen_BUFFER_LEN_MAX];
    uint8_t qrcode[qrcodegen_BUFFER_LEN_MAX];
    bool codeGenerated = qrcodegen_encodeText(inString, tempBuffer, qrcode, qrcodegen_Ecc_MEDIUM, qrcodegen_VERSION_MIN, qrcodegen_VERSION_MAX, qrcodegen_Mask_AUTO, true);
    if (codeGenerated)
    {
        unsigned tempSideDim = qrcodegen_getSize(qrcode);
        width = tempSideDim * sizeMultiplier;
        height = tempSideDim * sizeMultiplier;
        // bytes to monobitmap with sizemodifier
        uint8_t* image = bytesToMono(qrcode, sizeMultiplier);
        //encode jpeg
        jpec_enc_t* enc = jpec_enc_new(image, width, height);
        jpg = jpec_enc_run(enc, &jpgsize);
        FILE* file = fopen(outFilename, "wb");
        fwrite(jpg, sizeof(uint8_t), jpgsize, file);
        fclose(file);
        jpec_enc_del(enc);
        free(image);
        return jpgsize;
    }
    else
    {
        printf("Error generating QR\n");
        return -1;
    }
}
qrgen_string_to_qr_pngfile()
int qrgen_string_to_qr_pngfile (const char * outFilename, const char * inString, uint8_t sizeMultiplier)
Definition at line 173 of file qrengine.c.
{
    if (sizeMultiplier<1)
    {
        sizeMultiplier = 1;
    }
    unsigned char* png;
    size_t pngsize;
    unsigned width;
    unsigned height;
    uint8_t tempBuffer[qrcodegen_BUFFER_LEN_MAX];
    uint8_t qrcode[qrcodegen_BUFFER_LEN_MAX];
    bool codeGenerated = qrcodegen_encodeText(inString, tempBuffer, qrcode, qrcodegen_Ecc_MEDIUM, qrcodegen_VERSION_MIN, qrcodegen_VERSION_MAX, qrcodegen_Mask_AUTO, true);
    if (codeGenerated)
    {
        unsigned tempSideDim = qrcodegen_getSize(qrcode);
        width = tempSideDim * sizeMultiplier;
        height = tempSideDim * sizeMultiplier;
        // bytes to rgb
        uint8_t* image = bytesToRgb(qrcode, sizeMultiplier);
        unsigned error = lodepng_encode24(&png, &pngsize, image, width, height);
        if (!error)
        {
            lodepng_save_file(png, pngsize, outFilename);
            free(png);
            free(image);
            return (int)pngsize;
        }
       else
        {
            printf("png error %u: %s\n", error, lodepng_error_text(error));
            free(png);
            free(image);
            return -1;
        }
    }
    else
    {
        printf("Error generating QR\n");
        return -1;
    }
}
remove_all()
void remove_all ()
This function removes all working transactions from the hash table.
Returns
Nothing.
Definition at line 103 of file transaction.c.
                  {
    struct working_transaction *current_tx;
    struct working_transaction *tmp;
    HASH_ITER(hh, transactions, current_tx, tmp) {
        remove_transaction(current_tx);
    }
}
remove_eckey()
void remove_eckey (eckey * key)
This function removes the specified working eckey from the hash table and frees the keys in memory.
Parameters
key The pointer to the eckey to remove.
Returns
Nothing.
Definition at line 131 of file eckey.c.
{
    HASH_DEL(keys, key); /* delete it (keys advances to next) */
    dogecoin_privkey_cleanse(&key->private_key);
    dogecoin_pubkey_cleanse(&key->public_key);
    dogecoin_key_free(key);
}
References dogecoin_key_free(), dogecoin_privkey_cleanse(), dogecoin_pubkey_cleanse(), HASH_DEL, keys, eckey::private_key, and eckey::public_key.
sign_message()
char * sign_message (char * privkey, char * msg)
Sign message with private key.
Parameters
privkey The key to sign the message with.
message The message to be signed.
Returns
Base64 encoded signature if successful, False (0) if not
Definition at line 61 of file sign.c.
{
    if (!privkey || !msg) return false;
    uint256 message_bytes;
    hash_message(msg, message_bytes);
    size_t compact_signature_length = 65;
    unsigned char* compact_signature = dogecoin_uchar_vla(compact_signature_length);
    dogecoin_key key;
    dogecoin_pubkey pubkey;
    if (!init_keypair(privkey, &key, &pubkey)) return false;
    int recid = -1;
    if (!dogecoin_key_sign_hash_compact_recoverable_fcomp(&key, message_bytes, compact_signature, &compact_signature_length, &recid)) return false;
    if (!dogecoin_key_recover_pubkey((const unsigned char*)compact_signature, message_bytes, recid, &pubkey)) return false;
    char p2pkh_address[35];
    if (!dogecoin_pubkey_getaddr_p2pkh(&pubkey, &dogecoin_chainparams_main, p2pkh_address)) return false;
    unsigned char* base64_encoded_output = dogecoin_uchar_vla(1+(sizeof(char)*base64_encoded_size(compact_signature_length)));
    base64_encode((unsigned char*)compact_signature, compact_signature_length, base64_encoded_output);
    dogecoin_free(compact_signature);
    dogecoin_privkey_cleanse(&key);
    dogecoin_pubkey_cleanse(&pubkey);
    return (char*)base64_encoded_output;
}
sign_raw_transaction()
int sign_raw_transaction (int inputindex, char * incomingrawtx, char * scripthex, int sighashtype, char * privkey)
This function signs the specified input of a working transaction, according to the signing parameters specified.
Parameters
inputindex The index of the current transaction input to sign.
incomingrawtx The hex representation of the transaction to sign.
scripthex The hex representation of the public key script.
sighashtype The type of signature hash to perform.
privkey The private key used to sign the transaction input.
Returns
1 if the raw transaction was signed successfully, 0 otherwise.
Definition at line 479 of file transaction.c.
{
    if(!incomingrawtx || !scripthex) return false;
    if (strlen(incomingrawtx) > 1024*100) { //don't accept tx larger then 100kb
        printf("tx too large (max 100kb)\n");
        return false;
    }
    const dogecoin_chainparams* chain = (privkey[0] == 'c') ? &dogecoin_chainparams_test : &dogecoin_chainparams_main;
    // deserialize transaction
    dogecoin_tx* txtmp = dogecoin_tx_new();
    uint8_t* data_bin = dogecoin_malloc(strlen(incomingrawtx) / 2);
    size_t outlength = 0;
    // convert incomingrawtx to byte array to dogecoin_tx and if it fails free from memory
    utils_hex_to_bin(incomingrawtx, data_bin, strlen(incomingrawtx), &outlength);
    if (!dogecoin_tx_deserialize(data_bin, outlength, txtmp, NULL)) {
        // free byte array
        dogecoin_free(data_bin);
        // free dogecoin_tx
        dogecoin_tx_free(txtmp);
        printf("invalid tx hex\n");
        return false;
    }
    // free byte array
    dogecoin_free(data_bin);
    // if utxo input doesn't exist abort attempt to sign message
    if ((size_t)inputindex >= txtmp->vin->len) {
        // free dogecoin_tx
        dogecoin_tx_free(txtmp);
        printf("input index out of range");
        return false;
    }
    // initialize byte array with length equal to account for byte size
    uint8_t* script_data = dogecoin_uint8_vla(strlen(scripthex));
    // convert hex string to byte array
    utils_hex_to_bin(scripthex, script_data, strlen(scripthex), &outlength);
    cstring* script = cstr_new_buf(script_data, outlength);
    uint256 sighash;
    dogecoin_mem_zero(sighash, sizeof(sighash));
    free(script_data);
    dogecoin_tx_sighash(txtmp, script, inputindex, sighashtype, sighash);
    char *hex = utils_uint8_to_hex(sighash, 32);
    utils_reverse_hex(hex, 64);
    debug_print("script: %s\n", scripthex);
    debug_print("script-type: %s\n", dogecoin_tx_out_type_to_str(dogecoin_script_classify(script, NULL)));
    debug_print("inputindex: %d\n", inputindex);
    debug_print("sighashtype: %d\n", sighashtype);
    debug_print("hash: %s\n", hex);
    // sign
    dogecoin_bool sign = false;
    dogecoin_key key;
    dogecoin_privkey_init(&key);
    if (dogecoin_privkey_decode_wif(privkey, chain, &key)) {
        sign = true;
    } else {
        if (privkey) {
            if (strlen(privkey) > 50) {
                dogecoin_tx_free(txtmp);
                cstr_free(script, true);
                return false;
            }
        } else {
            return false;
        }
    }
    if (sign) {
        uint8_t sigcompact[64] = {0};
        size_t sigderlen = 74 + 1; //&hashtype
        uint8_t sigder_plus_hashtype[75] = {0};
        enum dogecoin_tx_sign_result res = dogecoin_tx_sign_input(txtmp, script, &key, inputindex, sighashtype, sigcompact, sigder_plus_hashtype, &sigderlen);
        cstr_free(script, true);
        if (res != DOGECOIN_SIGN_OK) return false;
        char sigcompacthex[64*2+1] = {0};
        utils_bin_to_hex((unsigned char *)sigcompact, 64, sigcompacthex);
        char sigderhex[74*2+2+1]; //74 der, 2 hashtype, 1 nullbyte
        dogecoin_mem_zero(sigderhex, sizeof(sigderhex));
        utils_bin_to_hex((unsigned char *)sigder_plus_hashtype, sigderlen, sigderhex);
        debug_print("\nsignature created:\nsignature compact: %s\n", sigcompacthex);
        debug_print("signature DER (+hashtype): %s\n", sigderhex);
        cstring* signed_tx = cstr_new_sz(1024);
        dogecoin_tx_serialize(signed_tx, txtmp);
        char* signed_tx_hex = dogecoin_char_vla(signed_tx->len * 2 + 1);
        utils_bin_to_hex((unsigned char *)signed_tx->str, signed_tx->len, signed_tx_hex);
        memcpy(incomingrawtx, signed_tx_hex, strlen(signed_tx_hex));
        debug_print("signed TX: %s\n", incomingrawtx);
        cstr_free(signed_tx, true);
        dogecoin_tx_free(txtmp);
        free(signed_tx_hex);
    }
    return true;
}
sign_transaction()
int sign_transaction (int txindex, char * script_pubkey, char * privkey)
This function signs all of the inputs in the specified working transaction using the provided script pubkey and private key.
Parameters
txindex The index of the working transaction to sign.
script_pubkey The hex representation of the public key script.
privkey The private key used to sign the transaction input.
Returns
1 if the transaction was signed successfully, 0 otherwise.
Definition at line 621 of file transaction.c.
{
    char* raw_hexadecimal_transaction = get_raw_transaction(txindex);
    // deserialize transaction
    dogecoin_tx* txtmp = dogecoin_tx_new();
    uint8_t* data_bin = dogecoin_malloc(strlen(raw_hexadecimal_transaction) / 2);
    size_t outlength = 0;
    // convert incomingrawtx to byte array to dogecoin_tx and if it fails free from memory
    utils_hex_to_bin(raw_hexadecimal_transaction, data_bin, strlen(raw_hexadecimal_transaction), &outlength);
    if (!dogecoin_tx_deserialize(data_bin, outlength, txtmp, NULL)) {
        // free byte array
        dogecoin_free(data_bin);
        // free dogecoin_tx
        dogecoin_tx_free(txtmp);
        printf("invalid tx hex\n");
        return false;
    }
    // free byte array
    dogecoin_free(data_bin);
    size_t i = 0, len = txtmp->vin->len;
    for (; i < len; i++) {
        if (!sign_raw_transaction(i, raw_hexadecimal_transaction, script_pubkey, 1, privkey)) {
            printf("error signing raw transaction\n");
            return false;
        }
    }
    save_raw_transaction(txindex, raw_hexadecimal_transaction);
    dogecoin_tx_free(txtmp);
    return true;
}
start_key()
int start_key ()
start_transaction()
int start_transaction ()
This function creates a new transaction, places it in the hash table, and returns the index of the new transaction, starting from 1 and incrementing each subsequent call.
Returns
The index of the new transaction.
Definition at line 227 of file transaction.c.
{
    working_transaction* working_tx = new_transaction();
    int index = working_tx->idx;
    add_transaction(working_tx);
    return index;
}
store_raw_transaction()
int store_raw_transaction (char * incomingrawtx)
This function stores a raw transaction to the next available working transaction in the hash table.
Parameters
incomingrawtx The hex of the raw transaction
Returns
The index of the new working transaction if stored successfully, 0 otherwise.
Definition at line 659 of file transaction.c.
{
    if (strlen(incomingrawtx) > 1024*100) { //don't accept tx larger then 100kb
        printf("tx too large (max 100kb)\n");
        return false;
    }
    // deserialize transaction
    dogecoin_tx* txtmp = dogecoin_tx_new();
    int txindex = start_transaction();
    working_transaction* tx_raw = find_transaction(txindex);
    uint8_t* data_bin = dogecoin_malloc(strlen(incomingrawtx));
    size_t outlength = 0;
    // convert incomingrawtx to byte array to dogecoin_tx and if it fails free from memory
    utils_hex_to_bin(incomingrawtx, data_bin, strlen(incomingrawtx), &outlength);
    if (!dogecoin_tx_deserialize(data_bin, outlength, txtmp, NULL)) {
        // free byte array
        dogecoin_free(data_bin);
        // free dogecoin_tx
        dogecoin_tx_free(txtmp);
        printf("invalid tx hex");
        return false;
    }
    // free byte array
    dogecoin_free(data_bin);
    dogecoin_tx_copy(tx_raw->transaction, txtmp);
    dogecoin_tx_free(txtmp);
    return txindex;
}
verify_message()
int verify_message (char * sig, char * msg, char * address)
Verify signed message using non BIP32 encoded address.
Parameters
sig
msg
address
Returns
P2PKH address if successful, False (0) otherwise
Definition at line 102 of file sign.c.
{
    if (!(sig || msg || address)) return false;
    uint256 message_bytes;
    hash_message(msg, message_bytes);
    size_t encoded_length = strlen((const char*)sig);
    unsigned char* decoded_signature = dogecoin_uchar_vla(base64_decoded_size(encoded_length+1)+1);
    base64_decode((unsigned char*)sig, encoded_length, decoded_signature);
    dogecoin_pubkey pub_key;
    dogecoin_pubkey_init(&pub_key);
    pub_key.compressed = false;
    int header = decoded_signature[0] & 0xFF;
    if (header < 27 || header > 42) return false;
    if (header >= 31) {
        pub_key.compressed = true;
        header -= 4;
    }
    int recid = header - 27;
    if (!dogecoin_key_recover_pubkey((const unsigned char*)decoded_signature, message_bytes, recid, &pub_key)) return false;
    if (!dogecoin_pubkey_verify_sigcmp(&pub_key, message_bytes, decoded_signature)) return false;
    char p2pkh_address[35];
    const dogecoin_chainparams* chain = chain_from_b58_prefix(address);
    if (!dogecoin_pubkey_getaddr_p2pkh(&pub_key, chain, p2pkh_address)) return false;
    dogecoin_free(decoded_signature);
    dogecoin_pubkey_cleanse(&pub_key);
    return strcmp(p2pkh_address, address)==0;
}
verifyHDMasterPubKeypair()
int verifyHDMasterPubKeypair (char * wif_privkey_master, char * p2pkh_pubkey_master, bool is_testnet)
This function verifies that a given HD master private key matches a given HD master public key and that both are valid on the specified network.
Parameters
is_testnet The flag denoting which network, 0 for mainnet and 1 for testnet.
wif_privkey_master The master private key to check.
p2pkh_pubkey_master The master public key to check.
Returns
1 if the keys match and are valid on the specified network, 0 otherwise.
Definition at line 268 of file address.c.
{
    /* require both private and public key */
    if (!wif_privkey_master || !p2pkh_pubkey_master) return false;
    /* determine if mainnet or testnet/regtest */
    const dogecoin_chainparams* chain = is_testnet ? &dogecoin_chainparams_test : &dogecoin_chainparams_main;
    /* calculate master pubkey from master privkey */
    dogecoin_hdnode node;
    dogecoin_hdnode_deserialize(wif_privkey_master, chain, &node);
    char new_p2pkh_pubkey_master[HD_MASTERKEY_STRINGLEN];
    dogecoin_hdnode_get_p2pkh_address(&node, chain, new_p2pkh_pubkey_master, sizeof(new_p2pkh_pubkey_master));
    /* compare derived and given pubkeys */
    if (strcmp(p2pkh_pubkey_master, new_p2pkh_pubkey_master)) return false;
    return true;
}
References dogecoin_chainparams_main, dogecoin_chainparams_test, dogecoin_hdnode_deserialize(), dogecoin_hdnode_get_p2pkh_address(), HD_MASTERKEY_STRINGLEN, and is_testnet.
verifyP2pkhAddress()
int verifyP2pkhAddress (char * p2pkh_pubkey, size_t len)
This function takes a public key and does some basic validation to determine if it is a valid Dogecoin address.
Parameters
p2pkh_pubkey The address to check.
len The length of the address in characters.
Returns
1 if it is a valid Dogecoin address, 0 otherwise.
Definition at line 296 of file address.c.
{
    if (!p2pkh_pubkey || !len) return false;
    /* check length */
    unsigned char* dec = dogecoin_uchar_vla(len);
    unsigned char d1[SHA256_DIGEST_LENGTH];
    unsigned char d2[SHA256_DIGEST_LENGTH];
    if (!dogecoin_base58_decode_check(p2pkh_pubkey, dec, len))
    {
        free(dec);
        return false;
    }
    /* check validity */
    sha256_raw(dec, 21, d1);
    sha256_raw(d1, SHA256_DIGEST_LENGTH, d2);
    if (memcmp(dec + 21, d2, 4) != 0)
    {
        free(dec);
        return false;
    }
    free(dec);
    return true;
}
References dogecoin_base58_decode_check(), dogecoin_uchar_vla(), SHA256_DIGEST_LENGTH, and sha256_raw().
Referenced by transaction_output_menu().
verifyPrivPubKeypair()
int verifyPrivPubKeypair (char * wif_privkey, char * p2pkh_pubkey, bool is_testnet)
This function verifies that a given private key matches a given public key and that both are valid on the specified network.
Parameters
wif_privkey The private key to check.
p2pkh_pubkey The public key to check.
is_testnet The flag denoting which network, 0 for mainnet and 1 for testnet.
Returns
1 if the keys match and are valid on the specified network, 0 otherwise.
Definition at line 219 of file address.c.
{
    /* require both private and public key */
    if (!wif_privkey || !p2pkh_pubkey) return false;
    /* set chain */
    const dogecoin_chainparams* chain = is_testnet ? &dogecoin_chainparams_test : &dogecoin_chainparams_main;
    /* verify private key */
    dogecoin_key key;
    dogecoin_privkey_init(&key);
    dogecoin_privkey_decode_wif(wif_privkey, chain, &key);
    if (!dogecoin_privkey_is_valid(&key)) return false;
    char new_wif_privkey[WIF_UNCOMPRESSED_PRIVKEY_STRINGLEN];
    size_t sizeout = sizeof(new_wif_privkey);
    dogecoin_privkey_encode_wif(&key, chain, new_wif_privkey, &sizeout);
    /* verify public key */
    dogecoin_pubkey pubkey;
    dogecoin_pubkey_init(&pubkey);
    dogecoin_pubkey_from_key(&key, &pubkey);
    if (!dogecoin_pubkey_is_valid(&pubkey)) return false;
    /* verify address derived matches provided address */
    char* new_p2pkh_pubkey = dogecoin_char_vla(sizeout);
    dogecoin_pubkey_getaddr_p2pkh(&pubkey, chain, new_p2pkh_pubkey);
    if (strcmp(p2pkh_pubkey, new_p2pkh_pubkey))
    {
        free(new_p2pkh_pubkey);
        return false;
    }
    dogecoin_pubkey_cleanse(&pubkey);
    dogecoin_privkey_cleanse(&key);
    free(new_p2pkh_pubkey);
    return true;
}
References dogecoin_chainparams_main, dogecoin_chainparams_test, dogecoin_char_vla(), dogecoin_privkey_cleanse(), dogecoin_privkey_decode_wif(), dogecoin_privkey_encode_wif(), dogecoin_privkey_init(), dogecoin_privkey_is_valid(), dogecoin_pubkey_cleanse(), dogecoin_pubkey_from_key(), dogecoin_pubkey_getaddr_p2pkh(), dogecoin_pubkey_init(), dogecoin_pubkey_is_valid(), is_testnet, and WIF_UNCOMPRESSED_PRIVKEY_STRINGLEN.
Variable Documentation
keys
eckey* keys = NULL static
Definition at line 208 of file libdogecoin.h.