libdogecoin: src/libevent/buffer.c File Reference
buffer.c File Reference
#include "event2/event-config.h"
#include "evconfig-private.h"
#include <sys/types.h>
#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include "event2/event.h"
#include "event2/buffer.h"
#include "event2/buffer_compat.h"
#include "event2/bufferevent.h"
#include "event2/bufferevent_compat.h"
#include "event2/bufferevent_struct.h"
#include "event2/thread.h"
#include "log-internal.h"
#include "mm-internal.h"
#include "util-internal.h"
#include "evthread-internal.h"
#include "evbuffer-internal.h"
#include "bufferevent-internal.h"
#include "event-internal.h"
Macros
#define MAP_FAILED ((void *)-1)
#define EVBUFFER_CB_USER_FLAGS 0xffff
#define EVBUFFER_CB_INTERNAL_FLAGS 0xffff0000
#define EVBUFFER_CB_OBSOLETE 0x00040000
#define CHAIN_SPACE_PTR(ch) ((ch)->buffer + (ch)->misalign + (ch)->off)
#define CHAIN_SPACE_LEN(ch)
#define CHAIN_PINNED(ch) (((ch)->flags & EVBUFFER_MEM_PINNED_ANY) != 0)
#define CHAIN_PINNED_R(ch) (((ch)->flags & EVBUFFER_MEM_PINNED_R) != 0)
#define PTR_NOT_FOUND(ptr)
#define CHUNK_SZ 128
#define EVBUFFER_CHAIN_MAX_AUTO_SIZE 4096
#define MAX_TO_COPY_IN_EXPAND 4096
#define MAX_TO_REALIGN_IN_EXPAND 2048
#define NUM_READ_IOVEC 4
#define EVBUFFER_MAX_READ 4096
#define va_copy(dst, src) memcpy(&(dst), &(src), sizeof(va_list))
Functions
static void evbuffer_chain_align (struct evbuffer_chain *chain)
static int evbuffer_chain_should_realign (struct evbuffer_chain *chain, size_t datalen)
static void evbuffer_deferred_callback (struct event_callback *cb, void *arg)
static int evbuffer_ptr_memcmp (const struct evbuffer *buf, const struct evbuffer_ptr *pos, const char *mem, size_t len)
static struct evbuffer_chain * evbuffer_expand_singlechain (struct evbuffer *buf, size_t datlen)
static int evbuffer_ptr_subtract (struct evbuffer *buf, struct evbuffer_ptr *pos, size_t howfar)
static int evbuffer_file_segment_materialize (struct evbuffer_file_segment *seg)
static void evbuffer_chain_incref (struct evbuffer_chain *chain)
static struct evbuffer_chain * evbuffer_chain_new (size_t size)
static void evbuffer_chain_free (struct evbuffer_chain *chain)
static void evbuffer_free_all_chains (struct evbuffer_chain *chain)
static int evbuffer_chains_all_empty (struct evbuffer_chain *chain)
static struct evbuffer_chain ** evbuffer_free_trailing_empty_chains (struct evbuffer *buf)
static void evbuffer_chain_insert (struct evbuffer *buf, struct evbuffer_chain *chain)
static struct evbuffer_chain * evbuffer_chain_insert_new (struct evbuffer *buf, size_t datlen)
void evbuffer_chain_pin_ (struct evbuffer_chain *chain, unsigned flag)
void evbuffer_chain_unpin_ (struct evbuffer_chain *chain, unsigned flag)
struct evbuffer * evbuffer_new (void)
int evbuffer_set_flags (struct evbuffer *buf, ev_uint64_t flags)
int evbuffer_clear_flags (struct evbuffer *buf, ev_uint64_t flags)
void evbuffer_incref_ (struct evbuffer *buf)
void evbuffer_incref_and_lock_ (struct evbuffer *buf)
int evbuffer_defer_callbacks (struct evbuffer *buffer, struct event_base *base)
int evbuffer_enable_locking (struct evbuffer *buf, void *lock)
void evbuffer_set_parent_ (struct evbuffer *buf, struct bufferevent *bev)
static void evbuffer_run_callbacks (struct evbuffer *buffer, int running_deferred)
void evbuffer_invoke_callbacks_ (struct evbuffer *buffer)
static void evbuffer_remove_all_callbacks (struct evbuffer *buffer)
void evbuffer_decref_and_unlock_ (struct evbuffer *buffer)
void evbuffer_free (struct evbuffer *buffer)
void evbuffer_lock (struct evbuffer *buf)
void evbuffer_unlock (struct evbuffer *buf)
size_t evbuffer_get_length (const struct evbuffer *buffer)
size_t evbuffer_get_contiguous_space (const struct evbuffer *buf)
size_t evbuffer_add_iovec (struct evbuffer *buf, struct evbuffer_iovec *vec, int n_vec)
int evbuffer_reserve_space (struct evbuffer *buf, ev_ssize_t size, struct evbuffer_iovec *vec, int n_vecs)
static int advance_last_with_data (struct evbuffer *buf)
int evbuffer_commit_space (struct evbuffer *buf, struct evbuffer_iovec *vec, int n_vecs)
static int HAS_PINNED_R (struct evbuffer *buf)
static void ZERO_CHAIN (struct evbuffer *dst)
static int PRESERVE_PINNED (struct evbuffer *src, struct evbuffer_chain **first, struct evbuffer_chain **last)
static void RESTORE_PINNED (struct evbuffer *src, struct evbuffer_chain *pinned, struct evbuffer_chain *last)
static void COPY_CHAIN (struct evbuffer *dst, struct evbuffer *src)
static void APPEND_CHAIN (struct evbuffer *dst, struct evbuffer *src)
static void APPEND_CHAIN_MULTICAST (struct evbuffer *dst, struct evbuffer *src)
static void PREPEND_CHAIN (struct evbuffer *dst, struct evbuffer *src)
int evbuffer_add_buffer (struct evbuffer *outbuf, struct evbuffer *inbuf)
int evbuffer_add_buffer_reference (struct evbuffer *outbuf, struct evbuffer *inbuf)
int evbuffer_prepend_buffer (struct evbuffer *outbuf, struct evbuffer *inbuf)
int evbuffer_drain (struct evbuffer *buf, size_t len)
int evbuffer_remove (struct evbuffer *buf, void *data_out, size_t datlen)
ev_ssize_t evbuffer_copyout (struct evbuffer *buf, void *data_out, size_t datlen)
ev_ssize_t evbuffer_copyout_from (struct evbuffer *buf, const struct evbuffer_ptr *pos, void *data_out, size_t datlen)
int evbuffer_remove_buffer (struct evbuffer *src, struct evbuffer *dst, size_t datlen)
unsigned char * evbuffer_pullup (struct evbuffer *buf, ev_ssize_t size)
char * evbuffer_readline (struct evbuffer *buffer)
static ev_ssize_t evbuffer_strchr (struct evbuffer_ptr *it, const char chr)
static char * find_eol_char (char *s, size_t len)
static ev_ssize_t evbuffer_find_eol_char (struct evbuffer_ptr *it)
static size_t evbuffer_strspn (struct evbuffer_ptr *ptr, const char *chrset)
static int evbuffer_getchr (struct evbuffer_ptr *it)
struct evbuffer_ptr evbuffer_search_eol (struct evbuffer *buffer, struct evbuffer_ptr *start, size_t *eol_len_out, enum evbuffer_eol_style eol_style)
char * evbuffer_readln (struct evbuffer *buffer, size_t *n_read_out, enum evbuffer_eol_style eol_style)
int evbuffer_add (struct evbuffer *buf, const void *data_in, size_t datlen)
int evbuffer_prepend (struct evbuffer *buf, const void *data, size_t datlen)
int evbuffer_expand_fast_ (struct evbuffer *buf, size_t datlen, int n)
int evbuffer_expand (struct evbuffer *buf, size_t datlen)
int evbuffer_read_setup_vecs_ (struct evbuffer *buf, ev_ssize_t howmuch, struct evbuffer_iovec *vecs, int n_vecs_avail, struct evbuffer_chain ***chainp, int exact)
static int get_n_bytes_readable_on_socket (evutil_socket_t fd)
int evbuffer_read (struct evbuffer *buf, evutil_socket_t fd, int howmuch)
int evbuffer_write_atmost (struct evbuffer *buffer, evutil_socket_t fd, ev_ssize_t howmuch)
int evbuffer_write (struct evbuffer *buffer, evutil_socket_t fd)
unsigned char * evbuffer_find (struct evbuffer *buffer, const unsigned char *what, size_t len)
int evbuffer_ptr_set (struct evbuffer *buf, struct evbuffer_ptr *pos, size_t position, enum evbuffer_ptr_how how)
struct evbuffer_ptr evbuffer_search (struct evbuffer *buffer, const char *what, size_t len, const struct evbuffer_ptr *start)
struct evbuffer_ptr evbuffer_search_range (struct evbuffer *buffer, const char *what, size_t len, const struct evbuffer_ptr *start, const struct evbuffer_ptr *end)
int evbuffer_peek (struct evbuffer *buffer, ev_ssize_t len, struct evbuffer_ptr *start_at, struct evbuffer_iovec *vec, int n_vec)
int evbuffer_add_vprintf (struct evbuffer *buf, const char *fmt, va_list ap)
int evbuffer_add_printf (struct evbuffer *buf, const char *fmt,...)
int evbuffer_add_reference (struct evbuffer *outbuf, const void *data, size_t datlen, evbuffer_ref_cleanup_cb cleanupfn, void *extra)
struct evbuffer_file_segment * evbuffer_file_segment_new (int fd, ev_off_t offset, ev_off_t length, unsigned flags)
void evbuffer_file_segment_add_cleanup_cb (struct evbuffer_file_segment *seg, evbuffer_file_segment_cleanup_cb cb, void *arg)
void evbuffer_file_segment_free (struct evbuffer_file_segment *seg)
int evbuffer_add_file_segment (struct evbuffer *buf, struct evbuffer_file_segment *seg, ev_off_t offset, ev_off_t length)
int evbuffer_add_file (struct evbuffer *buf, int fd, ev_off_t offset, ev_off_t length)
int evbuffer_setcb (struct evbuffer *buffer, evbuffer_cb cb, void *cbarg)
struct evbuffer_cb_entry * evbuffer_add_cb (struct evbuffer *buffer, evbuffer_cb_func cb, void *cbarg)
int evbuffer_remove_cb_entry (struct evbuffer *buffer, struct evbuffer_cb_entry *ent)
int evbuffer_remove_cb (struct evbuffer *buffer, evbuffer_cb_func cb, void *cbarg)
int evbuffer_cb_set_flags (struct evbuffer *buffer, struct evbuffer_cb_entry *cb, ev_uint32_t flags)
int evbuffer_cb_clear_flags (struct evbuffer *buffer, struct evbuffer_cb_entry *cb, ev_uint32_t flags)
int evbuffer_freeze (struct evbuffer *buffer, int start)
int evbuffer_unfreeze (struct evbuffer *buffer, int start)
int evbuffer_get_callbacks_ (struct evbuffer *buffer, struct event_callback **cbs, int max_cbs)
Macro Definition Documentation
CHAIN_PINNED
#define CHAIN_PINNED (ch) (((ch)->flags & EVBUFFER_MEM_PINNED_ANY) != 0)
Definition at line 133 of file buffer.c.
CHAIN_PINNED_R
#define CHAIN_PINNED_R (ch) (((ch)->flags & EVBUFFER_MEM_PINNED_R) != 0)
Definition at line 134 of file buffer.c.
CHAIN_SPACE_LEN
#define CHAIN_SPACE_LEN (ch)
Value:
        ((ch)->flags & EVBUFFER_IMMUTABLE ? \
        0 : (ch)->buffer_len - ((ch)->misalign + (ch)->off))
Definition at line 130 of file buffer.c.
CHAIN_SPACE_PTR
#define CHAIN_SPACE_PTR (ch) ((ch)->buffer + (ch)->misalign + (ch)->off)
Definition at line 129 of file buffer.c.
CHUNK_SZ
#define CHUNK_SZ 128
EVBUFFER_CB_INTERNAL_FLAGS
#define EVBUFFER_CB_INTERNAL_FLAGS 0xffff0000
Definition at line 123 of file buffer.c.
EVBUFFER_CB_OBSOLETE
#define EVBUFFER_CB_OBSOLETE 0x00040000
Definition at line 126 of file buffer.c.
EVBUFFER_CB_USER_FLAGS
#define EVBUFFER_CB_USER_FLAGS 0xffff
Definition at line 121 of file buffer.c.
EVBUFFER_CHAIN_MAX_AUTO_SIZE
#define EVBUFFER_CHAIN_MAX_AUTO_SIZE 4096
Definition at line 1725 of file buffer.c.
EVBUFFER_MAX_READ
#define EVBUFFER_MAX_READ 4096
Definition at line 2209 of file buffer.c.
MAP_FAILED
#define MAP_FAILED ((void *)-1)
Definition at line 102 of file buffer.c.
MAX_TO_COPY_IN_EXPAND
#define MAX_TO_COPY_IN_EXPAND 4096
Definition at line 1922 of file buffer.c.
MAX_TO_REALIGN_IN_EXPAND
#define MAX_TO_REALIGN_IN_EXPAND 2048
Definition at line 1923 of file buffer.c.
NUM_READ_IOVEC
#define NUM_READ_IOVEC 4
Definition at line 2207 of file buffer.c.
PTR_NOT_FOUND
#define PTR_NOT_FOUND (ptr)
Value:
    do {            \
    (ptr)->pos = -1;                    \
    (ptr)->internal_.chain = NULL;      \
    (ptr)->internal_.pos_in_chain = 0;  \
} while (0)
Definition at line 137 of file buffer.c.
va_copy
#define va_copy (dst, src) memcpy(&(dst), &(src), sizeof(va_list))
Function Documentation
advance_last_with_data()
static int advance_last_with_data (struct evbuffer * buf) static
Definition at line 704 of file buffer.c.
{
    int n = 0;
    struct evbuffer_chain **chainp = buf->last_with_datap;
    ASSERT_EVBUFFER_LOCKED(buf);
    if (!*chainp)
        return 0;
    while ((*chainp)->next) {
        chainp = &(*chainp)->next;
        if ((*chainp)->off)
            buf->last_with_datap = chainp;
        ++n;
    }
    return n;
}
References ASSERT_EVBUFFER_LOCKED, evbuffer::last_with_datap, and evbuffer_chain::next.
Referenced by evbuffer_add_vprintf(), evbuffer_commit_space(), evbuffer_read(), and evbuffer_remove_buffer().
APPEND_CHAIN()
static void APPEND_CHAIN (struct evbuffer * dst, struct evbuffer * src) static
Definition at line 889 of file buffer.c.
{
    struct evbuffer_chain **chp;
    ASSERT_EVBUFFER_LOCKED(dst);
    ASSERT_EVBUFFER_LOCKED(src);
    chp = evbuffer_free_trailing_empty_chains(dst);
    *chp = src->first;
    if (src->last_with_datap == &src->first)
        dst->last_with_datap = chp;
    else
        dst->last_with_datap = src->last_with_datap;
    dst->last = src->last;
    dst->total_len += src->total_len;
}
References ASSERT_EVBUFFER_LOCKED, evbuffer_free_trailing_empty_chains(), evbuffer::first, evbuffer::last, evbuffer::last_with_datap, and evbuffer::total_len.
Referenced by evbuffer_add_buffer().
APPEND_CHAIN_MULTICAST()
static void APPEND_CHAIN_MULTICAST (struct evbuffer * dst, struct evbuffer * src) inline static
Definition at line 908 of file buffer.c.
{
    struct evbuffer_chain *tmp;
    struct evbuffer_chain *chain = src->first;
    struct evbuffer_multicast_parent *extra;
    ASSERT_EVBUFFER_LOCKED(dst);
    ASSERT_EVBUFFER_LOCKED(src);
    for (; chain; chain = chain->next) {
        if (!chain->off || chain->flags & EVBUFFER_DANGLING) {
            /* skip empty chains */
            continue;
        }
        tmp = evbuffer_chain_new(sizeof(struct evbuffer_multicast_parent));
        if (!tmp) {
            event_warn("%s: out of memory", __func__);
            return;
        }
        extra = EVBUFFER_CHAIN_EXTRA(struct evbuffer_multicast_parent, tmp);
        /* reference evbuffer containing source chain so it
         * doesn't get released while the chain is still
         * being referenced to */
        evbuffer_incref_(src);
        extra->source = src;
        /* reference source chain which now becomes immutable */
        evbuffer_chain_incref(chain);
        extra->parent = chain;
        chain->flags |= EVBUFFER_IMMUTABLE;
        tmp->buffer_len = chain->buffer_len;
        tmp->misalign = chain->misalign;
        tmp->off = chain->off;
        tmp->flags |= EVBUFFER_MULTICAST|EVBUFFER_IMMUTABLE;
        tmp->buffer = chain->buffer;
        evbuffer_chain_insert(dst, tmp);
    }
}
References __func__, ASSERT_EVBUFFER_LOCKED, evbuffer_chain::buffer, evbuffer_chain::buffer_len, EVBUFFER_CHAIN_EXTRA, evbuffer_chain_incref(), evbuffer_chain_insert(), evbuffer_chain_new(), EVBUFFER_DANGLING, EVBUFFER_IMMUTABLE, evbuffer_incref_(), EVBUFFER_MULTICAST, event_warn(), evbuffer::first, evbuffer_chain::flags, evbuffer_chain::misalign, evbuffer_chain::next, evbuffer_chain::off, evbuffer_multicast_parent::parent, and evbuffer_multicast_parent::source.
Referenced by evbuffer_add_buffer_reference().
COPY_CHAIN()
static void COPY_CHAIN (struct evbuffer * dst, struct evbuffer * src) inline static
Definition at line 875 of file buffer.c.
{
    ASSERT_EVBUFFER_LOCKED(dst);
    ASSERT_EVBUFFER_LOCKED(src);
    dst->first = src->first;
    if (src->last_with_datap == &src->first)
        dst->last_with_datap = &dst->first;
    else
        dst->last_with_datap = src->last_with_datap;
    dst->last = src->last;
    dst->total_len = src->total_len;
}
References ASSERT_EVBUFFER_LOCKED, evbuffer::first, evbuffer::last, evbuffer::last_with_datap, and evbuffer::total_len.
Referenced by evbuffer_add_buffer(), and evbuffer_prepend_buffer().
evbuffer_add()
int evbuffer_add (struct evbuffer * buf, const void * data_in, size_t datlen)
Definition at line 1730 of file buffer.c.
{
    struct evbuffer_chain *chain, *tmp;
    const unsigned char *data = data_in;
    size_t remain, to_alloc;
    int result = -1;
    EVBUFFER_LOCK(buf);
    if (buf->freeze_end) {
        goto done;
    }
    /* Prevent buf->total_len overflow */
    if (datlen > EV_SIZE_MAX - buf->total_len) {
        goto done;
    }
    if (*buf->last_with_datap == NULL) {
        chain = buf->last;
    } else {
        chain = *buf->last_with_datap;
    }
    /* If there are no chains allocated for this buffer, allocate one
     * big enough to hold all the data. */
    if (chain == NULL) {
        chain = evbuffer_chain_new(datlen);
        if (!chain)
            goto done;
        evbuffer_chain_insert(buf, chain);
    }
    if ((chain->flags & EVBUFFER_IMMUTABLE) == 0) {
        /* Always true for mutable buffers */
        EVUTIL_ASSERT(chain->misalign >= 0 &&
            (ev_uint64_t)chain->misalign <= EVBUFFER_CHAIN_MAX);
        remain = chain->buffer_len - (size_t)chain->misalign - chain->off;
        if (remain >= datlen) {
            /* there's enough space to hold all the data in the
             * current last chain */
            memcpy(chain->buffer + chain->misalign + chain->off,
                data, datlen);
            chain->off += datlen;
            buf->total_len += datlen;
            buf->n_add_for_cb += datlen;
            goto out;
        } else if (!CHAIN_PINNED(chain) &&
            evbuffer_chain_should_realign(chain, datlen)) {
            /* we can fit the data into the misalignment */
            evbuffer_chain_align(chain);
            memcpy(chain->buffer + chain->off, data, datlen);
            chain->off += datlen;
            buf->total_len += datlen;
            buf->n_add_for_cb += datlen;
            goto out;
        }
    } else {
        /* we cannot write any data to the last chain */
        remain = 0;
    }
    /* we need to add another chain */
    to_alloc = chain->buffer_len;
    if (to_alloc <= EVBUFFER_CHAIN_MAX_AUTO_SIZE/2)
        to_alloc <<= 1;
    if (datlen > to_alloc)
        to_alloc = datlen;
    tmp = evbuffer_chain_new(to_alloc);
    if (tmp == NULL)
        goto done;
    if (remain) {
        memcpy(chain->buffer + chain->misalign + chain->off,
            data, remain);
        chain->off += remain;
        buf->total_len += remain;
        buf->n_add_for_cb += remain;
    }
    data += remain;
    datlen -= remain;
    memcpy(tmp->buffer, data, datlen);
    tmp->off = datlen;
    evbuffer_chain_insert(buf, tmp);
    buf->n_add_for_cb += datlen;
out:
    evbuffer_invoke_callbacks_(buf);
    result = 0;
done:
    EVBUFFER_UNLOCK(buf);
    return result;
}
References evbuffer_chain::buffer, evbuffer_chain::buffer_len, CHAIN_PINNED, evbuffer_chain_align(), evbuffer_chain_insert(), EVBUFFER_CHAIN_MAX, EVBUFFER_CHAIN_MAX_AUTO_SIZE, evbuffer_chain_new(), evbuffer_chain_should_realign(), EVBUFFER_IMMUTABLE, evbuffer_invoke_callbacks_(), EVBUFFER_LOCK, EVBUFFER_UNLOCK, EVUTIL_ASSERT, evbuffer_chain::flags, evbuffer::freeze_end, evbuffer::last, evbuffer::last_with_datap, evbuffer_chain::misalign, evbuffer::n_add_for_cb, evbuffer_chain::off, and evbuffer::total_len.
Referenced by bio_bufferevent_write(), bufferevent_write(), evbuffer_add_iovec(), evbuffer_remove_buffer(), evhttp_make_header(), evhttp_send_reply_chunk_with_cb(), evhttp_send_reply_end(), evhttp_uri_join(), evhttp_uriencode(), evtag_encode_int(), evtag_encode_int64(), evtag_encode_tag(), evtag_marshal(), evtag_marshal_int(), evtag_marshal_int64(), and evtag_unmarshal().
evbuffer_add_buffer()
int evbuffer_add_buffer (struct evbuffer * outbuf, struct evbuffer * inbuf)
Definition at line 966 of file buffer.c.
{
    struct evbuffer_chain *pinned, *last;
    size_t in_total_len, out_total_len;
    int result = 0;
    EVBUFFER_LOCK2(inbuf, outbuf);
    in_total_len = inbuf->total_len;
    out_total_len = outbuf->total_len;
    if (in_total_len == 0 || outbuf == inbuf)
        goto done;
    if (outbuf->freeze_end || inbuf->freeze_start) {
        result = -1;
        goto done;
    }
    if (PRESERVE_PINNED(inbuf, &pinned, &last) < 0) {
        result = -1;
        goto done;
    }
    if (out_total_len == 0) {
        /* There might be an empty chain at the start of outbuf; free
         * it. */
        evbuffer_free_all_chains(outbuf->first);
        COPY_CHAIN(outbuf, inbuf);
    } else {
        APPEND_CHAIN(outbuf, inbuf);
    }
    RESTORE_PINNED(inbuf, pinned, last);
    inbuf->n_del_for_cb += in_total_len;
    outbuf->n_add_for_cb += in_total_len;
    evbuffer_invoke_callbacks_(inbuf);
    evbuffer_invoke_callbacks_(outbuf);
done:
    EVBUFFER_UNLOCK2(inbuf, outbuf);
    return result;
}
References APPEND_CHAIN(), COPY_CHAIN(), evbuffer_free_all_chains(), evbuffer_invoke_callbacks_(), EVBUFFER_LOCK2, EVBUFFER_UNLOCK2, evbuffer::first, evbuffer::freeze_end, evbuffer::freeze_start, evbuffer::n_add_for_cb, evbuffer::n_del_for_cb, PRESERVE_PINNED(), RESTORE_PINNED(), and evbuffer::total_len.
Referenced by be_pair_transfer(), bufferevent_read_buffer(), bufferevent_write_buffer(), evbuffer_remove_buffer(), evhttp_make_header(), evhttp_read_body(), evhttp_read_header(), evhttp_send(), evhttp_send_reply_chunk_with_cb(), and evtag_marshal_buffer().
evbuffer_add_buffer_reference()
int evbuffer_add_buffer_reference (struct evbuffer * outbuf, struct evbuffer * inbuf)
Definition at line 1012 of file buffer.c.
{
    size_t in_total_len, out_total_len;
    struct evbuffer_chain *chain;
    int result = 0;
    EVBUFFER_LOCK2(inbuf, outbuf);
    in_total_len = inbuf->total_len;
    out_total_len = outbuf->total_len;
    chain = inbuf->first;
    if (in_total_len == 0)
        goto done;
    if (outbuf->freeze_end || outbuf == inbuf) {
        result = -1;
        goto done;
    }
    for (; chain; chain = chain->next) {
        if ((chain->flags & (EVBUFFER_FILESEGMENT|EVBUFFER_SENDFILE|EVBUFFER_MULTICAST)) != 0) {
            /* chain type can not be referenced */
            result = -1;
            goto done;
        }
    }
    if (out_total_len == 0) {
        /* There might be an empty chain at the start of outbuf; free
         * it. */
        evbuffer_free_all_chains(outbuf->first);
    }
    APPEND_CHAIN_MULTICAST(outbuf, inbuf);
    outbuf->n_add_for_cb += in_total_len;
    evbuffer_invoke_callbacks_(outbuf);
done:
    EVBUFFER_UNLOCK2(inbuf, outbuf);
    return result;
}
References APPEND_CHAIN_MULTICAST(), EVBUFFER_FILESEGMENT, evbuffer_free_all_chains(), evbuffer_invoke_callbacks_(), EVBUFFER_LOCK2, EVBUFFER_MULTICAST, EVBUFFER_SENDFILE, EVBUFFER_UNLOCK2, evbuffer::first, evbuffer_chain::flags, evbuffer::freeze_end, evbuffer::n_add_for_cb, evbuffer_chain::next, and evbuffer::total_len.
evbuffer_add_cb()
struct evbuffer_cb_entry * evbuffer_add_cb (struct evbuffer * buffer, evbuffer_cb_func cb, void * cbarg)
Definition at line 3334 of file buffer.c.
{
    struct evbuffer_cb_entry *e;
    if (! (e = mm_calloc(1, sizeof(struct evbuffer_cb_entry))))
        return NULL;
    EVBUFFER_LOCK(buffer);
    e->cb.cb_func = cb;
    e->cbarg = cbarg;
    e->flags = EVBUFFER_CB_ENABLED;
    LIST_INSERT_HEAD(&buffer->callbacks, e, next);
    EVBUFFER_UNLOCK(buffer);
    return e;
}
References evbuffer_cb_entry::cb, evbuffer_cb_entry::cb_func, evbuffer_cb_entry::cbarg, EVBUFFER_LOCK, EVBUFFER_UNLOCK, evbuffer_cb_entry::flags, and mm_calloc.
Referenced by bufferevent_async_new_(), bufferevent_filter_new(), bufferevent_openssl_new_impl(), bufferevent_pair_elt_new(), bufferevent_setwatermark(), bufferevent_socket_new(), and evbuffer_setcb().
evbuffer_add_file()
int evbuffer_add_file (struct evbuffer * buf, int fd, ev_off_t offset, ev_off_t length)
Definition at line 3296 of file buffer.c.
{
    struct evbuffer_file_segment *seg;
    unsigned flags = EVBUF_FS_CLOSE_ON_FREE;
    int r;
    seg = evbuffer_file_segment_new(fd, offset, length, flags);
    if (!seg)
        return -1;
    r = evbuffer_add_file_segment(buf, seg, 0, length);
    if (r == 0)
        evbuffer_file_segment_free(seg);
    return r;
}
References evbuffer_add_file_segment(), evbuffer_file_segment_free(), evbuffer_file_segment_new(), evbuffer_file_segment::fd, evbuffer_file_segment::flags, and evbuffer_file_segment::length.
evbuffer_add_file_segment()
int evbuffer_add_file_segment (struct evbuffer * buf, struct evbuffer_file_segment * seg, ev_off_t offset, ev_off_t length)
Definition at line 3194 of file buffer.c.
{
    struct evbuffer_chain *chain;
    struct evbuffer_chain_file_segment *extra;
    int can_use_sendfile = 0;
    EVBUFFER_LOCK(buf);
    EVLOCK_LOCK(seg->lock, 0);
    if (buf->flags & EVBUFFER_FLAG_DRAINS_TO_FD) {
        can_use_sendfile = 1;
    } else {
        if (!seg->contents) {
            if (evbuffer_file_segment_materialize(seg)<0) {
                EVLOCK_UNLOCK(seg->lock, 0);
                EVBUFFER_UNLOCK(buf);
                return -1;
            }
        }
    }
    EVLOCK_UNLOCK(seg->lock, 0);
    if (buf->freeze_end)
        goto err;
    if (length < 0) {
        if (offset > seg->length)
            goto err;
        length = seg->length - offset;
    }
    /* Can we actually add this? */
    if (offset+length > seg->length)
        goto err;
    chain = evbuffer_chain_new(sizeof(struct evbuffer_chain_file_segment));
    if (!chain)
        goto err;
    extra = EVBUFFER_CHAIN_EXTRA(struct evbuffer_chain_file_segment, chain);
    chain->flags |= EVBUFFER_IMMUTABLE|EVBUFFER_FILESEGMENT;
    if (can_use_sendfile && seg->can_sendfile) {
        chain->flags |= EVBUFFER_SENDFILE;
        chain->misalign = seg->file_offset + offset;
        chain->off = length;
        chain->buffer_len = chain->misalign + length;
    } else if (seg->is_mapping) {
#ifdef _WIN32
        ev_uint64_t total_offset = seg->mmap_offset+offset;
        ev_uint64_t offset_rounded=0, offset_remaining=0;
        LPVOID data;
        if (total_offset) {
            SYSTEM_INFO si;
            memset(&si, 0, sizeof(si)); /* cargo cult */
            GetSystemInfo(&si);
            offset_remaining = total_offset % si.dwAllocationGranularity;
            offset_rounded = total_offset - offset_remaining;
        }
        data = MapViewOfFile(
            seg->mapping_handle,
            FILE_MAP_READ,
            offset_rounded >> 32,
            offset_rounded & 0xfffffffful,
            length + offset_remaining);
        if (data == NULL) {
            mm_free(chain);
            goto err;
        }
        chain->buffer = (unsigned char*) data;
        chain->buffer_len = length+offset_remaining;
        chain->misalign = offset_remaining;
        chain->off = length;
#else
        chain->buffer = (unsigned char*)(seg->contents + offset);
        chain->buffer_len = length;
        chain->off = length;
#endif
    } else {
        chain->buffer = (unsigned char*)(seg->contents + offset);
        chain->buffer_len = length;
        chain->off = length;
    }
    EVLOCK_LOCK(seg->lock, 0);
    ++seg->refcnt;
    EVLOCK_UNLOCK(seg->lock, 0);
    extra->segment = seg;
    buf->n_add_for_cb += length;
    evbuffer_chain_insert(buf, chain);
    evbuffer_invoke_callbacks_(buf);
    EVBUFFER_UNLOCK(buf);
    return 0;
err:
    EVBUFFER_UNLOCK(buf);
    evbuffer_file_segment_free(seg); /* Lowers the refcount */
    return -1;
}
References evbuffer_chain::buffer, evbuffer_chain::buffer_len, evbuffer_file_segment::can_sendfile, evbuffer_file_segment::contents, EVBUFFER_CHAIN_EXTRA, evbuffer_chain_insert(), evbuffer_chain_new(), evbuffer_file_segment_free(), evbuffer_file_segment_materialize(), EVBUFFER_FILESEGMENT, EVBUFFER_IMMUTABLE, evbuffer_invoke_callbacks_(), EVBUFFER_LOCK, EVBUFFER_SENDFILE, EVBUFFER_UNLOCK, EVLOCK_LOCK, EVLOCK_UNLOCK, evbuffer_file_segment::file_offset, evbuffer::flags, evbuffer_chain::flags, evbuffer::freeze_end, evbuffer_file_segment::is_mapping, evbuffer_file_segment::length, evbuffer_file_segment::lock, evbuffer_chain::misalign, mm_free, evbuffer_file_segment::mmap_offset, evbuffer::n_add_for_cb, evbuffer_chain::off, evbuffer_file_segment::refcnt, and evbuffer_chain_file_segment::segment.
Referenced by evbuffer_add_file().
evbuffer_add_iovec()
size_t evbuffer_add_iovec (struct evbuffer * buf, struct evbuffer_iovec * vec, int n_vec)
Definition at line 635 of file buffer.c.
{
    int n;
    size_t res;
    size_t to_alloc;
    EVBUFFER_LOCK(buf);
    res = to_alloc = 0;
    for (n = 0; n < n_vec; n++) {
        to_alloc += vec[n].iov_len;
    }
    if (evbuffer_expand_fast_(buf, to_alloc, 2) < 0) {
        goto done;
    }
    for (n = 0; n < n_vec; n++) {
        /* XXX each 'add' call here does a bunch of setup that's
         * obviated by evbuffer_expand_fast_, and some cleanup that we
         * would like to do only once.  Instead we should just extract
         * the part of the code that's needed. */
        if (evbuffer_add(buf, vec[n].iov_base, vec[n].iov_len) < 0) {
            goto done;
        }
        res += vec[n].iov_len;
    }
done:
    EVBUFFER_UNLOCK(buf);
    return res;
}
References evbuffer_add(), evbuffer_expand_fast_(), EVBUFFER_LOCK, and EVBUFFER_UNLOCK.
evbuffer_add_printf()
int evbuffer_add_printf (struct evbuffer * buf, const char * fmt, ...)
Definition at line 2908 of file buffer.c.
{
    int res = -1;
    va_list ap;
    va_start(ap, fmt);
    res = evbuffer_add_vprintf(buf, fmt, ap);
    va_end(ap);
    return (res);
}
References evbuffer_add_vprintf().
Referenced by evhttp_handle_request(), evhttp_make_header(), evhttp_make_header_request(), evhttp_make_header_response(), evhttp_send_continue(), evhttp_send_error(), evhttp_send_reply_chunk_with_cb(), evhttp_uri_join(), and evhttp_uriencode().
evbuffer_add_reference()
int evbuffer_add_reference (struct evbuffer * outbuf, const void * data, size_t datlen, evbuffer_ref_cleanup_cb cleanupfn, void * extra)
Definition at line 2921 of file buffer.c.
{
    struct evbuffer_chain *chain;
    struct evbuffer_chain_reference *info;
    int result = -1;
    chain = evbuffer_chain_new(sizeof(struct evbuffer_chain_reference));
    if (!chain)
        return (-1);
    chain->flags |= EVBUFFER_REFERENCE | EVBUFFER_IMMUTABLE;
    chain->buffer = (unsigned char *)data;
    chain->buffer_len = datlen;
    chain->off = datlen;
    info = EVBUFFER_CHAIN_EXTRA(struct evbuffer_chain_reference, chain);
    info->cleanupfn = cleanupfn;
    info->extra = extra;
    EVBUFFER_LOCK(outbuf);
    if (outbuf->freeze_end) {
        /* don't call chain_free; we do not want to actually invoke
         * the cleanup function */
        mm_free(chain);
        goto done;
    }
    evbuffer_chain_insert(outbuf, chain);
    outbuf->n_add_for_cb += datlen;
    evbuffer_invoke_callbacks_(outbuf);
    result = 0;
done:
    EVBUFFER_UNLOCK(outbuf);
    return result;
}
References evbuffer_chain::buffer, evbuffer_chain::buffer_len, evbuffer_chain_reference::cleanupfn, EVBUFFER_CHAIN_EXTRA, evbuffer_chain_insert(), evbuffer_chain_new(), EVBUFFER_IMMUTABLE, evbuffer_invoke_callbacks_(), EVBUFFER_LOCK, EVBUFFER_REFERENCE, EVBUFFER_UNLOCK, evbuffer_chain_reference::extra, evbuffer_chain::flags, evbuffer::freeze_end, mm_free, evbuffer::n_add_for_cb, and evbuffer_chain::off.
evbuffer_add_vprintf()
int evbuffer_add_vprintf (struct evbuffer * buf, const char * fmt, va_list ap)
Definition at line 2844 of file buffer.c.
{
    char *buffer;
    size_t space;
    int sz, result = -1;
    va_list aq;
    struct evbuffer_chain *chain;
    EVBUFFER_LOCK(buf);
    if (buf->freeze_end) {
        goto done;
    }
    /* make sure that at least some space is available */
    if ((chain = evbuffer_expand_singlechain(buf, 64)) == NULL)
        goto done;
    for (;;) {
#if 0
        size_t used = chain->misalign + chain->off;
        buffer = (char *)chain->buffer + chain->misalign + chain->off;
        EVUTIL_ASSERT(chain->buffer_len >= used);
        space = chain->buffer_len - used;
#endif
        buffer = (char*) CHAIN_SPACE_PTR(chain);
        space = (size_t) CHAIN_SPACE_LEN(chain);
#ifndef va_copy
#define va_copy(dst, src)   memcpy(&(dst), &(src), sizeof(va_list))
#endif
        va_copy(aq, ap);
        sz = evutil_vsnprintf(buffer, space, fmt, aq);
        va_end(aq);
        if (sz < 0)
            goto done;
        if (INT_MAX >= EVBUFFER_CHAIN_MAX &&
            (size_t)sz >= EVBUFFER_CHAIN_MAX)
            goto done;
        if ((size_t)sz < space) {
            chain->off += sz;
            buf->total_len += sz;
            buf->n_add_for_cb += sz;
            advance_last_with_data(buf);
            evbuffer_invoke_callbacks_(buf);
            result = sz;
            goto done;
        }
        if ((chain = evbuffer_expand_singlechain(buf, sz + 1)) == NULL)
            goto done;
    }
    /* NOTREACHED */
done:
    EVBUFFER_UNLOCK(buf);
    return result;
}
References advance_last_with_data(), evbuffer_chain::buffer, evbuffer_chain::buffer_len, CHAIN_SPACE_LEN, CHAIN_SPACE_PTR, EVBUFFER_CHAIN_MAX, evbuffer_expand_singlechain(), evbuffer_invoke_callbacks_(), EVBUFFER_LOCK, EVBUFFER_UNLOCK, EVUTIL_ASSERT, evutil_vsnprintf(), evbuffer::freeze_end, evbuffer_chain::misalign, evbuffer::n_add_for_cb, evbuffer_chain::off, evbuffer::total_len, and va_copy.
Referenced by evbuffer_add_printf().
evbuffer_cb_clear_flags()
int evbuffer_cb_clear_flags (struct evbuffer * buffer, struct evbuffer_cb_entry * cb, ev_uint32_t flags)
Definition at line 3389 of file buffer.c.
{
    /* the user isn't allowed to mess with these. */
    flags &= ~EVBUFFER_CB_INTERNAL_FLAGS;
    EVBUFFER_LOCK(buffer);
    cb->flags &= ~flags;
    EVBUFFER_UNLOCK(buffer);
    return 0;
}
References evbuffer_cb_entry::cb, EVBUFFER_LOCK, EVBUFFER_UNLOCK, and evbuffer_cb_entry::flags.
Referenced by be_filter_process_output(), bufferevent_filter_new(), bufferevent_filtered_inbuf_cb(), and bufferevent_setwatermark().
evbuffer_cb_set_flags()
int evbuffer_cb_set_flags (struct evbuffer * buffer, struct evbuffer_cb_entry * cb, ev_uint32_t flags)
Definition at line 3377 of file buffer.c.
{
    /* the user isn't allowed to mess with these. */
    flags &= ~EVBUFFER_CB_INTERNAL_FLAGS;
    EVBUFFER_LOCK(buffer);
    cb->flags |= flags;
    EVBUFFER_UNLOCK(buffer);
    return 0;
}
References evbuffer_cb_entry::cb, EVBUFFER_LOCK, EVBUFFER_UNLOCK, and evbuffer_cb_entry::flags.
Referenced by be_filter_process_output(), be_filter_read_nolock_(), and bufferevent_setwatermark().
evbuffer_chain_align()
static void evbuffer_chain_align (struct evbuffer_chain * chain) static
Helper: realigns the memory in chain->buffer so that misalign is 0.
Definition at line 1914 of file buffer.c.
{
    EVUTIL_ASSERT(!(chain->flags & EVBUFFER_IMMUTABLE));
    EVUTIL_ASSERT(!(chain->flags & EVBUFFER_MEM_PINNED_ANY));
    memmove(chain->buffer, chain->buffer + chain->misalign, chain->off);
    chain->misalign = 0;
}
References evbuffer_chain::buffer, EVBUFFER_IMMUTABLE, EVBUFFER_MEM_PINNED_ANY, EVUTIL_ASSERT, evbuffer_chain::flags, evbuffer_chain::misalign, and evbuffer_chain::off.
Referenced by evbuffer_add(), and evbuffer_expand_singlechain().
evbuffer_chain_free()
static void evbuffer_chain_free (struct evbuffer_chain * chain) inline static
Definition at line 196 of file buffer.c.
{
    EVUTIL_ASSERT(chain->refcnt > 0);
    if (--chain->refcnt > 0) {
        /* chain is still referenced by other chains */
        return;
    }
    if (CHAIN_PINNED(chain)) {
        /* will get freed once no longer dangling */
        chain->refcnt++;
        chain->flags |= EVBUFFER_DANGLING;
        return;
    }
    /* safe to release chain, it's either a referencing
     * chain or all references to it have been freed */
    if (chain->flags & EVBUFFER_REFERENCE) {
        struct evbuffer_chain_reference *info =
            EVBUFFER_CHAIN_EXTRA(
                struct evbuffer_chain_reference,
                chain);
        if (info->cleanupfn)
            (*info->cleanupfn)(chain->buffer,
                chain->buffer_len,
                info->extra);
    }
    if (chain->flags & EVBUFFER_FILESEGMENT) {
        struct evbuffer_chain_file_segment *info =
            EVBUFFER_CHAIN_EXTRA(
                struct evbuffer_chain_file_segment,
                chain);
        if (info->segment) {
#ifdef _WIN32
            if (info->segment->is_mapping)
                UnmapViewOfFile(chain->buffer);
#endif
            evbuffer_file_segment_free(info->segment);
        }
    }
    if (chain->flags & EVBUFFER_MULTICAST) {
        struct evbuffer_multicast_parent *info =
            EVBUFFER_CHAIN_EXTRA(
                struct evbuffer_multicast_parent,
                chain);
        /* referencing chain is being freed, decrease
         * refcounts of source chain and associated
         * evbuffer (which get freed once both reach
         * zero) */
        EVUTIL_ASSERT(info->source != NULL);
        EVUTIL_ASSERT(info->parent != NULL);
        EVBUFFER_LOCK(info->source);
        evbuffer_chain_free(info->parent);
        evbuffer_decref_and_unlock_(info->source);
    }
    mm_free(chain);
}
References evbuffer_chain::buffer, evbuffer_chain::buffer_len, CHAIN_PINNED, evbuffer_chain_reference::cleanupfn, EVBUFFER_CHAIN_EXTRA, evbuffer_chain_free(), EVBUFFER_DANGLING, evbuffer_decref_and_unlock_(), evbuffer_file_segment_free(), EVBUFFER_FILESEGMENT, EVBUFFER_LOCK, EVBUFFER_MULTICAST, EVBUFFER_REFERENCE, EVUTIL_ASSERT, evbuffer_chain_reference::extra, evbuffer_chain::flags, evbuffer_file_segment::is_mapping, mm_free, evbuffer_multicast_parent::parent, evbuffer_chain::refcnt, evbuffer_chain_file_segment::segment, and evbuffer_multicast_parent::source.
Referenced by evbuffer_chain_free(), evbuffer_chain_unpin_(), evbuffer_decref_and_unlock_(), evbuffer_drain(), evbuffer_expand_fast_(), evbuffer_expand_singlechain(), evbuffer_free_all_chains(), and evbuffer_pullup().
evbuffer_chain_incref()
static void evbuffer_chain_incref (struct evbuffer_chain * chain) inline static
Definition at line 356 of file buffer.c.
{
    ++chain->refcnt;
}
References evbuffer_chain::refcnt.
Referenced by APPEND_CHAIN_MULTICAST().
evbuffer_chain_insert()
static void evbuffer_chain_insert (struct evbuffer * buf, struct evbuffer_chain * chain) static
Definition at line 309 of file buffer.c.
{
    ASSERT_EVBUFFER_LOCKED(buf);
    if (*buf->last_with_datap == NULL) {
        /* There are no chains data on the buffer at all. */
        EVUTIL_ASSERT(buf->last_with_datap == &buf->first);
        EVUTIL_ASSERT(buf->first == NULL);
        buf->first = buf->last = chain;
    } else {
        struct evbuffer_chain **chp;
        chp = evbuffer_free_trailing_empty_chains(buf);
        *chp = chain;
        if (chain->off)
            buf->last_with_datap = chp;
        buf->last = chain;
    }
    buf->total_len += chain->off;
}
References ASSERT_EVBUFFER_LOCKED, evbuffer_free_trailing_empty_chains(), EVUTIL_ASSERT, evbuffer::first, evbuffer::last, evbuffer::last_with_datap, evbuffer_chain::off, and evbuffer::total_len.
Referenced by APPEND_CHAIN_MULTICAST(), evbuffer_add(), evbuffer_add_file_segment(), evbuffer_add_reference(), evbuffer_chain_insert_new(), evbuffer_expand_fast_(), and evbuffer_prepend().
evbuffer_chain_insert_new()
static struct evbuffer_chain * evbuffer_chain_insert_new (struct evbuffer * buf, size_t datlen) inline static
Definition at line 330 of file buffer.c.
{
    struct evbuffer_chain *chain;
    if ((chain = evbuffer_chain_new(datlen)) == NULL)
        return NULL;
    evbuffer_chain_insert(buf, chain);
    return chain;
}
References evbuffer_chain_insert(), and evbuffer_chain_new().
Referenced by evbuffer_expand_singlechain().
evbuffer_chain_new()
static struct evbuffer_chain * evbuffer_chain_new (size_t size) static
Definition at line 157 of file buffer.c.
{
    struct evbuffer_chain *chain;
    size_t to_alloc;
    if (size > EVBUFFER_CHAIN_MAX - EVBUFFER_CHAIN_SIZE)
        return (NULL);
    size += EVBUFFER_CHAIN_SIZE;
    /* get the next largest memory that can hold the buffer */
    if (size < EVBUFFER_CHAIN_MAX / 2) {
        to_alloc = MIN_BUFFER_SIZE;
        while (to_alloc < size) {
            to_alloc <<= 1;
        }
    } else {
        to_alloc = size;
    }
    /* we get everything in one chunk */
    if ((chain = mm_malloc(to_alloc)) == NULL)
        return (NULL);
    memset(chain, 0, EVBUFFER_CHAIN_SIZE);
    chain->buffer_len = to_alloc - EVBUFFER_CHAIN_SIZE;
    /* this way we can manipulate the buffer to different addresses,
     * which is required for mmap for example.
     */
    chain->buffer = EVBUFFER_CHAIN_EXTRA(unsigned char, chain);
    chain->refcnt = 1;
    return (chain);
}
References evbuffer_chain::buffer, evbuffer_chain::buffer_len, EVBUFFER_CHAIN_EXTRA, EVBUFFER_CHAIN_MAX, EVBUFFER_CHAIN_SIZE, MIN_BUFFER_SIZE, mm_malloc, and evbuffer_chain::refcnt.
Referenced by APPEND_CHAIN_MULTICAST(), evbuffer_add(), evbuffer_add_file_segment(), evbuffer_add_reference(), evbuffer_chain_insert_new(), evbuffer_expand_fast_(), evbuffer_expand_singlechain(), evbuffer_prepend(), evbuffer_pullup(), and PRESERVE_PINNED().
evbuffer_chain_pin_()
void evbuffer_chain_pin_ (struct evbuffer_chain * chain, unsigned flag)
Pin a single buffer chain using a given flag. A pinned chunk may not be moved or freed until it is unpinned.
Definition at line 340 of file buffer.c.
{
    EVUTIL_ASSERT((chain->flags & flag) == 0);
    chain->flags |= flag;
}
References EVUTIL_ASSERT, and evbuffer_chain::flags.
Referenced by evbuffer_launch_read_(), and evbuffer_launch_write_().
evbuffer_chain_should_realign()
static int evbuffer_chain_should_realign (struct evbuffer_chain * chain, size_t datlen) static
Helper: return true iff we should realign chain to fit datalen bytes of data in it.
Definition at line 1928 of file buffer.c.
{
    return chain->buffer_len - chain->off >= datlen &&
        (chain->off < chain->buffer_len / 2) &&
        (chain->off <= MAX_TO_REALIGN_IN_EXPAND);
}
References evbuffer_chain::buffer_len, MAX_TO_REALIGN_IN_EXPAND, and evbuffer_chain::off.
Referenced by evbuffer_add(), and evbuffer_expand_singlechain().
evbuffer_chain_unpin_()
void evbuffer_chain_unpin_ (struct evbuffer_chain * chain, unsigned flag)
Unpin a single buffer chain using a given flag.
Definition at line 347 of file buffer.c.
{
    EVUTIL_ASSERT((chain->flags & flag) != 0);
    chain->flags &= ~flag;
    if (chain->flags & EVBUFFER_DANGLING)
        evbuffer_chain_free(chain);
}
References evbuffer_chain_free(), EVBUFFER_DANGLING, EVUTIL_ASSERT, and evbuffer_chain::flags.
Referenced by pin_release().
evbuffer_chains_all_empty()
static int evbuffer_chains_all_empty (struct evbuffer_chain * chain) static
Definition at line 267 of file buffer.c.
{
    for (; chain; chain = chain->next) {
        if (chain->off)
            return 0;
    }
    return 1;
}
References evbuffer_chain::next, and evbuffer_chain::off.
Referenced by evbuffer_free_trailing_empty_chains().
evbuffer_clear_flags()
int evbuffer_clear_flags (struct evbuffer * buf, ev_uint64_t flags)
Definition at line 387 of file buffer.c.
{
    EVBUFFER_LOCK(buf);
    buf->flags &= ~(ev_uint32_t)flags;
    EVBUFFER_UNLOCK(buf);
    return 0;
}
References EVBUFFER_LOCK, EVBUFFER_UNLOCK, and evbuffer::flags.
evbuffer_commit_space()
int evbuffer_commit_space (struct evbuffer * buf, struct evbuffer_iovec * vec, int n_vecs)
Definition at line 724 of file buffer.c.
{
    struct evbuffer_chain *chain, **firstchainp, **chainp;
    int result = -1;
    size_t added = 0;
    int i;
    EVBUFFER_LOCK(buf);
    if (buf->freeze_end)
        goto done;
    if (n_vecs == 0) {
        result = 0;
        goto done;
    } else if (n_vecs == 1 &&
        (buf->last && vec[0].iov_base == (void *)CHAIN_SPACE_PTR(buf->last))) {
        /* The user only got or used one chain; it might not
         * be the first one with space in it. */
        if ((size_t)vec[0].iov_len > (size_t)CHAIN_SPACE_LEN(buf->last))
            goto done;
        buf->last->off += vec[0].iov_len;
        added = vec[0].iov_len;
        if (added)
            advance_last_with_data(buf);
        goto okay;
    }
    /* Advance 'firstchain' to the first chain with space in it. */
    firstchainp = buf->last_with_datap;
    if (!*firstchainp)
        goto done;
    if (CHAIN_SPACE_LEN(*firstchainp) == 0) {
        firstchainp = &(*firstchainp)->next;
    }
    chain = *firstchainp;
    /* pass 1: make sure that the pointers and lengths of vecs[] are in
     * bounds before we try to commit anything. */
    for (i=0; i<n_vecs; ++i) {
        if (!chain)
            goto done;
        if (vec[i].iov_base != (void *)CHAIN_SPACE_PTR(chain) ||
            (size_t)vec[i].iov_len > CHAIN_SPACE_LEN(chain))
            goto done;
        chain = chain->next;
    }
    /* pass 2: actually adjust all the chains. */
    chainp = firstchainp;
    for (i=0; i<n_vecs; ++i) {
        (*chainp)->off += vec[i].iov_len;
        added += vec[i].iov_len;
        if (vec[i].iov_len) {
            buf->last_with_datap = chainp;
        }
        chainp = &(*chainp)->next;
    }
okay:
    buf->total_len += added;
    buf->n_add_for_cb += added;
    result = 0;
    evbuffer_invoke_callbacks_(buf);
done:
    EVBUFFER_UNLOCK(buf);
    return result;
}
References advance_last_with_data(), CHAIN_SPACE_LEN, CHAIN_SPACE_PTR, evbuffer_invoke_callbacks_(), EVBUFFER_LOCK, EVBUFFER_UNLOCK, evbuffer::freeze_end, evbuffer::last, evbuffer::last_with_datap, evbuffer::n_add_for_cb, evbuffer_chain::next, evbuffer_chain::off, and evbuffer::total_len.
Referenced by do_read().
evbuffer_copyout()
ev_ssize_t evbuffer_copyout (struct evbuffer * buf, void * data_out, size_t datlen)
Definition at line 1184 of file buffer.c.
{
    return evbuffer_copyout_from(buf, NULL, data_out, datlen);
}
References evbuffer_copyout_from().
Referenced by read_cb().
evbuffer_copyout_from()
ev_ssize_t evbuffer_copyout_from (struct evbuffer * buf, const struct evbuffer_ptr * pos, void * data_out, size_t datlen)
Definition at line 1190 of file buffer.c.
{
    /*XXX fails badly on sendfile case. */
    struct evbuffer_chain *chain;
    char *data = data_out;
    size_t nread;
    ev_ssize_t result = 0;
    size_t pos_in_chain;
    EVBUFFER_LOCK(buf);
    if (pos) {
        if (datlen > (size_t)(EV_SSIZE_MAX - pos->pos)) {
            result = -1;
            goto done;
        }
        chain = pos->internal_.chain;
        pos_in_chain = pos->internal_.pos_in_chain;
        if (datlen + pos->pos > buf->total_len)
            datlen = buf->total_len - pos->pos;
    } else {
        chain = buf->first;
        pos_in_chain = 0;
        if (datlen > buf->total_len)
            datlen = buf->total_len;
    }
    if (datlen == 0)
        goto done;
    if (buf->freeze_start) {
        result = -1;
        goto done;
    }
    nread = datlen;
    while (datlen && datlen >= chain->off - pos_in_chain) {
        size_t copylen = chain->off - pos_in_chain;
        memcpy(data,
            chain->buffer + chain->misalign + pos_in_chain,
            copylen);
        data += copylen;
        datlen -= copylen;
        chain = chain->next;
        pos_in_chain = 0;
        EVUTIL_ASSERT(chain || datlen==0);
    }
    if (datlen) {
        EVUTIL_ASSERT(chain);
        EVUTIL_ASSERT(datlen+pos_in_chain <= chain->off);
        memcpy(data, chain->buffer + chain->misalign + pos_in_chain,
            datlen);
    }
    result = nread;
done:
    EVBUFFER_UNLOCK(buf);
    return result;
}
References evbuffer_chain::buffer, EVBUFFER_LOCK, EVBUFFER_UNLOCK, EVUTIL_ASSERT, evbuffer::first, evbuffer::freeze_start, evbuffer_chain::misalign, evbuffer_chain::next, evbuffer_chain::off, and evbuffer::total_len.
Referenced by evbuffer_copyout(), and evbuffer_remove().
evbuffer_decref_and_unlock_()
void evbuffer_decref_and_unlock_ (struct evbuffer * buffer)
As evbuffer_free, but requires that we hold a lock on the buffer, and releases the lock before freeing it and the buffer.
Definition at line 561 of file buffer.c.
{
    struct evbuffer_chain *chain, *next;
    ASSERT_EVBUFFER_LOCKED(buffer);
    EVUTIL_ASSERT(buffer->refcnt > 0);
    if (--buffer->refcnt > 0) {
        EVBUFFER_UNLOCK(buffer);
        return;
    }
    for (chain = buffer->first; chain != NULL; chain = next) {
        next = chain->next;
        evbuffer_chain_free(chain);
    }
    evbuffer_remove_all_callbacks(buffer);
    if (buffer->deferred_cbs)
        event_deferred_cb_cancel_(buffer->cb_queue, &buffer->deferred);
    EVBUFFER_UNLOCK(buffer);
    if (buffer->own_lock)
        EVTHREAD_FREE_LOCK(buffer->lock, EVTHREAD_LOCKTYPE_RECURSIVE);
    mm_free(buffer);
}
References ASSERT_EVBUFFER_LOCKED, evbuffer_chain_free(), evbuffer_remove_all_callbacks(), EVBUFFER_UNLOCK, event_deferred_cb_cancel_(), EVTHREAD_FREE_LOCK, EVUTIL_ASSERT, mm_free, and evbuffer_chain::next.
Referenced by evbuffer_chain_free(), evbuffer_commit_read_(), evbuffer_commit_write_(), evbuffer_deferred_callback(), and evbuffer_free().
evbuffer_defer_callbacks()
int evbuffer_defer_callbacks (struct evbuffer * buffer, struct event_base * base)
Definition at line 411 of file buffer.c.
{
    EVBUFFER_LOCK(buffer);
    buffer->cb_queue = base;
    buffer->deferred_cbs = 1;
    event_deferred_cb_init_(&buffer->deferred,
        event_base_get_npriorities(base) / 2,
        evbuffer_deferred_callback, buffer);
    EVBUFFER_UNLOCK(buffer);
    return 0;
}
References evbuffer_deferred_callback(), EVBUFFER_LOCK, EVBUFFER_UNLOCK, event_base_get_npriorities(), and event_deferred_cb_init_().
evbuffer_deferred_callback()
static void evbuffer_deferred_callback (struct event_callback * cb, void * arg) static
Definition at line 534 of file buffer.c.
{
    struct bufferevent *parent = NULL;
    struct evbuffer *buffer = arg;
    /* XXXX It would be better to run these callbacks without holding the
     * lock */
    EVBUFFER_LOCK(buffer);
    parent = buffer->parent;
    evbuffer_run_callbacks(buffer, 1);
    evbuffer_decref_and_unlock_(buffer);
    if (parent)
        bufferevent_decref_(parent);
}
References bufferevent_decref_, evbuffer_decref_and_unlock_(), EVBUFFER_LOCK, evbuffer_run_callbacks(), and evbuffer::parent.
Referenced by evbuffer_defer_callbacks().
evbuffer_drain()
int evbuffer_drain (struct evbuffer * buf, size_t len)
Definition at line 1101 of file buffer.c.
{
    struct evbuffer_chain *chain, *next;
    size_t remaining, old_len;
    int result = 0;
    EVBUFFER_LOCK(buf);
    old_len = buf->total_len;
    if (old_len == 0)
        goto done;
    if (buf->freeze_start) {
        result = -1;
        goto done;
    }
    if (len >= old_len && !HAS_PINNED_R(buf)) {
        len = old_len;
        for (chain = buf->first; chain != NULL; chain = next) {
            next = chain->next;
            evbuffer_chain_free(chain);
        }
        ZERO_CHAIN(buf);
    } else {
        if (len >= old_len)
            len = old_len;
        buf->total_len -= len;
        remaining = len;
        for (chain = buf->first;
             remaining >= chain->off;
             chain = next) {
            next = chain->next;
            remaining -= chain->off;
            if (chain == *buf->last_with_datap) {
                buf->last_with_datap = &buf->first;
            }
            if (&chain->next == buf->last_with_datap)
                buf->last_with_datap = &buf->first;
            if (CHAIN_PINNED_R(chain)) {
                EVUTIL_ASSERT(remaining == 0);
                chain->misalign += chain->off;
                chain->off = 0;
                break;
            } else
                evbuffer_chain_free(chain);
        }
        buf->first = chain;
        EVUTIL_ASSERT(remaining <= chain->off);
        chain->misalign += remaining;
        chain->off -= remaining;
    }
    buf->n_del_for_cb += len;
    /* Tell someone about changes in this buffer */
    evbuffer_invoke_callbacks_(buf);
done:
    EVBUFFER_UNLOCK(buf);
    return result;
}
References CHAIN_PINNED_R, evbuffer_chain_free(), evbuffer_invoke_callbacks_(), EVBUFFER_LOCK, EVBUFFER_UNLOCK, EVUTIL_ASSERT, evbuffer::first, evbuffer::freeze_start, HAS_PINNED_R(), evbuffer::last_with_datap, evbuffer_chain::misalign, evbuffer::n_del_for_cb, evbuffer_chain::next, evbuffer_chain::off, evbuffer::total_len, and ZERO_CHAIN().
Referenced by decode_tag_internal(), do_write(), evbuffer_commit_write_(), evbuffer_readln(), evbuffer_remove(), evbuffer_write_atmost(), evhttp_connection_read_on_write_error(), evhttp_connection_reset_(), evhttp_handle_chunked_read(), evhttp_lingering_close(), evhttp_read_body(), evtag_consume(), evtag_decode_int(), evtag_decode_int64(), evtag_unmarshal(), evtag_unmarshal_int(), evtag_unmarshal_int64(), evtag_unmarshal_timeval(), and read_cb().
evbuffer_enable_locking()
int evbuffer_enable_locking (struct evbuffer * buf, void * lock)
Definition at line 424 of file buffer.c.
{
#ifdef EVENT__DISABLE_THREAD_SUPPORT
    return -1;
#else
    if (buf->lock)
        return -1;
    if (!lock) {
        EVTHREAD_ALLOC_LOCK(lock, EVTHREAD_LOCKTYPE_RECURSIVE);
        if (!lock)
            return -1;
        buf->lock = lock;
        buf->own_lock = 1;
    } else {
        buf->lock = lock;
        buf->own_lock = 0;
    }
    return 0;
#endif
}
References EVTHREAD_ALLOC_LOCK, evbuffer::lock, and evbuffer::own_lock.
Referenced by bufferevent_enable_locking_().
evbuffer_expand()
int evbuffer_expand (struct evbuffer * buf, size_t datlen)
Definition at line 2161 of file buffer.c.
{
    struct evbuffer_chain *chain;
    EVBUFFER_LOCK(buf);
    chain = evbuffer_expand_singlechain(buf, datlen);
    EVBUFFER_UNLOCK(buf);
    return chain ? 0 : -1;
}
References evbuffer_expand_singlechain(), EVBUFFER_LOCK, and EVBUFFER_UNLOCK.
evbuffer_expand_fast_()
int evbuffer_expand_fast_ (struct evbuffer * buf, size_t datlen, int n)
As evbuffer_expand, but does not guarantee that the newly allocated memory is contiguous. Instead, it may be split across two or more chunks.
Definition at line 2051 of file buffer.c.
{
    struct evbuffer_chain *chain = buf->last, *tmp, *next;
    size_t avail;
    int used;
    ASSERT_EVBUFFER_LOCKED(buf);
    EVUTIL_ASSERT(n >= 2);
    if (chain == NULL || (chain->flags & EVBUFFER_IMMUTABLE)) {
        /* There is no last chunk, or we can't touch the last chunk.
         * Just add a new chunk. */
        chain = evbuffer_chain_new(datlen);
        if (chain == NULL)
            return (-1);
        evbuffer_chain_insert(buf, chain);
        return (0);
    }
    used = 0; /* number of chains we're using space in. */
    avail = 0; /* how much space they have. */
    /* How many bytes can we stick at the end of buffer as it is?  Iterate
     * over the chains at the end of the buffer, tring to see how much
     * space we have in the first n. */
    for (chain = *buf->last_with_datap; chain; chain = chain->next) {
        if (chain->off) {
            size_t space = (size_t) CHAIN_SPACE_LEN(chain);
            EVUTIL_ASSERT(chain == *buf->last_with_datap);
            if (space) {
                avail += space;
                ++used;
            }
        } else {
            /* No data in chain; realign it. */
            chain->misalign = 0;
            avail += chain->buffer_len;
            ++used;
        }
        if (avail >= datlen) {
            /* There is already enough space.  Just return */
            return (0);
        }
        if (used == n)
            break;
    }
    /* There wasn't enough space in the first n chains with space in
     * them. Either add a new chain with enough space, or replace all
     * empty chains with one that has enough space, depending on n. */
    if (used < n) {
        /* The loop ran off the end of the chains before it hit n
         * chains; we can add another. */
        EVUTIL_ASSERT(chain == NULL);
        tmp = evbuffer_chain_new(datlen - avail);
        if (tmp == NULL)
            return (-1);
        buf->last->next = tmp;
        buf->last = tmp;
        /* (we would only set last_with_data if we added the first
         * chain. But if the buffer had no chains, we would have
         * just allocated a new chain earlier) */
        return (0);
    } else {
        /* Nuke _all_ the empty chains. */
        int rmv_all = 0; /* True iff we removed last_with_data. */
        chain = *buf->last_with_datap;
        if (!chain->off) {
            EVUTIL_ASSERT(chain == buf->first);
            rmv_all = 1;
            avail = 0;
        } else {
            /* can't overflow, since only mutable chains have
             * huge misaligns. */
            avail = (size_t) CHAIN_SPACE_LEN(chain);
            chain = chain->next;
        }
        for (; chain; chain = next) {
            next = chain->next;
            EVUTIL_ASSERT(chain->off == 0);
            evbuffer_chain_free(chain);
        }
        EVUTIL_ASSERT(datlen >= avail);
        tmp = evbuffer_chain_new(datlen - avail);
        if (tmp == NULL) {
            if (rmv_all) {
                ZERO_CHAIN(buf);
            } else {
                buf->last = *buf->last_with_datap;
                (*buf->last_with_datap)->next = NULL;
            }
            return (-1);
        }
        if (rmv_all) {
            buf->first = buf->last = tmp;
            buf->last_with_datap = &buf->first;
        } else {
            (*buf->last_with_datap)->next = tmp;
            buf->last = tmp;
        }
        return (0);
    }
}
References ASSERT_EVBUFFER_LOCKED, evbuffer_chain::buffer_len, CHAIN_SPACE_LEN, evbuffer_chain_free(), evbuffer_chain_insert(), evbuffer_chain_new(), EVBUFFER_IMMUTABLE, EVUTIL_ASSERT, evbuffer::first, evbuffer_chain::flags, evbuffer::last, evbuffer::last_with_datap, evbuffer_chain::misalign, evbuffer_chain::next, evbuffer_chain::off, and ZERO_CHAIN().
Referenced by evbuffer_add_iovec(), evbuffer_launch_read_(), evbuffer_read(), and evbuffer_reserve_space().
evbuffer_expand_singlechain()
static struct evbuffer_chain * evbuffer_expand_singlechain (struct evbuffer * buf, size_t datlen) static
Definition at line 1939 of file buffer.c.
{
    struct evbuffer_chain *chain, **chainp;
    struct evbuffer_chain *result = NULL;
    ASSERT_EVBUFFER_LOCKED(buf);
    chainp = buf->last_with_datap;
    /* XXX If *chainp is no longer writeable, but has enough space in its
     * misalign, this might be a bad idea: we could still use *chainp, not
     * (*chainp)->next. */
    if (*chainp && CHAIN_SPACE_LEN(*chainp) == 0)
        chainp = &(*chainp)->next;
    /* 'chain' now points to the first chain with writable space (if any)
     * We will either use it, realign it, replace it, or resize it. */
    chain = *chainp;
    if (chain == NULL ||
        (chain->flags & (EVBUFFER_IMMUTABLE|EVBUFFER_MEM_PINNED_ANY))) {
        /* We can't use the last_with_data chain at all.  Just add a
         * new one that's big enough. */
        goto insert_new;
    }
    /* If we can fit all the data, then we don't have to do anything */
    if (CHAIN_SPACE_LEN(chain) >= datlen) {
        result = chain;
        goto ok;
    }
    /* If the chain is completely empty, just replace it by adding a new
     * empty chain. */
    if (chain->off == 0) {
        goto insert_new;
    }
    /* If the misalignment plus the remaining space fulfills our data
     * needs, we could just force an alignment to happen.  Afterwards, we
     * have enough space.  But only do this if we're saving a lot of space
     * and not moving too much data.  Otherwise the space savings are
     * probably offset by the time lost in copying.
     */
    if (evbuffer_chain_should_realign(chain, datlen)) {
        evbuffer_chain_align(chain);
        result = chain;
        goto ok;
    }
    /* At this point, we can either resize the last chunk with space in
     * it, use the next chunk after it, or   If we add a new chunk, we waste
     * CHAIN_SPACE_LEN(chain) bytes in the former last chunk.  If we
     * resize, we have to copy chain->off bytes.
     */
    /* Would expanding this chunk be affordable and worthwhile? */
    if (CHAIN_SPACE_LEN(chain) < chain->buffer_len / 8 ||
        chain->off > MAX_TO_COPY_IN_EXPAND ||
        datlen >= (EVBUFFER_CHAIN_MAX - chain->off)) {
        /* It's not worth resizing this chain. Can the next one be
         * used? */
        if (chain->next && CHAIN_SPACE_LEN(chain->next) >= datlen) {
            /* Yes, we can just use the next chain (which should
             * be empty. */
            result = chain->next;
            goto ok;
        } else {
            /* No; append a new chain (which will free all
             * terminal empty chains.) */
            goto insert_new;
        }
    } else {
        /* Okay, we're going to try to resize this chain: Not doing so
         * would waste at least 1/8 of its current allocation, and we
         * can do so without having to copy more than
         * MAX_TO_COPY_IN_EXPAND bytes. */
        /* figure out how much space we need */
        size_t length = chain->off + datlen;
        struct evbuffer_chain *tmp = evbuffer_chain_new(length);
        if (tmp == NULL)
            goto err;
        /* copy the data over that we had so far */
        tmp->off = chain->off;
        memcpy(tmp->buffer, chain->buffer + chain->misalign,
            chain->off);
        /* fix up the list */
        EVUTIL_ASSERT(*chainp == chain);
        result = *chainp = tmp;
        if (buf->last == chain)
            buf->last = tmp;
        tmp->next = chain->next;
        evbuffer_chain_free(chain);
        goto ok;
    }
insert_new:
    result = evbuffer_chain_insert_new(buf, datlen);
    if (!result)
        goto err;
ok:
    EVUTIL_ASSERT(result);
    EVUTIL_ASSERT(CHAIN_SPACE_LEN(result) >= datlen);
err:
    return result;
}
References ASSERT_EVBUFFER_LOCKED, evbuffer_chain::buffer, evbuffer_chain::buffer_len, CHAIN_SPACE_LEN, evbuffer_chain_align(), evbuffer_chain_free(), evbuffer_chain_insert_new(), EVBUFFER_CHAIN_MAX, evbuffer_chain_new(), evbuffer_chain_should_realign(), EVBUFFER_IMMUTABLE, EVBUFFER_MEM_PINNED_ANY, EVUTIL_ASSERT, evbuffer_chain::flags, evbuffer::last, evbuffer::last_with_datap, MAX_TO_COPY_IN_EXPAND, evbuffer_chain::misalign, evbuffer_chain::next, and evbuffer_chain::off.
Referenced by evbuffer_add_vprintf(), evbuffer_expand(), evbuffer_read(), and evbuffer_reserve_space().
evbuffer_file_segment_add_cleanup_cb()
void evbuffer_file_segment_add_cleanup_cb (struct evbuffer_file_segment * seg, evbuffer_file_segment_cleanup_cb cb, void * arg)
Definition at line 3146 of file buffer.c.
{
    EVUTIL_ASSERT(seg->refcnt > 0);
    seg->cleanup_cb = cb;
    seg->cleanup_cb_arg = arg;
}
References evbuffer_file_segment::cleanup_cb, evbuffer_file_segment::cleanup_cb_arg, EVUTIL_ASSERT, and evbuffer_file_segment::refcnt.
evbuffer_file_segment_free()
void evbuffer_file_segment_free (struct evbuffer_file_segment * seg)
Definition at line 3155 of file buffer.c.
{
    int refcnt;
    EVLOCK_LOCK(seg->lock, 0);
    refcnt = --seg->refcnt;
    EVLOCK_UNLOCK(seg->lock, 0);
    if (refcnt > 0)
        return;
    EVUTIL_ASSERT(refcnt == 0);
    if (seg->is_mapping) {
#ifdef _WIN32
        CloseHandle(seg->mapping_handle);
#elif defined (EVENT__HAVE_MMAP)
        off_t offset_leftover;
        offset_leftover = seg->file_offset % get_page_size();
        if (munmap(seg->mapping, seg->length + offset_leftover) == -1)
            event_warn("%s: munmap failed", __func__);
#endif
    } else if (seg->contents) {
        mm_free(seg->contents);
    }
    if ((seg->flags & EVBUF_FS_CLOSE_ON_FREE) && seg->fd >= 0) {
        close(seg->fd);
    }
    if (seg->cleanup_cb) {
        (*seg->cleanup_cb)((struct evbuffer_file_segment const*)seg,
            seg->flags, seg->cleanup_cb_arg);
        seg->cleanup_cb = NULL;
        seg->cleanup_cb_arg = NULL;
    }
    EVTHREAD_FREE_LOCK(seg->lock, 0);
    mm_free(seg);
}
References __func__, evbuffer_file_segment::cleanup_cb, evbuffer_file_segment::cleanup_cb_arg, evbuffer_file_segment::contents, event_warn(), EVLOCK_LOCK, EVLOCK_UNLOCK, EVTHREAD_FREE_LOCK, EVUTIL_ASSERT, evbuffer_file_segment::fd, evbuffer_file_segment::file_offset, evbuffer_file_segment::flags, evbuffer_file_segment::is_mapping, evbuffer_file_segment::length, evbuffer_file_segment::lock, evbuffer_file_segment::mapping, mm_free, and evbuffer_file_segment::refcnt.
Referenced by evbuffer_add_file(), evbuffer_add_file_segment(), and evbuffer_chain_free().
evbuffer_file_segment_materialize()
static int evbuffer_file_segment_materialize (struct evbuffer_file_segment * seg) static
Definition at line 3040 of file buffer.c.
{
    const unsigned flags = seg->flags;
    const int fd = seg->fd;
    const ev_off_t length = seg->length;
    const ev_off_t offset = seg->file_offset;
    if (seg->contents)
        return 0; /* already materialized */
#if defined(EVENT__HAVE_MMAP)
    if (!(flags & EVBUF_FS_DISABLE_MMAP)) {
        off_t offset_rounded = 0, offset_leftover = 0;
        void *mapped;
        if (offset) {
            /* mmap implementations don't generally like us
             * to have an offset that isn't a round  */
            long page_size = get_page_size();
            if (page_size == -1)
                goto err;
            offset_leftover = offset % page_size;
            offset_rounded = offset - offset_leftover;
        }
        mapped = mmap(NULL, length + offset_leftover,
            PROT_READ,
#ifdef MAP_NOCACHE
            MAP_NOCACHE | /* ??? */
#endif
#ifdef MAP_FILE
            MAP_FILE |
#endif
            MAP_PRIVATE,
            fd, offset_rounded);
        if (mapped == MAP_FAILED) {
            event_warn("%s: mmap(%d, %d, %zu) failed",
                __func__, fd, 0, (size_t)(offset + length));
        } else {
            seg->mapping = mapped;
            seg->contents = (char*)mapped+offset_leftover;
            seg->mmap_offset = 0;
            seg->is_mapping = 1;
            goto done;
        }
    }
#endif
#ifdef _WIN32
    if (!(flags & EVBUF_FS_DISABLE_MMAP)) {
        intptr_t h = _get_osfhandle(fd);
        HANDLE m;
        ev_uint64_t total_size = length+offset;
        if ((HANDLE)h == INVALID_HANDLE_VALUE)
            goto err;
        m = CreateFileMapping((HANDLE)h, NULL, PAGE_READONLY,
            (total_size >> 32), total_size & 0xfffffffful,
            NULL);
        if (m != INVALID_HANDLE_VALUE) { /* Does h leak? */
            seg->mapping_handle = m;
            seg->mmap_offset = offset;
            seg->is_mapping = 1;
            goto done;
        }
    }
#endif
    {
        ev_off_t start_pos = lseek(fd, 0, SEEK_CUR), pos;
        ev_off_t read_so_far = 0;
        char *mem;
        int e;
        ev_ssize_t n = 0;
        if (!(mem = mm_malloc(length)))
            goto err;
        if (start_pos < 0) {
            mm_free(mem);
            goto err;
        }
        if (lseek(fd, offset, SEEK_SET) < 0) {
            mm_free(mem);
            goto err;
        }
        while (read_so_far < length) {
            n = read(fd, mem+read_so_far, length-read_so_far);
            if (n <= 0)
                break;
            read_so_far += n;
        }
        e = errno;
        pos = lseek(fd, start_pos, SEEK_SET);
        if (n < 0 || (n == 0 && length > read_so_far)) {
            mm_free(mem);
            errno = e;
            goto err;
        } else if (pos < 0) {
            mm_free(mem);
            goto err;
        }
        seg->contents = mem;
    }
done:
    return 0;
err:
    return -1;
}
References __func__, evbuffer_file_segment::contents, event_warn(), evbuffer_file_segment::fd, evbuffer_file_segment::file_offset, evbuffer_file_segment::flags, evbuffer_file_segment::is_mapping, evbuffer_file_segment::length, lseek, MAP_FAILED, evbuffer_file_segment::mapping, mm_free, mm_malloc, and evbuffer_file_segment::mmap_offset.
Referenced by evbuffer_add_file_segment(), and evbuffer_file_segment_new().
evbuffer_file_segment_new()
struct evbuffer_file_segment * evbuffer_file_segment_new (int fd, ev_off_t offset, ev_off_t length, unsigned flags)
Definition at line 2964 of file buffer.c.
{
    struct evbuffer_file_segment *seg =
        mm_calloc(sizeof(struct evbuffer_file_segment), 1);
    if (!seg)
        return NULL;
    seg->refcnt = 1;
    seg->fd = fd;
    seg->flags = flags;
    seg->file_offset = offset;
    seg->cleanup_cb = NULL;
    seg->cleanup_cb_arg = NULL;
#ifdef _WIN32
#ifndef lseek
#define lseek _lseeki64
#endif
#ifndef fstat
#define fstat _fstat
#endif
#ifndef stat
#define stat _stat
#endif
#endif
    if (length == -1) {
        struct stat st;
        if (fstat(fd, &st) < 0)
            goto err;
        length = st.st_size;
    }
    seg->length = length;
    if (offset < 0 || length < 0 ||
        ((ev_uint64_t)length > EVBUFFER_CHAIN_MAX) ||
        (ev_uint64_t)offset > (ev_uint64_t)(EVBUFFER_CHAIN_MAX - length))
        goto err;
#if defined(USE_SENDFILE)
    if (!(flags & EVBUF_FS_DISABLE_SENDFILE)) {
        seg->can_sendfile = 1;
        goto done;
    }
#endif
    if (evbuffer_file_segment_materialize(seg)<0)
        goto err;
#if defined(USE_SENDFILE)
done:
#endif
    if (!(flags & EVBUF_FS_DISABLE_LOCKING)) {
        EVTHREAD_ALLOC_LOCK(seg->lock, 0);
    }
    return seg;
err:
    mm_free(seg);
    return NULL;
}
References evbuffer_file_segment::can_sendfile, evbuffer_file_segment::cleanup_cb, evbuffer_file_segment::cleanup_cb_arg, EVBUFFER_CHAIN_MAX, evbuffer_file_segment_materialize(), EVTHREAD_ALLOC_LOCK, evbuffer_file_segment::fd, evbuffer_file_segment::file_offset, evbuffer_file_segment::flags, evbuffer_file_segment::length, evbuffer_file_segment::lock, mm_calloc, mm_free, and evbuffer_file_segment::refcnt.
Referenced by evbuffer_add_file().
evbuffer_find()
unsigned char * evbuffer_find (struct evbuffer * buffer, const unsigned char * what, size_t len)
Definition at line 2578 of file buffer.c.
{
    unsigned char *search;
    struct evbuffer_ptr ptr;
    EVBUFFER_LOCK(buffer);
    ptr = evbuffer_search(buffer, (const char *)what, len, NULL);
    if (ptr.pos < 0) {
        search = NULL;
    } else {
        search = evbuffer_pullup(buffer, ptr.pos + len);
        if (search)
            search += ptr.pos;
    }
    EVBUFFER_UNLOCK(buffer);
    return search;
}
References EVBUFFER_LOCK, evbuffer_pullup(), evbuffer_search(), and EVBUFFER_UNLOCK.
evbuffer_find_eol_char()
static ev_ssize_t evbuffer_find_eol_char (struct evbuffer_ptr * it) static
Definition at line 1523 of file buffer.c.
{
    struct evbuffer_chain *chain = it->internal_.chain;
    size_t i = it->internal_.pos_in_chain;
    while (chain != NULL) {
        char *buffer = (char *)chain->buffer + chain->misalign;
        char *cp = find_eol_char(buffer+i, chain->off-i);
        if (cp) {
            it->internal_.chain = chain;
            it->internal_.pos_in_chain = cp - buffer;
            it->pos += (cp - buffer) - i;
            return it->pos;
        }
        it->pos += chain->off - i;
        i = 0;
        chain = chain->next;
    }
    return (-1);
}
References evbuffer_chain::buffer, find_eol_char(), evbuffer_chain::misalign, evbuffer_chain::next, and evbuffer_chain::off.
Referenced by evbuffer_search_eol().
evbuffer_free()
void evbuffer_free (struct evbuffer * buffer)
Definition at line 588 of file buffer.c.
{
    EVBUFFER_LOCK(buffer);
    evbuffer_decref_and_unlock_(buffer);
}
References evbuffer_decref_and_unlock_(), and EVBUFFER_LOCK.
Referenced by bufferevent_async_new_(), bufferevent_finalize_cb_(), bufferevent_init_common_(), evbuffer_launch_read_(), evbuffer_launch_write_(), evhttp_handle_request(), evhttp_request_free(), evhttp_send_error(), evhttp_uri_join(), evhttp_uriencode(), and evrpc_reqstate_free_().
evbuffer_free_all_chains()
static void evbuffer_free_all_chains (struct evbuffer_chain * chain) static
Definition at line 256 of file buffer.c.
{
    struct evbuffer_chain *next;
    for (; chain; chain = next) {
        next = chain->next;
        evbuffer_chain_free(chain);
    }
}
References evbuffer_chain_free(), and evbuffer_chain::next.
Referenced by evbuffer_add_buffer(), evbuffer_add_buffer_reference(), evbuffer_free_trailing_empty_chains(), and evbuffer_prepend_buffer().
evbuffer_free_trailing_empty_chains()
static struct evbuffer_chain ** evbuffer_free_trailing_empty_chains (struct evbuffer * buf) static
Definition at line 291 of file buffer.c.
{
    struct evbuffer_chain **ch = buf->last_with_datap;
    /* Find the first victim chain.  It might be *last_with_datap */
    while ((*ch) && ((*ch)->off != 0 || CHAIN_PINNED(*ch)))
        ch = &(*ch)->next;
    if (*ch) {
        EVUTIL_ASSERT(evbuffer_chains_all_empty(*ch));
        evbuffer_free_all_chains(*ch);
        *ch = NULL;
    }
    return ch;
}
References CHAIN_PINNED, evbuffer_chains_all_empty(), evbuffer_free_all_chains(), EVUTIL_ASSERT, evbuffer::last_with_datap, and evbuffer_chain::next.
Referenced by APPEND_CHAIN(), evbuffer_chain_insert(), and evbuffer_remove_buffer().
evbuffer_freeze()
int evbuffer_freeze (struct evbuffer * buffer, int start)
Definition at line 3401 of file buffer.c.
{
    EVBUFFER_LOCK(buffer);
    if (start)
        buffer->freeze_start = 1;
    else
        buffer->freeze_end = 1;
    EVBUFFER_UNLOCK(buffer);
    return 0;
}
References EVBUFFER_LOCK, and EVBUFFER_UNLOCK.
Referenced by be_pair_transfer(), bufferevent_pair_new(), bufferevent_readcb(), bufferevent_socket_new(), bufferevent_writecb(), evbuffer_launch_read_(), evbuffer_launch_write_(), and evhttp_connection_read_on_write_error().
evbuffer_get_callbacks_()
int evbuffer_get_callbacks_ (struct evbuffer * buffer, struct event_callback ** cbs, int max_cbs)
Definition at line 3451 of file buffer.c.
{
    int r = 0;
    EVBUFFER_LOCK(buffer);
    if (buffer->deferred_cbs) {
        if (max_cbs < 1) {
            r = -1;
            goto done;
        }
        cbs[0] = &buffer->deferred;
        r = 1;
    }
done:
    EVBUFFER_UNLOCK(buffer);
    return r;
}
References EVBUFFER_LOCK, and EVBUFFER_UNLOCK.
Referenced by bufferevent_decref_and_unlock_().
evbuffer_get_contiguous_space()
size_t evbuffer_get_contiguous_space (const struct evbuffer * buf)
Definition at line 621 of file buffer.c.
{
    struct evbuffer_chain *chain;
    size_t result;
    EVBUFFER_LOCK(buf);
    chain = buf->first;
    result = (chain != NULL ? chain->off : 0);
    EVBUFFER_UNLOCK(buf);
    return result;
}
References EVBUFFER_LOCK, EVBUFFER_UNLOCK, evbuffer::first, and evbuffer_chain::off.
evbuffer_get_length()
size_t evbuffer_get_length (const struct evbuffer * buffer)
Definition at line 607 of file buffer.c.
{
    size_t result;
    EVBUFFER_LOCK(buffer);
    result = (buffer->total_len);
    EVBUFFER_UNLOCK(buffer);
    return result;
}
References EVBUFFER_LOCK, and EVBUFFER_UNLOCK.
Referenced by be_filter_process_input(), be_filter_process_output(), be_filter_read_nolock_(), be_pair_enable(), be_pair_transfer(), be_pair_wants_to_talk(), be_readbuf_full(), be_underlying_writebuf_full(), bev_async_consider_reading(), bev_async_consider_writing(), bio_bufferevent_ctrl(), bio_bufferevent_read(), bio_bufferevent_write(), bufferevent_filtered_inbuf_cb(), bufferevent_generic_adj_timeouts_(), bufferevent_inbuf_wm_cb(), bufferevent_inbuf_wm_check(), bufferevent_readcb(), bufferevent_setwatermark(), bufferevent_trigger_nolock_(), bufferevent_writecb(), bytes_to_read(), consider_writing(), decode_tag_internal(), evhttp_connection_read_on_write_error(), evhttp_error_cb(), evhttp_get_body(), evhttp_get_body_length(), evhttp_handle_chunked_read(), evhttp_lingering_close(), evhttp_make_header(), evhttp_make_header_request(), evhttp_make_header_response(), evhttp_parse_firstline_(), evhttp_parse_headers_(), evhttp_read_body(), evhttp_read_cb(), evhttp_send_reply_chunk_with_cb(), evhttp_send_reply_end(), evhttp_start_read_(), evhttp_uri_join(), evhttp_uriencode(), evhttp_write_connectioncb(), evrpc_request_cb(), evtag_marshal_buffer(), evtag_unmarshal_header(), evtag_unmarshal_int(), evtag_unmarshal_int64(), and read_cb().
evbuffer_getchr()
static int evbuffer_getchr (struct evbuffer_ptr * it) inline static
Definition at line 1585 of file buffer.c.
{
    struct evbuffer_chain *chain = it->internal_.chain;
    size_t off = it->internal_.pos_in_chain;
    if (chain == NULL)
        return -1;
    return (unsigned char)chain->buffer[chain->misalign + off];
}
References evbuffer_chain::buffer, evbuffer_chain::misalign, and evbuffer_chain::off.
Referenced by evbuffer_search_eol().
evbuffer_incref_()
void evbuffer_incref_ (struct evbuffer * buf)
Increase the reference count of buf by one.
Definition at line 396 of file buffer.c.
{
    EVBUFFER_LOCK(buf);
    ++buf->refcnt;
    EVBUFFER_UNLOCK(buf);
}
References EVBUFFER_LOCK, EVBUFFER_UNLOCK, and evbuffer::refcnt.
Referenced by APPEND_CHAIN_MULTICAST(), evbuffer_launch_read_(), and evbuffer_launch_write_().
evbuffer_incref_and_lock_()
void evbuffer_incref_and_lock_ (struct evbuffer * buf)
Increase the reference count of buf by one and acquire the lock.
Definition at line 404 of file buffer.c.
{
    EVBUFFER_LOCK(buf);
    ++buf->refcnt;
}
References EVBUFFER_LOCK, and evbuffer::refcnt.
Referenced by evbuffer_invoke_callbacks_().
evbuffer_invoke_callbacks_()
void evbuffer_invoke_callbacks_ (struct evbuffer * buffer)
Definition at line 514 of file buffer.c.
{
    if (LIST_EMPTY(&buffer->callbacks)) {
        buffer->n_add_for_cb = buffer->n_del_for_cb = 0;
        return;
    }
    if (buffer->deferred_cbs) {
        if (event_deferred_cb_schedule_(buffer->cb_queue, &buffer->deferred)) {
            evbuffer_incref_and_lock_(buffer);
            if (buffer->parent)
                bufferevent_incref_(buffer->parent);
            EVBUFFER_UNLOCK(buffer);
        }
    }
    evbuffer_run_callbacks(buffer, 0);
}
References bufferevent_incref_, evbuffer_incref_and_lock_(), evbuffer_run_callbacks(), EVBUFFER_UNLOCK, and event_deferred_cb_schedule_().
Referenced by evbuffer_add(), evbuffer_add_buffer(), evbuffer_add_buffer_reference(), evbuffer_add_file_segment(), evbuffer_add_reference(), evbuffer_add_vprintf(), evbuffer_commit_read_(), evbuffer_commit_space(), evbuffer_drain(), evbuffer_prepend(), evbuffer_prepend_buffer(), evbuffer_read(), and evbuffer_remove_buffer().
evbuffer_lock()
void evbuffer_lock (struct evbuffer * buf)
Definition at line 595 of file buffer.c.
{
    EVBUFFER_LOCK(buf);
}
References EVBUFFER_LOCK.
evbuffer_new()
struct evbuffer * evbuffer_new (void)
Definition at line 362 of file buffer.c.
{
    struct evbuffer *buffer;
    buffer = mm_calloc(1, sizeof(struct evbuffer));
    if (buffer == NULL)
        return (NULL);
    LIST_INIT(&buffer->callbacks);
    buffer->refcnt = 1;
    buffer->last_with_datap = &buffer->first;
    return (buffer);
}
References mm_calloc.
Referenced by bufferevent_init_common_(), evhttp_handle_request(), evhttp_request_new(), evhttp_send_error(), evhttp_uri_join(), evhttp_uriencode(), and evrpc_request_done().
evbuffer_peek()
int evbuffer_peek (struct evbuffer * buffer, ev_ssize_t len, struct evbuffer_ptr * start_at, struct evbuffer_iovec * vec, int n_vec)
Definition at line 2785 of file buffer.c.
{
    struct evbuffer_chain *chain;
    int idx = 0;
    ev_ssize_t len_so_far = 0;
    /* Avoid locking in trivial edge cases */
    if (start_at && start_at->internal_.chain == NULL)
        return 0;
    EVBUFFER_LOCK(buffer);
    if (start_at) {
        chain = start_at->internal_.chain;
        len_so_far = chain->off
            - start_at->internal_.pos_in_chain;
        idx = 1;
        if (n_vec > 0) {
            vec[0].iov_base = (void *)(chain->buffer + chain->misalign
                + start_at->internal_.pos_in_chain);
            vec[0].iov_len = len_so_far;
        }
        chain = chain->next;
    } else {
        chain = buffer->first;
    }
    if (n_vec == 0 && len < 0) {
        /* If no vectors are provided and they asked for "everything",
         * pretend they asked for the actual available amount. */
        len = buffer->total_len;
        if (start_at) {
            len -= start_at->pos;
        }
    }
    while (chain) {
        if (len >= 0 && len_so_far >= len)
            break;
        if (idx<n_vec) {
            vec[idx].iov_base = (void *)(chain->buffer + chain->misalign);
            vec[idx].iov_len = chain->off;
        } else if (len<0) {
            break;
        }
        ++idx;
        len_so_far += chain->off;
        chain = chain->next;
    }
    EVBUFFER_UNLOCK(buffer);
    return idx;
}
References evbuffer_chain::buffer, EVBUFFER_LOCK, EVBUFFER_UNLOCK, evbuffer_chain::misalign, evbuffer_chain::next, and evbuffer_chain::off.
Referenced by do_write().
evbuffer_prepend()
int evbuffer_prepend (struct evbuffer * buf, const void * data, size_t datlen)
Definition at line 1827 of file buffer.c.
{
    struct evbuffer_chain *chain, *tmp;
    int result = -1;
    EVBUFFER_LOCK(buf);
    if (datlen == 0) {
        result = 0;
        goto done;
    }
    if (buf->freeze_start) {
        goto done;
    }
    if (datlen > EV_SIZE_MAX - buf->total_len) {
        goto done;
    }
    chain = buf->first;
    if (chain == NULL) {
        chain = evbuffer_chain_new(datlen);
        if (!chain)
            goto done;
        evbuffer_chain_insert(buf, chain);
    }
    /* we cannot touch immutable buffers */
    if ((chain->flags & EVBUFFER_IMMUTABLE) == 0) {
        /* Always true for mutable buffers */
        EVUTIL_ASSERT(chain->misalign >= 0 &&
            (ev_uint64_t)chain->misalign <= EVBUFFER_CHAIN_MAX);
        /* If this chain is empty, we can treat it as
         * 'empty at the beginning' rather than 'empty at the end' */
        if (chain->off == 0)
            chain->misalign = chain->buffer_len;
        if ((size_t)chain->misalign >= datlen) {
            /* we have enough space to fit everything */
            memcpy(chain->buffer + chain->misalign - datlen,
                data, datlen);
            chain->off += datlen;
            chain->misalign -= datlen;
            buf->total_len += datlen;
            buf->n_add_for_cb += datlen;
            goto out;
        } else if (chain->misalign) {
            /* we can only fit some of the data. */
            memcpy(chain->buffer,
                (char*)data + datlen - chain->misalign,
                (size_t)chain->misalign);
            chain->off += (size_t)chain->misalign;
            buf->total_len += (size_t)chain->misalign;
            buf->n_add_for_cb += (size_t)chain->misalign;
            datlen -= (size_t)chain->misalign;
            chain->misalign = 0;
        }
    }
    /* we need to add another chain */
    if ((tmp = evbuffer_chain_new(datlen)) == NULL)
        goto done;
    buf->first = tmp;
    if (buf->last_with_datap == &buf->first && chain->off)
        buf->last_with_datap = &tmp->next;
    tmp->next = chain;
    tmp->off = datlen;
    EVUTIL_ASSERT(datlen <= tmp->buffer_len);
    tmp->misalign = tmp->buffer_len - datlen;
    memcpy(tmp->buffer + tmp->misalign, data, datlen);
    buf->total_len += datlen;
    buf->n_add_for_cb += datlen;
out:
    evbuffer_invoke_callbacks_(buf);
    result = 0;
done:
    EVBUFFER_UNLOCK(buf);
    return result;
}
References evbuffer_chain::buffer, evbuffer_chain::buffer_len, evbuffer_chain_insert(), EVBUFFER_CHAIN_MAX, evbuffer_chain_new(), EVBUFFER_IMMUTABLE, evbuffer_invoke_callbacks_(), EVBUFFER_LOCK, EVBUFFER_UNLOCK, EVUTIL_ASSERT, evbuffer::first, evbuffer_chain::flags, evbuffer::freeze_start, evbuffer::last_with_datap, evbuffer_chain::misalign, evbuffer::n_add_for_cb, evbuffer_chain::next, evbuffer_chain::off, and evbuffer::total_len.
evbuffer_prepend_buffer()
int evbuffer_prepend_buffer (struct evbuffer * outbuf, struct evbuffer * inbuf)
Definition at line 1055 of file buffer.c.
{
    struct evbuffer_chain *pinned, *last;
    size_t in_total_len, out_total_len;
    int result = 0;
    EVBUFFER_LOCK2(inbuf, outbuf);
    in_total_len = inbuf->total_len;
    out_total_len = outbuf->total_len;
    if (!in_total_len || inbuf == outbuf)
        goto done;
    if (outbuf->freeze_start || inbuf->freeze_start) {
        result = -1;
        goto done;
    }
    if (PRESERVE_PINNED(inbuf, &pinned, &last) < 0) {
        result = -1;
        goto done;
    }
    if (out_total_len == 0) {
        /* There might be an empty chain at the start of outbuf; free
         * it. */
        evbuffer_free_all_chains(outbuf->first);
        COPY_CHAIN(outbuf, inbuf);
    } else {
        PREPEND_CHAIN(outbuf, inbuf);
    }
    RESTORE_PINNED(inbuf, pinned, last);
    inbuf->n_del_for_cb += in_total_len;
    outbuf->n_add_for_cb += in_total_len;
    evbuffer_invoke_callbacks_(inbuf);
    evbuffer_invoke_callbacks_(outbuf);
done:
    EVBUFFER_UNLOCK2(inbuf, outbuf);
    return result;
}
References COPY_CHAIN(), evbuffer_free_all_chains(), evbuffer_invoke_callbacks_(), EVBUFFER_LOCK2, EVBUFFER_UNLOCK2, evbuffer::first, evbuffer::freeze_start, evbuffer::n_add_for_cb, evbuffer::n_del_for_cb, PREPEND_CHAIN(), PRESERVE_PINNED(), RESTORE_PINNED(), and evbuffer::total_len.
evbuffer_ptr_memcmp()
static int evbuffer_ptr_memcmp (const struct evbuffer * buf, const struct evbuffer_ptr * pos, const char * mem, size_t len) static
Compare the bytes in buf at position pos to the len bytes in mem. Return less than 0, 0, or greater than 0 as memcmp.
Definition at line 2679 of file buffer.c.
{
    struct evbuffer_chain *chain;
    size_t position;
    int r;
    ASSERT_EVBUFFER_LOCKED(buf);
    if (pos->pos < 0 ||
        EV_SIZE_MAX - len < (size_t)pos->pos ||
        pos->pos + len > buf->total_len)
        return -1;
    chain = pos->internal_.chain;
    position = pos->internal_.pos_in_chain;
    while (len && chain) {
        size_t n_comparable;
        if (len + position > chain->off)
            n_comparable = chain->off - position;
        else
            n_comparable = len;
        r = memcmp(chain->buffer + chain->misalign + position, mem,
            n_comparable);
        if (r)
            return r;
        mem += n_comparable;
        len -= n_comparable;
        position = 0;
        chain = chain->next;
    }
    return 0;
}
References ASSERT_EVBUFFER_LOCKED, evbuffer_chain::buffer, evbuffer_chain::misalign, evbuffer_chain::next, evbuffer_chain::off, and evbuffer::total_len.
Referenced by evbuffer_search_range().
evbuffer_ptr_set()
int evbuffer_ptr_set (struct evbuffer * buf, struct evbuffer_ptr * pos, size_t position, enum evbuffer_ptr_how how)
Definition at line 2623 of file buffer.c.
{
    size_t left = position;
    struct evbuffer_chain *chain = NULL;
    int result = 0;
    EVBUFFER_LOCK(buf);
    switch (how) {
    case EVBUFFER_PTR_SET:
        chain = buf->first;
        pos->pos = position;
        position = 0;
        break;
    case EVBUFFER_PTR_ADD:
        /* this avoids iterating over all previous chains if
           we just want to advance the position */
        if (pos->pos < 0 || EV_SIZE_MAX - position < (size_t)pos->pos) {
            EVBUFFER_UNLOCK(buf);
            return -1;
        }
        chain = pos->internal_.chain;
        pos->pos += position;
        position = pos->internal_.pos_in_chain;
        break;
    }
    EVUTIL_ASSERT(EV_SIZE_MAX - left >= position);
    while (chain && position + left >= chain->off) {
        left -= chain->off - position;
        chain = chain->next;
        position = 0;
    }
    if (chain) {
        pos->internal_.chain = chain;
        pos->internal_.pos_in_chain = position + left;
    } else if (left == 0) {
        /* The first byte in the (nonexistent) chain after the last chain */
        pos->internal_.chain = NULL;
        pos->internal_.pos_in_chain = 0;
    } else {
        PTR_NOT_FOUND(pos);
        result = -1;
    }
    EVBUFFER_UNLOCK(buf);
    return result;
}
References EVBUFFER_LOCK, EVBUFFER_UNLOCK, EVUTIL_ASSERT, evbuffer::first, evbuffer_chain::next, evbuffer_chain::off, and PTR_NOT_FOUND.
Referenced by evbuffer_ptr_subtract().
evbuffer_ptr_subtract()
static int evbuffer_ptr_subtract (struct evbuffer * buf, struct evbuffer_ptr * pos, size_t howfar) static
Definition at line 2603 of file buffer.c.
{
    if (pos->pos < 0)
        return -1;
    if (howfar > (size_t)pos->pos)
        return -1;
    if (pos->internal_.chain && howfar <= pos->internal_.pos_in_chain) {
        pos->internal_.pos_in_chain -= howfar;
        pos->pos -= howfar;
        return 0;
    } else {
        const size_t newpos = pos->pos - howfar;
        /* Here's the inefficient part: it walks over the
         * chains until we hit newpos. */
        return evbuffer_ptr_set(buf, pos, newpos, EVBUFFER_PTR_SET);
    }
}
References evbuffer_ptr_set().
Referenced by evbuffer_search_eol().
evbuffer_pullup()
unsigned char * evbuffer_pullup (struct evbuffer * buf, ev_ssize_t size)
Definition at line 1350 of file buffer.c.
{
    struct evbuffer_chain *chain, *next, *tmp, *last_with_data;
    unsigned char *buffer, *result = NULL;
    ev_ssize_t remaining;
    int removed_last_with_data = 0;
    int removed_last_with_datap = 0;
    EVBUFFER_LOCK(buf);
    chain = buf->first;
    if (size < 0)
        size = buf->total_len;
    /* if size > buf->total_len, we cannot guarantee to the user that she
     * is going to have a long enough buffer afterwards; so we return
     * NULL */
    if (size == 0 || (size_t)size > buf->total_len)
        goto done;
    /* No need to pull up anything; the first size bytes are
     * already here. */
    if (chain->off >= (size_t)size) {
        result = chain->buffer + chain->misalign;
        goto done;
    }
    /* Make sure that none of the chains we need to copy from is pinned. */
    remaining = size - chain->off;
    EVUTIL_ASSERT(remaining >= 0);
    for (tmp=chain->next; tmp; tmp=tmp->next) {
        if (CHAIN_PINNED(tmp))
            goto done;
        if (tmp->off >= (size_t)remaining)
            break;
        remaining -= tmp->off;
    }
    if (CHAIN_PINNED(chain)) {
        size_t old_off = chain->off;
        if (CHAIN_SPACE_LEN(chain) < size - chain->off) {
            /* not enough room at end of chunk. */
            goto done;
        }
        buffer = CHAIN_SPACE_PTR(chain);
        tmp = chain;
        tmp->off = size;
        size -= old_off;
        chain = chain->next;
    } else if (chain->buffer_len - chain->misalign >= (size_t)size) {
        /* already have enough space in the first chain */
        size_t old_off = chain->off;
        buffer = chain->buffer + chain->misalign + chain->off;
        tmp = chain;
        tmp->off = size;
        size -= old_off;
        chain = chain->next;
    } else {
        if ((tmp = evbuffer_chain_new(size)) == NULL) {
            event_warn("%s: out of memory", __func__);
            goto done;
        }
        buffer = tmp->buffer;
        tmp->off = size;
        buf->first = tmp;
    }
    /* TODO(niels): deal with buffers that point to NULL like sendfile */
    /* Copy and free every chunk that will be entirely pulled into tmp */
    last_with_data = *buf->last_with_datap;
    for (; chain != NULL && (size_t)size >= chain->off; chain = next) {
        next = chain->next;
        if (chain->buffer) {
            memcpy(buffer, chain->buffer + chain->misalign, chain->off);
            size -= chain->off;
            buffer += chain->off;
        }
        if (chain == last_with_data)
            removed_last_with_data = 1;
        if (&chain->next == buf->last_with_datap)
            removed_last_with_datap = 1;
        evbuffer_chain_free(chain);
    }
    if (chain != NULL) {
        memcpy(buffer, chain->buffer + chain->misalign, size);
        chain->misalign += size;
        chain->off -= size;
    } else {
        buf->last = tmp;
    }
    tmp->next = chain;
    if (removed_last_with_data) {
        buf->last_with_datap = &buf->first;
    } else if (removed_last_with_datap) {
        if (buf->first->next && buf->first->next->off)
            buf->last_with_datap = &buf->first->next;
        else
            buf->last_with_datap = &buf->first;
    }
    result = (tmp->buffer + tmp->misalign);
done:
    EVBUFFER_UNLOCK(buf);
    return result;
}
References __func__, evbuffer_chain::buffer, evbuffer_chain::buffer_len, CHAIN_PINNED, CHAIN_SPACE_LEN, CHAIN_SPACE_PTR, evbuffer_chain_free(), evbuffer_chain_new(), EVBUFFER_LOCK, EVBUFFER_UNLOCK, event_warn(), EVUTIL_ASSERT, evbuffer::first, evbuffer::last, evbuffer::last_with_datap, evbuffer_chain::misalign, evbuffer_chain::next, evbuffer_chain::off, and evbuffer::total_len.
Referenced by decode_tag_internal(), evbuffer_find(), evbuffer_write_atmost(), and evtag_unmarshal().
evbuffer_read()
int evbuffer_read (struct evbuffer * buf, evutil_socket_t fd, int howmuch)
USE_IOVEC_IMPL
Definition at line 2284 of file buffer.c.
{
    struct evbuffer_chain **chainp;
    int n;
    int result;
#ifdef USE_IOVEC_IMPL
    int nvecs, i, remaining;
#else
    struct evbuffer_chain *chain;
    unsigned char *p;
#endif
    EVBUFFER_LOCK(buf);
    if (buf->freeze_end) {
        result = -1;
        goto done;
    }
    n = get_n_bytes_readable_on_socket(fd);
    if (n <= 0 || n > EVBUFFER_MAX_READ)
        n = EVBUFFER_MAX_READ;
    if (howmuch < 0 || howmuch > n)
        howmuch = n;
#ifdef USE_IOVEC_IMPL
    /* Since we can use iovecs, we're willing to use the last
     * NUM_READ_IOVEC chains. */
    if (evbuffer_expand_fast_(buf, howmuch, NUM_READ_IOVEC) == -1) {
        result = -1;
        goto done;
    } else {
        IOV_TYPE vecs[NUM_READ_IOVEC];
#ifdef EVBUFFER_IOVEC_IS_NATIVE_
        nvecs = evbuffer_read_setup_vecs_(buf, howmuch, vecs,
            NUM_READ_IOVEC, &chainp, 1);
#else
        /* We aren't using the native struct iovec.  Therefore,
           we are on win32. */
        struct evbuffer_iovec ev_vecs[NUM_READ_IOVEC];
        nvecs = evbuffer_read_setup_vecs_(buf, howmuch, ev_vecs, 2,
            &chainp, 1);
        for (i=0; i < nvecs; ++i)
            WSABUF_FROM_EVBUFFER_IOV(&vecs[i], &ev_vecs[i]);
#endif
#ifdef _WIN32
        {
            DWORD bytesRead;
            DWORD flags=0;
            if (WSARecv(fd, vecs, nvecs, &bytesRead, &flags, NULL, NULL)) {
                /* The read failed. It might be a close,
                 * or it might be an error. */
                if (WSAGetLastError() == WSAECONNABORTED)
                    n = 0;
                else
                    n = -1;
            } else
                n = bytesRead;
        }
#else
        n = readv(fd, vecs, nvecs);
#endif
    }
#else
    /* If we don't have FIONREAD, we might waste some space here */
    /* XXX we _will_ waste some space here if there is any space left
     * over on buf->last. */
    if ((chain = evbuffer_expand_singlechain(buf, howmuch)) == NULL) {
        result = -1;
        goto done;
    }
    /* We can append new data at this point */
    p = chain->buffer + chain->misalign + chain->off;
#ifndef _WIN32
    n = read(fd, p, howmuch);
#else
    n = recv(fd, p, howmuch, 0);
#endif
#endif /* USE_IOVEC_IMPL */
    if (n == -1) {
        result = -1;
        goto done;
    }
    if (n == 0) {
        result = 0;
        goto done;
    }
#ifdef USE_IOVEC_IMPL
    remaining = n;
    for (i=0; i < nvecs; ++i) {
        /* can't overflow, since only mutable chains have
         * huge misaligns. */
        size_t space = (size_t) CHAIN_SPACE_LEN(*chainp);
        /* XXXX This is a kludge that can waste space in perverse
         * situations. */
        if (space > EVBUFFER_CHAIN_MAX)
            space = EVBUFFER_CHAIN_MAX;
        if ((ev_ssize_t)space < remaining) {
            (*chainp)->off += space;
            remaining -= (int)space;
        } else {
            (*chainp)->off += remaining;
            buf->last_with_datap = chainp;
            break;
        }
        chainp = &(*chainp)->next;
    }
#else
    chain->off += n;
    advance_last_with_data(buf);
#endif
    buf->total_len += n;
    buf->n_add_for_cb += n;
    /* Tell someone about changes in this buffer */
    evbuffer_invoke_callbacks_(buf);
    result = n;
done:
    EVBUFFER_UNLOCK(buf);
    return result;
}
References advance_last_with_data(), evbuffer_chain::buffer, CHAIN_SPACE_LEN, EVBUFFER_CHAIN_MAX, evbuffer_expand_fast_(), evbuffer_expand_singlechain(), evbuffer_invoke_callbacks_(), EVBUFFER_LOCK, EVBUFFER_MAX_READ, evbuffer_read_setup_vecs_(), EVBUFFER_UNLOCK, evbuffer::freeze_end, get_n_bytes_readable_on_socket(), evbuffer::last_with_datap, evbuffer_chain::misalign, evbuffer::n_add_for_cb, evbuffer_chain::next, NUM_READ_IOVEC, evbuffer_chain::off, evbuffer::total_len, and WSABUF_FROM_EVBUFFER_IOV.
Referenced by bufferevent_readcb().
evbuffer_read_setup_vecs_()
int evbuffer_read_setup_vecs_ (struct evbuffer * buf, ev_ssize_t howmuch, struct evbuffer_iovec * vecs, int n_vecs_avail, struct evbuffer_chain *** chainp, int exact)
Helper function to figure out which space to use for reading data into an evbuffer. Internal use only.
Parameters
buf The buffer to read into
howmuch How much we want to read.
vecs An array of two or more iovecs or WSABUFs.
n_vecs_avail The length of vecs
chainp A pointer to a variable to hold the first chain we're reading into.
exact Boolean: if true, we do not provide more than 'howmuch' space in the vectors, even if more space is available.
Returns
The number of buffers we're using.
Definition at line 2225 of file buffer.c.
{
    struct evbuffer_chain *chain;
    struct evbuffer_chain **firstchainp;
    size_t so_far;
    int i;
    ASSERT_EVBUFFER_LOCKED(buf);
    if (howmuch < 0)
        return -1;
    so_far = 0;
    /* Let firstchain be the first chain with any space on it */
    firstchainp = buf->last_with_datap;
    EVUTIL_ASSERT(*firstchainp);
    if (CHAIN_SPACE_LEN(*firstchainp) == 0) {
        firstchainp = &(*firstchainp)->next;
    }
    chain = *firstchainp;
    EVUTIL_ASSERT(chain);
    for (i = 0; i < n_vecs_avail && so_far < (size_t)howmuch; ++i) {
        size_t avail = (size_t) CHAIN_SPACE_LEN(chain);
        if (avail > (howmuch - so_far) && exact)
            avail = howmuch - so_far;
        vecs[i].iov_base = (void *)CHAIN_SPACE_PTR(chain);
        vecs[i].iov_len = avail;
        so_far += avail;
        chain = chain->next;
    }
    *chainp = firstchainp;
    return i;
}
References ASSERT_EVBUFFER_LOCKED, CHAIN_SPACE_LEN, CHAIN_SPACE_PTR, EVUTIL_ASSERT, evbuffer::last_with_datap, and evbuffer_chain::next.
Referenced by evbuffer_launch_read_(), evbuffer_read(), and evbuffer_reserve_space().
evbuffer_readline()
char * evbuffer_readline (struct evbuffer * buffer)
Definition at line 1468 of file buffer.c.
{
    return evbuffer_readln(buffer, NULL, EVBUFFER_EOL_ANY);
}
References evbuffer_readln().
evbuffer_readln()
char * evbuffer_readln (struct evbuffer * buffer, size_t * n_read_out, enum evbuffer_eol_style eol_style)
Definition at line 1687 of file buffer.c.
{
    struct evbuffer_ptr it;
    char *line;
    size_t n_to_copy=0, extra_drain=0;
    char *result = NULL;
    EVBUFFER_LOCK(buffer);
    if (buffer->freeze_start) {
        goto done;
    }
    it = evbuffer_search_eol(buffer, NULL, &extra_drain, eol_style);
    if (it.pos < 0)
        goto done;
    n_to_copy = it.pos;
    if ((line = mm_malloc(n_to_copy+1)) == NULL) {
        event_warn("%s: out of memory", __func__);
        goto done;
    }
    evbuffer_remove(buffer, line, n_to_copy);
    line[n_to_copy] = '\0';
    evbuffer_drain(buffer, extra_drain);
    result = line;
done:
    EVBUFFER_UNLOCK(buffer);
    if (n_read_out)
        *n_read_out = result ? n_to_copy : 0;
    return result;
}
References __func__, evbuffer_drain(), EVBUFFER_LOCK, evbuffer_remove(), evbuffer_search_eol(), EVBUFFER_UNLOCK, event_warn(), and mm_malloc.
Referenced by evbuffer_readline(), evhttp_handle_chunked_read(), evhttp_parse_firstline_(), and evhttp_parse_headers_().
evbuffer_remove()
int evbuffer_remove (struct evbuffer * buf, void * data_out, size_t datlen)
Definition at line 1170 of file buffer.c.
{
    ev_ssize_t n;
    EVBUFFER_LOCK(buf);
    n = evbuffer_copyout_from(buf, NULL, data_out, datlen);
    if (n > 0) {
        if (evbuffer_drain(buf, n)<0)
            n = -1;
    }
    EVBUFFER_UNLOCK(buf);
    return (int)n;
}
References evbuffer_copyout_from(), evbuffer_drain(), EVBUFFER_LOCK, and EVBUFFER_UNLOCK.
Referenced by bio_bufferevent_read(), bufferevent_read(), evbuffer_readln(), evhttp_uri_join(), evhttp_uriencode(), evtag_unmarshal_fixed(), and evtag_unmarshal_string().
evbuffer_remove_all_callbacks()
static void evbuffer_remove_all_callbacks (struct evbuffer * buffer) static
Definition at line 550 of file buffer.c.
{
    struct evbuffer_cb_entry *cbent;
    while ((cbent = LIST_FIRST(&buffer->callbacks))) {
        LIST_REMOVE(cbent, next);
        mm_free(cbent);
    }
}
References mm_free.
Referenced by evbuffer_decref_and_unlock_(), and evbuffer_setcb().
evbuffer_remove_buffer()
int evbuffer_remove_buffer (struct evbuffer * src, struct evbuffer * dst, size_t datlen)
Definition at line 1260 of file buffer.c.
{
    /*XXX We should have an option to force this to be zero-copy.*/
    /*XXX can fail badly on sendfile case. */
    struct evbuffer_chain *chain, *previous;
    size_t nread = 0;
    int result;
    EVBUFFER_LOCK2(src, dst);
    chain = previous = src->first;
    if (datlen == 0 || dst == src) {
        result = 0;
        goto done;
    }
    if (dst->freeze_end || src->freeze_start) {
        result = -1;
        goto done;
    }
    /* short-cut if there is no more data buffered */
    if (datlen >= src->total_len) {
        datlen = src->total_len;
        evbuffer_add_buffer(dst, src);
        result = (int)datlen; /*XXXX should return ev_ssize_t*/
        goto done;
    }
    /* removes chains if possible */
    while (chain->off <= datlen) {
        /* We can't remove the last with data from src unless we
         * remove all chains, in which case we would have done the if
         * block above */
        EVUTIL_ASSERT(chain != *src->last_with_datap);
        nread += chain->off;
        datlen -= chain->off;
        previous = chain;
        if (src->last_with_datap == &chain->next)
            src->last_with_datap = &src->first;
        chain = chain->next;
    }
    if (chain != src->first) {
        /* we can remove the chain */
        struct evbuffer_chain **chp;
        chp = evbuffer_free_trailing_empty_chains(dst);
        if (dst->first == NULL) {
            dst->first = src->first;
        } else {
            *chp = src->first;
        }
        dst->last = previous;
        previous->next = NULL;
        src->first = chain;
        advance_last_with_data(dst);
        dst->total_len += nread;
        dst->n_add_for_cb += nread;
    }
    /* we know that there is more data in the src buffer than
     * we want to read, so we manually drain the chain */
    evbuffer_add(dst, chain->buffer + chain->misalign, datlen);
    chain->misalign += datlen;
    chain->off -= datlen;
    nread += datlen;
    /* You might think we would want to increment dst->n_add_for_cb
     * here too.  But evbuffer_add above already took care of that.
     */
    src->total_len -= nread;
    src->n_del_for_cb += nread;
    if (nread) {
        evbuffer_invoke_callbacks_(dst);
        evbuffer_invoke_callbacks_(src);
    }
    result = (int)nread;/*XXXX should change return type */
done:
    EVBUFFER_UNLOCK2(src, dst);
    return result;
}
References advance_last_with_data(), evbuffer_chain::buffer, evbuffer_add(), evbuffer_add_buffer(), evbuffer_free_trailing_empty_chains(), evbuffer_invoke_callbacks_(), EVBUFFER_LOCK2, EVBUFFER_UNLOCK2, EVUTIL_ASSERT, evbuffer::first, evbuffer::freeze_end, evbuffer::freeze_start, evbuffer::last, evbuffer::last_with_datap, evbuffer_chain::misalign, evbuffer::n_add_for_cb, evbuffer::n_del_for_cb, evbuffer_chain::next, evbuffer_chain::off, and evbuffer::total_len.
Referenced by be_null_filter(), be_pair_transfer(), evhttp_handle_chunked_read(), and evhttp_read_body().
evbuffer_remove_cb()
int evbuffer_remove_cb (struct evbuffer * buffer, evbuffer_cb_func cb, void * cbarg)
Definition at line 3360 of file buffer.c.
{
    struct evbuffer_cb_entry *cbent;
    int result = -1;
    EVBUFFER_LOCK(buffer);
    LIST_FOREACH(cbent, &buffer->callbacks, next) {
        if (cb == cbent->cb.cb_func && cbarg == cbent->cbarg) {
            result = evbuffer_remove_cb_entry(buffer, cbent);
            goto done;
        }
    }
done:
    EVBUFFER_UNLOCK(buffer);
    return result;
}
References evbuffer_cb_entry::cb, evbuffer_cb_entry::cb_func, evbuffer_cb_entry::cbarg, EVBUFFER_LOCK, evbuffer_remove_cb_entry(), and EVBUFFER_UNLOCK.
evbuffer_remove_cb_entry()
int evbuffer_remove_cb_entry (struct evbuffer * buffer, struct evbuffer_cb_entry * ent)
Definition at line 3349 of file buffer.c.
{
    EVBUFFER_LOCK(buffer);
    LIST_REMOVE(ent, next);
    EVBUFFER_UNLOCK(buffer);
    mm_free(ent);
    return 0;
}
References EVBUFFER_LOCK, EVBUFFER_UNLOCK, and mm_free.
Referenced by be_filter_destruct(), and evbuffer_remove_cb().
evbuffer_reserve_space()
int evbuffer_reserve_space (struct evbuffer * buf, ev_ssize_t size, struct evbuffer_iovec * vec, int n_vecs)
Definition at line 671 of file buffer.c.
{
    struct evbuffer_chain *chain, **chainp;
    int n = -1;
    EVBUFFER_LOCK(buf);
    if (buf->freeze_end)
        goto done;
    if (n_vecs < 1)
        goto done;
    if (n_vecs == 1) {
        if ((chain = evbuffer_expand_singlechain(buf, size)) == NULL)
            goto done;
        vec[0].iov_base = (void *)CHAIN_SPACE_PTR(chain);
        vec[0].iov_len = (size_t)CHAIN_SPACE_LEN(chain);
        EVUTIL_ASSERT(size<0 || (size_t)vec[0].iov_len >= (size_t)size);
        n = 1;
    } else {
        if (evbuffer_expand_fast_(buf, size, n_vecs)<0)
            goto done;
        n = evbuffer_read_setup_vecs_(buf, size, vec, n_vecs,
                &chainp, 0);
    }
done:
    EVBUFFER_UNLOCK(buf);
    return n;
}
References CHAIN_SPACE_LEN, CHAIN_SPACE_PTR, evbuffer_expand_fast_(), evbuffer_expand_singlechain(), EVBUFFER_LOCK, evbuffer_read_setup_vecs_(), EVBUFFER_UNLOCK, EVUTIL_ASSERT, and evbuffer::freeze_end.
Referenced by do_read().
evbuffer_run_callbacks()
static void evbuffer_run_callbacks (struct evbuffer * buffer, int running_deferred) static
Definition at line 456 of file buffer.c.
{
    struct evbuffer_cb_entry *cbent, *next;
    struct evbuffer_cb_info info;
    size_t new_size;
    ev_uint32_t mask, masked_val;
    int clear = 1;
    if (running_deferred) {
        mask = EVBUFFER_CB_NODEFER|EVBUFFER_CB_ENABLED;
        masked_val = EVBUFFER_CB_ENABLED;
    } else if (buffer->deferred_cbs) {
        mask = EVBUFFER_CB_NODEFER|EVBUFFER_CB_ENABLED;
        masked_val = EVBUFFER_CB_NODEFER|EVBUFFER_CB_ENABLED;
        /* Don't zero-out n_add/n_del, since the deferred callbacks
           will want to see them. */
        clear = 0;
    } else {
        mask = EVBUFFER_CB_ENABLED;
        masked_val = EVBUFFER_CB_ENABLED;
    }
    ASSERT_EVBUFFER_LOCKED(buffer);
    if (LIST_EMPTY(&buffer->callbacks)) {
        buffer->n_add_for_cb = buffer->n_del_for_cb = 0;
        return;
    }
    if (buffer->n_add_for_cb == 0 && buffer->n_del_for_cb == 0)
        return;
    new_size = buffer->total_len;
    info.orig_size = new_size + buffer->n_del_for_cb - buffer->n_add_for_cb;
    info.n_added = buffer->n_add_for_cb;
    info.n_deleted = buffer->n_del_for_cb;
    if (clear) {
        buffer->n_add_for_cb = 0;
        buffer->n_del_for_cb = 0;
    }
    for (cbent = LIST_FIRST(&buffer->callbacks);
         cbent != LIST_END(&buffer->callbacks);
         cbent = next) {
        /* Get the 'next' pointer now in case this callback decides
         * to remove itself or something. */
        next = LIST_NEXT(cbent, next);
        if ((cbent->flags & mask) != masked_val)
            continue;
        if ((cbent->flags & EVBUFFER_CB_OBSOLETE))
            cbent->cb.cb_obsolete(buffer,
                info.orig_size, new_size, cbent->cbarg);
        else
            cbent->cb.cb_func(buffer, &info, cbent->cbarg);
    }
}
References ASSERT_EVBUFFER_LOCKED, evbuffer_cb_entry::cb, evbuffer_cb_entry::cb_func, evbuffer_cb_entry::cb_obsolete, evbuffer_cb_entry::cbarg, EVBUFFER_CB_NODEFER, EVBUFFER_CB_OBSOLETE, evbuffer_cb_entry::flags, and LIST_END.
Referenced by evbuffer_deferred_callback(), and evbuffer_invoke_callbacks_().
evbuffer_search()
struct evbuffer_ptr evbuffer_search (struct evbuffer * buffer, const char * what, size_t len, const struct evbuffer_ptr * start)
Definition at line 2715 of file buffer.c.
{
    return evbuffer_search_range(buffer, what, len, start, NULL);
}
References evbuffer_search_range().
Referenced by evbuffer_find(), and evbuffer_search_eol().
evbuffer_search_eol()
struct evbuffer_ptr evbuffer_search_eol (struct evbuffer * buffer, struct evbuffer_ptr * start, size_t * eol_len_out, enum evbuffer_eol_style eol_style)
Definition at line 1597 of file buffer.c.
{
    struct evbuffer_ptr it, it2;
    size_t extra_drain = 0;
    int ok = 0;
    /* Avoid locking in trivial edge cases */
    if (start && start->internal_.chain == NULL) {
        PTR_NOT_FOUND(&it);
        if (eol_len_out)
            *eol_len_out = extra_drain;
        return it;
    }
    EVBUFFER_LOCK(buffer);
    if (start) {
        memcpy(&it, start, sizeof(it));
    } else {
        it.pos = 0;
        it.internal_.chain = buffer->first;
        it.internal_.pos_in_chain = 0;
    }
    /* the eol_style determines our first stop character and how many
     * characters we are going to drain afterwards. */
    switch (eol_style) {
    case EVBUFFER_EOL_ANY:
        if (evbuffer_find_eol_char(&it) < 0)
            goto done;
        memcpy(&it2, &it, sizeof(it));
        extra_drain = evbuffer_strspn(&it2, "\r\n");
        break;
    case EVBUFFER_EOL_CRLF_STRICT: {
        it = evbuffer_search(buffer, "\r\n", 2, &it);
        if (it.pos < 0)
            goto done;
        extra_drain = 2;
        break;
    }
    case EVBUFFER_EOL_CRLF: {
        ev_ssize_t start_pos = it.pos;
        /* Look for a LF ... */
        if (evbuffer_strchr(&it, '\n') < 0)
            goto done;
        extra_drain = 1;
        /* ... optionally preceeded by a CR. */
        if (it.pos == start_pos)
            break; /* If the first character is \n, don't back up */
        /* This potentially does an extra linear walk over the first
         * few chains.  Probably, that's not too expensive unless you
         * have a really pathological setup. */
        memcpy(&it2, &it, sizeof(it));
        if (evbuffer_ptr_subtract(buffer, &it2, 1)<0)
            break;
        if (evbuffer_getchr(&it2) == '\r') {
            memcpy(&it, &it2, sizeof(it));
            extra_drain = 2;
        }
        break;
    }
    case EVBUFFER_EOL_LF:
        if (evbuffer_strchr(&it, '\n') < 0)
            goto done;
        extra_drain = 1;
        break;
    case EVBUFFER_EOL_NUL:
        if (evbuffer_strchr(&it, '\0') < 0)
            goto done;
        extra_drain = 1;
        break;
    default:
        goto done;
    }
    ok = 1;
done:
    EVBUFFER_UNLOCK(buffer);
    if (!ok)
        PTR_NOT_FOUND(&it);
    if (eol_len_out)
        *eol_len_out = extra_drain;
    return it;
}
References evbuffer_find_eol_char(), evbuffer_getchr(), EVBUFFER_LOCK, evbuffer_ptr_subtract(), evbuffer_search(), evbuffer_strchr(), evbuffer_strspn(), EVBUFFER_UNLOCK, and PTR_NOT_FOUND.
Referenced by evbuffer_readln().
evbuffer_search_range()
struct evbuffer_ptr evbuffer_search_range (struct evbuffer * buffer, const char * what, size_t len, const struct evbuffer_ptr * start, const struct evbuffer_ptr * end)
Definition at line 2721 of file buffer.c.
{
    struct evbuffer_ptr pos;
    struct evbuffer_chain *chain, *last_chain = NULL;
    const unsigned char *p;
    char first;
    EVBUFFER_LOCK(buffer);
    if (start) {
        memcpy(&pos, start, sizeof(pos));
        chain = pos.internal_.chain;
    } else {
        pos.pos = 0;
        chain = pos.internal_.chain = buffer->first;
        pos.internal_.pos_in_chain = 0;
    }
    if (end)
        last_chain = end->internal_.chain;
    if (!len || len > EV_SSIZE_MAX)
        goto done;
    first = what[0];
    while (chain) {
        const unsigned char *start_at =
            chain->buffer + chain->misalign +
            pos.internal_.pos_in_chain;
        p = memchr(start_at, first,
            chain->off - pos.internal_.pos_in_chain);
        if (p) {
            pos.pos += p - start_at;
            pos.internal_.pos_in_chain += p - start_at;
            if (!evbuffer_ptr_memcmp(buffer, &pos, what, len)) {
                if (end && pos.pos + (ev_ssize_t)len > end->pos)
                    goto not_found;
                else
                    goto done;
            }
            ++pos.pos;
            ++pos.internal_.pos_in_chain;
            if (pos.internal_.pos_in_chain == chain->off) {
                chain = pos.internal_.chain = chain->next;
                pos.internal_.pos_in_chain = 0;
            }
        } else {
            if (chain == last_chain)
                goto not_found;
            pos.pos += chain->off - pos.internal_.pos_in_chain;
            chain = pos.internal_.chain = chain->next;
            pos.internal_.pos_in_chain = 0;
        }
    }
not_found:
    PTR_NOT_FOUND(&pos);
done:
    EVBUFFER_UNLOCK(buffer);
    return pos;
}
References evbuffer_chain::buffer, EVBUFFER_LOCK, evbuffer_ptr_memcmp(), EVBUFFER_UNLOCK, evbuffer_chain::misalign, evbuffer_chain::next, evbuffer_chain::off, and PTR_NOT_FOUND.
Referenced by evbuffer_search().
evbuffer_set_flags()
int evbuffer_set_flags (struct evbuffer * buf, ev_uint64_t flags)
Definition at line 378 of file buffer.c.
{
    EVBUFFER_LOCK(buf);
    buf->flags |= (ev_uint32_t)flags;
    EVBUFFER_UNLOCK(buf);
    return 0;
}
References EVBUFFER_LOCK, EVBUFFER_UNLOCK, and evbuffer::flags.
Referenced by bufferevent_socket_new().
evbuffer_set_parent_()
void evbuffer_set_parent_ (struct evbuffer * buf, struct bufferevent * bev)
Set the parent bufferevent object for buf to bev
Definition at line 448 of file buffer.c.
{
    EVBUFFER_LOCK(buf);
    buf->parent = bev;
    EVBUFFER_UNLOCK(buf);
}
References EVBUFFER_LOCK, EVBUFFER_UNLOCK, and evbuffer::parent.
Referenced by bufferevent_init_common_().
evbuffer_setcb()
int evbuffer_setcb (struct evbuffer * buffer, evbuffer_cb cb, void * cbarg)
Definition at line 3312 of file buffer.c.
{
    EVBUFFER_LOCK(buffer);
    if (!LIST_EMPTY(&buffer->callbacks))
        evbuffer_remove_all_callbacks(buffer);
    if (cb) {
        struct evbuffer_cb_entry *ent =
            evbuffer_add_cb(buffer, NULL, cbarg);
        if (!ent) {
            EVBUFFER_UNLOCK(buffer);
            return -1;
        }
        ent->cb.cb_obsolete = cb;
        ent->flags |= EVBUFFER_CB_OBSOLETE;
    }
    EVBUFFER_UNLOCK(buffer);
    return 0;
}
References evbuffer_cb_entry::cb, evbuffer_cb_entry::cb_obsolete, evbuffer_cb_entry::cbarg, evbuffer_add_cb(), EVBUFFER_CB_OBSOLETE, EVBUFFER_LOCK, evbuffer_remove_all_callbacks(), EVBUFFER_UNLOCK, and evbuffer_cb_entry::flags.
evbuffer_strchr()
static ev_ssize_t evbuffer_strchr (struct evbuffer_ptr * it, const char chr) inline static
Definition at line 1474 of file buffer.c.
{
    struct evbuffer_chain *chain = it->internal_.chain;
    size_t i = it->internal_.pos_in_chain;
    while (chain != NULL) {
        char *buffer = (char *)chain->buffer + chain->misalign;
        char *cp = memchr(buffer+i, chr, chain->off-i);
        if (cp) {
            it->internal_.chain = chain;
            it->internal_.pos_in_chain = cp - buffer;
            it->pos += (cp - buffer - i);
            return it->pos;
        }
        it->pos += chain->off - i;
        i = 0;
        chain = chain->next;
    }
    return (-1);
}
References evbuffer_chain::buffer, evbuffer_chain::misalign, evbuffer_chain::next, and evbuffer_chain::off.
Referenced by evbuffer_search_eol().
evbuffer_strspn()
static size_t evbuffer_strspn (struct evbuffer_ptr * ptr, const char * chrset) inline static
Definition at line 1545 of file buffer.c.
{
    size_t count = 0;
    struct evbuffer_chain *chain = ptr->internal_.chain;
    size_t i = ptr->internal_.pos_in_chain;
    if (!chain)
        return 0;
    while (1) {
        char *buffer = (char *)chain->buffer + chain->misalign;
        for (; i < chain->off; ++i) {
            const char *p = chrset;
            while (*p) {
                if (buffer[i] == *p++)
                    goto next;
            }
            ptr->internal_.chain = chain;
            ptr->internal_.pos_in_chain = i;
            ptr->pos += count;
            return count;
        next:
            ++count;
        }
        i = 0;
        if (! chain->next) {
            ptr->internal_.chain = chain;
            ptr->internal_.pos_in_chain = i;
            ptr->pos += count;
            return count;
        }
        chain = chain->next;
    }
}
References evbuffer_chain::buffer, count, evbuffer_chain::misalign, evbuffer_chain::next, and evbuffer_chain::off.
Referenced by evbuffer_search_eol().
evbuffer_unfreeze()
int evbuffer_unfreeze (struct evbuffer * buffer, int start)
Definition at line 3413 of file buffer.c.
{
    EVBUFFER_LOCK(buffer);
    if (start)
        buffer->freeze_start = 0;
    else
        buffer->freeze_end = 0;
    EVBUFFER_UNLOCK(buffer);
    return 0;
}
References EVBUFFER_LOCK, and EVBUFFER_UNLOCK.
Referenced by be_pair_transfer(), be_socket_setfd(), bufferevent_readcb(), bufferevent_writecb(), evbuffer_commit_read_(), evbuffer_commit_write_(), evbuffer_launch_read_(), evbuffer_launch_write_(), and evhttp_connection_read_on_write_error().
evbuffer_unlock()
void evbuffer_unlock (struct evbuffer * buf)
Definition at line 601 of file buffer.c.
{
    EVBUFFER_UNLOCK(buf);
}
References EVBUFFER_UNLOCK.
evbuffer_write()
int evbuffer_write (struct evbuffer * buffer, evutil_socket_t fd)
Definition at line 2572 of file buffer.c.
{
    return evbuffer_write_atmost(buffer, fd, -1);
}
References evbuffer_write_atmost().
evbuffer_write_atmost()
int evbuffer_write_atmost (struct evbuffer * buffer, evutil_socket_t fd, ev_ssize_t howmuch)
Definition at line 2524 of file buffer.c.
{
    int n = -1;
    EVBUFFER_LOCK(buffer);
    if (buffer->freeze_start) {
        goto done;
    }
    if (howmuch < 0 || (size_t)howmuch > buffer->total_len)
        howmuch = buffer->total_len;
    if (howmuch > 0) {
#ifdef USE_SENDFILE
        struct evbuffer_chain *chain = buffer->first;
        if (chain != NULL && (chain->flags & EVBUFFER_SENDFILE))
            n = evbuffer_write_sendfile(buffer, fd, howmuch);
        else {
#endif
#ifdef USE_IOVEC_IMPL
        n = evbuffer_write_iovec(buffer, fd, howmuch);
#elif defined(_WIN32)
        /* XXX(nickm) Don't disable this code until we know if
         * the WSARecv code above works. */
        void *p = evbuffer_pullup(buffer, howmuch);
        EVUTIL_ASSERT(p || !howmuch);
        n = send(fd, p, howmuch, 0);
#else
        void *p = evbuffer_pullup(buffer, howmuch);
        EVUTIL_ASSERT(p || !howmuch);
        n = write(fd, p, howmuch);
#endif
#ifdef USE_SENDFILE
        }
#endif
    }
    if (n > 0)
        evbuffer_drain(buffer, n);
done:
    EVBUFFER_UNLOCK(buffer);
    return (n);
}
References evbuffer_drain(), EVBUFFER_LOCK, evbuffer_pullup(), EVBUFFER_SENDFILE, EVBUFFER_UNLOCK, EVUTIL_ASSERT, and evbuffer_chain::flags.
Referenced by bufferevent_writecb(), and evbuffer_write().
find_eol_char()
static char * find_eol_char (char * s, size_t len) inline static
Definition at line 1496 of file buffer.c.
{
#define CHUNK_SZ 128
    /* Lots of benchmarking found this approach to be faster in practice
     * than doing two memchrs over the whole buffer, doin a memchr on each
     * char of the buffer, or trying to emulate memchr by hand. */
    char *s_end, *cr, *lf;
    s_end = s+len;
    while (s < s_end) {
        size_t chunk = (s + CHUNK_SZ < s_end) ? CHUNK_SZ : (s_end - s);
        cr = memchr(s, '\r', chunk);
        lf = memchr(s, '\n', chunk);
        if (cr) {
            if (lf && lf < cr)
                return lf;
            return cr;
        } else if (lf) {
            return lf;
        }
        s += CHUNK_SZ;
    }
    return NULL;
#undef CHUNK_SZ
}
References CHUNK_SZ.
Referenced by evbuffer_find_eol_char().
get_n_bytes_readable_on_socket()
static int get_n_bytes_readable_on_socket (evutil_socket_t fd) static
Definition at line 2263 of file buffer.c.
{
#if defined(FIONREAD) && defined(_WIN32)
    unsigned long lng = EVBUFFER_MAX_READ;
    if (ioctlsocket(fd, FIONREAD, &lng) < 0)
        return -1;
    /* Can overflow, but mostly harmlessly. XXXX */
    return (int)lng;
#elif defined(FIONREAD)
    int n = EVBUFFER_MAX_READ;
    if (ioctl(fd, FIONREAD, &n) < 0)
        return -1;
    return n;
#else
    return EVBUFFER_MAX_READ;
#endif
}
References EVBUFFER_MAX_READ.
Referenced by evbuffer_read().
HAS_PINNED_R()
static int HAS_PINNED_R (struct evbuffer * buf) inline static
Definition at line 794 of file buffer.c.
{
    return (buf->last && CHAIN_PINNED_R(buf->last));
}
References CHAIN_PINNED_R, and evbuffer::last.
Referenced by evbuffer_drain(), and PRESERVE_PINNED().
PREPEND_CHAIN()
static void PREPEND_CHAIN (struct evbuffer * dst, struct evbuffer * src) static
Definition at line 948 of file buffer.c.
{
    ASSERT_EVBUFFER_LOCKED(dst);
    ASSERT_EVBUFFER_LOCKED(src);
    src->last->next = dst->first;
    dst->first = src->first;
    dst->total_len += src->total_len;
    if (*dst->last_with_datap == NULL) {
        if (src->last_with_datap == &(src)->first)
            dst->last_with_datap = &dst->first;
        else
            dst->last_with_datap = src->last_with_datap;
    } else if (dst->last_with_datap == &dst->first) {
        dst->last_with_datap = &src->last->next;
    }
}
References ASSERT_EVBUFFER_LOCKED, evbuffer::first, evbuffer::last, evbuffer::last_with_datap, evbuffer_chain::next, and evbuffer::total_len.
Referenced by evbuffer_prepend_buffer().
PRESERVE_PINNED()
static int PRESERVE_PINNED (struct evbuffer * src, struct evbuffer_chain ** first, struct evbuffer_chain ** last) static
Definition at line 814 of file buffer.c.
{
    struct evbuffer_chain *chain, **pinned;
    ASSERT_EVBUFFER_LOCKED(src);
    if (!HAS_PINNED_R(src)) {
        *first = *last = NULL;
        return 0;
    }
    pinned = src->last_with_datap;
    if (!CHAIN_PINNED_R(*pinned))
        pinned = &(*pinned)->next;
    EVUTIL_ASSERT(CHAIN_PINNED_R(*pinned));
    chain = *first = *pinned;
    *last = src->last;
    /* If there's data in the first pinned chain, we need to allocate
     * a new chain and copy the data over. */
    if (chain->off) {
        struct evbuffer_chain *tmp;
        EVUTIL_ASSERT(pinned == src->last_with_datap);
        tmp = evbuffer_chain_new(chain->off);
        if (!tmp)
            return -1;
        memcpy(tmp->buffer, chain->buffer + chain->misalign,
            chain->off);
        tmp->off = chain->off;
        *src->last_with_datap = tmp;
        src->last = tmp;
        chain->misalign += chain->off;
        chain->off = 0;
    } else {
        src->last = *src->last_with_datap;
        *pinned = NULL;
    }
    return 0;
}
References ASSERT_EVBUFFER_LOCKED, evbuffer_chain::buffer, CHAIN_PINNED_R, evbuffer_chain_new(), EVUTIL_ASSERT, HAS_PINNED_R(), evbuffer::last, evbuffer::last_with_datap, evbuffer_chain::misalign, evbuffer_chain::next, and evbuffer_chain::off.
Referenced by evbuffer_add_buffer(), and evbuffer_prepend_buffer().
RESTORE_PINNED()
static void RESTORE_PINNED (struct evbuffer * src, struct evbuffer_chain * pinned, struct evbuffer_chain * last) inline static
Definition at line 858 of file buffer.c.
{
    ASSERT_EVBUFFER_LOCKED(src);
    if (!pinned) {
        ZERO_CHAIN(src);
        return;
    }
    src->first = pinned;
    src->last = last;
    src->last_with_datap = &src->first;
    src->total_len = 0;
}
References ASSERT_EVBUFFER_LOCKED, evbuffer::first, evbuffer::last, evbuffer::last_with_datap, evbuffer::total_len, and ZERO_CHAIN().
Referenced by evbuffer_add_buffer(), and evbuffer_prepend_buffer().
ZERO_CHAIN()
static void ZERO_CHAIN (struct evbuffer * dst) inline static
Definition at line 800 of file buffer.c.
{
    ASSERT_EVBUFFER_LOCKED(dst);
    dst->first = NULL;
    dst->last = NULL;
    dst->last_with_datap = &(dst)->first;
    dst->total_len = 0;
}
References ASSERT_EVBUFFER_LOCKED, evbuffer::first, evbuffer::last, evbuffer::last_with_datap, and evbuffer::total_len.
Referenced by evbuffer_drain(), evbuffer_expand_fast_(), and RESTORE_PINNED().