libdogecoin: src/libevent/listener.c File Reference
listener.c File Reference
#include "event2/event-config.h"
#include "evconfig-private.h"
#include <sys/types.h>
#include <errno.h>
#include "event2/listener.h"
#include "event2/util.h"
#include "event2/event.h"
#include "event2/event_struct.h"
#include "mm-internal.h"
#include "util-internal.h"
#include "log-internal.h"
#include "evthread-internal.h"
Data Structures
struct evconnlistener_ops
struct evconnlistener
struct evconnlistener_event
Macros
#define LOCK(listener) EVLOCK_LOCK((listener)->lock, 0)
#define UNLOCK(listener) EVLOCK_UNLOCK((listener)->lock, 0)
Functions
struct evconnlistener * evconnlistener_new_async (struct event_base *base, evconnlistener_cb cb, void *ptr, unsigned flags, int backlog, evutil_socket_t fd)
static int event_listener_enable (struct evconnlistener *)
static int event_listener_disable (struct evconnlistener *)
static void event_listener_destroy (struct evconnlistener *)
static evutil_socket_t event_listener_getfd (struct evconnlistener *)
static struct event_base * event_listener_getbase (struct evconnlistener *)
static int listener_decref_and_unlock (struct evconnlistener *listener)
static void listener_read_cb (evutil_socket_t, short, void *)
struct evconnlistener * evconnlistener_new (struct event_base *base, evconnlistener_cb cb, void *ptr, unsigned flags, int backlog, evutil_socket_t fd)
struct evconnlistener * evconnlistener_new_bind (struct event_base *base, evconnlistener_cb cb, void *ptr, unsigned flags, int backlog, const struct sockaddr *sa, int socklen)
void evconnlistener_free (struct evconnlistener *lev)
int evconnlistener_enable (struct evconnlistener *lev)
int evconnlistener_disable (struct evconnlistener *lev)
evutil_socket_t evconnlistener_get_fd (struct evconnlistener *lev)
struct event_base * evconnlistener_get_base (struct evconnlistener *lev)
void evconnlistener_set_cb (struct evconnlistener *lev, evconnlistener_cb cb, void *arg)
void evconnlistener_set_error_cb (struct evconnlistener *lev, evconnlistener_errorcb errorcb)
Variables
static const struct evconnlistener_ops evconnlistener_event_ops
Macro Definition Documentation
LOCK
#define LOCK (listener) EVLOCK_LOCK((listener)->lock, 0)
Definition at line 106 of file listener.c.
UNLOCK
#define UNLOCK (listener) EVLOCK_UNLOCK((listener)->lock, 0)
Definition at line 107 of file listener.c.
Function Documentation
evconnlistener_disable()
int evconnlistener_disable (struct evconnlistener * lev)
Definition at line 307 of file listener.c.
{
    int r;
    LOCK(lev);
    lev->enabled = 0;
    r = lev->ops->disable(lev);
    UNLOCK(lev);
    return r;
}
References evconnlistener_ops::disable, evconnlistener::enabled, LOCK, evconnlistener::ops, and UNLOCK.
evconnlistener_enable()
int evconnlistener_enable (struct evconnlistener * lev)
Definition at line 293 of file listener.c.
{
    int r;
    LOCK(lev);
    lev->enabled = 1;
    if (lev->cb)
        r = lev->ops->enable(lev);
    else
        r = 0;
    UNLOCK(lev);
    return r;
}
References evconnlistener::cb, evconnlistener_ops::enable, evconnlistener::enabled, LOCK, evconnlistener::ops, and UNLOCK.
Referenced by evconnlistener_new(), and evconnlistener_set_cb().
evconnlistener_free()
void evconnlistener_free (struct evconnlistener * lev)
Definition at line 270 of file listener.c.
{
    LOCK(lev);
    lev->cb = NULL;
    lev->errorcb = NULL;
    if (lev->ops->shutdown)
        lev->ops->shutdown(lev);
    listener_decref_and_unlock(lev);
}
References evconnlistener::cb, evconnlistener::errorcb, listener_decref_and_unlock(), LOCK, evconnlistener::ops, and evconnlistener_ops::shutdown.
Referenced by evhttp_accept_socket_with_handle(), evhttp_del_accept_socket(), and evhttp_free().
evconnlistener_get_base()
struct event_base * evconnlistener_get_base (struct evconnlistener * lev)
Definition at line 352 of file listener.c.
{
    struct event_base *base;
    LOCK(lev);
    base = lev->ops->getbase(lev);
    UNLOCK(lev);
    return base;
}
References evconnlistener_ops::getbase, LOCK, evconnlistener::ops, and UNLOCK.
evconnlistener_get_fd()
evutil_socket_t evconnlistener_get_fd (struct evconnlistener * lev)
Definition at line 334 of file listener.c.
{
    evutil_socket_t fd;
    LOCK(lev);
    fd = lev->ops->getfd(lev);
    UNLOCK(lev);
    return fd;
}
References evconnlistener_ops::getfd, LOCK, evconnlistener::ops, and UNLOCK.
Referenced by evhttp_bound_socket_get_fd().
evconnlistener_new()
struct evconnlistener * evconnlistener_new (struct event_base * base, evconnlistener_cb cb, void * ptr, unsigned flags, int backlog, evutil_socket_t fd)
Definition at line 157 of file listener.c.
{
    struct evconnlistener_event *lev;
#ifdef _WIN32
    if (base && event_base_get_iocp_(base)) {
        const struct win32_extension_fns *ext =
            event_get_win32_extension_fns_();
        if (ext->AcceptEx && ext->GetAcceptExSockaddrs)
            return evconnlistener_new_async(base, cb, ptr, flags,
                backlog, fd);
    }
#endif
    if (backlog > 0) {
        if (listen(fd, backlog) < 0)
            return NULL;
    } else if (backlog < 0) {
        if (listen(fd, 128) < 0)
            return NULL;
    }
    lev = mm_calloc(1, sizeof(struct evconnlistener_event));
    if (!lev)
        return NULL;
    lev->base.ops = &evconnlistener_event_ops;
    lev->base.cb = cb;
    lev->base.user_data = ptr;
    lev->base.flags = flags;
    lev->base.refcnt = 1;
    lev->base.accept4_flags = 0;
    if (!(flags & LEV_OPT_LEAVE_SOCKETS_BLOCKING))
        lev->base.accept4_flags |= EVUTIL_SOCK_NONBLOCK;
    if (flags & LEV_OPT_CLOSE_ON_EXEC)
        lev->base.accept4_flags |= EVUTIL_SOCK_CLOEXEC;
    if (flags & LEV_OPT_THREADSAFE) {
        EVTHREAD_ALLOC_LOCK(lev->base.lock, EVTHREAD_LOCKTYPE_RECURSIVE);
    }
    event_assign(&lev->listener, base, fd, EV_READ|EV_PERSIST,
        listener_read_cb, lev);
    if (!(flags & LEV_OPT_DISABLED))
        evconnlistener_enable(&lev->base);
    return &lev->base;
}
References evconnlistener::accept4_flags, evconnlistener_event::base, evconnlistener::cb, evconnlistener_enable(), evconnlistener_event_ops, evconnlistener_new_async(), event_assign(), event_base_get_iocp_(), event_get_win32_extension_fns_(), EVTHREAD_ALLOC_LOCK, EVUTIL_SOCK_CLOEXEC, EVUTIL_SOCK_NONBLOCK, evconnlistener::flags, evconnlistener_event::listener, listener_read_cb(), evconnlistener::lock, mm_calloc, evconnlistener::ops, evconnlistener::refcnt, and evconnlistener::user_data.
Referenced by evconnlistener_new_bind(), and evhttp_accept_socket_with_handle().
evconnlistener_new_async()
struct evconnlistener * evconnlistener_new_async (struct event_base * base, evconnlistener_cb cb, void * ptr, unsigned flags, int backlog, evutil_socket_t fd)
Referenced by evconnlistener_new().
evconnlistener_new_bind()
struct evconnlistener * evconnlistener_new_bind (struct event_base * base, evconnlistener_cb cb, void * ptr, unsigned flags, int backlog, const struct sockaddr * sa, int socklen)
Definition at line 211 of file listener.c.
{
    struct evconnlistener *listener;
    evutil_socket_t fd;
    int on = 1;
    int family = sa ? sa->sa_family : AF_UNSPEC;
    int socktype = SOCK_STREAM | EVUTIL_SOCK_NONBLOCK;
    if (backlog == 0)
        return NULL;
    if (flags & LEV_OPT_CLOSE_ON_EXEC)
        socktype |= EVUTIL_SOCK_CLOEXEC;
    fd = evutil_socket_(family, socktype, 0);
    if (fd == -1)
        return NULL;
    if (setsockopt(fd, SOL_SOCKET, SO_KEEPALIVE, (void*)&on, sizeof(on))<0)
        goto err;
    if (flags & LEV_OPT_REUSEABLE) {
        if (evutil_make_listen_socket_reuseable(fd) < 0)
            goto err;
    }
    if (flags & LEV_OPT_REUSEABLE_PORT) {
        if (evutil_make_listen_socket_reuseable_port(fd) < 0)
            goto err;
    }
    if (flags & LEV_OPT_DEFERRED_ACCEPT) {
        if (evutil_make_tcp_listen_socket_deferred(fd) < 0)
            goto err;
    }
    if (flags & LEV_OPT_BIND_IPV6ONLY) {
        if (evutil_make_listen_socket_ipv6only(fd) < 0)
            goto err;
    }
    if (sa) {
        if (bind(fd, sa, socklen)<0)
            goto err;
    }
    listener = evconnlistener_new(base, cb, ptr, flags, backlog, fd);
    if (!listener)
        goto err;
    return listener;
err:
    evutil_closesocket(fd);
    return NULL;
}
References evconnlistener::cb, evconnlistener_new(), evutil_closesocket(), evutil_make_listen_socket_ipv6only(), evutil_make_listen_socket_reuseable(), evutil_make_listen_socket_reuseable_port(), evutil_make_tcp_listen_socket_deferred(), EVUTIL_SOCK_CLOEXEC, EVUTIL_SOCK_NONBLOCK, evutil_socket_(), and evconnlistener::flags.
evconnlistener_set_cb()
void evconnlistener_set_cb (struct evconnlistener * lev, evconnlistener_cb cb, void * arg)
Definition at line 370 of file listener.c.
{
    int enable = 0;
    LOCK(lev);
    if (lev->enabled && !lev->cb)
        enable = 1;
    lev->cb = cb;
    lev->user_data = arg;
    if (enable)
        evconnlistener_enable(lev);
    UNLOCK(lev);
}
References evconnlistener::cb, evconnlistener::enabled, evconnlistener_enable(), LOCK, UNLOCK, and evconnlistener::user_data.
Referenced by evhttp_bind_listener().
evconnlistener_set_error_cb()
void evconnlistener_set_error_cb (struct evconnlistener * lev, evconnlistener_errorcb errorcb)
Definition at line 385 of file listener.c.
{
    LOCK(lev);
    lev->errorcb = errorcb;
    UNLOCK(lev);
}
References evconnlistener::errorcb, LOCK, and UNLOCK.
event_listener_destroy()
static void event_listener_destroy (struct evconnlistener * lev) static
Definition at line 281 of file listener.c.
{
    struct evconnlistener_event *lev_e =
        EVUTIL_UPCAST(lev, struct evconnlistener_event, base);
    event_del(&lev_e->listener);
    if (lev->flags & LEV_OPT_CLOSE_ON_FREE)
        evutil_closesocket(event_get_fd(&lev_e->listener));
    event_debug_unassign(&lev_e->listener);
}
References evconnlistener_event::base, event_debug_unassign(), event_del(), event_get_fd(), evutil_closesocket(), EVUTIL_UPCAST, evconnlistener::flags, and evconnlistener_event::listener.
event_listener_disable()
static int event_listener_disable (struct evconnlistener * lev) static
Definition at line 326 of file listener.c.
{
    struct evconnlistener_event *lev_e =
        EVUTIL_UPCAST(lev, struct evconnlistener_event, base);
    return event_del(&lev_e->listener);
}
References evconnlistener_event::base, event_del(), EVUTIL_UPCAST, and evconnlistener_event::listener.
event_listener_enable()
static int event_listener_enable (struct evconnlistener * lev) static
Definition at line 318 of file listener.c.
{
    struct evconnlistener_event *lev_e =
        EVUTIL_UPCAST(lev, struct evconnlistener_event, base);
    return event_add(&lev_e->listener, NULL);
}
References evconnlistener_event::base, event_add(), EVUTIL_UPCAST, and evconnlistener_event::listener.
event_listener_getbase()
static struct event_base * event_listener_getbase (struct evconnlistener * lev) static
Definition at line 362 of file listener.c.
{
    struct evconnlistener_event *lev_e =
        EVUTIL_UPCAST(lev, struct evconnlistener_event, base);
    return event_get_base(&lev_e->listener);
}
References evconnlistener_event::base, event_get_base(), EVUTIL_UPCAST, and evconnlistener_event::listener.
event_listener_getfd()
static evutil_socket_t event_listener_getfd (struct evconnlistener * lev) static
Definition at line 344 of file listener.c.
{
    struct evconnlistener_event *lev_e =
        EVUTIL_UPCAST(lev, struct evconnlistener_event, base);
    return event_get_fd(&lev_e->listener);
}
References evconnlistener_event::base, event_get_fd(), EVUTIL_UPCAST, and evconnlistener_event::listener.
listener_decref_and_unlock()
static int listener_decref_and_unlock (struct evconnlistener * listener) static
Definition at line 130 of file listener.c.
{
    int refcnt = --listener->refcnt;
    if (refcnt == 0) {
        listener->ops->destroy(listener);
        UNLOCK(listener);
        EVTHREAD_FREE_LOCK(listener->lock, EVTHREAD_LOCKTYPE_RECURSIVE);
        mm_free(listener);
        return 1;
    } else {
        UNLOCK(listener);
        return 0;
    }
}
References evconnlistener_ops::destroy, EVTHREAD_FREE_LOCK, evconnlistener::lock, mm_free, evconnlistener::ops, evconnlistener::refcnt, and UNLOCK.
Referenced by evconnlistener_free(), and listener_read_cb().
listener_read_cb()
static void listener_read_cb (evutil_socket_t fd, short what, void * p) static
Definition at line 394 of file listener.c.
{
    struct evconnlistener *lev = p;
    int err;
    evconnlistener_cb cb;
    evconnlistener_errorcb errorcb;
    void *user_data;
    LOCK(lev);
    while (1) {
        struct sockaddr_storage ss;
        ev_socklen_t socklen = sizeof(ss);
        evutil_socket_t new_fd = evutil_accept4_(fd, (struct sockaddr*)&ss, &socklen, lev->accept4_flags);
        if (new_fd < 0)
            break;
        if (socklen == 0) {
            /* This can happen with some older linux kernels in
             * response to nmap. */
            evutil_closesocket(new_fd);
            continue;
        }
        if (lev->cb == NULL) {
            evutil_closesocket(new_fd);
            UNLOCK(lev);
            return;
        }
        ++lev->refcnt;
        cb = lev->cb;
        user_data = lev->user_data;
        UNLOCK(lev);
        cb(lev, new_fd, (struct sockaddr*)&ss, (int)socklen,
            user_data);
        LOCK(lev);
        if (lev->refcnt == 1) {
            int freed = listener_decref_and_unlock(lev);
            EVUTIL_ASSERT(freed);
            return;
        }
        --lev->refcnt;
        if (!lev->enabled) {
            /* the callback could have disabled the listener */
            UNLOCK(lev);
            return;
        }
    }
    err = evutil_socket_geterror(fd);
    if (EVUTIL_ERR_ACCEPT_RETRIABLE(err)) {
        UNLOCK(lev);
        return;
    }
    if (lev->errorcb != NULL) {
        ++lev->refcnt;
        errorcb = lev->errorcb;
        user_data = lev->user_data;
        UNLOCK(lev);
        errorcb(lev, user_data);
        LOCK(lev);
        listener_decref_and_unlock(lev);
    } else {
        event_sock_warn(fd, "Error from accept() call");
        UNLOCK(lev);
    }
}
References evconnlistener::accept4_flags, evconnlistener::cb, evconnlistener::enabled, evconnlistener::errorcb, event_sock_warn(), evutil_accept4_(), EVUTIL_ASSERT, evutil_closesocket(), EVUTIL_ERR_ACCEPT_RETRIABLE, listener_decref_and_unlock(), LOCK, evconnlistener::refcnt, UNLOCK, and evconnlistener::user_data.
Referenced by evconnlistener_new().
Variable Documentation
evconnlistener_event_ops
const struct evconnlistener_ops evconnlistener_event_ops static
Initial value:
= {
    event_listener_enable,
    event_listener_disable,
    event_listener_destroy,
    NULL,
    event_listener_getfd,
    event_listener_getbase
}
Definition at line 145 of file listener.c.
Referenced by evconnlistener_new().