libdogecoin: src/libevent/log-internal.h File Reference
log-internal.h File Reference
#include "event2/util.h"
Macros
#define EV_CHECK_FMT(a, b)
#define EV_NORETURN
#define EVENT_ERR_ABORT_ ((int)0xdeaddead)
#define EVENT_DEBUG_LOGGING_ENABLED
#define event_debug_get_logging_mask_() (event_debug_logging_mask_)
#define event_debug(x)
Functions
EVENT2_EXPORT_SYMBOL void event_err (int eval, const char *fmt,...) EV_CHECK_FMT(2
EVENT2_EXPORT_SYMBOL void event_warn (const char *fmt,...) EV_CHECK_FMT(1
EVENT2_EXPORT_SYMBOL void EVENT2_EXPORT_SYMBOL void event_sock_err (int eval, evutil_socket_t sock, const char *fmt,...) EV_CHECK_FMT(3
EVENT2_EXPORT_SYMBOL void event_sock_warn (evutil_socket_t sock, const char *fmt,...) EV_CHECK_FMT(2
EVENT2_EXPORT_SYMBOL void EVENT2_EXPORT_SYMBOL void event_errx (int eval, const char *fmt,...) EV_CHECK_FMT(2
EVENT2_EXPORT_SYMBOL void event_warnx (const char *fmt,...) EV_CHECK_FMT(1
EVENT2_EXPORT_SYMBOL void EVENT2_EXPORT_SYMBOL void event_msgx (const char *fmt,...) EV_CHECK_FMT(1
EVENT2_EXPORT_SYMBOL void EVENT2_EXPORT_SYMBOL void EVENT2_EXPORT_SYMBOL void event_debugx_ (const char *fmt,...) EV_CHECK_FMT(1
EVENT2_EXPORT_SYMBOL void EVENT2_EXPORT_SYMBOL void EVENT2_EXPORT_SYMBOL void EVENT2_EXPORT_SYMBOL void event_logv_ (int severity, const char *errstr, const char *fmt, va_list ap) EV_CHECK_FMT(3
Variables
EVENT2_CORE_EXPORT_SYMBOL ev_uint32_t event_debug_logging_mask_
EVENT2_EXPORT_SYMBOL void EV_NORETURN
Macro Definition Documentation
EV_CHECK_FMT
#define EV_CHECK_FMT (a, b)
Definition at line 40 of file log-internal.h.
EV_NORETURN
EVENT2_EXPORT_SYMBOL void EVENT2_EXPORT_SYMBOL void EV_NORETURN
Definition at line 41 of file log-internal.h.
event_debug
#define event_debug (x)
Value:
    do {            \
    if (event_debug_get_logging_mask_()) {  \
        event_debugx_ x;        \
    }                   \
    } while (0)
Definition at line 79 of file log-internal.h.
event_debug_get_logging_mask_
#define event_debug_get_logging_mask_ () (event_debug_logging_mask_)
Definition at line 52 of file log-internal.h.
EVENT_DEBUG_LOGGING_ENABLED
#define EVENT_DEBUG_LOGGING_ENABLED
Definition at line 47 of file log-internal.h.
EVENT_ERR_ABORT_
#define EVENT_ERR_ABORT_ ((int)0xdeaddead)
Definition at line 44 of file log-internal.h.
Function Documentation
event_debugx_()
EVENT2_EXPORT_SYMBOL void EVENT2_EXPORT_SYMBOL void EVENT2_EXPORT_SYMBOL void event_debugx_ (const char * fmt, ...)
event_err()
EVENT2_EXPORT_SYMBOL void event_err (int eval, const char * fmt, ...)
Referenced by evrpc_construct_uri(), and name_from_addr().
event_errx()
EVENT2_EXPORT_SYMBOL void EVENT2_EXPORT_SYMBOL void event_errx (int eval, const char * fmt, ...)
Referenced by event_debug_assert_is_setup_(), event_debug_assert_not_added_(), event_debug_note_add_(), event_debug_note_del_(), event_enable_debug_mode(), event_init(), event_queue_insert_inserted(), event_queue_insert_timeout(), event_queue_remove_active(), event_queue_remove_active_later(), event_queue_remove_inserted(), event_queue_remove_timeout(), event_reinit(), evhttp_read_cb(), evthread_set_condition_callbacks(), evthread_set_lock_callbacks(), evutil_date_rfc1123(), and name_from_addr().
event_logv_()
EVENT2_EXPORT_SYMBOL void EVENT2_EXPORT_SYMBOL void EVENT2_EXPORT_SYMBOL void EVENT2_EXPORT_SYMBOL void event_logv_ (int severity, const char * errstr, const char * fmt, va_list ap)
Referenced by evdns_log_().
event_msgx()
EVENT2_EXPORT_SYMBOL void EVENT2_EXPORT_SYMBOL void event_msgx (const char * fmt, ...)
Referenced by event_base_new_with_config().
event_sock_err()
EVENT2_EXPORT_SYMBOL void EVENT2_EXPORT_SYMBOL void event_sock_err (int eval, evutil_socket_t sock, const char * fmt, ...)
Referenced by evsig_cb(), and evsig_init_().
event_sock_warn()
EVENT2_EXPORT_SYMBOL void event_sock_warn (evutil_socket_t sock, const char * fmt, ...)
Referenced by create_bind_socket_nonblock(), evhttp_bind_socket_with_handle(), evhttp_connection_connect_(), evhttp_get_request(), evsig_init_(), evutil_make_socket_nonblocking(), and listener_read_cb().
event_warn()
EVENT2_EXPORT_SYMBOL void event_warn (const char * fmt, ...)
Referenced by APPEND_CHAIN_MULTICAST(), evbuffer_file_segment_free(), evbuffer_file_segment_materialize(), evbuffer_pullup(), evbuffer_readln(), event_base_init_common_timeout(), event_base_new_with_config(), event_base_priority_init(), evhttp_add_header_internal(), evhttp_associate_new_request_with_connection(), evhttp_connection_base_bufferevent_new(), evhttp_connection_set_local_address(), evhttp_decode_uri(), evhttp_htmlescape(), evhttp_make_request(), evhttp_new_object(), evhttp_parse_query_impl(), evhttp_parse_response_line(), evhttp_request_get_host(), evhttp_request_new(), evhttp_response_code_(), evhttp_set_cb(), evhttp_uri_parse_authority(), evhttp_uri_parse_with_flags(), evhttp_uridecode(), evsig_restore_handler_(), evsig_set_handler_(), evtag_unmarshal_string(), evutil_check_ifaddrs(), evutil_fast_socket_closeonexec(), evutil_fast_socket_nonblocking(), evutil_make_internal_pipe_(), evutil_make_socket_closeonexec(), evutil_make_socket_nonblocking(), make_addrinfo(), parse_authority(), and reply_schedule_callback().
event_warnx()
EVENT2_EXPORT_SYMBOL void event_warnx (const char * fmt, ...)
Referenced by addrinfo_from_hostent(), be_filter_unlink(), be_openssl_unlink(), bufferevent_init_common_(), conn_closed(), event_active(), event_add(), event_assign(), event_base_free_(), event_base_init_common_timeout(), event_base_loop(), event_base_new_with_config(), event_base_start_iocp_(), event_del_(), event_finalize_impl_(), event_pending(), event_remove_timer(), evhttp_read_header(), evmap_io_add_(), evsig_add(), evsig_handler(), evthread_set_condition_callbacks(), evthread_set_lock_callbacks(), loop(), and make_addrinfo().
Variable Documentation
EV_NORETURN
EVENT2_EXPORT_SYMBOL void EVENT2_EXPORT_SYMBOL void EV_NORETURN
Definition at line 58 of file log-internal.h.
event_debug_logging_mask_
EVENT2_CORE_EXPORT_SYMBOL ev_uint32_t event_debug_logging_mask_ extern
Definition at line 72 of file log.c.
Referenced by event_enable_debug_logging().