libdogecoin: src/libevent/log.c File Reference
log.c File Reference
#include "event2/event-config.h"
#include "evconfig-private.h"
#include <sys/types.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdarg.h>
#include <string.h>
#include <errno.h>
#include "event2/event.h"
#include "event2/util.h"
#include "log-internal.h"
Macros
#define DEFAULT_MASK 0
Functions
static void event_log (int severity, const char *msg)
static void event_exit (int errcode) EV_NORETURN
void event_enable_debug_logging (ev_uint32_t which)
void event_set_fatal_callback (event_fatal_cb cb)
void event_err (int eval, const char *fmt,...)
void event_warn (const char *fmt,...)
void event_sock_err (int eval, evutil_socket_t sock, const char *fmt,...)
void event_sock_warn (evutil_socket_t sock, const char *fmt,...)
void event_errx (int eval, const char *fmt,...)
void event_warnx (const char *fmt,...)
void event_msgx (const char *fmt,...)
void event_debugx_ (const char *fmt,...)
void event_logv_ (int severity, const char *errstr, const char *fmt, va_list ap)
void event_set_log_callback (event_log_cb cb)
Variables
static event_fatal_cb fatal_fn = NULL
EVENT2_EXPORT_SYMBOL ev_uint32_t event_debug_logging_mask_ = DEFAULT_MASK
static event_log_cb log_fn = NULL
Macro Definition Documentation
DEFAULT_MASK
#define DEFAULT_MASK 0
Definition at line 69 of file log.c.
Function Documentation
event_debugx_()
void event_debugx_ (const char * fmt, ...)
Definition at line 177 of file log.c.
{
    va_list ap;
    va_start(ap, fmt);
    event_logv_(EVENT_LOG_DEBUG, NULL, fmt, ap);
    va_end(ap);
}
References event_logv_().
event_enable_debug_logging()
void event_enable_debug_logging (ev_uint32_t which)
Definition at line 76 of file log.c.
{
#ifdef EVENT_DEBUG_LOGGING_ENABLED
    event_debug_logging_mask_ = which;
#endif
}
References event_debug_logging_mask_.
event_err()
void event_err (int eval, const char * fmt, ...)
Definition at line 102 of file log.c.
{
    va_list ap;
    va_start(ap, fmt);
    event_logv_(EVENT_LOG_ERR, strerror(errno), fmt, ap);
    va_end(ap);
    event_exit(eval);
}
References event_exit(), and event_logv_().
event_errx()
void event_errx (int eval, const char * fmt, ...)
Definition at line 146 of file log.c.
{
    va_list ap;
    va_start(ap, fmt);
    event_logv_(EVENT_LOG_ERR, NULL, fmt, ap);
    va_end(ap);
    event_exit(eval);
}
References event_exit(), and event_logv_().
event_exit()
static void event_exit (int errcode) static
Definition at line 90 of file log.c.
{
    if (fatal_fn) {
        fatal_fn(errcode);
        exit(errcode); /* should never be reached */
    } else if (errcode == EVENT_ERR_ABORT_)
        abort();
    else
        exit(errcode);
}
References EVENT_ERR_ABORT_, and fatal_fn.
Referenced by event_err(), event_errx(), and event_sock_err().
event_log()
static void event_log (int severity, const char * msg) static
Definition at line 219 of file log.c.
{
    if (log_fn)
        log_fn(severity, msg);
    else {
        const char *severity_str;
        switch (severity) {
        case EVENT_LOG_DEBUG:
            severity_str = "debug";
            break;
        case EVENT_LOG_MSG:
            severity_str = "msg";
            break;
        case EVENT_LOG_WARN:
            severity_str = "warn";
            break;
        case EVENT_LOG_ERR:
            severity_str = "err";
            break;
        default:
            severity_str = "???";
            break;
        }
        (void)fprintf(stderr, "[%s] %s\n", severity_str, msg);
    }
}
References log_fn.
Referenced by event_logv_().
event_logv_()
void event_logv_ (int severity, const char * errstr, const char * fmt, va_list ap)
Definition at line 187 of file log.c.
{
    char buf[1024];
    size_t len;
    if (severity == EVENT_LOG_DEBUG && !event_debug_get_logging_mask_())
        return;
    if (fmt != NULL)
        evutil_vsnprintf(buf, sizeof(buf), fmt, ap);
    else
        buf[0] = '\0';
    if (errstr) {
        len = strlen(buf);
        if (len < sizeof(buf) - 3) {
            evutil_snprintf(buf + len, sizeof(buf) - len, ": %s", errstr);
        }
    }
    event_log(severity, buf);
}
References event_debug_get_logging_mask_, event_log(), evutil_snprintf(), and evutil_vsnprintf().
Referenced by event_debugx_(), event_err(), event_errx(), event_msgx(), event_sock_err(), event_sock_warn(), event_warn(), and event_warnx().
event_msgx()
void event_msgx (const char * fmt, ...)
Definition at line 167 of file log.c.
{
    va_list ap;
    va_start(ap, fmt);
    event_logv_(EVENT_LOG_MSG, NULL, fmt, ap);
    va_end(ap);
}
References event_logv_().
event_set_fatal_callback()
void event_set_fatal_callback (event_fatal_cb cb)
Definition at line 84 of file log.c.
{
    fatal_fn = cb;
}
References fatal_fn.
event_set_log_callback()
void event_set_log_callback (event_log_cb cb)
Definition at line 213 of file log.c.
{
    log_fn = cb;
}
References log_fn.
event_sock_err()
void event_sock_err (int eval, evutil_socket_t sock, const char * fmt, ...)
Definition at line 123 of file log.c.
{
    va_list ap;
    int err = evutil_socket_geterror(sock);
    va_start(ap, fmt);
    event_logv_(EVENT_LOG_ERR, evutil_socket_error_to_string(err), fmt, ap);
    va_end(ap);
    event_exit(eval);
}
References event_exit(), and event_logv_().
event_sock_warn()
void event_sock_warn (evutil_socket_t sock, const char * fmt, ...)
Definition at line 135 of file log.c.
{
    va_list ap;
    int err = evutil_socket_geterror(sock);
    va_start(ap, fmt);
    event_logv_(EVENT_LOG_WARN, evutil_socket_error_to_string(err), fmt, ap);
    va_end(ap);
}
References event_logv_().
event_warn()
void event_warn (const char * fmt, ...)
Definition at line 113 of file log.c.
{
    va_list ap;
    va_start(ap, fmt);
    event_logv_(EVENT_LOG_WARN, strerror(errno), fmt, ap);
    va_end(ap);
}
References event_logv_().
event_warnx()
void event_warnx (const char * fmt, ...)
Definition at line 157 of file log.c.
{
    va_list ap;
    va_start(ap, fmt);
    event_logv_(EVENT_LOG_WARN, NULL, fmt, ap);
    va_end(ap);
}
References event_logv_().
Variable Documentation
event_debug_logging_mask_
EVENT2_EXPORT_SYMBOL ev_uint32_t event_debug_logging_mask_ = DEFAULT_MASK
Definition at line 72 of file log.c.
Referenced by event_enable_debug_logging().
fatal_fn
event_fatal_cb fatal_fn = NULL static
Definition at line 63 of file log.c.
Referenced by event_exit(), and event_set_fatal_callback().
log_fn
event_log_cb log_fn = NULL static
Definition at line 210 of file log.c.
Referenced by event_log(), and event_set_log_callback().