libdogecoin: src/mem.c File Reference
mem.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <errno.h>
#include <dogecoin/mem.h>
Functions
void * dogecoin_malloc_internal (size_t size)
This function allocates a memory block.
void * dogecoin_calloc_internal (size_t count, size_t size)
This function allocates memory and initializes all bytes to zero.
void * dogecoin_realloc_internal (void *ptr, size_t size)
This function resizes the memory block pointed to by ptr which was previously allocated.
void dogecoin_free_internal (void *ptr)
This function frees previously allocated memory.
void dogecoin_mem_set_mapper_default ()
This function sets the current memory mapper to the default memory mapper.
void dogecoin_mem_set_mapper (const dogecoin_mem_mapper mapper)
This function sets the current memory mapper to the specified mapper.
void * dogecoin_malloc (size_t size)
This function calls dogecoin_malloc_internal() using the current memory mapper.
void * dogecoin_calloc (size_t count, size_t size)
This function calls dogecoin_calloc_internal() using the current memory mapper.
void * dogecoin_realloc (void *ptr, size_t size)
This function calls dogecoin_realloc_internal() using the current memory mapper.
void dogecoin_free (void *ptr)
This function calls dogecoin_free_internal() using the current memory mapper.
void * memcpy_safe (void *destination, const void *source, size_t count)
errno_t memset_safe (volatile void *v, rsize_t smax, int c, rsize_t n)
volatile void * dogecoin_mem_zero (volatile void *dst, size_t len)
uint32_t * dogecoin_uint32_vla (size_t size)
uint8_t * dogecoin_uint8_vla (size_t size)
char * dogecoin_char_vla (size_t size)
char * dogecoin_string_vla (size_t size)
unsigned char * dogecoin_uchar_vla (size_t size)
unsigned char ** dogecoin_ucharptr_vla (size_t size)
uint8_t ** dogecoin_uint8ptr_vla (size_t size)
Variables
static const dogecoin_mem_mapper default_mem_mapper = {dogecoin_malloc_internal, dogecoin_calloc_internal, dogecoin_realloc_internal, dogecoin_free_internal}
static dogecoin_mem_mapper current_mem_mapper = {dogecoin_malloc_internal, dogecoin_calloc_internal, dogecoin_realloc_internal, dogecoin_free_internal}
Function Documentation
dogecoin_calloc()
void * dogecoin_calloc (size_t count, size_t size)
This function calls dogecoin_calloc_internal() using the current memory mapper.
Parameters
count The number of elements to allocate.
size The size of each element.
Returns
A pointer to the allocated memory.
Definition at line 92 of file mem.c.
{
    return current_mem_mapper.dogecoin_calloc(count, size);
}
References count, current_mem_mapper, and dogecoin_mem_mapper::dogecoin_calloc.
Referenced by buffer_copy(), cstr_new_sz(), dogecoin_block_header_new(), dogecoin_get_peers_from_dns(), dogecoin_hdnode_deserialize(), dogecoin_hdnode_new(), dogecoin_node_group_new(), dogecoin_node_new(), dogecoin_privkey_decode_wif(), dogecoin_script_copy_without_op_codeseperator(), dogecoin_script_get_ops(), dogecoin_script_is_pubkey(), dogecoin_script_is_pubkeyhash(), dogecoin_script_is_scripthash(), dogecoin_script_op_new(), dogecoin_tx_add_address_out(), dogecoin_tx_in_new(), dogecoin_tx_new(), dogecoin_tx_out_new(), new_eckey(), new_eckey_from_privkey(), new_transaction(), utils_reverse_hex(), and vector_new().
dogecoin_calloc_internal()
void * dogecoin_calloc_internal (size_t count, size_t size)
This function allocates memory and initializes all bytes to zero.
Parameters
count The number of elements to allocate.
size The size of each element.
Returns
A pointer to the allocated memory.
Definition at line 158 of file mem.c.
{
    void* result;
    if ((result = calloc(count, size))) { /* assignment intentional */
        return (result);
    } else {
        printf("memory overflow: calloc failed in dogecoin_calloc.");
        printf("  Exiting Program.\n");
        exit(-1);
        return (0);
    }
}
References count.
dogecoin_char_vla()
char * dogecoin_char_vla (size_t size)
Definition at line 263 of file mem.c.
{
    char* outarray;
    outarray = (char*)malloc(size * sizeof(char));
    return outarray;
}
Referenced by dogecoin_private_key_wif_to_script_hash(), get_mnemonic(), hash_message(), koinu_to_coins_str(), main(), sign_raw_transaction(), and verifyPrivPubKeypair().
dogecoin_free()
void dogecoin_free (void * ptr)
This function calls dogecoin_free_internal() using the current memory mapper.
Parameters
ptr The pointer to the memory block to be freed.
Returns
Nothing.
Definition at line 121 of file mem.c.
{
    current_mem_mapper.dogecoin_free(ptr);
}
References current_mem_mapper, and dogecoin_mem_mapper::dogecoin_free.
Referenced by add_eckey(), add_transaction(), buffer_copy(), buffer_free(), cstr_free(), cstr_new_sz(), dogecoin_block_header_free(), dogecoin_btree_tdestroy(), dogecoin_generate_mnemonic(), dogecoin_hd_generate_key(), dogecoin_hdnode_deserialize(), dogecoin_hdnode_free(), dogecoin_key_free(), dogecoin_node_free(), dogecoin_node_group_free(), dogecoin_node_group_new(), dogecoin_p2p_deser_msg_getheaders(), dogecoin_privkey_decode_wif(), dogecoin_script_copy_without_op_codeseperator(), dogecoin_script_op_free(), dogecoin_script_op_free_cb(), dogecoin_tx_add_address_out(), dogecoin_tx_deserialize(), dogecoin_tx_free(), dogecoin_tx_in_free(), dogecoin_tx_out_free(), generateEnglishMnemonic(), get_mnemonic(), get_root_seed(), hash_message(), main(), produce_mnemonic_sentence(), remove_transaction(), save_raw_transaction(), sign_message(), sign_raw_transaction(), sign_transaction(), store_raw_transaction(), transaction_input_menu(), utils_reverse_hex(), vector_free(), vector_free_data(), vector_new(), and verify_message().
dogecoin_free_internal()
void dogecoin_free_internal (void * ptr)
This function frees previously allocated memory.
Parameters
ptr The pointer to the memory block to be freed.
Returns
Nothing.
Definition at line 204 of file mem.c.
{
    free(ptr);
}
dogecoin_malloc()
void * dogecoin_malloc (size_t size)
This function calls dogecoin_malloc_internal() using the current memory mapper.
Parameters
size The size of the memory block to be allocated.
Returns
A pointer to the allocated memory.
Definition at line 77 of file mem.c.
{
    return current_mem_mapper.dogecoin_malloc(size);
}
References current_mem_mapper, and dogecoin_mem_mapper::dogecoin_malloc.
Referenced by dogecoin_hd_generate_key(), dogecoin_p2p_deser_msg_getheaders(), dogecoin_p2pkh_to_script_hash(), dogecoin_tx_copy(), main(), save_raw_transaction(), sign_raw_transaction(), sign_transaction(), and store_raw_transaction().
dogecoin_malloc_internal()
void * dogecoin_malloc_internal (size_t size)
This function allocates a memory block.
Parameters
size The size of the memory block to be allocated.
Returns
A pointer to the allocated memory.
Definition at line 134 of file mem.c.
{
    void* result;
    if ((result = malloc(size))) { /* assignment intentional */
        return (result);
    } else {
        printf("memory overflow: malloc failed in dogecoin_malloc.");
        printf("  Exiting Program.\n");
        exit(-1);
        return (0);
    }
}
dogecoin_mem_set_mapper()
void dogecoin_mem_set_mapper (const dogecoin_mem_mapper mapper)
This function sets the current memory mapper to the specified mapper.
Parameters
mapper The mapper to be used.
Returns
Nothing.
Definition at line 63 of file mem.c.
{
    current_mem_mapper = mapper;
}
References current_mem_mapper.
dogecoin_mem_set_mapper_default()
void dogecoin_mem_set_mapper_default ()
This function sets the current memory mapper to the default memory mapper.
Returns
Nothing.
Definition at line 49 of file mem.c.
{
    current_mem_mapper = default_mem_mapper;
}
References current_mem_mapper, and default_mem_mapper.
dogecoin_mem_zero()
volatile void * dogecoin_mem_zero (volatile void * dst, size_t len)
"memset_safe() is a secure version of memset()."
The memset_safe() function is a secure version of memset() that fills the memory pointed to by dst with zeros
Parameters
dst The destination buffer to be zeroed.
len The length of the memory block to zero.
Definition at line 243 of file mem.c.
{
    memset_safe(dst, len, 0, len);
    return 0;
}
References memset_safe().
Referenced by broadcast_handshake_done(), broadcast_post_cmd(), coins_to_koinu_str(), cstr_free(), dogecoin_addr_to_p2paddr(), dogecoin_b58check(), dogecoin_base58_decode(), dogecoin_base58_decode_check(), dogecoin_base58_encode(), dogecoin_base58_encode_check(), dogecoin_block_header_free(), dogecoin_ecc_get_pubkey(), dogecoin_ecc_verify_pubkey(), dogecoin_get_peers_from_dns(), dogecoin_hash_clear(), dogecoin_hd_generate_key(), dogecoin_hdnode_deserialize(), dogecoin_hdnode_free(), dogecoin_hdnode_from_seed(), dogecoin_hdnode_private_ckd(), dogecoin_hdnode_public_ckd(), dogecoin_key_recover_pubkey(), dogecoin_key_sign_recover_pubkey(), dogecoin_node_group_add_peers_by_ip_or_seed(), dogecoin_node_send_version(), dogecoin_p2p_address_init(), dogecoin_p2p_message_new(), dogecoin_p2p_msg_inv_deser(), dogecoin_p2p_msg_version_deser(), dogecoin_privkey_cleanse(), dogecoin_privkey_decode_wif(), dogecoin_privkey_encode_wif(), dogecoin_privkey_init(), dogecoin_pubkey_cleanse(), dogecoin_pubkey_init(), dogecoin_script_hash_to_p2pkh(), dogecoin_tx_in_free(), dogecoin_tx_in_new(), dogecoin_tx_out_free(), dogecoin_tx_sign_input(), finalize_transaction(), generateDerivedHDPubkey(), generatePrivPubKeypair(), get_mnemonic(), hd_gen_master(), hmac_sha256(), hmac_sha512(), main(), rmd160(), sign_raw_transaction(), transaction_output_menu(), utils_clear_buffers(), utils_hex_to_bin(), utils_hex_to_uint8(), utils_uint256_sethex(), utils_uint8_to_hex(), and vector_free().
dogecoin_realloc()
void * dogecoin_realloc (void * ptr, size_t size)
This function calls dogecoin_realloc_internal() using the current memory mapper.
Parameters
ptr The pointer to the old memory block.
size The size of the new memory block to be reallocated.
Returns
A pointer to the reallocated memory.
Definition at line 107 of file mem.c.
{
    return current_mem_mapper.dogecoin_realloc(ptr, size);
}
References current_mem_mapper, and dogecoin_mem_mapper::dogecoin_realloc.
Referenced by cstr_alloc_min_sz(), and vector_grow().
dogecoin_realloc_internal()
void * dogecoin_realloc_internal (void * ptr, size_t size)
This function resizes the memory block pointed to by ptr which was previously allocated.
Parameters
ptr The pointer to the old memory block.
size The size of the new memory block to be reallocated.
Returns
A pointer to the reallocated memory.
Definition at line 182 of file mem.c.
{
    void* result;
    if ((result = realloc(ptr, size))) { /* assignment intentional */
        return (result);
    } else {
        printf("memory overflow: realloc failed in dogecoin_realloc.");
        printf("  Exiting Program.\n");
        exit(-1);
        return (0);
    }
}
dogecoin_string_vla()
LIBDOGECOIN_API char * dogecoin_string_vla (size_t size)
Definition at line 270 of file mem.c.
{
    char* outarray;
    outarray = (char*)malloc(size + 1 * sizeof(char));
    outarray[size] = '\0';
    return outarray;
}
Referenced by produce_mnemonic_sentence().
dogecoin_uchar_vla()
unsigned char * dogecoin_uchar_vla (size_t size)
Definition at line 278 of file mem.c.
{
    unsigned char* outarray;
    outarray = (unsigned char*)malloc(size * sizeof(unsigned char));
    return outarray;
}
Referenced by get_mnemonic(), sign_message(), verify_message(), and verifyP2pkhAddress().
dogecoin_ucharptr_vla()
unsigned char ** dogecoin_ucharptr_vla (size_t size)
Definition at line 285 of file mem.c.
{
    unsigned char** outarray;
    outarray = (unsigned char**)malloc(size * sizeof(unsigned char*));
    return outarray;
}
dogecoin_uint32_vla()
uint32_t * dogecoin_uint32_vla (size_t size)
Definition at line 249 of file mem.c.
{
    uint32_t* outarray;
    outarray = (uint32_t*)malloc(size * sizeof(uint32_t));
    return outarray;
}
Referenced by dogecoin_base58_decode().
dogecoin_uint8_vla()
uint8_t * dogecoin_uint8_vla (size_t size)
Definition at line 256 of file mem.c.
{
    uint8_t* outarray;
    outarray = (uint8_t*)malloc(size * sizeof(uint8_t));
    return outarray;
}
Referenced by dogecoin_base58_encode(), dogecoin_base58_encode_check(), dogecoin_script_hash_to_p2pkh(), main(), and sign_raw_transaction().
dogecoin_uint8ptr_vla()
uint8_t ** dogecoin_uint8ptr_vla (size_t size)
Definition at line 292 of file mem.c.
{
    uint8_t** outarray;
    outarray = (uint8_t**)malloc(size * sizeof(uint8_t*));
    return outarray;
}
memcpy_safe()
void * memcpy_safe (void * destination, const void * source, size_t count)
Definition at line 209 of file mem.c.
{
    char *pszDest = (char *)destination;
    const char *pszSource =( const char*)source;
    if((pszDest!= NULL) && (pszSource!= NULL)) {
        while(count) {
            *(pszDest++)= *(pszSource++);
            --count;
        }
    }
    return destination;
}
References count.
Referenced by aes256_cbc_encrypt(), buffer_copy(), cstr_append_buf(), cstr_new_buf(), deser_bytes(), deser_varlen_file(), dogecoin_addr_to_p2paddr(), dogecoin_base58_encode_check(), dogecoin_block_header_copy(), dogecoin_get_peers_from_dns(), dogecoin_hash_set(), dogecoin_hd_generate_key(), dogecoin_hdnode_copy(), dogecoin_hdnode_deserialize(), dogecoin_hdnode_from_seed(), dogecoin_hdnode_get_pub_hex(), dogecoin_hdnode_private_ckd(), dogecoin_hdnode_public_ckd(), dogecoin_hdnode_serialize(), dogecoin_key_recover_pubkey(), dogecoin_key_sign_recover_pubkey(), dogecoin_p2p_message_new(), dogecoin_p2p_msg_inv_init(), dogecoin_p2p_msg_version_deser(), dogecoin_p2p_msg_version_init(), dogecoin_p2paddr_to_addr(), dogecoin_p2pkh_addr_from_hash160(), dogecoin_p2sh_addr_from_hash160(), dogecoin_privkey_decode_wif(), dogecoin_privkey_encode_wif(), dogecoin_script_get_ops(), dogecoin_script_is_pubkey(), dogecoin_script_is_pubkeyhash(), dogecoin_script_is_scripthash(), dogecoin_tx_in_copy(), dogecoin_tx_sign_input(), gen_privatekey(), generateDerivedHDPubkey(), generateHDMasterPubKeypair(), generatePrivPubKeypair(), get_mnemonic(), get_root_seed(), hash_message(), hd_print_node(), hmac_sha256(), hmac_sha512(), koinu_to_coins_str(), main(), new_eckey(), new_eckey_from_privkey(), sha256_finalize(), sha512_finalize(), transaction_output_menu(), and utils_reverse_hex().
memset_safe()
errno_t memset_safe (volatile void * v, rsize_t smax, int c, rsize_t n)
Definition at line 221 of file mem.c.
{
  if (v == NULL) return EINVAL;
  if (smax > RSIZE_MAX) return EINVAL;
  if (n > smax) return EINVAL;
  volatile unsigned char *p = v;
  while (smax-- && n--) {
    *p++ = c;
  }
  return 0;
}
References RSIZE_MAX.
Referenced by dogecoin_mem_zero().
Variable Documentation
current_mem_mapper
dogecoin_mem_mapper current_mem_mapper = {dogecoin_malloc_internal, dogecoin_calloc_internal, dogecoin_realloc_internal, dogecoin_free_internal} static
Definition at line 40 of file mem.c.
Referenced by dogecoin_calloc(), dogecoin_free(), dogecoin_malloc(), dogecoin_mem_set_mapper(), dogecoin_mem_set_mapper_default(), and dogecoin_realloc().
default_mem_mapper
const dogecoin_mem_mapper default_mem_mapper = {dogecoin_malloc_internal, dogecoin_calloc_internal, dogecoin_realloc_internal, dogecoin_free_internal} static
Definition at line 39 of file mem.c.
Referenced by dogecoin_mem_set_mapper_default().