libdogecoin: src/libevent/minheap-internal.h File Reference
minheap-internal.h File Reference
#include "event2/event-config.h"
#include "evconfig-private.h"
#include "event2/event.h"
#include "event2/event_struct.h"
#include "event2/util.h"
#include "util-internal.h"
#include "mm-internal.h"
Data Structures
struct min_heap
Macros
#define min_heap_elem_greater(a, b) (evutil_timercmp(&(a)->ev_timeout, &(b)->ev_timeout, >))
Typedefs
typedef struct min_heap min_heap_t
Functions
static void min_heap_ctor_ (min_heap_t *s)
static void min_heap_dtor_ (min_heap_t *s)
static void min_heap_elem_init_ (struct event *e)
static int min_heap_elt_is_top_ (const struct event *e)
static int min_heap_empty_ (min_heap_t *s)
static unsigned min_heap_size_ (min_heap_t *s)
static struct event * min_heap_top_ (min_heap_t *s)
static int min_heap_reserve_ (min_heap_t *s, unsigned n)
static int min_heap_push_ (min_heap_t *s, struct event *e)
static struct event * min_heap_pop_ (min_heap_t *s)
static int min_heap_adjust_ (min_heap_t *s, struct event *e)
static int min_heap_erase_ (min_heap_t *s, struct event *e)
static void min_heap_shift_up_ (min_heap_t *s, unsigned hole_index, struct event *e)
static void min_heap_shift_up_unconditional_ (min_heap_t *s, unsigned hole_index, struct event *e)
static void min_heap_shift_down_ (min_heap_t *s, unsigned hole_index, struct event *e)
Macro Definition Documentation
min_heap_elem_greater
#define min_heap_elem_greater (a, b) (evutil_timercmp(&(a)->ev_timeout, &(b)->ev_timeout, >))
Definition at line 61 of file minheap-internal.h.
Typedef Documentation
min_heap_t
typedef struct min_heap min_heap_t
Function Documentation
min_heap_adjust_()
int min_heap_adjust_ (min_heap_t * s, struct event * e) inline static
Definition at line 117 of file minheap-internal.h.
{
    if (-1 == e->ev_timeout_pos.min_heap_idx) {
        return min_heap_push_(s, e);
    } else {
        unsigned parent = (e->ev_timeout_pos.min_heap_idx - 1) / 2;
        /* The position of e has changed; we shift it up or down
         * as needed.  We can't need to do both. */
        if (e->ev_timeout_pos.min_heap_idx > 0 && min_heap_elem_greater(s->p[parent], e))
            min_heap_shift_up_unconditional_(s, e->ev_timeout_pos.min_heap_idx, e);
        else
            min_heap_shift_down_(s, e->ev_timeout_pos.min_heap_idx, e);
        return 0;
    }
}
References min_heap_elem_greater, min_heap_push_(), min_heap_shift_down_(), min_heap_shift_up_unconditional_(), and min_heap::p.
min_heap_ctor_()
void min_heap_ctor_ (min_heap_t * s) inline static
Definition at line 64 of file minheap-internal.h.
{ s->p = 0; s->n = 0; s->a = 0; }
References min_heap::a, min_heap::n, and min_heap::p.
Referenced by event_base_new_with_config().
min_heap_dtor_()
void min_heap_dtor_ (min_heap_t * s) inline static
Definition at line 65 of file minheap-internal.h.
{ if (s->p) mm_free(s->p); }
References mm_free, and min_heap::p.
Referenced by event_base_free_().
min_heap_elem_init_()
void min_heap_elem_init_ (struct event * e) inline static
Definition at line 66 of file minheap-internal.h.
{ e->ev_timeout_pos.min_heap_idx = -1; }
Referenced by event_assign().
min_heap_elt_is_top_()
int min_heap_elt_is_top_ (const struct event * e) inline static
Definition at line 91 of file minheap-internal.h.
{
    return e->ev_timeout_pos.min_heap_idx == 0;
}
Referenced by event_add_nolock_().
min_heap_empty_()
int min_heap_empty_ (min_heap_t * s) inline static
Definition at line 67 of file minheap-internal.h.
{ return 0u == s->n; }
References min_heap::n.
Referenced by event_base_free_(), and timeout_process().
min_heap_erase_()
int min_heap_erase_ (min_heap_t * s, struct event * e) inline static
Definition at line 96 of file minheap-internal.h.
{
    if (-1 != e->ev_timeout_pos.min_heap_idx)
    {
        struct event *last = s->p[--s->n];
        unsigned parent = (e->ev_timeout_pos.min_heap_idx - 1) / 2;
        /* we replace e with the last element in the heap.  We might need to
           shift it upward if it is less than its parent, or downward if it is
           greater than one or both its children. Since the children are known
           to be less than the parent, it can't need to shift both up and
           down. */
        if (e->ev_timeout_pos.min_heap_idx > 0 && min_heap_elem_greater(s->p[parent], last))
            min_heap_shift_up_unconditional_(s, e->ev_timeout_pos.min_heap_idx, last);
        else
            min_heap_shift_down_(s, e->ev_timeout_pos.min_heap_idx, last);
        e->ev_timeout_pos.min_heap_idx = -1;
        return 0;
    }
    return -1;
}
References min_heap_elem_greater, min_heap_shift_down_(), min_heap_shift_up_unconditional_(), min_heap::n, and min_heap::p.
Referenced by event_queue_remove_timeout().
min_heap_pop_()
struct event * min_heap_pop_ (min_heap_t * s) inline static
Definition at line 79 of file minheap-internal.h.
{
    if (s->n)
    {
        struct event* e = *s->p;
        min_heap_shift_down_(s, 0u, s->p[--s->n]);
        e->ev_timeout_pos.min_heap_idx = -1;
        return e;
    }
    return 0;
}
References min_heap_shift_down_(), min_heap::n, and min_heap::p.
min_heap_push_()
int min_heap_push_ (min_heap_t * s, struct event * e) inline static
Definition at line 71 of file minheap-internal.h.
{
    if (s->n == UINT32_MAX || min_heap_reserve_(s, s->n + 1))
        return -1;
    min_heap_shift_up_(s, s->n++, e);
    return 0;
}
References min_heap_reserve_(), min_heap_shift_up_(), and min_heap::n.
Referenced by event_queue_insert_timeout(), and min_heap_adjust_().
min_heap_reserve_()
int min_heap_reserve_ (min_heap_t * s, unsigned n) inline static
Definition at line 133 of file minheap-internal.h.
{
    if (s->a < n)
    {
        struct event** p;
        unsigned a = s->a ? s->a * 2 : 8;
        if (a < n)
            a = n;
#if (SIZE_MAX == UINT32_MAX)
        if (a > SIZE_MAX / sizeof *p)
            return -1;
#endif
        if (!(p = (struct event**)mm_realloc(s->p, a * sizeof *p)))
            return -1;
        s->p = p;
        s->a = a;
    }
    return 0;
}
References min_heap::a, mm_realloc, and min_heap::p.
Referenced by event_add_nolock_(), and min_heap_push_().
min_heap_shift_down_()
void min_heap_shift_down_ (min_heap_t * s, unsigned hole_index, struct event * e) inline static
Definition at line 177 of file minheap-internal.h.
{
    unsigned min_child = 2 * (hole_index + 1);
    while (min_child <= s->n)
    {
    min_child -= min_child == s->n || min_heap_elem_greater(s->p[min_child], s->p[min_child - 1]);
    if (!(min_heap_elem_greater(e, s->p[min_child])))
        break;
    (s->p[hole_index] = s->p[min_child])->ev_timeout_pos.min_heap_idx = hole_index;
    hole_index = min_child;
    min_child = 2 * (hole_index + 1);
    }
    (s->p[hole_index] = e)->ev_timeout_pos.min_heap_idx = hole_index;
}
References min_heap_elem_greater, min_heap::n, and min_heap::p.
Referenced by min_heap_adjust_(), min_heap_erase_(), and min_heap_pop_().
min_heap_shift_up_()
void min_heap_shift_up_ (min_heap_t * s, unsigned hole_index, struct event * e) inline static
Definition at line 165 of file minheap-internal.h.
{
    unsigned parent = (hole_index - 1) / 2;
    while (hole_index && min_heap_elem_greater(s->p[parent], e))
    {
    (s->p[hole_index] = s->p[parent])->ev_timeout_pos.min_heap_idx = hole_index;
    hole_index = parent;
    parent = (hole_index - 1) / 2;
    }
    (s->p[hole_index] = e)->ev_timeout_pos.min_heap_idx = hole_index;
}
References min_heap_elem_greater, and min_heap::p.
Referenced by min_heap_push_().
min_heap_shift_up_unconditional_()
void min_heap_shift_up_unconditional_ (min_heap_t * s, unsigned hole_index, struct event * e) inline static
Definition at line 153 of file minheap-internal.h.
{
    unsigned parent = (hole_index - 1) / 2;
    do
    {
    (s->p[hole_index] = s->p[parent])->ev_timeout_pos.min_heap_idx = hole_index;
    hole_index = parent;
    parent = (hole_index - 1) / 2;
    } while (hole_index && min_heap_elem_greater(s->p[parent], e));
    (s->p[hole_index] = e)->ev_timeout_pos.min_heap_idx = hole_index;
}
References min_heap_elem_greater, and min_heap::p.
Referenced by min_heap_adjust_(), and min_heap_erase_().
min_heap_size_()
unsigned min_heap_size_ (min_heap_t * s) inline static
Definition at line 68 of file minheap-internal.h.
{ return s->n; }
References min_heap::n.
Referenced by event_add_nolock_().
min_heap_top_()
struct event * min_heap_top_ (min_heap_t * s) inline static
Definition at line 69 of file minheap-internal.h.
{ return s->n ? *s->p : 0; }
References min_heap::n, and min_heap::p.
Referenced by event_add_nolock_(), event_base_free_(), timeout_next(), and timeout_process().