libdogecoin: src/net.c File Reference
net.c File Reference
#include <arpa/inet.h>
#include <netinet/in.h>
#include <sys/socket.h>
#include <assert.h>
#include <inttypes.h>
#include <fcntl.h>
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <errno.h>
#include <pthread.h>
#include <time.h>
#include <event2/event.h>
#include <event2/util.h>
#include <event2/buffer.h>
#include <event2/bufferevent.h>
#include <dogecoin/buffer.h>
#include <dogecoin/chainparams.h>
#include <dogecoin/cstr.h>
#include <dogecoin/hash.h>
#include <dogecoin/net.h>
#include <dogecoin/protocol.h>
#include <dogecoin/serialize.h>
#include <dogecoin/utils.h>
#include <dogecoin/mem.h>
Macros
#define UNUSED(x) (void)(x)
Functions
int net_write_log_printf (const char *format,...)
int net_write_log_null (const char *format,...)
void read_cb (struct bufferevent *bev, void *ctx)
void write_cb (struct bufferevent *ev, void *ctx)
void node_periodical_timer (int fd, short int event, void *ctx)
void event_cb (struct bufferevent *ev, short type, void *ctx)
dogecoin_node * dogecoin_node_new ()
dogecoin_bool dogecoin_node_set_ipport (dogecoin_node *node, const char *ipport)
void dogecoin_node_release_events (dogecoin_node *node)
dogecoin_bool dogecoin_node_misbehave (dogecoin_node *node)
void dogecoin_node_disconnect (dogecoin_node *node)
void dogecoin_node_free (dogecoin_node *node)
void dogecoin_node_free_cb (void *obj)
dogecoin_node_group * dogecoin_node_group_new (const dogecoin_chainparams *chainparams)
void dogecoin_node_group_shutdown (dogecoin_node_group *group)
void dogecoin_node_group_free (dogecoin_node_group *group)
void dogecoin_node_group_event_loop (dogecoin_node_group *group)
void dogecoin_node_group_add_node (dogecoin_node_group *group, dogecoin_node *node)
int dogecoin_node_group_amount_of_connected_nodes (dogecoin_node_group *group, enum NODE_STATE state)
dogecoin_bool dogecoin_node_group_connect_next_nodes (dogecoin_node_group *group)
void dogecoin_node_connection_state_changed (dogecoin_node *node)
void dogecoin_node_send (dogecoin_node *node, cstring *data)
void dogecoin_node_send_version (dogecoin_node *node)
int dogecoin_node_parse_message (dogecoin_node *node, dogecoin_p2p_msg_hdr *hdr, struct const_buffer *buf)
size_t dogecoin_get_peers_from_dns (const char *seed, vector *ips_out, int port, int family)
dogecoin_bool dogecoin_node_group_add_peers_by_ip_or_seed (dogecoin_node_group *group, const char *ips)
static dogecoin_bool broadcast_timer_cb (dogecoin_node *node, uint64_t *now)
Disconnect node if it has been connected for more than the timeout.
void broadcast_handshake_done (struct dogecoin_node_ *node)
We send an INV message to the peer and set hints flag to 0 to indicate that we've sent an INV message.
dogecoin_bool broadcast_should_connect_more (dogecoin_node *node)
This function deterimines if we have connected to the maximum number of peers (true) or not (false).
void broadcast_post_cmd (struct dogecoin_node_ *node, dogecoin_p2p_msg_hdr *hdr, struct const_buffer *buf)
If we receive an INV message we check if the transaction is in the message. If true we indicate that we have the transaction. If we receive a GETDATA message we check if the transaction is in the message. If true we broadcast the transaction.
dogecoin_bool broadcast_tx (const dogecoin_chainparams *chain, const dogecoin_tx *tx, const char *ips, int maxpeers, int timeout, dogecoin_bool debug)
broadcast utilities
Variables
static const int DOGECOIN_PERIODICAL_NODE_TIMER_S = 3
static const int DOGECOIN_PING_INTERVAL_S = 120
static const int DOGECOIN_CONNECT_TIMEOUT_S = 10
Macro Definition Documentation
UNUSED
#define UNUSED (x) (void)(x)
Definition at line 77 of file net.c.
Function Documentation
broadcast_handshake_done()
void broadcast_handshake_done (struct dogecoin_node_ * node)
We send an INV message to the peer and set hints flag to 0 to indicate that we've sent an INV message.
Parameters
node The node that is broadcasting the handshake.
Definition at line 873 of file net.c.
{
    char ipaddr[256];
    struct sockaddr_in* ad = (struct sockaddr_in*)&node->addr;
    evutil_inet_ntop(node->addr.sa_family, &ad->sin_addr, ipaddr, sizeof(ipaddr));
    printf("Successfully connected to peer %d (%s)\n", node->nodeid, ipaddr);
    struct broadcast_ctx* ctx = (struct broadcast_ctx*)node->nodegroup->ctx;
    ctx->connected_to_peers++;
    if (ctx->inved_to_peers >= ctx->max_peers_to_inv) {
        return;
        }
    /* create a INV */
    cstring* inv_msg_cstr = cstr_new_sz(256);
    dogecoin_p2p_inv_msg inv_msg;
    dogecoin_mem_zero(&inv_msg, sizeof(inv_msg));
    uint256 hash;
    dogecoin_tx_hash(ctx->tx, hash);
    dogecoin_p2p_msg_inv_init(&inv_msg, DOGECOIN_INV_TYPE_TX, hash);
    /* serialize the inv count (1) */
    ser_varlen(inv_msg_cstr, 1);
    dogecoin_p2p_msg_inv_ser(&inv_msg, inv_msg_cstr);
    cstring* p2p_msg = dogecoin_p2p_message_new(node->nodegroup->chainparams->netmagic, DOGECOIN_MSG_INV, inv_msg_cstr->str, inv_msg_cstr->len);
    cstr_free(inv_msg_cstr, true);
    dogecoin_node_send(node, p2p_msg);
    cstr_free(p2p_msg, true);
    /* INV sent */
    node->hints |= (1 << 0);
    ctx->inved_to_peers++;
    }
References dogecoin_node_::addr, dogecoin_node_group_::chainparams, cstr_free(), cstr_new_sz(), dogecoin_node_group_::ctx, ctx, DOGECOIN_INV_TYPE_TX, dogecoin_mem_zero(), DOGECOIN_MSG_INV, dogecoin_node_send(), dogecoin_p2p_message_new(), dogecoin_p2p_msg_inv_init(), dogecoin_p2p_msg_inv_ser(), dogecoin_tx_hash(), evutil_inet_ntop(), dogecoin_node_::hints, cstring::len, dogecoin_chainparams_::netmagic, dogecoin_node_::nodegroup, dogecoin_node_::nodeid, ser_varlen(), cstring::str, and uint256.
Referenced by broadcast_tx().
broadcast_post_cmd()
void broadcast_post_cmd (struct dogecoin_node_ * node, dogecoin_p2p_msg_hdr * hdr, struct const_buffer * buf)
If we receive an INV message we check if the transaction is in the message. If true we indicate that we have the transaction. If we receive a GETDATA message we check if the transaction is in the message. If true we broadcast the transaction.
Parameters
node the node that received the message
hdr The header of the message.
buf the buffer containing the message
Definition at line 935 of file net.c.
{
    struct broadcast_ctx* ctx = (struct broadcast_ctx*)node->nodegroup->ctx;
    if (strcmp(hdr->command, DOGECOIN_MSG_INV) == 0) {
        /* hash the tx */
        /* TODO: cache the hash */
        uint256 hash;
        dogecoin_tx_hash(ctx->tx, hash);
        uint32_t vsize;
        if (!deser_varlen(&vsize, buf)) {
            dogecoin_node_misbehave(node);
            return;
            };
        for (unsigned int i = 0; i < vsize; i++) {
            dogecoin_p2p_inv_msg inv_msg;
            if (!dogecoin_p2p_msg_inv_deser(&inv_msg, buf)) {
                dogecoin_node_misbehave(node);
                return;
                }
            if (memcmp(hash, inv_msg.hash, sizeof(hash)) == 0) {
                /* tx found on peer */
                node->hints |= (1 << 2);
                printf("node %d has the tx\n", node->nodeid);
                ctx->found_on_non_inved_peers++;
                printf("tx successfully seen on node %d\n", node->nodeid);
                }
            }
        }
    else if (strcmp(hdr->command, DOGECOIN_MSG_GETDATA) == 0 && ((node->hints & (1 << 1)) != (1 << 1))) {
        ctx->getdata_from_peers++;
        // only allow a single object in GETDATA for the broadcaster
        uint32_t vsize;
        if (!deser_varlen(&vsize, buf) || vsize != 1) {
            dogecoin_node_misbehave(node);
            return;
            }
        dogecoin_p2p_inv_msg inv_msg;
        dogecoin_mem_zero(&inv_msg, sizeof(inv_msg));
        if (!dogecoin_p2p_msg_inv_deser(&inv_msg, buf) || inv_msg.type != DOGECOIN_INV_TYPE_TX) {
            dogecoin_node_misbehave(node);
            return;
            };
        /* send the tx */
        cstring* tx_ser = cstr_new_sz(1024);
        dogecoin_tx_serialize(tx_ser, ctx->tx);
        cstring* p2p_msg = dogecoin_p2p_message_new(node->nodegroup->chainparams->netmagic, DOGECOIN_MSG_TX, tx_ser->str, tx_ser->len);
        cstr_free(tx_ser, true);
        dogecoin_node_send(node, p2p_msg);
        cstr_free(p2p_msg, true);
        /* tx sent */
        node->hints |= (1 << 1);
        printf("tx successfully sent to node %d\n", node->nodeid);
        }
    }
References dogecoin_node_group_::chainparams, dogecoin_p2p_msg_hdr_::command, cstr_free(), cstr_new_sz(), dogecoin_node_group_::ctx, ctx, deser_varlen(), DOGECOIN_INV_TYPE_TX, dogecoin_mem_zero(), DOGECOIN_MSG_GETDATA, DOGECOIN_MSG_INV, DOGECOIN_MSG_TX, dogecoin_node_misbehave(), dogecoin_node_send(), dogecoin_p2p_message_new(), dogecoin_p2p_msg_inv_deser(), dogecoin_tx_hash(), dogecoin_tx_serialize(), dogecoin_p2p_inv_msg_::hash, dogecoin_node_::hints, cstring::len, dogecoin_chainparams_::netmagic, dogecoin_node_::nodegroup, dogecoin_node_::nodeid, cstring::str, dogecoin_p2p_inv_msg_::type, and uint256.
Referenced by broadcast_tx().
broadcast_should_connect_more()
dogecoin_bool broadcast_should_connect_more (dogecoin_node * node)
This function deterimines if we have connected to the maximum number of peers (true) or not (false).
Parameters
node the node that we are broadcasting to.
Returns
dogecoin_bool (uint8_t)
Definition at line 917 of file net.c.
{
    struct broadcast_ctx* ctx = (struct broadcast_ctx*)node->nodegroup->ctx;
    node->nodegroup->log_write_cb("check if more nodes are required (connected to already: %d)\n", ctx->connected_to_peers);
    if (ctx->connected_to_peers >= ctx->max_peers_to_connect) {
        return false;
        }
    return true;
    }
References dogecoin_node_group_::ctx, ctx, dogecoin_node_group_::log_write_cb, and dogecoin_node_::nodegroup.
Referenced by broadcast_tx().
broadcast_timer_cb()
static dogecoin_bool broadcast_timer_cb (dogecoin_node * node, uint64_t * now) static
Disconnect node if it has been connected for more than the timeout.
Parameters
node the node that is being checked
now the current time in seconds since the epoch
Returns
static dogecoin_bool (uint8_t)
Definition at line 846 of file net.c.
{
    struct broadcast_ctx* ctx = (struct broadcast_ctx*)node->nodegroup->ctx;
    if (node->time_started_con > 0) {
        node->nodegroup->log_write_cb("timer node %d, delta: %" PRIu64 " secs (timeout is: %d)\n", node->nodeid, (*now - ctx->start_time), ctx->timeout);
        }
    if ((*now - ctx->start_time) > ctx->timeout)
        dogecoin_node_disconnect(node);
    if ((node->hints & (1 << 1)) == (1 << 1)) {
        dogecoin_node_disconnect(node);
        }
    if ((node->hints & (1 << 2)) == (1 << 2)) {
        dogecoin_node_disconnect(node);
        }
    /* return true = run internal timer logic (ping, disconnect-timeout, etc.) */
    return true;
    }
References dogecoin_node_group_::ctx, ctx, dogecoin_node_disconnect(), dogecoin_node_::hints, dogecoin_node_group_::log_write_cb, dogecoin_node_::nodegroup, dogecoin_node_::nodeid, and dogecoin_node_::time_started_con.
Referenced by broadcast_tx().
broadcast_tx()
dogecoin_bool broadcast_tx (const dogecoin_chainparams * chain, const dogecoin_tx * tx, const char * ips, int maxpeers, int timeout, dogecoin_bool debug)
broadcast utilities
Connect to a set of nodes and then wait for the transaction to be broadcasted.
Parameters
chain the chain parameters
tx The transaction to broadcast
ips a comma separated list of IPs or DNS seeds to connect to.
maxpeers The maximum number of peers to connect to.
timeout How long to wait for the transaction to be broadcasted.
debug if set to 1, will print out debug messages
Returns
dogecoin_bool (uint8_t)
Definition at line 1006 of file net.c.
{
    struct broadcast_ctx ctx;
    ctx.tx = tx;
    ctx.debuglevel = debug;
    ctx.timeout = timeout;
    ctx.max_peers_to_inv = 2;
    ctx.found_on_non_inved_peers = 0;
    ctx.getdata_from_peers = 0;
    ctx.inved_to_peers = 0;
    ctx.connected_to_peers = 0;
    ctx.max_peers_to_connect = maxpeers;
    /* create a node group */
    dogecoin_node_group* group = dogecoin_node_group_new(chain);
    group->desired_amount_connected_nodes = ctx.max_peers_to_connect;
    group->ctx = &ctx;
    /* set the timeout callback */
    group->periodic_timer_cb = broadcast_timer_cb;
    /* set a individual log print function */
    if (debug) {
        group->log_write_cb = net_write_log_printf;
        }
    group->postcmd_cb = broadcast_post_cmd;
    group->handshake_done_cb = broadcast_handshake_done;
    group->should_connect_to_more_nodes_cb = broadcast_should_connect_more;
    dogecoin_node_group_add_peers_by_ip_or_seed(group, ips);
    uint256 txhash;
    dogecoin_tx_hash(tx, txhash);
    char hexout[sizeof(txhash) * 2 + 1];
    utils_bin_to_hex(txhash, sizeof(txhash), hexout);
    hexout[sizeof(txhash) * 2] = 0;
    utils_reverse_hex(hexout, strlen(hexout));
    printf("Start broadcasting transaction: %s with timeout %d seconds\n", hexout, timeout);
    /* connect to the next node */
    ctx.start_time = time(NULL);
    printf("Trying to connect to nodes...\n");
    dogecoin_node_group_connect_next_nodes(group);
    /* start the event loop */
    dogecoin_node_group_event_loop(group);
    /* cleanup (free) nodes structures from the heap */
    dogecoin_node_group_free(group);
    printf("\n\nResult:\n=============\n");
    printf("Max nodes to connect to: %d\n", ctx.max_peers_to_connect);
    printf("Successfully connected to nodes: %d\n", ctx.connected_to_peers);
    printf("Informed nodes: %d\n", ctx.inved_to_peers);
    printf("Requested from nodes: %d\n", ctx.getdata_from_peers);
    printf("Seen on other nodes: %d\n", ctx.found_on_non_inved_peers);
    if (ctx.getdata_from_peers == 0)
        {
        printf("\nError: The transaction was not requested by the informed nodes. This usually happens when the transaction has already been broadcasted\n");
        }
    else if (ctx.found_on_non_inved_peers == 0)
        {
        printf("\nError: The transaction was not relayed back. Your transaction is very likely invalid (or was already broadcasted and picked up by an invalid node)\n");
        }
    return 1;
    }
References broadcast_handshake_done(), broadcast_post_cmd(), broadcast_should_connect_more(), broadcast_timer_cb(), dogecoin_node_group_::ctx, ctx, debug, dogecoin_node_group_::desired_amount_connected_nodes, dogecoin_node_group_add_peers_by_ip_or_seed(), dogecoin_node_group_connect_next_nodes(), dogecoin_node_group_event_loop(), dogecoin_node_group_free(), dogecoin_node_group_new(), dogecoin_tx_hash(), dogecoin_node_group_::handshake_done_cb, dogecoin_node_group_::log_write_cb, net_write_log_printf(), dogecoin_node_group_::periodic_timer_cb, dogecoin_node_group_::postcmd_cb, dogecoin_node_group_::should_connect_to_more_nodes_cb, broadcast_ctx::timeout, broadcast_ctx::tx, uint256, utils_bin_to_hex(), and utils_reverse_hex().
Referenced by main().
dogecoin_get_peers_from_dns()
size_t dogecoin_get_peers_from_dns (const char * seed, vector * ips_out, int port, int family)
Given a seed DNS name, return a vector of IP addresses and ports. (utility function to get peers (ips/port as char*) from a seed)
Parameters
seed The seed DNS name.
ips_out A vector of strings.
port The port to connect to.
family The address family of the socket. AF_INET or AF_INET6.
Returns
size_t
Definition at line 743 of file net.c.
{
    if (!seed || !ips_out || (family != AF_INET && family != AF_INET6) || port > 99999) {
        return 0;
    }
    char def_port[12] = {0};
    sprintf(def_port, "%d", port);
    struct evutil_addrinfo hints, *aiTrav = NULL, *aiRes = NULL;
    dogecoin_mem_zero(&hints, sizeof(hints));
    hints.ai_family = AF_INET;
    hints.ai_socktype = SOCK_STREAM;
    hints.ai_protocol = IPPROTO_TCP;
    int err = evutil_getaddrinfo(seed, NULL, &hints, &aiRes);
    if (err)
        return 0;
    aiTrav = aiRes;
    while (aiTrav != NULL) {
        int maxlen = 256;
        char* ipaddr = dogecoin_calloc(1, maxlen);
        if (aiTrav->ai_family == AF_INET) {
            assert(aiTrav->ai_addrlen >= sizeof(struct sockaddr_in));
            evutil_inet_ntop(aiTrav->ai_family, &((struct sockaddr_in*)(aiTrav->ai_addr))->sin_addr, ipaddr, maxlen);
        }
        if (aiTrav->ai_family == AF_INET6) {
            assert(aiTrav->ai_addrlen >= sizeof(struct sockaddr_in6));
            evutil_inet_ntop(aiTrav->ai_family, &((struct sockaddr_in6*)(aiTrav->ai_addr))->sin6_addr, ipaddr, maxlen);
        }
        memcpy_safe(ipaddr + strlen(ipaddr), ":", 1);
        memcpy_safe(ipaddr + strlen(ipaddr), def_port, strlen(def_port));
        vector_add(ips_out, ipaddr);
        aiTrav = aiTrav->ai_next;
    }
    evutil_freeaddrinfo(aiRes);
    return ips_out->len;
}
References AF_INET6, dogecoin_calloc(), dogecoin_mem_zero(), evutil_freeaddrinfo(), evutil_getaddrinfo(), evutil_inet_ntop(), vector::len, memcpy_safe(), and vector_add().
Referenced by dogecoin_node_group_add_peers_by_ip_or_seed().
dogecoin_node_connection_state_changed()
void dogecoin_node_connection_state_changed (dogecoin_node * node)
If the node is in an error state or misbehaving state we disconnect it. If the node is in a connecting state we do nothing. Otherwise we send a version message to it.
Parameters
node The node that has changed state.
Definition at line 598 of file net.c.
{
    if (node->nodegroup->node_connection_state_changed_cb)
        node->nodegroup->node_connection_state_changed_cb(node);
    if ((node->state & NODE_ERRORED) == NODE_ERRORED) {
        dogecoin_node_release_events(node);
        /* connect to more nodes are required */
        dogecoin_bool should_connect_to_more_nodes = true;
        if (node->nodegroup->should_connect_to_more_nodes_cb)
            should_connect_to_more_nodes = node->nodegroup->should_connect_to_more_nodes_cb(node);
        if (should_connect_to_more_nodes && (dogecoin_node_group_amount_of_connected_nodes(node->nodegroup, NODE_CONNECTED) + dogecoin_node_group_amount_of_connected_nodes(node->nodegroup, NODE_CONNECTING) < node->nodegroup->desired_amount_connected_nodes))
            dogecoin_node_group_connect_next_nodes(node->nodegroup);
    }
    if ((node->state & NODE_MISSBEHAVED) == NODE_MISSBEHAVED) {
        if ((node->state & NODE_CONNECTED) == NODE_CONNECTED || (node->state & NODE_CONNECTING) == NODE_CONNECTING) {
            dogecoin_node_disconnect(node);
        }
    } else
        dogecoin_node_send_version(node);
}
References dogecoin_node_group_::desired_amount_connected_nodes, dogecoin_node_disconnect(), dogecoin_node_group_amount_of_connected_nodes(), dogecoin_node_group_connect_next_nodes(), dogecoin_node_release_events(), dogecoin_node_send_version(), NODE_CONNECTED, NODE_CONNECTING, dogecoin_node_group_::node_connection_state_changed_cb, NODE_ERRORED, NODE_MISSBEHAVED, dogecoin_node_::nodegroup, dogecoin_node_group_::should_connect_to_more_nodes_cb, and dogecoin_node_::state.
Referenced by dogecoin_node_misbehave(), event_cb(), and node_periodical_timer().
dogecoin_node_disconnect()
void dogecoin_node_disconnect (dogecoin_node * node)
If the node is connected, disconnect it
Parameters
node The node that is being disconnected.
Definition at line 363 of file net.c.
{
    if ((node->state & NODE_CONNECTED) == NODE_CONNECTED || (node->state & NODE_CONNECTING) == NODE_CONNECTING) {
        node->nodegroup->log_write_cb("Disconnect node %d\n", node->nodeid);
    }
    dogecoin_node_release_events(node);
    node->state &= ~NODE_CONNECTING;
    node->state &= ~NODE_CONNECTED;
    node->state |= NODE_DISCONNECTED;
    node->time_started_con = 0;
}
References dogecoin_node_release_events(), dogecoin_node_group_::log_write_cb, NODE_CONNECTED, NODE_CONNECTING, NODE_DISCONNECTED, dogecoin_node_::nodegroup, dogecoin_node_::nodeid, dogecoin_node_::state, and dogecoin_node_::time_started_con.
Referenced by broadcast_timer_cb(), dogecoin_node_connection_state_changed(), dogecoin_node_free(), dogecoin_node_group_shutdown(), and dogecoin_node_parse_message().
dogecoin_node_free()
void dogecoin_node_free (dogecoin_node * node)
It frees the memory allocated to the node
Parameters
node The node to disconnect from.
Definition at line 382 of file net.c.
{
    dogecoin_node_disconnect(node);
    cstr_free(node->recvBuffer, true);
    dogecoin_free(node);
}
References cstr_free(), dogecoin_free(), dogecoin_node_disconnect(), and dogecoin_node_::recvBuffer.
Referenced by dogecoin_node_free_cb().
dogecoin_node_free_cb()
void dogecoin_node_free_cb (void * obj)
It takes a pointer to a dogecoin_node object and frees it
Parameters
obj The object to be freed.
Definition at line 394 of file net.c.
{
    dogecoin_node* node = (dogecoin_node*)obj;
    dogecoin_node_free(node);
}
References dogecoin_node_free().
Referenced by dogecoin_node_group_new().
dogecoin_node_group_add_node()
void dogecoin_node_group_add_node (dogecoin_node_group * group, dogecoin_node * node)
Adds a node to a node group
Parameters
group The node group to add the node to.
node The node to add to the group.
Definition at line 513 of file net.c.
{
    vector_add(group->nodes, node);
    node->nodegroup = group;
    node->nodeid = group->nodes->len;
}
References vector::len, dogecoin_node_::nodegroup, dogecoin_node_::nodeid, dogecoin_node_group_::nodes, and vector_add().
Referenced by dogecoin_node_group_add_peers_by_ip_or_seed().
dogecoin_node_group_add_peers_by_ip_or_seed()
dogecoin_bool dogecoin_node_group_add_peers_by_ip_or_seed (dogecoin_node_group * group, const char * ips)
It takes a comma seperated list of IPs and adds them to the group
Parameters
group the node group to add the nodes to
ips comma seperated list of ip addresses
Returns
dogecoin_bool (uint8_t)
Definition at line 793 of file net.c.
{
    if (ips == NULL) {
        /* === DNS QUERY === */
        vector* ips_dns = vector_new(10, free);
        const dogecoin_dns_seed seed = group->chainparams->dnsseeds[0];
        if (strlen(seed.domain) == 0) {
            return false;
        }
        /* todo: make sure we have enough peers, eventually */
        dogecoin_get_peers_from_dns(seed.domain, ips_dns, group->chainparams->default_port, AF_INET);
        unsigned int i;
        for (i = 0; i < ips_dns->len; i++) {
            char* ip = (char*)vector_idx(ips_dns, i);
            /* create a node */
            dogecoin_node* node = dogecoin_node_new();
            if (dogecoin_node_set_ipport(node, ip) > 0) {
                /* add the node to the group */
                dogecoin_node_group_add_node(group, node);
            }
        }
        vector_free(ips_dns, true);
    } else {
        // add comma seperated ips (nodes)
        char working_str[64];
        dogecoin_mem_zero(working_str, sizeof(working_str));
        size_t offset = 0;
        unsigned int i;
        for (i = 0; i <= strlen(ips); i++) {
            if (i == strlen(ips) || ips[i] == ',') {
                dogecoin_node* node = dogecoin_node_new();
                if (dogecoin_node_set_ipport(node, working_str) > 0) {
                    dogecoin_node_group_add_node(group, node);
                }
                offset = 0;
                dogecoin_mem_zero(working_str, sizeof(working_str));
            } else if (ips[i] != ' ' && offset < sizeof(working_str)) {
                working_str[offset] = ips[i];
                offset++;
            }
        }
    }
    return true;
}
References dogecoin_node_group_::chainparams, dogecoin_chainparams_::default_port, dogecoin_chainparams_::dnsseeds, dogecoin_get_peers_from_dns(), dogecoin_mem_zero(), dogecoin_node_group_add_node(), dogecoin_node_new(), dogecoin_node_set_ipport(), vector::len, vector_free(), vector_idx, and vector_new().
Referenced by broadcast_tx().
dogecoin_node_group_amount_of_connected_nodes()
int dogecoin_node_group_amount_of_connected_nodes (dogecoin_node_group * group, enum NODE_STATE state)
The function is used to count the number of nodes in the group that are in the given state
Parameters
group the group to check
state The state of the node.
Returns
The number of nodes in the group that are in the given state.
Definition at line 528 of file net.c.
{
    int count = 0;
    for (size_t i = 0; i < group->nodes->len; i++) {
        dogecoin_node* node = vector_idx(group->nodes, i);
        if ((node->state & state) == state)
            count++;
    }
    return count;
}
References count, vector::len, dogecoin_node_group_::nodes, dogecoin_node_::state, and vector_idx.
Referenced by dogecoin_node_connection_state_changed(), dogecoin_node_group_connect_next_nodes(), and event_cb().
dogecoin_node_group_connect_next_nodes()
dogecoin_bool dogecoin_node_group_connect_next_nodes (dogecoin_node_group * group)
Try to connect to a node that is not connected, not in connecting state, not errored, and has not been connected for more than DOGECOIN_PERIODICAL_NODE_TIMER_S seconds.
Parameters
group the node group we're connecting to
Returns
A boolean value.
Definition at line 547 of file net.c.
{
    dogecoin_bool connected_at_least_to_one_node = false;
    int connect_amount = group->desired_amount_connected_nodes - dogecoin_node_group_amount_of_connected_nodes(group, NODE_CONNECTED);
    if (connect_amount <= 0)
        return true;
    connect_amount = connect_amount*3;
    for (size_t i = 0; i < group->nodes->len; i++) {
        dogecoin_node* node = vector_idx(group->nodes, i);
        if (
            !((node->state & NODE_CONNECTED) == NODE_CONNECTED) &&
            !((node->state & NODE_CONNECTING) == NODE_CONNECTING) &&
            !((node->state & NODE_DISCONNECTED) == NODE_DISCONNECTED) &&
            !((node->state & NODE_ERRORED) == NODE_ERRORED)) {
            /* setup buffer event */
            node->event_bev = bufferevent_socket_new(group->event_base, -1, BEV_OPT_CLOSE_ON_FREE);
            bufferevent_setcb(node->event_bev, read_cb, write_cb, event_cb, node);
            bufferevent_enable(node->event_bev, EV_READ | EV_WRITE);
            if (bufferevent_socket_connect(node->event_bev, (struct sockaddr*)&node->addr, sizeof(node->addr)) < 0) {
                if (node->event_bev) {
                    bufferevent_free(node->event_bev);
                    node->event_bev = NULL;
                }
                return false;
            }
            /* setup periodic timer */
            node->time_started_con = time(NULL);
            struct timeval tv;
            tv.tv_sec = DOGECOIN_PERIODICAL_NODE_TIMER_S;
            tv.tv_usec = 0;
            node->timer_event = event_new(group->event_base, 0, EV_TIMEOUT | EV_PERSIST, node_periodical_timer, node);
            event_add(node->timer_event, &tv);
            node->state |= NODE_CONNECTING;
            connected_at_least_to_one_node = true;
            node->nodegroup->log_write_cb("Trying to connect to %d...\n", node->nodeid);
            connect_amount--;
            if (connect_amount <= 0)
                return true;
        }
    }
    return connected_at_least_to_one_node;
}
References dogecoin_node_::addr, bufferevent_enable(), bufferevent_free(), bufferevent_setcb(), bufferevent_socket_connect(), bufferevent_socket_new(), dogecoin_node_group_::desired_amount_connected_nodes, dogecoin_node_group_amount_of_connected_nodes(), DOGECOIN_PERIODICAL_NODE_TIMER_S, event_add(), dogecoin_node_group_::event_base, dogecoin_node_::event_bev, event_cb(), event_new(), vector::len, dogecoin_node_group_::log_write_cb, NODE_CONNECTED, NODE_CONNECTING, NODE_DISCONNECTED, NODE_ERRORED, node_periodical_timer(), dogecoin_node_::nodegroup, dogecoin_node_::nodeid, dogecoin_node_group_::nodes, read_cb(), dogecoin_node_::state, dogecoin_node_::time_started_con, dogecoin_node_::timer_event, vector_idx, and write_cb().
Referenced by broadcast_tx(), and dogecoin_node_connection_state_changed().
dogecoin_node_group_event_loop()
void dogecoin_node_group_event_loop (dogecoin_node_group * group)
The event loop is the core of the event-driven networking library
Parameters
group The dogecoin_node_group object.
Definition at line 502 of file net.c.
{
    event_base_dispatch(group->event_base);
}
References dogecoin_node_group_::event_base, and event_base_dispatch().
Referenced by broadcast_tx().
dogecoin_node_group_free()
void dogecoin_node_group_free (dogecoin_node_group * group)
It takes a pointer to a dogecoin_node_group, and frees the memory allocated to it
Parameters
group The group to free.
Definition at line 482 of file net.c.
{
    if (!group)
        return;
    if (group->event_base) {
        event_base_free(group->event_base);
    }
    if (group->nodes) {
        vector_free(group->nodes, true);
    }
    dogecoin_free(group);
}
References dogecoin_free(), dogecoin_node_group_::event_base, event_base_free(), dogecoin_node_group_::nodes, and vector_free().
Referenced by broadcast_tx().
dogecoin_node_group_new()
dogecoin_node_group * dogecoin_node_group_new (const dogecoin_chainparams * chainparams)
Creates a new dogecoin_node_group object
Parameters
chainparams The chainparams to use. If NULL, use the mainnet.
Returns
A dogecoin_node_group object.
Definition at line 407 of file net.c.
{
    dogecoin_node_group* node_group;
    node_group = dogecoin_calloc(1, sizeof(*node_group));
#ifdef _WIN32
    WSADATA wsaData;
    WORD wVersionRequested;
    int err;
    /* Use the MAKEWORD(lowbyte, highbyte) macro declared in Windef.h */
    wVersionRequested = MAKEWORD(2, 2);
    err = WSAStartup(wVersionRequested, &wsaData);
    printf("\ninitializing winsock...");
    if (err != 0) {
        /* Tell the user that we could not find a usable */
        /* Winsock DLL.                                  */
        printf("WSAStartup failed. error code : %d", err);
    }
    printf("initialized.\n");
    /* Confirm that the WinSock DLL supports 2.2.*/
    /* Note that if the DLL supports versions greater    */
    /* than 2.2 in addition to 2.2, it will still return */
    /* 2.2 in wVersion since that is the version we      */
    /* requested.                                        */
    if (LOBYTE(wsaData.wVersion) != 2 || HIBYTE(wsaData.wVersion) != 2) {
        /* Tell the user that we could not find a usable */
        /* WinSock DLL.                                  */
        printf("Could not find a usable version of Winsock.dll\n");
        WSACleanup();
    }
    else
        printf("winsock 2.2 dll was found okay\n");
#endif
    struct event_base *base = event_base_new();
    node_group->event_base = base;
    if (!base) {
        dogecoin_free(node_group);
        printf("node_group->event_base not created\n");
        return NULL;
    };
    node_group->nodes = vector_new(1, dogecoin_node_free_cb);
    node_group->chainparams = (chainparams ? chainparams : &dogecoin_chainparams_main);
    node_group->parse_cmd_cb = NULL;
    strcpy(node_group->clientstr, "libdogecoin 0.1");
    /* nullify callbacks */
    node_group->postcmd_cb = NULL;
    node_group->node_connection_state_changed_cb = NULL;
    node_group->should_connect_to_more_nodes_cb = NULL;
    node_group->handshake_done_cb = NULL;
    node_group->log_write_cb = net_write_log_null;
    node_group->desired_amount_connected_nodes = 25;
    return node_group;
}
References dogecoin_node_group_::chainparams, dogecoin_node_group_::clientstr, dogecoin_node_group_::desired_amount_connected_nodes, dogecoin_calloc(), dogecoin_chainparams_main, dogecoin_free(), dogecoin_node_free_cb(), dogecoin_node_group_::event_base, event_base_new(), dogecoin_node_group_::handshake_done_cb, dogecoin_node_group_::log_write_cb, net_write_log_null(), dogecoin_node_group_::node_connection_state_changed_cb, dogecoin_node_group_::nodes, dogecoin_node_group_::parse_cmd_cb, dogecoin_node_group_::postcmd_cb, dogecoin_node_group_::should_connect_to_more_nodes_cb, and vector_new().
Referenced by broadcast_tx().
dogecoin_node_group_shutdown()
void dogecoin_node_group_shutdown (dogecoin_node_group * group)
Shut down all the nodes in the group.
Parameters
group The group to shutdown.
Definition at line 470 of file net.c.
{
    for (size_t i = 0; i < group->nodes->len; i++) {
        dogecoin_node* node = vector_idx(group->nodes, i);
        dogecoin_node_disconnect(node);
    }
}
References dogecoin_node_disconnect(), vector::len, dogecoin_node_group_::nodes, and vector_idx.
dogecoin_node_misbehave()
dogecoin_bool dogecoin_node_misbehave (dogecoin_node * node)
Mark the node as misbehaved
Parameters
node The node that is being marked as misbehaved.
Returns
dogecoin_bool (uint8_t)
Definition at line 350 of file net.c.
{
    node->nodegroup->log_write_cb("Mark node %d as missbehaved\n", node->nodeid);
    node->state |= NODE_MISSBEHAVED;
    dogecoin_node_connection_state_changed(node);
    return 0;
}
References dogecoin_node_connection_state_changed(), dogecoin_node_group_::log_write_cb, NODE_MISSBEHAVED, dogecoin_node_::nodegroup, dogecoin_node_::nodeid, and dogecoin_node_::state.
Referenced by broadcast_post_cmd(), dogecoin_node_parse_message(), and read_cb().
dogecoin_node_new()
dogecoin_node * dogecoin_node_new ()
Initializes a new dogecoin_node
Returns
A pointer to a new dogecoin_node object.
Definition at line 291 of file net.c.
{
    dogecoin_node* node;
    node = dogecoin_calloc(1, sizeof(*node));
    node->version_handshake = false;
    node->state = 0;
    node->nonce = 0;
    node->services = 0;
    node->lastping = 0;
    node->time_started_con = 0;
    node->time_last_request = 0;
    dogecoin_hash_clear(node->last_requested_inv);
    node->recvBuffer = cstr_new_sz(DOGECOIN_P2P_MESSAGE_CHUNK_SIZE);
    node->hints = 0;
    return node;
}
References cstr_new_sz(), dogecoin_calloc(), dogecoin_hash_clear(), DOGECOIN_P2P_MESSAGE_CHUNK_SIZE, dogecoin_node_::hints, dogecoin_node_::last_requested_inv, dogecoin_node_::lastping, dogecoin_node_::nonce, dogecoin_node_::recvBuffer, dogecoin_node_::services, dogecoin_node_::state, dogecoin_node_::time_last_request, dogecoin_node_::time_started_con, and dogecoin_node_::version_handshake.
Referenced by dogecoin_node_group_add_peers_by_ip_or_seed().
dogecoin_node_parse_message()
int dogecoin_node_parse_message (dogecoin_node * node, dogecoin_p2p_msg_hdr * hdr, struct const_buffer * buf)
This function parses a command message received from another node.
Parameters
node The node that received the message.
hdr The header of the message.
buf The buffer containing the message.
Returns
int
Definition at line 687 of file net.c.
{
    node->nodegroup->log_write_cb("received command from node %d: %s\n", node->nodeid, hdr->command);
    if (memcmp(hdr->netmagic, node->nodegroup->chainparams->netmagic, sizeof(node->nodegroup->chainparams->netmagic)) != 0) {
        return dogecoin_node_misbehave(node);
    }
    /* send the header and buffer to the possible callback */
    if (!node->nodegroup->parse_cmd_cb || node->nodegroup->parse_cmd_cb(node, hdr, buf)) {
        if (strcmp(hdr->command, DOGECOIN_MSG_VERSION) == 0) {
            dogecoin_p2p_version_msg v_msg_check;
            if (!dogecoin_p2p_msg_version_deser(&v_msg_check, buf)) {
                return dogecoin_node_misbehave(node);
            }
            if ((v_msg_check.services & DOGECOIN_NODE_NETWORK) != DOGECOIN_NODE_NETWORK) {
                dogecoin_node_disconnect(node);
            }
            node->bestknownheight = v_msg_check.start_height;
            node->nodegroup->log_write_cb("Connected to node %d: %s (%d)\n", node->nodeid, v_msg_check.useragent, v_msg_check.start_height);
            /* confirm version via verack */
            cstring* verack = dogecoin_p2p_message_new(node->nodegroup->chainparams->netmagic, DOGECOIN_MSG_VERACK, NULL, 0);
            dogecoin_node_send(node, verack);
            cstr_free(verack, true);
        } else if (strcmp(hdr->command, DOGECOIN_MSG_VERACK) == 0) {
            /* complete handshake if verack has been received */
            node->version_handshake = true;
            if (node->nodegroup->handshake_done_cb)
                node->nodegroup->handshake_done_cb(node);
        } else if (strcmp(hdr->command, DOGECOIN_MSG_PING) == 0) {
            uint64_t nonce = 0;
            if (!deser_u64(&nonce, buf)) {
                return dogecoin_node_misbehave(node);
            }
            cstring* pongmsg = dogecoin_p2p_message_new(node->nodegroup->chainparams->netmagic, DOGECOIN_MSG_PONG, &nonce, 8);
            dogecoin_node_send(node, pongmsg);
            cstr_free(pongmsg, true);
        }
    }
    if (node->nodegroup->postcmd_cb)
        node->nodegroup->postcmd_cb(node, hdr, buf);
    return true;
}
References dogecoin_node_::bestknownheight, dogecoin_node_group_::chainparams, dogecoin_p2p_msg_hdr_::command, cstr_free(), deser_u64(), DOGECOIN_MSG_PING, DOGECOIN_MSG_PONG, DOGECOIN_MSG_VERACK, DOGECOIN_MSG_VERSION, dogecoin_node_disconnect(), dogecoin_node_misbehave(), DOGECOIN_NODE_NETWORK, dogecoin_node_send(), dogecoin_p2p_message_new(), dogecoin_p2p_msg_version_deser(), dogecoin_node_group_::handshake_done_cb, dogecoin_node_group_::log_write_cb, dogecoin_chainparams_::netmagic, dogecoin_p2p_msg_hdr_::netmagic, dogecoin_node_::nodegroup, dogecoin_node_::nodeid, dogecoin_node_group_::parse_cmd_cb, dogecoin_node_group_::postcmd_cb, dogecoin_p2p_version_msg_::services, dogecoin_p2p_version_msg_::start_height, dogecoin_p2p_version_msg_::useragent, and dogecoin_node_::version_handshake.
Referenced by read_cb().
dogecoin_node_release_events()
void dogecoin_node_release_events (dogecoin_node * node)
Release the event buffer and timer event
Parameters
node The node that we're releasing the events for.
Definition at line 329 of file net.c.
{
    if (node->event_bev) {
        bufferevent_free(node->event_bev);
        node->event_bev = NULL;
    }
    if (node->timer_event) {
        event_del(node->timer_event);
        event_free(node->timer_event);
        node->timer_event = NULL;
    }
}
References bufferevent_free(), dogecoin_node_::event_bev, event_del(), event_free(), and dogecoin_node_::timer_event.
Referenced by dogecoin_node_connection_state_changed(), and dogecoin_node_disconnect().
dogecoin_node_send()
void dogecoin_node_send (dogecoin_node * node, cstring * data)
Send a message to a node
Parameters
node the node that is sending the message
data The data to send.
Returns
dogecoin_bool (uint8_t)
Definition at line 630 of file net.c.
{
    if ((node->state & NODE_CONNECTED) != NODE_CONNECTED)
        return;
    bufferevent_write(node->event_bev, data->str, data->len);
    char* dummy = data->str + 4;
    node->nodegroup->log_write_cb("sending message to node %d: %s\n", node->nodeid, dummy);
}
References bufferevent_write(), dogecoin_node_::event_bev, cstring::len, dogecoin_node_group_::log_write_cb, NODE_CONNECTED, dogecoin_node_::nodegroup, dogecoin_node_::nodeid, dogecoin_node_::state, and cstring::str.
Referenced by broadcast_handshake_done(), broadcast_post_cmd(), dogecoin_node_parse_message(), dogecoin_node_send_version(), and node_periodical_timer().
dogecoin_node_send_version()
void dogecoin_node_send_version (dogecoin_node * node)
Send a version message to the remote node
Parameters
node The node that is sending the message.
Definition at line 645 of file net.c.
{
    if (!node)
        return;
    cstring* version_msg_cstr = cstr_new_sz(256);
    /* copy socket_addr to p2p addr */
    dogecoin_p2p_address fromAddr;
    dogecoin_p2p_address_init(&fromAddr);
    dogecoin_p2p_address toAddr;
    dogecoin_p2p_address_init(&toAddr);
    dogecoin_addr_to_p2paddr(&node->addr, &toAddr);
    /* create a version message struct */
    dogecoin_p2p_version_msg version_msg;
    dogecoin_mem_zero(&version_msg, sizeof(version_msg));
    /* create a serialized version message */
    dogecoin_p2p_msg_version_init(&version_msg, &fromAddr, &toAddr, node->nodegroup->clientstr, true);
    dogecoin_p2p_msg_version_ser(&version_msg, version_msg_cstr);
    /* create p2p message */
    cstring* p2p_msg = dogecoin_p2p_message_new(node->nodegroup->chainparams->netmagic, DOGECOIN_MSG_VERSION, version_msg_cstr->str, version_msg_cstr->len);
    /* send message */
    dogecoin_node_send(node, p2p_msg);
    /* cleanup */
    cstr_free(version_msg_cstr, true);
    cstr_free(p2p_msg, true);
}
References dogecoin_node_::addr, dogecoin_node_group_::chainparams, dogecoin_node_group_::clientstr, cstr_free(), cstr_new_sz(), dogecoin_addr_to_p2paddr(), dogecoin_mem_zero(), DOGECOIN_MSG_VERSION, dogecoin_node_send(), dogecoin_p2p_address_init(), dogecoin_p2p_message_new(), dogecoin_p2p_msg_version_init(), dogecoin_p2p_msg_version_ser(), cstring::len, dogecoin_chainparams_::netmagic, dogecoin_node_::nodegroup, and cstring::str.
Referenced by dogecoin_node_connection_state_changed().
dogecoin_node_set_ipport()
dogecoin_bool dogecoin_node_set_ipport (dogecoin_node * node, const char * ipport)
Given a node and a string, set the node's address to the string
Parameters
node the node structure to be filled
ipport The IP address and port of the node.
Returns
dogecoin_bool (uint8_t)
Definition at line 317 of file net.c.
{
    int outlen = (int)sizeof(node->addr);
    return (evutil_parse_sockaddr_port(ipport, &node->addr, &outlen) == 0);
}
References dogecoin_node_::addr, and evutil_parse_sockaddr_port().
Referenced by dogecoin_node_group_add_peers_by_ip_or_seed().
event_cb()
void event_cb (struct bufferevent * ev, short type, void * ctx)
When the event callback is called it sets the node's state with the type of event that happened.
Parameters
ev The bufferevent structure.
type The event type.
ctx The node object.
Definition at line 251 of file net.c.
{
    UNUSED(ev);
    dogecoin_node* node = (dogecoin_node*)ctx;
    node->nodegroup->log_write_cb("Event callback on node %d\n", node->nodeid);
    if (((type & BEV_EVENT_TIMEOUT) != 0) && ((node->state & NODE_CONNECTING) == NODE_CONNECTING)) {
        node->nodegroup->log_write_cb("Timout connecting to node %d.\n", node->nodeid);
        node->state = 0;
        node->state |= NODE_ERRORED;
        node->state |= NODE_TIMEOUT;
        dogecoin_node_connection_state_changed(node);
    } else if (((type & BEV_EVENT_EOF) != 0) ||
               ((type & BEV_EVENT_ERROR) != 0)) {
        node->state = 0;
        node->state |= NODE_ERRORED;
        node->state |= NODE_DISCONNECTED;
        if ((type & BEV_EVENT_EOF) != 0) {
            node->nodegroup->log_write_cb("Disconnected from the remote peer %d.\n", node->nodeid);
            node->state |= NODE_DISCONNECTED_FROM_REMOTE_PEER;
        }
        else {
            node->nodegroup->log_write_cb("Error connecting to node %d.\n", node->nodeid);
        }
        dogecoin_node_connection_state_changed(node);
    } else if (type & BEV_EVENT_CONNECTED) {
        node->nodegroup->log_write_cb("Successful connected to node %d.\n", node->nodeid);
        node->state |= NODE_CONNECTED;
        node->state &= ~NODE_CONNECTING;
        node->state &= ~NODE_ERRORED;
        dogecoin_node_connection_state_changed(node);
    }
    node->nodegroup->log_write_cb("Connected nodes: %d\n", dogecoin_node_group_amount_of_connected_nodes(node->nodegroup, NODE_CONNECTED));
}
References ctx, dogecoin_node_connection_state_changed(), dogecoin_node_group_amount_of_connected_nodes(), dogecoin_node_group_::log_write_cb, NODE_CONNECTED, NODE_CONNECTING, NODE_DISCONNECTED, NODE_DISCONNECTED_FROM_REMOTE_PEER, NODE_ERRORED, NODE_TIMEOUT, dogecoin_node_::nodegroup, dogecoin_node_::nodeid, dogecoin_node_::state, and UNUSED.
Referenced by dogecoin_node_group_connect_next_nodes().
net_write_log_null()
int net_write_log_null (const char * format, ...)
This function is used to write to the log file
Parameters
format The format string for the printf function.
Returns
1
Definition at line 106 of file net.c.
{
    UNUSED(format);
    return 1;
}
References UNUSED.
Referenced by dogecoin_node_group_new().
net_write_log_printf()
int net_write_log_printf (const char * format, ...)
This function is used to print debug messages to the log file
Parameters
format The format string.
Returns
1
Definition at line 89 of file net.c.
{
    va_list args;
    va_start(args, format);
    printf("DEBUG: ");
    vprintf(format, args);
    va_end(args);
    return 1;
}
Referenced by broadcast_tx().
node_periodical_timer()
void node_periodical_timer (int fd, short int event, void * ctx)
The node_periodical_timer function is called every second by the node_timer_loop function and checks if the node is connected to the network.
Parameters
fd The file descriptor of the socket.
event The event that triggered the callback.
ctx The node object.
Returns
dogecoin_bool (uint8_t)
Definition at line 212 of file net.c.
{
    UNUSED(fd);
    UNUSED(event);
    dogecoin_node* node = (dogecoin_node*)ctx;
    uint64_t now = time(NULL);
    if (node->nodegroup->periodic_timer_cb)
        if (!node->nodegroup->periodic_timer_cb(node, &now))
            return;
    if (node->time_started_con + DOGECOIN_CONNECT_TIMEOUT_S < now && ((node->state & NODE_CONNECTING) == NODE_CONNECTING)) {
        node->state = 0;
        node->time_started_con = 0;
        node->state |= NODE_ERRORED;
        node->state |= NODE_TIMEOUT;
        dogecoin_node_connection_state_changed(node);
    }
    /* This is checking if the node is connected and if the last ping time is greater than the current
    time plus the ping interval. */
    if (((node->state & NODE_CONNECTED) == NODE_CONNECTED) && node->lastping + DOGECOIN_PING_INTERVAL_S < now) {
        uint64_t nonce;
        dogecoin_cheap_random_bytes((uint8_t*)&nonce, sizeof(nonce));
        cstring* pingmsg = dogecoin_p2p_message_new(node->nodegroup->chainparams->netmagic, DOGECOIN_MSG_PING, &nonce, sizeof(nonce));
        dogecoin_node_send(node, pingmsg);
        cstr_free(pingmsg, true);
        node->lastping = now;
    }
}
References dogecoin_node_group_::chainparams, cstr_free(), ctx, dogecoin_cheap_random_bytes(), DOGECOIN_CONNECT_TIMEOUT_S, DOGECOIN_MSG_PING, dogecoin_node_connection_state_changed(), dogecoin_node_send(), dogecoin_p2p_message_new(), DOGECOIN_PING_INTERVAL_S, dogecoin_node_::lastping, dogecoin_chainparams_::netmagic, NODE_CONNECTED, NODE_CONNECTING, NODE_ERRORED, NODE_TIMEOUT, dogecoin_node_::nodegroup, dogecoin_node_group_::periodic_timer_cb, dogecoin_node_::state, dogecoin_node_::time_started_con, and UNUSED.
Referenced by dogecoin_node_group_connect_next_nodes().
read_cb()
void read_cb (struct bufferevent * bev, void * ctx)
If we have a complete message, parse it
Parameters
bev The bufferevent that is being read from.
ctx The node object.
Returns
dogecoin_bool (uint8_t)
Definition at line 120 of file net.c.
{
    struct evbuffer* input = bufferevent_get_input(bev);
    if (!input)
        return;
    size_t length = evbuffer_get_length(input);
    dogecoin_node* node = (dogecoin_node*)ctx;
    if ((node->state & NODE_CONNECTED) != NODE_CONNECTED) {
        // ignore messages from disconnected peers
        return;
    }
    // expand the cstring buffer if required
    cstr_alloc_minsize(node->recvBuffer, node->recvBuffer->len + length);
    // copy direct to cstring, avoid another heap buffer
    evbuffer_copyout(input, node->recvBuffer->str + node->recvBuffer->len, length);
    node->recvBuffer->len += length;
    // drain the event buffer
    evbuffer_drain(input, length);
    struct const_buffer buf = {node->recvBuffer->str, node->recvBuffer->len};
    dogecoin_p2p_msg_hdr hdr;
    char* read_upto = NULL;
    do {
        if (buf.len < DOGECOIN_P2P_HDRSZ) {
            break;
        }
        dogecoin_p2p_deser_msghdr(&hdr, &buf);
        if (hdr.data_len > DOGECOIN_MAX_P2P_MSG_SIZE) {
            dogecoin_node_misbehave(node);
            return;
        }
        if (buf.len < hdr.data_len) {
            break;
        }
        if (buf.len >= hdr.data_len) {
            struct const_buffer cmd_data_buf = {buf.p, buf.len};
            if ((node->state & NODE_CONNECTED) != NODE_CONNECTED) {
                return;
            }
            dogecoin_node_parse_message(node, &hdr, &cmd_data_buf);
            buf.p = (const unsigned char*)buf.p + hdr.data_len;
            buf.len -= hdr.data_len;
            read_upto = (void*)buf.p;
        }
        if (buf.len == 0) {
            node->recvBuffer->len = 0;
            break;
        }
    } while (1);
    if (read_upto != NULL && node->recvBuffer->len != 0 && read_upto != (node->recvBuffer->str + node->recvBuffer->len)) {
        char* end = node->recvBuffer->str + node->recvBuffer->len;
        size_t available_chunk_data = end - read_upto;
        cstring* tmp = cstr_new_buf(read_upto, available_chunk_data);
        cstr_free(node->recvBuffer, true);
        node->recvBuffer = tmp;
    }
}
References bufferevent_get_input(), cstr_alloc_minsize(), cstr_free(), cstr_new_buf(), ctx, dogecoin_p2p_msg_hdr_::data_len, DOGECOIN_MAX_P2P_MSG_SIZE, dogecoin_node_misbehave(), dogecoin_node_parse_message(), dogecoin_p2p_deser_msghdr(), DOGECOIN_P2P_HDRSZ, evbuffer_copyout(), evbuffer_drain(), evbuffer_get_length(), const_buffer::len, cstring::len, NODE_CONNECTED, const_buffer::p, dogecoin_node_::recvBuffer, dogecoin_node_::state, and cstring::str.
Referenced by dogecoin_node_group_connect_next_nodes().
write_cb()
void write_cb (struct bufferevent * ev, void * ctx)
This function is called when the client sends data to the server
Parameters
ev The bufferevent object.
ctx The context parameter is a pointer to the context object that was passed to bufferevent_socket_new().
Definition at line 194 of file net.c.
{
    UNUSED(ev);
    UNUSED(ctx);
}
References ctx, and UNUSED.
Referenced by dogecoin_node_group_connect_next_nodes().
Variable Documentation
DOGECOIN_CONNECT_TIMEOUT_S
const int DOGECOIN_CONNECT_TIMEOUT_S = 10 static
Definition at line 80 of file net.c.
Referenced by node_periodical_timer().
DOGECOIN_PERIODICAL_NODE_TIMER_S
const int DOGECOIN_PERIODICAL_NODE_TIMER_S = 3 static
Definition at line 78 of file net.c.
Referenced by dogecoin_node_group_connect_next_nodes().
DOGECOIN_PING_INTERVAL_S
const int DOGECOIN_PING_INTERVAL_S = 120 static
Definition at line 79 of file net.c.
Referenced by node_periodical_timer().