libdogecoin: src/png.c File Reference
png.c File Reference
#include <qr/png.h>
Data Structures
struct ucvector
Macros
#define LODEPNG_INLINE /* not available */
#define LODEPNG_RESTRICT /* not available */
#define LODEPNG_MAX(a, b) (((a) > (b)) ? (a) : (b))
#define LODEPNG_MIN(a, b) (((a) < (b)) ? (a) : (b))
#define LODEPNG_ABS(x) ((x) < 0 ? -(x) : (x))
#define CERROR_BREAK(errorvar, code)
#define ERROR_BREAK(code) CERROR_BREAK(error, code)
#define CERROR_RETURN_ERROR(errorvar, code)
#define CERROR_TRY_RETURN(call)
#define CERROR_RETURN(errorvar, code)
Typedefs
typedef struct ucvector ucvector
Functions
void * lodepng_malloc (size_t size)
void * lodepng_realloc (void *ptr, size_t new_size)
void lodepng_free (void *ptr)
static void lodepng_memcpy (void *LODEPNG_RESTRICT dst, const void *LODEPNG_RESTRICT src, size_t size)
static void lodepng_memset (void *LODEPNG_RESTRICT dst, int value, size_t num)
static size_t lodepng_strlen (const char *a)
static unsigned ucvector_reserve (ucvector *p, size_t size)
static unsigned ucvector_resize (ucvector *p, size_t size)
static ucvector ucvector_init (unsigned char *buffer, size_t size)
Variables
const char * LODEPNG_VERSION_STRING = "20221108"
Macro Definition Documentation
CERROR_BREAK
#define CERROR_BREAK (errorvar, code)
Value:
  {\
  errorvar = code;\
  break;\
}
Definition at line 180 of file png.c.
CERROR_RETURN
#define CERROR_RETURN (errorvar, code)
Value:
  {\
  errorvar = code;\
  return;\
}
Definition at line 201 of file png.c.
CERROR_RETURN_ERROR
#define CERROR_RETURN_ERROR (errorvar, code)
Value:
  {\
  errorvar = code;\
  return code;\
}
Definition at line 189 of file png.c.
CERROR_TRY_RETURN
#define CERROR_TRY_RETURN (call)
Value:
  {\
  unsigned error = call;\
  if(error) return error;\
}
Definition at line 195 of file png.c.
ERROR_BREAK
#define ERROR_BREAK (code) CERROR_BREAK(error, code)
Definition at line 186 of file png.c.
LODEPNG_ABS
#define LODEPNG_ABS (x) ((x) < 0 ? -(x) : (x))
Definition at line 143 of file png.c.
LODEPNG_INLINE
#define LODEPNG_INLINE /* not available */
Definition at line 104 of file png.c.
LODEPNG_MAX
#define LODEPNG_MAX (a, b) (((a) > (b)) ? (a) : (b))
Definition at line 141 of file png.c.
LODEPNG_MIN
#define LODEPNG_MIN (a, b) (((a) < (b)) ? (a) : (b))
Definition at line 142 of file png.c.
LODEPNG_RESTRICT
#define LODEPNG_RESTRICT /* not available */
Definition at line 113 of file png.c.
Typedef Documentation
ucvector
typedef struct ucvector ucvector
Function Documentation
lodepng_free()
void lodepng_free (void * ptr)
lodepng_malloc()
void * lodepng_malloc (size_t size)
lodepng_memcpy()
static void lodepng_memcpy (void *LODEPNG_RESTRICT dst, const void *LODEPNG_RESTRICT src, size_t size) static
Definition at line 120 of file png.c.
{
  size_t i;
  for(i = 0; i < size; i++) ((char*)dst)[i] = ((const char*)src)[i];
}
lodepng_memset()
static void lodepng_memset (void *LODEPNG_RESTRICT dst, int value, size_t num) static
Definition at line 126 of file png.c.
{
  size_t i;
  for(i = 0; i < num; i++) ((char*)dst)[i] = (char)value;
}
lodepng_realloc()
void * lodepng_realloc (void * ptr, size_t new_size)
Referenced by ucvector_reserve().
lodepng_strlen()
static size_t lodepng_strlen (const char * a) static
Definition at line 133 of file png.c.
{
  const char* orig = a;
  /* avoid warning about unused function in case of disabled COMPILE... macros */
  (void)(&lodepng_strlen);
  while(*a) a++;
  return (size_t)(a - orig);
}
References lodepng_strlen().
Referenced by lodepng_strlen().
ucvector_init()
static ucvector ucvector_init (unsigned char * buffer, size_t size) static
Definition at line 289 of file png.c.
{
  ucvector v;
  v.data = buffer;
  v.allocsize = v.size = size;
  return v;
}
References ucvector::allocsize, ucvector::data, and ucvector::size.
ucvector_reserve()
static unsigned ucvector_reserve (ucvector * p, size_t size) static
Definition at line 270 of file png.c.
{
  if(size > p->allocsize) {
    size_t newsize = size + (p->allocsize >> 1u);
    void* data = lodepng_realloc(p->data, newsize);
    if(data) {
      p->allocsize = newsize;
      p->data = (unsigned char*)data;
    }
    else return 0; /*error: not enough memory*/
  }
  return 1; /*success*/
}
References ucvector::allocsize, ucvector::data, and lodepng_realloc().
Referenced by ucvector_resize().
ucvector_resize()
static unsigned ucvector_resize (ucvector * p, size_t size) static
Definition at line 284 of file png.c.
{
  p->size = size;
  return ucvector_reserve(p, size);
}
References ucvector::size, and ucvector_reserve().
Variable Documentation
LODEPNG_VERSION_STRING
const char* LODEPNG_VERSION_STRING = "20221108"
Definition at line 47 of file png.c.