libdogecoin: src/secp256k1/src/precomputed_ecmult.h File Reference
precomputed_ecmult.h File Reference
#include "group.h"
Macros
#define WINDOW_G ECMULT_WINDOW_SIZE
Variables
const secp256k1_ge_storage secp256k1_pre_g [ECMULT_TABLE_SIZE(WINDOW_G)]
const secp256k1_ge_storage secp256k1_pre_g_128 [ECMULT_TABLE_SIZE(WINDOW_G)]
Macro Definition Documentation
WINDOW_G
#define WINDOW_G ECMULT_WINDOW_SIZE
Definition at line 26 of file precomputed_ecmult.h.
Variable Documentation
secp256k1_pre_g
const secp256k1_ge_storage secp256k1_pre_g[ECMULT_TABLE_SIZE(WINDOW_G)] extern
Definition at line 20 of file precomputed_ecmult.c.
Referenced by main(), run_ecmult_pre_g(), and secp256k1_ecmult_strauss_wnaf().
secp256k1_pre_g_128
const secp256k1_ge_storage secp256k1_pre_g_128[ECMULT_TABLE_SIZE(WINDOW_G)] extern
Definition at line 8240 of file precomputed_ecmult.c.
Referenced by main(), run_ecmult_pre_g(), and secp256k1_ecmult_strauss_wnaf().