libdogecoin: include/dogecoin/protocol.h File Reference
protocol.h File Reference
#include <dogecoin/buffer.h>
#include <dogecoin/cstr.h>
#include <dogecoin/dogecoin.h>
#include <dogecoin/vector.h>
#include <arpa/inet.h>
#include <netinet/in.h>
#include <sys/socket.h>
Data Structures
struct dogecoin_p2p_msg_hdr_
struct dogecoin_p2p_inv_msg_
struct dogecoin_p2p_address_
struct dogecoin_p2p_version_msg_
Typedefs
typedef struct dogecoin_p2p_msg_hdr_ dogecoin_p2p_msg_hdr
typedef struct dogecoin_p2p_inv_msg_ dogecoin_p2p_inv_msg
typedef struct dogecoin_p2p_address_ dogecoin_p2p_address
typedef struct dogecoin_p2p_version_msg_ dogecoin_p2p_version_msg
Enumerations
enum service_bits {
DOGECOIN_NODE_NONE = 0 , DOGECOIN_NODE_NETWORK = (1 << 0) , DOGECOIN_NODE_GETUTXO = (1 << 1) , DOGECOIN_NODE_BLOOM = (1 << 2) ,
DOGECOIN_NODE_XTHIN = (1 << 4) , DOGECOIN_NODE_COMPACT_FILTERS = (1 << 6)
}
enum DOGECOIN_INV_TYPE {
DOGECOIN_INV_TYPE_ERROR = 0 , DOGECOIN_INV_TYPE_TX = 1 , DOGECOIN_INV_TYPE_BLOCK = 2 , DOGECOIN_INV_TYPE_FILTERED_BLOCK = 3 ,
DOGECOIN_INV_TYPE_CMPCT_BLOCK = 4
}
enum GetDataMsg { MSG_TX = 1 , MSG_BLOCK = 2 , MSG_FILTERED_BLOCK = 3 , MSG_CMPCT_BLOCK = 4 }
Functions
LIBDOGECOIN_API void dogecoin_p2p_msg_version_init (dogecoin_p2p_version_msg *msg, const dogecoin_p2p_address *addrFrom, const dogecoin_p2p_address *addrTo, const char *strSubVer, dogecoin_bool relay)
LIBDOGECOIN_API void dogecoin_p2p_msg_version_ser (dogecoin_p2p_version_msg *msg, cstring *buf)
LIBDOGECOIN_API dogecoin_bool dogecoin_p2p_msg_version_deser (dogecoin_p2p_version_msg *msg, struct const_buffer *buf)
LIBDOGECOIN_API void dogecoin_p2p_msg_inv_init (dogecoin_p2p_inv_msg *msg, uint32_t type, uint256 hash)
LIBDOGECOIN_API void dogecoin_p2p_msg_inv_ser (dogecoin_p2p_inv_msg *msg, cstring *buf)
LIBDOGECOIN_API dogecoin_bool dogecoin_p2p_msg_inv_deser (dogecoin_p2p_inv_msg *msg, struct const_buffer *buf)
LIBDOGECOIN_API void dogecoin_p2p_address_init (dogecoin_p2p_address *addr)
LIBDOGECOIN_API void dogecoin_addr_to_p2paddr (struct sockaddr *addr, dogecoin_p2p_address *addr_out)
LIBDOGECOIN_API dogecoin_bool dogecoin_p2p_deser_addr (unsigned int protocol_version, dogecoin_p2p_address *addr, struct const_buffer *buf)
LIBDOGECOIN_API void dogecoin_p2p_ser_addr (unsigned int protover, const dogecoin_p2p_address *addr, cstring *str_out)
LIBDOGECOIN_API void dogecoin_p2paddr_to_addr (dogecoin_p2p_address *p2p_addr, struct sockaddr *addr_out)
LIBDOGECOIN_API void dogecoin_p2p_deser_msghdr (dogecoin_p2p_msg_hdr *hdr, struct const_buffer *buf)
LIBDOGECOIN_API cstring * dogecoin_p2p_message_new (const unsigned char netmagic[4], const char *command, const void *data, uint32_t data_len)
LIBDOGECOIN_API void dogecoin_p2p_msg_getheaders (vector *blocklocators, uint256 hashstop, cstring *str_out)
LIBDOGECOIN_API dogecoin_bool dogecoin_p2p_deser_msg_getheaders (vector *blocklocators, uint256 hashstop, struct const_buffer *buf)
Variables
static LIBDOGECOIN_BEGIN_DECL const unsigned int DOGECOIN_MAX_P2P_MSG_SIZE = 0x003D0900
static const unsigned int DOGECOIN_P2P_HDRSZ = 24
static DISABLE_WARNING_PUSH uint256 NULLHASH = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
static const char * DOGECOIN_MSG_VERSION = "version"
static const char * DOGECOIN_MSG_VERACK = "verack"
static const char * DOGECOIN_MSG_PING = "ping"
static const char * DOGECOIN_MSG_PONG = "pong"
static const char * DOGECOIN_MSG_GETDATA = "getdata"
static const char * DOGECOIN_MSG_GETHEADERS = "getheaders"
static const char * DOGECOIN_MSG_HEADERS = "headers"
static const char * DOGECOIN_MSG_GETBLOCKS = "getblocks"
static const char * DOGECOIN_MSG_BLOCK = "block"
static const char * DOGECOIN_MSG_INV = "inv"
static const char * DOGECOIN_MSG_TX = "tx"
static const unsigned int MAX_HEADERS_RESULTS = 2000
static const int DOGECOIN_PROTOCOL_VERSION = 70015
static const uint32_t MSG_TYPE_MASK = 0xffffffff >> 2
Typedef Documentation
dogecoin_p2p_address
typedef struct dogecoin_p2p_address_ dogecoin_p2p_address
dogecoin_p2p_inv_msg
typedef struct dogecoin_p2p_inv_msg_ dogecoin_p2p_inv_msg
dogecoin_p2p_msg_hdr
typedef struct dogecoin_p2p_msg_hdr_ dogecoin_p2p_msg_hdr
dogecoin_p2p_version_msg
typedef struct dogecoin_p2p_version_msg_ dogecoin_p2p_version_msg
Enumeration Type Documentation
DOGECOIN_INV_TYPE
enum DOGECOIN_INV_TYPE
Enumerator
DOGECOIN_INV_TYPE_ERROR
DOGECOIN_INV_TYPE_TX
DOGECOIN_INV_TYPE_BLOCK
DOGECOIN_INV_TYPE_FILTERED_BLOCK
DOGECOIN_INV_TYPE_CMPCT_BLOCK
Definition at line 93 of file protocol.h.
                       {
    DOGECOIN_INV_TYPE_ERROR = 0,
    DOGECOIN_INV_TYPE_TX = 1,
    DOGECOIN_INV_TYPE_BLOCK = 2,
    DOGECOIN_INV_TYPE_FILTERED_BLOCK = 3,
    DOGECOIN_INV_TYPE_CMPCT_BLOCK = 4,
};
GetDataMsg
enum GetDataMsg
getdata / inv message types. These numbers are defined by the protocol. When adding a new value, be sure to mention it in the respective BIP.
Enumerator
MSG_TX
MSG_BLOCK
MSG_FILTERED_BLOCK
Defined in BIP37.
MSG_CMPCT_BLOCK
Defined in BIP152.
Definition at line 142 of file protocol.h.
{
    MSG_TX = 1,
    MSG_BLOCK = 2,
    // The following can only occur in getdata. Invs always use TX or BLOCK.
    MSG_FILTERED_BLOCK = 3,
    MSG_CMPCT_BLOCK = 4,
};
service_bits
enum service_bits
Enumerator
DOGECOIN_NODE_NONE
DOGECOIN_NODE_NETWORK
DOGECOIN_NODE_GETUTXO
DOGECOIN_NODE_BLOOM
DOGECOIN_NODE_XTHIN
DOGECOIN_NODE_COMPACT_FILTERS
Definition at line 59 of file protocol.h.
                  {
    // Nothing
    DOGECOIN_NODE_NONE = 0,
    // NODE_NETWORK means that the node is capable of serving the block chain. It is currently
    // set by all Bitcoin Core nodes, and is unset by SPV clients or other peers that just want
    // network services but don't provide them.
    DOGECOIN_NODE_NETWORK = (1 << 0),
    // NODE_GETUTXO means the node is capable of responding to the getutxo protocol request.
    // Bitcoin Core does not support this but a patch set called Bitcoin XT does.
    // See BIP 64 for details on how this is implemented.
    DOGECOIN_NODE_GETUTXO = (1 << 1),
    // NODE_BLOOM means the node is capable and willing to handle bloom-filtered connections.
    // Bitcoin Core nodes used to support this by default, without advertising this bit,
    // but no longer do as of protocol version 70011 (= NO_BLOOM_VERSION)
    DOGECOIN_NODE_BLOOM = (1 << 2),
    // NODE_XTHIN means the node supports Xtreme Thinblocks
    // If this is turned off then the node will not service nor make xthin requests
    DOGECOIN_NODE_XTHIN = (1 << 4),
    DOGECOIN_NODE_COMPACT_FILTERS = (1 << 6),
};
Function Documentation
dogecoin_addr_to_p2paddr()
LIBDOGECOIN_API void dogecoin_addr_to_p2paddr (struct sockaddr * addr, dogecoin_p2p_address * addr_out)
Convert a sockaddr to a dogecoin_p2p_address
Parameters
addr The address to convert.
addr_out the address to be filled in
Definition at line 159 of file protocol.c.
{
    if (addr->sa_family == AF_INET6) {
        struct sockaddr_in6* saddr = (struct sockaddr_in6*)addr;
        memcpy_safe(&addr_out->ip, &saddr->sin6_addr, 16);
        addr_out->port = ntohs(saddr->sin6_port);
    } else if (addr->sa_family == AF_INET) {
        struct sockaddr_in* saddr = (struct sockaddr_in*)addr;
        dogecoin_mem_zero(&addr_out->ip[0], 10);
        memset(&addr_out->ip[10], 0xff, 2);
        memcpy_safe(&addr_out->ip[12], &saddr->sin_addr, 4);
        addr_out->port = ntohs(saddr->sin_port);
    }
}
References AF_INET6, dogecoin_mem_zero(), dogecoin_p2p_address_::ip, memcpy_safe(), dogecoin_p2p_address_::port, sockaddr_in6::sin6_addr, and sockaddr_in6::sin6_port.
Referenced by dogecoin_node_send_version().
dogecoin_p2p_address_init()
LIBDOGECOIN_API void dogecoin_p2p_address_init (dogecoin_p2p_address * addr)
Initialize a dogecoin_p2p_address struct
Parameters
addr the address structure to initialize
Definition at line 65 of file protocol.c.
{
    dogecoin_mem_zero(addr, sizeof(*addr));
}
References dogecoin_mem_zero().
Referenced by dogecoin_node_send_version(), and dogecoin_p2p_msg_version_init().
dogecoin_p2p_deser_addr()
LIBDOGECOIN_API dogecoin_bool dogecoin_p2p_deser_addr (unsigned int protocol_version, dogecoin_p2p_address * addr, struct const_buffer * buf)
Deserialize an address
Parameters
protocol_version The version of the protocol the node is using.
addr the address object to be filled in
buf The buffer to deserialize from.
Returns
dogecoin_bool (uint8_t)
Definition at line 119 of file protocol.c.
{
    if (protocol_version >= DOGECOIN_ADDR_TIME_VERSION) {
        if (!deser_u32(&addr->time, buf))
            return false;
    } else
        addr->time = 0;
    if (!deser_u64(&addr->services, buf))
        return false;
    if (!deser_bytes(&addr->ip, buf, 16))
        return false;
    if (!deser_u16(&addr->port, buf))
        return false;
    return true;
}
References deser_bytes(), deser_u16(), deser_u32(), deser_u64(), DOGECOIN_ADDR_TIME_VERSION, dogecoin_p2p_address_::ip, dogecoin_p2p_address_::port, dogecoin_p2p_address_::services, and dogecoin_p2p_address_::time.
Referenced by dogecoin_p2p_msg_version_deser().
dogecoin_p2p_deser_msg_getheaders()
LIBDOGECOIN_API dogecoin_bool dogecoin_p2p_deser_msg_getheaders (vector * blocklocators, uint256 hashstop, struct const_buffer * buf)
Deserialize a getheaders message
Parameters
blocklocators a vector of block hashes
hashstop The hash of the last block that we want to request.
buf the buffer to deserialize from
Returns
dogecoin_bool (uint8_t)
Definition at line 376 of file protocol.c.
{
    int32_t version;
    uint32_t vsize;
    if (!deser_s32(&version, buf))
        return false;
    if (!deser_varlen(&vsize, buf))
        return false;
    vector_resize(blocklocators, vsize);
    for (unsigned int i = 0; i < vsize; i++) {
        uint256 *hash = dogecoin_malloc(DOGECOIN_HASH_LENGTH);
        if (!deser_u256(*hash, buf)) {
            dogecoin_free(hash);
            return false;
        }
        vector_add(blocklocators, hash);
    }
    if (!deser_u256(hashstop, buf))
        return false;
    return true;
}
References deser_s32(), deser_u256(), deser_varlen(), dogecoin_free(), DOGECOIN_HASH_LENGTH, dogecoin_malloc(), uint256, vector_add(), and vector_resize().
dogecoin_p2p_deser_msghdr()
LIBDOGECOIN_API void dogecoin_p2p_deser_msghdr (dogecoin_p2p_msg_hdr * hdr, struct const_buffer * buf)
Deserialize the dogecoin_p2p_msg_hdr structure
Parameters
hdr The dogecoin_p2p_msg_hdr struct that we're deserializing into.
buf The buffer to deserialize from.
Definition at line 404 of file protocol.c.
{
    deser_bytes(hdr->netmagic, buf, 4);
    deser_bytes(hdr->command, buf, 12);
    deser_u32(&hdr->data_len, buf);
    deser_bytes(hdr->hash, buf, 4);
}
References dogecoin_p2p_msg_hdr_::command, dogecoin_p2p_msg_hdr_::data_len, deser_bytes(), deser_u32(), dogecoin_p2p_msg_hdr_::hash, and dogecoin_p2p_msg_hdr_::netmagic.
Referenced by read_cb().
dogecoin_p2p_message_new()
LIBDOGECOIN_API cstring * dogecoin_p2p_message_new (const unsigned char netmagic[4], const char * command, const void * data, uint32_t data_len)
Create a new cstring object with the header information for a dogecoin p2p message
Parameters
netmagic The magic number is a 4-byte value that identifies the network.
command The command string.
data The data to be sent.
data_len The length of the data payload.
Returns
A cstring object.
Definition at line 80 of file protocol.c.
{
    cstring* s = cstr_new_sz(DOGECOIN_P2P_HDRSZ + data_len);
    /* network identifier (magic number) */
    cstr_append_buf(s, netmagic, 4);
    /* command string */
    char command_null[12];
    dogecoin_mem_zero(command_null, 12);
    memcpy_safe(command_null, command, strlen(command));
    //memset(command_null+strlen(command), 0, 12-strlen(command));
    cstr_append_buf(s, command_null, 12);
    /* data length, always 4 bytes */
    uint32_t data_len_le = htole32(data_len);
    cstr_append_buf(s, &data_len_le, 4);
    /* data checksum (first 4 bytes of the double sha256 hash of the pl) */
    uint256 msghash;
    dogecoin_hash(data, data_len, msghash);
    cstr_append_buf(s, &msghash[0], 4);
    /* data payload */
    if (data_len > 0)
        cstr_append_buf(s, data, data_len);
    return s;
}
References cstr_append_buf(), cstr_new_sz(), dogecoin_hash(), dogecoin_mem_zero(), DOGECOIN_P2P_HDRSZ, memcpy_safe(), and uint256.
Referenced by broadcast_handshake_done(), broadcast_post_cmd(), dogecoin_node_parse_message(), dogecoin_node_send_version(), and node_periodical_timer().
dogecoin_p2p_msg_getheaders()
LIBDOGECOIN_API void dogecoin_p2p_msg_getheaders (vector * blocklocators, uint256 hashstop, cstring * s)
This function serializes a getheaders message
Parameters
blocklocators a vector of block hashes
hashstop The hash of the last block in the chain that we want to download.
s the serialized message
Definition at line 351 of file protocol.c.
{
    unsigned int i;
    ser_u32(s, DOGECOIN_PROTOCOL_VERSION);
    ser_varlen(s, blocklocators->len);
    for (i = 0; i < blocklocators->len; i++) {
        uint256 *hash = vector_idx(blocklocators, i);
        ser_bytes(s, hash, DOGECOIN_HASH_LENGTH);
    }
    if (hashstop)
        ser_bytes(s, hashstop, DOGECOIN_HASH_LENGTH);
    else
        ser_bytes(s, NULLHASH, DOGECOIN_HASH_LENGTH);
}
References DOGECOIN_HASH_LENGTH, DOGECOIN_PROTOCOL_VERSION, vector::len, NULLHASH, ser_bytes(), ser_u32(), ser_varlen(), uint256, and vector_idx.
dogecoin_p2p_msg_inv_deser()
LIBDOGECOIN_API dogecoin_bool dogecoin_p2p_msg_inv_deser (dogecoin_p2p_inv_msg * msg, struct const_buffer * buf)
Deserialize a dogecoin_p2p_inv_msg from a const_buffer
Parameters
msg The message object to be filled in.
buf The buffer to deserialize from.
Returns
dogecoin_bool (uint8_t)
Definition at line 334 of file protocol.c.
{
    dogecoin_mem_zero(msg, sizeof(*msg));
    if (!deser_u32(&msg->type, buf))
        return false;
    if (!deser_u256(msg->hash, buf))
        return false;
    return true;
}
References deser_u256(), deser_u32(), dogecoin_mem_zero(), dogecoin_p2p_inv_msg_::hash, and dogecoin_p2p_inv_msg_::type.
Referenced by broadcast_post_cmd().
dogecoin_p2p_msg_inv_init()
LIBDOGECOIN_API void dogecoin_p2p_msg_inv_init (dogecoin_p2p_inv_msg * msg, uint32_t type, uint256 hash)
Initialize a dogecoin_p2p_inv_msg object
Parameters
msg The message object to initialize.
type The type of the inventory message.
hash The hash of the item being advertised.
Definition at line 308 of file protocol.c.
{
    msg->type = type;
    memcpy_safe(&msg->hash, hash, DOGECOIN_HASH_LENGTH);
}
References DOGECOIN_HASH_LENGTH, dogecoin_p2p_inv_msg_::hash, memcpy_safe(), and dogecoin_p2p_inv_msg_::type.
Referenced by broadcast_handshake_done().
dogecoin_p2p_msg_inv_ser()
LIBDOGECOIN_API void dogecoin_p2p_msg_inv_ser (dogecoin_p2p_inv_msg * msg, cstring * buf)
Serialize a dogecoin_p2p_inv_msg to a cstring.
Parameters
msg The message object to serialize.
buf The buffer to serialize into.
Definition at line 320 of file protocol.c.
{
    ser_u32(buf, msg->type);
    ser_bytes(buf, msg->hash, DOGECOIN_HASH_LENGTH);
}
References DOGECOIN_HASH_LENGTH, dogecoin_p2p_inv_msg_::hash, ser_bytes(), ser_u32(), and dogecoin_p2p_inv_msg_::type.
Referenced by broadcast_handshake_done().
dogecoin_p2p_msg_version_deser()
LIBDOGECOIN_API dogecoin_bool dogecoin_p2p_msg_version_deser (dogecoin_p2p_version_msg * msg, struct const_buffer * buf)
Deserialize a version message
Parameters
msg the message object to be filled
buf the buffer to deserialize from
Returns
dogecoin_bool (uint8_t)
Definition at line 257 of file protocol.c.
{
    dogecoin_mem_zero(msg, sizeof(*msg));
    if (!deser_s32(&msg->version, buf))
        return false;
    if (!deser_u64(&msg->services, buf))
        return false;
    if (!deser_s64(&msg->timestamp, buf))
        return false;
    if (!dogecoin_p2p_deser_addr(0, &msg->addr_recv, buf))
        return false;
    if (!dogecoin_p2p_deser_addr(0, &msg->addr_from, buf))
        return false;
    if (!deser_u64(&msg->nonce, buf))
        return false;
    uint32_t ua_len;
    uint32_t cpy_len;
    if (!deser_varlen(&ua_len, buf))
        return false;
    cpy_len = ua_len;
    if (cpy_len > 128)
        cpy_len = 128;
    /* we only support user agent strings up to 1024 chars */
    /* we only copy 128bytes to the message structure */
    if (ua_len > 1024)
        return false;
    char ua_str[1024];
    if (!deser_bytes(ua_str, buf, ua_len))
        return false;
    dogecoin_mem_zero(msg->useragent, sizeof(msg->useragent));
    memcpy_safe(&msg->useragent, ua_str, cpy_len);
    if (!deser_s32(&msg->start_height, buf))
        return false;
    if (msg->version > 70003)
        if (!deser_bytes(&msg->relay, buf, 1))
            return false;
    return true;
}
References dogecoin_p2p_version_msg_::addr_from, dogecoin_p2p_version_msg_::addr_recv, deser_bytes(), deser_s32(), deser_s64(), deser_u64(), deser_varlen(), dogecoin_mem_zero(), dogecoin_p2p_deser_addr(), memcpy_safe(), dogecoin_p2p_version_msg_::nonce, dogecoin_p2p_version_msg_::relay, dogecoin_p2p_version_msg_::services, dogecoin_p2p_version_msg_::start_height, dogecoin_p2p_version_msg_::timestamp, dogecoin_p2p_version_msg_::useragent, and dogecoin_p2p_version_msg_::version.
Referenced by dogecoin_node_parse_message().
dogecoin_p2p_msg_version_init()
LIBDOGECOIN_API void dogecoin_p2p_msg_version_init (dogecoin_p2p_version_msg * msg, const dogecoin_p2p_address * addrFrom, const dogecoin_p2p_address * addrTo, const char * strSubVer, dogecoin_bool relay)
Initialize a dogecoin_p2p_version_msg struct with the given parameters
Parameters
msg the message object
addrFrom The address of the node that sent the message.
addrTo The address to which the message is being sent.
strSubVer The user agent string.
relay If set to true, the node will relay transactions and blocks to other nodes.
Definition at line 208 of file protocol.c.
{
    msg->version = DOGECOIN_PROTOCOL_VERSION;
    msg->services = 0;
    msg->timestamp = time(NULL);
    msg->timestamp = time(NULL);
    if (addrTo)
        msg->addr_recv = *addrTo;
    else
        dogecoin_p2p_address_init(&msg->addr_recv);
    if (addrFrom)
        msg->addr_from = *addrFrom;
    else
        dogecoin_p2p_address_init(&msg->addr_from);
    dogecoin_cheap_random_bytes((uint8_t*)&msg->nonce, sizeof(msg->nonce));
    if (strSubVer && strlen(strSubVer) < 128)
        memcpy_safe(msg->useragent, strSubVer, strlen(strSubVer));
    msg->start_height = 0;
    msg->relay = relay;
}
References dogecoin_p2p_version_msg_::addr_from, dogecoin_p2p_version_msg_::addr_recv, dogecoin_cheap_random_bytes(), dogecoin_p2p_address_init(), DOGECOIN_PROTOCOL_VERSION, memcpy_safe(), dogecoin_p2p_version_msg_::nonce, dogecoin_p2p_version_msg_::relay, dogecoin_p2p_version_msg_::services, dogecoin_p2p_version_msg_::start_height, dogecoin_p2p_version_msg_::timestamp, dogecoin_p2p_version_msg_::useragent, and dogecoin_p2p_version_msg_::version.
Referenced by dogecoin_node_send_version().
dogecoin_p2p_msg_version_ser()
LIBDOGECOIN_API void dogecoin_p2p_msg_version_ser (dogecoin_p2p_version_msg * msg, cstring * buf)
It serializes a dogecoin_p2p_version_msg object into a cstring
Parameters
msg the message object
buf the buffer to serialize into
Definition at line 236 of file protocol.c.
{
    ser_s32(buf, msg->version);
    ser_u64(buf, msg->services);
    ser_s64(buf, msg->timestamp);
    dogecoin_p2p_ser_addr(0, &msg->addr_recv, buf);
    dogecoin_p2p_ser_addr(0, &msg->addr_from, buf);
    ser_u64(buf, msg->nonce);
    ser_str(buf, msg->useragent, 1024);
    ser_s32(buf, msg->start_height);
    cstr_append_c(buf, msg->relay);
}
References dogecoin_p2p_version_msg_::addr_from, dogecoin_p2p_version_msg_::addr_recv, cstr_append_c(), dogecoin_p2p_ser_addr(), dogecoin_p2p_version_msg_::nonce, dogecoin_p2p_version_msg_::relay, ser_s32(), ser_s64(), ser_str(), ser_u64(), dogecoin_p2p_version_msg_::services, dogecoin_p2p_version_msg_::start_height, dogecoin_p2p_version_msg_::timestamp, dogecoin_p2p_version_msg_::useragent, and dogecoin_p2p_version_msg_::version.
Referenced by dogecoin_node_send_version().
dogecoin_p2p_ser_addr()
LIBDOGECOIN_API void dogecoin_p2p_ser_addr (unsigned int protover, const dogecoin_p2p_address * addr, cstring * s)
Serialize a dogecoin_p2p_address struct to a cstring
Parameters
protover The protocol version.
addr The address to serialize.
s The cstring to serialize to.
Definition at line 143 of file protocol.c.
{
    if (protover >= DOGECOIN_ADDR_TIME_VERSION)
        ser_u32(s, addr->time);
    ser_u64(s, addr->services);
    ser_bytes(s, addr->ip, 16);
    ser_u16(s, addr->port);
}
References DOGECOIN_ADDR_TIME_VERSION, dogecoin_p2p_address_::ip, dogecoin_p2p_address_::port, ser_bytes(), ser_u16(), ser_u32(), ser_u64(), dogecoin_p2p_address_::services, and dogecoin_p2p_address_::time.
Referenced by dogecoin_p2p_msg_version_ser().
dogecoin_p2paddr_to_addr()
LIBDOGECOIN_API void dogecoin_p2paddr_to_addr (dogecoin_p2p_address * p2p_addr, struct sockaddr * addr_out)
Convert a dogecoin_p2p_address struct to a sockaddr struct
Parameters
p2p_addr the p2p_address struct to convert
addr_out The address to write the result to.
Returns
a pointer to a dogecoin_p2p_address structure.
Definition at line 182 of file protocol.c.
{
    if (!p2p_addr || !addr_out)
        return;
    if (!is_ipv4_mapped(p2p_addr->ip)) {
        /* ipv6 */
        struct sockaddr_in6* saddr = (struct sockaddr_in6*)addr_out;
        memcpy_safe(&saddr->sin6_addr, p2p_addr->ip, 16);
        saddr->sin6_port = htons(p2p_addr->port);
    } else {
        struct sockaddr_in* saddr = (struct sockaddr_in*)addr_out;
        memcpy_safe(&saddr->sin_addr, &p2p_addr->ip[12], 4);
        saddr->sin_port = htons(p2p_addr->port);
    }
}
References dogecoin_p2p_address_::ip, is_ipv4_mapped(), memcpy_safe(), dogecoin_p2p_address_::port, sockaddr_in6::sin6_addr, and sockaddr_in6::sin6_port.
Variable Documentation
DOGECOIN_MAX_P2P_MSG_SIZE
LIBDOGECOIN_BEGIN_DECL const unsigned int DOGECOIN_MAX_P2P_MSG_SIZE = 0x003D0900 static
Definition at line 51 of file protocol.h.
Referenced by main(), and read_cb().
DOGECOIN_MSG_BLOCK
const char* DOGECOIN_MSG_BLOCK = "block" static
Definition at line 88 of file protocol.h.
DOGECOIN_MSG_GETBLOCKS
const char* DOGECOIN_MSG_GETBLOCKS = "getblocks" static
Definition at line 87 of file protocol.h.
DOGECOIN_MSG_GETDATA
const char* DOGECOIN_MSG_GETDATA = "getdata" static
Definition at line 84 of file protocol.h.
Referenced by broadcast_post_cmd().
DOGECOIN_MSG_GETHEADERS
const char* DOGECOIN_MSG_GETHEADERS = "getheaders" static
Definition at line 85 of file protocol.h.
DOGECOIN_MSG_HEADERS
const char* DOGECOIN_MSG_HEADERS = "headers" static
Definition at line 86 of file protocol.h.
DOGECOIN_MSG_INV
const char* DOGECOIN_MSG_INV = "inv" static
Definition at line 89 of file protocol.h.
Referenced by broadcast_handshake_done(), and broadcast_post_cmd().
DOGECOIN_MSG_PING
const char* DOGECOIN_MSG_PING = "ping" static
Definition at line 82 of file protocol.h.
Referenced by dogecoin_node_parse_message(), and node_periodical_timer().
DOGECOIN_MSG_PONG
const char* DOGECOIN_MSG_PONG = "pong" static
Definition at line 83 of file protocol.h.
Referenced by dogecoin_node_parse_message().
DOGECOIN_MSG_TX
const char* DOGECOIN_MSG_TX = "tx" static
Definition at line 90 of file protocol.h.
Referenced by broadcast_post_cmd().
DOGECOIN_MSG_VERACK
const char* DOGECOIN_MSG_VERACK = "verack" static
Definition at line 81 of file protocol.h.
Referenced by dogecoin_node_parse_message().
DOGECOIN_MSG_VERSION
const char* DOGECOIN_MSG_VERSION = "version" static
Definition at line 80 of file protocol.h.
Referenced by dogecoin_node_parse_message(), and dogecoin_node_send_version().
DOGECOIN_P2P_HDRSZ
const unsigned int DOGECOIN_P2P_HDRSZ = 24 static
Definition at line 53 of file protocol.h.
Referenced by dogecoin_p2p_message_new(), and read_cb().
DOGECOIN_PROTOCOL_VERSION
const int DOGECOIN_PROTOCOL_VERSION = 70015 static
Definition at line 102 of file protocol.h.
Referenced by dogecoin_p2p_msg_getheaders(), and dogecoin_p2p_msg_version_init().
MAX_HEADERS_RESULTS
const unsigned int MAX_HEADERS_RESULTS = 2000 static
Definition at line 101 of file protocol.h.
MSG_TYPE_MASK
const uint32_t MSG_TYPE_MASK = 0xffffffff >> 2 static
getdata message type flags
Definition at line 136 of file protocol.h.
NULLHASH
DISABLE_WARNING_PUSH uint256 NULLHASH = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00} static
Definition at line 57 of file protocol.h.
Referenced by dogecoin_p2p_msg_getheaders().