libdogecoin: include/qr/qr.h File Reference
qr.h File Reference
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
Data Structures
struct qrcodegen_Segment
Macros
#define qrcodegen_VERSION_MIN 1
#define qrcodegen_VERSION_MAX 40
#define qrcodegen_BUFFER_LEN_FOR_VERSION(n) ((((n) * 4 + 17) * ((n) * 4 + 17) + 7) / 8 + 1)
#define qrcodegen_BUFFER_LEN_MAX qrcodegen_BUFFER_LEN_FOR_VERSION(qrcodegen_VERSION_MAX)
Enumerations
enum qrcodegen_Ecc { qrcodegen_Ecc_LOW = 0 , qrcodegen_Ecc_MEDIUM , qrcodegen_Ecc_QUARTILE , qrcodegen_Ecc_HIGH }
enum qrcodegen_Mask {
qrcodegen_Mask_AUTO = -1 , qrcodegen_Mask_0 = 0 , qrcodegen_Mask_1 , qrcodegen_Mask_2 ,
qrcodegen_Mask_3 , qrcodegen_Mask_4 , qrcodegen_Mask_5 , qrcodegen_Mask_6 ,
qrcodegen_Mask_7
}
enum qrcodegen_Mode {
qrcodegen_Mode_NUMERIC = 0x1 , qrcodegen_Mode_ALPHANUMERIC = 0x2 , qrcodegen_Mode_BYTE = 0x4 , qrcodegen_Mode_KANJI = 0x8 ,
qrcodegen_Mode_ECI = 0x7
}
Functions
bool qrcodegen_encodeText (const char *text, uint8_t tempBuffer[], uint8_t qrcode[], enum qrcodegen_Ecc ecl, int minVersion, int maxVersion, enum qrcodegen_Mask mask, bool boostEcl)
bool qrcodegen_encodeBinary (uint8_t dataAndTemp[], size_t dataLen, uint8_t qrcode[], enum qrcodegen_Ecc ecl, int minVersion, int maxVersion, enum qrcodegen_Mask mask, bool boostEcl)
bool qrcodegen_encodeSegments (const struct qrcodegen_Segment segs[], size_t len, enum qrcodegen_Ecc ecl, uint8_t tempBuffer[], uint8_t qrcode[])
bool qrcodegen_encodeSegmentsAdvanced (const struct qrcodegen_Segment segs[], size_t len, enum qrcodegen_Ecc ecl, int minVersion, int maxVersion, enum qrcodegen_Mask mask, bool boostEcl, uint8_t tempBuffer[], uint8_t qrcode[])
bool qrcodegen_isNumeric (const char *text)
bool qrcodegen_isAlphanumeric (const char *text)
size_t qrcodegen_calcSegmentBufferSize (enum qrcodegen_Mode mode, size_t numChars)
struct qrcodegen_Segment qrcodegen_makeBytes (const uint8_t data[], size_t len, uint8_t buf[])
struct qrcodegen_Segment qrcodegen_makeNumeric (const char *digits, uint8_t buf[])
struct qrcodegen_Segment qrcodegen_makeAlphanumeric (const char *text, uint8_t buf[])
struct qrcodegen_Segment qrcodegen_makeEci (long assignVal, uint8_t buf[])
int qrcodegen_getSize (const uint8_t qrcode[])
bool qrcodegen_getModule (const uint8_t qrcode[], int x, int y)
Macro Definition Documentation
qrcodegen_BUFFER_LEN_FOR_VERSION
#define qrcodegen_BUFFER_LEN_FOR_VERSION (n) ((((n) * 4 + 17) * ((n) * 4 + 17) + 7) / 8 + 1)
Definition at line 139 of file qr.h.
qrcodegen_BUFFER_LEN_MAX
#define qrcodegen_BUFFER_LEN_MAX qrcodegen_BUFFER_LEN_FOR_VERSION(qrcodegen_VERSION_MAX)
Definition at line 144 of file qr.h.
qrcodegen_VERSION_MAX
#define qrcodegen_VERSION_MAX 40
Definition at line 133 of file qr.h.
qrcodegen_VERSION_MIN
#define qrcodegen_VERSION_MIN 1
Definition at line 132 of file qr.h.
Enumeration Type Documentation
qrcodegen_Ecc
enum qrcodegen_Ecc
Enumerator
qrcodegen_Ecc_LOW
qrcodegen_Ecc_MEDIUM
qrcodegen_Ecc_QUARTILE
qrcodegen_Ecc_HIGH
Definition at line 57 of file qr.h.
                   {
    // Must be declared in ascending order of error protection
    // so that an internal qrcodegen function works properly
    qrcodegen_Ecc_LOW = 0 ,  // The QR Code can tolerate about  7% erroneous codewords
    qrcodegen_Ecc_MEDIUM  ,  // The QR Code can tolerate about 15% erroneous codewords
    qrcodegen_Ecc_QUARTILE,  // The QR Code can tolerate about 25% erroneous codewords
    qrcodegen_Ecc_HIGH    ,  // The QR Code can tolerate about 30% erroneous codewords
};
qrcodegen_Mask
enum qrcodegen_Mask
Enumerator
qrcodegen_Mask_AUTO
qrcodegen_Mask_0
qrcodegen_Mask_1
qrcodegen_Mask_2
qrcodegen_Mask_3
qrcodegen_Mask_4
qrcodegen_Mask_5
qrcodegen_Mask_6
qrcodegen_Mask_7
Definition at line 70 of file qr.h.
                    {
    // A special value to tell the QR Code encoder to
    // automatically select an appropriate mask pattern
    qrcodegen_Mask_AUTO = -1,
    // The eight actual mask patterns
    qrcodegen_Mask_0 = 0,
    qrcodegen_Mask_1,
    qrcodegen_Mask_2,
    qrcodegen_Mask_3,
    qrcodegen_Mask_4,
    qrcodegen_Mask_5,
    qrcodegen_Mask_6,
    qrcodegen_Mask_7,
};
qrcodegen_Mode
enum qrcodegen_Mode
Enumerator
qrcodegen_Mode_NUMERIC
qrcodegen_Mode_ALPHANUMERIC
qrcodegen_Mode_BYTE
qrcodegen_Mode_KANJI
qrcodegen_Mode_ECI
Definition at line 89 of file qr.h.
                    {
    qrcodegen_Mode_NUMERIC      = 0x1,
    qrcodegen_Mode_ALPHANUMERIC = 0x2,
    qrcodegen_Mode_BYTE         = 0x4,
    qrcodegen_Mode_KANJI        = 0x8,
    qrcodegen_Mode_ECI          = 0x7,
};
Function Documentation
qrcodegen_calcSegmentBufferSize()
size_t qrcodegen_calcSegmentBufferSize (enum qrcodegen_Mode mode, size_t numChars)
Definition at line 832 of file qr.c.
{
    int temp = calcSegmentBitLength(mode, numChars);
    if (temp == -1)
        return SIZE_MAX;
    assert(0 <= temp && temp <= INT16_MAX);
    return ((size_t)temp + 7) / 8;
}
References calcSegmentBitLength(), qrcodegen_Segment::mode, and qrcodegen_Segment::numChars.
Referenced by qrcodegen_encodeText().
qrcodegen_encodeBinary()
bool qrcodegen_encodeBinary (uint8_t dataAndTemp[], size_t dataLen, uint8_t qrcode[], enum qrcodegen_Ecc ecl, int minVersion, int maxVersion, enum qrcodegen_Mask mask, bool boostEcl)
Definition at line 167 of file qr.c.
{
    struct qrcodegen_Segment seg;
    seg.mode = qrcodegen_Mode_BYTE;
    seg.bitLength = calcSegmentBitLength(seg.mode, dataLen);
    if (seg.bitLength == -1) {
        qrcode[0] = 0;  // Set size to invalid value for safety
        return false;
    }
    seg.numChars = (int)dataLen;
    seg.data = dataAndTemp;
    return qrcodegen_encodeSegmentsAdvanced(&seg, 1, ecl, minVersion, maxVersion, mask, boostEcl, dataAndTemp, qrcode);
}
References qrcodegen_Segment::bitLength, calcSegmentBitLength(), qrcodegen_Segment::data, qrcodegen_Segment::mode, qrcodegen_Segment::numChars, qrcodegen_encodeSegmentsAdvanced(), and qrcodegen_Mode_BYTE.
qrcodegen_encodeSegments()
bool qrcodegen_encodeSegments (const struct qrcodegen_Segment segs[], size_t len, enum qrcodegen_Ecc ecl, uint8_t tempBuffer[], uint8_t qrcode[])
Definition at line 196 of file qr.c.
{
    return qrcodegen_encodeSegmentsAdvanced(segs, len, ecl,
        qrcodegen_VERSION_MIN, qrcodegen_VERSION_MAX, qrcodegen_Mask_AUTO, true, tempBuffer, qrcode);
}
References qrcodegen_encodeSegmentsAdvanced(), qrcodegen_Mask_AUTO, qrcodegen_VERSION_MAX, and qrcodegen_VERSION_MIN.
qrcodegen_encodeSegmentsAdvanced()
bool qrcodegen_encodeSegmentsAdvanced (const struct qrcodegen_Segment segs[], size_t len, enum qrcodegen_Ecc ecl, int minVersion, int maxVersion, enum qrcodegen_Mask mask, bool boostEcl, uint8_t tempBuffer[], uint8_t qrcode[])
Definition at line 204 of file qr.c.
{
    assert(segs != NULL || len == 0);
    assert(qrcodegen_VERSION_MIN <= minVersion && minVersion <= maxVersion && maxVersion <= qrcodegen_VERSION_MAX);
    assert(0 <= (int)ecl && (int)ecl <= 3 && -1 <= (int)mask && (int)mask <= 7);
    // Find the minimal version number to use
    int version, dataUsedBits;
    for (version = minVersion; ; version++) {
        int dataCapacityBits = getNumDataCodewords(version, ecl) * 8;  // Number of data bits available
        dataUsedBits = getTotalBits(segs, len, version);
        if (dataUsedBits != -1 && dataUsedBits <= dataCapacityBits)
            break;  // This version number is found to be suitable
        if (version >= maxVersion) {  // All versions in the range could not fit the given data
            qrcode[0] = 0;  // Set size to invalid value for safety
            return false;
        }
    }
    assert(dataUsedBits != -1);
    // Increase the error correction level while the data still fits in the current version number
    for (int i = (int)qrcodegen_Ecc_MEDIUM; i <= (int)qrcodegen_Ecc_HIGH; i++) {  // From low to high
        if (boostEcl && dataUsedBits <= getNumDataCodewords(version, (enum qrcodegen_Ecc)i) * 8)
            ecl = (enum qrcodegen_Ecc)i;
    }
    // Concatenate all segments to create the data bit string
    memset(qrcode, 0, (size_t)qrcodegen_BUFFER_LEN_FOR_VERSION(version) * sizeof(qrcode[0]));
    int bitLen = 0;
    for (size_t i = 0; i < len; i++) {
        const struct qrcodegen_Segment *seg = &segs[i];
        appendBitsToBuffer((unsigned int)seg->mode, 4, qrcode, &bitLen);
        appendBitsToBuffer((unsigned int)seg->numChars, numCharCountBits(seg->mode, version), qrcode, &bitLen);
        for (int j = 0; j < seg->bitLength; j++) {
            int bit = (seg->data[j >> 3] >> (7 - (j & 7))) & 1;
            appendBitsToBuffer((unsigned int)bit, 1, qrcode, &bitLen);
        }
    }
    assert(bitLen == dataUsedBits);
    // Add terminator and pad up to a byte if applicable
    int dataCapacityBits = getNumDataCodewords(version, ecl) * 8;
    assert(bitLen <= dataCapacityBits);
    int terminatorBits = dataCapacityBits - bitLen;
    if (terminatorBits > 4)
        terminatorBits = 4;
    appendBitsToBuffer(0, terminatorBits, qrcode, &bitLen);
    appendBitsToBuffer(0, (8 - bitLen % 8) % 8, qrcode, &bitLen);
    assert(bitLen % 8 == 0);
    // Pad with alternating bytes until data capacity is reached
    for (uint8_t padByte = 0xEC; bitLen < dataCapacityBits; padByte ^= 0xEC ^ 0x11)
        appendBitsToBuffer(padByte, 8, qrcode, &bitLen);
    // Compute ECC, draw modules
    addEccAndInterleave(qrcode, version, ecl, tempBuffer);
    initializeFunctionModules(version, qrcode);
    drawCodewords(tempBuffer, getNumRawDataModules(version) / 8, qrcode);
    drawLightFunctionModules(qrcode, version);
    initializeFunctionModules(version, tempBuffer);
    // Do masking
    if (mask == qrcodegen_Mask_AUTO) {  // Automatically choose best mask
        long minPenalty = LONG_MAX;
        for (int i = 0; i < 8; i++) {
            enum qrcodegen_Mask msk = (enum qrcodegen_Mask)i;
            applyMask(tempBuffer, qrcode, msk);
            drawFormatBits(ecl, msk, qrcode);
            long penalty = getPenaltyScore(qrcode);
            if (penalty < minPenalty) {
                mask = msk;
                minPenalty = penalty;
            }
            applyMask(tempBuffer, qrcode, msk);  // Undoes the mask due to XOR
        }
    }
    assert(0 <= (int)mask && (int)mask <= 7);
    applyMask(tempBuffer, qrcode, mask);  // Apply the final choice of mask
    drawFormatBits(ecl, mask, qrcode);  // Overwrite old format bits
    return true;
}
References addEccAndInterleave(), appendBitsToBuffer(), applyMask(), qrcodegen_Segment::bitLength, qrcodegen_Segment::data, drawCodewords(), drawFormatBits(), drawLightFunctionModules(), getNumDataCodewords(), getNumRawDataModules(), getPenaltyScore(), getTotalBits(), initializeFunctionModules(), qrcodegen_Segment::mode, numCharCountBits(), qrcodegen_Segment::numChars, qrcodegen_BUFFER_LEN_FOR_VERSION, qrcodegen_Ecc_HIGH, qrcodegen_Ecc_MEDIUM, qrcodegen_Mask_AUTO, qrcodegen_VERSION_MAX, and qrcodegen_VERSION_MIN.
Referenced by qrcodegen_encodeBinary(), qrcodegen_encodeSegments(), and qrcodegen_encodeText().
qrcodegen_encodeText()
bool qrcodegen_encodeText (const char * text, uint8_t tempBuffer[], uint8_t qrcode[], enum qrcodegen_Ecc ecl, int minVersion, int maxVersion, enum qrcodegen_Mask mask, bool boostEcl)
Definition at line 129 of file qr.c.
{
    size_t textLen = strlen(text);
    if (textLen == 0)
        return qrcodegen_encodeSegmentsAdvanced(NULL, 0, ecl, minVersion, maxVersion, mask, boostEcl, tempBuffer, qrcode);
    size_t bufLen = (size_t)qrcodegen_BUFFER_LEN_FOR_VERSION(maxVersion);
    struct qrcodegen_Segment seg;
    if (qrcodegen_isNumeric(text)) {
        if (qrcodegen_calcSegmentBufferSize(qrcodegen_Mode_NUMERIC, textLen) > bufLen)
            goto fail;
        seg = qrcodegen_makeNumeric(text, tempBuffer);
    } else if (qrcodegen_isAlphanumeric(text)) {
        if (qrcodegen_calcSegmentBufferSize(qrcodegen_Mode_ALPHANUMERIC, textLen) > bufLen)
            goto fail;
        seg = qrcodegen_makeAlphanumeric(text, tempBuffer);
    } else {
        if (textLen > bufLen)
            goto fail;
        for (size_t i = 0; i < textLen; i++)
            tempBuffer[i] = (uint8_t)text[i];
        seg.mode = qrcodegen_Mode_BYTE;
        seg.bitLength = calcSegmentBitLength(seg.mode, textLen);
        if (seg.bitLength == -1)
            goto fail;
        seg.numChars = (int)textLen;
        seg.data = tempBuffer;
    }
    return qrcodegen_encodeSegmentsAdvanced(&seg, 1, ecl, minVersion, maxVersion, mask, boostEcl, tempBuffer, qrcode);
fail:
    qrcode[0] = 0;  // Set size to invalid value for safety
    return false;
}
References qrcodegen_Segment::bitLength, calcSegmentBitLength(), qrcodegen_Segment::data, qrcodegen_Segment::mode, qrcodegen_Segment::numChars, qrcodegen_BUFFER_LEN_FOR_VERSION, qrcodegen_calcSegmentBufferSize(), qrcodegen_encodeSegmentsAdvanced(), qrcodegen_isAlphanumeric(), qrcodegen_isNumeric(), qrcodegen_makeAlphanumeric(), qrcodegen_makeNumeric(), qrcodegen_Mode_ALPHANUMERIC, qrcodegen_Mode_BYTE, and qrcodegen_Mode_NUMERIC.
Referenced by qrgen_string_to_qr_jpgfile(), qrgen_string_to_qr_pngfile(), and stringToQrArray().
qrcodegen_getModule()
bool qrcodegen_getModule (const uint8_t qrcode[], int x, int y)
Definition at line 762 of file qr.c.
{
    assert(qrcode != NULL);
    int qrsize = qrcode[0];
    return (0 <= x && x < qrsize && 0 <= y && y < qrsize) && getModuleBounded(qrcode, x, y);
}
References getModuleBounded().
Referenced by bytesToMono(), bytesToRgb(), outputQRStringFromQRBytes(), and printQr().
qrcodegen_getSize()
int qrcodegen_getSize (const uint8_t qrcode[])
Definition at line 752 of file qr.c.
{
    assert(qrcode != NULL);
    int result = qrcode[0];
    assert((qrcodegen_VERSION_MIN * 4 + 17) <= result
        && result <= (qrcodegen_VERSION_MAX * 4 + 17));
    return result;
}
References qrcodegen_VERSION_MAX, and qrcodegen_VERSION_MIN.
Referenced by applyMask(), bytesToMono(), bytesToRgb(), drawCodewords(), drawFormatBits(), drawLightFunctionModules(), getPenaltyScore(), outputQRStringFromQRBytes(), printQr(), qrgen_p2pkh_to_qrbits(), qrgen_string_to_qr_jpgfile(), and qrgen_string_to_qr_pngfile().
qrcodegen_isAlphanumeric()
bool qrcodegen_isAlphanumeric (const char * text)
Definition at line 821 of file qr.c.
{
    assert(text != NULL);
    for (; *text != '\0'; text++) {
        if (strchr(ALPHANUMERIC_CHARSET, *text) == NULL)
            return false;
    }
    return true;
}
References ALPHANUMERIC_CHARSET.
Referenced by qrcodegen_encodeText().
qrcodegen_isNumeric()
bool qrcodegen_isNumeric (const char * text)
Definition at line 810 of file qr.c.
{
    assert(text != NULL);
    for (; *text != '\0'; text++) {
        if (*text < '0' || *text > '9')
            return false;
    }
    return true;
}
Referenced by qrcodegen_encodeText().
qrcodegen_makeAlphanumeric()
struct qrcodegen_Segment qrcodegen_makeAlphanumeric (const char * text, uint8_t buf[])
Definition at line 925 of file qr.c.
{
    assert(text != NULL);
    struct qrcodegen_Segment result;
    size_t len = strlen(text);
    result.mode = qrcodegen_Mode_ALPHANUMERIC;
    int bitLen = calcSegmentBitLength(result.mode, len);
    assert(bitLen != -1);
    result.numChars = (int)len;
    if (bitLen > 0)
        memset(buf, 0, ((size_t)bitLen + 7) / 8 * sizeof(buf[0]));
    result.bitLength = 0;
    unsigned int accumData = 0;
    int accumCount = 0;
    for (; *text != '\0'; text++) {
        const char *temp = strchr(ALPHANUMERIC_CHARSET, *text);
        assert(temp != NULL);
        accumData = accumData * 45 + (unsigned int)(temp - ALPHANUMERIC_CHARSET);
        accumCount++;
        if (accumCount == 2) {
            appendBitsToBuffer(accumData, 11, buf, &result.bitLength);
            accumData = 0;
            accumCount = 0;
        }
    }
    if (accumCount > 0)  // 1 character remaining
        appendBitsToBuffer(accumData, 6, buf, &result.bitLength);
    assert(result.bitLength == bitLen);
    result.data = buf;
    return result;
}
References ALPHANUMERIC_CHARSET, appendBitsToBuffer(), qrcodegen_Segment::bitLength, calcSegmentBitLength(), qrcodegen_Segment::data, qrcodegen_Segment::mode, qrcodegen_Segment::numChars, and qrcodegen_Mode_ALPHANUMERIC.
Referenced by qrcodegen_encodeText().
qrcodegen_makeBytes()
struct qrcodegen_Segment qrcodegen_makeBytes (const uint8_t data[], size_t len, uint8_t buf[])
Definition at line 876 of file qr.c.
{
    assert(data != NULL || len == 0);
    struct qrcodegen_Segment result;
    result.mode = qrcodegen_Mode_BYTE;
    result.bitLength = calcSegmentBitLength(result.mode, len);
    assert(result.bitLength != -1);
    result.numChars = (int)len;
    if (len > 0)
        memcpy(buf, data, len * sizeof(buf[0]));
    result.data = buf;
    return result;
}
References qrcodegen_Segment::bitLength, calcSegmentBitLength(), qrcodegen_Segment::data, qrcodegen_Segment::mode, qrcodegen_Segment::numChars, and qrcodegen_Mode_BYTE.
qrcodegen_makeEci()
struct qrcodegen_Segment qrcodegen_makeEci (long assignVal, uint8_t buf[])
Definition at line 959 of file qr.c.
{
    struct qrcodegen_Segment result;
    result.mode = qrcodegen_Mode_ECI;
    result.numChars = 0;
    result.bitLength = 0;
    if (assignVal < 0)
        assert(false);
    else if (assignVal < (1 << 7)) {
        memset(buf, 0, 1 * sizeof(buf[0]));
        appendBitsToBuffer((unsigned int)assignVal, 8, buf, &result.bitLength);
    } else if (assignVal < (1 << 14)) {
        memset(buf, 0, 2 * sizeof(buf[0]));
        appendBitsToBuffer(2, 2, buf, &result.bitLength);
        appendBitsToBuffer((unsigned int)assignVal, 14, buf, &result.bitLength);
    } else if (assignVal < 1000000L) {
        memset(buf, 0, 3 * sizeof(buf[0]));
        appendBitsToBuffer(6, 3, buf, &result.bitLength);
        appendBitsToBuffer((unsigned int)(assignVal >> 10), 11, buf, &result.bitLength);
        appendBitsToBuffer((unsigned int)(assignVal & 0x3FF), 10, buf, &result.bitLength);
    } else
        assert(false);
    result.data = buf;
    return result;
}
References appendBitsToBuffer(), qrcodegen_Segment::bitLength, qrcodegen_Segment::data, qrcodegen_Segment::mode, qrcodegen_Segment::numChars, and qrcodegen_Mode_ECI.
qrcodegen_makeNumeric()
struct qrcodegen_Segment qrcodegen_makeNumeric (const char * digits, uint8_t buf[])
Definition at line 891 of file qr.c.
{
    assert(digits != NULL);
    struct qrcodegen_Segment result;
    size_t len = strlen(digits);
    result.mode = qrcodegen_Mode_NUMERIC;
    int bitLen = calcSegmentBitLength(result.mode, len);
    assert(bitLen != -1);
    result.numChars = (int)len;
    if (bitLen > 0)
        memset(buf, 0, ((size_t)bitLen + 7) / 8 * sizeof(buf[0]));
    result.bitLength = 0;
    unsigned int accumData = 0;
    int accumCount = 0;
    for (; *digits != '\0'; digits++) {
        char c = *digits;
        assert('0' <= c && c <= '9');
        accumData = accumData * 10 + (unsigned int)(c - '0');
        accumCount++;
        if (accumCount == 3) {
            appendBitsToBuffer(accumData, 10, buf, &result.bitLength);
            accumData = 0;
            accumCount = 0;
        }
    }
    if (accumCount > 0)  // 1 or 2 digits remaining
        appendBitsToBuffer(accumData, accumCount * 3 + 1, buf, &result.bitLength);
    assert(result.bitLength == bitLen);
    result.data = buf;
    return result;
}
References appendBitsToBuffer(), qrcodegen_Segment::bitLength, calcSegmentBitLength(), qrcodegen_Segment::data, qrcodegen_Segment::mode, qrcodegen_Segment::numChars, and qrcodegen_Mode_NUMERIC.
Referenced by qrcodegen_encodeText().