libdogecoin: src/qrengine.c File Reference
qrengine.c File Reference
#include <stdbool.h>
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <qr/qr.h>
#include <qr/png.h>
#include <qr/jpeg.h>
#include <dogecoin/qrengine.h>
Functions
int stringToQrArray (const char *inString, uint8_t *outQrBytes)
int outputQRStringFromQRBytes (const uint8_t *inQrBytes, char *outString)
int qrgen_p2pkh_to_qr_string (const char *in_p2pkh, char *outString)
int qrgen_p2pkh_to_qrbits (const char *in_p2pkh, uint8_t *outQrByteArray)
void qrgen_p2pkh_consoleprint_to_qr (const char *in_p2pkh)
void printQr (const uint8_t qrcode[])
uint8_t * bytesToRgb (uint8_t *qrBytes, size_t multiplier)
uint8_t * bytesToMono (uint8_t *qrBytes, size_t multiplier)
int qrgen_string_to_qr_pngfile (const char *outFilename, const char *inString, uint8_t sizeMultiplier)
int qrgen_string_to_qr_jpgfile (const char *outFilename, const char *inString, uint8_t sizeMultiplier)
Function Documentation
bytesToMono()
uint8_t * bytesToMono (uint8_t * qrBytes, size_t multiplier)
Definition at line 142 of file qrengine.c.
{
    size_t side = qrcodegen_getSize(qrBytes);
    size_t pixelRunLength = side * side;
    uint8_t darkPixel[3] = {0, 0, 0};
    uint8_t litePixel[3] = {255, 255, 255};
    int step = 1;
    uint8_t* outMono = (uint8_t*)calloc(pixelRunLength * step * multiplier * multiplier, sizeof(uint8_t));
    int iterator = 0;
    for (int y = 0; y < (int)side; y++) {
        for (int r = 0; r < (int)multiplier; ++r) {
            for (int x = 0; x < (int)side; x++) {
                for (int n = 0; n < (int)multiplier; ++n) {
                    if (qrcodegen_getModule(qrBytes, x, y)) {
                        memcpy(outMono + iterator, litePixel, step);
                        iterator = iterator + step;
                    } else {
                        memcpy(outMono + iterator, darkPixel, step);
                        iterator = iterator + step;
                    }
                }
            }
        }
    }
    return outMono;
}
References qrcodegen_getModule(), and qrcodegen_getSize().
Referenced by qrgen_string_to_qr_jpgfile().
bytesToRgb()
uint8_t * bytesToRgb (uint8_t * qrBytes, size_t multiplier)
Definition at line 110 of file qrengine.c.
{
    size_t side = qrcodegen_getSize(qrBytes);
    size_t pixelRunLength = side * side;
    uint8_t darkPixel[3] = {0, 0, 0};
    uint8_t litePixel[3] = {255, 255, 255};
    int step = 3;
    uint8_t* outRgb = (uint8_t*)calloc(pixelRunLength * step * multiplier * multiplier, sizeof(uint8_t));
    int iterator = 0;
    for (int y = 0; y < (int)side; y++) {
        for (int r = 0; r < (int)multiplier; ++r) {
            for (int x = 0; x < (int)side; x++) {
                for (int n = 0; n < (int)multiplier; ++n) {
                    if (qrcodegen_getModule(qrBytes, x, y)) {
                        memcpy(outRgb + iterator, litePixel, step);
                        iterator = iterator + step;
                    } else {
                        memcpy(outRgb + iterator, darkPixel, step);
                        iterator = iterator + step;
                    }
                }
            }
        }
    }
    // should have outRgb now... sized correctly
    return outRgb;
}
References qrcodegen_getModule(), and qrcodegen_getSize().
Referenced by qrgen_string_to_qr_pngfile().
outputQRStringFromQRBytes()
int outputQRStringFromQRBytes (const uint8_t * inQrBytes, char * outString)
Definition at line 38 of file qrengine.c.
{
    outString[0] = '\0'; //make sure it starts with a nul so strcat knows what to do
    int size = qrcodegen_getSize(inQrBytes);
    int border = 4;
    const char* dark = "  ";
    const char* light = "##";
    for (int y = -border; y < size + border; y++) {
        for (int x = -border; x < size + border; x++) {
            if (qrcodegen_getModule(inQrBytes, x, y)) {
                strcat(outString, light);
            } else {
                strcat(outString, dark);
            }
        }
        strcat(outString, "\n");
    }
    strcat(outString,"\n");
    return 0;
}
References qrcodegen_getModule(), and qrcodegen_getSize().
Referenced by qrgen_p2pkh_to_qr_string().
printQr()
void printQr (const uint8_t qrcode[])
Definition at line 87 of file qrengine.c.
{
    int size = qrcodegen_getSize(qrcode);
    int border = 4;
    const char* dark = "  ";
    const char* light = "##";
    for (int y = -border; y < size + border; y++) {
        for (int x = -border; x < size + border; x++) {
            if (qrcodegen_getModule(qrcode, x, y)) {
                printf("%s", light);
            } else {
                printf("%s", dark);
            }
        }
        printf("\n");
    }
    printf("\n");
}
References qrcodegen_getModule(), and qrcodegen_getSize().
Referenced by qrgen_p2pkh_consoleprint_to_qr().
qrgen_p2pkh_consoleprint_to_qr()
void qrgen_p2pkh_consoleprint_to_qr (const char * in_p2pkh)
Definition at line 79 of file qrengine.c.
{
    uint8_t qrcode[qrcodegen_BUFFER_LEN_MAX];
    stringToQrArray(in_p2pkh, qrcode);
    printQr(qrcode);
}
References printQr(), qrcodegen_BUFFER_LEN_MAX, and stringToQrArray().
qrgen_p2pkh_to_qr_string()
int qrgen_p2pkh_to_qr_string (const char * in_p2pkh, char * outString)
Definition at line 62 of file qrengine.c.
{
    uint8_t temparray[qrcodegen_BUFFER_LEN_MAX];
    stringToQrArray(in_p2pkh, temparray);
    outputQRStringFromQRBytes(temparray, outString);
    return 0;
}
References outputQRStringFromQRBytes(), qrcodegen_BUFFER_LEN_MAX, and stringToQrArray().
qrgen_p2pkh_to_qrbits()
int qrgen_p2pkh_to_qrbits (const char * in_p2pkh, uint8_t * outQrByteArray)
Definition at line 71 of file qrengine.c.
{
    int size = qrcodegen_getSize(outQrByteArray);
    stringToQrArray(in_p2pkh,outQrByteArray);
    return size;
}
References qrcodegen_getSize(), and stringToQrArray().
qrgen_string_to_qr_jpgfile()
int qrgen_string_to_qr_jpgfile (const char * outFilename, const char * inString, uint8_t sizeMultiplier)
Definition at line 223 of file qrengine.c.
{
    if (sizeMultiplier < 1)
    {
        sizeMultiplier = 1;
    }
    const uint8_t* jpg;
    int jpgsize;
    unsigned width;
    unsigned height;
    uint8_t tempBuffer[qrcodegen_BUFFER_LEN_MAX];
    uint8_t qrcode[qrcodegen_BUFFER_LEN_MAX];
    bool codeGenerated = qrcodegen_encodeText(inString, tempBuffer, qrcode, qrcodegen_Ecc_MEDIUM, qrcodegen_VERSION_MIN, qrcodegen_VERSION_MAX, qrcodegen_Mask_AUTO, true);
    if (codeGenerated)
    {
        unsigned tempSideDim = qrcodegen_getSize(qrcode);
        width = tempSideDim * sizeMultiplier;
        height = tempSideDim * sizeMultiplier;
        // bytes to monobitmap with sizemodifier
        uint8_t* image = bytesToMono(qrcode, sizeMultiplier);
        //encode jpeg
        jpec_enc_t* enc = jpec_enc_new(image, width, height);
        jpg = jpec_enc_run(enc, &jpgsize);
        FILE* file = fopen(outFilename, "wb");
        fwrite(jpg, sizeof(uint8_t), jpgsize, file);
        fclose(file);
        jpec_enc_del(enc);
        free(image);
        return jpgsize;
    }
    else
    {
        printf("Error generating QR\n");
        return -1;
    }
}
References bytesToMono(), jpec_enc_del(), jpec_enc_new(), jpec_enc_run(), qrcodegen_BUFFER_LEN_MAX, qrcodegen_Ecc_MEDIUM, qrcodegen_encodeText(), qrcodegen_getSize(), qrcodegen_Mask_AUTO, qrcodegen_VERSION_MAX, and qrcodegen_VERSION_MIN.
qrgen_string_to_qr_pngfile()
int qrgen_string_to_qr_pngfile (const char * outFilename, const char * inString, uint8_t sizeMultiplier)
Definition at line 173 of file qrengine.c.
{
    if (sizeMultiplier<1)
    {
        sizeMultiplier = 1;
    }
    unsigned char* png;
    size_t pngsize;
    unsigned width;
    unsigned height;
    uint8_t tempBuffer[qrcodegen_BUFFER_LEN_MAX];
    uint8_t qrcode[qrcodegen_BUFFER_LEN_MAX];
    bool codeGenerated = qrcodegen_encodeText(inString, tempBuffer, qrcode, qrcodegen_Ecc_MEDIUM, qrcodegen_VERSION_MIN, qrcodegen_VERSION_MAX, qrcodegen_Mask_AUTO, true);
    if (codeGenerated)
    {
        unsigned tempSideDim = qrcodegen_getSize(qrcode);
        width = tempSideDim * sizeMultiplier;
        height = tempSideDim * sizeMultiplier;
        // bytes to rgb
        uint8_t* image = bytesToRgb(qrcode, sizeMultiplier);
        unsigned error = lodepng_encode24(&png, &pngsize, image, width, height);
        if (!error)
        {
            lodepng_save_file(png, pngsize, outFilename);
            free(png);
            free(image);
            return (int)pngsize;
        }
       else
        {
            printf("png error %u: %s\n", error, lodepng_error_text(error));
            free(png);
            free(image);
            return -1;
        }
    }
    else
    {
        printf("Error generating QR\n");
        return -1;
    }
}
References bytesToRgb(), lodepng_encode24(), lodepng_error_text(), lodepng_save_file(), qrcodegen_BUFFER_LEN_MAX, qrcodegen_Ecc_MEDIUM, qrcodegen_encodeText(), qrcodegen_getSize(), qrcodegen_Mask_AUTO, qrcodegen_VERSION_MAX, and qrcodegen_VERSION_MIN.
stringToQrArray()
int stringToQrArray (const char * inString, uint8_t * outQrBytes)
Definition at line 21 of file qrengine.c.
{
    uint8_t tempBuffer[qrcodegen_BUFFER_LEN_MAX];
    bool codeGenerated = qrcodegen_encodeText(inString, tempBuffer, outQrBytes, qrcodegen_Ecc_MEDIUM, qrcodegen_VERSION_MIN, qrcodegen_VERSION_MAX, qrcodegen_Mask_AUTO, true);
    if (codeGenerated)
    {
        //return 0 on pass/OK.
        return 0;
    }
    else
    {
        printf("Error generating QR\n");
        return 1;
    }
}
References qrcodegen_BUFFER_LEN_MAX, qrcodegen_Ecc_MEDIUM, qrcodegen_encodeText(), qrcodegen_Mask_AUTO, qrcodegen_VERSION_MAX, and qrcodegen_VERSION_MIN.
Referenced by qrgen_p2pkh_consoleprint_to_qr(), qrgen_p2pkh_to_qr_string(), and qrgen_p2pkh_to_qrbits().