libdogecoin: include/dogecoin/qrengine.h File Reference
qrengine.h File Reference
#include <dogecoin/cstr.h>
#include <dogecoin/dogecoin.h>
Functions
void printQr (const uint8_t qrcode[])
int outputQRStringFromQRBytes (const uint8_t *inQrBytes, char *outString)
int stringToQrArray (const char *inString, uint8_t *outQrBytes)
LIBDOGECOIN_BEGIN_DECL LIBDOGECOIN_API int qrgen_p2pkh_to_qr_string (const char *in_p2pkh, char *outString)
LIBDOGECOIN_API void qrgen_p2pkh_consoleprint_to_qr (const char *in_p2pkh)
LIBDOGECOIN_API int qrgen_p2pkh_to_qrbits (const char *in_p2pkh, uint8_t *outQrByteArray)
LIBDOGECOIN_API int qrgen_string_to_qr_pngfile (const char *outFilename, const char *inString, uint8_t sizeMultiplier)
LIBDOGECOIN_API int qrgen_string_to_qr_jpgfile (const char *outFilename, const char *inString, uint8_t sizeMultiplier)
Function Documentation
outputQRStringFromQRBytes()
int outputQRStringFromQRBytes (const uint8_t * inQrBytes, char * outString)
Definition at line 38 of file qrengine.c.
{
    outString[0] = '\0'; //make sure it starts with a nul so strcat knows what to do
    int size = qrcodegen_getSize(inQrBytes);
    int border = 4;
    const char* dark = "  ";
    const char* light = "##";
    for (int y = -border; y < size + border; y++) {
        for (int x = -border; x < size + border; x++) {
            if (qrcodegen_getModule(inQrBytes, x, y)) {
                strcat(outString, light);
            } else {
                strcat(outString, dark);
            }
        }
        strcat(outString, "\n");
    }
    strcat(outString,"\n");
    return 0;
}
References qrcodegen_getModule(), and qrcodegen_getSize().
Referenced by qrgen_p2pkh_to_qr_string().
printQr()
void printQr (const uint8_t qrcode[])
Definition at line 87 of file qrengine.c.
{
    int size = qrcodegen_getSize(qrcode);
    int border = 4;
    const char* dark = "  ";
    const char* light = "##";
    for (int y = -border; y < size + border; y++) {
        for (int x = -border; x < size + border; x++) {
            if (qrcodegen_getModule(qrcode, x, y)) {
                printf("%s", light);
            } else {
                printf("%s", dark);
            }
        }
        printf("\n");
    }
    printf("\n");
}
References qrcodegen_getModule(), and qrcodegen_getSize().
Referenced by qrgen_p2pkh_consoleprint_to_qr().
qrgen_p2pkh_consoleprint_to_qr()
LIBDOGECOIN_API void qrgen_p2pkh_consoleprint_to_qr (const char * in_p2pkh)
Definition at line 79 of file qrengine.c.
{
    uint8_t qrcode[qrcodegen_BUFFER_LEN_MAX];
    stringToQrArray(in_p2pkh, qrcode);
    printQr(qrcode);
}
References printQr(), qrcodegen_BUFFER_LEN_MAX, and stringToQrArray().
qrgen_p2pkh_to_qr_string()
LIBDOGECOIN_BEGIN_DECL LIBDOGECOIN_API int qrgen_p2pkh_to_qr_string (const char * in_p2pkh, char * outString)
Definition at line 62 of file qrengine.c.
{
    uint8_t temparray[qrcodegen_BUFFER_LEN_MAX];
    stringToQrArray(in_p2pkh, temparray);
    outputQRStringFromQRBytes(temparray, outString);
    return 0;
}
References outputQRStringFromQRBytes(), qrcodegen_BUFFER_LEN_MAX, and stringToQrArray().
qrgen_p2pkh_to_qrbits()
LIBDOGECOIN_API int qrgen_p2pkh_to_qrbits (const char * in_p2pkh, uint8_t * outQrByteArray)
Definition at line 71 of file qrengine.c.
{
    int size = qrcodegen_getSize(outQrByteArray);
    stringToQrArray(in_p2pkh,outQrByteArray);
    return size;
}
References qrcodegen_getSize(), and stringToQrArray().
qrgen_string_to_qr_jpgfile()
LIBDOGECOIN_API int qrgen_string_to_qr_jpgfile (const char * outFilename, const char * inString, uint8_t sizeMultiplier)
Definition at line 223 of file qrengine.c.
{
    if (sizeMultiplier < 1)
    {
        sizeMultiplier = 1;
    }
    const uint8_t* jpg;
    int jpgsize;
    unsigned width;
    unsigned height;
    uint8_t tempBuffer[qrcodegen_BUFFER_LEN_MAX];
    uint8_t qrcode[qrcodegen_BUFFER_LEN_MAX];
    bool codeGenerated = qrcodegen_encodeText(inString, tempBuffer, qrcode, qrcodegen_Ecc_MEDIUM, qrcodegen_VERSION_MIN, qrcodegen_VERSION_MAX, qrcodegen_Mask_AUTO, true);
    if (codeGenerated)
    {
        unsigned tempSideDim = qrcodegen_getSize(qrcode);
        width = tempSideDim * sizeMultiplier;
        height = tempSideDim * sizeMultiplier;
        // bytes to monobitmap with sizemodifier
        uint8_t* image = bytesToMono(qrcode, sizeMultiplier);
        //encode jpeg
        jpec_enc_t* enc = jpec_enc_new(image, width, height);
        jpg = jpec_enc_run(enc, &jpgsize);
        FILE* file = fopen(outFilename, "wb");
        fwrite(jpg, sizeof(uint8_t), jpgsize, file);
        fclose(file);
        jpec_enc_del(enc);
        free(image);
        return jpgsize;
    }
    else
    {
        printf("Error generating QR\n");
        return -1;
    }
}
References bytesToMono(), jpec_enc_del(), jpec_enc_new(), jpec_enc_run(), qrcodegen_BUFFER_LEN_MAX, qrcodegen_Ecc_MEDIUM, qrcodegen_encodeText(), qrcodegen_getSize(), qrcodegen_Mask_AUTO, qrcodegen_VERSION_MAX, and qrcodegen_VERSION_MIN.
qrgen_string_to_qr_pngfile()
LIBDOGECOIN_API int qrgen_string_to_qr_pngfile (const char * outFilename, const char * inString, uint8_t sizeMultiplier)
Definition at line 173 of file qrengine.c.
{
    if (sizeMultiplier<1)
    {
        sizeMultiplier = 1;
    }
    unsigned char* png;
    size_t pngsize;
    unsigned width;
    unsigned height;
    uint8_t tempBuffer[qrcodegen_BUFFER_LEN_MAX];
    uint8_t qrcode[qrcodegen_BUFFER_LEN_MAX];
    bool codeGenerated = qrcodegen_encodeText(inString, tempBuffer, qrcode, qrcodegen_Ecc_MEDIUM, qrcodegen_VERSION_MIN, qrcodegen_VERSION_MAX, qrcodegen_Mask_AUTO, true);
    if (codeGenerated)
    {
        unsigned tempSideDim = qrcodegen_getSize(qrcode);
        width = tempSideDim * sizeMultiplier;
        height = tempSideDim * sizeMultiplier;
        // bytes to rgb
        uint8_t* image = bytesToRgb(qrcode, sizeMultiplier);
        unsigned error = lodepng_encode24(&png, &pngsize, image, width, height);
        if (!error)
        {
            lodepng_save_file(png, pngsize, outFilename);
            free(png);
            free(image);
            return (int)pngsize;
        }
       else
        {
            printf("png error %u: %s\n", error, lodepng_error_text(error));
            free(png);
            free(image);
            return -1;
        }
    }
    else
    {
        printf("Error generating QR\n");
        return -1;
    }
}
References bytesToRgb(), lodepng_encode24(), lodepng_error_text(), lodepng_save_file(), qrcodegen_BUFFER_LEN_MAX, qrcodegen_Ecc_MEDIUM, qrcodegen_encodeText(), qrcodegen_getSize(), qrcodegen_Mask_AUTO, qrcodegen_VERSION_MAX, and qrcodegen_VERSION_MIN.
stringToQrArray()
int stringToQrArray (const char * inString, uint8_t * outQrBytes)
Definition at line 21 of file qrengine.c.
{
    uint8_t tempBuffer[qrcodegen_BUFFER_LEN_MAX];
    bool codeGenerated = qrcodegen_encodeText(inString, tempBuffer, outQrBytes, qrcodegen_Ecc_MEDIUM, qrcodegen_VERSION_MIN, qrcodegen_VERSION_MAX, qrcodegen_Mask_AUTO, true);
    if (codeGenerated)
    {
        //return 0 on pass/OK.
        return 0;
    }
    else
    {
        printf("Error generating QR\n");
        return 1;
    }
}
References qrcodegen_BUFFER_LEN_MAX, qrcodegen_Ecc_MEDIUM, qrcodegen_encodeText(), qrcodegen_Mask_AUTO, qrcodegen_VERSION_MAX, and qrcodegen_VERSION_MIN.
Referenced by qrgen_p2pkh_consoleprint_to_qr(), qrgen_p2pkh_to_qr_string(), and qrgen_p2pkh_to_qrbits().