libdogecoin: src/random.c File Reference
random.c File Reference
#include <dogecoin/random.h>
#include <assert.h>
#include <errno.h>
#include <fcntl.h>
#include <stdio.h>
#include <string.h>
#include <time.h>
#include <unistd.h>
Functions
void dogecoin_random_init_internal (void)
dogecoin_bool dogecoin_random_bytes_internal (uint8_t *buf, uint32_t len, const uint8_t update_seed)
void dogecoin_rnd_set_mapper_default ()
void dogecoin_rnd_set_mapper (const dogecoin_rnd_mapper mapper)
void dogecoin_random_init (void)
dogecoin_bool dogecoin_random_bytes (uint8_t *buf, uint32_t len, const uint8_t update_seed)
Variables
static const dogecoin_rnd_mapper default_rnd_mapper = { dogecoin_random_init_internal, dogecoin_random_bytes_internal }
static dogecoin_rnd_mapper current_rnd_mapper = { dogecoin_random_init_internal, dogecoin_random_bytes_internal }
Function Documentation
dogecoin_random_bytes()
dogecoin_bool dogecoin_random_bytes (uint8_t * buf, uint32_t len, const uint8_t update_seed)
Definition at line 131 of file random.c.
    {
    return current_rnd_mapper.dogecoin_random_bytes(buf, len, update_seed);
    }
References current_rnd_mapper.
Referenced by dogecoin_ecc_start(), dogecoin_privkey_gen(), dogecoin_privkey_verify_pubkey(), get_mnemonic(), and hd_gen_master().
dogecoin_random_bytes_internal()
dogecoin_bool dogecoin_random_bytes_internal (uint8_t * buf, uint32_t len, const uint8_t update_seed)
Definition at line 153 of file random.c.
    {
#ifdef WIN32
    (void)update_seed;
    /* BCryptGenRandom, defined in <bcrypt.h>
         <https://docs.microsoft.com/en-us/windows/win32/api/bcrypt/nf-bcrypt-bcryptgenrandom>
         with the BCRYPT_USE_SYSTEM_PREFERRED_RNG flag
         works in Windows 7 and newer.  */
    static int bcrypt_not_working /* = 0 */;
    if (!bcrypt_not_working) {
#if !HAVE_LIB_BCRYPT
        if (!initialized)
            initialize();
#endif
        if (BCryptGenRandomFunc != NULL
            && BCryptGenRandomFunc(NULL, buf, len, BCRYPT_USE_SYSTEM_PREFERRED_RNG) == 0 /*STATUS_SUCCESS*/)
            return 1;
        bcrypt_not_working = 1;
        }
#if !HAVE_LIB_BCRYPT
    /* CryptGenRandom, defined in <wincrypt.h>
       <https://docs.microsoft.com/en-us/windows/win32/api/wincrypt/nf-wincrypt-cryptgenrandom>
       works in older releases as well, but is now deprecated.
       CryptAcquireContext, defined in <wincrypt.h>
       <https://docs.microsoft.com/en-us/windows/win32/api/wincrypt/nf-wincrypt-cryptacquirecontexta>  */
    {
    static int crypt_initialized /* = 0 */;
    static HCRYPTPROV provider;
    if (!crypt_initialized) {
        if (CryptAcquireContextA(&provider, NULL, NULL, PROV_RSA_FULL, CRYPT_VERIFY_CONTEXT))
            crypt_initialized = 1;
        else
            crypt_initialized = -1;
        }
    if (crypt_initialized >= 0) {
        if (!CryptGenRandom(provider, len, buf)) {
            errno = EIO;
            return -1;
            }
        return 1;
        }
    }
# endif
    errno = ENOSYS;
    return -1;
#else
    (void)update_seed; //unused
    FILE* frand = fopen("/dev/urandom", "r"); // figure out why RANDOM_DEVICE is undeclared here
    if (!frand)
        return false;
    size_t len_read = fread(buf, 1, len, frand);
    assert(len_read == len);
    fclose(frand);
    return true;
#endif
    }
dogecoin_random_init()
void dogecoin_random_init (void)
Definition at line 126 of file random.c.
    {
    current_rnd_mapper.dogecoin_random_init();
    }
References current_rnd_mapper.
Referenced by dogecoin_ecc_start().
dogecoin_random_init_internal()
void dogecoin_random_init_internal (void)
Definition at line 150 of file random.c.
    {
    }
dogecoin_rnd_set_mapper()
void dogecoin_rnd_set_mapper (const dogecoin_rnd_mapper mapper)
Definition at line 121 of file random.c.
    {
    current_rnd_mapper = mapper;
    }
References current_rnd_mapper.
dogecoin_rnd_set_mapper_default()
void dogecoin_rnd_set_mapper_default ()
Definition at line 116 of file random.c.
    {
    current_rnd_mapper = default_rnd_mapper;
    }
References current_rnd_mapper, and default_rnd_mapper.
Variable Documentation
current_rnd_mapper
dogecoin_rnd_mapper current_rnd_mapper = { dogecoin_random_init_internal, dogecoin_random_bytes_internal } static
Definition at line 114 of file random.c.
Referenced by dogecoin_random_bytes(), dogecoin_random_init(), dogecoin_rnd_set_mapper(), and dogecoin_rnd_set_mapper_default().
default_rnd_mapper
const dogecoin_rnd_mapper default_rnd_mapper = { dogecoin_random_init_internal, dogecoin_random_bytes_internal } static
Definition at line 113 of file random.c.
Referenced by dogecoin_rnd_set_mapper_default().