libdogecoin: include/dogecoin/random.h File Reference
random.h File Reference
#include <dogecoin/dogecoin.h>
Data Structures
struct dogecoin_rnd_mapper_
Typedefs
typedef LIBDOGECOIN_BEGIN_DECL struct dogecoin_rnd_mapper_ dogecoin_rnd_mapper
Functions
LIBDOGECOIN_API void dogecoin_rnd_set_mapper (const dogecoin_rnd_mapper mapper)
LIBDOGECOIN_API void dogecoin_rnd_set_mapper_default ()
LIBDOGECOIN_API void dogecoin_random_init (void)
LIBDOGECOIN_API dogecoin_bool dogecoin_random_bytes (uint8_t *buf, uint32_t len, const uint8_t update_seed)
Typedef Documentation
dogecoin_rnd_mapper
typedef LIBDOGECOIN_BEGIN_DECL struct dogecoin_rnd_mapper_ dogecoin_rnd_mapper
Function Documentation
dogecoin_random_bytes()
LIBDOGECOIN_API dogecoin_bool dogecoin_random_bytes (uint8_t * buf, uint32_t len, const uint8_t update_seed)
Definition at line 131 of file random.c.
    {
    return current_rnd_mapper.dogecoin_random_bytes(buf, len, update_seed);
    }
References current_rnd_mapper.
Referenced by dogecoin_ecc_start(), dogecoin_privkey_gen(), dogecoin_privkey_verify_pubkey(), get_mnemonic(), and hd_gen_master().
dogecoin_random_init()
LIBDOGECOIN_API void dogecoin_random_init (void)
Definition at line 126 of file random.c.
    {
    current_rnd_mapper.dogecoin_random_init();
    }
References current_rnd_mapper.
Referenced by dogecoin_ecc_start().
dogecoin_rnd_set_mapper()
LIBDOGECOIN_API void dogecoin_rnd_set_mapper (const dogecoin_rnd_mapper mapper)
Definition at line 121 of file random.c.
    {
    current_rnd_mapper = mapper;
    }
References current_rnd_mapper.
dogecoin_rnd_set_mapper_default()
LIBDOGECOIN_API void dogecoin_rnd_set_mapper_default ()
Definition at line 116 of file random.c.
    {
    current_rnd_mapper = default_rnd_mapper;
    }
References current_rnd_mapper, and default_rnd_mapper.