libdogecoin: src/libevent/ratelim-internal.h File Reference
ratelim-internal.h File Reference
#include "event2/util.h"
Data Structures
struct ev_token_bucket
struct ev_token_bucket_cfg
Macros
#define ev_token_bucket_decrement_read(b, n)
#define ev_token_bucket_decrement_write(b, n)
Functions
int ev_token_bucket_update_ (struct ev_token_bucket *bucket, const struct ev_token_bucket_cfg *cfg, ev_uint32_t current_tick)
ev_uint32_t ev_token_bucket_get_tick_ (const struct timeval *tv, const struct ev_token_bucket_cfg *cfg)
int ev_token_bucket_init_ (struct ev_token_bucket *bucket, const struct ev_token_bucket_cfg *cfg, ev_uint32_t current_tick, int reinitialize)
int bufferevent_remove_from_rate_limit_group_internal_ (struct bufferevent *bev, int unsuspend)
Macro Definition Documentation
ev_token_bucket_decrement_read
#define ev_token_bucket_decrement_read (b, n)
Value:
    do {                    \
        (b)->read_limit -= (n);     \
    } while (0)
Decrease the read limit of 'b' by 'n' bytes
Definition at line 91 of file ratelim-internal.h.
ev_token_bucket_decrement_write
#define ev_token_bucket_decrement_write (b, n)
Value:
    do {                    \
        (b)->write_limit -= (n);    \
    } while (0)
Decrease the write limit of 'b' by 'n' bytes
Definition at line 96 of file ratelim-internal.h.
Function Documentation
bufferevent_remove_from_rate_limit_group_internal_()
int bufferevent_remove_from_rate_limit_group_internal_ (struct bufferevent * bev, int unsuspend)
Definition at line 787 of file bufferevent_ratelim.c.
{
    struct bufferevent_private *bevp = BEV_UPCAST(bev);
    BEV_LOCK(bev);
    if (bevp->rate_limiting && bevp->rate_limiting->group) {
        struct bufferevent_rate_limit_group *g =
            bevp->rate_limiting->group;
        LOCK_GROUP(g);
        bevp->rate_limiting->group = NULL;
        --g->n_members;
        LIST_REMOVE(bevp, rate_limiting->next_in_group);
        UNLOCK_GROUP(g);
    }
    if (unsuspend) {
        bufferevent_unsuspend_read_(bev, BEV_SUSPEND_BW_GROUP);
        bufferevent_unsuspend_write_(bev, BEV_SUSPEND_BW_GROUP);
    }
    BEV_UNLOCK(bev);
    return 0;
}
References bufferevent_private::bev, BEV_LOCK, BEV_SUSPEND_BW_GROUP, BEV_UNLOCK, BEV_UPCAST, bufferevent_unsuspend_read_(), bufferevent_unsuspend_write_(), bufferevent_rate_limit::group, LOCK_GROUP, bufferevent_rate_limit_group::n_members, bufferevent_private::rate_limiting, and UNLOCK_GROUP.
Referenced by bufferevent_finalize_cb_(), and bufferevent_remove_from_rate_limit_group().
ev_token_bucket_get_tick_()
ev_uint32_t ev_token_bucket_get_tick_ (const struct timeval * tv, const struct ev_token_bucket_cfg * cfg)
In which tick does 'tv' fall according to 'cfg'? Note that ticks can overflow easily; your code needs to handle this.
Definition at line 127 of file bufferevent_ratelim.c.
{
    /* This computation uses two multiplies and a divide.  We could do
     * fewer if we knew that the tick length was an integer number of
     * seconds, or if we knew it divided evenly into a second.  We should
     * investigate that more.
     */
    /* We cast to an ev_uint64_t first, since we don't want to overflow
     * before we do the final divide. */
    ev_uint64_t msec = (ev_uint64_t)tv->tv_sec * 1000 + tv->tv_usec / 1000;
    return (unsigned)(msec / cfg->msec_per_tick);
}
References ev_token_bucket_cfg::msec_per_tick.
Referenced by bev_group_refill_callback_(), bev_refill_callback_(), bufferevent_rate_limit_group_new(), bufferevent_set_rate_limit(), and bufferevent_update_buckets().
ev_token_bucket_init_()
int ev_token_bucket_init_ (struct ev_token_bucket * bucket, const struct ev_token_bucket_cfg * cfg, ev_uint32_t current_tick, int reinitialize)
Adjust 'bucket' to respect 'cfg', and note that it was last updated in 'current_tick'. If 'reinitialize' is true, we are changing the configuration of 'bucket'; otherwise, we are setting it up for the first time.
Definition at line 50 of file bufferevent_ratelim.c.
{
    if (reinitialize) {
        /* on reinitialization, we only clip downwards, since we've
           already used who-knows-how-much bandwidth this tick.  We
           leave "last_updated" as it is; the next update will add the
           appropriate amount of bandwidth to the bucket.
        */
        if (bucket->read_limit > (ev_int64_t) cfg->read_maximum)
            bucket->read_limit = cfg->read_maximum;
        if (bucket->write_limit > (ev_int64_t) cfg->write_maximum)
            bucket->write_limit = cfg->write_maximum;
    } else {
        bucket->read_limit = cfg->read_rate;
        bucket->write_limit = cfg->write_rate;
        bucket->last_updated = current_tick;
    }
    return 0;
}
References ev_token_bucket::last_updated, ev_token_bucket::read_limit, ev_token_bucket_cfg::read_maximum, ev_token_bucket_cfg::read_rate, ev_token_bucket::write_limit, ev_token_bucket_cfg::write_maximum, and ev_token_bucket_cfg::write_rate.
Referenced by bufferevent_rate_limit_group_new(), and bufferevent_set_rate_limit().
ev_token_bucket_update_()
int ev_token_bucket_update_ (struct ev_token_bucket * bucket, const struct ev_token_bucket_cfg * cfg, ev_uint32_t current_tick)
The current tick is 'current_tick': add bytes to 'bucket' as specified in 'cfg'.
Definition at line 74 of file bufferevent_ratelim.c.
{
    /* It's okay if the tick number overflows, since we'll just
     * wrap around when we do the unsigned substraction. */
    unsigned n_ticks = current_tick - bucket->last_updated;
    /* Make sure some ticks actually happened, and that time didn't
     * roll back. */
    if (n_ticks == 0 || n_ticks > INT_MAX)
        return 0;
    /* Naively, we would say
        bucket->limit += n_ticks * cfg->rate;
        if (bucket->limit > cfg->maximum)
            bucket->limit = cfg->maximum;
       But we're worried about overflow, so we do it like this:
    */
    if ((cfg->read_maximum - bucket->read_limit) / n_ticks < cfg->read_rate)
        bucket->read_limit = cfg->read_maximum;
    else
        bucket->read_limit += n_ticks * cfg->read_rate;
    if ((cfg->write_maximum - bucket->write_limit) / n_ticks < cfg->write_rate)
        bucket->write_limit = cfg->write_maximum;
    else
        bucket->write_limit += n_ticks * cfg->write_rate;
    bucket->last_updated = current_tick;
    return 1;
}
References ev_token_bucket::last_updated, ev_token_bucket::read_limit, ev_token_bucket_cfg::read_maximum, ev_token_bucket_cfg::read_rate, ev_token_bucket::write_limit, ev_token_bucket_cfg::write_maximum, and ev_token_bucket_cfg::write_rate.
Referenced by bev_group_refill_callback_(), bev_refill_callback_(), and bufferevent_update_buckets().