libdogecoin: include/dogecoin/rmd160.h File Reference
rmd160.h File Reference
#include <dogecoin/dogecoin.h>
Functions
LIBDOGECOIN_BEGIN_DECL LIBDOGECOIN_API void rmd160 (const uint8_t *msg, uint32_t msg_len, uint8_t *hash)
Function Documentation
rmd160()
LIBDOGECOIN_BEGIN_DECL LIBDOGECOIN_API void rmd160 (const uint8_t * msg, uint32_t msg_len, uint8_t * hash)
Copyright (c) 2013-2014 Tomas Dzetkulic Copyright (c) 2013-2014 Pavol Rusnak Copyright (c) 2022 bluezr Copyright (c) 2022 The Dogecoin Foundation
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
Definition at line 294 of file rmd160.c.
{
    uint32_t i;
    int j;
    uint32_t digest[5] = {0x67452301, 0xefcdab89, 0x98badcfe, 0x10325476, 0xc3d2e1f0UL};
    for (i = 0; i < (msg_len >> 6); ++i) {
        uint32_t chunk[16];
        for (j = 0; j < 16; ++j) {
            chunk[j] = (uint32_t)(*(msg++));
            chunk[j] |= (uint32_t)(*(msg++)) << 8;
            chunk[j] |= (uint32_t)(*(msg++)) << 16;
            chunk[j] |= (uint32_t)(*(msg++)) << 24;
        }
        compress(digest, chunk);
    }
    // Last chunk
    {
        uint32_t chunk[16] = {0};
        for (i = 0; i < (msg_len & 63); ++i) {
            chunk[i >> 2] ^= (uint32_t)*msg++ << ((i & 3) << 3);
        }
        chunk[(msg_len >> 2) & 15] ^= (uint32_t)1 << (8 * (msg_len & 3) + 7);
        if ((msg_len & 63) > 55) {
            compress(digest, chunk);
            dogecoin_mem_zero(chunk, 64);
        }
        chunk[14] = msg_len << 3;
        chunk[15] = (msg_len >> 29);
        compress(digest, chunk);
    }
    for (i = 0; i < 5; ++i) {
        *(hash++) = digest[i];
        *(hash++) = digest[i] >> 8;
        *(hash++) = digest[i] >> 16;
        *(hash++) = digest[i] >> 24;
    }
}
References compress(), and dogecoin_mem_zero().
Referenced by dogecoin_hdnode_get_hash160(), dogecoin_hdnode_private_ckd(), dogecoin_hdnode_public_ckd(), dogecoin_pubkey_get_hash160(), and dogecoin_script_get_scripthash().