libdogecoin: src/secp256k1/src/scalar.h File Reference
scalar.h File Reference
#include "util.h"
#include "scalar_8x32.h"
Functions
static void secp256k1_scalar_clear (secp256k1_scalar *r)
static unsigned int secp256k1_scalar_get_bits (const secp256k1_scalar *a, unsigned int offset, unsigned int count)
static unsigned int secp256k1_scalar_get_bits_var (const secp256k1_scalar *a, unsigned int offset, unsigned int count)
static void secp256k1_scalar_set_b32 (secp256k1_scalar *r, const unsigned char *bin, int *overflow)
static int secp256k1_scalar_set_b32_seckey (secp256k1_scalar *r, const unsigned char *bin)
static void secp256k1_scalar_set_int (secp256k1_scalar *r, unsigned int v)
static void secp256k1_scalar_get_b32 (unsigned char *bin, const secp256k1_scalar *a)
static int secp256k1_scalar_add (secp256k1_scalar *r, const secp256k1_scalar *a, const secp256k1_scalar *b)
static void secp256k1_scalar_cadd_bit (secp256k1_scalar *r, unsigned int bit, int flag)
static void secp256k1_scalar_mul (secp256k1_scalar *r, const secp256k1_scalar *a, const secp256k1_scalar *b)
static int secp256k1_scalar_shr_int (secp256k1_scalar *r, int n)
static void secp256k1_scalar_inverse (secp256k1_scalar *r, const secp256k1_scalar *a)
static void secp256k1_scalar_inverse_var (secp256k1_scalar *r, const secp256k1_scalar *a)
static void secp256k1_scalar_negate (secp256k1_scalar *r, const secp256k1_scalar *a)
static int secp256k1_scalar_is_zero (const secp256k1_scalar *a)
static int secp256k1_scalar_is_one (const secp256k1_scalar *a)
static int secp256k1_scalar_is_even (const secp256k1_scalar *a)
static int secp256k1_scalar_is_high (const secp256k1_scalar *a)
static int secp256k1_scalar_cond_negate (secp256k1_scalar *a, int flag)
static int secp256k1_scalar_eq (const secp256k1_scalar *a, const secp256k1_scalar *b)
static void secp256k1_scalar_split_128 (secp256k1_scalar *r1, secp256k1_scalar *r2, const secp256k1_scalar *k)
static void secp256k1_scalar_split_lambda (secp256k1_scalar *r1, secp256k1_scalar *r2, const secp256k1_scalar *k)
static void secp256k1_scalar_mul_shift_var (secp256k1_scalar *r, const secp256k1_scalar *a, const secp256k1_scalar *b, unsigned int shift)
static void secp256k1_scalar_cmov (secp256k1_scalar *r, const secp256k1_scalar *a, int flag)
Function Documentation
secp256k1_scalar_add()
static int secp256k1_scalar_add (secp256k1_scalar * r, const secp256k1_scalar * a, const secp256k1_scalar * b) static
Add two scalars together (modulo the group order). Returns whether it overflowed.
Referenced by bench_ecmult_teardown_helper(), bench_ecmult_wnaf(), bench_scalar_add(), bench_scalar_inverse(), bench_scalar_inverse_var(), bench_scalar_split(), bench_wnaf_const(), main(), run_ecmult_chain(), run_ecmult_multi_bench(), run_endomorphism_tests(), run_scalar_tests(), run_wnaf(), scalar_test(), secp256k1_ecdsa_sig_sign(), secp256k1_eckey_privkey_tweak_add(), secp256k1_ecmult_gen(), secp256k1_scalar_split_lambda(), test_constant_wnaf(), test_ec_combine(), test_ecdsa_sign_verify(), test_ecmult_constants_2bit(), test_ecmult_multi(), test_ecmult_multi_random(), test_ecmult_target(), test_exhaustive_verify(), test_fixed_wnaf(), test_inverse_scalar(), test_scalar_split(), and test_wnaf().
secp256k1_scalar_cadd_bit()
static void secp256k1_scalar_cadd_bit (secp256k1_scalar * r, unsigned int bit, int flag) static
Conditionally add a power of two to a scalar. The result is not allowed to overflow.
Referenced by scalar_test(), and test_fixed_wnaf().
secp256k1_scalar_clear()
static void secp256k1_scalar_clear (secp256k1_scalar * r) static
Clear a scalar to prevent the leak of sensitive data.
Referenced by bench_ecmult_teardown_helper(), secp256k1_ec_pubkey_create(), secp256k1_ec_seckey_negate(), secp256k1_ec_seckey_tweak_add(), secp256k1_ec_seckey_tweak_add_helper(), secp256k1_ec_seckey_tweak_mul(), secp256k1_ec_seckey_verify(), secp256k1_ecdsa_sig_sign(), secp256k1_ecdsa_sign_inner(), secp256k1_ecmult_gen(), secp256k1_ecmult_gen_blind(), secp256k1_ecmult_gen_context_clear(), secp256k1_ecmult_pippenger_batch(), and test_ecmult_multi().
secp256k1_scalar_cmov()
static void secp256k1_scalar_cmov (secp256k1_scalar * r, const secp256k1_scalar * a, int flag) static
If flag is true, set *r equal to *a; otherwise leave it. Constant-time. Both *r and *a must be initialized.
Referenced by scalar_cmov_test(), secp256k1_ec_pubkey_create_helper(), secp256k1_ec_seckey_negate(), secp256k1_ec_seckey_tweak_add(), secp256k1_ec_seckey_tweak_mul(), secp256k1_ecdsa_sign_inner(), and secp256k1_ecmult_gen_blind().
secp256k1_scalar_cond_negate()
static int secp256k1_scalar_cond_negate (secp256k1_scalar * a, int flag) static
Conditionally negate a number, in constant time. Returns -1 if the number was negated, 1 otherwise
Referenced by run_wnaf(), secp256k1_ecdsa_sig_sign(), test_constant_wnaf_negate(), and test_ecmult_multi().
secp256k1_scalar_eq()
static int secp256k1_scalar_eq (const secp256k1_scalar * a, const secp256k1_scalar * b) static
Compare two scalars.
Referenced by run_inverse_tests(), run_scalar_set_b32_seckey_tests(), run_scalar_tests(), scalar_test(), secp256k1_ecdsa_sig_verify(), test_constant_wnaf(), test_constant_wnaf_negate(), test_ecdsa_edge_cases(), test_ecmult_gen_blind(), test_ecmult_gen_blind_reset(), test_exhaustive_verify(), test_fixed_wnaf(), test_scalar_split(), and test_wnaf().
secp256k1_scalar_get_b32()
static void secp256k1_scalar_get_b32 (unsigned char * bin, const secp256k1_scalar * a) static
Convert a scalar to a byte array.
Referenced by nonce_function_rfc6979(), random_scalar_order_b32(), scalar_test(), secp256k1_ec_seckey_negate(), secp256k1_ec_seckey_tweak_add(), secp256k1_ec_seckey_tweak_mul(), secp256k1_ecdsa_sig_serialize(), secp256k1_ecdsa_sig_verify(), secp256k1_ecdsa_signature_save(), secp256k1_ecdsa_signature_serialize_compact(), secp256k1_ecmult_gen_blind(), secp256k1_nonce_function_smallint(), test_ecdsa_end_to_end(), test_exhaustive_sign(), test_exhaustive_verify(), and test_scalar_split().
secp256k1_scalar_get_bits()
static unsigned int secp256k1_scalar_get_bits (const secp256k1_scalar * a, unsigned int offset, unsigned int count) static
Access bits from a scalar. All requested bits must belong to the same 32-bit limb.
Referenced by scalar_test(), secp256k1_ecmult_gen(), secp256k1_ecmult_wnaf(), and test_constant_wnaf_negate().
secp256k1_scalar_get_bits_var()
static unsigned int secp256k1_scalar_get_bits_var (const secp256k1_scalar * a, unsigned int offset, unsigned int count) static
Access bits from a scalar. Not constant time.
Referenced by scalar_test(), secp256k1_ecmult_wnaf(), and secp256k1_wnaf_fixed().
secp256k1_scalar_inverse()
static void secp256k1_scalar_inverse (secp256k1_scalar * r, const secp256k1_scalar * a) static
Compute the inverse of a scalar (modulo the group order).
Referenced by bench_scalar_inverse(), run_scalar_tests(), run_wnaf(), secp256k1_ecdsa_sig_sign(), test_ecdsa_edge_cases(), test_ecmult_multi_random(), and test_inverse_scalar().
secp256k1_scalar_inverse_var()
static void secp256k1_scalar_inverse_var (secp256k1_scalar * r, const secp256k1_scalar * a) static
Compute the inverse of a scalar (modulo the group order), without constant-time guarantee.
Referenced by bench_scalar_inverse_var(), run_scalar_tests(), secp256k1_ecdsa_sig_verify(), test_ecdsa_edge_cases(), test_ecmult_multi_random(), and test_inverse_scalar().
secp256k1_scalar_is_even()
static int secp256k1_scalar_is_even (const secp256k1_scalar * a) static
Check whether a scalar, considered as an nonnegative integer, is even.
Referenced by secp256k1_wnaf_fixed(), and test_constant_wnaf_negate().
secp256k1_scalar_is_high()
static int secp256k1_scalar_is_high (const secp256k1_scalar * a) static
Check whether a scalar is higher than the group order divided by 2.
Referenced by secp256k1_ecdsa_sig_sign(), secp256k1_ecdsa_signature_normalize(), secp256k1_ecdsa_verify(), secp256k1_ecmult_endo_split(), test_exhaustive_verify(), and test_scalar_split().
secp256k1_scalar_is_one()
static int secp256k1_scalar_is_one (const secp256k1_scalar * a) static
Check whether a scalar equals one.
Referenced by run_scalar_tests(), scalar_test(), and test_inverse_scalar().
secp256k1_scalar_is_zero()
static int secp256k1_scalar_is_zero (const secp256k1_scalar * a) static
Check whether a scalar equals zero.
Referenced by random_scalar_order(), random_scalar_order_test(), run_scalar_tests(), run_wnaf(), secp256k1_ecdsa_sig_sign(), secp256k1_ecdsa_sig_verify(), secp256k1_eckey_privkey_tweak_add(), secp256k1_eckey_privkey_tweak_mul(), secp256k1_eckey_pubkey_tweak_mul(), secp256k1_ecmult_gen_blind(), secp256k1_ecmult_pippenger_wnaf(), secp256k1_ecmult_strauss_wnaf(), secp256k1_scalar_set_b32_seckey(), secp256k1_wnaf_fixed(), and test_inverse_scalar().
secp256k1_scalar_mul()
static void secp256k1_scalar_mul (secp256k1_scalar * r, const secp256k1_scalar * a, const secp256k1_scalar * b) static
Multiply two scalars (modulo the group order).
Referenced by bench_ecmult_teardown_helper(), bench_scalar_mul(), run_ecmult_chain(), run_ecmult_multi_bench(), run_scalar_tests(), scalar_test(), secp256k1_ecdsa_sig_sign(), secp256k1_ecdsa_sig_verify(), secp256k1_eckey_privkey_tweak_mul(), secp256k1_scalar_split_lambda(), test_constant_wnaf(), test_ecmult_multi(), test_ecmult_multi_random(), test_exhaustive_verify(), test_fixed_wnaf(), test_inverse_scalar(), test_scalar_split(), and test_wnaf().
secp256k1_scalar_mul_shift_var()
static void secp256k1_scalar_mul_shift_var (secp256k1_scalar * r, const secp256k1_scalar * a, const secp256k1_scalar * b, unsigned int shift) static
Multiply a and b (without taking the modulus!), divide by 2**shift, and round to the nearest integer. Shift must be at least 256.
Referenced by secp256k1_scalar_split_lambda().
secp256k1_scalar_negate()
static void secp256k1_scalar_negate (secp256k1_scalar * r, const secp256k1_scalar * a) static
Compute the complement of a scalar (modulo the group order).
Referenced by bench_scalar_negate(), ecmult_const_mult_zero_one(), run_ecmult_multi_bench(), run_endomorphism_tests(), run_inverse_tests(), run_scalar_tests(), run_wnaf(), secp256k1_ec_seckey_negate(), secp256k1_ecdsa_signature_normalize(), secp256k1_ecmult_endo_split(), secp256k1_ecmult_gen_blind(), secp256k1_ecmult_wnaf(), secp256k1_scalar_split_lambda(), test_constant_wnaf(), test_constant_wnaf_negate(), test_ecdsa_edge_cases(), test_ecdsa_end_to_end(), test_ecmult_constants_2bit(), test_ecmult_constants_sha(), test_ecmult_multi(), test_ecmult_multi_random(), test_ecmult_target(), test_fixed_wnaf(), test_point_times_order(), test_scalar_split(), and test_wnaf().
secp256k1_scalar_set_b32()
static void secp256k1_scalar_set_b32 (secp256k1_scalar * r, const unsigned char * bin, int * overflow) static
Set a scalar from a big endian byte array. The scalar will be reduced modulo group order n. In: bin: pointer to a 32-byte array. Out: r: scalar to be set. overflow: non-zero if the scalar was bigger or equal to n before reduction, zero otherwise (can be NULL).
Referenced by bench_setup(), generate_scalar(), nonce_function_rfc6979(), r_from_k(), random_scalar_order(), random_scalar_order_test(), run_inverse_tests(), run_scalar_set_b32_seckey_tests(), run_scalar_tests(), secp256k1_der_parse_integer(), secp256k1_ec_pubkey_tweak_add_helper(), secp256k1_ec_pubkey_tweak_mul(), secp256k1_ec_seckey_tweak_add_helper(), secp256k1_ec_seckey_tweak_mul(), secp256k1_ecdsa_sig_sign(), secp256k1_ecdsa_sig_verify(), secp256k1_ecdsa_sign_inner(), secp256k1_ecdsa_signature_load(), secp256k1_ecdsa_signature_parse_compact(), secp256k1_ecdsa_verify(), secp256k1_ecmult_gen_blind(), secp256k1_scalar_set_b32_seckey(), test_ecdsa_edge_cases(), and test_ecmult_constants_sha().
secp256k1_scalar_set_b32_seckey()
static int secp256k1_scalar_set_b32_seckey (secp256k1_scalar * r, const unsigned char * bin) static
Set a scalar from a big endian byte array and returns 1 if it is a valid seckey and 0 otherwise.
Referenced by run_scalar_set_b32_seckey_tests(), secp256k1_ec_pubkey_create_helper(), secp256k1_ec_seckey_negate(), secp256k1_ec_seckey_tweak_add(), secp256k1_ec_seckey_tweak_mul(), secp256k1_ec_seckey_verify(), and secp256k1_ecdsa_sign_inner().
secp256k1_scalar_set_int()
static void secp256k1_scalar_set_int (secp256k1_scalar * r, unsigned int v) static
Set a scalar to an unsigned integer.
Referenced by bench_ecmult_0p_g(), main(), run_scalar_tests(), run_wnaf(), scalar_test(), secp256k1_der_parse_integer(), secp256k1_eckey_pubkey_tweak_add(), secp256k1_eckey_pubkey_tweak_mul(), secp256k1_ecmult_gen_blind(), secp256k1_ecmult_multi_simple_var(), secp256k1_ecmult_multi_var(), secp256k1_nonce_function_smallint(), test_constant_wnaf(), test_ecdsa_edge_cases(), test_ecdsa_sign_verify(), test_ecmult_constants_2bit(), test_ecmult_constants_sha(), test_ecmult_multi(), test_ecmult_multi_batch_single(), test_ecmult_multi_batching(), test_ecmult_multi_random(), test_exhaustive_ecmult(), test_exhaustive_ecmult_multi(), test_exhaustive_sign(), test_exhaustive_verify(), test_fixed_wnaf(), test_fixed_wnaf_small(), and test_wnaf().
secp256k1_scalar_shr_int()
static int secp256k1_scalar_shr_int (secp256k1_scalar * r, int n) static
Shift a scalar right by some amount strictly between 0 and 16, returning the low bits that were shifted off
Referenced by scalar_test(), test_constant_wnaf(), and test_fixed_wnaf().
secp256k1_scalar_split_128()
static void secp256k1_scalar_split_128 (secp256k1_scalar * r1, secp256k1_scalar * r2, const secp256k1_scalar * k) static
Find r1 and r2 such that r1+r2*2^128 = k.
Referenced by secp256k1_ecmult_strauss_wnaf().
secp256k1_scalar_split_lambda()
static void secp256k1_scalar_split_lambda (secp256k1_scalar * r1, secp256k1_scalar * r2, const secp256k1_scalar * k) static
Find r1 and r2 such that r1+r2*lambda = k, where r1 and r2 or their negations are maximum 128 bits long (see secp256k1_ge_mul_lambda).
Referenced by bench_scalar_split(), secp256k1_ecmult_endo_split(), secp256k1_ecmult_strauss_wnaf(), and test_scalar_split().