libdogecoin: src/secp256k1/src/scalar_impl.h File Reference
scalar_impl.h File Reference
#include "scalar.h"
#include "util.h"
#include "scalar_8x32_impl.h"
Functions
static int secp256k1_scalar_set_b32_seckey (secp256k1_scalar *r, const unsigned char *bin)
static void secp256k1_scalar_split_lambda (secp256k1_scalar *r1, secp256k1_scalar *r2, const secp256k1_scalar *k)
Variables
static const secp256k1_scalar secp256k1_scalar_one = SECP256K1_SCALAR_CONST(0, 0, 0, 0, 0, 0, 0, 1)
static const secp256k1_scalar secp256k1_scalar_zero = SECP256K1_SCALAR_CONST(0, 0, 0, 0, 0, 0, 0, 0)
static const secp256k1_scalar secp256k1_const_lambda
Function Documentation
secp256k1_scalar_set_b32_seckey()
static int secp256k1_scalar_set_b32_seckey (secp256k1_scalar * r, const unsigned char * bin) static
Definition at line 34 of file scalar_impl.h.
{
    int overflow;
    secp256k1_scalar_set_b32(r, bin, &overflow);
    return (!overflow) & (!secp256k1_scalar_is_zero(r));
}
References secp256k1_scalar_is_zero(), and secp256k1_scalar_set_b32().
secp256k1_scalar_split_lambda()
static void secp256k1_scalar_split_lambda (secp256k1_scalar * r1, secp256k1_scalar * r2, const secp256k1_scalar * k) static
Definition at line 123 of file scalar_impl.h.
{
    secp256k1_scalar c1, c2;
    static const secp256k1_scalar minus_b1 = SECP256K1_SCALAR_CONST(
        0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL,
        0xE4437ED6UL, 0x010E8828UL, 0x6F547FA9UL, 0x0ABFE4C3UL
    );
    static const secp256k1_scalar minus_b2 = SECP256K1_SCALAR_CONST(
        0xFFFFFFFFUL, 0xFFFFFFFFUL, 0xFFFFFFFFUL, 0xFFFFFFFEUL,
        0x8A280AC5UL, 0x0774346DUL, 0xD765CDA8UL, 0x3DB1562CUL
    );
    static const secp256k1_scalar g1 = SECP256K1_SCALAR_CONST(
        0x3086D221UL, 0xA7D46BCDUL, 0xE86C90E4UL, 0x9284EB15UL,
        0x3DAA8A14UL, 0x71E8CA7FUL, 0xE893209AUL, 0x45DBB031UL
    );
    static const secp256k1_scalar g2 = SECP256K1_SCALAR_CONST(
        0xE4437ED6UL, 0x010E8828UL, 0x6F547FA9UL, 0x0ABFE4C4UL,
        0x221208ACUL, 0x9DF506C6UL, 0x1571B4AEUL, 0x8AC47F71UL
    );
    VERIFY_CHECK(r1 != k);
    VERIFY_CHECK(r2 != k);
    /* these _var calls are constant time since the shift amount is constant */
    secp256k1_scalar_mul_shift_var(&c1, k, &g1, 384);
    secp256k1_scalar_mul_shift_var(&c2, k, &g2, 384);
    secp256k1_scalar_mul(&c1, &c1, &minus_b1);
    secp256k1_scalar_mul(&c2, &c2, &minus_b2);
    secp256k1_scalar_add(r2, &c1, &c2);
    secp256k1_scalar_mul(r1, r2, &secp256k1_const_lambda);
    secp256k1_scalar_negate(r1, r1);
    secp256k1_scalar_add(r1, r1, k);
#ifdef VERIFY
    secp256k1_scalar_split_lambda_verify(r1, r2, k);
#endif
}
References secp256k1_const_lambda, secp256k1_scalar_add(), SECP256K1_SCALAR_CONST, secp256k1_scalar_mul(), secp256k1_scalar_mul_shift_var(), secp256k1_scalar_negate(), and VERIFY_CHECK.
Variable Documentation
secp256k1_const_lambda
const secp256k1_scalar secp256k1_const_lambda static
Initial value:
= SECP256K1_SCALAR_CONST(
    0x5363AD4CUL, 0xC05C30E0UL, 0xA5261C02UL, 0x8812645AUL,
    0x122E22EAUL, 0x20816678UL, 0xDF02967CUL, 0x1B23BD72UL
)
The Secp256k1 curve has an endomorphism, where lambda * (x, y) = (beta * x, y), where lambda is:
Definition at line 64 of file scalar_impl.h.
Referenced by run_endomorphism_tests(), secp256k1_scalar_split_lambda(), and test_scalar_split().
secp256k1_scalar_one
const secp256k1_scalar secp256k1_scalar_one = SECP256K1_SCALAR_CONST(0, 0, 0, 0, 0, 0, 0, 1) static
Definition at line 31 of file scalar_impl.h.
Referenced by run_endomorphism_tests(), run_wnaf(), secp256k1_ec_pubkey_create_helper(), secp256k1_ecdsa_sign_inner(), secp256k1_ecmult_gen_blind(), and test_inverse_scalar().
secp256k1_scalar_zero
const secp256k1_scalar secp256k1_scalar_zero = SECP256K1_SCALAR_CONST(0, 0, 0, 0, 0, 0, 0, 0) static
Definition at line 32 of file scalar_impl.h.
Referenced by run_endomorphism_tests(), secp256k1_ec_seckey_negate(), secp256k1_ec_seckey_tweak_add(), secp256k1_ec_seckey_tweak_mul(), and secp256k1_ecdsa_sign_inner().