libdogecoin: src/secp256k1/src/scalar_low_impl.h File Reference
scalar_low_impl.h File Reference
#include "scalar.h"
#include <string.h>
Functions
static SECP256K1_INLINE int secp256k1_scalar_is_even (const secp256k1_scalar *a)
static SECP256K1_INLINE void secp256k1_scalar_clear (secp256k1_scalar *r)
static SECP256K1_INLINE void secp256k1_scalar_set_int (secp256k1_scalar *r, unsigned int v)
static SECP256K1_INLINE unsigned int secp256k1_scalar_get_bits (const secp256k1_scalar *a, unsigned int offset, unsigned int count)
static SECP256K1_INLINE unsigned int secp256k1_scalar_get_bits_var (const secp256k1_scalar *a, unsigned int offset, unsigned int count)
static SECP256K1_INLINE int secp256k1_scalar_check_overflow (const secp256k1_scalar *a)
static int secp256k1_scalar_add (secp256k1_scalar *r, const secp256k1_scalar *a, const secp256k1_scalar *b)
static void secp256k1_scalar_cadd_bit (secp256k1_scalar *r, unsigned int bit, int flag)
static void secp256k1_scalar_set_b32 (secp256k1_scalar *r, const unsigned char *b32, int *overflow)
static void secp256k1_scalar_get_b32 (unsigned char *bin, const secp256k1_scalar *a)
static SECP256K1_INLINE int secp256k1_scalar_is_zero (const secp256k1_scalar *a)
static void secp256k1_scalar_negate (secp256k1_scalar *r, const secp256k1_scalar *a)
static SECP256K1_INLINE int secp256k1_scalar_is_one (const secp256k1_scalar *a)
static int secp256k1_scalar_is_high (const secp256k1_scalar *a)
static int secp256k1_scalar_cond_negate (secp256k1_scalar *r, int flag)
static void secp256k1_scalar_mul (secp256k1_scalar *r, const secp256k1_scalar *a, const secp256k1_scalar *b)
static int secp256k1_scalar_shr_int (secp256k1_scalar *r, int n)
static void secp256k1_scalar_split_128 (secp256k1_scalar *r1, secp256k1_scalar *r2, const secp256k1_scalar *a)
static SECP256K1_INLINE int secp256k1_scalar_eq (const secp256k1_scalar *a, const secp256k1_scalar *b)
static SECP256K1_INLINE void secp256k1_scalar_cmov (secp256k1_scalar *r, const secp256k1_scalar *a, int flag)
static void secp256k1_scalar_inverse (secp256k1_scalar *r, const secp256k1_scalar *x)
static void secp256k1_scalar_inverse_var (secp256k1_scalar *r, const secp256k1_scalar *x)
Function Documentation
secp256k1_scalar_add()
static int secp256k1_scalar_add (secp256k1_scalar * r, const secp256k1_scalar * a, const secp256k1_scalar * b) static
Definition at line 34 of file scalar_low_impl.h.
{
    *r = (*a + *b) % EXHAUSTIVE_TEST_ORDER;
    return *r < *b;
}
References EXHAUSTIVE_TEST_ORDER.
secp256k1_scalar_cadd_bit()
static void secp256k1_scalar_cadd_bit (secp256k1_scalar * r, unsigned int bit, int flag) static
Definition at line 39 of file scalar_low_impl.h.
{
    if (flag && bit < 32)
        *r += ((uint32_t)1 << bit);
#ifdef VERIFY
    VERIFY_CHECK(bit < 32);
    /* Verify that adding (1 << bit) will not overflow any in-range scalar *r by overflowing the underlying uint32_t. */
    VERIFY_CHECK(((uint32_t)1 << bit) - 1 <= UINT32_MAX - EXHAUSTIVE_TEST_ORDER);
    VERIFY_CHECK(secp256k1_scalar_check_overflow(r) == 0);
#endif
}
References EXHAUSTIVE_TEST_ORDER, secp256k1_scalar_check_overflow(), and VERIFY_CHECK.
secp256k1_scalar_check_overflow()
static SECP256K1_INLINE int secp256k1_scalar_check_overflow (const secp256k1_scalar * a) static
Definition at line 32 of file scalar_low_impl.h.
{ return *a >= EXHAUSTIVE_TEST_ORDER; }
References EXHAUSTIVE_TEST_ORDER.
Referenced by secp256k1_scalar_cadd_bit().
secp256k1_scalar_clear()
static SECP256K1_INLINE void secp256k1_scalar_clear (secp256k1_scalar * r) static
Definition at line 18 of file scalar_low_impl.h.
{ *r = 0; }
secp256k1_scalar_cmov()
static SECP256K1_INLINE void secp256k1_scalar_cmov (secp256k1_scalar * r, const secp256k1_scalar * a, int flag) static
Definition at line 116 of file scalar_low_impl.h.
{
    uint32_t mask0, mask1;
    VG_CHECK_VERIFY(r, sizeof(*r));
    mask0 = flag + ~((uint32_t)0);
    mask1 = ~mask0;
    *r = (*r & mask0) | (*a & mask1);
}
References VG_CHECK_VERIFY.
secp256k1_scalar_cond_negate()
static int secp256k1_scalar_cond_negate (secp256k1_scalar * r, int flag) static
Definition at line 89 of file scalar_low_impl.h.
{
    if (flag) secp256k1_scalar_negate(r, r);
    return flag ? -1 : 1;
}
References secp256k1_scalar_negate().
secp256k1_scalar_eq()
static SECP256K1_INLINE int secp256k1_scalar_eq (const secp256k1_scalar * a, const secp256k1_scalar * b) static
Definition at line 112 of file scalar_low_impl.h.
{
    return *a == *b;
}
secp256k1_scalar_get_b32()
static void secp256k1_scalar_get_b32 (unsigned char * bin, const secp256k1_scalar * a) static
Definition at line 64 of file scalar_low_impl.h.
{
    memset(bin, 0, 32);
    bin[28] = *a >> 24; bin[29] = *a >> 16; bin[30] = *a >> 8; bin[31] = *a;
}
secp256k1_scalar_get_bits()
static SECP256K1_INLINE unsigned int secp256k1_scalar_get_bits (const secp256k1_scalar * a, unsigned int offset, unsigned int count) static
Definition at line 21 of file scalar_low_impl.h.
{
    if (offset < 32)
        return ((*a >> offset) & ((((uint32_t)1) << count) - 1));
    else
        return 0;
}
References count.
Referenced by secp256k1_scalar_get_bits_var().
secp256k1_scalar_get_bits_var()
static SECP256K1_INLINE unsigned int secp256k1_scalar_get_bits_var (const secp256k1_scalar * a, unsigned int offset, unsigned int count) static
Definition at line 28 of file scalar_low_impl.h.
{
    return secp256k1_scalar_get_bits(a, offset, count);
}
References count, and secp256k1_scalar_get_bits().
secp256k1_scalar_inverse()
static void secp256k1_scalar_inverse (secp256k1_scalar * r, const secp256k1_scalar * x) static
Definition at line 124 of file scalar_low_impl.h.
{
    int i;
    *r = 0;
    for (i = 0; i < EXHAUSTIVE_TEST_ORDER; i++)
        if ((i * *x) % EXHAUSTIVE_TEST_ORDER == 1)
            *r = i;
    /* If this VERIFY_CHECK triggers we were given a noninvertible scalar (and thus
     * have a composite group order; fix it in exhaustive_tests.c). */
    VERIFY_CHECK(*r != 0);
}
References EXHAUSTIVE_TEST_ORDER, and VERIFY_CHECK.
Referenced by secp256k1_scalar_inverse_var().
secp256k1_scalar_inverse_var()
static void secp256k1_scalar_inverse_var (secp256k1_scalar * r, const secp256k1_scalar * x) static
Definition at line 135 of file scalar_low_impl.h.
{
    secp256k1_scalar_inverse(r, x);
}
References secp256k1_scalar_inverse().
secp256k1_scalar_is_even()
static SECP256K1_INLINE int secp256k1_scalar_is_even (const secp256k1_scalar * a) static
Definition at line 14 of file scalar_low_impl.h.
{
    return !(*a & 1);
}
secp256k1_scalar_is_high()
static int secp256k1_scalar_is_high (const secp256k1_scalar * a) static
Definition at line 85 of file scalar_low_impl.h.
{
    return *a > EXHAUSTIVE_TEST_ORDER / 2;
}
References EXHAUSTIVE_TEST_ORDER.
secp256k1_scalar_is_one()
static SECP256K1_INLINE int secp256k1_scalar_is_one (const secp256k1_scalar * a) static
Definition at line 81 of file scalar_low_impl.h.
{
    return *a == 1;
}
secp256k1_scalar_is_zero()
static SECP256K1_INLINE int secp256k1_scalar_is_zero (const secp256k1_scalar * a) static
Definition at line 69 of file scalar_low_impl.h.
{
    return *a == 0;
}
secp256k1_scalar_mul()
static void secp256k1_scalar_mul (secp256k1_scalar * r, const secp256k1_scalar * a, const secp256k1_scalar * b) static
Definition at line 94 of file scalar_low_impl.h.
{
    *r = (*a * *b) % EXHAUSTIVE_TEST_ORDER;
}
References EXHAUSTIVE_TEST_ORDER.
secp256k1_scalar_negate()
static void secp256k1_scalar_negate (secp256k1_scalar * r, const secp256k1_scalar * a) static
Definition at line 73 of file scalar_low_impl.h.
{
    if (*a == 0) {
        *r = 0;
    } else {
        *r = EXHAUSTIVE_TEST_ORDER - *a;
    }
}
References EXHAUSTIVE_TEST_ORDER.
Referenced by secp256k1_scalar_cond_negate().
secp256k1_scalar_set_b32()
static void secp256k1_scalar_set_b32 (secp256k1_scalar * r, const unsigned char * b32, int * overflow) static
Definition at line 50 of file scalar_low_impl.h.
{
    int i;
    int over = 0;
    *r = 0;
    for (i = 0; i < 32; i++) {
        *r = (*r * 0x100) + b32[i];
        if (*r >= EXHAUSTIVE_TEST_ORDER) {
            over = 1;
            *r %= EXHAUSTIVE_TEST_ORDER;
        }
    }
    if (overflow) *overflow = over;
}
References EXHAUSTIVE_TEST_ORDER.
secp256k1_scalar_set_int()
static SECP256K1_INLINE void secp256k1_scalar_set_int (secp256k1_scalar * r, unsigned int v) static
Definition at line 19 of file scalar_low_impl.h.
{ *r = v; }
secp256k1_scalar_shr_int()
static int secp256k1_scalar_shr_int (secp256k1_scalar * r, int n) static
Definition at line 98 of file scalar_low_impl.h.
{
    int ret;
    VERIFY_CHECK(n > 0);
    VERIFY_CHECK(n < 16);
    ret = *r & ((1 << n) - 1);
    *r >>= n;
    return ret;
}
References VERIFY_CHECK.
secp256k1_scalar_split_128()
static void secp256k1_scalar_split_128 (secp256k1_scalar * r1, secp256k1_scalar * r2, const secp256k1_scalar * a) static
Definition at line 107 of file scalar_low_impl.h.
{
    *r1 = *a;
    *r2 = 0;
}