libdogecoin: src/secp256k1/src/scratch_impl.h File Reference
scratch_impl.h File Reference
#include "util.h"
#include "scratch.h"
Functions
static secp256k1_scratch * secp256k1_scratch_create (const secp256k1_callback *error_callback, size_t size)
static void secp256k1_scratch_destroy (const secp256k1_callback *error_callback, secp256k1_scratch *scratch)
static size_t secp256k1_scratch_checkpoint (const secp256k1_callback *error_callback, const secp256k1_scratch *scratch)
static void secp256k1_scratch_apply_checkpoint (const secp256k1_callback *error_callback, secp256k1_scratch *scratch, size_t checkpoint)
static size_t secp256k1_scratch_max_allocation (const secp256k1_callback *error_callback, const secp256k1_scratch *scratch, size_t objects)
static void * secp256k1_scratch_alloc (const secp256k1_callback *error_callback, secp256k1_scratch *scratch, size_t size)
Function Documentation
secp256k1_scratch_alloc()
static void * secp256k1_scratch_alloc (const secp256k1_callback * error_callback, secp256k1_scratch * scratch, size_t size) static
Definition at line 73 of file scratch_impl.h.
{
    void *ret;
    size_t rounded_size;
    rounded_size = ROUND_TO_ALIGN(size);
    /* Check that rounding did not wrap around */
    if (rounded_size < size) {
        return NULL;
    }
    size = rounded_size;
    if (secp256k1_memcmp_var(scratch->magic, "scratch", 8) != 0) {
        secp256k1_callback_call(error_callback, "invalid scratch space");
        return NULL;
    }
    if (size > scratch->max_size - scratch->alloc_size) {
        return NULL;
    }
    ret = (void *) ((char *) scratch->data + scratch->alloc_size);
    memset(ret, 0, size);
    scratch->alloc_size += size;
    return ret;
}
References secp256k1_scratch_space_struct::alloc_size, secp256k1_scratch_space_struct::data, secp256k1_scratch_space_struct::magic, secp256k1_scratch_space_struct::max_size, ROUND_TO_ALIGN, secp256k1_callback_call(), and secp256k1_memcmp_var().
secp256k1_scratch_apply_checkpoint()
static void secp256k1_scratch_apply_checkpoint (const secp256k1_callback * error_callback, secp256k1_scratch * scratch, size_t checkpoint) static
Definition at line 46 of file scratch_impl.h.
{
    if (secp256k1_memcmp_var(scratch->magic, "scratch", 8) != 0) {
        secp256k1_callback_call(error_callback, "invalid scratch space");
        return;
    }
    if (checkpoint > scratch->alloc_size) {
        secp256k1_callback_call(error_callback, "invalid checkpoint");
        return;
    }
    scratch->alloc_size = checkpoint;
}
References secp256k1_scratch_space_struct::alloc_size, secp256k1_scratch_space_struct::magic, secp256k1_callback_call(), and secp256k1_memcmp_var().
secp256k1_scratch_checkpoint()
static size_t secp256k1_scratch_checkpoint (const secp256k1_callback * error_callback, const secp256k1_scratch * scratch) static
Definition at line 38 of file scratch_impl.h.
{
    if (secp256k1_memcmp_var(scratch->magic, "scratch", 8) != 0) {
        secp256k1_callback_call(error_callback, "invalid scratch space");
        return 0;
    }
    return scratch->alloc_size;
}
References secp256k1_scratch_space_struct::alloc_size, secp256k1_scratch_space_struct::magic, secp256k1_callback_call(), and secp256k1_memcmp_var().
secp256k1_scratch_create()
static secp256k1_scratch * secp256k1_scratch_create (const secp256k1_callback * error_callback, size_t size) static
Definition at line 13 of file scratch_impl.h.
{
    const size_t base_alloc = ROUND_TO_ALIGN(sizeof(secp256k1_scratch));
    void *alloc = checked_malloc(error_callback, base_alloc + size);
    secp256k1_scratch* ret = (secp256k1_scratch *)alloc;
    if (ret != NULL) {
        memset(ret, 0, sizeof(*ret));
        memcpy(ret->magic, "scratch", 8);
        ret->data = (void *) ((char *) alloc + base_alloc);
        ret->max_size = size;
    }
    return ret;
}
References checked_malloc(), secp256k1_scratch_space_struct::data, secp256k1_scratch_space_struct::magic, secp256k1_scratch_space_struct::max_size, and ROUND_TO_ALIGN.
secp256k1_scratch_destroy()
static void secp256k1_scratch_destroy (const secp256k1_callback * error_callback, secp256k1_scratch * scratch) static
Definition at line 26 of file scratch_impl.h.
{
    if (scratch != NULL) {
        VERIFY_CHECK(scratch->alloc_size == 0); /* all checkpoints should be applied */
        if (secp256k1_memcmp_var(scratch->magic, "scratch", 8) != 0) {
            secp256k1_callback_call(error_callback, "invalid scratch space");
            return;
        }
        memset(scratch->magic, 0, sizeof(scratch->magic));
        free(scratch);
    }
}
References secp256k1_scratch_space_struct::alloc_size, secp256k1_scratch_space_struct::magic, secp256k1_callback_call(), secp256k1_memcmp_var(), and VERIFY_CHECK.
secp256k1_scratch_max_allocation()
static size_t secp256k1_scratch_max_allocation (const secp256k1_callback * error_callback, const secp256k1_scratch * scratch, size_t objects) static
Definition at line 58 of file scratch_impl.h.
{
    if (secp256k1_memcmp_var(scratch->magic, "scratch", 8) != 0) {
        secp256k1_callback_call(error_callback, "invalid scratch space");
        return 0;
    }
    /* Ensure that multiplication will not wrap around */
    if (ALIGNMENT > 1 && objects > SIZE_MAX/(ALIGNMENT - 1)) {
        return 0;
    }
    if (scratch->max_size - scratch->alloc_size <= objects * (ALIGNMENT - 1)) {
        return 0;
    }
    return scratch->max_size - scratch->alloc_size - objects * (ALIGNMENT - 1);
}
References ALIGNMENT, secp256k1_scratch_space_struct::alloc_size, secp256k1_scratch_space_struct::magic, secp256k1_scratch_space_struct::max_size, secp256k1_callback_call(), and secp256k1_memcmp_var().