libdogecoin: include/dogecoin/script.h File Reference
script.h File Reference
#include <dogecoin/cstr.h>
#include <dogecoin/dogecoin.h>
#include <dogecoin/key.h>
#include <dogecoin/vector.h>
Data Structures
struct dogecoin_script_op_
Typedefs
typedef struct dogecoin_script_op_ dogecoin_script_op
Enumerations
enum dogecoin_sig_version { SIGVERSION_BASE = 0 }
enum { SIGHASH_ALL = 1 , SIGHASH_NONE = 2 , SIGHASH_SINGLE = 3 , SIGHASH_ANYONECANPAY = 0x80 }
enum opcodetype {
OP_0 = 0x00 , OP_FALSE = OP_0 , OP_PUSHDATA1 = 0x4c , OP_PUSHDATA2 = 0x4d ,
OP_PUSHDATA4 = 0x4e , OP_1NEGATE = 0x4f , OP_RESERVED = 0x50 , OP_1 = 0x51 ,
OP_TRUE = OP_1 , OP_2 = 0x52 , OP_3 = 0x53 , OP_4 = 0x54 ,
OP_5 = 0x55 , OP_6 = 0x56 , OP_7 = 0x57 , OP_8 = 0x58 ,
OP_9 = 0x59 , OP_10 = 0x5a , OP_11 = 0x5b , OP_12 = 0x5c ,
OP_13 = 0x5d , OP_14 = 0x5e , OP_15 = 0x5f , OP_16 = 0x60 ,
OP_NOP = 0x61 , OP_VER = 0x62 , OP_IF = 0x63 , OP_NOTIF = 0x64 ,
OP_VERIF = 0x65 , OP_VERNOTIF = 0x66 , OP_ELSE = 0x67 , OP_ENDIF = 0x68 ,
OP_VERIFY = 0x69 , OP_RETURN = 0x6a , OP_TOALTSTACK = 0x6b , OP_FROMALTSTACK = 0x6c ,
OP_2DROP = 0x6d , OP_2DUP = 0x6e , OP_3DUP = 0x6f , OP_2OVER = 0x70 ,
OP_2ROT = 0x71 , OP_2SWAP = 0x72 , OP_IFDUP = 0x73 , OP_DEPTH = 0x74 ,
OP_DROP = 0x75 , OP_DUP = 0x76 , OP_NIP = 0x77 , OP_OVER = 0x78 ,
OP_PICK = 0x79 , OP_ROLL = 0x7a , OP_ROT = 0x7b , OP_SWAP = 0x7c ,
OP_TUCK = 0x7d , OP_CAT = 0x7e , OP_SUBSTR = 0x7f , OP_LEFT = 0x80 ,
OP_RIGHT = 0x81 , OP_SIZE = 0x82 , OP_INVERT = 0x83 , OP_AND = 0x84 ,
OP_OR = 0x85 , OP_XOR = 0x86 , OP_EQUAL = 0x87 , OP_EQUALVERIFY = 0x88 ,
OP_RESERVED1 = 0x89 , OP_RESERVED2 = 0x8a , OP_1ADD = 0x8b , OP_1SUB = 0x8c ,
OP_2MUL = 0x8d , OP_2DIV = 0x8e , OP_NEGATE = 0x8f , OP_ABS = 0x90 ,
OP_NOT = 0x91 , OP_0NOTEQUAL = 0x92 , OP_ADD = 0x93 , OP_SUB = 0x94 ,
OP_MUL = 0x95 , OP_DIV = 0x96 , OP_MOD = 0x97 , OP_LSHIFT = 0x98 ,
OP_RSHIFT = 0x99 , OP_BOOLAND = 0x9a , OP_BOOLOR = 0x9b , OP_NUMEQUAL = 0x9c ,
OP_NUMEQUALVERIFY = 0x9d , OP_NUMNOTEQUAL = 0x9e , OP_LESSTHAN = 0x9f , OP_GREATERTHAN = 0xa0 ,
OP_LESSTHANOREQUAL = 0xa1 , OP_GREATERTHANOREQUAL = 0xa2 , OP_MIN = 0xa3 , OP_MAX = 0xa4 ,
OP_WITHIN = 0xa5 , OP_RIPEMD160 = 0xa6 , OP_SHA1 = 0xa7 , OP_SHA256 = 0xa8 ,
OP_HASH160 = 0xa9 , OP_HASH256 = 0xaa , OP_CODESEPARATOR = 0xab , OP_CHECKSIG = 0xac ,
OP_CHECKSIGVERIFY = 0xad , OP_CHECKMULTISIG = 0xae , OP_CHECKMULTISIGVERIFY = 0xaf , OP_NOP1 = 0xb0 ,
OP_NOP2 = 0xb1 , OP_CHECKLOCKTIMEVERIFY = OP_NOP2 , OP_NOP3 = 0xb2 , OP_NOP4 = 0xb3 ,
OP_NOP5 = 0xb4 , OP_NOP6 = 0xb5 , OP_NOP7 = 0xb6 , OP_NOP8 = 0xb7 ,
OP_NOP9 = 0xb8 , OP_NOP10 = 0xb9 , OP_SMALLINTEGER = 0xfa , OP_PUBKEYS = 0xfb ,
OP_PUBKEYHASH = 0xfd , OP_PUBKEY = 0xfe , OP_INVALIDOPCODE = 0xff
}
enum dogecoin_tx_out_type {
DOGECOIN_TX_INVALID = -1 , DOGECOIN_TX_NONSTANDARD , DOGECOIN_TX_PUBKEY , DOGECOIN_TX_PUBKEYHASH ,
DOGECOIN_TX_SCRIPTHASH , DOGECOIN_TX_MULTISIG
}
Functions
dogecoin_bool dogecoin_script_copy_without_op_codeseperator (const cstring *scriptin, cstring *scriptout)
This function copies a script without the OP_CODESEPARATOR opcode.
LIBDOGECOIN_API dogecoin_script_op * dogecoin_script_op_new ()
This function allocates the memory for a new dogecoin_script_op object.
LIBDOGECOIN_API void dogecoin_script_op_free (dogecoin_script_op *script_op)
This function frees the pointer to a dogecoin_script_op object and sets the pointer to NULL.
void dogecoin_script_op_free_cb (void *data)
This function casts data from a channel buffer to a dogecoin_script_op object and then frees it by calling dogecoin_script_op_free().
dogecoin_bool dogecoin_script_get_ops (const cstring *script_in, vector *ops_out)
This function converts a cstring script into a vector of dogecoin_script_op objects.
LIBDOGECOIN_API enum dogecoin_tx_out_type dogecoin_script_classify_ops (const vector *ops)
This function classifies a script as one of four types: pubkey, pubkey hash, script hash, or multisig.
LIBDOGECOIN_API enum dogecoin_tx_out_type dogecoin_script_classify (const cstring *script, vector *data_out)
This function takes a cstring representation of a script, classifies it as one of the four script types and loads the script data into data_out if it is not a multisig script.
LIBDOGECOIN_API enum opcodetype dogecoin_encode_op_n (const int n)
This function takes an int and translates it to a small int opcode if it is between 0 and 16, inclusive.
LIBDOGECOIN_API void dogecoin_script_append_op (cstring *script_in, enum opcodetype op)
This function takes an existing script in cstring form and appends another script operation to it. No data is pushed to the stack.
LIBDOGECOIN_API void dogecoin_script_append_pushdata (cstring *script_in, const unsigned char *data, const size_t datalen)
This function takes an existing script in cstring form and appends an operation to push a specified buffer of data to the stack.
LIBDOGECOIN_API dogecoin_bool dogecoin_script_build_multisig (cstring *script_in, const unsigned int required_signatures, const vector *pubkeys_chars)
This function takes a vector of dogecoin_pubkeys and builds a multisig script which pushes all pubkeys to the stack and checks that each one is valid.
LIBDOGECOIN_API dogecoin_bool dogecoin_script_build_p2pkh (cstring *script, const uint160 hash160)
This function builds a pay-to-public-key-hash script which duplicates the value at the top of the stack (a public key), hashes this value, checks that this hash equals the given uint160 object, and verifies the signature. This script is then loaded into the cstring script_in.
LIBDOGECOIN_API dogecoin_bool dogecoin_script_build_p2sh (cstring *script_in, const uint160 hash160)
This function builds a pay-to-script-hash script which hashes the value on the top of the stack (script data) and ensures that this equals the uint160 object given. The script is then loaded into the cstring script_in.
LIBDOGECOIN_API dogecoin_bool dogecoin_script_get_scripthash (const cstring *script_in, uint160 scripthash)
This function takes a script, computes its hash, and returns it as a uint160 object.
LIBDOGECOIN_API const char * dogecoin_tx_out_type_to_str (const enum dogecoin_tx_out_type type)
This function takes a script type and translates it into string format.
Variables
static const int MAX_SCRIPT_SIZE = 10000
Typedef Documentation
dogecoin_script_op
typedef struct dogecoin_script_op_ dogecoin_script_op
Enumeration Type Documentation
anonymous enum
anonymous enum
Signature hash types/flags
Enumerator
SIGHASH_ALL
SIGHASH_NONE
SIGHASH_SINGLE
SIGHASH_ANYONECANPAY
Definition at line 46 of file script.h.
     {
    SIGHASH_ALL = 1,
    SIGHASH_NONE = 2,
    SIGHASH_SINGLE = 3,
    SIGHASH_ANYONECANPAY = 0x80,
};
dogecoin_sig_version
enum dogecoin_sig_version
Sighash version types
Enumerator
SIGVERSION_BASE
Definition at line 41 of file script.h.
{
    SIGVERSION_BASE = 0,
};
dogecoin_tx_out_type
enum dogecoin_tx_out_type
Enumerator
DOGECOIN_TX_INVALID
DOGECOIN_TX_NONSTANDARD
DOGECOIN_TX_PUBKEY
DOGECOIN_TX_PUBKEYHASH
DOGECOIN_TX_SCRIPTHASH
DOGECOIN_TX_MULTISIG
Definition at line 197 of file script.h.
{
    DOGECOIN_TX_INVALID = -1,
    DOGECOIN_TX_NONSTANDARD,
    // 'standard' transaction types:
    DOGECOIN_TX_PUBKEY,
    DOGECOIN_TX_PUBKEYHASH,
    DOGECOIN_TX_SCRIPTHASH,
    DOGECOIN_TX_MULTISIG,
};
opcodetype
enum opcodetype
Script opcodes
Enumerator
OP_0
OP_FALSE
OP_PUSHDATA1
OP_PUSHDATA2
OP_PUSHDATA4
OP_1NEGATE
OP_RESERVED
OP_1
OP_TRUE
OP_2
OP_3
OP_4
OP_5
OP_6
OP_7
OP_8
OP_9
OP_10
OP_11
OP_12
OP_13
OP_14
OP_15
OP_16
OP_NOP
OP_VER
OP_IF
OP_NOTIF
OP_VERIF
OP_VERNOTIF
OP_ELSE
OP_ENDIF
OP_VERIFY
OP_RETURN
OP_TOALTSTACK
OP_FROMALTSTACK
OP_2DROP
OP_2DUP
OP_3DUP
OP_2OVER
OP_2ROT
OP_2SWAP
OP_IFDUP
OP_DEPTH
OP_DROP
OP_DUP
OP_NIP
OP_OVER
OP_PICK
OP_ROLL
OP_ROT
OP_SWAP
OP_TUCK
OP_CAT
OP_SUBSTR
OP_LEFT
OP_RIGHT
OP_SIZE
OP_INVERT
OP_AND
OP_OR
OP_XOR
OP_EQUAL
OP_EQUALVERIFY
OP_RESERVED1
OP_RESERVED2
OP_1ADD
OP_1SUB
OP_2MUL
OP_2DIV
OP_NEGATE
OP_ABS
OP_NOT
OP_0NOTEQUAL
OP_ADD
OP_SUB
OP_MUL
OP_DIV
OP_MOD
OP_LSHIFT
OP_RSHIFT
OP_BOOLAND
OP_BOOLOR
OP_NUMEQUAL
OP_NUMEQUALVERIFY
OP_NUMNOTEQUAL
OP_LESSTHAN
OP_GREATERTHAN
OP_LESSTHANOREQUAL
OP_GREATERTHANOREQUAL
OP_MIN
OP_MAX
OP_WITHIN
OP_RIPEMD160
OP_SHA1
OP_SHA256
OP_HASH160
OP_HASH256
OP_CODESEPARATOR
OP_CHECKSIG
OP_CHECKSIGVERIFY
OP_CHECKMULTISIG
OP_CHECKMULTISIGVERIFY
OP_NOP1
OP_NOP2
OP_CHECKLOCKTIMEVERIFY
OP_NOP3
OP_NOP4
OP_NOP5
OP_NOP6
OP_NOP7
OP_NOP8
OP_NOP9
OP_NOP10
OP_SMALLINTEGER
OP_PUBKEYS
OP_PUBKEYHASH
OP_PUBKEY
OP_INVALIDOPCODE
Definition at line 54 of file script.h.
                {
    // push value
    OP_0 = 0x00,
    OP_FALSE = OP_0,
    OP_PUSHDATA1 = 0x4c,
    OP_PUSHDATA2 = 0x4d,
    OP_PUSHDATA4 = 0x4e,
    OP_1NEGATE = 0x4f,
    OP_RESERVED = 0x50,
    OP_1 = 0x51,
    OP_TRUE = OP_1,
    OP_2 = 0x52,
    OP_3 = 0x53,
    OP_4 = 0x54,
    OP_5 = 0x55,
    OP_6 = 0x56,
    OP_7 = 0x57,
    OP_8 = 0x58,
    OP_9 = 0x59,
    OP_10 = 0x5a,
    OP_11 = 0x5b,
    OP_12 = 0x5c,
    OP_13 = 0x5d,
    OP_14 = 0x5e,
    OP_15 = 0x5f,
    OP_16 = 0x60,
    // control
    OP_NOP = 0x61,
    OP_VER = 0x62,
    OP_IF = 0x63,
    OP_NOTIF = 0x64,
    OP_VERIF = 0x65,
    OP_VERNOTIF = 0x66,
    OP_ELSE = 0x67,
    OP_ENDIF = 0x68,
    OP_VERIFY = 0x69,
    OP_RETURN = 0x6a,
    // stack ops
    OP_TOALTSTACK = 0x6b,
    OP_FROMALTSTACK = 0x6c,
    OP_2DROP = 0x6d,
    OP_2DUP = 0x6e,
    OP_3DUP = 0x6f,
    OP_2OVER = 0x70,
    OP_2ROT = 0x71,
    OP_2SWAP = 0x72,
    OP_IFDUP = 0x73,
    OP_DEPTH = 0x74,
    OP_DROP = 0x75,
    OP_DUP = 0x76,
    OP_NIP = 0x77,
    OP_OVER = 0x78,
    OP_PICK = 0x79,
    OP_ROLL = 0x7a,
    OP_ROT = 0x7b,
    OP_SWAP = 0x7c,
    OP_TUCK = 0x7d,
    // splice ops
    OP_CAT = 0x7e,
    OP_SUBSTR = 0x7f,
    OP_LEFT = 0x80,
    OP_RIGHT = 0x81,
    OP_SIZE = 0x82,
    // bit logic
    OP_INVERT = 0x83,
    OP_AND = 0x84,
    OP_OR = 0x85,
    OP_XOR = 0x86,
    OP_EQUAL = 0x87,
    OP_EQUALVERIFY = 0x88,
    OP_RESERVED1 = 0x89,
    OP_RESERVED2 = 0x8a,
    // numeric
    OP_1ADD = 0x8b,
    OP_1SUB = 0x8c,
    OP_2MUL = 0x8d,
    OP_2DIV = 0x8e,
    OP_NEGATE = 0x8f,
    OP_ABS = 0x90,
    OP_NOT = 0x91,
    OP_0NOTEQUAL = 0x92,
    OP_ADD = 0x93,
    OP_SUB = 0x94,
    OP_MUL = 0x95,
    OP_DIV = 0x96,
    OP_MOD = 0x97,
    OP_LSHIFT = 0x98,
    OP_RSHIFT = 0x99,
    OP_BOOLAND = 0x9a,
    OP_BOOLOR = 0x9b,
    OP_NUMEQUAL = 0x9c,
    OP_NUMEQUALVERIFY = 0x9d,
    OP_NUMNOTEQUAL = 0x9e,
    OP_LESSTHAN = 0x9f,
    OP_GREATERTHAN = 0xa0,
    OP_LESSTHANOREQUAL = 0xa1,
    OP_GREATERTHANOREQUAL = 0xa2,
    OP_MIN = 0xa3,
    OP_MAX = 0xa4,
    OP_WITHIN = 0xa5,
    // crypto
    OP_RIPEMD160 = 0xa6,
    OP_SHA1 = 0xa7,
    OP_SHA256 = 0xa8,
    OP_HASH160 = 0xa9,
    OP_HASH256 = 0xaa,
    OP_CODESEPARATOR = 0xab,
    OP_CHECKSIG = 0xac,
    OP_CHECKSIGVERIFY = 0xad,
    OP_CHECKMULTISIG = 0xae,
    OP_CHECKMULTISIGVERIFY = 0xaf,
    // expansion
    OP_NOP1 = 0xb0,
    OP_NOP2 = 0xb1,
    OP_CHECKLOCKTIMEVERIFY = OP_NOP2,
    OP_NOP3 = 0xb2,
    OP_NOP4 = 0xb3,
    OP_NOP5 = 0xb4,
    OP_NOP6 = 0xb5,
    OP_NOP7 = 0xb6,
    OP_NOP8 = 0xb7,
    OP_NOP9 = 0xb8,
    OP_NOP10 = 0xb9,
    // template matching params
    OP_SMALLINTEGER = 0xfa,
    OP_PUBKEYS = 0xfb,
    OP_PUBKEYHASH = 0xfd,
    OP_PUBKEY = 0xfe,
    OP_INVALIDOPCODE = 0xff,
};
Function Documentation
dogecoin_encode_op_n()
LIBDOGECOIN_API enum opcodetype dogecoin_encode_op_n (const int n)
This function takes an int and translates it to a small int opcode if it is between 0 and 16, inclusive.
Parameters
n The number of the desired small int opcode.
Returns
The small int opcode.
Definition at line 508 of file script.c.
{
    assert(n >= 0 && n <= 16);
    if (n == 0)
        return OP_0;
    return (enum opcodetype)(OP_1 + n - 1);
}
References OP_0, and OP_1.
Referenced by dogecoin_script_build_multisig().
dogecoin_script_append_op()
LIBDOGECOIN_API void dogecoin_script_append_op (cstring * script_in, enum opcodetype op)
This function takes an existing script in cstring form and appends another script operation to it. No data is pushed to the stack.
Parameters
script_in The pointer to the cstring containing the script.
op The opcode to append.
Returns
Nothing.
Definition at line 527 of file script.c.
{
    cstr_append_buf(script_in, &op, 1);
}
References cstr_append_buf().
Referenced by dogecoin_script_append_pushdata(), dogecoin_script_build_p2pkh(), dogecoin_script_build_p2sh(), dogecoin_tx_add_data_out(), and dogecoin_tx_add_puzzle_out().
dogecoin_script_append_pushdata()
LIBDOGECOIN_API void dogecoin_script_append_pushdata (cstring * script_in, const unsigned char * data, const size_t datalen)
This function takes an existing script in cstring form and appends an operation to push a specified buffer of data to the stack.
Parameters
script_in The pointer to the cstring containing the script.
data The buffer to be pushed in the push operation.
datalen The size in bytes of the buffer.
Returns
Nothing.
Definition at line 544 of file script.c.
{
    if (datalen < OP_PUSHDATA1) {
        cstr_append_buf(script_in, (unsigned char*)&datalen, 1);
    } else if (datalen <= 0xff) {
        dogecoin_script_append_op(script_in, OP_PUSHDATA1);
        cstr_append_buf(script_in, (unsigned char*)&datalen, 1);
    } else if (datalen <= 0xffff) {
        dogecoin_script_append_op(script_in, OP_PUSHDATA2);
        uint16_t v = htole16((uint16_t)datalen);
        cstr_append_buf(script_in, &v, sizeof(v));
    } else {
        dogecoin_script_append_op(script_in, OP_PUSHDATA4);
        uint32_t v = htole32((uint32_t)datalen);
        cstr_append_buf(script_in, &v, sizeof(v));
    }
    cstr_append_buf(script_in, data, datalen);
}
References cstr_append_buf(), dogecoin_script_append_op(), OP_PUSHDATA1, OP_PUSHDATA2, and OP_PUSHDATA4.
Referenced by dogecoin_script_build_multisig(), dogecoin_script_build_p2pkh(), dogecoin_script_build_p2sh(), dogecoin_tx_add_data_out(), and dogecoin_tx_add_puzzle_out().
dogecoin_script_build_multisig()
LIBDOGECOIN_API dogecoin_bool dogecoin_script_build_multisig (cstring * script_in, const unsigned int required_signatures, const vector * pubkeys_chars)
This function takes a vector of dogecoin_pubkeys and builds a multisig script which pushes all pubkeys to the stack and checks that each one is valid.
Parameters
script_in The pointer to the cstring where the new multisig script will be built.
required_signatures The number of required signatures.
pubkeys_chars The pointer to the vector of pubkey push operations to combine into the multisig.
Returns
1 if the script was built successfully, 0 if more than 16 pubkeys are given.
Definition at line 574 of file script.c.
{
    cstr_resize(script_in, 0); //clear script
    if (required_signatures > 16 || pubkeys_chars->len > 16)
        return false;
    enum opcodetype op_req_sig = dogecoin_encode_op_n(required_signatures);
    cstr_append_buf(script_in, &op_req_sig, 1);
    int i;
    for (i = 0; i < (int)pubkeys_chars->len; i++) {
        dogecoin_pubkey* pkey = pubkeys_chars->data[i];
        dogecoin_script_append_pushdata(script_in, pkey->pubkey, (pkey->compressed ? DOGECOIN_ECKEY_COMPRESSED_LENGTH : DOGECOIN_ECKEY_UNCOMPRESSED_LENGTH));
    }
    enum opcodetype op_pub_len = dogecoin_encode_op_n(pubkeys_chars->len);
    cstr_append_buf(script_in, &op_pub_len, 1);
    enum opcodetype op_checkmultisig = OP_CHECKMULTISIG;
    cstr_append_buf(script_in, &op_checkmultisig, 1);
    return true;
}
References dogecoin_pubkey_::compressed, cstr_append_buf(), cstr_resize(), vector::data, DOGECOIN_ECKEY_COMPRESSED_LENGTH, DOGECOIN_ECKEY_UNCOMPRESSED_LENGTH, dogecoin_encode_op_n(), dogecoin_script_append_pushdata(), vector::len, OP_CHECKMULTISIG, and dogecoin_pubkey_::pubkey.
dogecoin_script_build_p2pkh()
LIBDOGECOIN_API dogecoin_bool dogecoin_script_build_p2pkh (cstring * script_in, const uint160 hash160)
This function builds a pay-to-public-key-hash script which duplicates the value at the top of the stack (a public key), hashes this value, checks that this hash equals the given uint160 object, and verifies the signature. This script is then loaded into the cstring script_in.
Parameters
script_in The pointer to the cstring where the p2pkh script will be built.
hash160 The hash160 of a public key.
Returns
1 if the p2pkh script was built successfully.
Definition at line 611 of file script.c.
{
    cstr_resize(script_in, 0); //clear script
    dogecoin_script_append_op(script_in, OP_DUP);
    dogecoin_script_append_op(script_in, OP_HASH160);
    dogecoin_script_append_pushdata(script_in, (unsigned char*)hash160, sizeof(uint160));
    dogecoin_script_append_op(script_in, OP_EQUALVERIFY);
    dogecoin_script_append_op(script_in, OP_CHECKSIG);
    return true;
}
References cstr_resize(), dogecoin_script_append_op(), dogecoin_script_append_pushdata(), OP_CHECKSIG, OP_DUP, OP_EQUALVERIFY, and OP_HASH160.
Referenced by dogecoin_tx_add_p2pkh_hash160_out().
dogecoin_script_build_p2sh()
LIBDOGECOIN_API dogecoin_bool dogecoin_script_build_p2sh (cstring * script_in, const uint160 hash160)
This function builds a pay-to-script-hash script which hashes the value on the top of the stack (script data) and ensures that this equals the uint160 object given. The script is then loaded into the cstring script_in.
Parameters
script_in The pointer to the cstring where the p2sh script will be built.
hash160 The hash160 of a public key.
Returns
1 if the p2sh script was built successfully.
Definition at line 638 of file script.c.
{
    cstr_resize(script_in, 0); //clear script
    dogecoin_script_append_op(script_in, OP_HASH160);
    dogecoin_script_append_pushdata(script_in, (unsigned char*)hash160, sizeof(uint160));
    dogecoin_script_append_op(script_in, OP_EQUAL);
    return true;
}
References cstr_resize(), dogecoin_script_append_op(), dogecoin_script_append_pushdata(), OP_EQUAL, and OP_HASH160.
Referenced by dogecoin_tx_add_p2sh_hash160_out().
dogecoin_script_classify()
LIBDOGECOIN_API enum dogecoin_tx_out_type dogecoin_script_classify (const cstring * script, vector * data_out)
This function takes a cstring representation of a script, classifies it as one of the four script types and loads the script data into data_out if it is not a multisig script.
Parameters
script The pointer to the cstring script to be parsed and classified.
data_out The pointer to the vector that will contain the parsed scripts.
Returns
The script type.
Definition at line 477 of file script.c.
{
    //INFO: could be speed up by not forming a vector
    //      and directly parse the script cstring
    enum dogecoin_tx_out_type tx_out_type = DOGECOIN_TX_NONSTANDARD;
    vector* ops = vector_new(10, dogecoin_script_op_free_cb);
    dogecoin_script_get_ops(script, ops);
    if (dogecoin_script_is_pubkeyhash(ops, data_out))
        tx_out_type = DOGECOIN_TX_PUBKEYHASH;
    if (dogecoin_script_is_scripthash(ops, data_out))
        tx_out_type = DOGECOIN_TX_SCRIPTHASH;
    if (dogecoin_script_is_pubkey(ops, data_out))
        tx_out_type = DOGECOIN_TX_PUBKEY;
    if (dogecoin_script_is_multisig(ops))
        tx_out_type = DOGECOIN_TX_MULTISIG;
    vector_free(ops, true);
    return tx_out_type;
}
References dogecoin_script_get_ops(), dogecoin_script_is_multisig(), dogecoin_script_is_pubkey(), dogecoin_script_is_pubkeyhash(), dogecoin_script_is_scripthash(), dogecoin_script_op_free_cb(), DOGECOIN_TX_MULTISIG, DOGECOIN_TX_NONSTANDARD, DOGECOIN_TX_PUBKEY, DOGECOIN_TX_PUBKEYHASH, DOGECOIN_TX_SCRIPTHASH, vector_free(), and vector_new().
Referenced by dogecoin_tx_sign_input(), main(), and sign_raw_transaction().
dogecoin_script_classify_ops()
LIBDOGECOIN_API enum dogecoin_tx_out_type dogecoin_script_classify_ops (const vector * ops)
This function classifies a script as one of four types: pubkey, pubkey hash, script hash, or multisig.
Parameters
ops The pointer to the vector storing the script.
Returns
The type of script.
Definition at line 451 of file script.c.
{
    if (dogecoin_script_is_pubkeyhash(ops, NULL))
        return DOGECOIN_TX_PUBKEYHASH;
    if (dogecoin_script_is_scripthash(ops, NULL))
        return DOGECOIN_TX_SCRIPTHASH;
    if (dogecoin_script_is_pubkey(ops, NULL))
        return DOGECOIN_TX_PUBKEY;
    if (dogecoin_script_is_multisig(ops))
        return DOGECOIN_TX_MULTISIG;
    return DOGECOIN_TX_NONSTANDARD;
}
References dogecoin_script_is_multisig(), dogecoin_script_is_pubkey(), dogecoin_script_is_pubkeyhash(), dogecoin_script_is_scripthash(), DOGECOIN_TX_MULTISIG, DOGECOIN_TX_NONSTANDARD, DOGECOIN_TX_PUBKEY, DOGECOIN_TX_PUBKEYHASH, and DOGECOIN_TX_SCRIPTHASH.
dogecoin_script_copy_without_op_codeseperator()
dogecoin_bool dogecoin_script_copy_without_op_codeseperator (const cstring * script_in, cstring * script_out)
This function copies a script without the OP_CODESEPARATOR opcode.
Parameters
script_in The pointer to the cstring which holds the script to be copied.
script_out The pointer to the cstring to hold the script to be created.
Returns
1 if copied successfully, 0 otherwise.
Definition at line 50 of file script.c.
{
    if (script_in->len == 0)
        return false; /* EOF */
    struct const_buffer buf = {script_in->str, script_in->len};
    unsigned char opcode;
    while (buf.len > 0) {
        if (!deser_bytes(&opcode, &buf, 1))
            goto err_out;
        uint32_t data_len = 0;
        if (opcode < OP_PUSHDATA1 && opcode > OP_0) {
            data_len = opcode;
            cstr_append_buf(script_out, &opcode, 1);
        } else if (opcode == OP_PUSHDATA1) {
            uint8_t v8;
            if (!deser_bytes(&v8, &buf, 1))
                goto err_out;
            cstr_append_buf(script_out, &opcode, 1);
            cstr_append_buf(script_out, &v8, 1);
            data_len = v8;
        } else if (opcode == OP_PUSHDATA2) {
            uint16_t v16;
            if (!deser_u16(&v16, &buf))
                goto err_out;
            cstr_append_buf(script_out, &opcode, 1);
            cstr_append_buf(script_out, &v16, 2);
            data_len = v16;
        } else if (opcode == OP_PUSHDATA4) {
            uint32_t v32;
            if (!deser_u32(&v32, &buf))
                goto err_out;
            cstr_append_buf(script_out, &opcode, 1);
            cstr_append_buf(script_out, &v32, 4);
            data_len = v32;
        } else if (opcode == OP_CODESEPARATOR)
            continue;
        if (data_len > 0) {
            assert(data_len < 16777215); //limit max push to 0xFFFFFF
            unsigned char* bufpush = (unsigned char*)dogecoin_calloc(1, data_len);
            if (!deser_bytes(bufpush, &buf, data_len)) {
                dogecoin_free(bufpush);
                goto err_out;
            }
            cstr_append_buf(script_out, bufpush, data_len);
            dogecoin_free(bufpush);
        } else
            cstr_append_buf(script_out, &opcode, 1);
    }
    return true;
err_out:
    return false;
}
References cstr_append_buf(), deser_bytes(), deser_u16(), deser_u32(), dogecoin_calloc(), dogecoin_free(), const_buffer::len, cstring::len, OP_0, OP_CODESEPARATOR, OP_PUSHDATA1, OP_PUSHDATA2, OP_PUSHDATA4, and cstring::str.
Referenced by dogecoin_tx_sighash().
dogecoin_script_get_ops()
dogecoin_bool dogecoin_script_get_ops (const cstring * script_in, vector * ops_out)
This function converts a cstring script into a vector of dogecoin_script_op objects.
Parameters
script_in The pointer to the cstring holding the script to be parsed.
ops_out The pointer to a vector that will store the parsed script operations.
Returns
1 if converted successfully, 0 otherwise.
Definition at line 171 of file script.c.
{
    if (script_in->len == 0)
        return false; /* EOF */
    struct const_buffer buf = {script_in->str, script_in->len};
    unsigned char opcode;
    dogecoin_script_op* op = NULL;
    while (buf.len > 0) {
        op = dogecoin_script_op_new();
        if (!deser_bytes(&opcode, &buf, 1))
            goto err_out;
        op->op = opcode;
        uint32_t data_len;
        if (opcode < OP_PUSHDATA1) {
            data_len = opcode;
        } else if (opcode == OP_PUSHDATA1) {
            uint8_t v8;
            if (!deser_bytes(&v8, &buf, 1))
                goto err_out;
            data_len = v8;
        } else if (opcode == OP_PUSHDATA2) {
            uint16_t v16;
            if (!deser_u16(&v16, &buf))
                goto err_out;
            data_len = v16;
        } else if (opcode == OP_PUSHDATA4) {
            uint32_t v32;
            if (!deser_u32(&v32, &buf))
                goto err_out;
            data_len = v32;
        } else {
            vector_add(ops_out, op);
            continue;
        }
        // don't alloc a push buffer if there is no more data available
        if (buf.len == 0 || data_len > buf.len) {
            goto err_out;
        }
        op->data = dogecoin_calloc(1, data_len);
        memcpy_safe(op->data, buf.p, data_len);
        op->datalen = data_len;
        vector_add(ops_out, op);
        if (!deser_skip(&buf, data_len))
            goto err_out;
    }
    return true;
err_out:
    dogecoin_script_op_free_cb(op);
    return false;
}
References dogecoin_script_op_::data, dogecoin_script_op_::datalen, deser_bytes(), deser_skip(), deser_u16(), deser_u32(), dogecoin_calloc(), dogecoin_script_op_free_cb(), dogecoin_script_op_new(), const_buffer::len, cstring::len, memcpy_safe(), dogecoin_script_op_::op, OP_PUSHDATA1, OP_PUSHDATA2, OP_PUSHDATA4, const_buffer::p, cstring::str, and vector_add().
Referenced by dogecoin_script_classify().
dogecoin_script_get_scripthash()
LIBDOGECOIN_API dogecoin_bool dogecoin_script_get_scripthash (const cstring * script_in, uint160 scripthash)
This function takes a script, computes its hash, and returns it as a uint160 object.
Parameters
script_in The pointer to the cstring which holds the script.
scripthash The uint160 object that will hold the hash of the script.
Returns
1 if the script was hashed correctly, 0 if a null cstring was provided.
Definition at line 658 of file script.c.
{
    if (!script_in) {
        return false;
    }
    uint256 hash;
    dogecoin_hash_sngl_sha256((const unsigned char*)script_in->str, script_in->len, hash);
    rmd160(hash, sizeof(hash), scripthash);
    return true;
}
References dogecoin_hash_sngl_sha256(), cstring::len, rmd160(), cstring::str, and uint256.
dogecoin_script_op_free()
LIBDOGECOIN_API void dogecoin_script_op_free (dogecoin_script_op * script_op)
This function frees the pointer to a dogecoin_script_op object and sets the pointer to NULL.
Parameters
script_op The pointer to the script operation to be freed.
Returns
Nothing.
Definition at line 133 of file script.c.
{
    if (script_op->data) {
        dogecoin_free(script_op->data);
        script_op->data = NULL;
    }
    script_op->datalen = 0;
    script_op->op = OP_0;
}
References dogecoin_script_op_::data, dogecoin_script_op_::datalen, dogecoin_free(), dogecoin_script_op_::op, and OP_0.
Referenced by dogecoin_script_op_free_cb().
dogecoin_script_op_free_cb()
void dogecoin_script_op_free_cb (void * data)
This function casts data from a channel buffer to a dogecoin_script_op object and then frees it by calling dogecoin_script_op_free().
Parameters
data The pointer to the data that must be cast.
Returns
Nothing.
Definition at line 153 of file script.c.
{
    dogecoin_script_op* script_op = data;
    dogecoin_script_op_free(script_op);
    dogecoin_free(script_op);
}
References dogecoin_free(), and dogecoin_script_op_free().
Referenced by dogecoin_script_classify(), and dogecoin_script_get_ops().
dogecoin_script_op_new()
LIBDOGECOIN_API dogecoin_script_op * dogecoin_script_op_new ()
This function allocates the memory for a new dogecoin_script_op object.
Returns
A pointer to the new script operation.
Definition at line 116 of file script.c.
{
    dogecoin_script_op* script_op;
    script_op = dogecoin_calloc(1, sizeof(dogecoin_script_op));
    return script_op;
}
References dogecoin_calloc().
Referenced by dogecoin_script_get_ops().
dogecoin_tx_out_type_to_str()
LIBDOGECOIN_API const char * dogecoin_tx_out_type_to_str (const enum dogecoin_tx_out_type type)
This function takes a script type and translates it into string format.
Parameters
type The type of script.
Returns
The string representation of the script.
Definition at line 679 of file script.c.
{
    if (type == DOGECOIN_TX_PUBKEY) {
        return "TX_PUBKEY";
    } else if (type == DOGECOIN_TX_PUBKEYHASH) {
        return "TX_PUBKEYHASH";
    } else if (type == DOGECOIN_TX_SCRIPTHASH) {
        return "TX_SCRIPTHASH";
    } else if (type == DOGECOIN_TX_MULTISIG) {
        return "TX_MULTISIG";
    } else {
        return "TX_NONSTANDARD";
    }
}
References DOGECOIN_TX_MULTISIG, DOGECOIN_TX_PUBKEY, DOGECOIN_TX_PUBKEYHASH, and DOGECOIN_TX_SCRIPTHASH.
Referenced by main(), and sign_raw_transaction().
Variable Documentation
MAX_SCRIPT_SIZE
const int MAX_SCRIPT_SIZE = 10000 static
Definition at line 214 of file script.h.