libdogecoin: src/cli/sendtx.c File Reference
sendtx.c File Reference
#include <assert.h>
#include <getopt.h>
#include <inttypes.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <unistd.h>
#include <dogecoin/chainparams.h>
#include <dogecoin/ecc.h>
#include <dogecoin/serialize.h>
#include <dogecoin/tool.h>
#include <dogecoin/tx.h>
#include <dogecoin/utils.h>
Functions
static void print_version ()
static void print_usage ()
static bool showError (const char *er)
int main (int argc, char *argv[])
Variables
static struct option long_options []
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 94 of file sendtx.c.
{
    int ret = 0;
    int long_index = 0;
    int opt = 0;
    char* data = 0;
    char* ips = 0;
    int debug = 0;
    int timeout = 15;
    int maxnodes = 10;
    const dogecoin_chainparams* chain = &dogecoin_chainparams_main;
    if (argc <= 1 || strlen(argv[argc - 1]) == 0 || argv[argc - 1][0] == '-') {
        /* exit if no command was provided */
        print_usage();
        exit(EXIT_FAILURE);
        }
    data = argv[argc - 1];
    /* get arguments */
    while ((opt = getopt_long_only(argc, argv, "i:trds:m:", long_options, &long_index)) != -1) {
        switch (opt) {
                case 't':
                    chain = &dogecoin_chainparams_test;
                    break;
                case 'r':
                    chain = &dogecoin_chainparams_regtest;
                    break;
                case 'd':
                    debug = 1;
                    break;
                case 's':
                    timeout = (int)strtol(optarg, (char**)NULL, 10);
                    break;
                case 'i':
                    ips = optarg;
                    break;
                case 'm':
                    maxnodes = (int)strtol(optarg, (char**)NULL, 10);
                    break;
                case 'v':
                    print_version();
                    exit(EXIT_SUCCESS);
                    break;
                default:
                    print_usage();
                    exit(EXIT_FAILURE);
            }
        }
    /* The above code is checking if the data is NULL, empty or larger than the maximum
    size of a p2p message. */
    if (data == NULL || strlen(data) == 0 || strlen(data) > DOGECOIN_MAX_P2P_MSG_SIZE) {
        return showError("Transaction in invalid or to large.\n");
        }
    uint8_t* data_bin = dogecoin_malloc(strlen(data) / 2 + 1);
    size_t outlen = 0;
    utils_hex_to_bin(data, data_bin, strlen(data), &outlen);
    dogecoin_tx* tx = dogecoin_tx_new();
    /* Deserializing the transaction and broadcasting it to the network. */
    if (dogecoin_tx_deserialize(data_bin, outlen, tx, NULL)) {
        broadcast_tx(chain, tx, ips, maxnodes, timeout, debug);
        }
    else {
        showError("Transaction is invalid\n");
        ret = 1;
        }
    dogecoin_free(data_bin);
    dogecoin_tx_free(tx);
    return ret;
    }
References broadcast_tx(), debug, dogecoin_chainparams_main, dogecoin_chainparams_regtest, dogecoin_chainparams_test, dogecoin_free(), dogecoin_malloc(), DOGECOIN_MAX_P2P_MSG_SIZE, dogecoin_tx_deserialize(), dogecoin_tx_free(), dogecoin_tx_new(), long_options, print_usage(), print_version(), showError(), and utils_hex_to_bin().
print_usage()
static void print_usage () static
Definition at line 79 of file sendtx.c.
{
    print_version();
    printf("Usage: sendtx (-i|-ips <ip,ip,...]>) (-m[--maxpeers] <int>) (-t[--testnet]) (-r[--regtest]) (-d[--debug]) (-s[--timeout] <secs>) <txhex>\n");
    printf("\nExamples: \n");
    printf("Send a TX to random peers on testnet:\n");
    printf("> sendtx --testnet <txhex>\n\n");
    printf("Send a TX to specific peers on mainnet:\n");
    printf("> sendtx -i 127.0.0.1:22556,192.168.0.1:22556 <txhex>\n\n");
    }
References print_version().
Referenced by main().
print_version()
static void print_version () static
Definition at line 75 of file sendtx.c.
{
    printf("Version: %s %s\n", PACKAGE_NAME, PACKAGE_VERSION);
    }
References PACKAGE_NAME, and PACKAGE_VERSION.
Referenced by main(), and print_usage().
showError()
static bool showError (const char * er) static
Definition at line 89 of file sendtx.c.
{
    printf("Error: %s\n", er);
    return 1;
    }
Referenced by main().
Variable Documentation
long_options
struct option long_options[] static
Initial value:
= {
        {"testnet", no_argument, NULL, 't'},
        {"regtest", no_argument, NULL, 'r'},
        {"ips", no_argument, NULL, 'i'},
        {"debug", no_argument, NULL, 'd'},
        {"timeout", no_argument, NULL, 's'},
        {"maxnodes", no_argument, NULL, 'm'},
        {NULL, 0, NULL, 0} }
Definition at line 66 of file sendtx.c.
Referenced by main().