libdogecoin: include/dogecoin/serialize.h File Reference
serialize.h File Reference
#include <stdint.h>
#include <stdio.h>
#include <dogecoin/buffer.h>
#include <dogecoin/dogecoin.h>
#include <dogecoin/cstr.h>
#include <dogecoin/portable_endian.h>
Functions
LIBDOGECOIN_BEGIN_DECL LIBDOGECOIN_API void ser_bytes (cstring *s, const void *p, size_t len)
This function appends a buffer of raw bytes to an existing cstring.
LIBDOGECOIN_API void ser_u16 (cstring *s, uint16_t v_)
This function takes 2 unsigned bytes and appends them to an existing cstring by converting them to a little endian byte array.
LIBDOGECOIN_API void ser_u32 (cstring *s, uint32_t v_)
This function takes 4 unsigned bytes and appends them to an existing cstring by converting them to a little endian byte array.
LIBDOGECOIN_API void ser_u64 (cstring *s, uint64_t v_)
This function takes 8 unsigned bytes and appends them to an existing cstring by converting them to a little endian byte array.
LIBDOGECOIN_API void ser_u256 (cstring *s, const unsigned char *v_)
This function takes 32 unsigned bytes and appends them to an existing cstring by converting them to a little endian byte array.
LIBDOGECOIN_API void ser_varlen (cstring *s, uint32_t vlen)
This function takes a variable length unsigned integer and appends the minimum number of bytes to the cstring in order to preserve the data.
LIBDOGECOIN_API void ser_str (cstring *s, const char *s_in, size_t maxlen)
This function takes a variable length string and appends up to maxlen bytes to an existing cstring.
LIBDOGECOIN_API void ser_varstr (cstring *s, cstring *s_in)
This function takes a cstring and appends its contents an existing cstring.
LIBDOGECOIN_API void ser_s32 (cstring *s, int32_t v_)
This function takes 4 bytes and appends them to an existing cstring by converting them to a uint32_t and calling ser_u32().
LIBDOGECOIN_API void ser_s64 (cstring *s, int64_t v_)
This function takes 8 bytes and appends them to an existing cstring by converting them to a uint64_t and calling ser_u64().
LIBDOGECOIN_API int deser_skip (struct const_buffer *buf, size_t len)
This function skips the next len bytes of a const_buffer by moving the pointer up by len bytes and subtracting that amount from its len attribute.
LIBDOGECOIN_API int deser_bytes (void *po, struct const_buffer *buf, size_t len)
This function takes a const_buffer and consumes the first len bytes, which are then placed into a void buffer.
LIBDOGECOIN_API int deser_u16 (uint16_t *vo, struct const_buffer *buf)
This function deserializes 2 bytes from a const_buffer into a uint16_t object.
LIBDOGECOIN_API int deser_u32 (uint32_t *vo, struct const_buffer *buf)
This function deserializes 4 bytes from a const_buffer into a uint32_t object.
LIBDOGECOIN_API int deser_i32 (int32_t *vo, struct const_buffer *buf)
LIBDOGECOIN_API int deser_s32 (int32_t *vo, struct const_buffer *buf)
This function deserializes 4 bytes from a const_buffer into an int32_t object.
LIBDOGECOIN_API int deser_u64 (uint64_t *vo, struct const_buffer *buf)
This function deserializes 8 bytes from a const_buffer into a uint64_t object.
LIBDOGECOIN_API int deser_u256 (uint8_t *vo, struct const_buffer *buf)
This function deserializes 32 bytes from a const_buffer into an unsigned byte array.
LIBDOGECOIN_API int deser_varlen (uint32_t *lo, struct const_buffer *buf)
This function deserializes a variable number of bytes from a const_buffer into an variable length unsigned integer. Only the minimum bytes needed to preserve its value are deserialized.
LIBDOGECOIN_API int deser_varlen_file (uint32_t *lo, FILE *file, uint8_t *rawdata, size_t *buflen_inout)
This function reads the first byte of the file as an indicator of how many bytes to deserialize.
LIBDOGECOIN_API int deser_str (char *so, struct const_buffer *buf, size_t maxlen)
This function deserializes maxlen bytes from a const_buffer into a string object.
LIBDOGECOIN_API int deser_varstr (cstring **so, struct const_buffer *buf)
This function deserializes a variable length string.
LIBDOGECOIN_API int deser_s64 (int64_t *vo, struct const_buffer *buf)
This function deserializes 8 bytes from a const_buffer into an int64_t object.
Function Documentation
deser_bytes()
LIBDOGECOIN_API int deser_bytes (void * po, struct const_buffer * buf, size_t len)
This function takes a const_buffer and consumes the first len bytes, which are then placed into a void buffer.
Parameters
po The pointer to the object to deserialize into.
buf The pointer to the const_buffer to deserialize from.
len The number of bytes to be deserialized.
Returns
1 if the bytes were deserialized successfully, 0 if too many bytes were specified.
Definition at line 241 of file serialize.c.
{
    char* p;
    if (buf->len < len) {
        return false;
    }
    memcpy_safe(po, buf->p, len);
    p = (char*)buf->p;
    p += len;
    buf->p = p;
    buf->len -= len;
    return true;
}
References const_buffer::len, memcpy_safe(), and const_buffer::p.
Referenced by deser_s32(), deser_str(), deser_u16(), deser_u256(), deser_u32(), deser_u64(), deser_varlen(), dogecoin_p2p_deser_addr(), dogecoin_p2p_deser_msghdr(), dogecoin_p2p_msg_version_deser(), dogecoin_script_copy_without_op_codeseperator(), and dogecoin_script_get_ops().
deser_i32()
LIBDOGECOIN_API int deser_i32 (int32_t * vo, struct const_buffer * buf)
deser_s32()
LIBDOGECOIN_API int deser_s32 (int32_t * vo, struct const_buffer * buf)
This function deserializes 4 bytes from a const_buffer into an int32_t object.
Parameters
vo The pointer to the int32_t object to deserialize into.
buf The const_buffer to deserialize from.
Returns
1 if bytes were deserialized correctly, 0 otherwise.
Definition at line 289 of file serialize.c.
{
    int32_t v;
    if (!deser_bytes(&v, buf, sizeof(v))) {
        return false;
    }
    *vo = le32toh(v);
    return true;
}
References deser_bytes().
Referenced by dogecoin_block_header_deserialize(), dogecoin_p2p_deser_msg_getheaders(), dogecoin_p2p_msg_version_deser(), and dogecoin_tx_deserialize().
deser_s64()
LIBDOGECOIN_API int deser_s64 (int64_t * vo, struct const_buffer * buf)
This function deserializes 8 bytes from a const_buffer into an int64_t object.
Parameters
vo The pointer to the int64_t object to deserialize into.
buf The const_buffer to deserialize from.
Returns
1 if bytes were deserialized correctly, 0 otherwise.
Definition at line 561 of file serialize.c.
{
    return deser_u64((uint64_t*)vo, buf);
}
References deser_u64().
Referenced by dogecoin_p2p_msg_version_deser(), and dogecoin_tx_out_deserialize().
deser_skip()
LIBDOGECOIN_API int deser_skip (struct const_buffer * buf, size_t len)
This function skips the next len bytes of a const_buffer by moving the pointer up by len bytes and subtracting that amount from its len attribute.
Parameters
buf The pointer to the const_buffer whose bytes will be skipped.
len The amount of bytes to be skipped.
Returns
1 if the bytes were skipped successfully, 0 if too many bytes were specified.
Definition at line 214 of file serialize.c.
{
    char* p;
    if (buf->len < len) {
        return false;
    }
    p = (char*)buf->p;
    p += len;
    buf->p = p;
    buf->len -= len;
    return true;
}
References const_buffer::len, and const_buffer::p.
Referenced by deser_str(), and dogecoin_script_get_ops().
deser_str()
LIBDOGECOIN_API int deser_str (char * so, struct const_buffer * buf, size_t maxlen)
This function deserializes maxlen bytes from a const_buffer into a string object.
Parameters
so The string to deserialize into.
buf The pointer to the const_buffer to deserialize from.
maxlen The maximum number of bytes to deserialize.
Returns
1 if deserialized successfully, 0 otherwise.
Definition at line 479 of file serialize.c.
{
    uint32_t len;
    uint32_t skip_len = 0;
    if (!deser_varlen(&len, buf)) {
        return false;
    }
    /* if input larger than buffer, truncate copy, skip remainder */
    if (len > maxlen) {
        skip_len = len - maxlen;
        len = maxlen;
    }
    if (!deser_bytes(so, buf, len)) {
        return false;
    }
    if (!deser_skip(buf, skip_len)) {
        return false;
    }
    /* add C string null */
    if (len < maxlen) {
        so[len] = 0;
    }
    else {
        so[maxlen - 1] = 0;
    }
    return true;
}
References deser_bytes(), deser_skip(), deser_varlen(), and const_buffer::len.
deser_u16()
LIBDOGECOIN_API int deser_u16 (uint16_t * vo, struct const_buffer * buf)
This function deserializes 2 bytes from a const_buffer into a uint16_t object.
Parameters
vo The pointer to the uint16_t object to deserialize into.
buf The const_buffer to deserialize from.
Returns
1 if the bytes were deserialized successfully, 0 if too many bytes were specified.
Definition at line 267 of file serialize.c.
{
    uint16_t v;
    if (!deser_bytes(&v, buf, sizeof(v))) {
        return false;
    }
    *vo = le16toh(v);
    return true;
}
References deser_bytes().
Referenced by deser_varlen(), deser_varlen_file(), dogecoin_p2p_deser_addr(), dogecoin_script_copy_without_op_codeseperator(), and dogecoin_script_get_ops().
deser_u256()
LIBDOGECOIN_API int deser_u256 (uint8_t * vo, struct const_buffer * buf)
This function deserializes 32 bytes from a const_buffer into an unsigned byte array.
Parameters
vo The unsigned byte array to deserialize into.
buf The const_buffer to deserialize from.
Returns
1 if the bytes were deserialized correctly, 0 otherwise.
Definition at line 353 of file serialize.c.
{
    return deser_bytes(vo, buf, 32);
}
References deser_bytes().
Referenced by dogecoin_block_header_deserialize(), dogecoin_p2p_deser_msg_getheaders(), dogecoin_p2p_msg_inv_deser(), and dogecoin_tx_in_deserialize().
deser_u32()
LIBDOGECOIN_API int deser_u32 (uint32_t * vo, struct const_buffer * buf)
This function deserializes 4 bytes from a const_buffer into a uint32_t object.
Parameters
vo The pointer to the uint32_t object to deserialize into.
buf The const_buffer to deserialize from.
Returns
1 if the bytes were deserialized correctly, 0 otherwise.
Definition at line 310 of file serialize.c.
{
    uint32_t v;
    if (!deser_bytes(&v, buf, sizeof(v))) {
        return false;
    }
    *vo = le32toh(v);
    return true;
}
References deser_bytes().
Referenced by deser_varlen(), deser_varlen_file(), dogecoin_block_header_deserialize(), dogecoin_p2p_deser_addr(), dogecoin_p2p_deser_msghdr(), dogecoin_p2p_msg_inv_deser(), dogecoin_script_copy_without_op_codeseperator(), dogecoin_script_get_ops(), dogecoin_tx_deserialize(), and dogecoin_tx_in_deserialize().
deser_u64()
LIBDOGECOIN_API int deser_u64 (uint64_t * vo, struct const_buffer * buf)
This function deserializes 8 bytes from a const_buffer into a uint64_t object.
Parameters
vo The pointer to the uint64_t object to deserialize into.
buf The const_buffer to deserialize from.
Returns
1 if the bytes were deserialized correctly, 0 otherwise.
Definition at line 331 of file serialize.c.
{
    uint64_t v;
    if (!deser_bytes(&v, buf, sizeof(v))) {
        return false;
    }
    *vo = le64toh(v);
    return true;
}
References deser_bytes().
Referenced by deser_s64(), deser_varlen(), deser_varlen_file(), dogecoin_node_parse_message(), dogecoin_p2p_deser_addr(), and dogecoin_p2p_msg_version_deser().
deser_varlen()
LIBDOGECOIN_API int deser_varlen (uint32_t * lo, struct const_buffer * buf)
This function deserializes a variable number of bytes from a const_buffer into an variable length unsigned integer. Only the minimum bytes needed to preserve its value are deserialized.
Parameters
lo The pointer to the uint32_t object to deserialize into.
buf The const_buffer to deserialize from.
Returns
1 if bytes were deserialized successfully, 0 otherwise.
Definition at line 370 of file serialize.c.
{
    uint32_t len;
    unsigned char c;
    if (!deser_bytes(&c, buf, 1))
        return false;
    if (c == 253) {
        uint16_t v16;
        if (!deser_u16(&v16, buf))
            return false;
        len = v16;
    } else if (c == 254) {
        uint32_t v32;
        if (!deser_u32(&v32, buf))
            return false;
        len = v32;
    } else if (c == 255) {
        uint64_t v64;
        if (!deser_u64(&v64, buf))
            return false;
        len = (uint32_t)v64; /* WARNING: truncate */
    } else {
        len = c;
    }
    *lo = len;
    return true;
}
References deser_bytes(), deser_u16(), deser_u32(), and deser_u64().
Referenced by broadcast_post_cmd(), deser_str(), deser_varstr(), dogecoin_p2p_deser_msg_getheaders(), dogecoin_p2p_msg_version_deser(), and dogecoin_tx_deserialize().
deser_varlen_file()
LIBDOGECOIN_API int deser_varlen_file (uint32_t * lo, FILE * file, uint8_t * rawdata, size_t * buflen_inout)
This function reads the first byte of the file as an indicator of how many bytes to deserialize.
Parameters
lo The length of the unsigned integer read from the file.
file The file which contains the bytes to deserialize from.
rawdata The buffer to be parsed.
buflen_inout The number of total bytes read from the file, including the first byte.
Returns
1 if file is read successfully, 0 otherwise.
Definition at line 413 of file serialize.c.
{
    uint32_t len;
    struct const_buffer buf;
    unsigned char c;
    const unsigned char bufp[sizeof(uint64_t)];
    /* check min size of the buffer */
    if (*buflen_inout < sizeof(len))
        return false;
    if (fread(&c, 1, 1, file) != 1)
        return false;
    rawdata[0] = c;
    *buflen_inout = 1;
    buf.p = (void*)bufp;
    buf.len = sizeof(uint64_t);
    if (c == 253) {
        uint16_t v16;
        if (fread((void*)buf.p, 1, sizeof(v16), file) != sizeof(v16))
            return false;
        memcpy_safe(rawdata + 1, buf.p, sizeof(v16));
        *buflen_inout += sizeof(v16);
        if (!deser_u16(&v16, &buf))
            return false;
        len = v16;
    } else if (c == 254) {
        uint32_t v32;
        if (fread((void*)buf.p, 1, sizeof(v32), file) != sizeof(v32))
            return false;
        memcpy_safe(rawdata + 1, buf.p, sizeof(v32));
        *buflen_inout += sizeof(v32);
        if (!deser_u32(&v32, &buf))
            return false;
        len = v32;
    } else if (c == 255) {
        uint64_t v64;
        if (fread((void*)buf.p, 1, sizeof(v64), file) != sizeof(v64))
            return false;
        memcpy_safe(rawdata + 1, buf.p, sizeof(uint32_t)); /* warning, truncate! */
        *buflen_inout += sizeof(uint32_t);
        if (!deser_u64(&v64, &buf))
            return false;
        len = (uint32_t)v64; /* WARNING: truncate */
    } else {
        len = c;
    }
    *lo = len;
    return true;
}
References deser_u16(), deser_u32(), deser_u64(), const_buffer::len, memcpy_safe(), and const_buffer::p.
deser_varstr()
LIBDOGECOIN_API int deser_varstr (cstring ** so, struct const_buffer * buf)
This function deserializes a variable length string.
Parameters
so The pointer to the pointer to the cstring to deserialize into.
buf The const_buffer to deserialize from.
Returns
1 if string deserialized successfully, 0 otherwise.
Definition at line 521 of file serialize.c.
{
    uint32_t len;
    cstring* s;
    char* p;
    if (*so) {
        cstr_free(*so, 1);
        *so = NULL;
    }
    if (!deser_varlen(&len, buf))
        return false;
    if (buf->len < len)
        return false;
    s = cstr_new_sz(len);
    cstr_append_buf(s, buf->p, len);
    p = (char*)buf->p;
    p += len;
    buf->p = p;
    buf->len -= len;
    *so = s;
    return true;
}
References cstr_append_buf(), cstr_free(), cstr_new_sz(), deser_varlen(), const_buffer::len, and const_buffer::p.
Referenced by dogecoin_tx_in_deserialize(), and dogecoin_tx_out_deserialize().
ser_bytes()
LIBDOGECOIN_BEGIN_DECL LIBDOGECOIN_API void ser_bytes (cstring * s, const void * p, size_t len)
This function appends a buffer of raw bytes to an existing cstring.
Parameters
s The pointer to the cstring to append to.
p The buffer of raw bytes to be appended.
len The length of the buffer to be appended.
Returns
Nothing.
Definition at line 24 of file serialize.c.
{
    cstr_append_buf(s, p, len);
}
References cstr_append_buf().
Referenced by dogecoin_p2p_msg_getheaders(), dogecoin_p2p_msg_inv_ser(), dogecoin_p2p_ser_addr(), dogecoin_tx_sign_input(), ser_str(), ser_u256(), ser_varlen(), and ser_varstr().
ser_s32()
LIBDOGECOIN_API void ser_s32 (cstring * s, int32_t v_)
This function takes 4 bytes and appends them to an existing cstring by converting them to a uint32_t and calling ser_u32().
Parameters
s The pointer to the cstring to append to.
v_ The bytes to be appended as an int32_t.
Returns
Nothing.
Definition at line 74 of file serialize.c.
{
    ser_u32(s, (uint32_t)v_);
}
References ser_u32().
Referenced by dogecoin_block_header_serialize(), dogecoin_p2p_msg_version_ser(), dogecoin_tx_serialize(), and dogecoin_tx_sighash().
ser_s64()
LIBDOGECOIN_API void ser_s64 (cstring * s, int64_t v_)
This function takes 8 bytes and appends them to an existing cstring by converting them to a uint64_t and calling ser_u64().
Parameters
s The pointer to the cstring to append to.
v_ The bytes to be appended as an int64_t.
Returns
Nothing.
Definition at line 107 of file serialize.c.
{
    ser_u64(s, (uint64_t)v_);
}
References ser_u64().
Referenced by dogecoin_p2p_msg_version_ser(), and dogecoin_tx_out_serialize().
ser_str()
LIBDOGECOIN_API void ser_str (cstring * s, const char * s_in, size_t maxlen)
This function takes a variable length string and appends up to maxlen bytes to an existing cstring.
Parameters
s The pointer to the cstring to append to.
s_in The bytes to be appended as a string.
maxlen The maximum number of bytes to be appended.
Returns
Nothing.
Definition at line 174 of file serialize.c.
{
    size_t slen = strnlen(s_in, maxlen);
    ser_varlen(s, slen);
    ser_bytes(s, s_in, slen);
}
References ser_bytes(), and ser_varlen().
Referenced by dogecoin_p2p_msg_version_ser().
ser_u16()
LIBDOGECOIN_API void ser_u16 (cstring * s, uint16_t v_)
This function takes 2 unsigned bytes and appends them to an existing cstring by converting them to a little endian byte array.
Parameters
s The pointer to the cstring to append to.
v_ The bytes to be appended as a uint16_t.
Returns
Nothing.
Definition at line 40 of file serialize.c.
{
    uint16_t v = htole16(v_);
    cstr_append_buf(s, &v, sizeof(v));
}
References cstr_append_buf().
Referenced by dogecoin_p2p_ser_addr(), and ser_varlen().
ser_u256()
LIBDOGECOIN_API void ser_u256 (cstring * s, const unsigned char * v_)
This function takes 32 unsigned bytes and appends them to an existing cstring by converting them to a little endian byte array.
Parameters
s The pointer to the cstring to append to.
v_ The bytes to be appended as an unsigned char array.
Returns
Nothing.
Definition at line 123 of file serialize.c.
{
    ser_bytes(s, v_, 32);
}
References ser_bytes().
Referenced by dogecoin_block_header_serialize(), dogecoin_tx_in_serialize(), and dogecoin_tx_prevout_hash().
ser_u32()
LIBDOGECOIN_API void ser_u32 (cstring * s, uint32_t v_)
This function takes 4 unsigned bytes and appends them to an existing cstring by converting them to a little endian byte array.
Parameters
s The pointer to the cstring to append to.
v_ The bytes to be appended as a uint32_t.
Returns
Nothing.
Definition at line 57 of file serialize.c.
{
    uint32_t v = htole32(v_);
    cstr_append_buf(s, &v, sizeof(v));
}
References cstr_append_buf().
Referenced by dogecoin_block_header_serialize(), dogecoin_p2p_msg_getheaders(), dogecoin_p2p_msg_inv_ser(), dogecoin_p2p_ser_addr(), dogecoin_tx_in_serialize(), dogecoin_tx_prevout_hash(), dogecoin_tx_sequence_hash(), dogecoin_tx_serialize(), ser_s32(), and ser_varlen().
ser_u64()
LIBDOGECOIN_API void ser_u64 (cstring * s, uint64_t v_)
This function takes 8 unsigned bytes and appends them to an existing cstring by converting them to a little endian byte array.
Parameters
s The pointer to the cstring to append to.
v_ The bytes to be appended as a uint64_t.
Returns
Nothing.
Definition at line 90 of file serialize.c.
{
    uint64_t v = htole64(v_);
    cstr_append_buf(s, &v, sizeof(v));
}
References cstr_append_buf().
Referenced by dogecoin_p2p_msg_version_ser(), dogecoin_p2p_ser_addr(), and ser_s64().
ser_varlen()
LIBDOGECOIN_API void ser_varlen (cstring * s, uint32_t vlen)
This function takes a variable length unsigned integer and appends the minimum number of bytes to the cstring in order to preserve the data.
Parameters
s The pointer to the cstring to append to.
vlen The bytes to be appended as a uint32_t.
Returns
Nothing.
Definition at line 139 of file serialize.c.
{
    unsigned char c;
    if (vlen < 253) {
        c = vlen;
        ser_bytes(s, &c, 1);
    }
    else if (vlen < 0x10000) {
        c = 253;
        ser_bytes(s, &c, 1);
        ser_u16(s, (uint16_t)vlen);
    }
    else {
        c = 254;
        ser_bytes(s, &c, 1);
        ser_u32(s, vlen);
    }
    /* u64 case intentionally not implemented */
}
References ser_bytes(), ser_u16(), and ser_u32().
Referenced by broadcast_handshake_done(), dogecoin_p2p_msg_getheaders(), dogecoin_tx_serialize(), dogecoin_tx_sign_input(), ser_str(), and ser_varstr().
ser_varstr()
LIBDOGECOIN_API void ser_varstr (cstring * s, cstring * s_in)
This function takes a cstring and appends its contents an existing cstring.
Parameters
s The pointer to the cstring to append to.
s_in The pointer to the cstring to be appended.
Returns
Nothing.
Definition at line 192 of file serialize.c.
{
    if (!s_in || !s_in->len) {
        ser_varlen(s, 0);
        return;
    }
    ser_varlen(s, s_in->len);
    ser_bytes(s, s_in->str, s_in->len);
}
References cstring::len, ser_bytes(), ser_varlen(), and cstring::str.
Referenced by dogecoin_tx_in_serialize(), and dogecoin_tx_out_serialize().