libdogecoin: include/dogecoin/sha2.h File Reference
sha2.h File Reference
#include <stddef.h>
#include <stdint.h>
#include <dogecoin/dogecoin.h>
Data Structures
struct _sha256_context
struct _sha512_context
struct _hmac_sha256_context
struct _hmac_sha512_context
struct _pbkdf2_hmac_sha256_context
struct _pbkdf2_hmac_sha512_context
Macros
#define SHA256_BLOCK_LENGTH 64
#define SHA256_DIGEST_LENGTH 32
#define SHA256_DIGEST_STRING_LENGTH (SHA256_DIGEST_LENGTH * 2 + 1)
#define SHA512_BLOCK_LENGTH 128
#define SHA512_DIGEST_LENGTH 64
#define SHA512_DIGEST_STRING_LENGTH (SHA512_DIGEST_LENGTH * 2 + 1)
Typedefs
typedef struct _sha256_context sha256_context
typedef struct _sha512_context sha512_context
typedef struct _hmac_sha256_context hmac_sha256_context
typedef struct _hmac_sha512_context hmac_sha512_context
typedef struct _pbkdf2_hmac_sha256_context pbkdf2_hmac_sha256_context
typedef struct _pbkdf2_hmac_sha512_context pbkdf2_hmac_sha512_context
Functions
LIBDOGECOIN_API void sha256_init (sha256_context *)
LIBDOGECOIN_API void sha256_write (sha256_context *, const uint8_t *, size_t)
LIBDOGECOIN_API void sha256_finalize (sha256_context *, uint8_t[SHA256_DIGEST_LENGTH])
LIBDOGECOIN_API void sha256_raw (const uint8_t *, size_t, uint8_t[SHA256_DIGEST_LENGTH])
LIBDOGECOIN_API void sha512_init (sha512_context *)
LIBDOGECOIN_API void sha512_write (sha512_context *, const uint8_t *, size_t)
LIBDOGECOIN_API void sha512_finalize (sha512_context *, uint8_t[SHA512_DIGEST_LENGTH])
LIBDOGECOIN_API void sha512_raw (const uint8_t *, size_t, uint8_t[SHA512_DIGEST_LENGTH])
LIBDOGECOIN_API void hmac_sha256_init (hmac_sha256_context *hctx, const uint8_t *key, const uint32_t keylen)
LIBDOGECOIN_API void hmac_sha256_write (hmac_sha256_context *hctx, const uint8_t *msg, const uint32_t msglen)
LIBDOGECOIN_API void hmac_sha256_finalize (hmac_sha256_context *hctx, uint8_t *hmac)
LIBDOGECOIN_API void hmac_sha256 (const uint8_t *key, const size_t keylen, const uint8_t *msg, const size_t msglen, uint8_t *hmac)
LIBDOGECOIN_API void hmac_sha512_init (hmac_sha512_context *hctx, const uint8_t *key, const uint32_t keylen)
LIBDOGECOIN_API void hmac_sha512_write (hmac_sha512_context *hctx, const uint8_t *msg, const uint32_t msglen)
LIBDOGECOIN_API void hmac_sha512_finalize (hmac_sha512_context *hctx, uint8_t *hmac)
LIBDOGECOIN_API void hmac_sha512 (const uint8_t *key, const size_t keylen, const uint8_t *msg, const size_t msglen, uint8_t *hmac)
LIBDOGECOIN_API void pbkdf2_hmac_sha256_init (pbkdf2_hmac_sha256_context *pctx, const uint8_t *pass, int passlen, const uint8_t *salt, int saltlen)
LIBDOGECOIN_API void pbkdf2_hmac_sha256_write (pbkdf2_hmac_sha256_context *pctx, uint32_t iterations)
LIBDOGECOIN_API void pbkdf2_hmac_sha256_finalize (pbkdf2_hmac_sha256_context *pctx, uint8_t *key)
LIBDOGECOIN_API void pbkdf2_hmac_sha256 (const uint8_t *pass, int passlen, const uint8_t *salt, int saltlen, uint32_t iterations, uint8_t *key)
LIBDOGECOIN_API void pbkdf2_hmac_sha512_init (pbkdf2_hmac_sha512_context *pctx, const uint8_t *pass, int passlen, const uint8_t *salt, int saltlen)
LIBDOGECOIN_API void pbkdf2_hmac_sha512_write (pbkdf2_hmac_sha512_context *pctx, uint32_t iterations)
LIBDOGECOIN_API void pbkdf2_hmac_sha512_finalize (pbkdf2_hmac_sha512_context *pctx, uint8_t *key)
LIBDOGECOIN_API void pbkdf2_hmac_sha512 (const uint8_t *pass, int passlen, const uint8_t *salt, int saltlen, uint32_t iterations, uint8_t *key)
Macro Definition Documentation
SHA256_BLOCK_LENGTH
#define SHA256_BLOCK_LENGTH 64
Copyright (c) 2000-2001 Aaron D. Gifford Copyright (c) 2013-2014 Tomas Dzetkulic Copyright (c) 2013-2014 Pavol Rusnak Copyright (c) 2022 bluezr Copyright (c) 2022 The Dogecoin Foundation All rights reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Neither the name of the copyright holder nor the names of contributors may be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTOR(S) `‘AS IS’' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTOR(S) BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Definition at line 44 of file sha2.h.
SHA256_DIGEST_LENGTH
#define SHA256_DIGEST_LENGTH 32
Definition at line 45 of file sha2.h.
SHA256_DIGEST_STRING_LENGTH
#define SHA256_DIGEST_STRING_LENGTH (SHA256_DIGEST_LENGTH * 2 + 1)
Definition at line 46 of file sha2.h.
SHA512_BLOCK_LENGTH
#define SHA512_BLOCK_LENGTH 128
Definition at line 47 of file sha2.h.
SHA512_DIGEST_LENGTH
#define SHA512_DIGEST_LENGTH 64
Definition at line 48 of file sha2.h.
SHA512_DIGEST_STRING_LENGTH
#define SHA512_DIGEST_STRING_LENGTH (SHA512_DIGEST_LENGTH * 2 + 1)
Definition at line 49 of file sha2.h.
Typedef Documentation
hmac_sha256_context
typedef struct _hmac_sha256_context hmac_sha256_context
hmac_sha512_context
typedef struct _hmac_sha512_context hmac_sha512_context
pbkdf2_hmac_sha256_context
typedef struct _pbkdf2_hmac_sha256_context pbkdf2_hmac_sha256_context
pbkdf2_hmac_sha512_context
typedef struct _pbkdf2_hmac_sha512_context pbkdf2_hmac_sha512_context
sha256_context
typedef struct _sha256_context sha256_context
sha512_context
typedef struct _sha512_context sha512_context
Function Documentation
hmac_sha256()
LIBDOGECOIN_API void hmac_sha256 (const uint8_t * key, const size_t keylen, const uint8_t * msg, const size_t msglen, uint8_t * hmac)
Definition at line 964 of file sha2.c.
{
    int i;
    uint8_t buf[SHA256_BLOCK_LENGTH], o_key_pad[SHA256_BLOCK_LENGTH],
        i_key_pad[SHA256_BLOCK_LENGTH];
    sha256_context ctx;
    dogecoin_mem_zero(buf, SHA256_BLOCK_LENGTH);
    if (keylen > SHA256_BLOCK_LENGTH) {
        sha256_raw(key, keylen, buf);
    } else {
        memcpy_safe(buf, key, keylen);
    }
    for (i = 0; i < SHA256_BLOCK_LENGTH; i++) {
        o_key_pad[i] = buf[i] ^ 0x5c;
        i_key_pad[i] = buf[i] ^ 0x36;
    }
    sha256_init(&ctx);
    sha256_write(&ctx, i_key_pad, SHA256_BLOCK_LENGTH);
    sha256_write(&ctx, msg, msglen);
    sha256_finalize(&ctx, buf);
    sha256_init(&ctx);
    sha256_write(&ctx, o_key_pad, SHA256_BLOCK_LENGTH);
    sha256_write(&ctx, buf, SHA256_DIGEST_LENGTH);
    sha256_finalize(&ctx, hmac);
}
References ctx, dogecoin_mem_zero(), memcpy_safe(), SHA256_BLOCK_LENGTH, SHA256_DIGEST_LENGTH, sha256_finalize(), sha256_init(), sha256_raw(), and sha256_write().
Referenced by pbkdf2_hmac_sha256_write().
hmac_sha256_finalize()
LIBDOGECOIN_API void hmac_sha256_finalize (hmac_sha256_context * hctx, uint8_t * hmac)
Definition at line 952 of file sha2.c.
{
    uint8_t hash[SHA256_DIGEST_LENGTH];
    sha256_finalize(&(hctx->ctx), hash);
    sha256_init(&(hctx->ctx));
    sha256_write(&(hctx->ctx), hctx->o_key_pad, SHA256_BLOCK_LENGTH);
    sha256_write(&(hctx->ctx), hash, SHA256_DIGEST_LENGTH);
    sha256_finalize(&(hctx->ctx), hmac);
    MEMSET_BZERO(hash, sizeof(hash));
    MEMSET_BZERO(hctx, sizeof(hmac_sha256_context));
}
References _hmac_sha256_context::ctx, MEMSET_BZERO, _hmac_sha256_context::o_key_pad, SHA256_BLOCK_LENGTH, SHA256_DIGEST_LENGTH, sha256_finalize(), sha256_init(), and sha256_write().
Referenced by pbkdf2_hmac_sha256_init().
hmac_sha256_init()
LIBDOGECOIN_API void hmac_sha256_init (hmac_sha256_context * hctx, const uint8_t * key, const uint32_t keylen)
Definition at line 928 of file sha2.c.
{
    uint8_t i_key_pad[SHA256_BLOCK_LENGTH];
    memset(i_key_pad, 0, SHA256_BLOCK_LENGTH);
    if (keylen > SHA256_BLOCK_LENGTH) {
        sha256_raw(key, keylen, i_key_pad);
    } else {
        memcpy(i_key_pad, key, keylen);
    }
    int i;
    for (i = 0; i < SHA256_BLOCK_LENGTH; i++) {
        hctx->o_key_pad[i] = i_key_pad[i] ^ 0x5c;
        i_key_pad[i] ^= 0x36;
    }
    sha256_init(&(hctx->ctx));
    sha256_write(&(hctx->ctx), i_key_pad, SHA256_BLOCK_LENGTH);
    MEMSET_BZERO(i_key_pad, sizeof(i_key_pad));
}
References _hmac_sha256_context::ctx, MEMSET_BZERO, _hmac_sha256_context::o_key_pad, SHA256_BLOCK_LENGTH, sha256_init(), sha256_raw(), and sha256_write().
Referenced by pbkdf2_hmac_sha256_init().
hmac_sha256_write()
LIBDOGECOIN_API void hmac_sha256_write (hmac_sha256_context * hctx, const uint8_t * msg, const uint32_t msglen)
Definition at line 947 of file sha2.c.
{
    sha256_write(&(hctx->ctx), msg, msglen);
}
References _hmac_sha256_context::ctx, and sha256_write().
Referenced by pbkdf2_hmac_sha256_init().
hmac_sha512()
LIBDOGECOIN_API void hmac_sha512 (const uint8_t * key, const size_t keylen, const uint8_t * msg, const size_t msglen, uint8_t * hmac)
Definition at line 1027 of file sha2.c.
{
    int i;
    uint8_t buf[SHA512_BLOCK_LENGTH], o_key_pad[SHA512_BLOCK_LENGTH],
        i_key_pad[SHA512_BLOCK_LENGTH];
    sha512_context ctx;
    dogecoin_mem_zero(buf, SHA512_BLOCK_LENGTH);
    if (keylen > SHA512_BLOCK_LENGTH)
        sha512_raw(key, keylen, buf);
    else
        memcpy_safe(buf, key, keylen);
    for (i = 0; i < SHA512_BLOCK_LENGTH; i++) {
        o_key_pad[i] = buf[i] ^ 0x5c;
        i_key_pad[i] = buf[i] ^ 0x36;
    }
    sha512_init(&ctx);
    sha512_write(&ctx, i_key_pad, SHA512_BLOCK_LENGTH);
    sha512_write(&ctx, msg, msglen);
    sha512_finalize(&ctx, buf);
    sha512_init(&ctx);
    sha512_write(&ctx, o_key_pad, SHA512_BLOCK_LENGTH);
    sha512_write(&ctx, buf, SHA512_DIGEST_LENGTH);
    sha512_finalize(&ctx, hmac);
}
References ctx, dogecoin_mem_zero(), memcpy_safe(), SHA512_BLOCK_LENGTH, SHA512_DIGEST_LENGTH, sha512_finalize(), sha512_init(), sha512_raw(), and sha512_write().
Referenced by dogecoin_hdnode_from_seed(), dogecoin_hdnode_private_ckd(), dogecoin_hdnode_public_ckd(), and pbkdf2_hmac_sha512_write().
hmac_sha512_finalize()
LIBDOGECOIN_API void hmac_sha512_finalize (hmac_sha512_context * hctx, uint8_t * hmac)
Definition at line 1015 of file sha2.c.
{
    uint8_t hash[SHA512_DIGEST_LENGTH];
    sha512_finalize(&(hctx->ctx), hash);
    sha512_init(&(hctx->ctx));
    sha512_write(&(hctx->ctx), hctx->o_key_pad, SHA512_BLOCK_LENGTH);
    sha512_write(&(hctx->ctx), hash, SHA512_DIGEST_LENGTH);
    sha512_finalize(&(hctx->ctx), hmac);
    MEMSET_BZERO(hash, sizeof(hash));
    MEMSET_BZERO(hctx, sizeof(hmac_sha512_context));
}
References _hmac_sha512_context::ctx, MEMSET_BZERO, _hmac_sha512_context::o_key_pad, SHA512_BLOCK_LENGTH, SHA512_DIGEST_LENGTH, sha512_finalize(), sha512_init(), and sha512_write().
Referenced by pbkdf2_hmac_sha512_init().
hmac_sha512_init()
LIBDOGECOIN_API void hmac_sha512_init (hmac_sha512_context * hctx, const uint8_t * key, const uint32_t keylen)
Definition at line 991 of file sha2.c.
{
    uint8_t i_key_pad[SHA512_BLOCK_LENGTH];
    memset(i_key_pad, 0, SHA512_BLOCK_LENGTH);
    if (keylen > SHA512_BLOCK_LENGTH) {
        sha512_raw(key, keylen, i_key_pad);
    } else {
        memcpy(i_key_pad, key, keylen);
    }
    int i;
    for (i = 0; i < SHA512_BLOCK_LENGTH; i++) {
        hctx->o_key_pad[i] = i_key_pad[i] ^ 0x5c;
        i_key_pad[i] ^= 0x36;
    }
    sha512_init(&(hctx->ctx));
    sha512_write(&(hctx->ctx), i_key_pad, SHA512_BLOCK_LENGTH);
    MEMSET_BZERO(i_key_pad, sizeof(i_key_pad));
}
References _hmac_sha512_context::ctx, MEMSET_BZERO, _hmac_sha512_context::o_key_pad, SHA512_BLOCK_LENGTH, sha512_init(), sha512_raw(), and sha512_write().
Referenced by pbkdf2_hmac_sha512_init().
hmac_sha512_write()
LIBDOGECOIN_API void hmac_sha512_write (hmac_sha512_context * hctx, const uint8_t * msg, const uint32_t msglen)
Definition at line 1010 of file sha2.c.
{
    sha512_write(&(hctx->ctx), msg, msglen);
}
References _hmac_sha512_context::ctx, and sha512_write().
Referenced by pbkdf2_hmac_sha512_init().
pbkdf2_hmac_sha256()
LIBDOGECOIN_API void pbkdf2_hmac_sha256 (const uint8_t * pass, int passlen, const uint8_t * salt, int saltlen, uint32_t iterations, uint8_t * key)
Definition at line 1086 of file sha2.c.
{
    pbkdf2_hmac_sha256_context pctx;
    pbkdf2_hmac_sha256_init(&pctx, pass, passlen, salt, saltlen);
    pbkdf2_hmac_sha256_write(&pctx, iterations);
    pbkdf2_hmac_sha256_finalize(&pctx, key);
}
References pbkdf2_hmac_sha256_finalize(), pbkdf2_hmac_sha256_init(), and pbkdf2_hmac_sha256_write().
pbkdf2_hmac_sha256_finalize()
LIBDOGECOIN_API void pbkdf2_hmac_sha256_finalize (pbkdf2_hmac_sha256_context * pctx, uint8_t * key)
Definition at line 1080 of file sha2.c.
{
    memcpy(key, pctx->f, SHA256_DIGEST_LENGTH);
    MEMSET_BZERO(pctx, sizeof(pbkdf2_hmac_sha256_context));
}
References _pbkdf2_hmac_sha256_context::f, MEMSET_BZERO, and SHA256_DIGEST_LENGTH.
Referenced by pbkdf2_hmac_sha256().
pbkdf2_hmac_sha256_init()
LIBDOGECOIN_API void pbkdf2_hmac_sha256_init (pbkdf2_hmac_sha256_context * pctx, const uint8_t * pass, int passlen, const uint8_t * salt, int saltlen)
Definition at line 1054 of file sha2.c.
{
    hmac_sha256_context hctx;
    hmac_sha256_init(&hctx, pass, passlen);
    hmac_sha256_write(&hctx, salt, saltlen);
    hmac_sha256_write(&hctx, (const uint8_t *)"\x00\x00\x00\x01", 4);
    hmac_sha256_finalize(&hctx, pctx->g);
    memcpy(pctx->f, pctx->g, SHA256_DIGEST_LENGTH);
    pctx->pass = pass;
    pctx->passlen = passlen;
    pctx->first = 1;
}
References _pbkdf2_hmac_sha256_context::f, _pbkdf2_hmac_sha256_context::first, _pbkdf2_hmac_sha256_context::g, hmac_sha256_finalize(), hmac_sha256_init(), hmac_sha256_write(), _pbkdf2_hmac_sha256_context::pass, _pbkdf2_hmac_sha256_context::passlen, and SHA256_DIGEST_LENGTH.
Referenced by pbkdf2_hmac_sha256().
pbkdf2_hmac_sha256_write()
LIBDOGECOIN_API void pbkdf2_hmac_sha256_write (pbkdf2_hmac_sha256_context * pctx, uint32_t iterations)
Definition at line 1067 of file sha2.c.
{
    uint32_t i;
    for (i = pctx->first; i < iterations; i++) {
        hmac_sha256(pctx->pass, pctx->passlen, pctx->g, SHA256_DIGEST_LENGTH, pctx->g);
        uint32_t j;
        for (j = 0; j < SHA256_DIGEST_LENGTH; j++) {
            pctx->f[j] ^= pctx->g[j];
        }
    }
    pctx->first = 0;
}
References _pbkdf2_hmac_sha256_context::f, _pbkdf2_hmac_sha256_context::first, _pbkdf2_hmac_sha256_context::g, hmac_sha256(), _pbkdf2_hmac_sha256_context::pass, _pbkdf2_hmac_sha256_context::passlen, and SHA256_DIGEST_LENGTH.
Referenced by pbkdf2_hmac_sha256().
pbkdf2_hmac_sha512()
LIBDOGECOIN_API void pbkdf2_hmac_sha512 (const uint8_t * pass, int passlen, const uint8_t * salt, int saltlen, uint32_t iterations, uint8_t * key)
Definition at line 1126 of file sha2.c.
{
    pbkdf2_hmac_sha512_context pctx;
    pbkdf2_hmac_sha512_init(&pctx, pass, passlen, salt, saltlen);
    pbkdf2_hmac_sha512_write(&pctx, iterations);
    pbkdf2_hmac_sha512_finalize(&pctx, key);
}
References pbkdf2_hmac_sha512_finalize(), pbkdf2_hmac_sha512_init(), and pbkdf2_hmac_sha512_write().
Referenced by get_root_seed().
pbkdf2_hmac_sha512_finalize()
LIBDOGECOIN_API void pbkdf2_hmac_sha512_finalize (pbkdf2_hmac_sha512_context * pctx, uint8_t * key)
Definition at line 1120 of file sha2.c.
{
    memcpy(key, pctx->f, SHA512_DIGEST_LENGTH);
    MEMSET_BZERO(pctx, sizeof(pbkdf2_hmac_sha512_context));
}
References _pbkdf2_hmac_sha512_context::f, MEMSET_BZERO, and SHA512_DIGEST_LENGTH.
Referenced by pbkdf2_hmac_sha512().
pbkdf2_hmac_sha512_init()
LIBDOGECOIN_API void pbkdf2_hmac_sha512_init (pbkdf2_hmac_sha512_context * pctx, const uint8_t * pass, int passlen, const uint8_t * salt, int saltlen)
Definition at line 1094 of file sha2.c.
{
    hmac_sha512_context hctx;
    hmac_sha512_init(&hctx, pass, passlen);
    hmac_sha512_write(&hctx, salt, saltlen);
    hmac_sha512_write(&hctx, (const uint8_t *)"\x00\x00\x00\x01", 4);
    hmac_sha512_finalize(&hctx, pctx->g);
    memcpy(pctx->f, pctx->g, SHA512_DIGEST_LENGTH);
    pctx->pass = pass;
    pctx->passlen = passlen;
    pctx->first = 1;
}
References _pbkdf2_hmac_sha512_context::f, _pbkdf2_hmac_sha512_context::first, _pbkdf2_hmac_sha512_context::g, hmac_sha512_finalize(), hmac_sha512_init(), hmac_sha512_write(), _pbkdf2_hmac_sha512_context::pass, _pbkdf2_hmac_sha512_context::passlen, and SHA512_DIGEST_LENGTH.
Referenced by pbkdf2_hmac_sha512().
pbkdf2_hmac_sha512_write()
LIBDOGECOIN_API void pbkdf2_hmac_sha512_write (pbkdf2_hmac_sha512_context * pctx, uint32_t iterations)
Definition at line 1107 of file sha2.c.
{
    uint32_t i;
    for (i = pctx->first; i < iterations; i++) {
        hmac_sha512(pctx->pass, pctx->passlen, pctx->g, SHA512_DIGEST_LENGTH, pctx->g);
        uint32_t j;
        for (j = 0; j < SHA512_DIGEST_LENGTH; j++) {
            pctx->f[j] ^= pctx->g[j];
        }
    }
    pctx->first = 0;
}
References _pbkdf2_hmac_sha512_context::f, _pbkdf2_hmac_sha512_context::first, _pbkdf2_hmac_sha512_context::g, hmac_sha512(), _pbkdf2_hmac_sha512_context::pass, _pbkdf2_hmac_sha512_context::passlen, and SHA512_DIGEST_LENGTH.
Referenced by pbkdf2_hmac_sha512().
sha256_finalize()
LIBDOGECOIN_API void sha256_finalize (sha256_context * context, uint8_t digest[SHA256_DIGEST_LENGTH])
Definition at line 578 of file sha2.c.
{
    sha2_word32* d = (sha2_word32*)digest;
    unsigned int usedspace;
    sha2_word64* t;
    /* If no digest buffer is passed, we don't bother doing this: */
    if (digest != (sha2_byte*)0) {
        usedspace = (context->bitcount >> 3) % SHA256_BLOCK_LENGTH;
#if BYTE_ORDER == LITTLE_ENDIAN
        /* Convert FROM host byte order */
        REVERSE64(context->bitcount, context->bitcount);
#endif
        if (usedspace > 0) {
            /* Begin padding with a 1 bit: */
            context->buffer[usedspace++] = 0x80;
            if (usedspace <= SHA256_SHORT_BLOCK_LENGTH) {
                /* Set-up for the last transform: */
                MEMSET_BZERO(&context->buffer[usedspace], SHA256_SHORT_BLOCK_LENGTH - usedspace);
            } else {
                if (usedspace < SHA256_BLOCK_LENGTH) {
                    MEMSET_BZERO(&context->buffer[usedspace], SHA256_BLOCK_LENGTH - usedspace);
                }
                /* Do second-to-last transform: */
                sha256_transform(context, (sha2_word32*)context->buffer);
                /* And set-up for the last transform: */
                MEMSET_BZERO(context->buffer, SHA256_SHORT_BLOCK_LENGTH);
            }
        } else {
            /* Set-up for the last transform: */
            MEMSET_BZERO(context->buffer, SHA256_SHORT_BLOCK_LENGTH);
            /* Begin padding with a 1 bit: */
            *context->buffer = 0x80;
        }
        /* Set the bit count: */
        t = (sha2_word64*)&context->buffer[SHA256_SHORT_BLOCK_LENGTH];
        *t = context->bitcount;
        /* Final transform: */
        sha256_transform(context, (sha2_word32*)context->buffer);
#if BYTE_ORDER == LITTLE_ENDIAN
        {
            /* Convert TO host byte order */
            int j;
            for (j = 0; j < 8; j++) {
                REVERSE32(context->state[j], context->state[j]);
                memcpy_safe(d++, &context->state[j], sizeof(context->state[j]));
            }
        }
#else
        MEMCPY_BCOPY(d, context->state, SHA256_DIGEST_LENGTH);
#endif
    }
    /* Clean up state data: */
    MEMSET_BZERO(context, sizeof(sha256_context));
}
References _sha256_context::bitcount, _sha256_context::buffer, MEMCPY_BCOPY, memcpy_safe(), MEMSET_BZERO, REVERSE32, REVERSE64, SHA256_BLOCK_LENGTH, SHA256_DIGEST_LENGTH, SHA256_SHORT_BLOCK_LENGTH, sha256_transform(), and _sha256_context::state.
Referenced by hmac_sha256(), hmac_sha256_finalize(), and sha256_raw().
sha256_init()
LIBDOGECOIN_API void sha256_init (sha256_context * context)
Definition at line 361 of file sha2.c.
{
    if (context == (sha256_context*)0)
        return;
    MEMCPY_BCOPY(context->state, sha256_initial_hash_value, SHA256_DIGEST_LENGTH);
    MEMSET_BZERO(context->buffer, SHA256_BLOCK_LENGTH);
    context->bitcount = 0;
}
References _sha256_context::bitcount, _sha256_context::buffer, MEMCPY_BCOPY, MEMSET_BZERO, SHA256_BLOCK_LENGTH, SHA256_DIGEST_LENGTH, sha256_initial_hash_value, and _sha256_context::state.
Referenced by hmac_sha256(), hmac_sha256_finalize(), hmac_sha256_init(), and sha256_raw().
sha256_raw()
LIBDOGECOIN_API void sha256_raw (const uint8_t * data, size_t len, uint8_t digest[SHA256_DIGEST_LENGTH])
Definition at line 635 of file sha2.c.
{
    sha256_context context;
    sha256_init(&context);
    sha256_write(&context, data, len);
    sha256_finalize(&context, digest);
}
References sha256_finalize(), sha256_init(), and sha256_write().
Referenced by dogecoin_block_header_hash(), dogecoin_dblhash(), dogecoin_hash(), dogecoin_hash_sngl_sha256(), dogecoin_hdnode_private_ckd(), dogecoin_hdnode_public_ckd(), dogecoin_tx_hash(), get_mnemonic(), hmac_sha256(), hmac_sha256_init(), and verifyP2pkhAddress().
sha256_write()
LIBDOGECOIN_API void sha256_write (sha256_context * context, const uint8_t * data, size_t len)
Definition at line 541 of file sha2.c.
{
    unsigned int freespace, usedspace;
    if (len == 0)
        return; /* Calling with no data is valid - we do nothing */
    usedspace = (context->bitcount >> 3) % SHA256_BLOCK_LENGTH;
    if (usedspace > 0) {
        /* Calculate how much free space is available in the buffer */
        freespace = SHA256_BLOCK_LENGTH - usedspace;
        if (len >= freespace) {
            /* Fill the buffer completely and process it */
            MEMCPY_BCOPY(&context->buffer[usedspace], data, freespace);
            context->bitcount += freespace << 3;
            len -= freespace;
            data += freespace;
            sha256_transform(context, (sha2_word32*)context->buffer);
        } else {
            /* The buffer is not yet full */
            MEMCPY_BCOPY(&context->buffer[usedspace], data, len);
            context->bitcount += len << 3;
            return;
        }
    }
    while (len >= SHA256_BLOCK_LENGTH) {
        /* Process as many complete blocks as we can */
        sha256_transform(context, (const sha2_word32*)data);
        context->bitcount += SHA256_BLOCK_LENGTH << 3;
        len -= SHA256_BLOCK_LENGTH;
        data += SHA256_BLOCK_LENGTH;
    }
    if (len > 0) {
        /* There's left-overs, so save 'em */
        MEMCPY_BCOPY(context->buffer, data, len);
        context->bitcount += len << 3;
    }
}
References _sha256_context::bitcount, _sha256_context::buffer, MEMCPY_BCOPY, SHA256_BLOCK_LENGTH, and sha256_transform().
Referenced by hmac_sha256(), hmac_sha256_finalize(), hmac_sha256_init(), hmac_sha256_write(), and sha256_raw().
sha512_finalize()
LIBDOGECOIN_API void sha512_finalize (sha512_context * context, uint8_t digest[SHA512_DIGEST_LENGTH])
Definition at line 895 of file sha2.c.
{
    sha2_word64* d = (sha2_word64*)digest;
    /* If no digest buffer is passed, we don't bother doing this: */
    if (digest != (sha2_byte*)0) {
        sha512_last(context);
/* Save the hash data for output: */
#if BYTE_ORDER == LITTLE_ENDIAN
        {
            /* Convert TO host byte order */
            int j;
            for (j = 0; j < 8; j++) {
                REVERSE64(context->state[j], context->state[j]);
                memcpy_safe(d++, &context->state[j], sizeof(context->state[j]));
            }
        }
#else
        MEMCPY_BCOPY(d, context->state, SHA512_DIGEST_LENGTH);
#endif
    }
    /* Zero out state data */
    MEMSET_BZERO(context, sizeof(sha512_context));
}
References MEMCPY_BCOPY, memcpy_safe(), MEMSET_BZERO, REVERSE64, SHA512_DIGEST_LENGTH, sha512_last(), and _sha512_context::state.
Referenced by hmac_sha512(), hmac_sha512_finalize(), and sha512_raw().
sha512_init()
LIBDOGECOIN_API void sha512_init (sha512_context * context)
Definition at line 644 of file sha2.c.
{
    if (context == (sha512_context*)0)
        return;
    MEMCPY_BCOPY(context->state, sha512_initial_hash_value, SHA512_DIGEST_LENGTH);
    MEMSET_BZERO(context->buffer, SHA512_BLOCK_LENGTH);
    context->bitcount[0] = context->bitcount[1] = 0;
}
References _sha512_context::bitcount, _sha512_context::buffer, MEMCPY_BCOPY, MEMSET_BZERO, SHA512_BLOCK_LENGTH, SHA512_DIGEST_LENGTH, sha512_initial_hash_value, and _sha512_context::state.
Referenced by hmac_sha512(), hmac_sha512_finalize(), hmac_sha512_init(), and sha512_raw().
sha512_raw()
LIBDOGECOIN_API void sha512_raw (const uint8_t * data, size_t len, uint8_t digest[SHA512_DIGEST_LENGTH])
Definition at line 918 of file sha2.c.
{
    sha512_context context;
    sha512_init(&context);
    sha512_write(&context, data, len);
    sha512_finalize(&context, digest);
}
References sha512_finalize(), sha512_init(), and sha512_write().
Referenced by hmac_sha512(), and hmac_sha512_init().
sha512_write()
LIBDOGECOIN_API void sha512_write (sha512_context * context, const uint8_t * data, size_t len)
Definition at line 818 of file sha2.c.
{
    unsigned int freespace, usedspace;
    if (len == 0)
        return; /* Calling with no data is valid - we do nothing */
    usedspace = (context->bitcount[0] >> 3) % SHA512_BLOCK_LENGTH;
    if (usedspace > 0) {
        /* Calculate how much free space is available in the buffer */
        freespace = SHA512_BLOCK_LENGTH - usedspace;
        if (len >= freespace) {
            /* Fill the buffer completely and process it */
            MEMCPY_BCOPY(&context->buffer[usedspace], data, freespace);
            ADDINC128(context->bitcount, freespace << 3);
            len -= freespace;
            data += freespace;
            sha512_transform(context, (sha2_word64*)context->buffer);
        } else {
            /* The buffer is not yet full */
            MEMCPY_BCOPY(&context->buffer[usedspace], data, len);
            ADDINC128(context->bitcount, len << 3);
            return;
        }
    }
    while (len >= SHA512_BLOCK_LENGTH) {
        /* Process as many complete blocks as we can */
        sha512_transform(context, (const sha2_word64*)data);
        ADDINC128(context->bitcount, SHA512_BLOCK_LENGTH << 3);
        len -= SHA512_BLOCK_LENGTH;
        data += SHA512_BLOCK_LENGTH;
    }
    if (len > 0) {
        /* There's left-overs, so save 'em */
        MEMCPY_BCOPY(context->buffer, data, len);
        ADDINC128(context->bitcount, len << 3);
    }
}
References ADDINC128, _sha512_context::bitcount, _sha512_context::buffer, MEMCPY_BCOPY, SHA512_BLOCK_LENGTH, and sha512_transform().
Referenced by hmac_sha512(), hmac_sha512_finalize(), hmac_sha512_init(), hmac_sha512_write(), and sha512_raw().