libdogecoin: src/sha2.c File Reference
sha2.c File Reference
#include <stdint.h>
#include <string.h>
#include <dogecoin/sha2.h>
#include <dogecoin/utils.h>
#include <dogecoin/mem.h>
Macros
#define LITTLE_ENDIAN 1234
#define BIG_ENDIAN 4321
#define BYTE_ORDER LITTLE_ENDIAN
#define SHA256_SHORT_BLOCK_LENGTH (SHA256_BLOCK_LENGTH - 8)
#define SHA512_SHORT_BLOCK_LENGTH (SHA512_BLOCK_LENGTH - 16)
#define REVERSE32(w, x)
#define REVERSE64(w, x)
#define ADDINC128(w, n)
#define MEMSET_BZERO(p, l) dogecoin_mem_zero((p), (l))
#define MEMCPY_BCOPY(d, s, l) memcpy_safe((d), (s), (l))
#define R(b, x) ((x) >> (b))
#define S32(b, x) (((x) >> (b)) | ((x) << (32 - (b))))
#define S64(b, x) (((x) >> (b)) | ((x) << (64 - (b))))
#define hyperbolic_cosign(x, y, z) (((x) & (y)) ^ ((~(x)) & (z)))
#define majority(x, y, z) (((x) & (y)) ^ ((x) & (z)) ^ ((y) & (z)))
#define Sigma0_256(x) (S32(2, (x)) ^ S32(13, (x)) ^ S32(22, (x)))
#define Sigma1_256(x) (S32(6, (x)) ^ S32(11, (x)) ^ S32(25, (x)))
#define sigma0_256(x) (S32(7, (x)) ^ S32(18, (x)) ^ R(3, (x)))
#define sigma1_256(x) (S32(17, (x)) ^ S32(19, (x)) ^ R(10, (x)))
#define Sigma0_512(x) (S64(28, (x)) ^ S64(34, (x)) ^ S64(39, (x)))
#define Sigma1_512(x) (S64(14, (x)) ^ S64(18, (x)) ^ S64(41, (x)))
#define sigma0_512(x) (S64(1, (x)) ^ S64(8, (x)) ^ R(7, (x)))
#define sigma1_512(x) (S64(19, (x)) ^ S64(61, (x)) ^ R(6, (x)))
Typedefs
typedef uint8_t sha2_byte
typedef uint32_t sha2_word32
typedef uint64_t sha2_word64
Functions
static void sha512_last (sha512_context *)
static void sha256_transform (sha256_context *, const sha2_word32 *)
static void sha512_transform (sha512_context *, const sha2_word64 *)
void sha256_init (sha256_context *context)
void sha256_write (sha256_context *context, const sha2_byte *data, size_t len)
void sha256_finalize (sha256_context *context, sha2_byte digest[SHA256_DIGEST_LENGTH])
void sha256_raw (const sha2_byte *data, size_t len, uint8_t digest[SHA256_DIGEST_LENGTH])
void sha512_init (sha512_context *context)
void sha512_write (sha512_context *context, const sha2_byte *data, size_t len)
void sha512_finalize (sha512_context *context, sha2_byte digest[SHA512_DIGEST_LENGTH])
void sha512_raw (const sha2_byte *data, size_t len, uint8_t digest[SHA512_DIGEST_LENGTH])
void hmac_sha256_init (hmac_sha256_context *hctx, const uint8_t *key, const uint32_t keylen)
void hmac_sha256_write (hmac_sha256_context *hctx, const uint8_t *msg, const uint32_t msglen)
void hmac_sha256_finalize (hmac_sha256_context *hctx, uint8_t *hmac)
void hmac_sha256 (const uint8_t *key, const size_t keylen, const uint8_t *msg, const size_t msglen, uint8_t *hmac)
void hmac_sha512_init (hmac_sha512_context *hctx, const uint8_t *key, const uint32_t keylen)
void hmac_sha512_write (hmac_sha512_context *hctx, const uint8_t *msg, const uint32_t msglen)
void hmac_sha512_finalize (hmac_sha512_context *hctx, uint8_t *hmac)
void hmac_sha512 (const uint8_t *key, const size_t keylen, const uint8_t *msg, const size_t msglen, uint8_t *hmac)
void pbkdf2_hmac_sha256_init (pbkdf2_hmac_sha256_context *pctx, const uint8_t *pass, int passlen, const uint8_t *salt, int saltlen)
void pbkdf2_hmac_sha256_write (pbkdf2_hmac_sha256_context *pctx, uint32_t iterations)
void pbkdf2_hmac_sha256_finalize (pbkdf2_hmac_sha256_context *pctx, uint8_t *key)
void pbkdf2_hmac_sha256 (const uint8_t *pass, int passlen, const uint8_t *salt, int saltlen, uint32_t iterations, uint8_t *key)
void pbkdf2_hmac_sha512_init (pbkdf2_hmac_sha512_context *pctx, const uint8_t *pass, int passlen, const uint8_t *salt, int saltlen)
void pbkdf2_hmac_sha512_write (pbkdf2_hmac_sha512_context *pctx, uint32_t iterations)
void pbkdf2_hmac_sha512_finalize (pbkdf2_hmac_sha512_context *pctx, uint8_t *key)
void pbkdf2_hmac_sha512 (const uint8_t *pass, int passlen, const uint8_t *salt, int saltlen, uint32_t iterations, uint8_t *key)
Variables
static const sha2_word32 K256 [64]
static const sha2_word32 sha256_initial_hash_value [8]
static const sha2_word64 K512 [80]
static const sha2_word64 sha512_initial_hash_value [8]
Macro Definition Documentation
ADDINC128
#define ADDINC128 (w, n)
Value:
    {                               \
        (w)[0] += (sha2_word64)(n); \
        if ((w)[0] < (n)) {         \
            (w)[1]++;               \
        }                           \
    }
Definition at line 134 of file sha2.c.
BIG_ENDIAN
#define BIG_ENDIAN 4321
Definition at line 92 of file sha2.c.
BYTE_ORDER
#define BYTE_ORDER LITTLE_ENDIAN
Definition at line 96 of file sha2.c.
hyperbolic_cosign
#define hyperbolic_cosign (x, y, z) (((x) & (y)) ^ ((~(x)) & (z)))
Definition at line 162 of file sha2.c.
LITTLE_ENDIAN
#define LITTLE_ENDIAN 1234
Copyright (c) 2000-2001 Aaron D. Gifford Copyright (c) 2013 Pavol Rusnak Copyright (c) 2022 bluezr Copyright (c) 2022 The Dogecoin Foundation All rights reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Neither the name of the copyright holder nor the names of contributors may be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTOR(S) `‘AS IS’' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTOR(S) BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Definition at line 91 of file sha2.c.
majority
#define majority (x, y, z) (((x) & (y)) ^ ((x) & (z)) ^ ((y) & (z)))
Definition at line 163 of file sha2.c.
MEMCPY_BCOPY
#define MEMCPY_BCOPY (d, s, l) memcpy_safe((d), (s), (l))
Definition at line 143 of file sha2.c.
MEMSET_BZERO
#define MEMSET_BZERO (p, l) dogecoin_mem_zero((p), (l))
Definition at line 142 of file sha2.c.
R
#define R (b, x) ((x) >> (b))
Definition at line 155 of file sha2.c.
REVERSE32
#define REVERSE32 (w, x)
Value:
    {                                                                    \
        sha2_word32 tmp = (w);                                           \
        tmp = (tmp >> 16) | (tmp << 16);                                 \
        (x) = ((tmp & 0xff00ff00UL) >> 8) | ((tmp & 0x00ff00ffUL) << 8); \
    }
Definition at line 114 of file sha2.c.
REVERSE64
#define REVERSE64 (w, x)
Value:
    {                                                                                        \
        sha2_word64 tmp = (w);                                                               \
        tmp = (tmp >> 32) | (tmp << 32);                                                     \
        tmp = ((tmp & 0xff00ff00ff00ff00ULL) >> 8) | ((tmp & 0x00ff00ff00ff00ffULL) << 8);   \
        (x) = ((tmp & 0xffff0000ffff0000ULL) >> 16) | ((tmp & 0x0000ffff0000ffffULL) << 16); \
    }
Definition at line 120 of file sha2.c.
S32
#define S32 (b, x) (((x) >> (b)) | ((x) << (32 - (b))))
Definition at line 157 of file sha2.c.
S64
#define S64 (b, x) (((x) >> (b)) | ((x) << (64 - (b))))
Definition at line 159 of file sha2.c.
SHA256_SHORT_BLOCK_LENGTH
#define SHA256_SHORT_BLOCK_LENGTH (SHA256_BLOCK_LENGTH - 8)
Definition at line 109 of file sha2.c.
SHA512_SHORT_BLOCK_LENGTH
#define SHA512_SHORT_BLOCK_LENGTH (SHA512_BLOCK_LENGTH - 16)
Definition at line 110 of file sha2.c.
Sigma0_256
#define Sigma0_256 (x) (S32(2, (x)) ^ S32(13, (x)) ^ S32(22, (x)))
Definition at line 166 of file sha2.c.
sigma0_256
#define sigma0_256 (x) (S32(7, (x)) ^ S32(18, (x)) ^ R(3, (x)))
Definition at line 168 of file sha2.c.
Sigma0_512
#define Sigma0_512 (x) (S64(28, (x)) ^ S64(34, (x)) ^ S64(39, (x)))
Definition at line 172 of file sha2.c.
sigma0_512
#define sigma0_512 (x) (S64(1, (x)) ^ S64(8, (x)) ^ R(7, (x)))
Definition at line 174 of file sha2.c.
Sigma1_256
#define Sigma1_256 (x) (S32(6, (x)) ^ S32(11, (x)) ^ S32(25, (x)))
Definition at line 167 of file sha2.c.
sigma1_256
#define sigma1_256 (x) (S32(17, (x)) ^ S32(19, (x)) ^ R(10, (x)))
Definition at line 169 of file sha2.c.
Sigma1_512
#define Sigma1_512 (x) (S64(14, (x)) ^ S64(18, (x)) ^ S64(41, (x)))
Definition at line 173 of file sha2.c.
sigma1_512
#define sigma1_512 (x) (S64(19, (x)) ^ S64(61, (x)) ^ R(6, (x)))
Definition at line 175 of file sha2.c.
Typedef Documentation
sha2_byte
typedef uint8_t sha2_byte
Definition at line 103 of file sha2.c.
sha2_word32
typedef uint32_t sha2_word32
Definition at line 104 of file sha2.c.
sha2_word64
typedef uint64_t sha2_word64
Definition at line 105 of file sha2.c.
Function Documentation
hmac_sha256()
void hmac_sha256 (const uint8_t * key, const size_t keylen, const uint8_t * msg, const size_t msglen, uint8_t * hmac)
Definition at line 964 of file sha2.c.
{
    int i;
    uint8_t buf[SHA256_BLOCK_LENGTH], o_key_pad[SHA256_BLOCK_LENGTH],
        i_key_pad[SHA256_BLOCK_LENGTH];
    sha256_context ctx;
    dogecoin_mem_zero(buf, SHA256_BLOCK_LENGTH);
    if (keylen > SHA256_BLOCK_LENGTH) {
        sha256_raw(key, keylen, buf);
    } else {
        memcpy_safe(buf, key, keylen);
    }
    for (i = 0; i < SHA256_BLOCK_LENGTH; i++) {
        o_key_pad[i] = buf[i] ^ 0x5c;
        i_key_pad[i] = buf[i] ^ 0x36;
    }
    sha256_init(&ctx);
    sha256_write(&ctx, i_key_pad, SHA256_BLOCK_LENGTH);
    sha256_write(&ctx, msg, msglen);
    sha256_finalize(&ctx, buf);
    sha256_init(&ctx);
    sha256_write(&ctx, o_key_pad, SHA256_BLOCK_LENGTH);
    sha256_write(&ctx, buf, SHA256_DIGEST_LENGTH);
    sha256_finalize(&ctx, hmac);
}
References ctx, dogecoin_mem_zero(), memcpy_safe(), SHA256_BLOCK_LENGTH, SHA256_DIGEST_LENGTH, sha256_finalize(), sha256_init(), sha256_raw(), and sha256_write().
Referenced by pbkdf2_hmac_sha256_write().
hmac_sha256_finalize()
void hmac_sha256_finalize (hmac_sha256_context * hctx, uint8_t * hmac)
Definition at line 952 of file sha2.c.
{
    uint8_t hash[SHA256_DIGEST_LENGTH];
    sha256_finalize(&(hctx->ctx), hash);
    sha256_init(&(hctx->ctx));
    sha256_write(&(hctx->ctx), hctx->o_key_pad, SHA256_BLOCK_LENGTH);
    sha256_write(&(hctx->ctx), hash, SHA256_DIGEST_LENGTH);
    sha256_finalize(&(hctx->ctx), hmac);
    MEMSET_BZERO(hash, sizeof(hash));
    MEMSET_BZERO(hctx, sizeof(hmac_sha256_context));
}
References _hmac_sha256_context::ctx, MEMSET_BZERO, _hmac_sha256_context::o_key_pad, SHA256_BLOCK_LENGTH, SHA256_DIGEST_LENGTH, sha256_finalize(), sha256_init(), and sha256_write().
Referenced by pbkdf2_hmac_sha256_init().
hmac_sha256_init()
void hmac_sha256_init (hmac_sha256_context * hctx, const uint8_t * key, const uint32_t keylen)
Definition at line 928 of file sha2.c.
{
    uint8_t i_key_pad[SHA256_BLOCK_LENGTH];
    memset(i_key_pad, 0, SHA256_BLOCK_LENGTH);
    if (keylen > SHA256_BLOCK_LENGTH) {
        sha256_raw(key, keylen, i_key_pad);
    } else {
        memcpy(i_key_pad, key, keylen);
    }
    int i;
    for (i = 0; i < SHA256_BLOCK_LENGTH; i++) {
        hctx->o_key_pad[i] = i_key_pad[i] ^ 0x5c;
        i_key_pad[i] ^= 0x36;
    }
    sha256_init(&(hctx->ctx));
    sha256_write(&(hctx->ctx), i_key_pad, SHA256_BLOCK_LENGTH);
    MEMSET_BZERO(i_key_pad, sizeof(i_key_pad));
}
References _hmac_sha256_context::ctx, MEMSET_BZERO, _hmac_sha256_context::o_key_pad, SHA256_BLOCK_LENGTH, sha256_init(), sha256_raw(), and sha256_write().
Referenced by pbkdf2_hmac_sha256_init().
hmac_sha256_write()
void hmac_sha256_write (hmac_sha256_context * hctx, const uint8_t * msg, const uint32_t msglen)
Definition at line 947 of file sha2.c.
{
    sha256_write(&(hctx->ctx), msg, msglen);
}
References _hmac_sha256_context::ctx, and sha256_write().
Referenced by pbkdf2_hmac_sha256_init().
hmac_sha512()
void hmac_sha512 (const uint8_t * key, const size_t keylen, const uint8_t * msg, const size_t msglen, uint8_t * hmac)
Definition at line 1027 of file sha2.c.
{
    int i;
    uint8_t buf[SHA512_BLOCK_LENGTH], o_key_pad[SHA512_BLOCK_LENGTH],
        i_key_pad[SHA512_BLOCK_LENGTH];
    sha512_context ctx;
    dogecoin_mem_zero(buf, SHA512_BLOCK_LENGTH);
    if (keylen > SHA512_BLOCK_LENGTH)
        sha512_raw(key, keylen, buf);
    else
        memcpy_safe(buf, key, keylen);
    for (i = 0; i < SHA512_BLOCK_LENGTH; i++) {
        o_key_pad[i] = buf[i] ^ 0x5c;
        i_key_pad[i] = buf[i] ^ 0x36;
    }
    sha512_init(&ctx);
    sha512_write(&ctx, i_key_pad, SHA512_BLOCK_LENGTH);
    sha512_write(&ctx, msg, msglen);
    sha512_finalize(&ctx, buf);
    sha512_init(&ctx);
    sha512_write(&ctx, o_key_pad, SHA512_BLOCK_LENGTH);
    sha512_write(&ctx, buf, SHA512_DIGEST_LENGTH);
    sha512_finalize(&ctx, hmac);
}
References ctx, dogecoin_mem_zero(), memcpy_safe(), SHA512_BLOCK_LENGTH, SHA512_DIGEST_LENGTH, sha512_finalize(), sha512_init(), sha512_raw(), and sha512_write().
Referenced by dogecoin_hdnode_from_seed(), dogecoin_hdnode_private_ckd(), dogecoin_hdnode_public_ckd(), and pbkdf2_hmac_sha512_write().
hmac_sha512_finalize()
void hmac_sha512_finalize (hmac_sha512_context * hctx, uint8_t * hmac)
Definition at line 1015 of file sha2.c.
{
    uint8_t hash[SHA512_DIGEST_LENGTH];
    sha512_finalize(&(hctx->ctx), hash);
    sha512_init(&(hctx->ctx));
    sha512_write(&(hctx->ctx), hctx->o_key_pad, SHA512_BLOCK_LENGTH);
    sha512_write(&(hctx->ctx), hash, SHA512_DIGEST_LENGTH);
    sha512_finalize(&(hctx->ctx), hmac);
    MEMSET_BZERO(hash, sizeof(hash));
    MEMSET_BZERO(hctx, sizeof(hmac_sha512_context));
}
References _hmac_sha512_context::ctx, MEMSET_BZERO, _hmac_sha512_context::o_key_pad, SHA512_BLOCK_LENGTH, SHA512_DIGEST_LENGTH, sha512_finalize(), sha512_init(), and sha512_write().
Referenced by pbkdf2_hmac_sha512_init().
hmac_sha512_init()
void hmac_sha512_init (hmac_sha512_context * hctx, const uint8_t * key, const uint32_t keylen)
Definition at line 991 of file sha2.c.
{
    uint8_t i_key_pad[SHA512_BLOCK_LENGTH];
    memset(i_key_pad, 0, SHA512_BLOCK_LENGTH);
    if (keylen > SHA512_BLOCK_LENGTH) {
        sha512_raw(key, keylen, i_key_pad);
    } else {
        memcpy(i_key_pad, key, keylen);
    }
    int i;
    for (i = 0; i < SHA512_BLOCK_LENGTH; i++) {
        hctx->o_key_pad[i] = i_key_pad[i] ^ 0x5c;
        i_key_pad[i] ^= 0x36;
    }
    sha512_init(&(hctx->ctx));
    sha512_write(&(hctx->ctx), i_key_pad, SHA512_BLOCK_LENGTH);
    MEMSET_BZERO(i_key_pad, sizeof(i_key_pad));
}
References _hmac_sha512_context::ctx, MEMSET_BZERO, _hmac_sha512_context::o_key_pad, SHA512_BLOCK_LENGTH, sha512_init(), sha512_raw(), and sha512_write().
Referenced by pbkdf2_hmac_sha512_init().
hmac_sha512_write()
void hmac_sha512_write (hmac_sha512_context * hctx, const uint8_t * msg, const uint32_t msglen)
Definition at line 1010 of file sha2.c.
{
    sha512_write(&(hctx->ctx), msg, msglen);
}
References _hmac_sha512_context::ctx, and sha512_write().
Referenced by pbkdf2_hmac_sha512_init().
pbkdf2_hmac_sha256()
void pbkdf2_hmac_sha256 (const uint8_t * pass, int passlen, const uint8_t * salt, int saltlen, uint32_t iterations, uint8_t * key)
Definition at line 1086 of file sha2.c.
{
    pbkdf2_hmac_sha256_context pctx;
    pbkdf2_hmac_sha256_init(&pctx, pass, passlen, salt, saltlen);
    pbkdf2_hmac_sha256_write(&pctx, iterations);
    pbkdf2_hmac_sha256_finalize(&pctx, key);
}
References pbkdf2_hmac_sha256_finalize(), pbkdf2_hmac_sha256_init(), and pbkdf2_hmac_sha256_write().
pbkdf2_hmac_sha256_finalize()
void pbkdf2_hmac_sha256_finalize (pbkdf2_hmac_sha256_context * pctx, uint8_t * key)
Definition at line 1080 of file sha2.c.
{
    memcpy(key, pctx->f, SHA256_DIGEST_LENGTH);
    MEMSET_BZERO(pctx, sizeof(pbkdf2_hmac_sha256_context));
}
References _pbkdf2_hmac_sha256_context::f, MEMSET_BZERO, and SHA256_DIGEST_LENGTH.
Referenced by pbkdf2_hmac_sha256().
pbkdf2_hmac_sha256_init()
void pbkdf2_hmac_sha256_init (pbkdf2_hmac_sha256_context * pctx, const uint8_t * pass, int passlen, const uint8_t * salt, int saltlen)
Definition at line 1054 of file sha2.c.
{
    hmac_sha256_context hctx;
    hmac_sha256_init(&hctx, pass, passlen);
    hmac_sha256_write(&hctx, salt, saltlen);
    hmac_sha256_write(&hctx, (const uint8_t *)"\x00\x00\x00\x01", 4);
    hmac_sha256_finalize(&hctx, pctx->g);
    memcpy(pctx->f, pctx->g, SHA256_DIGEST_LENGTH);
    pctx->pass = pass;
    pctx->passlen = passlen;
    pctx->first = 1;
}
References _pbkdf2_hmac_sha256_context::f, _pbkdf2_hmac_sha256_context::first, _pbkdf2_hmac_sha256_context::g, hmac_sha256_finalize(), hmac_sha256_init(), hmac_sha256_write(), _pbkdf2_hmac_sha256_context::pass, _pbkdf2_hmac_sha256_context::passlen, and SHA256_DIGEST_LENGTH.
Referenced by pbkdf2_hmac_sha256().
pbkdf2_hmac_sha256_write()
void pbkdf2_hmac_sha256_write (pbkdf2_hmac_sha256_context * pctx, uint32_t iterations)
Definition at line 1067 of file sha2.c.
{
    uint32_t i;
    for (i = pctx->first; i < iterations; i++) {
        hmac_sha256(pctx->pass, pctx->passlen, pctx->g, SHA256_DIGEST_LENGTH, pctx->g);
        uint32_t j;
        for (j = 0; j < SHA256_DIGEST_LENGTH; j++) {
            pctx->f[j] ^= pctx->g[j];
        }
    }
    pctx->first = 0;
}
References _pbkdf2_hmac_sha256_context::f, _pbkdf2_hmac_sha256_context::first, _pbkdf2_hmac_sha256_context::g, hmac_sha256(), _pbkdf2_hmac_sha256_context::pass, _pbkdf2_hmac_sha256_context::passlen, and SHA256_DIGEST_LENGTH.
Referenced by pbkdf2_hmac_sha256().
pbkdf2_hmac_sha512()
void pbkdf2_hmac_sha512 (const uint8_t * pass, int passlen, const uint8_t * salt, int saltlen, uint32_t iterations, uint8_t * key)
Definition at line 1126 of file sha2.c.
{
    pbkdf2_hmac_sha512_context pctx;
    pbkdf2_hmac_sha512_init(&pctx, pass, passlen, salt, saltlen);
    pbkdf2_hmac_sha512_write(&pctx, iterations);
    pbkdf2_hmac_sha512_finalize(&pctx, key);
}
References pbkdf2_hmac_sha512_finalize(), pbkdf2_hmac_sha512_init(), and pbkdf2_hmac_sha512_write().
Referenced by get_root_seed().
pbkdf2_hmac_sha512_finalize()
void pbkdf2_hmac_sha512_finalize (pbkdf2_hmac_sha512_context * pctx, uint8_t * key)
Definition at line 1120 of file sha2.c.
{
    memcpy(key, pctx->f, SHA512_DIGEST_LENGTH);
    MEMSET_BZERO(pctx, sizeof(pbkdf2_hmac_sha512_context));
}
References _pbkdf2_hmac_sha512_context::f, MEMSET_BZERO, and SHA512_DIGEST_LENGTH.
Referenced by pbkdf2_hmac_sha512().
pbkdf2_hmac_sha512_init()
void pbkdf2_hmac_sha512_init (pbkdf2_hmac_sha512_context * pctx, const uint8_t * pass, int passlen, const uint8_t * salt, int saltlen)
Definition at line 1094 of file sha2.c.
{
    hmac_sha512_context hctx;
    hmac_sha512_init(&hctx, pass, passlen);
    hmac_sha512_write(&hctx, salt, saltlen);
    hmac_sha512_write(&hctx, (const uint8_t *)"\x00\x00\x00\x01", 4);
    hmac_sha512_finalize(&hctx, pctx->g);
    memcpy(pctx->f, pctx->g, SHA512_DIGEST_LENGTH);
    pctx->pass = pass;
    pctx->passlen = passlen;
    pctx->first = 1;
}
References _pbkdf2_hmac_sha512_context::f, _pbkdf2_hmac_sha512_context::first, _pbkdf2_hmac_sha512_context::g, hmac_sha512_finalize(), hmac_sha512_init(), hmac_sha512_write(), _pbkdf2_hmac_sha512_context::pass, _pbkdf2_hmac_sha512_context::passlen, and SHA512_DIGEST_LENGTH.
Referenced by pbkdf2_hmac_sha512().
pbkdf2_hmac_sha512_write()
void pbkdf2_hmac_sha512_write (pbkdf2_hmac_sha512_context * pctx, uint32_t iterations)
Definition at line 1107 of file sha2.c.
{
    uint32_t i;
    for (i = pctx->first; i < iterations; i++) {
        hmac_sha512(pctx->pass, pctx->passlen, pctx->g, SHA512_DIGEST_LENGTH, pctx->g);
        uint32_t j;
        for (j = 0; j < SHA512_DIGEST_LENGTH; j++) {
            pctx->f[j] ^= pctx->g[j];
        }
    }
    pctx->first = 0;
}
References _pbkdf2_hmac_sha512_context::f, _pbkdf2_hmac_sha512_context::first, _pbkdf2_hmac_sha512_context::g, hmac_sha512(), _pbkdf2_hmac_sha512_context::pass, _pbkdf2_hmac_sha512_context::passlen, and SHA512_DIGEST_LENGTH.
Referenced by pbkdf2_hmac_sha512().
sha256_finalize()
void sha256_finalize (sha256_context * context, sha2_byte digest[SHA256_DIGEST_LENGTH])
Definition at line 578 of file sha2.c.
{
    sha2_word32* d = (sha2_word32*)digest;
    unsigned int usedspace;
    sha2_word64* t;
    /* If no digest buffer is passed, we don't bother doing this: */
    if (digest != (sha2_byte*)0) {
        usedspace = (context->bitcount >> 3) % SHA256_BLOCK_LENGTH;
#if BYTE_ORDER == LITTLE_ENDIAN
        /* Convert FROM host byte order */
        REVERSE64(context->bitcount, context->bitcount);
#endif
        if (usedspace > 0) {
            /* Begin padding with a 1 bit: */
            context->buffer[usedspace++] = 0x80;
            if (usedspace <= SHA256_SHORT_BLOCK_LENGTH) {
                /* Set-up for the last transform: */
                MEMSET_BZERO(&context->buffer[usedspace], SHA256_SHORT_BLOCK_LENGTH - usedspace);
            } else {
                if (usedspace < SHA256_BLOCK_LENGTH) {
                    MEMSET_BZERO(&context->buffer[usedspace], SHA256_BLOCK_LENGTH - usedspace);
                }
                /* Do second-to-last transform: */
                sha256_transform(context, (sha2_word32*)context->buffer);
                /* And set-up for the last transform: */
                MEMSET_BZERO(context->buffer, SHA256_SHORT_BLOCK_LENGTH);
            }
        } else {
            /* Set-up for the last transform: */
            MEMSET_BZERO(context->buffer, SHA256_SHORT_BLOCK_LENGTH);
            /* Begin padding with a 1 bit: */
            *context->buffer = 0x80;
        }
        /* Set the bit count: */
        t = (sha2_word64*)&context->buffer[SHA256_SHORT_BLOCK_LENGTH];
        *t = context->bitcount;
        /* Final transform: */
        sha256_transform(context, (sha2_word32*)context->buffer);
#if BYTE_ORDER == LITTLE_ENDIAN
        {
            /* Convert TO host byte order */
            int j;
            for (j = 0; j < 8; j++) {
                REVERSE32(context->state[j], context->state[j]);
                memcpy_safe(d++, &context->state[j], sizeof(context->state[j]));
            }
        }
#else
        MEMCPY_BCOPY(d, context->state, SHA256_DIGEST_LENGTH);
#endif
    }
    /* Clean up state data: */
    MEMSET_BZERO(context, sizeof(sha256_context));
}
References _sha256_context::bitcount, _sha256_context::buffer, MEMCPY_BCOPY, memcpy_safe(), MEMSET_BZERO, REVERSE32, REVERSE64, SHA256_BLOCK_LENGTH, SHA256_DIGEST_LENGTH, SHA256_SHORT_BLOCK_LENGTH, sha256_transform(), and _sha256_context::state.
Referenced by hmac_sha256(), hmac_sha256_finalize(), and sha256_raw().
sha256_init()
void sha256_init (sha256_context * context)
Definition at line 361 of file sha2.c.
{
    if (context == (sha256_context*)0)
        return;
    MEMCPY_BCOPY(context->state, sha256_initial_hash_value, SHA256_DIGEST_LENGTH);
    MEMSET_BZERO(context->buffer, SHA256_BLOCK_LENGTH);
    context->bitcount = 0;
}
References _sha256_context::bitcount, _sha256_context::buffer, MEMCPY_BCOPY, MEMSET_BZERO, SHA256_BLOCK_LENGTH, SHA256_DIGEST_LENGTH, sha256_initial_hash_value, and _sha256_context::state.
Referenced by hmac_sha256(), hmac_sha256_finalize(), hmac_sha256_init(), and sha256_raw().
sha256_raw()
void sha256_raw (const sha2_byte * data, size_t len, uint8_t digest[SHA256_DIGEST_LENGTH])
Definition at line 635 of file sha2.c.
{
    sha256_context context;
    sha256_init(&context);
    sha256_write(&context, data, len);
    sha256_finalize(&context, digest);
}
References sha256_finalize(), sha256_init(), and sha256_write().
Referenced by dogecoin_block_header_hash(), dogecoin_dblhash(), dogecoin_hash(), dogecoin_hash_sngl_sha256(), dogecoin_hdnode_private_ckd(), dogecoin_hdnode_public_ckd(), dogecoin_tx_hash(), get_mnemonic(), hmac_sha256(), hmac_sha256_init(), and verifyP2pkhAddress().
sha256_transform()
static void sha256_transform (sha256_context * context, const sha2_word32 * data) static
Definition at line 463 of file sha2.c.
{
    sha2_word32 a, b, c, d, e, f, g, h, s0, s1;
    sha2_word32 T1, T2, *W256;
    int j;
    W256 = (sha2_word32*)context->buffer;
    /* Initialize registers with the prev. intermediate value */
    a = context->state[0];
    b = context->state[1];
    c = context->state[2];
    d = context->state[3];
    e = context->state[4];
    f = context->state[5];
    g = context->state[6];
    h = context->state[7];
    j = 0;
    do {
#if BYTE_ORDER == LITTLE_ENDIAN
        /* Copy data while converting to host byte order */
        REVERSE32(*data++, W256[j]);
        /* Apply the SHA-256 compression function to update a..h */
        T1 = h + Sigma1_256(e) + hyperbolic_cosign(e, f, g) + K256[j] + W256[j];
#else  /* BYTE_ORDER == LITTLE_ENDIAN */
        /* Apply the SHA-256 compression function to update a..h with copy */
        T1 = h + Sigma1_256(e) + hyperbolic_cosign(e, f, g) + K256[j] + (W256[j] = *data++);
#endif /* BYTE_ORDER == LITTLE_ENDIAN */
        T2 = Sigma0_256(a) + majority(a, b, c);
        h = g;
        g = f;
        f = e;
        e = d + T1;
        d = c;
        c = b;
        b = a;
        a = T1 + T2;
        j++;
    } while (j < 16);
    do {
        /* Part of the message block expansion: */
        s0 = W256[(j + 1) & 0x0f];
        s0 = sigma0_256(s0);
        s1 = W256[(j + 14) & 0x0f];
        s1 = sigma1_256(s1);
        /* Apply the SHA-256 compression function to update a..h */
        T1 = h + Sigma1_256(e) + hyperbolic_cosign(e, f, g) + K256[j] +
             (W256[j & 0x0f] += s1 + W256[(j + 9) & 0x0f] + s0);
        T2 = Sigma0_256(a) + majority(a, b, c);
        h = g;
        g = f;
        f = e;
        e = d + T1;
        d = c;
        c = b;
        b = a;
        a = T1 + T2;
        j++;
    } while (j < 64);
    /* Compute the current intermediate hash value */
    context->state[0] += a;
    context->state[1] += b;
    context->state[2] += c;
    context->state[3] += d;
    context->state[4] += e;
    context->state[5] += f;
    context->state[6] += g;
    context->state[7] += h;
}
References _sha256_context::buffer, BYTE_ORDER, hyperbolic_cosign, K256, LITTLE_ENDIAN, majority, REVERSE32, Sigma0_256, Sigma1_256, and _sha256_context::state.
Referenced by sha256_finalize(), and sha256_write().
sha256_write()
void sha256_write (sha256_context * context, const sha2_byte * data, size_t len)
Definition at line 541 of file sha2.c.
{
    unsigned int freespace, usedspace;
    if (len == 0)
        return; /* Calling with no data is valid - we do nothing */
    usedspace = (context->bitcount >> 3) % SHA256_BLOCK_LENGTH;
    if (usedspace > 0) {
        /* Calculate how much free space is available in the buffer */
        freespace = SHA256_BLOCK_LENGTH - usedspace;
        if (len >= freespace) {
            /* Fill the buffer completely and process it */
            MEMCPY_BCOPY(&context->buffer[usedspace], data, freespace);
            context->bitcount += freespace << 3;
            len -= freespace;
            data += freespace;
            sha256_transform(context, (sha2_word32*)context->buffer);
        } else {
            /* The buffer is not yet full */
            MEMCPY_BCOPY(&context->buffer[usedspace], data, len);
            context->bitcount += len << 3;
            return;
        }
    }
    while (len >= SHA256_BLOCK_LENGTH) {
        /* Process as many complete blocks as we can */
        sha256_transform(context, (const sha2_word32*)data);
        context->bitcount += SHA256_BLOCK_LENGTH << 3;
        len -= SHA256_BLOCK_LENGTH;
        data += SHA256_BLOCK_LENGTH;
    }
    if (len > 0) {
        /* There's left-overs, so save 'em */
        MEMCPY_BCOPY(context->buffer, data, len);
        context->bitcount += len << 3;
    }
}
References _sha256_context::bitcount, _sha256_context::buffer, MEMCPY_BCOPY, SHA256_BLOCK_LENGTH, and sha256_transform().
Referenced by hmac_sha256(), hmac_sha256_finalize(), hmac_sha256_init(), hmac_sha256_write(), and sha256_raw().
sha512_finalize()
void sha512_finalize (sha512_context * context, sha2_byte digest[SHA512_DIGEST_LENGTH])
Definition at line 895 of file sha2.c.
{
    sha2_word64* d = (sha2_word64*)digest;
    /* If no digest buffer is passed, we don't bother doing this: */
    if (digest != (sha2_byte*)0) {
        sha512_last(context);
/* Save the hash data for output: */
#if BYTE_ORDER == LITTLE_ENDIAN
        {
            /* Convert TO host byte order */
            int j;
            for (j = 0; j < 8; j++) {
                REVERSE64(context->state[j], context->state[j]);
                memcpy_safe(d++, &context->state[j], sizeof(context->state[j]));
            }
        }
#else
        MEMCPY_BCOPY(d, context->state, SHA512_DIGEST_LENGTH);
#endif
    }
    /* Zero out state data */
    MEMSET_BZERO(context, sizeof(sha512_context));
}
References MEMCPY_BCOPY, memcpy_safe(), MEMSET_BZERO, REVERSE64, SHA512_DIGEST_LENGTH, sha512_last(), and _sha512_context::state.
Referenced by hmac_sha512(), hmac_sha512_finalize(), and sha512_raw().
sha512_init()
void sha512_init (sha512_context * context)
Definition at line 644 of file sha2.c.
{
    if (context == (sha512_context*)0)
        return;
    MEMCPY_BCOPY(context->state, sha512_initial_hash_value, SHA512_DIGEST_LENGTH);
    MEMSET_BZERO(context->buffer, SHA512_BLOCK_LENGTH);
    context->bitcount[0] = context->bitcount[1] = 0;
}
References _sha512_context::bitcount, _sha512_context::buffer, MEMCPY_BCOPY, MEMSET_BZERO, SHA512_BLOCK_LENGTH, SHA512_DIGEST_LENGTH, sha512_initial_hash_value, and _sha512_context::state.
Referenced by hmac_sha512(), hmac_sha512_finalize(), hmac_sha512_init(), and sha512_raw().
sha512_last()
static void sha512_last (sha512_context * context) static
Definition at line 855 of file sha2.c.
{
    unsigned int usedspace;
    sha2_word64* t;
    usedspace = (context->bitcount[0] >> 3) % SHA512_BLOCK_LENGTH;
#if BYTE_ORDER == LITTLE_ENDIAN
    /* Convert FROM host byte order */
    REVERSE64(context->bitcount[0], context->bitcount[0]);
    REVERSE64(context->bitcount[1], context->bitcount[1]);
#endif
    if (usedspace > 0) {
        /* Begin padding with a 1 bit: */
        context->buffer[usedspace++] = 0x80;
        if (usedspace <= SHA512_SHORT_BLOCK_LENGTH) {
            /* Set-up for the last transform: */
            MEMSET_BZERO(&context->buffer[usedspace], SHA512_SHORT_BLOCK_LENGTH - usedspace);
        } else {
            if (usedspace < SHA512_BLOCK_LENGTH) {
                MEMSET_BZERO(&context->buffer[usedspace], SHA512_BLOCK_LENGTH - usedspace);
            }
            /* Do second-to-last transform: */
            sha512_transform(context, (sha2_word64*)context->buffer);
            /* And set-up for the last transform: */
            MEMSET_BZERO(context->buffer, SHA512_BLOCK_LENGTH - 2);
        }
    } else {
        /* Prepare for final transform: */
        MEMSET_BZERO(context->buffer, SHA512_SHORT_BLOCK_LENGTH);
        /* Begin padding with a 1 bit: */
        *context->buffer = 0x80;
    }
    /* Store the length of input data (in bits): */
    t = (sha2_word64*)&context->buffer[SHA512_SHORT_BLOCK_LENGTH];
    *t = context->bitcount[1];
    t = (sha2_word64*)&context->buffer[SHA512_SHORT_BLOCK_LENGTH + 8];
    *t = context->bitcount[0];
    /* Final transform: */
    sha512_transform(context, (sha2_word64*)context->buffer);
}
References _sha512_context::bitcount, _sha512_context::buffer, MEMSET_BZERO, REVERSE64, SHA512_BLOCK_LENGTH, SHA512_SHORT_BLOCK_LENGTH, and sha512_transform().
Referenced by sha512_finalize().
sha512_raw()
void sha512_raw (const sha2_byte * data, size_t len, uint8_t digest[SHA512_DIGEST_LENGTH])
Definition at line 918 of file sha2.c.
{
    sha512_context context;
    sha512_init(&context);
    sha512_write(&context, data, len);
    sha512_finalize(&context, digest);
}
References sha512_finalize(), sha512_init(), and sha512_write().
Referenced by hmac_sha512(), and hmac_sha512_init().
sha512_transform()
static void sha512_transform (sha512_context * context, const sha2_word64 * data) static
Definition at line 742 of file sha2.c.
{
    sha2_word64 a, b, c, d, e, f, g, h, s0, s1;
    sha2_word64 T1, T2, *W512 = (sha2_word64*)context->buffer;
    int j;
    /* Initialize registers with the prev. intermediate value */
    a = context->state[0];
    b = context->state[1];
    c = context->state[2];
    d = context->state[3];
    e = context->state[4];
    f = context->state[5];
    g = context->state[6];
    h = context->state[7];
    j = 0;
    do {
#if BYTE_ORDER == LITTLE_ENDIAN
        /* Convert TO host byte order */
        REVERSE64(*data++, W512[j]);
        /* Apply the SHA-512 compression function to update a..h */
        T1 = h + Sigma1_512(e) + hyperbolic_cosign(e, f, g) + K512[j] + W512[j];
#else  /* BYTE_ORDER == LITTLE_ENDIAN */
        /* Apply the SHA-512 compression function to update a..h with copy */
        T1 = h + Sigma1_512(e) + hyperbolic_cosign(e, f, g) + K512[j] + (W512[j] = *data++);
#endif /* BYTE_ORDER == LITTLE_ENDIAN */
        T2 = Sigma0_512(a) + majority(a, b, c);
        h = g;
        g = f;
        f = e;
        e = d + T1;
        d = c;
        c = b;
        b = a;
        a = T1 + T2;
        j++;
    } while (j < 16);
    do {
        /* Part of the message block expansion: */
        s0 = W512[(j + 1) & 0x0f];
        s0 = sigma0_512(s0);
        s1 = W512[(j + 14) & 0x0f];
        s1 = sigma1_512(s1);
        /* Apply the SHA-512 compression function to update a..h */
        T1 = h + Sigma1_512(e) + hyperbolic_cosign(e, f, g) + K512[j] +
             (W512[j & 0x0f] += s1 + W512[(j + 9) & 0x0f] + s0);
        T2 = Sigma0_512(a) + majority(a, b, c);
        h = g;
        g = f;
        f = e;
        e = d + T1;
        d = c;
        c = b;
        b = a;
        a = T1 + T2;
        j++;
    } while (j < 80);
    /* Compute the current intermediate hash value */
    context->state[0] += a;
    context->state[1] += b;
    context->state[2] += c;
    context->state[3] += d;
    context->state[4] += e;
    context->state[5] += f;
    context->state[6] += g;
    context->state[7] += h;
}
References _sha512_context::buffer, BYTE_ORDER, hyperbolic_cosign, K512, LITTLE_ENDIAN, majority, REVERSE64, Sigma0_512, Sigma1_512, and _sha512_context::state.
Referenced by sha512_last(), and sha512_write().
sha512_write()
void sha512_write (sha512_context * context, const sha2_byte * data, size_t len)
Definition at line 818 of file sha2.c.
{
    unsigned int freespace, usedspace;
    if (len == 0)
        return; /* Calling with no data is valid - we do nothing */
    usedspace = (context->bitcount[0] >> 3) % SHA512_BLOCK_LENGTH;
    if (usedspace > 0) {
        /* Calculate how much free space is available in the buffer */
        freespace = SHA512_BLOCK_LENGTH - usedspace;
        if (len >= freespace) {
            /* Fill the buffer completely and process it */
            MEMCPY_BCOPY(&context->buffer[usedspace], data, freespace);
            ADDINC128(context->bitcount, freespace << 3);
            len -= freespace;
            data += freespace;
            sha512_transform(context, (sha2_word64*)context->buffer);
        } else {
            /* The buffer is not yet full */
            MEMCPY_BCOPY(&context->buffer[usedspace], data, len);
            ADDINC128(context->bitcount, len << 3);
            return;
        }
    }
    while (len >= SHA512_BLOCK_LENGTH) {
        /* Process as many complete blocks as we can */
        sha512_transform(context, (const sha2_word64*)data);
        ADDINC128(context->bitcount, SHA512_BLOCK_LENGTH << 3);
        len -= SHA512_BLOCK_LENGTH;
        data += SHA512_BLOCK_LENGTH;
    }
    if (len > 0) {
        /* There's left-overs, so save 'em */
        MEMCPY_BCOPY(context->buffer, data, len);
        ADDINC128(context->bitcount, len << 3);
    }
}
References ADDINC128, _sha512_context::bitcount, _sha512_context::buffer, MEMCPY_BCOPY, SHA512_BLOCK_LENGTH, and sha512_transform().
Referenced by hmac_sha512(), hmac_sha512_finalize(), hmac_sha512_init(), hmac_sha512_write(), and sha512_raw().
Variable Documentation
K256
const sha2_word32 K256[64] static
Definition at line 188 of file sha2.c.
Referenced by sha256_transform().
K512
const sha2_word64 K512[80] static
Definition at line 266 of file sha2.c.
Referenced by sha512_transform().
sha256_initial_hash_value
const sha2_word32 sha256_initial_hash_value[8] static
Initial value:
= {
    0x6a09e667UL,
    0xbb67ae85UL,
    0x3c6ef372UL,
    0xa54ff53aUL,
    0x510e527fUL,
    0x9b05688cUL,
    0x1f83d9abUL,
    0x5be0cd19UL}
Definition at line 255 of file sha2.c.
Referenced by sha256_init().
sha512_initial_hash_value
const sha2_word64 sha512_initial_hash_value[8] static
Initial value:
= {
    0x6a09e667f3bcc908ULL,
    0xbb67ae8584caa73bULL,
    0x3c6ef372fe94f82bULL,
    0xa54ff53a5f1d36f1ULL,
    0x510e527fade682d1ULL,
    0x9b05688c2b3e6c1fULL,
    0x1f83d9abfb41bd6bULL,
    0x5be0cd19137e2179ULL}
Definition at line 349 of file sha2.c.
Referenced by sha512_init().