libdogecoin: src/libevent/signal.c File Reference
signal.c File Reference
#include "event2/event-config.h"
#include "evconfig-private.h"
#include <sys/types.h>
#include <sys/queue.h>
#include <signal.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>
#include "event2/event.h"
#include "event2/event_struct.h"
#include "event-internal.h"
#include "event2/util.h"
#include "evsignal-internal.h"
#include "log-internal.h"
#include "evmap-internal.h"
#include "evthread-internal.h"
Macros
#define __cdecl
#define EVSIGBASE_LOCK() EVLOCK_LOCK(evsig_base_lock, 0)
#define EVSIGBASE_UNLOCK() EVLOCK_UNLOCK(evsig_base_lock, 0)
Functions
static int evsig_add (struct event_base *, evutil_socket_t, short, short, void *)
static int evsig_del (struct event_base *, evutil_socket_t, short, short, void *)
static void __cdecl evsig_handler (int sig)
void evsig_set_base_ (struct event_base *base)
static void evsig_cb (evutil_socket_t fd, short what, void *arg)
int evsig_init_ (struct event_base *base)
int evsig_set_handler_ (struct event_base *base, int evsignal, void(__cdecl *handler)(int))
int evsig_restore_handler_ (struct event_base *base, int evsignal)
void evsig_dealloc_ (struct event_base *base)
static void evsig_free_globals_locks (void)
void evsig_free_globals_ (void)
int evsig_global_setup_locks_ (const int enable_locks)
Variables
static const struct eventop evsigops
static void * evsig_base_lock = NULL
static struct event_base * evsig_base = NULL
static int evsig_base_n_signals_added = 0
static evutil_socket_t evsig_base_fd = -1
Macro Definition Documentation
__cdecl
#define __cdecl
Definition at line 89 of file signal.c.
EVSIGBASE_LOCK
#define EVSIGBASE_LOCK () EVLOCK_LOCK(evsig_base_lock, 0)
Definition at line 118 of file signal.c.
EVSIGBASE_UNLOCK
#define EVSIGBASE_UNLOCK () EVLOCK_UNLOCK(evsig_base_lock, 0)
Definition at line 119 of file signal.c.
Function Documentation
evsig_add()
static int evsig_add (struct event_base * base, evutil_socket_t evsignal, short old, short events, void * p) static
Definition at line 280 of file signal.c.
{
    struct evsig_info *sig = &base->sig;
    (void)p;
    EVUTIL_ASSERT(evsignal >= 0 && evsignal < NSIG);
    /* catch signals if they happen quickly */
    EVSIGBASE_LOCK();
    if (evsig_base != base && evsig_base_n_signals_added) {
        event_warnx("Added a signal to event base %p with signals "
            "already added to event_base %p.  Only one can have "
            "signals at a time with the %s backend.  The base with "
            "the most recently added signal or the most recent "
            "event_base_loop() call gets preference; do "
            "not rely on this behavior in future Libevent versions.",
            base, evsig_base, base->evsel->name);
    }
    evsig_base = base;
    evsig_base_n_signals_added = ++sig->ev_n_signals_added;
    evsig_base_fd = base->sig.ev_signal_pair[1];
    EVSIGBASE_UNLOCK();
    event_debug(("%s: %d: changing signal handler", __func__, (int)evsignal));
    if (evsig_set_handler_(base, (int)evsignal, evsig_handler) == -1) {
        goto err;
    }
    if (!sig->ev_signal_added) {
        if (event_add_nolock_(&sig->ev_signal, NULL, 0))
            goto err;
        sig->ev_signal_added = 1;
    }
    return (0);
err:
    EVSIGBASE_LOCK();
    --evsig_base_n_signals_added;
    --sig->ev_n_signals_added;
    EVSIGBASE_UNLOCK();
    return (-1);
}
References __func__, evsig_info::ev_n_signals_added, evsig_info::ev_signal, evsig_info::ev_signal_added, evsig_info::ev_signal_pair, event_add_nolock_(), event_debug, event_warnx(), event_base::evsel, evsig_base, evsig_base_fd, evsig_base_n_signals_added, evsig_handler(), evsig_set_handler_(), EVSIGBASE_LOCK, EVSIGBASE_UNLOCK, EVUTIL_ASSERT, eventop::name, and event_base::sig.
evsig_cb()
static void evsig_cb (evutil_socket_t fd, short what, void * arg) static
Definition at line 133 of file signal.c.
{
    static char signals[1024];
    ev_ssize_t n;
    int i;
    int ncaught[NSIG];
    struct event_base *base;
    base = arg;
    memset(&ncaught, 0, sizeof(ncaught));
    while (1) {
#ifdef _WIN32
        n = recv(fd, signals, sizeof(signals), 0);
#else
        n = read(fd, signals, sizeof(signals));
#endif
        if (n == -1) {
            int err = evutil_socket_geterror(fd);
            if (! EVUTIL_ERR_RW_RETRIABLE(err))
                event_sock_err(1, fd, "%s: recv", __func__);
            break;
        } else if (n == 0) {
            /* XXX warn? */
            break;
        }
        for (i = 0; i < n; ++i) {
            ev_uint8_t sig = signals[i];
            if (sig < NSIG)
                ncaught[sig]++;
        }
    }
    EVBASE_ACQUIRE_LOCK(base, th_base_lock);
    for (i = 0; i < NSIG; ++i) {
        if (ncaught[i])
            evmap_signal_active_(base, i, ncaught[i]);
    }
    EVBASE_RELEASE_LOCK(base, th_base_lock);
}
References __func__, EVBASE_ACQUIRE_LOCK, EVBASE_RELEASE_LOCK, event_sock_err(), evmap_signal_active_(), EVUTIL_ERR_RW_RETRIABLE, event_base::sig, and event_base::th_base_lock.
Referenced by evsig_init_().
evsig_dealloc_()
void evsig_dealloc_ (struct event_base * base)
Definition at line 415 of file signal.c.
{
    int i = 0;
    if (base->sig.ev_signal_added) {
        event_del(&base->sig.ev_signal);
        base->sig.ev_signal_added = 0;
    }
    /* debug event is created in evsig_init_/event_assign even when
     * ev_signal_added == 0, so unassign is required */
    event_debug_unassign(&base->sig.ev_signal);
    for (i = 0; i < NSIG; ++i) {
        if (i < base->sig.sh_old_max && base->sig.sh_old[i] != NULL)
            evsig_restore_handler_(base, i);
    }
    EVSIGBASE_LOCK();
    if (base == evsig_base) {
        evsig_base = NULL;
        evsig_base_n_signals_added = 0;
        evsig_base_fd = -1;
    }
    EVSIGBASE_UNLOCK();
    if (base->sig.ev_signal_pair[0] != -1) {
        evutil_closesocket(base->sig.ev_signal_pair[0]);
        base->sig.ev_signal_pair[0] = -1;
    }
    if (base->sig.ev_signal_pair[1] != -1) {
        evutil_closesocket(base->sig.ev_signal_pair[1]);
        base->sig.ev_signal_pair[1] = -1;
    }
    base->sig.sh_old_max = 0;
    /* per index frees are handled in evsig_del() */
    if (base->sig.sh_old) {
        mm_free(base->sig.sh_old);
        base->sig.sh_old = NULL;
    }
}
References evsig_info::ev_signal, evsig_info::ev_signal_added, evsig_info::ev_signal_pair, event_debug_unassign(), event_del(), evsig_base, evsig_base_fd, evsig_base_n_signals_added, evsig_restore_handler_(), EVSIGBASE_LOCK, EVSIGBASE_UNLOCK, evutil_closesocket(), mm_free, evsig_info::sh_old, evsig_info::sh_old_max, and event_base::sig.
evsig_del()
static int evsig_del (struct event_base * base, evutil_socket_t evsignal, short old, short events, void * p) static
Definition at line 363 of file signal.c.
{
    EVUTIL_ASSERT(evsignal >= 0 && evsignal < NSIG);
    event_debug(("%s: "EV_SOCK_FMT": restoring signal handler",
        __func__, EV_SOCK_ARG(evsignal)));
    EVSIGBASE_LOCK();
    --evsig_base_n_signals_added;
    --base->sig.ev_n_signals_added;
    EVSIGBASE_UNLOCK();
    return (evsig_restore_handler_(base, (int)evsignal));
}
References __func__, evsig_info::ev_n_signals_added, EV_SOCK_ARG, EV_SOCK_FMT, event_debug, evsig_base_n_signals_added, evsig_restore_handler_(), EVSIGBASE_LOCK, EVSIGBASE_UNLOCK, EVUTIL_ASSERT, and event_base::sig.
evsig_free_globals_()
void evsig_free_globals_ (void)
Definition at line 468 of file signal.c.
{
    evsig_free_globals_locks();
}
References evsig_free_globals_locks().
Referenced by event_free_evsig_globals().
evsig_free_globals_locks()
static void evsig_free_globals_locks (void) static
Definition at line 456 of file signal.c.
{
#ifndef EVENT__DISABLE_THREAD_SUPPORT
    if (evsig_base_lock != NULL) {
        EVTHREAD_FREE_LOCK(evsig_base_lock, 0);
        evsig_base_lock = NULL;
    }
#endif
    return;
}
References evsig_base_lock, and EVTHREAD_FREE_LOCK.
Referenced by evsig_free_globals_().
evsig_global_setup_locks_()
int evsig_global_setup_locks_ (const int enable_locks)
Definition at line 475 of file signal.c.
{
    EVTHREAD_SETUP_GLOBAL_LOCK(evsig_base_lock, 0);
    return 0;
}
References evsig_base_lock, and EVTHREAD_SETUP_GLOBAL_LOCK.
Referenced by event_global_setup_locks_().
evsig_handler()
static void __cdecl evsig_handler (int sig) static
Definition at line 379 of file signal.c.
{
    int save_errno = errno;
#ifdef _WIN32
    int socket_errno = EVUTIL_SOCKET_ERROR();
#endif
    ev_uint8_t msg;
    if (evsig_base == NULL) {
        event_warnx(
            "%s: received signal %d, but have no base configured",
            __func__, sig);
        return;
    }
#ifndef EVENT__HAVE_SIGACTION
    signal(sig, evsig_handler);
#endif
    /* Wake up our notification mechanism */
    msg = sig;
#ifdef _WIN32
    send(evsig_base_fd, (char*)&msg, 1, 0);
#else
    {
        int r = write(evsig_base_fd, (char*)&msg, 1);
        (void)r; /* Suppress 'unused return value' and 'unused var' */
    }
#endif
    errno = save_errno;
#ifdef _WIN32
    EVUTIL_SET_SOCKET_ERROR(socket_errno);
#endif
}
References __func__, event_warnx(), evsig_base, evsig_base_fd, and evsig_handler().
Referenced by evsig_add(), and evsig_handler().
evsig_init_()
int evsig_init_ (struct event_base * base)
Definition at line 176 of file signal.c.
{
    /*
     * Our signal handler is going to write to one end of the socket
     * pair to wake up our event loop.  The event loop then scans for
     * signals that got delivered.
     */
    if (evutil_make_internal_pipe_(base->sig.ev_signal_pair) == -1) {
#ifdef _WIN32
        /* Make this nonfatal on win32, where sometimes people
           have localhost firewalled. */
        event_sock_warn(-1, "%s: socketpair", __func__);
#else
        event_sock_err(1, -1, "%s: socketpair", __func__);
#endif
        return -1;
    }
    if (base->sig.sh_old) {
        mm_free(base->sig.sh_old);
    }
    base->sig.sh_old = NULL;
    base->sig.sh_old_max = 0;
    event_assign(&base->sig.ev_signal, base, base->sig.ev_signal_pair[0],
        EV_READ | EV_PERSIST, evsig_cb, base);
    base->sig.ev_signal.ev_flags |= EVLIST_INTERNAL;
    event_priority_set(&base->sig.ev_signal, 0);
    base->evsigsel = &evsigops;
    return 0;
}
References __func__, evsig_info::ev_signal, evsig_info::ev_signal_pair, event_assign(), event_priority_set(), event_sock_err(), event_sock_warn(), evsig_cb(), evsigops, event_base::evsigsel, evutil_make_internal_pipe_(), mm_free, evsig_info::sh_old, evsig_info::sh_old_max, and event_base::sig.
Referenced by event_reinit().
evsig_restore_handler_()
int evsig_restore_handler_ (struct event_base * base, int evsignal)
Definition at line 326 of file signal.c.
{
    int ret = 0;
    struct evsig_info *sig = &base->sig;
#ifdef EVENT__HAVE_SIGACTION
    struct sigaction *sh;
#else
    ev_sighandler_t *sh;
#endif
    if (evsignal >= sig->sh_old_max) {
        /* Can't actually restore. */
        /* XXXX.*/
        return 0;
    }
    /* restore previous handler */
    sh = sig->sh_old[evsignal];
    sig->sh_old[evsignal] = NULL;
#ifdef EVENT__HAVE_SIGACTION
    if (sigaction(evsignal, sh, NULL) == -1) {
        event_warn("sigaction");
        ret = -1;
    }
#else
    if (signal(evsignal, *sh) == SIG_ERR) {
        event_warn("signal");
        ret = -1;
    }
#endif
    mm_free(sh);
    return ret;
}
References event_warn(), mm_free, evsig_info::sh_old, evsig_info::sh_old_max, and event_base::sig.
Referenced by evsig_dealloc_(), and evsig_del().
evsig_set_base_()
void evsig_set_base_ (struct event_base * base)
Definition at line 122 of file signal.c.
{
    EVSIGBASE_LOCK();
    evsig_base = base;
    evsig_base_n_signals_added = base->sig.ev_n_signals_added;
    evsig_base_fd = base->sig.ev_signal_pair[1];
    EVSIGBASE_UNLOCK();
}
References evsig_info::ev_n_signals_added, evsig_info::ev_signal_pair, evsig_base, evsig_base_fd, evsig_base_n_signals_added, EVSIGBASE_LOCK, EVSIGBASE_UNLOCK, and event_base::sig.
Referenced by event_base_loop().
evsig_set_handler_()
int evsig_set_handler_ (struct event_base * base, int evsignal, void(__cdecl *handler)(int))
Definition at line 214 of file signal.c.
{
#ifdef EVENT__HAVE_SIGACTION
    struct sigaction sa;
#else
    ev_sighandler_t sh;
#endif
    struct evsig_info *sig = &base->sig;
    void *p;
    /*
     * resize saved signal handler array up to the highest signal number.
     * a dynamic array is used to keep footprint on the low side.
     */
    if (evsignal >= sig->sh_old_max) {
        int new_max = evsignal + 1;
        event_debug(("%s: evsignal (%d) >= sh_old_max (%d), resizing",
                __func__, evsignal, sig->sh_old_max));
        p = mm_realloc(sig->sh_old, new_max * sizeof(*sig->sh_old));
        if (p == NULL) {
            event_warn("realloc");
            return (-1);
        }
        memset((char *)p + sig->sh_old_max * sizeof(*sig->sh_old),
            0, (new_max - sig->sh_old_max) * sizeof(*sig->sh_old));
        sig->sh_old_max = new_max;
        sig->sh_old = p;
    }
    /* allocate space for previous handler out of dynamic array */
    sig->sh_old[evsignal] = mm_malloc(sizeof *sig->sh_old[evsignal]);
    if (sig->sh_old[evsignal] == NULL) {
        event_warn("malloc");
        return (-1);
    }
    /* save previous handler and setup new handler */
#ifdef EVENT__HAVE_SIGACTION
    memset(&sa, 0, sizeof(sa));
    sa.sa_handler = handler;
    sa.sa_flags |= SA_RESTART;
    sigfillset(&sa.sa_mask);
    if (sigaction(evsignal, &sa, sig->sh_old[evsignal]) == -1) {
        event_warn("sigaction");
        mm_free(sig->sh_old[evsignal]);
        sig->sh_old[evsignal] = NULL;
        return (-1);
    }
#else
    if ((sh = signal(evsignal, handler)) == SIG_ERR) {
        event_warn("signal");
        mm_free(sig->sh_old[evsignal]);
        sig->sh_old[evsignal] = NULL;
        return (-1);
    }
    *sig->sh_old[evsignal] = sh;
#endif
    return (0);
}
References __func__, event_debug, event_warn(), mm_free, mm_malloc, mm_realloc, evsig_info::sh_old, evsig_info::sh_old_max, and event_base::sig.
Referenced by evsig_add().
Variable Documentation
evsig_base
struct event_base* evsig_base = NULL static
Definition at line 111 of file signal.c.
Referenced by evsig_add(), evsig_dealloc_(), evsig_handler(), and evsig_set_base_().
evsig_base_fd
evutil_socket_t evsig_base_fd = -1 static
Definition at line 114 of file signal.c.
Referenced by evsig_add(), evsig_dealloc_(), evsig_handler(), and evsig_set_base_().
evsig_base_lock
void* evsig_base_lock = NULL static
Definition at line 108 of file signal.c.
Referenced by evsig_free_globals_locks(), and evsig_global_setup_locks_().
evsig_base_n_signals_added
int evsig_base_n_signals_added = 0 static
Definition at line 113 of file signal.c.
Referenced by evsig_add(), evsig_dealloc_(), evsig_del(), and evsig_set_base_().
evsigops
const struct eventop evsigops static
Initial value:
= {
    "signal",
    NULL,
    evsig_add,
    evsig_del,
    NULL,
    NULL,
    0, 0, 0
}
Definition at line 96 of file signal.c.
Referenced by evsig_init_().