libdogecoin: include/dogecoin/sign.h File Reference
sign.h File Reference
#include <dogecoin/dogecoin.h>
#include <dogecoin/eckey.h>
Functions
LIBDOGECOIN_BEGIN_DECL LIBDOGECOIN_API void hash_message (char *msg, uint256 message_bytes)
LIBDOGECOIN_API char * sign_message (char *privkey, char *msg)
Sign message with private key.
LIBDOGECOIN_API int verify_message (char *sig, char *msg, char *address)
Verify signed message using non BIP32 encoded address.
Function Documentation
hash_message()
LIBDOGECOIN_BEGIN_DECL LIBDOGECOIN_API void hash_message (char * msg, uint256 message_bytes)
Definition at line 41 of file sign.c.
{
    size_t msg_magic_len = strlen(msg_magic), msg_len = strlen(msg);
    char* tmp_msg = dogecoin_char_vla(msg_magic_len + msg_len + 7);
    tmp_msg[0] = msg_magic_len;
    memcpy_safe(tmp_msg + 1, msg_magic, msg_magic_len);
    tmp_msg[msg_magic_len + 1] = msg_len;
    memcpy_safe(tmp_msg + msg_magic_len + 2, msg, msg_len + 1);
    dogecoin_hash((const unsigned char*)tmp_msg, strlen(tmp_msg), message_bytes);
    dogecoin_free(tmp_msg);
}
References dogecoin_char_vla(), dogecoin_free(), dogecoin_hash(), memcpy_safe(), and msg_magic.
Referenced by sign_message(), and verify_message().
sign_message()
LIBDOGECOIN_API char * sign_message (char * privkey, char * msg)
Sign message with private key.
Parameters
privkey The key to sign the message with.
message The message to be signed.
Returns
Base64 encoded signature if successful, False (0) if not
Definition at line 61 of file sign.c.
{
    if (!privkey || !msg) return false;
    uint256 message_bytes;
    hash_message(msg, message_bytes);
    size_t compact_signature_length = 65;
    unsigned char* compact_signature = dogecoin_uchar_vla(compact_signature_length);
    dogecoin_key key;
    dogecoin_pubkey pubkey;
    if (!init_keypair(privkey, &key, &pubkey)) return false;
    int recid = -1;
    if (!dogecoin_key_sign_hash_compact_recoverable_fcomp(&key, message_bytes, compact_signature, &compact_signature_length, &recid)) return false;
    if (!dogecoin_key_recover_pubkey((const unsigned char*)compact_signature, message_bytes, recid, &pubkey)) return false;
    char p2pkh_address[35];
    if (!dogecoin_pubkey_getaddr_p2pkh(&pubkey, &dogecoin_chainparams_main, p2pkh_address)) return false;
    unsigned char* base64_encoded_output = dogecoin_uchar_vla(1+(sizeof(char)*base64_encoded_size(compact_signature_length)));
    base64_encode((unsigned char*)compact_signature, compact_signature_length, base64_encoded_output);
    dogecoin_free(compact_signature);
    dogecoin_privkey_cleanse(&key);
    dogecoin_pubkey_cleanse(&pubkey);
    return (char*)base64_encoded_output;
}
References base64_encode(), base64_encoded_size(), dogecoin_chainparams_main, dogecoin_free(), dogecoin_key_recover_pubkey(), dogecoin_key_sign_hash_compact_recoverable_fcomp(), dogecoin_privkey_cleanse(), dogecoin_pubkey_cleanse(), dogecoin_pubkey_getaddr_p2pkh(), dogecoin_uchar_vla(), hash_message(), init_keypair(), and uint256.
Referenced by main().
verify_message()
LIBDOGECOIN_API int verify_message (char * sig, char * msg, char * address)
Verify signed message using non BIP32 encoded address.
Parameters
sig
msg
address
Returns
P2PKH address if successful, False (0) otherwise
Definition at line 102 of file sign.c.
{
    if (!(sig || msg || address)) return false;
    uint256 message_bytes;
    hash_message(msg, message_bytes);
    size_t encoded_length = strlen((const char*)sig);
    unsigned char* decoded_signature = dogecoin_uchar_vla(base64_decoded_size(encoded_length+1)+1);
    base64_decode((unsigned char*)sig, encoded_length, decoded_signature);
    dogecoin_pubkey pub_key;
    dogecoin_pubkey_init(&pub_key);
    pub_key.compressed = false;
    int header = decoded_signature[0] & 0xFF;
    if (header < 27 || header > 42) return false;
    if (header >= 31) {
        pub_key.compressed = true;
        header -= 4;
    }
    int recid = header - 27;
    if (!dogecoin_key_recover_pubkey((const unsigned char*)decoded_signature, message_bytes, recid, &pub_key)) return false;
    if (!dogecoin_pubkey_verify_sigcmp(&pub_key, message_bytes, decoded_signature)) return false;
    char p2pkh_address[35];
    const dogecoin_chainparams* chain = chain_from_b58_prefix(address);
    if (!dogecoin_pubkey_getaddr_p2pkh(&pub_key, chain, p2pkh_address)) return false;
    dogecoin_free(decoded_signature);
    dogecoin_pubkey_cleanse(&pub_key);
    return strcmp(p2pkh_address, address)==0;
}
References base64_decode(), base64_decoded_size(), chain_from_b58_prefix(), dogecoin_pubkey_::compressed, dogecoin_free(), dogecoin_key_recover_pubkey(), dogecoin_pubkey_cleanse(), dogecoin_pubkey_getaddr_p2pkh(), dogecoin_pubkey_init(), dogecoin_pubkey_verify_sigcmp(), dogecoin_uchar_vla(), hash_message(), and uint256.
Referenced by main().