libdogecoin: src/secp256k1/src/hash.h File Reference
hash.h File Reference
#include <stdlib.h>
#include <stdint.h>
Data Structures
struct secp256k1_sha256
struct secp256k1_hmac_sha256
struct secp256k1_rfc6979_hmac_sha256
Functions
static void secp256k1_sha256_initialize (secp256k1_sha256 *hash)
static void secp256k1_sha256_write (secp256k1_sha256 *hash, const unsigned char *data, size_t size)
static void secp256k1_sha256_finalize (secp256k1_sha256 *hash, unsigned char *out32)
static void secp256k1_hmac_sha256_initialize (secp256k1_hmac_sha256 *hash, const unsigned char *key, size_t size)
static void secp256k1_hmac_sha256_write (secp256k1_hmac_sha256 *hash, const unsigned char *data, size_t size)
static void secp256k1_hmac_sha256_finalize (secp256k1_hmac_sha256 *hash, unsigned char *out32)
static void secp256k1_rfc6979_hmac_sha256_initialize (secp256k1_rfc6979_hmac_sha256 *rng, const unsigned char *key, size_t keylen)
static void secp256k1_rfc6979_hmac_sha256_generate (secp256k1_rfc6979_hmac_sha256 *rng, unsigned char *out, size_t outlen)
static void secp256k1_rfc6979_hmac_sha256_finalize (secp256k1_rfc6979_hmac_sha256 *rng)
Function Documentation
secp256k1_hmac_sha256_finalize()
static void secp256k1_hmac_sha256_finalize (secp256k1_hmac_sha256 * hash, unsigned char * out32) static
Referenced by bench_hmac_sha256(), and run_hmac_sha256_tests().
secp256k1_hmac_sha256_initialize()
static void secp256k1_hmac_sha256_initialize (secp256k1_hmac_sha256 * hash, const unsigned char * key, size_t size) static
Referenced by bench_hmac_sha256(), and run_hmac_sha256_tests().
secp256k1_hmac_sha256_write()
static void secp256k1_hmac_sha256_write (secp256k1_hmac_sha256 * hash, const unsigned char * data, size_t size) static
Referenced by bench_hmac_sha256(), and run_hmac_sha256_tests().
secp256k1_rfc6979_hmac_sha256_finalize()
static void secp256k1_rfc6979_hmac_sha256_finalize (secp256k1_rfc6979_hmac_sha256 * rng) static
Referenced by nonce_function_rfc6979(), run_rfc6979_hmac_sha256_tests(), and secp256k1_ecmult_gen_blind().
secp256k1_rfc6979_hmac_sha256_generate()
static void secp256k1_rfc6979_hmac_sha256_generate (secp256k1_rfc6979_hmac_sha256 * rng, unsigned char * out, size_t outlen) static
Referenced by bench_rfc6979_hmac_sha256(), nonce_function_rfc6979(), run_rfc6979_hmac_sha256_tests(), and secp256k1_ecmult_gen_blind().
secp256k1_rfc6979_hmac_sha256_initialize()
static void secp256k1_rfc6979_hmac_sha256_initialize (secp256k1_rfc6979_hmac_sha256 * rng, const unsigned char * key, size_t keylen) static
Referenced by bench_rfc6979_hmac_sha256(), nonce_function_rfc6979(), run_rfc6979_hmac_sha256_tests(), and secp256k1_ecmult_gen_blind().
secp256k1_sha256_finalize()
static void secp256k1_sha256_finalize (secp256k1_sha256 * hash, unsigned char * out32) static
Referenced by bench_sha256(), generate_scalar(), run_sha256_tests(), secp256k1_selftest_sha256(), secp256k1_tagged_sha256(), secp256k1_testrand_seed(), test_ecmult_constants_2bit(), and test_ecmult_constants_sha().
secp256k1_sha256_initialize()
static void secp256k1_sha256_initialize (secp256k1_sha256 * hash) static
Referenced by bench_sha256(), generate_scalar(), run_sha256_tests(), secp256k1_selftest_sha256(), secp256k1_testrand_seed(), test_ecmult_constants_2bit(), and test_ecmult_constants_sha().
secp256k1_sha256_write()
static void secp256k1_sha256_write (secp256k1_sha256 * hash, const unsigned char * data, size_t size) static
Referenced by bench_sha256(), generate_scalar(), run_sha256_tests(), secp256k1_selftest_sha256(), secp256k1_tagged_sha256(), secp256k1_testrand_seed(), test_ecmult_accumulate(), and test_ecmult_constants_sha().