libdogecoin: dogecoin_mem_mapper Struct Reference
dogecoin_mem_mapper Struct Reference
#include <mem.h>
Data Fields
void *(* dogecoin_malloc)(size_t size)
void *(* dogecoin_calloc)(size_t count, size_t size)
void *(* dogecoin_realloc)(void *ptr, size_t size)
void(* dogecoin_free)(void *ptr)
Detailed Description
It's a struct that has pointers to functions that do the actual memory management.
Definition at line 43 of file mem.h.
Field Documentation
dogecoin_calloc
void *(* dogecoin_mem_mapper::dogecoin_calloc) (size_t count, size_t size)
Definition at line 45 of file mem.h.
Referenced by dogecoin_calloc().
dogecoin_free
void(* dogecoin_mem_mapper::dogecoin_free) (void *ptr)
Definition at line 47 of file mem.h.
Referenced by dogecoin_free().
dogecoin_malloc
void *(* dogecoin_mem_mapper::dogecoin_malloc) (size_t size)
Definition at line 44 of file mem.h.
Referenced by dogecoin_malloc().
dogecoin_realloc
void *(* dogecoin_mem_mapper::dogecoin_realloc) (void *ptr, size_t size)
Definition at line 46 of file mem.h.
Referenced by dogecoin_realloc().
The documentation for this struct was generated from the following file:
include/dogecoin/mem.h