libdogecoin: evconnlistener_ops Struct Reference
evconnlistener_ops Struct Reference
Data Fields
int(* enable)(struct evconnlistener *)
int(* disable)(struct evconnlistener *)
void(* destroy)(struct evconnlistener *)
void(* shutdown)(struct evconnlistener *)
evutil_socket_t(* getfd)(struct evconnlistener *)
struct event_base *(* getbase)(struct evconnlistener *)
Detailed Description
Definition at line 67 of file listener.c.
Field Documentation
destroy
void(* evconnlistener_ops::destroy) (struct evconnlistener *)
Definition at line 70 of file listener.c.
Referenced by listener_decref_and_unlock().
disable
int(* evconnlistener_ops::disable) (struct evconnlistener *)
Definition at line 69 of file listener.c.
Referenced by evconnlistener_disable().
enable
int(* evconnlistener_ops::enable) (struct evconnlistener *)
Definition at line 68 of file listener.c.
Referenced by evconnlistener_enable().
getbase
struct event_base *(* evconnlistener_ops::getbase) (struct evconnlistener *)
Definition at line 72 of file listener.c.
Referenced by evconnlistener_get_base().
getfd
evutil_socket_t(* evconnlistener_ops::getfd) (struct evconnlistener *)
Definition at line 72 of file listener.c.
Referenced by evconnlistener_get_fd().
shutdown
void(* evconnlistener_ops::shutdown) (struct evconnlistener *)
Definition at line 71 of file listener.c.
Referenced by evconnlistener_free().
The documentation for this struct was generated from the following file:
src/libevent/listener.c