libdogecoin: eventop Struct Reference
eventop Struct Reference
#include <event-internal.h>
Data Fields
const char * name
void *(* init)(struct event_base *)
int(* add)(struct event_base *, evutil_socket_t fd, short old, short events, void *fdinfo)
int(* del)(struct event_base *, evutil_socket_t fd, short old, short events, void *fdinfo)
int(* dispatch)(struct event_base *, struct timeval *)
void(* dealloc)(struct event_base *)
int need_reinit
enum event_method_feature features
size_t fdinfo_len
Detailed Description
Structure to define the backend of a given event_base.
Definition at line 86 of file event-internal.h.
Field Documentation
add
int(* eventop::add) (struct event_base *, evutil_socket_t fd, short old, short events, void *fdinfo)
Enable reading/writing on a given fd or signal. 'events' will be the events that we're trying to enable: one or more of EV_READ, EV_WRITE, EV_SIGNAL, and EV_ET. 'old' will be those events that were enabled on this fd previously. 'fdinfo' will be a structure associated with the fd by the evmap; its size is defined by the fdinfo field below. It will be set to 0 the first time the fd is added. The function should return 0 on success and -1 on error.
Definition at line 103 of file event-internal.h.
Referenced by evmap_check_integrity_(), evmap_io_add_(), evmap_io_reinit_iter_fn(), evmap_signal_add_(), and evmap_signal_reinit_iter_fn().
dealloc
void(* eventop::dealloc) (struct event_base *)
Function to clean up and free our data from the event_base.
Definition at line 113 of file event-internal.h.
Referenced by event_base_free_(), and event_reinit().
del
int(* eventop::del) (struct event_base *, evutil_socket_t fd, short old, short events, void *fdinfo)
As "add", except 'events' contains the events we mean to disable.
Definition at line 105 of file event-internal.h.
Referenced by evmap_io_del_(), and evmap_signal_del_().
dispatch
int(* eventop::dispatch) (struct event_base *, struct timeval *)
Function to implement the core of an event loop. It must see which added events are ready, and cause event_active to be called for each active event (usually via event_io_active or such). It should return 0 on success and -1 on error.
Definition at line 111 of file event-internal.h.
Referenced by event_base_loop().
fdinfo_len
size_t eventop::fdinfo_len
Length of the extra information we should record for each fd that has one or more active events. This information is recorded as part of the evmap entry for each fd, and passed as an argument to the add and del functions above.
Definition at line 125 of file event-internal.h.
Referenced by evmap_io_add_(), evmap_io_reinit_iter_fn(), and evmap_signal_add_().
features
enum event_method_feature eventop::features
Bit-array of supported event_method_features that this backend can provide.
Definition at line 119 of file event-internal.h.
Referenced by event_base_get_features().
init
void *(* eventop::init) (struct event_base *)
Function to set up an event_base to use this backend. It should create a new structure holding whatever information is needed to run the backend, and return it. The returned pointer will get stored by event_init into the event_base.evbase field. On failure, this function should return NULL.
Definition at line 94 of file event-internal.h.
Referenced by event_base_new_with_config(), and event_reinit().
name
const char* eventop::name
The name of this backend.
Definition at line 88 of file event-internal.h.
Referenced by event_base_get_method(), event_base_new_with_config(), event_get_supported_methods(), and evsig_add().
need_reinit
int eventop::need_reinit
Flag: set if we need to reinitialize the event base after we fork.
Definition at line 116 of file event-internal.h.
Referenced by event_reinit().
The documentation for this struct was generated from the following file:
src/libevent/event-internal.h