libdogecoin: dogecoin_node_group_ Struct Reference
dogecoin_node_group_ Struct Reference
#include <net.h>
Data Fields
void * ctx
struct event_base * event_base
vector * nodes
char clientstr [1024]
int desired_amount_connected_nodes
const dogecoin_chainparams * chainparams
int(* log_write_cb)(const char *format,...)
dogecoin_bool(* parse_cmd_cb)(struct dogecoin_node_ *node, dogecoin_p2p_msg_hdr *hdr, struct const_buffer *buf)
void(* postcmd_cb)(struct dogecoin_node_ *node, dogecoin_p2p_msg_hdr *hdr, struct const_buffer *buf)
void(* node_connection_state_changed_cb)(struct dogecoin_node_ *node)
dogecoin_bool(* should_connect_to_more_nodes_cb)(struct dogecoin_node_ *node)
void(* handshake_done_cb)(struct dogecoin_node_ *node)
dogecoin_bool(* periodic_timer_cb)(struct dogecoin_node_ *node, uint64_t *time)
Detailed Description
Definition at line 56 of file net.h.
Field Documentation
chainparams
const dogecoin_chainparams* dogecoin_node_group_::chainparams
Definition at line 62 of file net.h.
Referenced by broadcast_handshake_done(), broadcast_post_cmd(), dogecoin_node_group_add_peers_by_ip_or_seed(), dogecoin_node_group_new(), dogecoin_node_parse_message(), dogecoin_node_send_version(), and node_periodical_timer().
clientstr
char dogecoin_node_group_::clientstr[1024]
Definition at line 60 of file net.h.
Referenced by dogecoin_node_group_new(), and dogecoin_node_send_version().
ctx
void* dogecoin_node_group_::ctx
Definition at line 57 of file net.h.
Referenced by broadcast_handshake_done(), broadcast_post_cmd(), broadcast_should_connect_more(), broadcast_timer_cb(), and broadcast_tx().
desired_amount_connected_nodes
int dogecoin_node_group_::desired_amount_connected_nodes
Definition at line 61 of file net.h.
Referenced by broadcast_tx(), dogecoin_node_connection_state_changed(), dogecoin_node_group_connect_next_nodes(), and dogecoin_node_group_new().
event_base
struct event_base* dogecoin_node_group_::event_base
Definition at line 58 of file net.h.
Referenced by dogecoin_node_group_connect_next_nodes(), dogecoin_node_group_event_loop(), dogecoin_node_group_free(), and dogecoin_node_group_new().
handshake_done_cb
void(* dogecoin_node_group_::handshake_done_cb) (struct dogecoin_node_ *node)
Definition at line 70 of file net.h.
Referenced by broadcast_tx(), dogecoin_node_group_new(), and dogecoin_node_parse_message().
log_write_cb
int(* dogecoin_node_group_::log_write_cb) (const char *format,...)
Definition at line 65 of file net.h.
Referenced by broadcast_should_connect_more(), broadcast_timer_cb(), broadcast_tx(), dogecoin_node_disconnect(), dogecoin_node_group_connect_next_nodes(), dogecoin_node_group_new(), dogecoin_node_misbehave(), dogecoin_node_parse_message(), dogecoin_node_send(), and event_cb().
node_connection_state_changed_cb
void(* dogecoin_node_group_::node_connection_state_changed_cb) (struct dogecoin_node_ *node)
Definition at line 68 of file net.h.
Referenced by dogecoin_node_connection_state_changed(), and dogecoin_node_group_new().
nodes
vector* dogecoin_node_group_::nodes
Definition at line 59 of file net.h.
Referenced by dogecoin_node_group_add_node(), dogecoin_node_group_amount_of_connected_nodes(), dogecoin_node_group_connect_next_nodes(), dogecoin_node_group_free(), dogecoin_node_group_new(), and dogecoin_node_group_shutdown().
parse_cmd_cb
dogecoin_bool(* dogecoin_node_group_::parse_cmd_cb) (struct dogecoin_node_ *node, dogecoin_p2p_msg_hdr *hdr, struct const_buffer *buf)
Definition at line 66 of file net.h.
Referenced by dogecoin_node_group_new(), and dogecoin_node_parse_message().
periodic_timer_cb
dogecoin_bool(* dogecoin_node_group_::periodic_timer_cb) (struct dogecoin_node_ *node, uint64_t *time)
Definition at line 71 of file net.h.
Referenced by broadcast_tx(), and node_periodical_timer().
postcmd_cb
void(* dogecoin_node_group_::postcmd_cb) (struct dogecoin_node_ *node, dogecoin_p2p_msg_hdr *hdr, struct const_buffer *buf)
Definition at line 67 of file net.h.
Referenced by broadcast_tx(), dogecoin_node_group_new(), and dogecoin_node_parse_message().
should_connect_to_more_nodes_cb
dogecoin_bool(* dogecoin_node_group_::should_connect_to_more_nodes_cb) (struct dogecoin_node_ *node)
Definition at line 69 of file net.h.
Referenced by broadcast_tx(), dogecoin_node_connection_state_changed(), and dogecoin_node_group_new().
The documentation for this struct was generated from the following file:
include/dogecoin/net.h