libdogecoin: src/secp256k1/src/testrand.h File Reference
testrand.h File Reference
Functions
static SECP256K1_INLINE void secp256k1_testrand_seed (const unsigned char *seed16)
static SECP256K1_INLINE uint32_t secp256k1_testrand32 (void)
static SECP256K1_INLINE uint64_t secp256k1_testrand64 (void)
static SECP256K1_INLINE uint64_t secp256k1_testrand_bits (int bits)
static uint32_t secp256k1_testrand_int (uint32_t range)
static void secp256k1_testrand256 (unsigned char *b32)
static void secp256k1_testrand256_test (unsigned char *b32)
static void secp256k1_testrand_bytes_test (unsigned char *bytes, size_t len)
static void secp256k1_testrand_flip (unsigned char *b, size_t len)
static void secp256k1_testrand_init (const char *hexseed)
static void secp256k1_testrand_finish (void)
Function Documentation
secp256k1_testrand256()
static void secp256k1_testrand256 (unsigned char * b32) static
Generate a pseudorandom 32-byte array.
Referenced by main(), random_fe(), random_scalar_order(), run_inverse_tests(), test_ecmult_gen_blind(), and test_random_pubkeys().
secp256k1_testrand256_test()
static void secp256k1_testrand256_test (unsigned char * b32) static
Generate a pseudorandom 32-byte array with long sequences of zero and one bits.
Referenced by random_fe_test(), random_field_element_test(), random_scalar_order_test(), run_inverse_tests(), run_modinv_tests(), and test_ecdsa_end_to_end().
secp256k1_testrand32()
static SECP256K1_INLINE uint32_t secp256k1_testrand32 (void) static
Generate a pseudorandom number in the range [0..2**32-1].
Referenced by test_rand_bits().
secp256k1_testrand64()
static SECP256K1_INLINE uint64_t secp256k1_testrand64 (void) static
Generate a pseudorandom number in the range [0..2**64-1].
secp256k1_testrand_bits()
static SECP256K1_INLINE uint64_t secp256k1_testrand_bits (int bits) static
Generate a pseudorandom number in the range [0..2**bits-1]. Bits must be 1 or more.
Referenced by damage_array(), main(), mutate_sign_signed30(), random_ber_signature(), random_group_element_test(), scalar_test(), test_ecdsa_end_to_end(), test_ecdsa_sign_verify(), test_ecmult_multi_pippenger_max_points(), test_ecmult_multi_random(), test_rand_bits(), and test_random_pubkeys().
secp256k1_testrand_bytes_test()
static void secp256k1_testrand_bytes_test (unsigned char * bytes, size_t len) static
Generate pseudorandom bytes with long sequences of zero and one bits.
Referenced by random_ber_signature().
secp256k1_testrand_finish()
static void secp256k1_testrand_finish (void) static
Print final test information.
Referenced by main().
secp256k1_testrand_flip()
static void secp256k1_testrand_flip (unsigned char * b, size_t len) static
Flip a single random bit in a byte array
secp256k1_testrand_init()
static void secp256k1_testrand_init (const char * hexseed) static
Initialize the test RNG using (hex encoded) array up to 16 bytes, or randomly if hexseed is NULL.
Referenced by main().
secp256k1_testrand_int()
static uint32_t secp256k1_testrand_int (uint32_t range) static
Generate a pseudorandom number in the range [0..range-1].
Referenced by damage_array(), random_ber_signature(), random_field_element_magnitude(), run_hmac_sha256_tests(), run_sha256_tests(), scalar_test(), test_ecdsa_end_to_end(), test_ecmult_multi_random(), test_ge(), and test_rand_int().
secp256k1_testrand_seed()
static SECP256K1_INLINE void secp256k1_testrand_seed (const unsigned char * seed16) static
Seed the pseudorandom number generator for testing.