libdogecoin: src/libevent/time-internal.h File Reference
time-internal.h File Reference
#include "event2/event-config.h"
#include "evconfig-private.h"
#include <time.h>
#include "event2/util.h"
Data Structures
struct evutil_monotonic_timer
Macros
#define HAVE_FALLBACK_MONOTONIC
Functions
long evutil_tv_to_msec_ (const struct timeval *tv)
EVENT2_EXPORT_SYMBOL void evutil_usleep_ (const struct timeval *tv)
EVENT2_EXPORT_SYMBOL int evutil_configure_monotonic_time_ (struct evutil_monotonic_timer *mt, int flags)
EVENT2_EXPORT_SYMBOL int evutil_gettime_monotonic_ (struct evutil_monotonic_timer *mt, struct timeval *tv)
Macro Definition Documentation
HAVE_FALLBACK_MONOTONIC
#define HAVE_FALLBACK_MONOTONIC
Definition at line 53 of file time-internal.h.
Function Documentation
evutil_configure_monotonic_time_()
EVENT2_EXPORT_SYMBOL int evutil_configure_monotonic_time_ (struct evutil_monotonic_timer * mt, int flags)
Definition at line 604 of file evutil_time.c.
{
    memset(base, 0, sizeof(*base));
    return 0;
}
Referenced by event_base_new_with_config(), and evutil_configure_monotonic_time().
evutil_gettime_monotonic_()
EVENT2_EXPORT_SYMBOL int evutil_gettime_monotonic_ (struct evutil_monotonic_timer * mt, struct timeval * tv)
Definition at line 612 of file evutil_time.c.
{
    if (evutil_gettimeofday(tp, NULL) < 0)
        return -1;
    adjust_monotonic_time(base, tp);
    return 0;
}
References adjust_monotonic_time(), and evutil_gettimeofday().
Referenced by event_gettime_monotonic(), evutil_gettime_monotonic(), and gettime().
evutil_tv_to_msec_()
long evutil_tv_to_msec_ (const struct timeval * tv)
Definition at line 128 of file evutil_time.c.
{
    if (tv->tv_usec > 1000000 || tv->tv_sec > MAX_SECONDS_IN_MSEC_LONG)
        return -1;
    return (tv->tv_sec * 1000) + ((tv->tv_usec + 999) / 1000);
}
References MAX_SECONDS_IN_MSEC_LONG.
Referenced by evthread_win32_cond_wait().
evutil_usleep_()
EVENT2_EXPORT_SYMBOL void evutil_usleep_ (const struct timeval * tv)
Definition at line 141 of file evutil_time.c.
{
    if (!tv)
        return;
#if defined(_WIN32)
    {
        __int64 usec;
        LARGE_INTEGER li;
        HANDLE timer;
        usec = tv->tv_sec * 1000000LL + tv->tv_usec;
        if (!usec)
            return;
        li.QuadPart = -10LL * usec;
        timer = CreateWaitableTimer(NULL, TRUE, NULL);
        if (!timer)
            return;
        SetWaitableTimer(timer, &li, 0, NULL, NULL, 0);
        WaitForSingleObject(timer, INFINITE);
        CloseHandle(timer);
    }
#elif defined(EVENT__HAVE_NANOSLEEP)
    {
        struct timespec ts;
        ts.tv_sec = tv->tv_sec;
        ts.tv_nsec = tv->tv_usec*1000;
        nanosleep(&ts, NULL);
    }
#elif defined(EVENT__HAVE_USLEEP)
    /* Some systems don't like to usleep more than 999999 usec */
    sleep(tv->tv_sec);
    usleep(tv->tv_usec);
#else
    {
        struct timeval tv2 = *tv;
        select(0, NULL, NULL, NULL, &tv2);
    }
#endif
}