libdogecoin: src/cli/tool.c File Reference
tool.c File Reference
#include <assert.h>
#include <stdarg.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <getopt.h>
#include <unistd.h>
#include <dogecoin/bip32.h>
#include <dogecoin/base58.h>
#include <dogecoin/ecc.h>
#include <dogecoin/key.h>
#include <dogecoin/random.h>
#include <dogecoin/serialize.h>
#include <dogecoin/tx.h>
#include <dogecoin/utils.h>
Functions
dogecoin_bool addresses_from_pubkey (const dogecoin_chainparams *chain, const char *pubkey_hex, char *p2pkh_address)
Given a public key, it returns the addresses that correspond to it.
dogecoin_bool pubkey_from_privatekey (const dogecoin_chainparams *chain, const char *privkey_wif, char *pubkey_hex, size_t *sizeout)
Given a private key in WIF format, convert it to a public key and return it in hex format.
dogecoin_bool gen_privatekey (const dogecoin_chainparams *chain, char *privkey_wif, size_t strsize_wif, char *privkey_hex_or_null)
Generate a private key and export it in both WIF and hex format.
dogecoin_bool hd_gen_master (const dogecoin_chainparams *chain, char *masterkeyhex, size_t strsize)
Generate a master key from a random seed.
dogecoin_bool hd_print_node (const dogecoin_chainparams *chain, const char *nodeser)
It takes in a serialized extended public key and prints out all the information about it.
dogecoin_bool hd_derive (const dogecoin_chainparams *chain, const char *masterkey, const char *derived_path, char *extkeyout, size_t extkeyout_size)
It takes a master key, a path, and an output buffer. It derives the child key at the path and writes it to the output buffer.
Function Documentation
addresses_from_pubkey()
dogecoin_bool addresses_from_pubkey (const dogecoin_chainparams * chain, const char * pubkey_hex, char * p2pkh_address)
Given a public key, it returns the addresses that correspond to it.
Parameters
chain The chainparams struct for the chain you want to generate addresses for.
pubkey_hex The hexadecimal representation of the public key.
p2pkh_address The address in legacy format (DRnwTww6YB2zw1TTjiPfeFkfuabojfyaB8)
Returns
dogecoin_bool (uint8_t)
Definition at line 57 of file tool.c.
{
    if (!pubkey_hex)
        return false;
    if (strlen(pubkey_hex) != 66)
        return false;
    dogecoin_pubkey pubkey;
    dogecoin_pubkey_init(&pubkey);
    pubkey.compressed = 1;
    size_t outlen = 0;
    utils_hex_to_bin(pubkey_hex, pubkey.pubkey, strlen(pubkey_hex), &outlen);
    assert(dogecoin_pubkey_is_valid(&pubkey) == 1);
    dogecoin_pubkey_getaddr_p2pkh(&pubkey, chain, p2pkh_address);
    return true;
}
References dogecoin_pubkey_::compressed, dogecoin_pubkey_getaddr_p2pkh(), dogecoin_pubkey_init(), dogecoin_pubkey_is_valid(), dogecoin_pubkey_::pubkey, and utils_hex_to_bin().
Referenced by hd_print_node(), and main().
gen_privatekey()
dogecoin_bool gen_privatekey (const dogecoin_chainparams * chain, char * privkey_wif, size_t strsize_wif, char * privkey_hex_or_null)
Generate a private key and export it in both WIF and hex format.
Parameters
chain the chain parameters
privkey_wif the private key in WIF format
strsize_wif the size of the buffer to hold the WIF key
privkey_hex_or_null If you pass in a valid pointer, the function will export the private key in hex format.
Returns
dogecoin_bool (uint8_t)
Definition at line 111 of file tool.c.
{
    uint8_t pkeybase58c[34];
    pkeybase58c[0] = chain->b58prefix_secret_address;
    pkeybase58c[33] = 1; /* always use compressed keys */
    dogecoin_key key;
    dogecoin_privkey_init(&key);
    dogecoin_privkey_gen(&key);
    memcpy_safe(&pkeybase58c[1], key.privkey, DOGECOIN_ECKEY_PKEY_LENGTH);
    assert(dogecoin_base58_encode_check(pkeybase58c, 34, privkey_wif, strsize_wif) != 0);
    // also export the hex privkey if use had passed in a valid pointer
    // will always export 32 bytes
    if (privkey_hex_or_null != NULL)
        utils_bin_to_hex(key.privkey, DOGECOIN_ECKEY_PKEY_LENGTH, privkey_hex_or_null);
    dogecoin_privkey_cleanse(&key);
    return true;
}
References dogecoin_chainparams_::b58prefix_secret_address, dogecoin_base58_encode_check(), DOGECOIN_ECKEY_PKEY_LENGTH, dogecoin_privkey_cleanse(), dogecoin_privkey_gen(), dogecoin_privkey_init(), memcpy_safe(), and utils_bin_to_hex().
Referenced by main().
hd_derive()
dogecoin_bool hd_derive (const dogecoin_chainparams * chain, const char * masterkey, const char * derived_path, char * extkeyout, size_t extkeyout_size)
It takes a master key, a path, and an output buffer. It derives the child key at the path and writes it to the output buffer.
Parameters
chain The chain parameters.
masterkey The master key to derive the child key from.
derived_path The path to derive the key from.
extkeyout The output buffer to write the extended key to.
extkeyout_size The size of the extkeyout buffer.
Returns
dogecoin_bool (uint8_t)
Definition at line 204 of file tool.c.
{
    if (!derived_path || !masterkey || !extkeyout)
        return false;
    dogecoin_hdnode node, nodenew;
    if (!dogecoin_hdnode_deserialize(masterkey, chain, &node))
        return false;
    //check if we only have the publickey
    bool pubckd = !dogecoin_hdnode_has_privkey(&node);
    //derive child key, use pubckd or privckd
    if (!dogecoin_hd_generate_key(&nodenew, derived_path, pubckd ? node.public_key : node.private_key, node.chain_code, pubckd))
        return false;
    if (pubckd)
        dogecoin_hdnode_serialize_public(&nodenew, chain, extkeyout, extkeyout_size);
    else
        dogecoin_hdnode_serialize_private(&nodenew, chain, extkeyout, extkeyout_size);
    return true;
}
References dogecoin_hdnode::chain_code, dogecoin_hd_generate_key(), dogecoin_hdnode_deserialize(), dogecoin_hdnode_has_privkey(), dogecoin_hdnode_serialize_private(), dogecoin_hdnode_serialize_public(), dogecoin_hdnode::private_key, and dogecoin_hdnode::public_key.
Referenced by main().
hd_gen_master()
dogecoin_bool hd_gen_master (const dogecoin_chainparams * chain, char * masterkeyhex, size_t strsize)
Generate a master key from a random seed.
Parameters
chain The chain parameters to use.
masterkeyhex The master key in hexadecimal format.
strsize The size of the buffer to be returned.
Returns
dogecoin_bool (uint8_t)
Definition at line 138 of file tool.c.
{
    dogecoin_hdnode node;
    uint8_t seed[32];
    dogecoin_random_bytes(seed, 32, true);
    dogecoin_hdnode_from_seed(seed, 32, &node);
    dogecoin_mem_zero(seed, 32);
    dogecoin_hdnode_serialize_private(&node, chain, masterkeyhex, strsize);
    dogecoin_mem_zero(&node, sizeof(node));
    return true;
}
References dogecoin_hdnode_from_seed(), dogecoin_hdnode_serialize_private(), dogecoin_mem_zero(), and dogecoin_random_bytes().
Referenced by generateHDMasterPubKeypair(), and main().
hd_print_node()
dogecoin_bool hd_print_node (const dogecoin_chainparams * chain, const char * nodeser)
It takes in a serialized extended public key and prints out all the information about it.
Parameters
chain The chain parameters.
nodeser The serialized extended public key.
Returns
dogecoin_bool (uint8_t)
Definition at line 158 of file tool.c.
{
    dogecoin_hdnode node;
    if (!dogecoin_hdnode_deserialize(nodeser, chain, &node))
        return false;
    char str[128];
    size_t strsize = sizeof(str);
    printf("ext key:             %s\n", nodeser);
    uint8_t pkeybase58c[34];
    dogecoin_hdnode_serialize_public(&node, chain, str, strsize);
    printf("extended pubkey:     %s\n", str);
    if (!dogecoin_hdnode_get_pub_hex(&node, str, &strsize))
        return false;
    printf("pubkey hex:          %s\n", str);
    pkeybase58c[0] = chain->b58prefix_secret_address;
    pkeybase58c[33] = 1; /* always use compressed keys */
    char privkey_wif[128];
    memcpy_safe(&pkeybase58c[1], node.private_key, DOGECOIN_ECKEY_PKEY_LENGTH);
    assert(dogecoin_base58_encode_check(pkeybase58c, sizeof(pkeybase58c), privkey_wif, sizeof(privkey_wif)) != 0);
    if (dogecoin_hdnode_has_privkey(&node)) {
        printf("privatekey WIF:      %s\n", privkey_wif);
    }
    printf("depth:               %d\n", node.depth);
    printf("child index:         %d\n", node.child_num);
    char addr[34 + 1];
    addresses_from_pubkey(&dogecoin_chainparams_main, str, addr);
    printf("p2pkh address:       %s\n", addr);
    return true;
}
References addresses_from_pubkey(), dogecoin_chainparams_::b58prefix_secret_address, dogecoin_hdnode::child_num, dogecoin_hdnode::depth, dogecoin_base58_encode_check(), dogecoin_chainparams_main, DOGECOIN_ECKEY_PKEY_LENGTH, dogecoin_hdnode_deserialize(), dogecoin_hdnode_get_pub_hex(), dogecoin_hdnode_has_privkey(), dogecoin_hdnode_serialize_public(), memcpy_safe(), and dogecoin_hdnode::private_key.
Referenced by main().
pubkey_from_privatekey()
dogecoin_bool pubkey_from_privatekey (const dogecoin_chainparams * chain, const char * privkey_wif, char * pubkey_hex, size_t * sizeout)
Given a private key in WIF format, convert it to a public key and return it in hex format.
Parameters
chain The chainparams structure.
privkey_wif The private key in WIF format.
pubkey_hex The public key in hexadecimal format.
sizeout The size of the output buffer.
Returns
dogecoin_bool (uint8_t)
Definition at line 83 of file tool.c.
{
    dogecoin_key key;
    dogecoin_privkey_init(&key);
    if (!dogecoin_privkey_decode_wif(privkey_wif, chain, &key))
        return false;
    dogecoin_pubkey pubkey;
    dogecoin_pubkey_init(&pubkey);
    assert(dogecoin_pubkey_is_valid(&pubkey) == 0);
    dogecoin_pubkey_from_key(&key, &pubkey);
    assert(dogecoin_pubkey_is_valid(&pubkey) == 1);
    dogecoin_privkey_cleanse(&key);
    dogecoin_pubkey_get_hex(&pubkey, pubkey_hex, sizeout);
    dogecoin_pubkey_cleanse(&pubkey);
    return true;
}
References dogecoin_privkey_cleanse(), dogecoin_privkey_decode_wif(), dogecoin_privkey_init(), dogecoin_pubkey_cleanse(), dogecoin_pubkey_from_key(), dogecoin_pubkey_get_hex(), dogecoin_pubkey_init(), and dogecoin_pubkey_is_valid().
Referenced by main().