libdogecoin: include/dogecoin/transaction.h File Reference
transaction.h File Reference
#include <stdlib.h>
#include <stddef.h>
#include <stdio.h>
#include <string.h>
#include <dogecoin/uthash.h>
#include <dogecoin/dogecoin.h>
#include <dogecoin/tx.h>
Data Structures
struct working_transaction
Typedefs
typedef LIBDOGECOIN_BEGIN_DECL struct working_transaction working_transaction
Functions
LIBDOGECOIN_API working_transaction * new_transaction ()
This function instantiates a new working transaction, but does not add it to the hash table.
LIBDOGECOIN_API void add_transaction (working_transaction *working_tx)
This function takes a pointer to an existing working transaction object and adds it to the hash table.
LIBDOGECOIN_API working_transaction * find_transaction (int idx)
This function takes an index and returns the working transaction associated with that index in the hash table.
LIBDOGECOIN_API void remove_transaction (working_transaction *working_tx)
This function removes the specified working transaction from the hash table and frees the transactions in memory.
LIBDOGECOIN_API void remove_all ()
This function removes all working transactions from the hash table.
LIBDOGECOIN_API void print_transactions ()
This function prints the raw hex representation of each working transaction in the hash table.
LIBDOGECOIN_API void count_transactions ()
This function counts the number of working transactions currently in the hash table.
LIBDOGECOIN_API int by_id ()
LIBDOGECOIN_API const char * getl (const char *prompt)
This function prints a prompt and parses the user's response for a CLI tool.
LIBDOGECOIN_API const char * get_raw_tx (const char *prompt_tx)
This function prompts the user to enter a raw transaction and parses it.
LIBDOGECOIN_API const char * get_private_key (const char *prompt_key)
This function prompts the user to enter a private key and parses it.
LIBDOGECOIN_API int start_transaction ()
This function creates a new transaction, places it in the hash table, and returns the index of the new transaction, starting from 1 and incrementing each subsequent call.
LIBDOGECOIN_API int save_raw_transaction (int txindex, const char *hexadecimal_transaction)
This function takes a transaction represented in raw hex and serializes it into a transaction which is then saved in the hashtable at the specified index.
LIBDOGECOIN_API int add_utxo (int txindex, char *hex_utxo_txid, int vout)
This function takes a transaction represented in raw hex and adds it as an input to the specified working transaction.
LIBDOGECOIN_API int add_output (int txindex, char *destinationaddress, char *amount)
This function constructs an output sending the specified amount to the specified address and adds it to the transaction with the specified index.
LIBDOGECOIN_API char * finalize_transaction (int txindex, char *destinationaddress, char *subtractedfee, char *out_dogeamount_for_verification, char *public_key)
This function 'closes the inputs' by returning change to the recipient after the total amount and desired fee is confirmed.
LIBDOGECOIN_API char * get_raw_transaction (int txindex)
This function takes an index of a working transaction and returns the hex representation of it.
LIBDOGECOIN_API void clear_transaction (int txindex)
This function removes the specified working transaction from the hash table.
LIBDOGECOIN_API int sign_raw_transaction (int inputindex, char *incomingrawtx, char *scripthex, int sighashtype, char *privkey)
This function signs the specified input of a working transaction, according to the signing parameters specified.
LIBDOGECOIN_API int sign_indexed_raw_transaction (int txindex, int inputindex, char *incomingrawtx, char *scripthex, int sighashtype, char *privkey)
This function is for internal use and saves the result of sign_raw_transaction to a working transaction in the hash table.
LIBDOGECOIN_API int sign_transaction (int txindex, char *script_pubkey, char *privkey)
This function signs all of the inputs in the specified working transaction using the provided script pubkey and private key.
LIBDOGECOIN_API int store_raw_transaction (char *incomingrawtx)
This function stores a raw transaction to the next available working transaction in the hash table.
Variables
static working_transaction * transactions = NULL
Typedef Documentation
working_transaction
typedef LIBDOGECOIN_BEGIN_DECL struct working_transaction working_transaction
Function Documentation
add_output()
LIBDOGECOIN_API int add_output (int txindex, char * destinationaddress, char * amount)
This function constructs an output sending the specified amount to the specified address and adds it to the transaction with the specified index.
Parameters
txindex The index of the transaction where the output will be added.
destinationaddress The address to send the funds to.
amount The amount of dogecoin to send.
Returns
1 if the transaction input was added successfully, 0 otherwise.
Definition at line 321 of file transaction.c.
{
    // find working transaction by index and pass to funciton local variable to manipulate:
    working_transaction* tx = find_transaction(txindex);
    // guard against null pointer exceptions
    if (tx == NULL) {
        return false;
    }
    // determine intended network by checking address prefix:
    const dogecoin_chainparams* chain = (destinationaddress[0] == 'D') ? &dogecoin_chainparams_main : &dogecoin_chainparams_test;
    uint64_t koinu = coins_to_koinu_str(amount);
    // calculate total minus fees
    // pass in transaction obect, network paramters, amount of dogecoin to send to address and finally p2pkh address:
    return dogecoin_tx_add_address_out(tx->transaction, chain, (int64_t)koinu, destinationaddress);
}
References coins_to_koinu_str(), dogecoin_chainparams_main, dogecoin_chainparams_test, dogecoin_tx_add_address_out(), find_transaction(), and working_transaction::transaction.
Referenced by sub_menu().
add_transaction()
LIBDOGECOIN_API void add_transaction (working_transaction * working_tx)
This function takes a pointer to an existing working transaction object and adds it to the hash table.
Parameters
working_tx The pointer to the working transaction.
Returns
Nothing.
Definition at line 57 of file transaction.c.
{
    working_transaction *tx;
    HASH_FIND_INT(transactions, &working_tx->idx, tx);
    if (tx == NULL) {
        HASH_ADD_INT(transactions, idx, working_tx);
    } else {
        HASH_REPLACE_INT(transactions, idx, working_tx, tx);
    }
    dogecoin_free(tx);
}
References dogecoin_free(), HASH_ADD_INT, HASH_FIND_INT, HASH_REPLACE_INT, working_transaction::idx, and transactions.
Referenced by start_transaction().
add_utxo()
LIBDOGECOIN_API int add_utxo (int txindex, char * hex_utxo_txid, int vout)
This function takes a transaction represented in raw hex and adds it as an input to the specified working transaction.
Parameters
txindex The index of the transaction to add the input to.
hex_utxo_txid The raw transaction hex of the input transaction.
vout The output index of the input transaction containing spendable funds.
Returns
1 if the transaction input was added successfully, 0 otherwise.
Definition at line 283 of file transaction.c.
{
    // find working transaction by index and pass to funciton local variable to manipulate:
    working_transaction* tx = find_transaction(txindex);
    // guard against null pointer exceptions
    if (tx == NULL) return false;
    size_t flag = tx->transaction->vin->len;
    // instantiate empty dogecoin_tx_in object to set previous output txid and output n:
    dogecoin_tx_in* tx_in = dogecoin_tx_in_new();
    // add prevout hash to tx_in->prevout.hash in prep of adding to tx->transaction-vin vector
    utils_uint256_sethex((char *)hex_utxo_txid, (uint8_t *)tx_in->prevout.hash);
    // set index of utxo we want to spend
    tx_in->prevout.n = vout;
    // add to working tx object
    vector_add(tx->transaction->vin, tx_in);
    // free tx_in struct since it has been added to our working tx
    // ensure the length of our working tx inputs length has incremented by 1
    // which will return true if successful:
    return flag + 1 == tx->transaction->vin->len;
}
References dogecoin_tx_in_new(), find_transaction(), dogecoin_tx_outpoint_::hash, vector::len, dogecoin_tx_outpoint_::n, dogecoin_tx_in_::prevout, working_transaction::transaction, utils_uint256_sethex(), vector_add(), and dogecoin_tx_::vin.
Referenced by sub_menu().
by_id()
LIBDOGECOIN_API int by_id ()
clear_transaction()
LIBDOGECOIN_API void clear_transaction (int txindex)
This function removes the specified working transaction from the hash table.
Parameters
txindex The index of the working transaction to remove.
Returns
Nothing.
Definition at line 460 of file transaction.c.
{
    // find working transaction by index and pass to funciton local variable to manipulate:
    working_transaction* tx = find_transaction(txindex);
    // remove from hashmap
    remove_transaction(tx);
}
References find_transaction(), and remove_transaction().
Referenced by main_menu().
count_transactions()
LIBDOGECOIN_API void count_transactions ()
This function counts the number of working transactions currently in the hash table.
Returns
Nothing.
Definition at line 133 of file transaction.c.
{
    int temp = HASH_COUNT(transactions);
    printf("there are %d transactions\n", temp);
}
References HASH_COUNT, and transactions.
Referenced by main_menu().
finalize_transaction()
LIBDOGECOIN_API char * finalize_transaction (int txindex, char * destinationaddress, char * subtractedfee, char * out_dogeamount_for_verification, char * changeaddress)
This function 'closes the inputs' by returning change to the recipient after the total amount and desired fee is confirmed.
Parameters
txindex The index of the working transaction to finalize.
destinationaddress The address where the funds are being sent.
subtractedfee The amount to set aside as a fee to the miner.
out_dogeamount_for_verification An echo of the total amount to send.
changeaddress The address of the sender to receive the change.
Returns
The hex of the finalized transaction.
Definition at line 378 of file transaction.c.
{
    // find working transaction by index and pass to funciton local variable to manipulate:
    working_transaction* tx = find_transaction(txindex);
    // guard against null pointer exceptions
    if (tx == NULL) return false;
    // determine intended network by checking address prefix:
    int is_testnet = chain_from_b58_prefix_bool(destinationaddress);
    uint64_t subtractedfee_koinu = coins_to_koinu_str(subtractedfee);
    uint64_t out_koinu_for_verification = coins_to_koinu_str(out_dogeamount_for_verification);
    // calculate total minus desired fees
    uint64_t total = (uint64_t)out_koinu_for_verification - (uint64_t)subtractedfee_koinu, tx_out_total = 0;
    int i, p2pkh_count = 0, length = (int)tx->transaction->vout->len;
    // iterate through transaction output values while adding each one to tx_out_total:
    for (i = 0; i < length; i++) {
        dogecoin_tx_out* tx_out_tmp = vector_idx(tx->transaction->vout, i);
        tx_out_total += tx_out_tmp->value;
        char p2pkh[36]; //mlumin: this was originally 17, caused problems if < 25.  p2pkh len is 24-36.
        //MLUMIN:MSVC
        dogecoin_mem_zero(p2pkh, sizeof(p2pkh));
        p2pkh_count = dogecoin_script_hash_to_p2pkh(tx_out_tmp, (char *)p2pkh, is_testnet);
        if (i == length - 1 && changeaddress) {
            // manually make change and send back to our public key address
            if (make_change(txindex, changeaddress, subtractedfee_koinu, out_koinu_for_verification - tx_out_total)) {
                p2pkh_count += 1;
                tx_out_tmp = vector_idx(tx->transaction->vout, tx->transaction->vout->len - 1);
                tx_out_total += tx_out_tmp->value;
            }
            break;
        }
    }
    if (p2pkh_count < 1) {
        printf("p2pkh address not found from any output script hash!\n");
        return false;
    }
    // pass in transaction obect, network paramters, amount of dogecoin to send to address and finally p2pkh address:
    return tx_out_total == total ? get_raw_transaction(txindex) : false;
}
References chain_from_b58_prefix_bool(), coins_to_koinu_str(), dogecoin_mem_zero(), dogecoin_script_hash_to_p2pkh(), find_transaction(), get_raw_transaction(), is_testnet, vector::len, make_change(), working_transaction::transaction, dogecoin_tx_out_::value, vector_idx, and dogecoin_tx_::vout.
Referenced by sub_menu().
find_transaction()
LIBDOGECOIN_API working_transaction * find_transaction (int idx)
This function takes an index and returns the working transaction associated with that index in the hash table.
Parameters
idx The index of the target working transaction.
Returns
The pointer to the working transaction associated with the provided index.
Definition at line 77 of file transaction.c.
{
    working_transaction *working_tx;
    HASH_FIND_INT(transactions, &idx, working_tx);
    return working_tx;
}
References HASH_FIND_INT, working_transaction::idx, and transactions.
Referenced by add_output(), add_utxo(), clear_transaction(), finalize_transaction(), get_raw_transaction(), main_menu(), make_change(), save_raw_transaction(), store_raw_transaction(), transaction_input_menu(), and transaction_output_menu().
get_private_key()
LIBDOGECOIN_API const char * get_private_key (const char * prompt_key)
This function prompts the user to enter a private key and parses it.
Parameters
prompt_tx The prompt to display to the user.
Returns
The string containing user input.
Definition at line 206 of file transaction.c.
{
    static char buf_key[100];
    char *p_key;
    printf("%s? ", prompt_key); fflush(stdout);
    p_key = fgets(buf_key, sizeof(buf_key), stdin);
    if (p_key == NULL || (p_key = strchr(buf_key, '\n')) == NULL) {
        puts("invalid input!");
        exit(EXIT_FAILURE);
    }
    *p_key = '\0';
    return buf_key;
}
Referenced by signing_menu(), and transaction_input_menu().
get_raw_transaction()
LIBDOGECOIN_API char * get_raw_transaction (int txindex)
This function takes an index of a working transaction and returns the hex representation of it.
Parameters
txindex The index of the working transaction.
Returns
The hex representation of the transaction.
Definition at line 432 of file transaction.c.
{
    // find working transaction by index and pass to function local variable to manipulate:
    working_transaction* tx = find_transaction(txindex);
    // guard against null pointer exceptions
    if (tx == NULL) return false;
    // new allocated cstring to store hexadeicmal buffer string:
    cstring* serialized_transaction = cstr_new_sz(1024);
    // serialize transaction object to new cstring:
    dogecoin_tx_serialize(serialized_transaction, tx->transaction);
    char* hexadecimal_buffer = utils_uint8_to_hex((unsigned char*)serialized_transaction->str, serialized_transaction->len);
    cstr_free(serialized_transaction, true);
    return hexadecimal_buffer;
}
References cstr_free(), cstr_new_sz(), dogecoin_tx_serialize(), find_transaction(), cstring::len, cstring::str, working_transaction::transaction, and utils_uint8_to_hex().
Referenced by finalize_transaction(), main_menu(), print_transactions(), sign_transaction(), signing_menu(), sub_menu(), and transaction_input_menu().
get_raw_tx()
LIBDOGECOIN_API const char * get_raw_tx (const char * prompt_tx)
This function prompts the user to enter a raw transaction and parses it.
Parameters
prompt_tx The prompt to display to the user.
Returns
The string containing user input.
Definition at line 184 of file transaction.c.
{
    static char buf_tx[1000*100];
    char *p_tx;
    printf("%s? ", prompt_tx); fflush(stdout);
    p_tx = fgets(buf_tx, sizeof(buf_tx), stdin);
    if (p_tx == NULL || (p_tx = strchr(buf_tx, '\n')) == NULL) {
        puts("invalid input!");
        exit(EXIT_FAILURE);
    }
    *p_tx = '\0';
    return buf_tx;
}
Referenced by main_menu(), signing_menu(), and transaction_input_menu().
getl()
LIBDOGECOIN_API const char * getl (const char * prompt)
This function prints a prompt and parses the user's response for a CLI tool.
Parameters
prompt The prompt to display to the user.
Returns
The string containing user input.
Definition at line 162 of file transaction.c.
{
    static char buf[100];
    char *p;
    printf("%s? ", prompt); fflush(stdout);
    p = fgets(buf, sizeof(buf), stdin);
    if (p == NULL || (p = strchr(buf, '\n')) == NULL) {
        puts("invalid input!");
        exit(EXIT_FAILURE);
    }
    *p = '\0';
    return buf;
}
Referenced by chainparams_menu(), edit_menu(), main_menu(), signing_menu(), sub_menu(), transaction_input_menu(), and transaction_output_menu().
new_transaction()
LIBDOGECOIN_API working_transaction * new_transaction ()
This function instantiates a new working transaction, but does not add it to the hash table.
Returns
A pointer to the new working transaction.
Definition at line 42 of file transaction.c.
{
    working_transaction* working_tx = (struct working_transaction*)dogecoin_calloc(1, sizeof *working_tx);
    working_tx->transaction = dogecoin_tx_new();
    working_tx->idx = HASH_COUNT(transactions) + 1;
    return working_tx;
}
References dogecoin_calloc(), dogecoin_tx_new(), HASH_COUNT, working_transaction::idx, working_transaction::transaction, and transactions.
Referenced by start_transaction().
print_transactions()
LIBDOGECOIN_API void print_transactions ()
This function prints the raw hex representation of each working transaction in the hash table.
Returns
Nothing.
Definition at line 118 of file transaction.c.
{
    struct working_transaction *s;
    for (s = transactions; s != NULL; s = (struct working_transaction*)(s->hh.next)) {
        printf("\nworking transaction id: %d\nraw transaction (hexadecimal): %s\n", s->idx, get_raw_transaction(s->idx));
    }
}
References get_raw_transaction(), working_transaction::hh, working_transaction::idx, UT_hash_handle::next, and transactions.
Referenced by main_menu().
remove_all()
LIBDOGECOIN_API void remove_all ()
This function removes all working transactions from the hash table.
Returns
Nothing.
Definition at line 103 of file transaction.c.
                  {
    struct working_transaction *current_tx;
    struct working_transaction *tmp;
    HASH_ITER(hh, transactions, current_tx, tmp) {
        remove_transaction(current_tx);
    }
}
References HASH_ITER, working_transaction::hh, remove_transaction(), and transactions.
Referenced by main_menu().
remove_transaction()
LIBDOGECOIN_API void remove_transaction (working_transaction * working_tx)
This function removes the specified working transaction from the hash table and frees the transactions in memory.
Parameters
working_tx The pointer to the transaction to remove.
Returns
Nothing.
Definition at line 91 of file transaction.c.
{
    HASH_DEL(transactions, working_tx); /* delete it (transactions advances to next) */
    dogecoin_tx_free(working_tx->transaction);
    dogecoin_free(working_tx);
}
References dogecoin_free(), dogecoin_tx_free(), HASH_DEL, working_transaction::transaction, and transactions.
Referenced by clear_transaction(), main_menu(), and remove_all().
save_raw_transaction()
LIBDOGECOIN_API int save_raw_transaction (int txindex, const char * hexadecimal_transaction)
This function takes a transaction represented in raw hex and serializes it into a transaction which is then saved in the hashtable at the specified index.
Parameters
txindex The index to save the transaction to.
hexadecimal_transaction The raw hex of the transaction to serialize and save.
Returns
1 if the transaction was saved successfully, 0 otherwise.
Definition at line 244 of file transaction.c.
{
    debug_print("raw_hexadecimal_transaction: %s\n", hexadecimal_transaction);
    if (strlen(hexadecimal_transaction) > 1024*100) { //don't accept tx larger then 100kb
        printf("tx too large (max 100kb)\n");
        return false;
    }
    // deserialize transaction
    dogecoin_tx* txtmp = dogecoin_tx_new();
    uint8_t* data_bin = dogecoin_malloc(strlen(hexadecimal_transaction));
    size_t outlength = 0;
    // convert incomingrawtx to byte array to dogecoin_tx and if it fails free from memory
    utils_hex_to_bin(hexadecimal_transaction, data_bin, strlen(hexadecimal_transaction), &outlength);
    if (!dogecoin_tx_deserialize(data_bin, outlength, txtmp, NULL)) {
        // free byte array
        dogecoin_free(data_bin);
        // free dogecoin_tx
        dogecoin_tx_free(txtmp);
        printf("invalid tx hex");
        return false;
    }
    // free byte array
    working_transaction* tx_raw = find_transaction(txindex);
    dogecoin_tx_copy(tx_raw->transaction, txtmp);
    dogecoin_tx_free(txtmp);
    dogecoin_free(data_bin);
    return true;
}
References debug_print, dogecoin_free(), dogecoin_malloc(), dogecoin_tx_copy(), dogecoin_tx_deserialize(), dogecoin_tx_free(), dogecoin_tx_new(), find_transaction(), working_transaction::transaction, and utils_hex_to_bin().
Referenced by main_menu(), sign_indexed_raw_transaction(), and sign_transaction().
sign_indexed_raw_transaction()
LIBDOGECOIN_API int sign_indexed_raw_transaction (int txindex, int inputindex, char * incomingrawtx, char * scripthex, int sighashtype, char * privkey)
This function is for internal use and saves the result of sign_raw_transaction to a working transaction in the hash table.
Parameters
txindex The index where the signed transaction will be saved.
inputindex The index of the current transaction input to sign.
incomingrawtx The hex representation of the transaction to sign.
scripthex The hex representation of the public key script.
sighashtype The type of signature hash to perform.
privkey The private key used to sign the transaction input.
Returns
1 if the transaction was signed successfully, 0 otherwise.
Definition at line 598 of file transaction.c.
{
    if (!txindex) return false;
    if (!sign_raw_transaction(inputindex, incomingrawtx, scripthex, sighashtype, privkey)) {
        printf("error signing raw transaction\n");
        return false;
    }
    if (!save_raw_transaction(txindex, incomingrawtx)) {
        printf("error saving transaction!\n");
        return false;
    }
    return true;
}
References save_raw_transaction(), and sign_raw_transaction().
Referenced by signing_menu(), and transaction_input_menu().
sign_raw_transaction()
LIBDOGECOIN_API int sign_raw_transaction (int inputindex, char * incomingrawtx, char * scripthex, int sighashtype, char * privkey)
This function signs the specified input of a working transaction, according to the signing parameters specified.
Parameters
inputindex The index of the current transaction input to sign.
incomingrawtx The hex representation of the transaction to sign.
scripthex The hex representation of the public key script.
sighashtype The type of signature hash to perform.
privkey The private key used to sign the transaction input.
Returns
1 if the raw transaction was signed successfully, 0 otherwise.
Definition at line 479 of file transaction.c.
{
    if(!incomingrawtx || !scripthex) return false;
    if (strlen(incomingrawtx) > 1024*100) { //don't accept tx larger then 100kb
        printf("tx too large (max 100kb)\n");
        return false;
    }
    const dogecoin_chainparams* chain = (privkey[0] == 'c') ? &dogecoin_chainparams_test : &dogecoin_chainparams_main;
    // deserialize transaction
    dogecoin_tx* txtmp = dogecoin_tx_new();
    uint8_t* data_bin = dogecoin_malloc(strlen(incomingrawtx) / 2);
    size_t outlength = 0;
    // convert incomingrawtx to byte array to dogecoin_tx and if it fails free from memory
    utils_hex_to_bin(incomingrawtx, data_bin, strlen(incomingrawtx), &outlength);
    if (!dogecoin_tx_deserialize(data_bin, outlength, txtmp, NULL)) {
        // free byte array
        dogecoin_free(data_bin);
        // free dogecoin_tx
        dogecoin_tx_free(txtmp);
        printf("invalid tx hex\n");
        return false;
    }
    // free byte array
    dogecoin_free(data_bin);
    // if utxo input doesn't exist abort attempt to sign message
    if ((size_t)inputindex >= txtmp->vin->len) {
        // free dogecoin_tx
        dogecoin_tx_free(txtmp);
        printf("input index out of range");
        return false;
    }
    // initialize byte array with length equal to account for byte size
    uint8_t* script_data = dogecoin_uint8_vla(strlen(scripthex));
    // convert hex string to byte array
    utils_hex_to_bin(scripthex, script_data, strlen(scripthex), &outlength);
    cstring* script = cstr_new_buf(script_data, outlength);
    uint256 sighash;
    dogecoin_mem_zero(sighash, sizeof(sighash));
    free(script_data);
    dogecoin_tx_sighash(txtmp, script, inputindex, sighashtype, sighash);
    char *hex = utils_uint8_to_hex(sighash, 32);
    utils_reverse_hex(hex, 64);
    debug_print("script: %s\n", scripthex);
    debug_print("script-type: %s\n", dogecoin_tx_out_type_to_str(dogecoin_script_classify(script, NULL)));
    debug_print("inputindex: %d\n", inputindex);
    debug_print("sighashtype: %d\n", sighashtype);
    debug_print("hash: %s\n", hex);
    // sign
    dogecoin_bool sign = false;
    dogecoin_key key;
    dogecoin_privkey_init(&key);
    if (dogecoin_privkey_decode_wif(privkey, chain, &key)) {
        sign = true;
    } else {
        if (privkey) {
            if (strlen(privkey) > 50) {
                dogecoin_tx_free(txtmp);
                cstr_free(script, true);
                return false;
            }
        } else {
            return false;
        }
    }
    if (sign) {
        uint8_t sigcompact[64] = {0};
        size_t sigderlen = 74 + 1; //&hashtype
        uint8_t sigder_plus_hashtype[75] = {0};
        enum dogecoin_tx_sign_result res = dogecoin_tx_sign_input(txtmp, script, &key, inputindex, sighashtype, sigcompact, sigder_plus_hashtype, &sigderlen);
        cstr_free(script, true);
        if (res != DOGECOIN_SIGN_OK) return false;
        char sigcompacthex[64*2+1] = {0};
        utils_bin_to_hex((unsigned char *)sigcompact, 64, sigcompacthex);
        char sigderhex[74*2+2+1]; //74 der, 2 hashtype, 1 nullbyte
        dogecoin_mem_zero(sigderhex, sizeof(sigderhex));
        utils_bin_to_hex((unsigned char *)sigder_plus_hashtype, sigderlen, sigderhex);
        debug_print("\nsignature created:\nsignature compact: %s\n", sigcompacthex);
        debug_print("signature DER (+hashtype): %s\n", sigderhex);
        cstring* signed_tx = cstr_new_sz(1024);
        dogecoin_tx_serialize(signed_tx, txtmp);
        char* signed_tx_hex = dogecoin_char_vla(signed_tx->len * 2 + 1);
        utils_bin_to_hex((unsigned char *)signed_tx->str, signed_tx->len, signed_tx_hex);
        memcpy(incomingrawtx, signed_tx_hex, strlen(signed_tx_hex));
        debug_print("signed TX: %s\n", incomingrawtx);
        cstr_free(signed_tx, true);
        dogecoin_tx_free(txtmp);
        free(signed_tx_hex);
    }
    return true;
}
References cstr_free(), cstr_new_buf(), cstr_new_sz(), debug_print, dogecoin_chainparams_main, dogecoin_chainparams_test, dogecoin_char_vla(), dogecoin_free(), dogecoin_malloc(), dogecoin_mem_zero(), dogecoin_privkey_decode_wif(), dogecoin_privkey_init(), dogecoin_script_classify(), DOGECOIN_SIGN_OK, dogecoin_tx_deserialize(), dogecoin_tx_free(), dogecoin_tx_new(), dogecoin_tx_out_type_to_str(), dogecoin_tx_serialize(), dogecoin_tx_sighash(), dogecoin_tx_sign_input(), dogecoin_uint8_vla(), cstring::len, vector::len, cstring::str, uint256, utils_bin_to_hex(), utils_hex_to_bin(), utils_reverse_hex(), utils_uint8_to_hex(), and dogecoin_tx_::vin.
Referenced by sign_indexed_raw_transaction(), and sign_transaction().
sign_transaction()
LIBDOGECOIN_API int sign_transaction (int txindex, char * script_pubkey, char * privkey)
This function signs all of the inputs in the specified working transaction using the provided script pubkey and private key.
Parameters
txindex The index of the working transaction to sign.
script_pubkey The hex representation of the public key script.
privkey The private key used to sign the transaction input.
Returns
1 if the transaction was signed successfully, 0 otherwise.
Definition at line 621 of file transaction.c.
{
    char* raw_hexadecimal_transaction = get_raw_transaction(txindex);
    // deserialize transaction
    dogecoin_tx* txtmp = dogecoin_tx_new();
    uint8_t* data_bin = dogecoin_malloc(strlen(raw_hexadecimal_transaction) / 2);
    size_t outlength = 0;
    // convert incomingrawtx to byte array to dogecoin_tx and if it fails free from memory
    utils_hex_to_bin(raw_hexadecimal_transaction, data_bin, strlen(raw_hexadecimal_transaction), &outlength);
    if (!dogecoin_tx_deserialize(data_bin, outlength, txtmp, NULL)) {
        // free byte array
        dogecoin_free(data_bin);
        // free dogecoin_tx
        dogecoin_tx_free(txtmp);
        printf("invalid tx hex\n");
        return false;
    }
    // free byte array
    dogecoin_free(data_bin);
    size_t i = 0, len = txtmp->vin->len;
    for (; i < len; i++) {
        if (!sign_raw_transaction(i, raw_hexadecimal_transaction, script_pubkey, 1, privkey)) {
            printf("error signing raw transaction\n");
            return false;
        }
    }
    save_raw_transaction(txindex, raw_hexadecimal_transaction);
    dogecoin_tx_free(txtmp);
    return true;
}
References dogecoin_free(), dogecoin_malloc(), dogecoin_tx_deserialize(), dogecoin_tx_free(), dogecoin_tx_new(), get_raw_transaction(), vector::len, save_raw_transaction(), sign_raw_transaction(), utils_hex_to_bin(), and dogecoin_tx_::vin.
start_transaction()
LIBDOGECOIN_API int start_transaction ()
This function creates a new transaction, places it in the hash table, and returns the index of the new transaction, starting from 1 and incrementing each subsequent call.
Returns
The index of the new transaction.
Definition at line 227 of file transaction.c.
{
    working_transaction* working_tx = new_transaction();
    int index = working_tx->idx;
    add_transaction(working_tx);
    return index;
}
References add_transaction(), working_transaction::idx, and new_transaction().
Referenced by main_menu(), and store_raw_transaction().
store_raw_transaction()
LIBDOGECOIN_API int store_raw_transaction (char * incomingrawtx)
This function stores a raw transaction to the next available working transaction in the hash table.
Parameters
incomingrawtx The hex of the raw transaction
Returns
The index of the new working transaction if stored successfully, 0 otherwise.
Definition at line 659 of file transaction.c.
{
    if (strlen(incomingrawtx) > 1024*100) { //don't accept tx larger then 100kb
        printf("tx too large (max 100kb)\n");
        return false;
    }
    // deserialize transaction
    dogecoin_tx* txtmp = dogecoin_tx_new();
    int txindex = start_transaction();
    working_transaction* tx_raw = find_transaction(txindex);
    uint8_t* data_bin = dogecoin_malloc(strlen(incomingrawtx));
    size_t outlength = 0;
    // convert incomingrawtx to byte array to dogecoin_tx and if it fails free from memory
    utils_hex_to_bin(incomingrawtx, data_bin, strlen(incomingrawtx), &outlength);
    if (!dogecoin_tx_deserialize(data_bin, outlength, txtmp, NULL)) {
        // free byte array
        dogecoin_free(data_bin);
        // free dogecoin_tx
        dogecoin_tx_free(txtmp);
        printf("invalid tx hex");
        return false;
    }
    // free byte array
    dogecoin_free(data_bin);
    dogecoin_tx_copy(tx_raw->transaction, txtmp);
    dogecoin_tx_free(txtmp);
    return txindex;
}
References dogecoin_free(), dogecoin_malloc(), dogecoin_tx_copy(), dogecoin_tx_deserialize(), dogecoin_tx_free(), dogecoin_tx_new(), find_transaction(), start_transaction(), working_transaction::transaction, and utils_hex_to_bin().
Variable Documentation
transactions
working_transaction* transactions = NULL static
Definition at line 46 of file transaction.h.
Referenced by add_transaction(), count_transactions(), find_transaction(), new_transaction(), print_transactions(), remove_all(), and remove_transaction().