libdogecoin: src/utils.c File Reference
utils.c File Reference
#include <ctype.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <string.h>
#include <assert.h>
#include <time.h>
#include <dogecoin/cstr.h>
#include <dogecoin/mem.h>
#include <dogecoin/utils.h>
#include <dogecoin/vector.h>
#include <unistd.h>
Macros
#define MAX_LEN 128
Functions
void utils_clear_buffers (void)
This function clears the buffers used for functions inside utils.c.
void utils_hex_to_bin (const char *str, unsigned char *out, size_t inLen, size_t *outLen)
This function takes a hex-encoded string and loads a buffer with its binary representation.
uint8_t * utils_hex_to_uint8 (const char *str)
This function takes a hex-encoded string and returns the binary representation as a uint8_t array.
void utils_bin_to_hex (unsigned char *bin_in, size_t inlen, char *hex_out)
This function takes an array of raw data and converts them to a hex-encoded string.
char * utils_uint8_to_hex (const uint8_t *bin, size_t l)
This function takes an array of raw bytes and converts them to a hex-encoded string.
void utils_reverse_hex (char *h, size_t len)
This function takes a hex-encoded string and reverses the order of its bytes.
signed char utils_hex_digit (char c)
This function takes a char from a hex string and returns the actual hex digit as a signed char.
void utils_uint256_sethex (char *psz, uint8_t *out)
This function takes a hex-encoded string and sets a 256-bit array to the numerical value in little endian format.
void * safe_malloc (size_t size)
This function executes malloc() but exits the program if unsuccessful.
void dogecoin_cheap_random_bytes (uint8_t *buf, size_t len)
This function generates a buffer of random bytes.
void dogecoin_get_default_datadir (cstring *path_out)
This function takes a path variable and appends the default data directory according to the user's operating system.
void dogecoin_file_commit (FILE *file)
This function flushes all data left in the output stream into the specified file.
void print_header (char *filepath)
void print_image (FILE *fptr)
void print_bits (size_t const size, void const *ptr)
void prepend (char *s, const char *t)
Allows prepending characters (char* t) to the beginning of a string (char* s).
void append (char *s, char *t)
Allows appending characters (char* t) to the end of a string (char* s).
void text_to_hex (char *in, char *out)
function to convert ascii text to hexadecimal string
const char * get_build ()
void dogecoin_str_reverse (char s[])
void dogecoin_uitoa (int n, char s[])
bool dogecoin_network_enabled ()
unsigned int base64_int (unsigned int ch)
unsigned int base64_encoded_size (unsigned int in_size)
unsigned int base64_decoded_size (unsigned int in_size)
unsigned int base64_encode (const unsigned char *in, unsigned int in_len, unsigned char *out)
unsigned int base64_decode (const unsigned char *in, unsigned int in_len, unsigned char *out)
Variables
static uint8_t buffer_hex_to_uint8 [TO_UINT8_HEX_BUF_LEN]
static char buffer_uint8_to_hex [TO_UINT8_HEX_BUF_LEN]
const signed char p_util_hexdigit [256]
unsigned char base64_char [] = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"
Macro Definition Documentation
MAX_LEN
#define MAX_LEN 128
Definition at line 80 of file utils.c.
Function Documentation
append()
void append (char * s, char * t)
Allows appending characters (char* t) to the end of a string (char* s).
Parameters
s The string to append to.
t The characters that will be appended.
Definition at line 491 of file utils.c.
    {
    size_t i = 0, length = 0;
    /* get length of char* s */
    for (; memcmp(&s[i], "\0", 1) != 0; i++) length++;
    /*  append char* t to char* s */
    for (i = 0; memcmp(&t[i], "\0", 1) != 0; i++) {
        s[length + i] = t[i];
        }
    memcpy(&s[length + i], "\0", 1);
    }
Referenced by cstr_append_cstr(), and evutil_addrinfo_append_().
base64_decode()
unsigned int base64_decode (const unsigned char * in, unsigned int in_len, unsigned char * out)
Definition at line 649 of file utils.c.
{
    unsigned int i=0, j=0, k=0, s[4];
    for (i=0;i<in_len;i++) {
        s[j++]=base64_int(*(in+i));
        if (j==4) {
            out[k+0] = ((s[0]&255)<<2)+((s[1]&0x30)>>4);
            if (s[2]!=64) {
                out[k+1] = ((s[1]&0x0F)<<4)+((s[2]&0x3C)>>2);
                if ((s[3]!=64)) {
                    out[k+2] = ((s[2]&0x03)<<6)+(s[3]); k+=3;
                } else {
                    k+=2;
                }
            } else {
                k+=1;
            }
            j=0;
        }
    }
    out[k] = '\0';
    return k;
}
References base64_int().
Referenced by verify_message().
base64_decoded_size()
unsigned int base64_decoded_size (unsigned int in_size)
Definition at line 611 of file utils.c.
{
    return ((3*in_size)/4);
}
Referenced by verify_message().
base64_encode()
unsigned int base64_encode (const unsigned char * in, unsigned int in_len, unsigned char * out)
Definition at line 616 of file utils.c.
{
    unsigned int i=0, j=0, k=0, s[3];
    for (i=0;i<in_len;i++) {
        s[j++]=*(in+i);
        if (j==3) {
            out[k+0] = base64_char[ (s[0]&255)>>2 ];
            out[k+1] = base64_char[ ((s[0]&0x03)<<4)+((s[1]&0xF0)>>4) ];
            out[k+2] = base64_char[ ((s[1]&0x0F)<<2)+((s[2]&0xC0)>>6) ];
            out[k+3] = base64_char[ s[2]&0x3F ];
            j=0; k+=4;
        }
    }
    if (j) {
        if (j==1)
            s[1] = 0;
        out[k+0] = base64_char[ (s[0]&255)>>2 ];
        out[k+1] = base64_char[ ((s[0]&0x03)<<4)+((s[1]&0xF0)>>4) ];
        if (j==2)
            out[k+2] = base64_char[ ((s[1]&0x0F)<<2) ];
        else
            out[k+2] = '=';
        out[k+3] = '=';
        k+=4;
    }
    out[k] = '\0';
    return k;
}
References base64_char.
Referenced by sign_message().
base64_encoded_size()
unsigned int base64_encoded_size (unsigned int in_size)
Definition at line 600 of file utils.c.
{
    // size equals 4*floor((1/3)*(in_size+2));
    unsigned int i, j = 0;
    for (i=0;i<in_size;i++) {
        if (i % 3 == 0)
        j += 1;
    }
    return (4*j);
}
Referenced by sign_message().
base64_int()
unsigned int base64_int (unsigned int ch)
Definition at line 576 of file utils.c.
{
    // ASCII to base64_int
    // 65-90  Upper Case  >>  0-25
    // 97-122 Lower Case  >>  26-51
    // 48-57  Numbers     >>  52-61
    // 43     Plus (+)    >>  62
    // 47     Slash (/)   >>  63
    // 61     Equal (=)   >>  64~
    if (ch==43)
    return 62;
    if (ch==47)
    return 63;
    if (ch==61)
    return 64;
    if ((ch>47) && (ch<58))
    return ch + 4;
    if ((ch>64) && (ch<91))
    return ch - 'A';
    if ((ch>96) && (ch<123))
    return (ch - 'a') + 26;
    return 0;
}
Referenced by base64_decode().
dogecoin_cheap_random_bytes()
void dogecoin_cheap_random_bytes (uint8_t * buf, size_t len)
This function generates a buffer of random bytes.
Parameters
buf The buffer to store the random data.
len The number of random bytes to generate.
Returns
Nothing.
Definition at line 360 of file utils.c.
    {
    srand(time(NULL)); // insecure
    for (size_t i = 0; i < len; i++) {
        buf[i] = rand(); // weak non secure cryptographic rng
        }
    }
Referenced by dogecoin_p2p_msg_version_init(), and node_periodical_timer().
dogecoin_file_commit()
void dogecoin_file_commit (FILE * file)
This function flushes all data left in the output stream into the specified file.
Parameters
file The pointer to the file descriptor that will store the data.
Returns
Nothing.
Definition at line 415 of file utils.c.
    {
    fflush(file); // harmless if redundantly called
#ifdef WIN32
    HANDLE hFile = (HANDLE)_get_osfhandle(_fileno(file));
    FlushFileBuffers(hFile);
#elif defined(__linux__) || defined(__NetBSD__)
    fdatasync(fileno(file));
#elif defined(__APPLE__) && defined(F_FULLFSYNC)
    fcntl(fileno(file), F_FULLFSYNC, 0);
#endif
    }
References fileno.
dogecoin_get_default_datadir()
void dogecoin_get_default_datadir (cstring * path_out)
This function takes a path variable and appends the default data directory according to the user's operating system.
Parameters
path_out The pointer to the cstring containing the path.
Definition at line 376 of file utils.c.
    {
    // Windows < Vista: C:\Documents and Settings\Username\Application Data\Bitcoin
    // Windows >= Vista: C:\Users\Username\AppData\Roaming\Bitcoin
    // Mac: ~/Library/Application Support/Bitcoin
    // Unix: ~/.dogecoin
#ifdef WIN32
    // Windows
    char* homedrive = getenv("HOMEDRIVE");
    char* homepath = getenv("HOMEDRIVE");
    cstr_append_buf(path_out, homedrive, strlen(homedrive));
    cstr_append_buf(path_out, homepath, strlen(homepath));
#else
    char* home = getenv("HOME");
    if (home == NULL || strlen(home) == 0)
        cstr_append_c(path_out, '/');
    else
        cstr_append_buf(path_out, home, strlen(home));
#ifdef __APPLE__
    // Mac
    char* osx_home = "/Library/Application Support/Dogecoin";
    cstr_append_buf(path_out, osx_home, strlen(osx_home));
#else
    // Unix
    char* posix_home = "/.dogecoin";
    cstr_append_buf(path_out, posix_home, strlen(posix_home));
#endif
#endif
    }
References cstr_append_buf(), and cstr_append_c().
dogecoin_network_enabled()
bool dogecoin_network_enabled ()
Definition at line 566 of file utils.c.
{
#ifndef WITH_NET
    return false;
#else
    return true;
#endif
}
dogecoin_str_reverse()
void dogecoin_str_reverse (char s[])
Definition at line 537 of file utils.c.
{
    size_t i, j;
    char c;
    for (i = 0, j = strlen(s)-1; i<j; i++, j--) {
        c = s[i];
        s[i] = s[j];
        s[j] = c;
    }
}
Referenced by dogecoin_uitoa().
dogecoin_uitoa()
void dogecoin_uitoa (int n, char s[])
Definition at line 550 of file utils.c.
{
    int i, sign;
    if ((sign = n) < 0)  /* record sign */
        n = -n;          /* make n positive */
    i = 0;
    do {       /* generate digits in reverse order */
        s[i++] = n % 10 + '0';   /* get next digit */
    } while ((n /= 10) > 0);     /* delete it */
    if (sign < 0)
        s[i++] = '-';
    s[i] = '\0';
    dogecoin_str_reverse(s);
}
References dogecoin_str_reverse().
get_build()
const char * get_build ()
Definition at line 522 of file utils.c.
{
        #if defined(__x86_64__) || defined(_M_X64)
            return "x86_64";
        #elif defined(i386) || defined(__i386__) || defined(__i386) || defined(_M_IX86)
            return "x86_32";
        #elif defined(__ARM_ARCH_7__) || defined(__ARM_ARCH_7A__) || defined(__ARM_ARCH_7R__) || defined(__ARM_ARCH_7M__) || defined(__ARM_ARCH_7S__)
            return "ARM7";
        #elif defined(__aarch64__) || defined(_M_ARM64)
            return "ARM64";
        #else
            return "UNKNOWN";
        #endif
    }
prepend()
void prepend (char * s, const char * t)
Allows prepending characters (char* t) to the beginning of a string (char* s).
Parameters
s The string to prepend to.
t The characters that will be prepended.
Definition at line 472 of file utils.c.
    {
    /* get length of const char* t */
    size_t length = strlen(t);
    /* allocate enough length of both s and t
    for s and move each char back one */
    memmove(s + length, s, strlen(s) + 1);
    /* prepend t to new empty space in s */
    memcpy(s, t, length);
    }
print_bits()
void print_bits (size_t const size, void const * ptr)
Definition at line 451 of file utils.c.
    {
    unsigned char* b = (unsigned char*)ptr;
    unsigned char byte;
    int i, j;
    for (i = size - 1; i >= 0; i--) {
        for (j = 7; j >= 0; j--) {
            byte = (b[i] >> j) & 1;
            printf("%u", byte);
            }
        }
    puts("");
    }
print_header()
void print_header (char * filepath)
Definition at line 428 of file utils.c.
{
    if (!filepath) return;
    char* filename = filepath;
    FILE* fptr = NULL;
    if ((fptr = fopen(filename, "r")) == NULL)
        {
        fprintf(stderr, "error opening %s\n", filename);
        }
    print_image(fptr);
    fclose(fptr);
    }
References print_image().
print_image()
void print_image (FILE * fptr)
Definition at line 443 of file utils.c.
    {
    char read_string[MAX_LEN];
    while (fgets(read_string, sizeof(read_string), fptr) != NULL)
        printf("%s", read_string);
    }
References MAX_LEN.
Referenced by print_header().
safe_malloc()
void * safe_malloc (size_t size)
This function executes malloc() but exits the program if unsuccessful.
Parameters
size The size of the memory to allocate.
Returns
A pointer to the memory that was allocated.
Definition at line 336 of file utils.c.
    {
    void* result;
    if ((result = malloc(size))) { /* assignment intentional */
        return (result);
        }
    else {
        printf("memory overflow: malloc failed in safe_malloc.");
        printf("  Exiting Program.\n");
        exit(-1);
        return (0);
        }
    }
text_to_hex()
void text_to_hex (char * in, char * out)
function to convert ascii text to hexadecimal string
Parameters
in
output
Definition at line 510 of file utils.c.
{
    size_t length = 0;
    size_t i = 0;
    while (in[length] != '\0') {
        sprintf((char*)(out + i), "%02X", in[length]);
        length += 1;
        i += 2;
        }
    out[i++] = '\0';
    }
utils_bin_to_hex()
void utils_bin_to_hex (unsigned char * bin_in, size_t inlen, char * hex_out)
This function takes an array of raw data and converts them to a hex-encoded string.
Parameters
bin_in The array of raw data to convert.
inlen The number of bytes in the array.
hex_out The resulting hex string.
Returns
Nothing.
Definition at line 191 of file utils.c.
    {
    static char digits[] = "0123456789abcdef";
    size_t i;
    for (i = 0; i < inlen; i++) {
        hex_out[i * 2] = digits[(bin_in[i] >> 4) & 0xF];
        hex_out[i * 2 + 1] = digits[bin_in[i] & 0xF];
        }
    hex_out[inlen * 2] = '\0';
    }
Referenced by broadcast_tx(), dogecoin_pubkey_get_hex(), gen_privatekey(), main(), and sign_raw_transaction().
utils_clear_buffers()
void utils_clear_buffers (void)
This function clears the buffers used for functions inside utils.c.
Returns
Nothing.
Definition at line 92 of file utils.c.
{
    dogecoin_mem_zero(buffer_hex_to_uint8, TO_UINT8_HEX_BUF_LEN);
    dogecoin_mem_zero(buffer_uint8_to_hex, TO_UINT8_HEX_BUF_LEN);
}
References buffer_hex_to_uint8, buffer_uint8_to_hex, dogecoin_mem_zero(), and TO_UINT8_HEX_BUF_LEN.
utils_hex_digit()
signed char utils_hex_digit (char c)
This function takes a char from a hex string and returns the actual hex digit as a signed char.
Parameters
c The character to convert to hex digit.
Returns
The equivalent hex digit.
Definition at line 280 of file utils.c.
    {
    return p_util_hexdigit[(unsigned char)c];
    }
References p_util_hexdigit.
Referenced by utils_uint256_sethex().
utils_hex_to_bin()
void utils_hex_to_bin (const char * str, unsigned char * out, size_t inLen, size_t * outLen)
This function takes a hex-encoded string and loads a buffer with its binary representation.
Parameters
str The hex string to convert.
out The buffer for the raw data to be returned.
inLen The number of characters in the hex string.
outLen The number of raw bytes that were written to the out buffer.
Returns
Nothing.
Definition at line 109 of file utils.c.
    {
    size_t bLen = inLen / 2;
    size_t i;
    dogecoin_mem_zero(out, bLen);
    for (i = 0; i < bLen; i++) {
        if (str[i * 2] >= '0' && str[i * 2] <= '9') {
            *out = (str[i * 2] - '0') << 4;
            }
        if (str[i * 2] >= 'a' && str[i * 2] <= 'f') {
            *out = (10 + str[i * 2] - 'a') << 4;
            }
        if (str[i * 2] >= 'A' && str[i * 2] <= 'F') {
            *out = (10 + str[i * 2] - 'A') << 4;
            }
        if (str[i * 2 + 1] >= '0' && str[i * 2 + 1] <= '9') {
            *out |= (str[i * 2 + 1] - '0');
            }
        if (str[i * 2 + 1] >= 'a' && str[i * 2 + 1] <= 'f') {
            *out |= (10 + str[i * 2 + 1] - 'a');
            }
        if (str[i * 2 + 1] >= 'A' && str[i * 2 + 1] <= 'F') {
            *out |= (10 + str[i * 2 + 1] - 'A');
            }
        out++;
        }
    *outLen = i;
    }
References dogecoin_mem_zero().
Referenced by addresses_from_pubkey(), main(), save_raw_transaction(), sign_raw_transaction(), sign_transaction(), and store_raw_transaction().
utils_hex_to_uint8()
uint8_t * utils_hex_to_uint8 (const char * str)
This function takes a hex-encoded string and returns the binary representation as a uint8_t array.
Parameters
str The hex string to convert.
Returns
The array of binary data.
Definition at line 147 of file utils.c.
    {
    uint8_t c;
    size_t i;
    if (strlens(str) > TO_UINT8_HEX_BUF_LEN) {
        return NULL;
    }
    dogecoin_mem_zero(buffer_hex_to_uint8, TO_UINT8_HEX_BUF_LEN);
    for (i = 0; i < strlens(str) / 2; i++) {
        c = 0;
        if (str[i * 2] >= '0' && str[i * 2] <= '9') {
            c += (str[i * 2] - '0') << 4;
            }
        if (str[i * 2] >= 'a' && str[i * 2] <= 'f') {
            c += (10 + str[i * 2] - 'a') << 4;
            }
        if (str[i * 2] >= 'A' && str[i * 2] <= 'F') {
            c += (10 + str[i * 2] - 'A') << 4;
            }
        if (str[i * 2 + 1] >= '0' && str[i * 2 + 1] <= '9') {
            c += (str[i * 2 + 1] - '0');
            }
        if (str[i * 2 + 1] >= 'a' && str[i * 2 + 1] <= 'f') {
            c += (10 + str[i * 2 + 1] - 'a');
            }
        if (str[i * 2 + 1] >= 'A' && str[i * 2 + 1] <= 'F') {
            c += (10 + str[i * 2 + 1] - 'A');
            }
        buffer_hex_to_uint8[i] = c;
        }
    return buffer_hex_to_uint8;
    }
References buffer_hex_to_uint8, dogecoin_mem_zero(), strlens, and TO_UINT8_HEX_BUF_LEN.
Referenced by get_mnemonic(), and produce_mnemonic_sentence().
utils_reverse_hex()
void utils_reverse_hex (char * h, size_t len)
This function takes a hex-encoded string and reverses the order of its bytes.
Parameters
h The hex string to reverse.
len The length of the hex string.
Returns
Nothing.
Definition at line 239 of file utils.c.
    {
    char* copy = dogecoin_calloc(1, len);
    size_t i;
    memcpy_safe(copy, h, len);
    for (i = 0; i < len - 1; i += 2) {
        h[i] = copy[len - i - 2];
        h[i + 1] = copy[len - i - 1];
        }
    dogecoin_free(copy);
    }
References dogecoin_calloc(), dogecoin_free(), and memcpy_safe().
Referenced by broadcast_tx(), main(), and sign_raw_transaction().
utils_uint256_sethex()
void utils_uint256_sethex (char * psz, uint8_t * out)
This function takes a hex-encoded string and sets a 256-bit array to the numerical value in little endian format.
Parameters
psz The hex string to convert.
out The resulting byte array.
Returns
Nothing.
Definition at line 296 of file utils.c.
{
    dogecoin_mem_zero(out, sizeof(uint256));
    // skip leading spaces
    while (isspace(*psz)) {
        psz++;
        }
    // skip 0x
    if (psz[0] == '0' && tolower(psz[1]) == 'x') {
        psz += 2;
        }
    // hex string to uint
    const char* pbegin = psz;
    while (utils_hex_digit(*psz) != -1) {
        psz++;
        }
    psz--;
    unsigned char* p1 = (unsigned char*)out;
    unsigned char* pend = p1 + sizeof(uint256);
    while (psz >= pbegin && p1 < pend) {
        *p1 = utils_hex_digit(*psz--);
        if (psz >= pbegin) {
            *p1 |= ((unsigned char)utils_hex_digit(*psz--) << 4);
            p1++;
            }
        }
    }
References dogecoin_mem_zero(), uint256, and utils_hex_digit().
Referenced by add_utxo(), and transaction_input_menu().
utils_uint8_to_hex()
char * utils_uint8_to_hex (const uint8_t * bin, size_t l)
This function takes an array of raw bytes and converts them to a hex-encoded string.
Parameters
bin The array of raw bytes to convert.
l The number of bytes to convert.
Returns
The hex-encoded string.
Definition at line 212 of file utils.c.
    {
    static char digits[] = "0123456789abcdef";
    size_t i;
    if (l > (TO_UINT8_HEX_BUF_LEN / 2 - 1)) {
        return NULL;
    }
    dogecoin_mem_zero(buffer_uint8_to_hex, TO_UINT8_HEX_BUF_LEN);
    for (i = 0; i < l; i++) {
        buffer_uint8_to_hex[i * 2] = digits[(bin[i] >> 4) & 0xF];
        buffer_uint8_to_hex[i * 2 + 1] = digits[bin[i] & 0xF];
        }
    buffer_uint8_to_hex[l * 2] = '\0';
    return buffer_uint8_to_hex;
    }
References buffer_uint8_to_hex, dogecoin_mem_zero(), and TO_UINT8_HEX_BUF_LEN.
Referenced by dogecoin_p2pkh_to_script_hash(), dogecoin_script_hash_to_p2pkh(), get_mnemonic(), get_raw_transaction(), main(), new_eckey(), new_eckey_from_privkey(), sign_raw_transaction(), transaction_input_menu(), and transaction_output_menu().
Variable Documentation
base64_char
unsigned char base64_char[] = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"
Definition at line 574 of file utils.c.
Referenced by base64_encode().
buffer_hex_to_uint8
uint8_t buffer_hex_to_uint8[TO_UINT8_HEX_BUF_LEN] static
Definition at line 82 of file utils.c.
Referenced by utils_clear_buffers(), and utils_hex_to_uint8().
buffer_uint8_to_hex
char buffer_uint8_to_hex[TO_UINT8_HEX_BUF_LEN] static
Definition at line 83 of file utils.c.
Referenced by utils_clear_buffers(), and utils_uint8_to_hex().
p_util_hexdigit
const signed char p_util_hexdigit[256]
Initial value:
=
    {
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
    0, 1, 2, 3, 4, 5, 6, 7, 8, 9, -1, -1, -1, -1, -1, -1,
    -1, 0xa, 0xb, 0xc, 0xd, 0xe, 0xf, -1, -1, -1, -1, -1, -1, -1, -1, -1,
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
    -1, 0xa, 0xb, 0xc, 0xd, 0xe, 0xf, -1, -1, -1, -1, -1, -1, -1, -1, -1,
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
    }
Definition at line 251 of file utils.c.
Referenced by utils_hex_digit().