libdogecoin: src/libevent/util-internal.h File Reference
util-internal.h File Reference
#include "event2/event-config.h"
#include "evconfig-private.h"
#include <errno.h>
#include "log-internal.h"
#include <stdio.h>
#include <stdlib.h>
#include "event2/util.h"
#include "time-internal.h"
#include "ipv6-internal.h"
Data Structures
struct evutil_weakrand_state
struct sockaddr_storage
Macros
#define EVUTIL_HAS_ATTRIBUTE(x) 0
#define __func__ __FILE__
#define EVUTIL_NIL_STMT_ ((void)0)
#define EVUTIL_NIL_CONDITION_(condition)
#define EVUTIL_ERR_IS_EAGAIN(e) ((e) == EAGAIN)
#define EVUTIL_ERR_RW_RETRIABLE(e) ((e) == EINTR || EVUTIL_ERR_IS_EAGAIN(e))
#define EVUTIL_ERR_CONNECT_RETRIABLE(e) ((e) == EINTR || (e) == EINPROGRESS)
#define EVUTIL_ERR_ACCEPT_RETRIABLE(e) ((e) == EINTR || EVUTIL_ERR_IS_EAGAIN(e) || (e) == ECONNABORTED)
#define EVUTIL_ERR_CONNECT_REFUSED(e) ((e) == ECONNREFUSED)
#define EVUTIL_SHUT_RD 0
#define EVUTIL_SHUT_WR 1 /* SD_SEND */
#define EVUTIL_SHUT_BOTH 2
#define EVUTIL_ASSERT_LIST_OK(dlist, type, field)
#define EVUTIL_ASSERT_TAILQ_OK(tailq, type, field)
#define EVUTIL_UPCAST(ptr, type, field) ((type *)(((char*)(ptr)) - evutil_offsetof(type, field)))
#define EVUTIL_WEAKRAND_MAX EV_INT32_MAX
#define EVUTIL_UNLIKELY(p) (p)
#define EVUTIL_FALLTHROUGH /* fallthrough */
#define EVUTIL_ASSERT(cond)
#define EVUTIL_FAILURE_CHECK(cond) EVUTIL_UNLIKELY(cond)
#define ss_family ss_union.ss_sa.sa_family
#define EVUTIL_EAI_NEED_RESOLVE -90002
#define EV_U64_FMT "%llu"
#define EV_I64_FMT "%lld"
#define EV_I64_ARG(x) ((long long)(x))
#define EV_U64_ARG(x) ((unsigned long long)(x))
#define EV_SOCK_FMT "%d"
#define EV_SOCK_ARG(x) (x)
#define EV_SIZE_FMT "%lu"
#define EV_SSIZE_FMT "%ld"
#define EV_SIZE_ARG(x) ((unsigned long)(x))
#define EV_SSIZE_ARG(x) ((long)(x))
#define EVUTIL_SOCK_NONBLOCK 0x4000000
#define EVUTIL_SOCK_CLOEXEC 0x80000000
#define EVUTIL_EFD_NONBLOCK 0x4000
#define EVUTIL_EFD_CLOEXEC 0x8000
Typedefs
typedef struct evdns_getaddrinfo_request *(* evdns_getaddrinfo_fn) (struct evdns_base *base, const char *nodename, const char *servname, const struct evutil_addrinfo *hints_in, void(*cb) (int, struct evutil_addrinfo *, void *), void *arg)
typedef void(* evdns_getaddrinfo_cancel_fn) (struct evdns_getaddrinfo_request *req)
Functions
EVENT2_EXPORT_SYMBOL int EVUTIL_ISALPHA_ (char c)
EVENT2_EXPORT_SYMBOL int EVUTIL_ISALNUM_ (char c)
int EVUTIL_ISSPACE_ (char c)
EVENT2_EXPORT_SYMBOL int EVUTIL_ISDIGIT_ (char c)
EVENT2_EXPORT_SYMBOL int EVUTIL_ISXDIGIT_ (char c)
int EVUTIL_ISPRINT_ (char c)
int EVUTIL_ISLOWER_ (char c)
int EVUTIL_ISUPPER_ (char c)
EVENT2_EXPORT_SYMBOL char EVUTIL_TOUPPER_ (char c)
EVENT2_EXPORT_SYMBOL char EVUTIL_TOLOWER_ (char c)
EVENT2_EXPORT_SYMBOL void evutil_rtrim_lws_ (char *)
int evutil_open_closeonexec_ (const char *pathname, int flags, unsigned mode)
EVENT2_EXPORT_SYMBOL int evutil_read_file_ (const char *filename, char **content_out, size_t *len_out, int is_binary)
EVENT2_EXPORT_SYMBOL int evutil_socket_connect_ (evutil_socket_t *fd_ptr, const struct sockaddr *sa, int socklen)
int evutil_socket_finished_connecting_ (evutil_socket_t fd)
EVENT2_EXPORT_SYMBOL int evutil_ersatz_socketpair_ (int, int, int, evutil_socket_t[])
int evutil_resolve_ (int family, const char *hostname, struct sockaddr *sa, ev_socklen_t *socklen, int port)
const char * evutil_getenv_ (const char *name)
EVENT2_EXPORT_SYMBOL ev_uint32_t evutil_weakrand_seed_ (struct evutil_weakrand_state *state, ev_uint32_t seed)
EVENT2_EXPORT_SYMBOL ev_int32_t evutil_weakrand_ (struct evutil_weakrand_state *seed)
EVENT2_EXPORT_SYMBOL ev_int32_t evutil_weakrand_range_ (struct evutil_weakrand_state *seed, ev_int32_t top)
EVENT2_EXPORT_SYMBOL void evutil_set_evdns_getaddrinfo_fn_ (evdns_getaddrinfo_fn fn)
EVENT2_EXPORT_SYMBOL void evutil_set_evdns_getaddrinfo_cancel_fn_ (evdns_getaddrinfo_cancel_fn fn)
EVENT2_EXPORT_SYMBOL struct evutil_addrinfo * evutil_new_addrinfo_ (struct sockaddr *sa, ev_socklen_t socklen, const struct evutil_addrinfo *hints)
EVENT2_EXPORT_SYMBOL struct evutil_addrinfo * evutil_addrinfo_append_ (struct evutil_addrinfo *first, struct evutil_addrinfo *append)
EVENT2_EXPORT_SYMBOL void evutil_adjust_hints_for_addrconfig_ (struct evutil_addrinfo *hints)
EVENT2_EXPORT_SYMBOL int evutil_getaddrinfo_common_ (const char *nodename, const char *servname, struct evutil_addrinfo *hints, struct evutil_addrinfo **res, int *portnum)
struct evdns_getaddrinfo_request * evutil_getaddrinfo_async_ (struct evdns_base *dns_base, const char *nodename, const char *servname, const struct evutil_addrinfo *hints_in, void(*cb)(int, struct evutil_addrinfo *, void *), void *arg)
void evutil_getaddrinfo_cancel_async_ (struct evdns_getaddrinfo_request *data)
EVENT2_EXPORT_SYMBOL int evutil_sockaddr_is_loopback_ (const struct sockaddr *sa)
EVENT2_EXPORT_SYMBOL const char * evutil_format_sockaddr_port_ (const struct sockaddr *sa, char *out, size_t outlen)
int evutil_hex_char_to_int_ (char c)
void evutil_free_secure_rng_globals_ (void)
void evutil_free_globals_ (void)
EVENT2_EXPORT_SYMBOL evutil_socket_t evutil_socket_ (int domain, int type, int protocol)
evutil_socket_t evutil_accept4_ (evutil_socket_t sockfd, struct sockaddr *addr, ev_socklen_t *addrlen, int flags)
EVENT2_EXPORT_SYMBOL int evutil_make_internal_pipe_ (evutil_socket_t fd[2])
evutil_socket_t evutil_eventfd_ (unsigned initval, int flags)
void evutil_memclear_ (void *mem, size_t len)
EVENT2_EXPORT_SYMBOL int evutil_v4addr_is_local_ (const struct in_addr *in)
EVENT2_EXPORT_SYMBOL int evutil_v6addr_is_local_ (const struct in6_addr *in)
Macro Definition Documentation
__func__
#define __func__ __FILE__
Definition at line 86 of file util-internal.h.
EV_I64_ARG
#define EV_I64_ARG (x) ((long long)(x))
Definition at line 467 of file util-internal.h.
EV_I64_FMT
#define EV_I64_FMT "%lld"
Definition at line 466 of file util-internal.h.
EV_SIZE_ARG
#define EV_SIZE_ARG (x) ((unsigned long)(x))
Definition at line 493 of file util-internal.h.
EV_SIZE_FMT
#define EV_SIZE_FMT "%lu"
Definition at line 491 of file util-internal.h.
EV_SOCK_ARG
#define EV_SOCK_ARG (x) (x)
Definition at line 477 of file util-internal.h.
EV_SOCK_FMT
#define EV_SOCK_FMT "%d"
Definition at line 476 of file util-internal.h.
EV_SSIZE_ARG
#define EV_SSIZE_ARG (x) ((long)(x))
Definition at line 494 of file util-internal.h.
EV_SSIZE_FMT
#define EV_SSIZE_FMT "%ld"
Definition at line 492 of file util-internal.h.
EV_U64_ARG
#define EV_U64_ARG (x) ((unsigned long long)(x))
Definition at line 468 of file util-internal.h.
EV_U64_FMT
#define EV_U64_FMT "%llu"
Definition at line 465 of file util-internal.h.
EVUTIL_ASSERT
#define EVUTIL_ASSERT (cond)
Value:
    do {                                \
        if (EVUTIL_UNLIKELY(!(cond))) {             \
            event_errx(EVENT_ERR_ABORT_,            \
                "%s:%d: Assertion %s failed in %s",     \
                __FILE__,__LINE__,#cond,__func__);      \
            /* In case a user-supplied handler tries to */  \
            /* return control to us, log and abort here. */ \
            (void)fprintf(stderr,               \
                "%s:%d: Assertion %s failed in %s",     \
                __FILE__,__LINE__,#cond,__func__);      \
            abort();                    \
        }                           \
    } while (0)
Definition at line 363 of file util-internal.h.
EVUTIL_ASSERT_LIST_OK
#define EVUTIL_ASSERT_LIST_OK (dlist, type, field)
Value:
        do {            \
        struct type *elm1, *elm2, **nextp;          \
        if (LIST_EMPTY((dlist)))                \
            break;                      \
                                    \
        /* Check list for circularity using Floyd's */      \
        /* 'Tortoise and Hare' algorithm */         \
        elm1 = LIST_FIRST((dlist));             \
        elm2 = LIST_NEXT(elm1, field);              \
        while (elm1 && elm2) {                  \
            EVUTIL_ASSERT(elm1 != elm2);            \
            elm1 = LIST_NEXT(elm1, field);          \
            elm2 = LIST_NEXT(elm2, field);          \
            if (!elm2)                  \
                break;                  \
            EVUTIL_ASSERT(elm1 != elm2);            \
            elm2 = LIST_NEXT(elm2, field);          \
        }                           \
                                    \
        /* Now check next and prev pointers for consistency. */ \
        nextp = &LIST_FIRST((dlist));               \
        elm1 = LIST_FIRST((dlist));             \
        while (elm1) {                      \
            EVUTIL_ASSERT(*nextp == elm1);          \
            EVUTIL_ASSERT(nextp == elm1->field.le_prev);    \
            nextp = &LIST_NEXT(elm1, field);        \
            elm1 = *nextp;                  \
        }                           \
    } while (0)
Definition at line 179 of file util-internal.h.
EVUTIL_ASSERT_TAILQ_OK
#define EVUTIL_ASSERT_TAILQ_OK (tailq, type, field)
Value:
        do {            \
        struct type *elm1, *elm2, **nextp;          \
        if (TAILQ_EMPTY((tailq)))               \
            break;                      \
                                    \
        /* Check list for circularity using Floyd's */      \
        /* 'Tortoise and Hare' algorithm */         \
        elm1 = TAILQ_FIRST((tailq));                \
        elm2 = TAILQ_NEXT(elm1, field);             \
        while (elm1 && elm2) {                  \
            EVUTIL_ASSERT(elm1 != elm2);            \
            elm1 = TAILQ_NEXT(elm1, field);         \
            elm2 = TAILQ_NEXT(elm2, field);         \
            if (!elm2)                  \
                break;                  \
            EVUTIL_ASSERT(elm1 != elm2);            \
            elm2 = TAILQ_NEXT(elm2, field);         \
        }                           \
                                    \
        /* Now check next and prev pointers for consistency. */ \
        nextp = &TAILQ_FIRST((tailq));              \
        elm1 = TAILQ_FIRST((tailq));                \
        while (elm1) {                      \
            EVUTIL_ASSERT(*nextp == elm1);          \
            EVUTIL_ASSERT(nextp == elm1->field.tqe_prev);   \
            nextp = &TAILQ_NEXT(elm1, field);       \
            elm1 = *nextp;                  \
        }                           \
        EVUTIL_ASSERT(nextp == (tailq)->tqh_last);      \
    } while (0)
Definition at line 215 of file util-internal.h.
EVUTIL_EAI_NEED_RESOLVE
#define EVUTIL_EAI_NEED_RESOLVE -90002
Definition at line 398 of file util-internal.h.
EVUTIL_EFD_CLOEXEC
#define EVUTIL_EFD_CLOEXEC 0x8000
Definition at line 531 of file util-internal.h.
EVUTIL_EFD_NONBLOCK
#define EVUTIL_EFD_NONBLOCK 0x4000
Definition at line 526 of file util-internal.h.
EVUTIL_ERR_ACCEPT_RETRIABLE
#define EVUTIL_ERR_ACCEPT_RETRIABLE (e) ((e) == EINTR || EVUTIL_ERR_IS_EAGAIN(e) || (e) == ECONNABORTED)
Definition at line 125 of file util-internal.h.
EVUTIL_ERR_CONNECT_REFUSED
#define EVUTIL_ERR_CONNECT_REFUSED (e) ((e) == ECONNREFUSED)
Definition at line 129 of file util-internal.h.
EVUTIL_ERR_CONNECT_RETRIABLE
#define EVUTIL_ERR_CONNECT_RETRIABLE (e) ((e) == EINTR || (e) == EINPROGRESS)
Definition at line 122 of file util-internal.h.
EVUTIL_ERR_IS_EAGAIN
#define EVUTIL_ERR_IS_EAGAIN (e) ((e) == EAGAIN)
Definition at line 111 of file util-internal.h.
EVUTIL_ERR_RW_RETRIABLE
#define EVUTIL_ERR_RW_RETRIABLE (e) ((e) == EINTR || EVUTIL_ERR_IS_EAGAIN(e))
Definition at line 119 of file util-internal.h.
EVUTIL_FAILURE_CHECK
#define EVUTIL_FAILURE_CHECK (cond) EVUTIL_UNLIKELY(cond)
Definition at line 377 of file util-internal.h.
EVUTIL_FALLTHROUGH
#define EVUTIL_FALLTHROUGH /* fallthrough */
Definition at line 355 of file util-internal.h.
EVUTIL_HAS_ATTRIBUTE
#define EVUTIL_HAS_ATTRIBUTE (x) 0
clang 3 __has_attribute misbehaves in some versions
Definition at line 70 of file util-internal.h.
EVUTIL_NIL_CONDITION_
#define EVUTIL_NIL_CONDITION_ (condition)
Value:
    do { \
    (void)sizeof(!(condition));  \
} while(0)
Definition at line 96 of file util-internal.h.
EVUTIL_NIL_STMT_
#define EVUTIL_NIL_STMT_ ((void)0)
Definition at line 90 of file util-internal.h.
EVUTIL_SHUT_BOTH
#define EVUTIL_SHUT_BOTH 2
Definition at line 170 of file util-internal.h.
EVUTIL_SHUT_RD
#define EVUTIL_SHUT_RD 0
Definition at line 160 of file util-internal.h.
EVUTIL_SHUT_WR
#define EVUTIL_SHUT_WR 1 /* SD_SEND */
Definition at line 165 of file util-internal.h.
EVUTIL_SOCK_CLOEXEC
#define EVUTIL_SOCK_CLOEXEC 0x80000000
Definition at line 521 of file util-internal.h.
EVUTIL_SOCK_NONBLOCK
#define EVUTIL_SOCK_NONBLOCK 0x4000000
Definition at line 516 of file util-internal.h.
EVUTIL_UNLIKELY
#define EVUTIL_UNLIKELY (p) (p)
Definition at line 349 of file util-internal.h.
EVUTIL_UPCAST
#define EVUTIL_UPCAST (ptr, type, field) ((type *)(((char*)(ptr)) - evutil_offsetof(type, field)))
Helper macro. If we know that a given pointer points to a field in a structure, return a pointer to the structure itself. Used to implement our half-baked C OO. Example:
struct subtype { int x; struct supertype common; int y; }; ... void fn(struct supertype *super) { struct subtype *sub = EVUTIL_UPCAST(super, struct subtype, common); ... }
Definition at line 288 of file util-internal.h.
EVUTIL_WEAKRAND_MAX
#define EVUTIL_WEAKRAND_MAX EV_INT32_MAX
Definition at line 319 of file util-internal.h.
ss_family
#define ss_family ss_union.ss_sa.sa_family
Definition at line 392 of file util-internal.h.
Typedef Documentation
evdns_getaddrinfo_cancel_fn
typedef void(* evdns_getaddrinfo_cancel_fn) (struct evdns_getaddrinfo_request *req)
Definition at line 409 of file util-internal.h.
evdns_getaddrinfo_fn
typedef struct evdns_getaddrinfo_request *(* evdns_getaddrinfo_fn) (struct evdns_base *base, const char *nodename, const char *servname, const struct evutil_addrinfo *hints_in, void(*cb)(int, struct evutil_addrinfo *, void *), void *arg)
Definition at line 342 of file util-internal.h.
Function Documentation
evutil_accept4_()
evutil_socket_t evutil_accept4_ (evutil_socket_t sockfd, struct sockaddr * addr, ev_socklen_t * addrlen, int flags)
Definition at line 2633 of file evutil.c.
{
    evutil_socket_t result;
#if defined(EVENT__HAVE_ACCEPT4) && defined(SOCK_CLOEXEC) && defined(SOCK_NONBLOCK)
    result = accept4(sockfd, addr, addrlen, flags);
    if (result >= 0 || (errno != EINVAL && errno != ENOSYS)) {
        /* A nonnegative result means that we succeeded, so return.
         * Failing with EINVAL means that an option wasn't supported,
         * and failing with ENOSYS means that the syscall wasn't
         * there: in those cases we want to fall back.  Otherwise, we
         * got a real error, and we should return. */
        return result;
    }
#endif
    result = accept(sockfd, addr, addrlen);
    if (result < 0)
        return result;
    if (flags & EVUTIL_SOCK_CLOEXEC) {
        if (evutil_fast_socket_closeonexec(result) < 0) {
            evutil_closesocket(result);
            return -1;
        }
    }
    if (flags & EVUTIL_SOCK_NONBLOCK) {
        if (evutil_fast_socket_nonblocking(result) < 0) {
            evutil_closesocket(result);
            return -1;
        }
    }
    return result;
}
References evutil_closesocket(), evutil_fast_socket_closeonexec(), evutil_fast_socket_nonblocking(), EVUTIL_SOCK_CLOEXEC, and EVUTIL_SOCK_NONBLOCK.
Referenced by listener_read_cb().
evutil_addrinfo_append_()
EVENT2_EXPORT_SYMBOL struct evutil_addrinfo * evutil_addrinfo_append_ (struct evutil_addrinfo * first, struct evutil_addrinfo * append)
Definition at line 877 of file evutil.c.
{
    struct evutil_addrinfo *ai = first;
    if (!ai)
        return append;
    while (ai->ai_next)
        ai = ai->ai_next;
    ai->ai_next = append;
    return first;
}
References append().
Referenced by addrinfo_from_hostent(), evdns_getaddrinfo_fromhosts(), evdns_getaddrinfo_gotresolve(), and evutil_getaddrinfo_common_().
evutil_adjust_hints_for_addrconfig_()
EVENT2_EXPORT_SYMBOL void evutil_adjust_hints_for_addrconfig_ (struct evutil_addrinfo * hints)
Definition at line 1236 of file evutil.c.
{
    if (!(hints->ai_flags & EVUTIL_AI_ADDRCONFIG))
        return;
    if (hints->ai_family != PF_UNSPEC)
        return;
    evutil_check_interfaces();
    if (had_ipv4_address && !had_ipv6_address) {
        hints->ai_family = PF_INET;
    } else if (!had_ipv4_address && had_ipv6_address) {
        hints->ai_family = PF_INET6;
    }
}
References evutil_check_interfaces(), had_ipv4_address, had_ipv6_address, and PF_INET6.
Referenced by evdns_getaddrinfo(), and evutil_getaddrinfo().
evutil_ersatz_socketpair_()
EVENT2_EXPORT_SYMBOL int evutil_ersatz_socketpair_ (int , int , int , evutil_socket_t [])
evutil_eventfd_()
evutil_socket_t evutil_eventfd_ (unsigned initval, int flags)
Definition at line 2730 of file evutil.c.
{
#if defined(EVENT__HAVE_EVENTFD) && defined(EVENT__HAVE_SYS_EVENTFD_H)
    int r;
#if defined(EFD_CLOEXEC) && defined(EFD_NONBLOCK)
    r = eventfd(initval, flags);
    if (r >= 0 || flags == 0)
        return r;
#endif
    r = eventfd(initval, 0);
    if (r < 0)
        return r;
    if (flags & EVUTIL_EFD_CLOEXEC) {
        if (evutil_fast_socket_closeonexec(r) < 0) {
            evutil_closesocket(r);
            return -1;
        }
    }
    if (flags & EVUTIL_EFD_NONBLOCK) {
        if (evutil_fast_socket_nonblocking(r) < 0) {
            evutil_closesocket(r);
            return -1;
        }
    }
    return r;
#else
    return -1;
#endif
}
References evutil_closesocket(), EVUTIL_EFD_CLOEXEC, EVUTIL_EFD_NONBLOCK, evutil_fast_socket_closeonexec(), and evutil_fast_socket_nonblocking().
Referenced by evthread_make_base_notifiable_nolock_().
evutil_format_sockaddr_port_()
EVENT2_EXPORT_SYMBOL const char * evutil_format_sockaddr_port_ (const struct sockaddr * sa, char * out, size_t outlen)
Formats a sockaddr sa into a string buffer of size outlen stored in out. Returns a pointer to out. Always writes something into out, so it's safe to use the output of this function without checking it for NULL.
Definition at line 2246 of file evutil.c.
{
    char b[128];
    const char *res=NULL;
    int port;
    if (sa->sa_family == AF_INET) {
        const struct sockaddr_in *sin = (const struct sockaddr_in*)sa;
        res = evutil_inet_ntop(AF_INET, &sin->sin_addr,b,sizeof(b));
        port = ntohs(sin->sin_port);
        if (res) {
            evutil_snprintf(out, outlen, "%s:%d", b, port);
            return out;
        }
    } else if (sa->sa_family == AF_INET6) {
        const struct sockaddr_in6 *sin6 = (const struct sockaddr_in6*)sa;
        res = evutil_inet_ntop(AF_INET6, &sin6->sin6_addr,b,sizeof(b));
        port = ntohs(sin6->sin6_port);
        if (res) {
            evutil_snprintf(out, outlen, "[%s]:%d", b, port);
            return out;
        }
    }
    evutil_snprintf(out, outlen, "<addr with socktype %d>",
        (int)sa->sa_family);
    return out;
}
References AF_INET6, evutil_inet_ntop(), evutil_snprintf(), sockaddr_in6::sin6_addr, and sockaddr_in6::sin6_port.
Referenced by evdns_nameserver_add_impl_(), nameserver_failed(), nameserver_probe_failed(), nameserver_read(), nameserver_send_probe(), nameserver_up(), nameserver_write_waiting(), and reply_handle().
evutil_free_globals_()
void evutil_free_globals_ (void)
Definition at line 2761 of file evutil.c.
{
    evutil_free_secure_rng_globals_();
    evutil_free_sock_err_globals();
}
References evutil_free_secure_rng_globals_(), and evutil_free_sock_err_globals().
Referenced by event_free_evutil_globals().
evutil_free_secure_rng_globals_()
void evutil_free_secure_rng_globals_ (void)
Definition at line 203 of file evutil_rand.c.
{
    evutil_free_secure_rng_globals_locks();
}
References evutil_free_secure_rng_globals_locks().
Referenced by evutil_free_globals_().
evutil_getaddrinfo_async_()
struct evdns_getaddrinfo_request * evutil_getaddrinfo_async_ (struct evdns_base * dns_base, const char * nodename, const char * servname, const struct evutil_addrinfo * hints_in, void(*)(int, struct evutil_addrinfo *, void *) cb, void * arg)
Definition at line 1613 of file evutil.c.
{
    if (dns_base && evdns_getaddrinfo_impl) {
        return evdns_getaddrinfo_impl(
            dns_base, nodename, servname, hints_in, cb, arg);
    } else {
        struct evutil_addrinfo *ai=NULL;
        int err;
        err = evutil_getaddrinfo(nodename, servname, hints_in, &ai);
        cb(err, ai, arg);
        return NULL;
    }
}
References evdns_getaddrinfo_impl, and evutil_getaddrinfo().
Referenced by bufferevent_socket_connect_hostname().
evutil_getaddrinfo_cancel_async_()
void evutil_getaddrinfo_cancel_async_ (struct evdns_getaddrinfo_request * data)
Definition at line 1631 of file evutil.c.
{
    if (evdns_getaddrinfo_cancel_impl && data) {
        evdns_getaddrinfo_cancel_impl(data);
    }
}
References evdns_getaddrinfo_cancel_impl.
Referenced by be_socket_destruct(), and be_socket_setfd().
evutil_getaddrinfo_common_()
EVENT2_EXPORT_SYMBOL int evutil_getaddrinfo_common_ (const char * nodename, const char * servname, struct evutil_addrinfo * hints, struct evutil_addrinfo ** res, int * portnum)
Implements the part of looking up hosts by name that's common to both the blocking and nonblocking resolver:
Adjust 'hints' to have a reasonable socktype and protocol.
Look up the port based on 'servname', and store it in *portnum,
Handle the nodename==NULL case
Handle some invalid arguments cases.
Handle the cases where nodename is an IPv4 or IPv6 address.
If we need the resolver to look up the hostname, we return EVUTIL_EAI_NEED_RESOLVE. Otherwise, we can completely implement getaddrinfo: we return 0 or an appropriate EVUTIL_EAI_* error, and set *res as getaddrinfo would.
Definition at line 993 of file evutil.c.
{
    int port = 0;
    unsigned int if_index;
    const char *pname;
    if (nodename == NULL && servname == NULL)
        return EVUTIL_EAI_NONAME;
    /* We only understand 3 families */
    if (hints->ai_family != PF_UNSPEC && hints->ai_family != PF_INET &&
        hints->ai_family != PF_INET6)
        return EVUTIL_EAI_FAMILY;
    evutil_getaddrinfo_infer_protocols(hints);
    /* Look up the port number and protocol, if possible. */
    pname = evutil_unparse_protoname(hints->ai_protocol);
    if (servname) {
        /* XXXX We could look at the protocol we got back from
         * getservbyname, but it doesn't seem too useful. */
        port = evutil_parse_servname(servname, pname, hints);
        if (port < 0) {
            return EVUTIL_EAI_NONAME;
        }
    }
    /* If we have no node name, then we're supposed to bind to 'any' and
     * connect to localhost. */
    if (nodename == NULL) {
        struct evutil_addrinfo *res4=NULL, *res6=NULL;
        if (hints->ai_family != PF_INET) { /* INET6 or UNSPEC. */
            struct sockaddr_in6 sin6;
            memset(&sin6, 0, sizeof(sin6));
            sin6.sin6_family = AF_INET6;
            sin6.sin6_port = htons(port);
            if (hints->ai_flags & EVUTIL_AI_PASSIVE) {
                /* Bind to :: */
            } else {
                /* connect to ::1 */
                sin6.sin6_addr.s6_addr[15] = 1;
            }
            res6 = evutil_new_addrinfo_((struct sockaddr*)&sin6,
                sizeof(sin6), hints);
            if (!res6)
                return EVUTIL_EAI_MEMORY;
        }
        if (hints->ai_family != PF_INET6) { /* INET or UNSPEC */
            struct sockaddr_in sin;
            memset(&sin, 0, sizeof(sin));
            sin.sin_family = AF_INET;
            sin.sin_port = htons(port);
            if (hints->ai_flags & EVUTIL_AI_PASSIVE) {
                /* Bind to 0.0.0.0 */
            } else {
                /* connect to 127.0.0.1 */
                sin.sin_addr.s_addr = htonl(0x7f000001);
            }
            res4 = evutil_new_addrinfo_((struct sockaddr*)&sin,
                sizeof(sin), hints);
            if (!res4) {
                if (res6)
                    evutil_freeaddrinfo(res6);
                return EVUTIL_EAI_MEMORY;
            }
        }
        *res = evutil_addrinfo_append_(res4, res6);
        return 0;
    }
    /* If we can, we should try to parse the hostname without resolving
     * it. */
    /* Try ipv6. */
    if (hints->ai_family == PF_INET6 || hints->ai_family == PF_UNSPEC) {
        struct sockaddr_in6 sin6;
        memset(&sin6, 0, sizeof(sin6));
        if (1 == evutil_inet_pton_scope(
            AF_INET6, nodename, &sin6.sin6_addr, &if_index)) {
            /* Got an ipv6 address. */
            sin6.sin6_family = AF_INET6;
            sin6.sin6_port = htons(port);
            sin6.sin6_scope_id = if_index;
            *res = evutil_new_addrinfo_((struct sockaddr*)&sin6,
                sizeof(sin6), hints);
            if (!*res)
                return EVUTIL_EAI_MEMORY;
            return 0;
        }
    }
    /* Try ipv4. */
    if (hints->ai_family == PF_INET || hints->ai_family == PF_UNSPEC) {
        struct sockaddr_in sin;
        memset(&sin, 0, sizeof(sin));
        if (1==evutil_inet_pton(AF_INET, nodename, &sin.sin_addr)) {
            /* Got an ipv4 address. */
            sin.sin_family = AF_INET;
            sin.sin_port = htons(port);
            *res = evutil_new_addrinfo_((struct sockaddr*)&sin,
                sizeof(sin), hints);
            if (!*res)
                return EVUTIL_EAI_MEMORY;
            return 0;
        }
    }
    /* If we have reached this point, we definitely need to do a DNS
     * lookup. */
    if ((hints->ai_flags & EVUTIL_AI_NUMERICHOST)) {
        /* If we're not allowed to do one, then say so. */
        return EVUTIL_EAI_NONAME;
    }
    *portnum = port;
    return EVUTIL_EAI_NEED_RESOLVE;
}
References AF_INET6, evutil_addrinfo_append_(), EVUTIL_EAI_NEED_RESOLVE, evutil_freeaddrinfo(), evutil_getaddrinfo_infer_protocols(), evutil_inet_pton(), evutil_inet_pton_scope(), evutil_new_addrinfo_(), evutil_parse_servname(), evutil_unparse_protoname(), PF_INET6, in6_addr::s6_addr, sockaddr_in6::sin6_addr, sockaddr_in6::sin6_family, and sockaddr_in6::sin6_port.
Referenced by evdns_getaddrinfo(), and evutil_getaddrinfo().
evutil_getenv_()
const char * evutil_getenv_ (const char * name)
Definition at line 2463 of file evutil.c.
{
    if (evutil_issetugid())
        return NULL;
    return getenv(varname);
}
References evutil_issetugid().
Referenced by event_base_new_with_config(), and event_is_method_disabled().
evutil_hex_char_to_int_()
int evutil_hex_char_to_int_ (char c)
Definition at line 2547 of file evutil.c.
{
    switch(c)
    {
        case '0': return 0;
        case '1': return 1;
        case '2': return 2;
        case '3': return 3;
        case '4': return 4;
        case '5': return 5;
        case '6': return 6;
        case '7': return 7;
        case '8': return 8;
        case '9': return 9;
        case 'A': case 'a': return 10;
        case 'B': case 'b': return 11;
        case 'C': case 'c': return 12;
        case 'D': case 'd': return 13;
        case 'E': case 'e': return 14;
        case 'F': case 'f': return 15;
    }
    return -1;
}
EVUTIL_ISALNUM_()
EVENT2_EXPORT_SYMBOL int EVUTIL_ISALNUM_ (char c)
Referenced by scheme_ok().
EVUTIL_ISALPHA_()
EVENT2_EXPORT_SYMBOL int EVUTIL_ISALPHA_ (char c)
Referenced by request_new(), and scheme_ok().
EVUTIL_ISDIGIT_()
EVENT2_EXPORT_SYMBOL int EVUTIL_ISDIGIT_ (char c)
Referenced by evhttp_request_get_host(), evutil_inet_pton(), evutil_strtoll(), parse_authority(), and parse_port().
EVUTIL_ISLOWER_()
int EVUTIL_ISLOWER_ (char c)
EVUTIL_ISPRINT_()
int EVUTIL_ISPRINT_ (char c)
EVUTIL_ISSPACE_()
int EVUTIL_ISSPACE_ (char c)
Referenced by evutil_strtoll().
EVUTIL_ISUPPER_()
int EVUTIL_ISUPPER_ (char c)
EVUTIL_ISXDIGIT_()
EVENT2_EXPORT_SYMBOL int EVUTIL_ISXDIGIT_ (char c)
Referenced by bracket_addr_ok(), end_of_path(), evhttp_decode_uri_internal(), evutil_inet_pton(), evutil_strtoll(), regname_ok(), and userinfo_ok().
evutil_make_internal_pipe_()
EVENT2_EXPORT_SYMBOL int evutil_make_internal_pipe_ (evutil_socket_t fd[2])
Definition at line 2672 of file evutil.c.
{
    /*
      Making the second socket nonblocking is a bit subtle, given that we
      ignore any EAGAIN returns when writing to it, and you don't usally
      do that for a nonblocking socket. But if the kernel gives us EAGAIN,
      then there's no need to add any more data to the buffer, since
      the main thread is already either about to wake up and drain it,
      or woken up and in the process of draining it.
    */
#if defined(EVENT__HAVE_PIPE2)
    if (pipe2(fd, O_NONBLOCK|O_CLOEXEC) == 0)
        return 0;
#endif
#if defined(EVENT__HAVE_PIPE)
    if (pipe(fd) == 0) {
        if (evutil_fast_socket_nonblocking(fd[0]) < 0 ||
            evutil_fast_socket_nonblocking(fd[1]) < 0 ||
            evutil_fast_socket_closeonexec(fd[0]) < 0 ||
            evutil_fast_socket_closeonexec(fd[1]) < 0) {
            close(fd[0]);
            close(fd[1]);
            fd[0] = fd[1] = -1;
            return -1;
        }
        return 0;
    } else {
        event_warn("%s: pipe", __func__);
    }
#endif
#ifdef _WIN32
#define LOCAL_SOCKETPAIR_AF AF_INET
#else
#define LOCAL_SOCKETPAIR_AF AF_UNIX
#endif
    if (evutil_socketpair(LOCAL_SOCKETPAIR_AF, SOCK_STREAM, 0, fd) == 0) {
        if (evutil_fast_socket_nonblocking(fd[0]) < 0 ||
            evutil_fast_socket_nonblocking(fd[1]) < 0 ||
            evutil_fast_socket_closeonexec(fd[0]) < 0 ||
            evutil_fast_socket_closeonexec(fd[1]) < 0) {
            evutil_closesocket(fd[0]);
            evutil_closesocket(fd[1]);
            fd[0] = fd[1] = -1;
            return -1;
        }
        return 0;
    }
    fd[0] = fd[1] = -1;
    return -1;
}
References __func__, event_warn(), evutil_closesocket(), evutil_fast_socket_closeonexec(), evutil_fast_socket_nonblocking(), evutil_socketpair(), and LOCAL_SOCKETPAIR_AF.
Referenced by evsig_init_(), and evthread_make_base_notifiable_nolock_().
evutil_memclear_()
void evutil_memclear_ (void * mem, size_t len)
Definition at line 2526 of file evutil.c.
{
    evutil_memset_volatile_(mem, 0, len);
}
References evutil_memset_volatile_.
Referenced by arc4_seed_urandom_helper_().
evutil_new_addrinfo_()
EVENT2_EXPORT_SYMBOL struct evutil_addrinfo * evutil_new_addrinfo_ (struct sockaddr * sa, ev_socklen_t socklen, const struct evutil_addrinfo * hints)
Definition at line 832 of file evutil.c.
{
    struct evutil_addrinfo *res;
    EVUTIL_ASSERT(hints);
    if (hints->ai_socktype == 0 && hints->ai_protocol == 0) {
        /* Indecisive user! Give them a UDP and a TCP. */
        struct evutil_addrinfo *r1, *r2;
        struct evutil_addrinfo tmp;
        memcpy(&tmp, hints, sizeof(tmp));
        tmp.ai_socktype = SOCK_STREAM; tmp.ai_protocol = IPPROTO_TCP;
        r1 = evutil_new_addrinfo_(sa, socklen, &tmp);
        if (!r1)
            return NULL;
        tmp.ai_socktype = SOCK_DGRAM; tmp.ai_protocol = IPPROTO_UDP;
        r2 = evutil_new_addrinfo_(sa, socklen, &tmp);
        if (!r2) {
            evutil_freeaddrinfo(r1);
            return NULL;
        }
        r1->ai_next = r2;
        return r1;
    }
    /* We're going to allocate extra space to hold the sockaddr. */
    res = mm_calloc(1,sizeof(struct evutil_addrinfo)+socklen);
    if (!res)
        return NULL;
    res->ai_addr = (struct sockaddr*)
        (((char*)res) + sizeof(struct evutil_addrinfo));
    memcpy(res->ai_addr, sa, socklen);
    res->ai_addrlen = socklen;
    res->ai_family = sa->sa_family; /* Same or not? XXX */
    res->ai_flags = EVUTIL_AI_LIBEVENT_ALLOCATED;
    res->ai_socktype = hints->ai_socktype;
    res->ai_protocol = hints->ai_protocol;
    return res;
}
References EVUTIL_AI_LIBEVENT_ALLOCATED, EVUTIL_ASSERT, evutil_freeaddrinfo(), evutil_new_addrinfo_(), and mm_calloc.
Referenced by addrinfo_from_hostent(), evdns_getaddrinfo_fromhosts(), evdns_getaddrinfo_gotresolve(), evutil_getaddrinfo_common_(), and evutil_new_addrinfo_().
evutil_open_closeonexec_()
int evutil_open_closeonexec_ (const char * pathname, int flags, unsigned mode)
Definition at line 110 of file evutil.c.
{
    int fd;
#ifdef O_CLOEXEC
    fd = open(pathname, flags|O_CLOEXEC, (mode_t)mode);
    if (fd >= 0 || errno == EINVAL)
        return fd;
    /* If we got an EINVAL, fall through and try without O_CLOEXEC */
#endif
    fd = open(pathname, flags, (mode_t)mode);
    if (fd < 0)
        return -1;
#if defined(FD_CLOEXEC)
    if (fcntl(fd, F_SETFD, FD_CLOEXEC) < 0) {
        close(fd);
        return -1;
    }
#endif
    return fd;
}
Referenced by arc4_seed_urandom_helper_(), and evutil_read_file_().
evutil_read_file_()
EVENT2_EXPORT_SYMBOL int evutil_read_file_ (const char * filename, char ** content_out, size_t * len_out, int is_binary)
Read the contents of 'filename' into a newly allocated NUL-terminated string. Set *content_out to hold this string, and *len_out to hold its length (not including the appended NUL). If 'is_binary', open the file in binary mode.
Returns 0 on success, -1 if the open fails, and -2 for all other failures.
Used internally only; may go away in a future version.
Definition at line 145 of file evutil.c.
{
    int fd, r;
    struct stat st;
    char *mem;
    size_t read_so_far=0;
    int mode = O_RDONLY;
    EVUTIL_ASSERT(content_out);
    EVUTIL_ASSERT(len_out);
    *content_out = NULL;
    *len_out = 0;
#ifdef O_BINARY
    if (is_binary)
        mode |= O_BINARY;
#endif
    fd = evutil_open_closeonexec_(filename, mode, 0);
    if (fd < 0)
        return -1;
    if (fstat(fd, &st) || st.st_size < 0 ||
        st.st_size > EV_SSIZE_MAX-1 ) {
        close(fd);
        return -2;
    }
    mem = mm_malloc((size_t)st.st_size + 1);
    if (!mem) {
        close(fd);
        return -2;
    }
    read_so_far = 0;
#ifdef _WIN32
#define N_TO_READ(x) ((x) > INT_MAX) ? INT_MAX : ((int)(x))
#else
#define N_TO_READ(x) (x)
#endif
    while ((r = read(fd, mem+read_so_far, N_TO_READ(st.st_size - read_so_far))) > 0) {
        read_so_far += r;
        if (read_so_far >= (size_t)st.st_size)
            break;
        EVUTIL_ASSERT(read_so_far < (size_t)st.st_size);
    }
    close(fd);
    if (r < 0) {
        mm_free(mem);
        return -2;
    }
    mem[read_so_far] = 0;
    *len_out = read_so_far;
    *content_out = mem;
    return 0;
}
References EVUTIL_ASSERT, evutil_open_closeonexec_(), mm_free, mm_malloc, and N_TO_READ.
Referenced by evdns_base_load_hosts_impl(), and evdns_base_resolv_conf_parse_impl().
evutil_resolve_()
int evutil_resolve_ (int family, const char * hostname, struct sockaddr * sa, ev_socklen_t * socklen, int port)
evutil_rtrim_lws_()
EVENT2_EXPORT_SYMBOL void evutil_rtrim_lws_ (char * str)
Remove all trailing horizontal whitespace (space or tab) from the end of a string
Definition at line 2423 of file evutil.c.
{
    char *cp;
    if (str == NULL)
        return;
    if ((cp = strchr(str, '\0')) == NULL || (cp == str))
        return;
    --cp;
    while (*cp == ' ' || *cp == '\t') {
        *cp = '\0';
        if (cp == str)
            break;
        --cp;
    }
}
Referenced by evhttp_append_to_last_header(), and evhttp_parse_headers_().
evutil_set_evdns_getaddrinfo_cancel_fn_()
EVENT2_EXPORT_SYMBOL void evutil_set_evdns_getaddrinfo_cancel_fn_ (evdns_getaddrinfo_cancel_fn fn)
Definition at line 1603 of file evutil.c.
{
    if (!evdns_getaddrinfo_cancel_impl)
        evdns_getaddrinfo_cancel_impl = fn;
}
References evdns_getaddrinfo_cancel_impl.
Referenced by evdns_base_new().
evutil_set_evdns_getaddrinfo_fn_()
EVENT2_EXPORT_SYMBOL void evutil_set_evdns_getaddrinfo_fn_ (evdns_getaddrinfo_fn fn)
Definition at line 1597 of file evutil.c.
{
    if (!evdns_getaddrinfo_impl)
        evdns_getaddrinfo_impl = fn;
}
References evdns_getaddrinfo_impl.
Referenced by evdns_base_new().
evutil_sockaddr_is_loopback_()
EVENT2_EXPORT_SYMBOL int evutil_sockaddr_is_loopback_ (const struct sockaddr * sa)
Return true iff sa is a looback address. (That is, it is 127.0.0.1/8, or ::1).
Definition at line 2532 of file evutil.c.
{
    static const char LOOPBACK_S6[16] =
        "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\1";
    if (addr->sa_family == AF_INET) {
        struct sockaddr_in *sin = (struct sockaddr_in *)addr;
        return (ntohl(sin->sin_addr.s_addr) & 0xff000000) == 0x7f000000;
    } else if (addr->sa_family == AF_INET6) {
        struct sockaddr_in6 *sin6 = (struct sockaddr_in6 *)addr;
        return !memcmp(sin6->sin6_addr.s6_addr, LOOPBACK_S6, 16);
    }
    return 0;
}
References AF_INET6, in6_addr::s6_addr, and sockaddr_in6::sin6_addr.
Referenced by evdns_nameserver_add_impl_().
evutil_socket_()
EVENT2_EXPORT_SYMBOL evutil_socket_t evutil_socket_ (int domain, int type, int protocol)
Definition at line 2595 of file evutil.c.
{
    evutil_socket_t r;
#if defined(SOCK_NONBLOCK) && defined(SOCK_CLOEXEC)
    r = socket(domain, type, protocol);
    if (r >= 0)
        return r;
    else if ((type & (SOCK_NONBLOCK|SOCK_CLOEXEC)) == 0)
        return -1;
#endif
#define SOCKET_TYPE_MASK (~(EVUTIL_SOCK_NONBLOCK|EVUTIL_SOCK_CLOEXEC))
    r = socket(domain, type & SOCKET_TYPE_MASK, protocol);
    if (r < 0)
        return -1;
    if (type & EVUTIL_SOCK_NONBLOCK) {
        if (evutil_fast_socket_nonblocking(r) < 0) {
            evutil_closesocket(r);
            return -1;
        }
    }
    if (type & EVUTIL_SOCK_CLOEXEC) {
        if (evutil_fast_socket_closeonexec(r) < 0) {
            evutil_closesocket(r);
            return -1;
        }
    }
    return r;
}
References evutil_closesocket(), evutil_fast_socket_closeonexec(), evutil_fast_socket_nonblocking(), EVUTIL_SOCK_CLOEXEC, EVUTIL_SOCK_NONBLOCK, and SOCKET_TYPE_MASK.
Referenced by bufferevent_socket_connect(), create_bind_socket_nonblock(), evconnlistener_new_bind(), and evdns_nameserver_add_impl_().
evutil_socket_connect_()
EVENT2_EXPORT_SYMBOL int evutil_socket_connect_ (evutil_socket_t * fd_ptr, const struct sockaddr * sa, int socklen)
Definition at line 543 of file evutil.c.
{
    int made_fd = 0;
    if (*fd_ptr < 0) {
        if ((*fd_ptr = socket(sa->sa_family, SOCK_STREAM, 0)) < 0)
            goto err;
        made_fd = 1;
        if (evutil_make_socket_nonblocking(*fd_ptr) < 0) {
            goto err;
        }
    }
    if (connect(*fd_ptr, sa, socklen) < 0) {
        int e = evutil_socket_geterror(*fd_ptr);
        if (EVUTIL_ERR_CONNECT_RETRIABLE(e))
            return 0;
        if (EVUTIL_ERR_CONNECT_REFUSED(e))
            return 2;
        goto err;
    } else {
        return 1;
    }
err:
    if (made_fd) {
        evutil_closesocket(*fd_ptr);
        *fd_ptr = -1;
    }
    return -1;
}
References evutil_closesocket(), EVUTIL_ERR_CONNECT_REFUSED, EVUTIL_ERR_CONNECT_RETRIABLE, and evutil_make_socket_nonblocking().
Referenced by bufferevent_socket_connect().
evutil_socket_finished_connecting_()
int evutil_socket_finished_connecting_ (evutil_socket_t fd)
Definition at line 580 of file evutil.c.
{
    int e;
    ev_socklen_t elen = sizeof(e);
    if (getsockopt(fd, SOL_SOCKET, SO_ERROR, (void*)&e, &elen) < 0)
        return -1;
    if (e) {
        if (EVUTIL_ERR_CONNECT_RETRIABLE(e))
            return 0;
        EVUTIL_SET_SOCKET_ERROR(e);
        return -1;
    }
    return 1;
}
References EVUTIL_ERR_CONNECT_RETRIABLE.
Referenced by bufferevent_writecb().
EVUTIL_TOLOWER_()
EVENT2_EXPORT_SYMBOL char EVUTIL_TOLOWER_ (char c)
Definition at line 2383 of file evutil.c.
{
    return ((char)EVUTIL_TOLOWER_TABLE[(ev_uint8_t)c]);
}
References EVUTIL_TOLOWER_TABLE.
Referenced by evutil_ascii_strcasecmp(), evutil_ascii_strncasecmp(), and prefix_suffix_match().
EVUTIL_TOUPPER_()
EVENT2_EXPORT_SYMBOL char EVUTIL_TOUPPER_ (char c)
Definition at line 2387 of file evutil.c.
{
    return ((char)EVUTIL_TOUPPER_TABLE[(ev_uint8_t)c]);
}
References EVUTIL_TOUPPER_TABLE.
Referenced by event_is_method_disabled().
evutil_v4addr_is_local_()
EVENT2_EXPORT_SYMBOL int evutil_v4addr_is_local_ (const struct in_addr * in)
Definition at line 629 of file evutil.c.
{
    const ev_uint32_t addr = ntohl(in->s_addr);
    return addr == INADDR_ANY ||
        evutil_v4addr_is_localhost(addr) ||
        evutil_v4addr_is_linklocal(addr) ||
        evutil_v4addr_is_classd(addr);
}
References evutil_v4addr_is_classd(), evutil_v4addr_is_linklocal(), and evutil_v4addr_is_localhost().
Referenced by evutil_found_ifaddr().
evutil_v6addr_is_local_()
EVENT2_EXPORT_SYMBOL int evutil_v6addr_is_local_ (const struct in6_addr * in)
Definition at line 638 of file evutil.c.
{
    static const char ZEROES[] =
        "\x00\x00\x00\x00\x00\x00\x00\x00"
        "\x00\x00\x00\x00\x00\x00\x00\x00";
    const unsigned char *addr = (const unsigned char *)in->s6_addr;
    return !memcmp(addr, ZEROES, 8) ||
        ((addr[0] & 0xfe) == 0xfc) ||
        (addr[0] == 0xfe && (addr[1] & 0xc0) == 0x80) ||
        (addr[0] == 0xfe && (addr[1] & 0xc0) == 0xc0) ||
        (addr[0] == 0xff);
}
References in6_addr::s6_addr.
Referenced by evutil_found_ifaddr().
evutil_weakrand_()
EVENT2_EXPORT_SYMBOL ev_int32_t evutil_weakrand_ (struct evutil_weakrand_state * seed)
Definition at line 2489 of file evutil.c.
{
    /* This RNG implementation is a linear congruential generator, with
     * modulus 2^31, multiplier 1103515245, and addend 12345.  It's also
     * used by OpenBSD, and by Glibc's TYPE_0 RNG.
     *
     * The linear congruential generator is not an industrial-strength
     * RNG!  It's fast, but it can have higher-order patterns.  Notably,
     * the low bits tend to have periodicity.
     */
    state->seed = ((state->seed) * 1103515245 + 12345) & 0x7fffffff;
    return (ev_int32_t)(state->seed);
}
References evutil_weakrand_state::seed.
Referenced by evutil_weakrand_range_().
evutil_weakrand_range_()
EVENT2_EXPORT_SYMBOL ev_int32_t evutil_weakrand_range_ (struct evutil_weakrand_state * seed, ev_int32_t top)
Definition at line 2504 of file evutil.c.
{
    ev_int32_t divisor, result;
    /* We can't just do weakrand() % top, since the low bits of the LCG
     * are less random than the high ones.  (Specifically, since the LCG
     * modulus is 2^N, every 2^m for m<N will divide the modulus, and so
     * therefore the low m bits of the LCG will have period 2^m.) */
    divisor = EVUTIL_WEAKRAND_MAX / top;
    do {
        result = evutil_weakrand_(state) / divisor;
    } while (result >= top);
    return result;
}
References evutil_weakrand_(), and EVUTIL_WEAKRAND_MAX.
Referenced by bev_group_random_element_().
evutil_weakrand_seed_()
EVENT2_EXPORT_SYMBOL ev_uint32_t evutil_weakrand_seed_ (struct evutil_weakrand_state * state, ev_uint32_t seed)
Definition at line 2472 of file evutil.c.
{
    if (seed == 0) {
        struct timeval tv;
        evutil_gettimeofday(&tv, NULL);
        seed = (ev_uint32_t)tv.tv_sec + (ev_uint32_t)tv.tv_usec;
#ifdef _WIN32
        seed += (ev_uint32_t) _getpid();
#else
        seed += (ev_uint32_t) getpid();
#endif
    }
    state->seed = seed;
    return seed;
}
References evutil_gettimeofday(), and evutil_weakrand_state::seed.
Referenced by bufferevent_rate_limit_group_new().