libdogecoin: src/secp256k1/src/util.h File Reference
util.h File Reference
#include <stdlib.h>
#include <stdint.h>
#include <stdio.h>
#include <limits.h>
Data Structures
struct secp256k1_callback
Macros
#define TEST_FAILURE(msg)
#define EXPECT(x, c) (x)
#define CHECK(cond)
#define VERIFY_CHECK(cond) do { (void)(cond); } while(0)
#define VERIFY_SETUP(stmt)
#define VG_UNDEF(x, y)
#define VG_CHECK(x, y)
#define VG_CHECK_VERIFY(x, y)
#define ALIGNMENT 16
#define ROUND_TO_ALIGN(size) ((((size) + ALIGNMENT - 1) / ALIGNMENT) * ALIGNMENT)
#define SECP256K1_RESTRICT
#define I64FORMAT "lld"
#define I64uFORMAT "llu"
#define SECP256K1_GNUC_EXT
#define SECP256K1_WIDEMUL_INT64 1
#define __has_builtin(x) 0
Functions
static SECP256K1_INLINE void secp256k1_callback_call (const secp256k1_callback *const cb, const char *const text)
static void secp256k1_default_illegal_callback_fn (const char *str, void *data)
static void secp256k1_default_error_callback_fn (const char *str, void *data)
static SECP256K1_INLINE void * checked_malloc (const secp256k1_callback *cb, size_t size)
static SECP256K1_INLINE void * checked_realloc (const secp256k1_callback *cb, void *ptr, size_t size)
static SECP256K1_INLINE void secp256k1_memczero (void *s, size_t len, int flag)
static SECP256K1_INLINE int secp256k1_memcmp_var (const void *s1, const void *s2, size_t n)
static SECP256K1_INLINE void secp256k1_int_cmov (int *r, const int *a, int flag)
static SECP256K1_INLINE int secp256k1_ctz32_var_debruijn (uint32_t x)
static SECP256K1_INLINE int secp256k1_ctz64_var_debruijn (uint64_t x)
static SECP256K1_INLINE int secp256k1_ctz32_var (uint32_t x)
static SECP256K1_INLINE int secp256k1_ctz64_var (uint64_t x)
Variables
static const secp256k1_callback default_illegal_callback
static const secp256k1_callback default_error_callback
Macro Definition Documentation
__has_builtin
#define __has_builtin (x) 0
Definition at line 277 of file util.h.
ALIGNMENT
#define ALIGNMENT 16
Definition at line 140 of file util.h.
CHECK
#define CHECK (cond)
Value:
    do { \
    if (EXPECT(!(cond), 0)) { \
        TEST_FAILURE("test condition failed: " #cond); \
    } \
} while(0)
Definition at line 80 of file util.h.
EXPECT
#define EXPECT (x, c) (x)
Definition at line 70 of file util.h.
I64FORMAT
#define I64FORMAT "lld"
Definition at line 166 of file util.h.
I64uFORMAT
#define I64uFORMAT "llu"
Definition at line 167 of file util.h.
ROUND_TO_ALIGN
#define ROUND_TO_ALIGN (size) ((((size) + ALIGNMENT - 1) / ALIGNMENT) * ALIGNMENT)
Definition at line 143 of file util.h.
SECP256K1_GNUC_EXT
#define SECP256K1_GNUC_EXT
Definition at line 173 of file util.h.
SECP256K1_RESTRICT
#define SECP256K1_RESTRICT
Definition at line 155 of file util.h.
SECP256K1_WIDEMUL_INT64
#define SECP256K1_WIDEMUL_INT64 1
Definition at line 263 of file util.h.
TEST_FAILURE
#define TEST_FAILURE (msg)
Value:
    do { \
    fprintf(stderr, "%s:%d: %s\n", __FILE__, __LINE__, msg); \
    abort(); \
} while(0)
Definition at line 61 of file util.h.
VERIFY_CHECK
#define VERIFY_CHECK (cond) do { (void)(cond); } while(0)
Definition at line 95 of file util.h.
VERIFY_SETUP
#define VERIFY_SETUP (stmt)
Definition at line 96 of file util.h.
VG_CHECK
#define VG_CHECK (x, y)
Definition at line 107 of file util.h.
VG_CHECK_VERIFY
#define VG_CHECK_VERIFY (x, y)
Definition at line 115 of file util.h.
VG_UNDEF
#define VG_UNDEF (x, y)
Definition at line 106 of file util.h.
Function Documentation
checked_malloc()
static SECP256K1_INLINE void * checked_malloc (const secp256k1_callback * cb, size_t size) static
Definition at line 118 of file util.h.
{
    void *ret = malloc(size);
    if (ret == NULL) {
        secp256k1_callback_call(cb, "Out of memory");
    }
    return ret;
}
References secp256k1_callback_call().
Referenced by main(), secp256k1_context_clone(), secp256k1_context_create(), secp256k1_ecmult_gen_compute_table(), secp256k1_scratch_create(), test_ecmult_multi_batching(), and test_ge().
checked_realloc()
static SECP256K1_INLINE void * checked_realloc (const secp256k1_callback * cb, void * ptr, size_t size) static
Definition at line 126 of file util.h.
{
    void *ret = realloc(ptr, size);
    if (ret == NULL) {
        secp256k1_callback_call(cb, "Out of memory");
    }
    return ret;
}
References secp256k1_callback_call().
secp256k1_callback_call()
static SECP256K1_INLINE void secp256k1_callback_call (const secp256k1_callback *const cb, const char *const text) static
Definition at line 24 of file util.h.
{
    cb->fn(text, (void*)cb->data);
}
References secp256k1_callback::data, and secp256k1_callback::fn.
Referenced by checked_malloc(), checked_realloc(), secp256k1_context_preallocated_create(), secp256k1_context_preallocated_size(), secp256k1_scratch_alloc(), secp256k1_scratch_apply_checkpoint(), secp256k1_scratch_checkpoint(), secp256k1_scratch_destroy(), and secp256k1_scratch_max_allocation().
secp256k1_ctz32_var()
static SECP256K1_INLINE int secp256k1_ctz32_var (uint32_t x) static
Definition at line 306 of file util.h.
{
    VERIFY_CHECK(x != 0);
#if (__has_builtin(__builtin_ctz) || SECP256K1_GNUC_PREREQ(3,4))
    /* If the unsigned type is sufficient to represent the largest uint32_t, consider __builtin_ctz. */
    if (((unsigned)UINT32_MAX) == UINT32_MAX) {
        return __builtin_ctz(x);
    }
#endif
#if (__has_builtin(__builtin_ctzl) || SECP256K1_GNUC_PREREQ(3,4))
    /* Otherwise consider __builtin_ctzl (the unsigned long type is always at least 32 bits). */
    return __builtin_ctzl(x);
#else
    /* If no suitable CTZ builtin is available, use a (variable time) software emulation. */
    return secp256k1_ctz32_var_debruijn(x);
#endif
}
References secp256k1_ctz32_var_debruijn(), and VERIFY_CHECK.
Referenced by run_ctz_tests(), and secp256k1_modinv32_divsteps_30_var().
secp256k1_ctz32_var_debruijn()
static SECP256K1_INLINE int secp256k1_ctz32_var_debruijn (uint32_t x) static
Definition at line 283 of file util.h.
{
    static const uint8_t debruijn[32] = {
        0x00, 0x01, 0x02, 0x18, 0x03, 0x13, 0x06, 0x19, 0x16, 0x04, 0x14, 0x0A,
        0x10, 0x07, 0x0C, 0x1A, 0x1F, 0x17, 0x12, 0x05, 0x15, 0x09, 0x0F, 0x0B,
        0x1E, 0x11, 0x08, 0x0E, 0x1D, 0x0D, 0x1C, 0x1B
    };
    return debruijn[((x & -x) * 0x04D7651F) >> 27];
}
Referenced by run_ctz_tests(), and secp256k1_ctz32_var().
secp256k1_ctz64_var()
static SECP256K1_INLINE int secp256k1_ctz64_var (uint64_t x) static
Definition at line 324 of file util.h.
{
    VERIFY_CHECK(x != 0);
#if (__has_builtin(__builtin_ctzl) || SECP256K1_GNUC_PREREQ(3,4))
    /* If the unsigned long type is sufficient to represent the largest uint64_t, consider __builtin_ctzl. */
    if (((unsigned long)UINT64_MAX) == UINT64_MAX) {
        return __builtin_ctzl(x);
    }
#endif
#if (__has_builtin(__builtin_ctzll) || SECP256K1_GNUC_PREREQ(3,4))
    /* Otherwise consider __builtin_ctzll (the unsigned long long type is always at least 64 bits). */
    return __builtin_ctzll(x);
#else
    /* If no suitable CTZ builtin is available, use a (variable time) software emulation. */
    return secp256k1_ctz64_var_debruijn(x);
#endif
}
References secp256k1_ctz64_var_debruijn(), and VERIFY_CHECK.
Referenced by run_ctz_tests(), and secp256k1_modinv64_divsteps_62_var().
secp256k1_ctz64_var_debruijn()
static SECP256K1_INLINE int secp256k1_ctz64_var_debruijn (uint64_t x) static
Definition at line 295 of file util.h.
{
    static const uint8_t debruijn[64] = {
        0, 1, 2, 53, 3, 7, 54, 27, 4, 38, 41, 8, 34, 55, 48, 28,
        62, 5, 39, 46, 44, 42, 22, 9, 24, 35, 59, 56, 49, 18, 29, 11,
        63, 52, 6, 26, 37, 40, 33, 47, 61, 45, 43, 21, 23, 58, 17, 10,
        51, 25, 36, 32, 60, 20, 57, 16, 50, 31, 19, 15, 30, 14, 13, 12
    };
    return debruijn[((x & -x) * 0x022FDD63CC95386D) >> 58];
}
Referenced by run_ctz_tests(), and secp256k1_ctz64_var().
secp256k1_default_error_callback_fn()
static void secp256k1_default_error_callback_fn (const char * str, void * data) static
Definition at line 34 of file util.h.
{
    (void)data;
    fprintf(stderr, "[libsecp256k1] internal consistency check failed: %s\n", str);
    abort();
}
Referenced by secp256k1_context_set_error_callback().
secp256k1_default_illegal_callback_fn()
static void secp256k1_default_illegal_callback_fn (const char * str, void * data) static
Definition at line 29 of file util.h.
{
    (void)data;
    fprintf(stderr, "[libsecp256k1] illegal argument: %s\n", str);
    abort();
}
Referenced by run_context_tests(), and secp256k1_context_set_illegal_callback().
secp256k1_int_cmov()
static SECP256K1_INLINE void secp256k1_int_cmov (int * r, const int * a, int flag) static
If flag is true, set *r equal to *a; otherwise leave it. Constant-time. Both *r and *a must be initialized and non-negative.
Definition at line 235 of file util.h.
{
    unsigned int mask0, mask1, r_masked, a_masked;
    /* Access flag with a volatile-qualified lvalue.
       This prevents clang from figuring out (after inlining) that flag can
       take only be 0 or 1, which leads to variable time code. */
    volatile int vflag = flag;
    /* Casting a negative int to unsigned and back to int is implementation defined behavior */
    VERIFY_CHECK(*r >= 0 && *a >= 0);
    mask0 = (unsigned int)vflag + ~0u;
    mask1 = ~mask0;
    r_masked = ((unsigned int)*r & mask0);
    a_masked = ((unsigned int)*a & mask1);
    *r = (int)(r_masked | a_masked);
}
References VERIFY_CHECK.
Referenced by int_cmov_test(), and secp256k1_ecdsa_sign_inner().
secp256k1_memcmp_var()
static SECP256K1_INLINE int secp256k1_memcmp_var (const void * s1, const void * s2, size_t n) static
Semantics like memcmp. Variable-time.
We use this to avoid possible compiler bugs with memcmp, e.g. https://gcc.gnu.org/bugzilla/show_bug.cgi?id=95189
Definition at line 221 of file util.h.
{
    const unsigned char *p1 = s1, *p2 = s2;
    size_t i;
    for (i = 0; i < n; i++) {
        int diff = p1[i] - p2[i];
        if (diff != 0) {
            return diff;
        }
    }
    return 0;
}
Referenced by ec_pubkey_parse_pointtest(), fe_cmov_test(), fe_identical(), fe_storage_cmov_test(), ge_storage_cmov_test(), is_empty_signature(), run_eckey_edge_case_test(), run_eckey_negate_test(), run_ecmult_pre_g(), run_field_convert(), run_field_misc(), run_hmac_sha256_tests(), run_rfc6979_hmac_sha256_tests(), run_secp256k1_memczero_test(), run_sha256_tests(), run_tagged_sha256_tests(), scalar_cmov_test(), secp256k1_ec_pubkey_cmp(), secp256k1_scratch_alloc(), secp256k1_scratch_apply_checkpoint(), secp256k1_scratch_checkpoint(), secp256k1_scratch_destroy(), secp256k1_scratch_max_allocation(), secp256k1_selftest_sha256(), test_ec_combine(), test_ecdsa_der_parse(), test_ecdsa_edge_cases(), test_ecdsa_end_to_end(), test_ecmult_constants_2bit(), test_ecmult_constants_sha(), test_fe_mul(), test_random_pubkeys(), and test_scalar_split().
secp256k1_memczero()
static SECP256K1_INLINE void secp256k1_memczero (void * s, size_t len, int flag) static
Definition at line 202 of file util.h.
{
    unsigned char *p = (unsigned char *)s;
    /* Access flag with a volatile-qualified lvalue.
       This prevents clang from figuring out (after inlining) that flag can
       take only be 0 or 1, which leads to variable time code. */
    volatile int vflag = flag;
    unsigned char mask = -(unsigned char) vflag;
    while (len) {
        *p &= ~mask;
        p++;
        len--;
    }
}
Referenced by run_secp256k1_memczero_test(), and secp256k1_ec_pubkey_create().
Variable Documentation
default_error_callback
const secp256k1_callback default_error_callback static
Initial value:
= {
    secp256k1_default_error_callback_fn,
    NULL
}
Definition at line 49 of file util.h.
Referenced by main(), secp256k1_context_create(), secp256k1_context_preallocated_create(), and secp256k1_ecmult_gen_compute_table().
default_illegal_callback
const secp256k1_callback default_illegal_callback static
Initial value:
= {
    secp256k1_default_illegal_callback_fn,
    NULL
}
Definition at line 44 of file util.h.
Referenced by secp256k1_context_preallocated_create(), and secp256k1_context_preallocated_size().