libdogecoin: src/vector.c File Reference
vector.c File Reference
#include <dogecoin/mem.h>
#include <dogecoin/vector.h>
Functions
vector * vector_new (size_t res, void(*free_f)(void *))
This function creates a new vector object and initializes it to 0.
static void vector_free_data (vector *vec)
This function frees all of a vector's elements, calling the function associated with its free operation set during vector creation. The vector object itself is not freed.
void vector_free (vector *vec, dogecoin_bool free_array)
This function frees an entire vector object and all of its elements if specified.
static dogecoin_bool vector_grow (vector *vec, size_t min_sz)
This function grows the vector by doubling in size until it is larger than the size specified.
ssize_t vector_find (vector *vec, void *data)
This function finds and returns the first element in the vector whose data matches the data specified.
dogecoin_bool vector_add (vector *vec, void *data)
This function adds an element to an existing vector, growing it by one if necessary.
void vector_remove_range (vector *vec, size_t pos, size_t len)
This function deletes a range of consecutive elements from the specified vector.
void vector_remove_idx (vector *vec, size_t pos)
This function removes a single element from the specified vector.
dogecoin_bool vector_remove (vector *vec, void *data)
This function finds an element whose data matches the data specified and removes it if it exists.
dogecoin_bool vector_resize (vector *vec, size_t newsz)
This function resizes the vector to be newsz elements long. If the new size is bigger, the vector is grown and the new elements are left empty. If the new size is smaller, vector elements will be truncated. If the new size is the same, do nothing.
Function Documentation
vector_add()
dogecoin_bool vector_add (vector * vec, void * data)
This function adds an element to an existing vector, growing it by one if necessary.
Parameters
vec The pointer to the vector to add to.
data The data to be added into the vector.
Returns
1 if the element was added successfully, 0 otherwise.
Definition at line 182 of file vector.c.
{
    if (vec->len == vec->alloc) {
        if (!vector_grow(vec, vec->len + 1)) {
            return false;
        }
    }
    vec->data[vec->len] = data;
    vec->len++;
    return true;
}
References vector::alloc, vector::data, vector::len, and vector_grow().
Referenced by add_utxo(), dogecoin_get_peers_from_dns(), dogecoin_node_group_add_node(), dogecoin_p2p_deser_msg_getheaders(), dogecoin_script_get_ops(), dogecoin_script_is_pubkey(), dogecoin_script_is_pubkeyhash(), dogecoin_script_is_scripthash(), dogecoin_tx_add_data_out(), dogecoin_tx_add_p2pkh_hash160_out(), dogecoin_tx_add_p2sh_hash160_out(), dogecoin_tx_add_puzzle_out(), dogecoin_tx_copy(), and dogecoin_tx_deserialize().
vector_find()
ssize_t vector_find (vector * vec, void * data)
This function finds and returns the first element in the vector whose data matches the data specified.
Parameters
vec The pointer to the vector to search.
data The data to match.
Returns
The index of the data if it exists in the vector, -1 otherwise.
Definition at line 158 of file vector.c.
{
    if (vec && vec->len) {
        size_t i;
        for (i = 0; i < vec->len; i++) {
            if (vec->data[i] == data) {
                return (ssize_t)i;
            }
        }
    }
    return -1;
}
References vector::data, and vector::len.
Referenced by vector_remove().
vector_free()
void vector_free (vector * vec, dogecoin_bool free_array)
This function frees an entire vector object and all of its elements if specified.
Parameters
vec The pointer to the vector to be freed.
free_array The flag denoting whether to free the vector's elements.
Returns
Nothing.
Definition at line 103 of file vector.c.
{
    if (!vec) {
        return;
    }
    if (free_array) {
        vector_free_data(vec);
    }
    dogecoin_mem_zero(vec, sizeof(*vec));
    dogecoin_free(vec);
}
References dogecoin_free(), dogecoin_mem_zero(), and vector_free_data().
Referenced by dogecoin_node_group_add_peers_by_ip_or_seed(), dogecoin_node_group_free(), dogecoin_script_classify(), dogecoin_tx_copy(), dogecoin_tx_free(), dogecoin_tx_sighash(), and dogecoin_tx_sign_input().
vector_free_data()
static void vector_free_data (vector * vec) static
This function frees all of a vector's elements, calling the function associated with its free operation set during vector creation. The vector object itself is not freed.
Parameters
vec The pointer to the vector to be freed.
Returns
Nothing.
Definition at line 73 of file vector.c.
{
    if (!vec->data)
        return;
    if (vec->elem_free_f) {
        unsigned int i;
        for (i = 0; i < vec->len; i++)
            if (vec->data[i]) {
                vec->elem_free_f(vec->data[i]);
                vec->data[i] = NULL;
            }
    }
    dogecoin_free(vec->data);
    vec->data = NULL;
    vec->alloc = 0;
    vec->len = 0;
}
References vector::alloc, vector::data, dogecoin_free(), vector::elem_free_f, and vector::len.
Referenced by vector_free().
vector_grow()
static dogecoin_bool vector_grow (vector * vec, size_t min_sz) static
This function grows the vector by doubling in size until it is larger than the size specified.
Parameters
vec The pointer to the vector to be grown.
min_sz The minimum size the vector must be grown to.
Returns
1 if the vector is grown successfully, 0 if it reaches the max size allowed.
Definition at line 127 of file vector.c.
{
    size_t new_alloc = vec->alloc;
    while (new_alloc < min_sz) {
        new_alloc *= 2;
    }
    if (vec->alloc == new_alloc) {
        return true;
    }
    void* new_data = dogecoin_realloc(vec->data, new_alloc * sizeof(void*));
    if (!new_data) {
        return false;
    }
    vec->data = new_data;
    vec->alloc = new_alloc;
    return true;
}
References vector::alloc, vector::data, and dogecoin_realloc().
Referenced by vector_add(), and vector_resize().
vector_new()
vector * vector_new (size_t res, void(*)(void *) free_f)
This function creates a new vector object and initializes it to 0.
Parameters
res The size of memory to allocate for the vector's contents.
free_f The function that will be called when a vector element is freed.
Returns
A pointer to the new vector object.
Definition at line 42 of file vector.c.
{
    vector* vec = dogecoin_calloc(1, sizeof(vector));
    if (!vec)
        return NULL;
    vec->alloc = 8;
    while (vec->alloc < res)
        vec->alloc *= 2;
    vec->elem_free_f = free_f;
    vec->data = dogecoin_calloc(1, vec->alloc * sizeof(void*));
    if (!vec->data) {
        dogecoin_free(vec);
        return NULL;
    }
    return vec;
}
References vector::alloc, vector::data, dogecoin_calloc(), dogecoin_free(), and vector::elem_free_f.
Referenced by dogecoin_node_group_add_peers_by_ip_or_seed(), dogecoin_node_group_new(), dogecoin_script_classify(), dogecoin_tx_copy(), dogecoin_tx_new(), dogecoin_tx_sighash(), and dogecoin_tx_sign_input().
vector_remove()
dogecoin_bool vector_remove (vector * vec, void * data)
This function finds an element whose data matches the data specified and removes it if it exists.
Parameters
vec The pointer to the vector to edit.
data The data to match.
Returns
1 if the element was removed successfully, 0 if the data was not found.
Definition at line 247 of file vector.c.
{
    ssize_t idx = vector_find(vec, data);
    if (idx < 0) {
        return false;
    }
    vector_remove_idx(vec, idx);
    return true;
}
References vector_find(), and vector_remove_idx().
vector_remove_idx()
void vector_remove_idx (vector * vec, size_t pos)
This function removes a single element from the specified vector.
Parameters
vec The pointer to the vector to edit.
pos The index of the element to remove.
Definition at line 231 of file vector.c.
{
    vector_remove_range(vec, pos, 1);
}
References vector_remove_range().
Referenced by transaction_output_menu(), and vector_remove().
vector_remove_range()
void vector_remove_range (vector * vec, size_t pos, size_t len)
This function deletes a range of consecutive elements from the specified vector.
Parameters
vec The pointer to the vector to edit.
pos The index of the first item to remove.
len The number of consecutive elements to remove.
Returns
Nothing.
Definition at line 206 of file vector.c.
{
    if (!vec || ((pos + len) > vec->len)) {
        return;
    }
    if (vec->elem_free_f) {
        size_t i, count;
        for (i = pos, count = 0; count < len; i++, count++) {
            vec->elem_free_f(vec->data[i]);
        }
    }
    memmove(&vec->data[pos], &vec->data[pos + len], (vec->len - pos - len) * sizeof(void*));
    vec->len -= len;
}
References count, vector::data, vector::elem_free_f, and vector::len.
Referenced by dogecoin_tx_sighash(), and vector_remove_idx().
vector_resize()
dogecoin_bool vector_resize (vector * vec, size_t newsz)
This function resizes the vector to be newsz elements long. If the new size is bigger, the vector is grown and the new elements are left empty. If the new size is smaller, vector elements will be truncated. If the new size is the same, do nothing.
Parameters
vec The pointer to the vector to resize.
newsz The new desired size of the vector.
Returns
1 if the vector was resized successfully, 0 otherwise.
Definition at line 271 of file vector.c.
{
    size_t i;
    /* same size */
    if (newsz == vec->len) {
        return true;
    }
    /* truncate */
    else if (newsz < vec->len) {
        size_t del_count = vec->len - newsz;
        for (i = (vec->len - del_count); i < vec->len; i++) {
            if (vec->elem_free_f) {
                vec->elem_free_f(vec->data[i]);
            }
            vec->data[i] = NULL;
        }
        vec->len = newsz;
        return true;
    }
    /* last possibility: grow */
    if (!vector_grow(vec, newsz)) {
        return false;
    }
    /* set new elements to NULL */
    for (i = vec->len; i < newsz; i++) {
        vec->data[i] = NULL;
    }
    return true;
}
References vector::data, vector::elem_free_f, vector::len, and vector_grow().
Referenced by dogecoin_p2p_deser_msg_getheaders(), and dogecoin_tx_sighash().